const albania = [
  {
    "countryCode": "RSTA",
    "bankCode": "AL",
    "branchCode": "LTT",
    "SWIFT Code": "RSTAALTT",
    "Bank Name": "ALBANIAN SECURITIES REGISTER ALREG",
    "Address": "AP 3, KATI 1, FLOOR 3, RRUGA NIKOLLA TUPE 1, NJESIA BASHKIAKE 5",
    "City": "TIRANA",
    "Branch": "",
    "Postcode": "1001",
    "Country": "Albania",
    "Connection": "Active"
  },
  {
    "countryCode": "EMPO",
    "bankCode": "AL",
    "branchCode": "LTR",
    "SWIFT Code": "EMPOALTR",
    "Bank Name": "AMERICAN BANK OF INVESTMENTS S.A.",
    "Address": "KAVAJA STR 27",
    "City": "TIRANA",
    "Branch": "",
    "Postcode": "1001",
    "Country": "Albania",
    "Connection": "Active"
  },
  {
    "countryCode": "STAN",
    "bankCode": "AL",
    "branchCode": "LTR",
    "SWIFT Code": "STANALTR",
    "Bank Name": "BANK OF ALBANIA",
    "Address": "SHESHI SKONDERBEJ 1",
    "City": "TIRANA",
    "Branch": "",
    "Postcode": "1001",
    "Country": "Albania",
    "Connection": "Active"
  },
  {
    "countryCode": "STAN",
    "bankCode": "AL",
    "branchCode": "LTS",
    "SWIFT Code": "STANALTS",
    "Bank Name": "BANK OF ALBANIA",
    "Address": "SHESHI SKENDERBEJ 1",
    "City": "TIRANA",
    "Branch": "",
    "Postcode": "1001",
    "Country": "Albania",
    "Connection": "Active"
  },
  {
    "countryCode": "NCBA",
    "bankCode": "AL",
    "branchCode": "LTX",
    "SWIFT Code": "NCBAALTX",
    "Bank Name": "BANKA KOMBETARE TREGTARE SH.A.",
    "Address": "RRUGA E VILAVE, LUNDER 1",
    "City": "TIRANA",
    "Branch": "",
    "Postcode": "1045",
    "Country": "Albania",
    "Connection": "Active"
  },
  {
    "countryCode": "CRBA",
    "bankCode": "AL",
    "branchCode": "LTR",
    "SWIFT Code": "CRBAALTR",
    "Bank Name": "BANKA OTP ALBANIA SH.A",
    "Address": "TWIN TOWERS, 1ST TOWER, FLOOR 8, BLVD.DESHMORET E KOMBIT",
    "City": "TIRANA",
    "Branch": "",
    "Postcode": "1001",
    "Country": "Albania",
    "Connection": "Active"
  },
  {
    "countryCode": "PUPP",
    "bankCode": "AL",
    "branchCode": "LTR",
    "SWIFT Code": "PUPPALTR",
    "Bank Name": "BANKA OTP ALBANIA SH.A.",
    "Address": "TWIN TOWERS 1ST TOWER, BLVD.DESHMORET E KOMBIT",
    "City": "TIRANA",
    "Branch": "",
    "Postcode": "1010",
    "Country": "Albania",
    "Connection": "Active"
  },
  {
    "countryCode": "CDIS",
    "bankCode": "AL",
    "branchCode": "LTR",
    "SWIFT Code": "CDISALTR",
    "Bank Name": "CREDINS BANK S.A.",
    "Address": "VASO PASHA 8",
    "City": "TIRANA",
    "Branch": "",
    "Postcode": "1019",
    "Country": "Albania",
    "Connection": "Active"
  },
  {
    "countryCode": "FINV",
    "bankCode": "AL",
    "branchCode": "LTR",
    "SWIFT Code": "FINVALTR",
    "Bank Name": "FIRST INVESTMENT BANK-ALBANIA SH.A",
    "Address": "TWIN TOWERS NO.2, BLVD.DESHMORET E KOMBIT",
    "City": "TIRANA",
    "Branch": "",
    "Postcode": "1010",
    "Country": "Albania",
    "Connection": "Active"
  },
  {
    "countryCode": "USAL",
    "bankCode": "AL",
    "branchCode": "LTR",
    "SWIFT Code": "USALALTR",
    "Bank Name": "INTESA SANPAOLO BANK ALBANIA SH.A.",
    "Address": "RRUGA ISMAIL QEMALI 27",
    "City": "TIRANA",
    "Branch": "",
    "Postcode": "1010",
    "Country": "Albania",
    "Connection": "Active"
  },
  {
    "countryCode": "MIFB",
    "bankCode": "AL",
    "branchCode": "LTR",
    "SWIFT Code": "MIFBALTR",
    "Bank Name": "MINISTRY OF FINANCE OF ALBANIA",
    "Address": "BLVD DESHMORET E KOMBIT 3",
    "City": "TIRANA",
    "Branch": "",
    "Postcode": "1001",
    "Country": "Albania",
    "Connection": "Active"
  },
  {
    "countryCode": "FEFA",
    "bankCode": "AL",
    "branchCode": "LTR",
    "SWIFT Code": "FEFAALTR",
    "Bank Name": "PROCREDIT BANK SH. A. ALBANIA (FORMERLY FEFAD BANK)",
    "Address": "H. 15, RRUGA DRITAN HOXHA, NJESIA BASHKIAKE 11",
    "City": "TIRANA",
    "Branch": "HEAD OFFICE",
    "Postcode": "1023",
    "Country": "Albania",
    "Connection": "Active"
  },
  {
    "countryCode": "SGSB",
    "bankCode": "AL",
    "branchCode": "LTX",
    "SWIFT Code": "SGSBALTX",
    "Bank Name": "RAIFFEISEN BANK SH.A.",
    "Address": "RR 'DESHMORET E 4 SHKURTIT' 6",
    "City": "TIRANA",
    "Branch": "",
    "Postcode": "1010",
    "Country": "Albania",
    "Connection": "Active"
  },
  {
    "countryCode": "TIRB",
    "bankCode": "AL",
    "branchCode": "LTR",
    "SWIFT Code": "TIRBALTR",
    "Bank Name": "TIRANA BANK",
    "Address": "IBRAHIM RUGOVA STR",
    "City": "TIRANA",
    "Branch": "",
    "Postcode": "1019",
    "Country": "Albania",
    "Connection": "Active"
  },
  {
    "countryCode": "UNAL",
    "bankCode": "AL",
    "branchCode": "LTR",
    "SWIFT Code": "UNALALTR",
    "Bank Name": "UNION BANK SH.A.",
    "Address": "FLOOR 13 BULVARDI ZOGU I, KATESH PERBALLE STACIONIT TE TRENIT",
    "City": "TIRANA",
    "Branch": "",
    "Postcode": "1016",
    "Country": "Albania",
    "Connection": "Active"
  },
  {
    "countryCode": "AAIS",
    "bankCode": "AL",
    "branchCode": "LTR",
    "SWIFT Code": "AAISALTR",
    "Bank Name": "UNITED BANK OF ALBANIA SH.A",
    "Address": "HYRJA 3, RR. DRITAN HOXHA ND. 11",
    "City": "TIRANA",
    "Branch": "",
    "Postcode": "1023",
    "Country": "Albania",
    "Connection": "Active"
  }
]
module.exports = albania
