const algeria = [
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "032",
    "SWIFT Code": "BEXADZAL032",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "PLACE DE SEDRATA",
    "City": "OUARGLA",
    "Branch": "AGENCE OUARGLA",
    "Postcode": "30000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "051",
    "SWIFT Code": "BEXADZAL051",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "1954, AVENUE DU 1 NOVEMBRE",
    "City": "OUM EL BOUAGHI",
    "Branch": "AGENCE OUM EL BOUAGHI",
    "Postcode": "04000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "073",
    "SWIFT Code": "BEXADZAL073",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "RUE ANGLE DU BARRAGE",
    "City": "RELIZANE",
    "Branch": "AGENCE DE RELIZANE",
    "Postcode": "48000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "061",
    "SWIFT Code": "BEXADZAL061",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "24, AVENUE DE L'INDEPENDANCE",
    "City": "SAIDA",
    "Branch": "AGENCE SAIDA",
    "Postcode": "20000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "087",
    "SWIFT Code": "BEXADZAL087",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "1954, AVENUE DU 1 NOVEMBRE",
    "City": "SETIF",
    "Branch": "AGENCE EL EULMA",
    "Postcode": "19000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "036",
    "SWIFT Code": "BEXADZAL036",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "22, AVENUE DU 1 MAI 1945",
    "City": "SETIF",
    "Branch": "AGENCE SETIF",
    "Postcode": "19000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "053",
    "SWIFT Code": "BEXADZAL053",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "CITE BELLAIRE",
    "City": "SETIF",
    "Branch": "AGENCE SETIF II",
    "Postcode": "19000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "065",
    "SWIFT Code": "BEXADZAL065",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "25, AVENUE LARBI TEBESSI",
    "City": "SIDI BEL ABBES",
    "Branch": "AGENCE SIDI BEL ABBES",
    "Postcode": "22000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "084",
    "SWIFT Code": "BEXADZAL084",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "16, RUE J.F. KENNEDY",
    "City": "SIG",
    "Branch": "AGENCE SIG",
    "Postcode": "29001",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "052",
    "SWIFT Code": "BEXADZAL052",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "23, RUE DIDOUCHE MOURAD",
    "City": "SKIKDA",
    "Branch": "AGENCE DE SKIKDA",
    "Postcode": "21000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "085",
    "SWIFT Code": "BEXADZAL085",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "SITE SONATRACH",
    "City": "SKIKDA",
    "Branch": "AGENCE SKIKDA SITE SH",
    "Postcode": "21000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "057",
    "SWIFT Code": "BEXADZAL057",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "1700, CITE DES LOGTS",
    "City": "SOUK AHRAS",
    "Branch": "AGENCE SOUK AHRAS",
    "Postcode": "41000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "046",
    "SWIFT Code": "BEXADZAL046",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "RUE EMIR ABDELKADER",
    "City": "TEBESSA",
    "Branch": "AGENCE TEBESSA",
    "Postcode": "12000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "069",
    "SWIFT Code": "BEXADZAL069",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "2, BLD BEN BADIS",
    "City": "TIARET",
    "Branch": "AGENCE DE TIARET",
    "Postcode": "14000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "108",
    "SWIFT Code": "BEXADZAL108",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "02, RUE ROULANA ELLAH NORDINE",
    "City": "TIARET",
    "Branch": "AGENCE TIARET TOUR",
    "Postcode": "14000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "120",
    "SWIFT Code": "BEXADZAL120",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "LOTISSEMENT ABANE RAMDANE",
    "City": "TIPAZA",
    "Branch": "TIPAZA",
    "Postcode": "42400",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "098",
    "SWIFT Code": "BEXADZAL098",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "SITE ENIEM Z1 OUED AISSI",
    "City": "TIZI-OUZOU",
    "Branch": "AGENCE OUED AISSI",
    "Postcode": "15000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "121",
    "SWIFT Code": "BEXADZAL121",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "2, STE ENIEM BD STITI ALI",
    "City": "TIZI-OUZOU",
    "Branch": "TIZI OUZOU 2",
    "Postcode": "15000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "096",
    "SWIFT Code": "BEXADZAL096",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "AIN SEBAA EL KIFFANE",
    "City": "TLEMCEN",
    "Branch": "AGENCE EL KIFFANE",
    "Postcode": "13000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "064",
    "SWIFT Code": "BEXADZAL064",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "2, RUE DE L'INDEPENDANCE",
    "City": "TLEMCEN",
    "Branch": "AGENCE TLEMCEN INDEPDT",
    "Postcode": "13000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "114",
    "SWIFT Code": "BEXADZAL114",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "MAGHNIA",
    "City": "TLEMCEN",
    "Branch": "MAGHNIA 114",
    "Postcode": "13000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "088",
    "SWIFT Code": "BEXADZAL088",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "RUE DES FRERES MESSAOUDI",
    "City": "TOUGGOURT",
    "Branch": "AGENCE DE TOUGGOURT",
    "Postcode": "30002",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BNAL",
    "countryCode": "DZ",
    "branchCode": "RTG",
    "SWIFT Code": "BNALDZALRTG",
    "Bank Name": "BANQUE NATIONALE D'ALGERIE",
    "Address": "",
    "City": "ALGIERS",
    "Branch": "",
    "Postcode": "16000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BNAL",
    "countryCode": "DZ",
    "branchCode": "ZAL",
    "SWIFT Code": "BNALDZAL",
    "Bank Name": "BANQUE NATIONALE D'ALGERIE",
    "Address": "12, ROUTE DE MEFTAH, OUED-SMAR",
    "City": "ALGIERS",
    "Branch": "",
    "Postcode": "16030",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BNAL",
    "countryCode": "DZ",
    "branchCode": "615",
    "SWIFT Code": "BNALDZAL615",
    "Bank Name": "BANQUE NATIONALE D'ALGERIE",
    "Address": "24, RUE BALAHDJEL HOCINE",
    "City": "ALGIERS",
    "Branch": "BELAHDJEL",
    "Postcode": "16000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BNAL",
    "countryCode": "DZ",
    "branchCode": "623",
    "SWIFT Code": "BNALDZAL623",
    "Bank Name": "BANQUE NATIONALE D'ALGERIE",
    "Address": "64, RUE BEN M'HIDI",
    "City": "ALGIERS",
    "Branch": "BEN M'HIDI",
    "Postcode": "16000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BNAL",
    "countryCode": "DZ",
    "branchCode": "633",
    "SWIFT Code": "BNALDZAL633",
    "Bank Name": "BANQUE NATIONALE D'ALGERIE",
    "Address": "30, RUE DES FRERES DJILLALI",
    "City": "ALGIERS",
    "Branch": "BIRKILADEM",
    "Postcode": "16330",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BNAL",
    "countryCode": "DZ",
    "branchCode": "608",
    "SWIFT Code": "BNALDZAL608",
    "Bank Name": "BANQUE NATIONALE D'ALGERIE",
    "Address": "AVENUE ZIAR ABDELKADER",
    "City": "ALGIERS",
    "Branch": "BOLOGHINE",
    "Postcode": "16030",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BNAL",
    "countryCode": "DZ",
    "branchCode": "601",
    "SWIFT Code": "BNALDZAL601",
    "Bank Name": "BANQUE NATIONALE D'ALGERIE",
    "Address": "45-47, RUE DIDOUCHE MOURAD",
    "City": "ALGIERS",
    "Branch": "DIDOUCHE MOURAD",
    "Postcode": "16000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BNAL",
    "countryCode": "DZ",
    "branchCode": "621",
    "SWIFT Code": "BNALDZAL621",
    "Bank Name": "BANQUE NATIONALE D'ALGERIE",
    "Address": "16, AVENUE MESSAOUD TALEB ET FILS",
    "City": "ALGIERS",
    "Branch": "EL BIAR",
    "Postcode": "16000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BNAL",
    "countryCode": "DZ",
    "branchCode": "599",
    "SWIFT Code": "BNALDZAL599",
    "Bank Name": "BANQUE NATIONALE D'ALGERIE",
    "Address": "8, BLD ERNESTO CHE GUEVARA",
    "City": "ALGIERS",
    "Branch": "GUEVARA",
    "Postcode": "16000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BNAL",
    "countryCode": "DZ",
    "branchCode": "607",
    "SWIFT Code": "BNALDZAL607",
    "Bank Name": "BANQUE NATIONALE D'ALGERIE",
    "Address": "71, RUE HASSIBA BENBOUALI",
    "City": "ALGIERS",
    "Branch": "HASSIBA BEN BOUALI",
    "Postcode": "16000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BNAL",
    "countryCode": "DZ",
    "branchCode": "602",
    "SWIFT Code": "BNALDZAL602",
    "Bank Name": "BANQUE NATIONALE D'ALGERIE",
    "Address": "VIADUC BD KRIM BELKACEM",
    "City": "ALGIERS",
    "Branch": "KRIM BELKACEM",
    "Postcode": "16000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BNAL",
    "countryCode": "DZ",
    "branchCode": "605",
    "SWIFT Code": "BNALDZAL605",
    "Bank Name": "BANQUE NATIONALE D'ALGERIE",
    "Address": "8, BLD DE LA LIBERTE",
    "City": "ALGIERS",
    "Branch": "LIBERTE",
    "Postcode": "16000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BNAL",
    "countryCode": "DZ",
    "branchCode": "620",
    "SWIFT Code": "BNALDZAL620",
    "Bank Name": "BANQUE NATIONALE D'ALGERIE",
    "Address": "12, BLD ZIROUT YOUCEF",
    "City": "ALGIERS",
    "Branch": "ZIROUT YOUCEF",
    "Postcode": "16000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BNAL",
    "countryCode": "DZ",
    "branchCode": "810",
    "SWIFT Code": "BNALDZAL810",
    "Bank Name": "BANQUE NATIONALE D'ALGERIE",
    "Address": "PLACE DE L'ESPLANADE",
    "City": "ANNABA",
    "Branch": "ANNABA 810",
    "Postcode": "23000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BNAL",
    "countryCode": "DZ",
    "branchCode": "811",
    "SWIFT Code": "BNALDZAL811",
    "Bank Name": "BANQUE NATIONALE D'ALGERIE",
    "Address": "17, COURS DE LA REVOLTION",
    "City": "ANNABA",
    "Branch": "ANNABA 811",
    "Postcode": "23000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BNAL",
    "countryCode": "DZ",
    "branchCode": "954",
    "SWIFT Code": "BNALDZAL954",
    "Bank Name": "BANQUE NATIONALE D'ALGERIE",
    "Address": "BLD EMIR ABDELKADER",
    "City": "ARZEW",
    "Branch": "ARZEW",
    "Postcode": "31004",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BNAL",
    "countryCode": "DZ",
    "branchCode": "412",
    "SWIFT Code": "BNALDZAL412",
    "Bank Name": "BANQUE NATIONALE D'ALGERIE",
    "Address": "AVENUE COLONEL LOTFI",
    "City": "BECHAR",
    "Branch": "BECHAR",
    "Postcode": "15013",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BNAL",
    "countryCode": "DZ",
    "branchCode": "356",
    "SWIFT Code": "BNALDZAL356",
    "Bank Name": "BANQUE NATIONALE D'ALGERIE",
    "Address": "CITE TOBAL",
    "City": "BEJAIA",
    "Branch": "BEJAIA",
    "Postcode": "06000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BNAL",
    "countryCode": "DZ",
    "branchCode": "857",
    "SWIFT Code": "BNALDZAL857",
    "Bank Name": "BANQUE NATIONALE D'ALGERIE",
    "Address": "COMPLEXE POVAL",
    "City": "BERROUAGHIA",
    "Branch": "BERROUAGHIA",
    "Postcode": "26002",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BNAL",
    "countryCode": "DZ",
    "branchCode": "386",
    "SWIFT Code": "BNALDZAL386",
    "Bank Name": "BANQUE NATIONALE D'ALGERIE",
    "Address": "27, RUE DE LA REPUBLIQUE",
    "City": "BISKRA",
    "Branch": "BISKRA",
    "Postcode": "07000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BNAL",
    "countryCode": "DZ",
    "branchCode": "442",
    "SWIFT Code": "BNALDZAL442",
    "Bank Name": "BANQUE NATIONALE D'ALGERIE",
    "Address": "BLD TAKARLI ABDERREZAK",
    "City": "BLIDA",
    "Branch": "BLIDA",
    "Postcode": "09000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BNAL",
    "countryCode": "DZ",
    "branchCode": "705",
    "SWIFT Code": "BNALDZAL705",
    "Bank Name": "BANQUE NATIONALE D'ALGERIE",
    "Address": "RUE ZIOUI ABDELHAMID",
    "City": "BORDJ BOU ARRERIDJ",
    "Branch": "BORDJ BOU ARRERIDJ",
    "Postcode": "34000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BNAL",
    "countryCode": "DZ",
    "branchCode": "640",
    "SWIFT Code": "BNALDZAL640",
    "Bank Name": "BANQUE NATIONALE D'ALGERIE",
    "Address": "HOTEL DES FINANCES, AV DU 1ER NOVEMBRE",
    "City": "BORDJ EL KIFFAN",
    "Branch": "BORDJ EL KIFFAN",
    "Postcode": "16031",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BNAL",
    "countryCode": "DZ",
    "branchCode": "643",
    "SWIFT Code": "BNALDZAL643",
    "Bank Name": "BANQUE NATIONALE D'ALGERIE",
    "Address": "RUE LARBI BEN M'HIDI",
    "City": "BORDJ MENAIEL",
    "Branch": "BORDJ MENAIEL",
    "Postcode": "35001",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BNAL",
    "countryCode": "DZ",
    "branchCode": "430",
    "SWIFT Code": "BNALDZAL430",
    "Bank Name": "BANQUE NATIONALE D'ALGERIE",
    "Address": "13, AVENUE SOUIDANI BOUDJEMAA",
    "City": "BOUFARIK",
    "Branch": "BOUFARIK",
    "Postcode": "09001",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BNAL",
    "countryCode": "DZ",
    "branchCode": "460",
    "SWIFT Code": "BNALDZAL460",
    "Bank Name": "BANQUE NATIONALE D'ALGERIE",
    "Address": "RUE GUETTAF SEDDIK",
    "City": "BOUIRA",
    "Branch": "BOUIRA",
    "Postcode": "10000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BNAL",
    "countryCode": "DZ",
    "branchCode": "260",
    "SWIFT Code": "BNALDZAL260",
    "Bank Name": "BANQUE NATIONALE D'ALGERIE",
    "Address": "RUE IBN BADIS",
    "City": "CHLEF",
    "Branch": "CHLEF",
    "Postcode": "02000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BNAL",
    "countryCode": "DZ",
    "branchCode": "832",
    "SWIFT Code": "BNALDZAL832",
    "Bank Name": "BANQUE NATIONALE D'ALGERIE",
    "Address": "AV. DE L'INDEPENDANCE",
    "City": "CONSTANTINE",
    "Branch": "CONSTANTINE 832",
    "Postcode": "25000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "SALG",
    "countryCode": "DZ",
    "branchCode": "ZAL",
    "SWIFT Code": "SALGDZAL",
    "Bank Name": "AL SALAM BANK ALGERIA",
    "Address": "233, RUE AHMED OUKED DELY IBRAHIM",
    "City": "ALGIERS",
    "Branch": "",
    "Postcode": "16000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "ARAB",
    "countryCode": "DZ",
    "branchCode": "ZAL",
    "SWIFT Code": "ARABDZAL",
    "Bank Name": "ARAB BANK PLC ALGERIA",
    "Address": "12, RESIDENCE CHAABANI, VAL D'HYDRA",
    "City": "ALGIERS",
    "Branch": "",
    "Postcode": "16035",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "ABCO",
    "countryCode": "DZ",
    "branchCode": "ZAL",
    "SWIFT Code": "ABCODZAL",
    "Bank Name": "ARAB BANKING CORPORATION - ALGERIA",
    "Address": "54, AVENUE DES TROIS FRERES BOUADOU",
    "City": "BIR MOURAD RAIS",
    "Branch": "",
    "Postcode": "16030",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BALG",
    "countryCode": "DZ",
    "branchCode": "ZAP",
    "SWIFT Code": "BALGDZAP",
    "Bank Name": "BANK OF ALGERIA",
    "Address": "8, BOULEVARD ZIGHOUD YOUCEF",
    "City": "ALGIERS",
    "Branch": "",
    "Postcode": "16000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BALG",
    "countryCode": "DZ",
    "branchCode": "ZAL",
    "SWIFT Code": "BALGDZAL",
    "Bank Name": "BANK OF ALGERIA",
    "Address": "7, BOULEVARD ERNESTO CHE GUEVARA",
    "City": "ALGIERS",
    "Branch": "HEAD OFFICE",
    "Postcode": "16000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BALG",
    "countryCode": "DZ",
    "branchCode": "SBE",
    "SWIFT Code": "BALGDZALSBE",
    "Bank Name": "BANK OF ALGERIA",
    "Address": "7, BOULEVARD ERNESTO CHE GUEVARA",
    "City": "ALGIERS",
    "Branch": "SERVICES BANCAIRES ETRANGERS",
    "Postcode": "16000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BRKA",
    "countryCode": "DZ",
    "branchCode": "ZAL",
    "SWIFT Code": "BRKADZAL",
    "Bank Name": "BANQUE AL-BARAKA D'ALGERIE",
    "Address": "1, ROCADE SUD-BENAKNOUN HAI, BOUTELDJA HOUIDEF VILIA",
    "City": "ALGIERS",
    "Branch": "",
    "Postcode": "16035",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BDLO",
    "countryCode": "DZ",
    "branchCode": "ZAL",
    "SWIFT Code": "BDLODZAL",
    "Bank Name": "BANQUE DE DEVELOPPEMENT LOCAL",
    "Address": "05, RUE GACI AMAR - STAOUELI",
    "City": "ALGIERS",
    "Branch": "",
    "Postcode": "16000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BADR",
    "countryCode": "DZ",
    "branchCode": "ZAL",
    "SWIFT Code": "BADRDZAL",
    "Bank Name": "BANQUE DE L'AGRICULTURE ET DE DEVELOPPEMENT RURAL",
    "Address": "ALGER CENTRE, 17, BOULEVARD COLONEL AMIROUCHE",
    "City": "ALGIERS",
    "Branch": "",
    "Postcode": "16000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BMIC",
    "countryCode": "DZ",
    "branchCode": "ZAL",
    "SWIFT Code": "BMICDZAL",
    "Bank Name": "BANQUE DU MAGHREB ARABE POUR L'INVESTISSEMENT ET LE COMMERCE",
    "Address": "7, PARK D'HYDRA RUE DUBOIS",
    "City": "ALGIERS",
    "Branch": "",
    "Postcode": "16035",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "122",
    "SWIFT Code": "BEXADZAL122",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "HASSI ILATOU SITE SH",
    "City": "ADRAR",
    "Branch": "",
    "Postcode": "15069",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "118",
    "SWIFT Code": "BEXADZAL118",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "",
    "City": "AIN DEFLA",
    "Branch": "AGENCE AIN DEFLA",
    "Postcode": "44000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "072",
    "SWIFT Code": "BEXADZAL072",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "54, AVENUE DU 1 NOVEMBRE",
    "City": "AIN TEMOUCHENT",
    "Branch": "AGENCE AIN TEMOUCHENT",
    "Postcode": "46000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "113",
    "SWIFT Code": "BEXADZAL113",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "",
    "City": "ALGIERS",
    "Branch": "AGENCE 113",
    "Postcode": "16000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "012",
    "SWIFT Code": "BEXADZAL012",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "11, BLD COLONEL AMIROUCHE",
    "City": "ALGIERS",
    "Branch": "AGENCE AMIROUCHE",
    "Postcode": "16000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "020",
    "SWIFT Code": "BEXADZAL020",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "122, RUE BELOUIZDAD",
    "City": "ALGIERS",
    "Branch": "AGENCE BELCOURT",
    "Postcode": "16000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "015",
    "SWIFT Code": "BEXADZAL015",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "49, RUE LARBI BEN M'HIDI",
    "City": "ALGIERS",
    "Branch": "AGENCE BEN M'HIDI",
    "Postcode": "16000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "001",
    "SWIFT Code": "BEXADZAL001",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "23, ROUTE DE L'ALN CAROUBIER",
    "City": "ALGIERS",
    "Branch": "AGENCE CAROUBIER NAFTAL",
    "Postcode": "16000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "008",
    "SWIFT Code": "BEXADZAL008",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "ROUTE DES DUNES CHERAGA",
    "City": "ALGIERS",
    "Branch": "AGENCE CHERAGA NAFTAL",
    "Postcode": "16000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "004",
    "SWIFT Code": "BEXADZAL004",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "LOT BEN-HADDADI, CHERAGA",
    "City": "ALGIERS",
    "Branch": "AGENCE CHERAGA VILLE",
    "Postcode": "16000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "034",
    "SWIFT Code": "BEXADZAL034",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "AVENUE HOUARI BOUMEDIENNE",
    "City": "ALGIERS",
    "Branch": "AGENCE DE TIZI OUZOU",
    "Postcode": "16000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "090",
    "SWIFT Code": "BEXADZAL090",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "36, DELY IBRAHIM",
    "City": "ALGIERS",
    "Branch": "AGENCE DELY IBRAHIM",
    "Postcode": "16000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "017",
    "SWIFT Code": "BEXADZAL017",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "BOULEVARD MOHAMED V ALGER",
    "City": "ALGIERS",
    "Branch": "AGENCE DES ACCREDITES",
    "Postcode": "16000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "116",
    "SWIFT Code": "BEXADZAL116",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "48, LOTISSEMENT F",
    "City": "ALGIERS",
    "Branch": "AGENCE DRARIA",
    "Postcode": "16050",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "030",
    "SWIFT Code": "BEXADZAL030",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "14, RUE AHMED AOUN EL HARRACH",
    "City": "ALGIERS",
    "Branch": "AGENCE EL HARRACH",
    "Postcode": "16000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "010",
    "SWIFT Code": "BEXADZAL010",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "6, BOULEVARD CHE GUEVARA",
    "City": "ALGIERS",
    "Branch": "AGENCE GUEVARA",
    "Postcode": "16000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "018",
    "SWIFT Code": "BEXADZAL018",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "1, RUE HAMANI",
    "City": "ALGIERS",
    "Branch": "AGENCE HAMANI",
    "Postcode": "16000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "038",
    "SWIFT Code": "BEXADZAL038",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "88, RUE HASSIBA BEN BOUALI",
    "City": "ALGIERS",
    "Branch": "AGENCE HASSIBA BEN BOUALI",
    "Postcode": "16000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "022",
    "SWIFT Code": "BEXADZAL022",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "33, AVENUE DE TRIPOLI HUSSEIN DEY",
    "City": "ALGIERS",
    "Branch": "AGENCE HUSSEIN DEY",
    "Postcode": "16000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "912",
    "SWIFT Code": "BEXADZAL912",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "HYDRA LES ROSIERS",
    "City": "ALGIERS",
    "Branch": "AGENCE HYDRA LES ROSIERS",
    "Postcode": "16000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "005",
    "SWIFT Code": "BEXADZAL005",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "DJENANE EL MALIK HYDRA SITE, SONATRACH",
    "City": "ALGIERS",
    "Branch": "AGENCE HYDRA SITE SONATRACH",
    "Postcode": "16035",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "013",
    "SWIFT Code": "BEXADZAL013",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "RUE DJILTI MUSTAPHA",
    "City": "ALGIERS",
    "Branch": "AGENCE KHEMIS MILIANA",
    "Postcode": "16000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "016",
    "SWIFT Code": "BEXADZAL016",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "LES PINS MARITIMES",
    "City": "ALGIERS",
    "Branch": "AGENCE PALIS DES EXPOSITIONS",
    "Postcode": "16000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "089",
    "SWIFT Code": "BEXADZAL089",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "02, BOULEVARD BELARBI MOHAMED",
    "City": "ALGIERS",
    "Branch": "BARAKI",
    "Postcode": "16000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "DTD",
    "SWIFT Code": "BEXADZALDTD",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "5, PLACE EMIR ABDELKADER",
    "City": "ALGIERS",
    "Branch": "DIRECTION DE LA TRESORERIE",
    "Postcode": "16000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "DOE",
    "SWIFT Code": "BEXADZALDOE",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "11, BOULEVARD COLONEL AMIROUCHE",
    "City": "ALGIERS",
    "Branch": "DIRECTION DES OPERATIONS AVEC L'ETRANGER - DEPARTEMENT L/C ET NOSTRO",
    "Postcode": "16000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "DRI",
    "SWIFT Code": "BEXADZALDRI",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "11, BOULEVARD COLONEL AMIROUCHE",
    "City": "ALGIERS",
    "Branch": "DIRECTION DES RELATIONS INTERNATIONALES",
    "Postcode": "16000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "DCE",
    "SWIFT Code": "BEXADZALDCE",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "11, BOULEVARD COLONEL AMIROUCHE",
    "City": "ALGIERS",
    "Branch": "DIRECTION DU COMMERCE EXTERIEUR",
    "Postcode": "16000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "101",
    "SWIFT Code": "BEXADZAL101",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "20, BOULEVARD SOUIDANI BOUDJEMAA",
    "City": "ALGIERS",
    "Branch": "EL DJAZAIR",
    "Postcode": "16000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "102",
    "SWIFT Code": "BEXADZAL102",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "47, AVENUE SOUIDANI BOUDJEMAA",
    "City": "ALGIERS",
    "Branch": "EL MOURADIA",
    "Postcode": "16000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "100",
    "SWIFT Code": "BEXADZAL100",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "11, ROUTE NATIONALE NUMERO 9",
    "City": "ALGIERS",
    "Branch": "ZERALDA",
    "Postcode": "16061",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "044",
    "SWIFT Code": "BEXADZAL044",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "17, COURS DE LA REVOLUTION",
    "City": "ANNABA",
    "Branch": "AGENCE ANNABA 44",
    "Postcode": "23000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "077",
    "SWIFT Code": "BEXADZAL077",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "COMPLEXE ASMIDAL, ROUTE DES SALINES",
    "City": "ANNABA",
    "Branch": "AGENCE ANNABA ASMIDAL",
    "Postcode": "23000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "076",
    "SWIFT Code": "BEXADZAL076",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "SITE SIDER EL HADJAR",
    "City": "ANNABA",
    "Branch": "AGENCE ANNABA EL HADJAR",
    "Postcode": "23220",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "107",
    "SWIFT Code": "BEXADZAL107",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "122, RUE MAATAR LAKHTAR",
    "City": "ANNABA",
    "Branch": "AGENCE ANNABA ELYSA",
    "Postcode": "23000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "042",
    "SWIFT Code": "BEXADZAL042",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "14, COURS DE LA REVOLUTION",
    "City": "ANNABA",
    "Branch": "AGENCE ANNABA REVOLUTION",
    "Postcode": "23000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "078",
    "SWIFT Code": "BEXADZAL078",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "21, RUE DES JARDINS",
    "City": "ARZEW",
    "Branch": "AGENCE ARZEW LES JARDINS",
    "Postcode": "31004",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "054",
    "SWIFT Code": "BEXADZAL054",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "RUE HADJ ABDESSEMED LA VERDURE",
    "City": "BATNA",
    "Branch": "AGENCE BATNA",
    "Postcode": "05000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "093",
    "SWIFT Code": "BEXADZAL093",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "3, CITE 742 BOUAKAL",
    "City": "BATNA",
    "Branch": "BATNA BOUAKAL",
    "Postcode": "05000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "071",
    "SWIFT Code": "BEXADZAL071",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "37, AVENUE COLONEL LOTFI",
    "City": "BECHAR",
    "Branch": "AGENCE BECHAR",
    "Postcode": "15013",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BNAL",
    "countryCode": "DZ",
    "branchCode": "850",
    "SWIFT Code": "BNALDZAL850",
    "Bank Name": "BANQUE NATIONALE D'ALGERIE",
    "Address": "CITE HILLALI",
    "City": "CONSTANTINE",
    "Branch": "CONSTANTINE 850",
    "Postcode": "25000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BNAL",
    "countryCode": "DZ",
    "branchCode": "835",
    "SWIFT Code": "BNALDZAL835",
    "Bank Name": "BANQUE NATIONALE D'ALGERIE",
    "Address": "450, CITE H.L.M. LOGTS",
    "City": "CONSTANTINE",
    "Branch": "EL KHROUB",
    "Postcode": "25000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BNAL",
    "countryCode": "DZ",
    "branchCode": "616",
    "SWIFT Code": "BNALDZAL616",
    "Bank Name": "BANQUE NATIONALE D'ALGERIE",
    "Address": "AVENUE DES FRERES DJELI HAI NAILI",
    "City": "EL HARRACH",
    "Branch": "EL HARRACH 616",
    "Postcode": "16000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BNAL",
    "countryCode": "DZ",
    "branchCode": "619",
    "SWIFT Code": "BNALDZAL619",
    "Bank Name": "BANQUE NATIONALE D'ALGERIE",
    "Address": "14, RUE DU 5 JUILLET",
    "City": "EL HARRACH",
    "Branch": "EL HARRACH 619",
    "Postcode": "16000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BNAL",
    "countryCode": "DZ",
    "branchCode": "291",
    "SWIFT Code": "BNALDZAL291",
    "Bank Name": "BANQUE NATIONALE D'ALGERIE",
    "Address": "1, PLACE MED KHEMISTI",
    "City": "GHARDAIA",
    "Branch": "GHARDAIA",
    "Postcode": "47000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BNAL",
    "countryCode": "DZ",
    "branchCode": "441",
    "SWIFT Code": "BNALDZAL441",
    "Bank Name": "BANQUE NATIONALE D'ALGERIE",
    "Address": "16, RUE SOUIDANI BOUDJEMAA",
    "City": "KOLEA",
    "Branch": "KOLEA",
    "Postcode": "42003",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BNAL",
    "countryCode": "DZ",
    "branchCode": "301",
    "SWIFT Code": "BNALDZAL301",
    "Bank Name": "BANQUE NATIONALE D'ALGERIE",
    "Address": "RUE BENSAHNOUN EL MAAMOURA",
    "City": "LAGHOUAT",
    "Branch": "",
    "Postcode": "03000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BNAL",
    "countryCode": "DZ",
    "branchCode": "901",
    "SWIFT Code": "BNALDZAL901",
    "Bank Name": "BANQUE NATIONALE D'ALGERIE",
    "Address": "CENTRE COMMERCIAL",
    "City": "M'SILA",
    "Branch": "M'SILA",
    "Postcode": "31016",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BNAL",
    "countryCode": "DZ",
    "branchCode": "876",
    "SWIFT Code": "BNALDZAL876",
    "Bank Name": "BANQUE NATIONALE D'ALGERIE",
    "Address": "1, AVENUE BENYAHIA BEL",
    "City": "MOSTAGANEM",
    "Branch": "MOSTAGANEM",
    "Postcode": "27000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BNAL",
    "countryCode": "DZ",
    "branchCode": "871",
    "SWIFT Code": "BNALDZAL871",
    "Bank Name": "BANQUE NATIONALE D'ALGERIE",
    "Address": "12, RUE BENHADDADA",
    "City": "MOSTAGANEM",
    "Branch": "MOSTAGANEM 871",
    "Postcode": "27000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BNAL",
    "countryCode": "DZ",
    "branchCode": "952",
    "SWIFT Code": "BNALDZAL952",
    "Bank Name": "BANQUE NATIONALE D'ALGERIE",
    "Address": "",
    "City": "ORAN",
    "Branch": "BOULANGER ORAN",
    "Postcode": "31000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BNAL",
    "countryCode": "DZ",
    "branchCode": "958",
    "SWIFT Code": "BNALDZAL958",
    "Bank Name": "BANQUE NATIONALE D'ALGERIE",
    "Address": "",
    "City": "ORAN",
    "Branch": "DIDOUCHE MOURAD ORAN",
    "Postcode": "31000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BNAL",
    "countryCode": "DZ",
    "branchCode": "966",
    "SWIFT Code": "BNALDZAL966",
    "Bank Name": "BANQUE NATIONALE D'ALGERIE",
    "Address": "6, RUE A. TEMOUCHENT",
    "City": "ORAN",
    "Branch": "ORAN 966",
    "Postcode": "31000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BNAL",
    "countryCode": "DZ",
    "branchCode": "960",
    "SWIFT Code": "BNALDZAL960",
    "Bank Name": "BANQUE NATIONALE D'ALGERIE",
    "Address": "",
    "City": "ORAN",
    "Branch": "ORAN KHEMISTI",
    "Postcode": "31000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BNAL",
    "countryCode": "DZ",
    "branchCode": "951",
    "SWIFT Code": "BNALDZAL951",
    "Bank Name": "BANQUE NATIONALE D'ALGERIE",
    "Address": "4, BLD DE LA SOUMMAM",
    "City": "ORAN",
    "Branch": "ORAN SOUMMAM",
    "Postcode": "31000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BNAL",
    "countryCode": "DZ",
    "branchCode": "946",
    "SWIFT Code": "BNALDZAL946",
    "Bank Name": "BANQUE NATIONALE D'ALGERIE",
    "Address": "AVE DE L'ALN",
    "City": "OUARGLA",
    "Branch": "",
    "Postcode": "30000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BNAL",
    "countryCode": "DZ",
    "branchCode": "869",
    "SWIFT Code": "BNALDZAL869",
    "Bank Name": "BANQUE NATIONALE D'ALGERIE",
    "Address": "29, BLD MED KHEMISTI",
    "City": "RELIZANE",
    "Branch": "RELIZANE",
    "Postcode": "48000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BNAL",
    "countryCode": "DZ",
    "branchCode": "632",
    "SWIFT Code": "BNALDZAL632",
    "Bank Name": "BANQUE NATIONALE D'ALGERIE",
    "Address": "PLACE DU 1ER NOVEMBRE",
    "City": "ROUIBA",
    "Branch": "ROUIBA 632",
    "Postcode": "10031",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BNAL",
    "countryCode": "DZ",
    "branchCode": "641",
    "SWIFT Code": "BNALDZAL641",
    "Bank Name": "BANQUE NATIONALE D'ALGERIE",
    "Address": "RUE HASSIBA BEN BOUALI",
    "City": "ROUIBA",
    "Branch": "ROUIBA 641",
    "Postcode": "10031",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BNAL",
    "countryCode": "DZ",
    "branchCode": "704",
    "SWIFT Code": "BNALDZAL704",
    "Bank Name": "BANQUE NATIONALE D'ALGERIE",
    "Address": "24, AV. MUSTAPHA BENBOULAID",
    "City": "SETIF",
    "Branch": "SETIF",
    "Postcode": "19000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BNAL",
    "countryCode": "DZ",
    "branchCode": "743",
    "SWIFT Code": "BNALDZAL743",
    "Bank Name": "BANQUE NATIONALE D'ALGERIE",
    "Address": "26, RUE DIDOUCHE MOURAD",
    "City": "SKIKDA",
    "Branch": "SKIKDA",
    "Postcode": "21000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BNAL",
    "countryCode": "DZ",
    "branchCode": "440",
    "SWIFT Code": "BNALDZAL440",
    "Bank Name": "BANQUE NATIONALE D'ALGERIE",
    "Address": "RUE MELLEL",
    "City": "STAOUELI",
    "Branch": "STAOUELI",
    "Postcode": "16101",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BNAL",
    "countryCode": "DZ",
    "branchCode": "473",
    "SWIFT Code": "BNALDZAL473",
    "Bank Name": "BANQUE NATIONALE D'ALGERIE",
    "Address": "CENTRE COMMERCIAL",
    "City": "TAMANRASSET",
    "Branch": "TAMANRASSET",
    "Postcode": "11000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BNAL",
    "countryCode": "DZ",
    "branchCode": "491",
    "SWIFT Code": "BNALDZAL491",
    "Bank Name": "BANQUE NATIONALE D'ALGERIE",
    "Address": "BLD MAHMOUD CHERIF",
    "City": "TEBESSA",
    "Branch": "TEBESSA",
    "Postcode": "12000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BNAL",
    "countryCode": "DZ",
    "branchCode": "540",
    "SWIFT Code": "BNALDZAL540",
    "Bank Name": "BANQUE NATIONALE D'ALGERIE",
    "Address": "17, BLD DE LA VICTOIRE",
    "City": "TIARET",
    "Branch": "TIARET",
    "Postcode": "14000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BNAL",
    "countryCode": "DZ",
    "branchCode": "581",
    "SWIFT Code": "BNALDZAL581",
    "Bank Name": "BANQUE NATIONALE D'ALGERIE",
    "Address": "AVENUE ABANE RAMDANE",
    "City": "TIZI-OUZOU",
    "Branch": "TIZI-OUZOU 581",
    "Postcode": "15000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BNAL",
    "countryCode": "DZ",
    "branchCode": "583",
    "SWIFT Code": "BNALDZAL583",
    "Bank Name": "BANQUE NATIONALE D'ALGERIE",
    "Address": "2000, CITE LOGEMENTS",
    "City": "TIZI-OUZOU",
    "Branch": "TIZI-OUZOU 583",
    "Postcode": "15000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BNAL",
    "countryCode": "DZ",
    "branchCode": "526",
    "SWIFT Code": "BNALDZAL526",
    "Bank Name": "BANQUE NATIONALE D'ALGERIE",
    "Address": "Z.I. SUR SITE",
    "City": "TLEMCEN",
    "Branch": "ABOU TACHFINE",
    "Postcode": "13000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BNAL",
    "countryCode": "DZ",
    "branchCode": "512",
    "SWIFT Code": "BNALDZAL512",
    "Bank Name": "BANQUE NATIONALE D'ALGERIE",
    "Address": "30, PLACE KHEMISTI",
    "City": "TLEMCEN",
    "Branch": "TLEMCEN",
    "Postcode": "13000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BNAL",
    "countryCode": "DZ",
    "branchCode": "527",
    "SWIFT Code": "BNALDZAL527",
    "Bank Name": "BANQUE NATIONALE D'ALGERIE",
    "Address": "29, PLACE KHEMISTI",
    "City": "TLEMCEN",
    "Branch": "TLEMCEN BRANCH",
    "Postcode": "13000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BNAL",
    "countryCode": "DZ",
    "branchCode": "941",
    "SWIFT Code": "BNALDZAL941",
    "Bank Name": "BANQUE NATIONALE D'ALGERIE",
    "Address": "AV. DU 1ER NOVEMBRE",
    "City": "TOUGGOURT",
    "Branch": "TOUGGOURT",
    "Postcode": "30002",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BNAL",
    "countryCode": "DZ",
    "branchCode": "630",
    "SWIFT Code": "BNALDZAL630",
    "Bank Name": "BANQUE NATIONALE D'ALGERIE",
    "Address": "CENTRE DES AFFAIRES",
    "City": "ZERALDA",
    "Branch": "AIN EL BENIAN",
    "Postcode": "16063",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BNPA",
    "countryCode": "DZ",
    "branchCode": "ZAL",
    "SWIFT Code": "BNPADZAL",
    "Bank Name": "BNP PARIBAS EL DJAZAIR",
    "Address": "03.1 , LOT 1, BAB EZZOUAR, QUARTIER D'AFFAIRES D'ALGER",
    "City": "ALGIERS",
    "Branch": "",
    "Postcode": "16024",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "EPPR",
    "countryCode": "DZ",
    "branchCode": "ZAL",
    "SWIFT Code": "EPPRDZAL",
    "Bank Name": "CAISSE NATIONALE D'EPARGNE ET DE PREVOYANCE-BANQUE",
    "Address": "42, RUE KHELIFA BOUKHALFA",
    "City": "ALGIERS",
    "Branch": "",
    "Postcode": "16000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "CITI",
    "countryCode": "DZ",
    "branchCode": "ZAL",
    "SWIFT Code": "CITIDZAL",
    "Bank Name": "CITIBANK N.A. ALGERIA",
    "Address": "IMMEUBLE LE KSAR, 34/35, QUARTIER D'AFFAIRES, BAB EZZOUAR",
    "City": "ALGIERS",
    "Branch": "",
    "Postcode": "16311",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "CITI",
    "countryCode": "DZ",
    "branchCode": "TRD",
    "SWIFT Code": "CITIDZALTRD",
    "Bank Name": "CITIBANK N.A. ALGERIA",
    "Address": "HOTEL EL-AURASSI, BOULEVARD FRANTZ FANON",
    "City": "ALGIERS",
    "Branch": "TRADE SERVICES DEPT",
    "Postcode": "16000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "CPAL",
    "countryCode": "DZ",
    "branchCode": "ZAL",
    "SWIFT Code": "CPALDZAL",
    "Bank Name": "CREDIT POPULAIRE D'ALGERIE",
    "Address": "CITE DU 5 JUILLET, BAB EZZOUAR",
    "City": "ALGIERS",
    "Branch": "",
    "Postcode": "16000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "EPAL",
    "countryCode": "DZ",
    "branchCode": "ZAL",
    "SWIFT Code": "EPALDZAL",
    "Bank Name": "EPIC ALGERIE POSTE",
    "Address": "QUARTIER DES AFFAIRES",
    "City": "BAB EZZOUAR",
    "Branch": "",
    "Postcode": "16024",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "FSBK",
    "countryCode": "DZ",
    "branchCode": "ZAL",
    "SWIFT Code": "FSBKDZAL",
    "Bank Name": "FRANSABANK EL DJAZAIR SPA",
    "Address": "FRANSABANK EL DJAZAIR SPA BLDG, 45B, PETITE PROVENCE, SIDI YEHIA",
    "City": "ALGIERS",
    "Branch": "",
    "Postcode": "16000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "AGUB",
    "countryCode": "DZ",
    "branchCode": "ZAL",
    "SWIFT Code": "AGUBDZAL",
    "Bank Name": "GULF BANK ALGERIE",
    "Address": "AGB TOWER, 190, AVENUE ALI KHODJA EL BIAR",
    "City": "ALGIERS",
    "Branch": "",
    "Postcode": "16138",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "HSBC",
    "countryCode": "DZ",
    "branchCode": "ZAL",
    "SWIFT Code": "HSBCDZAL",
    "Bank Name": "HSBC ALGERIA",
    "Address": "COMPLEXE IMMOBILIER ORIENTAL, BUSINESS PARK, BUSINESS DISTRICT, BAB EZZOUAR",
    "City": "ALGIERS",
    "Branch": "",
    "Postcode": "16311",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "NATX",
    "countryCode": "DZ",
    "branchCode": "ZAL",
    "SWIFT Code": "NATXDZAL",
    "Bank Name": "NATIXIS ALGERIE",
    "Address": "IMMEUBLE LE KSAR, 34/35, Z D'AFFAIRES MERCURE, BAB EZZOUAR",
    "City": "ALGIERS",
    "Branch": "",
    "Postcode": "16311",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "SOGE",
    "countryCode": "DZ",
    "branchCode": "ZAL",
    "SWIFT Code": "SOGEDZAL",
    "Bank Name": "SOCIETE GENERALE ALGERIE",
    "Address": "RESIDENCE EL KERMA, 105, 16, GUE DE CONSTANTINE",
    "City": "ALGIERS",
    "Branch": "",
    "Postcode": "16105",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "HBHO",
    "countryCode": "DZ",
    "branchCode": "ZAL",
    "SWIFT Code": "HBHODZAL",
    "Bank Name": "THE HOUSING BANK FOR TRADE AND FINANCE ALGERIA",
    "Address": "16, AVENUE AHMED OUAKED DELY BRAHIM",
    "City": "ALGIERS",
    "Branch": "",
    "Postcode": "16320",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "TBAL",
    "countryCode": "DZ",
    "branchCode": "ZAL",
    "SWIFT Code": "TBALDZAL",
    "Bank Name": "TRUST BANK ALGERIA",
    "Address": "70, CHEMIN LARBI ALLIK HYDRA",
    "City": "ALGIERS",
    "Branch": "",
    "Postcode": "16035",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "041",
    "SWIFT Code": "BEXADZAL041",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "BLD KRIM BELKACEM",
    "City": "BEJAIA",
    "Branch": "AGENCE BEJAIA 041",
    "Postcode": "06000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "040",
    "SWIFT Code": "BEXADZAL040",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "11, RUE SI HOUAS",
    "City": "BEJAIA",
    "Branch": "AGENCE DE BEJAIA",
    "Postcode": "06000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "075",
    "SWIFT Code": "BEXADZAL075",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "10, RUE DE LA REPUBLIQUE",
    "City": "BENI SAF",
    "Branch": "AGENCE BENI SAF",
    "Postcode": "46001",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "ZAL",
    "SWIFT Code": "BEXADZAL",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "48, RUE DES FRERES BOUADOU",
    "City": "BIR MOURAD RAIS",
    "Branch": "",
    "Postcode": "16000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "095",
    "SWIFT Code": "BEXADZAL095",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "48, RUE DES FRERES BOUADOU",
    "City": "BIR MOURAD RAIS",
    "Branch": "AGENCE RAVIN",
    "Postcode": "16000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "056",
    "SWIFT Code": "BEXADZAL056",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "AVENUE BEN BADIS ET SI EL HAOUES",
    "City": "BISKRA",
    "Branch": "AGENCE BISKRA",
    "Postcode": "07000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "025",
    "SWIFT Code": "BEXADZAL025",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "SOUIDANI BOUDJEMAA, FLOOR 04, BASE CENTRALE LOGISTIQUE",
    "City": "BLIDA",
    "Branch": "AGENCE BENI MERED",
    "Postcode": "09000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "024",
    "SWIFT Code": "BEXADZAL024",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "10, BLD LAYACHI ABDELLAH",
    "City": "BLIDA",
    "Branch": "AGENCE BLIDA",
    "Postcode": "09000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "117",
    "SWIFT Code": "BEXADZAL117",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "",
    "City": "BLIDA",
    "Branch": "AGENCE BLIDA 2",
    "Postcode": "09000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "027",
    "SWIFT Code": "BEXADZAL027",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "54, AVENUE DU 1 NOVEMBRE",
    "City": "BLIDA",
    "Branch": "AGENCE MOUZAIA",
    "Postcode": "09000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "112",
    "SWIFT Code": "BEXADZAL112",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "BLD DES MARTYRS CITE 1ER MAI",
    "City": "BLIDA",
    "Branch": "OULED YAICH",
    "Postcode": "09100",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "058",
    "SWIFT Code": "BEXADZAL058",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "25, BLD DE LA REPUBLIQUE",
    "City": "BORDJ BOU ARRERIDJ",
    "Branch": "AGENCE BORDJ",
    "Postcode": "34000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "109",
    "SWIFT Code": "BEXADZAL109",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "25, BOULEVARD DE LA REPUBLIQUE",
    "City": "BORDJ BOU ARRERIDJ",
    "Branch": "AGENCE BORDJ BOU ARRERIDJ 2",
    "Postcode": "34000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "019",
    "SWIFT Code": "BEXADZAL019",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "",
    "City": "BOUFARIK",
    "Branch": "AGENCE BOUFARIK",
    "Postcode": "09001",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "037",
    "SWIFT Code": "BEXADZAL037",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "11, RUE ABANE RAMDANE",
    "City": "BOUIRA",
    "Branch": "AGENCE BOUIRA",
    "Postcode": "10000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "082",
    "SWIFT Code": "BEXADZAL082",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "COM LE ROCHER PLACE DE LA STELE",
    "City": "BOUMERDES",
    "Branch": "AGENCE BOUMERDES",
    "Postcode": "35000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "111",
    "SWIFT Code": "BEXADZAL111",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "BLOCK A, OUED TATAREG",
    "City": "BOUMERDES",
    "Branch": "AGENCE BOUMERDES 2",
    "Postcode": "35000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "006",
    "SWIFT Code": "BEXADZAL006",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "2, RUE HASSIBA BEN BOUALI",
    "City": "BOUMERDES",
    "Branch": "AGENCE ROUIBA",
    "Postcode": "35000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "086",
    "SWIFT Code": "BEXADZAL086",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "CENTRE COMMERCIAL",
    "City": "BOUSAADA",
    "Branch": "AGENCE BOUSAADA",
    "Postcode": "28001",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "068",
    "SWIFT Code": "BEXADZAL068",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "17, COLONEL BOU NAAMA",
    "City": "CHLEF",
    "Branch": "AGENCE DE CHLEF",
    "Postcode": "02000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "110",
    "SWIFT Code": "BEXADZAL110",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "7, IV NOUVELLE VILLE ALI MENDJLI",
    "City": "CONSTANTINE",
    "Branch": "AGENCE CONSTANTINE EL BEY",
    "Postcode": "25000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "050",
    "SWIFT Code": "BEXADZAL050",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "3, PLACE SI HOUAS",
    "City": "CONSTANTINE",
    "Branch": "AGENCE DE CONSTANTINE",
    "Postcode": "25000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "103",
    "SWIFT Code": "BEXADZAL103",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "1, PLACE COLONEL SI EL HAOUS",
    "City": "CONSTANTINE",
    "Branch": "CONSTANTINE SI EL HAOUES",
    "Postcode": "25000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "031",
    "SWIFT Code": "BEXADZAL031",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "CITE BEN REBIH",
    "City": "DJELFA",
    "Branch": "AGENCE DJELFA",
    "Postcode": "17000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "039",
    "SWIFT Code": "BEXADZAL039",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "1100, CITE DES LOGTS",
    "City": "EL KHROUB",
    "Branch": "AGENCE EL KHROUB",
    "Postcode": "25005",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "002",
    "SWIFT Code": "BEXADZAL002",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "CENTRE DES ARTS, 108",
    "City": "EL MADANIA",
    "Branch": "AGENCE RIAD EL FETH",
    "Postcode": "16015",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "097",
    "SWIFT Code": "BEXADZAL097",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "20, RUE DU AOUT 1955",
    "City": "EL MILIA",
    "Branch": "AGENCE EL MILIA",
    "Postcode": "18001",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "094",
    "SWIFT Code": "BEXADZAL094",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "CITE RIMMEL",
    "City": "EL-OUED",
    "Branch": "AGENCE EL-OUED",
    "Postcode": "39000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "028",
    "SWIFT Code": "BEXADZAL028",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "54, AVENUE DU 1 NOVEMBRE",
    "City": "GHARDAIA",
    "Branch": "AGENCE GHARDAIA",
    "Postcode": "47000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "080",
    "SWIFT Code": "BEXADZAL080",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "1954, AVENUE DU 1 NOVEMBRE",
    "City": "GHAZAOUET",
    "Branch": "AGENCE GHAZAOUET",
    "Postcode": "13002",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "055",
    "SWIFT Code": "BEXADZAL055",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "AVENUE ALI CHORFI",
    "City": "GUELMA",
    "Branch": "AGENCE GUELMA",
    "Postcode": "24000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "035",
    "SWIFT Code": "BEXADZAL035",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "2, AGENCE HASSI MESSAOUD 035 XABC, BEA",
    "City": "HASSI-MESSAOUD",
    "Branch": "",
    "Postcode": "30500",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "033",
    "SWIFT Code": "BEXADZAL033",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "VILLA D'HOTES",
    "City": "HASSI-MESSAOUD",
    "Branch": "AGENCE DE HASSI-MESSAOUD",
    "Postcode": "30500",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "083",
    "SWIFT Code": "BEXADZAL083",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "5, CITE DU 05 JUILLET SITE, SONATRACH",
    "City": "HASSI-R'MEL",
    "Branch": "AGENCE HASSI-R'MEL",
    "Postcode": "03300",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "092",
    "SWIFT Code": "BEXADZAL092",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "11, PLACE DU DECEMBRE 1960",
    "City": "IN AMENAS",
    "Branch": "AGENCE IN AMENAS",
    "Postcode": "33001",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "048",
    "SWIFT Code": "BEXADZAL048",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "ROUTE DE CONSTANTINE",
    "City": "JIJEL",
    "Branch": "AGENCE JIJEL",
    "Postcode": "18000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "043",
    "SWIFT Code": "BEXADZAL043",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "1, RUE IBN KHELDOUN",
    "City": "JIJEL",
    "Branch": "AGENCE JIJEL IBN KHELDOUN",
    "Postcode": "18000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "029",
    "SWIFT Code": "BEXADZAL029",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "35, BLD EMIR ABDELKADER",
    "City": "LAGHOUAT",
    "Branch": "AGENCE DE LAGHOUAT",
    "Postcode": "03000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "047",
    "SWIFT Code": "BEXADZAL047",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "32, CITE DES 200 LOGTS",
    "City": "M'SILA",
    "Branch": "AGENCE M'SILA",
    "Postcode": "31016",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "067",
    "SWIFT Code": "BEXADZAL067",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "PLACE EMIR ABDELKADER",
    "City": "MASCARA",
    "Branch": "AGENCE MASCARA",
    "Postcode": "16000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "026",
    "SWIFT Code": "BEXADZAL026",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "AVENUE AHMED FARAH",
    "City": "MEDEA",
    "Branch": "AGENCE MEDEA",
    "Postcode": "26000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "066",
    "SWIFT Code": "BEXADZAL066",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "4, RUE EMIR ABDELKADER",
    "City": "MOSTAGANEM",
    "Branch": "AGENCE DE MOSTAGANEM",
    "Postcode": "27000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "104",
    "SWIFT Code": "BEXADZAL104",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "13, RUE COUR DE FACULTE",
    "City": "MOSTAGANEM",
    "Branch": "MOSTAGANEM CORPORATE",
    "Postcode": "27000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "070",
    "SWIFT Code": "BEXADZAL070",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "ZONE INDUSTRIELLE ARZEW",
    "City": "ORAN",
    "Branch": "AGENCE ARZEW SITE SONATRACH",
    "Postcode": "31000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "074",
    "SWIFT Code": "BEXADZAL074",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "AVENUE CHEIKH ABK MEDIONI",
    "City": "ORAN",
    "Branch": "AGENCE ORAN",
    "Postcode": "31000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "060",
    "SWIFT Code": "BEXADZAL060",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "RUE LARBI BEN M'HIDI ALGER",
    "City": "ORAN",
    "Branch": "AGENCE ORAN ABDELAKADER",
    "Postcode": "16000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "062",
    "SWIFT Code": "BEXADZAL062",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "5, SQUARE CAYLA",
    "City": "ORAN",
    "Branch": "AGENCE ORAN KHEMISTI",
    "Postcode": "31000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "079",
    "SWIFT Code": "BEXADZAL079",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "19, RUE MEKKI KHELIFA",
    "City": "ORAN",
    "Branch": "AGENCE ORAN SITE SNS",
    "Postcode": "31000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "115",
    "SWIFT Code": "BEXADZAL115",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "RESIDENCE TOURS CHERIF, RUE OULD KABLIA SALIHA, CITE EL OMARIA",
    "City": "ORAN",
    "Branch": "ORAN 115",
    "Postcode": "31000",
    "Country": "Algeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BEXA",
    "countryCode": "DZ",
    "branchCode": "081",
    "SWIFT Code": "BEXADZAL081",
    "Bank Name": "BANQUE EXTERIEURE D'ALGERIE",
    "Address": "",
    "City": "ORAN",
    "Branch": "ORAN EL DJAMEL",
    "Postcode": "31000",
    "Country": "Algeria",
    "Connection": "Active"
  }
]
module.exports = algeria
