const angola = [
  {
    "bankCode": "BAIP",
    "countryCode": "AO",
    "branchCode": "OLU",
    "SWIFT Code": "BAIPAOLU",
    "Bank Name": "BANCO ANGOLANO DE INVESTIMENTOS, SA",
    "Address": "COMPLEXO GARDEN TOWERS, TORRE BAI, TRAVESSA HO-CHI-MIN, MAIANGA",
    "City": "LUANDA",
    "Branch": "",
    "Postcode": "",
    "Country": "Angola",
    "Connection": "Active"
  },
  {
    "bankCode": "ANCE",
    "countryCode": "AO",
    "branchCode": "OLU",
    "SWIFT Code": "ANCEAOLU",
    "Bank Name": "BANCO ANGOLANO NEGOCIOS E COMERCIO",
    "Address": "TRAVESSA DA SORTE 12",
    "City": "LUANDA",
    "Branch": "",
    "Postcode": "",
    "Country": "Angola",
    "Connection": "Active"
  },
  {
    "bankCode": "BCCB",
    "countryCode": "AO",
    "branchCode": "OLU",
    "SWIFT Code": "BCCBAOLU",
    "Bank Name": "BANCO BIC, S.A.",
    "Address": "BAIRRO DE TALATONA, SECTOR INST 4, SAMBA",
    "City": "LUANDA",
    "Branch": "",
    "Postcode": "",
    "Country": "Angola",
    "Connection": "Active"
  },
  {
    "bankCode": "BCGA",
    "countryCode": "AO",
    "branchCode": "OLU",
    "SWIFT Code": "BCGAAOLU",
    "Bank Name": "BANCO CAIXA GERAL DE ANGOLA",
    "Address": "AVENIDA 4 DE FEVEREIRO 99",
    "City": "LUANDA",
    "Branch": "",
    "Postcode": "0001",
    "Country": "Angola",
    "Connection": "Active"
  },
  {
    "bankCode": "COML",
    "countryCode": "AO",
    "branchCode": "OLU",
    "SWIFT Code": "COMLAOLU",
    "Bank Name": "BANCO COMERCIAL ANGOLANO",
    "Address": "AVENIDA COMANDANTE VALODIA 83 A",
    "City": "LUANDA",
    "Branch": "",
    "Postcode": "",
    "Country": "Angola",
    "Connection": "Active"
  },
  {
    "bankCode": "BCHU",
    "countryCode": "AO",
    "branchCode": "OLU",
    "SWIFT Code": "BCHUAOLU",
    "Bank Name": "BANCO COMERCIAL DO HUAMBO",
    "Address": "AV. INDEPENDENCIA 11-13",
    "City": "HUAMBO",
    "Branch": "",
    "Postcode": "",
    "Country": "Angola",
    "Connection": "Active"
  },
  {
    "bankCode": "BDAA",
    "countryCode": "AO",
    "branchCode": "OLU",
    "SWIFT Code": "BDAAAOLU",
    "Bank Name": "BANCO DE DESENVOLVIMENTO DE ANGOLA",
    "Address": "AVENIDA 4 DE FEVEREIRO 113",
    "City": "LUANDA",
    "Branch": "",
    "Postcode": "",
    "Country": "Angola",
    "Connection": "Active"
  },
  {
    "bankCode": "BFMX",
    "countryCode": "AO",
    "branchCode": "OLU",
    "SWIFT Code": "BFMXAOLU",
    "Bank Name": "BANCO DE FOMENTO ANGOLA, S.A.",
    "Address": "EDIFICIO ROBERT HUDSON, RUA AMILCAR CABRAL 58",
    "City": "LUANDA",
    "Branch": "",
    "Postcode": "",
    "Country": "Angola",
    "Connection": "Active"
  },
  {
    "bankCode": "BIRV",
    "countryCode": "AO",
    "branchCode": "OLU",
    "SWIFT Code": "BIRVAOLU",
    "Bank Name": "BANCO DE INVESTIMENTO RURAL, S.A.",
    "Address": "EDF BENGO, BELAS BUSINESS PARK, FLOOR 7, TALATONA",
    "City": "LUANDA",
    "Branch": "",
    "Postcode": "",
    "Country": "Angola",
    "Connection": "Active"
  },
  {
    "bankCode": "BNIC",
    "countryCode": "AO",
    "branchCode": "052",
    "SWIFT Code": "BNICAOLU052",
    "Bank Name": "BANCO DE NEGOCIOS INTERNACIONAL",
    "Address": "",
    "City": "LUANDA",
    "Branch": "",
    "Postcode": "",
    "Country": "Angola",
    "Connection": "Active"
  },
  {
    "bankCode": "BNIC",
    "countryCode": "AO",
    "branchCode": "OLU",
    "SWIFT Code": "BNICAOLU",
    "Bank Name": "BANCO DE NEGOCIOS INTERNACIONAL",
    "Address": "AVENIDA CHE-GUEVARA,MACULUSSO 42A",
    "City": "LUANDA",
    "Branch": "",
    "Postcode": "",
    "Country": "Angola",
    "Connection": "Active"
  },
  {
    "bankCode": "BESC",
    "countryCode": "AO",
    "branchCode": "OLU",
    "SWIFT Code": "BESCAOLU",
    "Bank Name": "BANCO ECONOMICO, S.A.",
    "Address": "RUA DO 1 CONGRESSO DO MPLA 8, INGOMBOTAS",
    "City": "LUANDA",
    "Branch": "",
    "Postcode": "",
    "Country": "Angola",
    "Connection": "Active"
  },
  {
    "bankCode": "BRDK",
    "countryCode": "AO",
    "branchCode": "OLU",
    "SWIFT Code": "BRDKAOLU",
    "Bank Name": "BANCO KEVE, SA",
    "Address": "EDIFICIO GARDEN, TORRE B AV. HO, CHI MIN EMP. CDT GIKA 1, FLOOR 12",
    "City": "LUANDA",
    "Branch": "",
    "Postcode": "",
    "Country": "Angola",
    "Connection": "Active"
  },
  {
    "bankCode": "PUAD",
    "countryCode": "AO",
    "branchCode": "OLU",
    "SWIFT Code": "PUADAOLU",
    "Bank Name": "BANCO MAIS, S.A.",
    "Address": "ED CMDT GIKA B4, TRAVESSA HO CHI MINH, FLOOR 7, BAIRRO ALVALADE, MAIANGA",
    "City": "LUANDA",
    "Branch": "",
    "Postcode": "",
    "Country": "Angola",
    "Connection": "Active"
  },
  {
    "bankCode": "PRTL",
    "countryCode": "AO",
    "branchCode": "OLU",
    "SWIFT Code": "PRTLAOLU",
    "Bank Name": "BANCO MILLENNIUM ATLANTICO, S.A.",
    "Address": "CIDADE FINANCEIRA, VIA S8, TALATONA LUANDA SUL 7/8",
    "City": "LUANDA",
    "Branch": "",
    "Postcode": "",
    "Country": "Angola",
    "Connection": "Active"
  },
  {
    "bankCode": "BNAN",
    "countryCode": "AO",
    "branchCode": "OLU",
    "SWIFT Code": "BNANAOLU",
    "Bank Name": "BANCO NACIONAL DE ANGOLA",
    "Address": "AV. 4 DE FEVEREIRO 151",
    "City": "LUANDA",
    "Branch": "",
    "Postcode": "",
    "Country": "Angola",
    "Connection": "Active"
  },
  {
    "bankCode": "BNAN",
    "countryCode": "AO",
    "branchCode": "OLD",
    "SWIFT Code": "BNANAOLD",
    "Bank Name": "BANCO NACIONAL DE ANGOLA",
    "Address": "AV. 4 DE FEVEREIRO 151",
    "City": "LUANDA",
    "Branch": "BNA-SEDE",
    "Postcode": "",
    "Country": "Angola",
    "Connection": "Active"
  },
  {
    "bankCode": "BNAN",
    "countryCode": "AO",
    "branchCode": "975",
    "SWIFT Code": "BNANAOLU975",
    "Bank Name": "BANCO NACIONAL DE ANGOLA",
    "Address": "",
    "City": "LUANDA",
    "Branch": "T2S WAVE 1",
    "Postcode": "",
    "Country": "Angola",
    "Connection": "Active"
  },
  {
    "bankCode": "POTA",
    "countryCode": "AO",
    "branchCode": "OLU",
    "SWIFT Code": "POTAAOLU",
    "Bank Name": "BANCO POSTAL, S.A.",
    "Address": "ESCOM MARECHAL BROS TITO 35 / 37,, FLOOR 15",
    "City": "LUANDA",
    "Branch": "",
    "Postcode": "",
    "Country": "Angola",
    "Connection": "Active"
  },
  {
    "bankCode": "PRTS",
    "countryCode": "AO",
    "branchCode": "OLU",
    "SWIFT Code": "PRTSAOLU",
    "Bank Name": "BANCO PRESTIGIO, SA.",
    "Address": "TORRE ELYSEE E2, RAINHA GINGA 31, FLOOR 3",
    "City": "LUANDA",
    "Branch": "",
    "Postcode": "",
    "Country": "Angola",
    "Connection": "Active"
  },
  {
    "bankCode": "SOLO",
    "countryCode": "AO",
    "branchCode": "OLU",
    "SWIFT Code": "SOLOAOLU",
    "Bank Name": "BANCO SOL, S.A.",
    "Address": "RUE REI KATYAVALA 110/112, BAIRRO MACULUSSO",
    "City": "LUANDA",
    "Branch": "",
    "Postcode": "",
    "Country": "Angola",
    "Connection": "Active"
  },
  {
    "bankCode": "BVBX",
    "countryCode": "AO",
    "branchCode": "OLU",
    "SWIFT Code": "BVBXAOLU",
    "Bank Name": "BANCO VALOR BANK",
    "Address": "EDIF. V BLOCO RUA DO CENTRO DE, CONVENCOES 9/10, FLOOR 1",
    "City": "LUANDA",
    "Branch": "",
    "Postcode": "",
    "Country": "Angola",
    "Connection": "Active"
  },
  {
    "bankCode": "VTBL",
    "countryCode": "AO",
    "branchCode": "OLU",
    "SWIFT Code": "VTBLAOLU",
    "Bank Name": "BANCO VTB AFRICA, S.A.",
    "Address": "EDIFICIO DO BANCO VTB AFRICA, RUA DA MISSAO 22",
    "City": "LUANDA",
    "Branch": "",
    "Postcode": "",
    "Country": "Angola",
    "Connection": "Active"
  },
  {
    "bankCode": "YETU",
    "countryCode": "AO",
    "branchCode": "OLU",
    "SWIFT Code": "YETUAOLU",
    "Bank Name": "BANCO YETU, S.A.",
    "Address": "TORRE MACULUSSO PISO 2, RUA FREDERICO WELWITSCH, FLOOR 2, INGOMBOTA URBAN DISTRICT",
    "City": "LUANDA",
    "Branch": "",
    "Postcode": "",
    "Country": "Angola",
    "Connection": "Active"
  },
  {
    "bankCode": "BKCH",
    "countryCode": "AO",
    "branchCode": "OLU",
    "SWIFT Code": "BKCHAOLU",
    "Bank Name": "BANK OF CHINA LIMITED LUANDA BRANCH",
    "Address": "COMD BELAS BUS PARK, TOR CUANZA SUL, FLOOR 8",
    "City": "LUANDA",
    "Branch": "",
    "Postcode": "",
    "Country": "Angola",
    "Connection": "Active"
  },
  {
    "bankCode": "BCID",
    "countryCode": "AO",
    "branchCode": "OLU",
    "SWIFT Code": "BCIDAOLU",
    "Bank Name": "BCI - BANCO DE COMERCIO E INDUSTRIA",
    "Address": "LGO ATLCO BCI-BANCO DE COMERCIO E, INDUSTRIA RUA RAINHA GINGA 79/83",
    "City": "LUANDA",
    "Branch": "",
    "Postcode": "",
    "Country": "Angola",
    "Connection": "Active"
  },
  {
    "bankCode": "CDTS",
    "countryCode": "AO",
    "branchCode": "OLU",
    "SWIFT Code": "CDTSAOLU",
    "Bank Name": "BCS - BANCO DE CREDITO DO SUL, S.A.",
    "Address": "AVENIDA NOSSA SENHORA DO MONTE",
    "City": "LUANDA",
    "Branch": "",
    "Postcode": "",
    "Country": "Angola",
    "Connection": "Active"
  },
  {
    "bankCode": "BDVA",
    "countryCode": "AO",
    "branchCode": "OLU",
    "SWIFT Code": "BDVAAOLU",
    "Bank Name": "BOLSA DE DIVIDA E VALORES DE ANGOLA BODIVA SOCIEDADE GESTORA DE MERCADOS REGULAMENTADOS SA",
    "Address": "SKY BUSINESS TOWER, MARECHAL BROS TITO 41, FLOOR 8",
    "City": "LUANDA",
    "Branch": "",
    "Postcode": "",
    "Country": "Angola",
    "Connection": "Active"
  },
  {
    "bankCode": "BPCL",
    "countryCode": "AO",
    "branchCode": "OLU",
    "SWIFT Code": "BPCLAOLU",
    "Bank Name": "BPC-BANCO DE POUPANCA E CREDITO",
    "Address": "LARGO SAYDI MINGAS",
    "City": "LUANDA",
    "Branch": "",
    "Postcode": "",
    "Country": "Angola",
    "Connection": "Active"
  },
  {
    "bankCode": "FBCO",
    "countryCode": "AO",
    "branchCode": "OLU",
    "SWIFT Code": "FBCOAOLU",
    "Bank Name": "FINIBANCO ANGOLA S.A",
    "Address": "TRAVESSA ENGRACIA FRAGOSO 24, INGOMBOTAS. BAIRRO PATRICE LUMUMBA",
    "City": "LUANDA",
    "Branch": "",
    "Postcode": "",
    "Country": "Angola",
    "Connection": "Active"
  },
  {
    "bankCode": "SBIC",
    "countryCode": "AO",
    "branchCode": "OLU",
    "SWIFT Code": "SBICAOLU",
    "Bank Name": "STANDARD BANK DE ANGOLA S.A.",
    "Address": "TORRE 1 INARA BUSINESS PARK AND, GARDENS VIA A2 DISTRITO URBANO DE",
    "City": "TALATONA",
    "Branch": "",
    "Postcode": "",
    "Country": "Angola",
    "Connection": "Active"
  },
  {
    "bankCode": "SCBL",
    "countryCode": "AO",
    "branchCode": "OLU",
    "SWIFT Code": "SCBLAOLU",
    "Bank Name": "STANDARD CHARTERED BANK ANGOLA SA",
    "Address": "EDIFICIO KILAMBA AV. 4 DE, FEVEREIRO, MARGINAL, FLOOR 8",
    "City": "LUANDA",
    "Branch": "",
    "Postcode": "",
    "Country": "Angola",
    "Connection": "Active"
  }
]
module.exports = angola
