const antiguaAndBarbuda = [
  {
    "bankCode": "ANCB",
    "countryCode": "AG",
    "branchCode": "GAG",
    "SWIFT Code": "ANCBAGAG",
    "Bank Name": "ANTIGUA COMMERCIAL BANK",
    "Address": "THAMES AND ST. MARY'S STREETS",
    "City": "ST. JOHN'S",
    "Branch": "",
    "Postcode": "",
    "Country": "Antigua and Barbuda",
    "Connection": "Active"
  },
  {
    "bankCode": "BOIB",
    "countryCode": "AG",
    "branchCode": "GAG",
    "SWIFT Code": "BOIBAGAG",
    "Bank Name": "BOI BANK CORPORATION",
    "Address": "FLOOR 1, SUITE 2 , VILLAGE WALK, COMMERCIAL CENTER FRIAR S HILL ROAD",
    "City": "ST. JOHN'S",
    "Branch": "",
    "Postcode": "",
    "Country": "Antigua and Barbuda",
    "Connection": "Active"
  },
  {
    "bankCode": "BRSF",
    "countryCode": "AG",
    "branchCode": "GAG",
    "SWIFT Code": "BRSFAGAG",
    "Bank Name": "BRS BANQUE S.A.",
    "Address": "SUITE 25-26, JASMINE COURT, FRIARS HILL ROAD",
    "City": "ST. JOHN'S",
    "Branch": "",
    "Postcode": "",
    "Country": "Antigua and Barbuda",
    "Connection": "Active"
  },
  {
    "bankCode": "CUNB",
    "countryCode": "AG",
    "branchCode": "GAG",
    "SWIFT Code": "CUNBAGAG",
    "Bank Name": "CARIBBEAN UNION BANK LTD",
    "Address": "GLOBAL FINANCIAL CENTRE, FRIARS HILL ROAD",
    "City": "ST. JOHN'S",
    "Branch": "",
    "Postcode": "",
    "Country": "Antigua and Barbuda",
    "Connection": "Active"
  },
  {
    "bankCode": "DANL",
    "countryCode": "AG",
    "branchCode": "GAG",
    "SWIFT Code": "DANLAGAG",
    "Bank Name": "D BANK LTD.",
    "Address": "SUITE 2, LONDON HOUSE BUILDING, LONG AND CROSS ST",
    "City": "ST. JOHN'S",
    "Branch": "",
    "Postcode": "",
    "Country": "Antigua and Barbuda",
    "Connection": "Active"
  },
  {
    "bankCode": "ECAB",
    "countryCode": "AG",
    "branchCode": "GAG",
    "SWIFT Code": "ECABAGAG",
    "Bank Name": "EASTERN CARIBBEAN AMALGAMATED BANK LTD. (ECAB)",
    "Address": "AIRPORT BOULEVARD, 1000 AT PAVILION DRIVE",
    "City": "COOLIDGE",
    "Branch": "",
    "Postcode": "",
    "Country": "Antigua and Barbuda",
    "Connection": "Active"
  },
  {
    "bankCode": "FCIB",
    "countryCode": "AG",
    "branchCode": "GAG",
    "SWIFT Code": "FCIBAGAG",
    "Bank Name": "FIRSTCARIBBEAN INTERNATIONAL BANK (BARBADOS) LIMITED",
    "Address": "HIGH STREET",
    "City": "ST. JOHN'S",
    "Branch": "",
    "Postcode": "",
    "Country": "Antigua and Barbuda",
    "Connection": "Active"
  },
  {
    "bankCode": "GBCL",
    "countryCode": "AG",
    "branchCode": "GAG",
    "SWIFT Code": "GBCLAGAG",
    "Bank Name": "GLOBAL BANK OF COMMERCE, LTD.",
    "Address": "GLOBAL FINANCIAL CENTRE, FRIARS HILL ROAD",
    "City": "ST. JOHN'S",
    "Branch": "",
    "Postcode": "",
    "Country": "Antigua and Barbuda",
    "Connection": "Active"
  },
  {
    "bankCode": "NEXO",
    "countryCode": "AG",
    "branchCode": "GA2",
    "SWIFT Code": "NEXOAGA2",
    "Bank Name": "NEXO BANK INC",
    "Address": "SUITE 28, JASMINE COURT",
    "City": "ST. JOHN'S",
    "Branch": "",
    "Postcode": "",
    "Country": "Antigua and Barbuda",
    "Connection": "Active"
  },
  {
    "bankCode": "NOIT",
    "countryCode": "AG",
    "branchCode": "GAG",
    "SWIFT Code": "NOITAGAG",
    "Bank Name": "NORTH INTERNATIONAL BANK, LTD.",
    "Address": "SUITE 20, WOODS MALL, FRIAS HIL ROAD",
    "City": "ST. JOHN'S",
    "Branch": "",
    "Postcode": "",
    "Country": "Antigua and Barbuda",
    "Connection": "Active"
  },
  {
    "bankCode": "TOLM",
    "countryCode": "AG",
    "branchCode": "GAG",
    "SWIFT Code": "TOLMAGAG",
    "Bank Name": "TOLOMEO BANK LIMITED",
    "Address": "10 REDCLIFFE QUAY",
    "City": "ST. JOHN'S",
    "Branch": "",
    "Postcode": "",
    "Country": "Antigua and Barbuda",
    "Connection": "Active"
  }
]
module.exports = antiguaAndBarbuda
