const argentina = [
  {
    "countryCode": "BFRP",
    "bankCode": "AR",
    "branchCode": "RBA",
    "SWIFT Code": "BFRPARBA",
    "Bank Name": "BANCO BBVA ARGENTINA S.A.",
    "Address": "AV. CORDOBA 111",
    "City": "BUENOS AIRES",
    "Branch": "",
    "Postcode": "C1054AAA",
    "Country": "Argentina",
    "Connection": "Active"
  },
  {
    "countryCode": "BICA",
    "bankCode": "AR",
    "branchCode": "RBS",
    "SWIFT Code": "BICAARBS",
    "Bank Name": "BANCO BICA  S.A.",
    "Address": "25 DE MAYO 2446",
    "City": "SANTA FE",
    "Branch": "",
    "Postcode": "S3000FTT",
    "Country": "Argentina",
    "Connection": "Active"
  },
  {
    "countryCode": "ITAU",
    "bankCode": "AR",
    "branchCode": "RBA",
    "SWIFT Code": "ITAUARBA",
    "Bank Name": "BANCO BMA S.A.U.",
    "Address": "VICTORIA OCAMPO 360",
    "City": "BUENOS AIRES",
    "Branch": "",
    "Postcode": "C1107DAB",
    "Country": "Argentina",
    "Connection": "Active"
  },
  {
    "countryCode": "BCRA",
    "bankCode": "AR",
    "branchCode": "RBA",
    "SWIFT Code": "BCRAARBA",
    "Bank Name": "BANCO CENTRAL DE LA REPUBLICA ARGENTINA",
    "Address": "RECONQUISTA 266-74",
    "City": "BUENOS AIRES",
    "Branch": "",
    "Postcode": "C1003ABF",
    "Country": "Argentina",
    "Connection": "Active"
  },
  {
    "countryCode": "CMFB",
    "bankCode": "AR",
    "branchCode": "RBA",
    "SWIFT Code": "CMFBARBA",
    "Bank Name": "BANCO CMF S.A.",
    "Address": "MACACHA GUEMES 150, PUERTO MADERO",
    "City": "BUENOS AIRES",
    "Branch": "",
    "Postcode": "C1106BKD",
    "Country": "Argentina",
    "Connection": "Active"
  },
  {
    "countryCode": "CNIA",
    "bankCode": "AR",
    "branchCode": "RBR",
    "SWIFT Code": "CNIAARBR",
    "Bank Name": "BANCO COINAG S.A.",
    "Address": "MITRE 602, FLOOR 4, CASA CENTRAL",
    "City": "ROSARIO",
    "Branch": "",
    "Postcode": "S2000CON",
    "Country": "Argentina",
    "Connection": "Active"
  },
  {
    "countryCode": "CLLU",
    "bankCode": "AR",
    "branchCode": "RBA",
    "SWIFT Code": "CLLUARBA",
    "Bank Name": "BANCO COLUMBIA S.A.",
    "Address": "J.D. PERON 350",
    "City": "BUENOS AIRES",
    "Branch": "",
    "Postcode": "C1038AAH",
    "Country": "Argentina",
    "Connection": "Active"
  },
  {
    "countryCode": "QUIL",
    "bankCode": "AR",
    "branchCode": "RBA",
    "SWIFT Code": "QUILARBA",
    "Bank Name": "BANCO COMAFI S.A.",
    "Address": "AV. ROQUE SAENZ PENA 660",
    "City": "BUENOS AIRES",
    "Branch": "",
    "Postcode": "C1035AAO",
    "Country": "Argentina",
    "Connection": "Active"
  },
  {
    "countryCode": "BCOO",
    "bankCode": "AR",
    "branchCode": "RBA",
    "SWIFT Code": "BCOOARBA",
    "Bank Name": "BANCO CREDICOOP COOPERATIVO LIMITADO",
    "Address": "RECONQUISTA 484, FLOOR 3",
    "City": "BUENOS AIRES",
    "Branch": "",
    "Postcode": "C1003ABJ",
    "Country": "Argentina",
    "Connection": "Active"
  },
  {
    "countryCode": "MCFA",
    "bankCode": "AR",
    "branchCode": "RBA",
    "SWIFT Code": "MCFAARBA",
    "Bank Name": "BANCO DE COMERCIO S.A.",
    "Address": "SARMIENTO 356",
    "City": "BUENOS AIRES",
    "Branch": "",
    "Postcode": "C1041AAH",
    "Country": "Argentina",
    "Connection": "Active"
  },
  {
    "countryCode": "BCOR",
    "bankCode": "AR",
    "branchCode": "RBC",
    "SWIFT Code": "BCORARBC",
    "Bank Name": "BANCO DE CORRIENTES S.A.",
    "Address": "LAVALLE 415",
    "City": "CORRIENTES",
    "Branch": "",
    "Postcode": "W3400AYR",
    "Country": "Argentina",
    "Connection": "Active"
  },
  {
    "countryCode": "BFSA",
    "bankCode": "AR",
    "branchCode": "RBF",
    "SWIFT Code": "BFSAARBF",
    "Bank Name": "BANCO DE FORMOSA S.A.",
    "Address": "AV. 25 DE MAYO 102",
    "City": "FORMOSA",
    "Branch": "",
    "Postcode": "3600",
    "Country": "Argentina",
    "Connection": "Active"
  },
  {
    "countryCode": "GABA",
    "bankCode": "AR",
    "branchCode": "RBA",
    "SWIFT Code": "GABAARBA",
    "Bank Name": "BANCO DE GALICIA Y BUENOS AIRES",
    "Address": "TTE. GRAL. JUAN DOMINGO PERON 407",
    "City": "BUENOS AIRES",
    "Branch": "",
    "Postcode": "C1038AAI",
    "Country": "Argentina",
    "Connection": "Active"
  },
  {
    "countryCode": "BICX",
    "bankCode": "AR",
    "branchCode": "RBA",
    "SWIFT Code": "BICXARBA",
    "Bank Name": "BANCO DE INVERSION Y COMERCIO EXTERIOR S.A.",
    "Address": "BARTOLOME MITRE 836",
    "City": "BUENOS AIRES",
    "Branch": "",
    "Postcode": "C1036AAP",
    "Country": "Argentina",
    "Connection": "Active"
  },
  {},
  {
    "countryCode": "NACN",
    "bankCode": "AR",
    "branchCode": "BAH",
    "SWIFT Code": "NACNARBABAH",
    "Bank Name": "BANCO DE LA NACION ARGENTINA",
    "Address": "CORONEL BRANDSEN 36",
    "City": "BAHIA BLANCA",
    "Branch": "BAHIA BLANCA BRANCH",
    "Postcode": "B8000IQB",
    "Country": "Argentina",
    "Connection": "Active"
  },
  {
    "countryCode": "NACN",
    "bankCode": "AR",
    "branchCode": "RBA",
    "SWIFT Code": "NACNARBA",
    "Bank Name": "BANCO DE LA NACION ARGENTINA",
    "Address": "BARTOLOME MITRE 326",
    "City": "BUENOS AIRES",
    "Branch": "",
    "Postcode": "C1036AAF",
    "Country": "Argentina",
    "Connection": "Active"
  },
  {
    "countryCode": "NACN",
    "bankCode": "AR",
    "branchCode": "CCL",
    "SWIFT Code": "NACNARBACCL",
    "Bank Name": "BANCO DE LA NACION ARGENTINA",
    "Address": "",
    "City": "BUENOS AIRES",
    "Branch": "CASA CENTRAL",
    "Postcode": "",
    "Country": "Argentina",
    "Connection": "Active"
  },
  {
    "countryCode": "NACN",
    "bankCode": "AR",
    "branchCode": "CON",
    "SWIFT Code": "NACNARBACON",
    "Bank Name": "BANCO DE LA NACION ARGENTINA",
    "Address": "CARLOS PELLEGRINI 651",
    "City": "CONCORDIA",
    "Branch": "CONCORDIA BRANCH",
    "Postcode": "E3200AMK",
    "Country": "Argentina",
    "Connection": "Active"
  },
  {
    "countryCode": "NACN",
    "bankCode": "AR",
    "branchCode": "COR",
    "SWIFT Code": "NACNARBACOR",
    "Bank Name": "BANCO DE LA NACION ARGENTINA",
    "Address": "SAN JERONIMO 30",
    "City": "CORDOBA",
    "Branch": "CORDOBA BRANCH",
    "Postcode": "X5000AGB",
    "Country": "Argentina",
    "Connection": "Active"
  },
  {
    "countryCode": "NACN",
    "bankCode": "AR",
    "branchCode": "CTS",
    "SWIFT Code": "NACNARBACTS",
    "Bank Name": "BANCO DE LA NACION ARGENTINA",
    "Address": "DE JULIO 1298 9",
    "City": "CORRIENTES",
    "Branch": "CORRIENTES BRANCH",
    "Postcode": "W3400AYV",
    "Country": "Argentina",
    "Connection": "Active"
  },
  {
    "countryCode": "NACN",
    "bankCode": "AR",
    "branchCode": "MPL",
    "SWIFT Code": "NACNARBAMPL",
    "Bank Name": "BANCO DE LA NACION ARGENTINA",
    "Address": "GRAL. SAN MARTIN 2594",
    "City": "MAR DEL PLATA",
    "Branch": "MAR DEL PLATA BRANCH",
    "Postcode": "B7600GQJ",
    "Country": "Argentina",
    "Connection": "Active"
  },
  {
    "countryCode": "NACN",
    "bankCode": "AR",
    "branchCode": "MEN",
    "SWIFT Code": "NACNARBAMEN",
    "Bank Name": "BANCO DE LA NACION ARGENTINA",
    "Address": "NECOCHEA 101",
    "City": "MENDOZA",
    "Branch": "MENDOZA BRANCH",
    "Postcode": "M5500GLC",
    "Country": "Argentina",
    "Connection": "Active"
  },
  {
    "countryCode": "NACN",
    "bankCode": "AR",
    "branchCode": "NEU",
    "SWIFT Code": "NACNARBANEU",
    "Bank Name": "BANCO DE LA NACION ARGENTINA",
    "Address": "AV ARGENTINA 82",
    "City": "NEUQUEN",
    "Branch": "NEUQUEN BRANCH",
    "Postcode": "Q8300AYN",
    "Country": "Argentina",
    "Connection": "Active"
  },
  {
    "countryCode": "NACN",
    "bankCode": "AR",
    "branchCode": "PER",
    "SWIFT Code": "NACNARBAPER",
    "Bank Name": "BANCO DE LA NACION ARGENTINA",
    "Address": "SAN NICOLAS 720",
    "City": "PERGAMINO",
    "Branch": "PERGAMINO BRANCH",
    "Postcode": "B2700LAP",
    "Country": "Argentina",
    "Connection": "Active"
  },
  {
    "countryCode": "NACN",
    "bankCode": "AR",
    "branchCode": "POS",
    "SWIFT Code": "NACNARBAPOS",
    "Bank Name": "BANCO DE LA NACION ARGENTINA",
    "Address": "BOLIVAR 1799",
    "City": "POSADAS",
    "Branch": "POSADAS BRANCH",
    "Postcode": "N3300AHK",
    "Country": "Argentina",
    "Connection": "Active"
  },
  {
    "countryCode": "NACN",
    "bankCode": "AR",
    "branchCode": "RAF",
    "SWIFT Code": "NACNARBARAF",
    "Bank Name": "BANCO DE LA NACION ARGENTINA",
    "Address": "SAN MARTIN 175",
    "City": "RAFAELA",
    "Branch": "RAFAELA BRANCH",
    "Postcode": "S2300KSC",
    "Country": "Argentina",
    "Connection": "Active"
  },
  {
    "countryCode": "NACN",
    "bankCode": "AR",
    "branchCode": "REC",
    "SWIFT Code": "NACNARBAREC",
    "Bank Name": "BANCO DE LA NACION ARGENTINA",
    "Address": "SAN MARTIN 802",
    "City": "RECONQUISTA",
    "Branch": "RECONQUISTA BRANCH",
    "Postcode": "S3560GUR",
    "Country": "Argentina",
    "Connection": "Active"
  },
  {
    "countryCode": "NACN",
    "bankCode": "AR",
    "branchCode": "RCU",
    "SWIFT Code": "NACNARBARCU",
    "Bank Name": "BANCO DE LA NACION ARGENTINA",
    "Address": "SOBREMONTE 777",
    "City": "RIO CUARTO",
    "Branch": "RIO CUARTO BRANCH",
    "Postcode": "X5800AAO",
    "Country": "Argentina",
    "Connection": "Active"
  },
  {
    "countryCode": "NACN",
    "bankCode": "AR",
    "branchCode": "ROS",
    "SWIFT Code": "NACNARBAROS",
    "Bank Name": "BANCO DE LA NACION ARGENTINA",
    "Address": "CORDOBA 1026",
    "City": "ROSARIO",
    "Branch": "ROSARIO BRANCH",
    "Postcode": "S2000AWN",
    "Country": "Argentina",
    "Connection": "Active"
  },
  {
    "countryCode": "NACN",
    "bankCode": "AR",
    "branchCode": "SAL",
    "SWIFT Code": "NACNARBASAL",
    "Bank Name": "BANCO DE LA NACION ARGENTINA",
    "Address": "BARTOLOME MITRE 151",
    "City": "SALTA",
    "Branch": "SALTA BRANCH",
    "Postcode": "A4400EHC",
    "Country": "Argentina",
    "Connection": "Active"
  },
  {
    "countryCode": "NACN",
    "bankCode": "AR",
    "branchCode": "SJU",
    "SWIFT Code": "NACNARBASJU",
    "Bank Name": "BANCO DE LA NACION ARGENTINA",
    "Address": "AV. RIOJA 210",
    "City": "SAN JUAN",
    "Branch": "SAN JUAN BRANCH",
    "Postcode": "",
    "Country": "Argentina",
    "Connection": "Active"
  },
  {
    "countryCode": "NACN",
    "bankCode": "AR",
    "branchCode": "SMT",
    "SWIFT Code": "NACNARBASMT",
    "Bank Name": "BANCO DE LA NACION ARGENTINA",
    "Address": "GRAL. SAN MARTIN 690",
    "City": "SAN MIGUEL DE TUCUMAN",
    "Branch": "SAN MIGUEL DE TUCUMAN BRANCH",
    "Postcode": "T4000CVN",
    "Country": "Argentina",
    "Connection": "Active"
  },
  {
    "countryCode": "NACN",
    "bankCode": "AR",
    "branchCode": "SRA",
    "SWIFT Code": "NACNARBASRA",
    "Bank Name": "BANCO DE LA NACION ARGENTINA",
    "Address": "AVDA. HIPOLITO YRIGOYEN 113",
    "City": "SAN RAFAEL",
    "Branch": "SAN RAFAEL BRANCH",
    "Postcode": "M5602HBB",
    "Country": "Argentina",
    "Connection": "Active"
  },
  {
    "countryCode": "NACN",
    "bankCode": "AR",
    "branchCode": "SFE",
    "SWIFT Code": "NACNARBASFE",
    "Bank Name": "BANCO DE LA NACION ARGENTINA",
    "Address": "GRAL. SAN MARTIN 2499",
    "City": "SANTA FE",
    "Branch": "SANTA FE BRANCH",
    "Postcode": "S3000FSA",
    "Country": "Argentina",
    "Connection": "Active"
  },
  {
    "countryCode": "NACN",
    "bankCode": "AR",
    "branchCode": "VMA",
    "SWIFT Code": "NACNARBAVMA",
    "Bank Name": "BANCO DE LA NACION ARGENTINA",
    "Address": "SANTA FE 1101",
    "City": "VILLA MARIA",
    "Branch": "VILLA MARIA BRANCH",
    "Postcode": "X5900DTC",
    "Country": "Argentina",
    "Connection": "Active"
  },
  {
    "countryCode": "PAMP",
    "bankCode": "AR",
    "branchCode": "RBA",
    "SWIFT Code": "PAMPARBA",
    "Bank Name": "BANCO DE LA PAMPA S.E.M.",
    "Address": "RECONQUISTA 319, FLOOR 2",
    "City": "BUENOS AIRES",
    "Branch": "",
    "Postcode": "C1003ABG",
    "Country": "Argentina",
    "Connection": "Active"
  },
  {
    "countryCode": "PAMP",
    "bankCode": "AR",
    "branchCode": "200",
    "SWIFT Code": "PAMPARBA200",
    "Bank Name": "BANCO DE LA PAMPA S.E.M.",
    "Address": "CALLE 22 704",
    "City": "GENERAL PICO",
    "Branch": "",
    "Postcode": "L6360ABN",
    "Country": "Argentina",
    "Connection": "Active"
  },
  {
    "countryCode": "PAMP",
    "bankCode": "AR",
    "branchCode": "001",
    "SWIFT Code": "PAMPARBA001",
    "Bank Name": "BANCO DE LA PAMPA S.E.M.",
    "Address": "PELEGRINI 255",
    "City": "SANTA ROSA",
    "Branch": "",
    "Postcode": "L6300DRF",
    "Country": "Argentina",
    "Connection": "Active"
  },
  {
    "countryCode": "PRBA",
    "bankCode": "AR",
    "branchCode": "BAH",
    "SWIFT Code": "PRBAARBABAH",
    "Bank Name": "BANCO DE LA PROVINCIA DE BUENOS AIRES",
    "Address": "",
    "City": "BAHIA BLANCA",
    "Branch": "BAHIA BLANCA BRANCH",
    "Postcode": "",
    "Country": "Argentina",
    "Connection": "Active"
  },
  {
    "countryCode": "PRBA",
    "bankCode": "AR",
    "branchCode": "RBA",
    "SWIFT Code": "PRBAARBA",
    "Bank Name": "BANCO DE LA PROVINCIA DE BUENOS AIRES",
    "Address": "SAN MARTIN 137",
    "City": "BUENOS AIRES",
    "Branch": "",
    "Postcode": "C1004AAC",
    "Country": "Argentina",
    "Connection": "Active"
  },
  {
    "countryCode": "PRBA",
    "bankCode": "AR",
    "branchCode": "LPT",
    "SWIFT Code": "PRBAARBALPT",
    "Bank Name": "BANCO DE LA PROVINCIA DE BUENOS AIRES",
    "Address": "",
    "City": "LA PLATA",
    "Branch": "LA PLATA HOUSE",
    "Postcode": "",
    "Country": "Argentina",
    "Connection": "Active"
  },
  {
    "countryCode": "PRBA",
    "bankCode": "AR",
    "branchCode": "MP1",
    "SWIFT Code": "PRBAARBAMP1",
    "Bank Name": "BANCO DE LA PROVINCIA DE BUENOS AIRES",
    "Address": "SAN MARTIN 2563",
    "City": "MAR DEL PLATA",
    "Branch": "",
    "Postcode": "B7600GQI",
    "Country": "Argentina",
    "Connection": "Active"
  },
  {
    "countryCode": "CORD",
    "bankCode": "AR",
    "branchCode": "RBA",
    "SWIFT Code": "CORDARBA",
    "Bank Name": "BANCO DE LA PROVINCIA DE CORDOBA",
    "Address": "SAN JERONIMO 166, CASA MATRIZ",
    "City": "CORDOBA",
    "Branch": "",
    "Postcode": "X5000AGD",
    "Country": "Argentina",
    "Connection": "Active"
  },
  {
    "countryCode": "CORD",
    "bankCode": "AR",
    "branchCode": "COR",
    "SWIFT Code": "CORDARBACOR",
    "Bank Name": "BANCO DE LA PROVINCIA DE CORDOBA",
    "Address": "SAN GERONIMO 166",
    "City": "CORDOBA",
    "Branch": "GERENCIA DE COMERCIO EXTERIOR",
    "Postcode": "X5000AGD",
    "Country": "Argentina",
    "Connection": "Active"
  },
  {
    "countryCode": "BPNE",
    "bankCode": "AR",
    "branchCode": "RBA",
    "SWIFT Code": "BPNEARBA",
    "Bank Name": "BANCO DE LA PROVINCIA DEL NEUQUEN S.A.",
    "Address": "MAIPU 50",
    "City": "BUENOS AIRES",
    "Branch": "",
    "Postcode": "C1084ABB",
    "Country": "Argentina",
    "Connection": "Active"
  },
  {
    "countryCode": "BROU",
    "bankCode": "AR",
    "branchCode": "RBA",
    "SWIFT Code": "BROUARBA",
    "Bank Name": "BANCO DE LA REPUBLICA ORIENTAL DEL URUGUAY",
    "Address": "ESMERALDA 111",
    "City": "BUENOS AIRES",
    "Branch": "",
    "Postcode": "C1035ABC",
    "Country": "Argentina",
    "Connection": "Active"
  },
  {
    "countryCode": "BSJU",
    "bankCode": "AR",
    "branchCode": "RBJ",
    "SWIFT Code": "BSJUARBJ",
    "Bank Name": "BANCO DE SAN JUAN SA",
    "Address": "AV. JOSE IGNACIO DE LA ROZA 85, CASA MATRIZ",
    "City": "SAN JUAN",
    "Branch": "",
    "Postcode": "J5402DCA",
    "Country": "Argentina",
    "Connection": "Active"
  },
  {
    "countryCode": "BPSC",
    "bankCode": "AR",
    "branchCode": "RBA",
    "SWIFT Code": "BPSCARBA",
    "Bank Name": "BANCO DE SANTA CRUZ S A",
    "Address": "AV. PTE. DR. NESTOR C. KIRCHNER 812, CASA CENTRAL",
    "City": "RIO GALLEGOS",
    "Branch": "",
    "Postcode": "Z9400BAU",
    "Country": "Argentina",
    "Connection": "Active"
  },
  {
    "countryCode": "BSTI",
    "bankCode": "AR",
    "branchCode": "RBA",
    "SWIFT Code": "BSTIARBA",
    "Bank Name": "BANCO DE SERVICIOS Y TRANSACCIONES SA",
    "Address": "CORRIENTES 1174",
    "City": "BUENOS AIRES",
    "Branch": "",
    "Postcode": "C1043AAY",
    "Country": "Argentina",
    "Connection": "Active"
  },
  {
    "countryCode": "BAVA",
    "bankCode": "AR",
    "branchCode": "RBA",
    "SWIFT Code": "BAVAARBA",
    "Bank Name": "BANCO DE VALORES",
    "Address": "SARMIENTO 310",
    "City": "BUENOS AIRES",
    "Branch": "",
    "Postcode": "C1041AAH",
    "Country": "Argentina",
    "Connection": "Active"
  },
  {
    "countryCode": "BPCH",
    "bankCode": "AR",
    "branchCode": "RBA",
    "SWIFT Code": "BPCHARBA",
    "Bank Name": "BANCO DEL CHUBUT S.A.",
    "Address": "25 DE MAYO 273",
    "City": "BUENOS AIRES",
    "Branch": "",
    "Postcode": "C1002ABE",
    "Country": "Argentina",
    "Connection": "Active"
  },
  {
    "countryCode": "BHIP",
    "bankCode": "AR",
    "branchCode": "RBA",
    "SWIFT Code": "BHIPARBA",
    "Bank Name": "BANCO HIPOTECARIO S.A.",
    "Address": "RECONQUISTA 151, FLOOR 2",
    "City": "BUENOS AIRES",
    "Branch": "",
    "Postcode": "C1003ABC",
    "Country": "Argentina",
    "Connection": "Active"
  },
  {
    "countryCode": "NBIA",
    "bankCode": "AR",
    "branchCode": "RBA",
    "SWIFT Code": "NBIAARBA",
    "Bank Name": "BANCO INDUSTRIAL S.A.",
    "Address": "CAPITAL FEDERAL, SARMIENTO 530, CASA CENTRAL",
    "City": "BUENOS AIRES",
    "Branch": "",
    "Postcode": "C1041AAK",
    "Country": "Argentina",
    "Connection": "Active"
  },
  {
    "countryCode": "BJUL",
    "bankCode": "AR",
    "branchCode": "RBC",
    "SWIFT Code": "BJULARBC",
    "Bank Name": "BANCO JULIO SOCIEDAD ANONIMA",
    "Address": "SAN JERONIMO 135",
    "City": "CORDOBA",
    "Branch": "",
    "Postcode": "X5000AGC",
    "Country": "Argentina",
    "Connection": "Active"
  },
  {
    "countryCode": "BOSU",
    "bankCode": "AR",
    "branchCode": "RBA",
    "SWIFT Code": "BOSUARBA",
    "Bank Name": "BANCO MACRO S.A.",
    "Address": "SARMIENTO 447, FLOOR 7",
    "City": "BUENOS AIRES",
    "Branch": "",
    "Postcode": "C1041AAI",
    "Country": "Argentina",
    "Connection": "Active"
  },
  {
    "countryCode": "MARI",
    "bankCode": "AR",
    "branchCode": "RBA",
    "SWIFT Code": "MARIARBA",
    "Bank Name": "BANCO MARIVA S.A.",
    "Address": "SARMIENTO 500",
    "City": "BUENOS AIRES",
    "Branch": "",
    "Postcode": "C1041AAJ",
    "Country": "Argentina",
    "Connection": "Active"
  },
  {
    "countryCode": "BMRD",
    "bankCode": "AR",
    "branchCode": "RBA",
    "SWIFT Code": "BMRDARBA",
    "Bank Name": "BANCO MERIDIAN S.A.",
    "Address": "TUCUMAN, CAPITAL FEDERAL 821, CASA CENTRAL",
    "City": "BUENOS AIRES",
    "Branch": "",
    "Postcode": "C1049AAQ",
    "Country": "Argentina",
    "Connection": "Active"
  },
  {
    "countryCode": "MUNR",
    "bankCode": "AR",
    "branchCode": "RBR",
    "SWIFT Code": "MUNRARBR",
    "Bank Name": "BANCO MUNICIPAL DE ROSARIO",
    "Address": "SAN MARTIN 730",
    "City": "ROSARIO",
    "Branch": "",
    "Postcode": "2000",
    "Country": "Argentina",
    "Connection": "Active"
  },
  {
    "countryCode": "BSUD",
    "bankCode": "AR",
    "branchCode": "RBA",
    "SWIFT Code": "BSUDARBA",
    "Bank Name": "BANCO PATAGONIA S.A.",
    "Address": "AV. DE MAYO 701, FLOOR 24, EDIFICIO PATAGONIA",
    "City": "BUENOS AIRES",
    "Branch": "",
    "Postcode": "C1084AAC",
    "Country": "Argentina",
    "Connection": "Active"
  },
  {
    "countryCode": "BAPI",
    "bankCode": "AR",
    "branchCode": "RBA",
    "SWIFT Code": "BAPIARBA",
    "Bank Name": "BANCO PIANO S.A.",
    "Address": "SAN MARTIN 345-347",
    "City": "BUENOS AIRES",
    "Branch": "",
    "Postcode": "C1004AAG",
    "Country": "Argentina",
    "Connection": "Active"
  },
  {
    "countryCode": "TTFA",
    "bankCode": "AR",
    "branchCode": "RBA",
    "SWIFT Code": "TTFAARBA",
    "Bank Name": "BANCO PROVINCIA DE TIERRA DEL FUEGO",
    "Address": "MAIPU USHUAIA 897, TIERRA DEL FUEGO CP",
    "City": "BUENOS AIRES",
    "Branch": "",
    "Postcode": "V9410BJQ",
    "Country": "Argentina",
    "Connection": "Active"
  },
  {
    "countryCode": "BSAE",
    "bankCode": "AR",
    "branchCode": "RBA",
    "SWIFT Code": "BSAEARBA",
    "Bank Name": "BANCO SAENZ S.A.",
    "Address": "ESMERALDA 83",
    "City": "BUENOS AIRES",
    "Branch": "",
    "Postcode": "1035",
    "Country": "Argentina",
    "Connection": "Active"
  },
  {
    "countryCode": "BSCH",
    "bankCode": "AR",
    "branchCode": "RBA",
    "SWIFT Code": "BSCHARBA",
    "Bank Name": "BANCO SANTANDER ARGENTINA S.A.",
    "Address": "AV. JUAN DE GARAY 151",
    "City": "BUENOS AIRES",
    "Branch": "",
    "Postcode": "1063",
    "Country": "Argentina",
    "Connection": "Active"
  },
  {
    "countryCode": "BSCH",
    "bankCode": "AR",
    "branchCode": "SSS",
    "SWIFT Code": "BSCHARBASSS",
    "Bank Name": "BANCO SANTANDER ARGENTINA S.A.",
    "Address": "",
    "City": "BUENOS AIRES",
    "Branch": "SECURITIES SERVICES SYSTEM",
    "Postcode": "",
    "Country": "Argentina",
    "Connection": "Active"
  },
  {
    "countryCode": "BSUP",
    "bankCode": "AR",
    "branchCode": "RBA",
    "SWIFT Code": "BSUPARBA",
    "Bank Name": "BANCO SUPERVIELLE",
    "Address": "BARTOLOME MITRE 434",
    "City": "BUENOS AIRES",
    "Branch": "",
    "Postcode": "C1036AAH",
    "Country": "Argentina",
    "Connection": "Active"
  },
  {
    "countryCode": "BSUP",
    "bankCode": "AR",
    "branchCode": "EXT",
    "SWIFT Code": "BSUPARBAEXT",
    "Bank Name": "BANCO SUPERVIELLE",
    "Address": "",
    "City": "BUENOS AIRES",
    "Branch": "DTO. COMERCIO EXTERIOR",
    "Postcode": "",
    "Country": "Argentina",
    "Connection": "Active"
  },
  {
    "countryCode": "BSUP",
    "bankCode": "AR",
    "branchCode": "FIN",
    "SWIFT Code": "BSUPARBAFIN",
    "Bank Name": "BANCO SUPERVIELLE",
    "Address": "",
    "City": "BUENOS AIRES",
    "Branch": "DTO. OPERACIONES DE MERCADO",
    "Postcode": "",
    "Country": "Argentina",
    "Connection": "Active"
  },
  {
    "countryCode": "BSUP",
    "bankCode": "AR",
    "branchCode": "TIT",
    "SWIFT Code": "BSUPARBATIT",
    "Bank Name": "BANCO SUPERVIELLE",
    "Address": "",
    "City": "BUENOS AIRES",
    "Branch": "DTO. OPERACIONES DE TITULOS",
    "Postcode": "",
    "Country": "Argentina",
    "Connection": "Active"
  },
  {
    "countryCode": "BSUP",
    "bankCode": "AR",
    "branchCode": "DOC",
    "SWIFT Code": "BSUPARBADOC",
    "Bank Name": "BANCO SUPERVIELLE",
    "Address": "",
    "City": "BUENOS AIRES",
    "Branch": "OPERACIONES CENTRALIZADAS",
    "Postcode": "",
    "Country": "Argentina",
    "Connection": "Active"
  },
  {
    "countryCode": "VOIB",
    "bankCode": "AR",
    "branchCode": "RBA",
    "SWIFT Code": "VOIBARBA",
    "Bank Name": "BANCO VOII S.A.",
    "Address": "SARMIENTO 336",
    "City": "BUENOS AIRES",
    "Branch": "",
    "Postcode": "C1041AAH",
    "Country": "Argentina",
    "Connection": "Active"
  },
  {
    "countryCode": "BKCH",
    "bankCode": "AR",
    "branchCode": "RBA",
    "SWIFT Code": "BKCHARBA",
    "Bank Name": "BANK OF CHINA LIMITED SUCURSAL BUENOS AIRES",
    "Address": "JUANA MANSO 999, FLOOR 5",
    "City": "BUENOS AIRES",
    "Branch": "",
    "Postcode": "C1107CBS",
    "Country": "Argentina",
    "Connection": "Active"
  },
  {
    "countryCode": "BIIN",
    "bankCode": "AR",
    "branchCode": "RBA",
    "SWIFT Code": "BIINARBA",
    "Bank Name": "BIBANK S.A.",
    "Address": "BOUCHARD 547, FLOOR 24, TORRE BOUCHARD",
    "City": "BUENOS AIRES",
    "Branch": "",
    "Postcode": "C1106ABG",
    "Country": "Argentina",
    "Connection": "Active"
  },
  {
    "countryCode": "BNPA",
    "bankCode": "AR",
    "branchCode": "RBA",
    "SWIFT Code": "BNPAARBA",
    "Bank Name": "BNP PARIBAS - SUCCURSALE DE BUENOS AIRES",
    "Address": "BOUCHARD 547, FLOOR 26",
    "City": "BUENOS AIRES",
    "Branch": "",
    "Postcode": "C1002ABI",
    "Country": "Argentina",
    "Connection": "Active"
  },
  {
    "countryCode": "CAVL",
    "bankCode": "AR",
    "branchCode": "RBA",
    "SWIFT Code": "CAVLARBA",
    "Bank Name": "CAJA DE VALORES S.A.",
    "Address": "25 DE MAYO 362, CASA CENTRAL",
    "City": "BUENOS AIRES",
    "Branch": "",
    "Postcode": "C1002ABH",
    "Country": "Argentina",
    "Connection": "Active"
  },
  {
    "countryCode": "CITI",
    "bankCode": "AR",
    "branchCode": "RBA",
    "SWIFT Code": "CITIARBA",
    "Bank Name": "CITIBANK N.A.",
    "Address": "BARTOLOME MITRE 530, CASA CENTRAL",
    "City": "BUENOS AIRES",
    "Branch": "",
    "Postcode": "C1036AAJ",
    "Country": "Argentina",
    "Connection": "Active"
  },
  {
    "countryCode": "BACO",
    "bankCode": "AR",
    "branchCode": "RBA",
    "SWIFT Code": "BACOARBA",
    "Bank Name": "HSBC BANK ARGENTINA SA",
    "Address": "FLORIDA 201",
    "City": "BUENOS AIRES",
    "Branch": "",
    "Postcode": "C105AAE",
    "Country": "Argentina",
    "Connection": "Active"
  },
  {
    "countryCode": "BACO",
    "bankCode": "AR",
    "branchCode": "RCM",
    "SWIFT Code": "BACOARBARCM",
    "Bank Name": "HSBC BANK ARGENTINA SA",
    "Address": "",
    "City": "BUENOS AIRES",
    "Branch": "CAPITAL MARKETS DEPARTMENT",
    "Postcode": "",
    "Country": "Argentina",
    "Connection": "Active"
  },
  {
    "countryCode": "ICBK",
    "bankCode": "AR",
    "branchCode": "RBA",
    "SWIFT Code": "ICBKARBA",
    "Bank Name": "INDUSTRIAL AND COMMERCIAL BANK OF CHINA (ARGENTINA) S.A.U",
    "Address": "FLORIDA 99",
    "City": "BUENOS AIRES",
    "Branch": "",
    "Postcode": "C1005AAA",
    "Country": "Argentina",
    "Connection": "Active"
  },
  {
    "countryCode": "ICBK",
    "bankCode": "AR",
    "branchCode": "GCM",
    "SWIFT Code": "ICBKARBAGCM",
    "Bank Name": "INDUSTRIAL AND COMMERCIAL BANK OF CHINA (ARGENTINA) S.A.U",
    "Address": "",
    "City": "BUENOS AIRES",
    "Branch": "CASH MANAGEMENT",
    "Postcode": "",
    "Country": "Argentina",
    "Connection": "Active"
  },
  {
    "countryCode": "ICBK",
    "bankCode": "AR",
    "branchCode": "CLR",
    "SWIFT Code": "ICBKARBACLR",
    "Bank Name": "INDUSTRIAL AND COMMERCIAL BANK OF CHINA (ARGENTINA) S.A.U",
    "Address": "",
    "City": "BUENOS AIRES",
    "Branch": "CLEARING OFFICE",
    "Postcode": "",
    "Country": "Argentina",
    "Connection": "Active"
  },
  {
    "countryCode": "ICBK",
    "bankCode": "AR",
    "branchCode": "GCD",
    "SWIFT Code": "ICBKARBAGCD",
    "Bank Name": "INDUSTRIAL AND COMMERCIAL BANK OF CHINA (ARGENTINA) S.A.U",
    "Address": "",
    "City": "BUENOS AIRES",
    "Branch": "GLOBAL CUSTODY DEPARTMENT",
    "Postcode": "",
    "Country": "Argentina",
    "Connection": "Active"
  },
  {
    "countryCode": "CHAS",
    "bankCode": "AR",
    "branchCode": "RBA",
    "SWIFT Code": "CHASARBA",
    "Bank Name": "JPMORGAN CHASE BANK, N.A., BUENOS AIRES BRANCH",
    "Address": "MADERO EDUARDO AV 900, FLOOR 23",
    "City": "BUENOS AIRES",
    "Branch": "",
    "Postcode": "C1106ACV",
    "Country": "Argentina",
    "Connection": "Active"
  },
  {
    "countryCode": "MCFI",
    "bankCode": "AR",
    "branchCode": "RBM",
    "SWIFT Code": "MCFIARBM",
    "Bank Name": "MONTEMAR COMPANIA FINANCIERA S.A.",
    "Address": "SAN MARTIN 1152",
    "City": "MENDOZA",
    "Branch": "",
    "Postcode": "M5500 ECF",
    "Country": "Argentina",
    "Connection": "Active"
  },
  {
    "countryCode": "BERA",
    "bankCode": "AR",
    "branchCode": "RBA",
    "SWIFT Code": "BERAARBA",
    "Bank Name": "NUEVO BANCO DE ENTRE RIOS S.A.",
    "Address": "MONTE CASEROS 128",
    "City": "PARANA",
    "Branch": "",
    "Postcode": "E3100ACD",
    "Country": "Argentina",
    "Connection": "Active"
  },
  {
    "countryCode": "BPSF",
    "bankCode": "AR",
    "branchCode": "A86",
    "SWIFT Code": "BPSFARBAA86",
    "Bank Name": "NUEVO BANCO DE SANTA FE S.A.",
    "Address": "",
    "City": "RIO GALLEGOS",
    "Branch": "",
    "Postcode": "9400",
    "Country": "Argentina",
    "Connection": "Active"
  },
  {
    "countryCode": "BPSF",
    "bankCode": "AR",
    "branchCode": "000",
    "SWIFT Code": "BPSFARBA000",
    "Bank Name": "NUEVO BANCO DE SANTA FE S.A.",
    "Address": "",
    "City": "ROSARIO",
    "Branch": "",
    "Postcode": "",
    "Country": "Argentina",
    "Connection": "Active"
  },
  {
    "countryCode": "BPSF",
    "bankCode": "AR",
    "branchCode": "A45",
    "SWIFT Code": "BPSFARBAA45",
    "Bank Name": "NUEVO BANCO DE SANTA FE S.A.",
    "Address": "",
    "City": "SAN JUAN",
    "Branch": "",
    "Postcode": "",
    "Country": "Argentina",
    "Connection": "Active"
  },
  {
    "countryCode": "BPSF",
    "bankCode": "AR",
    "branchCode": "500",
    "SWIFT Code": "BPSFARBA500",
    "Bank Name": "NUEVO BANCO DE SANTA FE S.A.",
    "Address": "",
    "City": "SANTA FE",
    "Branch": "",
    "Postcode": "3000",
    "Country": "Argentina",
    "Connection": "Active"
  },
  {
    "countryCode": "BPSF",
    "bankCode": "AR",
    "branchCode": "RBA",
    "SWIFT Code": "BPSFARBA",
    "Bank Name": "NUEVO BANCO DE SANTA FE S.A.",
    "Address": "25 DE MAYO 2499",
    "City": "SANTA FE",
    "Branch": "",
    "Postcode": "S3000FTU",
    "Country": "Argentina",
    "Connection": "Active"
  },
  {
    "countryCode": "BACH",
    "bankCode": "AR",
    "branchCode": "RBA",
    "SWIFT Code": "BACHARBA",
    "Bank Name": "NUEVO BANCO DEL CHACO S.A.",
    "Address": "SARMIENTO 781",
    "City": "BUENOS AIRES",
    "Branch": "",
    "Postcode": "C1041AAO",
    "Country": "Argentina",
    "Connection": "Active"
  },
  {
    "countryCode": "MFCF",
    "bankCode": "AR",
    "branchCode": "RBA",
    "SWIFT Code": "MFCFARBA",
    "Bank Name": "REBA COMPANIA FINANCIERA",
    "Address": "CABA ZONA NORTA, MAIPU PB 272, CASA CENTRAL",
    "City": "BUENOS AIRES",
    "Branch": "",
    "Postcode": "1084",
    "Country": "Argentina",
    "Connection": "Active"
  }
]
module.exports = argentina
