const armenia = [
  {
    "countryCode": "AROJ",
    "bankCode": "AM",
    "branchCode": "M22",
    "SWIFT Code": "AROJAM22",
    "Bank Name": "'ARMBROK' OJSC",
    "Address": "HANRAPETUTYAN ST 39",
    "City": "YEREVAN",
    "Branch": "",
    "Postcode": "0010",
    "Country": "Armenia",
    "Connection": "Active"
  },
  {
    "countryCode": "CDAM",
    "bankCode": "AM",
    "branchCode": "M22",
    "SWIFT Code": "CDAMAM22",
    "Bank Name": "'CENTRAL DEPOSITORY OF ARMENIA' OJSC",
    "Address": "VAZGEN SARGSYAN STR. 26/1 EREBUNI, PLAZA BUSINESS CENTRE, FLOOR 5",
    "City": "YEREVAN",
    "Branch": "",
    "Postcode": "0010",
    "Country": "Armenia",
    "Connection": "Active"
  },
  {
    "countryCode": "FCAO",
    "bankCode": "AM",
    "branchCode": "M22",
    "SWIFT Code": "FCAOAM22",
    "Bank Name": "'FAST BANK' CJSC",
    "Address": "G. HOVSEPYAN STR 32/6, NORK-MARASH",
    "City": "YEREVAN",
    "Branch": "",
    "Postcode": "0047",
    "Country": "Armenia",
    "Connection": "Active"
  },
  {
    "countryCode": "ANIK",
    "bankCode": "AM",
    "branchCode": "M22",
    "SWIFT Code": "ANIKAM22",
    "Bank Name": "'ID BANK' CJSC",
    "Address": "VARDANANTS STREET 13",
    "City": "YEREVAN",
    "Branch": "",
    "Postcode": "0010",
    "Country": "Armenia",
    "Connection": "Active"
  },
  {
    "countryCode": "AGCA",
    "bankCode": "AM",
    "branchCode": "M22",
    "SWIFT Code": "AGCAAM22",
    "Bank Name": "ACBA BANK OJSC",
    "Address": "ARAMI STREET 82-84",
    "City": "YEREVAN",
    "Branch": "",
    "Postcode": "0002",
    "Country": "Armenia",
    "Connection": "Active"
  },
  {
    "countryCode": "ARMI",
    "bankCode": "AM",
    "branchCode": "M22",
    "SWIFT Code": "ARMIAM22",
    "Bank Name": "AMERIABANK (FORMERLY ARMIMPEXBANK)",
    "Address": "VAZGEN SARGSYAN STREET 2",
    "City": "YEREVAN",
    "Branch": "",
    "Postcode": "0010",
    "Country": "Armenia",
    "Connection": "Active"
  },
  {
    "countryCode": "ARMN",
    "bankCode": "AM",
    "branchCode": "M22",
    "SWIFT Code": "ARMNAM22",
    "Bank Name": "AMIO BANK",
    "Address": "NALBANDYAN ST 48",
    "City": "YEREVAN",
    "Branch": "",
    "Postcode": "0010",
    "Country": "Armenia",
    "Connection": "Active"
  },
  {
    "countryCode": "ARMC",
    "bankCode": "AM",
    "branchCode": "M22",
    "SWIFT Code": "ARMCAM22",
    "Bank Name": "ARARATBANK OJSC",
    "Address": "BUZAND STREET 87/85",
    "City": "YEREVAN",
    "Branch": "",
    "Postcode": "0002",
    "Country": "Armenia",
    "Connection": "Active"
  },
  {
    "countryCode": "ASHB",
    "bankCode": "AM",
    "branchCode": "M22",
    "SWIFT Code": "ASHBAM22",
    "Bank Name": "ARDSHINBANK CJSC",
    "Address": "GRIGOR LUSAVORICH 13",
    "City": "YEREVAN",
    "Branch": "",
    "Postcode": "0015",
    "Country": "Armenia",
    "Connection": "Active"
  },
  {
    "countryCode": "AREC",
    "bankCode": "AM",
    "branchCode": "M22",
    "SWIFT Code": "ARECAM22",
    "Bank Name": "ARMECONOMBANK",
    "Address": "AMIRYAN STREET 23/1",
    "City": "YEREVAN",
    "Branch": "",
    "Postcode": "0002",
    "Country": "Armenia",
    "Connection": "Active"
  },
  {
    "countryCode": "ARSJ",
    "bankCode": "AM",
    "branchCode": "M22",
    "SWIFT Code": "ARSJAM22",
    "Bank Name": "ARMSWISSBANK CJSC",
    "Address": "VAZGEN SARGSYAN 10",
    "City": "YEREVAN",
    "Branch": "",
    "Postcode": "0010",
    "Country": "Armenia",
    "Connection": "Active"
  },
  {
    "countryCode": "ARTS",
    "bankCode": "AM",
    "branchCode": "M22",
    "SWIFT Code": "ARTSAM22",
    "Bank Name": "ARTSAKHBANK CJSC",
    "Address": "CHARENTS STR 1B",
    "City": "YEREVAN",
    "Branch": "",
    "Postcode": "0025",
    "Country": "Armenia",
    "Connection": "Active"
  },
  {
    "countryCode": "BYBA",
    "bankCode": "AM",
    "branchCode": "M22",
    "SWIFT Code": "BYBAAM22",
    "Bank Name": "BYBLOS BANK ARMENIA CJSC",
    "Address": "AMIRYAN STREET 18/3",
    "City": "YEREVAN",
    "Branch": "",
    "Postcode": "0002",
    "Country": "Armenia",
    "Connection": "Active"
  },
  {
    "countryCode": "CBRA",
    "bankCode": "AM",
    "branchCode": "M22",
    "SWIFT Code": "CBRAAM22",
    "Bank Name": "CENTRAL BANK OF ARMENIA",
    "Address": "VAZGEN SARGSYAN STREET 6",
    "City": "YEREVAN",
    "Branch": "",
    "Postcode": "0010",
    "Country": "Armenia",
    "Connection": "Active"
  },
  {
    "countryCode": "COVB",
    "bankCode": "AM",
    "branchCode": "M22",
    "SWIFT Code": "COVBAM22",
    "Bank Name": "CONVERSE BANK CJSC",
    "Address": "VAZGEN SARGSYAN STREET 26/1",
    "City": "YEREVAN",
    "Branch": "",
    "Postcode": "0010",
    "Country": "Armenia",
    "Connection": "Active"
  },
  {
    "countryCode": "PRML",
    "bankCode": "AM",
    "branchCode": "M22",
    "SWIFT Code": "PRMLAM22",
    "Bank Name": "EVOCABANK CJSC",
    "Address": "HANRAPETUTYAN STR 44/2",
    "City": "YEREVAN",
    "Branch": "",
    "Postcode": "0010",
    "Country": "Armenia",
    "Connection": "Active"
  },
  {
    "countryCode": "MIDL",
    "bankCode": "AM",
    "branchCode": "M22",
    "SWIFT Code": "MIDLAM22",
    "Bank Name": "HSBC BANK ARMENIA CLOSED JOINT STOCK COMPANY",
    "Address": "AREA, PARONYAN STREET 42 90",
    "City": "YEREVAN",
    "Branch": "",
    "Postcode": "0015",
    "Country": "Armenia",
    "Connection": "Active"
  },
  {
    "countryCode": "INJS",
    "bankCode": "AM",
    "branchCode": "M22",
    "SWIFT Code": "INJSAM22",
    "Bank Name": "INECOBANK CJSC",
    "Address": "TUMANYAN STREET 17",
    "City": "YEREVAN",
    "Branch": "",
    "Postcode": "0001",
    "Country": "Armenia",
    "Connection": "Active"
  },
  {
    "countryCode": "UNIJ",
    "bankCode": "AM",
    "branchCode": "M22",
    "SWIFT Code": "UNIJAM22",
    "Bank Name": "UNIBANK O.J.S.C",
    "Address": "CHARENTS STREET 1-5, 53, BUILDING 12",
    "City": "YEREVAN",
    "Branch": "",
    "Postcode": "0025",
    "Country": "Armenia",
    "Connection": "Active"
  },
  {
    "countryCode": "ARMJ",
    "bankCode": "AM",
    "branchCode": "M22",
    "SWIFT Code": "ARMJAM22",
    "Bank Name": "VTB BANK (ARMENIA) CJSC",
    "Address": "MANANDYAN 33/3",
    "City": "YEREVAN",
    "Branch": "",
    "Postcode": "0006",
    "Country": "Armenia",
    "Connection": "Active"
  }
]
module.exports = armenia
