const bahamas = [
  {
    "countryCode": "ROYC",
    "bankCode": "BS",
    "branchCode": "MAI",
    "SWIFT Code": "ROYCBSNSMAI",
    "Bank Name": "RBC ROYAL BANK (BAHAMAS) LIMITED (FORMERLY KNOWN AS ROYAL BANK OF CANADA NASSAU)",
    "Address": "",
    "City": "NASSAU",
    "Branch": "MAIN BRANCH",
    "Postcode": "",
    "Country": "Bahamas",
    "Connection": "Active"
  },
  {},
  {
    "countryCode": "RFMB",
    "bankCode": "BS",
    "branchCode": "SNS",
    "SWIFT Code": "RFMBBSNS",
    "Bank Name": "RF BANK AND TRUST (BAHAMAS) LIMITED",
    "Address": "RF HOUSE, EAST HILL STREET",
    "City": "NASSAU",
    "Branch": "",
    "Postcode": "",
    "Country": "Bahamas",
    "Connection": "Active"
  },
  {
    "countryCode": "NOSC",
    "bankCode": "BS",
    "branchCode": "FPO",
    "SWIFT Code": "NOSCBSNSFPO",
    "Bank Name": "SCOTIABANK (BAHAMAS) LTD",
    "Address": "REGENT CENTRE, EXPLORERS WAY",
    "City": "FREEPORT",
    "Branch": "FREEPORT BRANCH",
    "Postcode": "",
    "Country": "Bahamas",
    "Connection": "Active"
  },
  {
    "countryCode": "NOSC",
    "bankCode": "BS",
    "branchCode": "SNS",
    "SWIFT Code": "NOSCBSNS",
    "Bank Name": "SCOTIABANK (BAHAMAS) LTD",
    "Address": "SCOTIABANK BUILDING, RAWSON SQUARE",
    "City": "NASSAU",
    "Branch": "",
    "Postcode": "",
    "Country": "Bahamas",
    "Connection": "Active"
  },
  {
    "countryCode": "NOSC",
    "bankCode": "BS",
    "branchCode": "TMK",
    "SWIFT Code": "NOSCBSNSTMK",
    "Bank Name": "SCOTIABANK (BAHAMAS) LTD",
    "Address": "TRADEWINDS BUILDING, BAY STREET",
    "City": "NASSAU",
    "Branch": "CARIBBEAN TREASURY UNIT",
    "Postcode": "",
    "Country": "Bahamas",
    "Connection": "Active"
  },
  {
    "countryCode": "STGT",
    "bankCode": "BS",
    "branchCode": "SNS",
    "SWIFT Code": "STGTBSNS",
    "Bank Name": "STERLING BANK AND TRUST LTD.",
    "Address": "SUITE 200, STERLING COMMONS WEST, 1 MARINA DRIVE, PARADISE ISLAND",
    "City": "NASSAU",
    "Branch": "",
    "Postcode": "",
    "Country": "Bahamas",
    "Connection": "Active"
  },
  {
    "countryCode": "TSWC",
    "bankCode": "BS",
    "branchCode": "SNS",
    "SWIFT Code": "TSWCBSNS",
    "Bank Name": "TEACHERS AND SALARIED WORKERS CO-OPERATIVE CREDIT UNION LIMITED",
    "Address": "TSWCCUL, INDEPENDANCE DRIVE, EAST STREET",
    "City": "NASSAU",
    "Branch": "HEAD OFFICE",
    "Postcode": "",
    "Country": "Bahamas",
    "Connection": "Active"
  },
  {
    "countryCode": "NFZB",
    "bankCode": "BS",
    "branchCode": "SNS",
    "SWIFT Code": "NFZBBSNS",
    "Bank Name": "UNION BANCAIRE PRIVEE, UBP SA",
    "Address": "FLOOR 5, LYFORD CAY HOUSE, WESTERN ROAD",
    "City": "NASSAU",
    "Branch": "",
    "Postcode": "",
    "Country": "Bahamas",
    "Connection": "Active"
  },
  {
    "countryCode": "NFZB",
    "bankCode": "BS",
    "branchCode": "FND",
    "SWIFT Code": "NFZBBSNSFND",
    "Bank Name": "UNION BANCAIRE PRIVEE, UBP SA",
    "Address": "FLOOR 5, LYFORD CAY HOUSE, WESTERN ROAD",
    "City": "NASSAU",
    "Branch": "FUND ADMINISTRATION DEPARTMENT",
    "Postcode": "",
    "Country": "Bahamas",
    "Connection": "Active"
  },
  {
    "countryCode": "USNA",
    "bankCode": "BS",
    "branchCode": "SN2",
    "SWIFT Code": "USNABSN2",
    "Bank Name": "USTS NASSAU, BAHAMAS LTD.",
    "Address": "SUITE 407-1, 191 SHIRLEY STREET / MOUNT ROYAL AV",
    "City": "NASSAU",
    "Branch": "",
    "Postcode": "",
    "Country": "Bahamas",
    "Connection": "Active"
  },
  {
    "countryCode": "WNTR",
    "bankCode": "BS",
    "branchCode": "SNS",
    "SWIFT Code": "WNTRBSNS",
    "Bank Name": "WINTERBOTHAM TRUST COMPANY LIMITED, THE",
    "Address": "WINTERBOTHAM PLACE, QUEEN STREETS, MARLBOROUGH",
    "City": "NASSAU",
    "Branch": "",
    "Postcode": "",
    "Country": "Bahamas",
    "Connection": "Active"
  },
  {
    "countryCode": "BBHM",
    "bankCode": "BS",
    "branchCode": "SNS",
    "SWIFT Code": "BBHMBSNS",
    "Bank Name": "BAC BAHAMAS",
    "Address": "FLOOR 2, NORFOLK HOUSE, FREDERICK STREET",
    "City": "NASSAU",
    "Branch": "",
    "Postcode": "",
    "Country": "Bahamas",
    "Connection": "Active"
  },
  {
    "countryCode": "BASE",
    "bankCode": "BS",
    "branchCode": "SNS",
    "SWIFT Code": "BASEBSNS",
    "Bank Name": "BANCA DEL SEMPIONE (OVERSEAS) LTD",
    "Address": "FLOOR 2, OLD FORT BAY TOWN CENTRE, BUILDING 2 WINDSOR FIELD ROAD",
    "City": "NASSAU",
    "Branch": "",
    "Postcode": "",
    "Country": "Bahamas",
    "Connection": "Active"
  },
  {
    "countryCode": "BBIN",
    "bankCode": "BS",
    "branchCode": "SNS",
    "SWIFT Code": "BBINBSNS",
    "Bank Name": "BANCO BOCOM BBM S.A.",
    "Address": "SHIRLEY HOUSE 2, 50 SHIRLEY STREET",
    "City": "NASSAU",
    "Branch": "",
    "Postcode": "",
    "Country": "Bahamas",
    "Connection": "Active"
  },
  {
    "countryCode": "SCHT",
    "bankCode": "BS",
    "branchCode": "SNS",
    "SWIFT Code": "SCHTBSNS",
    "Bank Name": "BANCO SANTANDER INTERNATIONAL SA BAHAMAS BRANCH",
    "Address": "FLOOR 1, THE CAVES CORPORATE, CENTRE A WEST BAY STREET AND BLAKE, ROAD",
    "City": "NASSAU",
    "Branch": "",
    "Postcode": "",
    "Country": "Bahamas",
    "Connection": "Active"
  },
  {
    "countryCode": "BAVO",
    "bankCode": "BS",
    "branchCode": "SNS",
    "SWIFT Code": "BAVOBSNS",
    "Bank Name": "BANCO VOTORANTIM S/A - NASSAU BRANCH",
    "Address": "SUITE 401, CENTRE OF COMMERCE, BUILDING 1 BAY STREET",
    "City": "NASSAU",
    "Branch": "",
    "Postcode": "",
    "Country": "Bahamas",
    "Connection": "Active"
  },
  {
    "countryCode": "BSAF",
    "bankCode": "BS",
    "branchCode": "SNS",
    "SWIFT Code": "BSAFBSNS",
    "Bank Name": "BANK J. SAFRA SARASIN (BAHAMAS) LTD.",
    "Address": "LYFORD FINANCIAL CENTRE, BUILDING 2, WESTERN ROAD",
    "City": "NASSAU",
    "Branch": "",
    "Postcode": "",
    "Country": "Bahamas",
    "Connection": "Active"
  },
  {
    "countryCode": "NOSC",
    "bankCode": "BS",
    "branchCode": "SNT",
    "SWIFT Code": "NOSCBSNT",
    "Bank Name": "BANK OF NOVA SCOTIA TRUST COMPANY (BAHAMAS) LTD,THE",
    "Address": "SCOTIA HOUSE, 404 EAST BAY STREET",
    "City": "NASSAU",
    "Branch": "",
    "Postcode": "",
    "Country": "Bahamas",
    "Connection": "Active"
  },
  {
    "countryCode": "BOTB",
    "bankCode": "BS",
    "branchCode": "0FR",
    "SWIFT Code": "BOTBBSNS0FR",
    "Bank Name": "BANK OF THE BAHAMAS LIMITED",
    "Address": "BANK LANE AND WOODSTOCK STREETS",
    "City": "FREEPORT",
    "Branch": "",
    "Postcode": "",
    "Country": "Bahamas",
    "Connection": "Active"
  },
  {
    "countryCode": "BOTB",
    "bankCode": "BS",
    "branchCode": "0N2",
    "SWIFT Code": "BOTBBSNS0N2",
    "Bank Name": "BANK OF THE BAHAMAS LIMITED",
    "Address": "MATTHEW TOWN",
    "City": "INAGUA",
    "Branch": "",
    "Postcode": "",
    "Country": "Bahamas",
    "Connection": "Active"
  },
  {
    "countryCode": "BOTB",
    "bankCode": "BS",
    "branchCode": "SNS",
    "SWIFT Code": "BOTBBSNS",
    "Bank Name": "BANK OF THE BAHAMAS LIMITED",
    "Address": "FLOOR 1, CLAUGHTON HOUSE, SHIRLEY AND CHARLOTTE STREETS",
    "City": "NASSAU",
    "Branch": "",
    "Postcode": "",
    "Country": "Bahamas",
    "Connection": "Active"
  },
  {
    "countryCode": "BOTB",
    "bankCode": "BS",
    "branchCode": "0N3",
    "SWIFT Code": "BOTBBSNS0N3",
    "Bank Name": "BANK OF THE BAHAMAS LIMITED",
    "Address": "EURO CANADIAN CENTRE",
    "City": "NASSAU",
    "Branch": "MAIN BRANCH",
    "Postcode": "",
    "Country": "Bahamas",
    "Connection": "Active"
  },
  {
    "countryCode": "BKPR",
    "bankCode": "BS",
    "branchCode": "SN2",
    "SWIFT Code": "BKPRBSN2",
    "Bank Name": "BANKPRO LIMITED",
    "Address": "LYFORD FINANCIAL CENTRE",
    "City": "NASSAU",
    "Branch": "",
    "Postcode": "",
    "Country": "Bahamas",
    "Connection": "Active"
  },
  {
    "countryCode": "BBIN",
    "bankCode": "BS",
    "branchCode": "SNX",
    "SWIFT Code": "BBINBSNX",
    "Bank Name": "BBM BANK LIMITED",
    "Address": "SHIRLEY HOUSE 2, 50 SHIRLEY STREET",
    "City": "NASSAU",
    "Branch": "",
    "Postcode": "",
    "Country": "Bahamas",
    "Connection": "Active"
  },
  {
    "countryCode": "AMRR",
    "bankCode": "BS",
    "branchCode": "SNS",
    "SWIFT Code": "AMRRBSNS",
    "Bank Name": "BRITANNIA BANK AND TRUST LTD.",
    "Address": "BUILDING 2, WEST BAY STREET, CAVES VILLAGE",
    "City": "NASSAU",
    "Branch": "",
    "Postcode": "",
    "Country": "Bahamas",
    "Connection": "Active"
  },
  {
    "countryCode": "ARUE",
    "bankCode": "BS",
    "branchCode": "SNS",
    "SWIFT Code": "ARUEBSNS",
    "Bank Name": "BRITANNIA SECURITIES LIMITED",
    "Address": "CAVES VILLAGE BUILDING 2, WEST BAY STREET",
    "City": "NASSAU",
    "Branch": "",
    "Postcode": "",
    "Country": "Bahamas",
    "Connection": "Active"
  },
  {
    "countryCode": "CUBL",
    "bankCode": "BS",
    "branchCode": "SNS",
    "SWIFT Code": "CUBLBSNS",
    "Bank Name": "CAPITAL UNION BANK LTD",
    "Address": "CUB FINANCIAL CENTER, LYFORD CAY",
    "City": "NASSAU",
    "Branch": "",
    "Postcode": "",
    "Country": "Bahamas",
    "Connection": "Active"
  },
  {
    "countryCode": "BSSA",
    "bankCode": "BS",
    "branchCode": "SNS",
    "SWIFT Code": "BSSABSNS",
    "Bank Name": "CBH (BAHAMAS) LTD.",
    "Address": "CBH HOUSE, EAST BAY STREET",
    "City": "NASSAU",
    "Branch": "",
    "Postcode": "",
    "Country": "Bahamas",
    "Connection": "Active"
  },
  {
    "countryCode": "CBBH",
    "bankCode": "BS",
    "branchCode": "SNS",
    "SWIFT Code": "CBBHBSNS",
    "Bank Name": "CENTRAL BANK OF THE BAHAMAS,THE",
    "Address": "FREDERICK STREET",
    "City": "NASSAU",
    "Branch": "",
    "Postcode": "",
    "Country": "Bahamas",
    "Connection": "Active"
  },
  {
    "countryCode": "CITI",
    "bankCode": "BS",
    "branchCode": "SNA",
    "SWIFT Code": "CITIBSNA",
    "Bank Name": "CITIBANK NA",
    "Address": "CITI BUILDING, 14 UNIVERSITY DRIVE",
    "City": "NASSAU",
    "Branch": "",
    "Postcode": "",
    "Country": "Bahamas",
    "Connection": "Active"
  },
  {
    "countryCode": "CITI",
    "bankCode": "BS",
    "branchCode": "TPS",
    "SWIFT Code": "CITIBSNATPS",
    "Bank Name": "CITIBANK NA",
    "Address": "",
    "City": "NASSAU",
    "Branch": "CITITRUST BAHAMAS THIRD PARTY STATEMENTS",
    "Postcode": "",
    "Country": "Bahamas",
    "Connection": "Active"
  },
  {
    "countryCode": "COMW",
    "bankCode": "BS",
    "branchCode": "SNS",
    "SWIFT Code": "COMWBSNS",
    "Bank Name": "COMMONWEALTH BANK LIMITED",
    "Address": "THE PLAZA, MACKEY STREET",
    "City": "NASSAU",
    "Branch": "",
    "Postcode": "",
    "Country": "Bahamas",
    "Connection": "Active"
  },
  {
    "countryCode": "CBLU",
    "bankCode": "BS",
    "branchCode": "SN2",
    "SWIFT Code": "CBLUBSN2",
    "Bank Name": "CORNER BANK (OVERSEAS) LIMITED",
    "Address": "FLOOR 5, LYFORD CAY HOUSE, WESTERN ROAD",
    "City": "NASSAU",
    "Branch": "",
    "Postcode": "",
    "Country": "Bahamas",
    "Connection": "Active"
  },
  {
    "countryCode": "CRES",
    "bankCode": "BS",
    "branchCode": "SNS",
    "SWIFT Code": "CRESBSNS",
    "Bank Name": "CREDIT SUISSE AG, NASSAU BRANCH",
    "Address": "FLOOR 4, THE BAHAMAS FINANCIAL, CENTRE SHIRLEY AND CHARLOTTE, STREETS NEW PROVIDENCE",
    "City": "NASSAU",
    "Branch": "NASSAU BRANCH",
    "Postcode": "",
    "Country": "Bahamas",
    "Connection": "Active"
  },
  {
    "countryCode": "GBLI",
    "bankCode": "BS",
    "branchCode": "SNX",
    "SWIFT Code": "GBLIBSNX",
    "Bank Name": "CREDIT SUISSE AG, NASSAU BRANCH, LATAM INVESTMENT BANKING",
    "Address": "FLOOR 4, THE BAHAMAS FINANCIAL, CENTRE SHIRLEY AND CHARLOTTE, STREETS",
    "City": "NASSAU",
    "Branch": "",
    "Postcode": "",
    "Country": "Bahamas",
    "Connection": "Active"
  },
  {
    "countryCode": "CRES",
    "bankCode": "BS",
    "branchCode": "NAS",
    "SWIFT Code": "CRESBSNSNAS",
    "Bank Name": "CREDIT SUISSE AG, NASSAU BRANCH, TREASURY AND ISSUANCE",
    "Address": "",
    "City": "NASSAU",
    "Branch": "NASSAU BRANCH",
    "Postcode": "",
    "Country": "Bahamas",
    "Connection": "Active"
  },
  {
    "countryCode": "CRES",
    "bankCode": "BS",
    "branchCode": "SNX",
    "SWIFT Code": "CRESBSNX",
    "Bank Name": "CREDIT SUISSE AG, NASSAU BRANCH, WEALTH MANAGEMENT",
    "Address": "FLOOR 4, BAHAMAS FINANCIAL CENTRE, SHIRLEY AND CHARLOTTE STREETS",
    "City": "NASSAU",
    "Branch": "",
    "Postcode": "",
    "Country": "Bahamas",
    "Connection": "Active"
  },
  {
    "countryCode": "BIGA",
    "bankCode": "BS",
    "branchCode": "ABT",
    "SWIFT Code": "BIGABSNSABT",
    "Bank Name": "CREDIT SUISSE BRAZIL (BAHAMAS) LIMITED",
    "Address": "",
    "City": "NASSAU",
    "Branch": "",
    "Postcode": "",
    "Country": "Bahamas",
    "Connection": "Active"
  },
  {
    "countryCode": "BIGA",
    "bankCode": "BS",
    "branchCode": "SNS",
    "SWIFT Code": "BIGABSNS",
    "Bank Name": "CREDIT SUISSE BRAZIL (BAHAMAS) LIMITED",
    "Address": "FLOOR 4, BAHAMAS FINANCIAL CENTRE, SHIRLEY AND CHARLOTTE STREETS",
    "City": "NASSAU",
    "Branch": "",
    "Postcode": "",
    "Country": "Bahamas",
    "Connection": "Active"
  },
  {
    "countryCode": "DBTL",
    "bankCode": "BS",
    "branchCode": "SNS",
    "SWIFT Code": "DBTLBSNS",
    "Bank Name": "DELTEC BANK AND TRUST LIMITED",
    "Address": "DELTEC HOUSE, LYFORD CAY",
    "City": "NASSAU",
    "Branch": "",
    "Postcode": "",
    "Country": "Bahamas",
    "Connection": "Active"
  },
  {
    "countryCode": "DBTL",
    "bankCode": "BS",
    "branchCode": "ECC",
    "SWIFT Code": "DBTLBSNSECC",
    "Bank Name": "DELTEC BANK AND TRUST LIMITED",
    "Address": "DELTEC HOUSE, LYFORD CAY",
    "City": "NASSAU",
    "Branch": "",
    "Postcode": "",
    "Country": "Bahamas",
    "Connection": "Active"
  },
  {
    "countryCode": "EFGB",
    "bankCode": "BS",
    "branchCode": "SNS",
    "SWIFT Code": "EFGBBSNS",
    "Bank Name": "EFG BANK AND TRUST (BAHAMAS) LTD",
    "Address": "FLOOR 3, GOODMAN S BAY CORPORATE, CENTRE WEST BAY STREET AND SEA VIEW, DRIVE",
    "City": "NASSAU",
    "Branch": "",
    "Postcode": "",
    "Country": "Bahamas",
    "Connection": "Active"
  },
  {
    "countryCode": "EQTT",
    "bankCode": "BS",
    "branchCode": "SNS",
    "SWIFT Code": "EQTTBSNS",
    "Bank Name": "EQUITY BANK BAHAMAS LIMITED",
    "Address": "EQUITY TRUST HOUSE, WEST BAY STREET",
    "City": "NASSAU",
    "Branch": "",
    "Postcode": "",
    "Country": "Bahamas",
    "Connection": "Active"
  },
  {
    "countryCode": "EUBO",
    "bankCode": "BS",
    "branchCode": "SNS",
    "SWIFT Code": "EUBOBSNS",
    "Bank Name": "EUROBANCO BANK LTD",
    "Address": "SUITE 5, CAVES PROFESSIONAL CENTRE, WEST BAY STREET, BLAKE ROAD",
    "City": "NASSAU",
    "Branch": "",
    "Postcode": "",
    "Country": "Bahamas",
    "Connection": "Active"
  },
  {
    "countryCode": "BTAM",
    "bankCode": "BS",
    "branchCode": "SNS",
    "SWIFT Code": "BTAMBSNS",
    "Bank Name": "FIDELITY BANK (BAHAMAS) LIMITED",
    "Address": "51 FREDERICK STREEET",
    "City": "NASSAU",
    "Branch": "",
    "Postcode": "",
    "Country": "Bahamas",
    "Connection": "Active"
  },
  {
    "countryCode": "FOBL",
    "bankCode": "BS",
    "branchCode": "SNS",
    "SWIFT Code": "FOBLBSNS",
    "Bank Name": "FIRST OVERSEAS BANK LIMITED",
    "Address": "OFFIC2, BUILDING 8, WEST BAY STREET, CAVES VILLAGE",
    "City": "NASSAU",
    "Branch": "",
    "Postcode": "",
    "Country": "Bahamas",
    "Connection": "Active"
  },
  {
    "countryCode": "FCIB",
    "bankCode": "BS",
    "branchCode": "SNS",
    "SWIFT Code": "FCIBBSNS",
    "Bank Name": "FIRSTCARIBBEAN INTERNATIONAL BANK (BAHAMAS) LIMITED",
    "Address": "FINANCIAL CENTRE, SHIRLEY STREET",
    "City": "NASSAU",
    "Branch": "",
    "Postcode": "",
    "Country": "Bahamas",
    "Connection": "Active"
  },
  {
    "countryCode": "CIBC",
    "bankCode": "BS",
    "branchCode": "SNB",
    "SWIFT Code": "CIBCBSNB",
    "Bank Name": "FIRSTCARIBBEAN INTERNATIONAL TRUST COMPANY (BAHAMAS) LIMITED",
    "Address": "FLOOR 1, GOODMAN'S BAY CORPORATE, CENTRE 309 WEST BAY STREET",
    "City": "NASSAU",
    "Branch": "",
    "Postcode": "",
    "Country": "Bahamas",
    "Connection": "Active"
  },
  {
    "countryCode": "GONE",
    "bankCode": "BS",
    "branchCode": "SNS",
    "SWIFT Code": "GONEBSNS",
    "Bank Name": "GONET BANK AND TRUST LIMITED",
    "Address": "PINEAPPLE HOUSE, 8 WESTERN ROAD",
    "City": "NASSAU",
    "Branch": "",
    "Postcode": "",
    "Country": "Bahamas",
    "Connection": "Active"
  },
  {
    "countryCode": "CBBA",
    "bankCode": "BS",
    "branchCode": "GCH",
    "SWIFT Code": "CBBABSNSGCH",
    "Bank Name": "ITAU UNIBANCO S.A. - NASSAU BRANCH (FORMERLY BANCO ITAU BBA S.A. - NASSAU BRANCH)",
    "Address": "FLOOR 2, ANNEX BUILDING, 31B EAST BAY STREET",
    "City": "NASSAU",
    "Branch": "",
    "Postcode": "",
    "Country": "Bahamas",
    "Connection": "Active"
  },
  {
    "countryCode": "CBBA",
    "bankCode": "BS",
    "branchCode": "SNS",
    "SWIFT Code": "CBBABSNS",
    "Bank Name": "ITAU UNIBANCO S.A. - NASSAU BRANCH (FORMERLY BANCO ITAU BBA S.A. - NASSAU BRANCH)",
    "Address": "FLOOR 2, ANNEX BUILDING, 31B EAST BAY STREET",
    "City": "NASSAU",
    "Branch": "",
    "Postcode": "",
    "Country": "Bahamas",
    "Connection": "Active"
  },
  {
    "countryCode": "CBBA",
    "bankCode": "BS",
    "branchCode": "BNF",
    "SWIFT Code": "CBBABSNSBNF",
    "Bank Name": "ITAU UNIBANCO S.A. - NASSAU BRANCH (FORMERLY BANCO ITAU BBA S.A. - NASSAU BRANCH)",
    "Address": "FLOOR 2, ANNEX BUILDING, 31B EAST BAY STREET",
    "City": "NASSAU",
    "Branch": "CASH CUSTOMERS TRANFS",
    "Postcode": "",
    "Country": "Bahamas",
    "Connection": "Active"
  },
  {
    "countryCode": "CBBA",
    "bankCode": "BS",
    "branchCode": "INM",
    "SWIFT Code": "CBBABSNSINM",
    "Bank Name": "ITAU UNIBANCO S.A. - NASSAU BRANCH (FORMERLY BANCO ITAU BBA S.A. - NASSAU BRANCH)",
    "Address": "FLOOR 2, ANNEX BUILDING, 31B EAST BAY STREET",
    "City": "NASSAU",
    "Branch": "INITIAL MARGIN ON OTC DERIVATIVES",
    "Postcode": "",
    "Country": "Bahamas",
    "Connection": "Active"
  },
  {
    "countryCode": "LOCY",
    "bankCode": "BS",
    "branchCode": "SNS",
    "SWIFT Code": "LOCYBSNS",
    "Bank Name": "LOMBARD ODIER AND CIE (BAHAMAS) LIMITED",
    "Address": "LYFORD CAY HOUSE, WESTERN ROAD",
    "City": "NASSAU",
    "Branch": "",
    "Postcode": "",
    "Country": "Bahamas",
    "Connection": "Active"
  },
  {
    "countryCode": "LOCY",
    "bankCode": "BS",
    "branchCode": "NDP",
    "SWIFT Code": "LOCYBSNSNDP",
    "Bank Name": "LOMBARD ODIER AND CIE (BAHAMAS) LIMITED",
    "Address": "",
    "City": "NASSAU",
    "Branch": "NDP DEPT",
    "Postcode": "",
    "Country": "Bahamas",
    "Connection": "Active"
  },
  {
    "countryCode": "MMGB",
    "bankCode": "BS",
    "branchCode": "SNS",
    "SWIFT Code": "MMGBBSNS",
    "Bank Name": "MMG BANK AND TRUST LTD.",
    "Address": "FLOOR 1, SUITE 102 , SAFFREY SQUARE, BAY STREET AND BANK LANE",
    "City": "NASSAU",
    "Branch": "",
    "Postcode": "",
    "Country": "Bahamas",
    "Connection": "Active"
  },
  {
    "countryCode": "PICT",
    "bankCode": "BS",
    "branchCode": "SNX",
    "SWIFT Code": "PICTBSNX",
    "Bank Name": "PICTET BANK AND TRUST LIMITED",
    "Address": "BAYSIDE EXECUTIVE PARK NO. 1 WEST, BAY STREET AND BLAKE ROAD",
    "City": "NASSAU",
    "Branch": "",
    "Postcode": "",
    "Country": "Bahamas",
    "Connection": "Active"
  },
  {
    "countryCode": "PICT",
    "bankCode": "BS",
    "branchCode": "COR",
    "SWIFT Code": "PICTBSNXCOR",
    "Bank Name": "PICTET BANK AND TRUST LIMITED",
    "Address": "BAYSIDE EXECUTIVE PARK NO. 1 WEST, BAY STREET AND BLAKE ROAD",
    "City": "NASSAU",
    "Branch": "CORPORATE ACTIONS",
    "Postcode": "",
    "Country": "Bahamas",
    "Connection": "Active"
  },
  {
    "countryCode": "ROYC",
    "bankCode": "BS",
    "branchCode": "FRE",
    "SWIFT Code": "ROYCBSNSFRE",
    "Bank Name": "RBC ROYAL BANK (BAHAMAS) LIMITED (FORMERLY KNOWN AS ROYAL BANK OF CANADA NASSAU)",
    "Address": "",
    "City": "FREEPORT",
    "Branch": "FREEPORT BRANCH",
    "Postcode": "",
    "Country": "Bahamas",
    "Connection": "Active"
  },
  {
    "countryCode": "ROYC",
    "bankCode": "BS",
    "branchCode": "SNS",
    "SWIFT Code": "ROYCBSNS",
    "Bank Name": "RBC ROYAL BANK (BAHAMAS) LIMITED (FORMERLY KNOWN AS ROYAL BANK OF CANADA NASSAU)",
    "Address": "FLOOR 2, ROYAL BANK HOUSE, EAST HILL STREET",
    "City": "NASSAU",
    "Branch": "ALL OFFICES",
    "Postcode": "",
    "Country": "Bahamas",
    "Connection": "Active"
  },
  {
    "countryCode": "ROYC",
    "bankCode": "BS",
    "branchCode": "OPC",
    "SWIFT Code": "ROYCBSNSOPC",
    "Bank Name": "RBC ROYAL BANK (BAHAMAS) LIMITED (FORMERLY KNOWN AS ROYAL BANK OF CANADA NASSAU)",
    "Address": "",
    "City": "NASSAU",
    "Branch": "HEAD OFFICE OPERATIONS CENTRE",
    "Postcode": "",
    "Country": "Bahamas",
    "Connection": "Active"
  }
]
module.exports = bahamas
