const bahrain = [
  {
    "countryCode": "BBKU",
    "bankCode": "BH",
    "branchCode": "MNM",
    "SWIFT Code": "BBKUBHBMMNM",
    "Bank Name": "BBK",
    "Address": "",
    "City": "MANAMA",
    "Branch": "MANAMA BRANCH",
    "Postcode": "323",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "BBKU",
    "bankCode": "BH",
    "branchCode": "MHF",
    "SWIFT Code": "BBKUBHBMMHF",
    "Bank Name": "BBK",
    "Address": "",
    "City": "MANAMA",
    "Branch": "MUHARRAQ BRANCH",
    "Postcode": "323",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "BBKU",
    "bankCode": "BH",
    "branchCode": "MSF",
    "SWIFT Code": "BBKUBHBMMSF",
    "Bank Name": "BBK",
    "Address": "",
    "City": "MANAMA",
    "Branch": "MUHARRAQ SUQ BRANCH",
    "Postcode": "323",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "BBKU",
    "bankCode": "BH",
    "branchCode": "REC",
    "SWIFT Code": "BBKUBHBMREC",
    "Bank Name": "BBK",
    "Address": "",
    "City": "MANAMA",
    "Branch": "RECONCILIATION",
    "Postcode": "323",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "BBKU",
    "bankCode": "BH",
    "branchCode": "REF",
    "SWIFT Code": "BBKUBHBMREF",
    "Bank Name": "BBK",
    "Address": "",
    "City": "MANAMA",
    "Branch": "REFINERY BRANCH",
    "Postcode": "323",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {},
  {
    "countryCode": "BBKU",
    "bankCode": "BH",
    "branchCode": "SAL",
    "SWIFT Code": "BBKUBHBMSAL",
    "Bank Name": "BBK",
    "Address": "",
    "City": "MANAMA",
    "Branch": "SALARIES DEPARTMENT",
    "Postcode": "323",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "BBKU",
    "bankCode": "BH",
    "branchCode": "SUW",
    "SWIFT Code": "BBKUBHBMSUW",
    "Bank Name": "BBK",
    "Address": "",
    "City": "MANAMA",
    "Branch": "SUQ WAQIF BRANCH",
    "Postcode": "323",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "BBKU",
    "bankCode": "BH",
    "branchCode": "TSU",
    "SWIFT Code": "BBKUBHBMTSU",
    "Bank Name": "BBK",
    "Address": "",
    "City": "MANAMA",
    "Branch": "TREASURY SERVICES UNIT",
    "Postcode": "323",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "BBKU",
    "bankCode": "BH",
    "branchCode": "WRF",
    "SWIFT Code": "BBKUBHBMWRF",
    "Bank Name": "BBK",
    "Address": "",
    "City": "WEST RIFFA",
    "Branch": "WEST RIFFA BRANCH",
    "Postcode": "",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "BNPA",
    "bankCode": "BH",
    "branchCode": "HBC",
    "SWIFT Code": "BNPABHBC",
    "Bank Name": "BNP PARIBAS BAHRAIN CONVENTIONAL RETAIL BANK",
    "Address": "WEST TOWER, KING FAISAL HIGHWAY, BAHRAIN FINANCIAL HARBOUR",
    "City": "MANAMA",
    "Branch": "",
    "Postcode": "209",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "BNPA",
    "bankCode": "BH",
    "branchCode": "HBM",
    "SWIFT Code": "BNPABHBM",
    "Bank Name": "BNP PARIBAS BAHRAIN CONVENTIONAL WHOLESALE BANK",
    "Address": "UGB TOWER, BUILDING 440, BL, ROAD 1705, DIPLOMATIC AREA",
    "City": "MANAMA",
    "Branch": "",
    "Postcode": "323",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "BNPA",
    "bankCode": "BH",
    "branchCode": "WMI",
    "SWIFT Code": "BNPABHBMWMI",
    "Bank Name": "BNP PARIBAS BAHRAIN CONVENTIONAL WHOLESALE BANK",
    "Address": "",
    "City": "MANAMA",
    "Branch": "MANAMA OFFSHORE BANKING UNIT(OBU)",
    "Postcode": "323",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "BOKN",
    "bankCode": "BH",
    "branchCode": "HBM",
    "SWIFT Code": "BOKNBHBM",
    "Bank Name": "BOK INTERNATIONAL",
    "Address": "FLOOR 5, ALUBAF TOWER BUILDING 854, ROAD 3618, AL SEEF",
    "City": "MANAMA",
    "Branch": "",
    "Postcode": "436",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "CAAB",
    "bankCode": "BH",
    "branchCode": "HBM",
    "SWIFT Code": "CAABBHBM",
    "Bank Name": "CAIRO AMMAN BANK",
    "Address": "OFFICE 112, FLOOR 11, BUILDING 470, ROAD 1010",
    "City": "MANAMA",
    "Branch": "",
    "Postcode": "710",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "BMAG",
    "bankCode": "BH",
    "branchCode": "HBM",
    "SWIFT Code": "BMAGBHBM",
    "Bank Name": "CENTRAL BANK OF BAHRAIN",
    "Address": "BUILDING 96, ROAD 1702",
    "City": "MANAMA",
    "Branch": "",
    "Postcode": "317",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {},
  {
    "countryCode": "CITI",
    "bankCode": "BH",
    "branchCode": "BBU",
    "SWIFT Code": "CITIBHBXBBU",
    "Bank Name": "CITIBANK N.A.",
    "Address": "",
    "City": "MANAMA",
    "Branch": "BAHRAIN OFFSHORE UNIT",
    "Postcode": "323",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "CITI",
    "bankCode": "BH",
    "branchCode": "TRD",
    "SWIFT Code": "CITIBHBXTRD",
    "Bank Name": "CITIBANK N.A.",
    "Address": "",
    "City": "MANAMA",
    "Branch": "TRADE",
    "Postcode": "323",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "DENI",
    "bankCode": "BH",
    "branchCode": "HBX",
    "SWIFT Code": "DENIBHBX",
    "Bank Name": "DENIZBANK AS BAHRAIN BRANCH (OBU)",
    "Address": "OFFICE 62/6, FLOOR 6, AL JASRAH, TOWER, BUILDING 95 ROAD 1702, DIPLOMATIC AREA AREA 317",
    "City": "MANAMA",
    "Branch": "",
    "Postcode": "323",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "ESKB",
    "bankCode": "BH",
    "branchCode": "HBM",
    "SWIFT Code": "ESKBBHBM",
    "Bank Name": "ESKAN BANK",
    "Address": "ALMOAYYED TOWER, SEEF DISTRICT",
    "City": "MANAMA",
    "Branch": "",
    "Postcode": "323",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "FNNB",
    "bankCode": "BH",
    "branchCode": "HBM",
    "SWIFT Code": "FNNBBHBM",
    "Bank Name": "FINANSBANK A.S. BAHRAIN BRANCH",
    "Address": "BLOCK 315, FLAT 51, BUILDING 150, 383 GOVERNMENT AVE ROAD",
    "City": "MANAMA",
    "Branch": "",
    "Postcode": "323",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "NBAD",
    "bankCode": "BH",
    "branchCode": "HBM",
    "SWIFT Code": "NBADBHBM",
    "Bank Name": "FIRST ABU DHABI BANK PJSC (FORMERLY NATIONAL BANK OF ABU DHABI) BAHRAIN",
    "Address": "BLOCK 317, UNIT 1601, FLOOR 10,, BUILDING 1565 ROAD 1722 DIPLOMATIC, AREA",
    "City": "MANAMA",
    "Branch": "",
    "Postcode": "317",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "NBAD",
    "bankCode": "BH",
    "branchCode": "BRA",
    "SWIFT Code": "NBADBHBMBRA",
    "Bank Name": "FIRST ABU DHABI BANK PJSC (FORMERLY NATIONAL BANK OF ABU DHABI) BAHRAIN",
    "Address": "428, BUILDING NO.2611, ROAD NO. 2833, AL SEEF DISTRICT",
    "City": "MANAMA",
    "Branch": "BAHRAIN BRANCH",
    "Postcode": "323",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "NBAD",
    "bankCode": "BH",
    "branchCode": "TFO",
    "SWIFT Code": "NBADBHBMTFO",
    "Bank Name": "FIRST ABU DHABI BANK PJSC (FORMERLY NATIONAL BANK OF ABU DHABI) BAHRAIN",
    "Address": "",
    "City": "MANAMA",
    "Branch": "TRADE FINANCE DEPARTMENT",
    "Postcode": "323",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "GFHI",
    "bankCode": "BH",
    "branchCode": "HBM",
    "SWIFT Code": "GFHIBHBM",
    "Bank Name": "GFH FINANCIAL GROUP B.S.C.",
    "Address": "FLOOR 29, EAST TOWER, BARHAIN FINANCIAL HARBOUR",
    "City": "MANAMA",
    "Branch": "",
    "Postcode": "209",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "GULF",
    "bankCode": "BH",
    "branchCode": "CLS",
    "SWIFT Code": "GULFBHBMCLS",
    "Bank Name": "GULF INTERNATIONAL BANK, B.S.C.",
    "Address": "AL-DOWALI BUILDING, 3 PALACE AVENUE",
    "City": "MANAMA",
    "Branch": "",
    "Postcode": "317",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "GULF",
    "bankCode": "BH",
    "branchCode": "HBM",
    "SWIFT Code": "GULFBHBM",
    "Bank Name": "GULF INTERNATIONAL BANK, B.S.C.",
    "Address": "AL-DOWALI BUILDING, 3 PALACE AVENUE",
    "City": "MANAMA",
    "Branch": "",
    "Postcode": "317",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "GULF",
    "bankCode": "BH",
    "branchCode": "RET",
    "SWIFT Code": "GULFBHBMRET",
    "Bank Name": "GULF INTERNATIONAL BANK, B.S.C.",
    "Address": "AL-DOWALI BUILDING, 3 PALACE AVENUE",
    "City": "MANAMA",
    "Branch": "BAHRAIN RETAIL BANKING",
    "Postcode": "317",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "HABB",
    "bankCode": "BH",
    "branchCode": "HBM",
    "SWIFT Code": "HABBBHBM",
    "Bank Name": "HABIB BANK LTD.",
    "Address": "BLOCK 215, BUILDING 1130, ROAD 10",
    "City": "MANAMA",
    "Branch": "",
    "Postcode": "323",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "HABB",
    "bankCode": "BH",
    "branchCode": "OBU",
    "SWIFT Code": "HABBBHBMOBU",
    "Bank Name": "HABIB BANK LTD.",
    "Address": "BABUL BAHRAIN BLDG, GOVERNMENT ROAD",
    "City": "MANAMA",
    "Branch": "OFFSHORE BANKING UNIT",
    "Postcode": "323",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "HDFC",
    "bankCode": "BH",
    "branchCode": "HBM",
    "SWIFT Code": "HDFCBHBM",
    "Bank Name": "HDFC BANK LIMITED",
    "Address": "FLAT 2224, BLOCK 346, BUILDING 1459, ROAD 4626, BAHRAIN FINANCIAL HARBOR",
    "City": "MANAMA",
    "Branch": "",
    "Postcode": "209",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "HDFC",
    "bankCode": "BH",
    "branchCode": "WMS",
    "SWIFT Code": "HDFCBHBMWMS",
    "Bank Name": "HDFC BANK LIMITED",
    "Address": "FLAT 2224, BUILDING 1459, 4626 BAHRAIN FINANCIAL HARBOR, ROAD",
    "City": "MANAMA",
    "Branch": "BAHRAIN BRANCH- CUSTODY BUSINESS",
    "Postcode": "323",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "HBHO",
    "bankCode": "BH",
    "branchCode": "HBM",
    "SWIFT Code": "HBHOBHBM",
    "Bank Name": "HOUSING BANK FOR TRADE AND FINANCE / BAHRAIN, MANAMA, THE",
    "Address": "MANAMA CENTRE, GOVERMENT AVENUE",
    "City": "MANAMA",
    "Branch": "",
    "Postcode": "323",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "BBME",
    "bankCode": "BH",
    "branchCode": "HBX",
    "SWIFT Code": "BBMEBHBX",
    "Bank Name": "HSBC BANK MIDDLE EAST LIMITED",
    "Address": "ROAD 2832, BUILDING 2505, AL SEEF 428, PLOT 5780",
    "City": "MANAMA",
    "Branch": "",
    "Postcode": "323",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {},
  {
    "countryCode": "ICIC",
    "bankCode": "BH",
    "branchCode": "HBM",
    "SWIFT Code": "ICICBHBM",
    "Bank Name": "ICICI BANK LTD",
    "Address": "MANAMA CENTRE BUILDING NO. 116, 383 GOVERNMENT AVENUE, ROAD",
    "City": "MANAMA",
    "Branch": "",
    "Postcode": "316",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "ICIC",
    "bankCode": "BH",
    "branchCode": "IPB",
    "SWIFT Code": "ICICBHBMIPB",
    "Bank Name": "ICICI BANK LTD",
    "Address": "MANAMA CENTRE BUILDING NO. 116, 383 GOVERNMENT AVENUE, ROAD",
    "City": "MANAMA",
    "Branch": "",
    "Postcode": "316",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "ICIC",
    "bankCode": "BH",
    "branchCode": "COP",
    "SWIFT Code": "ICICBHBMCOP",
    "Bank Name": "ICICI BANK LTD",
    "Address": "",
    "City": "MANAMA",
    "Branch": "CENTRAL OPERATIONS",
    "Postcode": "323",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "ICIC",
    "bankCode": "BH",
    "branchCode": "GTS",
    "SWIFT Code": "ICICBHBMGTS",
    "Bank Name": "ICICI BANK LTD",
    "Address": "BUILDING 114, 316 GOVERNMENT AVENUE, MUNICIPALITY 116",
    "City": "MANAMA",
    "Branch": "GLOBAL TRADE SERVICE UNIT",
    "Postcode": "323",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "ICIC",
    "bankCode": "BH",
    "branchCode": "IOG",
    "SWIFT Code": "ICICBHBMIOG",
    "Bank Name": "ICICI BANK LTD",
    "Address": "BUILDING 114, 316 GOVERNMENT AVENUE, MUNICIPALITY 116",
    "City": "MANAMA",
    "Branch": "IIOG",
    "Postcode": "323",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "ICIC",
    "bankCode": "BH",
    "branchCode": "TMG",
    "SWIFT Code": "ICICBHBMTMG",
    "Bank Name": "ICICI BANK LTD",
    "Address": "BUILDING 114, 316 GOVERNMENT AVENUE, MUNICIPALITY 116",
    "City": "MANAMA",
    "Branch": "TREASURY",
    "Postcode": "323",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "IPSC",
    "bankCode": "BH",
    "branchCode": "HBM",
    "SWIFT Code": "IPSCBHBM",
    "Bank Name": "INTERNATIONAL PAYMENT SERVICES",
    "Address": "BLOCK 428, FLOOR 7, BNH TOWER 2832, 2491",
    "City": "MANAMA",
    "Branch": "",
    "Postcode": "323",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "INVC",
    "bankCode": "BH",
    "branchCode": "HBM",
    "SWIFT Code": "INVCBHBM",
    "Bank Name": "INVESTCORP HOLDINGS B.S.C (CLOSED)",
    "Address": "INVESTCORP HSE BLDG 499, BLOCK 317, ROAD 1706, DIPLOMATIC AREA",
    "City": "MANAMA",
    "Branch": "",
    "Postcode": "317",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "FIBH",
    "bankCode": "BH",
    "branchCode": "HBM",
    "SWIFT Code": "FIBHBHBM",
    "Bank Name": "ITHMAAR BANK B.S.C. (C)",
    "Address": "ADDAX TOWER, SEEF DISTRICT",
    "City": "MANAMA",
    "Branch": "",
    "Postcode": "428",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "JSBL",
    "bankCode": "BH",
    "branchCode": "HBM",
    "SWIFT Code": "JSBLBHBM",
    "Bank Name": "JS BANK LIMITED",
    "Address": "UNIT 45 (B), WEST TOWER, BLOCK 346, 4686 45 ROAD",
    "City": "MANAMA",
    "Branch": "",
    "Postcode": "323",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "KOEX",
    "bankCode": "BH",
    "branchCode": "HBM",
    "SWIFT Code": "KOEXBHBM",
    "Bank Name": "KEB HANA BANK BAHRAIN BRANCH",
    "Address": "BLOCK 304, YATEEM CENTRE BUILDING, ROAD 341",
    "City": "MANAMA",
    "Branch": "",
    "Postcode": "323",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "KHCB",
    "bankCode": "BH",
    "branchCode": "HBM",
    "SWIFT Code": "KHCBBHBM",
    "Bank Name": "KHALEEJI BANK B.S.C.",
    "Address": "BUILDING 1411 BLOCK 346, 4626 ROAD",
    "City": "MANAMA",
    "Branch": "",
    "Postcode": "305",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "KFHO",
    "bankCode": "BH",
    "branchCode": "HBM",
    "SWIFT Code": "KFHOBHBM",
    "Bank Name": "KUWAIT FINANCE HOUSE",
    "Address": "BAHRAIN WTC WEST TOWER",
    "City": "MANAMA",
    "Branch": "",
    "Postcode": "323",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "KTEF",
    "bankCode": "BH",
    "branchCode": "HBM",
    "SWIFT Code": "KTEFBHBM",
    "Bank Name": "KUWAIT TURKISH PARTICIPATION BANK INC. BAHRAIN BRANCH",
    "Address": "OFFICE 1003, FLOOR 10, WEST TOWER, BUILDING 1459 4626 BAHRAIN, FINANCIAL HARBOUR, KING FAISAL, HIGHWAY ROAD",
    "City": "MANAMA",
    "Branch": "",
    "Postcode": "346",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "ABCI",
    "bankCode": "BH",
    "branchCode": "HBM",
    "SWIFT Code": "ABCIBHBM",
    "Bank Name": "ABC ISLAMIC BANK (E.C)",
    "Address": "BLOCK 317, FLOOR 2, ABC TOWER, 152 ROAD 1703, DIPLOMATIC AREA",
    "City": "MANAMA",
    "Branch": "",
    "Postcode": "317",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "AUBB",
    "bankCode": "BH",
    "branchCode": "HBB",
    "SWIFT Code": "AUBBBHBB",
    "Bank Name": "AHLI UNITED BANK (BAHRAIN) B.S.C. (CLOSED)",
    "Address": "BLOCK 428, OFFICE 21, BUILDING NO, 2495 ROAD NO 2832 AL SEEF",
    "City": "MANAMA",
    "Branch": "",
    "Postcode": "323",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "AUBB",
    "bankCode": "BH",
    "branchCode": "HBM",
    "SWIFT Code": "AUBBBHBM",
    "Bank Name": "AHLI UNITED BANK B.S.C.",
    "Address": "",
    "City": "MANAMA",
    "Branch": "",
    "Postcode": "323",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "AUBB",
    "bankCode": "BH",
    "branchCode": "ISB",
    "SWIFT Code": "AUBBBHBMISB",
    "Bank Name": "AHLI UNITED BANK B.S.C.",
    "Address": "2495 2832 ROAD, SEEF DISTRICT",
    "City": "MANAMA",
    "Branch": "ALHILAL ISLAMIC BANKING SERVICES",
    "Postcode": "323",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "ABIB",
    "bankCode": "BH",
    "branchCode": "HBM",
    "SWIFT Code": "ABIBBHBM",
    "Bank Name": "AL BARAKA ISLAMIC BANK B.S.C CLOSED",
    "Address": "BLOCK 346, ABG TOWER 4611 MANAMA, SEA FRONT (BAHRAIN BAY) 370 ROAD",
    "City": "MANAMA",
    "Branch": "",
    "Postcode": "323",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "ABIB",
    "bankCode": "BH",
    "branchCode": "TBO",
    "SWIFT Code": "ABIBBHBMTBO",
    "Bank Name": "AL BARAKA ISLAMIC BANK B.S.C CLOSED",
    "Address": "ALBARAKA TOWER, DIPLOMATIC AREA",
    "City": "MANAMA",
    "Branch": "HEAD OFFICE",
    "Postcode": "323",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "ABIB",
    "bankCode": "BH",
    "branchCode": "PMT",
    "SWIFT Code": "ABIBBHBMPMT",
    "Bank Name": "AL BARAKA ISLAMIC BANK B.S.C CLOSED",
    "Address": "ALBARAKA TOWER, DIPLOMATIC AREA",
    "City": "MANAMA",
    "Branch": "HEAD OFFICE",
    "Postcode": "323",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "ABIB",
    "bankCode": "BH",
    "branchCode": "FCR",
    "SWIFT Code": "ABIBBHBMFCR",
    "Bank Name": "AL BARAKA ISLAMIC BANK B.S.C CLOSED",
    "Address": "ALBARAKA TOWER, DIPLOMATIC AREA",
    "City": "MANAMA",
    "Branch": "HEAD OFFICE",
    "Postcode": "323",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "ABIB",
    "bankCode": "BH",
    "branchCode": "TRF",
    "SWIFT Code": "ABIBBHBMTRF",
    "Bank Name": "AL BARAKA ISLAMIC BANK B.S.C CLOSED",
    "Address": "ALBARAKA TOWER, DIPLOMATIC AREA",
    "City": "MANAMA",
    "Branch": "TRADE FINANCE OPERATIONS - HEAD OFFICE",
    "Postcode": "323",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "ALSA",
    "bankCode": "BH",
    "branchCode": "HBM",
    "SWIFT Code": "ALSABHBM",
    "Bank Name": "AL SALAM BANK BAHRAIN",
    "Address": "BUILDING NO. 935, STREET NO. 1015, DIPLOMATIC AREA",
    "City": "SANABIS",
    "Branch": "HEAD OFFICE",
    "Postcode": "410",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "ABBG",
    "bankCode": "BH",
    "branchCode": "HBM",
    "SWIFT Code": "ABBGBHBM",
    "Bank Name": "ALBARAKA GROUP",
    "Address": "BLOCK 346, FLOOR 7, ABG TOWER 4611, MANAMA SEA FRONT (BAHRAIN BAY) 370, ROAD",
    "City": "MANAMA",
    "Branch": "",
    "Postcode": "323",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "ABLW",
    "bankCode": "BH",
    "branchCode": "HBM",
    "SWIFT Code": "ABLWBHBM",
    "Bank Name": "ALLIED BANK LIMITED, WHOLESALE BANKING BRANCH",
    "Address": "OFFICE NO. 1001, BLOCK NO. 3,, FLOOR 10, HARBOUR TOWER WEST, BUILDING NO.1459 4626 BAHRAIN, FINANCIAL HARBOUR",
    "City": "MANAMA",
    "Branch": "",
    "Postcode": "209",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "ALUB",
    "bankCode": "BH",
    "branchCode": "HBM",
    "SWIFT Code": "ALUBBHBM",
    "Bank Name": "ALUBAF ARAB INTERNATIONAL BANK B.S.C. (C)",
    "Address": "BLOCK 436, FLOOR 8, ALUBAF TOWER, 3618 854 ROAD, AL SEEF",
    "City": "MANAMA",
    "Branch": "",
    "Postcode": "436",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "ARAB",
    "bankCode": "BH",
    "branchCode": "HBM",
    "SWIFT Code": "ARABBHBM",
    "Bank Name": "ARAB BANK PLC",
    "Address": "BUILDING 540/542, ROAD 1706, DIPLOMATIC AREA",
    "City": "MANAMA",
    "Branch": "",
    "Postcode": "317",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "ARAB",
    "bankCode": "BH",
    "branchCode": "CTU",
    "SWIFT Code": "ARABBHBMCTU",
    "Bank Name": "ARAB BANK PLC",
    "Address": "BAHRAIN BLDG, 179 GOVERNMENT AVENUE",
    "City": "MANAMA",
    "Branch": "CENTRAL TRANSFER UNIT",
    "Postcode": "395",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "ARAB",
    "bankCode": "BH",
    "branchCode": "MAN",
    "SWIFT Code": "ARABBHBMMAN",
    "Bank Name": "ARAB BANK PLC",
    "Address": "GOVERNMENT STREET",
    "City": "MANAMA",
    "Branch": "COMMERCIAL BRANCH",
    "Postcode": "323",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "ARAB",
    "bankCode": "BH",
    "branchCode": "INV",
    "SWIFT Code": "ARABBHBMINV",
    "Bank Name": "ARAB BANK PLC",
    "Address": "BAHRAIN BLDG, 179 GOVERNMENT AVENUE",
    "City": "MANAMA",
    "Branch": "PAYMENTS INVESTIGATIONS",
    "Postcode": "395",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "ARAB",
    "bankCode": "BH",
    "branchCode": "TSU",
    "SWIFT Code": "ARABBHBMTSU",
    "Bank Name": "ARAB BANK PLC",
    "Address": "BAHRAIN BLDG, 179 GOVERNMENT AVENUE",
    "City": "MANAMA",
    "Branch": "TRADE SERVICES UNIT",
    "Postcode": "395",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "ARAB",
    "bankCode": "BH",
    "branchCode": "TRO",
    "SWIFT Code": "ARABBHBMTRO",
    "Bank Name": "ARAB BANK PLC",
    "Address": "BAHRAIN BLDG, 179 GOVERNMENT AVENUE",
    "City": "MANAMA",
    "Branch": "TREASURY OPERATIONS",
    "Postcode": "395",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "ABCO",
    "bankCode": "BH",
    "branchCode": "HBM",
    "SWIFT Code": "ABCOBHBM",
    "Bank Name": "ARAB BANKING CORPORATION (B.S.C.)",
    "Address": "BLOCK 317, FLOOR 4, ABC TOWER, BUILDING 152 ROAD 1703",
    "City": "MANAMA",
    "Branch": "",
    "Postcode": "317",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "TAIQ",
    "bankCode": "BH",
    "branchCode": "HBM",
    "SWIFT Code": "TAIQBHBM",
    "Bank Name": "ARAB INVESTMENT COMPANY, THE",
    "Address": "428, THE ARAB INVESTMENT CO. BLDG, 2309 ROAD 2830 ALSEEF DISTRICT",
    "City": "MANAMA",
    "Branch": "",
    "Postcode": "428",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "APIC",
    "bankCode": "BH",
    "branchCode": "HBM",
    "SWIFT Code": "APICBHBM",
    "Bank Name": "ARAB PETROLEUM INVESTMENTS CORPORATION",
    "Address": "AL MOAYYED TOWER, ROAD 2833",
    "City": "MANAMA",
    "Branch": "",
    "Postcode": "428",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "APIC",
    "bankCode": "BH",
    "branchCode": "BH2",
    "SWIFT Code": "APICBHBMBH2",
    "Bank Name": "ARAB PETROLEUM INVESTMENTS CORPORATION",
    "Address": "AL MUAYYED TOWER, ROAD 2832",
    "City": "MANAMA",
    "Branch": "APICORP BAHRAIN PROJECT",
    "Postcode": "428",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "FIIV",
    "bankCode": "BH",
    "branchCode": "HBM",
    "SWIFT Code": "FIIVBHBM",
    "Bank Name": "ARCAPITA",
    "Address": "FLOOR 5, ARCAPITA BUILDING, BAHRAIN BAY",
    "City": "MANAMA",
    "Branch": "",
    "Postcode": "973",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "ASCM",
    "bankCode": "BH",
    "branchCode": "HBM",
    "SWIFT Code": "ASCMBHBM",
    "Bank Name": "ASKARI BANK LIMITED, BAHRAIN BRANCH",
    "Address": "SUITE 102, FLOOR 10, WIND TOWER, ROAD 1705, DIPLOMATIC AREA",
    "City": "MANAMA",
    "Branch": "",
    "Postcode": "317",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "BHBN",
    "bankCode": "BH",
    "branchCode": "HBM",
    "SWIFT Code": "BHBNBHBM",
    "Bank Name": "BAHRAIN BOURSE",
    "Address": "FLOOR 4, HARBOUR MALL, BUILDING, 1435 4626 KING FAISAL ROAD",
    "City": "MANAMA",
    "Branch": "",
    "Postcode": "346",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "BDBB",
    "bankCode": "BH",
    "branchCode": "HBM",
    "SWIFT Code": "BDBBBHBM",
    "Bank Name": "BAHRAIN DEVELOPMENT BANK B S C (C)",
    "Address": "BLOCK 317, BULIDING 170, ROAD 1703",
    "City": "MANAMA",
    "Branch": "",
    "Postcode": "323",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "BFCC",
    "bankCode": "BH",
    "branchCode": "HBM",
    "SWIFT Code": "BFCCBHBM",
    "Bank Name": "BAHRAIN FINANCING COMPANY",
    "Address": "BLOCK 315, BAB AL BAHRAIN BUILDING, 150 ROAD N. 1507",
    "City": "MANAMA",
    "Branch": "",
    "Postcode": "323",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "BIBB",
    "bankCode": "BH",
    "branchCode": "HBM",
    "SWIFT Code": "BIBBBHBM",
    "Bank Name": "BAHRAIN ISLAMIC BANK B.S.C.",
    "Address": "AL SALAM TOWER, DIPLOMATIC AREA",
    "City": "MANAMA",
    "Branch": "",
    "Postcode": "317",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "BIBB",
    "bankCode": "BH",
    "branchCode": "INV",
    "SWIFT Code": "BIBBBHBMINV",
    "Bank Name": "BAHRAIN ISLAMIC BANK B.S.C.",
    "Address": "AL-SALAM TOWER, DIPLOMATIC AREA",
    "City": "MANAMA",
    "Branch": "INVESTMENT AND TREASURY BACK OFFICE",
    "Postcode": "317",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "BIBB",
    "bankCode": "BH",
    "branchCode": "TFD",
    "SWIFT Code": "BIBBBHBMTFD",
    "Bank Name": "BAHRAIN ISLAMIC BANK B.S.C.",
    "Address": "AL-SALAM TOWER, DIPLOMATIC AREA",
    "City": "MANAMA",
    "Branch": "TRADE FINANCE DEPARTMENT",
    "Postcode": "317",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "BMEA",
    "bankCode": "BH",
    "branchCode": "HBM",
    "SWIFT Code": "BMEABHBM",
    "Bank Name": "BAHRAIN MIDDLE EAST BANK B.S.C",
    "Address": "BMB CENTRE 135, ROAD 1702, DIPLOMATIC AREA",
    "City": "MANAMA",
    "Branch": "",
    "Postcode": "317",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "BMAG",
    "bankCode": "BH",
    "branchCode": "HBA",
    "SWIFT Code": "BMAGBHBA",
    "Bank Name": "BAHRAIN MONETARY AGENCY",
    "Address": "BUILDING 96, 1702 ROAD",
    "City": "MANAMA",
    "Branch": "",
    "Postcode": "317",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "BAHL",
    "bankCode": "BH",
    "branchCode": "HBM",
    "SWIFT Code": "BAHLBHBM",
    "Bank Name": "BANK AL HABIB LIMITED",
    "Address": "AL MOAYYED TOWER, 1302, AL SEEF DISCTRICT",
    "City": "MANAMA",
    "Branch": "",
    "Postcode": "428",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "ALFH",
    "bankCode": "BH",
    "branchCode": "HBM",
    "SWIFT Code": "ALFHBHBM",
    "Bank Name": "BANK ALFALAH LIMITED BAHRAIN",
    "Address": "HARBOUR TOWER WEST, 13-C BAHRAIN FINANCIAL HARBOUR",
    "City": "MANAMA",
    "Branch": "",
    "Postcode": "209",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "BJOR",
    "bankCode": "BH",
    "branchCode": "HBM",
    "SWIFT Code": "BJORBHBM",
    "Bank Name": "BANK OF JORDAN COMPANY - PUBLIC SHAREHOLDING COMPANY- FOREIGN BRANCH COMPANY",
    "Address": "KING FAISAL HIGHWAY",
    "City": "MANAMA",
    "Branch": "",
    "Postcode": "312",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "BBKU",
    "bankCode": "BH",
    "branchCode": "HBM",
    "SWIFT Code": "BBKUBHBM",
    "Bank Name": "BBK",
    "Address": "BBK BUILDING, 43 GOVERNMENT AVENUE",
    "City": "MANAMA",
    "Branch": "",
    "Postcode": "315",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "BBKU",
    "bankCode": "BH",
    "branchCode": "ADL",
    "SWIFT Code": "BBKUBHBMADL",
    "Bank Name": "BBK",
    "Address": "",
    "City": "MANAMA",
    "Branch": "ADLIYA BRANCH",
    "Postcode": "323",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "BBKU",
    "bankCode": "BH",
    "branchCode": "BUD",
    "SWIFT Code": "BBKUBHBMBUD",
    "Bank Name": "BBK",
    "Address": "",
    "City": "MANAMA",
    "Branch": "BUDAIYA BRANCH",
    "Postcode": "323",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "BBKU",
    "bankCode": "BH",
    "branchCode": "CMK",
    "SWIFT Code": "BBKUBHBMCMK",
    "Bank Name": "BBK",
    "Address": "",
    "City": "MANAMA",
    "Branch": "CENTRAL MARKET BRANCH",
    "Postcode": "323",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "BBKU",
    "bankCode": "BH",
    "branchCode": "CLG",
    "SWIFT Code": "BBKUBHBMCLG",
    "Bank Name": "BBK",
    "Address": "",
    "City": "MANAMA",
    "Branch": "CLEARING SECTION",
    "Postcode": "323",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "BBKU",
    "bankCode": "BH",
    "branchCode": "MAX",
    "SWIFT Code": "BBKUBHBMMAX",
    "Bank Name": "BBK",
    "Address": "AL HEDAYA, 49 GOVERNMENT AVENUE",
    "City": "MANAMA",
    "Branch": "CREDIMAX",
    "Postcode": "305",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "BBKU",
    "bankCode": "BH",
    "branchCode": "LOP",
    "SWIFT Code": "BBKUBHBMLOP",
    "Bank Name": "BBK",
    "Address": "",
    "City": "MANAMA",
    "Branch": "CREDIT SERVICES UNIT",
    "Postcode": "323",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "BBKU",
    "bankCode": "BH",
    "branchCode": "DIP",
    "SWIFT Code": "BBKUBHBMDIP",
    "Bank Name": "BBK",
    "Address": "",
    "City": "MANAMA",
    "Branch": "DIPLOMATIC AREA BRANCH",
    "Postcode": "323",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "BBKU",
    "bankCode": "BH",
    "branchCode": "ERF",
    "SWIFT Code": "BBKUBHBMERF",
    "Bank Name": "BBK",
    "Address": "",
    "City": "MANAMA",
    "Branch": "EAST RIFFA BRANCH",
    "Postcode": "323",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "BBKU",
    "bankCode": "BH",
    "branchCode": "EXH",
    "SWIFT Code": "BBKUBHBMEXH",
    "Bank Name": "BBK",
    "Address": "",
    "City": "MANAMA",
    "Branch": "EXHIBITION BRANCH",
    "Postcode": "323",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "BBKU",
    "bankCode": "BH",
    "branchCode": "HTN",
    "SWIFT Code": "BBKUBHBMHTN",
    "Bank Name": "BBK",
    "Address": "",
    "City": "MANAMA",
    "Branch": "HAMAD TOWN",
    "Postcode": "323",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "BBKU",
    "bankCode": "BH",
    "branchCode": "ITN",
    "SWIFT Code": "BBKUBHBMITN",
    "Bank Name": "BBK",
    "Address": "",
    "City": "MANAMA",
    "Branch": "ISA TOWN BRANCH",
    "Postcode": "323",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "BBKU",
    "bankCode": "BH",
    "branchCode": "CSU",
    "SWIFT Code": "BBKUBHBMCSU",
    "Bank Name": "BBK",
    "Address": "",
    "City": "MANAMA",
    "Branch": "LC DEPARTMENT",
    "Postcode": "323",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "BBKU",
    "bankCode": "BH",
    "branchCode": "MBR",
    "SWIFT Code": "BBKUBHBMMBR",
    "Bank Name": "BBK",
    "Address": "",
    "City": "MANAMA",
    "Branch": "MAIN BRANCH",
    "Postcode": "323",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "BOML",
    "bankCode": "BH",
    "branchCode": "WBH",
    "SWIFT Code": "BOMLBHBMWBH",
    "Bank Name": "MASHREQBANK PSC.",
    "Address": "SHOP NO.001 , BLOCK 410, FLOOR, 472, FAKHRO TOWER ROAD 1010",
    "City": "MANAMA",
    "Branch": "BAHRAIN WHOLE SALE BANKING",
    "Postcode": "323",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "BOML",
    "bankCode": "BH",
    "branchCode": "HBM",
    "SWIFT Code": "BOMLBHBM",
    "Bank Name": "MASHREQBANK PSC.",
    "Address": "BLOCK 410, SHOP NO.001, FLOOR 472, FAKHRO TOWER 1010 ROAD 1010",
    "City": "SANABIS",
    "Branch": "",
    "Postcode": "323",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "MUCB",
    "bankCode": "BH",
    "branchCode": "HBM",
    "SWIFT Code": "MUCBBHBM",
    "Bank Name": "MCB BANK LIMITED",
    "Address": "FLOOR 3, BKIC BUILDING, DIPLOMATIC AREA",
    "City": "MANAMA",
    "Branch": "",
    "Postcode": "323",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "NBOB",
    "bankCode": "BH",
    "branchCode": "HBM",
    "SWIFT Code": "NBOBBHBM",
    "Bank Name": "NATIONAL BANK OF BAHRAIN",
    "Address": "NBB BUILDING, GOVERNMENT AVENUE",
    "City": "MANAMA",
    "Branch": "",
    "Postcode": "323",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "NBOB",
    "bankCode": "BH",
    "branchCode": "MTD",
    "SWIFT Code": "NBOBBHBMMTD",
    "Bank Name": "NATIONAL BANK OF BAHRAIN",
    "Address": "",
    "City": "MANAMA",
    "Branch": "MONEY TRANSFERS DEPARTMENT",
    "Postcode": "323",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "NBOB",
    "bankCode": "BH",
    "branchCode": "TOP",
    "SWIFT Code": "NBOBBHBMTOP",
    "Bank Name": "NATIONAL BANK OF BAHRAIN",
    "Address": "",
    "City": "MANAMA",
    "Branch": "TREASURY OPERATION",
    "Postcode": "323",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "NBOK",
    "bankCode": "BH",
    "branchCode": "FCB",
    "SWIFT Code": "NBOKBHBMFCB",
    "Bank Name": "NATIONAL BANK OF KUWAIT S.A.K.P- BAHRAIN BRANCH",
    "Address": "",
    "City": "MANAMA",
    "Branch": "",
    "Postcode": "323",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "NBOK",
    "bankCode": "BH",
    "branchCode": "HBM",
    "SWIFT Code": "NBOKBHBM",
    "Bank Name": "NATIONAL BANK OF KUWAIT S.A.K.P- BAHRAIN BRANCH",
    "Address": "BLOCK 346, FLOOR 15, BUILDING 1411, SEA FRONT, ROAD 4626",
    "City": "MANAMA",
    "Branch": "",
    "Postcode": "323",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "NBPA",
    "bankCode": "BH",
    "branchCode": "HBM",
    "SWIFT Code": "NBPABHBM",
    "Bank Name": "NATIONAL BANK OF PAKISTAN",
    "Address": "BLOCK 316, BUILDING 66, 2831 383 ROAD",
    "City": "MANAMA",
    "Branch": "",
    "Postcode": "323",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "NECD",
    "bankCode": "BH",
    "branchCode": "HBQ",
    "SWIFT Code": "NECDBHBQ",
    "Bank Name": "NEC B.S.C CLOSED",
    "Address": "330 SH.ISA AVENUE A 226 / 882 1",
    "City": "QUDAIBIYAH",
    "Branch": "",
    "Postcode": "307",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "OSOL",
    "bankCode": "BH",
    "branchCode": "HBM",
    "SWIFT Code": "OSOLBHBM",
    "Bank Name": "OSOOL ASSET MANAGEMENT B.S.C. (C)",
    "Address": "BLOCK 346, FLOOR 1, ARCAPITA, BUILDING, BUILDING 551 4612 SEA, FRONT BAHRAIN BAY",
    "City": "MANAMA",
    "Branch": "",
    "Postcode": "323",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "PINV",
    "bankCode": "BH",
    "branchCode": "HBM",
    "SWIFT Code": "PINVBHBM",
    "Bank Name": "PALESTINE INVESTMENT BANK",
    "Address": "BUILDING 180 5, 383 GOVERNMENT AVENUE",
    "City": "MANAMA",
    "Branch": "",
    "Postcode": "323",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "RAFB",
    "bankCode": "BH",
    "branchCode": "HBM",
    "SWIFT Code": "RAFBBHBM",
    "Bank Name": "RAFIDAIN BANK",
    "Address": "BLOCK 316, FLOOR GF, MANAMA CENTER, BUILDING 60 383 GOVERNMENT AVENUE, ROAD",
    "City": "MANAMA",
    "Branch": "",
    "Postcode": "607",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "SICS",
    "bankCode": "BH",
    "branchCode": "HBM",
    "SWIFT Code": "SICSBHBM",
    "Bank Name": "SICO B.S.C. (C)",
    "Address": "BMB BUILDING",
    "City": "MANAMA",
    "Branch": "",
    "Postcode": "323",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "SCBL",
    "bankCode": "BH",
    "branchCode": "HBM",
    "SWIFT Code": "SCBLBHBM",
    "Bank Name": "STANDARD CHARTERED BANK",
    "Address": "BUILDING 180, 383 GOVERNMENT ROAD",
    "City": "MANAMA",
    "Branch": "ALL OFFICES",
    "Postcode": "315",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "SCBL",
    "bankCode": "BH",
    "branchCode": "OBU",
    "SWIFT Code": "SCBLBHBMOBU",
    "Bank Name": "STANDARD CHARTERED BANK",
    "Address": "BUILDING 180, 383 GOVERNMENT ROAD",
    "City": "MANAMA",
    "Branch": "OFFSHORE BANKING UNIT",
    "Postcode": "315",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "SBIN",
    "bankCode": "BH",
    "branchCode": "HBM",
    "SWIFT Code": "SBINBHBM",
    "Bank Name": "STATE BANK OF INDIA, OBU",
    "Address": "FLOOR 9, BAHRAIN TOWER, GOVERNMENT AVENUE",
    "City": "MANAMA",
    "Branch": "",
    "Postcode": "306",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "SBIN",
    "bankCode": "BH",
    "branchCode": "FCB",
    "SWIFT Code": "SBINBHBMFCB",
    "Bank Name": "STATE BANK OF INDIA, OBU",
    "Address": "BLOCK 306, BUILDING NO 60, 601 GOVT. AVENUE ROAD",
    "City": "MANAMA",
    "Branch": "FULL COMMERCIAL BRANCH",
    "Postcode": "317",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "TAIB",
    "bankCode": "BH",
    "branchCode": "HBM",
    "SWIFT Code": "TAIBBHBM",
    "Bank Name": "TAIB BANK B.S.C.(C)",
    "Address": "FLOOR 7, KINGDOM TOWER, 1901 EXHIBITION AVENUE 8",
    "City": "MANAMA",
    "Branch": "",
    "Postcode": "317",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "SNCB",
    "bankCode": "BH",
    "branchCode": "HBM",
    "SWIFT Code": "SNCBBHBM",
    "Bank Name": "THE SAUDI NATIONAL BANK, BAHRAIN BRANCH",
    "Address": "BLOCK 317, FLOOR 1, DIPLOMAT TOWER, 315 ROAD 1705, DIPLOMATIC AREA",
    "City": "MANAMA",
    "Branch": "",
    "Postcode": "315",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "SNCB",
    "bankCode": "BH",
    "branchCode": "COM",
    "SWIFT Code": "SNCBBHBMCOM",
    "Bank Name": "THE SAUDI NATIONAL BANK, BAHRAIN BRANCH",
    "Address": "",
    "City": "MANAMA",
    "Branch": "FULL COMMERCIAL BRANCH",
    "Postcode": "323",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "SNCB",
    "bankCode": "BH",
    "branchCode": "861",
    "SWIFT Code": "SNCBBHBM861",
    "Bank Name": "THE SAUDI NATIONAL BANK, BAHRAIN BRANCH",
    "Address": "FLOOR 27-28, BWTC EAST TOWER, GOVERMENT ROAD",
    "City": "MANAMA",
    "Branch": "S AND P BAHRAIN",
    "Postcode": "383",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "TRHB",
    "bankCode": "BH",
    "branchCode": "HBM",
    "SWIFT Code": "TRHBBHBM",
    "Bank Name": "TURKIYE HALK BANKASI A.S. BAHRAIN BRANCH",
    "Address": "SUITE 3302, FLOOR 8-33, ALMOAYYED, TOWER AL SEEF DISTRICT",
    "City": "MANAMA",
    "Branch": "",
    "Postcode": "323",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "ISBK",
    "bankCode": "BH",
    "branchCode": "HBM",
    "SWIFT Code": "ISBKBHBM",
    "Bank Name": "TURKIYE IS BANKASI A.S. BAHRAIN BRANCH",
    "Address": "FLOOR 8, AL JASRAH TOWER BUILDING, 95 ROAD 1702 DIPLOMATIC AREA AREA, 317",
    "City": "MANAMA",
    "Branch": "",
    "Postcode": "317",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "TVBA",
    "bankCode": "BH",
    "branchCode": "HBM",
    "SWIFT Code": "TVBABHBM",
    "Bank Name": "TURKIYE VAKIFLAR BANKASI T.A.O. BAHRAIN BRANCH (OBU)",
    "Address": "OFFICE 102, FLOOR 10, AL ROSSAIS, TOWER ROAD 1704 DIPLOMATIC AREA",
    "City": "MANAMA",
    "Branch": "",
    "Postcode": "283",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "UNIL",
    "bankCode": "BH",
    "branchCode": "HBM",
    "SWIFT Code": "UNILBHBM",
    "Bank Name": "UNITED BANK LIMITED",
    "Address": "BLOCK 304, FLOOR GF, BUILDING 117,, DELMON TOWER 385 ROAD",
    "City": "MANAMA",
    "Branch": "",
    "Postcode": "546",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "UNIL",
    "bankCode": "BH",
    "branchCode": "TRY",
    "SWIFT Code": "UNILBHBMTRY",
    "Bank Name": "UNITED BANK LIMITED",
    "Address": "",
    "City": "MANAMA",
    "Branch": "",
    "Postcode": "323",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "UGUB",
    "bankCode": "BH",
    "branchCode": "HBM",
    "SWIFT Code": "UGUBBHBM",
    "Bank Name": "UNITED GULF BANK B.S.C",
    "Address": "BLOCK 317, FLOOR 3, UGB TOWER, ROAD 1705, DIPLOMATIC AREA",
    "City": "MANAMA",
    "Branch": "",
    "Postcode": "323",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "VTOL",
    "bankCode": "BH",
    "branchCode": "HBM",
    "SWIFT Code": "VTOLBHBM",
    "Bank Name": "VITOL BAHRAIN E.C.",
    "Address": "OFFICE 203, 204, 205, FLOOR 2ND,, ARCAPITA BUILDING 551 4612 SOUTH, CORE ROAD",
    "City": "MANAMA",
    "Branch": "",
    "Postcode": "346",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "HVBK",
    "bankCode": "BH",
    "branchCode": "HBM",
    "SWIFT Code": "HVBKBHBM",
    "Bank Name": "WOORI BANK, MANAMA",
    "Address": "FLOOR 4, MANAMA CENTRE, 1 GOVERNMENT ROAD ENTRANCE",
    "City": "MANAMA",
    "Branch": "",
    "Postcode": "323",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "YAPI",
    "bankCode": "BH",
    "branchCode": "HBX",
    "SWIFT Code": "YAPIBHBX",
    "Bank Name": "YAPI VE KREDI BANKASI A.S.",
    "Address": "BLOCK NO 317 SUITE 101, FLOOR 10,, WIND TOWER 403 ROAD NO 1705, DIPLOMATIC AREA",
    "City": "MANAMA",
    "Branch": "",
    "Postcode": "317",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "ZAIN",
    "bankCode": "BH",
    "branchCode": "HBM",
    "SWIFT Code": "ZAINBHBM",
    "Bank Name": "ZAIN BAHRAIN B.S.C CLOSED",
    "Address": "AL AFOO ROAD, ROAD 662, ROAD 2811",
    "City": "MANAMA",
    "Branch": "",
    "Postcode": "323",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "ZENJ",
    "bankCode": "BH",
    "branchCode": "HBM",
    "SWIFT Code": "ZENJBHBM",
    "Bank Name": "ZENJ EXCHANGE CO. W.L.L",
    "Address": "BLOCK 311, BUILDING 32, ROAD 1103",
    "City": "MANAMA",
    "Branch": "",
    "Postcode": "323",
    "Country": "Bahrain",
    "Connection": "Active"
  },
  {
    "countryCode": "TCZB",
    "bankCode": "BH",
    "branchCode": "HBM",
    "SWIFT Code": "TCZBBHBM",
    "Bank Name": "ZIRAAT BANK A.S  BAHRAIN BRANCH",
    "Address": "FLOOR 5, HARBOUR TOWERS - EAST, 4626 KING FAISAL HIGHWAY",
    "City": "MANAMA",
    "Branch": "",
    "Postcode": "346",
    "Country": "Bahrain",
    "Connection": "Active"
  }
]
module.exports = bahrain
