const belize = [
  {
    "countryCode": "LIBA",
    "bankCode": "BZ",
    "branchCode": "ZBZ",
    "SWIFT Code": "LIBABZBZ",
    "Bank Name": "ATLANTIC BANK LIMITED",
    "Address": "CORNER CLEGHORN STREET AND, FREETOWN ROAD",
    "City": "BELIZE CITY",
    "Branch": "",
    "Postcode": "",
    "Country": "Belize",
    "Connection": "Active"
  },
  {
    "countryCode": "LIBA",
    "bankCode": "BZ",
    "branchCode": "0BS",
    "SWIFT Code": "LIBABZBZ0BS",
    "Bank Name": "ATLANTIC BANK LIMITED",
    "Address": "",
    "City": "SAN PEDRO",
    "Branch": "",
    "Postcode": "",
    "Country": "Belize",
    "Connection": "Active"
  },
  {
    "countryCode": "BCBT",
    "bankCode": "BZ",
    "branchCode": "ZBZ",
    "SWIFT Code": "BCBTBZBZ",
    "Bank Name": "BELIZE BANK INTERNATIONAL LIMITED",
    "Address": "FLOOR 2, THE MATALON BUSINESS, CENTER CONEY DRIVE",
    "City": "BELIZE CITY",
    "Branch": "",
    "Postcode": "",
    "Country": "Belize",
    "Connection": "Active"
  },
  {
    "countryCode": "BBLZ",
    "bankCode": "BZ",
    "branchCode": "ZBZ",
    "SWIFT Code": "BBLZBZBZ",
    "Bank Name": "BELIZE BANK LIMITED",
    "Address": "60 MARKET SQUARE",
    "City": "BELIZE CITY",
    "Branch": "",
    "Postcode": "",
    "Country": "Belize",
    "Connection": "Active"
  },
  {
    "countryCode": "CAYE",
    "bankCode": "BZ",
    "branchCode": "ZBZ",
    "SWIFT Code": "CAYEBZBZ",
    "Bank Name": "CAYE INTERNATIONAL BANK LTD.",
    "Address": "COCONUT DRIVE, AMBERGRIS CAYE",
    "City": "SAN PEDRO",
    "Branch": "",
    "Postcode": "",
    "Country": "Belize",
    "Connection": "Active"
  },
  {
    "countryCode": "CEBB",
    "bankCode": "BZ",
    "branchCode": "ZBZ",
    "SWIFT Code": "CEBBBZBZ",
    "Bank Name": "CENTRAL BANK OF BELIZE",
    "Address": "GABOUREL LANE",
    "City": "BELIZE CITY",
    "Branch": "",
    "Postcode": "",
    "Country": "Belize",
    "Connection": "Active"
  },
  {
    "countryCode": "PRVT",
    "bankCode": "BZ",
    "branchCode": "ZBD",
    "SWIFT Code": "PRVTBZBD",
    "Bank Name": "HERITAGE BANK LIMITED",
    "Address": "2609 MERCY LANE RD SUTTON",
    "City": "BELIZE CITY",
    "Branch": "",
    "Postcode": "",
    "Country": "Belize",
    "Connection": "Active"
  },
  {
    "countryCode": "PRVT",
    "bankCode": "BZ",
    "branchCode": "ZBS",
    "SWIFT Code": "PRVTBZBS",
    "Bank Name": "HERITAGE INTERNATIONAL BANK AND TRUST LIMITED",
    "Address": "2609 MERCY LANE RD SUTTON",
    "City": "BELIZE CITY",
    "Branch": "",
    "Postcode": "",
    "Country": "Belize",
    "Connection": "Active"
  },
  {
    "countryCode": "NBEL",
    "bankCode": "BZ",
    "branchCode": "ZBB",
    "SWIFT Code": "NBELBZBB",
    "Bank Name": "NATIONAL BANK OF BELIZE LIMITED",
    "Address": "COR. FOREST DRIVE HUMMINGBIRD HWAY",
    "City": "BELMOPAN",
    "Branch": "",
    "Postcode": "",
    "Country": "Belize",
    "Connection": "Active"
  }
]
module.exports = belize
