const benin = [
  {
    "countryCode": "AFRI",
    "bankCode": "BJ",
    "branchCode": "JBJ",
    "SWIFT Code": "AFRIBJBJ",
    "Bank Name": "BANK OF AFRICA - BENIN",
    "Address": "AVENUE JEAN PAUL II",
    "City": "COTONOU",
    "Branch": "",
    "Postcode": "",
    "Country": "Benin",
    "Connection": "Active"
  },
  {
    "countryCode": "ATBJ",
    "bankCode": "BJ",
    "branchCode": "JBJ",
    "SWIFT Code": "ATBJBJBJ",
    "Bank Name": "BANQUE ATLANTIQUE DU BENIN",
    "Address": "IMMEUBLE ATLANTIQUE, RUE DU GOUVERNEUR BAYOL",
    "City": "COTONOU",
    "Branch": "",
    "Postcode": "",
    "Country": "Benin",
    "Connection": "Active"
  },
  {
    "countryCode": "BCAO",
    "bankCode": "BJ",
    "branchCode": "JBJ",
    "SWIFT Code": "BCAOBJBJ",
    "Bank Name": "BANQUE CENTRALE DES ETATS DE L'AFRIQUE DE L'OUEST",
    "Address": "AVENUE JEAN PAUL II",
    "City": "COTONOU",
    "Branch": "",
    "Postcode": "",
    "Country": "Benin",
    "Connection": "Active"
  },
  {
    "countryCode": "BCAO",
    "bankCode": "BJ",
    "branchCode": "PAR",
    "SWIFT Code": "BCAOBJBJPAR",
    "Bank Name": "BANQUE CENTRALE DES ETATS DE L'AFRIQUE DE L'OUEST",
    "Address": "",
    "City": "PARAKOU",
    "Branch": "PARAKOU BRANCH",
    "Postcode": "",
    "Country": "Benin",
    "Connection": "Active"
  },
  {
    "countryCode": "BIIC",
    "bankCode": "BJ",
    "branchCode": "JBJ",
    "SWIFT Code": "BIICBJBJ",
    "Bank Name": "BANQUE INTERNATIONALE POUR L'INDUSTRIE ET LE COMMERCE BENIN",
    "Address": "IMMEUBLE BIIC, LOT 374 C, BOULEVARD SAINT MICHEL",
    "City": "COTONOU",
    "Branch": "",
    "Postcode": "",
    "Country": "Benin",
    "Connection": "Active"
  },
  {
    "countryCode": "AFIC",
    "bankCode": "BJ",
    "branchCode": "JBJ",
    "SWIFT Code": "AFICBJBJ",
    "Bank Name": "BANQUE INTERNATIONALE POUR L'INDUSTRIE ET LE COMMERCE BENIN",
    "Address": "IMMEUBLE BIIC, 522M , BOULEVARD ST MICHEL",
    "City": "COTONOU",
    "Branch": "",
    "Postcode": "017744",
    "Country": "Benin",
    "Connection": "Active"
  },
  {
    "countryCode": "BSAH",
    "bankCode": "BJ",
    "branchCode": "JBJ",
    "SWIFT Code": "BSAHBJBJ",
    "Bank Name": "BANQUE SAHELO-SAHARIENNE POUR L'INVESTISSEMENT ET LE COMMERCE (BENIN) S.A.",
    "Address": "LOT 26F, 106 , DAKO DONOU GUINKOMEY",
    "City": "COTONOU",
    "Branch": "",
    "Postcode": "",
    "Country": "Benin",
    "Connection": "Active"
  },
  {
    "countryCode": "BGFI",
    "bankCode": "BJ",
    "branchCode": "JBJ",
    "SWIFT Code": "BGFIBJBJ",
    "Bank Name": "BGFIBANK BENIN",
    "Address": "COOP BUILDING, GANHI",
    "City": "COTONOU",
    "Branch": "",
    "Postcode": "",
    "Country": "Benin",
    "Connection": "Active"
  },
  {
    "countryCode": "CBAO",
    "bankCode": "BJ",
    "branchCode": "JBJ",
    "SWIFT Code": "CBAOBJBJ",
    "Bank Name": "CBAO GROUP ATTIJARIWAFABANK",
    "Address": "ESPACE DINA SISE, 04, BLD SAINT MICHEL",
    "City": "COTONOU",
    "Branch": "",
    "Postcode": "6441",
    "Country": "Benin",
    "Connection": "Active"
  },
  {
    "countryCode": "CCEI",
    "bankCode": "BJ",
    "branchCode": "JBJ",
    "SWIFT Code": "CCEIBJBJ",
    "Bank Name": "CCEI BANK BENIN",
    "Address": "RUE DE LA CENA, ZONE COMMERCIALE",
    "City": "COTONOU",
    "Branch": "",
    "Postcode": "",
    "Country": "Benin",
    "Connection": "Active"
  },
  {
    "countryCode": "CORI",
    "bankCode": "BJ",
    "branchCode": "JBJ",
    "SWIFT Code": "CORIBJBJ",
    "Bank Name": "CORIS BANK INTERNATIONAL BENIN",
    "Address": "IMMEUBLE SAIZONOU MAGLOIRE, 122-ZA, QUARTIER AVENUE STEITMETZ, PARCELLE ZA",
    "City": "COTONOU",
    "Branch": "",
    "Postcode": "",
    "Country": "Benin",
    "Connection": "Active"
  },
  {
    "countryCode": "ECOC",
    "bankCode": "BJ",
    "branchCode": "JBJ",
    "SWIFT Code": "ECOCBJBJ",
    "Bank Name": "ECOBANK BENIN",
    "Address": "RUE DU GOUVERNEUR BAYOL",
    "City": "COTONOU",
    "Branch": "",
    "Postcode": "",
    "Country": "Benin",
    "Connection": "Active"
  },
  {},
  {
    "countryCode": "DBLN",
    "bankCode": "BJ",
    "branchCode": "SEN",
    "SWIFT Code": "DBLNBJBJSEN",
    "Bank Name": "NSIA BANQUE BENIN SA",
    "Address": "308 , RUE REVEREND PERE COLINEAU",
    "City": "COTONOU",
    "Branch": "SUCCURSALE SENEGAL",
    "Postcode": "",
    "Country": "Benin",
    "Connection": "Active"
  },
  {
    "countryCode": "DBLN",
    "bankCode": "BJ",
    "branchCode": "TGO",
    "SWIFT Code": "DBLNBJBJTGO",
    "Bank Name": "NSIA BANQUE BENIN SA",
    "Address": "308 , RUE REVEREND PERE COLINEAU",
    "City": "COTONOU",
    "Branch": "SUCCURSALE TOGO",
    "Postcode": "",
    "Country": "Benin",
    "Connection": "Active"
  },
  {},
  {},
  {},
  {}
]
module.exports = benin
