const bermuda = [
  {},
  {
    "bankCode": "AXSB",
    "countryCode": "BM",
    "branchCode": "MHM",
    "SWIFT Code": "AXSBBMHM",
    "Bank Name": "AXIS SPECIALTY LIMITED",
    "Address": "92 PITTS BAY ROAD",
    "City": "HAMILTON",
    "Branch": "",
    "Postcode": "HM 08",
    "Country": "Bermuda",
    "Connection": "Active"
  },
  {
    "bankCode": "BNTB",
    "countryCode": "BM",
    "branchCode": "MHM",
    "SWIFT Code": "BNTBBMHM",
    "Bank Name": "BANK OF N.T. BUTTERFIELD AND SON LIMITED, THE",
    "Address": "65 FRONT STREET",
    "City": "HAMILTON",
    "Branch": "",
    "Postcode": "HM 12",
    "Country": "Bermuda",
    "Connection": "Active"
  },
  {
    "bankCode": "BPBK",
    "countryCode": "BM",
    "branchCode": "MHM",
    "SWIFT Code": "BPBKBMHM",
    "Bank Name": "BERMUDA COMMERCIAL BANK LIMITED",
    "Address": "34 BERMUDIANA ROAD",
    "City": "HAMILTON",
    "Branch": "",
    "Postcode": "HM 11",
    "Country": "Bermuda",
    "Connection": "Active"
  },
  {
    "bankCode": "BEMA",
    "countryCode": "BM",
    "branchCode": "MHM",
    "SWIFT Code": "BEMABMHM",
    "Bank Name": "BERMUDA MONETARY AUTHORITY",
    "Address": "BMA HOUSE, 43 VICTORIA STREET",
    "City": "HAMILTON",
    "Branch": "",
    "Postcode": "HM 12",
    "Country": "Bermuda",
    "Connection": "Active"
  },
  {
    "bankCode": "BOSR",
    "countryCode": "BM",
    "branchCode": "MHM",
    "SWIFT Code": "BOSRBMHM",
    "Bank Name": "BOSTON RE LTD",
    "Address": "FLOOR 2, WELLESLEY HOUSE, 90 PITT'S BAY ROAD",
    "City": "HAMILTON",
    "Branch": "",
    "Postcode": "HM 08",
    "Country": "Bermuda",
    "Connection": "Active"
  },
  {
    "bankCode": "BOSR",
    "countryCode": "BM",
    "branchCode": "VIS",
    "SWIFT Code": "BOSRBMHMVIS",
    "Bank Name": "BOSTON RE LTD",
    "Address": "FLOOR 2, WELLESLEY HOUSE, 90 PITT'S BAY ROAD",
    "City": "HAMILTON",
    "Branch": "",
    "Postcode": "HM 08",
    "Country": "Bermuda",
    "Connection": "Active"
  },
  {},
  {},
  {
    "bankCode": "BNTB",
    "countryCode": "BM",
    "branchCode": "MHS",
    "SWIFT Code": "BNTBBMHS",
    "Bank Name": "BUTTERFIELD TRUST (BERMUDA) LIMITED",
    "Address": "ROSEBANK CENTRE, 11 BERMUDIANA ROAD, PEMBROKE",
    "City": "HAMILTON",
    "Branch": "",
    "Postcode": "HM 08",
    "Country": "Bermuda",
    "Connection": "Active"
  },
  {
    "bankCode": "CTLY",
    "countryCode": "BM",
    "branchCode": "MHM",
    "SWIFT Code": "CTLYBMHM",
    "Bank Name": "CATALYST RE INTERNATIONAL LTD.",
    "Address": "POWERHOUSE, 7 PAR-LA-VILLE ROAD",
    "City": "HAMILTON",
    "Branch": "",
    "Postcode": "HM 11",
    "Country": "Bermuda",
    "Connection": "Active"
  },
  {
    "bankCode": "CAGP",
    "countryCode": "BM",
    "branchCode": "MHM",
    "SWIFT Code": "CAGPBMHM",
    "Bank Name": "CLARIEN BANK LIMITED",
    "Address": "POINT HOUSE, 6 FRONT STREET",
    "City": "HAMILTON",
    "Branch": "",
    "Postcode": "HM 11",
    "Country": "Bermuda",
    "Connection": "Active"
  },
  {
    "bankCode": "CNVX",
    "countryCode": "BM",
    "branchCode": "MHM",
    "SWIFT Code": "CNVXBMHM",
    "Bank Name": "CONVEX GROUP LIMITED",
    "Address": "FLOOR 6, POINT HOUSE, 6 FRONT STREET",
    "City": "HAMILTON",
    "Branch": "",
    "Postcode": "HM 11",
    "Country": "Bermuda",
    "Connection": "Active"
  },
  {
    "bankCode": "EVIN",
    "countryCode": "BM",
    "branchCode": "MHH",
    "SWIFT Code": "EVINBMHH",
    "Bank Name": "EVEREST INTERNATIONAL REINSURANCE, LTD",
    "Address": "FLOOR 4, SEON PLACE, 141 FRONT STREET",
    "City": "HAMILTON",
    "Branch": "",
    "Postcode": "HM 19",
    "Country": "Bermuda",
    "Connection": "Active"
  },
  {
    "bankCode": "ERBE",
    "countryCode": "BM",
    "branchCode": "MHH",
    "SWIFT Code": "ERBEBMHH",
    "Bank Name": "EVEREST REINSURANCE (BERMUDA), LTD",
    "Address": "FLOOR 4, SEON PLACE, 141 FRONT STREET",
    "City": "HAMILTON",
    "Branch": "",
    "Postcode": "HM 19",
    "Country": "Bermuda",
    "Connection": "Active"
  },
  {
    "bankCode": "FIHG",
    "countryCode": "BM",
    "branchCode": "MHM",
    "SWIFT Code": "FIHGBMHM",
    "Bank Name": "FIDELIS INSURANCE HOLDINGS LIMITED",
    "Address": "100 PITTS BAY ROAD",
    "City": "HAMILTON",
    "Branch": "",
    "Postcode": "HM 08",
    "Country": "Bermuda",
    "Connection": "Active"
  },
  {
    "bankCode": "FLDI",
    "countryCode": "BM",
    "branchCode": "MH2",
    "SWIFT Code": "FLDIBMH2",
    "Bank Name": "FIL DISTRIBUTORS",
    "Address": "PEMBROKE HALL, 42 CROW LANE",
    "City": "PEMBROKE",
    "Branch": "",
    "Postcode": "HM 19",
    "Country": "Bermuda",
    "Connection": "Active"
  },
  {},
  {
    "bankCode": "BBDA",
    "countryCode": "BM",
    "branchCode": "CTS",
    "SWIFT Code": "BBDABMHMCTS",
    "Bank Name": "HSBC BANK BERMUDA LIMITED",
    "Address": "",
    "City": "HAMILTON",
    "Branch": "CORPORATE TRUST SERVICES",
    "Postcode": "HM 08",
    "Country": "Bermuda",
    "Connection": "Active"
  },
  {},
  {
    "bankCode": "IVZL",
    "countryCode": "BM",
    "branchCode": "MHH",
    "SWIFT Code": "IVZLBMHH",
    "Bank Name": "INVESCO LTD",
    "Address": "CANON'S COURT, 22 VICTORIA STREET",
    "City": "HAMILTON",
    "Branch": "",
    "Postcode": "HM 12",
    "Country": "Bermuda",
    "Connection": "Active"
  },
  {
    "bankCode": "JEBN",
    "countryCode": "BM",
    "branchCode": "MHM",
    "SWIFT Code": "JEBNBMHM",
    "Bank Name": "JEWEL BANCORP LIMITED",
    "Address": "FLOOR 2, THE SWAN BUILDING, 26 VICTORIA STREET",
    "City": "HAMILTON",
    "Branch": "",
    "Postcode": "HM 12",
    "Country": "Bermuda",
    "Connection": "Active"
  },
  {
    "bankCode": "MLRI",
    "countryCode": "BM",
    "branchCode": "MHM",
    "SWIFT Code": "MLRIBMHM",
    "Bank Name": "MERRILL LYNCH REINSURANCE SOLUTIONS LIMITED",
    "Address": "VICTORIA HALL, 11 VICTORIA STREET",
    "City": "HAMILTON",
    "Branch": "",
    "Postcode": "HM 11",
    "Country": "Bermuda",
    "Connection": "Active"
  },
  {
    "bankCode": "NEPH",
    "countryCode": "BM",
    "branchCode": "MHM",
    "SWIFT Code": "NEPHBMHM",
    "Bank Name": "NEPHILA CAPITAL LTD.",
    "Address": "FLOOR 3RD WEST, VICTORIA PLACE, 31 VICTORIA STREET",
    "City": "HAMILTON",
    "Branch": "",
    "Postcode": "HM 10",
    "Country": "Bermuda",
    "Connection": "Active"
  },
  {
    "bankCode": "NOSR",
    "countryCode": "BM",
    "branchCode": "MHM",
    "SWIFT Code": "NOSRBMHM",
    "Bank Name": "NOMURA SECURITIES (BERMUDA) LIMITED",
    "Address": "FLOOR 1, WELLESLEY HOUSE, 90 PITT'S BAY ROAD",
    "City": "HAMILTON",
    "Branch": "",
    "Postcode": "HM 08",
    "Country": "Bermuda",
    "Connection": "Active"
  },
  {
    "bankCode": "NOVR",
    "countryCode": "BM",
    "branchCode": "035",
    "SWIFT Code": "NOVRBMHM035",
    "Bank Name": "NOVARTIS SECURITIES INVESTMENT LTD",
    "Address": "",
    "City": "HAMILTON",
    "Branch": "",
    "Postcode": "HM 08",
    "Country": "Bermuda",
    "Connection": "Active"
  },
  {
    "bankCode": "NOVR",
    "countryCode": "BM",
    "branchCode": "MHM",
    "SWIFT Code": "NOVRBMHM",
    "Bank Name": "NOVARTIS SECURITIES INVESTMENT LTD",
    "Address": "FLOOR 7, CUMBERLAND HOUSE, 1 VICTORIA STREET",
    "City": "HAMILTON",
    "Branch": "",
    "Postcode": "HM 11",
    "Country": "Bermuda",
    "Connection": "Active"
  },
  {
    "bankCode": "NOVR",
    "countryCode": "BM",
    "branchCode": "019",
    "SWIFT Code": "NOVRBMHM019",
    "Bank Name": "NOVARTIS SECURITIES INVESTMENT LTD",
    "Address": "FLOOR 7, CUMBERLAND HOUSE, 1 VICTORIA STREET",
    "City": "HAMILTON",
    "Branch": "BEFICO",
    "Postcode": "HM 11",
    "Country": "Bermuda",
    "Connection": "Active"
  },
  {
    "bankCode": "RRHL",
    "countryCode": "BM",
    "branchCode": "MHL",
    "SWIFT Code": "RRHLBMHL",
    "Bank Name": "RENAISSANCERE HOLDINGS LTD.",
    "Address": "RENAISSANCE HOUSE, 12 CROW LANE",
    "City": "HAMILTON",
    "Branch": "",
    "Postcode": "HM 08",
    "Country": "Bermuda",
    "Connection": "Active"
  },
  {
    "bankCode": "ROCH",
    "countryCode": "BM",
    "branchCode": "MHA",
    "SWIFT Code": "ROCHBMHA",
    "Bank Name": "ROCHE INTERTRADE LIMITED",
    "Address": "FLOOR 1, AON BUILDING, 30 WOODBOURNE AVENUE",
    "City": "HAMILTON",
    "Branch": "",
    "Postcode": "HM 08",
    "Country": "Bermuda",
    "Connection": "Active"
  },
  {
    "bankCode": "SOIH",
    "countryCode": "BM",
    "branchCode": "MHM",
    "SWIFT Code": "SOIHBMHM",
    "Bank Name": "SOMPO INTERNATIONAL HOLDINGS LTD.",
    "Address": "WATERLOO HOUSE, 100 PITTS BAY ROAD, PEMBROKE",
    "City": "HAMILTON",
    "Branch": "",
    "Postcode": "HM 08",
    "Country": "Bermuda",
    "Connection": "Active"
  }
]
module.exports = bermuda
