const bhutan = [
  {
    "countryCode": "BHUB",
    "bankCode": "BT",
    "branchCode": "001",
    "SWIFT Code": "BHUBBTBT001",
    "Bank Name": "BANK OF BHUTAN LIMITED",
    "Address": "",
    "City": "PHUNTSHOLING",
    "Branch": "PHUENTSHOLING MAIN BRANCH",
    "Postcode": "21001",
    "Country": "Bhutan",
    "Connection": "Active"
  },
  {
    "countryCode": "BHUB",
    "bankCode": "BT",
    "branchCode": "022",
    "SWIFT Code": "BHUBBTBT022",
    "Bank Name": "BANK OF BHUTAN LIMITED",
    "Address": "",
    "City": "THIMPHU",
    "Branch": "",
    "Postcode": "11001",
    "Country": "Bhutan",
    "Connection": "Active"
  },
  {
    "countryCode": "BHUB",
    "bankCode": "BT",
    "branchCode": "TBT",
    "SWIFT Code": "BHUBBTBT",
    "Bank Name": "BANK OF BHUTAN LIMITED",
    "Address": "BABESA, 102",
    "City": "THIMPHU",
    "Branch": "",
    "Postcode": "11001",
    "Country": "Bhutan",
    "Connection": "Active"
  },
  {
    "countryCode": "BHDE",
    "bankCode": "BT",
    "branchCode": "TBT",
    "SWIFT Code": "BHDEBTBT",
    "Bank Name": "BHUTAN DEVELOPMENT BANK LIMITED",
    "Address": "NORZIN LAM, BDB HEAD OFFICE, 1",
    "City": "THIMPHU",
    "Branch": "",
    "Postcode": "11001",
    "Country": "Bhutan",
    "Connection": "Active"
  },
  {
    "countryCode": "BNBT",
    "bankCode": "BT",
    "branchCode": "TBT",
    "SWIFT Code": "BNBTBTBT",
    "Bank Name": "BHUTAN NATIONAL BANK LTD",
    "Address": "NORZIN LAM, RICBL BUILDING",
    "City": "THIMPHU",
    "Branch": "",
    "Postcode": "11001",
    "Country": "Bhutan",
    "Connection": "Active"
  },
  {
    "countryCode": "DIKI",
    "bankCode": "BT",
    "branchCode": "TBB",
    "SWIFT Code": "DIKIBTBB",
    "Bank Name": "DK LIMITED",
    "Address": "NORZIN LAM, 43",
    "City": "THIMPHU",
    "Branch": "",
    "Postcode": "11001",
    "Country": "Bhutan",
    "Connection": "Active"
  },
  {
    "countryCode": "DIKI",
    "bankCode": "BT",
    "branchCode": "ORO",
    "SWIFT Code": "DIKIBTBBORO",
    "Bank Name": "DK LIMITED",
    "Address": "NORZIN LAM, 43",
    "City": "THIMPHU",
    "Branch": "",
    "Postcode": "11001",
    "Country": "Bhutan",
    "Connection": "Active"
  },
  {
    "countryCode": "PUNB",
    "bankCode": "BT",
    "branchCode": "TBT",
    "SWIFT Code": "PUNBBTBT",
    "Bank Name": "DRUK PNB BANK LIMITED",
    "Address": "NORZIN LAM, NEAR MAIN TRAFFIC",
    "City": "THIMPHU",
    "Branch": "",
    "Postcode": "11001",
    "Country": "Bhutan",
    "Connection": "Active"
  },
  {
    "countryCode": "RMAB",
    "bankCode": "BT",
    "branchCode": "TBT",
    "SWIFT Code": "RMABBTBT",
    "Bank Name": "ROYAL MONETARY AUTHORITY OF BHUTAN",
    "Address": "KAWAJANGSA",
    "City": "THIMPHU",
    "Branch": "",
    "Postcode": "11001",
    "Country": "Bhutan",
    "Connection": "Active"
  },
  {
    "countryCode": "TBBT",
    "bankCode": "BT",
    "branchCode": "TBT",
    "SWIFT Code": "TBBTBTBT",
    "Bank Name": "T BANK LTD",
    "Address": "SAMTEN LAM, OPPOSITE TO HOTEL TAJ, TASHI",
    "City": "THIMPHU",
    "Branch": "",
    "Postcode": "11001",
    "Country": "Bhutan",
    "Connection": "Active"
  }
]
module.exports = bhutan
