const bolivia = [
  {
    "bankCode": "BANI",
    "countryCode": "BO",
    "branchCode": "CBB",
    "SWIFT Code": "BANIBOLXCBB",
    "Bank Name": "BANCO BISA S.A.",
    "Address": "CALLE NATIONIEL AGUIRRE S-508",
    "City": "COCHABAMBA",
    "Branch": "",
    "Postcode": "",
    "Country": "Bolivia",
    "Connection": "Active"
  },
  {
    "bankCode": "BANI",
    "countryCode": "BO",
    "branchCode": "OLX",
    "SWIFT Code": "BANIBOLX",
    "Bank Name": "BANCO BISA S.A.",
    "Address": "AVENIDA 16 DE JULIO 1628, EDIFICIO BISA",
    "City": "LA PAZ",
    "Branch": "",
    "Postcode": "",
    "Country": "Bolivia",
    "Connection": "Active"
  },
  {
    "bankCode": "BANI",
    "countryCode": "BO",
    "branchCode": "SCZ",
    "SWIFT Code": "BANIBOLXSCZ",
    "Bank Name": "BANCO BISA S.A.",
    "Address": "CALLE BENI 47",
    "City": "SANTA CRUZ DE LA SIERRA",
    "Branch": "",
    "Postcode": "",
    "Country": "Bolivia",
    "Connection": "Active"
  },
  {
    "bankCode": "BCEB",
    "countryCode": "BO",
    "branchCode": "OLP",
    "SWIFT Code": "BCEBBOLP",
    "Bank Name": "BANCO CENTRAL DE BOLIVIA",
    "Address": "AYACUCHO ESQ. MERCADO",
    "City": "LA PAZ",
    "Branch": "",
    "Postcode": "",
    "Country": "Bolivia",
    "Connection": "Active"
  },
  {
    "bankCode": "BCPL",
    "countryCode": "BO",
    "branchCode": "CBB",
    "SWIFT Code": "BCPLBOLXCBB",
    "Bank Name": "BANCO DE CREDITO DE BOLIVIA S.A.",
    "Address": "AVENIDA AVACUCHO S-311",
    "City": "COCHABAMBA",
    "Branch": "",
    "Postcode": "",
    "Country": "Bolivia",
    "Connection": "Active"
  },
  {
    "bankCode": "BCPL",
    "countryCode": "BO",
    "branchCode": "OLX",
    "SWIFT Code": "BCPLBOLX",
    "Bank Name": "BANCO DE CREDITO DE BOLIVIA S.A.",
    "Address": "AV. HERNANDO SILES 5555, TORRE EMPRESARIAL ESIMSA",
    "City": "LA PAZ",
    "Branch": "",
    "Postcode": "",
    "Country": "Bolivia",
    "Connection": "Active"
  },
  {
    "bankCode": "BCPL",
    "countryCode": "BO",
    "branchCode": "SCZ",
    "SWIFT Code": "BCPLBOLXSCZ",
    "Bank Name": "BANCO DE CREDITO DE BOLIVIA S.A.",
    "Address": "CALLE 24 DE SEPTIEMBRE 158",
    "City": "SANTA CRUZ DE LA SIERRA",
    "Branch": "",
    "Postcode": "",
    "Country": "Bolivia",
    "Connection": "Active"
  },
  {
    "bankCode": "NACN",
    "countryCode": "BO",
    "branchCode": "OLP",
    "SWIFT Code": "NACNBOLP",
    "Bank Name": "BANCO DE LA NACION ARGENTINA",
    "Address": "JUNIN 22, PLAZA 24 DE SEPTIEMBRE",
    "City": "SANTA CRUZ DE LA SIERRA",
    "Branch": "",
    "Postcode": "",
    "Country": "Bolivia",
    "Connection": "Active"
  },
  {
    "bankCode": "BOEO",
    "countryCode": "BO",
    "branchCode": "CBB",
    "SWIFT Code": "BOEOBO22CBB",
    "Bank Name": "BANCO ECONOMICO S.A.",
    "Address": "CALLE NATANIEL AGUIRRE, LADISLAO CABRERA",
    "City": "COCHABAMBA",
    "Branch": "COCHABAMBA BRANCH",
    "Postcode": "",
    "Country": "Bolivia",
    "Connection": "Active"
  },
  {
    "bankCode": "BOEO",
    "countryCode": "BO",
    "branchCode": "LPZ",
    "SWIFT Code": "BOEOBO22LPZ",
    "Bank Name": "BANCO ECONOMICO S.A.",
    "Address": "AV. CAMACHO 1245-1267",
    "City": "LA PAZ",
    "Branch": "LA PAZ BRANCH",
    "Postcode": "",
    "Country": "Bolivia",
    "Connection": "Active"
  },
  {
    "bankCode": "BOEO",
    "countryCode": "BO",
    "branchCode": "O22",
    "SWIFT Code": "BOEOBO22",
    "Bank Name": "BANCO ECONOMICO S.A.",
    "Address": "CALLE AYACUCHO 166",
    "City": "SANTA CRUZ DE LA SIERRA",
    "Branch": "",
    "Postcode": "",
    "Country": "Bolivia",
    "Connection": "Active"
  },
  {
    "bankCode": "BOEO",
    "countryCode": "BO",
    "branchCode": "BEC",
    "SWIFT Code": "BOEOBO22BEC",
    "Bank Name": "BANCO ECONOMICO S.A.",
    "Address": "AYACUCHO 166",
    "City": "SANTA CRUZ DE LA SIERRA",
    "Branch": "",
    "Postcode": "",
    "Country": "Bolivia",
    "Connection": "Active"
  },
  {
    "bankCode": "BOEO",
    "countryCode": "BO",
    "branchCode": "SCZ",
    "SWIFT Code": "BOEOBO22SCZ",
    "Bank Name": "BANCO ECONOMICO S.A.",
    "Address": "",
    "City": "SANTA CRUZ DE LA SIERRA",
    "Branch": "SANTA CRUZ BRANCH",
    "Postcode": "",
    "Country": "Bolivia",
    "Connection": "Active"
  },
  {
    "bankCode": "BFIF",
    "countryCode": "BO",
    "branchCode": "OLP",
    "SWIFT Code": "BFIFBOLP",
    "Bank Name": "BANCO FIE S.A.",
    "Address": "GENERAL GONZALES 1272",
    "City": "LA PAZ",
    "Branch": "",
    "Postcode": "",
    "Country": "Bolivia",
    "Connection": "Active"
  },
  {
    "bankCode": "BFOR",
    "countryCode": "BO",
    "branchCode": "OLP",
    "SWIFT Code": "BFORBOLP",
    "Bank Name": "BANCO FORTALEZA SA",
    "Address": "AVENIDA ARCE ESQUINA CORDERO 2799",
    "City": "LA PAZ",
    "Branch": "",
    "Postcode": "",
    "Country": "Bolivia",
    "Connection": "Active"
  },
  {
    "bankCode": "GNDR",
    "countryCode": "BO",
    "branchCode": "GEB",
    "SWIFT Code": "GNDRBO22GEB",
    "Bank Name": "BANCO GANADERO S.A.",
    "Address": "",
    "City": "SANTA CRUZ DE LA SIERRA",
    "Branch": "",
    "Postcode": "",
    "Country": "Bolivia",
    "Connection": "Active"
  },
  {
    "bankCode": "GNDR",
    "countryCode": "BO",
    "branchCode": "O22",
    "SWIFT Code": "GNDRBO22",
    "Bank Name": "BANCO GANADERO S.A.",
    "Address": "CALLE BOLIVAR 99",
    "City": "SANTA CRUZ DE LA SIERRA",
    "Branch": "",
    "Postcode": "",
    "Country": "Bolivia",
    "Connection": "Active"
  },
  {
    "bankCode": "GNDR",
    "countryCode": "BO",
    "branchCode": "FIT",
    "SWIFT Code": "GNDRBO22FIT",
    "Bank Name": "BANCO GANADERO S.A.",
    "Address": "",
    "City": "SANTA CRUZ DE LA SIERRA",
    "Branch": "",
    "Postcode": "",
    "Country": "Bolivia",
    "Connection": "Active"
  },
  {
    "bankCode": "GNDR",
    "countryCode": "BO",
    "branchCode": "CMI",
    "SWIFT Code": "GNDRBO22CMI",
    "Bank Name": "BANCO GANADERO S.A.",
    "Address": "",
    "City": "SANTA CRUZ DE LA SIERRA",
    "Branch": "",
    "Postcode": "",
    "Country": "Bolivia",
    "Connection": "Active"
  },
  {
    "bankCode": "MERB",
    "countryCode": "BO",
    "branchCode": "CBB",
    "SWIFT Code": "MERBBOLXCBB",
    "Bank Name": "BANCO MERCANTIL SANTA CRUZ S.A.",
    "Address": "NATANIEL AGUIRRE ESQUINA CALAMA",
    "City": "COCHABAMBA",
    "Branch": "",
    "Postcode": "",
    "Country": "Bolivia",
    "Connection": "Active"
  },
  {
    "bankCode": "MERB",
    "countryCode": "BO",
    "branchCode": "OLX",
    "SWIFT Code": "MERBBOLX",
    "Bank Name": "BANCO MERCANTIL SANTA CRUZ S.A.",
    "Address": "CALLE AYACUCHO ESQUINA MERCADO 295, ZONA CENTRAL",
    "City": "LA PAZ",
    "Branch": "",
    "Postcode": "",
    "Country": "Bolivia",
    "Connection": "Active"
  },
  {
    "bankCode": "MERB",
    "countryCode": "BO",
    "branchCode": "SCZ",
    "SWIFT Code": "MERBBOLXSCZ",
    "Bank Name": "BANCO MERCANTIL SANTA CRUZ S.A.",
    "Address": "RENE MORENO EQUINA S. DE FIGUEROA",
    "City": "SANTA CRUZ DE LA SIERRA",
    "Branch": "",
    "Postcode": "",
    "Country": "Bolivia",
    "Connection": "Active"
  },
  {
    "bankCode": "BNBO",
    "countryCode": "BO",
    "branchCode": "CBB",
    "SWIFT Code": "BNBOBOLXCBB",
    "Bank Name": "BANCO NACIONAL DE BOLIVIA",
    "Address": "NATANIEL AGUIRRE E-198, EDIFICIO B.N.B",
    "City": "COCHABAMBA",
    "Branch": "OFICINA CENTRAL",
    "Postcode": "",
    "Country": "Bolivia",
    "Connection": "Active"
  },
  {
    "bankCode": "BNBO",
    "countryCode": "BO",
    "branchCode": "OLX",
    "SWIFT Code": "BNBOBOLX",
    "Bank Name": "BANCO NACIONAL DE BOLIVIA",
    "Address": "AVENIDA CAMACHO ESQUINA COLON 1296, ZONA CENTRAL",
    "City": "LA PAZ",
    "Branch": "",
    "Postcode": "",
    "Country": "Bolivia",
    "Connection": "Active"
  },
  {
    "bankCode": "BNBO",
    "countryCode": "BO",
    "branchCode": "LPZ",
    "SWIFT Code": "BNBOBOLXLPZ",
    "Bank Name": "BANCO NACIONAL DE BOLIVIA",
    "Address": "AVENIDA CAMACHO 1296, EDIFICIO B.N.B",
    "City": "LA PAZ",
    "Branch": "OFICINA CENTRAL",
    "Postcode": "",
    "Country": "Bolivia",
    "Connection": "Active"
  },
  {
    "bankCode": "BNBO",
    "countryCode": "BO",
    "branchCode": "TES",
    "SWIFT Code": "BNBOBOLXTES",
    "Bank Name": "BANCO NACIONAL DE BOLIVIA",
    "Address": "AV. CAMACHO 1296",
    "City": "LA PAZ",
    "Branch": "TRESORERIA",
    "Postcode": "",
    "Country": "Bolivia",
    "Connection": "Active"
  },
  {
    "bankCode": "BNBO",
    "countryCode": "BO",
    "branchCode": "ORU",
    "SWIFT Code": "BNBOBOLXORU",
    "Bank Name": "BANCO NACIONAL DE BOLIVIA",
    "Address": "C. LA PLATA 6160, EDIFICIO B.N.B",
    "City": "ORURO",
    "Branch": "DEPARTAMENTO INTERNACIONAL",
    "Postcode": "",
    "Country": "Bolivia",
    "Connection": "Active"
  },
  {
    "bankCode": "BNBO",
    "countryCode": "BO",
    "branchCode": "POI",
    "SWIFT Code": "BNBOBOLXPOI",
    "Bank Name": "BANCO NACIONAL DE BOLIVIA",
    "Address": "JUNIN 4, EDIFICIO B.N.B",
    "City": "POTOSI",
    "Branch": "DEPARTAMENTO INTERNACIONAL",
    "Postcode": "",
    "Country": "Bolivia",
    "Connection": "Active"
  },
  {
    "bankCode": "BNBO",
    "countryCode": "BO",
    "branchCode": "SCZ",
    "SWIFT Code": "BNBOBOLXSCZ",
    "Bank Name": "BANCO NACIONAL DE BOLIVIA",
    "Address": "C. RENE MORENO 258, EDIFICIO B.N.B",
    "City": "SANTA CRUZ DE LA SIERRA",
    "Branch": "OFICINA CENTRAL",
    "Postcode": "",
    "Country": "Bolivia",
    "Connection": "Active"
  },
  {
    "bankCode": "BNBO",
    "countryCode": "BO",
    "branchCode": "SRE",
    "SWIFT Code": "BNBOBOLXSRE",
    "Bank Name": "BANCO NACIONAL DE BOLIVIA",
    "Address": "C. ESPANA 90, EDIFICIO B.N.B",
    "City": "SUCRE",
    "Branch": "DEPARTAMENTO INTERNACIONAL",
    "Postcode": "",
    "Country": "Bolivia",
    "Connection": "Active"
  },
  {
    "bankCode": "BNBO",
    "countryCode": "BO",
    "branchCode": "TJA",
    "SWIFT Code": "BNBOBOLXTJA",
    "Bank Name": "BANCO NACIONAL DE BOLIVIA",
    "Address": "C. SUCRE 735, EDIFICIO B.N.B",
    "City": "TARIJA",
    "Branch": "DEPARTAMENTO INTERNACIONAL",
    "Postcode": "",
    "Country": "Bolivia",
    "Connection": "Active"
  },
  {},
  {
    "bankCode": "PYEO",
    "countryCode": "BO",
    "branchCode": "OLP",
    "SWIFT Code": "PYEOBOLP",
    "Bank Name": "BANCO PYME ECOFUTURO S.A.",
    "Address": "AVENIDA SANCHEZ BUSTAMANTE, ESQUINA CALLE 9 302 ZONA CALACOTO",
    "City": "LA PAZ",
    "Branch": "",
    "Postcode": "",
    "Country": "Bolivia",
    "Connection": "Active"
  },
  {
    "bankCode": "BSOL",
    "countryCode": "BO",
    "branchCode": "OLP",
    "SWIFT Code": "BSOLBOLP",
    "Bank Name": "BANCO SOLIDARIO S.A.",
    "Address": "CALLE NICOLAS ACOSTA 289, SAN PEDRO",
    "City": "LA PAZ",
    "Branch": "",
    "Postcode": "",
    "Country": "Bolivia",
    "Connection": "Active"
  },
  {
    "bankCode": "BAUN",
    "countryCode": "BO",
    "branchCode": "CBB",
    "SWIFT Code": "BAUNBO22CBB",
    "Bank Name": "BANCO UNION S.A.",
    "Address": "CALLE SUCRE E-0348, EDIFICIO CAMARA DE COMERCIO",
    "City": "COCHABAMBA",
    "Branch": "SUCURSAL COCHABAMBA",
    "Postcode": "",
    "Country": "Bolivia",
    "Connection": "Active"
  },
  {
    "bankCode": "BAUN",
    "countryCode": "BO",
    "branchCode": "O22",
    "SWIFT Code": "BAUNBO22",
    "Bank Name": "BANCO UNION S.A.",
    "Address": "CALLE 21 DE CALACOTO ESQ. AGUIRRE, ACHA 8484",
    "City": "LA PAZ",
    "Branch": "OFICINA NACIONAL",
    "Postcode": "",
    "Country": "Bolivia",
    "Connection": "Active"
  },
  {
    "bankCode": "BAUN",
    "countryCode": "BO",
    "branchCode": "LPZ",
    "SWIFT Code": "BAUNBO22LPZ",
    "Bank Name": "BANCO UNION S.A.",
    "Address": "AVENIDA CAMACHO, ESQUINA CALLE, LOAYZA 1416 ZONA CENTRAL",
    "City": "LA PAZ",
    "Branch": "SUCURSAL LA PAZ",
    "Postcode": "",
    "Country": "Bolivia",
    "Connection": "Active"
  },
  {
    "bankCode": "BAUN",
    "countryCode": "BO",
    "branchCode": "SCZ",
    "SWIFT Code": "BAUNBO22SCZ",
    "Bank Name": "BANCO UNION S.A.",
    "Address": "CALLE LIBERTAD 156",
    "City": "SANTA CRUZ DE LA SIERRA",
    "Branch": "SUCURSAL SANTA CRUZ",
    "Postcode": "",
    "Country": "Bolivia",
    "Connection": "Active"
  }
]
module.exports = bolivia
