const botswana = [
  {
    "bankCode": "BARC",
    "countryCode": "BW",
    "branchCode": "WGX",
    "SWIFT Code": "BARCBWGX",
    "Bank Name": "ABSA BANK BOTSWANA LIMITED",
    "Address": "BUILDING 4, FLOOR 5, PRIME PLAZA PLOT 74358",
    "City": "GABORONE",
    "Branch": "",
    "Postcode": "",
    "Country": "Botswana",
    "Connection": "Active"
  },
  {
    "bankCode": "BARC",
    "countryCode": "BW",
    "branchCode": "CBS",
    "SWIFT Code": "BARCBWGXCBS",
    "Bank Name": "ABSA BANK BOTSWANA LIMITED",
    "Address": "BUILDING 4, FLOOR 5, PRIME PLAZA PLOT 74358",
    "City": "GABORONE",
    "Branch": "CORPORATE BONDS SETTLEMENT",
    "Postcode": "",
    "Country": "Botswana",
    "Connection": "Active"
  },
  {
    "bankCode": "FMBZ",
    "countryCode": "BW",
    "branchCode": "WGA",
    "SWIFT Code": "FMBZBWGA",
    "Bank Name": "ACCESS BANK BOTSWANA LIMITED",
    "Address": "ACEESS HOUSE FAIRGROUND OFFICE PARK, FAIRGROUND OFFICE PAR 62433",
    "City": "GABORONE",
    "Branch": "",
    "Postcode": "",
    "Country": "Botswana",
    "Connection": "Active"
  },
  {
    "bankCode": "BGLI",
    "countryCode": "BW",
    "branchCode": "WGX",
    "SWIFT Code": "BGLIBWGX",
    "Bank Name": "BANK GABORONE LIMITED",
    "Address": "CAPRICORN HOUSE, PILANE STREET PLOT 165",
    "City": "GABORONE",
    "Branch": "",
    "Postcode": "",
    "Country": "Botswana",
    "Connection": "Active"
  },
  {
    "bankCode": "BARB",
    "countryCode": "BW",
    "branchCode": "WGX",
    "SWIFT Code": "BARBBWGX",
    "Bank Name": "BANK OF BARODA (BOTSWANA) LIMITED",
    "Address": "POSTNET KGALE VIEW, KAMOADD PLOT, 14456",
    "City": "GABORONE",
    "Branch": "",
    "Postcode": "",
    "Country": "Botswana",
    "Connection": "Active"
  },
  {
    "bankCode": "BBOT",
    "countryCode": "BW",
    "branchCode": "WGX",
    "SWIFT Code": "BBOTBWGX",
    "Bank Name": "BANK OF BOTSWANA",
    "Address": "KHAMA CRESCENT",
    "City": "GABORONE",
    "Branch": "",
    "Postcode": "",
    "Country": "Botswana",
    "Connection": "Active"
  },
  {
    "bankCode": "BBKN",
    "countryCode": "BW",
    "branchCode": "WGX",
    "SWIFT Code": "BBKNBWGX",
    "Bank Name": "BBS BANK LIMITED",
    "Address": "FLOOR 4 CORNER OF LEMMENYANE DRIVE, AND SEGODITSHANE WAY PLOT 13108/12, BROADHURST",
    "City": "GABORONE",
    "Branch": "",
    "Postcode": "",
    "Country": "Botswana",
    "Connection": "Active"
  },
  {
    "bankCode": "BIFM",
    "countryCode": "BW",
    "branchCode": "WGA",
    "SWIFT Code": "BIFMBWGA",
    "Bank Name": "BOTSWANA INSURANCE FUND MANAGEMENT LIMITED",
    "Address": "BLOCK A, FLOOR 3, FAIRGROUNDS OFFICE PARK",
    "City": "GABORONE",
    "Branch": "",
    "Postcode": "",
    "Country": "Botswana",
    "Connection": "Active"
  },
  {},
  {
    "bankCode": "DDCO",
    "countryCode": "BW",
    "branchCode": "WGA",
    "SWIFT Code": "DDCOBWGA",
    "Bank Name": "DEBSWANA DIAMOND COMPANY (PTY) LTD",
    "Address": "PLOT 64288, AIRPORT ROAD 8",
    "City": "GABORONE",
    "Branch": "",
    "Postcode": "",
    "Country": "Botswana",
    "Connection": "Active"
  },
  {
    "bankCode": "FRCG",
    "countryCode": "BW",
    "branchCode": "WGA",
    "SWIFT Code": "FRCGBWGA",
    "Bank Name": "FIRST CAPITAL BANK LIMITED",
    "Address": "1ST CAPITAL HOUSE, FLOOR 1, 2ND COMMERCIAL RD NEW CBD",
    "City": "GABORONE",
    "Branch": "",
    "Postcode": "",
    "Country": "Botswana",
    "Connection": "Active"
  },
  {
    "bankCode": "FIRN",
    "countryCode": "BW",
    "branchCode": "WGX",
    "SWIFT Code": "FIRNBWGX",
    "Bank Name": "FIRST NATIONAL BANK OF BOTSWANA LIMITED",
    "Address": "FNB HOUSE, FLOOR 3, KHAMA CRESCENT PLOT 8844",
    "City": "GABORONE",
    "Branch": "",
    "Postcode": "",
    "Country": "Botswana",
    "Connection": "Active"
  },
  {
    "bankCode": "FIRN",
    "countryCode": "BW",
    "branchCode": "CUS",
    "SWIFT Code": "FIRNBWGXCUS",
    "Bank Name": "FIRST NATIONAL BANK OF BOTSWANA LIMITED",
    "Address": "",
    "City": "GABORONE",
    "Branch": "ELECTRONIC MONEY MARKET DEPOSITORY",
    "Postcode": "",
    "Country": "Botswana",
    "Connection": "Active"
  },
  {
    "bankCode": "SBIC",
    "countryCode": "BW",
    "branchCode": "WGX",
    "SWIFT Code": "SBICBWGX",
    "Bank Name": "STANBIC BANK BOTSWANA LIMITED",
    "Address": "STANBIC HOUSE, FLOOR GF, FAIRGROUNDS/OFF MACHEL DRIVE 50672",
    "City": "GABORONE",
    "Branch": "",
    "Postcode": "",
    "Country": "Botswana",
    "Connection": "Active"
  },
  {
    "bankCode": "SCHB",
    "countryCode": "BW",
    "branchCode": "017",
    "SWIFT Code": "SCHBBWGX017",
    "Bank Name": "STANDARD CHARTERED BANK BOTSWANA LTD.",
    "Address": "",
    "City": "FRANCISTOWN",
    "Branch": "HASKINS STREET",
    "Postcode": "",
    "Country": "Botswana",
    "Connection": "Active"
  },
  {},
  {
    "bankCode": "SCHB",
    "countryCode": "BW",
    "branchCode": "024",
    "SWIFT Code": "SCHBBWGX024",
    "Bank Name": "STANDARD CHARTERED BANK BOTSWANA LTD.",
    "Address": "",
    "City": "GABORONE",
    "Branch": "BROADHURST",
    "Postcode": "",
    "Country": "Botswana",
    "Connection": "Active"
  },
  {
    "bankCode": "SCHB",
    "countryCode": "BW",
    "branchCode": "036",
    "SWIFT Code": "SCHBBWGX036",
    "Bank Name": "STANDARD CHARTERED BANK BOTSWANA LTD.",
    "Address": "",
    "City": "GABORONE",
    "Branch": "FOREIGN TRADE",
    "Postcode": "",
    "Country": "Botswana",
    "Connection": "Active"
  },
  {
    "bankCode": "SCHB",
    "countryCode": "BW",
    "branchCode": "WGX",
    "SWIFT Code": "SCHBBWGX",
    "Bank Name": "STANDARD CHARTERED BANK BOTSWANA LTD.",
    "Address": "STANDARD HOUSE BUILDING, FLOOR 5, QUEENS ROAD THE MALL",
    "City": "GABORONE",
    "Branch": "HEAD OFFICE",
    "Postcode": "",
    "Country": "Botswana",
    "Connection": "Active"
  },
  {
    "bankCode": "SCHB",
    "countryCode": "BW",
    "branchCode": "023",
    "SWIFT Code": "SCHBBWGX023",
    "Bank Name": "STANDARD CHARTERED BANK BOTSWANA LTD.",
    "Address": "",
    "City": "GABORONE",
    "Branch": "INDUSTRIAL",
    "Postcode": "",
    "Country": "Botswana",
    "Connection": "Active"
  },
  {
    "bankCode": "SCHB",
    "countryCode": "BW",
    "branchCode": "021",
    "SWIFT Code": "SCHBBWGX021",
    "Bank Name": "STANDARD CHARTERED BANK BOTSWANA LTD.",
    "Address": "",
    "City": "GABORONE",
    "Branch": "MALL BRANCH",
    "Postcode": "",
    "Country": "Botswana",
    "Connection": "Active"
  },
  {
    "bankCode": "SCHB",
    "countryCode": "BW",
    "branchCode": "027",
    "SWIFT Code": "SCHBBWGX027",
    "Bank Name": "STANDARD CHARTERED BANK BOTSWANA LTD.",
    "Address": "P/BAG BR 85, BROADHURST",
    "City": "GABORONE",
    "Branch": "PROFESSIONAL HOUSE",
    "Postcode": "",
    "Country": "Botswana",
    "Connection": "Active"
  },
  {},
  {
    "bankCode": "SCHB",
    "countryCode": "BW",
    "branchCode": "022",
    "SWIFT Code": "SCHBBWGX022",
    "Bank Name": "STANDARD CHARTERED BANK BOTSWANA LTD.",
    "Address": "",
    "City": "GABORONE",
    "Branch": "STANDARD HOUSE",
    "Postcode": "",
    "Country": "Botswana",
    "Connection": "Active"
  },
  {
    "bankCode": "SCHB",
    "countryCode": "BW",
    "branchCode": "008",
    "SWIFT Code": "SCHBBWGX008",
    "Bank Name": "STANDARD CHARTERED BANK BOTSWANA LTD.",
    "Address": "",
    "City": "JWANENG",
    "Branch": "JWANENG BRANCH",
    "Postcode": "",
    "Country": "Botswana",
    "Connection": "Active"
  },
  {
    "bankCode": "SCHB",
    "countryCode": "BW",
    "branchCode": "009",
    "SWIFT Code": "SCHBBWGX009",
    "Bank Name": "STANDARD CHARTERED BANK BOTSWANA LTD.",
    "Address": "",
    "City": "LOBATSE",
    "Branch": "LOBATSE BRANCH",
    "Postcode": "",
    "Country": "Botswana",
    "Connection": "Active"
  },
  {
    "bankCode": "SCHB",
    "countryCode": "BW",
    "branchCode": "013",
    "SWIFT Code": "SCHBBWGX013",
    "Bank Name": "STANDARD CHARTERED BANK BOTSWANA LTD.",
    "Address": "",
    "City": "MAHALAPYE",
    "Branch": "MAHALAPYE BRANCH",
    "Postcode": "",
    "Country": "Botswana",
    "Connection": "Active"
  },
  {
    "bankCode": "SCHB",
    "countryCode": "BW",
    "branchCode": "019",
    "SWIFT Code": "SCHBBWGX019",
    "Bank Name": "STANDARD CHARTERED BANK BOTSWANA LTD.",
    "Address": "",
    "City": "MAUN",
    "Branch": "MAUN BRANCH",
    "Postcode": "",
    "Country": "Botswana",
    "Connection": "Active"
  },
  {
    "bankCode": "SCHB",
    "countryCode": "BW",
    "branchCode": "018",
    "SWIFT Code": "SCHBBWGX018",
    "Bank Name": "STANDARD CHARTERED BANK BOTSWANA LTD.",
    "Address": "",
    "City": "ORAPA",
    "Branch": "LETLHAKANE BRANCH",
    "Postcode": "",
    "Country": "Botswana",
    "Connection": "Active"
  },
  {
    "bankCode": "SCHB",
    "countryCode": "BW",
    "branchCode": "015",
    "SWIFT Code": "SCHBBWGX015",
    "Bank Name": "STANDARD CHARTERED BANK BOTSWANA LTD.",
    "Address": "",
    "City": "PALAPYE",
    "Branch": "PALAPYE BRANCH",
    "Postcode": "",
    "Country": "Botswana",
    "Connection": "Active"
  },
  {
    "bankCode": "SCHB",
    "countryCode": "BW",
    "branchCode": "016",
    "SWIFT Code": "SCHBBWGX016",
    "Bank Name": "STANDARD CHARTERED BANK BOTSWANA LTD.",
    "Address": "",
    "City": "SELEBI-PHIKWE",
    "Branch": "SELEBI PHIKWE BRANCH",
    "Postcode": "",
    "Country": "Botswana",
    "Connection": "Active"
  }
]
module.exports = botswana
