const bulgaria = [
  {
    "countryCode": "UNCR",
    "bankCode": "BG",
    "branchCode": "426",
    "SWIFT Code": "UNCRBGSF426",
    "Bank Name": "UNICREDIT BULBANK AD",
    "Address": "MAKEDONIJA STREET 41",
    "City": "SOFIA",
    "Branch": "VITOSHA BRANCH",
    "Postcode": "1000",
    "Country": "Bulgaria",
    "Connection": "Active"
  },
  {
    "countryCode": "UNCR",
    "bankCode": "BG",
    "branchCode": "733",
    "SWIFT Code": "UNCRBGSF733",
    "Bank Name": "UNICREDIT BULBANK AD",
    "Address": "DR. PUSKIULEV STREET 1",
    "City": "VARNA",
    "Branch": "",
    "Postcode": "9000",
    "Country": "Bulgaria",
    "Connection": "Active"
  },
  {
    "countryCode": "UNCR",
    "bankCode": "BG",
    "branchCode": "081",
    "SWIFT Code": "UNCRBGSF081",
    "Bank Name": "UNICREDIT BULBANK AD",
    "Address": "V. TARNOVO STREET 11",
    "City": "VELIKO TARNOVO",
    "Branch": "V. TARNOVO BRANCH",
    "Postcode": "5000",
    "Country": "Bulgaria",
    "Connection": "Active"
  },
  {
    "countryCode": "UBBS",
    "bankCode": "BG",
    "branchCode": "GSF",
    "SWIFT Code": "UBBSBGSF",
    "Bank Name": "UNITED BULGARIAN BANK AD",
    "Address": "VITOSHA BLVD 89B, MILLENNIUM CENTER",
    "City": "SOFIA",
    "Branch": "HEADQUARTER",
    "Postcode": "1463",
    "Country": "Bulgaria",
    "Connection": "Active"
  },
  {
    "countryCode": "RZBB",
    "bankCode": "BG",
    "branchCode": "GSF",
    "SWIFT Code": "RZBBBGSF",
    "Bank Name": "UNITED BULGARIAN BANK AD (FORMER KBC BANK BULGARIAEAD)",
    "Address": "VITOSHA BLVD. 89B, MILLENNIUM CENTER",
    "City": "SOFIA",
    "Branch": "",
    "Postcode": "1463",
    "Country": "Bulgaria",
    "Connection": "Active"
  },
  {},
  {
    "countryCode": "VPAY",
    "bankCode": "BG",
    "branchCode": "GS2",
    "SWIFT Code": "VPAYBGS2",
    "Bank Name": "VIVA PAYMENT SERVICES S.A. BULGARIA BRANCH",
    "Address": "SVETA NEDELYA SQ. 16, FLOOR 2, OFFICE 3",
    "City": "SOFIA",
    "Branch": "",
    "Postcode": "1000",
    "Country": "Bulgaria",
    "Connection": "Active"
  },
  {
    "countryCode": "BUIN",
    "bankCode": "BG",
    "branchCode": "GSF",
    "SWIFT Code": "BUINBGSF",
    "Bank Name": "ALLIANZ BANK BULGARIA AD",
    "Address": "SREBARNA 16, PARK LANE OFFICE CENTER, FLOOR 6",
    "City": "SOFIA",
    "Branch": "",
    "Postcode": "1407",
    "Country": "Bulgaria",
    "Connection": "Active"
  },
  {
    "countryCode": "BIGK",
    "bankCode": "BG",
    "branchCode": "GSF",
    "SWIFT Code": "BIGKBGSF",
    "Bank Name": "BIGBANK AS - BRANCH BULGARIA",
    "Address": "BOULEVARD GEN. EDUARD I. TOTL 53-55, FLOOR 2",
    "City": "SOFIA",
    "Branch": "",
    "Postcode": "1606",
    "Country": "Bulgaria",
    "Connection": "Active"
  },
  {
    "countryCode": "BNPA",
    "bankCode": "BG",
    "branchCode": "GSX",
    "SWIFT Code": "BNPABGSX",
    "Bank Name": "BNP PARIBAS S.A.-SOFIA BRANCH",
    "Address": "MLADOST 4 BUSINESS PARK SOFIA, BUILDING 14, FLOOR 1 RESIDENTIAL DISTRICT",
    "City": "SOFIA",
    "Branch": "",
    "Postcode": "1766",
    "Country": "Bulgaria",
    "Connection": "Active"
  },
  {
    "countryCode": "BSBG",
    "bankCode": "BG",
    "branchCode": "GS2",
    "SWIFT Code": "BSBGBGS2",
    "Bank Name": "BORICA AD",
    "Address": "TZAR BORIS III BLVD. 41",
    "City": "SOFIA",
    "Branch": "",
    "Postcode": "1612",
    "Country": "Bulgaria",
    "Connection": "Active"
  },
  {
    "countryCode": "BSBG",
    "bankCode": "BG",
    "branchCode": "GSF",
    "SWIFT Code": "BSBGBGSF",
    "Bank Name": "BORICA AD",
    "Address": "TZAR BORIS III BLVD 41",
    "City": "SOFIA",
    "Branch": "",
    "Postcode": "1612",
    "Country": "Bulgaria",
    "Connection": "Active"
  },
  {
    "countryCode": "BSBG",
    "bankCode": "BG",
    "branchCode": "TPS",
    "SWIFT Code": "BSBGBGSFTPS",
    "Bank Name": "BORICA AD",
    "Address": "TZAR BORIS III BLVD. 41",
    "City": "SOFIA",
    "Branch": "",
    "Postcode": "1612",
    "Country": "Bulgaria",
    "Connection": "Active"
  },
  {
    "countryCode": "BSBG",
    "bankCode": "BG",
    "branchCode": "ST2",
    "SWIFT Code": "BSBGBGSFST2",
    "Bank Name": "BORICA AD",
    "Address": "TZAR BORIS III BLVD. 41",
    "City": "SOFIA",
    "Branch": "",
    "Postcode": "1612",
    "Country": "Bulgaria",
    "Connection": "Active"
  },
  {
    "countryCode": "BSBG",
    "bankCode": "BG",
    "branchCode": "IOP",
    "SWIFT Code": "BSBGBGSFIOP",
    "Bank Name": "BORICA AD",
    "Address": "",
    "City": "SOFIA",
    "Branch": "T2 INTEROPERABILITY",
    "Postcode": "",
    "Country": "Bulgaria",
    "Connection": "Active"
  },
  {
    "countryCode": "NASB",
    "bankCode": "BG",
    "branchCode": "GSF",
    "SWIFT Code": "NASBBGSF",
    "Bank Name": "BULGARIAN DEVELOPMENT BANK EAD",
    "Address": "DYAKON IGNATIY STREET 1",
    "City": "SOFIA",
    "Branch": "",
    "Postcode": "1000",
    "Country": "Bulgaria",
    "Connection": "Active"
  },
  {
    "countryCode": "BNBG",
    "bankCode": "BG",
    "branchCode": "GSF",
    "SWIFT Code": "BNBGBGSF",
    "Bank Name": "BULGARIAN NATIONAL BANK",
    "Address": "ALEXANDER BATTENBERG SQUARE 1",
    "City": "SOFIA",
    "Branch": "",
    "Postcode": "1000",
    "Country": "Bulgaria",
    "Connection": "Active"
  },
  {
    "countryCode": "BNBG",
    "bankCode": "BG",
    "branchCode": "GSB",
    "SWIFT Code": "BNBGBGSB",
    "Bank Name": "BULGARIAN NATIONAL BANK",
    "Address": "ALEXANDER BATTENBERG SQUARE 1",
    "City": "SOFIA",
    "Branch": "",
    "Postcode": "1000",
    "Country": "Bulgaria",
    "Connection": "Active"
  },
  {
    "countryCode": "BNBG",
    "bankCode": "BG",
    "branchCode": "GSA",
    "SWIFT Code": "BNBGBGSA",
    "Bank Name": "BULGARIAN NATIONAL BANK",
    "Address": "ALEXANDER BATTENBERG SQUARE 1",
    "City": "SOFIA",
    "Branch": "",
    "Postcode": "1000",
    "Country": "Bulgaria",
    "Connection": "Active"
  },
  {
    "countryCode": "BNBG",
    "bankCode": "BG",
    "branchCode": "GSE",
    "SWIFT Code": "BNBGBGSE",
    "Bank Name": "BULGARIAN NATIONAL BANK",
    "Address": "KNYAZ ALEXANDER I SQUARE 1",
    "City": "SOFIA",
    "Branch": "",
    "Postcode": "1000",
    "Country": "Bulgaria",
    "Connection": "Active"
  },
  {
    "countryCode": "BNBG",
    "bankCode": "BG",
    "branchCode": "GSD",
    "SWIFT Code": "BNBGBGSD",
    "Bank Name": "BULGARIAN NATIONAL BANK - BGN",
    "Address": "ALEXANDER BATTENBERG SQUARE 1",
    "City": "SOFIA",
    "Branch": "",
    "Postcode": "1000",
    "Country": "Bulgaria",
    "Connection": "Active"
  },
  {
    "countryCode": "BGUS",
    "bankCode": "BG",
    "branchCode": "GSF",
    "SWIFT Code": "BGUSBGSF",
    "Bank Name": "BULGARIAN-AMERICAN CREDIT BANK",
    "Address": "SLAVYANSKA STR 2",
    "City": "SOFIA",
    "Branch": "",
    "Postcode": "1000",
    "Country": "Bulgaria",
    "Connection": "Active"
  },
  {
    "countryCode": "CECB",
    "bankCode": "BG",
    "branchCode": "GSF",
    "SWIFT Code": "CECBBGSF",
    "Bank Name": "CENTRAL COOPERATIVE BANK PLC",
    "Address": "TSARIGRADSKO SHOSE BLVD 87",
    "City": "SOFIA",
    "Branch": "",
    "Postcode": "1113",
    "Country": "Bulgaria",
    "Connection": "Active"
  },
  {
    "countryCode": "CEDP",
    "bankCode": "BG",
    "branchCode": "GSF",
    "SWIFT Code": "CEDPBGSF",
    "Bank Name": "CENTRAL DEPOSITORY AD",
    "Address": "TRI USHI STREET 6",
    "City": "SOFIA",
    "Branch": "",
    "Postcode": "1000",
    "Country": "Bulgaria",
    "Connection": "Active"
  },
  {
    "countryCode": "CEDP",
    "bankCode": "BG",
    "branchCode": "CLX",
    "SWIFT Code": "CEDPBGSFCLX",
    "Bank Name": "CENTRAL DEPOSITORY AD",
    "Address": "TRI USHI STREET 6",
    "City": "SOFIA",
    "Branch": "CREARING HOUSE",
    "Postcode": "1000",
    "Country": "Bulgaria",
    "Connection": "Active"
  },
  {
    "countryCode": "CITI",
    "bankCode": "BG",
    "branchCode": "GSF",
    "SWIFT Code": "CITIBGSF",
    "Bank Name": "CITIBANK EUROPE PLC, BULGARIA BRANCH",
    "Address": "SITNYAKOVO BLVD, SERDIKA OFFICES 48, FLOOR 10",
    "City": "SOFIA",
    "Branch": "",
    "Postcode": "1505",
    "Country": "Bulgaria",
    "Connection": "Active"
  },
  {
    "countryCode": "CITI",
    "bankCode": "BG",
    "branchCode": "TRD",
    "SWIFT Code": "CITIBGSFTRD",
    "Bank Name": "CITIBANK EUROPE PLC, BULGARIA BRANCH",
    "Address": "SITNYAKOVO BLVD, SERDIKA OFFICES 48, FLOOR 10",
    "City": "SOFIA",
    "Branch": "TRADE SERVICES DEPARTMENT",
    "Postcode": "1505",
    "Country": "Bulgaria",
    "Connection": "Active"
  },
  {
    "countryCode": "DEMI",
    "bankCode": "BG",
    "branchCode": "GSF",
    "SWIFT Code": "DEMIBGSF",
    "Bank Name": "D COMMERCE BANK AD",
    "Address": "GENERAL TOTLEBEN BLVD 8",
    "City": "SOFIA",
    "Branch": "",
    "Postcode": "1606",
    "Country": "Bulgaria",
    "Connection": "Active"
  },
  {
    "countryCode": "DPCD",
    "bankCode": "BG",
    "branchCode": "GS2",
    "SWIFT Code": "DPCDBGS2",
    "Bank Name": "DATECS PAYMENT TECHNOLOGY EAD",
    "Address": "TSARIGRADSKO SHOSSE 115A, FLOOR 6-TH",
    "City": "SOFIA",
    "Branch": "",
    "Postcode": "1784",
    "Country": "Bulgaria",
    "Connection": "Active"
  },
  {
    "countryCode": "STSA",
    "bankCode": "BG",
    "branchCode": "GSF",
    "SWIFT Code": "STSABGSF",
    "Bank Name": "DSK BANK (FORMERLY STATE SAVINGS BANK)",
    "Address": "MOSKOVSKA STREET 19",
    "City": "SOFIA",
    "Branch": "",
    "Postcode": "1040",
    "Country": "Bulgaria",
    "Connection": "Active"
  },
  {
    "countryCode": "EAPS",
    "bankCode": "BG",
    "branchCode": "GS2",
    "SWIFT Code": "EAPSBGS2",
    "Bank Name": "EASY PAYMENT SERVICES LTD",
    "Address": "JAWAHARLAL NEHRU BLVD, 7 LYULIN, RESIDENTIAL AREA 28 FLOOR 2, OFFICE, 40-46",
    "City": "SOFIA",
    "Branch": "",
    "Postcode": "1324",
    "Country": "Bulgaria",
    "Connection": "Active"
  },
  {
    "countryCode": "ECFE",
    "bankCode": "BG",
    "branchCode": "G22",
    "SWIFT Code": "ECFEBG22",
    "Bank Name": "ECONT FINANCIAL SERVICES LTD",
    "Address": "SLAVYANSKI BLVD 16",
    "City": "RUSE",
    "Branch": "",
    "Postcode": "7000",
    "Country": "Bulgaria",
    "Connection": "Active"
  },
  {
    "countryCode": "BPBI",
    "bankCode": "BG",
    "branchCode": "GSF",
    "SWIFT Code": "BPBIBGSF",
    "Bank Name": "EUROBANK BULGARIA AD",
    "Address": "OKOLOVRASTEN PAT STR 260",
    "City": "SOFIA",
    "Branch": "",
    "Postcode": "1766",
    "Country": "Bulgaria",
    "Connection": "Active"
  },
  {
    "countryCode": "BPBI",
    "bankCode": "BG",
    "branchCode": "SEC",
    "SWIFT Code": "BPBIBGSFSEC",
    "Bank Name": "EUROBANK BULGARIA AD",
    "Address": "",
    "City": "SOFIA",
    "Branch": "CUSTODY DEPARTMENT",
    "Postcode": "",
    "Country": "Bulgaria",
    "Connection": "Active"
  },
  {
    "countryCode": "BPBI",
    "bankCode": "BG",
    "branchCode": "ISD",
    "SWIFT Code": "BPBIBGSFISD",
    "Bank Name": "EUROBANK BULGARIA AD",
    "Address": "",
    "City": "SOFIA",
    "Branch": "INTERNATIONAL SECURITIES DEPOSITORY",
    "Postcode": "",
    "Country": "Bulgaria",
    "Connection": "Active"
  },
  {
    "countryCode": "XPAT",
    "bankCode": "BG",
    "branchCode": "GSF",
    "SWIFT Code": "XPATBGSF",
    "Bank Name": "EXPAT ASSET MANAGEMENT EAD",
    "Address": "GEORGI RAKOVSKI STR 96A",
    "City": "SOFIA",
    "Branch": "",
    "Postcode": "1000",
    "Country": "Bulgaria",
    "Connection": "Active"
  },
  {
    "countryCode": "FINV",
    "bankCode": "BG",
    "branchCode": "GSF",
    "SWIFT Code": "FINVBGSF",
    "Bank Name": "FIRST INVESTMENT BANK AD",
    "Address": "DRAGAN TZANKOV BLVD 37",
    "City": "SOFIA",
    "Branch": "",
    "Postcode": "1797",
    "Country": "Bulgaria",
    "Connection": "Active"
  },
  {
    "countryCode": "INTF",
    "bankCode": "BG",
    "branchCode": "GSF",
    "SWIFT Code": "INTFBGSF",
    "Bank Name": "ICARD AD",
    "Address": "BUSINESS PARK VARNA B1",
    "City": "VARNA",
    "Branch": "",
    "Postcode": "9009",
    "Country": "Bulgaria",
    "Connection": "Active"
  },
  {
    "countryCode": "INGB",
    "bankCode": "BG",
    "branchCode": "GSF",
    "SWIFT Code": "INGBBGSF",
    "Bank Name": "ING BANK N.V. SOFIA BRANCH",
    "Address": "BULGARIA BLVD 49B",
    "City": "SOFIA",
    "Branch": "",
    "Postcode": "1404",
    "Country": "Bulgaria",
    "Connection": "Active"
  },
  {
    "countryCode": "IABG",
    "bankCode": "BG",
    "branchCode": "GSF",
    "SWIFT Code": "IABGBGSF",
    "Bank Name": "INTERNATIONAL ASSET BANK AD",
    "Address": "TODOR ALEXANDROV BLVD 81-83",
    "City": "SOFIA",
    "Branch": "",
    "Postcode": "1303",
    "Country": "Bulgaria",
    "Connection": "Active"
  },
  {
    "countryCode": "IORT",
    "bankCode": "BG",
    "branchCode": "GSF",
    "SWIFT Code": "IORTBGSF",
    "Bank Name": "INVESTBANK JSC",
    "Address": "BULGARIA BLVD 85",
    "City": "SOFIA",
    "Branch": "",
    "Postcode": "1404",
    "Country": "Bulgaria",
    "Connection": "Active"
  },
  {
    "countryCode": "INMK",
    "bankCode": "BG",
    "branchCode": "GSS",
    "SWIFT Code": "INMKBGSS",
    "Bank Name": "IP INTERCAPITAL MARKETS AD",
    "Address": "GEORGI SAVA RAKOVSKI 140, FLOOR 6",
    "City": "SOFIA",
    "Branch": "",
    "Postcode": "1000",
    "Country": "Bulgaria",
    "Connection": "Active"
  },
  {
    "countryCode": "LTZI",
    "bankCode": "BG",
    "branchCode": "G22",
    "SWIFT Code": "LTZIBG22",
    "Bank Name": "LTZ INVESTMENTS LTD",
    "Address": "UL. ATON 1A, BUILDING 6, FLOOR 5, APT. 26",
    "City": "PLOVDIV",
    "Branch": "",
    "Postcode": "4001",
    "Country": "Bulgaria",
    "Connection": "Active"
  },
  {
    "countryCode": "SOMB",
    "bankCode": "BG",
    "branchCode": "GSF",
    "SWIFT Code": "SOMBBGSF",
    "Bank Name": "MUNICIPAL BANK AD",
    "Address": "VRABCHA STREET 6",
    "City": "SOFIA",
    "Branch": "",
    "Postcode": "1000",
    "Country": "Bulgaria",
    "Connection": "Active"
  },
  {
    "countryCode": "MYFN",
    "bankCode": "BG",
    "branchCode": "GSF",
    "SWIFT Code": "MYFNBGSF",
    "Bank Name": "MYFIN EAD",
    "Address": "TSARIGRADSKO SHOSE BLVD. 111P",
    "City": "SOFIA",
    "Branch": "",
    "Postcode": "1784",
    "Country": "Bulgaria",
    "Connection": "Active"
  },
  {
    "countryCode": "PYMN",
    "bankCode": "BG",
    "branchCode": "GS2",
    "SWIFT Code": "PYMNBGS2",
    "Bank Name": "PAYMAN GROUP OOD",
    "Address": "STR. BULGARIA 49, BUSINESS CENTER VITOSHA, FLOOR 1",
    "City": "SOFIA",
    "Branch": "",
    "Postcode": "1404",
    "Country": "Bulgaria",
    "Connection": "Active"
  },
  {
    "countryCode": "PATC",
    "bankCode": "BG",
    "branchCode": "GSF",
    "SWIFT Code": "PATCBGSF",
    "Bank Name": "PAYNETICS AD",
    "Address": "JAMES BOURCHIER 76A, HILL TOWER 1",
    "City": "SOFIA",
    "Branch": "",
    "Postcode": "1407",
    "Country": "Bulgaria",
    "Connection": "Active"
  },
  {
    "countryCode": "PRCB",
    "bankCode": "BG",
    "branchCode": "GSF",
    "SWIFT Code": "PRCBBGSF",
    "Bank Name": "PROCREDIT BANK (BULGARIA) EAD",
    "Address": "TODOR ALEXANDROV BLVD 26",
    "City": "SOFIA",
    "Branch": "",
    "Postcode": "1303",
    "Country": "Bulgaria",
    "Connection": "Active"
  },
  {
    "countryCode": "TCZB",
    "bankCode": "BG",
    "branchCode": "GSF",
    "SWIFT Code": "TCZBBGSF",
    "Bank Name": "T.C. ZIRAAT BANKASI - SOFIA BRANCH",
    "Address": "TSAR SAMUIL STR. 87",
    "City": "SOFIA",
    "Branch": "",
    "Postcode": "1000",
    "Country": "Bulgaria",
    "Connection": "Active"
  },
  {
    "countryCode": "TBIB",
    "bankCode": "BG",
    "branchCode": "GSF",
    "SWIFT Code": "TBIBBGSF",
    "Bank Name": "TBI BANK EAD",
    "Address": "DIMITAR HADJIKOCEV STR 52-54",
    "City": "SOFIA",
    "Branch": "",
    "Postcode": "1421",
    "Country": "Bulgaria",
    "Connection": "Active"
  },
  {
    "countryCode": "TEPJ",
    "bankCode": "BG",
    "branchCode": "GSF",
    "SWIFT Code": "TEPJBGSF",
    "Bank Name": "TENEN PAYMENTS JSC",
    "Address": "STRANDZHA STR 52",
    "City": "SOFIA",
    "Branch": "",
    "Postcode": "1303",
    "Country": "Bulgaria",
    "Connection": "Active"
  },
  {
    "countryCode": "TEXI",
    "bankCode": "BG",
    "branchCode": "GSF",
    "SWIFT Code": "TEXIBGSF",
    "Bank Name": "TEXIM BANK AD",
    "Address": "TODOR ALEXANDROV BLVD 117",
    "City": "SOFIA",
    "Branch": "",
    "Postcode": "1303",
    "Country": "Bulgaria",
    "Connection": "Active"
  },
  {
    "countryCode": "THRI",
    "bankCode": "BG",
    "branchCode": "GS2",
    "SWIFT Code": "THRIBGS2",
    "Bank Name": "THRACIAN INVEST INC.",
    "Address": "OKOLOVRASTEN PAT 251G MM BUSINESS, CENTER, FLOOR 4, MLADOST 4",
    "City": "SOFIA",
    "Branch": "",
    "Postcode": "1715",
    "Country": "Bulgaria",
    "Connection": "Active"
  },
  {
    "countryCode": "CREX",
    "bankCode": "BG",
    "branchCode": "GSF",
    "SWIFT Code": "CREXBGSF",
    "Bank Name": "TOKUDA BANK AD",
    "Address": "GEORG WASHINGTON 21",
    "City": "SOFIA",
    "Branch": "",
    "Postcode": "1000",
    "Country": "Bulgaria",
    "Connection": "Active"
  },
  {
    "countryCode": "UNCR",
    "bankCode": "BG",
    "branchCode": "720",
    "SWIFT Code": "UNCRBGSF720",
    "Bank Name": "UNICREDIT BULBANK AD",
    "Address": "VAZRAZHDANE BOULEVRD 37",
    "City": "PLOVDIV",
    "Branch": "PLOVDIV BRANCH",
    "Postcode": "4018",
    "Country": "Bulgaria",
    "Connection": "Active"
  },
  {
    "countryCode": "UNCR",
    "bankCode": "BG",
    "branchCode": "GSF",
    "SWIFT Code": "UNCRBGSF",
    "Bank Name": "UNICREDIT BULBANK AD",
    "Address": "SVETA NEDELYA SQUARE 7",
    "City": "SOFIA",
    "Branch": "",
    "Postcode": "1000",
    "Country": "Bulgaria",
    "Connection": "Active"
  },
  {
    "countryCode": "UNCR",
    "bankCode": "BG",
    "branchCode": "031",
    "SWIFT Code": "UNCRBGSF031",
    "Bank Name": "UNICREDIT BULBANK AD",
    "Address": "MARIA LOUISA BLVD 2",
    "City": "SOFIA",
    "Branch": "SERDIKA BRANCH",
    "Postcode": "1558",
    "Country": "Bulgaria",
    "Connection": "Active"
  }
]
module.exports = bulgaria
