const burkinaFaso = [
  {
    "countryCode": "AFRI",
    "bankCode": "BF",
    "branchCode": "FBF",
    "SWIFT Code": "AFRIBFBF",
    "Bank Name": "BANK OF AFRICA - BURKINA FASSO",
    "Address": "RUE VICTOR OUEDRAOGO - ZACA, ARRONDISSEMENT NO. 1, SECTEUR NO. 4",
    "City": "OUAGADOUGOU",
    "Branch": "",
    "Postcode": "",
    "Country": "Burkina Faso",
    "Connection": "Active"
  },
  {
    "countryCode": "BAGF",
    "bankCode": "BF",
    "branchCode": "FBF",
    "SWIFT Code": "BAGFBFBF",
    "Bank Name": "BANQUE AGRICOLE DU FASO",
    "Address": "4.42 RUE DU COMMERCE, IMMEUBLE ETHAF, ZACA",
    "City": "OUAGADOUGOU",
    "Branch": "",
    "Postcode": "",
    "Country": "Burkina Faso",
    "Connection": "Active"
  },
  {
    "countryCode": "ATBF",
    "bankCode": "BF",
    "branchCode": "FBF",
    "SWIFT Code": "ATBFBFBF",
    "Bank Name": "BANQUE ATLANTIQUE BURKINA FASO",
    "Address": "RUE DE L'HOTEL DE VILLE, IMMEUBLE NORIA HOLDING",
    "City": "OUAGADOUGOU",
    "Branch": "",
    "Postcode": "",
    "Country": "Burkina Faso",
    "Connection": "Active"
  },
  {
    "countryCode": "BCAO",
    "bankCode": "BF",
    "branchCode": "BOB",
    "SWIFT Code": "BCAOBFBFBOB",
    "Bank Name": "BANQUE CENTRALE DES ETATS DE L'AFRIQUE DE L'OUEST",
    "Address": "",
    "City": "BOBO-DIOULASSO",
    "Branch": "BOBO-DIOULASSO BRANCH",
    "Postcode": "",
    "Country": "Burkina Faso",
    "Connection": "Active"
  },
  {
    "countryCode": "BCAO",
    "bankCode": "BF",
    "branchCode": "FBF",
    "SWIFT Code": "BCAOBFBF",
    "Bank Name": "BANQUE CENTRALE DES ETATS DE L'AFRIQUE DE L'OUEST",
    "Address": "AVENUE GAMAL ABDEL NASSER",
    "City": "OUAGADOUGOU",
    "Branch": "",
    "Postcode": "365",
    "Country": "Burkina Faso",
    "Connection": "Active"
  },
  {
    "countryCode": "BNCF",
    "bankCode": "BF",
    "branchCode": "FBF",
    "SWIFT Code": "BNCFBFBF",
    "Bank Name": "BANQUE COMMERCIALE DU BURKINA",
    "Address": "653 AVENUE KWAME NKRUMAH, SIEGE SOCIAL",
    "City": "OUAGADOUGOU",
    "Branch": "",
    "Postcode": "",
    "Country": "Burkina Faso",
    "Connection": "Active"
  },
  {
    "countryCode": "BDUG",
    "bankCode": "BF",
    "branchCode": "FBF",
    "SWIFT Code": "BDUGBFBF",
    "Bank Name": "BANQUE DE L'UNION BURKINA FASO",
    "Address": "01 RUE LOUDUN, IMMEUBLE ABDOULAYE TRAORE, PROJET ZACA, SECTEUR NO. 05",
    "City": "OUAGADOUGOU",
    "Branch": "",
    "Postcode": "",
    "Country": "Burkina Faso",
    "Connection": "Active"
  },
  {},
  {
    "countryCode": "BSAH",
    "bankCode": "BF",
    "branchCode": "FBF",
    "SWIFT Code": "BSAHBFBF",
    "Bank Name": "BANQUE SAHELO-SAHARIENNE POUR L'INVESTISSEMENT ET LE COMMERCE (BURKINA FASO) S.A.",
    "Address": "AV. DU DR. KWAME N'KRUMAH",
    "City": "OUAGADOUGOU",
    "Branch": "",
    "Postcode": "",
    "Country": "Burkina Faso",
    "Connection": "Active"
  },
  {
    "countryCode": "CBAO",
    "bankCode": "BF",
    "branchCode": "FBG",
    "SWIFT Code": "CBAOBFBG",
    "Bank Name": "CBAO GROUPE ATTIJARIWAFA BANK BURKINA FASO",
    "Address": "479 AVE DU PRESIDENT ABOUBACAR",
    "City": "OUAGADOUGOU",
    "Branch": "",
    "Postcode": "",
    "Country": "Burkina Faso",
    "Connection": "Active"
  },
  {},
  {
    "countryCode": "ECOC",
    "bankCode": "BF",
    "branchCode": "FBF",
    "SWIFT Code": "ECOCBFBF",
    "Bank Name": "ECOBANK BURKINA",
    "Address": "49 RUE DE L'HOTEL DE VILLE",
    "City": "OUAGADOUGOU",
    "Branch": "",
    "Postcode": "",
    "Country": "Burkina Faso",
    "Connection": "Active"
  },
  {
    "countryCode": "IBBA",
    "bankCode": "BF",
    "branchCode": "FBF",
    "SWIFT Code": "IBBABFBF",
    "Bank Name": "INTERNATIONAL BUSINESS BANK (IB BANK)",
    "Address": "AVENUE TANSOBA GOALMA, ARRONDISSEMENT 12, SECTEUR 52",
    "City": "OUAGADOUGOU",
    "Branch": "",
    "Postcode": "",
    "Country": "Burkina Faso",
    "Connection": "Active"
  },
  {
    "countryCode": "ORBK",
    "bankCode": "BF",
    "branchCode": "FBF",
    "SWIFT Code": "ORBKBFBF",
    "Bank Name": "ORABANK BURKINA-FASO",
    "Address": "620 AVENUE KWAME N'KRUMA, IMMEUBLE RESIDENCE AZIZ, COTE SUD",
    "City": "OUAGADOUGOU",
    "Branch": "",
    "Postcode": "",
    "Country": "Burkina Faso",
    "Connection": "Active"
  },
  {
    "countryCode": "SGBB",
    "bankCode": "BF",
    "branchCode": "FBF",
    "SWIFT Code": "SGBBBFBF",
    "Bank Name": "SOCIETE GENERALE BURKINA FASO",
    "Address": "248 RUE DE L HOTEL DE VILLE",
    "City": "OUAGADOUGOU",
    "Branch": "",
    "Postcode": "",
    "Country": "Burkina Faso",
    "Connection": "Active"
  },
  {
    "countryCode": "BIBU",
    "bankCode": "BF",
    "branchCode": "FBF",
    "SWIFT Code": "BIBUBFBF",
    "Bank Name": "UBA BURKINA",
    "Address": "1340 AVENUE DIMDOLOBSOM",
    "City": "OUAGADOUGOU",
    "Branch": "",
    "Postcode": "",
    "Country": "Burkina Faso",
    "Connection": "Active"
  },
  {
    "countryCode": "BICI",
    "bankCode": "BF",
    "branchCode": "FBX",
    "SWIFT Code": "BICIBFBX",
    "Bank Name": "VISTA BANK BURKINA SA",
    "Address": "497 AVENUE DR KWAME N'KRUMAH",
    "City": "OUAGADOUGOU",
    "Branch": "",
    "Postcode": "",
    "Country": "Burkina Faso",
    "Connection": "Active"
  },
  {
    "countryCode": "WBIF",
    "bankCode": "BF",
    "branchCode": "FBF",
    "SWIFT Code": "WBIFBFBF",
    "Bank Name": "WENDKUNI BANK INTERNATIONAL",
    "Address": "11 RUE 5, SECTEUR NO 2, ARRONDISSEMENT NO 1",
    "City": "OUAGADOUGOU",
    "Branch": "",
    "Postcode": "",
    "Country": "Burkina Faso",
    "Connection": "Active"
  }
]
module.exports = burkinaFaso
