const capeVerde = [
  {
    "bankCode": "BAIP",
    "countryCode": "CV",
    "branchCode": "VCV",
    "SWIFT Code": "BAIPCVCV",
    "Bank Name": "BANCO BAI CABO VERDE, S.A",
    "Address": "AVENIDA CIDADE DE LISBOA, EDIFICIO BAICENTER, R/C-CHA D AREIA",
    "City": "PRAIA",
    "Branch": "",
    "Postcode": "7600",
    "Country": "Cape Verde",
    "Connection": "Active"
  },
  {
    "bankCode": "BAVD",
    "countryCode": "CV",
    "branchCode": "VCP",
    "SWIFT Code": "BAVDCVCP",
    "Bank Name": "BANCO BIC CABO VERDE, S.A.",
    "Address": "ACHADA DE SANTO ANTONIO, FERREIRA CARS, FLOOR 2",
    "City": "PRAIA",
    "Branch": "",
    "Postcode": "7602",
    "Country": "Cape Verde",
    "Connection": "Active"
  },
  {},
  {
    "bankCode": "BCAV",
    "countryCode": "CV",
    "branchCode": "VCV",
    "SWIFT Code": "BCAVCVCV",
    "Bank Name": "BANCO DE CABO VERDE",
    "Address": "AVENIDA OUA 02",
    "City": "PRAIA",
    "Branch": "",
    "Postcode": "7954",
    "Country": "Cape Verde",
    "Connection": "Active"
  },
  {
    "bankCode": "BFII",
    "countryCode": "CV",
    "branchCode": "VCV",
    "SWIFT Code": "BFIICVCV",
    "Bank Name": "BANCO DE FOMENTO INTERNACIONAL, S.A. (FORMERLY BANCO FIDUCIARIO INTERNACIONAL (I.F.I.), S.A.)",
    "Address": "AVENIDA SAO VICENTE 3, PALMAREJO",
    "City": "PRAIA",
    "Branch": "",
    "Postcode": "2100",
    "Country": "Cape Verde",
    "Connection": "Active"
  },
  {
    "bankCode": "CGDI",
    "countryCode": "CV",
    "branchCode": "VCP",
    "SWIFT Code": "CGDICVCP",
    "Bank Name": "BANCO INTERATLANTICO, SARL",
    "Address": "ACHADO DE SANTO ANTONIO",
    "City": "PRAIA",
    "Branch": "",
    "Postcode": "7602",
    "Country": "Cape Verde",
    "Connection": "Active"
  },
  {
    "bankCode": "PRIF",
    "countryCode": "CV",
    "branchCode": "VCV",
    "SWIFT Code": "PRIFCVCV",
    "Bank Name": "BANCO PRIVADO INTERNACIONAL (IFI)",
    "Address": "ACHADA DE SANTO ANTONIO 3 DT, PREDIO MCA",
    "City": "PRAIA",
    "Branch": "",
    "Postcode": "7602",
    "Country": "Cape Verde",
    "Connection": "Active"
  },
  {
    "bankCode": "CANB",
    "countryCode": "CV",
    "branchCode": "VCV",
    "SWIFT Code": "CANBCVCV",
    "Bank Name": "BCN-BANCO CABOVERDIANO DE NEGOCIOS SA",
    "Address": "AVENIDA AMILCAR CABRAL 97",
    "City": "PRAIA",
    "Branch": "",
    "Postcode": "1000",
    "Country": "Cape Verde",
    "Connection": "Active"
  },
  {
    "bankCode": "CXEC",
    "countryCode": "CV",
    "branchCode": "VCV",
    "SWIFT Code": "CXECCVCV",
    "Bank Name": "CAIXA ECONOMICA DE CABO VERDE, SA",
    "Address": "AV. CIDADE DE LISBOA",
    "City": "PRAIA",
    "Branch": "",
    "Postcode": "7600",
    "Country": "Cape Verde",
    "Connection": "Active"
  },
  {
    "bankCode": "ECOC",
    "countryCode": "CV",
    "branchCode": "VCV",
    "SWIFT Code": "ECOCCVCV",
    "Bank Name": "ECOBANK CABO VERDE",
    "Address": "AVENIDA CIDADE DE LISBOA 374 C",
    "City": "PRAIA",
    "Branch": "",
    "Postcode": "7600",
    "Country": "Cape Verde",
    "Connection": "Active"
  },
  {
    "bankCode": "BESC",
    "countryCode": "CV",
    "branchCode": "VCP",
    "SWIFT Code": "BESCCVCP",
    "Bank Name": "INTERNATIONAL INVESTMENT BANK, SA",
    "Address": "AVENIDA CIDADE DE LISBOA, FLOOR 7",
    "City": "PRAIA",
    "Branch": "",
    "Postcode": "7600",
    "Country": "Cape Verde",
    "Connection": "Active"
  }
]
module.exports = capeVerde
