const caymanIslands = [
  {
    "bankCode": "ABFT",
    "countryCode": "KY",
    "branchCode": "YKY",
    "SWIFT Code": "ABFTKYKY",
    "Bank Name": "AB FINANCIAL MARKETS LTD",
    "Address": "UGLAND HOUSE",
    "City": "GEORGETOWN",
    "Branch": "",
    "Postcode": "KY1-1104",
    "Country": "Cayman Islands",
    "Connection": "Active"
  },
  {
    "bankCode": "ABFK",
    "countryCode": "KY",
    "branchCode": "YKY",
    "SWIFT Code": "ABFKKYKY",
    "Bank Name": "ABC FINANCIAL MARKETS",
    "Address": "UGLAND HOUSE",
    "City": "GEORGETOWN",
    "Branch": "",
    "Postcode": "KY1-1104",
    "Country": "Cayman Islands",
    "Connection": "Active"
  },
  {
    "bankCode": "ABKK",
    "countryCode": "KY",
    "branchCode": "YKY",
    "SWIFT Code": "ABKKKYKY",
    "Bank Name": "ABK CAYMAN ISLAND LIMITED",
    "Address": "190 ELGIN AVENUE",
    "City": "GEORGETOWN",
    "Branch": "",
    "Postcode": "KY1-9008",
    "Country": "Cayman Islands",
    "Connection": "Active"
  },
  {
    "bankCode": "ADCB",
    "countryCode": "KY",
    "branchCode": "YKY",
    "SWIFT Code": "ADCBKYKY",
    "Bank Name": "ADCB MARKETS (CAYMAN) LIMITED",
    "Address": "190 ELGIN AVENUE",
    "City": "GEORGETOWN",
    "Branch": "",
    "Postcode": "KY1-9005",
    "Country": "Cayman Islands",
    "Connection": "Active"
  },
  {
    "bankCode": "ARNB",
    "countryCode": "KY",
    "branchCode": "YKY",
    "SWIFT Code": "ARNBKYKY",
    "Bank Name": "ANB GLOBAL MARKETS LIMITED",
    "Address": "UGLAND HOUSE",
    "City": "GEORGETOWN",
    "Branch": "",
    "Postcode": "KY1-1104",
    "Country": "Cayman Islands",
    "Connection": "Active"
  },
  {
    "bankCode": "CPNT",
    "countryCode": "KY",
    "branchCode": "YK2",
    "SWIFT Code": "CPNTKYK2",
    "Bank Name": "AP CAPITAL INVESTMENT LIMITED",
    "Address": "KENSINGTON HOUSE, 69 DR. ROY'S DRIVE",
    "City": "GEORGETOWN",
    "Branch": "",
    "Postcode": "KY1-1104",
    "Country": "Cayman Islands",
    "Connection": "Active"
  },
  {},
  {
    "bankCode": "AUGM",
    "countryCode": "KY",
    "branchCode": "YKY",
    "SWIFT Code": "AUGMKYKY",
    "Bank Name": "AUDI GLOBAL MARKETS LTD",
    "Address": "UGLAND HOUSE",
    "City": "GEORGETOWN",
    "Branch": "OFFICES OF MAPLES CORPORATE SERVICE",
    "Postcode": "KY1-1104",
    "Country": "Cayman Islands",
    "Connection": "Active"
  },
  {
    "bankCode": "ABCB",
    "countryCode": "KY",
    "branchCode": "YKX",
    "SWIFT Code": "ABCBKYKX",
    "Bank Name": "BANCO ABC BRASIL S.A. - CAYMAN ISLANDS BRANCH",
    "Address": "190 ELGIN AVENUE",
    "City": "GEORGETOWN",
    "Branch": "",
    "Postcode": "KY1-1102",
    "Country": "Cayman Islands",
    "Connection": "Active"
  },
  {
    "bankCode": "BBDE",
    "countryCode": "KY",
    "branchCode": "YKY",
    "SWIFT Code": "BBDEKYKY",
    "Bank Name": "BANCO BRADESCO S.A.",
    "Address": "FLOOR 5, APPLEBY TOWER, 71 FORT STREET",
    "City": "GEORGETOWN",
    "Branch": "",
    "Postcode": "KY1-1109",
    "Country": "Cayman Islands",
    "Connection": "Active"
  },
  {
    "bankCode": "BCBB",
    "countryCode": "KY",
    "branchCode": "YKY",
    "SWIFT Code": "BCBBKYKY",
    "Bank Name": "BANCO BRADESCO S.A. - GRAND CAYMAN (FORMERLY KIRTON BANK BRASIL S.A. - GRAND CAYMAN BRANCH)",
    "Address": "FLOOR 5, APPLEBY TOWER, 71 FORT STREET",
    "City": "GEORGETOWN",
    "Branch": "",
    "Postcode": "KY1-1109",
    "Country": "Cayman Islands",
    "Connection": "Active"
  },
  {
    "bankCode": "BBON",
    "countryCode": "KY",
    "branchCode": "YKY",
    "SWIFT Code": "BBONKYKY",
    "Bank Name": "BANCO BS2 S.A.",
    "Address": "FLOOR 5, 103 SOUTH CHURCH STREET",
    "City": "GEORGETOWN",
    "Branch": "",
    "Postcode": "KY1-1108",
    "Country": "Cayman Islands",
    "Connection": "Active"
  },
  {
    "bankCode": "BPAB",
    "countryCode": "KY",
    "branchCode": "YKG",
    "SWIFT Code": "BPABKYKG",
    "Bank Name": "BANCO BTG PACTUAL SA CAYMAN BRANCH",
    "Address": "BUTTERFIELD HOUSE, 68 FORT STREET",
    "City": "GEORGETOWN",
    "Branch": "",
    "Postcode": "KY1-1108",
    "Country": "Cayman Islands",
    "Connection": "Active"
  },
  {
    "bankCode": "CSIX",
    "countryCode": "KY",
    "branchCode": "YKY",
    "SWIFT Code": "CSIXKYKY",
    "Bank Name": "BANCO C6 S.A.",
    "Address": "FLOOR 5, HARBOUR PLACE, 103 SOUTH CHURCH STREET",
    "City": "GEORGETOWN",
    "Branch": "",
    "Postcode": "KY1-1108",
    "Country": "Cayman Islands",
    "Connection": "Active"
  },
  {
    "bankCode": "DAYC",
    "countryCode": "KY",
    "branchCode": "YKY",
    "SWIFT Code": "DAYCKYKY",
    "Bank Name": "BANCO DAYCOVAL S/A",
    "Address": "FLOOR 4, HARBOUR PLACE, 103 SOUTH CHURCH STREET",
    "City": "GEORGETOWN",
    "Branch": "",
    "Postcode": "KY1-1102",
    "Country": "Cayman Islands",
    "Connection": "Active"
  },
  {
    "bankCode": "BRAS",
    "countryCode": "KY",
    "branchCode": "YKY",
    "SWIFT Code": "BRASKYKY",
    "Bank Name": "BANCO DO BRASIL S.A.",
    "Address": "FLOOR 2, WATERFRONT CENTRE, 28 NORTH CHURCH STREET",
    "City": "GEORGETOWN",
    "Branch": "",
    "Postcode": "KY1-1108",
    "Country": "Cayman Islands",
    "Connection": "Active"
  },
  {
    "bankCode": "FIBI",
    "countryCode": "KY",
    "branchCode": "YKY",
    "SWIFT Code": "FIBIKYKY",
    "Bank Name": "BANCO FIBRA S/A - GRAND CAYMAN BRANCH",
    "Address": "FLOOR 5, HARBOUR PLACE, 103 SOUTH CHURCH STREET",
    "City": "GEORGETOWN",
    "Branch": "",
    "Postcode": "KY1-1108",
    "Country": "Cayman Islands",
    "Connection": "Active"
  },
  {
    "bankCode": "BGOS",
    "countryCode": "KY",
    "branchCode": "YKY",
    "SWIFT Code": "BGOSKYKY",
    "Bank Name": "BANCO GENERAL (OVERSEAS) INC.",
    "Address": "FLOOR 5, 103 SOUTH CHURCH STREET",
    "City": "GEORGETOWN",
    "Branch": "",
    "Postcode": "KY1-1108",
    "Country": "Cayman Islands",
    "Connection": "Active"
  },
  {
    "bankCode": "BNCE",
    "countryCode": "KY",
    "branchCode": "YKX",
    "SWIFT Code": "BNCEKYKX",
    "Bank Name": "BANCO NACIONAL DE COMERCIO EXTERIOR",
    "Address": "FLOOR 3, 25 MAIN STREET",
    "City": "GEORGETOWN",
    "Branch": "",
    "Postcode": "KY1-1107",
    "Country": "Cayman Islands",
    "Connection": "Active"
  },
  {
    "bankCode": "BORI",
    "countryCode": "KY",
    "branchCode": "YKY",
    "SWIFT Code": "BORIKYKY",
    "Bank Name": "BANCO ORIGINAL S.A.",
    "Address": "68 FORT STREET",
    "City": "GEORGETOWN",
    "Branch": "",
    "Postcode": "KY1-1107",
    "Country": "Cayman Islands",
    "Connection": "Active"
  },
  {
    "bankCode": "PBBR",
    "countryCode": "KY",
    "branchCode": "YKY",
    "SWIFT Code": "PBBRKYKY",
    "Bank Name": "BANCO PINE S.A",
    "Address": "BUTTERFIELD HOUSE, 68 FORT STREET",
    "City": "GEORGETOWN",
    "Branch": "",
    "Postcode": "KY1-1107",
    "Country": "Cayman Islands",
    "Connection": "Active"
  },
  {
    "bankCode": "SAFR",
    "countryCode": "KY",
    "branchCode": "YKY",
    "SWIFT Code": "SAFRKYKY",
    "Bank Name": "BANCO SAFRA S.A",
    "Address": "190 ELGIN AVENUE",
    "City": "GEORGETOWN",
    "Branch": "",
    "Postcode": "KY1-9005",
    "Country": "Cayman Islands",
    "Connection": "Active"
  },
  {
    "bankCode": "BSCH",
    "countryCode": "KY",
    "branchCode": "CAY",
    "SWIFT Code": "BSCHKYKXCAY",
    "Bank Name": "BANCO SANTANDER (BRASIL) SA GRAND CAYMAN BRANCH",
    "Address": "",
    "City": "GEORGETOWN",
    "Branch": "",
    "Postcode": "",
    "Country": "Cayman Islands",
    "Connection": "Active"
  },
  {
    "bankCode": "BSCH",
    "countryCode": "KY",
    "branchCode": "YKX",
    "SWIFT Code": "BSCHKYKX",
    "Bank Name": "BANCO SANTANDER (BRASIL) SA GRAND CAYMAN BRANCH",
    "Address": "FLOOR 2, WATERFRONT CENTRE BUILDING, 28 NORTH CHURCH STREET",
    "City": "GEORGETOWN",
    "Branch": "",
    "Postcode": "KY1-1004",
    "Country": "Cayman Islands",
    "Connection": "Active"
  },
  {},
  {
    "bankCode": "BSBS",
    "countryCode": "KY",
    "branchCode": "YKY",
    "SWIFT Code": "BSBSKYKY",
    "Bank Name": "BANCO SOFISA S.A.",
    "Address": "FLOOR 5, HARBOUR PLACE, 103 SOUTH CHURCH STREET, CAMANA BAY",
    "City": "GEORGETOWN",
    "Branch": "",
    "Postcode": "KY1-1108",
    "Country": "Cayman Islands",
    "Connection": "Active"
  },
  {
    "bankCode": "SUBR",
    "countryCode": "KY",
    "branchCode": "YKY",
    "SWIFT Code": "SUBRKYKY",
    "Bank Name": "BANCO SUMITOMO MITSUI BRASILEIRO S.A.",
    "Address": "25 MAIN STREET",
    "City": "GEORGETOWN",
    "Branch": "",
    "Postcode": "KY1-1107",
    "Country": "Cayman Islands",
    "Connection": "Active"
  },
  {
    "bankCode": "IDVL",
    "countryCode": "KY",
    "branchCode": "YKY",
    "SWIFT Code": "IDVLKYKY",
    "Bank Name": "BANCO VOITER S.A.",
    "Address": "FLOOR 5, HARBOUR PLACE, 103 CHURCH STREET",
    "City": "GEORGETOWN",
    "Branch": "",
    "Postcode": "KY1-1108",
    "Country": "Cayman Islands",
    "Connection": "Active"
  },
  {
    "bankCode": "BKCH",
    "countryCode": "KY",
    "branchCode": "YKY",
    "SWIFT Code": "BKCHKYKY",
    "Bank Name": "BANK OF CHINA LIMITED, GRAND CAYMAN BRANCH",
    "Address": "GRAND PAVILION COMMERCIAL CENTER, 802 WEST BAY ROAD",
    "City": "GEORGETOWN",
    "Branch": "",
    "Postcode": "KY1-1204",
    "Country": "Cayman Islands",
    "Connection": "Active"
  },
  {
    "bankCode": "BRIN",
    "countryCode": "KY",
    "branchCode": "YKX",
    "SWIFT Code": "BRINKYKX",
    "Bank Name": "BANK RAKYAT INDONESIA",
    "Address": "190 ELGIN AVENUE",
    "City": "GEORGETOWN",
    "Branch": "",
    "Postcode": "KY1-9005",
    "Country": "Cayman Islands",
    "Connection": "Active"
  },
  {
    "bankCode": "BAMB",
    "countryCode": "KY",
    "branchCode": "YKX",
    "SWIFT Code": "BAMBKYKX",
    "Bank Name": "BB CAYMAN ISLANDS HOLDING",
    "Address": "FLOOR 2, 28 NORTH CHURCH STREET",
    "City": "GEORGETOWN",
    "Branch": "",
    "Postcode": "KY1-1108",
    "Country": "Cayman Islands",
    "Connection": "Active"
  },
  {
    "bankCode": "BLOM",
    "countryCode": "KY",
    "branchCode": "YKY",
    "SWIFT Code": "BLOMKYKY",
    "Bank Name": "BLOM SPV LTD.",
    "Address": "CAYMAN CORPORATE CENTRE, 27 HOSPITAL ROAD",
    "City": "GEORGETOWN",
    "Branch": "",
    "Postcode": "KY1-9008",
    "Country": "Cayman Islands",
    "Connection": "Active"
  },
  {
    "bankCode": "BNTB",
    "countryCode": "KY",
    "branchCode": "YKY",
    "SWIFT Code": "BNTBKYKY",
    "Bank Name": "BUTTERFIELD BANK (CAYMAN) LIMITED",
    "Address": "BUTTERFIELD PLACE, 12 ALBERT PANTON STREET",
    "City": "GEORGETOWN",
    "Branch": "",
    "Postcode": "KY1-1107",
    "Country": "Cayman Islands",
    "Connection": "Active"
  },
  {
    "bankCode": "CIMG",
    "countryCode": "KY",
    "branchCode": "YKY",
    "SWIFT Code": "CIMGKYKY",
    "Bank Name": "CAYMAN ISLANDS MONETARY AUTHORITY",
    "Address": "FLOOR 1, SIX CRICKET SQUARE, 171 ELGIN AVENUE",
    "City": "GEORGETOWN",
    "Branch": "",
    "Postcode": "KY1-1001",
    "Country": "Cayman Islands",
    "Connection": "Active"
  },
  {
    "bankCode": "CNAT",
    "countryCode": "KY",
    "branchCode": "YKY",
    "SWIFT Code": "CNATKYKY",
    "Bank Name": "CAYMAN NATIONAL BANK LTD.",
    "Address": "2ND FLOOR, 200 ELGIN AVENUE",
    "City": "GEORGETOWN",
    "Branch": "",
    "Postcode": "KY1-1102",
    "Country": "Cayman Islands",
    "Connection": "Active"
  },
  {
    "bankCode": "BICB",
    "countryCode": "KY",
    "branchCode": "YKY",
    "SWIFT Code": "BICBKYKY",
    "Bank Name": "CHINA CONSTRUCTION BANK (BRASIL) BANCO MULTIPLO S /A",
    "Address": "FLOOR 5, HARBOUR PLACE, 103 CHURCH STREET",
    "City": "GEORGETOWN",
    "Branch": "",
    "Postcode": "KY1-1108",
    "Country": "Cayman Islands",
    "Connection": "Active"
  },
  {
    "bankCode": "COBV",
    "countryCode": "KY",
    "branchCode": "YKY",
    "SWIFT Code": "COBVKYKY",
    "Bank Name": "CIBC CAYMAN BANK LIMITED",
    "Address": "FLOOR 2, MONACO TOWERS, 11 DR. ROY'S DRIVE",
    "City": "GEORGETOWN",
    "Branch": "",
    "Postcode": "KY1-1105",
    "Country": "Cayman Islands",
    "Connection": "Active"
  },
  {
    "bankCode": "COBV",
    "countryCode": "KY",
    "branchCode": "YKB",
    "SWIFT Code": "COBVKYKB",
    "Bank Name": "CIBC CAYMAN BANK LIMITED",
    "Address": "CIBC FINANCIAL CENTRE, 2 DR. ROY'S DRIVE",
    "City": "GEORGETOWN",
    "Branch": "",
    "Postcode": "KY1-1107",
    "Country": "Cayman Islands",
    "Connection": "Active"
  },
  {
    "bankCode": "CITC",
    "countryCode": "KY",
    "branchCode": "YKY",
    "SWIFT Code": "CITCKYKY",
    "Bank Name": "CITCO BANK AND TRUST COMPANY LIMITED",
    "Address": "FLOOR 2, 89 NEXUS WAY",
    "City": "GEORGETOWN",
    "Branch": "",
    "Postcode": "KY1-1205",
    "Country": "Cayman Islands",
    "Connection": "Active"
  },
  {
    "bankCode": "COBA",
    "countryCode": "KY",
    "branchCode": "YKX",
    "SWIFT Code": "COBAKYKX",
    "Bank Name": "COMMERZBANK AG,CAYMAN ISLANDS BRANCH",
    "Address": "CIBC FINANCIAL CENTRE, 11 DR. ROYS DRIVE",
    "City": "GEORGETOWN",
    "Branch": "",
    "Postcode": "KY1-1107",
    "Country": "Cayman Islands",
    "Connection": "Active"
  },
  {
    "bankCode": "CSFB",
    "countryCode": "KY",
    "branchCode": "EQD",
    "SWIFT Code": "CSFBKYKXEQD",
    "Bank Name": "CREDIT SUISSE AG, CAYMAN ISLANDS BRANCH",
    "Address": "BRIT CAY HOUSE",
    "City": "GEORGETOWN",
    "Branch": "",
    "Postcode": "KY1-1102",
    "Country": "Cayman Islands",
    "Connection": "Active"
  },
  {
    "bankCode": "CSFB",
    "countryCode": "KY",
    "branchCode": "YKX",
    "SWIFT Code": "CSFBKYKX",
    "Bank Name": "CREDIT SUISSE AG, CAYMAN ISLANDS BRANCH",
    "Address": "BRIT CAY HOUSE",
    "City": "GEORGETOWN",
    "Branch": "CAYMAN ISLANDS BRANCH",
    "Postcode": "KY1-1102",
    "Country": "Cayman Islands",
    "Connection": "Active"
  },
  {
    "bankCode": "DEUT",
    "countryCode": "KY",
    "branchCode": "YKX",
    "SWIFT Code": "DEUTKYKX",
    "Bank Name": "DEUTSCHE BANK AG",
    "Address": "BOUNDARY HALL, 171 ELGIN AVENUE",
    "City": "GEORGETOWN",
    "Branch": "",
    "Postcode": "KY1-1103",
    "Country": "Cayman Islands",
    "Connection": "Active"
  },
  {
    "bankCode": "DLCL",
    "countryCode": "KY",
    "branchCode": "YKY",
    "SWIFT Code": "DLCLKYKY",
    "Bank Name": "DLOCAL LIMITED",
    "Address": "UGLAND HOUSE, 121 SOUTH CHURCH STREET",
    "City": "GEORGETOWN",
    "Branch": "",
    "Postcode": "KY1-1104",
    "Country": "Cayman Islands",
    "Connection": "Active"
  },
  {
    "bankCode": "ECAA",
    "countryCode": "KY",
    "branchCode": "YK2",
    "SWIFT Code": "ECAAKYK2",
    "Bank Name": "EAST COAST ASSET MANAGEMENT SEZC",
    "Address": "90 N CHURCH ST",
    "City": "GEORGETOWN",
    "Branch": "",
    "Postcode": "KY1-9012",
    "Country": "Cayman Islands",
    "Connection": "Active"
  },
  {
    "bankCode": "EFGB",
    "countryCode": "KY",
    "branchCode": "YKY",
    "SWIFT Code": "EFGBKYKY",
    "Bank Name": "EFG BANK, CAYMAN BRANCH",
    "Address": "9 FORUM LANE, CAMANA BAY",
    "City": "GEORGETOWN",
    "Branch": "",
    "Postcode": "KY1-1003",
    "Country": "Cayman Islands",
    "Connection": "Active"
  },
  {
    "bankCode": "ELTN",
    "countryCode": "KY",
    "branchCode": "YKY",
    "SWIFT Code": "ELTNKYKY",
    "Bank Name": "ELLIOTT INTERNATIONAL, L.P.",
    "Address": "UGLAND HOUSE, SOUTH CHURCH STREET",
    "City": "GEORGETOWN",
    "Branch": "C/O MAPLES CORPORATE",
    "Postcode": "KY1-1104",
    "Country": "Cayman Islands",
    "Connection": "Active"
  },
  {
    "bankCode": "EBIL",
    "countryCode": "KY",
    "branchCode": "YKY",
    "SWIFT Code": "EBILKYKY",
    "Bank Name": "EMIRATES NBD GLOBAL MARKETS LLC",
    "Address": "UGLAND HOUSE",
    "City": "GEORGETOWN",
    "Branch": "",
    "Postcode": "KY1-1104",
    "Country": "Cayman Islands",
    "Connection": "Active"
  },
  {
    "bankCode": "EPMF",
    "countryCode": "KY",
    "branchCode": "YKY",
    "SWIFT Code": "EPMFKYKY",
    "Bank Name": "EXODUSPOINT PARTNERS MASTER FUND, LP",
    "Address": "190 ELGIN AVENUE",
    "City": "GEORGETOWN",
    "Branch": "",
    "Postcode": "KY1-9008",
    "Country": "Cayman Islands",
    "Connection": "Active"
  },
  {
    "bankCode": "NBAD",
    "countryCode": "KY",
    "branchCode": "YKY",
    "SWIFT Code": "NBADKYKY",
    "Bank Name": "FAB GLOBAL MARKETS (CAYMAN) LIMITED",
    "Address": "UGLAND HOUSE",
    "City": "GEORGETOWN",
    "Branch": "",
    "Postcode": "KY1-1104",
    "Country": "Cayman Islands",
    "Connection": "Active"
  },
  {
    "bankCode": "FCIB",
    "countryCode": "KY",
    "branchCode": "YKY",
    "SWIFT Code": "FCIBKYKY",
    "Bank Name": "FIRSTCARIBBEAN INTERNATIONAL BANK (CAYMAN) LIMITED",
    "Address": "CIBC FIRSTCARIBBEAN HOUSE, 25 MAIN STREET",
    "City": "GEORGETOWN",
    "Branch": "",
    "Postcode": "KY1-1102",
    "Country": "Cayman Islands",
    "Connection": "Active"
  },
  {
    "bankCode": "CIBC",
    "countryCode": "KY",
    "branchCode": "YKC",
    "SWIFT Code": "CIBCKYKC",
    "Bank Name": "FIRSTCARIBBEAN INTERNATIONAL BANK AND TRUST COMPANY (CAYMAN) LIMITED",
    "Address": "25 MAIN STREET",
    "City": "GEORGETOWN",
    "Branch": "",
    "Postcode": "KY1-1102",
    "Country": "Cayman Islands",
    "Connection": "Active"
  },
  {
    "bankCode": "CAYI",
    "countryCode": "KY",
    "branchCode": "YKY",
    "SWIFT Code": "CAYIKYKY",
    "Bank Name": "FUNDBANK LTD",
    "Address": "DMS HOUSE, 20 GENESIS CLOSE",
    "City": "GEORGETOWN",
    "Branch": "",
    "Postcode": "KY1-1102",
    "Country": "Cayman Islands",
    "Connection": "Active"
  },
  {
    "bankCode": "GULF",
    "countryCode": "KY",
    "branchCode": "YK2",
    "SWIFT Code": "GULFKYK2",
    "Bank Name": "GIB KSA MARKETS LIMITED",
    "Address": "UGLAND HOUSE, SOUTH CHURCH STREET",
    "City": "GEORGETOWN",
    "Branch": "",
    "Postcode": "KY1-1104",
    "Country": "Cayman Islands",
    "Connection": "Active"
  },
  {
    "bankCode": "GIMK",
    "countryCode": "KY",
    "branchCode": "YKY",
    "SWIFT Code": "GIMKKYKY",
    "Bank Name": "GIB MARKETS LIMITED",
    "Address": "UGLAND HOUSE",
    "City": "GEORGETOWN",
    "Branch": "",
    "Postcode": "KY1-1104",
    "Country": "Cayman Islands",
    "Connection": "Active"
  },
  {
    "bankCode": "BESB",
    "countryCode": "KY",
    "branchCode": "YKY",
    "SWIFT Code": "BESBKYKY",
    "Bank Name": "HAITONG BANCO DE INVESTIMENTO DO BRASIL S.A.",
    "Address": "GRAND PAVILLION COMMERCIAL CENTRE, 802 WEST BAY ROAD",
    "City": "GEORGETOWN",
    "Branch": "",
    "Postcode": "KY1-1207",
    "Country": "Cayman Islands",
    "Connection": "Active"
  },
  {
    "bankCode": "INVC",
    "countryCode": "KY",
    "branchCode": "YKY",
    "SWIFT Code": "INVCKYKY",
    "Bank Name": "INVESTCORP TRADING LIMITED",
    "Address": "CRICKET SQUARE, CENTURY YARD",
    "City": "GEORGETOWN",
    "Branch": "",
    "Postcode": "KY1-1102",
    "Country": "Cayman Islands",
    "Connection": "Active"
  },
  {
    "bankCode": "INVC",
    "countryCode": "KY",
    "branchCode": "ISA",
    "SWIFT Code": "INVCKYKYISA",
    "Bank Name": "INVESTCORP TRADING LIMITED",
    "Address": "BOUNDARY HALL, CRICKET SQUARE",
    "City": "GEORGETOWN",
    "Branch": "FFC INVESTCORP S.A.",
    "Postcode": "KY1-1102",
    "Country": "Cayman Islands",
    "Connection": "Active"
  },
  {
    "bankCode": "ITAU",
    "countryCode": "KY",
    "branchCode": "YKT",
    "SWIFT Code": "ITAUKYKT",
    "Bank Name": "ITAU BANK, LIMITED",
    "Address": "FLOOR 5, HARBOUR PLACE, 103 SOUTH CHURCH STREET",
    "City": "GEORGETOWN",
    "Branch": "",
    "Postcode": "KY1-1108",
    "Country": "Cayman Islands",
    "Connection": "Active"
  },
  {
    "bankCode": "KBCF",
    "countryCode": "KY",
    "branchCode": "YKX",
    "SWIFT Code": "KBCFKYKX",
    "Bank Name": "KBC FINANCIAL PRODUCTS (CAYMAN ISLANDS) LTD.",
    "Address": "WALKER HOUSE, MARY STREET",
    "City": "GEORGETOWN",
    "Branch": "W.S. WALKER AND COMPANY",
    "Postcode": "KY1-9002",
    "Country": "Cayman Islands",
    "Connection": "Active"
  },
  {
    "bankCode": "KMRA",
    "countryCode": "KY",
    "branchCode": "YKY",
    "SWIFT Code": "KMRAKYKY",
    "Bank Name": "KIMERA LIMITED",
    "Address": "23 LIME TREE BAY AVENUE",
    "City": "GEORGETOWN",
    "Branch": "",
    "Postcode": "KY1-1102",
    "Country": "Cayman Islands",
    "Connection": "Active"
  },
  {
    "bankCode": "LIFD",
    "countryCode": "KY",
    "branchCode": "YKY",
    "SWIFT Code": "LIFDKYKY",
    "Bank Name": "LICANIA FUND LTD.",
    "Address": "190 ELGIN AVENUE",
    "City": "GEORGETOWN",
    "Branch": "INTERTRUST CORPORATE SERVICES - CAY",
    "Postcode": "KY1-9005",
    "Country": "Cayman Islands",
    "Connection": "Active"
  },
  {
    "bankCode": "MLBC",
    "countryCode": "KY",
    "branchCode": "YKX",
    "SWIFT Code": "MLBCKYKX",
    "Bank Name": "MERRILL LYNCH BANK AND TRUST COMPANY (CAYMAN) LTD",
    "Address": "FLOOR 4, HARBOUR CENTRE, NORTH CHURCH STREET",
    "City": "GEORGETOWN",
    "Branch": "",
    "Postcode": "KY1-1102",
    "Country": "Cayman Islands",
    "Connection": "Active"
  },
  {
    "bankCode": "MMCL",
    "countryCode": "KY",
    "branchCode": "YKY",
    "SWIFT Code": "MMCLKYKY",
    "Bank Name": "MIZUHO MARKETS CAYMAN LP",
    "Address": "UGLAND HOUSE, SOUTH CHURCH STREET",
    "City": "GEORGETOWN",
    "Branch": "",
    "Postcode": "KY1-1104",
    "Country": "Cayman Islands",
    "Connection": "Active"
  },
  {
    "bankCode": "UBSW",
    "countryCode": "KY",
    "branchCode": "GPP",
    "SWIFT Code": "UBSWKYKYGPP",
    "Bank Name": "MUFG ALTERNATIVE FUND SERVICES (CAYMAN) LIMITED",
    "Address": "227 ELGIN AVENUE",
    "City": "GEORGETOWN",
    "Branch": "",
    "Postcode": "KY1-1103",
    "Country": "Cayman Islands",
    "Connection": "Active"
  },
  {
    "bankCode": "UBSW",
    "countryCode": "KY",
    "branchCode": "YKY",
    "SWIFT Code": "UBSWKYKY",
    "Bank Name": "MUFG ALTERNATIVE FUND SERVICES (CAYMAN) LIMITED",
    "Address": "227 ELGIN AVENUE",
    "City": "GEORGETOWN",
    "Branch": "",
    "Postcode": "KY1-1103",
    "Country": "Cayman Islands",
    "Connection": "Active"
  },
  {
    "bankCode": "NBFU",
    "countryCode": "KY",
    "branchCode": "YKY",
    "SWIFT Code": "NBFUKYKY",
    "Bank Name": "NBF MARKETS (CAYMAN) LIMITED",
    "Address": "FLOOR 4, HARBOUR PLACE, 103 SOUTH CHURCH STREET",
    "City": "GEORGETOWN",
    "Branch": "",
    "Postcode": "KY1-1002",
    "Country": "Cayman Islands",
    "Connection": "Active"
  },
  {
    "bankCode": "NBGC",
    "countryCode": "KY",
    "branchCode": "YKY",
    "SWIFT Code": "NBGCKYKY",
    "Bank Name": "NBK GDM (CAYMANS) LIMITED",
    "Address": "CAYMAN CORPORATE CENTRE, 27 HOSPITAL ROAD",
    "City": "GEORGETOWN",
    "Branch": "",
    "Postcode": "KY1-9008",
    "Country": "Cayman Islands",
    "Connection": "Active"
  },
  {
    "bankCode": "FIYC",
    "countryCode": "KY",
    "branchCode": "YKY",
    "SWIFT Code": "FIYCKYKY",
    "Bank Name": "PROVEN BANK (CAYMAN) LIMITED",
    "Address": "CAYMAN FINANCIAL CENTRE, 36A DR. ROY S DRIVE",
    "City": "GEORGETOWN",
    "Branch": "",
    "Postcode": "KY1-1107",
    "Country": "Cayman Islands",
    "Connection": "Active"
  },
  {
    "bankCode": "BMRI",
    "countryCode": "KY",
    "branchCode": "YKY",
    "SWIFT Code": "BMRIKYKY",
    "Bank Name": "PT BANK MANDIRI (PERSERO)TBK CAYMAN ISLANDS BRANCH",
    "Address": "FL 3, ONE CAYMAN HOUSE, 30 CARDINAL AVE",
    "City": "GEORGETOWN",
    "Branch": "",
    "Postcode": "KY1-1109",
    "Country": "Cayman Islands",
    "Connection": "Active"
  },
  {
    "bankCode": "QNBA",
    "countryCode": "KY",
    "branchCode": "YKY",
    "SWIFT Code": "QNBAKYKY",
    "Bank Name": "QNB (DERIVATIVES) LIMITED",
    "Address": "UGLAND HOUSE, SOUTH CHURCH STREET",
    "City": "GEORGETOWN",
    "Branch": "",
    "Postcode": "KY1-1104",
    "Country": "Cayman Islands",
    "Connection": "Active"
  },
  {
    "bankCode": "ROYC",
    "countryCode": "KY",
    "branchCode": "YKY",
    "SWIFT Code": "ROYCKYKY",
    "Bank Name": "RBC ROYAL BANK (CAYMAN) LIMITED (FORMERLY KNOWN AS ROYAL BANK OF CANADA GRAND CAYMAN)",
    "Address": "24 SHEDDON ROAD",
    "City": "GEORGETOWN",
    "Branch": "",
    "Postcode": "KY1-1104",
    "Country": "Cayman Islands",
    "Connection": "Active"
  },
  {
    "bankCode": "ROYC",
    "countryCode": "KY",
    "branchCode": "KYQ",
    "SWIFT Code": "ROYCKYKYKYQ",
    "Bank Name": "RBC ROYAL BANK (CAYMAN) LIMITED (FORMERLY KNOWN AS ROYAL BANK OF CANADA GRAND CAYMAN)",
    "Address": "",
    "City": "GEORGETOWN",
    "Branch": "",
    "Postcode": "",
    "Country": "Cayman Islands",
    "Connection": "Active"
  },
  {
    "bankCode": "NOSC",
    "countryCode": "KY",
    "branchCode": "YKX",
    "SWIFT Code": "NOSCKYKX",
    "Bank Name": "SCOTIABANK AND TRUST (CAYMAN) LTD.",
    "Address": "18 FORUM LANE, CAMANA BAY",
    "City": "GEORGETOWN",
    "Branch": "",
    "Postcode": "KY1-1102",
    "Country": "Cayman Islands",
    "Connection": "Active"
  },
  {
    "bankCode": "NOSC",
    "countryCode": "KY",
    "branchCode": "TRU",
    "SWIFT Code": "NOSCKYKXTRU",
    "Bank Name": "SCOTIABANK AND TRUST (CAYMAN) LTD.",
    "Address": "8 CARDINAL AVENUE",
    "City": "GEORGETOWN",
    "Branch": "TRUST DEPARTMENT",
    "Postcode": "KY1-1201",
    "Country": "Cayman Islands",
    "Connection": "Active"
  },
  {
    "bankCode": "SICO",
    "countryCode": "KY",
    "branchCode": "YKY",
    "SWIFT Code": "SICOKYKY",
    "Bank Name": "SIAM COMMERCIAL BANK PCL., THE",
    "Address": "",
    "City": "GEORGETOWN",
    "Branch": "",
    "Postcode": "KY1-1108",
    "Country": "Cayman Islands",
    "Connection": "Active"
  },
  {
    "bankCode": "SAGM",
    "countryCode": "KY",
    "branchCode": "YKY",
    "SWIFT Code": "SAGMKYKY",
    "Bank Name": "SNB GLOBAL LIMITED",
    "Address": "UGLAND HOUSE",
    "City": "GEORGETOWN",
    "Branch": "C/O MAPLES CORPORATE SERVICES LTD",
    "Postcode": "KY1-1104",
    "Country": "Cayman Islands",
    "Connection": "Active"
  },
  {
    "bankCode": "GBTC",
    "countryCode": "KY",
    "branchCode": "YKY",
    "SWIFT Code": "GBTCKYKY",
    "Bank Name": "ST. GEORGES BANK AND TRUST COMPANY (CAYMAN) LTD.",
    "Address": "REGATTA OFFICE PARK 1ST, WEST BAY ROAD",
    "City": "GEORGETOWN",
    "Branch": "",
    "Postcode": "KY1-1103",
    "Country": "Cayman Islands",
    "Connection": "Active"
  },
  {
    "bankCode": "TCIM",
    "countryCode": "KY",
    "branchCode": "YK2",
    "SWIFT Code": "TCIMKYK2",
    "Bank Name": "TCI CAPITAL MARKETS LTD",
    "Address": "FLOOR 2, TWO ARTILLERY COURT, 161 SHEDDEN ROAD",
    "City": "GEORGETOWN",
    "Branch": "",
    "Postcode": "KY1-1103",
    "Country": "Cayman Islands",
    "Connection": "Active"
  },
  {
    "bankCode": "TOWE",
    "countryCode": "KY",
    "branchCode": "YKY",
    "SWIFT Code": "TOWEKYKY",
    "Bank Name": "TOWERBANK, LTD",
    "Address": "CIBIC FIN CENTRE, 11 DR. ROY'S DRIVE",
    "City": "GEORGETOWN",
    "Branch": "",
    "Postcode": "KY1-1107",
    "Country": "Cayman Islands",
    "Connection": "Active"
  },
  {
    "bankCode": "VBTB",
    "countryCode": "KY",
    "branchCode": "YKY",
    "SWIFT Code": "VBTBKYKY",
    "Bank Name": "VBT BANK AND TRUST,LTD.",
    "Address": "FLOOR 4, THE HARBOUR CENTRE, 42 NORTH CHURCH STREET",
    "City": "GEORGETOWN",
    "Branch": "",
    "Postcode": "KY1-1106",
    "Country": "Cayman Islands",
    "Connection": "Active"
  },
  {
    "bankCode": "VZCR",
    "countryCode": "KY",
    "branchCode": "YKY",
    "SWIFT Code": "VZCRKYKY",
    "Bank Name": "VENEZOLANO DE CREDITO, S.A., BANCO UNIVERSAL CAYMAN BRANCH",
    "Address": "FLOOR 2, THE HARBOUR CENTRE, 42 NORTH CHURCH STREET",
    "City": "GEORGETOWN",
    "Branch": "",
    "Postcode": "KY1-1106",
    "Country": "Cayman Islands",
    "Connection": "Active"
  },
  {
    "bankCode": "WPAC",
    "countryCode": "KY",
    "branchCode": "YKX",
    "SWIFT Code": "WPACKYKX",
    "Bank Name": "WESTPAC BANKING CORPORATION",
    "Address": "HARBOUR PLACE, 103 SOUTH CHURCH ST",
    "City": "GEORGETOWN",
    "Branch": "",
    "Postcode": "KY1-1108",
    "Country": "Cayman Islands",
    "Connection": "Active"
  }
]
module.exports = caymanIslands
