const chile = [
  {
    "bankCode": "CHAS",
    "countryCode": "CL",
    "branchCode": "LRM",
    "SWIFT Code": "CHASCLRM",
    "Bank Name": "JPMORGAN CHASE BANK, N.A., SANTIAGO BRANCH",
    "Address": "AV. APOQUINDO 2827, FLOOR 13, LAS CONDES",
    "City": "SANTIAGO",
    "Branch": "",
    "Postcode": "7590956",
    "Country": "Chile",
    "Connection": "Active"
  },
  {
    "bankCode": "CHAS",
    "countryCode": "CL",
    "branchCode": "ICM",
    "SWIFT Code": "CHASCLRMICM",
    "Bank Name": "JPMORGAN CHASE BANK, N.A., SANTIAGO BRANCH",
    "Address": "AV. APOQUINDO 2827, FLOOR 13, LAS CONDES",
    "City": "SANTIAGO",
    "Branch": "INVERSIONES JP MORGAN LIMITADA",
    "Postcode": "7590956",
    "Country": "Chile",
    "Connection": "Active"
  },
  {
    "bankCode": "CHAS",
    "countryCode": "CL",
    "branchCode": "AMM",
    "SWIFT Code": "CHASCLRMAMM",
    "Bank Name": "JPMORGAN CHASE BANK, N.A., SANTIAGO BRANCH",
    "Address": "AV. APOQUINDO 2827, FLOOR 13, LAS CONDES",
    "City": "SANTIAGO",
    "Branch": "JP MORGAN ASSET MANAGEMENT INVESTMENT CH",
    "Postcode": "7590956",
    "Country": "Chile",
    "Connection": "Active"
  },
  {
    "bankCode": "CHAS",
    "countryCode": "CL",
    "branchCode": "CDB",
    "SWIFT Code": "CHASCLRMCDB",
    "Bank Name": "JPMORGAN CHASE BANK, N.A., SANTIAGO BRANCH",
    "Address": "AV. APOQUINDO 2827, FLOOR 13, LAS CONDES",
    "City": "SANTIAGO",
    "Branch": "JPMORGAN CORREDORES DE BOLSA SPA",
    "Postcode": "7590956",
    "Country": "Chile",
    "Connection": "Active"
  },
  {
    "bankCode": "MAGD",
    "countryCode": "CL",
    "branchCode": "LRM",
    "SWIFT Code": "MAGDCLRM",
    "Bank Name": "MONEDA S.A. ADMINISTRADORA GENERAL DE FONDOS",
    "Address": "AVENIDA ISIDORA GOYENECHEA 3621,, FLOOR 8",
    "City": "SANTIAGO",
    "Branch": "",
    "Postcode": "8320000",
    "Country": "Chile",
    "Connection": "Active"
  },
  {
    "bankCode": "BKSA",
    "countryCode": "CL",
    "branchCode": "064",
    "SWIFT Code": "BKSACLRM064",
    "Bank Name": "SCOTIABANK CHILE",
    "Address": "21 DE MAYO 187",
    "City": "ARICA",
    "Branch": "",
    "Postcode": "1000000",
    "Country": "Chile",
    "Connection": "Active"
  },
  {
    "bankCode": "BKSA",
    "countryCode": "CL",
    "branchCode": "068",
    "SWIFT Code": "BKSACLRM068",
    "Bank Name": "SCOTIABANK CHILE",
    "Address": "O'HIGGINS 487",
    "City": "CONCEPCION",
    "Branch": "",
    "Postcode": "4030000",
    "Country": "Chile",
    "Connection": "Active"
  },
  {
    "bankCode": "BKSA",
    "countryCode": "CL",
    "branchCode": "055",
    "SWIFT Code": "BKSACLRM055",
    "Bank Name": "SCOTIABANK CHILE",
    "Address": "MORANDE 226, FLOOR 4",
    "City": "SANTIAGO",
    "Branch": "",
    "Postcode": "8320000",
    "Country": "Chile",
    "Connection": "Active"
  },
  {
    "bankCode": "BKSA",
    "countryCode": "CL",
    "branchCode": "LRM",
    "SWIFT Code": "BKSACLRM",
    "Bank Name": "SCOTIABANK CHILE",
    "Address": "AVENIDA COSTANERA SUR 2710, FLOOR 10 EDIFICIO PARQUE TITANIUM, TORRE A",
    "City": "SANTIAGO",
    "Branch": "",
    "Postcode": "8320000",
    "Country": "Chile",
    "Connection": "Active"
  },
  {
    "bankCode": "BKSA",
    "countryCode": "CL",
    "branchCode": "061",
    "SWIFT Code": "BKSACLRM061",
    "Bank Name": "SCOTIABANK CHILE",
    "Address": "",
    "City": "VALPARAISO",
    "Branch": "",
    "Postcode": "2340000",
    "Country": "Chile",
    "Connection": "Active"
  },
  {
    "bankCode": "FTLN",
    "countryCode": "CL",
    "branchCode": "LRM",
    "SWIFT Code": "FTLNCLRM",
    "Bank Name": "TANNER SERVICIOS FINANCIEROS S.A.",
    "Address": "HUERFANOS 863, FLOOR 3",
    "City": "SANTIAGO",
    "Branch": "",
    "Postcode": "8320176",
    "Country": "Chile",
    "Connection": "Active"
  },
  {
    "bankCode": "AFNT",
    "countryCode": "CL",
    "branchCode": "LRS",
    "SWIFT Code": "AFNTCLRS",
    "Bank Name": "ADMINISTRADORA DE FONDOS DE PENSIONES CAPITAL S.A.",
    "Address": "AVENIDA APOQUINDO 4820",
    "City": "SANTIAGO",
    "Branch": "",
    "Postcode": "7560969",
    "Country": "Chile",
    "Connection": "Active"
  },
  {
    "bankCode": "AFPP",
    "countryCode": "CL",
    "branchCode": "LR2",
    "SWIFT Code": "AFPPCLR2",
    "Bank Name": "ADMINISTRADORA DE FONDOS DE PENSIONES PROVIDA S.A.",
    "Address": "AVENIDA PEDRO DE VALDIVIA 100,, FLOOR 9 PROVIDENCIA",
    "City": "SANTIAGO",
    "Branch": "",
    "Postcode": "7580502",
    "Country": "Chile",
    "Connection": "Active"
  },
  {
    "bankCode": "AGDS",
    "countryCode": "CL",
    "branchCode": "LRS",
    "SWIFT Code": "AGDSCLRS",
    "Bank Name": "ADMINISTRADORA GENERAL DE FONDOS SURA S.A.",
    "Address": "AV. APOQUINDO 4820, FLOOR 15",
    "City": "SANTIAGO",
    "Branch": "",
    "Postcode": "8320000",
    "Country": "Chile",
    "Connection": "Active"
  },
  {
    "bankCode": "AAVL",
    "countryCode": "CL",
    "branchCode": "LR9",
    "SWIFT Code": "AAVLCLR9",
    "Bank Name": "AFEX AGENTES DE VALORES LIMITADA",
    "Address": "BURGOS 80, FLOOR 1",
    "City": "SANTIAGO",
    "Branch": "",
    "Postcode": "7550143",
    "Country": "Chile",
    "Connection": "Active"
  },
  {
    "bankCode": "AFPC",
    "countryCode": "CL",
    "branchCode": "LRS",
    "SWIFT Code": "AFPCCLRS",
    "Bank Name": "AFP CUPRUM, S.A.",
    "Address": "AV. APOQUINDO 3600, 601, FLOOR 6",
    "City": "SANTIAGO",
    "Branch": "",
    "Postcode": "7550108",
    "Country": "Chile",
    "Connection": "Active"
  },
  {
    "bankCode": "BICE",
    "countryCode": "CL",
    "branchCode": "LRM",
    "SWIFT Code": "BICECLRM",
    "Bank Name": "BANCO BICE",
    "Address": "AVENIDA APOQUINDO 3846",
    "City": "SANTIAGO",
    "Branch": "",
    "Postcode": "7550000",
    "Country": "Chile",
    "Connection": "Active"
  },
  {
    "bankCode": "BPAB",
    "countryCode": "CL",
    "branchCode": "LRM",
    "SWIFT Code": "BPABCLRM",
    "Bank Name": "BANCO BTG PACTUAL CHILE",
    "Address": "AVENIDA COSTANERA SUR 2730, P.19, PARQUE TITANIUM, TORRE B, LAS CONDES",
    "City": "SANTIAGO",
    "Branch": "",
    "Postcode": "7550177",
    "Country": "Chile",
    "Connection": "Active"
  },
  {
    "bankCode": "BCEC",
    "countryCode": "CL",
    "branchCode": "LRM",
    "SWIFT Code": "BCECCLRM",
    "Bank Name": "BANCO CENTRAL DE CHILE",
    "Address": "AGUSTINAS 1180",
    "City": "SANTIAGO",
    "Branch": "",
    "Postcode": "8340454",
    "Country": "Chile",
    "Connection": "Active"
  },
  {
    "bankCode": "BCEC",
    "countryCode": "CL",
    "branchCode": "LRR",
    "SWIFT Code": "BCECCLRR",
    "Bank Name": "BANCO CENTRAL DE CHILE",
    "Address": "AGUSTINAS 1180",
    "City": "SANTIAGO",
    "Branch": "",
    "Postcode": "8320000",
    "Country": "Chile",
    "Connection": "Active"
  },
  {
    "bankCode": "BCEC",
    "countryCode": "CL",
    "branchCode": "LR2",
    "SWIFT Code": "BCECCLR2",
    "Bank Name": "BANCO CENTRAL DE CHILE",
    "Address": "AGUSTINAS 1180",
    "City": "SANTIAGO",
    "Branch": "",
    "Postcode": "8340454",
    "Country": "Chile",
    "Connection": "Active"
  },
  {
    "bankCode": "BCEC",
    "countryCode": "CL",
    "branchCode": "LRD",
    "SWIFT Code": "BCECCLRD",
    "Bank Name": "BANCO CENTRAL DE CHILE",
    "Address": "AGUSTINAS 1180",
    "City": "SANTIAGO",
    "Branch": "",
    "Postcode": "6500590",
    "Country": "Chile",
    "Connection": "Active"
  },
  {
    "bankCode": "BCEC",
    "countryCode": "CL",
    "branchCode": "LRF",
    "SWIFT Code": "BCECCLRF",
    "Bank Name": "BANCO CENTRAL DE CHILE",
    "Address": "AGUSTINAS 1180",
    "City": "SANTIAGO",
    "Branch": "",
    "Postcode": "8320000",
    "Country": "Chile",
    "Connection": "Active"
  },
  {
    "bankCode": "BCEC",
    "countryCode": "CL",
    "branchCode": "CSH",
    "SWIFT Code": "BCECCLRMCSH",
    "Bank Name": "BANCO CENTRAL DE CHILE",
    "Address": "AGUSTINAS 1180",
    "City": "SANTIAGO",
    "Branch": "BANCO CENTRAL DE CHILE CASH (BCCH)",
    "Postcode": "8340454",
    "Country": "Chile",
    "Connection": "Active"
  },
  {
    "bankCode": "BCEC",
    "countryCode": "CL",
    "branchCode": "FCE",
    "SWIFT Code": "BCECCLRMFCE",
    "Bank Name": "BANCO CENTRAL DE CHILE",
    "Address": "AGUSTINAS 1180",
    "City": "SANTIAGO",
    "Branch": "FISCO DE LA REPUBLICA DE CHILE FCE",
    "Postcode": "8340454",
    "Country": "Chile",
    "Connection": "Active"
  },
  {
    "bankCode": "BCEC",
    "countryCode": "CL",
    "branchCode": "FES",
    "SWIFT Code": "BCECCLRMFES",
    "Bank Name": "BANCO CENTRAL DE CHILE",
    "Address": "AGUSTINAS 1180",
    "City": "SANTIAGO",
    "Branch": "FISCO DE LA REPUBLICA DE CHILE FEES",
    "Postcode": "8340454",
    "Country": "Chile",
    "Connection": "Active"
  },
  {
    "bankCode": "BCEC",
    "countryCode": "CL",
    "branchCode": "FRP",
    "SWIFT Code": "BCECCLRMFRP",
    "Bank Name": "BANCO CENTRAL DE CHILE",
    "Address": "AGUSTINAS 1180",
    "City": "SANTIAGO",
    "Branch": "FISCO DE LA REPUBLICA DE CHILE FRP",
    "Postcode": "8340454",
    "Country": "Chile",
    "Connection": "Active"
  },
  {
    "bankCode": "MNEX",
    "countryCode": "CL",
    "branchCode": "LRM",
    "SWIFT Code": "MNEXCLRM",
    "Bank Name": "BANCO CONSORCIO",
    "Address": "AV EL BOSQUE SUR 130, FLOOR 7, CONSORCIO, LAS CONDES",
    "City": "SANTIAGO",
    "Branch": "",
    "Postcode": "8320000",
    "Country": "Chile",
    "Connection": "Active"
  },
  {
    "bankCode": "BCHI",
    "countryCode": "CL",
    "branchCode": "LRM",
    "SWIFT Code": "BCHICLRM",
    "Bank Name": "BANCO DE CHILE",
    "Address": "PASEO AHUMADA 251",
    "City": "SANTIAGO",
    "Branch": "",
    "Postcode": "8320000",
    "Country": "Chile",
    "Connection": "Active"
  },
  {
    "bankCode": "BCHI",
    "countryCode": "CL",
    "branchCode": "CUS",
    "SWIFT Code": "BCHICLRMCUS",
    "Bank Name": "BANCO DE CHILE",
    "Address": "AHUMADA 251",
    "City": "SANTIAGO",
    "Branch": "CUSTODY",
    "Postcode": "8320000",
    "Country": "Chile",
    "Connection": "Active"
  },
  {
    "bankCode": "BCHI",
    "countryCode": "CL",
    "branchCode": "EXP",
    "SWIFT Code": "BCHICLRMEXP",
    "Bank Name": "BANCO DE CHILE",
    "Address": "",
    "City": "SANTIAGO",
    "Branch": "EXPORT",
    "Postcode": "8320000",
    "Country": "Chile",
    "Connection": "Active"
  },
  {
    "bankCode": "BCHI",
    "countryCode": "CL",
    "branchCode": "IMP",
    "SWIFT Code": "BCHICLRMIMP",
    "Bank Name": "BANCO DE CHILE",
    "Address": "",
    "City": "SANTIAGO",
    "Branch": "IMPORT HEAD OFFICE",
    "Postcode": "8320000",
    "Country": "Chile",
    "Connection": "Active"
  },
  {
    "bankCode": "BCHI",
    "countryCode": "CL",
    "branchCode": "IOB",
    "SWIFT Code": "BCHICLRMIOB",
    "Bank Name": "BANCO DE CHILE",
    "Address": "",
    "City": "SANTIAGO",
    "Branch": "IMPORT OTHER SANTIAGO BRANCHES",
    "Postcode": "8320000",
    "Country": "Chile",
    "Connection": "Active"
  },
  {
    "bankCode": "CRED",
    "countryCode": "CL",
    "branchCode": "LRM",
    "SWIFT Code": "CREDCLRM",
    "Bank Name": "BANCO DE CREDITO E INVERSIONES",
    "Address": "HUERFANOS 1134",
    "City": "SANTIAGO",
    "Branch": "",
    "Postcode": "8320000",
    "Country": "Chile",
    "Connection": "Active"
  },
  {
    "bankCode": "BECH",
    "countryCode": "CL",
    "branchCode": "LRM",
    "SWIFT Code": "BECHCLRM",
    "Bank Name": "BANCO DEL ESTADO DE CHILE",
    "Address": "AVDA LIBERTADOR BERNARDO O'HIG 1111",
    "City": "SANTIAGO",
    "Branch": "",
    "Postcode": "8320000",
    "Country": "Chile",
    "Connection": "Active"
  },
  {
    "bankCode": "FALA",
    "countryCode": "CL",
    "branchCode": "LRM",
    "SWIFT Code": "FALACLRM",
    "Bank Name": "BANCO FALABELLA",
    "Address": "MONEDA 970, FLOOR 9, EDIFICIO EUROCENTRO",
    "City": "SANTIAGO",
    "Branch": "",
    "Postcode": "8320313",
    "Country": "Chile",
    "Connection": "Active"
  },
  {
    "bankCode": "BICH",
    "countryCode": "CL",
    "branchCode": "LRM",
    "SWIFT Code": "BICHCLRM",
    "Bank Name": "BANCO INTERNACIONAL",
    "Address": "APOQUINDO 6750",
    "City": "SANTIAGO",
    "Branch": "",
    "Postcode": "8320000",
    "Country": "Chile",
    "Connection": "Active"
  },
  {
    "bankCode": "CONB",
    "countryCode": "CL",
    "branchCode": "LRM",
    "SWIFT Code": "CONBCLRM",
    "Bank Name": "BANCO ITAU CHILE",
    "Address": "PRESIDENTE RIESCO 5537, FLOOR 7, EDIFICIO NUEVA LAS CONDES, LAS CONDES",
    "City": "SANTIAGO",
    "Branch": "",
    "Postcode": "7561127",
    "Country": "Chile",
    "Connection": "Active"
  },
  {
    "bankCode": "ITAU",
    "countryCode": "CL",
    "branchCode": "LRM",
    "SWIFT Code": "ITAUCLRM",
    "Bank Name": "BANCO ITAU CHILE",
    "Address": "PRESIDENTE RIESCO 5537, FLOOR 7, EDIFICIO NUEVA LAS CONDES, LAS CONDES",
    "City": "SANTIAGO",
    "Branch": "",
    "Postcode": "7561127",
    "Country": "Chile",
    "Connection": "Active"
  },
  {
    "bankCode": "ITAU",
    "countryCode": "CL",
    "branchCode": "SSO",
    "SWIFT Code": "ITAUCLRMSSO",
    "Bank Name": "BANCO ITAU CHILE",
    "Address": "",
    "City": "SANTIAGO",
    "Branch": "SECURITY SERVICES",
    "Postcode": "8320000",
    "Country": "Chile",
    "Connection": "Active"
  },
  {
    "bankCode": "RPLY",
    "countryCode": "CL",
    "branchCode": "LRM",
    "SWIFT Code": "RPLYCLRM",
    "Bank Name": "BANCO RIPLEY",
    "Address": "ALONSO DE CORDOVA 5320, FLOOR 10",
    "City": "SANTIAGO",
    "Branch": "",
    "Postcode": "8320000",
    "Country": "Chile",
    "Connection": "Active"
  },
  {
    "bankCode": "BSCH",
    "countryCode": "CL",
    "branchCode": "LRM",
    "SWIFT Code": "BSCHCLRM",
    "Bank Name": "BANCO SANTANDER CHILE",
    "Address": "BANDERA 140",
    "City": "SANTIAGO",
    "Branch": "",
    "Postcode": "8320000",
    "Country": "Chile",
    "Connection": "Active"
  },
  {
    "bankCode": "BSCH",
    "countryCode": "CL",
    "branchCode": "GST",
    "SWIFT Code": "BSCHCLRMGST",
    "Bank Name": "BANCO SANTANDER CHILE",
    "Address": "BOMBERO OSSA 1068, FLOOR 7",
    "City": "SANTIAGO",
    "Branch": "GLOBAL CUSTODY DEPARTMENT",
    "Postcode": "8320000",
    "Country": "Chile",
    "Connection": "Active"
  },
  {
    "bankCode": "BSCL",
    "countryCode": "CL",
    "branchCode": "LRM",
    "SWIFT Code": "BSCLCLRM",
    "Bank Name": "BANCO SECURITY",
    "Address": "AGUSTINAS 621",
    "City": "SANTIAGO",
    "Branch": "",
    "Postcode": "8320000",
    "Country": "Chile",
    "Connection": "Active"
  },
  {
    "bankCode": "BKCH",
    "countryCode": "CL",
    "branchCode": "LRM",
    "SWIFT Code": "BKCHCLRM",
    "Bank Name": "BANK OF CHINA, AGENCIA EN CHILE",
    "Address": "AVENIDA ANDRES BELLO 2457, FLOOR 16, COSTANERA CENTER TORRE DOS, PROVIDENCIA",
    "City": "SANTIAGO",
    "Branch": "",
    "Postcode": "7510689",
    "Country": "Chile",
    "Connection": "Active"
  },
  {
    "bankCode": "BATS",
    "countryCode": "CL",
    "branchCode": "LR3",
    "SWIFT Code": "BATSCLR3",
    "Bank Name": "BAT CHILE S.A",
    "Address": "AVENIDA SUIZA",
    "City": "SANTIAGO",
    "Branch": "",
    "Postcode": "8320000",
    "Country": "Chile",
    "Connection": "Active"
  },
  {
    "bankCode": "BATS",
    "countryCode": "CL",
    "branchCode": "LR2",
    "SWIFT Code": "BATSCLR2",
    "Bank Name": "BRITISH AMERICAN TOBACCO CHILE OPERACIONES S.A.",
    "Address": "RUTA 68 S/N, FUNDO LA ROTUNDA",
    "City": "CASABLANCA",
    "Branch": "",
    "Postcode": "2480000",
    "Country": "Chile",
    "Connection": "Active"
  },
  {
    "bankCode": "ECCV",
    "countryCode": "CL",
    "branchCode": "LRM",
    "SWIFT Code": "ECCVCLRM",
    "Bank Name": "CCLV, CONTRAPARTE CENTRAL S.A.",
    "Address": "LA BOLSA 64",
    "City": "SANTIAGO",
    "Branch": "",
    "Postcode": "8340721",
    "Country": "Chile",
    "Connection": "Active"
  },
  {
    "bankCode": "ECCV",
    "countryCode": "CL",
    "branchCode": "LRS",
    "SWIFT Code": "ECCVCLRS",
    "Bank Name": "CCLV, CONTRAPARTE CENTRAL S.A.",
    "Address": "LA BOLSA 64",
    "City": "SANTIAGO",
    "Branch": "",
    "Postcode": "8340721",
    "Country": "Chile",
    "Connection": "Active"
  },
  {
    "bankCode": "CCTU",
    "countryCode": "CL",
    "branchCode": "LRR",
    "SWIFT Code": "CCTUCLRR",
    "Bank Name": "CENTRO DE COMPENSACION AUTOMATIZADO S.A.",
    "Address": "MIRAFLORES 222, FLOOR 12",
    "City": "SANTIAGO",
    "Branch": "",
    "Postcode": "8320000",
    "Country": "Chile",
    "Connection": "Active"
  },
  {
    "bankCode": "PCBC",
    "countryCode": "CL",
    "branchCode": "LRM",
    "SWIFT Code": "PCBCCLRM",
    "Bank Name": "CHINA CONSTRUCTION BANK,  AGENCIA EN CHILE",
    "Address": "ISIDORA CONYENECHEA 2800",
    "City": "SANTIAGO",
    "Branch": "",
    "Postcode": "7550083",
    "Country": "Chile",
    "Connection": "Active"
  },
  {
    "bankCode": "PCBC",
    "countryCode": "CL",
    "branchCode": "CLR",
    "SWIFT Code": "PCBCCLRMCLR",
    "Bank Name": "CHINA CONSTRUCTION BANK,  AGENCIA EN CHILE",
    "Address": "ISIDORA CONYENECHEA 2800",
    "City": "SANTIAGO",
    "Branch": "COMMERCIAL CLIENT",
    "Postcode": "7550083",
    "Country": "Chile",
    "Connection": "Active"
  },
  {
    "bankCode": "PCCA",
    "countryCode": "CL",
    "branchCode": "LRZ",
    "SWIFT Code": "PCCACLRZ",
    "Bank Name": "COMBANC S.A.",
    "Address": "CERRO COLORADO 5240, FLOOR 8-A",
    "City": "SANTIAGO",
    "Branch": "",
    "Postcode": "7550229",
    "Country": "Chile",
    "Connection": "Active"
  },
  {
    "bankCode": "PCCA",
    "countryCode": "CL",
    "branchCode": "LR2",
    "SWIFT Code": "PCCACLR2",
    "Bank Name": "COMBANC S.A.",
    "Address": "CERRO COLORADO 5240, FLOOR 8, TORRE 2",
    "City": "SANTIAGO",
    "Branch": "",
    "Postcode": "8320000",
    "Country": "Chile",
    "Connection": "Active"
  },
  {
    "bankCode": "PCCA",
    "countryCode": "CL",
    "branchCode": "LRM",
    "SWIFT Code": "PCCACLRM",
    "Bank Name": "COMBANC S.A.",
    "Address": "CERRO COLORADO 5240, FLOOR 8, TORRE DEL PARQUE II",
    "City": "SANTIAGO",
    "Branch": "",
    "Postcode": "7560995",
    "Country": "Chile",
    "Connection": "Active"
  },
  {
    "bankCode": "CDER",
    "countryCode": "CL",
    "branchCode": "LRG",
    "SWIFT Code": "CDERCLRG",
    "Bank Name": "COMDER CONTRAPARTE CENTRAL S.A.",
    "Address": "CERRO COLORADO 5240, FLOOR 18, TORRES DEL PARQUE I",
    "City": "SANTIAGO",
    "Branch": "",
    "Postcode": "7560591",
    "Country": "Chile",
    "Connection": "Active"
  },
  {
    "bankCode": "CDER",
    "countryCode": "CL",
    "branchCode": "LRM",
    "SWIFT Code": "CDERCLRM",
    "Bank Name": "COMDER CONTRAPARTE CENTRAL S.A.",
    "Address": "CERRO COLORADO 5240, FLOOR 18, EDIFICIO TORRES DEL PARQUE 1",
    "City": "SANTIAGO",
    "Branch": "",
    "Postcode": "7560995",
    "Country": "Chile",
    "Connection": "Active"
  },
  {
    "bankCode": "DCVV",
    "countryCode": "CL",
    "branchCode": "LRM",
    "SWIFT Code": "DCVVCLRM",
    "Bank Name": "DEPOSITO CENTRAL DE VALORES S.A.",
    "Address": "APOQUINDO 4001, FLOOR 12",
    "City": "SANTIAGO",
    "Branch": "",
    "Postcode": "8320000",
    "Country": "Chile",
    "Connection": "Active"
  },
  {
    "bankCode": "ENLC",
    "countryCode": "CL",
    "branchCode": "LRM",
    "SWIFT Code": "ENLCCLRM",
    "Bank Name": "ENEL CHILE S.A.",
    "Address": "AVENIDA SANTA ROSA 76, FLOOR 15, EDIFICIO ENEL",
    "City": "SANTIAGO",
    "Branch": "",
    "Postcode": "8330099",
    "Country": "Chile",
    "Connection": "Active"
  },
  {
    "bankCode": "FNOB",
    "countryCode": "CL",
    "branchCode": "LR2",
    "SWIFT Code": "FNOBCLR2",
    "Bank Name": "FINANZAS Y NEGOCIOS S.A. CORREDORES DE BOLSA",
    "Address": "ISIDORA GOYENECHEA 3477, FLOOR 11, LAS CONDES",
    "City": "SANTIAGO",
    "Branch": "",
    "Postcode": "7550106",
    "Country": "Chile",
    "Connection": "Active"
  },
  {
    "bankCode": "BLIC",
    "countryCode": "CL",
    "branchCode": "LRM",
    "SWIFT Code": "BLICCLRM",
    "Bank Name": "HSBC BANK (CHILE)",
    "Address": "AVENIDA ISIDORA GOYENECHEA 2800, LAS CONDES, FLOOR 23",
    "City": "SANTIAGO",
    "Branch": "",
    "Postcode": "8320000",
    "Country": "Chile",
    "Connection": "Active"
  }
]
module.exports = chile
