const colombia = [
  {
    "bankCode": "CHAS",
    "countryCode": "CO",
    "branchCode": "FIA",
    "SWIFT Code": "CHASCOBBFIA",
    "Bank Name": "BANCO J.P. MORGAN COLOMBIA S.A.",
    "Address": "CARRERA 11, 84 - 09",
    "City": "BOGOTA",
    "Branch": "JP MORGAN OVERSEAS CAPITAL LLC - COLOMBIA",
    "Postcode": "110221",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "CHAS",
    "countryCode": "CO",
    "branchCode": "WSP",
    "SWIFT Code": "CHASCOBBWSP",
    "Bank Name": "BANCO J.P. MORGAN COLOMBIA S.A.",
    "Address": "CARRERA 11, 84 - 09",
    "City": "BOGOTA",
    "Branch": "JPM COLOMBIA BRANCH FOR WHOLESALE PAYMENTS",
    "Postcode": "110221",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "CHAS",
    "countryCode": "CO",
    "branchCode": "MAC",
    "SWIFT Code": "CHASCOBBMAC",
    "Bank Name": "BANCO J.P. MORGAN COLOMBIA S.A.",
    "Address": "CARRERA 11, 84 - 09",
    "City": "BOGOTA",
    "Branch": "PATRIMONIO AUTONOMO MACONDO",
    "Postcode": "110221",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "PICH",
    "countryCode": "CO",
    "branchCode": "OBB",
    "SWIFT Code": "PICHCOBB",
    "Bank Name": "BANCO PICHINCHA S.A.",
    "Address": "CARRERA 11, 92-09, FLOOR 4",
    "City": "BOGOTA",
    "Branch": "",
    "Postcode": "110221",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "BPOP",
    "countryCode": "CO",
    "branchCode": "AXM",
    "SWIFT Code": "BPOPCOBBAXM",
    "Bank Name": "BANCO POPULAR SA - COLOMBIA",
    "Address": "",
    "City": "ARMENIA",
    "Branch": "",
    "Postcode": "",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "BPOP",
    "countryCode": "CO",
    "branchCode": "BAQ",
    "SWIFT Code": "BPOPCOBBBAQ",
    "Bank Name": "BANCO POPULAR SA - COLOMBIA",
    "Address": "",
    "City": "BARRANQUILLA",
    "Branch": "ZONA NORTE",
    "Postcode": "",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "BPOP",
    "countryCode": "CO",
    "branchCode": "OBB",
    "SWIFT Code": "BPOPCOBB",
    "Bank Name": "BANCO POPULAR SA - COLOMBIA",
    "Address": "CALLE 17, 7-43, FLOOR 3",
    "City": "BOGOTA",
    "Branch": "HEADQUARTERS",
    "Postcode": "110321",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "BPOP",
    "countryCode": "CO",
    "branchCode": "BO1",
    "SWIFT Code": "BPOPCOBBBO1",
    "Bank Name": "BANCO POPULAR SA - COLOMBIA",
    "Address": "",
    "City": "BOGOTA",
    "Branch": "ZONA 1",
    "Postcode": "",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "BPOP",
    "countryCode": "CO",
    "branchCode": "BO2",
    "SWIFT Code": "BPOPCOBBBO2",
    "Bank Name": "BANCO POPULAR SA - COLOMBIA",
    "Address": "",
    "City": "BOGOTA",
    "Branch": "ZONA 2",
    "Postcode": "",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {},
  {
    "bankCode": "BPOP",
    "countryCode": "CO",
    "branchCode": "BGA",
    "SWIFT Code": "BPOPCOBBBGA",
    "Bank Name": "BANCO POPULAR SA - COLOMBIA",
    "Address": "",
    "City": "BUCARAMANGA",
    "Branch": "ZONA ORIENTAL",
    "Postcode": "",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "BPOP",
    "countryCode": "CO",
    "branchCode": "CL1",
    "SWIFT Code": "BPOPCOBBCL1",
    "Bank Name": "BANCO POPULAR SA - COLOMBIA",
    "Address": "",
    "City": "CALI",
    "Branch": "ZONA SUR",
    "Postcode": "",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "BPOP",
    "countryCode": "CO",
    "branchCode": "CTG",
    "SWIFT Code": "BPOPCOBBCTG",
    "Bank Name": "BANCO POPULAR SA - COLOMBIA",
    "Address": "",
    "City": "CARTAGENA",
    "Branch": "",
    "Postcode": "",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {},
  {
    "bankCode": "BPOP",
    "countryCode": "CO",
    "branchCode": "MZ1",
    "SWIFT Code": "BPOPCOBBMZ1",
    "Bank Name": "BANCO POPULAR SA - COLOMBIA",
    "Address": "",
    "City": "MANIZALES",
    "Branch": "",
    "Postcode": "",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {},
  {
    "bankCode": "BPOP",
    "countryCode": "CO",
    "branchCode": "PEI",
    "SWIFT Code": "BPOPCOBBPEI",
    "Bank Name": "BANCO POPULAR SA - COLOMBIA",
    "Address": "",
    "City": "PEREIRA",
    "Branch": "",
    "Postcode": "",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "BPOP",
    "countryCode": "CO",
    "branchCode": "ADZ",
    "SWIFT Code": "BPOPCOBBADZ",
    "Bank Name": "BANCO POPULAR SA - COLOMBIA",
    "Address": "",
    "City": "SAN ANDRES",
    "Branch": "",
    "Postcode": "",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {},
  {
    "bankCode": "SERZ",
    "countryCode": "CO",
    "branchCode": "OBB",
    "SWIFT Code": "SERZCOBB",
    "Bank Name": "BANCO SERFINANZA S.A.",
    "Address": "CALLE 72, 54-35, EDIFICIOSERFINANZA, FLOOR 5",
    "City": "BARRANQUILLA",
    "Branch": "",
    "Postcode": "080001",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "GYDV",
    "countryCode": "CO",
    "branchCode": "OBC",
    "SWIFT Code": "GYDVCOBC",
    "Bank Name": "BANCO UNION S.A. (FORMERLY GIROS Y FINANZAS)",
    "Address": "CL 4  SAN FERNANDO, 27 52",
    "City": "CALI",
    "Branch": "",
    "Postcode": "760043",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "COLO",
    "countryCode": "CO",
    "branchCode": "BAQ",
    "SWIFT Code": "COLOCOBMBAQ",
    "Bank Name": "BANCOLOMBIA S.A.",
    "Address": "CARRERA 57, 72-25, EDIFICIO FINCAR, FLOOR 7",
    "City": "BARRANQUILLA",
    "Branch": "",
    "Postcode": "080001",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "COLO",
    "countryCode": "CO",
    "branchCode": "BGA",
    "SWIFT Code": "COLOCOBMBGA",
    "Bank Name": "BANCOLOMBIA S.A.",
    "Address": "CARRERA 18, 35-02",
    "City": "BUCARAMANGA",
    "Branch": "",
    "Postcode": "680006",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "COLO",
    "countryCode": "CO",
    "branchCode": "CL1",
    "SWIFT Code": "COLOCOBMCL1",
    "Bank Name": "BANCOLOMBIA S.A.",
    "Address": "CALLE 19, 2N-49, EDIFICIO TORRE DE CALI, FLOOR 9",
    "City": "CALI",
    "Branch": "",
    "Postcode": "760044",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "COLO",
    "countryCode": "CO",
    "branchCode": "CTG",
    "SWIFT Code": "COLOCOBMCTG",
    "Bank Name": "BANCOLOMBIA S.A.",
    "Address": "LA MATUNA EDIFICIO",
    "City": "CARTAGENA",
    "Branch": "",
    "Postcode": "130001",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "COLO",
    "countryCode": "CO",
    "branchCode": "MD1",
    "SWIFT Code": "COLOCOBMMD1",
    "Bank Name": "BANCOLOMBIA S.A.",
    "Address": "CALLE 50, 51-01",
    "City": "MEDELLIN",
    "Branch": "",
    "Postcode": "050010",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "COLO",
    "countryCode": "CO",
    "branchCode": "OBM",
    "SWIFT Code": "COLOCOBM",
    "Bank Name": "BANCOLOMBIA S.A.",
    "Address": "CARRERA 52, 50-20, FLOOR 9",
    "City": "MEDELLIN",
    "Branch": "",
    "Postcode": "050020",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "COLO",
    "countryCode": "CO",
    "branchCode": "PEI",
    "SWIFT Code": "COLOCOBMPEI",
    "Bank Name": "BANCOLOMBIA S.A.",
    "Address": "CARRERA 8, 17-50",
    "City": "PEREIRA",
    "Branch": "",
    "Postcode": "660002",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "FBBV",
    "countryCode": "CO",
    "branchCode": "OBB",
    "SWIFT Code": "FBBVCOBB",
    "Bank Name": "BBVA ASSET MANAGEMENT S.A., SOCIEDAD FIDUCIARIA",
    "Address": "CARRERA 9, 72-21, FLOOR 3",
    "City": "BOGOTA",
    "Branch": "",
    "Postcode": "110221",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "BNPA",
    "countryCode": "CO",
    "branchCode": "PEN",
    "SWIFT Code": "BNPACOBBPEN",
    "Bank Name": "BNP PARIBAS COLOMBIA CORPORACION FINANCIERA S.A.",
    "Address": "",
    "City": "BOGOTA",
    "Branch": "",
    "Postcode": "",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "BNPA",
    "countryCode": "CO",
    "branchCode": "OBB",
    "SWIFT Code": "BNPACOBB",
    "Bank Name": "BNP PARIBAS COLOMBIA CORPORACION FINANCIERA S.A.",
    "Address": "CARRERA 7, 77-07, EDIFICIO TORRE, FLOOR 11",
    "City": "BOGOTA",
    "Branch": "",
    "Postcode": "110221",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "BNPA",
    "countryCode": "CO",
    "branchCode": "MXN",
    "SWIFT Code": "BNPACOBBMXN",
    "Bank Name": "BNP PARIBAS COLOMBIA CORPORACION FINANCIERA S.A.",
    "Address": "CARRERA 7, 77-07, EDIFICIO TORRE, FLOOR 11",
    "City": "BOGOTA",
    "Branch": "",
    "Postcode": "110221",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "BNPA",
    "countryCode": "CO",
    "branchCode": "CHL",
    "SWIFT Code": "BNPACOBBCHL",
    "Bank Name": "BNP PARIBAS COLOMBIA CORPORACION FINANCIERA S.A.",
    "Address": "CARRERA 7, 77-07, EDIFICIO TORRE, FLOOR 11",
    "City": "BOGOTA",
    "Branch": "BNP PARIBAS SECURITIES SERVICES CHILE",
    "Postcode": "110221",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {},
  {
    "bankCode": "BNPA",
    "countryCode": "CO",
    "branchCode": "B2S",
    "SWIFT Code": "BNPACOBBB2S",
    "Bank Name": "BNP PARIBAS COLOMBIA CORPORACION FINANCIERA S.A.",
    "Address": "",
    "City": "BOGOTA",
    "Branch": "SECURITIES SERVICES",
    "Postcode": "",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "CCSF",
    "countryCode": "CO",
    "branchCode": "OBB",
    "SWIFT Code": "CCSFCOBB",
    "Bank Name": "CAJA COLOMBIANA DE SUBSIDIO FAMILIAR COLSUBSIDIO",
    "Address": "CALLE 26, 25-50",
    "City": "BOGOTA",
    "Branch": "",
    "Postcode": "111811",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "CCFO",
    "countryCode": "CO",
    "branchCode": "OBN",
    "SWIFT Code": "CCFOCOBN",
    "Bank Name": "CAJA DE COMPENSACION FAMILIAR DE ANTIOQUIA COMFAMA",
    "Address": "CARRERA 45, NO. 49 A 16",
    "City": "MEDELLIN",
    "Branch": "",
    "Postcode": "050012",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "CCDC",
    "countryCode": "CO",
    "branchCode": "OBB",
    "SWIFT Code": "CCDCCOBB",
    "Bank Name": "CAMARA DE RIESGO CENTRAL DE CONTRAPARTE DE COLOMBIA S.A.",
    "Address": "CARRERA 7, 71-21, TORRE B",
    "City": "BOGOTA",
    "Branch": "",
    "Postcode": "110121",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "CTAE",
    "countryCode": "CO",
    "branchCode": "OBC",
    "SWIFT Code": "CTAECOBC",
    "Bank Name": "CARTONES AMERICA S.A. CAME",
    "Address": "CALLE 70N, 2A-130",
    "City": "CALI",
    "Branch": "",
    "Postcode": "760006",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "CTYS",
    "countryCode": "CO",
    "branchCode": "OBC",
    "SWIFT Code": "CTYSCOBC",
    "Bank Name": "CARVAJAL SERVICIOS S.AS.",
    "Address": "",
    "City": "CALI",
    "Branch": "",
    "Postcode": "",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "CBLA",
    "countryCode": "CO",
    "branchCode": "OB2",
    "SWIFT Code": "CBLACOB2",
    "Bank Name": "CASA DE BOLSA S.A. SOCIEDAD COMISIONISTA DE BOLSA",
    "Address": "CARRERA 13, 26-45, EDIFICIO CORFICOLOMBIANA, FLOOR 5",
    "City": "BOGOTA",
    "Branch": "",
    "Postcode": "110311",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "CITI",
    "countryCode": "CO",
    "branchCode": "OBB",
    "SWIFT Code": "CITICOBB",
    "Bank Name": "CITIBANK COLOMBIA",
    "Address": "CALLE CRA 9A, EDIFICIO",
    "City": "BOGOTA",
    "Branch": "",
    "Postcode": "111831",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "CLTE",
    "countryCode": "CO",
    "branchCode": "OBM",
    "SWIFT Code": "CLTECOBM",
    "Bank Name": "COLTEFINANCIERA S.A. COMPANIA DE FINANCIAMIENTO COMERCIAL",
    "Address": "CALE 52, 47-42, ED. COLTEJEER, FLOOR 11",
    "City": "MEDELLIN",
    "Branch": "",
    "Postcode": "050012",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {},
  {
    "bankCode": "CFVA",
    "countryCode": "CO",
    "branchCode": "BAQ",
    "SWIFT Code": "CFVACOBCBAQ",
    "Bank Name": "CORPORACION FINANCIERA COLOMBIANA (FORMERLY CORPORACION FINANCIERA DEL VALLE S.A.)",
    "Address": "",
    "City": "BARRANQUILLA",
    "Branch": "BARRANQUILLA AGENCY",
    "Postcode": "",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "CFVA",
    "countryCode": "CO",
    "branchCode": "BO1",
    "SWIFT Code": "CFVACOBCBO1",
    "Bank Name": "CORPORACION FINANCIERA COLOMBIANA (FORMERLY CORPORACION FINANCIERA DEL VALLE S.A.)",
    "Address": "",
    "City": "BOGOTA",
    "Branch": "BOGOTA AGENCY",
    "Postcode": "",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "CFVA",
    "countryCode": "CO",
    "branchCode": "FXO",
    "SWIFT Code": "CFVACOBCFXO",
    "Bank Name": "CORPORACION FINANCIERA COLOMBIANA (FORMERLY CORPORACION FINANCIERA DEL VALLE S.A.)",
    "Address": "",
    "City": "CALI",
    "Branch": "",
    "Postcode": "",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "CFVA",
    "countryCode": "CO",
    "branchCode": "OBC",
    "SWIFT Code": "CFVACOBC",
    "Bank Name": "CORPORACION FINANCIERA COLOMBIANA (FORMERLY CORPORACION FINANCIERA DEL VALLE S.A.)",
    "Address": "CALLE 10, 4-47, FLOOR 23",
    "City": "CALI",
    "Branch": "HEADQUARTERS",
    "Postcode": "760044",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "CFVA",
    "countryCode": "CO",
    "branchCode": "CL1",
    "SWIFT Code": "CFVACOBCCL1",
    "Bank Name": "CORPORACION FINANCIERA COLOMBIANA (FORMERLY CORPORACION FINANCIERA DEL VALLE S.A.)",
    "Address": "",
    "City": "CALI",
    "Branch": "INTERNATIONAL BRANCH",
    "Postcode": "",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "CFVA",
    "countryCode": "CO",
    "branchCode": "MD1",
    "SWIFT Code": "CFVACOBCMD1",
    "Bank Name": "CORPORACION FINANCIERA COLOMBIANA (FORMERLY CORPORACION FINANCIERA DEL VALLE S.A.)",
    "Address": "",
    "City": "MEDELLIN",
    "Branch": "MEDELLIN AGENCY",
    "Postcode": "",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "AFES",
    "countryCode": "CO",
    "branchCode": "OBM",
    "SWIFT Code": "AFESCOBM",
    "Bank Name": "ADMINISTRADORA DE FONDOS DE PENSIONES Y CESANTIA PROTECCION S.A.",
    "Address": "CALLE 49, 63-100",
    "City": "MEDELLIN",
    "Branch": "",
    "Postcode": "",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "AFIU",
    "countryCode": "CO",
    "branchCode": "OBB",
    "SWIFT Code": "AFIUCOBB",
    "Bank Name": "ALIANZA FIDUCIARIA",
    "Address": "CARRERA 15, 82-99",
    "City": "BOGOTA",
    "Branch": "",
    "Postcode": "110221",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "HUBC",
    "countryCode": "CO",
    "branchCode": "OBB",
    "SWIFT Code": "HUBCCOBB",
    "Bank Name": "ALLIANCE ENTERPRISE S.A.S.",
    "Address": "CRA 11B, 99-25",
    "City": "BOGOTA",
    "Branch": "",
    "Postcode": "110221",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "HUBC",
    "countryCode": "CO",
    "branchCode": "LWE",
    "SWIFT Code": "HUBCCOBBLWE",
    "Bank Name": "ALLIANCE ENTERPRISE S.A.S.",
    "Address": "CRA. 9, 79-A-19, FLOOR 6",
    "City": "BOGOTA",
    "Branch": "LOWE SSP-3 SA",
    "Postcode": "110221",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "COZV",
    "countryCode": "CO",
    "branchCode": "OBB",
    "SWIFT Code": "COZVCOBB",
    "Bank Name": "ALLIANZ SEGUROS DE VIDA S.A.",
    "Address": "CRA 13A, 29-24",
    "City": "BOGOTA",
    "Branch": "",
    "Postcode": "110141",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "FPVC",
    "countryCode": "CO",
    "branchCode": "OBB",
    "SWIFT Code": "FPVCCOBB",
    "Bank Name": "ALLIANZ SEGUROS DE VIDA S.A.",
    "Address": "CRA 13A, 29-24",
    "City": "BOGOTA",
    "Branch": "",
    "Postcode": "110141",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "COZS",
    "countryCode": "CO",
    "branchCode": "OBB",
    "SWIFT Code": "COZSCOBB",
    "Bank Name": "ALLIANZ SEGUROS S.A.",
    "Address": "CRA 13A, 29-24",
    "City": "BOGOTA",
    "Branch": "",
    "Postcode": "110141",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "GEXI",
    "countryCode": "CO",
    "branchCode": "OBB",
    "SWIFT Code": "GEXICOBB",
    "Bank Name": "ALMACENES EXITO S.A. (GRUPO EXITO)",
    "Address": "CARRERA 48, 32BSUR139",
    "City": "ENVIGADO",
    "Branch": "",
    "Postcode": "055421",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "AIPA",
    "countryCode": "CO",
    "branchCode": "OBB",
    "SWIFT Code": "AIPACOBB",
    "Bank Name": "ALPINA PRODUCTOS ALIMENTICIOS SA BIC",
    "Address": "SOPO, 3",
    "City": "BOGOTA",
    "Branch": "",
    "Postcode": "251001",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "CCAI",
    "countryCode": "CO",
    "branchCode": "OBB",
    "SWIFT Code": "CCAICOBB",
    "Bank Name": "BANCO AGRARIO DE COLOMBIA S.A. (FORMERLY CAJA DE CREDITO AGRARIO INDUSTRIAL Y MINERO)",
    "Address": "CARRERA 8, 15-43, FLOOR 12",
    "City": "BOGOTA",
    "Branch": "",
    "Postcode": "110321",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "GERO",
    "countryCode": "CO",
    "branchCode": "OBB",
    "SWIFT Code": "GEROCOBB",
    "Bank Name": "BANCO BILBAO VIZCAYA ARGENTARIA COLOMBIA S.A.",
    "Address": "CARRERA 9, 72-21, FLOOR 5",
    "City": "BOGOTA",
    "Branch": "",
    "Postcode": "110011",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "GERO",
    "countryCode": "CO",
    "branchCode": "BO1",
    "SWIFT Code": "GEROCOBBBO1",
    "Bank Name": "BANCO BILBAO VIZCAYA ARGENTARIA COLOMBIA S.A.",
    "Address": "",
    "City": "BOGOTA",
    "Branch": "HEADQUARTERS",
    "Postcode": "",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "BPAB",
    "countryCode": "CO",
    "branchCode": "OBB",
    "SWIFT Code": "BPABCOBB",
    "Bank Name": "BANCO BTG PACTUAL COLOMBIA S.A.",
    "Address": "CRA 43 A, 1, 50, SAN FERNANDO PLAZA TORRE 2, FLOOR 10",
    "City": "MEDELLIN",
    "Branch": "",
    "Postcode": "050022",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "CASO",
    "countryCode": "CO",
    "branchCode": "OBB",
    "SWIFT Code": "CASOCOBB",
    "Bank Name": "BANCO CAJA SOCIAL",
    "Address": "CARRERA 7, 77-65, FLOOR 6",
    "City": "BOGOTA",
    "Branch": "",
    "Postcode": "110221",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "BAVI",
    "countryCode": "CO",
    "branchCode": "OBB",
    "SWIFT Code": "BAVICOBB",
    "Bank Name": "BANCO COMERCIAL AV VILLAS S.A.",
    "Address": "CRA 13, 26 A 47",
    "City": "BOGOTA",
    "Branch": "",
    "Postcode": "110311",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "CAFE",
    "countryCode": "CO",
    "branchCode": "BAQ",
    "SWIFT Code": "CAFECOBBBAQ",
    "Bank Name": "BANCO DAVIVIENDA S.A.(FORMERLY GRANBANCO BANCAFE S.A.)",
    "Address": "CARRERA 55, 72-109, FLOOR 5",
    "City": "BARRANQUILLA",
    "Branch": "",
    "Postcode": "080001",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "CAFE",
    "countryCode": "CO",
    "branchCode": "OBB",
    "SWIFT Code": "CAFECOBB",
    "Bank Name": "BANCO DAVIVIENDA S.A.(FORMERLY GRANBANCO BANCAFE S.A.)",
    "Address": "AVENIDA EL DORADO, 68 C-61, BANCAFE BUILDING, FLOOR 10",
    "City": "BOGOTA",
    "Branch": "",
    "Postcode": "110931",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "CAFE",
    "countryCode": "CO",
    "branchCode": "CL1",
    "SWIFT Code": "CAFECOBBCL1",
    "Bank Name": "BANCO DAVIVIENDA S.A.(FORMERLY GRANBANCO BANCAFE S.A.)",
    "Address": "CALLE 13, 5-21",
    "City": "CALI",
    "Branch": "",
    "Postcode": "760044",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "CAFE",
    "countryCode": "CO",
    "branchCode": "MD1",
    "SWIFT Code": "CAFECOBBMD1",
    "Bank Name": "BANCO DAVIVIENDA S.A.(FORMERLY GRANBANCO BANCAFE S.A.)",
    "Address": "CALLE 49, 50-51",
    "City": "MEDELLIN",
    "Branch": "",
    "Postcode": "050015",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "BBOG",
    "countryCode": "CO",
    "branchCode": "BAQ",
    "SWIFT Code": "BBOGCOBBBAQ",
    "Bank Name": "BANCO DE BOGOTA",
    "Address": "",
    "City": "BARRANQUILLA",
    "Branch": "",
    "Postcode": "",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "BBOG",
    "countryCode": "CO",
    "branchCode": "OBB",
    "SWIFT Code": "BBOGCOBB",
    "Bank Name": "BANCO DE BOGOTA",
    "Address": "CALLE 36, NO. 7-47",
    "City": "BOGOTA",
    "Branch": "",
    "Postcode": "110821",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "BBOG",
    "countryCode": "CO",
    "branchCode": "BO1",
    "SWIFT Code": "BBOGCOBBBO1",
    "Bank Name": "BANCO DE BOGOTA",
    "Address": "",
    "City": "BOGOTA",
    "Branch": "HEADQUARTERS OFFICES",
    "Postcode": "",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "BBOG",
    "countryCode": "CO",
    "branchCode": "BGA",
    "SWIFT Code": "BBOGCOBBBGA",
    "Bank Name": "BANCO DE BOGOTA",
    "Address": "",
    "City": "BUCARAMANGA",
    "Branch": "",
    "Postcode": "",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "BBOG",
    "countryCode": "CO",
    "branchCode": "CL1",
    "SWIFT Code": "BBOGCOBBCL1",
    "Bank Name": "BANCO DE BOGOTA",
    "Address": "",
    "City": "CALI",
    "Branch": "",
    "Postcode": "",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "BBOG",
    "countryCode": "CO",
    "branchCode": "CTG",
    "SWIFT Code": "BBOGCOBBCTG",
    "Bank Name": "BANCO DE BOGOTA",
    "Address": "",
    "City": "CARTAGENA",
    "Branch": "",
    "Postcode": "",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "BBOG",
    "countryCode": "CO",
    "branchCode": "CUC",
    "SWIFT Code": "BBOGCOBBCUC",
    "Bank Name": "BANCO DE BOGOTA",
    "Address": "",
    "City": "CUCUTA",
    "Branch": "",
    "Postcode": "",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "BBOG",
    "countryCode": "CO",
    "branchCode": "MZ1",
    "SWIFT Code": "BBOGCOBBMZ1",
    "Bank Name": "BANCO DE BOGOTA",
    "Address": "",
    "City": "MANIZALES",
    "Branch": "",
    "Postcode": "",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "BBOG",
    "countryCode": "CO",
    "branchCode": "MD1",
    "SWIFT Code": "BBOGCOBBMD1",
    "Bank Name": "BANCO DE BOGOTA",
    "Address": "",
    "City": "MEDELLIN",
    "Branch": "",
    "Postcode": "",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "BBOG",
    "countryCode": "CO",
    "branchCode": "PEI",
    "SWIFT Code": "BBOGCOBBPEI",
    "Bank Name": "BANCO DE BOGOTA",
    "Address": "",
    "City": "PEREIRA",
    "Branch": "",
    "Postcode": "",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "BBOG",
    "countryCode": "CO",
    "branchCode": "ADZ",
    "SWIFT Code": "BBOGCOBBADZ",
    "Bank Name": "BANCO DE BOGOTA",
    "Address": "",
    "City": "SAN ANDRES",
    "Branch": "",
    "Postcode": "",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "BCEX",
    "countryCode": "CO",
    "branchCode": "OBB",
    "SWIFT Code": "BCEXCOBB",
    "Bank Name": "BANCO DE COMERCIO EXTERIOR DE COLOMBIA S.A.",
    "Address": "CALLE 28, 13 A 15, FLOOR 40",
    "City": "BOGOTA",
    "Branch": "",
    "Postcode": "110311",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "BREP",
    "countryCode": "CO",
    "branchCode": "OBB",
    "SWIFT Code": "BREPCOBB",
    "Bank Name": "BANCO DE LA REPUBLICA",
    "Address": "CARRERA 7, 14-78, FLOOR 2",
    "City": "BOGOTA",
    "Branch": "",
    "Postcode": "110111",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "OCCI",
    "countryCode": "CO",
    "branchCode": "BAQ",
    "SWIFT Code": "OCCICOBCBAQ",
    "Bank Name": "BANCO DE OCCIDENTE",
    "Address": "",
    "City": "BARRANQUILLA",
    "Branch": "",
    "Postcode": "",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "OCCI",
    "countryCode": "CO",
    "branchCode": "BO2",
    "SWIFT Code": "OCCICOBCBO2",
    "Bank Name": "BANCO DE OCCIDENTE",
    "Address": "",
    "City": "BOGOTA",
    "Branch": "",
    "Postcode": "",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "OCCI",
    "countryCode": "CO",
    "branchCode": "BGA",
    "SWIFT Code": "OCCICOBCBGA",
    "Bank Name": "BANCO DE OCCIDENTE",
    "Address": "",
    "City": "BUCARAMANGA",
    "Branch": "",
    "Postcode": "",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "OCCI",
    "countryCode": "CO",
    "branchCode": "CL1",
    "SWIFT Code": "OCCICOBCCL1",
    "Bank Name": "BANCO DE OCCIDENTE",
    "Address": "",
    "City": "CALI",
    "Branch": "BRANCH",
    "Postcode": "",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "OCCI",
    "countryCode": "CO",
    "branchCode": "OBC",
    "SWIFT Code": "OCCICOBC",
    "Bank Name": "BANCO DE OCCIDENTE",
    "Address": "CARRERA 4, 7-61, FLOOR 12",
    "City": "CALI",
    "Branch": "HEADQUARTERS",
    "Postcode": "760044",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "OCCI",
    "countryCode": "CO",
    "branchCode": "CTG",
    "SWIFT Code": "OCCICOBCCTG",
    "Bank Name": "BANCO DE OCCIDENTE",
    "Address": "",
    "City": "CARTAGENA",
    "Branch": "",
    "Postcode": "",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "OCCI",
    "countryCode": "CO",
    "branchCode": "MD4",
    "SWIFT Code": "OCCICOBCMD4",
    "Bank Name": "BANCO DE OCCIDENTE",
    "Address": "",
    "City": "MEDELLIN",
    "Branch": "",
    "Postcode": "",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "OCCI",
    "countryCode": "CO",
    "branchCode": "ADZ",
    "SWIFT Code": "OCCICOBCADZ",
    "Bank Name": "BANCO DE OCCIDENTE",
    "Address": "",
    "City": "SAN ANDRES",
    "Branch": "",
    "Postcode": "",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "FALA",
    "countryCode": "CO",
    "branchCode": "OBT",
    "SWIFT Code": "FALACOBT",
    "Bank Name": "BANCO FALABELLA SA",
    "Address": "AVENIDA NO 120-71, 19",
    "City": "BOGOTA",
    "Branch": "",
    "Postcode": "",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "BSUD",
    "countryCode": "CO",
    "branchCode": "BAQ",
    "SWIFT Code": "BSUDCOBBBAQ",
    "Bank Name": "BANCO GNB SUDAMERIS",
    "Address": "",
    "City": "BARRANQUILLA",
    "Branch": "",
    "Postcode": "",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "BSUD",
    "countryCode": "CO",
    "branchCode": "OBB",
    "SWIFT Code": "BSUDCOBB",
    "Bank Name": "BANCO GNB SUDAMERIS",
    "Address": "CARRERA 8, 15-42, FLOOR 3",
    "City": "BOGOTA",
    "Branch": "",
    "Postcode": "110010",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "BSUD",
    "countryCode": "CO",
    "branchCode": "BGA",
    "SWIFT Code": "BSUDCOBBBGA",
    "Bank Name": "BANCO GNB SUDAMERIS",
    "Address": "",
    "City": "BUCARAMANGA",
    "Branch": "",
    "Postcode": "",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "BSUD",
    "countryCode": "CO",
    "branchCode": "CL1",
    "SWIFT Code": "BSUDCOBBCL1",
    "Bank Name": "BANCO GNB SUDAMERIS",
    "Address": "",
    "City": "CALI",
    "Branch": "",
    "Postcode": "",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "BSUD",
    "countryCode": "CO",
    "branchCode": "CTG",
    "SWIFT Code": "BSUDCOBBCTG",
    "Bank Name": "BANCO GNB SUDAMERIS",
    "Address": "",
    "City": "CARTAGENA",
    "Branch": "",
    "Postcode": "",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "BSUD",
    "countryCode": "CO",
    "branchCode": "MZ1",
    "SWIFT Code": "BSUDCOBBMZ1",
    "Bank Name": "BANCO GNB SUDAMERIS",
    "Address": "",
    "City": "MANIZALES",
    "Branch": "",
    "Postcode": "",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "BSUD",
    "countryCode": "CO",
    "branchCode": "MD1",
    "SWIFT Code": "BSUDCOBBMD1",
    "Bank Name": "BANCO GNB SUDAMERIS",
    "Address": "",
    "City": "MEDELLIN",
    "Branch": "",
    "Postcode": "",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "CHAS",
    "countryCode": "CO",
    "branchCode": "OBB",
    "SWIFT Code": "CHASCOBB",
    "Bank Name": "BANCO J.P. MORGAN COLOMBIA S.A.",
    "Address": "CARRERA 11, 84 - 09, TORRE AMADEUS, FLOOR 7",
    "City": "BOGOTA",
    "Branch": "",
    "Postcode": "110221",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "CHAS",
    "countryCode": "CO",
    "branchCode": "LIM",
    "SWIFT Code": "CHASCOBBLIM",
    "Bank Name": "BANCO J.P. MORGAN COLOMBIA S.A.",
    "Address": "CARRERA 11, 84 - 09",
    "City": "BOGOTA",
    "Branch": "JP MORGAN COLOMBIA LIMITADA",
    "Postcode": "110221",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "CRRD",
    "countryCode": "CO",
    "branchCode": "OBB",
    "SWIFT Code": "CRRDCOBB",
    "Bank Name": "CORREDORES DAVIVIENDA S.A.COMISIONISTA DE BOLSA",
    "Address": "CARRERA 7, 71-52, LOS VENADOS BUILDING, TORRE B, FLOOR 11",
    "City": "BOGOTA",
    "Branch": "",
    "Postcode": "110231",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "CRVL",
    "countryCode": "CO",
    "branchCode": "OBB",
    "SWIFT Code": "CRVLCOBB",
    "Bank Name": "CREDICORP CAPITAL COLOMBIA S.A.",
    "Address": "CALLE 34, 6-65",
    "City": "BOGOTA",
    "Branch": "",
    "Postcode": "110311",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "CRVL",
    "countryCode": "CO",
    "branchCode": "COF",
    "SWIFT Code": "CRVLCOBBCOF",
    "Bank Name": "CREDICORP CAPITAL COLOMBIA S.A.",
    "Address": "CALLE 34, 6-65",
    "City": "BOGOTA",
    "Branch": "CORFIOPERATION",
    "Postcode": "",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "CRVL",
    "countryCode": "CO",
    "branchCode": "FID",
    "SWIFT Code": "CRVLCOBBFID",
    "Bank Name": "CREDICORP CAPITAL COLOMBIA S.A.",
    "Address": "CALLE 34, 6-65",
    "City": "BOGOTA",
    "Branch": "NEGOCIOS FIDUCIARIOS",
    "Postcode": "110311",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "ECOP",
    "countryCode": "CO",
    "branchCode": "OBB",
    "SWIFT Code": "ECOPCOBB",
    "Bank Name": "ECOPETROL S.A.",
    "Address": "CARRERA 13, 36 - 24, EDIFICIO PRINCIPALL",
    "City": "BOGOTA",
    "Branch": "",
    "Postcode": "110311",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "ETBC",
    "countryCode": "CO",
    "branchCode": "OBB",
    "SWIFT Code": "ETBCCOBB",
    "Bank Name": "EMPRESA DE TELECOMUNICACIONES DE BOGOTA S.A E.SP.",
    "Address": "CRA 8, 20 56",
    "City": "BOGOTA",
    "Branch": "",
    "Postcode": "110311",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "CDEA",
    "countryCode": "CO",
    "branchCode": "OBB",
    "SWIFT Code": "CDEACOBB",
    "Bank Name": "ENEL COLOMBIA S.A. E.S.P",
    "Address": "CALLE 93, 13 45, FLOOR 1",
    "City": "BOGOTA",
    "Branch": "",
    "Postcode": "110221",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "FDBC",
    "countryCode": "CO",
    "branchCode": "OBM",
    "SWIFT Code": "FDBCCOBM",
    "Bank Name": "FIDUCIARIA BANCOLOMBIA",
    "Address": "CARRERA 48, 26-85, TORRE SUR, SECTOR E, FLOOR 10",
    "City": "MEDELLIN",
    "Branch": "",
    "Postcode": "050021",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "FBOG",
    "countryCode": "CO",
    "branchCode": "OBB",
    "SWIFT Code": "FBOGCOBB",
    "Bank Name": "FIDUCIARIA BOGOTA",
    "Address": "STREET 67, 7-37, BUILDING CARACOL, FLOOR 3",
    "City": "BOGOTA",
    "Branch": "",
    "Postcode": "110231",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "FCOI",
    "countryCode": "CO",
    "branchCode": "OBB",
    "SWIFT Code": "FCOICOBB",
    "Bank Name": "FIDUCIARIA CORFICOLOMBIANA S.A.",
    "Address": "CALLE 10, 4 47, FLOOR 20",
    "City": "CALI",
    "Branch": "",
    "Postcode": "760044",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "FIDV",
    "countryCode": "CO",
    "branchCode": "OBB",
    "SWIFT Code": "FIDVCOBB",
    "Bank Name": "FIDUCIARIA DAVIVIENDA S.A.",
    "Address": "AVENIDA EL DORADO, 68 B 85, TORRE SURAMERICANA, FLOOR 2",
    "City": "BOGOTA",
    "Branch": "",
    "Postcode": "110931",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "FDOC",
    "countryCode": "CO",
    "branchCode": "OBB",
    "SWIFT Code": "FDOCCOBB",
    "Bank Name": "FIDUCIARIA DE OCCIDENTE",
    "Address": "CARRERA 13, 27-47, EDIFICIO BANCO DE OCCIDENTE, 9",
    "City": "BOGOTA",
    "Branch": "",
    "Postcode": "111821",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "FENS",
    "countryCode": "CO",
    "branchCode": "OBB",
    "SWIFT Code": "FENSCOBB",
    "Bank Name": "FINANCIERA DE DESARROLLO NACIONAL S.A. FORMALLY FINANCIERA ENERGETICA NACIONAL S.A.-FEN",
    "Address": "CARRERA 7, 71-52, TORRE B, FLOOR 6",
    "City": "BOGOTA",
    "Branch": "",
    "Postcode": "110231",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "FOGI",
    "countryCode": "CO",
    "branchCode": "OBB",
    "SWIFT Code": "FOGICOBB",
    "Bank Name": "FONDO DE GARANTIAS DE INSTITUCIONES FINANCIERAS",
    "Address": "CARRERA 7, 35-40",
    "City": "BOGOTA",
    "Branch": "",
    "Postcode": "110111",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "FLAR",
    "countryCode": "CO",
    "branchCode": "OBB",
    "SWIFT Code": "FLARCOBB",
    "Bank Name": "FONDO LATINOAMERICANO DE RESERVAS",
    "Address": "84A 12-18, FLOOR 7",
    "City": "BOGOTA",
    "Branch": "",
    "Postcode": "110221",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "FLAR",
    "countryCode": "CO",
    "branchCode": "OBG",
    "SWIFT Code": "FLARCOBG",
    "Bank Name": "FONDO LATINOAMERICANO DE RESERVAS",
    "Address": "CALLE 84 A, 12-18, FLOOR 7",
    "City": "BOGOTA",
    "Branch": "",
    "Postcode": "110221",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "HCOL",
    "countryCode": "CO",
    "branchCode": "OBB",
    "SWIFT Code": "HCOLCOBB",
    "Bank Name": "HOCOL S.A.",
    "Address": "CARRERA 7, 113 45, TORRE SAMSUNG, FLOOR 16",
    "City": "BOGOTA",
    "Branch": "",
    "Postcode": "110111",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "ISGN",
    "countryCode": "CO",
    "branchCode": "OBM",
    "SWIFT Code": "ISGNCOBM",
    "Bank Name": "ISAGEN S.A. E.S.P.",
    "Address": "CARRERA 30, 10C-280",
    "City": "MEDELLIN",
    "Branch": "",
    "Postcode": "050021",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "BCTO",
    "countryCode": "CO",
    "branchCode": "BAQ",
    "SWIFT Code": "BCTOCOBBBAQ",
    "Bank Name": "ITAU COLOMBIA S.A.",
    "Address": "CARRA 54, 72-73",
    "City": "BARRANQUILLA",
    "Branch": "",
    "Postcode": "080020",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "BCTO",
    "countryCode": "CO",
    "branchCode": "OBB",
    "SWIFT Code": "BCTOCOBB",
    "Bank Name": "ITAU COLOMBIA S.A.",
    "Address": "CARRERA 7, 99-53, PISO 18",
    "City": "BOGOTA",
    "Branch": "",
    "Postcode": "110221",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "BCTO",
    "countryCode": "CO",
    "branchCode": "CL1",
    "SWIFT Code": "BCTOCOBBCL1",
    "Bank Name": "ITAU COLOMBIA S.A.",
    "Address": "CALLE 13, 4-13",
    "City": "CALI",
    "Branch": "",
    "Postcode": "760044",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "BCTO",
    "countryCode": "CO",
    "branchCode": "MD1",
    "SWIFT Code": "BCTOCOBBMD1",
    "Bank Name": "ITAU COLOMBIA S.A.",
    "Address": "CARRERA 46, 53-44",
    "City": "MEDELLIN",
    "Branch": "",
    "Postcode": "050012",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "MAPF",
    "countryCode": "CO",
    "branchCode": "OBB",
    "SWIFT Code": "MAPFCOBB",
    "Bank Name": "MAPFRE SEGUROS GENERALES DE COLOMBIA S.A.",
    "Address": "CARRERA 14, 96- 34",
    "City": "BOGOTA",
    "Branch": "",
    "Postcode": "110111",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "MSCL",
    "countryCode": "CO",
    "branchCode": "OBC",
    "SWIFT Code": "MSCLCOBC",
    "Bank Name": "MUNICIPIO SANTIAGO DE CALI",
    "Address": "AVENIDA 2 NORTE, 10-70, CENTRO ADMINISTRATIVO MUNICIPAL, 1",
    "City": "CALI",
    "Branch": "",
    "Postcode": "760045",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "OCEN",
    "countryCode": "CO",
    "branchCode": "OBB",
    "SWIFT Code": "OCENCOBB",
    "Bank Name": "OLEODUCTO CENTRAL S.A.",
    "Address": "LA CABRERA, 84-09, 11 FLOOR 10",
    "City": "BOGOTA",
    "Branch": "",
    "Postcode": "110221",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "PORV",
    "countryCode": "CO",
    "branchCode": "OBB",
    "SWIFT Code": "PORVCOBB",
    "Bank Name": "PORVENIR S.A.",
    "Address": "CERRERA A 13, 26-65",
    "City": "BOGOTA",
    "Branch": "",
    "Postcode": "110100",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "BSSC",
    "countryCode": "CO",
    "branchCode": "OBB",
    "SWIFT Code": "BSSCCOBB",
    "Bank Name": "SANTANDER CACEIS COLOMBIA S.A. SOCIEDAD FIDUCIARIA",
    "Address": "CALLE 93A, NRO 13-24, EDIFICIO QBO, FLOOR 3",
    "City": "BOGOTA",
    "Branch": "",
    "Postcode": "110221",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "COLP",
    "countryCode": "CO",
    "branchCode": "OBB",
    "SWIFT Code": "COLPCOBB",
    "Bank Name": "SCOTIABANK COLPATRIA S.A.",
    "Address": "CARRERA 7, 24-89, TORRE COLPATRIA, FLOOR 35",
    "City": "BOGOTA",
    "Branch": "",
    "Postcode": "110311",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "VABC",
    "countryCode": "CO",
    "branchCode": "OBM",
    "SWIFT Code": "VABCCOBM",
    "Bank Name": "VALORES BANCOLOMBIA S.A. COMISIONISTA DE BOLSA",
    "Address": "CRA 48, 26-85",
    "City": "MEDELLIN",
    "Branch": "",
    "Postcode": "050021",
    "Country": "Colombia",
    "Connection": "Active"
  },
  {
    "bankCode": "GASN",
    "countryCode": "CO",
    "branchCode": "OBB",
    "SWIFT Code": "GASNCOBB",
    "Bank Name": "VANTI S.A., E.S.P.",
    "Address": "CALLE 72, 5-38, EDIFICIO VANTI, FLOOR 10",
    "City": "BOGOTA",
    "Branch": "",
    "Postcode": "111711",
    "Country": "Colombia",
    "Connection": "Active"
  }
]
module.exports = colombia
