const coteDivoire = [
  {
    "bankCode": "BICI",
    "countryCode": "CI",
    "branchCode": "PLT",
    "SWIFT Code": "BICICIABPLT",
    "Bank Name": "BANQUE INTERNATIONALE POUR LE COMMERCE ET L'INDUSTRIE DE LA COTE D'IVOIRE",
    "Address": "",
    "City": "ABIDJAN",
    "Branch": "PLATEAU",
    "Postcode": "",
    "Country": "Côte D’ivoire",
    "Connection": "Active"
  },
  {
    "bankCode": "BICI",
    "countryCode": "CI",
    "branchCode": "SUD",
    "SWIFT Code": "BICICIABSUD",
    "Bank Name": "BANQUE INTERNATIONALE POUR LE COMMERCE ET L'INDUSTRIE DE LA COTE D'IVOIRE",
    "Address": "",
    "City": "ABIDJAN",
    "Branch": "SUD",
    "Postcode": "",
    "Country": "Côte D’ivoire",
    "Connection": "Active"
  },
  {
    "bankCode": "BICI",
    "countryCode": "CI",
    "branchCode": "BKE",
    "SWIFT Code": "BICICIABBKE",
    "Bank Name": "BANQUE INTERNATIONALE POUR LE COMMERCE ET L'INDUSTRIE DE LA COTE D'IVOIRE",
    "Address": "",
    "City": "BOUAKE",
    "Branch": "",
    "Postcode": "",
    "Country": "Côte D’ivoire",
    "Connection": "Active"
  },
  {
    "bankCode": "BSOI",
    "countryCode": "CI",
    "branchCode": "IAB",
    "SWIFT Code": "BSOICIAB",
    "Bank Name": "BANQUE MALIENNE DE SOLIDARITE COTE D'IVOIRE",
    "Address": "BMS CI HEAD OFFICE, ABIDJAN PLATEAU RUE PARIS VILLAGE",
    "City": "ABIDJAN",
    "Branch": "",
    "Postcode": "",
    "Country": "Côte D’ivoire",
    "Connection": "Active"
  },
  {
    "bankCode": "CSSS",
    "countryCode": "CI",
    "branchCode": "IAB",
    "SWIFT Code": "CSSSCIAB",
    "Bank Name": "BANQUE NATIONALE D'INVESTISSEMENT",
    "Address": "IMMEUBLES SCIAM, AVENUE MARCHAND 01",
    "City": "ABIDJAN",
    "Branch": "",
    "Postcode": "",
    "Country": "Côte D’ivoire",
    "Connection": "Active"
  },
  {
    "bankCode": "CNCG",
    "countryCode": "CI",
    "branchCode": "IAB",
    "SWIFT Code": "CNCGCIAB",
    "Bank Name": "BANQUE POPULAIRE DE COTE D'IVOIRE",
    "Address": "IMMEUBLE SMGL, FLOOR 14 AVENUE JOSEPH ANOMA, RUE DES BANQUES 11",
    "City": "ABIDJAN",
    "Branch": "",
    "Postcode": "",
    "Country": "Côte D’ivoire",
    "Connection": "Active"
  },
  {},
  {
    "bankCode": "BGFI",
    "countryCode": "CI",
    "branchCode": "IAB",
    "SWIFT Code": "BGFICIAB",
    "Bank Name": "BGFIBANK COTE D'IVOIRE",
    "Address": "FACE CAP SUD, BLVD VALERY GISCARD D ESTAING, MARCORY",
    "City": "ABIDJAN",
    "Branch": "",
    "Postcode": "",
    "Country": "Côte D’ivoire",
    "Connection": "Active"
  },
  {
    "bankCode": "BGCD",
    "countryCode": "CI",
    "branchCode": "IAB",
    "SWIFT Code": "BGCDCIAB",
    "Bank Name": "BRIDGE BANK GROUP COTE D'IVOIRE",
    "Address": "AVENUE DU GENERAL DE GAULLE, ABIDJAN PLATEAU",
    "City": "ABIDJAN",
    "Branch": "",
    "Postcode": "",
    "Country": "Côte D’ivoire",
    "Connection": "Active"
  },
  {
    "bankCode": "BSAH",
    "countryCode": "CI",
    "branchCode": "IAB",
    "SWIFT Code": "BSAHCIAB",
    "Bank Name": "BSIC COTE D'IVOIRE",
    "Address": "PLATEAU AVENUE NOGUES",
    "City": "ABIDJAN",
    "Branch": "",
    "Postcode": "",
    "Country": "Côte D’ivoire",
    "Connection": "Active"
  },
  {
    "bankCode": "CITI",
    "countryCode": "CI",
    "branchCode": "IAX",
    "SWIFT Code": "CITICIAX",
    "Bank Name": "CITIBANK COTE D'IVOIRE SA",
    "Address": "IMM. BOTREAU ROUSSEL, AVENUE DELAFOSSE 28",
    "City": "ABIDJAN",
    "Branch": "",
    "Postcode": "",
    "Country": "Côte D’ivoire",
    "Connection": "Active"
  },
  {
    "bankCode": "IBCI",
    "countryCode": "CI",
    "branchCode": "IAB",
    "SWIFT Code": "IBCICIAB",
    "Bank Name": "COFIPA INVESTMENT BANK CI",
    "Address": "IMMEUBLE BOUTREAU ROUSSEL, FLOOR 5, AVENUE DELAFOSSE",
    "City": "ABIDJAN",
    "Branch": "",
    "Postcode": "",
    "Country": "Côte D’ivoire",
    "Connection": "Active"
  },
  {
    "bankCode": "CIVD",
    "countryCode": "CI",
    "branchCode": "IAB",
    "SWIFT Code": "CIVDCIAB",
    "Bank Name": "COMPAGNIE IVOIRIENNE D'ELECTRICITE",
    "Address": "ABIDJAN TREICHEVILLE AVENUE 1",
    "City": "ABIDJAN",
    "Branch": "",
    "Postcode": "",
    "Country": "Côte D’ivoire",
    "Connection": "Active"
  },
  {
    "bankCode": "CORI",
    "countryCode": "CI",
    "branchCode": "IAB",
    "SWIFT Code": "CORICIAB",
    "Bank Name": "CORIS BANK INTERNATIONAL",
    "Address": "BOULEVARD VGE ANGLE BOULEVARD, DELAFOSSE 01 TREICHVILLE ZONE 1",
    "City": "ABIDJAN",
    "Branch": "",
    "Postcode": "",
    "Country": "Côte D’ivoire",
    "Connection": "Active"
  },
  {
    "bankCode": "ECOC",
    "countryCode": "CI",
    "branchCode": "IAB",
    "SWIFT Code": "ECOCCIAB",
    "Bank Name": "ECOBANK - COTE D'IVOIRE S.A.",
    "Address": "IMMEUBLE ALLIANCE, AVENUE TERRASSON DE FOUGERES",
    "City": "ABIDJAN",
    "Branch": "",
    "Postcode": "",
    "Country": "Côte D’ivoire",
    "Connection": "Active"
  },
  {
    "bankCode": "GTBI",
    "countryCode": "CI",
    "branchCode": "IAB",
    "SWIFT Code": "GTBICIAB",
    "Bank Name": "GUARANTY TRUST BANK COTE D'IVOIRE",
    "Address": "GTBANK CI HEAD OFFICE, RUE DU SENATEUR LAGAROSSE 11",
    "City": "ABIDJAN",
    "Branch": "",
    "Postcode": "",
    "Country": "Côte D’ivoire",
    "Connection": "Active"
  },
  {
    "bankCode": "MNSA",
    "countryCode": "CI",
    "branchCode": "IAB",
    "SWIFT Code": "MNSACIAB",
    "Bank Name": "MANSA BANK",
    "Address": "VILLA RIVER FOREST, RUE J41, II PLATEAUX 101, COCODY",
    "City": "ABIDJAN",
    "Branch": "",
    "Postcode": "",
    "Country": "Côte D’ivoire",
    "Connection": "Active"
  },
  {
    "bankCode": "BIAO",
    "countryCode": "CI",
    "branchCode": "GIN",
    "SWIFT Code": "BIAOCIABGIN",
    "Bank Name": "NSIA BANQUE COTE D'IVOIRE (NSIA BANQUE CI)",
    "Address": "AVENUE JOSEPH ANOMA 8-10",
    "City": "ABIDJAN",
    "Branch": "FILIALE GUINEE",
    "Postcode": "",
    "Country": "Côte D’ivoire",
    "Connection": "Active"
  },
  {
    "bankCode": "BIAO",
    "countryCode": "CI",
    "branchCode": "IAB",
    "SWIFT Code": "BIAOCIAB",
    "Bank Name": "NSIA BANQUE COTE D'IVOIRE (NSIA BANQUE CI)",
    "Address": "AVENUE JOSEPH ANOMA 8-10",
    "City": "ABIDJAN",
    "Branch": "HEAD OFFICE",
    "Postcode": "",
    "Country": "Côte D’ivoire",
    "Connection": "Active"
  },
  {
    "bankCode": "BIAO",
    "countryCode": "CI",
    "branchCode": "DMB",
    "SWIFT Code": "BIAOCIABDMB",
    "Bank Name": "NSIA BANQUE COTE D'IVOIRE (NSIA BANQUE CI)",
    "Address": "AVENUE JOSEPH ANOMA 8-10",
    "City": "ABIDJAN",
    "Branch": "SURCURSALE COTE IVOIRE",
    "Postcode": "",
    "Country": "Côte D’ivoire",
    "Connection": "Active"
  },
  {
    "bankCode": "BIAO",
    "countryCode": "CI",
    "branchCode": "032",
    "SWIFT Code": "BIAOCIAB032",
    "Bank Name": "NSIA BANQUE COTE D'IVOIRE (NSIA BANQUE CI)",
    "Address": "",
    "City": "BOUAKE",
    "Branch": "",
    "Postcode": "",
    "Country": "Côte D’ivoire",
    "Connection": "Active"
  },
  {
    "bankCode": "BIAO",
    "countryCode": "CI",
    "branchCode": "034",
    "SWIFT Code": "BIAOCIAB034",
    "Bank Name": "NSIA BANQUE COTE D'IVOIRE (NSIA BANQUE CI)",
    "Address": "",
    "City": "DALOA",
    "Branch": "",
    "Postcode": "",
    "Country": "Côte D’ivoire",
    "Connection": "Active"
  },
  {},
  {},
  {
    "bankCode": "ORBK",
    "countryCode": "CI",
    "branchCode": "BF1",
    "SWIFT Code": "ORBKCIABBF1",
    "Bank Name": "ORABANK COTE D'IVOIRE",
    "Address": "IMMEUBLE BRS ANGLE AVENUE JOSEPH, ANOMA, BOULEVARD DE LA REPUBLIQUE",
    "City": "ABIDJAN",
    "Branch": "ORABANK BURKINA",
    "Postcode": "",
    "Country": "Côte D’ivoire",
    "Connection": "Active"
  },
  {
    "bankCode": "ORBK",
    "countryCode": "CI",
    "branchCode": "ML1",
    "SWIFT Code": "ORBKCIABML1",
    "Bank Name": "ORABANK COTE D'IVOIRE",
    "Address": "IMMEUBLE BRS ANGLE AVENUE JOSEPH, ANOMA, BOULEVARD DE LA REPUBLIQUE",
    "City": "ABIDJAN",
    "Branch": "ORABANK MALI",
    "Postcode": "",
    "Country": "Côte D’ivoire",
    "Connection": "Active"
  },
  {},
  {
    "bankCode": "ORBK",
    "countryCode": "CI",
    "branchCode": "SN2",
    "SWIFT Code": "ORBKCIABSN2",
    "Bank Name": "ORABANK COTE D'IVOIRE",
    "Address": "IMMEUBLE BRS ANGLE AVENUE JOSEPH, ANOMA, BOULEVARD DE LA REPUBLIQUE",
    "City": "ABIDJAN",
    "Branch": "ORABANK SENEGAL",
    "Postcode": "",
    "Country": "Côte D’ivoire",
    "Connection": "Active"
  },
  {
    "bankCode": "ORAC",
    "countryCode": "CI",
    "branchCode": "IAB",
    "SWIFT Code": "ORACCIAB",
    "Bank Name": "ORANGE BANK AFRICA",
    "Address": "IMMEUBLE BAINI, FLOOR 1, RUE LOUIS LUMIERE, ZONE 4",
    "City": "ABIDJAN",
    "Branch": "",
    "Postcode": "",
    "Country": "Côte D’ivoire",
    "Connection": "Active"
  },
  {
    "bankCode": "SGCI",
    "countryCode": "CI",
    "branchCode": "IAB",
    "SWIFT Code": "SGCICIAB",
    "Bank Name": "SOCIETE GENERALE COTE D'IVOIRE",
    "Address": "AVENUE JOSEPH ANOMA 5-7",
    "City": "ABIDJAN",
    "Branch": "",
    "Postcode": "",
    "Country": "Côte D’ivoire",
    "Connection": "Active"
  },
  {
    "bankCode": "SIVB",
    "countryCode": "CI",
    "branchCode": "IAB",
    "SWIFT Code": "SIVBCIAB",
    "Bank Name": "SOCIETE IVOIRIENNE DE BANQUE",
    "Address": "IMMEUBLE ALPHA 2000, BOULEVARD DE LA REPUBLIQUE 34",
    "City": "ABIDJAN",
    "Branch": "SIEGE",
    "Postcode": "",
    "Country": "Côte D’ivoire",
    "Connection": "Active"
  },
  {
    "bankCode": "SBIC",
    "countryCode": "CI",
    "branchCode": "IAB",
    "SWIFT Code": "SBICCIAB",
    "Bank Name": "STANBIC BANK",
    "Address": "IMMEUBLE PLEIN CIEL 7TH, BLVD VALERY GISCARD D ESTAING 26",
    "City": "ABIDJAN",
    "Branch": "",
    "Postcode": "",
    "Country": "Côte D’ivoire",
    "Connection": "Active"
  },
  {
    "bankCode": "SCBL",
    "countryCode": "CI",
    "branchCode": "IAB",
    "SWIFT Code": "SCBLCIAB",
    "Bank Name": "STANDARD CHARTERED BANK COTE D'IVOIRE",
    "Address": "BOULEVARD DE LA REPUBLIQUE 23",
    "City": "ABIDJAN",
    "Branch": "",
    "Postcode": "",
    "Country": "Côte D’ivoire",
    "Connection": "Active"
  },
  {
    "bankCode": "SCBL",
    "countryCode": "CI",
    "branchCode": "SSU",
    "SWIFT Code": "SCBLCIABSSU",
    "Bank Name": "STANDARD CHARTERED BANK COTE D'IVOIRE",
    "Address": "BOULEVARD DE LA REPUBLIQUE 23",
    "City": "ABIDJAN",
    "Branch": "SECURITIES SERVICES",
    "Postcode": "",
    "Country": "Côte D’ivoire",
    "Connection": "Active"
  },
  {},
  {
    "bankCode": "UNAF",
    "countryCode": "CI",
    "branchCode": "IAB",
    "SWIFT Code": "UNAFCIAB",
    "Bank Name": "UNITED BANK FOR AFRICA COTE D'IVOIRE",
    "Address": "KHARRAT BUILDING, BOULEVARD BOTREAU-ROUSSEL",
    "City": "ABIDJAN",
    "Branch": "",
    "Postcode": "17808",
    "Country": "Côte D’ivoire",
    "Connection": "Active"
  },
  {
    "bankCode": "VSBK",
    "countryCode": "CI",
    "branchCode": "IAB",
    "SWIFT Code": "VSBKCIAB",
    "Bank Name": "VERSUS BANK",
    "Address": "IMMEUBLE CRRAE-UMOA, A. BOTREAU ROUSSEL/AVE JOSEPH ANOMA",
    "City": "ABIDJAN",
    "Branch": "",
    "Postcode": "",
    "Country": "Côte D’ivoire",
    "Connection": "Active"
  },
  {
    "bankCode": "AFGI",
    "countryCode": "CI",
    "branchCode": "IAB",
    "SWIFT Code": "AFGICIAB",
    "Bank Name": "AFG BANK COTE D'IVOIRE",
    "Address": "IMMEUBLE MACI, FLOOR 17, LOT 34/35, AVENUE JOSEPH ANOMA 15",
    "City": "ABIDJAN",
    "Branch": "",
    "Postcode": "",
    "Country": "Côte D’ivoire",
    "Connection": "Active"
  },
  {
    "bankCode": "AFDB",
    "countryCode": "CI",
    "branchCode": "SRP",
    "SWIFT Code": "AFDBCIABSRP",
    "Bank Name": "AFRICAN DEVELOPMENT BANK",
    "Address": "",
    "City": "ABIDJAN",
    "Branch": "",
    "Postcode": "",
    "Country": "Côte D’ivoire",
    "Connection": "Active"
  },
  {
    "bankCode": "AFDB",
    "countryCode": "CI",
    "branchCode": "MDT",
    "SWIFT Code": "AFDBCIABMDT",
    "Bank Name": "AFRICAN DEVELOPMENT BANK",
    "Address": "",
    "City": "ABIDJAN",
    "Branch": "",
    "Postcode": "",
    "Country": "Côte D’ivoire",
    "Connection": "Active"
  },
  {
    "bankCode": "AFDB",
    "countryCode": "CI",
    "branchCode": "ITF",
    "SWIFT Code": "AFDBCIABITF",
    "Bank Name": "AFRICAN DEVELOPMENT BANK",
    "Address": "",
    "City": "ABIDJAN",
    "Branch": "",
    "Postcode": "",
    "Country": "Côte D’ivoire",
    "Connection": "Active"
  },
  {
    "bankCode": "AFDB",
    "countryCode": "CI",
    "branchCode": "LTW",
    "SWIFT Code": "AFDBCIABLTW",
    "Bank Name": "AFRICAN DEVELOPMENT BANK",
    "Address": "",
    "City": "ABIDJAN",
    "Branch": "",
    "Postcode": "",
    "Country": "Côte D’ivoire",
    "Connection": "Active"
  },
  {
    "bankCode": "AFDB",
    "countryCode": "CI",
    "branchCode": "AGT",
    "SWIFT Code": "AFDBCIABAGT",
    "Bank Name": "AFRICAN DEVELOPMENT BANK",
    "Address": "",
    "City": "ABIDJAN",
    "Branch": "",
    "Postcode": "",
    "Country": "Côte D’ivoire",
    "Connection": "Active"
  },
  {
    "bankCode": "AFDB",
    "countryCode": "CI",
    "branchCode": "DRC",
    "SWIFT Code": "AFDBCIABDRC",
    "Bank Name": "AFRICAN DEVELOPMENT BANK",
    "Address": "AVENUE JOSEPH ANOMA 10-12",
    "City": "ABIDJAN",
    "Branch": "",
    "Postcode": "",
    "Country": "Côte D’ivoire",
    "Connection": "Active"
  },
  {
    "bankCode": "AFDB",
    "countryCode": "CI",
    "branchCode": "ATF",
    "SWIFT Code": "AFDBCIABATF",
    "Bank Name": "AFRICAN DEVELOPMENT BANK",
    "Address": "AVENUE JOSEPH ANOMA 10-12",
    "City": "ABIDJAN",
    "Branch": "",
    "Postcode": "",
    "Country": "Côte D’ivoire",
    "Connection": "Active"
  },
  {
    "bankCode": "AFDB",
    "countryCode": "CI",
    "branchCode": "AWF",
    "SWIFT Code": "AFDBCIABAWF",
    "Bank Name": "AFRICAN DEVELOPMENT BANK",
    "Address": "AVENUE JOSEPH ANOMA 10-12",
    "City": "ABIDJAN",
    "Branch": "",
    "Postcode": "",
    "Country": "Côte D’ivoire",
    "Connection": "Active"
  },
  {
    "bankCode": "AFDB",
    "countryCode": "CI",
    "branchCode": "CBF",
    "SWIFT Code": "AFDBCIABCBF",
    "Bank Name": "AFRICAN DEVELOPMENT BANK",
    "Address": "AVENUE JOSEPH ANOMA 10-12",
    "City": "ABIDJAN",
    "Branch": "",
    "Postcode": "",
    "Country": "Côte D’ivoire",
    "Connection": "Active"
  },
  {
    "bankCode": "AFDB",
    "countryCode": "CI",
    "branchCode": "FAP",
    "SWIFT Code": "AFDBCIABFAP",
    "Bank Name": "AFRICAN DEVELOPMENT BANK",
    "Address": "AVENUE JOSEPH ANOMA 10-12",
    "City": "ABIDJAN",
    "Branch": "",
    "Postcode": "",
    "Country": "Côte D’ivoire",
    "Connection": "Active"
  },
  {
    "bankCode": "AFDB",
    "countryCode": "CI",
    "branchCode": "MCB",
    "SWIFT Code": "AFDBCIABMCB",
    "Bank Name": "AFRICAN DEVELOPMENT BANK",
    "Address": "AVENUE JOSEPH ANOMA 10-12",
    "City": "ABIDJAN",
    "Branch": "",
    "Postcode": "",
    "Country": "Côte D’ivoire",
    "Connection": "Active"
  },
  {
    "bankCode": "AFDB",
    "countryCode": "CI",
    "branchCode": "NPD",
    "SWIFT Code": "AFDBCIABNPD",
    "Bank Name": "AFRICAN DEVELOPMENT BANK",
    "Address": "AVENUE JOSEPH ANOMA 10-12",
    "City": "ABIDJAN",
    "Branch": "",
    "Postcode": "",
    "Country": "Côte D’ivoire",
    "Connection": "Active"
  },
  {
    "bankCode": "AFDB",
    "countryCode": "CI",
    "branchCode": "SEF",
    "SWIFT Code": "AFDBCIABSEF",
    "Bank Name": "AFRICAN DEVELOPMENT BANK",
    "Address": "AVENUE JOSEPH ANOMA 10-12",
    "City": "ABIDJAN",
    "Branch": "",
    "Postcode": "",
    "Country": "Côte D’ivoire",
    "Connection": "Active"
  },
  {
    "bankCode": "AFDB",
    "countryCode": "CI",
    "branchCode": "SRF",
    "SWIFT Code": "AFDBCIABSRF",
    "Bank Name": "AFRICAN DEVELOPMENT BANK",
    "Address": "AVENUE JOSEPH ANOMA 10-12",
    "City": "ABIDJAN",
    "Branch": "",
    "Postcode": "",
    "Country": "Côte D’ivoire",
    "Connection": "Active"
  },
  {
    "bankCode": "AFDB",
    "countryCode": "CI",
    "branchCode": "ZMD",
    "SWIFT Code": "AFDBCIABZMD",
    "Bank Name": "AFRICAN DEVELOPMENT BANK",
    "Address": "AVENUE JOSEPH ANOMA 10-12",
    "City": "ABIDJAN",
    "Branch": "",
    "Postcode": "",
    "Country": "Côte D’ivoire",
    "Connection": "Active"
  },
  {
    "bankCode": "AFDB",
    "countryCode": "CI",
    "branchCode": "AMI",
    "SWIFT Code": "AFDBCIABAMI",
    "Bank Name": "AFRICAN DEVELOPMENT BANK",
    "Address": "",
    "City": "ABIDJAN",
    "Branch": "",
    "Postcode": "",
    "Country": "Côte D’ivoire",
    "Connection": "Active"
  },
  {
    "bankCode": "AFDB",
    "countryCode": "CI",
    "branchCode": "MIC",
    "SWIFT Code": "AFDBCIABMIC",
    "Bank Name": "AFRICAN DEVELOPMENT BANK",
    "Address": "",
    "City": "ABIDJAN",
    "Branch": "",
    "Postcode": "",
    "Country": "Côte D’ivoire",
    "Connection": "Active"
  },
  {
    "bankCode": "AFDB",
    "countryCode": "CI",
    "branchCode": "FSF",
    "SWIFT Code": "AFDBCIABFSF",
    "Bank Name": "AFRICAN DEVELOPMENT BANK",
    "Address": "",
    "City": "ABIDJAN",
    "Branch": "",
    "Postcode": "",
    "Country": "Côte D’ivoire",
    "Connection": "Active"
  },
  {
    "bankCode": "AFDB",
    "countryCode": "CI",
    "branchCode": "IAB",
    "SWIFT Code": "AFDBCIAB",
    "Bank Name": "AFRICAN DEVELOPMENT BANK",
    "Address": "AVENUE JOSEPH ANOMA 10-12",
    "City": "ABIDJAN",
    "Branch": "",
    "Postcode": "",
    "Country": "Côte D’ivoire",
    "Connection": "Active"
  },
  {
    "bankCode": "AFDB",
    "countryCode": "CI",
    "branchCode": "NTF",
    "SWIFT Code": "AFDBCIABNTF",
    "Bank Name": "AFRICAN DEVELOPMENT BANK",
    "Address": "",
    "City": "ABIDJAN",
    "Branch": "",
    "Postcode": "",
    "Country": "Côte D’ivoire",
    "Connection": "Active"
  },
  {
    "bankCode": "AFDB",
    "countryCode": "CI",
    "branchCode": "PRS",
    "SWIFT Code": "AFDBCIABPRS",
    "Bank Name": "AFRICAN DEVELOPMENT BANK",
    "Address": "",
    "City": "ABIDJAN",
    "Branch": "",
    "Postcode": "",
    "Country": "Côte D’ivoire",
    "Connection": "Active"
  },
  {
    "bankCode": "AFDB",
    "countryCode": "CI",
    "branchCode": "WAT",
    "SWIFT Code": "AFDBCIABWAT",
    "Bank Name": "AFRICAN DEVELOPMENT BANK",
    "Address": "",
    "City": "ABIDJAN",
    "Branch": "",
    "Postcode": "",
    "Country": "Côte D’ivoire",
    "Connection": "Active"
  },
  {
    "bankCode": "AFDB",
    "countryCode": "CI",
    "branchCode": "ADF",
    "SWIFT Code": "AFDBCIABADF",
    "Bank Name": "AFRICAN DEVELOPMENT BANK",
    "Address": "AVENUE JOSEPH ANOMA 10-12",
    "City": "ABIDJAN",
    "Branch": "ADF",
    "Postcode": "",
    "Country": "Côte D’ivoire",
    "Connection": "Active"
  },
  {
    "bankCode": "AFDB",
    "countryCode": "CI",
    "branchCode": "AIF",
    "SWIFT Code": "AFDBCIABAIF",
    "Bank Name": "AFRICAN DEVELOPMENT BANK",
    "Address": "AVENUE JOSEPH ANOMA 10-12",
    "City": "ABIDJAN",
    "Branch": "AFRICA INTEGRITY FUND",
    "Postcode": "",
    "Country": "Côte D’ivoire",
    "Connection": "Active"
  },
  {
    "bankCode": "AFDB",
    "countryCode": "CI",
    "branchCode": "ALS",
    "SWIFT Code": "AFDBCIABALS",
    "Bank Name": "AFRICAN DEVELOPMENT BANK",
    "Address": "",
    "City": "ABIDJAN",
    "Branch": "AFRICAN LEGAL SUPPORT FACILITY",
    "Postcode": "",
    "Country": "Côte D’ivoire",
    "Connection": "Active"
  },
  {
    "bankCode": "AFDB",
    "countryCode": "CI",
    "branchCode": "ARE",
    "SWIFT Code": "AFDBCIABARE",
    "Bank Name": "AFRICAN DEVELOPMENT BANK",
    "Address": "AVENUE JOSEPH ANOMA 10-12",
    "City": "ABIDJAN",
    "Branch": "AREI",
    "Postcode": "",
    "Country": "Côte D’ivoire",
    "Connection": "Active"
  },
  {
    "bankCode": "AFDB",
    "countryCode": "CI",
    "branchCode": "GAF",
    "SWIFT Code": "AFDBCIABGAF",
    "Bank Name": "AFRICAN DEVELOPMENT BANK",
    "Address": "AVENUE JOSEPH ANOMA 10-12",
    "City": "ABIDJAN",
    "Branch": "GAFSA TRUST FUND",
    "Postcode": "",
    "Country": "Côte D’ivoire",
    "Connection": "Active"
  },
  {
    "bankCode": "AFDB",
    "countryCode": "CI",
    "branchCode": "MFW",
    "SWIFT Code": "AFDBCIABMFW",
    "Bank Name": "AFRICAN DEVELOPMENT BANK",
    "Address": "",
    "City": "ABIDJAN",
    "Branch": "MAKING FINANCE",
    "Postcode": "",
    "Country": "Côte D’ivoire",
    "Connection": "Active"
  },
  {
    "bankCode": "AFDB",
    "countryCode": "CI",
    "branchCode": "PID",
    "SWIFT Code": "AFDBCIABPID",
    "Bank Name": "AFRICAN DEVELOPMENT BANK",
    "Address": "",
    "City": "ABIDJAN",
    "Branch": "PIDA ACCOUNT",
    "Postcode": "",
    "Country": "Côte D’ivoire",
    "Connection": "Active"
  },
  {
    "bankCode": "AFDB",
    "countryCode": "CI",
    "branchCode": "RWS",
    "SWIFT Code": "AFDBCIABRWS",
    "Bank Name": "AFRICAN DEVELOPMENT BANK",
    "Address": "AVENUE JOSEPH ANOMA 10-12",
    "City": "ABIDJAN",
    "Branch": "RWSSI",
    "Postcode": "",
    "Country": "Côte D’ivoire",
    "Connection": "Active"
  },
  {
    "bankCode": "AFDB",
    "countryCode": "CI",
    "branchCode": "TRY",
    "SWIFT Code": "AFDBCIABTRY",
    "Bank Name": "AFRICAN DEVELOPMENT BANK",
    "Address": "",
    "City": "ABIDJAN",
    "Branch": "TREASURY DEPARTMENT",
    "Postcode": "",
    "Country": "Côte D’ivoire",
    "Connection": "Active"
  },
  {
    "bankCode": "OMFN",
    "countryCode": "CI",
    "branchCode": "IAB",
    "SWIFT Code": "OMFNCIAB",
    "Bank Name": "AFRILAND FIRST BANK COTE D'IVOIRE",
    "Address": "IMMEUBLE WOODIN CENTER AVENUE, NOGUES, RUE DE COMMERCE,PLATEAU",
    "City": "ABIDJAN",
    "Branch": "",
    "Postcode": "",
    "Country": "Côte D’ivoire",
    "Connection": "Active"
  },
  {
    "bankCode": "SOAC",
    "countryCode": "CI",
    "branchCode": "IAB",
    "SWIFT Code": "SOACCIAB",
    "Bank Name": "ALIOS FINANCE (SAFCA)",
    "Address": "IMMEUBLE SAFCA, RUE DES CARROSSIERS 1, TREICHVILLE ZONE 3",
    "City": "ABIDJAN",
    "Branch": "",
    "Postcode": "",
    "Country": "Côte D’ivoire",
    "Connection": "Active"
  },
  {
    "bankCode": "AFRI",
    "countryCode": "CI",
    "branchCode": "IAB",
    "SWIFT Code": "AFRICIAB",
    "Bank Name": "BANK OF AFRICA - COTE D'IVOIRE",
    "Address": "ANGLE AV.TERRASSON DE FOUGERES RUE, GOURGAS",
    "City": "ABIDJAN",
    "Branch": "",
    "Postcode": "",
    "Country": "Côte D’ivoire",
    "Connection": "Active"
  },
  {
    "bankCode": "ATCI",
    "countryCode": "CI",
    "branchCode": "IAB",
    "SWIFT Code": "ATCICIAB",
    "Bank Name": "BANQUE ATLANTIQUE COTE D'IVOIRE",
    "Address": "IMMEUBLE ATLANTIQUE, AVENUE NOGUES",
    "City": "ABIDJAN",
    "Branch": "",
    "Postcode": "",
    "Country": "Côte D’ivoire",
    "Connection": "Active"
  },
  {
    "bankCode": "ATCI",
    "countryCode": "CI",
    "branchCode": "SAN",
    "SWIFT Code": "ATCICIABSAN",
    "Bank Name": "BANQUE ATLANTIQUE COTE D'IVOIRE",
    "Address": "RUE DU PORT",
    "City": "SAN PEDRO",
    "Branch": "CAISSE DE STABILISATION",
    "Postcode": "",
    "Country": "Côte D’ivoire",
    "Connection": "Active"
  },
  {
    "bankCode": "BCAO",
    "countryCode": "CI",
    "branchCode": "ABE",
    "SWIFT Code": "BCAOCIABABE",
    "Bank Name": "BANQUE CENTRALE DES ETATS DE L'AFRIQUE DE L'OUEST",
    "Address": "",
    "City": "ABENGOUROU",
    "Branch": "ABENGOUROU BRANCH",
    "Postcode": "",
    "Country": "Côte D’ivoire",
    "Connection": "Active"
  },
  {
    "bankCode": "BCAO",
    "countryCode": "CI",
    "branchCode": "IAB",
    "SWIFT Code": "BCAOCIAB",
    "Bank Name": "BANQUE CENTRALE DES ETATS DE L'AFRIQUE DE L'OUEST",
    "Address": "AV. ABDOULAYE FADIGA ANGLE, BD., ROUSSEL",
    "City": "ABIDJAN",
    "Branch": "",
    "Postcode": "",
    "Country": "Côte D’ivoire",
    "Connection": "Active"
  },
  {
    "bankCode": "BCAO",
    "countryCode": "CI",
    "branchCode": "BOU",
    "SWIFT Code": "BCAOCIABBOU",
    "Bank Name": "BANQUE CENTRALE DES ETATS DE L'AFRIQUE DE L'OUEST",
    "Address": "",
    "City": "BOUAKE",
    "Branch": "BOUAKE BRANCH",
    "Postcode": "",
    "Country": "Côte D’ivoire",
    "Connection": "Active"
  },
  {
    "bankCode": "BCAO",
    "countryCode": "CI",
    "branchCode": "DAL",
    "SWIFT Code": "BCAOCIABDAL",
    "Bank Name": "BANQUE CENTRALE DES ETATS DE L'AFRIQUE DE L'OUEST",
    "Address": "",
    "City": "DALOA",
    "Branch": "DALOA BRANCH",
    "Postcode": "",
    "Country": "Côte D’ivoire",
    "Connection": "Active"
  },
  {
    "bankCode": "BCAO",
    "countryCode": "CI",
    "branchCode": "KOR",
    "SWIFT Code": "BCAOCIABKOR",
    "Bank Name": "BANQUE CENTRALE DES ETATS DE L'AFRIQUE DE L'OUEST",
    "Address": "",
    "City": "KORHOGO",
    "Branch": "KORHOGO BRANCH",
    "Postcode": "",
    "Country": "Côte D’ivoire",
    "Connection": "Active"
  },
  {
    "bankCode": "BCAO",
    "countryCode": "CI",
    "branchCode": "MAN",
    "SWIFT Code": "BCAOCIABMAN",
    "Bank Name": "BANQUE CENTRALE DES ETATS DE L'AFRIQUE DE L'OUEST",
    "Address": "",
    "City": "MAN",
    "Branch": "MAN BRANCH",
    "Postcode": "",
    "Country": "Côte D’ivoire",
    "Connection": "Active"
  },
  {
    "bankCode": "BCAO",
    "countryCode": "CI",
    "branchCode": "SAN",
    "SWIFT Code": "BCAOCIABSAN",
    "Bank Name": "BANQUE CENTRALE DES ETATS DE L'AFRIQUE DE L'OUEST",
    "Address": "",
    "City": "SAN PEDRO",
    "Branch": "SAN PEDRO BRANCH",
    "Postcode": "",
    "Country": "Côte D’ivoire",
    "Connection": "Active"
  },
  {
    "bankCode": "BDAJ",
    "countryCode": "CI",
    "branchCode": "IAB",
    "SWIFT Code": "BDAJCIAB",
    "Bank Name": "BANQUE DABIDJAN, SA.",
    "Address": "IMMEUBLE GRANDE POSTE DU PLATEAU, PLACE DE LA REPUBLIQUE PLATEAU",
    "City": "ABIDJAN",
    "Branch": "",
    "Postcode": "",
    "Country": "Côte D’ivoire",
    "Connection": "Active"
  },
  {
    "bankCode": "BHCI",
    "countryCode": "CI",
    "branchCode": "IAB",
    "SWIFT Code": "BHCICIAB",
    "Bank Name": "BANQUE DE L'HABITAT DE COTE D'IVOIRE",
    "Address": "AVENUE JOSEPH ANOMA 22",
    "City": "ABIDJAN",
    "Branch": "",
    "Postcode": "",
    "Country": "Côte D’ivoire",
    "Connection": "Active"
  },
  {
    "bankCode": "BDUT",
    "countryCode": "CI",
    "branchCode": "IAB",
    "SWIFT Code": "BDUTCIAB",
    "Bank Name": "BANQUE DE L'UNION - COTE D'IVOIRE",
    "Address": "IMMEUBLE JECEDA, PLATEAU BOULEVARD DE LA REPUBLIQUE",
    "City": "ABIDJAN",
    "Branch": "",
    "Postcode": "",
    "Country": "Côte D’ivoire",
    "Connection": "Active"
  },
  {
    "bankCode": "BQTR",
    "countryCode": "CI",
    "branchCode": "IAD",
    "SWIFT Code": "BQTRCIAD",
    "Bank Name": "BANQUE DES DEPOTS DU TRESOR PUBLIC",
    "Address": "AVENUE A 58 CROZET 6/8",
    "City": "ABIDJAN",
    "Branch": "",
    "Postcode": "",
    "Country": "Côte D’ivoire",
    "Connection": "Active"
  },
  {
    "bankCode": "BICI",
    "countryCode": "CI",
    "branchCode": "BSE",
    "SWIFT Code": "BICICIABBSE",
    "Bank Name": "BANQUE INTERNATIONALE POUR LE COMMERCE ET L'INDUSTRIE DE LA COTE D'IVOIRE",
    "Address": "",
    "City": "ABIDJAN",
    "Branch": "",
    "Postcode": "",
    "Country": "Côte D’ivoire",
    "Connection": "Active"
  },
  {
    "bankCode": "BICI",
    "countryCode": "CI",
    "branchCode": "IAB",
    "SWIFT Code": "BICICIAB",
    "Bank Name": "BANQUE INTERNATIONALE POUR LE COMMERCE ET L'INDUSTRIE DE LA COTE D'IVOIRE",
    "Address": "AVENUE FRANCHET D'ESPEREY",
    "City": "ABIDJAN",
    "Branch": "",
    "Postcode": "",
    "Country": "Côte D’ivoire",
    "Connection": "Active"
  }
]
module.exports = coteDivoire
