const curacao = [
  {
    "countryCode": "IRPP",
    "bankCode": "CW",
    "branchCode": "WCW",
    "SWIFT Code": "IRPPCWCW",
    "Bank Name": "ADAMA IRVITA N.V.",
    "Address": "POS CABAI OFFICE PARK, UNIT 13, SCHOUWBURGWEG Z/N",
    "City": "WILLEMSTAD",
    "Branch": "",
    "Postcode": "",
    "Country": "Curaçao",
    "Connection": "Active"
  },
  {
    "countryCode": "APCP",
    "bankCode": "CW",
    "branchCode": "WC2",
    "SWIFT Code": "APCPCWC2",
    "Bank Name": "APC BANK N.V.",
    "Address": "SCHOUWBURGWEG Z/N",
    "City": "WILLEMSTAD",
    "Branch": "",
    "Postcode": "00000",
    "Country": "Curaçao",
    "Connection": "Active"
  },
  {
    "countryCode": "CARA",
    "bankCode": "CW",
    "branchCode": "WCU",
    "SWIFT Code": "CARACWCU",
    "Bank Name": "BANCARIBE CURACAO BANK N.V.",
    "Address": "SCHOTTEGATWEG OOST 54-56, GROOT DAVELAAR",
    "City": "WILLEMSTAD",
    "Branch": "",
    "Postcode": "",
    "Country": "Curaçao",
    "Connection": "Active"
  },
  {},
  {
    "countryCode": "NCRT",
    "bankCode": "CW",
    "branchCode": "WCA",
    "SWIFT Code": "NCRTCWCA",
    "Bank Name": "BANCO NACIONAL DE CREDITO, C.A. BANCO UNIVERSAL SUCURSAL CURACAO",
    "Address": "BLDG E, FLOOR 1, KAYA WFG JOMBY MENSING, ZEELANDIA",
    "City": "WILLEMSTAD",
    "Branch": "",
    "Postcode": "",
    "Country": "Curaçao",
    "Connection": "Active"
  },
  {
    "countryCode": "BPOC",
    "bankCode": "CW",
    "branchCode": "WCU",
    "SWIFT Code": "BPOCCWCU",
    "Bank Name": "BANCO PROVINCIAL OVERSEAS N.V.",
    "Address": "ZEELANDIA OFFICE PARK, BUILDING E,, FLOOR 3 KAYA W.F.G.(JOMBI) MENSING, 14",
    "City": "WILLEMSTAD",
    "Branch": "",
    "Postcode": "",
    "Country": "Curaçao",
    "Connection": "Active"
  },
  {
    "countryCode": "SFAN",
    "bankCode": "CW",
    "branchCode": "WCU",
    "SWIFT Code": "SFANCWCU",
    "Bank Name": "BANESCO N.V.",
    "Address": "KAYA W.F.G (JOMBI) MENSING 36C",
    "City": "WILLEMSTAD",
    "Branch": "",
    "Postcode": "",
    "Country": "Curaçao",
    "Connection": "Active"
  },
  {
    "countryCode": "BBIC",
    "bankCode": "CW",
    "branchCode": "WCW",
    "SWIFT Code": "BBICCWCW",
    "Bank Name": "BLUE BANK INTERNATIONAL N.V.",
    "Address": "ZEELANDIA OFFICE PARK, KAYA WFG JOMBI MENSING 14",
    "City": "WILLEMSTAD",
    "Branch": "",
    "Postcode": "",
    "Country": "Curaçao",
    "Connection": "Active"
  },
  {
    "countryCode": "CBCS",
    "bankCode": "CW",
    "branchCode": "WCU",
    "SWIFT Code": "CBCSCWCU",
    "Bank Name": "CENTRALE BANK VAN CURACAO EN SINT MAARTEN",
    "Address": "SIMON BOLIVAR PLEIN 1",
    "City": "WILLEMSTAD",
    "Branch": "",
    "Postcode": "",
    "Country": "Curaçao",
    "Connection": "Active"
  },
  {
    "countryCode": "CITC",
    "bankCode": "CW",
    "branchCode": "DSK",
    "SWIFT Code": "CITCCWCUDSK",
    "Bank Name": "CITCO BANKING CORPORATION N.V.",
    "Address": "KAYA FLAMBOYAN 9",
    "City": "WILLEMSTAD",
    "Branch": "DEALING ROOM",
    "Postcode": "",
    "Country": "Curaçao",
    "Connection": "Active"
  },
  {
    "countryCode": "CITC",
    "bankCode": "CW",
    "branchCode": "WCU",
    "SWIFT Code": "CITCCWCU",
    "Bank Name": "CITCO BANKING CORPORATION N.V.",
    "Address": "DE RUYTERKADE 62",
    "City": "WILLEMSTAD",
    "Branch": "HEAD OFFICE",
    "Postcode": "",
    "Country": "Curaçao",
    "Connection": "Active"
  },
  {
    "countryCode": "EBNV",
    "bankCode": "CW",
    "branchCode": "WCU",
    "SWIFT Code": "EBNVCWCU",
    "Bank Name": "EBNA BANK N.V.",
    "Address": "ANT BUILDING, KAYA W.F.G. (JOMBI) MENSING 36",
    "City": "WILLEMSTAD",
    "Branch": "",
    "Postcode": "",
    "Country": "Curaçao",
    "Connection": "Active"
  },
  {
    "countryCode": "EINB",
    "bankCode": "CW",
    "branchCode": "WCU",
    "SWIFT Code": "EINBCWCU",
    "Bank Name": "EXPRINTER INTERNATIONAL BANK N.V.",
    "Address": "ZEELANDIA OFFICE PARK, BUILDING E, FLOOR 1 KAYA W.F.G. (JOMBI 14",
    "City": "WILLEMSTAD",
    "Branch": "",
    "Postcode": "",
    "Country": "Curaçao",
    "Connection": "Active"
  },
  {
    "countryCode": "FCIB",
    "bankCode": "CW",
    "branchCode": "WCU",
    "SWIFT Code": "FCIBCWCU",
    "Bank Name": "FIRSTCARIBBEAN INTERNATIONAL BANK (CAYMAN) LTD CURACAO BRANCH",
    "Address": "DE RUIJTERKADE 61",
    "City": "WILLEMSTAD",
    "Branch": "",
    "Postcode": "",
    "Country": "Curaçao",
    "Connection": "Active"
  },
  {
    "countryCode": "FCIB",
    "bankCode": "CW",
    "branchCode": "WCD",
    "SWIFT Code": "FCIBCWCD",
    "Bank Name": "FIRSTCARIBBEAN INTERNATIONAL BANK (CAYMAN) LTD CURACAO BRANCH",
    "Address": "DE RUIJTERKADE 61",
    "City": "WILLEMSTAD",
    "Branch": "",
    "Postcode": "",
    "Country": "Curaçao",
    "Connection": "Active"
  },
  {},
  {
    "countryCode": "IBMS",
    "bankCode": "CW",
    "branchCode": "WCU",
    "SWIFT Code": "IBMSCWCU",
    "Bank Name": "IBIS MANAGEMENT ASSOCIATES N.V.",
    "Address": "IBIS PLAZA, SANTA ROSA WEG 32",
    "City": "WILLEMSTAD",
    "Branch": "",
    "Postcode": "",
    "Country": "Curaçao",
    "Connection": "Active"
  },
  {
    "countryCode": "MCBK",
    "bankCode": "CW",
    "branchCode": "WCU",
    "SWIFT Code": "MCBKCWCU",
    "Bank Name": "MADURO AND CURIEL'S BANK N.V.",
    "Address": "PLAZA JOJO CORREA 2-4",
    "City": "WILLEMSTAD",
    "Branch": "",
    "Postcode": "",
    "Country": "Curaçao",
    "Connection": "Active"
  },
  {
    "countryCode": "ORBA",
    "bankCode": "CW",
    "branchCode": "WCU",
    "SWIFT Code": "ORBACWCU",
    "Bank Name": "ORCO BANK N.V.",
    "Address": "LANDHUIS CERRITO, SCHOTTEGATWEG OOST Z/N",
    "City": "WILLEMSTAD",
    "Branch": "",
    "Postcode": "",
    "Country": "Curaçao",
    "Connection": "Active"
  },
  {
    "countryCode": "RBTT",
    "bankCode": "CW",
    "branchCode": "WCU",
    "SWIFT Code": "RBTTCWCU",
    "Bank Name": "RBC ROYAL BANK N.V. (FORMERLY RBTT BANK N.V.)",
    "Address": "KAYA FLAMBOYAN 1, ROOI CATOOTJE",
    "City": "WILLEMSTAD",
    "Branch": "",
    "Postcode": "",
    "Country": "Curaçao",
    "Connection": "Active"
  },
  {
    "countryCode": "RIBK",
    "bankCode": "CW",
    "branchCode": "WCU",
    "SWIFT Code": "RIBKCWCU",
    "Bank Name": "REPUBLIC INTERNATIONAL BANK, N.V.",
    "Address": "CASCORA 1, CASCORAWEG 1",
    "City": "WILLEMSTAD",
    "Branch": "",
    "Postcode": "",
    "Country": "Curaçao",
    "Connection": "Active"
  },
  {},
  {
    "countryCode": "CITC",
    "bankCode": "CW",
    "branchCode": "WCC",
    "SWIFT Code": "CITCCWCC",
    "Bank Name": "VIDANOVA BANK N.V. (FORMERLY S.F.T. BANK)",
    "Address": "SCHOTTEGATWEG OOST 44",
    "City": "WILLEMSTAD",
    "Branch": "",
    "Postcode": "",
    "Country": "Curaçao",
    "Connection": "Active"
  }
]
module.exports = curacao
