const czechRepublic = [
  {
    "countryCode": "PAER",
    "bankCode": "CZ",
    "branchCode": "FIN",
    "SWIFT Code": "PAERCZPPFIN",
    "Bank Name": "PAYMENT EXECUTION S.R.O.",
    "Address": "REVOLUCNI 724, 7, STARE MESTO",
    "City": "PRAGUE",
    "Branch": "",
    "Postcode": "110 00",
    "Country": "Czech Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "PAER",
    "bankCode": "CZ",
    "branchCode": "PRG",
    "SWIFT Code": "PAERCZPPPRG",
    "Bank Name": "PAYMENT EXECUTION S.R.O.",
    "Address": "REVOLUCNI 724, 7, STARE MESTO",
    "City": "PRAGUE",
    "Branch": "",
    "Postcode": "110 00",
    "Country": "Czech Republic",
    "Connection": "Active"
  },
  {},
  {},
  {
    "countryCode": "PAER",
    "bankCode": "CZ",
    "branchCode": "INT",
    "SWIFT Code": "PAERCZPPINT",
    "Bank Name": "PAYMENT EXECUTION S.R.O.",
    "Address": "REVOLUCNI 724, 7, STARE MESTO",
    "City": "PRAGUE",
    "Branch": "",
    "Postcode": "110 00",
    "Country": "Czech Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "PAER",
    "bankCode": "CZ",
    "branchCode": "ZPP",
    "SWIFT Code": "PAERCZPP",
    "Bank Name": "PAYMENT EXECUTION S.R.O.",
    "Address": "REVOLUCNI 724, 7, STARE MESTO",
    "City": "PRAGUE",
    "Branch": "",
    "Postcode": "110 00",
    "Country": "Czech Republic",
    "Connection": "Active"
  },
  {},
  {
    "countryCode": "PAER",
    "bankCode": "CZ",
    "branchCode": "GLB",
    "SWIFT Code": "PAERCZPPGLB",
    "Bank Name": "PAYMENT EXECUTION S.R.O.",
    "Address": "REVOLUCNI 724, 7, STARE MESTO",
    "City": "PRAGUE",
    "Branch": "",
    "Postcode": "110 00",
    "Country": "Czech Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "PAER",
    "bankCode": "CZ",
    "branchCode": "COR",
    "SWIFT Code": "PAERCZPPCOR",
    "Bank Name": "PAYMENT EXECUTION S.R.O.",
    "Address": "REVOLUCNI 724, 7, STARE MESTO",
    "City": "PRAGUE",
    "Branch": "",
    "Postcode": "110 00",
    "Country": "Czech Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "BPKO",
    "bankCode": "CZ",
    "branchCode": "ZPP",
    "SWIFT Code": "BPKOCZPP",
    "Bank Name": "PKO BP S.A., CZECH BRANCH",
    "Address": "KLIMENTSKA 1216, 46",
    "City": "PRAGUE",
    "Branch": "",
    "Postcode": "110 00",
    "Country": "Czech Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "PAPO",
    "bankCode": "CZ",
    "branchCode": "ZP2",
    "SWIFT Code": "PAPOCZP2",
    "Bank Name": "PP MONEY TRANSFER S.R.O.",
    "Address": "POLITICKYCH VEZNU 911, 8",
    "City": "PRAGUE",
    "Branch": "",
    "Postcode": "101 00",
    "Country": "Czech Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "PMBP",
    "bankCode": "CZ",
    "branchCode": "ZPP",
    "SWIFT Code": "PMBPCZPP",
    "Bank Name": "PPF BANKA A.S.",
    "Address": "EVROPSKA 2690, PPF GATE 17",
    "City": "PRAGUE",
    "Branch": "",
    "Postcode": "160 41",
    "Country": "Czech Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "RZBC",
    "bankCode": "CZ",
    "branchCode": "ZPP",
    "SWIFT Code": "RZBCCZPP",
    "Bank Name": "RAIFFEISENBANK A.S.",
    "Address": "HVEZDOVA 1716, 2B CITY TOWER",
    "City": "PRAGUE",
    "Branch": "",
    "Postcode": "140 78",
    "Country": "Czech Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "ROKE",
    "bankCode": "CZ",
    "branchCode": "ZP2",
    "SWIFT Code": "ROKECZP2",
    "Bank Name": "ROKLEN360 A.S.",
    "Address": "VACLAVSKE NAMESTI 838, 9",
    "City": "PRAGUE",
    "Branch": "",
    "Postcode": "110 00",
    "Country": "Czech Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "SBFN",
    "bankCode": "CZ",
    "branchCode": "ZP2",
    "SWIFT Code": "SBFNCZP2",
    "Bank Name": "SAB FINANCE A.S.",
    "Address": "SENOVAZNE NAMESTI 1375, 19",
    "City": "PRAGUE",
    "Branch": "",
    "Postcode": "110 00",
    "Country": "Czech Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "VBOE",
    "bankCode": "CZ",
    "branchCode": "Z2X",
    "SWIFT Code": "VBOECZ2X",
    "Bank Name": "SBERBANK CZ, A.S. V LIKVIDACI",
    "Address": "U TREZORKY 921, 2",
    "City": "PRAGUE",
    "Branch": "",
    "Postcode": "158 00",
    "Country": "Czech Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "SKTA",
    "bankCode": "CZ",
    "branchCode": "Z22",
    "SWIFT Code": "SKTACZ22",
    "Bank Name": "SKODA TRANSPORTATION A.S.",
    "Address": "EMILA SKODY 2922, 1",
    "City": "PLZEN",
    "Branch": "",
    "Postcode": "301 00",
    "Country": "Czech Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "MPUB",
    "bankCode": "CZ",
    "branchCode": "ZPP",
    "SWIFT Code": "MPUBCZPP",
    "Bank Name": "TRINITY BANK A.S.",
    "Address": "SENOVAZNE NAMESTI 1375, 19",
    "City": "PRAGUE",
    "Branch": "",
    "Postcode": "110 00",
    "Country": "Czech Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "BACX",
    "bankCode": "CZ",
    "branchCode": "ZPP",
    "SWIFT Code": "BACXCZPP",
    "Bank Name": "UNICREDIT BANK CZECH REPUBLIC AND SLOVAKIA, A.S.",
    "Address": "ZELETAVSKA 1525, 1",
    "City": "PRAGUE",
    "Branch": "",
    "Postcode": "140 92",
    "Country": "Czech Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "BACX",
    "bankCode": "CZ",
    "branchCode": "FAR",
    "SWIFT Code": "BACXCZPPFAR",
    "Bank Name": "UNICREDIT BANK CZECH REPUBLIC AND SLOVAKIA, A.S.",
    "Address": "",
    "City": "PRAGUE",
    "Branch": "INTERNAL FILE ACT ROUTING",
    "Postcode": "",
    "Country": "Czech Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "BACX",
    "bankCode": "CZ",
    "branchCode": "CBL",
    "SWIFT Code": "BACXCZPPCBL",
    "Bank Name": "UNICREDIT BANK CZECH REPUBLIC AND SLOVAKIA, A.S.",
    "Address": "ZELETAVSKA 1525, 1",
    "City": "PRAGUE",
    "Branch": "SECURITIES SERVICES",
    "Postcode": "140 92",
    "Country": "Czech Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "BACX",
    "bankCode": "CZ",
    "branchCode": "RET",
    "SWIFT Code": "BACXCZPPRET",
    "Bank Name": "UNICREDIT BANK CZECH REPUBLIC AND SLOVAKIA, A.S.",
    "Address": "",
    "City": "PRAGUE",
    "Branch": "SECURITIES SETTLEMENT",
    "Postcode": "",
    "Country": "Czech Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "PANX",
    "bankCode": "CZ",
    "branchCode": "ZP2",
    "SWIFT Code": "PANXCZP2",
    "Bank Name": "UNIFIEDPOST PAYMENTS S.A., ODSTEPNY ZAVOD",
    "Address": "ROZTYLSKA 1860, 1, CHODOV",
    "City": "PRAGUE",
    "Branch": "",
    "Postcode": "148 00",
    "Country": "Czech Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "AXIL",
    "bankCode": "CZ",
    "branchCode": "ZPP",
    "SWIFT Code": "AXILCZPP",
    "Bank Name": "UNIQA INVESTICNI SPOLECNOST, A. S.",
    "Address": "EVROPSKA 810, 136",
    "City": "PRAGUE",
    "Branch": "",
    "Postcode": "160 00",
    "Country": "Czech Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "VPAY",
    "bankCode": "CZ",
    "branchCode": "ZP2",
    "SWIFT Code": "VPAYCZP2",
    "Bank Name": "VIVA PAYMENT SERVICES S.A. ODSTEPNY ZAVOD",
    "Address": "DELNICKA 213, 12, PRAHA 7",
    "City": "PRAGUE",
    "Branch": "",
    "Postcode": "170 00",
    "Country": "Czech Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "SUBA",
    "bankCode": "CZ",
    "branchCode": "ZPP",
    "SWIFT Code": "SUBACZPP",
    "Bank Name": "VSEOBECNA UVEROVA BANKA A.S., PRAGUE BRANCH",
    "Address": "PURKYNOVA 2121, 3",
    "City": "PRAGUE",
    "Branch": "",
    "Postcode": "110 00",
    "Country": "Czech Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "WOOD",
    "bankCode": "CZ",
    "branchCode": "ZPP",
    "SWIFT Code": "WOODCZPP",
    "Bank Name": "WOOD AND COMPANY",
    "Address": "NAMESTI REPUBLIKY 1079, A",
    "City": "PRAGUE",
    "Branch": "",
    "Postcode": "110 00",
    "Country": "Czech Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "ZENG",
    "bankCode": "CZ",
    "branchCode": "ZPP",
    "SWIFT Code": "ZENGCZPP",
    "Bank Name": "ZENTIVA GROUP S.A.",
    "Address": "U KABELOVNY 529/16",
    "City": "PRAGUE",
    "Branch": "",
    "Postcode": "102 37",
    "Country": "Czech Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "AIRA",
    "bankCode": "CZ",
    "branchCode": "ZPP",
    "SWIFT Code": "AIRACZPP",
    "Bank Name": "AIR BANK A.S.",
    "Address": "EVROPSKA 2690, 17",
    "City": "PRAGUE",
    "Branch": "",
    "Postcode": "160 00",
    "Country": "Czech Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "AKCN",
    "bankCode": "CZ",
    "branchCode": "ZP2",
    "SWIFT Code": "AKCNCZP2",
    "Bank Name": "AKCENTA CZ A.S.",
    "Address": "SALVATORSKA 931, 8",
    "City": "PRAGUE",
    "Branch": "",
    "Postcode": "110 00",
    "Country": "Czech Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "APOR",
    "bankCode": "CZ",
    "branchCode": "ZP2",
    "SWIFT Code": "APORCZP2",
    "Bank Name": "ALTERNATIVE PAYMENT SOLUTIONS, S.R.O",
    "Address": "JECNA 2093, 32A",
    "City": "PRAGUE",
    "Branch": "",
    "Postcode": "120 00",
    "Country": "Czech Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "ARTT",
    "bankCode": "CZ",
    "branchCode": "ZPP",
    "SWIFT Code": "ARTTCZPP",
    "Bank Name": "ARTESA, SPORITELNI DRUZSTVO",
    "Address": "SKRETOVA 490, PANORAMA BUSINESS CENTER, 12",
    "City": "PRAGUE",
    "Branch": "",
    "Postcode": "120 00",
    "Country": "Czech Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "BKCH",
    "bankCode": "CZ",
    "branchCode": "ZPP",
    "SWIFT Code": "BKCHCZPP",
    "Bank Name": "BANK OF CHINA (CEE) LTD. PRAGUE BRANCH",
    "Address": "NA FLORENCI 2116, 15",
    "City": "PRAGUE",
    "Branch": "",
    "Postcode": "110 00",
    "Country": "Czech Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "COMM",
    "bankCode": "CZ",
    "branchCode": "ZPP",
    "SWIFT Code": "COMMCZPP",
    "Bank Name": "BANK OF COMMUNICATIONS CO., LTD. PRAGUE BRANCH ODSTEPNY ZAVOD",
    "Address": "ROHANSKE NABREZI STREET, KAR 693, RUSTONKA R2, 10",
    "City": "PRAGUE",
    "Branch": "",
    "Postcode": "186 00",
    "Country": "Czech Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "CTAS",
    "bankCode": "CZ",
    "branchCode": "Z22",
    "SWIFT Code": "CTASCZ22",
    "Bank Name": "BANKA CREDITAS",
    "Address": "SOKOLOVSKA 675, 9",
    "City": "PRAGUE",
    "Branch": "",
    "Postcode": "186 00",
    "Country": "Czech Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "BPOR",
    "bankCode": "CZ",
    "branchCode": "Z22",
    "SWIFT Code": "BPORCZ22",
    "Bank Name": "BEEKASH PAYMENT SOLUTION SRO",
    "Address": "KORUNNI 2569, OFFICE OPTION, 108, 3FG5+2F, VINOHRADY PRAHA 1",
    "City": "PRAGUE",
    "Branch": "",
    "Postcode": "101 00",
    "Country": "Czech Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "BEOR",
    "bankCode": "CZ",
    "branchCode": "ZP2",
    "SWIFT Code": "BEORCZP2",
    "Bank Name": "BESTPAY S.R.O.",
    "Address": "PURKYNOVA 74, 2, NOVE MESTO",
    "City": "PRAGUE",
    "Branch": "",
    "Postcode": "110 00",
    "Country": "Czech Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "GEBA",
    "bankCode": "CZ",
    "branchCode": "ZPP",
    "SWIFT Code": "GEBACZPP",
    "Bank Name": "BNP PARIBAS S.A., POBOCKA CESKA REPUBLIKA",
    "Address": "MILEVSKA 2095, MAIN POINT PANKRAC, 5, FLOOR 6",
    "City": "PRAGUE",
    "Branch": "",
    "Postcode": "140 00",
    "Country": "Czech Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "IDUS",
    "bankCode": "CZ",
    "branchCode": "ZPP",
    "SWIFT Code": "IDUSCZPP",
    "Bank Name": "CE INDUSTRIES A.S.",
    "Address": "SOKOLOVSKA 675/9, KARLIN",
    "City": "PRAGUE",
    "Branch": "",
    "Postcode": "186 00",
    "Country": "Czech Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "UNIY",
    "bankCode": "CZ",
    "branchCode": "ZPP",
    "SWIFT Code": "UNIYCZPP",
    "Bank Name": "CENTRALNI DEPOZITAR CENNYCH PAPIRU, A.S.",
    "Address": "RYBNA 14, PRAHA 1",
    "City": "PRAGUE",
    "Branch": "",
    "Postcode": "110 05",
    "Country": "Czech Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "UNIY",
    "bankCode": "CZ",
    "branchCode": "ZPA",
    "SWIFT Code": "UNIYCZPA",
    "Bank Name": "CENTRALNI DEPOZITAR CENNYCH PAPIRU, A.S.",
    "Address": "RYBNA 14",
    "City": "PRAGUE",
    "Branch": "",
    "Postcode": "110 05",
    "Country": "Czech Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "CNBA",
    "bankCode": "CZ",
    "branchCode": "ZPB",
    "SWIFT Code": "CNBACZPB",
    "Bank Name": "CESKA NARODNI BANKA",
    "Address": "NA PRIKOPE 28",
    "City": "PRAGUE",
    "Branch": "",
    "Postcode": "115 03",
    "Country": "Czech Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "CNBA",
    "bankCode": "CZ",
    "branchCode": "ZPP",
    "SWIFT Code": "CNBACZPP",
    "Bank Name": "CESKA NARODNI BANKA",
    "Address": "NA PRIKOPE 28",
    "City": "PRAGUE",
    "Branch": "",
    "Postcode": "115 03",
    "Country": "Czech Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "GIBA",
    "bankCode": "CZ",
    "branchCode": "ZPX",
    "SWIFT Code": "GIBACZPX",
    "Bank Name": "CESKA SPORITELNA A.S.",
    "Address": "OLBRACHTOVA 62",
    "City": "PRAGUE",
    "Branch": "",
    "Postcode": "140 00",
    "Country": "Czech Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "CEKO",
    "bankCode": "CZ",
    "branchCode": "ZPP",
    "SWIFT Code": "CEKOCZPP",
    "Bank Name": "CESKOSLOVENSKA OBCHODNI BANKA, A.S.",
    "Address": "RADLICKA 333, 150",
    "City": "PRAGUE",
    "Branch": "HEAD OFFICE",
    "Postcode": "150 57",
    "Country": "Czech Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "CEZC",
    "bankCode": "CZ",
    "branchCode": "ZPP",
    "SWIFT Code": "CEZCCZPP",
    "Bank Name": "CEZ, A. S.",
    "Address": "DUHOVA 2, 1444, PRAHA 4",
    "City": "PRAGUE",
    "Branch": "",
    "Postcode": "140 53",
    "Country": "Czech Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "CITF",
    "bankCode": "CZ",
    "branchCode": "ZPP",
    "SWIFT Code": "CITFCZPP",
    "Bank Name": "CITFIN, SPORITELNI DRUZSTVO",
    "Address": "RADLICKA 751, 113E",
    "City": "PRAGUE",
    "Branch": "",
    "Postcode": "158 00",
    "Country": "Czech Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "CITI",
    "bankCode": "CZ",
    "branchCode": "ZPX",
    "SWIFT Code": "CITICZPX",
    "Bank Name": "CITIBANK EUROPE PLC, ORGANIZACNI SLOZKA",
    "Address": "BUCHAROVA 2641, 14",
    "City": "PRAGUE",
    "Branch": "",
    "Postcode": "158 02",
    "Country": "Czech Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "CITI",
    "bankCode": "CZ",
    "branchCode": "AOC",
    "SWIFT Code": "CITICZPXAOC",
    "Bank Name": "CITIBANK EUROPE PLC, ORGANIZACNI SLOZKA",
    "Address": "BUCHAROVA 2641, 14",
    "City": "PRAGUE",
    "Branch": "CITI CDCP AO",
    "Postcode": "158 02",
    "Country": "Czech Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "CITI",
    "bankCode": "CZ",
    "branchCode": "GCM",
    "SWIFT Code": "CITICZPXGCM",
    "Bank Name": "CITIBANK EUROPE PLC, ORGANIZACNI SLOZKA",
    "Address": "BUCHAROVA 2641, 14",
    "City": "PRAGUE",
    "Branch": "CITI CDCP GCM",
    "Postcode": "158 02",
    "Country": "Czech Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "CITI",
    "bankCode": "CZ",
    "branchCode": "TRD",
    "SWIFT Code": "CITICZPXTRD",
    "Bank Name": "CITIBANK EUROPE PLC, ORGANIZACNI SLOZKA",
    "Address": "EVROPSKA 178, KOOSPOL, FLOOR 1",
    "City": "PRAGUE",
    "Branch": "TRADE SERVICES DEPT.",
    "Postcode": "166 40",
    "Country": "Czech Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "CMEH",
    "bankCode": "CZ",
    "branchCode": "ZPP",
    "SWIFT Code": "CMEHCZPP",
    "Bank Name": "CME SERVICES S.R.O.",
    "Address": "KRIZENECKEHO NAMESTI 1078, 5A, HLUBOCEPY",
    "City": "PRAGUE",
    "Branch": "",
    "Postcode": "152 00",
    "Country": "Czech Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "COBA",
    "bankCode": "CZ",
    "branchCode": "ZPX",
    "SWIFT Code": "COBACZPX",
    "Bank Name": "COMMERZBANK AG",
    "Address": "JUGOSLAVSKA 1",
    "City": "PRAGUE",
    "Branch": "",
    "Postcode": "120 21",
    "Country": "Czech Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "SMTL",
    "bankCode": "CZ",
    "branchCode": "ZP2",
    "SWIFT Code": "SMTLCZP2",
    "Bank Name": "CREA PAY S.R.O.",
    "Address": "V JAME 699/1",
    "City": "PRAGUE",
    "Branch": "",
    "Postcode": "110 00",
    "Country": "Czech Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "SGGM",
    "bankCode": "CZ",
    "branchCode": "ZPP",
    "SWIFT Code": "SGGMCZPP",
    "Bank Name": "CSGM A.S.",
    "Address": "PERNEROVA 691/42, FLOOR 3, KRALIN",
    "City": "PRAGUE",
    "Branch": "",
    "Postcode": "186 00",
    "Country": "Czech Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "CZEE",
    "bankCode": "CZ",
    "branchCode": "ZPP",
    "SWIFT Code": "CZEECZPP",
    "Bank Name": "CZECH EXPORT BANK",
    "Address": "VODICKOVA 34",
    "City": "PRAGUE",
    "Branch": "",
    "Postcode": "111 21",
    "Country": "Czech Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "DEUT",
    "bankCode": "CZ",
    "branchCode": "ZPX",
    "SWIFT Code": "DEUTCZPX",
    "Bank Name": "DEUTSCHE BANK AKTIENGESELLSCHAFT FILIALE PRAG, ORGANIZACNI SLOZKA",
    "Address": "JUNGMANNOVA 745, 24",
    "City": "PRAGUE",
    "Branch": "",
    "Postcode": "110 00",
    "Country": "Czech Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "ESRO",
    "bankCode": "CZ",
    "branchCode": "ZP2",
    "SWIFT Code": "ESROCZP2",
    "Bank Name": "E-STEPS S.R.O.",
    "Address": "NOVE NAMESTI 1370, 11",
    "City": "PRAGUE",
    "Branch": "",
    "Postcode": "104 00",
    "Country": "Czech Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "KOLO",
    "bankCode": "CZ",
    "branchCode": "ZP2",
    "SWIFT Code": "KOLOCZP2",
    "Bank Name": "EUROPEAN SECUREPAY CENTER S.R.O.",
    "Address": "DLOUHA 730/35, STARE MESTO",
    "City": "PRAGUE",
    "Branch": "",
    "Postcode": "110 00",
    "Country": "Czech Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "KOLO",
    "bankCode": "CZ",
    "branchCode": "999",
    "SWIFT Code": "KOLOCZP2999",
    "Bank Name": "EUROPEAN SECUREPAY CENTER S.R.O.",
    "Address": "DLOUHA 730/35, STARE MESTO",
    "City": "PRAGUE",
    "Branch": "DOC PROCESSING",
    "Postcode": "110 00",
    "Country": "Czech Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "FIOB",
    "bankCode": "CZ",
    "branchCode": "ZPP",
    "SWIFT Code": "FIOBCZPP",
    "Bank Name": "FIO BANKA, A.S.",
    "Address": "V CELNICI 1028, MILLENNIUM PLAZA 10, FLOOR 1",
    "City": "PRAGUE",
    "Branch": "",
    "Postcode": "117 21",
    "Country": "Czech Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "GNRL",
    "bankCode": "CZ",
    "branchCode": "ZPP",
    "SWIFT Code": "GNRLCZPP",
    "Bank Name": "GENERALI INVESTMENTS CEE, INV.SPOL,A.S.",
    "Address": "NA PANKRACI 1720, 123",
    "City": "PRAGUE",
    "Branch": "",
    "Postcode": "140 21",
    "Country": "Czech Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "MIDL",
    "bankCode": "CZ",
    "branchCode": "ZPP",
    "SWIFT Code": "MIDLCZPP",
    "Bank Name": "HSBC CONTINENTAL EUROPE, CZECH REPUBLIC",
    "Address": "NA FLORENCI 2116/15, NOVE MESTO",
    "City": "PRAGUE",
    "Branch": "",
    "Postcode": "110 00",
    "Country": "Czech Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "MIDL",
    "bankCode": "CZ",
    "branchCode": "SDD",
    "SWIFT Code": "MIDLCZPPSDD",
    "Bank Name": "HSBC CONTINENTAL EUROPE, CZECH REPUBLIC",
    "Address": "",
    "City": "PRAGUE",
    "Branch": "SEPA DIRECT DEBITS",
    "Postcode": "",
    "Country": "Czech Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "ICBK",
    "bankCode": "CZ",
    "branchCode": "ZPP",
    "SWIFT Code": "ICBKCZPP",
    "Bank Name": "INDUSTRIAL AND COMMERCIAL BANK OF CHINA LIMITED, PRAGUE BRANCH, ODSTEPNY ZAVOD",
    "Address": "NA STRZI 1702, CITY EMPIRIA 65, FLOOR 12",
    "City": "PRAGUE",
    "Branch": "",
    "Postcode": "140 00",
    "Country": "Czech Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "INGB",
    "bankCode": "CZ",
    "branchCode": "ZPP",
    "SWIFT Code": "INGBCZPP",
    "Bank Name": "ING BANK N.V.",
    "Address": "CESKOMORAVSKA 2420, 15",
    "City": "PRAGUE",
    "Branch": "",
    "Postcode": "190 00",
    "Country": "Czech Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "JTBP",
    "bankCode": "CZ",
    "branchCode": "ZPP",
    "SWIFT Code": "JTBPCZPP",
    "Bank Name": "J AND T BANKA A.S.",
    "Address": "SOKOLOVSKA 700, 113A",
    "City": "PRAGUE",
    "Branch": "",
    "Postcode": "186 00",
    "Country": "Czech Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "KSOO",
    "bankCode": "CZ",
    "branchCode": "Z22",
    "SWIFT Code": "KSOOCZ22",
    "Bank Name": "KIWI.COM S.R.O.",
    "Address": "ROHANSKE NABREZI 678, 25",
    "City": "PRAGUE",
    "Branch": "",
    "Postcode": "186 00",
    "Country": "Czech Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "KOMB",
    "bankCode": "CZ",
    "branchCode": "ZPP",
    "SWIFT Code": "KOMBCZPP",
    "Bank Name": "KOMERCNI BANKA A.S.",
    "Address": "NA PRIKOPE 33",
    "City": "PRAGUE",
    "Branch": "",
    "Postcode": "114 07",
    "Country": "Czech Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "EXPN",
    "bankCode": "CZ",
    "branchCode": "ZPP",
    "SWIFT Code": "EXPNCZPP",
    "Bank Name": "MAX BANKA A.S.",
    "Address": "NA STRZI 2097, 63",
    "City": "PRAGUE",
    "Branch": "",
    "Postcode": "140 00",
    "Country": "Czech Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "BREX",
    "bankCode": "CZ",
    "branchCode": "ZPP",
    "SWIFT Code": "BREXCZPP",
    "Bank Name": "MBANK S.A., ORGANIZACNI SLOZKA",
    "Address": "PERNEROVA 691, 42",
    "City": "PRAGUE",
    "Branch": "",
    "Postcode": "186 00",
    "Country": "Czech Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "AGBA",
    "bankCode": "CZ",
    "branchCode": "ZPP",
    "SWIFT Code": "AGBACZPP",
    "Bank Name": "MONETA MONEY BANK, A.S.",
    "Address": "VYSKOCILOVA 1442, BB CENTRUM 1B",
    "City": "PRAGUE",
    "Branch": "",
    "Postcode": "140 28",
    "Country": "Czech Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "MOUS",
    "bankCode": "CZ",
    "branchCode": "ZP2",
    "SWIFT Code": "MOUSCZP2",
    "Bank Name": "MONEYPOLO EUROPE S.R.O.",
    "Address": "ARCHEOLOGICKA 2256, 1",
    "City": "PRAGUE",
    "Branch": "",
    "Postcode": "155 00",
    "Country": "Czech Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "MRSO",
    "bankCode": "CZ",
    "branchCode": "Z22",
    "SWIFT Code": "MRSOCZ22",
    "Bank Name": "MORTONS S.R.O.",
    "Address": "TR. T.G. MASARYKA 1108",
    "City": "FRYDEK-MISTEK",
    "Branch": "",
    "Postcode": "738 01",
    "Country": "Czech Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "NROZ",
    "bankCode": "CZ",
    "branchCode": "ZPP",
    "SWIFT Code": "NROZCZPP",
    "Bank Name": "NARODNI ROZVOJOVA BANKA, A.S.",
    "Address": "PREMYSLOVSKA 2845/43",
    "City": "PRAGUE",
    "Branch": "",
    "Postcode": "130 00",
    "Country": "Czech Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "OBKL",
    "bankCode": "CZ",
    "branchCode": "Z2X",
    "SWIFT Code": "OBKLCZ2X",
    "Bank Name": "OBERBANK AG",
    "Address": "NAM. PREMYSLA OTOKARA II 6, 3",
    "City": "CESKE BUDEJOVICE",
    "Branch": "",
    "Postcode": "370 01",
    "Country": "Czech Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "PYYM",
    "bankCode": "CZ",
    "branchCode": "ZPP",
    "SWIFT Code": "PYYMCZPP",
    "Bank Name": "PAYMASTER A.S.",
    "Address": "RYBNA 682, 14, FLOOR 1, STARE MESTO, PRAHA 1",
    "City": "PRAGUE",
    "Branch": "",
    "Postcode": "110 00",
    "Country": "Czech Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "PAER",
    "bankCode": "CZ",
    "branchCode": "GEN",
    "SWIFT Code": "PAERCZPPGEN",
    "Bank Name": "PAYMENT EXECUTION S.R.O.",
    "Address": "REVOLUCNI 724, 7, STARE MESTO",
    "City": "PRAGUE",
    "Branch": "",
    "Postcode": "110 00",
    "Country": "Czech Republic",
    "Connection": "Active"
  }
]
module.exports = czechRepublic
