const djibouti = [
  {
    "bankCode": "MRIN",
    "countryCode": "DJ",
    "branchCode": "JJD",
    "SWIFT Code": "MRINDJJD",
    "Bank Name": "BANK OF AFRICA MER ROUGE",
    "Address": "PLACE LAGARDE 10",
    "City": "DJIBOUTI",
    "Branch": "",
    "Postcode": "77101",
    "Country": "Djibouti",
    "Connection": "Active"
  },
  {
    "bankCode": "BCDJ",
    "countryCode": "DJ",
    "branchCode": "JJD",
    "SWIFT Code": "BCDJDJJD",
    "Bank Name": "BANQUE CENTRALE DE DJIBOUTI",
    "Address": "BOULEVARD SAINT LAURENT DU VAR",
    "City": "DJIBOUTI",
    "Branch": "",
    "Postcode": "77101",
    "Country": "Djibouti",
    "Connection": "Active"
  },
  {
    "bankCode": "BKCH",
    "countryCode": "DJ",
    "branchCode": "JJD",
    "SWIFT Code": "BKCHDJJD",
    "Bank Name": "BANQUE DE CHINE(DJIBOUTI) SA",
    "Address": "RUE DE LA SIESTA LOT 219B, SOUTH INDUSTRIAL ZONE",
    "City": "DJIBOUTI",
    "Branch": "",
    "Postcode": "77101",
    "Country": "Djibouti",
    "Connection": "Active"
  },
  {
    "bankCode": "DECD",
    "countryCode": "DJ",
    "branchCode": "JJD",
    "SWIFT Code": "DECDDJJD",
    "Bank Name": "BANQUE DE DEPOT ET CREDIT DJIBOUTI",
    "Address": "PLACE LAGARDE",
    "City": "DJIBOUTI",
    "Branch": "",
    "Postcode": "77101",
    "Country": "Djibouti",
    "Connection": "Active"
  },
  {
    "bankCode": "BCIM",
    "countryCode": "DJ",
    "branchCode": "JJX",
    "SWIFT Code": "BCIMDJJX",
    "Bank Name": "BANQUE POUR LE COMMERCE ET L'INDUSTRIE - MER ROUGE",
    "Address": "PLACE LAGARDE",
    "City": "DJIBOUTI",
    "Branch": "",
    "Postcode": "77101",
    "Country": "Djibouti",
    "Connection": "Active"
  },
  {
    "bankCode": "CACD",
    "countryCode": "DJ",
    "branchCode": "JJD",
    "SWIFT Code": "CACDDJJD",
    "Bank Name": "CAC INTERNATIONAL BANK",
    "Address": "FLOOR GF, ALKARAM BUILDING, RUE DE MARSEILLE",
    "City": "DJIBOUTI",
    "Branch": "",
    "Postcode": "77101",
    "Country": "Djibouti",
    "Connection": "Active"
  },
  {
    "bankCode": "CBET",
    "countryCode": "DJ",
    "branchCode": "JJD",
    "SWIFT Code": "CBETDJJD",
    "Bank Name": "COMMERCIAL BANK OF ETHIOPIA DJIBOUTI LTD",
    "Address": "DICO BUILDING, AVENUE GEORGES CLEMENCEAU",
    "City": "DJIBOUTI",
    "Branch": "",
    "Postcode": "77101",
    "Country": "Djibouti",
    "Connection": "Active"
  },
  {
    "bankCode": "EABD",
    "countryCode": "DJ",
    "branchCode": "JJD",
    "SWIFT Code": "EABDDJJD",
    "Bank Name": "EAST AFRICA BANK",
    "Address": "PLACE DU 27 JUIN",
    "City": "DJIBOUTI",
    "Branch": "",
    "Postcode": "77101",
    "Country": "Djibouti",
    "Connection": "Active"
  },
  {
    "bankCode": "EXTN",
    "countryCode": "DJ",
    "branchCode": "JJD",
    "SWIFT Code": "EXTNDJJD",
    "Bank Name": "EXIM BANK (DJIBOUTI) S.A.",
    "Address": "AVENUE MOHAMED FARAH",
    "City": "DJIBOUTI",
    "Branch": "",
    "Postcode": "77101",
    "Country": "Djibouti",
    "Connection": "Active"
  },
  {
    "bankCode": "IBBD",
    "countryCode": "DJ",
    "branchCode": "JJD",
    "SWIFT Code": "IBBDDJJD",
    "Bank Name": "INTERNATIONAL BUSINESS BANK DJIBOUTI (IB BANK-DJIBOUTI)",
    "Address": "IMMEUBLE DAMAL COMPLEXE, BOULAOS ZONE INDUSTRIELLE SUD",
    "City": "DJIBOUTI",
    "Branch": "",
    "Postcode": "77101",
    "Country": "Djibouti",
    "Connection": "Active"
  },
  {
    "bankCode": "ICDJ",
    "countryCode": "DJ",
    "branchCode": "JJD",
    "SWIFT Code": "ICDJDJJD",
    "Bank Name": "INTERNATIONAL INVESTMENT BANK S.A, DJIBOUTI",
    "Address": "PLACE DU 27 JUIN, IMMEUBLE NO 15, RUE DIETHIOPIE",
    "City": "DJIBOUTI",
    "Branch": "",
    "Postcode": "77101",
    "Country": "Djibouti",
    "Connection": "Active"
  },
  {
    "bankCode": "SAFB",
    "countryCode": "DJ",
    "branchCode": "JJD",
    "SWIFT Code": "SAFBDJJD",
    "Bank Name": "SABA AFRICAN BANK AS",
    "Address": "FLOOR 1, SABA BANK BUILDING, MOHAMED KAMEL, SALINES OUEST",
    "City": "DJIBOUTI",
    "Branch": "",
    "Postcode": "77101",
    "Country": "Djibouti",
    "Connection": "Active"
  },
  {
    "bankCode": "ISEA",
    "countryCode": "DJ",
    "branchCode": "JJD",
    "SWIFT Code": "ISEADJJD",
    "Bank Name": "SALAAM AFRICAN BANK",
    "Address": "AL TAJ BLDG 01, PIERRE PASCAL AVENUE",
    "City": "DJIBOUTI",
    "Branch": "",
    "Postcode": "77101",
    "Country": "Djibouti",
    "Connection": "Active"
  },
  {
    "bankCode": "SRIB",
    "countryCode": "DJ",
    "branchCode": "JJD",
    "SWIFT Code": "SRIBDJJD",
    "Bank Name": "SILK ROAD INTERNATIONAL BANK S.A",
    "Address": "HARAMOUS 1, LOT NO2",
    "City": "DJIBOUTI",
    "Branch": "",
    "Postcode": "77101",
    "Country": "Djibouti",
    "Connection": "Active"
  }
]
module.exports = djibouti
