const dominica = [
  {
    "countryCode": "CMWB",
    "bankCode": "DM",
    "branchCode": "MDM",
    "SWIFT Code": "CMWBDMDM",
    "Bank Name": "COMMONWEALTH BANK AND TRUST LIMITED",
    "Address": "FLOOR GF, FINANCIAL CENTRE, KENNEDY AVENUE",
    "City": "ROSEAU",
    "Branch": "",
    "Postcode": "",
    "Country": "Dominica",
    "Connection": "Active"
  },
  {
    "countryCode": "CMBK",
    "bankCode": "DM",
    "branchCode": "MDM",
    "SWIFT Code": "CMBKDMDM",
    "Bank Name": "COMPASS BANK AND TRUST CORPORATION",
    "Address": "FLOOR 1, 4 CASTLE STREET",
    "City": "ROSEAU",
    "Branch": "",
    "Postcode": "",
    "Country": "Dominica",
    "Connection": "Active"
  },
  {
    "countryCode": "GVDM",
    "bankCode": "DM",
    "branchCode": "MDM",
    "SWIFT Code": "GVDMDMDM",
    "Bank Name": "GOVERNMENT OF DOMINICA",
    "Address": "GOVERNMENT HEADQUARTERS, KENNEDY AVENUE",
    "City": "ROSEAU",
    "Branch": "",
    "Postcode": "",
    "Country": "Dominica",
    "Connection": "Active"
  },
  {
    "countryCode": "GITR",
    "bankCode": "DM",
    "branchCode": "MD2",
    "SWIFT Code": "GITRDMD2",
    "Bank Name": "GUARDIAN INTERNATIONAL BANK AND TRUST CORPORATION",
    "Address": "FLOOR 43, GREAT GEORGE STREET",
    "City": "ROSEAU",
    "Branch": "",
    "Postcode": "",
    "Country": "Dominica",
    "Connection": "Active"
  },
  {
    "countryCode": "NCDM",
    "bankCode": "DM",
    "branchCode": "MDM",
    "SWIFT Code": "NCDMDMDM",
    "Bank Name": "NATIONAL BANK OF DOMINICA LTD",
    "Address": "64 HILLSBOROUGH STREET",
    "City": "ROSEAU",
    "Branch": "",
    "Postcode": "00152",
    "Country": "Dominica",
    "Connection": "Active"
  },
  {
    "countryCode": "PAXU",
    "bankCode": "DM",
    "branchCode": "MDM",
    "SWIFT Code": "PAXUDMDM",
    "Bank Name": "PAXUM BANK LIMITED",
    "Address": "FLOOR 1, 1 CENTRE CROSS LANE",
    "City": "ROSEAU",
    "Branch": "",
    "Postcode": "00152",
    "Country": "Dominica",
    "Connection": "Active"
  },
  {
    "countryCode": "RBNK",
    "bankCode": "DM",
    "branchCode": "MDM",
    "SWIFT Code": "RBNKDMDM",
    "Bank Name": "REPUBLIC BANK (EC) LIMITED",
    "Address": "28 HILLSBOROUGH",
    "City": "ROSEAU",
    "Branch": "",
    "Postcode": "",
    "Country": "Dominica",
    "Connection": "Active"
  },
  {
    "countryCode": "RBNK",
    "bankCode": "DM",
    "branchCode": "DMA",
    "SWIFT Code": "RBNKDMDMDMA",
    "Bank Name": "REPUBLIC BANK (EC) LIMITED",
    "Address": "28 HILLSBOROUGH",
    "City": "ROSEAU",
    "Branch": "SETTLEMENTS",
    "Postcode": "",
    "Country": "Dominica",
    "Connection": "Active"
  },
  {
    "countryCode": "KICP",
    "bankCode": "DM",
    "branchCode": "MD2",
    "SWIFT Code": "KICPDMD2",
    "Bank Name": "THE KINGDOM BANK CORPORATION",
    "Address": "FLOOR 1, 43 GREAT GEORGE STREET",
    "City": "ROSEAU",
    "Branch": "",
    "Postcode": "",
    "Country": "Dominica",
    "Connection": "Active"
  },
  {
    "countryCode": "ZUMA",
    "bankCode": "DM",
    "branchCode": "MDM",
    "SWIFT Code": "ZUMADMDM",
    "Bank Name": "ZUMA BANK CORPORATION",
    "Address": "FLOOR 2, 42 KENNEDY AVENUE",
    "City": "ROSEAU",
    "Branch": "",
    "Postcode": "",
    "Country": "Dominica",
    "Connection": "Active"
  }
]
module.exports = dominica
