const dominicanRepublic = [
  {
    "countryCode": "NOSC",
    "bankCode": "DO",
    "branchCode": "OSD",
    "SWIFT Code": "NOSCDOSD",
    "Bank Name": "SCOTIABANK REPUBLICA DOMINICANA, S.A., BANCO MULTIPLE",
    "Address": "AVE. 27 DE FEBRERO ESQ. W.CHURCHILL, ENS. PIANTINI",
    "City": "SANTO DOMINGO",
    "Branch": "",
    "Postcode": "10128",
    "Country": "Dominican Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "ACXA",
    "bankCode": "DO",
    "branchCode": "OS2",
    "SWIFT Code": "ACXADOS2",
    "Bank Name": "AGENTE DE CAMBIO EXTRANJERO A.C.E., S.A.",
    "Address": "AVE. ABRAHAM LOINCOLS 609, PLAZA ALEXANDRA, FLOOR 4",
    "City": "SANTO DOMINGO",
    "Branch": "",
    "Postcode": "10121",
    "Country": "Dominican Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "ABHR",
    "bankCode": "DO",
    "branchCode": "OSD",
    "SWIFT Code": "ABHRDOSD",
    "Bank Name": "ASOCIACION BONAO DE AHORROS Y PRESTAMOS",
    "Address": "AVENIDA LIBERTAD, ABONAP 1,, ESQUINA CALLE JARAGUA 1",
    "City": "BONAO",
    "Branch": "",
    "Postcode": "42000",
    "Country": "Dominican Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "ACIB",
    "bankCode": "DO",
    "branchCode": "OSX",
    "SWIFT Code": "ACIBDOSX",
    "Bank Name": "ASOCIACION CIBAO DE AHORROS Y PRESTAMOS",
    "Address": "AUTOPISTA DUARTE, ESQUINA PIKY LORA, TORRE CORPORATIVA ACAP",
    "City": "SANTIAGO",
    "Branch": "",
    "Postcode": "51000",
    "Country": "Dominican Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "ANAY",
    "bankCode": "DO",
    "branchCode": "OSD",
    "SWIFT Code": "ANAYDOSD",
    "Bank Name": "ASOCIACION LA NACIONAL DE AHORROS Y PRESTAMOS",
    "Address": "AVE. 27 DE FEBRERO 218, EL VERGEL",
    "City": "SANTO DOMINGO",
    "Branch": "",
    "Postcode": "10107",
    "Country": "Dominican Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "ALVR",
    "bankCode": "DO",
    "branchCode": "OS2",
    "SWIFT Code": "ALVRDOS2",
    "Bank Name": "ASOCIACION LA VEGA REAL DE AHORROS Y PRESTAMOS",
    "Address": "ANTONIO GUZMAN ESQ JUAN RODRIGUEZ",
    "City": "LA VEGA",
    "Branch": "",
    "Postcode": "00065",
    "Country": "Dominican Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "AMAR",
    "bankCode": "DO",
    "branchCode": "OS2",
    "SWIFT Code": "AMARDOS2",
    "Bank Name": "ASOCIACION MOCANA DE AHORROS Y PRESTAMOS",
    "Address": "INDEPENDENCIA ESQUINA JOSE MARIA, MICHEL",
    "City": "MOCA",
    "Branch": "",
    "Postcode": "56000",
    "Country": "Dominican Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "APOP",
    "bankCode": "DO",
    "branchCode": "OSX",
    "SWIFT Code": "APOPDOSX",
    "Bank Name": "ASOCIACION POPULAR DE AHORROS Y PRESTAMOS (APAP)",
    "Address": "27 DE FEBRERO ESQ MAXIMO GOMEZ",
    "City": "SANTO DOMINGO",
    "Branch": "",
    "Postcode": "10107",
    "Country": "Dominican Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "BAGR",
    "bankCode": "DO",
    "branchCode": "OSA",
    "SWIFT Code": "BAGRDOSA",
    "Bank Name": "BANCO AGRICOLA DE LA REPUBLICA DOMINICANA",
    "Address": "AVENIDA GEORGES WASHINGTON 601",
    "City": "SANTO DOMINGO",
    "Branch": "",
    "Postcode": "10207",
    "Country": "Dominican Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "BAAC",
    "bankCode": "DO",
    "branchCode": "OSD",
    "SWIFT Code": "BAACDOSD",
    "Bank Name": "BANCO ATLANTICO DE AHORRO Y CREDITO, S.A.",
    "Address": "CALLE FANTINO FALCO, PLAZA CRISCAR I, FLOOR 2",
    "City": "SANTO DOMINGO",
    "Branch": "",
    "Postcode": "11202",
    "Country": "Dominican Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "BCRD",
    "bankCode": "DO",
    "branchCode": "OMA",
    "SWIFT Code": "BCRDDOSXOMA",
    "Bank Name": "BANCO CENTRAL DE LA REPUBLICA DOMINICANA",
    "Address": "CALLE PEDRO HENRIQUEZ URENA, ESQ.LEOPOLDO NAVARRO",
    "City": "SANTO DOMINGO",
    "Branch": "",
    "Postcode": "10106",
    "Country": "Dominican Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "BCRD",
    "bankCode": "DO",
    "branchCode": "SBC",
    "SWIFT Code": "BCRDDOSXSBC",
    "Bank Name": "BANCO CENTRAL DE LA REPUBLICA DOMINICANA",
    "Address": "CALLE PEDRO HENRIQUEZ URENA, ESQ.LEOPOLDO NAVARRO",
    "City": "SANTO DOMINGO",
    "Branch": "",
    "Postcode": "10106",
    "Country": "Dominican Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "BCRD",
    "bankCode": "DO",
    "branchCode": "OSX",
    "SWIFT Code": "BCRDDOSX",
    "Bank Name": "BANCO CENTRAL DE LA REPUBLICA DOMINICANA",
    "Address": "CALLE PEDRO HENRIQUEZ URENA, ESQ.LEOPOLDO NAVARRO",
    "City": "SANTO DOMINGO",
    "Branch": "",
    "Postcode": "10106",
    "Country": "Dominican Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "AHCD",
    "bankCode": "DO",
    "branchCode": "OS2",
    "SWIFT Code": "AHCDDOS2",
    "Bank Name": "BANCO DE AHORRO Y CREDITO ADOPEM, S.A.",
    "Address": "HERIBERTO PIETER 12, ENSANCHE NACO",
    "City": "SANTO DOMINGO",
    "Branch": "BANCO ADOPEM",
    "Postcode": "10122",
    "Country": "Dominican Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "AHCC",
    "bankCode": "DO",
    "branchCode": "OS2",
    "SWIFT Code": "AHCCDOS2",
    "Bank Name": "BANCO DE AHORRO Y CREDITO COFACI,S.A.",
    "Address": "37 CALLE PEDRO LIVIO CEDENO NO 174, CASA CASTILLO HERMANOS, FLOOR 2",
    "City": "SANTO DOMINGO",
    "Branch": "",
    "Postcode": "10514",
    "Country": "Dominican Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "AHCO",
    "bankCode": "DO",
    "branchCode": "OSM",
    "SWIFT Code": "AHCODOSM",
    "Bank Name": "BANCO DE AHORRO Y CREDITO CONFISA,S.A.",
    "Address": "FRANCISCO PRATS RAMIREZ MANUEL DE, JESUS TRONCOSO 149 EDIFICIO CONFISA",
    "City": "SANTO DOMINGO",
    "Branch": "",
    "Postcode": "10149",
    "Country": "Dominican Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "AHCG",
    "bankCode": "DO",
    "branchCode": "OS3",
    "SWIFT Code": "AHCGDOS3",
    "Bank Name": "BANCO DE AHORRO Y CREDITO FIHOGAR,S.A.",
    "Address": "AVE. SAN MARTIN 253, EDIFICIO SANTANITA",
    "City": "SANTO DOMINGO",
    "Branch": "",
    "Postcode": "10514",
    "Country": "Dominican Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "ACFE",
    "bankCode": "DO",
    "branchCode": "OSC",
    "SWIFT Code": "ACFEDOSC",
    "Bank Name": "BANCO DE AHORRO Y CREDITO FONDESA, S.A. (BANFONDESA)",
    "Address": "CALLE RESTAURACION, ESQUINA CALLE, JACUBA 127 EDIFICIO CORPORATIVO",
    "City": "SANTIAGO",
    "Branch": "",
    "Postcode": "51000",
    "Country": "Dominican Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "AHRI",
    "bankCode": "DO",
    "branchCode": "OS2",
    "SWIFT Code": "AHRIDOS2",
    "Bank Name": "BANCO DE AHORRO Y CREDITO JMMB BANK, S.A.",
    "Address": "AVENIDA GUSTAVO MEJIA RICART 102, TORRE CORPORATIVO 2010, FLOOR 1",
    "City": "SANTO DOMINGO",
    "Branch": "",
    "Postcode": "10122",
    "Country": "Dominican Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "UNON",
    "bankCode": "DO",
    "branchCode": "OSD",
    "SWIFT Code": "UNONDOSD",
    "Bank Name": "BANCO DE AHORRO Y CREDITO UNION S.A.",
    "Address": "AVENIDA SARASOTA 20, TORRE EMPRESARIAL AIRD, FLOOR 9",
    "City": "SANTO DOMINGO",
    "Branch": "",
    "Postcode": "10109",
    "Country": "Dominican Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "BRRD",
    "bankCode": "DO",
    "branchCode": "OSD",
    "SWIFT Code": "BRRDDOSD",
    "Bank Name": "BANCO DE RESERVAS DE LA REPUBLICA DOMINICANA",
    "Address": "AVENIDA WINSTON CHURCHILL ESQUINA, PORFIRIO HERRERA TORRE BANRESERVAS",
    "City": "SANTO DOMINGO",
    "Branch": "",
    "Postcode": "03699",
    "Country": "Dominican Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "PVDL",
    "bankCode": "DO",
    "branchCode": "OSD",
    "SWIFT Code": "PVDLDOSD",
    "Bank Name": "BANCO MULTIPLE ACTIVO DOMINICANA, S.A.",
    "Address": "AVE. TIRADENTES, CENTRO COMERCIAL NACO II, LOCAL 1B, ENSANCHE NACO",
    "City": "SANTO DOMINGO",
    "Branch": "",
    "Postcode": "10119",
    "Country": "Dominican Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "AHCM",
    "bankCode": "DO",
    "branchCode": "OSD",
    "SWIFT Code": "AHCMDOSD",
    "Bank Name": "BANCO MULTIPLE ADEMI. S.A.",
    "Address": "AV. PEDRO HENRIQUEZ URENA",
    "City": "SANTO DOMINGO",
    "Branch": "",
    "Postcode": "10106",
    "Country": "Dominican Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "BBDI",
    "bankCode": "DO",
    "branchCode": "OSD",
    "SWIFT Code": "BBDIDOSD",
    "Bank Name": "BANCO MULTIPLE BDI, S.A.",
    "Address": "AVE. SARASOTA 27, ENSANCHE LA JULIA",
    "City": "SANTO DOMINGO",
    "Branch": "",
    "Postcode": "10109",
    "Country": "Dominican Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "BELN",
    "bankCode": "DO",
    "branchCode": "OSD",
    "SWIFT Code": "BELNDOSD",
    "Bank Name": "BANCO MULTIPLE BELLBANK",
    "Address": "AV GUSTAVO MEJIA RICART ESQ, ABRAHAM LINCOLN TORRE CORPORATIVO, 2010, FLOOR 9 PIANTINI",
    "City": "SANTO DOMINGO",
    "Branch": "",
    "Postcode": "10114",
    "Country": "Dominican Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "BCBH",
    "bankCode": "DO",
    "branchCode": "OSD",
    "SWIFT Code": "BCBHDOSD",
    "Bank Name": "BANCO MULTIPLE BHD S.A.",
    "Address": "AV. WINSTON CHURCHILL ESQ 27 DE, FEBRERO EDIFICIO SUR PLAZA BHD",
    "City": "SANTO DOMINGO",
    "Branch": "HEADQUARTERS OFFICE",
    "Postcode": "21721",
    "Country": "Dominican Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "STGO",
    "bankCode": "DO",
    "branchCode": "OSD",
    "SWIFT Code": "STGODOSD",
    "Bank Name": "BANCO MULTIPLE CARIBE INTERNACIONAL, S.A.",
    "Address": "AVENIDA 27 DE FEBRERO",
    "City": "SANTO DOMINGO",
    "Branch": "",
    "Postcode": "10122",
    "Country": "Dominican Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "AHCS",
    "bankCode": "DO",
    "branchCode": "OSD",
    "SWIFT Code": "AHCSDOSD",
    "Bank Name": "BANCO MULTIPLE DE LAS AMERICAS, S.A",
    "Address": "CALLE FRANCISCO PRATS RAMIREZ, ESQUINA PADRE EMILIANO TARDIF",
    "City": "SANTO DOMINGO",
    "Branch": "",
    "Postcode": "10144",
    "Country": "Dominican Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "BCCE",
    "bankCode": "DO",
    "branchCode": "OSD",
    "SWIFT Code": "BCCEDOSD",
    "Bank Name": "BANCO MULTIPLE LAFISE S.A.",
    "Address": "AV. ABRAHAM LINCOLN 414",
    "City": "SANTO DOMINGO",
    "Branch": "",
    "Postcode": "10147",
    "Country": "Dominican Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "BLDH",
    "bankCode": "DO",
    "branchCode": "OSD",
    "SWIFT Code": "BLDHDOSD",
    "Bank Name": "BANCO MULTIPLE LOPEZ DE HARO, S.A.",
    "Address": "AVENIDA SARASOTA 20",
    "City": "SANTO DOMINGO",
    "Branch": "",
    "Postcode": "10109",
    "Country": "Dominican Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "PRHR",
    "bankCode": "DO",
    "branchCode": "OSD",
    "SWIFT Code": "PRHRDOSD",
    "Bank Name": "BANCO MULTIPLE PROMERICA DE LA REPUBLICA DOMINICANA",
    "Address": "AV. ROBERTO PASTORIZA ESQUINA",
    "City": "SANTO DOMINGO",
    "Branch": "",
    "Postcode": "10148",
    "Country": "Dominican Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "SCRZ",
    "bankCode": "DO",
    "branchCode": "OSD",
    "SWIFT Code": "SCRZDOSD",
    "Bank Name": "BANCO MULTIPLE SANTA CRUZ, S.A.",
    "Address": "AV. LOPE DE VEGA 21, ENSANCHE NACO",
    "City": "SANTO DOMINGO",
    "Branch": "",
    "Postcode": "10122",
    "Country": "Dominican Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "OPAR",
    "bankCode": "DO",
    "branchCode": "OSD",
    "SWIFT Code": "OPARDOSD",
    "Bank Name": "BANCO OPTIMA DE AHORRO Y CREDITO, S.A.",
    "Address": "CALLE CUB SCOUT 42, ESQUINA BOY SCOUT, NACO",
    "City": "SANTO DOMINGO",
    "Branch": "",
    "Postcode": "10012",
    "Country": "Dominican Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "BPDO",
    "bankCode": "DO",
    "branchCode": "OSX",
    "SWIFT Code": "BPDODOSX",
    "Bank Name": "BANCO POPULAR DOMINICANO, S.A. BANCO MULTIPLE",
    "Address": "AVENIDA JOHN F. KENNEDY ESQ., MAXIMO GOMEZ 20 TORRE POPULAR,, FLOOR 4",
    "City": "SANTO DOMINGO",
    "Branch": "",
    "Postcode": "10203",
    "Country": "Dominican Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "BPDO",
    "bankCode": "DO",
    "branchCode": "REM",
    "SWIFT Code": "BPDODOSXREM",
    "Bank Name": "BANCO POPULAR DOMINICANO, S.A. BANCO MULTIPLE",
    "Address": "",
    "City": "SANTO DOMINGO",
    "Branch": "DEPTO. TRASFERENCIAS INTERNACIONALES",
    "Postcode": "",
    "Country": "Dominican Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "VIME",
    "bankCode": "DO",
    "branchCode": "OSD",
    "SWIFT Code": "VIMEDOSD",
    "Bank Name": "BANCO VIMENCA",
    "Address": "AV. ABRAHAM LINCOLN",
    "City": "SANTO DOMINGO",
    "Branch": "",
    "Postcode": "10148",
    "Country": "Dominican Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "BANS",
    "bankCode": "DO",
    "branchCode": "OSD",
    "SWIFT Code": "BANSDOSD",
    "Bank Name": "BANESCO BANCO MULTIPLE, S.A.",
    "Address": "AVE. ABRAHAM LINCOLN 1021, PIANTINI",
    "City": "SANTO DOMINGO",
    "Branch": "",
    "Postcode": "10127",
    "Country": "Dominican Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "BHDV",
    "bankCode": "DO",
    "branchCode": "OSD",
    "SWIFT Code": "BHDVDOSD",
    "Bank Name": "BHD LEON PUESTO DE BOLSA, S.A.",
    "Address": "LUIS F. THOMEN ESQ. WINSTON, CHURCHILL TORRE BHD",
    "City": "SANTO DOMINGO",
    "Branch": "",
    "Postcode": "10147",
    "Country": "Dominican Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "CSHA",
    "bankCode": "DO",
    "branchCode": "OS2",
    "SWIFT Code": "CSHADOS2",
    "Bank Name": "CASHAM S.A.",
    "Address": "LUIS F. THOMEN W/ WINSTON CHURCHILL, TORRE BHD, FLOOR 11",
    "City": "SANTO DOMINGO",
    "Branch": "",
    "Postcode": "10147",
    "Country": "Dominican Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "CVDP",
    "bankCode": "DO",
    "branchCode": "OSD",
    "SWIFT Code": "CVDPDOSD",
    "Bank Name": "CEVALDOM DEPOSITO CENTRALIZADO DE VALORES, S.A.",
    "Address": "CALLE RAFAEL AUGUSTO SANCHEZ, ESQUINA FREDDY PRESTOL CASTILLO 86, ROBLE CORPORATE CENTER, FLOOR 3",
    "City": "SANTO DOMINGO",
    "Branch": "",
    "Postcode": "10148",
    "Country": "Dominican Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "CVDP",
    "bankCode": "DO",
    "branchCode": "GAR",
    "SWIFT Code": "CVDPDOSDGAR",
    "Bank Name": "CEVALDOM DEPOSITO CENTRALIZADO DE VALORES, S.A.",
    "Address": "CALLE RAFAEL AUGUSTO SANCHEZ, ESQUINA FREDDY PRESTOL CASTILLO 86, ROBLE CORPORATE CENTER, FLOOR 3",
    "City": "SANTO DOMINGO",
    "Branch": "",
    "Postcode": "10150",
    "Country": "Dominican Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "CITI",
    "bankCode": "DO",
    "branchCode": "022",
    "SWIFT Code": "CITIDOSD022",
    "Bank Name": "CITIBANK, N.A.",
    "Address": "CALLE EL SOL ESQ MELLA",
    "City": "SANTIAGO",
    "Branch": "",
    "Postcode": "51000",
    "Country": "Dominican Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "CITI",
    "bankCode": "DO",
    "branchCode": "OSD",
    "SWIFT Code": "CITIDOSD",
    "Bank Name": "CITIBANK, N.A.",
    "Address": "AVENUE WINSTON CHURCHILL 1099, ACROPOLIS CENTER CITI TOWER",
    "City": "SANTO DOMINGO",
    "Branch": "",
    "Postcode": "10128",
    "Country": "Dominican Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "CITI",
    "bankCode": "DO",
    "branchCode": "CTV",
    "SWIFT Code": "CITIDOSDCTV",
    "Bank Name": "CITIBANK, N.A.",
    "Address": "",
    "City": "SANTO DOMINGO",
    "Branch": "CITIINVERSIONES S.A.",
    "Postcode": "",
    "Country": "Dominican Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "CCLC",
    "bankCode": "DO",
    "branchCode": "OSM",
    "SWIFT Code": "CCLCDOSM",
    "Bank Name": "CORPORACION DE CREDITO LEASING CONFISA, S.A.",
    "Address": "FRANCISCO PRATS RAMIREZ MANUEL DE, JESUS TRONCOSO 149 EDIFICIO CONFISA",
    "City": "SANTO DOMINGO",
    "Branch": "",
    "Postcode": "10148",
    "Country": "Dominican Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "IRPL",
    "bankCode": "DO",
    "branchCode": "OSD",
    "SWIFT Code": "IRPLDOSD",
    "Bank Name": "INVERSIONES AND RESERVAS S.A. PUESTO DE BOLSA",
    "Address": "CALLE FILOMENA GOMEZ DE COVA ESQ., AVE. GUSTAVO MEJIA RICART 3, EDIFICIO CORPORATIVO 2015, FLOOR, 13, LOCAL 1302",
    "City": "SANTO DOMINGO",
    "Branch": "",
    "Postcode": "10125",
    "Country": "Dominican Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "MIOV",
    "bankCode": "DO",
    "branchCode": "OS2",
    "SWIFT Code": "MIOVDOS2",
    "Bank Name": "MIO MOVIL, S.A.",
    "Address": "SAN MARTIN DE PORRES 3",
    "City": "SANTO DOMINGO",
    "Branch": "",
    "Postcode": "10119",
    "Country": "Dominican Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "MCAR",
    "bankCode": "DO",
    "branchCode": "OSD",
    "SWIFT Code": "MCARDOSD",
    "Bank Name": "MOTOR CREDITO, S.A., BANCO DE AHORRO Y CREDITO",
    "Address": "MOTOR CREDITO HAIM LOPEZ PENHA, ABRAHAM LINCOLN FLOOR 1",
    "City": "SANTO DOMINGO",
    "Branch": "",
    "Postcode": "10126",
    "Country": "Dominican Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "NITK",
    "bankCode": "DO",
    "branchCode": "OSD",
    "SWIFT Code": "NITKDOSD",
    "Bank Name": "NICKET S.A.",
    "Address": "ELAB 2DO AVENIDA GUSTAVO MEJIA, RICART 128",
    "City": "SANTO DOMINGO",
    "Branch": "",
    "Postcode": "10147",
    "Country": "Dominican Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "PVPO",
    "bankCode": "DO",
    "branchCode": "OSD",
    "SWIFT Code": "PVPODOSD",
    "Bank Name": "PRIMMA VALORES, S.A. PUESTO DE BOLSA",
    "Address": "AVE ROBERTO PASTORIZA 358, TORRE ROBERTO PASTORIZA, FLOOR 10",
    "City": "SANTO DOMINGO",
    "Branch": "",
    "Postcode": "10127",
    "Country": "Dominican Republic",
    "Connection": "Active"
  },
  {
    "countryCode": "QDDM",
    "bankCode": "DO",
    "branchCode": "OSD",
    "SWIFT Code": "QDDMDOSD",
    "Bank Name": "QIK BANCO DIGITAL DOMINICANO, S.A. BANCO MULTIPLE",
    "Address": "CALLE FEDERICO GERALDINO ESQUINA, 27 DE FEBRERO 256 TORRE, EMPRESARIAL, FLOOR 2",
    "City": "SANTO DOMINGO",
    "Branch": "",
    "Postcode": "10127",
    "Country": "Dominican Republic",
    "Connection": "Active"
  }
]
module.exports = dominicanRepublic
