const ecuador = [
  {
    "countryCode": "MUPI",
    "bankCode": "EC",
    "branchCode": "CEQ",
    "SWIFT Code": "MUPIECEQ",
    "Bank Name": "ASOCIACION MUTUALISTA DE AHORRO Y CREDITO PARA LA VIVIENDA PICHINCHA",
    "Address": "18 DE SEPTIEMBRE Y JUAN LEON MERA, E4-161",
    "City": "QUITO",
    "Branch": "",
    "Postcode": "170150",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "BASA",
    "bankCode": "EC",
    "branchCode": "CEG",
    "SWIFT Code": "BASAECEG",
    "Bank Name": "BANCO AMAZONAS S.A.",
    "Address": "GRAL CORDOVA Y P. ICAZA 1036",
    "City": "GUAYAQUIL",
    "Branch": "",
    "Postcode": "090313",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "BBOL",
    "bankCode": "EC",
    "branchCode": "CEG",
    "SWIFT Code": "BBOLECEG",
    "Bank Name": "BANCO BOLIVARIANO C.A.",
    "Address": "JUNIN Y PANAMA 200",
    "City": "GUAYAQUIL",
    "Branch": "",
    "Postcode": "090150",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "BBOL",
    "bankCode": "EC",
    "branchCode": "100",
    "SWIFT Code": "BBOLECEG100",
    "Bank Name": "BANCO BOLIVARIANO C.A.",
    "Address": "JUNIN Y PANAMA 200",
    "City": "GUAYAQUIL",
    "Branch": "MATRIZ",
    "Postcode": "090150",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "BCEN",
    "bankCode": "EC",
    "branchCode": "120",
    "SWIFT Code": "BCENECEQ120",
    "Bank Name": "BANCO CENTRAL DEL ECUADOR",
    "Address": "P ICAZA ENTRE PICHINCHA Y P. CA 203",
    "City": "GUAYAQUIL",
    "Branch": "",
    "Postcode": "170150",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "BCEN",
    "bankCode": "EC",
    "branchCode": "100",
    "SWIFT Code": "BCENECEQ100",
    "Bank Name": "BANCO CENTRAL DEL ECUADOR",
    "Address": "",
    "City": "QUITO",
    "Branch": "",
    "Postcode": "",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "BCEN",
    "bankCode": "EC",
    "branchCode": "CEQ",
    "SWIFT Code": "BCENECEQ",
    "Bank Name": "BANCO CENTRAL DEL ECUADOR",
    "Address": "AV. 10 DE AGOSTO Y BRICENO 11-409",
    "City": "QUITO",
    "Branch": "",
    "Postcode": "170136",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PROD",
    "bankCode": "EC",
    "branchCode": "100",
    "SWIFT Code": "PRODECEQ100",
    "Bank Name": "BANCO DE LA PRODUCCION S.A. PRODUBANCO",
    "Address": "PEDRO CARBO Y LUQUE 604",
    "City": "GUAYAQUIL",
    "Branch": "",
    "Postcode": "",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PROD",
    "bankCode": "EC",
    "branchCode": "CEQ",
    "SWIFT Code": "PRODECEQ",
    "Bank Name": "BANCO DE LA PRODUCCION S.A. PRODUBANCO",
    "Address": "CENTRO CORPORATIVO EKOPARK AV., SIMON BOLIVAR Y VIA A NAYON FLOOR 1",
    "City": "QUITO",
    "Branch": "",
    "Postcode": "170124",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "LOJB",
    "bankCode": "EC",
    "branchCode": "CEL",
    "SWIFT Code": "LOJBECEL",
    "Bank Name": "BANCO DE LOJA",
    "Address": "BOLIVAR Y ROCAFUERTE ESQUINA",
    "City": "LOJA",
    "Branch": "",
    "Postcode": "110130",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "BMAC",
    "bankCode": "EC",
    "branchCode": "0EG",
    "SWIFT Code": "BMACECEG0EG",
    "Bank Name": "BANCO DE MACHALA, C.A.",
    "Address": "PLAZA ICAZA 437",
    "City": "GUAYAQUIL",
    "Branch": "",
    "Postcode": "",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "BMAC",
    "bankCode": "EC",
    "branchCode": "CEG",
    "SWIFT Code": "BMACECEG",
    "Bank Name": "BANCO DE MACHALA, C.A.",
    "Address": "P. CARBO Y P. YCAZA",
    "City": "GUAYAQUIL",
    "Branch": "",
    "Postcode": "090313",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {},
  {
    "countryCode": "BMAC",
    "bankCode": "EC",
    "branchCode": "0E5",
    "SWIFT Code": "BMACECEG0E5",
    "Bank Name": "BANCO DE MACHALA, C.A.",
    "Address": "10 DE AGOSTO Y MACHALA",
    "City": "PASAJE",
    "Branch": "",
    "Postcode": "070950",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "BMAC",
    "bankCode": "EC",
    "branchCode": "0E3",
    "SWIFT Code": "BMACECEG0E3",
    "Bank Name": "BANCO DE MACHALA, C.A.",
    "Address": "AVENIDA SUCRE",
    "City": "PINAS",
    "Branch": "",
    "Postcode": "071050",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "BMAC",
    "bankCode": "EC",
    "branchCode": "0E8",
    "SWIFT Code": "BMACECEG0E8",
    "Bank Name": "BANCO DE MACHALA, C.A.",
    "Address": "CALLE BOLIVAR, FLOOR 4-5",
    "City": "QUEVEDO",
    "Branch": "",
    "Postcode": "120302",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "BMAC",
    "bankCode": "EC",
    "branchCode": "0E7",
    "SWIFT Code": "BMACECEG0E7",
    "Bank Name": "BANCO DE MACHALA, C.A.",
    "Address": "EL ORO Y SUCRE",
    "City": "SANTA ROSA",
    "Branch": "",
    "Postcode": "070602",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "BMAC",
    "bankCode": "EC",
    "branchCode": "0E6",
    "SWIFT Code": "BMACECEG0E6",
    "Bank Name": "BANCO DE MACHALA, C.A.",
    "Address": "PLAZA DE LA INDEPENDENCIA",
    "City": "ZARUMA",
    "Branch": "",
    "Postcode": "170143",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "AUST",
    "bankCode": "EC",
    "branchCode": "CEQ",
    "SWIFT Code": "AUSTECEQ",
    "Bank Name": "BANCO DEL AUSTRO S.A.",
    "Address": "SUCRE Y BORRERO ESQ",
    "City": "CUENCA",
    "Branch": "",
    "Postcode": "",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "LITB",
    "bankCode": "EC",
    "branchCode": "CEF",
    "SWIFT Code": "LITBECEF",
    "Bank Name": "BANCO DEL LITORAL",
    "Address": "MALECON 512, EDIFICIO RIVIERA",
    "City": "GUAYAQUIL",
    "Branch": "",
    "Postcode": "090313",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PACI",
    "bankCode": "EC",
    "branchCode": "400",
    "SWIFT Code": "PACIECEG400",
    "Bank Name": "BANCO DEL PACIFICO",
    "Address": "AVENIDA CEVALLOS Y LALAMA",
    "City": "AMBATO",
    "Branch": "",
    "Postcode": "180109",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PACI",
    "bankCode": "EC",
    "branchCode": "300",
    "SWIFT Code": "PACIECEG300",
    "Bank Name": "BANCO DEL PACIFICO",
    "Address": "BENIGNO MALO 975",
    "City": "CUENCA",
    "Branch": "",
    "Postcode": "010107",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PACI",
    "bankCode": "EC",
    "branchCode": "100",
    "SWIFT Code": "PACIECEG100",
    "Bank Name": "BANCO DEL PACIFICO",
    "Address": "FRANCISCO DE P. ICAZA Y PICHINC 200",
    "City": "GUAYAQUIL",
    "Branch": "",
    "Postcode": "090306",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PACI",
    "bankCode": "EC",
    "branchCode": "CEG",
    "SWIFT Code": "PACIECEG",
    "Bank Name": "BANCO DEL PACIFICO",
    "Address": "FRANCISCO DE P. ICAZA Y PICHINC 200",
    "City": "GUAYAQUIL",
    "Branch": "HEAD OFFICE",
    "Postcode": "090306",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PACI",
    "bankCode": "EC",
    "branchCode": "IBA",
    "SWIFT Code": "PACIECEGIBA",
    "Bank Name": "BANCO DEL PACIFICO",
    "Address": "",
    "City": "IBARRA",
    "Branch": "",
    "Postcode": "",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PACI",
    "bankCode": "EC",
    "branchCode": "110",
    "SWIFT Code": "PACIECEG110",
    "Bank Name": "BANCO DEL PACIFICO",
    "Address": "Y AVENIDA 9 DE OCTUBRE SALOMON, PINARGOTE 202",
    "City": "LA LIBERTAD",
    "Branch": "",
    "Postcode": "",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PACI",
    "bankCode": "EC",
    "branchCode": "200",
    "SWIFT Code": "PACIECEG200",
    "Bank Name": "BANCO DEL PACIFICO",
    "Address": "AVENIDA CIRCUNVALACION NORTE",
    "City": "MACHALA",
    "Branch": "",
    "Postcode": "070102",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PACI",
    "bankCode": "EC",
    "branchCode": "600",
    "SWIFT Code": "PACIECEG600",
    "Bank Name": "BANCO DEL PACIFICO",
    "Address": "AVENIDA TERCERA Y CALLE E12",
    "City": "MANTA",
    "Branch": "",
    "Postcode": "",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PACI",
    "bankCode": "EC",
    "branchCode": "640",
    "SWIFT Code": "PACIECEG640",
    "Bank Name": "BANCO DEL PACIFICO",
    "Address": "",
    "City": "PORTOVIEJO",
    "Branch": "",
    "Postcode": "",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PACI",
    "bankCode": "EC",
    "branchCode": "500",
    "SWIFT Code": "PACIECEG500",
    "Bank Name": "BANCO DEL PACIFICO",
    "Address": "AVENIDA NACIONES UNIDAS 680",
    "City": "QUITO",
    "Branch": "",
    "Postcode": "170135",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PACI",
    "bankCode": "EC",
    "branchCode": "350",
    "SWIFT Code": "PACIECEG350",
    "Bank Name": "BANCO DEL PACIFICO",
    "Address": "",
    "City": "RIOBAMBA",
    "Branch": "",
    "Postcode": "",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PACI",
    "bankCode": "EC",
    "branchCode": "871",
    "SWIFT Code": "PACIECEG871",
    "Bank Name": "BANCO DEL PACIFICO",
    "Address": "PTO. AYORA AVENIDA CHARLES DARWIN, S/N",
    "City": "SANTA CRUZ",
    "Branch": "GALAPAGOS",
    "Postcode": "200350",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PACI",
    "bankCode": "EC",
    "branchCode": "510",
    "SWIFT Code": "PACIECEG510",
    "Bank Name": "BANCO DEL PACIFICO",
    "Address": "",
    "City": "SANTO DOMINGO",
    "Branch": "",
    "Postcode": "",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "CODS",
    "bankCode": "EC",
    "branchCode": "001",
    "SWIFT Code": "CODSECEQ001",
    "Bank Name": "BANCO DESARROLLO DE LOS PUEBLOS S.A. CODESARROLLO",
    "Address": "CALLE MANUEL UGALLARDO",
    "City": "MARCABELI",
    "Branch": "MARCABELI BRANCH",
    "Postcode": "170179",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "CODS",
    "bankCode": "EC",
    "branchCode": "CEQ",
    "SWIFT Code": "CODSECEQ",
    "Bank Name": "BANCO DESARROLLO DE LOS PUEBLOS S.A. CODESARROLLO",
    "Address": "LADRON DE GUEVARA Y BARCELONA, E14-408",
    "City": "QUITO",
    "Branch": "",
    "Postcode": "170143",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "BGRM",
    "bankCode": "EC",
    "branchCode": "100",
    "SWIFT Code": "BGRMECEQ100",
    "Bank Name": "BANCO GENERAL RUMINAHUI S.A.",
    "Address": "LOS RIOS Y HURTADO 906",
    "City": "GUAYAQUIL",
    "Branch": "GUAYAQUIL BRANCH",
    "Postcode": "090311",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "BGRM",
    "bankCode": "EC",
    "branchCode": "200",
    "SWIFT Code": "BGRMECEQ200",
    "Bank Name": "BANCO GENERAL RUMINAHUI S.A.",
    "Address": "AYACUCHO ENTRE DO OCTUBRO Y SUCRO 9",
    "City": "MACHALA",
    "Branch": "MACHALA BRANCH",
    "Postcode": "",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "BGRM",
    "bankCode": "EC",
    "branchCode": "CEQ",
    "SWIFT Code": "BGRMECEQ",
    "Bank Name": "BANCO GENERAL RUMINAHUI S.A.",
    "Address": "AV. REPUBLICA Y MARTIN CARRI E37-55",
    "City": "QUITO",
    "Branch": "",
    "Postcode": "",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "BGRM",
    "bankCode": "EC",
    "branchCode": "505",
    "SWIFT Code": "BGRMECEQ505",
    "Bank Name": "BANCO GENERAL RUMINAHUI S.A.",
    "Address": "",
    "City": "QUITO",
    "Branch": "CASH MANAGEMENT",
    "Postcode": "",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "GUAY",
    "bankCode": "EC",
    "branchCode": "CEG",
    "SWIFT Code": "GUAYECEG",
    "Bank Name": "BANCO GUAYAQUIL S.A.",
    "Address": "FRANCISCO P. ICAZA Y PICHINCHA 107",
    "City": "GUAYAQUIL",
    "Branch": "",
    "Postcode": "090306",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "GUAY",
    "bankCode": "EC",
    "branchCode": "105",
    "SWIFT Code": "GUAYECEG105",
    "Bank Name": "BANCO GUAYAQUIL S.A.",
    "Address": "PICHINCHA Y P. ICAZA 107",
    "City": "GUAYAQUIL",
    "Branch": "COMERCIO EXTERIOR REGION CENTRO",
    "Postcode": "090150",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "BINT",
    "bankCode": "EC",
    "branchCode": "100",
    "SWIFT Code": "BINTECEQ100",
    "Bank Name": "BANCO INTERNACIONAL S.A.",
    "Address": "",
    "City": "GUAYAQUIL",
    "Branch": "",
    "Postcode": "",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "BINT",
    "bankCode": "EC",
    "branchCode": "CEQ",
    "SWIFT Code": "BINTECEQ",
    "Bank Name": "BANCO INTERNACIONAL S.A.",
    "Address": "AVENIDA PATRIA Y 9 DE OCTUBRE, E-421 E-421",
    "City": "QUITO",
    "Branch": "HEAD OFFICE AND ALL BRANCHES",
    "Postcode": "170143",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PICH",
    "bankCode": "EC",
    "branchCode": "400",
    "SWIFT Code": "PICHECEQ400",
    "Bank Name": "BANCO PICHINCHA C.A.",
    "Address": "",
    "City": "AMBATO",
    "Branch": "",
    "Postcode": "",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PICH",
    "bankCode": "EC",
    "branchCode": "450",
    "SWIFT Code": "PICHECEQ450",
    "Bank Name": "BANCO PICHINCHA C.A.",
    "Address": "RIVERA Y TENEMASA 903",
    "City": "AZOGUES",
    "Branch": "AZOGUES BRANCH",
    "Postcode": "030102",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PICH",
    "bankCode": "EC",
    "branchCode": "300",
    "SWIFT Code": "PICHECEQ300",
    "Bank Name": "BANCO PICHINCHA C.A.",
    "Address": "",
    "City": "CUENCA",
    "Branch": "",
    "Postcode": "",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PICH",
    "bankCode": "EC",
    "branchCode": "304",
    "SWIFT Code": "PICHECEQ304",
    "Bank Name": "BANCO PICHINCHA C.A.",
    "Address": "",
    "City": "CUENCA",
    "Branch": "BRANCH 304",
    "Postcode": "",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PICH",
    "bankCode": "EC",
    "branchCode": "306",
    "SWIFT Code": "PICHECEQ306",
    "Bank Name": "BANCO PICHINCHA C.A.",
    "Address": "",
    "City": "CUENCA",
    "Branch": "BRANCH 306",
    "Postcode": "",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PICH",
    "bankCode": "EC",
    "branchCode": "307",
    "SWIFT Code": "PICHECEQ307",
    "Bank Name": "BANCO PICHINCHA C.A.",
    "Address": "",
    "City": "CUENCA",
    "Branch": "BRANCH 307",
    "Postcode": "",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PICH",
    "bankCode": "EC",
    "branchCode": "302",
    "SWIFT Code": "PICHECEQ302",
    "Bank Name": "BANCO PICHINCHA C.A.",
    "Address": "",
    "City": "CUENCA",
    "Branch": "INTERNATIONAL OPERATIONS",
    "Postcode": "",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PICH",
    "bankCode": "EC",
    "branchCode": "519",
    "SWIFT Code": "PICHECEQ519",
    "Bank Name": "BANCO PICHINCHA C.A.",
    "Address": "",
    "City": "QUITO",
    "Branch": "AG. C.C.INAQUITO",
    "Postcode": "",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PICH",
    "bankCode": "EC",
    "branchCode": "517",
    "SWIFT Code": "PICHECEQ517",
    "Bank Name": "BANCO PICHINCHA C.A.",
    "Address": "",
    "City": "QUITO",
    "Branch": "AG. CARONDELET",
    "Postcode": "",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PICH",
    "bankCode": "EC",
    "branchCode": "523",
    "SWIFT Code": "PICHECEQ523",
    "Bank Name": "BANCO PICHINCHA C.A.",
    "Address": "",
    "City": "QUITO",
    "Branch": "AG. CUMBAYA",
    "Postcode": "",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PICH",
    "bankCode": "EC",
    "branchCode": "516",
    "SWIFT Code": "PICHECEQ516",
    "Bank Name": "BANCO PICHINCHA C.A.",
    "Address": "",
    "City": "QUITO",
    "Branch": "AG. EL BOSQUE",
    "Postcode": "",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PICH",
    "bankCode": "EC",
    "branchCode": "109",
    "SWIFT Code": "PICHECEQ109",
    "Bank Name": "BANCO PICHINCHA C.A.",
    "Address": "",
    "City": "QUITO",
    "Branch": "AG. EL DORADO",
    "Postcode": "",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PICH",
    "bankCode": "EC",
    "branchCode": "520",
    "SWIFT Code": "PICHECEQ520",
    "Bank Name": "BANCO PICHINCHA C.A.",
    "Address": "",
    "City": "QUITO",
    "Branch": "AG. EL INCA",
    "Postcode": "",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PICH",
    "bankCode": "EC",
    "branchCode": "521",
    "SWIFT Code": "PICHECEQ521",
    "Bank Name": "BANCO PICHINCHA C.A.",
    "Address": "",
    "City": "QUITO",
    "Branch": "AG. GONZALEZ SUAREZ",
    "Postcode": "",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PICH",
    "bankCode": "EC",
    "branchCode": "515",
    "SWIFT Code": "PICHECEQ515",
    "Bank Name": "BANCO PICHINCHA C.A.",
    "Address": "",
    "City": "QUITO",
    "Branch": "AG. INAQUITO",
    "Postcode": "",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PICH",
    "bankCode": "EC",
    "branchCode": "513",
    "SWIFT Code": "PICHECEQ513",
    "Bank Name": "BANCO PICHINCHA C.A.",
    "Address": "",
    "City": "QUITO",
    "Branch": "AG. LA REPUBLICA",
    "Postcode": "",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PICH",
    "bankCode": "EC",
    "branchCode": "510",
    "SWIFT Code": "PICHECEQ510",
    "Bank Name": "BANCO PICHINCHA C.A.",
    "Address": "",
    "City": "QUITO",
    "Branch": "AG. PLAZA GRANDE",
    "Postcode": "",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PICH",
    "bankCode": "EC",
    "branchCode": "518",
    "SWIFT Code": "PICHECEQ518",
    "Bank Name": "BANCO PICHINCHA C.A.",
    "Address": "",
    "City": "QUITO",
    "Branch": "AG. QUICENTRO",
    "Postcode": "",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PICH",
    "bankCode": "EC",
    "branchCode": "522",
    "SWIFT Code": "PICHECEQ522",
    "Bank Name": "BANCO PICHINCHA C.A.",
    "Address": "",
    "City": "QUITO",
    "Branch": "AG. VILLAFLORA",
    "Postcode": "",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PICH",
    "bankCode": "EC",
    "branchCode": "524",
    "SWIFT Code": "PICHECEQ524",
    "Bank Name": "BANCO PICHINCHA C.A.",
    "Address": "",
    "City": "QUITO",
    "Branch": "AG.ELOY ALFARO",
    "Postcode": "",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PICH",
    "bankCode": "EC",
    "branchCode": "537",
    "SWIFT Code": "PICHECEQ537",
    "Bank Name": "BANCO PICHINCHA C.A.",
    "Address": "",
    "City": "QUITO",
    "Branch": "BRANCH 537",
    "Postcode": "",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PICH",
    "bankCode": "EC",
    "branchCode": "538",
    "SWIFT Code": "PICHECEQ538",
    "Bank Name": "BANCO PICHINCHA C.A.",
    "Address": "",
    "City": "QUITO",
    "Branch": "BRANCH 538",
    "Postcode": "",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PICH",
    "bankCode": "EC",
    "branchCode": "539",
    "SWIFT Code": "PICHECEQ539",
    "Bank Name": "BANCO PICHINCHA C.A.",
    "Address": "",
    "City": "QUITO",
    "Branch": "BRANCH 539",
    "Postcode": "",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PICH",
    "bankCode": "EC",
    "branchCode": "540",
    "SWIFT Code": "PICHECEQ540",
    "Bank Name": "BANCO PICHINCHA C.A.",
    "Address": "",
    "City": "QUITO",
    "Branch": "BRANCH 540",
    "Postcode": "",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PICH",
    "bankCode": "EC",
    "branchCode": "541",
    "SWIFT Code": "PICHECEQ541",
    "Bank Name": "BANCO PICHINCHA C.A.",
    "Address": "",
    "City": "QUITO",
    "Branch": "BRANCH 541",
    "Postcode": "",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PICH",
    "bankCode": "EC",
    "branchCode": "503",
    "SWIFT Code": "PICHECEQ503",
    "Bank Name": "BANCO PICHINCHA C.A.",
    "Address": "",
    "City": "QUITO",
    "Branch": "DOMESTIC OPERATIONS",
    "Postcode": "",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PICH",
    "bankCode": "EC",
    "branchCode": "502",
    "SWIFT Code": "PICHECEQ502",
    "Bank Name": "BANCO PICHINCHA C.A.",
    "Address": "",
    "City": "QUITO",
    "Branch": "HEAD INTERNATIONAL DIVISION",
    "Postcode": "",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PICH",
    "bankCode": "EC",
    "branchCode": "CEQ",
    "SWIFT Code": "PICHECEQ",
    "Bank Name": "BANCO PICHINCHA C.A.",
    "Address": "AV. AMAZONAS Y ALONSO PEREIRA, MATRIZ 4560",
    "City": "QUITO",
    "Branch": "HEAD OFFICE",
    "Postcode": "170507",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PICH",
    "bankCode": "EC",
    "branchCode": "509",
    "SWIFT Code": "PICHECEQ509",
    "Bank Name": "BANCO PICHINCHA C.A.",
    "Address": "",
    "City": "QUITO",
    "Branch": "INTERNATIONAL CORRESPONDENTS",
    "Postcode": "",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PICH",
    "bankCode": "EC",
    "branchCode": "500",
    "SWIFT Code": "PICHECEQ500",
    "Bank Name": "BANCO PICHINCHA C.A.",
    "Address": "AV. AMAZONAS Y ALONSO PEREIRA 4560, MATRIZ",
    "City": "QUITO",
    "Branch": "LOAN AND CREDITS",
    "Postcode": "",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PICH",
    "bankCode": "EC",
    "branchCode": "800",
    "SWIFT Code": "PICHECEQ800",
    "Bank Name": "BANCO PICHINCHA C.A.",
    "Address": "AV. AMAZONAS Y ALONSO PEREIRA 4560",
    "City": "QUITO",
    "Branch": "MATRIZ GIROS",
    "Postcode": "170135",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PICH",
    "bankCode": "EC",
    "branchCode": "505",
    "SWIFT Code": "PICHECEQ505",
    "Bank Name": "BANCO PICHINCHA C.A.",
    "Address": "",
    "City": "QUITO",
    "Branch": "MONEY TRANSFER DEPARTMENT",
    "Postcode": "",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PICH",
    "bankCode": "EC",
    "branchCode": "508",
    "SWIFT Code": "PICHECEQ508",
    "Bank Name": "BANCO PICHINCHA C.A.",
    "Address": "",
    "City": "QUITO",
    "Branch": "RECONCILIATION",
    "Postcode": "",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PICH",
    "bankCode": "EC",
    "branchCode": "551",
    "SWIFT Code": "PICHECEQ551",
    "Bank Name": "BANCO PICHINCHA C.A.",
    "Address": "",
    "City": "QUITO",
    "Branch": "SUC. EL VALLE",
    "Postcode": "",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PICH",
    "bankCode": "EC",
    "branchCode": "512",
    "SWIFT Code": "PICHECEQ512",
    "Bank Name": "BANCO PICHINCHA C.A.",
    "Address": "",
    "City": "QUITO",
    "Branch": "SUC.NORTE",
    "Postcode": "",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PICH",
    "bankCode": "EC",
    "branchCode": "504",
    "SWIFT Code": "PICHECEQ504",
    "Bank Name": "BANCO PICHINCHA C.A.",
    "Address": "",
    "City": "QUITO",
    "Branch": "TREASURY AND SECURITIES OPERATIONS",
    "Postcode": "",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PICH",
    "bankCode": "EC",
    "branchCode": "350",
    "SWIFT Code": "PICHECEQ350",
    "Bank Name": "BANCO PICHINCHA C.A.",
    "Address": "TITUYENTE Y GARCIA MORENO 23-17",
    "City": "RIOBAMBA",
    "Branch": "RIOBAMBA BRANCH",
    "Postcode": "060105",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PICH",
    "bankCode": "EC",
    "branchCode": "550",
    "SWIFT Code": "PICHECEQ550",
    "Bank Name": "BANCO PICHINCHA C.A.",
    "Address": "",
    "City": "SANTO DOMINGO",
    "Branch": "",
    "Postcode": "",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PICH",
    "bankCode": "EC",
    "branchCode": "900",
    "SWIFT Code": "PICHECEQ900",
    "Bank Name": "BANCO PICHINCHA C.A.",
    "Address": "10 DE AGOSTO PARQUE DE LA, INDEPENCIA",
    "City": "TULCAN",
    "Branch": "TULCAN BRANCH",
    "Postcode": "040102",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PRCB",
    "bankCode": "EC",
    "branchCode": "CEQ",
    "SWIFT Code": "PRCBECEQ",
    "Bank Name": "BANCO PROCREDIT S.A.",
    "Address": "AVE. AMAZONAS Y ATAHUALPA CORNER",
    "City": "QUITO",
    "Branch": "",
    "Postcode": "",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "BNSL",
    "bankCode": "EC",
    "branchCode": "CEQ",
    "SWIFT Code": "BNSLECEQ",
    "Bank Name": "BANCO SOLIDARIO",
    "Address": "AMAZONAS COREA SECTOR LA CAROLINA, S2 SSG N38-87",
    "City": "QUITO",
    "Branch": "",
    "Postcode": "",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "CJEP",
    "bankCode": "EC",
    "branchCode": "CEQ",
    "SWIFT Code": "CJEPECEQ",
    "Bank Name": "COOPERATIVA DE AHORRO Y CREDITO JUVENTUD ECUATORIANA PROGRESISTA LTDA.",
    "Address": "SUCRE ENTRE GENERAL TORRES Y PADRE, AGUIRRE 10-56",
    "City": "CUENCA",
    "Branch": "",
    "Postcode": "010219",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "DICD",
    "bankCode": "EC",
    "branchCode": "CEQ",
    "SWIFT Code": "DICDECEQ",
    "Bank Name": "DINERS CLUB DEL ECUADOR S.A.",
    "Address": "AVENIDA RIO AMAZONAS N38-70, FLOOR 1, ALFONSO PEREIRA",
    "City": "QUITO",
    "Branch": "",
    "Postcode": "170506",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PICH",
    "bankCode": "EC",
    "branchCode": "305",
    "SWIFT Code": "PICHECEQ305",
    "Bank Name": "BANCO PICHINCHA C.A.",
    "Address": "",
    "City": "CUENCA",
    "Branch": "MONEY TRANSFER",
    "Postcode": "",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PICH",
    "bankCode": "EC",
    "branchCode": "700",
    "SWIFT Code": "PICHECEQ700",
    "Bank Name": "BANCO PICHINCHA C.A.",
    "Address": "",
    "City": "ESMERALDAS",
    "Branch": "",
    "Postcode": "",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PICH",
    "bankCode": "EC",
    "branchCode": "370",
    "SWIFT Code": "PICHECEQ370",
    "Bank Name": "BANCO PICHINCHA C.A.",
    "Address": "7 DE MAYO Y DE AGOSTO 10",
    "City": "GUARANDA",
    "Branch": "GUARANDA BRANCH",
    "Postcode": "020101",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PICH",
    "bankCode": "EC",
    "branchCode": "100",
    "SWIFT Code": "PICHECEQ100",
    "Bank Name": "BANCO PICHINCHA C.A.",
    "Address": "",
    "City": "GUAYAQUIL",
    "Branch": "",
    "Postcode": "",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PICH",
    "bankCode": "EC",
    "branchCode": "101",
    "SWIFT Code": "PICHECEQ101",
    "Bank Name": "BANCO PICHINCHA C.A.",
    "Address": "",
    "City": "GUAYAQUIL",
    "Branch": "AG.",
    "Postcode": "",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PICH",
    "bankCode": "EC",
    "branchCode": "115",
    "SWIFT Code": "PICHECEQ115",
    "Bank Name": "BANCO PICHINCHA C.A.",
    "Address": "",
    "City": "GUAYAQUIL",
    "Branch": "AG.",
    "Postcode": "",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PICH",
    "bankCode": "EC",
    "branchCode": "116",
    "SWIFT Code": "PICHECEQ116",
    "Bank Name": "BANCO PICHINCHA C.A.",
    "Address": "",
    "City": "GUAYAQUIL",
    "Branch": "AG.",
    "Postcode": "",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PICH",
    "bankCode": "EC",
    "branchCode": "117",
    "SWIFT Code": "PICHECEQ117",
    "Bank Name": "BANCO PICHINCHA C.A.",
    "Address": "",
    "City": "GUAYAQUIL",
    "Branch": "AG.",
    "Postcode": "",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PICH",
    "bankCode": "EC",
    "branchCode": "112",
    "SWIFT Code": "PICHECEQ112",
    "Bank Name": "BANCO PICHINCHA C.A.",
    "Address": "",
    "City": "GUAYAQUIL",
    "Branch": "AG. ALBAN BORJA",
    "Postcode": "",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PICH",
    "bankCode": "EC",
    "branchCode": "111",
    "SWIFT Code": "PICHECEQ111",
    "Bank Name": "BANCO PICHINCHA C.A.",
    "Address": "",
    "City": "GUAYAQUIL",
    "Branch": "AG. ALBORADA",
    "Postcode": "",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PICH",
    "bankCode": "EC",
    "branchCode": "110",
    "SWIFT Code": "PICHECEQ110",
    "Bank Name": "BANCO PICHINCHA C.A.",
    "Address": "",
    "City": "GUAYAQUIL",
    "Branch": "AG. CENTENARIO",
    "Postcode": "",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PICH",
    "bankCode": "EC",
    "branchCode": "107",
    "SWIFT Code": "PICHECEQ107",
    "Bank Name": "BANCO PICHINCHA C.A.",
    "Address": "AV. JOSE VICENTE TRUJILLO Y AV. 25, DE JULIO",
    "City": "GUAYAQUIL",
    "Branch": "AG. CENTENARIO SUR",
    "Postcode": "090102",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PICH",
    "bankCode": "EC",
    "branchCode": "108",
    "SWIFT Code": "PICHECEQ108",
    "Bank Name": "BANCO PICHINCHA C.A.",
    "Address": "PICHINCA Y 9 DE OCTUBRE 309",
    "City": "GUAYAQUIL",
    "Branch": "AG. CENTRO",
    "Postcode": "090313",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PICH",
    "bankCode": "EC",
    "branchCode": "106",
    "SWIFT Code": "PICHECEQ106",
    "Bank Name": "BANCO PICHINCHA C.A.",
    "Address": "CALLE Y CUARTA ESQUINA 23",
    "City": "GUAYAQUIL",
    "Branch": "AG. LA LIBERTAD",
    "Postcode": "090603",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PICH",
    "bankCode": "EC",
    "branchCode": "113",
    "SWIFT Code": "PICHECEQ113",
    "Bank Name": "BANCO PICHINCHA C.A.",
    "Address": "",
    "City": "GUAYAQUIL",
    "Branch": "AG. MALL DEL SOL",
    "Postcode": "",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PICH",
    "bankCode": "EC",
    "branchCode": "114",
    "SWIFT Code": "PICHECEQ114",
    "Bank Name": "BANCO PICHINCHA C.A.",
    "Address": "",
    "City": "GUAYAQUIL",
    "Branch": "AG. URDESA",
    "Postcode": "",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PICH",
    "bankCode": "EC",
    "branchCode": "118",
    "SWIFT Code": "PICHECEQ118",
    "Bank Name": "BANCO PICHINCHA C.A.",
    "Address": "",
    "City": "GUAYAQUIL",
    "Branch": "AG.POLICENTRO",
    "Postcode": "",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PICH",
    "bankCode": "EC",
    "branchCode": "119",
    "SWIFT Code": "PICHECEQ119",
    "Bank Name": "BANCO PICHINCHA C.A.",
    "Address": "",
    "City": "GUAYAQUIL",
    "Branch": "BRANCH 119",
    "Postcode": "",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PICH",
    "bankCode": "EC",
    "branchCode": "120",
    "SWIFT Code": "PICHECEQ120",
    "Bank Name": "BANCO PICHINCHA C.A.",
    "Address": "",
    "City": "GUAYAQUIL",
    "Branch": "BRANCH 120",
    "Postcode": "",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PICH",
    "bankCode": "EC",
    "branchCode": "121",
    "SWIFT Code": "PICHECEQ121",
    "Bank Name": "BANCO PICHINCHA C.A.",
    "Address": "",
    "City": "GUAYAQUIL",
    "Branch": "BRANCH 121",
    "Postcode": "",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PICH",
    "bankCode": "EC",
    "branchCode": "103",
    "SWIFT Code": "PICHECEQ103",
    "Bank Name": "BANCO PICHINCHA C.A.",
    "Address": "",
    "City": "GUAYAQUIL",
    "Branch": "DOMESTIC OPERATIONS",
    "Postcode": "",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PICH",
    "bankCode": "EC",
    "branchCode": "102",
    "SWIFT Code": "PICHECEQ102",
    "Bank Name": "BANCO PICHINCHA C.A.",
    "Address": "",
    "City": "GUAYAQUIL",
    "Branch": "INTERNATIONAL OPERATIONS",
    "Postcode": "",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PICH",
    "bankCode": "EC",
    "branchCode": "105",
    "SWIFT Code": "PICHECEQ105",
    "Bank Name": "BANCO PICHINCHA C.A.",
    "Address": "",
    "City": "GUAYAQUIL",
    "Branch": "MONEY TRANSFER",
    "Postcode": "",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PICH",
    "bankCode": "EC",
    "branchCode": "104",
    "SWIFT Code": "PICHECEQ104",
    "Bank Name": "BANCO PICHINCHA C.A.",
    "Address": "",
    "City": "GUAYAQUIL",
    "Branch": "TREASURY AND SECURITIES OPERATIONS",
    "Postcode": "",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PICH",
    "bankCode": "EC",
    "branchCode": "250",
    "SWIFT Code": "PICHECEQ250",
    "Bank Name": "BANCO PICHINCHA C.A.",
    "Address": "AVENIDA BOLIVAR Y OBISPO MOSQUERA",
    "City": "IBARRA",
    "Branch": "IBARRA BRANCH",
    "Postcode": "100106",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PICH",
    "bankCode": "EC",
    "branchCode": "270",
    "SWIFT Code": "PICHECEQ270",
    "Bank Name": "BANCO PICHINCHA C.A.",
    "Address": "CALLE QUITO 7183",
    "City": "LATACUNGA",
    "Branch": "LATACUNGA BRANCH",
    "Postcode": "050101",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PICH",
    "bankCode": "EC",
    "branchCode": "200",
    "SWIFT Code": "PICHECEQ200",
    "Bank Name": "BANCO PICHINCHA C.A.",
    "Address": "",
    "City": "MACHALA",
    "Branch": "",
    "Postcode": "",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PICH",
    "bankCode": "EC",
    "branchCode": "600",
    "SWIFT Code": "PICHECEQ600",
    "Bank Name": "BANCO PICHINCHA C.A.",
    "Address": "",
    "City": "MANTA",
    "Branch": "",
    "Postcode": "",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PICH",
    "bankCode": "EC",
    "branchCode": "605",
    "SWIFT Code": "PICHECEQ605",
    "Bank Name": "BANCO PICHINCHA C.A.",
    "Address": "",
    "City": "MANTA",
    "Branch": "MONEY TRANSFER DEPT.",
    "Postcode": "",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PICH",
    "bankCode": "EC",
    "branchCode": "253",
    "SWIFT Code": "PICHECEQ253",
    "Bank Name": "BANCO PICHINCHA C.A.",
    "Address": "BOLIVAR Y GARCIA MORENO 616",
    "City": "OTAVALO",
    "Branch": "OTAVALO BRANCH",
    "Postcode": "100201",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PICH",
    "bankCode": "EC",
    "branchCode": "610",
    "SWIFT Code": "PICHECEQ610",
    "Bank Name": "BANCO PICHINCHA C.A.",
    "Address": "",
    "City": "PORTOVIEJO",
    "Branch": "",
    "Postcode": "",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PICH",
    "bankCode": "EC",
    "branchCode": "804",
    "SWIFT Code": "PICHECEQ804",
    "Bank Name": "BANCO PICHINCHA C.A.",
    "Address": "BOLIVAR ENTRE CALLE 5TA E 6TA 503",
    "City": "QUEVEDO",
    "Branch": "QUEVEDO BRANCH",
    "Postcode": "120504",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PICH",
    "bankCode": "EC",
    "branchCode": "501",
    "SWIFT Code": "PICHECEQ501",
    "Bank Name": "BANCO PICHINCHA C.A.",
    "Address": "",
    "City": "QUITO",
    "Branch": "",
    "Postcode": "",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PICH",
    "bankCode": "EC",
    "branchCode": "506",
    "SWIFT Code": "PICHECEQ506",
    "Bank Name": "BANCO PICHINCHA C.A.",
    "Address": "",
    "City": "QUITO",
    "Branch": "",
    "Postcode": "",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PICH",
    "bankCode": "EC",
    "branchCode": "507",
    "SWIFT Code": "PICHECEQ507",
    "Bank Name": "BANCO PICHINCHA C.A.",
    "Address": "",
    "City": "QUITO",
    "Branch": "",
    "Postcode": "",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PICH",
    "bankCode": "EC",
    "branchCode": "525",
    "SWIFT Code": "PICHECEQ525",
    "Bank Name": "BANCO PICHINCHA C.A.",
    "Address": "",
    "City": "QUITO",
    "Branch": "AG.",
    "Postcode": "",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PICH",
    "bankCode": "EC",
    "branchCode": "526",
    "SWIFT Code": "PICHECEQ526",
    "Bank Name": "BANCO PICHINCHA C.A.",
    "Address": "",
    "City": "QUITO",
    "Branch": "AG.",
    "Postcode": "",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PICH",
    "bankCode": "EC",
    "branchCode": "527",
    "SWIFT Code": "PICHECEQ527",
    "Bank Name": "BANCO PICHINCHA C.A.",
    "Address": "",
    "City": "QUITO",
    "Branch": "AG.",
    "Postcode": "",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PICH",
    "bankCode": "EC",
    "branchCode": "528",
    "SWIFT Code": "PICHECEQ528",
    "Bank Name": "BANCO PICHINCHA C.A.",
    "Address": "",
    "City": "QUITO",
    "Branch": "AG.",
    "Postcode": "",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PICH",
    "bankCode": "EC",
    "branchCode": "529",
    "SWIFT Code": "PICHECEQ529",
    "Bank Name": "BANCO PICHINCHA C.A.",
    "Address": "",
    "City": "QUITO",
    "Branch": "AG.",
    "Postcode": "",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PICH",
    "bankCode": "EC",
    "branchCode": "530",
    "SWIFT Code": "PICHECEQ530",
    "Bank Name": "BANCO PICHINCHA C.A.",
    "Address": "",
    "City": "QUITO",
    "Branch": "AG.",
    "Postcode": "",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PICH",
    "bankCode": "EC",
    "branchCode": "531",
    "SWIFT Code": "PICHECEQ531",
    "Bank Name": "BANCO PICHINCHA C.A.",
    "Address": "",
    "City": "QUITO",
    "Branch": "AG.",
    "Postcode": "",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PICH",
    "bankCode": "EC",
    "branchCode": "532",
    "SWIFT Code": "PICHECEQ532",
    "Bank Name": "BANCO PICHINCHA C.A.",
    "Address": "",
    "City": "QUITO",
    "Branch": "AG.",
    "Postcode": "",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PICH",
    "bankCode": "EC",
    "branchCode": "533",
    "SWIFT Code": "PICHECEQ533",
    "Bank Name": "BANCO PICHINCHA C.A.",
    "Address": "",
    "City": "QUITO",
    "Branch": "AG.",
    "Postcode": "",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PICH",
    "bankCode": "EC",
    "branchCode": "534",
    "SWIFT Code": "PICHECEQ534",
    "Bank Name": "BANCO PICHINCHA C.A.",
    "Address": "",
    "City": "QUITO",
    "Branch": "AG.",
    "Postcode": "",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PICH",
    "bankCode": "EC",
    "branchCode": "535",
    "SWIFT Code": "PICHECEQ535",
    "Bank Name": "BANCO PICHINCHA C.A.",
    "Address": "",
    "City": "QUITO",
    "Branch": "AG.",
    "Postcode": "",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PICH",
    "bankCode": "EC",
    "branchCode": "536",
    "SWIFT Code": "PICHECEQ536",
    "Bank Name": "BANCO PICHINCHA C.A.",
    "Address": "",
    "City": "QUITO",
    "Branch": "AG.",
    "Postcode": "",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PICH",
    "bankCode": "EC",
    "branchCode": "552",
    "SWIFT Code": "PICHECEQ552",
    "Bank Name": "BANCO PICHINCHA C.A.",
    "Address": "",
    "City": "QUITO",
    "Branch": "AG.",
    "Postcode": "",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PICH",
    "bankCode": "EC",
    "branchCode": "511",
    "SWIFT Code": "PICHECEQ511",
    "Bank Name": "BANCO PICHINCHA C.A.",
    "Address": "",
    "City": "QUITO",
    "Branch": "AG. AMAZONAS",
    "Postcode": "",
    "Country": "Ecuador",
    "Connection": "Active"
  },
  {
    "countryCode": "PICH",
    "bankCode": "EC",
    "branchCode": "514",
    "SWIFT Code": "PICHECEQ514",
    "Bank Name": "BANCO PICHINCHA C.A.",
    "Address": "",
    "City": "QUITO",
    "Branch": "AG. AV. PORTUGAL",
    "Postcode": "",
    "Country": "Ecuador",
    "Connection": "Active"
  }
]
module.exports = ecuador
