const equatorialGuinea = [
  {
    "bankCode": "NAGC",
    "countryCode": "GQ",
    "branchCode": "QGQ",
    "SWIFT Code": "NAGCGQGQ",
    "Bank Name": "BANCO NACIONAL DE GUINEA ECUATORIAL (BANGE)",
    "Address": "AVENIDA DE LAS NACIONES UNIDAS 28",
    "City": "MALABO",
    "Branch": "",
    "Postcode": "",
    "Country": "Equatorial Guinea",
    "Connection": "Active"
  },
  {
    "bankCode": "BEAC",
    "countryCode": "GQ",
    "branchCode": "610",
    "SWIFT Code": "BEACGQGQ610",
    "Bank Name": "BANQUE DES ETATS DE L'AFRIQUE CENTRALE D.N. GUINEE EQUATORIALE",
    "Address": "",
    "City": "BATA",
    "Branch": "AGENCE DE BATA",
    "Postcode": "",
    "Country": "Equatorial Guinea",
    "Connection": "Active"
  },
  {
    "bankCode": "BEAC",
    "countryCode": "GQ",
    "branchCode": "QGQ",
    "SWIFT Code": "BEACGQGQ",
    "Bank Name": "BANQUE DES ETATS DE L'AFRIQUE CENTRALE D.N. GUINEE EQUATORIALE",
    "Address": "",
    "City": "MALABO",
    "Branch": "",
    "Postcode": "",
    "Country": "Equatorial Guinea",
    "Connection": "Active"
  },
  {
    "bankCode": "BGFI",
    "countryCode": "GQ",
    "branchCode": "QGQ",
    "SWIFT Code": "BGFIGQGQ",
    "Bank Name": "BGFIBANK GUINEE EQUATORIALE",
    "Address": "CTRA DE LUBA",
    "City": "MALABO",
    "Branch": "",
    "Postcode": "",
    "Country": "Equatorial Guinea",
    "Connection": "Active"
  },
  {},
  {
    "bankCode": "CCEI",
    "countryCode": "GQ",
    "branchCode": "EBI",
    "SWIFT Code": "CCEIGQGQEBI",
    "Bank Name": "CCEI BANK GE",
    "Address": "EDIFICIO CCEI BANK GUINEA, AVENIDA GENERAL OBIANG",
    "City": "BATA",
    "Branch": "EBIEBYIN",
    "Postcode": "",
    "Country": "Equatorial Guinea",
    "Connection": "Active"
  },
  {
    "bankCode": "CCEI",
    "countryCode": "GQ",
    "branchCode": "MON",
    "SWIFT Code": "CCEIGQGQMON",
    "Bank Name": "CCEI BANK GE",
    "Address": "EDIFICIO CCEI BANK GUINEA, CALLE MONGOMO 2",
    "City": "BATA",
    "Branch": "MONGOMO",
    "Postcode": "",
    "Country": "Equatorial Guinea",
    "Connection": "Active"
  },
  {
    "bankCode": "CCEI",
    "countryCode": "GQ",
    "branchCode": "QGQ",
    "SWIFT Code": "CCEIGQGQ",
    "Bank Name": "CCEI BANK GE",
    "Address": "ZONA MINISTERIAL, APDO 428",
    "City": "MALABO",
    "Branch": "",
    "Postcode": "",
    "Country": "Equatorial Guinea",
    "Connection": "Active"
  },
  {
    "bankCode": "ECOC",
    "countryCode": "GQ",
    "branchCode": "QGQ",
    "SWIFT Code": "ECOCGQGQ",
    "Bank Name": "ECOBANK GUINEE EQUATORIALE",
    "Address": "AVENIDA DE LA INDEPENDENCIA 01",
    "City": "MALABO",
    "Branch": "",
    "Postcode": "",
    "Country": "Equatorial Guinea",
    "Connection": "Active"
  },
  {
    "bankCode": "SGGE",
    "countryCode": "GQ",
    "branchCode": "QGQ",
    "SWIFT Code": "SGGEGQGQ",
    "Bank Name": "SOCIETE GENERALE DE BANQUES EN GUINEE EQUATORIALE",
    "Address": "AVENIDA DE LA INDEPENDENCIA",
    "City": "MALABO",
    "Branch": "",
    "Postcode": "",
    "Country": "Equatorial Guinea",
    "Connection": "Active"
  }
]
module.exports = equatorialGuinea
