const estonia = [
  {
    "countryCode": "PARX",
    "bankCode": "EE",
    "branchCode": "E22",
    "SWIFT Code": "PARXEE22",
    "Bank Name": "AS CITADELE BANKA EESTI FILIAAL",
    "Address": "NARVA MNT 63/1",
    "City": "TALLINN",
    "Branch": "",
    "Postcode": "10152",
    "Country": "Estonia",
    "Connection": "Active"
  },
  {
    "countryCode": "LHVB",
    "bankCode": "EE",
    "branchCode": "E22",
    "SWIFT Code": "LHVBEE22",
    "Bank Name": "AS LHV PANK",
    "Address": "TARTU MNT 2",
    "City": "TALLINN",
    "Branch": "",
    "Postcode": "10145",
    "Country": "Estonia",
    "Connection": "Active"
  },
  {
    "countryCode": "LHVB",
    "bankCode": "EE",
    "branchCode": "INS",
    "SWIFT Code": "LHVBEE22INS",
    "Bank Name": "AS LHV PANK",
    "Address": "TARTU MNT 2",
    "City": "TALLINN",
    "Branch": "INSTANT",
    "Postcode": "10145",
    "Country": "Estonia",
    "Connection": "Active"
  },
  {
    "countryCode": "EEUH",
    "bankCode": "EE",
    "branchCode": "TPS",
    "SWIFT Code": "EEUHEE2XTPS",
    "Bank Name": "AS SEB PANK",
    "Address": "FLOOR 10, TORNIMAE 2",
    "City": "TALLINN",
    "Branch": "",
    "Postcode": "15010",
    "Country": "Estonia",
    "Connection": "Active"
  },
  {
    "countryCode": "EEUH",
    "bankCode": "EE",
    "branchCode": "E2X",
    "SWIFT Code": "EEUHEE2X",
    "Bank Name": "AS SEB PANK",
    "Address": "FLOOR 10, TORNIMAE 2",
    "City": "TALLINN",
    "Branch": "",
    "Postcode": "15010",
    "Country": "Estonia",
    "Connection": "Active"
  },
  {
    "countryCode": "TABU",
    "bankCode": "EE",
    "branchCode": "E22",
    "SWIFT Code": "TABUEE22",
    "Bank Name": "AS TBB PANK",
    "Address": "VANA-VIRU 7",
    "City": "TALLINN",
    "Branch": "",
    "Postcode": "15097",
    "Country": "Estonia",
    "Connection": "Active"
  },
  {
    "countryCode": "TABU",
    "bankCode": "EE",
    "branchCode": "TPS",
    "SWIFT Code": "TABUEE22TPS",
    "Bank Name": "AS TBB PANK",
    "Address": "VANA-VIRU 7",
    "City": "TALLINN",
    "Branch": "TIPS",
    "Postcode": "15097",
    "Country": "Estonia",
    "Connection": "Active"
  },
  {
    "countryCode": "BIGK",
    "bankCode": "EE",
    "branchCode": "E2B",
    "SWIFT Code": "BIGKEE2B",
    "Bank Name": "BIGBANK AS",
    "Address": "NARVA MNT 11",
    "City": "TALLINN",
    "Branch": "",
    "Postcode": "15015",
    "Country": "Estonia",
    "Connection": "Active"
  },
  {
    "countryCode": "EKRD",
    "bankCode": "EE",
    "branchCode": "E22",
    "SWIFT Code": "EKRDEE22",
    "Bank Name": "COOP PANK",
    "Address": "MAAKRI 30",
    "City": "TALLINN",
    "Branch": "",
    "Postcode": "15014",
    "Country": "Estonia",
    "Connection": "Active"
  },
  {
    "countryCode": "EKRD",
    "bankCode": "EE",
    "branchCode": "TPS",
    "SWIFT Code": "EKRDEE22TPS",
    "Bank Name": "COOP PANK",
    "Address": "MAAKRI 30",
    "City": "TALLINN",
    "Branch": "",
    "Postcode": "15014",
    "Country": "Estonia",
    "Connection": "Active"
  },
  {
    "countryCode": "EPBE",
    "bankCode": "EE",
    "branchCode": "CCB",
    "SWIFT Code": "EPBEEE2XCCB",
    "Bank Name": "EESTI PANK (BANK OF ESTONIA)",
    "Address": "ESTONIA PST 13",
    "City": "TALLINN",
    "Branch": "",
    "Postcode": "15095",
    "Country": "Estonia",
    "Connection": "Active"
  },
  {
    "countryCode": "EPBE",
    "bankCode": "EE",
    "branchCode": "ECM",
    "SWIFT Code": "EPBEEE2XECM",
    "Bank Name": "EESTI PANK (BANK OF ESTONIA)",
    "Address": "ESTONIA PST 13",
    "City": "TALLINN",
    "Branch": "",
    "Postcode": "15095",
    "Country": "Estonia",
    "Connection": "Active"
  },
  {
    "countryCode": "EPBE",
    "bankCode": "EE",
    "branchCode": "E2X",
    "SWIFT Code": "EPBEEE2X",
    "Bank Name": "EESTI PANK (BANK OF ESTONIA)",
    "Address": "ESTONIA PST 13",
    "City": "TALLINN",
    "Branch": "",
    "Postcode": "15095",
    "Country": "Estonia",
    "Connection": "Active"
  },
  {
    "countryCode": "GUIV",
    "bankCode": "EE",
    "branchCode": "E22",
    "SWIFT Code": "GUIVEE22",
    "Bank Name": "G.U.S. INVESTMENTS OU",
    "Address": "ROOSIKRANTSI TN 2-671K",
    "City": "TALLINN",
    "Branch": "",
    "Postcode": "10119",
    "Country": "Estonia",
    "Connection": "Active"
  },
  {
    "countryCode": "HOMM",
    "bankCode": "EE",
    "branchCode": "E22",
    "SWIFT Code": "HOMMEE22",
    "Bank Name": "HOLM BANK AS",
    "Address": "POSTI 30",
    "City": "HAAPSALU",
    "Branch": "",
    "Postcode": "90504",
    "Country": "Estonia",
    "Connection": "Active"
  },
  {
    "countryCode": "IHPY",
    "bankCode": "EE",
    "branchCode": "E22",
    "SWIFT Code": "IHPYEE22",
    "Bank Name": "INHOUSE PAY AS",
    "Address": "VALUKOJA 8/1",
    "City": "TALLINN",
    "Branch": "",
    "Postcode": "11415",
    "Country": "Estonia",
    "Connection": "Active"
  },
  {
    "countryCode": "IPFD",
    "bankCode": "EE",
    "branchCode": "E22",
    "SWIFT Code": "IPFDEE22",
    "Bank Name": "IPF DIGITAL AS",
    "Address": "LOOTSA 5, ULEMISTE CITY",
    "City": "TALLINN",
    "Branch": "",
    "Postcode": "11415",
    "Country": "Estonia",
    "Connection": "Active"
  },
  {
    "countryCode": "LIEO",
    "bankCode": "EE",
    "branchCode": "E22",
    "SWIFT Code": "LIEOEE22",
    "Bank Name": "LIGHTYEAR EUROPE",
    "Address": "VOLTA TN 1",
    "City": "TALLINN",
    "Branch": "",
    "Postcode": "10412",
    "Country": "Estonia",
    "Connection": "Active"
  },
  {
    "countryCode": "RIKO",
    "bankCode": "EE",
    "branchCode": "CBC",
    "SWIFT Code": "RIKOEE22CBC",
    "Bank Name": "LUMINOR BANK AS, ESTONIA (FORMER AS DNB PANK)",
    "Address": "LIIVALAIA 45",
    "City": "TALLINN",
    "Branch": "",
    "Postcode": "10145",
    "Country": "Estonia",
    "Connection": "Active"
  },
  {
    "countryCode": "RIKO",
    "bankCode": "EE",
    "branchCode": "E22",
    "SWIFT Code": "RIKOEE22",
    "Bank Name": "LUMINOR BANK AS, ESTONIA (FORMER AS DNB PANK)",
    "Address": "LIIVALAIA 45",
    "City": "TALLINN",
    "Branch": "",
    "Postcode": "10145",
    "Country": "Estonia",
    "Connection": "Active"
  },
  {},
  {
    "countryCode": "MOMN",
    "bankCode": "EE",
    "branchCode": "E22",
    "SWIFT Code": "MOMNEE22",
    "Bank Name": "MONEMON AS",
    "Address": "MARIENTHALI KESKUS, FLOOR 8, MUSTAMAE TEE 16",
    "City": "TALLINN",
    "Branch": "",
    "Postcode": "10617",
    "Country": "Estonia",
    "Connection": "Active"
  },
  {
    "countryCode": "OKOY",
    "bankCode": "EE",
    "branchCode": "E2X",
    "SWIFT Code": "OKOYEE2X",
    "Bank Name": "OP CORPORATE BANK PLC ESTONIAN BRANCH",
    "Address": "MAAKRI TN 19/1",
    "City": "TALLINN",
    "Branch": "",
    "Postcode": "10145",
    "Country": "Estonia",
    "Connection": "Active"
  },
  {
    "countryCode": "NEUX",
    "bankCode": "EE",
    "branchCode": "E22",
    "SWIFT Code": "NEUXEE22",
    "Bank Name": "OU NEURONEXT",
    "Address": "KALDA TN 9A/1, NOMME LINNAOSA",
    "City": "TALLINN",
    "Branch": "",
    "Postcode": "11625",
    "Country": "Estonia",
    "Connection": "Active"
  },
  {
    "countryCode": "POHO",
    "bankCode": "EE",
    "branchCode": "E22",
    "SWIFT Code": "POHOEE22",
    "Bank Name": "PHJA-EESTI HOIU-LAENUHISTU",
    "Address": "PRONKSI 3",
    "City": "TALLINN",
    "Branch": "",
    "Postcode": "10124",
    "Country": "Estonia",
    "Connection": "Active"
  },
  {
    "countryCode": "HABA",
    "bankCode": "EE",
    "branchCode": "TIP",
    "SWIFT Code": "HABAEE2XTIP",
    "Bank Name": "SWEDBANK AS",
    "Address": "LIIVALAIA 8",
    "City": "TALLINN",
    "Branch": "",
    "Postcode": "15040",
    "Country": "Estonia",
    "Connection": "Active"
  },
  {
    "countryCode": "HABA",
    "bankCode": "EE",
    "branchCode": "E2X",
    "SWIFT Code": "HABAEE2X",
    "Bank Name": "SWEDBANK AS",
    "Address": "LIIVALAIA 8",
    "City": "TALLINN",
    "Branch": "",
    "Postcode": "15040",
    "Country": "Estonia",
    "Connection": "Active"
  },
  {
    "countryCode": "HABA",
    "bankCode": "EE",
    "branchCode": "HAM",
    "SWIFT Code": "HABAEE2XHAM",
    "Bank Name": "SWEDBANK AS",
    "Address": "",
    "City": "TALLINN",
    "Branch": "HANSA ASSET MANAGMENT",
    "Postcode": "",
    "Country": "Estonia",
    "Connection": "Active"
  },
  {
    "countryCode": "PANX",
    "bankCode": "EE",
    "branchCode": "E22",
    "SWIFT Code": "PANXEE22",
    "Bank Name": "UNIFIEDPOST PAYMENTS EESTI FILIAAL",
    "Address": "VEERENNI TN 40A, KESKLINNA LINNAOSA",
    "City": "TALLINN",
    "Branch": "",
    "Postcode": "10138",
    "Country": "Estonia",
    "Connection": "Active"
  },
  {
    "countryCode": "VINE",
    "bankCode": "EE",
    "branchCode": "E22",
    "SWIFT Code": "VINEEE22",
    "Bank Name": "VOLKSWAGEN INTERNATIONAL ESTONIA AS",
    "Address": "LOOTSA 1A",
    "City": "TALLINN",
    "Branch": "",
    "Postcode": "11415",
    "Country": "Estonia",
    "Connection": "Active"
  },
  {
    "countryCode": "WALL",
    "bankCode": "EE",
    "branchCode": "E22",
    "SWIFT Code": "WALLEE22",
    "Bank Name": "WALLESTER AS",
    "Address": "F. R. KREUTZWALDI TN 4",
    "City": "TALLINN",
    "Branch": "",
    "Postcode": "10120",
    "Country": "Estonia",
    "Connection": "Active"
  }
]
module.exports = estonia
