const ethiopia = [
  {
    "bankCode": "ABAY",
    "countryCode": "ET",
    "branchCode": "TAA",
    "SWIFT Code": "ABAYETAA",
    "Bank Name": "ABAY BANK S.C.",
    "Address": "ZIQUAL COMPLEX, JOMO KENYATTA STREET NEW",
    "City": "ADDIS ABABA",
    "Branch": "",
    "Postcode": "5887",
    "Country": "Ethiopia",
    "Connection": "Active"
  },
  {
    "bankCode": "ABSC",
    "countryCode": "ET",
    "branchCode": "TAA",
    "SWIFT Code": "ABSCETAA",
    "Bank Name": "ADDIS INTERNATIONAL BANK S.C.",
    "Address": "ZEQUALA COMPLEX BUILDING, FLOOR 0, 3 J.KENYATA STREET",
    "City": "ADDIS ABABA",
    "Branch": "",
    "Postcode": "2455",
    "Country": "Ethiopia",
    "Connection": "Active"
  },
  {
    "bankCode": "AFUN",
    "countryCode": "ET",
    "branchCode": "TAA",
    "SWIFT Code": "AFUNETAA",
    "Bank Name": "AFRICAN UNION",
    "Address": "ROOSEVELT SREET 1",
    "City": "ADDIS ABABA",
    "Branch": "",
    "Postcode": "3244",
    "Country": "Ethiopia",
    "Connection": "Active"
  },
  {
    "bankCode": "AHUU",
    "countryCode": "ET",
    "branchCode": "TAA",
    "SWIFT Code": "AHUUETAA",
    "Bank Name": "AHADU BANK S.C.",
    "Address": "SUNSHINE BUILDING, FLOOR 8 AFRICA, AVENUE (BOLE ROAD) AROUND FLAMINGO",
    "City": "ADDIS ABABA",
    "Branch": "",
    "Postcode": "1000",
    "Country": "Ethiopia",
    "Connection": "Active"
  },
  {
    "bankCode": "AMHR",
    "countryCode": "ET",
    "branchCode": "TAA",
    "SWIFT Code": "AMHRETAA",
    "Bank Name": "AMHARA BANK S.C.",
    "Address": "RAS MEKONNEN STREET",
    "City": "ADDIS ABABA",
    "Branch": "",
    "Postcode": "1138",
    "Country": "Ethiopia",
    "Connection": "Active"
  },
  {
    "bankCode": "AWIN",
    "countryCode": "ET",
    "branchCode": "TAA",
    "SWIFT Code": "AWINETAA",
    "Bank Name": "AWASH BANK S.C",
    "Address": "AWASH TOWER, ABEBE AREGAY STREET, KIRKOS SUBCITY, WOREDA 07",
    "City": "ADDIS ABEBA",
    "Branch": "",
    "Postcode": "1000",
    "Country": "Ethiopia",
    "Connection": "Active"
  },
  {
    "bankCode": "ABYS",
    "countryCode": "ET",
    "branchCode": "TAA",
    "SWIFT Code": "ABYSETAA",
    "Bank Name": "BANK OF ABYSSINIA",
    "Address": "LEGEHAR OWN HQ BUILDING, KIRKOS SUB-CITY",
    "City": "ADDIS ABABA",
    "Branch": "",
    "Postcode": "1000",
    "Country": "Ethiopia",
    "Connection": "Active"
  },
  {
    "bankCode": "BERH",
    "countryCode": "ET",
    "branchCode": "TAA",
    "SWIFT Code": "BERHETAA",
    "Bank Name": "BERHAN BANK SC",
    "Address": "TK BUILDING, FLOOR 5TH, BOLE CHINA AFRICA SQUARE",
    "City": "ADDIS ABABA",
    "Branch": "",
    "Postcode": "1110",
    "Country": "Ethiopia",
    "Connection": "Active"
  },
  {
    "bankCode": "BUNA",
    "countryCode": "ET",
    "branchCode": "TAA",
    "SWIFT Code": "BUNAETAA",
    "Bank Name": "BUNNA INTERNATIONAL BANK S.C",
    "Address": "BOLE ROAD",
    "City": "ADDIS ABABA",
    "Branch": "BUNNA BANK HEAD OFFICE",
    "Postcode": "1743",
    "Country": "Ethiopia",
    "Connection": "Active"
  },
  {
    "bankCode": "CBET",
    "countryCode": "ET",
    "branchCode": "TAA",
    "SWIFT Code": "CBETETAA",
    "Bank Name": "COMMERCIAL BANK OF ETHIOPIA",
    "Address": "WHITE BUILDING, CHURCHILL ROAD",
    "City": "ADDIS ABABA",
    "Branch": "",
    "Postcode": "1047",
    "Country": "Ethiopia",
    "Connection": "Active"
  },
  {
    "bankCode": "CBET",
    "countryCode": "ET",
    "branchCode": "ARA",
    "SWIFT Code": "CBETETAAARA",
    "Bank Name": "COMMERCIAL BANK OF ETHIOPIA",
    "Address": "",
    "City": "ADDIS ABABA",
    "Branch": "ARADA GIORGIS BRANCH",
    "Postcode": "1000",
    "Country": "Ethiopia",
    "Connection": "Active"
  },
  {
    "bankCode": "CBET",
    "countryCode": "ET",
    "branchCode": "DIR",
    "SWIFT Code": "CBETETAADIR",
    "Bank Name": "COMMERCIAL BANK OF ETHIOPIA",
    "Address": "",
    "City": "ADDIS ABABA",
    "Branch": "DIRE DAWA MAIN BRANCH",
    "Postcode": "1000",
    "Country": "Ethiopia",
    "Connection": "Active"
  },
  {
    "bankCode": "CBET",
    "countryCode": "ET",
    "branchCode": "FIN",
    "SWIFT Code": "CBETETAAFIN",
    "Bank Name": "COMMERCIAL BANK OF ETHIOPIA",
    "Address": "",
    "City": "ADDIS ABABA",
    "Branch": "FINFINE BRANCH",
    "Postcode": "1000",
    "Country": "Ethiopia",
    "Connection": "Active"
  },
  {
    "bankCode": "CBET",
    "countryCode": "ET",
    "branchCode": "IBD",
    "SWIFT Code": "CBETETAAIBD",
    "Bank Name": "COMMERCIAL BANK OF ETHIOPIA",
    "Address": "",
    "City": "ADDIS ABABA",
    "Branch": "INTERNATIONAL BANKING DEPARTMENT",
    "Postcode": "1000",
    "Country": "Ethiopia",
    "Connection": "Active"
  },
  {
    "bankCode": "CBET",
    "countryCode": "ET",
    "branchCode": "MEH",
    "SWIFT Code": "CBETETAAMEH",
    "Bank Name": "COMMERCIAL BANK OF ETHIOPIA",
    "Address": "",
    "City": "ADDIS ABABA",
    "Branch": "MEHAL GEBEYA BRANCH",
    "Postcode": "1000",
    "Country": "Ethiopia",
    "Connection": "Active"
  },
  {
    "bankCode": "CBET",
    "countryCode": "ET",
    "branchCode": "TEM",
    "SWIFT Code": "CBETETAATEM",
    "Bank Name": "COMMERCIAL BANK OF ETHIOPIA",
    "Address": "",
    "City": "ADDIS ABABA",
    "Branch": "TEMENJA YAJ BRANCH",
    "Postcode": "1000",
    "Country": "Ethiopia",
    "Connection": "Active"
  },
  {
    "bankCode": "CBET",
    "countryCode": "ET",
    "branchCode": "DOC",
    "SWIFT Code": "CBETETAADOC",
    "Bank Name": "COMMERCIAL BANK OF ETHIOPIA",
    "Address": "",
    "City": "ADDIS ABABA",
    "Branch": "TRADE SERVICE CENTER",
    "Postcode": "1000",
    "Country": "Ethiopia",
    "Connection": "Active"
  },
  {
    "bankCode": "CBET",
    "countryCode": "ET",
    "branchCode": "TRY",
    "SWIFT Code": "CBETETAATRY",
    "Bank Name": "COMMERCIAL BANK OF ETHIOPIA",
    "Address": "",
    "City": "ADDIS ABABA",
    "Branch": "TREASURY DEPARTMENT",
    "Postcode": "1000",
    "Country": "Ethiopia",
    "Connection": "Active"
  },
  {
    "bankCode": "CBOR",
    "countryCode": "ET",
    "branchCode": "TAA",
    "SWIFT Code": "CBORETAA",
    "Bank Name": "COOPERATIVE BANK OF OROMIA S.C.",
    "Address": "GET HOUSE BUILDING, AFRICA AVENUE, FLAMINGO AREA",
    "City": "ADDIS ABABA",
    "Branch": "",
    "Postcode": "1110",
    "Country": "Ethiopia",
    "Connection": "Active"
  },
  {
    "bankCode": "DASH",
    "countryCode": "ET",
    "branchCode": "TAA",
    "SWIFT Code": "DASHETAA",
    "Bank Name": "DASHEN BANK S.C.",
    "Address": "IN FRONT OF NAT. BANK OF ETHIOPIA,, FLOOR 4TH SUDAN STREET",
    "City": "ADDIS ABABA",
    "Branch": "",
    "Postcode": "1000",
    "Country": "Ethiopia",
    "Connection": "Active"
  },
  {
    "bankCode": "DEET",
    "countryCode": "ET",
    "branchCode": "TAA",
    "SWIFT Code": "DEETETAA",
    "Bank Name": "DEVELOPMENT BANK OF ETHIOPIA",
    "Address": "KEBELE, A.A. CITY ADMINISTRATION 17/18, HOUSE 612 KIRKOS SUBCITY",
    "City": "ADDIS ABABA",
    "Branch": "",
    "Postcode": "1900",
    "Country": "Ethiopia",
    "Connection": "Active"
  },
  {
    "bankCode": "ENAT",
    "countryCode": "ET",
    "branchCode": "TAA",
    "SWIFT Code": "ENATETAA",
    "Bank Name": "ENAT BANK S.C",
    "Address": "ENAT TOWER, JOMO KENYATTA STREET",
    "City": "ADDIS ABABA",
    "Branch": "",
    "Postcode": "5887",
    "Country": "Ethiopia",
    "Connection": "Active"
  },
  {
    "bankCode": "GDAA",
    "countryCode": "ET",
    "branchCode": "TAA",
    "SWIFT Code": "GDAAETAA",
    "Bank Name": "GADAA BANK SC",
    "Address": "OROMIA TOWER, FLOOR 2, GHANA STREET",
    "City": "ADDIS ABABA",
    "Branch": "",
    "Postcode": "1000",
    "Country": "Ethiopia",
    "Connection": "Active"
  },
  {
    "bankCode": "DEGA",
    "countryCode": "ET",
    "branchCode": "TAA",
    "SWIFT Code": "DEGAETAA",
    "Bank Name": "GLOBAL BANK ETHIOPIA S.C (FORMERLY DEBUB GLOBAL BANK S.C)",
    "Address": "NATIONAL TOWER, STADIUM AREA",
    "City": "ADDIS ABABA",
    "Branch": "",
    "Postcode": "1000",
    "Country": "Ethiopia",
    "Connection": "Active"
  },
  {
    "bankCode": "GOBT",
    "countryCode": "ET",
    "branchCode": "TAA",
    "SWIFT Code": "GOBTETAA",
    "Bank Name": "GOH BETOCH BANK S.C.",
    "Address": "ABDERUF PLAZA, AFRICA AVENUE",
    "City": "ADDIS ABABA",
    "Branch": "",
    "Postcode": "",
    "Country": "Ethiopia",
    "Connection": "Active"
  },
  {
    "bankCode": "UNTD",
    "countryCode": "ET",
    "branchCode": "TAA",
    "SWIFT Code": "UNTDETAA",
    "Bank Name": "HIBRET BANK SHARE COMPANY",
    "Address": "HIBER TOWER, FLOOR 32, RAS ABEBE AREGAY ROAD",
    "City": "ADDIS ABABA",
    "Branch": "",
    "Postcode": "9326",
    "Country": "Ethiopia",
    "Connection": "Active"
  },
  {
    "bankCode": "HIJR",
    "countryCode": "ET",
    "branchCode": "TAA",
    "SWIFT Code": "HIJRETAA",
    "Bank Name": "HIJRA BANK SHARE COMPANY",
    "Address": "HIJRA BANK SHARE COMPANY BUILDING,, FLOOR 9 AFRICA AVENUE",
    "City": "ADDIS ABABA",
    "Branch": "",
    "Postcode": "",
    "Country": "Ethiopia",
    "Connection": "Active"
  },
  {
    "bankCode": "LIBS",
    "countryCode": "ET",
    "branchCode": "TAA",
    "SWIFT Code": "LIBSETAA",
    "Bank Name": "LION INTERNATIONAL BANK S.C.",
    "Address": "LEX PLAZA, HAILE GEBRESELASSIE ROAD",
    "City": "ADDIS ABABA",
    "Branch": "",
    "Postcode": "1000",
    "Country": "Ethiopia",
    "Connection": "Active"
  },
  {
    "bankCode": "NBET",
    "countryCode": "ET",
    "branchCode": "TAA",
    "SWIFT Code": "NBETETAA",
    "Bank Name": "NATIONAL BANK OF ETHIOPIA",
    "Address": "UNITY SQUARE, CHURCHILL ROAD",
    "City": "ADDIS ABABA",
    "Branch": "",
    "Postcode": "5550",
    "Country": "Ethiopia",
    "Connection": "Active"
  },
  {
    "bankCode": "NIBI",
    "countryCode": "ET",
    "branchCode": "TAA",
    "SWIFT Code": "NIBIETAA",
    "Bank Name": "NIB INTERNATIONAL BANK S.C.",
    "Address": "DEMBEL BUILDING, FLOOR 6, BOLE ROAD (AFRICA AVENUE",
    "City": "ADDIS ABABA",
    "Branch": "",
    "Postcode": "8111",
    "Country": "Ethiopia",
    "Connection": "Active"
  },
  {
    "bankCode": "OSCO",
    "countryCode": "ET",
    "branchCode": "TAA",
    "SWIFT Code": "OSCOETAA",
    "Bank Name": "OMO BANK SHARE COMPANY",
    "Address": "JOB CREATION AND FOOD SEC AGENCY, MOZAMBIQUE ST, IN FRONT OF FEDERAL",
    "City": "ADDIS ABABA",
    "Branch": "",
    "Postcode": "",
    "Country": "Ethiopia",
    "Connection": "Active"
  },
  {
    "bankCode": "ORIR",
    "countryCode": "ET",
    "branchCode": "TAA",
    "SWIFT Code": "ORIRETAA",
    "Bank Name": "OROMIA INTERNATIONAL BANK S.C.",
    "Address": "NEAR GETU COMMERCIAL BUILDING, AFRICA VENUE STREET",
    "City": "ADDIS ABABA",
    "Branch": "",
    "Postcode": "8111",
    "Country": "Ethiopia",
    "Connection": "Active"
  },
  {
    "bankCode": "RMSI",
    "countryCode": "ET",
    "branchCode": "TAA",
    "SWIFT Code": "RMSIETAA",
    "Bank Name": "RAMMIS BANK SHARE COMPANY",
    "Address": "TOMMY TOWER, FLOOR 9 WOREDA 09, BOLE MAIN ROAD (AFRICA AV NEAR, FLAMINGO RESTAURANT HOUSE NO:059",
    "City": "ADDIS ABABA",
    "Branch": "",
    "Postcode": "",
    "Country": "Ethiopia",
    "Connection": "Active"
  },
  {
    "bankCode": "RMFI",
    "countryCode": "ET",
    "branchCode": "TA2",
    "SWIFT Code": "RMFIETA2",
    "Bank Name": "RAYS MICRO FINANCE INSTITUTION S.C",
    "Address": "FETLE BUILDING, FLOOR 5TH, ETHIO CHINA, WELLO SEFER",
    "City": "ADDIS ABABA",
    "Branch": "",
    "Postcode": "1000",
    "Country": "Ethiopia",
    "Connection": "Active"
  },
  {
    "bankCode": "SBEE",
    "countryCode": "ET",
    "branchCode": "TAA",
    "SWIFT Code": "SBEEETAA",
    "Bank Name": "SHABELLE BANK SHARE COMPANY",
    "Address": "SHABELLE BUSINESS CENTRE, FLOOR 5, MAIN STREET, NEAR SAYID M. HALL",
    "City": "JIJIGA",
    "Branch": "",
    "Postcode": "",
    "Country": "Ethiopia",
    "Connection": "Active"
  },
  {
    "bankCode": "SDMA",
    "countryCode": "ET",
    "branchCode": "TAA",
    "SWIFT Code": "SDMAETAA",
    "Bank Name": "SIDAMA BANK S.C",
    "Address": "HITATA",
    "City": "HAWASSA",
    "Branch": "",
    "Postcode": "",
    "Country": "Ethiopia",
    "Connection": "Active"
  },
  {
    "bankCode": "SINQ",
    "countryCode": "ET",
    "branchCode": "TAA",
    "SWIFT Code": "SINQETAA",
    "Bank Name": "SIINQEE BANK S,C",
    "Address": "ODA TOWER , FLOOR 10, KAZANCHIS",
    "City": "ADDIS ABABA",
    "Branch": "",
    "Postcode": "",
    "Country": "Ethiopia",
    "Connection": "Active"
  },
  {
    "bankCode": "TSDY",
    "countryCode": "ET",
    "branchCode": "TAA",
    "SWIFT Code": "TSDYETAA",
    "Bank Name": "TSEDEY BANK SC",
    "Address": "RAS MEKONNEN STREET, LEGHAR",
    "City": "ADDIS ABABA",
    "Branch": "",
    "Postcode": "0251",
    "Country": "Ethiopia",
    "Connection": "Active"
  },
  {
    "bankCode": "TSCP",
    "countryCode": "ET",
    "branchCode": "TAA",
    "SWIFT Code": "TSCPETAA",
    "Bank Name": "TSEHAY BANK S.C",
    "Address": "MEAZA DESALEGN TOWER, DEBRE ZEYIT ROAD, KIRKOS",
    "City": "ADDIS ABABA",
    "Branch": "",
    "Postcode": "2506",
    "Country": "Ethiopia",
    "Connection": "Active"
  },
  {
    "bankCode": "WEGA",
    "countryCode": "ET",
    "branchCode": "TAA",
    "SWIFT Code": "WEGAETAA",
    "Bank Name": "WEGAGEN BANK S.C.",
    "Address": "WEGAGEN BANK HQ, FLOOR 6-7, WEGAGEN BANK HQ, WEGAGEN TOWER",
    "City": "ADDIS ABEBA",
    "Branch": "",
    "Postcode": "1018",
    "Country": "Ethiopia",
    "Connection": "Active"
  },
  {
    "bankCode": "ZAMZ",
    "countryCode": "ET",
    "branchCode": "TAA",
    "SWIFT Code": "ZAMZETAA",
    "Bank Name": "ZAMZAM BANK S.C",
    "Address": "KADCO BULDING, FLOOR 2, ETHIO CHANIA FRIENDSHIP ROAD, WOLLO SEFER",
    "City": "ADDIS ABABA",
    "Branch": "",
    "Postcode": "1000",
    "Country": "Ethiopia",
    "Connection": "Active"
  },
  {
    "bankCode": "ZEME",
    "countryCode": "ET",
    "branchCode": "TAA",
    "SWIFT Code": "ZEMEETAA",
    "Bank Name": "ZEMEN BANK S.C.",
    "Address": "ABEBECH BUILDING, JOSEPH TITO STREET",
    "City": "ADDIS ABABA",
    "Branch": "",
    "Postcode": "1212",
    "Country": "Ethiopia",
    "Connection": "Active"
  }
]
module.exports = ethiopia
