const finland = [
  {
    "countryCode": "AHOJ",
    "bankCode": "FI",
    "branchCode": "IHH",
    "SWIFT Code": "AHOJFIHH",
    "Bank Name": "AHLSTROM OYJ",
    "Address": "ALVAR AALLON KATU 3 C",
    "City": "HELSINKI",
    "Branch": "",
    "Postcode": "FI-00100",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "HELS",
    "bankCode": "FI",
    "branchCode": "IHH",
    "SWIFT Code": "HELSFIHH",
    "Bank Name": "AKTIA BANK P.L.C.",
    "Address": "ARKADIANKATU 4-6",
    "City": "HELSINKI",
    "Branch": "",
    "Postcode": "FI-00100",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "HELS",
    "bankCode": "FI",
    "branchCode": "HAM",
    "SWIFT Code": "HELSFIHHHAM",
    "Bank Name": "AKTIA BANK P.L.C.",
    "Address": "ARKADIANKATU 4-6",
    "City": "HELSINKI",
    "Branch": "",
    "Postcode": "FI-00100",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "HELS",
    "bankCode": "FI",
    "branchCode": "TIP",
    "SWIFT Code": "HELSFIHHTIP",
    "Bank Name": "AKTIA BANK P.L.C.",
    "Address": "ARKADIANKATU 4-6",
    "City": "HELSINKI",
    "Branch": "TIPS TRANSACTIONS",
    "Postcode": "FI-00100",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "EVSE",
    "bankCode": "FI",
    "branchCode": "IH2",
    "SWIFT Code": "EVSEFIH2",
    "Bank Name": "ALISA BANK PLC",
    "Address": "ALEKSANTERINKATU 19 A",
    "City": "HELSINKI",
    "Branch": "",
    "Postcode": "FI-00101",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "EVSE",
    "bankCode": "FI",
    "branchCode": "IHH",
    "SWIFT Code": "EVSEFIHH",
    "Bank Name": "ALISA BANK PLC",
    "Address": "PURSIMIEHENKATU 4A",
    "City": "HELSINKI",
    "Branch": "",
    "Postcode": "FI-00150",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "EVSE",
    "bankCode": "FI",
    "branchCode": "FND",
    "SWIFT Code": "EVSEFIHHFND",
    "Bank Name": "ALISA BANK PLC",
    "Address": "",
    "City": "HELSINKI",
    "Branch": "INVESTMENT FUNDS",
    "Postcode": "",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "AABA",
    "bankCode": "FI",
    "branchCode": "I22",
    "SWIFT Code": "AABAFI22",
    "Bank Name": "BANK OF ALAND PLC",
    "Address": "NYGATAN 2",
    "City": "MARIEHAMN",
    "Branch": "",
    "Postcode": "FI-22100",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "AABA",
    "bankCode": "FI",
    "branchCode": "TET",
    "SWIFT Code": "AABAFI22TET",
    "Bank Name": "BANK OF ALAND PLC",
    "Address": "NYGATAN 2",
    "City": "MARIEHAMN",
    "Branch": "TECHNICAL",
    "Postcode": "FI-22100",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "AABA",
    "bankCode": "FI",
    "branchCode": "TMS",
    "SWIFT Code": "AABAFI22TMS",
    "Bank Name": "BANK OF ALAND PLC",
    "Address": "",
    "City": "MARIEHAMN",
    "Branch": "TREASURY DEPARTMENT",
    "Postcode": "",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "BPFN",
    "bankCode": "FI",
    "branchCode": "I22",
    "SWIFT Code": "BPFNFI22",
    "Bank Name": "BLUESTEP BANK AB (PUBL), FILIAL I FINLAND",
    "Address": "HERMANNIN RANTATIE 8",
    "City": "HELSINKI",
    "Branch": "",
    "Postcode": "FI-00580",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "POPF",
    "bankCode": "FI",
    "branchCode": "TIP",
    "SWIFT Code": "POPFFI22TIP",
    "Bank Name": "BONUM BANK PLC",
    "Address": "HEVOSENKENKA 3",
    "City": "ESPOO",
    "Branch": "",
    "Postcode": "FI-02600",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "POPF",
    "bankCode": "FI",
    "branchCode": "I22",
    "SWIFT Code": "POPFFI22",
    "Bank Name": "BONUM BANK PLC",
    "Address": "HEVOSENKENKA 3",
    "City": "ESPOO",
    "Branch": "",
    "Postcode": "FI-02600",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "KALM",
    "bankCode": "FI",
    "branchCode": "IHH",
    "SWIFT Code": "KALMFIHH",
    "Bank Name": "CARGOTEC OYJ",
    "Address": "PORKKALANKATU 5",
    "City": "HELSINKI",
    "Branch": "",
    "Postcode": "FI-00180",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "CTEC",
    "bankCode": "FI",
    "branchCode": "IHH",
    "SWIFT Code": "CTECFIHH",
    "Bank Name": "CARGOTEC OYJ",
    "Address": "PORKKALANKATU 5",
    "City": "HELSINKI",
    "Branch": "",
    "Postcode": "FI-00180",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "ITEL",
    "bankCode": "FI",
    "branchCode": "TIP",
    "SWIFT Code": "ITELFIHHTIP",
    "Bank Name": "CENTRAL BANK OF SAVINGS BANKS FINLAND PLC",
    "Address": "TEOLLISUUSKATU 33",
    "City": "HELSINKI",
    "Branch": "",
    "Postcode": "FI-00510",
    "Country": "Finland",
    "Connection": "Active"
  },
  {},
  {
    "countryCode": "CITI",
    "bankCode": "FI",
    "branchCode": "IHX",
    "SWIFT Code": "CITIFIHX",
    "Bank Name": "CITIBANK EUROPE PLC FINLAND BRANCH",
    "Address": "ALEKSANTERINKATU 48A",
    "City": "HELSINKI",
    "Branch": "",
    "Postcode": "FI-00100",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "BSUI",
    "bankCode": "FI",
    "branchCode": "IHH",
    "SWIFT Code": "BSUIFIHH",
    "Bank Name": "CREDIT AGRICOLE CIB",
    "Address": "UNIONINKATU 32B",
    "City": "HELSINKI",
    "Branch": "",
    "Postcode": "FI-00100",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "DABA",
    "bankCode": "FI",
    "branchCode": "IHH",
    "SWIFT Code": "DABAFIHH",
    "Bank Name": "DANSKE BANK A/S, FINLAND BRANCH",
    "Address": "TELEVISIOKATU 1",
    "City": "HELSINKI",
    "Branch": "",
    "Postcode": "FI-00075",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "DABA",
    "bankCode": "FI",
    "branchCode": "CLS",
    "SWIFT Code": "DABAFIHHCLS",
    "Bank Name": "DANSKE BANK A/S, FINLAND BRANCH",
    "Address": "TELEVISIOKATU 1",
    "City": "HELSINKI",
    "Branch": "CLS SERVICES",
    "Postcode": "FI-00075",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "DABA",
    "bankCode": "FI",
    "branchCode": "CAP",
    "SWIFT Code": "DABAFIHHCAP",
    "Bank Name": "DANSKE BANK A/S, FINLAND BRANCH",
    "Address": "TELEVISIOKATU 1",
    "City": "HELSINKI",
    "Branch": "DANSKE CAPITAL",
    "Postcode": "FI-00075",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "DABA",
    "bankCode": "FI",
    "branchCode": "HAM",
    "SWIFT Code": "DABAFIHHHAM",
    "Bank Name": "DANSKE BANK A/S, FINLAND BRANCH",
    "Address": "TELEVISIOKATU 1",
    "City": "HELSINKI",
    "Branch": "RESERVED FOR ECB USAGE",
    "Postcode": "FI-00075",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "DABA",
    "bankCode": "FI",
    "branchCode": "DCA",
    "SWIFT Code": "DABAFIHHDCA",
    "Bank Name": "DANSKE BANK A/S, FINLAND BRANCH",
    "Address": "TELEVISIOKATU 1",
    "City": "HELSINKI",
    "Branch": "RESERVED FOR ECB/TIPS USAGE",
    "Postcode": "FI-00075",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "DABA",
    "bankCode": "FI",
    "branchCode": "ST2",
    "SWIFT Code": "DABAFIHHST2",
    "Bank Name": "DANSKE BANK A/S, FINLAND BRANCH",
    "Address": "TELEVISIOKATU 1",
    "City": "HELSINKI",
    "Branch": "TECHNICAL ADDRESS ACH SETTLEMENT",
    "Postcode": "FI-00075",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "DABA",
    "bankCode": "FI",
    "branchCode": "SD2",
    "SWIFT Code": "DABAFIHHSD2",
    "Bank Name": "DANSKE BANK A/S, FINLAND BRANCH",
    "Address": "TELEVISIOKATU 1",
    "City": "HELSINKI",
    "Branch": "TECHNICAL ADDRESS ACH SETTLEMENT",
    "Postcode": "FI-00075",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "DAKO",
    "bankCode": "FI",
    "branchCode": "IHH",
    "SWIFT Code": "DAKOFIHH",
    "Bank Name": "DANSKE KIINNITYSLUOTTOPANKKI OYJ",
    "Address": "TELEVISIOKATU 1",
    "City": "HELSINKI",
    "Branch": "",
    "Postcode": "FI-00075",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "DNBA",
    "bankCode": "FI",
    "branchCode": "IHX",
    "SWIFT Code": "DNBAFIHX",
    "Bank Name": "DNB BANK ASA, FILIAL FINLAND",
    "Address": "URHO KEKKOSEN KATU 7B",
    "City": "HELSINKI",
    "Branch": "",
    "Postcode": "FI-00100",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "EMPN",
    "bankCode": "FI",
    "branchCode": "I2E",
    "SWIFT Code": "EMPNFI2E",
    "Bank Name": "ELO MUTUAL PENSION INSURANCE COMPANY",
    "Address": "REVONTULENTIE 7",
    "City": "ESPOO",
    "Branch": "",
    "Postcode": "FI-02100",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "APKE",
    "bankCode": "FI",
    "branchCode": "IHH",
    "SWIFT Code": "APKEFIHH",
    "Bank Name": "EUROCLEAR FINLAND LTD",
    "Address": "URHO KEKKOSEN KATU 5 C",
    "City": "HELSINKI",
    "Branch": "",
    "Postcode": "FI-00101",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "APKE",
    "bankCode": "FI",
    "branchCode": "MIG",
    "SWIFT Code": "APKEFIHHMIG",
    "Bank Name": "EUROCLEAR FINLAND LTD",
    "Address": "",
    "City": "HELSINKI",
    "Branch": "",
    "Postcode": "",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "APKE",
    "bankCode": "FI",
    "branchCode": "CLP",
    "SWIFT Code": "APKEFIHHCLP",
    "Bank Name": "EUROCLEAR FINLAND LTD",
    "Address": "",
    "City": "HELSINKI",
    "Branch": "CSD COMMUNITY",
    "Postcode": "",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "APKE",
    "bankCode": "FI",
    "branchCode": "ATP",
    "SWIFT Code": "APKEFIHHATP",
    "Bank Name": "EUROCLEAR FINLAND LTD",
    "Address": "UNIONINKATU 32 B",
    "City": "HELSINKI",
    "Branch": "MONEY MARKET SYSTEM",
    "Postcode": "FI-00131",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "EVII",
    "bankCode": "FI",
    "branchCode": "IHH",
    "SWIFT Code": "EVIIFIHH",
    "Bank Name": "EVLI PLC",
    "Address": "ALEKSANTERINKATU 19, FLOOR 4",
    "City": "HELSINKI",
    "Branch": "",
    "Postcode": "FI-00100",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "HOLV",
    "bankCode": "FI",
    "branchCode": "IHH",
    "SWIFT Code": "HOLVFIHH",
    "Bank Name": "HOLVI PAYMENT SERVICES LTD",
    "Address": "LAPINLAHDENPOLKU 8 E",
    "City": "HELSINKI",
    "Branch": "",
    "Postcode": "FI-00180",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "JPML",
    "bankCode": "FI",
    "branchCode": "IH2",
    "SWIFT Code": "JPMLFIH2",
    "Bank Name": "J.P. MORGAN AG HELSINGIN SIVULIIKE",
    "Address": "ALEKSANTERINKATU 44 A",
    "City": "HELSINKI",
    "Branch": "",
    "Postcode": "FI-00100",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "KEMI",
    "bankCode": "FI",
    "branchCode": "IHH",
    "SWIFT Code": "KEMIFIHH",
    "Bank Name": "KEMIRA OYJ",
    "Address": "ENERGIAKATU",
    "City": "HELSINKI",
    "Branch": "",
    "Postcode": "FI-00180",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "KONE",
    "bankCode": "FI",
    "branchCode": "I22",
    "SWIFT Code": "KONEFI22",
    "Bank Name": "KONE CORPORATION",
    "Address": "KARTANONTIE 1",
    "City": "ESPOO",
    "Branch": "",
    "Postcode": "FI-02150",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "LTAP",
    "bankCode": "FI",
    "branchCode": "I22",
    "SWIFT Code": "LTAPFI22",
    "Bank Name": "LOCALTAPIOLA ASSET MANAGEMENT LTD",
    "Address": "REVONTULENKUJA 1",
    "City": "ESPOO",
    "Branch": "",
    "Postcode": "FI-02010",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "MNAG",
    "bankCode": "FI",
    "branchCode": "MUL",
    "SWIFT Code": "MNAGFIH2MUL",
    "Bank Name": "MANDATUM ASSET MANAGEMENT LTD",
    "Address": "BULEVARDI 56",
    "City": "HELSINKI",
    "Branch": "",
    "Postcode": "FI-00120",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "MNAG",
    "bankCode": "FI",
    "branchCode": "MLI",
    "SWIFT Code": "MNAGFIH2MLI",
    "Bank Name": "MANDATUM ASSET MANAGEMENT LTD",
    "Address": "BULEVARDI 56",
    "City": "HELSINKI",
    "Branch": "",
    "Postcode": "FI-00120",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "MNAG",
    "bankCode": "FI",
    "branchCode": "IH2",
    "SWIFT Code": "MNAGFIH2",
    "Bank Name": "MANDATUM ASSET MANAGEMENT LTD",
    "Address": "BULEVARDI 56",
    "City": "HELSINKI",
    "Branch": "",
    "Postcode": "FI-00120",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "MNAG",
    "bankCode": "FI",
    "branchCode": "KUL",
    "SWIFT Code": "MNAGFIH2KUL",
    "Bank Name": "MANDATUM ASSET MANAGEMENT LTD",
    "Address": "BULEVARDI 56",
    "City": "HELSINKI",
    "Branch": "",
    "Postcode": "FI-00120",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "MNAG",
    "bankCode": "FI",
    "branchCode": "MNS",
    "SWIFT Code": "MNAGFIH2MNS",
    "Bank Name": "MANDATUM ASSET MANAGEMENT LTD",
    "Address": "BULEVARDI 56",
    "City": "HELSINKI",
    "Branch": "",
    "Postcode": "FI-00120",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "MNAG",
    "bankCode": "FI",
    "branchCode": "KVA",
    "SWIFT Code": "MNAGFIH2KVA",
    "Bank Name": "MANDATUM ASSET MANAGEMENT LTD",
    "Address": "BULEVARDI 56",
    "City": "HELSINKI",
    "Branch": "",
    "Postcode": "FI-00120",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "MNAG",
    "bankCode": "FI",
    "branchCode": "MAM",
    "SWIFT Code": "MNAGFIH2MAM",
    "Bank Name": "MANDATUM ASSET MANAGEMENT LTD",
    "Address": "BULEVARDI 56",
    "City": "HELSINKI",
    "Branch": "",
    "Postcode": "FI-00120",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "MGRP",
    "bankCode": "FI",
    "branchCode": "I22",
    "SWIFT Code": "MGRPFI22",
    "Bank Name": "METSA GROUP TREASURY OY",
    "Address": "REVONTULENPUISTO 2",
    "City": "ESPOO",
    "Branch": "",
    "Postcode": "FI-02020",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "OUTC",
    "bankCode": "FI",
    "branchCode": "I22",
    "SWIFT Code": "OUTCFI22",
    "Bank Name": "METSO OYJ",
    "Address": "TOOLONLAHDENKATU 2",
    "City": "HELSINKI",
    "Branch": "",
    "Postcode": "FI-00100",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "MTSO",
    "bankCode": "FI",
    "branchCode": "IHH",
    "SWIFT Code": "MTSOFIHH",
    "Bank Name": "METSO OYJ",
    "Address": "TOOLONLAHDENKATU 2",
    "City": "HELSINKI",
    "Branch": "",
    "Postcode": "FI-00100",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "MOUT",
    "bankCode": "FI",
    "branchCode": "IHH",
    "SWIFT Code": "MOUTFIHH",
    "Bank Name": "METSO OYJ",
    "Address": "TOOLONLAHDENKATU 2",
    "City": "HELSINKI",
    "Branch": "",
    "Postcode": "FI-00100",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "MUFI",
    "bankCode": "FI",
    "branchCode": "IHH",
    "SWIFT Code": "MUFIFIHH",
    "Bank Name": "MUNICIPALITY FINANCE PLC",
    "Address": "JAAKONKATU 3A",
    "City": "HELSINKI",
    "Branch": "",
    "Postcode": "FI-00100",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "NARY",
    "bankCode": "FI",
    "branchCode": "IH2",
    "SWIFT Code": "NARYFIH2",
    "Bank Name": "NARVI PAYMENTS OY AB",
    "Address": "EROTTAJANKATU 5 A 6",
    "City": "HELSINKI",
    "Branch": "",
    "Postcode": "FI-00130",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "NAPY",
    "bankCode": "FI",
    "branchCode": "IH2",
    "SWIFT Code": "NAPYFIH2",
    "Bank Name": "NARVI PAYMENTS OY AB",
    "Address": "MARIA 01, LAPINLAHDENKATU 16",
    "City": "HELSINKI",
    "Branch": "",
    "Postcode": "FI-00180",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "NSTE",
    "bankCode": "FI",
    "branchCode": "I22",
    "SWIFT Code": "NSTEFI22",
    "Bank Name": "NESTE OYJ",
    "Address": "KEILARANTA 21",
    "City": "ESPOO",
    "Branch": "",
    "Postcode": "FI-02150",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "OPUS",
    "bankCode": "FI",
    "branchCode": "I2H",
    "SWIFT Code": "OPUSFI2H",
    "Bank Name": "NOMENTIA OY",
    "Address": "LINNOITUSTIE 6",
    "City": "ESPOO",
    "Branch": "",
    "Postcode": "FI-02600",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "NDEA",
    "bankCode": "FI",
    "branchCode": "NCL",
    "SWIFT Code": "NDEAFIHHNCL",
    "Bank Name": "NORDEA BANK ABP",
    "Address": "",
    "City": "HELSINKI",
    "Branch": "",
    "Postcode": "",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "NDEA",
    "bankCode": "FI",
    "branchCode": "TRI",
    "SWIFT Code": "NDEAFIHHTRI",
    "Bank Name": "NORDEA BANK ABP",
    "Address": "",
    "City": "HELSINKI",
    "Branch": "",
    "Postcode": "",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "NDEA",
    "bankCode": "FI",
    "branchCode": "IHH",
    "SWIFT Code": "NDEAFIHH",
    "Bank Name": "NORDEA BANK ABP",
    "Address": "SATAMARADANKATU 5",
    "City": "HELSINKI",
    "Branch": "",
    "Postcode": "FI-00020",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "NDEA",
    "bankCode": "FI",
    "branchCode": "ISA",
    "SWIFT Code": "NDEAFIHHISA",
    "Bank Name": "NORDEA BANK ABP",
    "Address": "",
    "City": "HELSINKI",
    "Branch": "",
    "Postcode": "",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "NDEA",
    "bankCode": "FI",
    "branchCode": "NMB",
    "SWIFT Code": "NDEAFIHHNMB",
    "Bank Name": "NORDEA BANK ABP",
    "Address": "ALEKSIS KIVEN KATU 3-5",
    "City": "HELSINKI",
    "Branch": "",
    "Postcode": "FI-00020",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "NDEA",
    "bankCode": "FI",
    "branchCode": "IPL",
    "SWIFT Code": "NDEAFIHHIPL",
    "Bank Name": "NORDEA BANK ABP",
    "Address": "SATAMARADANKATU 5",
    "City": "HELSINKI",
    "Branch": "FOR ECB PAYMENTS ONLY",
    "Postcode": "FI-00020",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "NDEA",
    "bankCode": "FI",
    "branchCode": "HAM",
    "SWIFT Code": "NDEAFIHHHAM",
    "Bank Name": "NORDEA BANK ABP",
    "Address": "SATAMARADANKATU 5",
    "City": "HELSINKI",
    "Branch": "HOME ACCOUNTING MODULE",
    "Postcode": "FI-00020",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "NDEA",
    "bankCode": "FI",
    "branchCode": "NFC",
    "SWIFT Code": "NDEAFIHHNFC",
    "Bank Name": "NORDEA BANK ABP",
    "Address": "",
    "City": "HELSINKI",
    "Branch": "MARKETS CLIENTS",
    "Postcode": "",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "NDEA",
    "bankCode": "FI",
    "branchCode": "030",
    "SWIFT Code": "NDEAFIHH030",
    "Bank Name": "NORDEA BANK ABP",
    "Address": "",
    "City": "HELSINKI",
    "Branch": "MARKETS EQUITIES",
    "Postcode": "",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "NDEA",
    "bankCode": "FI",
    "branchCode": "NFH",
    "SWIFT Code": "NDEAFIHHNFH",
    "Bank Name": "NORDEA BANK ABP",
    "Address": "",
    "City": "HELSINKI",
    "Branch": "MARKETS HOUSE",
    "Postcode": "",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "NDEA",
    "bankCode": "FI",
    "branchCode": "NFF",
    "SWIFT Code": "NDEAFIHHNFF",
    "Bank Name": "NORDEA BANK ABP",
    "Address": "ALEKSANTERINKATU 36",
    "City": "HELSINKI",
    "Branch": "NORDEA FINANCE FINLAND LTD",
    "Postcode": "FI-00100",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "NDEA",
    "bankCode": "FI",
    "branchCode": "NSL",
    "SWIFT Code": "NDEAFIHHNSL",
    "Bank Name": "NORDEA BANK ABP",
    "Address": "SATAMARADANKATU 5",
    "City": "HELSINKI",
    "Branch": "SECURITIES",
    "Postcode": "FI-00020",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "NOHO",
    "bankCode": "FI",
    "branchCode": "IH2",
    "SWIFT Code": "NOHOFIH2",
    "Bank Name": "NORDEA HENKIVAKUUTUS SUOMI OY",
    "Address": "ALEKSIS KIVEN KATU 9",
    "City": "HELSINKI",
    "Branch": "",
    "Postcode": "FI-00020",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "NOHO",
    "bankCode": "FI",
    "branchCode": "B65",
    "SWIFT Code": "NOHOFIH2B65",
    "Bank Name": "NORDEA HENKIVAKUUTUS SUOMI OY",
    "Address": "ALEKSIS KIVEN KATU 9",
    "City": "HELSINKI",
    "Branch": "",
    "Postcode": "FI-00020",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "NOHO",
    "bankCode": "FI",
    "branchCode": "B66",
    "SWIFT Code": "NOHOFIH2B66",
    "Bank Name": "NORDEA HENKIVAKUUTUS SUOMI OY",
    "Address": "ALEKSIS KIVEN KATU 9",
    "City": "HELSINKI",
    "Branch": "",
    "Postcode": "FI-00020",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "NOHO",
    "bankCode": "FI",
    "branchCode": "E90",
    "SWIFT Code": "NOHOFIH2E90",
    "Bank Name": "NORDEA HENKIVAKUUTUS SUOMI OY",
    "Address": "ALEKSIS KIVEN KATU 9",
    "City": "HELSINKI",
    "Branch": "",
    "Postcode": "FI-00020",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "NOHO",
    "bankCode": "FI",
    "branchCode": "E91",
    "SWIFT Code": "NOHOFIH2E91",
    "Bank Name": "NORDEA HENKIVAKUUTUS SUOMI OY",
    "Address": "ALEKSIS KIVEN KATU 9",
    "City": "HELSINKI",
    "Branch": "",
    "Postcode": "FI-00020",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "NOHO",
    "bankCode": "FI",
    "branchCode": "I24",
    "SWIFT Code": "NOHOFIH2I24",
    "Bank Name": "NORDEA HENKIVAKUUTUS SUOMI OY",
    "Address": "ALEKSIS KIVEN KATU 9",
    "City": "HELSINKI",
    "Branch": "",
    "Postcode": "FI-00020",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "NOHO",
    "bankCode": "FI",
    "branchCode": "I25",
    "SWIFT Code": "NOHOFIH2I25",
    "Bank Name": "NORDEA HENKIVAKUUTUS SUOMI OY",
    "Address": "ALEKSIS KIVEN KATU 9",
    "City": "HELSINKI",
    "Branch": "",
    "Postcode": "FI-00020",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "NOHO",
    "bankCode": "FI",
    "branchCode": "Q67",
    "SWIFT Code": "NOHOFIH2Q67",
    "Bank Name": "NORDEA HENKIVAKUUTUS SUOMI OY",
    "Address": "ALEKSIS KIVEN KATU 9",
    "City": "HELSINKI",
    "Branch": "",
    "Postcode": "FI-00020",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "NOHO",
    "bankCode": "FI",
    "branchCode": "V03",
    "SWIFT Code": "NOHOFIH2V03",
    "Bank Name": "NORDEA HENKIVAKUUTUS SUOMI OY",
    "Address": "ALEKSIS KIVEN KATU 9",
    "City": "HELSINKI",
    "Branch": "",
    "Postcode": "FI-00020",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "NOHO",
    "bankCode": "FI",
    "branchCode": "V04",
    "SWIFT Code": "NOHOFIH2V04",
    "Bank Name": "NORDEA HENKIVAKUUTUS SUOMI OY",
    "Address": "ALEKSIS KIVEN KATU 9",
    "City": "HELSINKI",
    "Branch": "",
    "Postcode": "FI-00020",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "NOHO",
    "bankCode": "FI",
    "branchCode": "V75",
    "SWIFT Code": "NOHOFIH2V75",
    "Bank Name": "NORDEA HENKIVAKUUTUS SUOMI OY",
    "Address": "ALEKSIS KIVEN KATU 9",
    "City": "HELSINKI",
    "Branch": "",
    "Postcode": "FI-00020",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "NOHO",
    "bankCode": "FI",
    "branchCode": "V76",
    "SWIFT Code": "NOHOFIH2V76",
    "Bank Name": "NORDEA HENKIVAKUUTUS SUOMI OY",
    "Address": "ALEKSIS KIVEN KATU 9",
    "City": "HELSINKI",
    "Branch": "",
    "Postcode": "FI-00020",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "NOHO",
    "bankCode": "FI",
    "branchCode": "V77",
    "SWIFT Code": "NOHOFIH2V77",
    "Bank Name": "NORDEA HENKIVAKUUTUS SUOMI OY",
    "Address": "ALEKSIS KIVEN KATU 9",
    "City": "HELSINKI",
    "Branch": "",
    "Postcode": "FI-00020",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "NOHO",
    "bankCode": "FI",
    "branchCode": "V78",
    "SWIFT Code": "NOHOFIH2V78",
    "Bank Name": "NORDEA HENKIVAKUUTUS SUOMI OY",
    "Address": "ALEKSIS KIVEN KATU 9",
    "City": "HELSINKI",
    "Branch": "",
    "Postcode": "FI-00020",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "NOHO",
    "bankCode": "FI",
    "branchCode": "V79",
    "SWIFT Code": "NOHOFIH2V79",
    "Bank Name": "NORDEA HENKIVAKUUTUS SUOMI OY",
    "Address": "ALEKSIS KIVEN KATU 9",
    "City": "HELSINKI",
    "Branch": "",
    "Postcode": "FI-00020",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "NOHO",
    "bankCode": "FI",
    "branchCode": "V80",
    "SWIFT Code": "NOHOFIH2V80",
    "Bank Name": "NORDEA HENKIVAKUUTUS SUOMI OY",
    "Address": "ALEKSIS KIVEN KATU 9",
    "City": "HELSINKI",
    "Branch": "",
    "Postcode": "FI-00020",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "NOHO",
    "bankCode": "FI",
    "branchCode": "V81",
    "SWIFT Code": "NOHOFIH2V81",
    "Bank Name": "NORDEA HENKIVAKUUTUS SUOMI OY",
    "Address": "ALEKSIS KIVEN KATU 9",
    "City": "HELSINKI",
    "Branch": "",
    "Postcode": "FI-00020",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "NOHO",
    "bankCode": "FI",
    "branchCode": "V82",
    "SWIFT Code": "NOHOFIH2V82",
    "Bank Name": "NORDEA HENKIVAKUUTUS SUOMI OY",
    "Address": "ALEKSIS KIVEN KATU 9",
    "City": "HELSINKI",
    "Branch": "",
    "Postcode": "FI-00020",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "NOHO",
    "bankCode": "FI",
    "branchCode": "V83",
    "SWIFT Code": "NOHOFIH2V83",
    "Bank Name": "NORDEA HENKIVAKUUTUS SUOMI OY",
    "Address": "ALEKSIS KIVEN KATU 9",
    "City": "HELSINKI",
    "Branch": "",
    "Postcode": "FI-00020",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "NOIN",
    "bankCode": "FI",
    "branchCode": "IHH",
    "SWIFT Code": "NOINFIHH",
    "Bank Name": "NORDIC INVESTMENT BANK",
    "Address": "FABIANINKATU 34",
    "City": "HELSINKI",
    "Branch": "",
    "Postcode": "FI-00170",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "NOLF",
    "bankCode": "FI",
    "branchCode": "IH2",
    "SWIFT Code": "NOLFFIH2",
    "Bank Name": "NORTHMILL BANK AB, FILIAL I FINLAND",
    "Address": "UNIONSGATAN 20-22",
    "City": "HELSINKI",
    "Branch": "",
    "Postcode": "FI-00130",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "OMSA",
    "bankCode": "FI",
    "branchCode": "I2S",
    "SWIFT Code": "OMSAFI2S",
    "Bank Name": "OMA SAASTOPANKKI OY",
    "Address": "KESKUSKATU 13",
    "City": "SEINAJOKI",
    "Branch": "",
    "Postcode": "FI-60100",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "OKOY",
    "bankCode": "FI",
    "branchCode": "IHH",
    "SWIFT Code": "OKOYFIHH",
    "Bank Name": "OP CORPORATE BANK PLC",
    "Address": "GEBHARDINAUKIO 1",
    "City": "HELSINKI",
    "Branch": "",
    "Postcode": "FI-00510",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "OKOY",
    "bankCode": "FI",
    "branchCode": "DCA",
    "SWIFT Code": "OKOYFIHHDCA",
    "Bank Name": "OP CORPORATE BANK PLC",
    "Address": "GEBHARDINAUKIO 1",
    "City": "HELSINKI",
    "Branch": "TIPS DCA",
    "Postcode": "FI-00510",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "OKOY",
    "bankCode": "FI",
    "branchCode": "TRX",
    "SWIFT Code": "OKOYFIHHTRX",
    "Bank Name": "OP CORPORATE BANK PLC",
    "Address": "GEBHARDINAUKIO 1",
    "City": "HELSINKI",
    "Branch": "TRANSACTION SERVICES",
    "Postcode": "FI-00510",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "PSFF",
    "bankCode": "FI",
    "branchCode": "IH2",
    "SWIFT Code": "PSFFFIH2",
    "Bank Name": "PAYEX SVERIGE AB FILIAL I FINLAND",
    "Address": "PL 1107",
    "City": "HELSINKI",
    "Branch": "",
    "Postcode": "FI-00101",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "PCMO",
    "bankCode": "FI",
    "branchCode": "IH2",
    "SWIFT Code": "PCMOFIH2",
    "Bank Name": "PCKT MONEY OYJ",
    "Address": "FREDRIKINKATU 61",
    "City": "HELSINKI",
    "Branch": "",
    "Postcode": "FI-00100",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "PPSI",
    "bankCode": "FI",
    "branchCode": "I22",
    "SWIFT Code": "PPSIFI22",
    "Bank Name": "PPS EU SA -SUOMEN SIVULIIKE",
    "Address": "ELIMAENKATU 15",
    "City": "HELSINKI",
    "Branch": "",
    "Postcode": "FI-00510",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "RMRT",
    "bankCode": "FI",
    "branchCode": "I22",
    "SWIFT Code": "RMRTFI22",
    "Bank Name": "RAMIRENT LTD",
    "Address": "TAPULIKAUPUNGINTIE 37",
    "City": "HELSINKI",
    "Branch": "",
    "Postcode": "FI-00751",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "FISE",
    "bankCode": "FI",
    "branchCode": "IHH",
    "SWIFT Code": "FISEFIHH",
    "Bank Name": "S-BANK PLC",
    "Address": "ASSAKESKUS, FLEMINGINKATU 34,, FLOOR 2C",
    "City": "HELSINKI",
    "Branch": "",
    "Postcode": "FI-00510",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "SBAN",
    "bankCode": "FI",
    "branchCode": "IHH",
    "SWIFT Code": "SBANFIHH",
    "Bank Name": "S-BANK PLC",
    "Address": "FLEMINGINKATU 34",
    "City": "HELSINKI",
    "Branch": "",
    "Postcode": "FI-00510",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "SBAN",
    "bankCode": "FI",
    "branchCode": "TIP",
    "SWIFT Code": "SBANFIHHTIP",
    "Bank Name": "S-BANK PLC",
    "Address": "FLEMINGINKATU 34",
    "City": "HELSINKI",
    "Branch": "TIPS DCA",
    "Postcode": "FI-00510",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "UASN",
    "bankCode": "FI",
    "branchCode": "IH2",
    "SWIFT Code": "UASNFIH2",
    "Bank Name": "SALDO BANK UAB SUOMEN SIVULIIKE",
    "Address": "C/O WORKERY+ TEURASTAMO, LAUTATARHANKATU 10",
    "City": "HELSINKI",
    "Branch": "",
    "Postcode": "FI-00580",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "SAWS",
    "bankCode": "FI",
    "branchCode": "IHH",
    "SWIFT Code": "SAWSFIHH",
    "Bank Name": "SANOMA CORPORATION",
    "Address": "TOOLONLAHDENKATU 2",
    "City": "HELSINKI",
    "Branch": "",
    "Postcode": "FI-00100",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "SCNF",
    "bankCode": "FI",
    "branchCode": "IHH",
    "SWIFT Code": "SCNFFIHH",
    "Bank Name": "SANTANDER CONSUMER FINANCE OY",
    "Address": "RISTO RYTIN TIE 33",
    "City": "HELSINKI",
    "Branch": "",
    "Postcode": "FI-00570",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "SAHF",
    "bankCode": "FI",
    "branchCode": "IH2",
    "SWIFT Code": "SAHFFIH2",
    "Bank Name": "SAXO BANK A/S BRANCH IN FINLAND",
    "Address": "MANNERHEIMINTIE 12B",
    "City": "HELSINKI",
    "Branch": "",
    "Postcode": "FI-00100",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "ESSE",
    "bankCode": "FI",
    "branchCode": "IHX",
    "SWIFT Code": "ESSEFIHX",
    "Bank Name": "SKANDINAVISKA ENSKILDA BANKEN",
    "Address": "ETELAESPLANADI 18",
    "City": "HELSINKI",
    "Branch": "",
    "Postcode": "FI-00130",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "ESSE",
    "bankCode": "FI",
    "branchCode": "APX",
    "SWIFT Code": "ESSEFIHXAPX",
    "Bank Name": "SKANDINAVISKA ENSKILDA BANKEN",
    "Address": "ETELAESPLANADI 18",
    "City": "HELSINKI",
    "Branch": "APX",
    "Postcode": "FI-00130",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "ESSE",
    "bankCode": "FI",
    "branchCode": "HAM",
    "SWIFT Code": "ESSEFIHXHAM",
    "Bank Name": "SKANDINAVISKA ENSKILDA BANKEN",
    "Address": "ETELAESPLANADI 18",
    "City": "HELSINKI",
    "Branch": "CONCERNS A HAM ACCOUNT SETUP IN T2",
    "Postcode": "FI-00130",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "ESSE",
    "bankCode": "FI",
    "branchCode": "TIP",
    "SWIFT Code": "ESSEFIHXTIP",
    "Bank Name": "SKANDINAVISKA ENSKILDA BANKEN",
    "Address": "ETELAESPLANADI 18",
    "City": "HELSINKI",
    "Branch": "TIPS CONNECTION",
    "Postcode": "FI-00130",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "VKSK",
    "bankCode": "FI",
    "branchCode": "IHH",
    "SWIFT Code": "VKSKFIHH",
    "Bank Name": "STATE TREASURY",
    "Address": "SORNAISTEN 13B",
    "City": "HELSINKI",
    "Branch": "",
    "Postcode": "FI-00530",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "VKSK",
    "bankCode": "FI",
    "branchCode": "STF",
    "SWIFT Code": "VKSKFIHHSTF",
    "Bank Name": "STATE TREASURY",
    "Address": "SORNAISTEN 13B",
    "City": "HELSINKI",
    "Branch": "",
    "Postcode": "FI-00530",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "SAHP",
    "bankCode": "FI",
    "branchCode": "IH2",
    "SWIFT Code": "SAHPFIH2",
    "Bank Name": "SUOMEN ASUNTOHYPOPANKKI OY",
    "Address": "PL 509",
    "City": "HELSINKI",
    "Branch": "",
    "Postcode": "FI-00101",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "SPFB",
    "bankCode": "FI",
    "branchCode": "CON",
    "SWIFT Code": "SPFBFIHHCON",
    "Bank Name": "SUOMEN PANKKI - FINLANDS BANK",
    "Address": "",
    "City": "HELSINKI",
    "Branch": "",
    "Postcode": "",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "SPFB",
    "bankCode": "FI",
    "branchCode": "IHH",
    "SWIFT Code": "SPFBFIHH",
    "Bank Name": "SUOMEN PANKKI - FINLANDS BANK",
    "Address": "SNELLMANINAUKIO",
    "City": "HELSINKI",
    "Branch": "",
    "Postcode": "FI-00170",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "SPFB",
    "bankCode": "FI",
    "branchCode": "1A3",
    "SWIFT Code": "SPFBFIHH1A3",
    "Bank Name": "SUOMEN PANKKI - FINLANDS BANK",
    "Address": "SNELLMANINAUKIO",
    "City": "HELSINKI",
    "Branch": "",
    "Postcode": "FI-00170",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "SPFB",
    "bankCode": "FI",
    "branchCode": "INT",
    "SWIFT Code": "SPFBFIHHINT",
    "Bank Name": "SUOMEN PANKKI - FINLANDS BANK",
    "Address": "SNELLMANINAUKIO",
    "City": "HELSINKI",
    "Branch": "",
    "Postcode": "FI-00170",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "SPFB",
    "bankCode": "FI",
    "branchCode": "RPO",
    "SWIFT Code": "SPFBFIHHRPO",
    "Bank Name": "SUOMEN PANKKI - FINLANDS BANK",
    "Address": "SNELLMANINAUKIO",
    "City": "HELSINKI",
    "Branch": "",
    "Postcode": "FI-00170",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "SPFB",
    "bankCode": "FI",
    "branchCode": "CMS",
    "SWIFT Code": "SPFBFIHHCMS",
    "Bank Name": "SUOMEN PANKKI - FINLANDS BANK",
    "Address": "",
    "City": "HELSINKI",
    "Branch": "COLLATERAL MANAGEMENT",
    "Postcode": "",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "SPFB",
    "bankCode": "FI",
    "branchCode": "ECB",
    "SWIFT Code": "SPFBFIHHECB",
    "Bank Name": "SUOMEN PANKKI - FINLANDS BANK",
    "Address": "",
    "City": "HELSINKI",
    "Branch": "ECB OPERATIONS",
    "Postcode": "",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "SPFB",
    "bankCode": "FI",
    "branchCode": "ECM",
    "SWIFT Code": "SPFBFIHHECM",
    "Bank Name": "SUOMEN PANKKI - FINLANDS BANK",
    "Address": "SNELLMANINAUKIO",
    "City": "HELSINKI",
    "Branch": "ECMS-T2S TECHNICAL BIC",
    "Postcode": "FI-00170",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "SPFB",
    "bankCode": "FI",
    "branchCode": "EUX",
    "SWIFT Code": "SPFBFIHHEUX",
    "Bank Name": "SUOMEN PANKKI - FINLANDS BANK",
    "Address": "",
    "City": "HELSINKI",
    "Branch": "TARGET2 NCB/ECB INTERNAL",
    "Postcode": "",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "SPFB",
    "bankCode": "FI",
    "branchCode": "1A1",
    "SWIFT Code": "SPFBFIHH1A1",
    "Bank Name": "SUOMEN PANKKI - FINLANDS BANK",
    "Address": "",
    "City": "HELSINKI",
    "Branch": "TARGET2 PMJ-AS DTS",
    "Postcode": "",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "SPFB",
    "bankCode": "FI",
    "branchCode": "ASI",
    "SWIFT Code": "SPFBFIHHASI",
    "Bank Name": "SUOMEN PANKKI - FINLANDS BANK",
    "Address": "",
    "City": "HELSINKI",
    "Branch": "TARGET2 PMJ-AS NTS",
    "Postcode": "",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "SPFB",
    "bankCode": "FI",
    "branchCode": "1A2",
    "SWIFT Code": "SPFBFIHH1A2",
    "Bank Name": "SUOMEN PANKKI - FINLANDS BANK",
    "Address": "",
    "City": "HELSINKI",
    "Branch": "TARGET2 RAHAHUOLTO",
    "Postcode": "",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "SPFB",
    "bankCode": "FI",
    "branchCode": "RMA",
    "SWIFT Code": "SPFBFIHHRMA",
    "Bank Name": "SUOMEN PANKKI - FINLANDS BANK",
    "Address": "",
    "City": "HELSINKI",
    "Branch": "TARGET2 RMA INTERNAL",
    "Postcode": "",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "SPFB",
    "bankCode": "FI",
    "branchCode": "SFA",
    "SWIFT Code": "SPFBFIHHSFA",
    "Bank Name": "SUOMEN PANKKI - FINLANDS BANK",
    "Address": "",
    "City": "HELSINKI",
    "Branch": "TARGET2 SFA INTERNAL",
    "Postcode": "",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "SPFB",
    "bankCode": "FI",
    "branchCode": "SFM",
    "SWIFT Code": "SPFBFIHHSFM",
    "Bank Name": "SUOMEN PANKKI - FINLANDS BANK",
    "Address": "",
    "City": "HELSINKI",
    "Branch": "TARGET2 SFM INTERNAL",
    "Postcode": "",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "SVEA",
    "bankCode": "FI",
    "branchCode": "IH2",
    "SWIFT Code": "SVEAFIH2",
    "Bank Name": "SVEA BANK AB, FILIAL I FINLAND",
    "Address": "MECHELININKATU 1 A",
    "City": "HELSINKI",
    "Branch": "",
    "Postcode": "FI-00180",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "HAND",
    "bankCode": "FI",
    "branchCode": "IHH",
    "SWIFT Code": "HANDFIHH",
    "Bank Name": "SVENSKA HANDELSBANKEN",
    "Address": "ITAMERENKATU 11-13",
    "City": "HELSINKI",
    "Branch": "",
    "Postcode": "FI-00180",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "HAND",
    "bankCode": "FI",
    "branchCode": "CUS",
    "SWIFT Code": "HANDFIHHCUS",
    "Bank Name": "SVENSKA HANDELSBANKEN",
    "Address": "ITAMERENKATU 11-13",
    "City": "HELSINKI",
    "Branch": "NORDIC CUSTODY SERVICES",
    "Postcode": "FI-00180",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "HAND",
    "bankCode": "FI",
    "branchCode": "TIP",
    "SWIFT Code": "HANDFIHHTIP",
    "Bank Name": "SVENSKA HANDELSBANKEN",
    "Address": "ITAMERENKATU 11-13",
    "City": "HELSINKI",
    "Branch": "TIPS TRANSACTIONS",
    "Postcode": "FI-00180",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "SWED",
    "bankCode": "FI",
    "branchCode": "IHH",
    "SWIFT Code": "SWEDFIHH",
    "Bank Name": "SWEDBANK AB",
    "Address": "KASARMIKATU 25",
    "City": "HELSINKI",
    "Branch": "",
    "Postcode": "FI-00101",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "TAAL",
    "bankCode": "FI",
    "branchCode": "IHH",
    "SWIFT Code": "TAALFIHH",
    "Bank Name": "TAALERI OYJ",
    "Address": "KASARMIKATU 21B",
    "City": "HELSINKI",
    "Branch": "",
    "Postcode": "FI-00130",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "TICO",
    "bankCode": "FI",
    "branchCode": "IHH",
    "SWIFT Code": "TICOFIHH",
    "Bank Name": "TIETOEVRY OYJ",
    "Address": "KEILALAHDENTIE 2-4",
    "City": "ESPOO",
    "Branch": "",
    "Postcode": "FI-02150",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "TICO",
    "bankCode": "FI",
    "branchCode": "IHE",
    "SWIFT Code": "TICOFIHE",
    "Bank Name": "TIETOEVRY OYJ",
    "Address": "KEILALAHDENTIE 2-4",
    "City": "ESPOO",
    "Branch": "",
    "Postcode": "FI-02150",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "TRYE",
    "bankCode": "FI",
    "branchCode": "IH2",
    "SWIFT Code": "TRYEFIH2",
    "Bank Name": "TRUELAYER (IRELAND) LIMITED, SUOMEN SIVULIIKE",
    "Address": "KONEPAJANKUJA 1",
    "City": "HELSINKI",
    "Branch": "",
    "Postcode": "FI-00510",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "UPMK",
    "bankCode": "FI",
    "branchCode": "IHH",
    "SWIFT Code": "UPMKFIHH",
    "Bank Name": "UPM-KYMMENE CORPORATION",
    "Address": "ALVAR AALLON KATU 1",
    "City": "HELSINKI",
    "Branch": "",
    "Postcode": "FI-00101",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "VLMT",
    "bankCode": "FI",
    "branchCode": "IHH",
    "SWIFT Code": "VLMTFIHH",
    "Bank Name": "VALMET CORPORATION",
    "Address": "KEILASATAMA 5",
    "City": "ESPOO",
    "Branch": "",
    "Postcode": "FI-02150",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "NLES",
    "bankCode": "FI",
    "branchCode": "IHH",
    "SWIFT Code": "NLESFIHH",
    "Bank Name": "VALMET CORPORATION (FORMERLY NELES CORPORATION)",
    "Address": "KEILASATAMA 5",
    "City": "ESPOO",
    "Branch": "",
    "Postcode": "FI-02150",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "VPAY",
    "bankCode": "FI",
    "branchCode": "IH2",
    "SWIFT Code": "VPAYFIH2",
    "Bank Name": "VIVA PAYMENT SERVICES S.A. SUOMEN SIVULIIKE",
    "Address": "HAMEENTIE 19",
    "City": "HELSINKI",
    "Branch": "",
    "Postcode": "FI-00500",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "WRTC",
    "bankCode": "FI",
    "branchCode": "IHH",
    "SWIFT Code": "WRTCFIHH",
    "Bank Name": "WARTSILA OYJ ABP",
    "Address": "HIILILAITURINKUJA 2",
    "City": "HELSINKI",
    "Branch": "",
    "Postcode": "FI-00180",
    "Country": "Finland",
    "Connection": "Active"
  },
  {
    "countryCode": "WIHU",
    "bankCode": "FI",
    "branchCode": "IHH",
    "SWIFT Code": "WIHUFIHH",
    "Bank Name": "WIHURI INTERNATIONAL OY",
    "Address": "WIHURINAUKIO 2",
    "City": "HELSINKI",
    "Branch": "",
    "Postcode": "FI-00570",
    "Country": "Finland",
    "Connection": "Active"
  }
]
module.exports = finland
