const gabon = [
  {
    "bankCode": "BICI",
    "countryCode": "GA",
    "branchCode": "ALX",
    "SWIFT Code": "BICIGALX",
    "Bank Name": "B.I.C.I. DU GABON",
    "Address": "AVENUE DU COLONEL PARANT",
    "City": "LIBREVILLE",
    "Branch": "",
    "Postcode": "",
    "Country": "Gabon",
    "Connection": "Active"
  },
  {
    "bankCode": "BICI",
    "countryCode": "GA",
    "branchCode": "ADL",
    "SWIFT Code": "BICIGALXADL",
    "Bank Name": "B.I.C.I. DU GABON",
    "Address": "",
    "City": "LIBREVILLE",
    "Branch": "ADL BRANCH",
    "Postcode": "",
    "Country": "Gabon",
    "Connection": "Active"
  },
  {
    "bankCode": "BICI",
    "countryCode": "GA",
    "branchCode": "MBT",
    "SWIFT Code": "BICIGALXMBT",
    "Bank Name": "B.I.C.I. DU GABON",
    "Address": "",
    "City": "LIBREVILLE",
    "Branch": "MONT-BOUET BRANCH",
    "Postcode": "",
    "Country": "Gabon",
    "Connection": "Active"
  },
  {
    "bankCode": "BICI",
    "countryCode": "GA",
    "branchCode": "OLO",
    "SWIFT Code": "BICIGALXOLO",
    "Bank Name": "B.I.C.I. DU GABON",
    "Address": "",
    "City": "LIBREVILLE",
    "Branch": "OLOUMI BRANCH",
    "Postcode": "",
    "Country": "Gabon",
    "Connection": "Active"
  },
  {
    "bankCode": "BICI",
    "countryCode": "GA",
    "branchCode": "MDA",
    "SWIFT Code": "BICIGALXMDA",
    "Bank Name": "B.I.C.I. DU GABON",
    "Address": "",
    "City": "MOANDA",
    "Branch": "MOANDA BRANCH",
    "Postcode": "",
    "Country": "Gabon",
    "Connection": "Active"
  },
  {
    "bankCode": "BICI",
    "countryCode": "GA",
    "branchCode": "POG",
    "SWIFT Code": "BICIGALXPOG",
    "Bank Name": "B.I.C.I. DU GABON",
    "Address": "",
    "City": "PORT GENTIL",
    "Branch": "",
    "Postcode": "",
    "Country": "Gabon",
    "Connection": "Active"
  },
  {
    "bankCode": "BEAC",
    "countryCode": "GA",
    "branchCode": "520",
    "SWIFT Code": "BEACGALI520",
    "Bank Name": "BANQUE DES ETATS DE L'AFRIQUE CENTRALE D.N. GABON",
    "Address": "",
    "City": "FRANCEVILLE",
    "Branch": "AGENCE DE FRANCEVILLE",
    "Postcode": "",
    "Country": "Gabon",
    "Connection": "Active"
  },
  {
    "bankCode": "BEAC",
    "countryCode": "GA",
    "branchCode": "ALI",
    "SWIFT Code": "BEACGALI",
    "Bank Name": "BANQUE DES ETATS DE L'AFRIQUE CENTRALE D.N. GABON",
    "Address": "",
    "City": "LIBREVILLE",
    "Branch": "",
    "Postcode": "",
    "Country": "Gabon",
    "Connection": "Active"
  },
  {
    "bankCode": "BEAC",
    "countryCode": "GA",
    "branchCode": "530",
    "SWIFT Code": "BEACGALI530",
    "Bank Name": "BANQUE DES ETATS DE L'AFRIQUE CENTRALE D.N. GABON",
    "Address": "",
    "City": "OYEM",
    "Branch": "AGENCE DE OYEM",
    "Postcode": "",
    "Country": "Gabon",
    "Connection": "Active"
  },
  {
    "bankCode": "BEAC",
    "countryCode": "GA",
    "branchCode": "510",
    "SWIFT Code": "BEACGALI510",
    "Bank Name": "BANQUE DES ETATS DE L'AFRIQUE CENTRALE D.N. GABON",
    "Address": "",
    "City": "PORT GENTIL",
    "Branch": "AGENCE DE PORT GENTIL",
    "Postcode": "",
    "Country": "Gabon",
    "Connection": "Active"
  },
  {
    "bankCode": "BGFI",
    "countryCode": "GA",
    "branchCode": "ALI",
    "SWIFT Code": "BGFIGALI",
    "Bank Name": "BGFIBANK",
    "Address": "BOULEVARD DE L'INDEPENDANCE",
    "City": "LIBREVILLE",
    "Branch": "",
    "Postcode": "",
    "Country": "Gabon",
    "Connection": "Active"
  },
  {
    "bankCode": "BGFI",
    "countryCode": "GA",
    "branchCode": "PTN",
    "SWIFT Code": "BGFIGALIPTN",
    "Bank Name": "BGFIBANK",
    "Address": "BD. DE L'INDEPENDANCE",
    "City": "LIBREVILLE",
    "Branch": "",
    "Postcode": "",
    "Country": "Gabon",
    "Connection": "Active"
  },
  {
    "bankCode": "BGFI",
    "countryCode": "GA",
    "branchCode": "POG",
    "SWIFT Code": "BGFIGALIPOG",
    "Bank Name": "BGFIBANK",
    "Address": "BD. DE L'INDEPENDANCE",
    "City": "LIBREVILLE",
    "Branch": "",
    "Postcode": "",
    "Country": "Gabon",
    "Connection": "Active"
  },
  {
    "bankCode": "BGFI",
    "countryCode": "GA",
    "branchCode": "OWD",
    "SWIFT Code": "BGFIGALIOWD",
    "Bank Name": "BGFIBANK",
    "Address": "BD. DE L'INDEPENDANCE",
    "City": "LIBREVILLE",
    "Branch": "",
    "Postcode": "",
    "Country": "Gabon",
    "Connection": "Active"
  },
  {
    "bankCode": "BGFI",
    "countryCode": "GA",
    "branchCode": "MAL",
    "SWIFT Code": "BGFIGALIMAL",
    "Bank Name": "BGFIBANK",
    "Address": "BD. DE L'INDEPENDANCE",
    "City": "LIBREVILLE",
    "Branch": "",
    "Postcode": "",
    "Country": "Gabon",
    "Connection": "Active"
  },
  {
    "bankCode": "BGFI",
    "countryCode": "GA",
    "branchCode": "BKZ",
    "SWIFT Code": "BGFIGALIBKZ",
    "Bank Name": "BGFIBANK",
    "Address": "BD. DE L'INDEPENDANCE",
    "City": "LIBREVILLE",
    "Branch": "",
    "Postcode": "",
    "Country": "Gabon",
    "Connection": "Active"
  },
  {
    "bankCode": "CITI",
    "countryCode": "GA",
    "branchCode": "ALX",
    "SWIFT Code": "CITIGALX",
    "Bank Name": "CITIBANK N.A.",
    "Address": "BOULEVARD QUABEN ET RUE KRINGER",
    "City": "LIBREVILLE",
    "Branch": "CITIBANK N.A. LIBREVILLE",
    "Postcode": "",
    "Country": "Gabon",
    "Connection": "Active"
  },
  {
    "bankCode": "CITI",
    "countryCode": "GA",
    "branchCode": "TRD",
    "SWIFT Code": "CITIGALXTRD",
    "Bank Name": "CITIBANK N.A.",
    "Address": "RUE KRINGER QUABEN",
    "City": "LIBREVILLE",
    "Branch": "TRADE SERVICES DEPT.",
    "Postcode": "",
    "Country": "Gabon",
    "Connection": "Active"
  },
  {
    "bankCode": "ECOC",
    "countryCode": "GA",
    "branchCode": "ALI",
    "SWIFT Code": "ECOCGALI",
    "Bank Name": "ECOBANK GABON",
    "Address": "FLOOR 9, 214 AVENUE BOUET",
    "City": "LIBREVILLE",
    "Branch": "",
    "Postcode": "12111",
    "Country": "Gabon",
    "Connection": "Active"
  },
  {
    "bankCode": "CCPG",
    "countryCode": "GA",
    "branchCode": "ALI",
    "SWIFT Code": "CCPGGALI",
    "Bank Name": "GABON-POSTE",
    "Address": "DELTA-POSTAL",
    "City": "LIBREVILLE",
    "Branch": "",
    "Postcode": "20000",
    "Country": "Gabon",
    "Connection": "Active"
  },
  {
    "bankCode": "ORBK",
    "countryCode": "GA",
    "branchCode": "ALI",
    "SWIFT Code": "ORBKGALI",
    "Bank Name": "ORABANK GABON",
    "Address": "IMMEUBLE SERRENA MALL, 104 RUE GUSTAVE ANGUILE",
    "City": "LIBREVILLE",
    "Branch": "",
    "Postcode": "20333",
    "Country": "Gabon",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "GA",
    "branchCode": "ALI",
    "SWIFT Code": "UNAFGALI",
    "Bank Name": "UBA GABON",
    "Address": "FLOOR 3, BOULEVARD TRIOMPHAL, VALLEE SAINTE MARIE",
    "City": "LIBREVILLE",
    "Branch": "",
    "Postcode": "",
    "Country": "Gabon",
    "Connection": "Active"
  },
  {
    "bankCode": "UGAB",
    "countryCode": "GA",
    "branchCode": "ALI",
    "SWIFT Code": "UGABGALI",
    "Bank Name": "UNION GABONAISE DE BANQUE",
    "Address": "AVENUE DU COLONEL PARANT",
    "City": "LIBREVILLE",
    "Branch": "AGENCE LIBREVILLE",
    "Postcode": "",
    "Country": "Gabon",
    "Connection": "Active"
  }
]
module.exports = gabon
