const gambia = [
  {
    "bankCode": "ACGA",
    "countryCode": "GM",
    "branchCode": "MGF",
    "SWIFT Code": "ACGAGMGF",
    "Bank Name": "ACCESS BANK GAMBIA",
    "Address": "47 KAIRABA AVENUE",
    "City": "FAJARA",
    "Branch": "",
    "Postcode": "",
    "Country": "Gambia",
    "Connection": "Active"
  },
  {
    "bankCode": "AGIX",
    "countryCode": "GM",
    "branchCode": "MGM",
    "SWIFT Code": "AGIXGMGM",
    "Bank Name": "AGIB BANK LTD",
    "Address": "BECCA PLAZA, 5/6 LIBERATION AVENUE",
    "City": "BANJUL",
    "Branch": "",
    "Postcode": "",
    "Country": "Gambia",
    "Connection": "Active"
  },
  {
    "bankCode": "SKYE",
    "countryCode": "GM",
    "branchCode": "MGM",
    "SWIFT Code": "SKYEGMGM",
    "Bank Name": "BLOOM BANK AFRICA LIMITED, GAMBIA",
    "Address": "FAJARA KSMD, 70 KAIRABA AVENUE",
    "City": "BANJUL",
    "Branch": "",
    "Postcode": "",
    "Country": "Gambia",
    "Connection": "Active"
  },
  {
    "bankCode": "BSAH",
    "countryCode": "GM",
    "branchCode": "MGM",
    "SWIFT Code": "BSAHGMGM",
    "Bank Name": "BSIC GAMBIA LIMITED",
    "Address": "SANKUNG SILLAH, 52 KAIRABA AVENUE",
    "City": "KANIFING",
    "Branch": "",
    "Postcode": "",
    "Country": "Gambia",
    "Connection": "Active"
  },
  {
    "bankCode": "CBGA",
    "countryCode": "GM",
    "branchCode": "MGM",
    "SWIFT Code": "CBGAGMGM",
    "Bank Name": "CENTRAL BANK OF THE GAMBIA",
    "Address": "CENTRAL BANK BUILDING, 1 - 2 ECOWAS AVENUE",
    "City": "BANJUL",
    "Branch": "",
    "Postcode": "",
    "Country": "Gambia",
    "Connection": "Active"
  },
  {
    "bankCode": "ECOC",
    "countryCode": "GM",
    "branchCode": "MGM",
    "SWIFT Code": "ECOCGMGM",
    "Bank Name": "ECOBANK GAMBIA",
    "Address": "ECOBANK HOUSE, 42 KAIRABA AVENUE",
    "City": "SERREKUNDA",
    "Branch": "",
    "Postcode": "",
    "Country": "Gambia",
    "Connection": "Active"
  },
  {
    "bankCode": "ICBG",
    "countryCode": "GM",
    "branchCode": "MGS",
    "SWIFT Code": "ICBGGMGS",
    "Bank Name": "FBN BANK GAMBIA LIMITED",
    "Address": "48 KAIRABA AVE",
    "City": "SERREKUNDA",
    "Branch": "",
    "Postcode": "",
    "Country": "Gambia",
    "Connection": "Active"
  },
  {
    "bankCode": "FIBL",
    "countryCode": "GM",
    "branchCode": "MGM",
    "SWIFT Code": "FIBLGMGM",
    "Bank Name": "FIRST INTERNATIONAL BANK LIMITED",
    "Address": "6 OAU BOULEVARD",
    "City": "BANJUL",
    "Branch": "",
    "Postcode": "",
    "Country": "Gambia",
    "Connection": "Active"
  },
  {
    "bankCode": "GTBG",
    "countryCode": "GM",
    "branchCode": "MGM",
    "SWIFT Code": "GTBGGMGM",
    "Bank Name": "GUARANTY TRUST BANK (GAMBIA) LIMITED",
    "Address": "FAJARA KSMD, 56 KAIRABA AVENUE",
    "City": "BANJUL",
    "Branch": "",
    "Postcode": "",
    "Country": "Gambia",
    "Connection": "Active"
  },
  {},
  {
    "bankCode": "SCBL",
    "countryCode": "GM",
    "branchCode": "MGM",
    "SWIFT Code": "SCBLGMGM",
    "Bank Name": "STANDARD CHARTERED BANK GAMBIA LIMITED",
    "Address": "8 ECONAS AVENUE",
    "City": "BANJUL",
    "Branch": "",
    "Postcode": "",
    "Country": "Gambia",
    "Connection": "Active"
  },
  {
    "bankCode": "TBLT",
    "countryCode": "GM",
    "branchCode": "MGM",
    "SWIFT Code": "TBLTGMGM",
    "Bank Name": "TRUST BANK LTD",
    "Address": "TRUST BANK BUILDING, 3-4 ECOWAS AVENUE",
    "City": "BANJUL",
    "Branch": "",
    "Postcode": "",
    "Country": "Gambia",
    "Connection": "Active"
  },
  {
    "bankCode": "ZEIB",
    "countryCode": "GM",
    "branchCode": "MGM",
    "SWIFT Code": "ZEIBGMGM",
    "Bank Name": "ZENITH BANK GAMBIA",
    "Address": "49 KAIRABA AVENUE",
    "City": "FAJARA",
    "Branch": "",
    "Postcode": "",
    "Country": "Gambia",
    "Connection": "Active"
  }
]
module.exports = gambia
