const ghana = [
  {
    "countryCode": "SCBL",
    "bankCode": "GH",
    "branchCode": "TDI",
    "SWIFT Code": "SCBLGHACTDI",
    "Bank Name": "STANDARD CHARTERED BANK GHANA PLC",
    "Address": "",
    "City": "TAKORADI",
    "Branch": "",
    "Postcode": "",
    "Country": "Ghana",
    "Connection": "Active"
  },
  {
    "countryCode": "SCBL",
    "bankCode": "GH",
    "branchCode": "TMA",
    "SWIFT Code": "SCBLGHACTMA",
    "Bank Name": "STANDARD CHARTERED BANK GHANA PLC",
    "Address": "",
    "City": "TEMA",
    "Branch": "",
    "Postcode": "",
    "Country": "Ghana",
    "Connection": "Active"
  },
  {
    "countryCode": "TAKO",
    "bankCode": "GH",
    "branchCode": "HAC",
    "SWIFT Code": "TAKOGHAC",
    "Bank Name": "TAKORADI INTERNATIONAL COMPANY",
    "Address": "VRA ABOADZE THERMAL PLANT",
    "City": "TAKORADI",
    "Branch": "",
    "Postcode": "MC2204",
    "Country": "Ghana",
    "Connection": "Active"
  },
  {
    "countryCode": "STBG",
    "bankCode": "GH",
    "branchCode": "HAC",
    "SWIFT Code": "STBGGHAC",
    "Bank Name": "UNITED BANK FOR AFRICA (GHANA) LTD",
    "Address": "HERITAGE TOWER, AMBASSADORIAL ENCLAVE OFF LIBERIA R",
    "City": "ACCRA",
    "Branch": "",
    "Postcode": "",
    "Country": "Ghana",
    "Connection": "Active"
  },
  {
    "countryCode": "MBGH",
    "bankCode": "GH",
    "branchCode": "HAC",
    "SWIFT Code": "MBGHGHAC",
    "Bank Name": "UNIVERSAL MERCHANT BANK LTD",
    "Address": "SSNIT EMPORIUM PROPERTY, LIBERATION ROAD, AIRPORT CITY",
    "City": "ACCRA",
    "Branch": "",
    "Postcode": "",
    "Country": "Ghana",
    "Connection": "Active"
  },
  {
    "countryCode": "MBGH",
    "bankCode": "GH",
    "branchCode": "KSI",
    "SWIFT Code": "MBGHGHACKSI",
    "Bank Name": "UNIVERSAL MERCHANT BANK LTD",
    "Address": "",
    "City": "KUMASI",
    "Branch": "",
    "Postcode": "",
    "Country": "Ghana",
    "Connection": "Active"
  },
  {
    "countryCode": "MBGH",
    "bankCode": "GH",
    "branchCode": "TDI",
    "SWIFT Code": "MBGHGHACTDI",
    "Bank Name": "UNIVERSAL MERCHANT BANK LTD",
    "Address": "",
    "City": "TAKORADI",
    "Branch": "",
    "Postcode": "",
    "Country": "Ghana",
    "Connection": "Active"
  },
  {
    "countryCode": "MBGH",
    "bankCode": "GH",
    "branchCode": "TMA",
    "SWIFT Code": "MBGHGHACTMA",
    "Bank Name": "UNIVERSAL MERCHANT BANK LTD",
    "Address": "",
    "City": "TEMA",
    "Branch": "",
    "Postcode": "",
    "Country": "Ghana",
    "Connection": "Active"
  },
  {
    "countryCode": "ZEBL",
    "bankCode": "GH",
    "branchCode": "HAC",
    "SWIFT Code": "ZEBLGHAC",
    "Bank Name": "ZENITH BANK (GHANA) LTD",
    "Address": "PREMIERS TOWERS NO. 31, INDEPENDENCE AVENUE ZENITH HEIGHTS, CANTONM",
    "City": "ACCRA",
    "Branch": "",
    "Postcode": "",
    "Country": "Ghana",
    "Connection": "Active"
  },
  {
    "countryCode": "BARC",
    "bankCode": "GH",
    "branchCode": "CSS",
    "SWIFT Code": "BARCGHACCSS",
    "Bank Name": "ABSA BANK OF GHANA LIMITED",
    "Address": "ABSA HOUSE, HIGH STREET",
    "City": "ACCRA",
    "Branch": "ABSA GHANA CUSTODY SECURITIES SERVICES",
    "Postcode": "",
    "Country": "Ghana",
    "Connection": "Active"
  },
  {
    "countryCode": "BARC",
    "bankCode": "GH",
    "branchCode": "HAC",
    "SWIFT Code": "BARCGHAC",
    "Bank Name": "ABSA BANK OF GHANA LIMITED",
    "Address": "ABSA HOUSE, HIGH STREET",
    "City": "ACCRA",
    "Branch": "ALL BRANCHES IN GHANA",
    "Postcode": "",
    "Country": "Ghana",
    "Connection": "Active"
  },
  {
    "countryCode": "BARC",
    "bankCode": "GH",
    "branchCode": "OBU",
    "SWIFT Code": "BARCGHACOBU",
    "Bank Name": "ABSA BANK OF GHANA LIMITED",
    "Address": "UNA HOME, AIRPORT CITY",
    "City": "ACCRA",
    "Branch": "OFFSHORE BANKING UNIT",
    "Postcode": "",
    "Country": "Ghana",
    "Connection": "Active"
  },
  {
    "countryCode": "ABNG",
    "bankCode": "GH",
    "branchCode": "HAC",
    "SWIFT Code": "ABNGGHAC",
    "Bank Name": "ACCESS BANK (GHANA) PLC",
    "Address": "0000 STARLETS 91 ROAD OPPOSITE, OHENE DJAN STADIUM",
    "City": "ACCRA",
    "Branch": "",
    "Postcode": "",
    "Country": "Ghana",
    "Connection": "Active"
  },
  {
    "countryCode": "ADNT",
    "bankCode": "GH",
    "branchCode": "HAC",
    "SWIFT Code": "ADNTGHAC",
    "Bank Name": "AGRICULTURAL DEVELOPMENT BANK",
    "Address": "ACCRA FINANCIAL CENTRE, 3RD AMBASSADORIAL DEVELOPMENT AREA, RIDGE",
    "City": "ACCRA",
    "Branch": "",
    "Postcode": "",
    "Country": "Ghana",
    "Connection": "Active"
  },
  {
    "countryCode": "AREX",
    "bankCode": "GH",
    "branchCode": "HAC",
    "SWIFT Code": "AREXGHAC",
    "Bank Name": "ARB APEX BANK LIMITED",
    "Address": "5 9TH ROAD GAMEL ABDUL NASSER",
    "City": "ACCRA",
    "Branch": "",
    "Postcode": "",
    "Country": "Ghana",
    "Connection": "Active"
  },
  {
    "countryCode": "AMMA",
    "bankCode": "GH",
    "branchCode": "HAC",
    "SWIFT Code": "AMMAGHAC",
    "Bank Name": "BANK OF AFRICA - GHANA LIMITED",
    "Address": "1ST FLOOR, BLOCK A AND B, THE, OCTAGON INDEPENDENCE AVENUE, ADABRAKA",
    "City": "ACCRA",
    "Branch": "",
    "Postcode": "",
    "Country": "Ghana",
    "Connection": "Active"
  },
  {
    "countryCode": "BAGH",
    "bankCode": "GH",
    "branchCode": "HAB",
    "SWIFT Code": "BAGHGHAB",
    "Bank Name": "BANK OF GHANA",
    "Address": "1 THORPE ROAD",
    "City": "ACCRA",
    "Branch": "",
    "Postcode": "",
    "Country": "Ghana",
    "Connection": "Active"
  },
  {
    "countryCode": "BAGH",
    "bankCode": "GH",
    "branchCode": "HA4",
    "SWIFT Code": "BAGHGHA4",
    "Bank Name": "BANK OF GHANA",
    "Address": "FLOOR 4, CEDI HOUSE, LIBERIA ROAD",
    "City": "ACCRA",
    "Branch": "",
    "Postcode": "GA-077-9067",
    "Country": "Ghana",
    "Connection": "Active"
  },
  {
    "countryCode": "BAGH",
    "bankCode": "GH",
    "branchCode": "HA5",
    "SWIFT Code": "BAGHGHA5",
    "Bank Name": "BANK OF GHANA",
    "Address": "FLOOR 3, TREASURY DEPARTMENT, 1 HIGH STREET THORPE",
    "City": "ACCRA",
    "Branch": "",
    "Postcode": "",
    "Country": "Ghana",
    "Connection": "Active"
  },
  {
    "countryCode": "BAGH",
    "bankCode": "GH",
    "branchCode": "HAC",
    "SWIFT Code": "BAGHGHAC",
    "Bank Name": "BANK OF GHANA",
    "Address": "THORPE ROAD",
    "City": "ACCRA",
    "Branch": "",
    "Postcode": "",
    "Country": "Ghana",
    "Connection": "Active"
  },
  {
    "countryCode": "BAGH",
    "bankCode": "GH",
    "branchCode": "HA2",
    "SWIFT Code": "BAGHGHA2",
    "Bank Name": "BANK OF GHANA",
    "Address": "1 THORPE ROAD, HIGH STREET",
    "City": "ACCRA",
    "Branch": "",
    "Postcode": "GA-183-1907",
    "Country": "Ghana",
    "Connection": "Active"
  },
  {
    "countryCode": "BAGH",
    "bankCode": "GH",
    "branchCode": "HA3",
    "SWIFT Code": "BAGHGHA3",
    "Bank Name": "BANK OF GHANA",
    "Address": "1 THORPE ROAD, HIGH STREET",
    "City": "ACCRA",
    "Branch": "",
    "Postcode": "GA-183-1907",
    "Country": "Ghana",
    "Connection": "Active"
  },
  {
    "countryCode": "ACCC",
    "bankCode": "GH",
    "branchCode": "HAC",
    "SWIFT Code": "ACCCGHAC",
    "Bank Name": "CALBANK PLC",
    "Address": "23 INDEPENDENCE AVENUE",
    "City": "ACCRA",
    "Branch": "",
    "Postcode": "",
    "Country": "Ghana",
    "Connection": "Active"
  },
  {
    "countryCode": "ACCC",
    "bankCode": "GH",
    "branchCode": "CBS",
    "SWIFT Code": "ACCCGHACCBS",
    "Bank Name": "CALBANK PLC",
    "Address": "",
    "City": "ACCRA",
    "Branch": "CAL BANK CUSTODY SERVICES",
    "Postcode": "",
    "Country": "Ghana",
    "Connection": "Active"
  },
  {
    "countryCode": "CSDR",
    "bankCode": "GH",
    "branchCode": "HAC",
    "SWIFT Code": "CSDRGHAC",
    "Bank Name": "CENTRAL SECURITIES DEPOSITORY (GH) LTD",
    "Address": "FLOOR 4, CEDI HOUSE, LIBERIA ROAD, ACCRA CENTRAL",
    "City": "ACCRA",
    "Branch": "",
    "Postcode": "GA-077-9067",
    "Country": "Ghana",
    "Connection": "Active"
  },
  {
    "countryCode": "CBGH",
    "bankCode": "GH",
    "branchCode": "HAC",
    "SWIFT Code": "CBGHGHAC",
    "Bank Name": "CONSOLIDATED BANK GHANA LIMITED",
    "Address": "FLOOR 1, MANET TOWER 3, PLOT 27 LIBERATION LINK, AIRPORT CITY",
    "City": "ACCRA",
    "Branch": "",
    "Postcode": "",
    "Country": "Ghana",
    "Connection": "Active"
  },
  {
    "countryCode": "CODG",
    "bankCode": "GH",
    "branchCode": "HAC",
    "SWIFT Code": "CODGGHAC",
    "Bank Name": "CONTROLLER AND ACCOUNTANT-GENERAL'S DEPARTMENT",
    "Address": "CAGD HEADQUARTERS, 91 MINISTRIES STARLETS",
    "City": "ACCRA",
    "Branch": "",
    "Postcode": "",
    "Country": "Ghana",
    "Connection": "Active"
  },
  {
    "countryCode": "ECOC",
    "bankCode": "GH",
    "branchCode": "HAC",
    "SWIFT Code": "ECOCGHAC",
    "Bank Name": "ECOBANK GHANA PLC",
    "Address": "19 SEVENTH AVENUE, RIDGE-WEST",
    "City": "ACCRA",
    "Branch": "",
    "Postcode": "",
    "Country": "Ghana",
    "Connection": "Active"
  },
  {
    "countryCode": "ECOC",
    "bankCode": "GH",
    "branchCode": "CUS",
    "SWIFT Code": "ECOCGHACCUS",
    "Bank Name": "ECOBANK GHANA PLC",
    "Address": "",
    "City": "ACCRA",
    "Branch": "",
    "Postcode": "",
    "Country": "Ghana",
    "Connection": "Active"
  },
  {
    "countryCode": "ECOC",
    "bankCode": "GH",
    "branchCode": "KSI",
    "SWIFT Code": "ECOCGHACKSI",
    "Bank Name": "ECOBANK GHANA PLC",
    "Address": "COCOBOD BUILDING, LAKE ROAD STREET ADUM",
    "City": "KUMASI",
    "Branch": "KUMASI BRANCH",
    "Postcode": "",
    "Country": "Ghana",
    "Connection": "Active"
  },
  {
    "countryCode": "ECOC",
    "bankCode": "GH",
    "branchCode": "TDI",
    "SWIFT Code": "ECOCGHACTDI",
    "Bank Name": "ECOBANK GHANA PLC",
    "Address": "ECOBANK BUILDING, 34 HARBOUR BUSINESS AREA AXIM ROAD",
    "City": "TAKORADI",
    "Branch": "TAKORADI BRANCH",
    "Postcode": "",
    "Country": "Ghana",
    "Connection": "Active"
  },
  {
    "countryCode": "ECOC",
    "bankCode": "GH",
    "branchCode": "TMA",
    "SWIFT Code": "ECOCGHACTMA",
    "Bank Name": "ECOBANK GHANA PLC",
    "Address": "MERIDIAN PLAZA, C1 PMG TEMA",
    "City": "TEMA",
    "Branch": "TEMA BRANCH",
    "Postcode": "",
    "Country": "Ghana",
    "Connection": "Active"
  },
  {
    "countryCode": "INCE",
    "bankCode": "GH",
    "branchCode": "HAC",
    "SWIFT Code": "INCEGHAC",
    "Bank Name": "FBNBANK GHANA LIMITED",
    "Address": "NO. 16 678 NEAR GOLDEN TULIP, HOTEL, LIBERA PMB ACCRA NORTH",
    "City": "ACCRA",
    "Branch": "",
    "Postcode": "",
    "Country": "Ghana",
    "Connection": "Active"
  },
  {
    "countryCode": "FBLI",
    "bankCode": "GH",
    "branchCode": "HAC",
    "SWIFT Code": "FBLIGHAC",
    "Bank Name": "FIDELITY BANK GHANA LIMITED",
    "Address": "RIDGE TOWERS, CANTONMENTS",
    "City": "ACCRA",
    "Branch": "",
    "Postcode": "",
    "Country": "Ghana",
    "Connection": "Active"
  },
  {
    "countryCode": "FAMC",
    "bankCode": "GH",
    "branchCode": "HAC",
    "SWIFT Code": "FAMCGHAC",
    "Bank Name": "FIRST ATLANTIC BANK LIMITED",
    "Address": "ATLANTIC PLACE, 1 SEVENTH AVENUE, RIDGE WEST",
    "City": "ACCRA",
    "Branch": "",
    "Postcode": "",
    "Country": "Ghana",
    "Connection": "Active"
  },
  {
    "countryCode": "FIRN",
    "bankCode": "GH",
    "branchCode": "HAC",
    "SWIFT Code": "FIRNGHAC",
    "Bank Name": "FIRST NATIONAL BANK GHANA LIMITED",
    "Address": "FLOOR 6, ACCRA FINANCIAL CENTRE, INTERS INDEPENDENCE AV LIBERIA RD",
    "City": "ACCRA",
    "Branch": "",
    "Postcode": "",
    "Country": "Ghana",
    "Connection": "Active"
  },
  {
    "countryCode": "FIRN",
    "bankCode": "GH",
    "branchCode": "CUS",
    "SWIFT Code": "FIRNGHACCUS",
    "Bank Name": "FIRST NATIONAL BANK GHANA LIMITED",
    "Address": "FLOOR 6, ACCRA FINANCIAL CENTRE, INTERS INDEPENDENCE AV LIBERIA RD",
    "City": "ACCRA",
    "Branch": "FNB GHANA SECURITIES SERVICES UNIT",
    "Postcode": "",
    "Country": "Ghana",
    "Connection": "Active"
  },
  {
    "countryCode": "GHCB",
    "bankCode": "GH",
    "branchCode": "HAC",
    "SWIFT Code": "GHCBGHAC",
    "Bank Name": "GCB BANK PLC",
    "Address": "THORPE ROAD/HIGH STREET",
    "City": "ACCRA",
    "Branch": "",
    "Postcode": "",
    "Country": "Ghana",
    "Connection": "Active"
  },
  {
    "countryCode": "GHCB",
    "bankCode": "GH",
    "branchCode": "KSI",
    "SWIFT Code": "GHCBGHACKSI",
    "Bank Name": "GCB BANK PLC",
    "Address": "",
    "City": "KUMASI",
    "Branch": "",
    "Postcode": "",
    "Country": "Ghana",
    "Connection": "Active"
  },
  {
    "countryCode": "GHCB",
    "bankCode": "GH",
    "branchCode": "TDI",
    "SWIFT Code": "GHCBGHACTDI",
    "Bank Name": "GCB BANK PLC",
    "Address": "",
    "City": "TAKORADI",
    "Branch": "",
    "Postcode": "",
    "Country": "Ghana",
    "Connection": "Active"
  },
  {
    "countryCode": "GHCB",
    "bankCode": "GH",
    "branchCode": "TMA",
    "SWIFT Code": "GHCBGHACTMA",
    "Bank Name": "GCB BANK PLC",
    "Address": "",
    "City": "TEMA",
    "Branch": "",
    "Postcode": "",
    "Country": "Ghana",
    "Connection": "Active"
  },
  {
    "countryCode": "GHEI",
    "bankCode": "GH",
    "branchCode": "HAC",
    "SWIFT Code": "GHEIGHAC",
    "Bank Name": "GHANA EXPORT-IMPORT BANK",
    "Address": "FLOOR 7, AFRICA TRADE HOUSE LIBERIA ROAD, RIDGE AMBASSADORIAL ENCLAVE",
    "City": "ACCRA",
    "Branch": "",
    "Postcode": "",
    "Country": "Ghana",
    "Connection": "Active"
  },
  {
    "countryCode": "GHRA",
    "bankCode": "GH",
    "branchCode": "HAC",
    "SWIFT Code": "GHRAGHAC",
    "Bank Name": "GHANA REVENUE AUTHORITY",
    "Address": "GHANA REVENUE AUTHORITY, OFF STARLETS 91 ROAD",
    "City": "ACCRA",
    "Branch": "",
    "Postcode": "",
    "Country": "Ghana",
    "Connection": "Active"
  },
  {
    "countryCode": "GTBI",
    "bankCode": "GH",
    "branchCode": "HAC",
    "SWIFT Code": "GTBIGHAC",
    "Bank Name": "GUARANTY TRUST BANK (GHANA) LTD",
    "Address": "AMBASSADORIAL AREA, 25 A CASTLE ROAD, RIDGE",
    "City": "ACCRA",
    "Branch": "",
    "Postcode": "",
    "Country": "Ghana",
    "Connection": "Active"
  },
  {
    "countryCode": "NIBG",
    "bankCode": "GH",
    "branchCode": "HAC",
    "SWIFT Code": "NIBGGHAC",
    "Bank Name": "NATIONAL INVESTMENT BANK",
    "Address": "AIRPORT CITY MANET TOWER B, GA-141-9644",
    "City": "ACCRA",
    "Branch": "",
    "Postcode": "",
    "Country": "Ghana",
    "Connection": "Active"
  },
  {
    "countryCode": "OMBL",
    "bankCode": "GH",
    "branchCode": "HAC",
    "SWIFT Code": "OMBLGHAC",
    "Bank Name": "OMNIBSIC BANK GHANA LIMITED",
    "Address": "ATLANTIC TOWER AIRPORT, PLOT 16 GL-126-3809",
    "City": "ACCRA",
    "Branch": "",
    "Postcode": "",
    "Country": "Ghana",
    "Connection": "Active"
  },
  {
    "countryCode": "PUBK",
    "bankCode": "GH",
    "branchCode": "HAC",
    "SWIFT Code": "PUBKGHAC",
    "Bank Name": "PRUDENTIAL BANK LIMITED",
    "Address": "HEAD OFFICE BUILDING 8 NIMA AVE, P.M.B., G.P.O. RING ROAD CENTRAL, CANTONMENTE",
    "City": "ACCRA",
    "Branch": "",
    "Postcode": "",
    "Country": "Ghana",
    "Connection": "Active"
  },
  {
    "countryCode": "HFCA",
    "bankCode": "GH",
    "branchCode": "HAC",
    "SWIFT Code": "HFCAGHAC",
    "Bank Name": "REPUBLIC BANK (GHANA) PLC",
    "Address": "35 SIXTH AVENUE, NORTH RIDGE, EBANKESE",
    "City": "ACCRA",
    "Branch": "",
    "Postcode": "",
    "Country": "Ghana",
    "Connection": "Active"
  },
  {
    "countryCode": "HFCA",
    "bankCode": "GH",
    "branchCode": "CSD",
    "SWIFT Code": "HFCAGHACCSD",
    "Bank Name": "REPUBLIC BANK (GHANA) PLC",
    "Address": "",
    "City": "ACCRA",
    "Branch": "CUSTODY SERVICES",
    "Postcode": "",
    "Country": "Ghana",
    "Connection": "Active"
  },
  {
    "countryCode": "SRCM",
    "bankCode": "GH",
    "branchCode": "HA2",
    "SWIFT Code": "SRCMGHA2",
    "Bank Name": "SARPONG CAPITAL MARKETS LIMITED",
    "Address": "2 21 ALMOND AVENUE AND BOUNDARY, ROAD",
    "City": "ACCRA",
    "Branch": "",
    "Postcode": "GA-329-3127",
    "Country": "Ghana",
    "Connection": "Active"
  },
  {
    "countryCode": "SECX",
    "bankCode": "GH",
    "branchCode": "HA2",
    "SWIFT Code": "SECXGHA2",
    "Bank Name": "SECONDSTAX LIMITED",
    "Address": "AQUATEC PLACE, 222 SWANIKER STREET",
    "City": "ACCRA",
    "Branch": "",
    "Postcode": "",
    "Country": "Ghana",
    "Connection": "Active"
  },
  {
    "countryCode": "SSNT",
    "bankCode": "GH",
    "branchCode": "HAC",
    "SWIFT Code": "SSNTGHAC",
    "Bank Name": "SOCIAL SECURITY AND NATIONAL INSURANCE TRUST",
    "Address": "PENSION HOUSE, PENSION AVENUE",
    "City": "ACCRA",
    "Branch": "",
    "Postcode": "",
    "Country": "Ghana",
    "Connection": "Active"
  },
  {
    "countryCode": "SSEB",
    "bankCode": "GH",
    "branchCode": "HAC",
    "SWIFT Code": "SSEBGHAC",
    "Bank Name": "SOCIETE GENERALE GHANA PLC",
    "Address": "2ND CRESCENT, ROYALT CASTLE ROAD,, RING ROAD CENTRAL",
    "City": "ACCRA",
    "Branch": "",
    "Postcode": "",
    "Country": "Ghana",
    "Connection": "Active"
  },
  {
    "countryCode": "SSEB",
    "bankCode": "GH",
    "branchCode": "KSI",
    "SWIFT Code": "SSEBGHACKSI",
    "Bank Name": "SOCIETE GENERALE GHANA PLC",
    "Address": "",
    "City": "KUMASI",
    "Branch": "",
    "Postcode": "",
    "Country": "Ghana",
    "Connection": "Active"
  },
  {
    "countryCode": "SSEB",
    "bankCode": "GH",
    "branchCode": "TAM",
    "SWIFT Code": "SSEBGHACTAM",
    "Bank Name": "SOCIETE GENERALE GHANA PLC",
    "Address": "",
    "City": "TAMALE",
    "Branch": "",
    "Postcode": "",
    "Country": "Ghana",
    "Connection": "Active"
  },
  {
    "countryCode": "SBIC",
    "bankCode": "GH",
    "branchCode": "HAC",
    "SWIFT Code": "SBICGHAC",
    "Bank Name": "STANBIC BANK GHANA LTD",
    "Address": "STANBIC HEIGHTS, 215 SOUTH LIBERATION LINK, AIRPORT CITY",
    "City": "ACCRA",
    "Branch": "",
    "Postcode": "GL-116-5339",
    "Country": "Ghana",
    "Connection": "Active"
  },
  {
    "countryCode": "SCBL",
    "bankCode": "GH",
    "branchCode": "HAC",
    "SWIFT Code": "SCBLGHAC",
    "Bank Name": "STANDARD CHARTERED BANK GHANA PLC",
    "Address": "STANDARD CHARTERED BANK BUILDING, 87 INDEPENDENCE AVENUE",
    "City": "ACCRA",
    "Branch": "HEAD OFFICE",
    "Postcode": "",
    "Country": "Ghana",
    "Connection": "Active"
  },
  {
    "countryCode": "SCBL",
    "bankCode": "GH",
    "branchCode": "SSU",
    "SWIFT Code": "SCBLGHACSSU",
    "Bank Name": "STANDARD CHARTERED BANK GHANA PLC",
    "Address": "",
    "City": "ACCRA",
    "Branch": "SECURITIES SERVICES UNIT",
    "Postcode": "",
    "Country": "Ghana",
    "Connection": "Active"
  },
  {
    "countryCode": "SCBL",
    "bankCode": "GH",
    "branchCode": "KSI",
    "SWIFT Code": "SCBLGHACKSI",
    "Bank Name": "STANDARD CHARTERED BANK GHANA PLC",
    "Address": "",
    "City": "KUMASI",
    "Branch": "",
    "Postcode": "",
    "Country": "Ghana",
    "Connection": "Active"
  }
]
module.exports = ghana
