const gibraltar = [
  {
    "countryCode": "BJSB",
    "bankCode": "GI",
    "branchCode": "IGX",
    "SWIFT Code": "BJSBGIGX",
    "Bank Name": "BANK J. SAFRA SARASIN (GIBRALTAR) LTD",
    "Address": "FLOOR 1, NEPTUNE HOUSE, MARINA BAY",
    "City": "GIBRALTAR",
    "Branch": "",
    "Postcode": "GX11 1AA",
    "Country": "Gibraltar",
    "Connection": "Active"
  },
  {
    "countryCode": "GVSE",
    "bankCode": "GI",
    "branchCode": "IGG",
    "SWIFT Code": "GVSEGIGG",
    "Bank Name": "ENTAIN OPERATIONS LIMITED",
    "Address": "FLOOR 2, SUITE 6 , ATLANTIC SUITES, EUROPORT AVENUE",
    "City": "GIBRALTAR",
    "Branch": "",
    "Postcode": "GX11 1AA",
    "Country": "Gibraltar",
    "Connection": "Active"
  },
  {
    "countryCode": "GIBK",
    "bankCode": "GI",
    "branchCode": "IGI",
    "SWIFT Code": "GIBKGIGI",
    "Bank Name": "GIBRALTAR INTERNATIONAL BANK LIMITED",
    "Address": "INCES HOUSE, 310 MAIN STREET",
    "City": "GIBRALTAR",
    "Branch": "",
    "Postcode": "GX11 1AA",
    "Country": "Gibraltar",
    "Connection": "Active"
  },
  {
    "countryCode": "JBNK",
    "bankCode": "GI",
    "branchCode": "IGI",
    "SWIFT Code": "JBNKGIGI",
    "Bank Name": "JUSTBANK",
    "Address": "FLOOR 1, MONTARIK BUILDING, 3 BEDLAM COURT",
    "City": "GIBRALTAR",
    "Branch": "",
    "Postcode": "GX11 1AA",
    "Country": "Gibraltar",
    "Connection": "Active"
  },
  {
    "countryCode": "MOYP",
    "bankCode": "GI",
    "branchCode": "IGI",
    "SWIFT Code": "MOYPGIGI",
    "Bank Name": "MONEYCORP BANK",
    "Address": "7/B KING'S YARD LANE",
    "City": "GIBRALTAR",
    "Branch": "",
    "Postcode": "GX11 1AA",
    "Country": "Gibraltar",
    "Connection": "Active"
  },
  {
    "countryCode": "RBOS",
    "bankCode": "GI",
    "branchCode": "IGI",
    "SWIFT Code": "RBOSGIGI",
    "Bank Name": "RBSI TRADING AS NATWEST INTERNATIONAL (GIBRALTAR)",
    "Address": "55 LINE WALL ROAD",
    "City": "GIBRALTAR",
    "Branch": "",
    "Postcode": "GX11 1AA",
    "Country": "Gibraltar",
    "Connection": "Active"
  },
  {
    "countryCode": "RBBO",
    "bankCode": "GI",
    "branchCode": "IG2",
    "SWIFT Code": "RBBOGIG2",
    "Bank Name": "RIBBON PLC",
    "Address": "2 IRISH TOWN",
    "City": "GIBRALTAR",
    "Branch": "",
    "Postcode": "GX11 1AA",
    "Country": "Gibraltar",
    "Connection": "Active"
  },
  {
    "countryCode": "HAMB",
    "bankCode": "GI",
    "branchCode": "IGI",
    "SWIFT Code": "HAMBGIGI",
    "Bank Name": "SG KLEINWORT HAMBROS BANK LIMITED GIBRALTAR BRANCH",
    "Address": "UNIT 5.02, MADISON",
    "City": "GIBRALTAR",
    "Branch": "",
    "Postcode": "GX11 1AA",
    "Country": "Gibraltar",
    "Connection": "Active"
  },
  {
    "countryCode": "TRYA",
    "bankCode": "GI",
    "branchCode": "IG2",
    "SWIFT Code": "TRYAGIG2",
    "Bank Name": "TRANSACT PAYMENTS LTD",
    "Address": "FLOOR 5, UNIT 5.1 , MADISON, MIDTOWN, QUEENSWAY, MIDTOWN, QUEENSWAY",
    "City": "GIBRALTAR",
    "Branch": "",
    "Postcode": "GX11 1AA",
    "Country": "Gibraltar",
    "Connection": "Active"
  },
  {
    "countryCode": "TNOV",
    "bankCode": "GI",
    "branchCode": "IGI",
    "SWIFT Code": "TNOVGIGI",
    "Bank Name": "TRUSTED NOVUS BANK LIMITED",
    "Address": "76 MAIN STREET",
    "City": "GIBRALTAR",
    "Branch": "",
    "Postcode": "GX11 1AA",
    "Country": "Gibraltar",
    "Connection": "Active"
  },
  {
    "countryCode": "TURC",
    "bankCode": "GI",
    "branchCode": "IGI",
    "SWIFT Code": "TURCGIGI",
    "Bank Name": "TURICUM PRIVATE BANK LIMITED",
    "Address": "TURICUM HOUSE, 315 MAIN STREET",
    "City": "GIBRALTAR",
    "Branch": "",
    "Postcode": "GX11 1AA",
    "Country": "Gibraltar",
    "Connection": "Active"
  },
  {
    "countryCode": "XAPO",
    "bankCode": "GI",
    "branchCode": "IGI",
    "SWIFT Code": "XAPOGIGI",
    "Bank Name": "XAPO BANK LIMITED",
    "Address": "1 GRAND CASEMATES SQUARE",
    "City": "GIBRALTAR",
    "Branch": "",
    "Postcode": "GX11 1AA",
    "Country": "Gibraltar",
    "Connection": "Active"
  }
]
module.exports = gibraltar
