const greece = [
  {
    "countryCode": "AEBA",
    "bankCode": "GR",
    "branchCode": "RAA",
    "SWIFT Code": "AEBAGRAA",
    "Bank Name": "AEGEAN BALTIC BANK S.A.",
    "Address": "91 MEGALOU ALEXANDROU, AND 25TH MARTIOU STR",
    "City": "MAROUSI",
    "Branch": "",
    "Postcode": "151 24",
    "Country": "Greece",
    "Connection": "Active"
  },
  {
    "countryCode": "CRBA",
    "bankCode": "GR",
    "branchCode": "RAA",
    "SWIFT Code": "CRBAGRAA",
    "Bank Name": "ALPHA BANK SA",
    "Address": "40 STADIOU STR",
    "City": "ATHENS",
    "Branch": "",
    "Postcode": "102 52",
    "Country": "Greece",
    "Connection": "Active"
  },
  {
    "countryCode": "CRBA",
    "bankCode": "GR",
    "branchCode": "I01",
    "SWIFT Code": "CRBAGRAAI01",
    "Bank Name": "ALPHA BANK SA",
    "Address": "40 STADIOU STR",
    "City": "ATHENS",
    "Branch": "TIPS",
    "Postcode": "102 52",
    "Country": "Greece",
    "Connection": "Active"
  },
  {
    "countryCode": "ACHN",
    "bankCode": "GR",
    "branchCode": "R22",
    "SWIFT Code": "ACHNGR22",
    "Bank Name": "AMBROSIA CAPITAL HELLAS SINGLE MEMBER INVESTMENT SERVICES S.A.",
    "Address": "7 ALIMOY",
    "City": "ALIMOS",
    "Branch": "",
    "Postcode": "174 55",
    "Country": "Greece",
    "Connection": "Active"
  },
  {
    "countryCode": "APSY",
    "bankCode": "GR",
    "branchCode": "RA2",
    "SWIFT Code": "APSYGRA2",
    "Bank Name": "ARGO PAYMENT SERVICES S.A PAYMENT INSTITUTION",
    "Address": "29 SOKRATOUS, FLOOR 1",
    "City": "ATHENS",
    "Branch": "",
    "Postcode": "105 52",
    "Country": "Greece",
    "Connection": "Active"
  },
  {
    "countryCode": "ATHC",
    "bankCode": "GR",
    "branchCode": "RAB",
    "SWIFT Code": "ATHCGRAB",
    "Bank Name": "ATHEXCLEAR",
    "Address": "110 ATHINON AVENUE",
    "City": "ATHENS",
    "Branch": "",
    "Postcode": "104 42",
    "Country": "Greece",
    "Connection": "Active"
  },
  {
    "countryCode": "ATTI",
    "bankCode": "GR",
    "branchCode": "RAA",
    "SWIFT Code": "ATTIGRAA",
    "Bank Name": "ATTICA BANK SA",
    "Address": "3-5 PALAION PATRON GERMANOU STR",
    "City": "ATHENS",
    "Branch": "",
    "Postcode": "105 61",
    "Country": "Greece",
    "Connection": "Active"
  },
  {
    "countryCode": "ATTI",
    "bankCode": "GR",
    "branchCode": "068",
    "SWIFT Code": "ATTIGRAA068",
    "Bank Name": "ATTICA BANK SA",
    "Address": "3-5 PALAION PATRON GERMANOU STR",
    "City": "ATHENS",
    "Branch": "",
    "Postcode": "105 61",
    "Country": "Greece",
    "Connection": "Active"
  },
  {
    "countryCode": "BOFA",
    "bankCode": "GR",
    "branchCode": "R2X",
    "SWIFT Code": "BOFAGR2X",
    "Bank Name": "BANK OF AMERICA EUROPE DESIGNATED ACTIVITY COMPANY, ATHENS BRANCH",
    "Address": "68 VASILISSIS SOFIAS",
    "City": "ATHENS",
    "Branch": "",
    "Postcode": "115 28",
    "Country": "Greece",
    "Connection": "Active"
  },
  {
    "countryCode": "BKCH",
    "bankCode": "GR",
    "branchCode": "RAA",
    "SWIFT Code": "BKCHGRAA",
    "Bank Name": "BANK OF CHINA (EUROPE) S.A. ATHENS BRANCH",
    "Address": "2 LEOF. MESOGEION",
    "City": "ATHENS",
    "Branch": "",
    "Postcode": "115 27",
    "Country": "Greece",
    "Connection": "Active"
  },
  {
    "countryCode": "BNGR",
    "bankCode": "GR",
    "branchCode": "ST2",
    "SWIFT Code": "BNGRGRAAST2",
    "Bank Name": "BANK OF GREECE",
    "Address": "",
    "City": "ATHENS",
    "Branch": "",
    "Postcode": "",
    "Country": "Greece",
    "Connection": "Active"
  },
  {
    "countryCode": "BNGR",
    "bankCode": "GR",
    "branchCode": "RAA",
    "SWIFT Code": "BNGRGRAA",
    "Bank Name": "BANK OF GREECE",
    "Address": "21 PANEPISTIMIOU AVENUE",
    "City": "ATHENS",
    "Branch": "",
    "Postcode": "102 50",
    "Country": "Greece",
    "Connection": "Active"
  },
  {
    "countryCode": "BNGR",
    "bankCode": "GR",
    "branchCode": "030",
    "SWIFT Code": "BNGRGRAA030",
    "Bank Name": "BANK OF GREECE",
    "Address": "",
    "City": "ATHENS",
    "Branch": "ACCOUNTING CONTROL SECTION",
    "Postcode": "",
    "Country": "Greece",
    "Connection": "Active"
  },
  {
    "countryCode": "BNGR",
    "bankCode": "GR",
    "branchCode": "ACO",
    "SWIFT Code": "BNGRGRAAACO",
    "Bank Name": "BANK OF GREECE",
    "Address": "",
    "City": "ATHENS",
    "Branch": "ATHENS CLEARING OFFICE",
    "Postcode": "",
    "Country": "Greece",
    "Connection": "Active"
  },
  {
    "countryCode": "BNGR",
    "bankCode": "GR",
    "branchCode": "SSS",
    "SWIFT Code": "BNGRGRAASSS",
    "Bank Name": "BANK OF GREECE",
    "Address": "",
    "City": "ATHENS",
    "Branch": "BOOK ENTRY SECURITIES MANAGEMENT SECTION",
    "Postcode": "",
    "Country": "Greece",
    "Connection": "Active"
  },
  {
    "countryCode": "BNGR",
    "bankCode": "GR",
    "branchCode": "CCB",
    "SWIFT Code": "BNGRGRAACCB",
    "Bank Name": "BANK OF GREECE",
    "Address": "",
    "City": "ATHENS",
    "Branch": "BOOK ENTRY SECURITIES MANAGEMT SECTION-CORR.CENTRAL BK MODEL SYST",
    "Postcode": "",
    "Country": "Greece",
    "Connection": "Active"
  },
  {
    "countryCode": "BNGR",
    "bankCode": "GR",
    "branchCode": "053",
    "SWIFT Code": "BNGRGRAA053",
    "Bank Name": "BANK OF GREECE",
    "Address": "",
    "City": "ATHENS",
    "Branch": "CASH PROCESSING SECTION",
    "Postcode": "",
    "Country": "Greece",
    "Connection": "Active"
  },
  {
    "countryCode": "BNGR",
    "bankCode": "GR",
    "branchCode": "059",
    "SWIFT Code": "BNGRGRAA059",
    "Bank Name": "BANK OF GREECE",
    "Address": "",
    "City": "ATHENS",
    "Branch": "DATA CONTROL SECTION",
    "Postcode": "",
    "Country": "Greece",
    "Connection": "Active"
  },
  {
    "countryCode": "BNGR",
    "bankCode": "GR",
    "branchCode": "042",
    "SWIFT Code": "BNGRGRAA042",
    "Bank Name": "BANK OF GREECE",
    "Address": "",
    "City": "ATHENS",
    "Branch": "DEPOSIT ACCOUNTS SECTION",
    "Postcode": "",
    "Country": "Greece",
    "Connection": "Active"
  },
  {
    "countryCode": "BNGR",
    "bankCode": "GR",
    "branchCode": "IOP",
    "SWIFT Code": "BNGRGRAAIOP",
    "Bank Name": "BANK OF GREECE",
    "Address": "21 PANEPISTIMIOU AVENUE",
    "City": "ATHENS",
    "Branch": "DIAS ASI6-RT AA",
    "Postcode": "102 50",
    "Country": "Greece",
    "Connection": "Active"
  },
  {
    "countryCode": "BNGR",
    "bankCode": "GR",
    "branchCode": "INS",
    "SWIFT Code": "BNGRGRAAINS",
    "Bank Name": "BANK OF GREECE",
    "Address": "21 PANEPISTIMIOU AVENUE",
    "City": "ATHENS",
    "Branch": "DIAS ASI6-RT TA",
    "Postcode": "102 50",
    "Country": "Greece",
    "Connection": "Active"
  },
  {
    "countryCode": "BNGR",
    "bankCode": "GR",
    "branchCode": "DIA",
    "SWIFT Code": "BNGRGRAADIA",
    "Bank Name": "BANK OF GREECE",
    "Address": "",
    "City": "ATHENS",
    "Branch": "DIAS-CH",
    "Postcode": "",
    "Country": "Greece",
    "Connection": "Active"
  },
  {
    "countryCode": "BNGR",
    "bankCode": "GR",
    "branchCode": "017",
    "SWIFT Code": "BNGRGRAA017",
    "Bank Name": "BANK OF GREECE",
    "Address": "",
    "City": "ATHENS",
    "Branch": "DOCUMENTARY CREDITS SECTION",
    "Postcode": "",
    "Country": "Greece",
    "Connection": "Active"
  },
  {
    "countryCode": "BNGR",
    "bankCode": "GR",
    "branchCode": "EUX",
    "SWIFT Code": "BNGRGRAAEUX",
    "Bank Name": "BANK OF GREECE",
    "Address": "",
    "City": "ATHENS",
    "Branch": "ECB ACCOUNT FOR BANK OF GREECE",
    "Postcode": "",
    "Country": "Greece",
    "Connection": "Active"
  },
  {
    "countryCode": "BNGR",
    "bankCode": "GR",
    "branchCode": "013",
    "SWIFT Code": "BNGRGRAA013",
    "Bank Name": "BANK OF GREECE",
    "Address": "",
    "City": "ATHENS",
    "Branch": "FOREIGN EXCHANGE TRANSCACTIONS SECTION",
    "Postcode": "",
    "Country": "Greece",
    "Connection": "Active"
  },
  {
    "countryCode": "BNGR",
    "bankCode": "GR",
    "branchCode": "027",
    "SWIFT Code": "BNGRGRAA027",
    "Bank Name": "BANK OF GREECE",
    "Address": "",
    "City": "ATHENS",
    "Branch": "GOVERNMENT SECURITIES CUSTODY AND MANAGEMENT SECTION",
    "Postcode": "",
    "Country": "Greece",
    "Connection": "Active"
  },
  {
    "countryCode": "BNGR",
    "bankCode": "GR",
    "branchCode": "HRM",
    "SWIFT Code": "BNGRGRAAHRM",
    "Bank Name": "BANK OF GREECE",
    "Address": "21 PANEPISTIMIOU STREET",
    "City": "ATHENS",
    "Branch": "HERMES RTGS SYSTEM",
    "Postcode": "102 50",
    "Country": "Greece",
    "Connection": "Active"
  },
  {
    "countryCode": "BNGR",
    "bankCode": "GR",
    "branchCode": "CON",
    "SWIFT Code": "BNGRGRAACON",
    "Bank Name": "BANK OF GREECE",
    "Address": "",
    "City": "ATHENS",
    "Branch": "LARGE-VALUE PAYMENTS SYSTEM MANAGEMENT SECTION",
    "Postcode": "",
    "Country": "Greece",
    "Connection": "Active"
  },
  {
    "countryCode": "BNGR",
    "bankCode": "GR",
    "branchCode": "072",
    "SWIFT Code": "BNGRGRAA072",
    "Bank Name": "BANK OF GREECE",
    "Address": "",
    "City": "ATHENS",
    "Branch": "MONETARY POLICY IMPLEMENTATION SUPPORT SECTION",
    "Postcode": "",
    "Country": "Greece",
    "Connection": "Active"
  },
  {
    "countryCode": "BNGR",
    "bankCode": "GR",
    "branchCode": "094",
    "SWIFT Code": "BNGRGRAA094",
    "Bank Name": "BANK OF GREECE",
    "Address": "",
    "City": "ATHENS",
    "Branch": "MONEY MARKETS SECTION",
    "Postcode": "",
    "Country": "Greece",
    "Connection": "Active"
  },
  {
    "countryCode": "BNGR",
    "bankCode": "GR",
    "branchCode": "PBS",
    "SWIFT Code": "BNGRGRAAPBS",
    "Bank Name": "BANK OF GREECE",
    "Address": "",
    "City": "ATHENS",
    "Branch": "PAYMENTS OF BOOK ENTRY SECURITIES SECTION",
    "Postcode": "",
    "Country": "Greece",
    "Connection": "Active"
  },
  {
    "countryCode": "BNGR",
    "bankCode": "GR",
    "branchCode": "012",
    "SWIFT Code": "BNGRGRAA012",
    "Bank Name": "BANK OF GREECE",
    "Address": "",
    "City": "ATHENS",
    "Branch": "RESERVES MANAGEMENT BACKUP SECTION",
    "Postcode": "",
    "Country": "Greece",
    "Connection": "Active"
  },
  {
    "countryCode": "BNGR",
    "bankCode": "GR",
    "branchCode": "PEN",
    "SWIFT Code": "BNGRGRAAPEN",
    "Bank Name": "BANK OF GREECE",
    "Address": "21 PANEPISTIMIOU AVENUE",
    "City": "ATHENS",
    "Branch": "SDR PENALTY MECHANISM",
    "Postcode": "102 50",
    "Country": "Greece",
    "Connection": "Active"
  },
  {
    "countryCode": "BNGR",
    "bankCode": "GR",
    "branchCode": "SCT",
    "SWIFT Code": "BNGRGRAASCT",
    "Bank Name": "BANK OF GREECE",
    "Address": "",
    "City": "ATHENS",
    "Branch": "SEPA CREDIT TRANSFER",
    "Postcode": "",
    "Country": "Greece",
    "Connection": "Active"
  },
  {},
  {
    "countryCode": "BNGR",
    "bankCode": "GR",
    "branchCode": "ECM",
    "SWIFT Code": "BNGRGRAAECM",
    "Bank Name": "BANK OF GREECE",
    "Address": "21 PANEPISTIMIOU AVENUE",
    "City": "ATHENS",
    "Branch": "TECHNICAL T2S CSDP FOR ECMS",
    "Postcode": "102 50",
    "Country": "Greece",
    "Connection": "Active"
  },
  {
    "countryCode": "BNGR",
    "bankCode": "GR",
    "branchCode": "BR8",
    "SWIFT Code": "BNGRGRAABR8",
    "Bank Name": "BANK OF GREECE",
    "Address": "",
    "City": "ATHENS",
    "Branch": "TGT2 ACCOUNT27, INDIRECT MEMBER)",
    "Postcode": "",
    "Country": "Greece",
    "Connection": "Active"
  },
  {
    "countryCode": "BNGR",
    "bankCode": "GR",
    "branchCode": "BR4",
    "SWIFT Code": "BNGRGRAABR4",
    "Bank Name": "BANK OF GREECE",
    "Address": "",
    "City": "ATHENS",
    "Branch": "TGT2 SAD.BANK (INDIRECT MEMBER)",
    "Postcode": "",
    "Country": "Greece",
    "Connection": "Active"
  },
  {
    "countryCode": "BNGR",
    "bankCode": "GR",
    "branchCode": "FXD",
    "SWIFT Code": "BNGRGRAAFXD",
    "Bank Name": "BANK OF GREECE",
    "Address": "21 PANEPISTIMIOU STREET",
    "City": "ATHENS",
    "Branch": "TREASURY OPERATIONS SUPPORT SECTION",
    "Postcode": "102 50",
    "Country": "Greece",
    "Connection": "Active"
  },
  {
    "countryCode": "BNGR",
    "bankCode": "GR",
    "branchCode": "121",
    "SWIFT Code": "BNGRGRAA121",
    "Bank Name": "BANK OF GREECE",
    "Address": "",
    "City": "THESSALONIKI",
    "Branch": "THESSALONIKI BRANCH",
    "Postcode": "",
    "Country": "Greece",
    "Connection": "Active"
  },
  {
    "countryCode": "BSTD",
    "bankCode": "GR",
    "branchCode": "R2T",
    "SWIFT Code": "BSTDGR2T",
    "Bank Name": "BLACK SEA TRADE AND DEVELOPMENT BANK",
    "Address": "1 KOMNINON STREET",
    "City": "THESSALONIKI",
    "Branch": "",
    "Postcode": "546 24",
    "Country": "Greece",
    "Connection": "Active"
  },
  {
    "countryCode": "PARB",
    "bankCode": "GR",
    "branchCode": "RAX",
    "SWIFT Code": "PARBGRAX",
    "Bank Name": "BNP PARIBAS SECURITIES SERVICES, GREECE",
    "Address": "2 LAMPSAKOU STR",
    "City": "ATHENS",
    "Branch": "",
    "Postcode": "115 28",
    "Country": "Greece",
    "Connection": "Active"
  },
  {
    "countryCode": "CITI",
    "bankCode": "GR",
    "branchCode": "RAA",
    "SWIFT Code": "CITIGRAA",
    "Bank Name": "CITIBANK EUROPE PLC GREECE BRANCH",
    "Address": "8 OTHONOS STR, SYNTAGMA SQUARE",
    "City": "ATHENS",
    "Branch": "",
    "Postcode": "105 57",
    "Country": "Greece",
    "Connection": "Active"
  },
  {
    "countryCode": "CITI",
    "bankCode": "GR",
    "branchCode": "731",
    "SWIFT Code": "CITIGRAA731",
    "Bank Name": "CITIBANK EUROPE PLC GREECE BRANCH",
    "Address": "",
    "City": "ATHENS",
    "Branch": "",
    "Postcode": "",
    "Country": "Greece",
    "Connection": "Active"
  },
  {
    "countryCode": "CITI",
    "bankCode": "GR",
    "branchCode": "SEC",
    "SWIFT Code": "CITIGRAASEC",
    "Bank Name": "CITIBANK EUROPE PLC GREECE BRANCH",
    "Address": "",
    "City": "ATHENS",
    "Branch": "RESTRICTED USE CITIBANK ATHENS TARGET 2",
    "Postcode": "",
    "Country": "Greece",
    "Connection": "Active"
  },
  {
    "countryCode": "CITI",
    "bankCode": "GR",
    "branchCode": "732",
    "SWIFT Code": "CITIGRAA732",
    "Bank Name": "CITIBANK EUROPE PLC GREECE BRANCH",
    "Address": "",
    "City": "PIRAEUS",
    "Branch": "",
    "Postcode": "",
    "Country": "Greece",
    "Connection": "Active"
  },
  {
    "countryCode": "CITI",
    "bankCode": "GR",
    "branchCode": "733",
    "SWIFT Code": "CITIGRAA733",
    "Bank Name": "CITIBANK EUROPE PLC GREECE BRANCH",
    "Address": "",
    "City": "THESSALONIKI",
    "Branch": "",
    "Postcode": "",
    "Country": "Greece",
    "Connection": "Active"
  },
  {
    "countryCode": "COES",
    "bankCode": "GR",
    "branchCode": "R22",
    "SWIFT Code": "COESGR22",
    "Bank Name": "COOPERATIVE BANK OF CENTRAL MACEDONIA LTD",
    "Address": "VASILEOS VASILEIOU, NIKOLAOU, PLASTIRA FLOOR 3",
    "City": "SERRES",
    "Branch": "",
    "Postcode": "621 22",
    "Country": "Greece",
    "Connection": "Active"
  },
  {
    "countryCode": "STXA",
    "bankCode": "GR",
    "branchCode": "RA2",
    "SWIFT Code": "STXAGRA2",
    "Bank Name": "COOPERATIVE BANK OF CHANIA",
    "Address": "28-32 ELEFTHERIOU VENIZELOU",
    "City": "CHANIA",
    "Branch": "",
    "Postcode": "731 32",
    "Country": "Greece",
    "Connection": "Active"
  },
  {
    "countryCode": "STXA",
    "bankCode": "GR",
    "branchCode": "I01",
    "SWIFT Code": "STXAGRA2I01",
    "Bank Name": "COOPERATIVE BANK OF CHANIA",
    "Address": "28-32 ELEFTHERIOU VENIZELOU",
    "City": "CHANIA",
    "Branch": "TIPS",
    "Postcode": "731 32",
    "Country": "Greece",
    "Connection": "Active"
  },
  {
    "countryCode": "STIO",
    "bankCode": "GR",
    "branchCode": "R2I",
    "SWIFT Code": "STIOGR2I",
    "Bank Name": "COOPERATIVE BANK OF EPIRUS LLC",
    "Address": "45 PATRIARCHOU IOAKIM AND KARAPANOU",
    "City": "IOANNINA",
    "Branch": "",
    "Postcode": "452 21",
    "Country": "Greece",
    "Connection": "Active"
  },
  {
    "countryCode": "STIO",
    "bankCode": "GR",
    "branchCode": "I01",
    "SWIFT Code": "STIOGR2II01",
    "Bank Name": "COOPERATIVE BANK OF EPIRUS LLC",
    "Address": "45 PATRIARCHOU IOAKIM AND KARAPANOU",
    "City": "IOANNINA",
    "Branch": "IOANNINA",
    "Postcode": "452 21",
    "Country": "Greece",
    "Connection": "Active"
  },
  {
    "countryCode": "STKA",
    "bankCode": "GR",
    "branchCode": "RAX",
    "SWIFT Code": "STKAGRAX",
    "Bank Name": "COOPERATIVE BANK OF KARDITSA COOP L.L.",
    "Address": "1 KOLOKOTRONI AND TALIADOUROU",
    "City": "KARDITSA",
    "Branch": "",
    "Postcode": "431 00",
    "Country": "Greece",
    "Connection": "Active"
  },
  {
    "countryCode": "STTK",
    "bankCode": "GR",
    "branchCode": "I01",
    "SWIFT Code": "STTKGR22I01",
    "Bank Name": "COOPERATIVE BANK OF THESSALY LL",
    "Address": "61-63 KONDYLI",
    "City": "TRIKALA",
    "Branch": "",
    "Postcode": "421 32",
    "Country": "Greece",
    "Connection": "Active"
  },
  {
    "countryCode": "STTK",
    "bankCode": "GR",
    "branchCode": "I02",
    "SWIFT Code": "STTKGR22I02",
    "Bank Name": "COOPERATIVE BANK OF THESSALY LL",
    "Address": "61-63 KONDYLI",
    "City": "TRIKALA",
    "Branch": "",
    "Postcode": "421 32",
    "Country": "Greece",
    "Connection": "Active"
  },
  {
    "countryCode": "STTK",
    "bankCode": "GR",
    "branchCode": "R22",
    "SWIFT Code": "STTKGR22",
    "Bank Name": "COOPERATIVE BANK OF THESSALY LL",
    "Address": "61-63 KONDYLI",
    "City": "TRIKALA",
    "Branch": "",
    "Postcode": "421 32",
    "Country": "Greece",
    "Connection": "Active"
  },
  {
    "countryCode": "CPEM",
    "bankCode": "GR",
    "branchCode": "RA2",
    "SWIFT Code": "CPEMGRA2",
    "Bank Name": "COSMOTE PAYMENTS - ELECTRONIC MONEY SERVICES S.A",
    "Address": "99 KIFISIAS AVENUE OTE GROUP (HTO), HEADQUARTERS, FLOOR 4A",
    "City": "ATHENS",
    "Branch": "",
    "Postcode": "151 24",
    "Country": "Greece",
    "Connection": "Active"
  },
  {
    "countryCode": "ENCH",
    "bankCode": "GR",
    "branchCode": "RAA",
    "SWIFT Code": "ENCHGRAA",
    "Bank Name": "ENEX CLEARING HOUSE SINGLE MEMBER S.A.",
    "Address": "110 ATHINON AVE",
    "City": "ATHENS",
    "Branch": "",
    "Postcode": "104 42",
    "Country": "Greece",
    "Connection": "Active"
  },
  {
    "countryCode": "ENCH",
    "bankCode": "GR",
    "branchCode": "ASI",
    "SWIFT Code": "ENCHGRAAASI",
    "Bank Name": "ENEX CLEARING HOUSE SINGLE MEMBER S.A.",
    "Address": "110 ATHINON AVE",
    "City": "ATHENS",
    "Branch": "ENEXCLEAR ANCILLARY SYSTEM",
    "Postcode": "104 42",
    "Country": "Greece",
    "Connection": "Active"
  },
  {
    "countryCode": "ERBK",
    "bankCode": "GR",
    "branchCode": "RAA",
    "SWIFT Code": "ERBKGRAA",
    "Bank Name": "EUROBANK S.A.",
    "Address": "8 OTHONOS STREET",
    "City": "ATHENS",
    "Branch": "",
    "Postcode": "105 57",
    "Country": "Greece",
    "Connection": "Active"
  },
  {
    "countryCode": "ERBK",
    "bankCode": "GR",
    "branchCode": "SEC",
    "SWIFT Code": "ERBKGRAASEC",
    "Bank Name": "EUROBANK S.A.",
    "Address": "8 OTHONOS STREET",
    "City": "ATHENS",
    "Branch": "CUSTODY FOREIGN INSTITUTIONAL INVESTORS DEPT.",
    "Postcode": "105 57",
    "Country": "Greece",
    "Connection": "Active"
  },
  {
    "countryCode": "ERBK",
    "bankCode": "GR",
    "branchCode": "TIP",
    "SWIFT Code": "ERBKGRAATIP",
    "Bank Name": "EUROBANK S.A.",
    "Address": "8 IOLKOU STR - NEA IONIA, N. IONIA COMPLEX",
    "City": "ATHENS",
    "Branch": "TIPS DCA ADMIN BRANCH",
    "Postcode": "",
    "Country": "Greece",
    "Connection": "Active"
  },
  {
    "countryCode": "EISV",
    "bankCode": "GR",
    "branchCode": "RA2",
    "SWIFT Code": "EISVGRA2",
    "Bank Name": "EUROTRUST INVESTMENT SERVICES S.A.",
    "Address": "113 SEVASTOUPOLEOS AND ERITHROU, STAVROU",
    "City": "ATHENS",
    "Branch": "",
    "Postcode": "115 26",
    "Country": "Greece",
    "Connection": "Active"
  },
  {
    "countryCode": "EPSN",
    "bankCode": "GR",
    "branchCode": "RA2",
    "SWIFT Code": "EPSNGRA2",
    "Bank Name": "EVERYPAY PAYMENT SERVICES SINGLE MEMBER SOCIETE ANONYME",
    "Address": "25-29 KARNEADOU, FLOOR 1ST",
    "City": "ATHENS",
    "Branch": "",
    "Postcode": "106 75",
    "Country": "Greece",
    "Connection": "Active"
  },
  {
    "countryCode": "GHOP",
    "bankCode": "GR",
    "branchCode": "RAA",
    "SWIFT Code": "GHOPGRAA",
    "Bank Name": "GRIVALIA HOSPITALITY S.A.",
    "Address": "59-61 L.KIFISIAS 117 KAI AG.KONSTAN",
    "City": "ATHENS",
    "Branch": "",
    "Postcode": "151 24",
    "Country": "Greece",
    "Connection": "Active"
  },
  {
    "countryCode": "HCSD",
    "bankCode": "GR",
    "branchCode": "RAA",
    "SWIFT Code": "HCSDGRAA",
    "Bank Name": "HELLENIC CENTRAL SECURITIES DEPOSITORY S.A.",
    "Address": "110 ATHINON AVE",
    "City": "ATHENS",
    "Branch": "",
    "Postcode": "104 42",
    "Country": "Greece",
    "Connection": "Active"
  },
  {
    "countryCode": "HCSD",
    "bankCode": "GR",
    "branchCode": "ASI",
    "SWIFT Code": "HCSDGRAAASI",
    "Bank Name": "HELLENIC CENTRAL SECURITIES DEPOSITORY S.A.",
    "Address": "",
    "City": "ATHENS",
    "Branch": "HELEX ANCILLARY SYSTEM",
    "Postcode": "",
    "Country": "Greece",
    "Connection": "Active"
  },
  {
    "countryCode": "HEHI",
    "bankCode": "GR",
    "branchCode": "RAA",
    "SWIFT Code": "HEHIGRAA",
    "Bank Name": "HELLENIQ ENERGY HOLDINGS A.E.",
    "Address": "8A CHIMARRAS STREET",
    "City": "MAROUSI",
    "Branch": "",
    "Postcode": "151 25",
    "Country": "Greece",
    "Connection": "Active"
  },
  {
    "countryCode": "IEPI",
    "bankCode": "GR",
    "branchCode": "RA2",
    "SWIFT Code": "IEPIGRA2",
    "Bank Name": "INTEL EXPRESS PAYMENT INSTITUTION INTELI EXPRESS",
    "Address": "57 MENANDROU STREET",
    "City": "ATHENS",
    "Branch": "",
    "Postcode": "104 37",
    "Country": "Greece",
    "Connection": "Active"
  },
  {
    "countryCode": "MFGA",
    "bankCode": "GR",
    "branchCode": "RAA",
    "SWIFT Code": "MFGAGRAA",
    "Bank Name": "MINISTRY OF ECONOMY AND FINANCE, GENERAL ACCOUNTING OFFICE",
    "Address": "37 PANEPISTIMIOU STREET",
    "City": "ATHENS",
    "Branch": "",
    "Postcode": "101 65",
    "Country": "Greece",
    "Connection": "Active"
  },
  {
    "countryCode": "MFGA",
    "bankCode": "GR",
    "branchCode": "PDI",
    "SWIFT Code": "MFGAGRAAPDI",
    "Bank Name": "MINISTRY OF ECONOMY AND FINANCE, GENERAL ACCOUNTING OFFICE",
    "Address": "",
    "City": "ATHENS",
    "Branch": "PUBLIC DEBT ISSUANCE",
    "Postcode": "",
    "Country": "Greece",
    "Connection": "Active"
  },
  {
    "countryCode": "MFGA",
    "bankCode": "GR",
    "branchCode": "PDM",
    "SWIFT Code": "MFGAGRAAPDM",
    "Bank Name": "MINISTRY OF ECONOMY AND FINANCE, GENERAL ACCOUNTING OFFICE",
    "Address": "",
    "City": "ATHENS",
    "Branch": "PUBLIC DEBT MANAGEMENT",
    "Postcode": "",
    "Country": "Greece",
    "Connection": "Active"
  },
  {
    "countryCode": "MFGA",
    "bankCode": "GR",
    "branchCode": "SPP",
    "SWIFT Code": "MFGAGRAASPP",
    "Bank Name": "MINISTRY OF ECONOMY AND FINANCE, GENERAL ACCOUNTING OFFICE",
    "Address": "",
    "City": "ATHENS",
    "Branch": "SECRETARIAT OF PUBLIC PROPERTY",
    "Postcode": "",
    "Country": "Greece",
    "Connection": "Active"
  },
  {
    "countryCode": "MOHC",
    "bankCode": "GR",
    "branchCode": "R22",
    "SWIFT Code": "MOHCGR22",
    "Bank Name": "MOTOR OIL (HELLAS) CORINTH REFINERIES S.A.",
    "Address": "12A IRODOU ATTIKOU",
    "City": "MAROUSI",
    "Branch": "",
    "Postcode": "151 24",
    "Country": "Greece",
    "Connection": "Active"
  },
  {
    "countryCode": "ETHN",
    "bankCode": "GR",
    "branchCode": "RAA",
    "SWIFT Code": "ETHNGRAA",
    "Bank Name": "NATIONAL BANK OF GREECE S.A.",
    "Address": "86 AIOLOU STREET",
    "City": "ATHENS",
    "Branch": "",
    "Postcode": "102 32",
    "Country": "Greece",
    "Connection": "Active"
  },
  {
    "countryCode": "ETHN",
    "bankCode": "GR",
    "branchCode": "CUS",
    "SWIFT Code": "ETHNGRAACUS",
    "Bank Name": "NATIONAL BANK OF GREECE S.A.",
    "Address": "328-330 EL. VENIZELOU AVENUE, EUROPA PLAZA",
    "City": "ATHENS",
    "Branch": "CUSTODIAN FOR FOREIGN INST. INVESTORS",
    "Postcode": "176 75",
    "Country": "Greece",
    "Connection": "Active"
  },
  {
    "countryCode": "ETHN",
    "bankCode": "GR",
    "branchCode": "GRI",
    "SWIFT Code": "ETHNGRAAGRI",
    "Bank Name": "NATIONAL BANK OF GREECE S.A.",
    "Address": "328-330 EL. VENIZELOU AVENUE, EUROPA PLAZA",
    "City": "ATHENS",
    "Branch": "CUSTODIAN FOR GREEK INST. INVESTORS",
    "Postcode": "176 75",
    "Country": "Greece",
    "Connection": "Active"
  },
  {
    "countryCode": "ETHN",
    "bankCode": "GR",
    "branchCode": "TIP",
    "SWIFT Code": "ETHNGRAATIP",
    "Bank Name": "NATIONAL BANK OF GREECE S.A.",
    "Address": "OMIROU STREET 23",
    "City": "ATHENS",
    "Branch": "TIPS TECHNICAL ACNT BIC",
    "Postcode": "106 72",
    "Country": "Greece",
    "Connection": "Active"
  },
  {
    "countryCode": "IBOG",
    "bankCode": "GR",
    "branchCode": "RAA",
    "SWIFT Code": "IBOGGRAA",
    "Bank Name": "OPTIMA BANK S.A. (FORMERLY INVESTMENT BANK OF GREECE S.A)",
    "Address": "32 PARADISSOU STREET, AIGIALEIAS",
    "City": "MAROUSI",
    "Branch": "",
    "Postcode": "151 25",
    "Country": "Greece",
    "Connection": "Active"
  },
  {
    "countryCode": "IBOG",
    "bankCode": "GR",
    "branchCode": "TIP",
    "SWIFT Code": "IBOGGRAATIP",
    "Bank Name": "OPTIMA BANK S.A. (FORMERLY INVESTMENT BANK OF GREECE S.A)",
    "Address": "32 PARADISSOU STREET, AIGIALEIAS",
    "City": "MAROUSI",
    "Branch": "",
    "Postcode": "151 25",
    "Country": "Greece",
    "Connection": "Active"
  },
  {
    "countryCode": "STPG",
    "bankCode": "GR",
    "branchCode": "RAA",
    "SWIFT Code": "STPGGRAA",
    "Bank Name": "PANCRETA BANK S.A.",
    "Address": "5 IKAROU AVENUE",
    "City": "HERAKLION",
    "Branch": "",
    "Postcode": "711 10",
    "Country": "Greece",
    "Connection": "Active"
  },
  {
    "countryCode": "STPG",
    "bankCode": "GR",
    "branchCode": "I01",
    "SWIFT Code": "STPGGRAAI01",
    "Bank Name": "PANCRETA BANK S.A.",
    "Address": "5 IKAROU AVENUE",
    "City": "HERAKLION",
    "Branch": "TIPS SETTLEMENT",
    "Postcode": "711 10",
    "Country": "Greece",
    "Connection": "Active"
  },
  {
    "countryCode": "PIRB",
    "bankCode": "GR",
    "branchCode": "RAA",
    "SWIFT Code": "PIRBGRAA",
    "Bank Name": "PIRAEUS BANK SA",
    "Address": "4 AMERIKIS STREET",
    "City": "ATHENS",
    "Branch": "",
    "Postcode": "105 64",
    "Country": "Greece",
    "Connection": "Active"
  },
  {
    "countryCode": "PIRB",
    "bankCode": "GR",
    "branchCode": "INS",
    "SWIFT Code": "PIRBGRAAINS",
    "Bank Name": "PIRAEUS BANK SA",
    "Address": "4 AMERIKIS STREET",
    "City": "ATHENS",
    "Branch": "INSTANT PAYMENTS",
    "Postcode": "105 64",
    "Country": "Greece",
    "Connection": "Active"
  },
  {
    "countryCode": "PIRB",
    "bankCode": "GR",
    "branchCode": "SEC",
    "SWIFT Code": "PIRBGRAASEC",
    "Bank Name": "PIRAEUS BANK SA",
    "Address": "4 AMERIKIS",
    "City": "ATHENS",
    "Branch": "SECURITIES SERVICES",
    "Postcode": "105 64",
    "Country": "Greece",
    "Connection": "Active"
  },
  {
    "countryCode": "PIRB",
    "bankCode": "GR",
    "branchCode": "CBS",
    "SWIFT Code": "PIRBGRAACBS",
    "Bank Name": "PIRAEUS BANK SA",
    "Address": "4 AMERIKIS",
    "City": "ATHENS",
    "Branch": "SECURITIES SETTLEMENT",
    "Postcode": "105 64",
    "Country": "Greece",
    "Connection": "Active"
  },
  {
    "countryCode": "PRCB",
    "bankCode": "GR",
    "branchCode": "RAA",
    "SWIFT Code": "PRCBGRAA",
    "Bank Name": "PROCREDIT BANK (BULGARIA) EAD THESSALONIKI BRANCH",
    "Address": "47 STELIOU KAZANTZIDI STREET",
    "City": "THESSALONIKI",
    "Branch": "",
    "Postcode": "555 35",
    "Country": "Greece",
    "Connection": "Active"
  },
  {
    "countryCode": "TCZB",
    "bankCode": "GR",
    "branchCode": "RAT",
    "SWIFT Code": "TCZBGRAT",
    "Bank Name": "T.C. ZIRAAT BANKASI ATHENS CENTRAL BRANCH",
    "Address": "2 ERMOU",
    "City": "ATHENS",
    "Branch": "",
    "Postcode": "105 63",
    "Country": "Greece",
    "Connection": "Active"
  },
  {
    "countryCode": "TBIB",
    "bankCode": "GR",
    "branchCode": "RAA",
    "SWIFT Code": "TBIBGRAA",
    "Bank Name": "TBI BANK EAD, BRANCH GREECE",
    "Address": "196 KIFISIAS AVENUE, TBI BANK ATHENS, FLOOR 2",
    "City": "CHALANDRI",
    "Branch": "",
    "Postcode": "152 31",
    "Country": "Greece",
    "Connection": "Active"
  },
  {
    "countryCode": "TFIM",
    "bankCode": "GR",
    "branchCode": "RAA",
    "SWIFT Code": "TFIMGRAA",
    "Bank Name": "TFI MARKETS LTD GREEK BRANCH",
    "Address": "166 A, 2 KIFISSIAS AVENUE CORNER, WITH SOFOKLEOUS OFFICE 004",
    "City": "MAROUSI",
    "Branch": "",
    "Postcode": "151 26",
    "Country": "Greece",
    "Connection": "Active"
  },
  {
    "countryCode": "PANX",
    "bankCode": "GR",
    "branchCode": "RA2",
    "SWIFT Code": "PANXGRA2",
    "Bank Name": "UNIFIEDPOST PAYMENTS SA FOREIGN BRANCH",
    "Address": "1 ELLIS ST",
    "City": "ATHENS",
    "Branch": "",
    "Postcode": "172 35",
    "Country": "Greece",
    "Connection": "Active"
  },
  {
    "countryCode": "VPAY",
    "bankCode": "GR",
    "branchCode": "RA3",
    "SWIFT Code": "VPAYGRA3",
    "Bank Name": "VIVA PAYMENT SERVICES S.A.",
    "Address": "18-20 AMAROUSIOU CHALANDRIOU",
    "City": "MAROUSI",
    "Branch": "",
    "Postcode": "151 25",
    "Country": "Greece",
    "Connection": "Active"
  },
  {
    "countryCode": "VPAY",
    "bankCode": "GR",
    "branchCode": "RAA",
    "SWIFT Code": "VPAYGRAA",
    "Bank Name": "VIVA PAYMENT SERVICES SINGLE MEMBER S.A.",
    "Address": "18-20 AMAROUSIOU - CHALANDRIOU, ARCANIA BUSINESS CENTER",
    "City": "MAROUSI",
    "Branch": "",
    "Postcode": "151 25",
    "Country": "Greece",
    "Connection": "Active"
  },
  {
    "countryCode": "VPAY",
    "bankCode": "GR",
    "branchCode": "TPS",
    "SWIFT Code": "VPAYGRAATPS",
    "Bank Name": "VIVA PAYMENT SERVICES SINGLE MEMBER S.A.",
    "Address": "18-20 AMAROUSIOU - CHALANDRIOU, ARCANIA BUSINESS CENTER",
    "City": "MAROUSI",
    "Branch": "TIPS SETTLEMENT",
    "Postcode": "151 25",
    "Country": "Greece",
    "Connection": "Active"
  },
  {
    "countryCode": "PRXB",
    "bankCode": "GR",
    "branchCode": "RAA",
    "SWIFT Code": "PRXBGRAA",
    "Bank Name": "VIVABANK SINGLE MEMBER BANKING S.A.",
    "Address": "18-20 AMAROUSIOU-CHALANDRIOU AVE",
    "City": "CHALANDRI",
    "Branch": "",
    "Postcode": "151 25",
    "Country": "Greece",
    "Connection": "Active"
  },
  {
    "countryCode": "PRXB",
    "bankCode": "GR",
    "branchCode": "TPT",
    "SWIFT Code": "PRXBGRAATPT",
    "Bank Name": "VIVABANK SINGLE MEMBER BANKING S.A.",
    "Address": "18-20 AMAROUSIOU-CHALANDRIOU AVE",
    "City": "MAROUSI",
    "Branch": "",
    "Postcode": "151 25",
    "Country": "Greece",
    "Connection": "Active"
  },
  {
    "countryCode": "PRXB",
    "bankCode": "GR",
    "branchCode": "TPS",
    "SWIFT Code": "PRXBGRAATPS",
    "Bank Name": "VIVABANK SINGLE MEMBER BANKING S.A.",
    "Address": "18-20 AMAROUSIOU-CHALANDRIOU AVE",
    "City": "MAROUSI",
    "Branch": "TIPS SETTLEMENT",
    "Postcode": "151 25",
    "Country": "Greece",
    "Connection": "Active"
  }
]
module.exports = greece
