const guernsey = [
  {
    "countryCode": "ARMK",
    "bankCode": "GG",
    "branchCode": "GSP",
    "SWIFT Code": "ARMKGGSP",
    "Bank Name": "ALTERNATIVE RISK MANAGEMENT LIMITED",
    "Address": "MILL COURT, 5 LA CHAROTERIE",
    "City": "ST. PETER PORT",
    "Branch": "",
    "Postcode": "GY1 1EJ",
    "Country": "Guernsey",
    "Connection": "Active"
  },
  {
    "countryCode": "APAX",
    "bankCode": "GG",
    "branchCode": "GSP",
    "SWIFT Code": "APAXGGSP",
    "Bank Name": "APAX PARTNERS GUERNSEY LIMITED",
    "Address": "FLOOR 3, ROYAL BANK PLACE, 1 GLATEGNY ESPLANADE",
    "City": "ST. PETER PORT",
    "Branch": "",
    "Postcode": "GY1 2HJ",
    "Country": "Guernsey",
    "Connection": "Active"
  },
  {
    "countryCode": "IPES",
    "bankCode": "GG",
    "branchCode": "GSP",
    "SWIFT Code": "IPESGGSP",
    "Bank Name": "APEX FUND AND CORPORATE SERVICES (GUERNSEY) LIMITED",
    "Address": "1 ROYAL PLAZA, ROYAL AVENUE",
    "City": "ST. PETER PORT",
    "Branch": "",
    "Postcode": "GY1 2HL",
    "Country": "Guernsey",
    "Connection": "Active"
  },
  {
    "countryCode": "SARA",
    "bankCode": "GG",
    "branchCode": "GSP",
    "SWIFT Code": "SARAGGSP",
    "Bank Name": "BANK J. SAFRA SARASIN LTD, GUERNSEY BRANCH",
    "Address": "FRANCES HOUSE, 1 SIR WILLIAM PLACE",
    "City": "ST. PETER PORT",
    "Branch": "",
    "Postcode": "GY1 3UY",
    "Country": "Guernsey",
    "Connection": "Active"
  },
  {
    "countryCode": "BAER",
    "bankCode": "GG",
    "branchCode": "GSP",
    "SWIFT Code": "BAERGGSP",
    "Bank Name": "BANK JULIUS BAER AND CO LTD (GUERNSEY BRANCH)",
    "Address": "THE PLAZA, 1 ADMIRAL PARK, ELIZABETH AVENUE",
    "City": "ST. PETER PORT",
    "Branch": "",
    "Postcode": "GY1 4BS",
    "Country": "Guernsey",
    "Connection": "Active"
  },
  {
    "countryCode": "BNTB",
    "bankCode": "GG",
    "branchCode": "GSX",
    "SWIFT Code": "BNTBGGSX",
    "Bank Name": "BUTTERFIELD BANK (GUERNSEY) LIMITED",
    "Address": "REGENCY COURT, GLATEGNY ESPLANADE",
    "City": "ST. PETER PORT",
    "Branch": "",
    "Postcode": "GY1 3AP",
    "Country": "Guernsey",
    "Connection": "Active"
  },
  {
    "countryCode": "CGWI",
    "bankCode": "GG",
    "branchCode": "GSP",
    "SWIFT Code": "CGWIGGSP",
    "Bank Name": "CANACCORD GENUITY WEALTH (INTERNATIONAL) LIMITED",
    "Address": "TRAFALGAR COURT, ADMIRAL PARK",
    "City": "ST. PETER PORT",
    "Branch": "",
    "Postcode": "GY1 2JA",
    "Country": "Guernsey",
    "Connection": "Active"
  },
  {
    "countryCode": "CNFA",
    "bankCode": "GG",
    "branchCode": "GS2",
    "SWIFT Code": "CNFAGGS2",
    "Bank Name": "CONFIANCE LIMITED",
    "Address": "SARNIA HOUSE, LE TRUCHOT",
    "City": "ST. PETER PORT",
    "Branch": "",
    "Postcode": "GY1 1GR",
    "Country": "Guernsey",
    "Connection": "Active"
  },
  {
    "countryCode": "CRES",
    "bankCode": "GG",
    "branchCode": "GSP",
    "SWIFT Code": "CRESGGSP",
    "Bank Name": "CREDIT SUISSE AG, GUERNSEY BRANCH",
    "Address": "SOUTH ESPLANADE",
    "City": "ST. PETER PORT",
    "Branch": "",
    "Postcode": "GY1 3YJ",
    "Country": "Guernsey",
    "Connection": "Active"
  },
  {
    "countryCode": "CSDC",
    "bankCode": "GG",
    "branchCode": "GSX",
    "SWIFT Code": "CSDCGGSX",
    "Bank Name": "CREDIT SUISSE DEPOSIT CENTRE",
    "Address": "HELVETIA COURT, SOUTH ESPLANADE",
    "City": "ST. PETER PORT",
    "Branch": "",
    "Postcode": "GY1 3YJ",
    "Country": "Guernsey",
    "Connection": "Active"
  },
  {
    "countryCode": "EFGB",
    "bankCode": "GG",
    "branchCode": "GSP",
    "SWIFT Code": "EFGBGGSP",
    "Bank Name": "EFG BANK AG, GUERNSEY BRANCH",
    "Address": "SUITE 3, THE GRANGE, 2 GRANGE PLACE",
    "City": "ST. PETER PORT",
    "Branch": "",
    "Postcode": "GY1 2QA",
    "Country": "Guernsey",
    "Connection": "Active"
  },
  {
    "countryCode": "FIRN",
    "bankCode": "GG",
    "branchCode": "GSP",
    "SWIFT Code": "FIRNGGSP",
    "Bank Name": "FNB CHANNEL ISLANDS",
    "Address": "LA PLAIDERIE HOUSE, 1 LA PLAIDERIE",
    "City": "ST. PETER PORT",
    "Branch": "LA PLAIDERIE",
    "Postcode": "GY1 4NL",
    "Country": "Guernsey",
    "Connection": "Active"
  },
  {
    "countryCode": "BLIC",
    "bankCode": "GG",
    "branchCode": "GSX",
    "SWIFT Code": "BLICGGSX",
    "Bank Name": "HSBC PRIVATE BANK (SUISSE) SA, GUERNSEY BRANCH",
    "Address": "ARNOLD HOUSE, ST JULIAN'S AVENUE",
    "City": "ST. PETER PORT",
    "Branch": "",
    "Postcode": "GY1 3NF",
    "Country": "Guernsey",
    "Connection": "Active"
  },
  {
    "countryCode": "GMGU",
    "bankCode": "GG",
    "branchCode": "GSP",
    "SWIFT Code": "GMGUGGSP",
    "Bank Name": "INVESTEC BANK (CHANNEL ISLANDS) LIMITED",
    "Address": "GLATEGNY COURT, GLATEGNY ESPLANADE",
    "City": "ST. PETER PORT",
    "Branch": "",
    "Postcode": "GY1 3LP",
    "Country": "Guernsey",
    "Connection": "Active"
  },
  {
    "countryCode": "AFAL",
    "bankCode": "GG",
    "branchCode": "GSP",
    "SWIFT Code": "AFALGGSP",
    "Bank Name": "IQ EQ FUND SERVICES (GUERNSEY) LIMITED",
    "Address": "FLOOR GROUND, CAMBRIDGE HOUSE, LE TRUCHOT",
    "City": "ST. PETER PORT",
    "Branch": "",
    "Postcode": "GY1 4BF",
    "Country": "Guernsey",
    "Connection": "Active"
  },
  {
    "countryCode": "EFGF",
    "bankCode": "GG",
    "branchCode": "GSP",
    "SWIFT Code": "EFGFGGSP",
    "Bank Name": "LEONTEQ SECURITIES AG, GUERNSEY BRANCH",
    "Address": "L1, HIRZEL COURT, BLOCK F, HIRZEL STREET",
    "City": "ST. PETER PORT",
    "Branch": "",
    "Postcode": "GY1 4NH",
    "Country": "Guernsey",
    "Connection": "Active"
  },
  {
    "countryCode": "NETM",
    "bankCode": "GG",
    "branchCode": "GS2",
    "SWIFT Code": "NETMGGS2",
    "Bank Name": "NERINE TRUST COMPANY LIMITED",
    "Address": "SARNIA HOUSE, LE TRUCHOT",
    "City": "ST. PETER PORT",
    "Branch": "",
    "Postcode": "GY1 1GR",
    "Country": "Guernsey",
    "Connection": "Active"
  },
  {
    "countryCode": "NREI",
    "bankCode": "GG",
    "branchCode": "GSP",
    "SWIFT Code": "NREIGGSP",
    "Bank Name": "NOMURA REINSURANCE 1 IC LIMITED",
    "Address": "LEVEL 5, MILL COURT, LA CHAROTERIE",
    "City": "ST. PETER PORT",
    "Branch": "",
    "Postcode": "GY1 1EJ",
    "Country": "Guernsey",
    "Connection": "Active"
  },
  {
    "countryCode": "BBCO",
    "bankCode": "GG",
    "branchCode": "GSP",
    "SWIFT Code": "BBCOGGSP",
    "Bank Name": "NORTHERN TRUST (GUERNSEY) LIMITED",
    "Address": "TRAFALGAR COURT, LES BANQUES",
    "City": "ST. PETER PORT",
    "Branch": "",
    "Postcode": "GY1 3DA",
    "Country": "Guernsey",
    "Connection": "Active"
  },
  {
    "countryCode": "OAKT",
    "bankCode": "GG",
    "branchCode": "GSP",
    "SWIFT Code": "OAKTGGSP",
    "Bank Name": "OAK TRUST (GUERNSEY) LIMITED",
    "Address": "OAK HOUSE, HIRZEL STREET",
    "City": "ST. PETER PORT",
    "Branch": "",
    "Postcode": "GY1 2NP",
    "Country": "Guernsey",
    "Connection": "Active"
  },
  {
    "countryCode": "PXIS",
    "bankCode": "GG",
    "branchCode": "GSP",
    "SWIFT Code": "PXISGGSP",
    "Bank Name": "PRAXISIFM TRUST LIMITED",
    "Address": "SARNIA HOUSE, 1 LE TRUCHOT",
    "City": "ST. PETER PORT",
    "Branch": "",
    "Postcode": "GY1 4NA",
    "Country": "Guernsey",
    "Connection": "Active"
  },
  {
    "countryCode": "PXIS",
    "bankCode": "GG",
    "branchCode": "GSX",
    "SWIFT Code": "PXISGGSX",
    "Bank Name": "PRAXISIFM TRUST LIMITED",
    "Address": "SARNIA HOUSE, LE TRUCHOT",
    "City": "ST. PETER PORT",
    "Branch": "",
    "Postcode": "GY1 1GR",
    "Country": "Guernsey",
    "Connection": "Active"
  },
  {
    "countryCode": "PRDG",
    "bankCode": "GG",
    "branchCode": "GSP",
    "SWIFT Code": "PRDGGGSP",
    "Bank Name": "PRICEWATERHOUSECOOPERS (MIDDLE EAST GROUP) LIMITED",
    "Address": "ROYAL BANK PLACE, 1 GLATEGNY ESPLANADE",
    "City": "ST. PETER PORT",
    "Branch": "",
    "Postcode": "GY1 4ND",
    "Country": "Guernsey",
    "Connection": "Active"
  },
  {
    "countryCode": "RAVE",
    "bankCode": "GG",
    "branchCode": "GSP",
    "SWIFT Code": "RAVEGGSP",
    "Bank Name": "RAVENSCROFT (CI) LIMITED",
    "Address": "20 NEW STREET",
    "City": "ST. PETER PORT",
    "Branch": "",
    "Postcode": "GY1 4JG",
    "Country": "Guernsey",
    "Connection": "Active"
  },
  {
    "countryCode": "RBOS",
    "bankCode": "GG",
    "branchCode": "GSP",
    "SWIFT Code": "RBOSGGSP",
    "Bank Name": "RBS INTERNATIONAL (GUERNSEY)",
    "Address": "ROYAL BANK HOUSE, 1 GLATEGNY ESPLANADE",
    "City": "ST. PETER PORT",
    "Branch": "",
    "Postcode": "GY1 4BQ",
    "Country": "Guernsey",
    "Connection": "Active"
  },
  {
    "countryCode": "RBOS",
    "bankCode": "GG",
    "branchCode": "GSX",
    "SWIFT Code": "RBOSGGSX",
    "Bank Name": "RBSI TRADING AS NATWEST INTERNATIONAL (GUERNSEY)",
    "Address": "35 HIGH STREET",
    "City": "ST. PETER PORT",
    "Branch": "",
    "Postcode": "GY1 4BE",
    "Country": "Guernsey",
    "Connection": "Active"
  },
  {},
  {
    "countryCode": "ROSW",
    "bankCode": "GG",
    "branchCode": "GSP",
    "SWIFT Code": "ROSWGGSP",
    "Bank Name": "ROTHSCHILD AND CO BANK INTERNATIONAL LIMITED (WEALTH MANAGEMENT)",
    "Address": "ST JULIAN'S COURT, ST. JULIAN'S AVE",
    "City": "ST. PETER PORT",
    "Branch": "",
    "Postcode": "GY1 3BP",
    "Country": "Guernsey",
    "Connection": "Active"
  },
  {},
  {
    "countryCode": "ROYC",
    "bankCode": "GG",
    "branchCode": "OFM",
    "SWIFT Code": "ROYCGGSPOFM",
    "Bank Name": "ROYAL BANK OF CANADA (CHANNEL ISLANDS) LIMITED, GUERNSEY BRANCH",
    "Address": "",
    "City": "ST. PETER PORT",
    "Branch": "OFM",
    "Postcode": "",
    "Country": "Guernsey",
    "Connection": "Active"
  },
  {
    "countryCode": "SCHD",
    "bankCode": "GG",
    "branchCode": "GSP",
    "SWIFT Code": "SCHDGGSP",
    "Bank Name": "SCHRODERS (C.I.) LIMITED",
    "Address": "REGENCY COURT, GLATEGNY ESPLANADE",
    "City": "ST. PETER PORT",
    "Branch": "",
    "Postcode": "GY1 3UF",
    "Country": "Guernsey",
    "Connection": "Active"
  },
  {
    "countryCode": "SEIQ",
    "bankCode": "GG",
    "branchCode": "G26",
    "SWIFT Code": "SEIQGGSPG26",
    "Bank Name": "SEI INVESTMENTS-GUERNSEY LIMITED",
    "Address": "LES RUETTES BRYES",
    "City": "ST. PETER PORT",
    "Branch": "",
    "Postcode": "GY1 1EW",
    "Country": "Guernsey",
    "Connection": "Active"
  },
  {
    "countryCode": "SEIQ",
    "bankCode": "GG",
    "branchCode": "S53",
    "SWIFT Code": "SEIQGGSPS53",
    "Bank Name": "SEI INVESTMENTS-GUERNSEY LIMITED",
    "Address": "FLOOR 1 AND 2, ELIZABETH HOUSE, LES RUETTES BRYES",
    "City": "ST. PETER PORT",
    "Branch": "",
    "Postcode": "GY1 1EW",
    "Country": "Guernsey",
    "Connection": "Active"
  },
  {
    "countryCode": "SEIQ",
    "bankCode": "GG",
    "branchCode": "S29",
    "SWIFT Code": "SEIQGGSPS29",
    "Bank Name": "SEI INVESTMENTS-GUERNSEY LIMITED",
    "Address": "FLOOR 1 AND 2, ELIZABETH HOUSE, LES RUETTES BRYES",
    "City": "ST. PETER PORT",
    "Branch": "",
    "Postcode": "GY1 1EW",
    "Country": "Guernsey",
    "Connection": "Active"
  },
  {
    "countryCode": "SEIQ",
    "bankCode": "GG",
    "branchCode": "S27",
    "SWIFT Code": "SEIQGGSPS27",
    "Bank Name": "SEI INVESTMENTS-GUERNSEY LIMITED",
    "Address": "FLOOR 1 AND 2, ELIZABETH HOUSE, LES RUETTES BRYES",
    "City": "ST. PETER PORT",
    "Branch": "",
    "Postcode": "GY1 1EW",
    "Country": "Guernsey",
    "Connection": "Active"
  },
  {
    "countryCode": "SEIQ",
    "bankCode": "GG",
    "branchCode": "S25",
    "SWIFT Code": "SEIQGGSPS25",
    "Bank Name": "SEI INVESTMENTS-GUERNSEY LIMITED",
    "Address": "FLOOR 1 AND 2, ELIZABETH HOUSE, LES RUETTES BRYES",
    "City": "ST. PETER PORT",
    "Branch": "",
    "Postcode": "GY1 1EW",
    "Country": "Guernsey",
    "Connection": "Active"
  },
  {
    "countryCode": "SEIQ",
    "bankCode": "GG",
    "branchCode": "S23",
    "SWIFT Code": "SEIQGGSPS23",
    "Bank Name": "SEI INVESTMENTS-GUERNSEY LIMITED",
    "Address": "FLOOR 1 AND 2, ELIZABETH HOUSE, LES RUETTES BRYES",
    "City": "ST. PETER PORT",
    "Branch": "",
    "Postcode": "GY1 1EW",
    "Country": "Guernsey",
    "Connection": "Active"
  },
  {
    "countryCode": "SEIQ",
    "bankCode": "GG",
    "branchCode": "G92",
    "SWIFT Code": "SEIQGGSPG92",
    "Bank Name": "SEI INVESTMENTS-GUERNSEY LIMITED",
    "Address": "FLOOR 1 AND 2, ELIZABETH HOUSE, LES RUETTES BRYES",
    "City": "ST. PETER PORT",
    "Branch": "",
    "Postcode": "GY1 1EW",
    "Country": "Guernsey",
    "Connection": "Active"
  },
  {
    "countryCode": "SEIQ",
    "bankCode": "GG",
    "branchCode": "G52",
    "SWIFT Code": "SEIQGGSPG52",
    "Bank Name": "SEI INVESTMENTS-GUERNSEY LIMITED",
    "Address": "FLOOR 1 AND 2, ELIZABETH HOUSE, LES RUETTES BRYES",
    "City": "ST. PETER PORT",
    "Branch": "",
    "Postcode": "GY1 1EW",
    "Country": "Guernsey",
    "Connection": "Active"
  },
  {
    "countryCode": "SEIQ",
    "bankCode": "GG",
    "branchCode": "G89",
    "SWIFT Code": "SEIQGGSPG89",
    "Bank Name": "SEI INVESTMENTS-GUERNSEY LIMITED",
    "Address": "FLOOR 1 AND 2, ELIZABETH HOUSE, LES RUETTES BRYES",
    "City": "ST. PETER PORT",
    "Branch": "",
    "Postcode": "GY1 1EW",
    "Country": "Guernsey",
    "Connection": "Active"
  },
  {
    "countryCode": "SEIQ",
    "bankCode": "GG",
    "branchCode": "G66",
    "SWIFT Code": "SEIQGGSPG66",
    "Bank Name": "SEI INVESTMENTS-GUERNSEY LIMITED",
    "Address": "FLOOR 1 AND 2, ELIZABETH HOUSE, LES RUETTES BRYES",
    "City": "ST. PETER PORT",
    "Branch": "",
    "Postcode": "GY1 1EW",
    "Country": "Guernsey",
    "Connection": "Active"
  },
  {},
  {
    "countryCode": "HAMB",
    "bankCode": "GG",
    "branchCode": "GSP",
    "SWIFT Code": "HAMBGGSP",
    "Bank Name": "SG KLEINWORT HAMBROS BANK LIMITED - GUERNSEY BRANCH",
    "Address": "HAMBRO HOUSE, ST. JULIANS AVENUE",
    "City": "ST. PETER PORT",
    "Branch": "",
    "Postcode": "GY1 3AE",
    "Country": "Guernsey",
    "Connection": "Active"
  }
]
module.exports = guernsey
