const honduras = [
  {
    "countryCode": "ATTD",
    "bankCode": "HN",
    "branchCode": "NTE",
    "SWIFT Code": "ATTDHNTE",
    "Bank Name": "BANCO ATLANTIDA",
    "Address": "PLAZA BANCATLAN, BOULEVARD CENTROAMERICA",
    "City": "TEGUCIGALPA",
    "Branch": "OFICINA PRINCIPAL",
    "Postcode": "11101",
    "Country": "Honduras",
    "Connection": "Active"
  },
  {
    "countryCode": "AZTK",
    "bankCode": "HN",
    "branchCode": "NTE",
    "SWIFT Code": "AZTKHNTE",
    "Bank Name": "BANCO AZTECA DE HONDURAS, SA",
    "Address": "EDIFICIO CORPORATIVO, FLOOR 2, BOULEVARD 14 DE NOVIEMBRE, COLONIA MIRAMONTES",
    "City": "TEGUCIGALPA",
    "Branch": "",
    "Postcode": "11101",
    "Country": "Honduras",
    "Connection": "Active"
  },
  {
    "countryCode": "BCEH",
    "bankCode": "HN",
    "branchCode": "NTE",
    "SWIFT Code": "BCEHHNTE",
    "Bank Name": "BANCO CENTRAL DE HONDURAS",
    "Address": "CENTRO CIVICO GUBERNAMENTAL, BOULEVARD FUERZAS ARMADAS",
    "City": "TEGUCIGALPA",
    "Branch": "",
    "Postcode": "11101",
    "Country": "Honduras",
    "Connection": "Active"
  },
  {
    "countryCode": "BCEH",
    "bankCode": "HN",
    "branchCode": "NTT",
    "SWIFT Code": "BCEHHNTT",
    "Bank Name": "BANCO CENTRAL DE HONDURAS BANCO CENTRAL",
    "Address": "3165, BARRIO EL CENTRO",
    "City": "TEGUCIGALPA",
    "Branch": "",
    "Postcode": "11101",
    "Country": "Honduras",
    "Connection": "Active"
  },
  {
    "countryCode": "BCIE",
    "bankCode": "HN",
    "branchCode": "NTE",
    "SWIFT Code": "BCIEHNTE",
    "Bank Name": "BANCO CENTROAMERICANO DE INTEGRACION ECONOMICA",
    "Address": "EDIFICIO SEDE, BULEVAR SUYAPA",
    "City": "TEGUCIGALPA",
    "Branch": "",
    "Postcode": "11101",
    "Country": "Honduras",
    "Connection": "Active"
  },
  {
    "countryCode": "BGAH",
    "bankCode": "HN",
    "branchCode": "NTE",
    "SWIFT Code": "BGAHHNTE",
    "Bank Name": "BANCO DAVIVIENDA HONDURAS, S.A.",
    "Address": "FLOOR 5 INTERSECCION BOULEVARD, SUYAPA Y CENTROAMERICA",
    "City": "TEGUCIGALPA",
    "Branch": "OFICINA PRINCIPAL GERENCIA",
    "Postcode": "11101",
    "Country": "Honduras",
    "Connection": "Active"
  },
  {
    "countryCode": "BMIL",
    "bankCode": "HN",
    "branchCode": "NTE",
    "SWIFT Code": "BMILHNTE",
    "Bank Name": "BANCO DE AMERICA CENTRAL HONDURAS, S.A.(BAC BAMER)",
    "Address": "BOULLEVARD SUYAPA FRENTE, A,EMISORAS UNIDAS",
    "City": "TEGUCIGALPA",
    "Branch": "",
    "Postcode": "11101",
    "Country": "Honduras",
    "Connection": "Active"
  },
  {
    "countryCode": "PRCB",
    "bankCode": "HN",
    "branchCode": "NTE",
    "SWIFT Code": "PRCBHNTE",
    "Bank Name": "BANCO DE DESARROLLO RURAL HONDURAS, S.A.",
    "Address": "CENTRO COMERCIAL NOVACENTRO, FLOOR, 3-4 BULEVAR MORAZAN",
    "City": "TEGUCIGALPA",
    "Branch": "",
    "Postcode": "11101",
    "Country": "Honduras",
    "Connection": "Active"
  },
  {
    "countryCode": "HONA",
    "bankCode": "HN",
    "branchCode": "NT2",
    "SWIFT Code": "HONAHNT2",
    "Bank Name": "BANCO DE HONDURAS, S.A.",
    "Address": "BULEVAR SUYAPA",
    "City": "TEGUCIGALPA",
    "Branch": "",
    "Postcode": "11101",
    "Country": "Honduras",
    "Connection": "Active"
  },
  {
    "countryCode": "TSBO",
    "bankCode": "HN",
    "branchCode": "NTA",
    "SWIFT Code": "TSBOHNTA",
    "Bank Name": "BANCO DE LOS TRABAJADORES",
    "Address": "3A AVENIDA, CALLE COMAYAGUELA 13",
    "City": "TEGUCIGALPA",
    "Branch": "",
    "Postcode": "11101",
    "Country": "Honduras",
    "Connection": "Active"
  },
  {
    "countryCode": "BOCC",
    "bankCode": "HN",
    "branchCode": "NTE",
    "SWIFT Code": "BOCCHNTE",
    "Bank Name": "BANCO DE OCCIDENTE S.A.",
    "Address": "BLVD DEL SUR CONTIGUO A HOTEL, CAMINO REAL COLONIA LAS MESETAS",
    "City": "SAN PEDRO SULA",
    "Branch": "",
    "Postcode": "21104",
    "Country": "Honduras",
    "Connection": "Active"
  },
  {
    "countryCode": "BOCC",
    "bankCode": "HN",
    "branchCode": "SPS",
    "SWIFT Code": "BOCCHNTESPS",
    "Bank Name": "BANCO DE OCCIDENTE S.A.",
    "Address": "EDIFICIO PRINCIPAL, BLVD. DEL SUR, MONUMENTO A LA MADRE",
    "City": "SAN PEDRO SULA",
    "Branch": "SAN PEDRO SULA",
    "Postcode": "21104",
    "Country": "Honduras",
    "Connection": "Active"
  },
  {
    "countryCode": "BOCC",
    "bankCode": "HN",
    "branchCode": "SRC",
    "SWIFT Code": "BOCCHNTESRC",
    "Bank Name": "BANCO DE OCCIDENTE S.A.",
    "Address": "EDIFICIO PRINCIPAL PRIMERA AVENIDA, CALLE CENTENARIO, SUR ESTE, ESQUINA OPUESTA PARQUE",
    "City": "SANTA ROSA DE COPAN",
    "Branch": "SANTA ROSA DE COPAN",
    "Postcode": "41101",
    "Country": "Honduras",
    "Connection": "Active"
  },
  {
    "countryCode": "BOCC",
    "bankCode": "HN",
    "branchCode": "TGU",
    "SWIFT Code": "BOCCHNTETGU",
    "Bank Name": "BANCO DE OCCIDENTE S.A.",
    "Address": "EDIFICIO PRINCIPAL, COLONIA LAS COLINAS",
    "City": "TEGUCIGALPA",
    "Branch": "TEGUCIGALPA",
    "Postcode": "11101",
    "Country": "Honduras",
    "Connection": "Active"
  },
  {
    "countryCode": "PISA",
    "bankCode": "HN",
    "branchCode": "NTE",
    "SWIFT Code": "PISAHNTE",
    "Bank Name": "BANCO DEL PAIS,S.A.",
    "Address": "EDIF. TORRE DEL PAIS, AV BLVD. JOSE ANTONIO PERAZA 16-17, NOR-OESTE URBANO EL PLAYON",
    "City": "SAN PEDRO SULA",
    "Branch": "",
    "Postcode": "21102",
    "Country": "Honduras",
    "Connection": "Active"
  },
  {
    "countryCode": "CABF",
    "bankCode": "HN",
    "branchCode": "NTE",
    "SWIFT Code": "CABFHNTE",
    "Bank Name": "BANCO FINANCIERA CENTROAMERICANA S.A. FICENSA",
    "Address": "EDIFICIO FICENSA, BOULEVARD MORAZAN",
    "City": "TEGUCIGALPA",
    "Branch": "",
    "Postcode": "11101",
    "Country": "Honduras",
    "Connection": "Active"
  },
  {
    "countryCode": "FCOH",
    "bankCode": "HN",
    "branchCode": "NTE",
    "SWIFT Code": "FCOHHNTE",
    "Bank Name": "BANCO FINANCIERA COMERCIAL HONDURENA S.A. (BANCO FICOHSA)",
    "Address": "PLAZA VICTORIA, BOULEVARD FRANCIA, COLONIA LAS COLINAS",
    "City": "TEGUCIGALPA",
    "Branch": "",
    "Postcode": "11101",
    "Country": "Honduras",
    "Connection": "Active"
  },
  {
    "countryCode": "BHCA",
    "bankCode": "HN",
    "branchCode": "NTH",
    "SWIFT Code": "BHCAHNTH",
    "Bank Name": "BANCO HONDURENO DEL CAFE, S.A.",
    "Address": "PLAZA BANHCAFE, AVE. REPUBLICA DE COSTA RICA 1, COLONIA LOMAS DEL MAYAB",
    "City": "TEGUCIGALPA",
    "Branch": "",
    "Postcode": "11101",
    "Country": "Honduras",
    "Connection": "Active"
  },
  {
    "countryCode": "BCCE",
    "bankCode": "HN",
    "branchCode": "NTE",
    "SWIFT Code": "BCCEHNTE",
    "Bank Name": "BANCO LAFISE (HONDURAS), S.A.",
    "Address": "CENTRO CORPORATIVO TORRE LAFISE, AVENIDA LOS PROCERES, COLONIA SAN CARLOS",
    "City": "TEGUCIGALPA",
    "Branch": "",
    "Postcode": "11101",
    "Country": "Honduras",
    "Connection": "Active"
  },
  {
    "countryCode": "BPRH",
    "bankCode": "HN",
    "branchCode": "NTE",
    "SWIFT Code": "BPRHHNTE",
    "Bank Name": "BANCO PROMERICA, S.A.",
    "Address": "EDIFICIO PALIC, AVE. REPUBLICA DE CHILE 840, COLONIA PAMIRA",
    "City": "TEGUCIGALPA",
    "Branch": "",
    "Postcode": "11101",
    "Country": "Honduras",
    "Connection": "Active"
  },
  {
    "countryCode": "BCVO",
    "bankCode": "HN",
    "branchCode": "NT2",
    "SWIFT Code": "BCVOHNT2",
    "Bank Name": "BOLSA CENTROAMERICANA DE VALORES, S.A.",
    "Address": "TORRE ALIANZA II, FLOOR 5, BLVD. SAN JUAN BOSCO",
    "City": "TEGUCIGALPA",
    "Branch": "",
    "Postcode": "11101",
    "Country": "Honduras",
    "Connection": "Active"
  },
  {
    "countryCode": "CBVA",
    "bankCode": "HN",
    "branchCode": "NT2",
    "SWIFT Code": "CBVAHNT2",
    "Bank Name": "CASA DE BOLSA DE VALORES S.A. (CABVAL)",
    "Address": "EDIFICIO SANTOS Y CIA, FLOOR 1, AVENIDA CALLE PRINCIPAL 10",
    "City": "TEGUCIGALPA",
    "Branch": "",
    "Postcode": "11101",
    "Country": "Honduras",
    "Connection": "Active"
  },
  {
    "countryCode": "PBPR",
    "bankCode": "HN",
    "branchCode": "NT2",
    "SWIFT Code": "PBPRHNT2",
    "Bank Name": "PUESTO DE BOLSA PROMOTORA BURSATIL, S.A.",
    "Address": "PLAZA VICTORIA, TORRE UNO, FLOOR 5, BULEVAR FRANCIA, RESIDENCIAL LAS COLINA",
    "City": "TEGUCIGALPA",
    "Branch": "",
    "Postcode": "11101",
    "Country": "Honduras",
    "Connection": "Active"
  }
]
module.exports = honduras
