const iceland = [
  {
    "countryCode": "ESJA",
    "bankCode": "IS",
    "branchCode": "SRE",
    "SWIFT Code": "ESJAISRE",
    "Bank Name": "ARION BANK",
    "Address": "BORGARTUN 19",
    "City": "REYKJAVIK",
    "Branch": "",
    "Postcode": "105",
    "Country": "Iceland",
    "Connection": "Active"
  },
  {
    "countryCode": "SISL",
    "bankCode": "IS",
    "branchCode": "SRE",
    "SWIFT Code": "SISLISRE",
    "Bank Name": "CENTRAL BANK OF ICELAND",
    "Address": "KALKOFNSVEGUR 1",
    "City": "REYKJAVIK",
    "Branch": "",
    "Postcode": "150",
    "Country": "Iceland",
    "Connection": "Active"
  },
  {
    "countryCode": "SISL",
    "bankCode": "IS",
    "branchCode": "SRX",
    "SWIFT Code": "SISLISRX",
    "Bank Name": "CENTRAL BANK OF ICELAND",
    "Address": "KALKOFNSVEGI 1",
    "City": "REYKJAVIK",
    "Branch": "",
    "Postcode": "150",
    "Country": "Iceland",
    "Connection": "Active"
  },
  {
    "countryCode": "SISL",
    "bankCode": "IS",
    "branchCode": "TIA",
    "SWIFT Code": "SISLISRETIA",
    "Bank Name": "CENTRAL BANK OF ICELAND",
    "Address": "KALKOFNSVEGUR 1",
    "City": "REYKJAVIK",
    "Branch": "TECHNICAL CODE 1",
    "Postcode": "150",
    "Country": "Iceland",
    "Connection": "Active"
  },
  {
    "countryCode": "SISL",
    "bankCode": "IS",
    "branchCode": "ASA",
    "SWIFT Code": "SISLISREASA",
    "Bank Name": "CENTRAL BANK OF ICELAND",
    "Address": "KALKOFNSVEGUR 1",
    "City": "REYKJAVIK",
    "Branch": "TECHNICAL CODE 2",
    "Postcode": "150",
    "Country": "Iceland",
    "Connection": "Active"
  },
  {
    "countryCode": "EIMI",
    "bankCode": "IS",
    "branchCode": "SRE",
    "SWIFT Code": "EIMIISRE",
    "Bank Name": "EIMSKIPAFELAG ISLANDS HF",
    "Address": "SUNDABAKKA 2",
    "City": "REYKJAVIK",
    "Branch": "",
    "Postcode": "104",
    "Country": "Iceland",
    "Connection": "Active"
  },
  {},
  {
    "countryCode": "MPBA",
    "bankCode": "IS",
    "branchCode": "SRE",
    "SWIFT Code": "MPBAISRE",
    "Bank Name": "KVIKA BANKI HF.",
    "Address": "BORGARTUNI 25",
    "City": "REYKJAVIK",
    "Branch": "",
    "Postcode": "105",
    "Country": "Iceland",
    "Connection": "Active"
  },
  {
    "countryCode": "NBII",
    "bankCode": "IS",
    "branchCode": "SRE",
    "SWIFT Code": "NBIIISRE",
    "Bank Name": "LANDSBANKINN HF",
    "Address": "AUSTURSTRAETI 11",
    "City": "REYKJAVIK",
    "Branch": "",
    "Postcode": "155",
    "Country": "Iceland",
    "Connection": "Active"
  },
  {
    "countryCode": "OSSR",
    "bankCode": "IS",
    "branchCode": "SRR",
    "SWIFT Code": "OSSRISRR",
    "Bank Name": "OSSUR HF.",
    "Address": "GRJOTHALSI 5",
    "City": "REYKJAVIK",
    "Branch": "",
    "Postcode": "110",
    "Country": "Iceland",
    "Connection": "Active"
  },
  {
    "countryCode": "VATO",
    "bankCode": "IS",
    "branchCode": "SRE",
    "SWIFT Code": "VATOISRE",
    "Bank Name": "RAPYD EUROPE HF",
    "Address": "DALSHRAUN 3",
    "City": "HAFNARFJORDUR",
    "Branch": "",
    "Postcode": "220",
    "Country": "Iceland",
    "Connection": "Active"
  },
  {
    "countryCode": "SPUA",
    "bankCode": "IS",
    "branchCode": "SR2",
    "SWIFT Code": "SPUAISR2",
    "Bank Name": "SPARISJODUR AUSTURLANDS HF.",
    "Address": "EGILSBRAUT 25",
    "City": "NESKAUPSTAD",
    "Branch": "",
    "Postcode": "740",
    "Country": "Iceland",
    "Connection": "Active"
  },
  {
    "countryCode": "SPDS",
    "bankCode": "IS",
    "branchCode": "SR2",
    "SWIFT Code": "SPDSISR2",
    "Bank Name": "SPARISJODUR HOFDHVERFINGA SES",
    "Address": "TUNGATA 3",
    "City": "GRENIVIK",
    "Branch": "",
    "Postcode": "610",
    "Country": "Iceland",
    "Connection": "Active"
  },
  {
    "countryCode": "SSRS",
    "bankCode": "IS",
    "branchCode": "SR2",
    "SWIFT Code": "SSRSISR2",
    "Bank Name": "SPARISJODUR STRANDAMANNA SES.",
    "Address": "HAFNARBRAUT 19",
    "City": "HOLMAVIK",
    "Branch": "",
    "Postcode": "510",
    "Country": "Iceland",
    "Connection": "Active"
  },
  {
    "countryCode": "SPYE",
    "bankCode": "IS",
    "branchCode": "SR2",
    "SWIFT Code": "SPYEISR2",
    "Bank Name": "SPARISJODUR SUDUR-THINGEYINGA SES.",
    "Address": "KJARNA",
    "City": "HUSAVIK",
    "Branch": "",
    "Postcode": "641",
    "Country": "Iceland",
    "Connection": "Active"
  },
  {
    "countryCode": "BORG",
    "bankCode": "IS",
    "branchCode": "SRE",
    "SWIFT Code": "BORGISRE",
    "Bank Name": "TEYA ICELAND HF.",
    "Address": "KATRINARTUN 4",
    "City": "REYKJAVIK",
    "Branch": "",
    "Postcode": "105",
    "Country": "Iceland",
    "Connection": "Active"
  },
  {
    "countryCode": "SLTP",
    "bankCode": "IS",
    "branchCode": "SRE",
    "SWIFT Code": "SLTPISRE",
    "Bank Name": "TEYA ICELAND HF.",
    "Address": "KATRINARTUN 4",
    "City": "REYKJAVIK",
    "Branch": "",
    "Postcode": "105",
    "Country": "Iceland",
    "Connection": "Active"
  },
  {
    "countryCode": "VEIA",
    "bankCode": "IS",
    "branchCode": "SR2",
    "SWIFT Code": "VEIAISR2",
    "Bank Name": "VERDBREFAMIDSTOD ISLANDS HF.",
    "Address": "FISKISLOD 31, FLOOR 2",
    "City": "REYKJAVIK",
    "Branch": "",
    "Postcode": "101",
    "Country": "Iceland",
    "Connection": "Active"
  }
]
module.exports = iceland
