const israel = [
  {
    "countryCode": "MIZB",
    "bankCode": "IL",
    "branchCode": "LIT",
    "SWIFT Code": "MIZBILIT",
    "Bank Name": "MIZRAHI TEFAHOT BANK LTD.",
    "Address": "7 , JABOTINSKY ST",
    "City": "RAMAT GAN",
    "Branch": "",
    "Postcode": "5252007",
    "Country": "Israel",
    "Connection": "Active"
  },
  {
    "countryCode": "MIZB",
    "bankCode": "IL",
    "branchCode": "DMD",
    "SWIFT Code": "MIZBILITDMD",
    "Bank Name": "MIZRAHI TEFAHOT BANK LTD.",
    "Address": "1 , JABOTINSKY ROAD",
    "City": "RAMAT GAN",
    "Branch": "DIAMOND EXCHANGE BRANCH",
    "Postcode": "5252001",
    "Country": "Israel",
    "Connection": "Active"
  },
  {
    "countryCode": "MSEU",
    "bankCode": "IL",
    "branchCode": "LI2",
    "SWIFT Code": "MSEUILI2",
    "Bank Name": "MONTROSE SECURITIES LTD",
    "Address": "FLOOR 1, 19 , NACHAL DOLEV",
    "City": "BET SHEMESH",
    "Branch": "",
    "Postcode": "9962168",
    "Country": "Israel",
    "Connection": "Active"
  },
  {
    "countryCode": "OFCN",
    "bankCode": "IL",
    "branchCode": "LIT",
    "SWIFT Code": "OFCNILIT",
    "Bank Name": "OFEK CREDIT UNION",
    "Address": "FLOOR 23, 65, YIGAAL ALON",
    "City": "TEL AVIV",
    "Branch": "",
    "Postcode": "6133401",
    "Country": "Israel",
    "Connection": "Active"
  },
  {
    "countryCode": "DIGI",
    "bankCode": "IL",
    "branchCode": "LIT",
    "SWIFT Code": "DIGIILIT",
    "Bank Name": "ONE ZERO DIGITAL BANK LTD",
    "Address": "5, BEIT-OVED",
    "City": "TEL AVIV",
    "Branch": "",
    "Postcode": "6721105",
    "Country": "Israel",
    "Connection": "Active"
  },
  {
    "countryCode": "IPOA",
    "bankCode": "IL",
    "branchCode": "LIJ",
    "SWIFT Code": "IPOAILIJ",
    "Bank Name": "POSTAL BANK COMPANY LTD",
    "Address": "217 , JAFFA ROAD",
    "City": "JERUSALEM",
    "Branch": "",
    "Postcode": "9199908",
    "Country": "Israel",
    "Connection": "Active"
  },
  {
    "countryCode": "STUN",
    "bankCode": "IL",
    "branchCode": "LI2",
    "SWIFT Code": "STUNILI2",
    "Bank Name": "S.T.B. UNION LTD",
    "Address": "3, DAVID SENIOR",
    "City": "RISHON LEZIYYON",
    "Branch": "",
    "Postcode": "7528953",
    "Country": "Israel",
    "Connection": "Active"
  },
  {
    "countryCode": "SECT",
    "bankCode": "IL",
    "branchCode": "LI2",
    "SWIFT Code": "SECTILI2",
    "Bank Name": "SAMSUNG ELECTRONICS ISRAEL LTD",
    "Address": "BUILDING C, 22, AHARON BART ST",
    "City": "PETAH TIKVA",
    "Branch": "",
    "Postcode": "4917002",
    "Country": "Israel",
    "Connection": "Active"
  },
  {
    "countryCode": "SBIN",
    "bankCode": "IL",
    "branchCode": "LIT",
    "SWIFT Code": "SBINILIT",
    "Bank Name": "STATE BANK OF INDIA",
    "Address": "SHIMSHON - DIAMOND BOURSE, 3 , JABOTINSKY ST",
    "City": "RAMAT GAN",
    "Branch": "",
    "Postcode": "0352520",
    "Country": "Israel",
    "Connection": "Active"
  },
  {
    "countryCode": "XTAE",
    "bankCode": "IL",
    "branchCode": "LIC",
    "SWIFT Code": "XTAEILIC",
    "Bank Name": "TEL AVIV STOCK EXCHANGE",
    "Address": "2 , AHUZAT BAYIT",
    "City": "TEL AVIV",
    "Branch": "",
    "Postcode": "6525216",
    "Country": "Israel",
    "Connection": "Active"
  },
  {
    "countryCode": "XTAE",
    "bankCode": "IL",
    "branchCode": "LIB",
    "SWIFT Code": "XTAEILIB",
    "Bank Name": "TEL AVIV STOCK EXCHANGE",
    "Address": "2 , AHUZAT BAYIT",
    "City": "TEL AVIV",
    "Branch": "",
    "Postcode": "6525216",
    "Country": "Israel",
    "Connection": "Active"
  },
  {
    "countryCode": "XTAE",
    "bankCode": "IL",
    "branchCode": "LIM",
    "SWIFT Code": "XTAEILIM",
    "Bank Name": "TEL AVIV STOCK EXCHANGE",
    "Address": "2 , AHUZAT BAYIT",
    "City": "TEL AVIV",
    "Branch": "",
    "Postcode": "6525216",
    "Country": "Israel",
    "Connection": "Active"
  },
  {
    "countryCode": "XTAE",
    "bankCode": "IL",
    "branchCode": "LIT",
    "SWIFT Code": "XTAEILIT",
    "Bank Name": "TEL-AVIV STOCK EXCHANGE CLEARING HOUSE",
    "Address": "TEL-AVIV STOCK EXCHANGE, 2 , AHUZAT BAYIT",
    "City": "TEL AVIV",
    "Branch": "",
    "Postcode": "6525216",
    "Country": "Israel",
    "Connection": "Active"
  },
  {
    "countryCode": "TEVP",
    "bankCode": "IL",
    "branchCode": "LIT",
    "SWIFT Code": "TEVPILIT",
    "Bank Name": "TEVA PHARMACEUTICAL INDUSTRIES LTD",
    "Address": "124, DEVORAH HANEVI'A ST",
    "City": "PETAH TIKVA",
    "Branch": "",
    "Postcode": "6944038",
    "Country": "Israel",
    "Connection": "Active"
  },
  {
    "countryCode": "WWOF",
    "bankCode": "IL",
    "branchCode": "LI2",
    "SWIFT Code": "WWOFILI2",
    "Bank Name": "WIC WORLDCOM FINANCE LTD.",
    "Address": "FLOOR 10, 94, YIGAL ALON",
    "City": "TEL AVIV",
    "Branch": "",
    "Postcode": "6789156",
    "Country": "Israel",
    "Connection": "Active"
  },
  {
    "countryCode": "ABOM",
    "bankCode": "IL",
    "branchCode": "LI2",
    "SWIFT Code": "ABOMILI2",
    "Bank Name": "ALBERCOM LTD",
    "Address": "1, BEN YEHUDA STREET",
    "City": "TEL AVIV",
    "Branch": "",
    "Postcode": "6380101",
    "Country": "Israel",
    "Connection": "Active"
  },
  {
    "countryCode": "ALTH",
    "bankCode": "IL",
    "branchCode": "LI2",
    "SWIFT Code": "ALTHILI2",
    "Bank Name": "ALTSHULER SHAHAMM FINANCIAL SERVICES LTD",
    "Address": "19 , HABARZEL",
    "City": "TEL AVIV",
    "Branch": "",
    "Postcode": "6971026",
    "Country": "Israel",
    "Connection": "Active"
  },
  {
    "countryCode": "ASRI",
    "bankCode": "IL",
    "branchCode": "LIT",
    "SWIFT Code": "ASRIILIT",
    "Bank Name": "AUTOMATIC BANK SERVICES LTD.",
    "Address": "A FLOOR 1, 26, HAROKMIM STREET",
    "City": "HOLON",
    "Branch": "",
    "Postcode": "5885849",
    "Country": "Israel",
    "Connection": "Active"
  },
  {
    "countryCode": "ASRI",
    "bankCode": "IL",
    "branchCode": "LIC",
    "SWIFT Code": "ASRIILIC",
    "Bank Name": "AUTOMATIC BANK SERVICES LTD.",
    "Address": "BUILDING A, FLOOR 1, 26, HAROKMIM STREET",
    "City": "HOLON",
    "Branch": "",
    "Postcode": "5885849",
    "Country": "Israel",
    "Connection": "Active"
  },
  {
    "countryCode": "ASRI",
    "bankCode": "IL",
    "branchCode": "LIM",
    "SWIFT Code": "ASRIILIM",
    "Bank Name": "AUTOMATIC BANK SERVICES LTD.",
    "Address": "BUILDING A, FLOOR 1, 26, HAROKMIM STREET",
    "City": "HOLON",
    "Branch": "",
    "Postcode": "5885849",
    "Country": "Israel",
    "Connection": "Active"
  },
  {
    "countryCode": "CTEE",
    "bankCode": "IL",
    "branchCode": "LI2",
    "SWIFT Code": "CTEEILI2",
    "Bank Name": "BANK CLEARING CENTER LTD",
    "Address": "BUILDING D, FLOOR 10, 26, HAROKMIM",
    "City": "HOLON",
    "Branch": "",
    "Postcode": "5885849",
    "Country": "Israel",
    "Connection": "Active"
  },
  {
    "countryCode": "CTEE",
    "bankCode": "IL",
    "branchCode": "LIT",
    "SWIFT Code": "CTEEILIT",
    "Bank Name": "BANK CLEARING CENTER LTD",
    "Address": "BUILDING D, FLOOR 10, 26, HAROKMIM",
    "City": "HOLON",
    "Branch": "",
    "Postcode": "5885849",
    "Country": "Israel",
    "Connection": "Active"
  },
  {
    "countryCode": "EIET",
    "bankCode": "IL",
    "branchCode": "LIT",
    "SWIFT Code": "EIETILIT",
    "Bank Name": "BANK ESH ISRAEL (IN SETUP) LTD.",
    "Address": "AZRIELI SARONA POINT, FLOOR 60, 121, DERECH MENACHEM BEGIN",
    "City": "TEL AVIV",
    "Branch": "",
    "Postcode": "6701203",
    "Country": "Israel",
    "Connection": "Active"
  },
  {
    "countryCode": "POAL",
    "bankCode": "IL",
    "branchCode": "LIT",
    "SWIFT Code": "POALILIT",
    "Bank Name": "BANK HAPOALIM B.M.",
    "Address": "50 , ROTHSCHILD BOULEVARD",
    "City": "TEL AVIV",
    "Branch": "",
    "Postcode": "6100001",
    "Country": "Israel",
    "Connection": "Active"
  },
  {
    "countryCode": "POAL",
    "bankCode": "IL",
    "branchCode": "CLS",
    "SWIFT Code": "POALILITCLS",
    "Bank Name": "BANK HAPOALIM B.M.",
    "Address": "",
    "City": "TEL AVIV",
    "Branch": "CLS",
    "Postcode": "",
    "Country": "Israel",
    "Connection": "Active"
  },
  {
    "countryCode": "POAL",
    "bankCode": "IL",
    "branchCode": "GML",
    "SWIFT Code": "POALILITGML",
    "Bank Name": "BANK HAPOALIM B.M.",
    "Address": "",
    "City": "TEL AVIV",
    "Branch": "CUSTODIAN FOR PENSION",
    "Postcode": "",
    "Country": "Israel",
    "Connection": "Active"
  },
  {
    "countryCode": "POAL",
    "bankCode": "IL",
    "branchCode": "CMN",
    "SWIFT Code": "POALILITCMN",
    "Bank Name": "BANK HAPOALIM B.M.",
    "Address": "50 , ROTHSCHILD BOULEVARD",
    "City": "TEL AVIV",
    "Branch": "CUSTOMERS CASH MANAGEMENT",
    "Postcode": "6100001",
    "Country": "Israel",
    "Connection": "Active"
  },
  {
    "countryCode": "POAL",
    "bankCode": "IL",
    "branchCode": "FMT",
    "SWIFT Code": "POALILITFMT",
    "Bank Name": "BANK HAPOALIM B.M.",
    "Address": "",
    "City": "TEL AVIV",
    "Branch": "FOREIGN CURRENCY FOR ALL BRANCHES IN ISRAEL",
    "Postcode": "",
    "Country": "Israel",
    "Connection": "Active"
  },
  {
    "countryCode": "POAL",
    "bankCode": "IL",
    "branchCode": "SEC",
    "SWIFT Code": "POALILITSEC",
    "Bank Name": "BANK HAPOALIM B.M.",
    "Address": "50 , ROTHSCHILD BOULEVARD",
    "City": "TEL AVIV",
    "Branch": "FOREIGN SECURITIES",
    "Postcode": "6100001",
    "Country": "Israel",
    "Connection": "Active"
  },
  {
    "countryCode": "POAL",
    "bankCode": "IL",
    "branchCode": "FTD",
    "SWIFT Code": "POALILITFTD",
    "Bank Name": "BANK HAPOALIM B.M.",
    "Address": "",
    "City": "TEL AVIV",
    "Branch": "FOREIGN TRADE FOR ALL BRANCHES IN ISRAEL",
    "Postcode": "",
    "Country": "Israel",
    "Connection": "Active"
  },
  {
    "countryCode": "POAL",
    "bankCode": "IL",
    "branchCode": "BKR",
    "SWIFT Code": "POALILITBKR",
    "Bank Name": "BANK HAPOALIM B.M.",
    "Address": "",
    "City": "TEL AVIV",
    "Branch": "FOREX AND MONEY MARKET CONFIRMATIONS",
    "Postcode": "",
    "Country": "Israel",
    "Connection": "Active"
  },
  {
    "countryCode": "POAL",
    "bankCode": "IL",
    "branchCode": "DLR",
    "SWIFT Code": "POALILITDLR",
    "Bank Name": "BANK HAPOALIM B.M.",
    "Address": "",
    "City": "TEL AVIV",
    "Branch": "FOREX AND MONEY MARKET PAYMENTS",
    "Postcode": "",
    "Country": "Israel",
    "Connection": "Active"
  },
  {
    "countryCode": "POAL",
    "bankCode": "IL",
    "branchCode": "CBS",
    "SWIFT Code": "POALILITCBS",
    "Bank Name": "BANK HAPOALIM B.M.",
    "Address": "",
    "City": "TEL AVIV",
    "Branch": "SECURITIES",
    "Postcode": "",
    "Country": "Israel",
    "Connection": "Active"
  },
  {
    "countryCode": "LUMI",
    "bankCode": "IL",
    "branchCode": "HAI",
    "SWIFT Code": "LUMIILITHAI",
    "Bank Name": "BANK LEUMI LE ISRAEL B.M.",
    "Address": "2 , SDEROT HAPALYAM",
    "City": "HAIFA",
    "Branch": "HAIFA BRANCH",
    "Postcode": "3309502",
    "Country": "Israel",
    "Connection": "Active"
  },
  {
    "countryCode": "LUMI",
    "bankCode": "IL",
    "branchCode": "JLM",
    "SWIFT Code": "LUMIILITJLM",
    "Bank Name": "BANK LEUMI LE ISRAEL B.M.",
    "Address": "1 , AGUDAT SPORT HAPOEL STREET",
    "City": "JERUSALEM",
    "Branch": "JERUSALEM BRANCH",
    "Postcode": "9695101",
    "Country": "Israel",
    "Connection": "Active"
  },
  {
    "countryCode": "LUMI",
    "bankCode": "IL",
    "branchCode": "BSC",
    "SWIFT Code": "LUMIILITBSC",
    "Bank Name": "BANK LEUMI LE ISRAEL B.M.",
    "Address": "3 , ABA HILLEL SILVER STREET",
    "City": "LOD",
    "Branch": "BANKING SERVICES CENTER",
    "Postcode": "7129404",
    "Country": "Israel",
    "Connection": "Active"
  },
  {
    "countryCode": "LUMI",
    "bankCode": "IL",
    "branchCode": "TLV",
    "SWIFT Code": "LUMIILITTLV",
    "Bank Name": "BANK LEUMI LE ISRAEL B.M.",
    "Address": "BROSH BUILDING, FLOOR 3, 2 , YODFAT STREET",
    "City": "LOD",
    "Branch": "TEL-AVIV MAIN BRANCH",
    "Postcode": "7129105",
    "Country": "Israel",
    "Connection": "Active"
  },
  {
    "countryCode": "LUMI",
    "bankCode": "IL",
    "branchCode": "CLS",
    "SWIFT Code": "LUMIILITCLS",
    "Bank Name": "BANK LEUMI LE ISRAEL B.M.",
    "Address": "32-34 , YEHUDA HALEVI STREET",
    "City": "TEL AVIV",
    "Branch": "CLS OPERATIONS",
    "Postcode": "6513616",
    "Country": "Israel",
    "Connection": "Active"
  },
  {
    "countryCode": "LUMI",
    "bankCode": "IL",
    "branchCode": "LDB",
    "SWIFT Code": "LUMIILITLDB",
    "Bank Name": "BANK LEUMI LE ISRAEL B.M.",
    "Address": "32-34 , YEHUDA HALEVI STREET",
    "City": "TEL AVIV",
    "Branch": "DIGITAL SERVICES",
    "Postcode": "6513616",
    "Country": "Israel",
    "Connection": "Active"
  },
  {
    "countryCode": "LUMI",
    "bankCode": "IL",
    "branchCode": "LIT",
    "SWIFT Code": "LUMIILIT",
    "Bank Name": "BANK LEUMI LE ISRAEL B.M.",
    "Address": "32-34 , YEHUDA HALEVI STREET",
    "City": "TEL AVIV",
    "Branch": "TEL-AVIV MAIN BRANCH",
    "Postcode": "6513616",
    "Country": "Israel",
    "Connection": "Active"
  },
  {
    "countryCode": "MASB",
    "bankCode": "IL",
    "branchCode": "LIT",
    "SWIFT Code": "MASBILIT",
    "Bank Name": "BANK MASSAD LTD.",
    "Address": "12 , ABBA HILLEL ST",
    "City": "RAMAT GAN",
    "Branch": "",
    "Postcode": "5250606",
    "Country": "Israel",
    "Connection": "Active"
  },
  {
    "countryCode": "ISRA",
    "bankCode": "IL",
    "branchCode": "LIJ",
    "SWIFT Code": "ISRAILIJ",
    "Bank Name": "BANK OF ISRAEL",
    "Address": "2 , BANK OF ISRAEL STREET",
    "City": "JERUSALEM",
    "Branch": "",
    "Postcode": "91950",
    "Country": "Israel",
    "Connection": "Active"
  },
  {
    "countryCode": "ISRA",
    "bankCode": "IL",
    "branchCode": "LIB",
    "SWIFT Code": "ISRAILIB",
    "Bank Name": "BANK OF ISRAEL",
    "Address": "2, KAPLAN STREET, KIRYAT HAMEMSHALA",
    "City": "JERUSALEM",
    "Branch": "",
    "Postcode": "9103002",
    "Country": "Israel",
    "Connection": "Active"
  },
  {
    "countryCode": "ISRA",
    "bankCode": "IL",
    "branchCode": "LIR",
    "SWIFT Code": "ISRAILIR",
    "Bank Name": "BANK OF ISRAEL",
    "Address": "KIRYAT BEN GURION, KAPLAN STREET",
    "City": "JERUSALEM",
    "Branch": "",
    "Postcode": "9195016",
    "Country": "Israel",
    "Connection": "Active"
  },
  {
    "countryCode": "JERS",
    "bankCode": "IL",
    "branchCode": "LIT",
    "SWIFT Code": "JERSILIT",
    "Bank Name": "BANK OF JERUSALEM LTD. TEL-AVIV",
    "Address": "MOTOROLA BULIDING, FLOOR 4, 2 , NEGEV ST",
    "City": "LOD",
    "Branch": "",
    "Postcode": "7019900",
    "Country": "Israel",
    "Connection": "Active"
  },
  {
    "countryCode": "BYAH",
    "bankCode": "IL",
    "branchCode": "LIJ",
    "SWIFT Code": "BYAHILIJ",
    "Bank Name": "BANK YAHAV FOR GOVERMENT EMPLOYEES LTD",
    "Address": "YIRMIYAHU ST",
    "City": "JERUSALEM",
    "Branch": "",
    "Postcode": "9446728",
    "Country": "Israel",
    "Connection": "Active"
  },
  {
    "countryCode": "CITI",
    "bankCode": "IL",
    "branchCode": "LIT",
    "SWIFT Code": "CITIILIT",
    "Bank Name": "CITIBANK N.A.",
    "Address": "PLATINUM BUILDING, 21 , HAARBAA STREET",
    "City": "TEL AVIV",
    "Branch": "",
    "Postcode": "6473921",
    "Country": "Israel",
    "Connection": "Active"
  },
  {
    "countryCode": "CITI",
    "bankCode": "IL",
    "branchCode": "TRD",
    "SWIFT Code": "CITIILITTRD",
    "Bank Name": "CITIBANK N.A.",
    "Address": "PLATINIUM BUILDING, 21 , HAARBAA STREET",
    "City": "TEL AVIV",
    "Branch": "TRADE SERVICES DEPT",
    "Postcode": "6473921",
    "Country": "Israel",
    "Connection": "Active"
  },
  {
    "countryCode": "CLRE",
    "bankCode": "IL",
    "branchCode": "LI2",
    "SWIFT Code": "CLREILI2",
    "Bank Name": "CLEARSHIFT ISRAEL LTD",
    "Address": "LULIM, SUITE 10",
    "City": "KFAR ETZION",
    "Branch": "",
    "Postcode": "9091200",
    "Country": "Israel",
    "Connection": "Active"
  },
  {
    "countryCode": "CSVE",
    "bankCode": "IL",
    "branchCode": "LIT",
    "SWIFT Code": "CSVEILIT",
    "Bank Name": "CORRESPONDENT SERVICES LTD.",
    "Address": "AZRIELI TRIANGULAR TOWER, FLOOR 29, 132 , DERECH MENAHEM BEGIN",
    "City": "TEL AVIV",
    "Branch": "",
    "Postcode": "6701101",
    "Country": "Israel",
    "Connection": "Active"
  },
  {
    "countryCode": "ENRE",
    "bankCode": "IL",
    "branchCode": "LIT",
    "SWIFT Code": "ENREILIT",
    "Bank Name": "ENERGIX RENEWABLE ENERGIES LTD",
    "Address": "2 , JABOTINSKI",
    "City": "RAMAT GAN",
    "Branch": "",
    "Postcode": "5250501",
    "Country": "Israel",
    "Connection": "Active"
  },
  {
    "countryCode": "FIRB",
    "bankCode": "IL",
    "branchCode": "DEX",
    "SWIFT Code": "FIRBILITDEX",
    "Bank Name": "FIRST INTERNATIONAL BANK OF ISRAEL LTD.,THE",
    "Address": "BEIT NOAM, 23 , TOVAL ST",
    "City": "RAMAT GAN",
    "Branch": "DIAMOND EXCHANGE BRANCH",
    "Postcode": "5252238",
    "Country": "Israel",
    "Connection": "Active"
  },
  {
    "countryCode": "FIRB",
    "bankCode": "IL",
    "branchCode": "LIT",
    "SWIFT Code": "FIRBILIT",
    "Bank Name": "FIRST INTERNATIONAL BANK OF ISRAEL LTD.,THE",
    "Address": "42 , ROTSCHILD BLVD",
    "City": "TEL AVIV",
    "Branch": "",
    "Postcode": "6688310",
    "Country": "Israel",
    "Connection": "Active"
  },
  {
    "countryCode": "FIRB",
    "bankCode": "IL",
    "branchCode": "CBR",
    "SWIFT Code": "FIRBILITCBR",
    "Bank Name": "FIRST INTERNATIONAL BANK OF ISRAEL LTD.,THE",
    "Address": "38 , ROTSCHILD BLVD",
    "City": "TEL AVIV",
    "Branch": "",
    "Postcode": "6688307",
    "Country": "Israel",
    "Connection": "Active"
  },
  {
    "countryCode": "GMTI",
    "bankCode": "IL",
    "branchCode": "LI2",
    "SWIFT Code": "GMTIILI2",
    "Bank Name": "GMT TECH INNOVATION LTD",
    "Address": "18 , RAOUL WALLENBERG",
    "City": "TEL AVIV",
    "Branch": "",
    "Postcode": "6971915",
    "Country": "Israel",
    "Connection": "Active"
  },
  {
    "countryCode": "HAEH",
    "bankCode": "IL",
    "branchCode": "LI2",
    "SWIFT Code": "HAEHILI2",
    "Bank Name": "HAAVAROT MEHIROT LTD.",
    "Address": "BIG FASHION, 1 , YIGAL ALON AVE",
    "City": "BEIT SHEMESH",
    "Branch": "",
    "Postcode": "9906201",
    "Country": "Israel",
    "Connection": "Active"
  },
  {
    "countryCode": "HSBC",
    "bankCode": "IL",
    "branchCode": "LIT",
    "SWIFT Code": "HSBCILIT",
    "Bank Name": "HSBC BANK PLC",
    "Address": "AMOT ATRIUM TOWER, FLOOR 30, 2 JABOTINSKY STREET",
    "City": "RAMAT GAN",
    "Branch": "",
    "Postcode": "5250501",
    "Country": "Israel",
    "Connection": "Active"
  },
  {
    "countryCode": "IDBL",
    "bankCode": "IL",
    "branchCode": "LIT",
    "SWIFT Code": "IDBLILIT",
    "Bank Name": "ISRAEL DISCOUNT BANK LTD.",
    "Address": "27-31 , YEHUDA HALEVI STREET",
    "City": "TEL AVIV",
    "Branch": "HEAD OFFICE",
    "Postcode": "6513616",
    "Country": "Israel",
    "Connection": "Active"
  },
  {
    "countryCode": "ISRT",
    "bankCode": "IL",
    "branchCode": "LI2",
    "SWIFT Code": "ISRTILI2",
    "Bank Name": "ISRATRANSFER LTD",
    "Address": "12C, SHAMAI STREET",
    "City": "JERUSALEM",
    "Branch": "",
    "Postcode": "9463115",
    "Country": "Israel",
    "Connection": "Active"
  },
  {
    "countryCode": "BARD",
    "bankCode": "IL",
    "branchCode": "LIT",
    "SWIFT Code": "BARDILIT",
    "Bank Name": "MERCANTILE DISCOUNT BANK LTD.",
    "Address": "HAYOVEL TOWER, FLOOR 34, 125 , MENACHEM BEGIN ROAD",
    "City": "TEL AVIV",
    "Branch": "HEAD OFFICE",
    "Postcode": "6701201",
    "Country": "Israel",
    "Connection": "Active"
  },
  {
    "countryCode": "MPSI",
    "bankCode": "IL",
    "branchCode": "LI2",
    "SWIFT Code": "MPSIILI2",
    "Bank Name": "MESHULAM PAYMENT SOLUTIONS LTD.",
    "Address": "1, DERECH YITZHAK RABIN",
    "City": "PETAH TIKVA",
    "Branch": "",
    "Postcode": "4925110",
    "Country": "Israel",
    "Connection": "Active"
  },
  {
    "countryCode": "MIZB",
    "bankCode": "IL",
    "branchCode": "BSV",
    "SWIFT Code": "MIZBILITBSV",
    "Bank Name": "MIZRAHI TEFAHOT BANK LTD.",
    "Address": "60 , HERZL STREET",
    "City": "BEERSHEBA",
    "Branch": "BEER-SHEVA MAIN BRANCH",
    "Postcode": "8422060",
    "Country": "Israel",
    "Connection": "Active"
  },
  {
    "countryCode": "MIZB",
    "bankCode": "IL",
    "branchCode": "HAI",
    "SWIFT Code": "MIZBILITHAI",
    "Bank Name": "MIZRAHI TEFAHOT BANK LTD.",
    "Address": "64 , HAATZMAUT ROAD",
    "City": "HAIFA",
    "Branch": "HAIFA MAIN BRANCH",
    "Postcode": "33033",
    "Country": "Israel",
    "Connection": "Active"
  },
  {
    "countryCode": "MIZB",
    "bankCode": "IL",
    "branchCode": "JLM",
    "SWIFT Code": "MIZBILITJLM",
    "Bank Name": "MIZRAHI TEFAHOT BANK LTD.",
    "Address": "2 , BEN YEHUDA STREET",
    "City": "JERUSALEM",
    "Branch": "JERUSALEM MAIN BRANCH",
    "Postcode": "94622",
    "Country": "Israel",
    "Connection": "Active"
  },
  {
    "countryCode": "MIZB",
    "bankCode": "IL",
    "branchCode": "TLV",
    "SWIFT Code": "MIZBILITTLV",
    "Bank Name": "MIZRAHI TEFAHOT BANK LTD.",
    "Address": "13 , ABBA HILLEL SILVER",
    "City": "LOD",
    "Branch": "",
    "Postcode": "7129463",
    "Country": "Israel",
    "Connection": "Active"
  }
]
module.exports = israel
