const jamaica = [
  {
    "countryCode": "AIFV",
    "bankCode": "JM",
    "branchCode": "MK2",
    "SWIFT Code": "AIFVJMK2",
    "Bank Name": "ALLIANCE FINANCIAL SERVICES LIMITED",
    "Address": "7 BELMONT ROAD",
    "City": "KINGSTON",
    "Branch": "",
    "Postcode": "",
    "Country": "Jamaica",
    "Connection": "Active"
  },
  {
    "countryCode": "BAJA",
    "bankCode": "JM",
    "branchCode": "MKN",
    "SWIFT Code": "BAJAJMKN",
    "Bank Name": "BANK OF JAMAICA",
    "Address": "NETHERSOLE PLACE",
    "City": "KINGSTON",
    "Branch": "",
    "Postcode": "",
    "Country": "Jamaica",
    "Connection": "Active"
  },
  {
    "countryCode": "FILB",
    "bankCode": "JM",
    "branchCode": "MKN",
    "SWIFT Code": "FILBJMKN",
    "Bank Name": "FIRST GLOBAL BANK LIMITED",
    "Address": "SAGICOR BUILDING, 28 - 48 BARBADOS AVENUE",
    "City": "KINGSTON",
    "Branch": "",
    "Postcode": "",
    "Country": "Jamaica",
    "Connection": "Active"
  },
  {
    "countryCode": "FCIB",
    "bankCode": "JM",
    "branchCode": "MKN",
    "SWIFT Code": "FCIBJMKN",
    "Bank Name": "FIRSTCARIBBEAN INTERNATIONAL BANK (JAMAICA) LIMITED",
    "Address": "23-27 KNUTSFORD BOULEVARD",
    "City": "KINGSTON",
    "Branch": "",
    "Postcode": "",
    "Country": "Jamaica",
    "Connection": "Active"
  },
  {
    "countryCode": "GKCM",
    "bankCode": "JM",
    "branchCode": "MK2",
    "SWIFT Code": "GKCMJMK2",
    "Bank Name": "GK CAPITAL MANAGEMENT LIMITED",
    "Address": "58 HOPE ROAD",
    "City": "KINGSTON",
    "Branch": "",
    "Postcode": "",
    "Country": "Jamaica",
    "Connection": "Active"
  },
  {
    "countryCode": "JCSD",
    "bankCode": "JM",
    "branchCode": "MKN",
    "SWIFT Code": "JCSDJMKN",
    "Bank Name": "JAMAICA CENTRAL SECURITIES DEPOSITORY LTD",
    "Address": "STOCK EXCHANGE PLACE, 40 HARBOUR STREET",
    "City": "KINGSTON",
    "Branch": "",
    "Postcode": "",
    "Country": "Jamaica",
    "Connection": "Active"
  },
  {
    "countryCode": "JCSD",
    "bankCode": "JM",
    "branchCode": "JRR",
    "SWIFT Code": "JCSDJMKNJRR",
    "Bank Name": "JAMAICA CENTRAL SECURITIES DEPOSITORY LTD",
    "Address": "",
    "City": "KINGSTON",
    "Branch": "RETAIL REPO",
    "Postcode": "",
    "Country": "Jamaica",
    "Connection": "Active"
  },
  {
    "countryCode": "JMJA",
    "bankCode": "JM",
    "branchCode": "MKN",
    "SWIFT Code": "JMJAJMKN",
    "Bank Name": "JMMB BANK (JAMAICA) LIMITED",
    "Address": "6-8 GRENADA WAY",
    "City": "KINGSTON",
    "Branch": "",
    "Postcode": "",
    "Country": "Jamaica",
    "Connection": "Active"
  },
  {
    "countryCode": "JMSE",
    "bankCode": "JM",
    "branchCode": "MK2",
    "SWIFT Code": "JMSEJMK2",
    "Bank Name": "JMMB SECURITIES LIMITED",
    "Address": "6 HAUGHTON TERRACE",
    "City": "KINGSTON",
    "Branch": "",
    "Postcode": "",
    "Country": "Jamaica",
    "Connection": "Active"
  },
  {
    "countryCode": "JNBS",
    "bankCode": "JM",
    "branchCode": "MKN",
    "SWIFT Code": "JNBSJMKN",
    "Bank Name": "JN BANK LIMITED",
    "Address": "2-4 CONSTANT SPRING ROAD",
    "City": "KINGSTON",
    "Branch": "",
    "Postcode": "",
    "Country": "Jamaica",
    "Connection": "Active"
  },
  {
    "countryCode": "LAAV",
    "bankCode": "JM",
    "branchCode": "MK2",
    "SWIFT Code": "LAAVJMK2",
    "Bank Name": "LASCO FINANCIAL SERVICES LIMITED",
    "Address": "FLOOR 1, 38 1/2 RED HILLS ROAD",
    "City": "KINGSTON",
    "Branch": "",
    "Postcode": "",
    "Country": "Jamaica",
    "Connection": "Active"
  },
  {
    "countryCode": "MTIN",
    "bankCode": "JM",
    "branchCode": "MK2",
    "SWIFT Code": "MTINJMK2",
    "Bank Name": "M-TWENTYFOUR INVESTMENTS LIMITED",
    "Address": "UNIT 13 , FLOOR 1ST, THE ANNEX, FAIRVIEW",
    "City": "MONTEGO BAY",
    "Branch": "",
    "Postcode": "",
    "Country": "Jamaica",
    "Connection": "Active"
  },
  {
    "countryCode": "MFSF",
    "bankCode": "JM",
    "branchCode": "MK2",
    "SWIFT Code": "MFSFJMK2",
    "Bank Name": "MICRO-FINANCING SOLUTIONS (MFS) LTD",
    "Address": "SHOP 2, SBAJ COMPLEX, 2 TRAFALGAR ROAD",
    "City": "KINGSTON",
    "Branch": "",
    "Postcode": "",
    "Country": "Jamaica",
    "Connection": "Active"
  },
  {
    "countryCode": "JNCB",
    "bankCode": "JM",
    "branchCode": "MKX",
    "SWIFT Code": "JNCBJMKX",
    "Bank Name": "NATIONAL COMMERCIAL BANK JAMAICA LIMITED",
    "Address": "32 TRAFALGAR ROAD",
    "City": "KINGSTON",
    "Branch": "",
    "Postcode": "",
    "Country": "Jamaica",
    "Connection": "Active"
  },
  {
    "countryCode": "NAEB",
    "bankCode": "JM",
    "branchCode": "MKI",
    "SWIFT Code": "NAEBJMKI",
    "Bank Name": "NATIONAL EXPORT-IMPORT BANK OF JAMAICA LIMITED",
    "Address": "85 HOPE ROAD",
    "City": "KINGSTON",
    "Branch": "",
    "Postcode": "",
    "Country": "Jamaica",
    "Connection": "Active"
  },
  {
    "countryCode": "SAJA",
    "bankCode": "JM",
    "branchCode": "MKN",
    "SWIFT Code": "SAJAJMKN",
    "Bank Name": "SAGICOR BANK JAMAICA LIMITED",
    "Address": "17 DOMINICA",
    "City": "KINGSTON",
    "Branch": "",
    "Postcode": "",
    "Country": "Jamaica",
    "Connection": "Active"
  },
  {
    "countryCode": "SCNJ",
    "bankCode": "JM",
    "branchCode": "MKN",
    "SWIFT Code": "SCNJJMKN",
    "Bank Name": "SCOTIA INVESTMENTS JAMAICA LTD",
    "Address": "7 HOLBORN ROAD",
    "City": "KINGSTON",
    "Branch": "",
    "Postcode": "",
    "Country": "Jamaica",
    "Connection": "Active"
  },
  {
    "countryCode": "STJP",
    "bankCode": "JM",
    "branchCode": "MK2",
    "SWIFT Code": "STJPJMK2",
    "Bank Name": "ST. JAMES PLAZA DISTRIBUTORS LTD",
    "Address": "19 1/2 ST. JAMES STREET",
    "City": "MONTEGO BAY",
    "Branch": "",
    "Postcode": "",
    "Country": "Jamaica",
    "Connection": "Active"
  },
  {
    "countryCode": "TARE",
    "bankCode": "JM",
    "branchCode": "MK2",
    "SWIFT Code": "TAREJMK2",
    "Bank Name": "TARCAP ENTERPRISES LTD",
    "Address": "81 MAIN STREET",
    "City": "SANTA CRUZ",
    "Branch": "",
    "Postcode": "",
    "Country": "Jamaica",
    "Connection": "Active"
  },
  {
    "countryCode": "NOSC",
    "bankCode": "JM",
    "branchCode": "MKN",
    "SWIFT Code": "NOSCJMKN",
    "Bank Name": "THE BANK OF NOVA SCOTIA JAMAICA LTD",
    "Address": "SCOTIABANK CENTRE, DUKE AND PORT ROYAL STREETS",
    "City": "KINGSTON",
    "Branch": "",
    "Postcode": "",
    "Country": "Jamaica",
    "Connection": "Active"
  },
  {
    "countryCode": "VMBS",
    "bankCode": "JM",
    "branchCode": "MKN",
    "SWIFT Code": "VMBSJMKN",
    "Bank Name": "VICTORIA MUTUAL BUILDING SOCIETY",
    "Address": "8-10 DUKE STREET",
    "City": "KINGSTON",
    "Branch": "",
    "Postcode": "",
    "Country": "Jamaica",
    "Connection": "Active"
  },
  {
    "countryCode": "WITT",
    "bankCode": "JM",
    "branchCode": "MK2",
    "SWIFT Code": "WITTJMK2",
    "Bank Name": "WINTRADERS LIMITED",
    "Address": "SUITE 24 , FLOOR 2, ARDENNE, EMIRATES 7-9 ARDENNE ROAD",
    "City": "KINGSTON",
    "Branch": "",
    "Postcode": "",
    "Country": "Jamaica",
    "Connection": "Active"
  }
]
module.exports = jamaica
