const jersey = [
  {
    "bankCode": "ACTW",
    "countryCode": "JE",
    "branchCode": "ESH",
    "SWIFT Code": "ACTWJESH",
    "Bank Name": "ACCURO TRUST (JERSEY) LTD",
    "Address": "ONE THE ESPLANADE",
    "City": "ST. HELIER",
    "Branch": "",
    "Postcode": "JE4 8UW",
    "Country": "Jersey",
    "Connection": "Active"
  },
  {
    "bankCode": "AFEE",
    "countryCode": "JE",
    "branchCode": "ESH",
    "SWIFT Code": "AFEEJESH",
    "Bank Name": "AFEX OFFSHORE LIMITED",
    "Address": "FLOOR 3, VANTAGE HOUSE, 5 ANLEY STREET",
    "City": "ST. HELIER",
    "Branch": "",
    "Postcode": "JE2 3QE",
    "Country": "Jersey",
    "Connection": "Active"
  },
  {
    "bankCode": "ANWG",
    "countryCode": "JE",
    "branchCode": "ESH",
    "SWIFT Code": "ANWGJESH",
    "Bank Name": "ANGLIAN WATER GROUP LIMITED",
    "Address": "44 ESPLANADE",
    "City": "ST. HELIER",
    "Branch": "",
    "Postcode": "JE4 9WG",
    "Country": "Jersey",
    "Connection": "Active"
  },
  {
    "bankCode": "SNLT",
    "countryCode": "JE",
    "branchCode": "ESH",
    "SWIFT Code": "SNLTJESH",
    "Bank Name": "APEX GROUP FIDUCIARY SERVICES LIMITED",
    "Address": "IFC, 5",
    "City": "ST. HELIER",
    "Branch": "",
    "Postcode": "JE1 1ST",
    "Country": "Jersey",
    "Connection": "Active"
  },
  {
    "bankCode": "APWN",
    "countryCode": "JE",
    "branchCode": "ESH",
    "SWIFT Code": "APWNJESH",
    "Bank Name": "APW INVESTORS LIMITED",
    "Address": "FLOOR 1, 27 ESPLANADE",
    "City": "ST. HELIER",
    "Branch": "",
    "Postcode": "JE4 9XJ",
    "Country": "Jersey",
    "Connection": "Active"
  },
  {
    "bankCode": "AFSJ",
    "countryCode": "JE",
    "branchCode": "ESH",
    "SWIFT Code": "AFSJJESH",
    "Bank Name": "AZTEC FINANCIAL SERVICES (JERSEY) LIMITED",
    "Address": "AZTEC GROUP HOUSE, 11 - 15 SEATON PLACE",
    "City": "ST. HELIER",
    "Branch": "",
    "Postcode": "JE4 0QH",
    "Country": "Jersey",
    "Connection": "Active"
  },
  {
    "bankCode": "BARC",
    "countryCode": "JE",
    "branchCode": "ESA",
    "SWIFT Code": "BARCJESA",
    "Bank Name": "BARCLAYS BANK PLC, JERSEY BRANCH",
    "Address": "13 LIBRARY PLACE",
    "City": "ST. HELIER",
    "Branch": "",
    "Postcode": "JE4 8NE",
    "Country": "Jersey",
    "Connection": "Active"
  },
  {
    "bankCode": "PARB",
    "countryCode": "JE",
    "branchCode": "ESH",
    "SWIFT Code": "PARBJESH",
    "Bank Name": "BNP PARIBAS SECURITIES SERVICES JERSEY",
    "Address": "IFC, 1 THE ESPLANADE",
    "City": "ST. HELIER",
    "Branch": "",
    "Postcode": "JE1 4BP",
    "Country": "Jersey",
    "Connection": "Active"
  },
  {
    "bankCode": "PARB",
    "countryCode": "JE",
    "branchCode": "ISI",
    "SWIFT Code": "PARBJESHISI",
    "Bank Name": "BNP PARIBAS SECURITIES SERVICES JERSEY",
    "Address": "",
    "City": "ST. HELIER",
    "Branch": "GLOBAL CUSTODY",
    "Postcode": "",
    "Country": "Jersey",
    "Connection": "Active"
  },
  {
    "bankCode": "PARB",
    "countryCode": "JE",
    "branchCode": "FDA",
    "SWIFT Code": "PARBJESHFDA",
    "Bank Name": "BNP PARIBAS SECURITIES SERVICES JERSEY",
    "Address": "",
    "City": "ST. HELIER",
    "Branch": "JERSEY",
    "Postcode": "",
    "Country": "Jersey",
    "Connection": "Active"
  },
  {
    "bankCode": "DPHI",
    "countryCode": "JE",
    "branchCode": "ESH",
    "SWIFT Code": "DPHIJESH",
    "Bank Name": "BORGWARNER JERSEY LIMITED",
    "Address": "QUEENSWAY HOUSE, HILGROVE STREET",
    "City": "ST. HELIER",
    "Branch": "",
    "Postcode": "JE1 1ES",
    "Country": "Jersey",
    "Connection": "Active"
  },
  {
    "bankCode": "BNTB",
    "countryCode": "JE",
    "branchCode": "ESH",
    "SWIFT Code": "BNTBJESH",
    "Bank Name": "BUTTERFIELD BANK (JERSEY) LIMITED",
    "Address": "ST PAUL'S GATE, NEW STREET",
    "City": "ST. HELIER",
    "Branch": "",
    "Postcode": "JE4 5PU",
    "Country": "Jersey",
    "Connection": "Active"
  },
  {
    "bankCode": "CITI",
    "countryCode": "JE",
    "branchCode": "ESX",
    "SWIFT Code": "CITIJESX",
    "Bank Name": "CITIBANK N.A.",
    "Address": "FLOOR 4, 38 ESPLANADE",
    "City": "ST. HELIER",
    "Branch": "",
    "Postcode": "JE4 8QB",
    "Country": "Jersey",
    "Connection": "Active"
  },
  {
    "bankCode": "CITI",
    "countryCode": "JE",
    "branchCode": "EFX",
    "SWIFT Code": "CITIJESXEFX",
    "Bank Name": "CITIBANK N.A.",
    "Address": "",
    "City": "ST. HELIER",
    "Branch": "CITIBANK JERSEY EMFX CONFIRMATIONS",
    "Postcode": "",
    "Country": "Jersey",
    "Connection": "Active"
  },
  {
    "bankCode": "CITI",
    "countryCode": "JE",
    "branchCode": "LPN",
    "SWIFT Code": "CITIJESXLPN",
    "Bank Name": "CITIBANK N.A.",
    "Address": "38 ESPLANADE",
    "City": "ST. HELIER",
    "Branch": "PRIVATE BANKING GROUP",
    "Postcode": "JE4 8ZT",
    "Country": "Jersey",
    "Connection": "Active"
  },
  {
    "bankCode": "CITI",
    "countryCode": "JE",
    "branchCode": "EJX",
    "SWIFT Code": "CITIJEJX",
    "Bank Name": "CITIBANK N.A., JERSEY BRANCH (FORMERLY CITIGROUP (CHANNEL ISLANDS) LIMITED)",
    "Address": "38 ESPLANADE",
    "City": "ST. HELIER",
    "Branch": "",
    "Postcode": "JE4 8QB",
    "Country": "Jersey",
    "Connection": "Active"
  },
  {
    "bankCode": "CITI",
    "countryCode": "JE",
    "branchCode": "EHX",
    "SWIFT Code": "CITIJEHX",
    "Bank Name": "CITICORP BANKING CORPORATION",
    "Address": "CHANNEL HOUSE, GREEN STREET",
    "City": "ST. HELIER",
    "Branch": "",
    "Postcode": "JE4 8WZ",
    "Country": "Jersey",
    "Connection": "Active"
  },
  {
    "bankCode": "EFGB",
    "countryCode": "JE",
    "branchCode": "ESH",
    "SWIFT Code": "EFGBJESH",
    "Bank Name": "EFG PRIVATE BANK LIMITED, JERSEY BRANCH",
    "Address": "44 ESPLANADE",
    "City": "ST. HELIER",
    "Branch": "",
    "Postcode": "JE1 3FG",
    "Country": "Jersey",
    "Connection": "Active"
  },
  {
    "bankCode": "SMIW",
    "countryCode": "JE",
    "branchCode": "ESH",
    "SWIFT Code": "SMIWJESH",
    "Bank Name": "EVELYN PARTNERS INTERNATIONAL LTD",
    "Address": "FLOOR 3, WEIGHBRIDGE HOUSE, LIBERATION SQUARE",
    "City": "ST. HELIER",
    "Branch": "",
    "Postcode": "JE2 3NA",
    "Country": "Jersey",
    "Connection": "Active"
  },
  {
    "bankCode": "EWGG",
    "countryCode": "JE",
    "branchCode": "ESH",
    "SWIFT Code": "EWGGJESH",
    "Bank Name": "EWEALTHGLOBAL GROUP LIMITED",
    "Address": "FLOOR 2, 17 BROAD STREET",
    "City": "ST. HELIER",
    "Branch": "",
    "Postcode": "JE2 3RR",
    "Country": "Jersey",
    "Connection": "Active"
  },
  {
    "bankCode": "FRGS",
    "countryCode": "JE",
    "branchCode": "ESH",
    "SWIFT Code": "FRGSJESH",
    "Bank Name": "FERGUSON PLC",
    "Address": "26 NEW STREET",
    "City": "ST. HELIER",
    "Branch": "",
    "Postcode": "JE2 3RA",
    "Country": "Jersey",
    "Connection": "Active"
  },
  {
    "bankCode": "FIUH",
    "countryCode": "JE",
    "branchCode": "ESH",
    "SWIFT Code": "FIUHJESH",
    "Bank Name": "FIDUCHI LIMITED",
    "Address": "FLOOR 1, KENSINGTON CHAMBERS, 46/50 KENSINGTON PLACE",
    "City": "ST. HELIER",
    "Branch": "",
    "Postcode": "JE4 0ZE",
    "Country": "Jersey",
    "Connection": "Active"
  },
  {
    "bankCode": "MIDL",
    "countryCode": "JE",
    "branchCode": "01A",
    "SWIFT Code": "MIDLJESH01A",
    "Bank Name": "HSBC BANK PLC, JERSEY BRANCH",
    "Address": "",
    "City": "ST. HELIER",
    "Branch": "",
    "Postcode": "",
    "Country": "Jersey",
    "Connection": "Active"
  },
  {
    "bankCode": "MIDL",
    "countryCode": "JE",
    "branchCode": "ESH",
    "SWIFT Code": "MIDLJESH",
    "Bank Name": "HSBC BANK PLC, JERSEY BRANCH",
    "Address": "HSBC HOUSE, ESPLANADE",
    "City": "ST. HELIER",
    "Branch": "",
    "Postcode": "JE1 1HS",
    "Country": "Jersey",
    "Connection": "Active"
  },
  {
    "bankCode": "CHAS",
    "countryCode": "JE",
    "branchCode": "ESX",
    "SWIFT Code": "CHASJESX",
    "Bank Name": "JPMORGAN CHASE BANK, N.A., JERSEY BRANCH",
    "Address": "FLOOR 4, ENSIGN HOUSE, 29 SEATON PLACE",
    "City": "ST. HELIER",
    "Branch": "",
    "Postcode": "JE2 3QL",
    "Country": "Jersey",
    "Connection": "Active"
  },
  {
    "bankCode": "CHAS",
    "countryCode": "JE",
    "branchCode": "ENQ",
    "SWIFT Code": "CHASJESXENQ",
    "Bank Name": "JPMORGAN CHASE BANK, N.A., JERSEY BRANCH",
    "Address": "",
    "City": "ST. HELIER",
    "Branch": "TELEX AND S.W.I.F.T. MESSAGE ENQUIRIES",
    "Postcode": "",
    "Country": "Jersey",
    "Connection": "Active"
  },
  {
    "bankCode": "MTCS",
    "countryCode": "JE",
    "branchCode": "ESH",
    "SWIFT Code": "MTCSJESH",
    "Bank Name": "JTC (JERSEY) LIMITED",
    "Address": "28 ESPLANADE",
    "City": "ST. HELIER",
    "Branch": "",
    "Postcode": "JE2 3QA",
    "Country": "Jersey",
    "Connection": "Active"
  },
  {
    "bankCode": "LHFM",
    "countryCode": "JE",
    "branchCode": "ESH",
    "SWIFT Code": "LHFMJESH",
    "Bank Name": "LANGHAM HALL FUND MANAGEMENT (JERSEY) LIMITED",
    "Address": "FLOOR 3, LIBERATION HOUSE, CASTLE STREET",
    "City": "ST. HELIER",
    "Branch": "",
    "Postcode": "JE1 2LH",
    "Country": "Jersey",
    "Connection": "Active"
  },
  {
    "bankCode": "LOYD",
    "countryCode": "JE",
    "branchCode": "E32",
    "SWIFT Code": "LOYDJE32",
    "Bank Name": "LLOYDS BANK CORPORATE MARKETS PLC JERSEY BRANCH",
    "Address": "9 BROAD STREET",
    "City": "ST. HELIER",
    "Branch": "",
    "Postcode": "JE2 3RR",
    "Country": "Jersey",
    "Connection": "Active"
  },
  {
    "bankCode": "LOYD",
    "countryCode": "JE",
    "branchCode": "EJJ",
    "SWIFT Code": "LOYDJEJJ",
    "Bank Name": "LLOYDS BANK CORPORATE MARKETS PLC JERSEY BRANCH",
    "Address": "9 BROAD STREET",
    "City": "ST. HELIER",
    "Branch": "",
    "Postcode": "JE2 3RR",
    "Country": "Jersey",
    "Connection": "Active"
  },
  {
    "bankCode": "LOYD",
    "countryCode": "JE",
    "branchCode": "ESH",
    "SWIFT Code": "LOYDJESH",
    "Bank Name": "LLOYDS BANK CORPORATE MARKETS PLC, JERSEY BRANCH",
    "Address": "9 BROAD STREET",
    "City": "ST. HELIER",
    "Branch": "",
    "Postcode": "JE2 3RR",
    "Country": "Jersey",
    "Connection": "Active"
  },
  {
    "bankCode": "LLCM",
    "countryCode": "JE",
    "branchCode": "MKT",
    "SWIFT Code": "LLCMJESHMKT",
    "Bank Name": "LLOYDS BANK CORPORATE MARKETS PLC, JERSEY BRANCH",
    "Address": "25 NEW STREET",
    "City": "ST. HELIER",
    "Branch": "",
    "Postcode": "JE4 8RG",
    "Country": "Jersey",
    "Connection": "Active"
  },
  {
    "bankCode": "HSAM",
    "countryCode": "JE",
    "branchCode": "ESH",
    "SWIFT Code": "HSAMJESH",
    "Bank Name": "LLOYDS BANK CORPORATE MARKETS PLC, JERSEY BRANCH",
    "Address": "9 BROAD STREET",
    "City": "ST. HELIER",
    "Branch": "",
    "Postcode": "JE2 3RR",
    "Country": "Jersey",
    "Connection": "Active"
  },
  {
    "bankCode": "LLCM",
    "countryCode": "JE",
    "branchCode": "ESH",
    "SWIFT Code": "LLCMJESH",
    "Bank Name": "LLOYDS BANK CORPORATE MARKETS PLC, JERSEY BRANCH",
    "Address": "9 BROAD STREET",
    "City": "ST. HELIER",
    "Branch": "",
    "Postcode": "JE2 3RR",
    "Country": "Jersey",
    "Connection": "Active"
  },
  {
    "bankCode": "PEIT",
    "countryCode": "JE",
    "branchCode": "EJ2",
    "SWIFT Code": "PEITJEJ2",
    "Bank Name": "MORNINGSTAR WEALTH INTERNATIONAL LIMITED",
    "Address": "FLOOR 3, SALISBURY HOUSE, 1-9 UNION STREET",
    "City": "ST. HELIER",
    "Branch": "",
    "Postcode": "JE2 3RF",
    "Country": "Jersey",
    "Connection": "Active"
  },
  {
    "bankCode": "PEIT",
    "countryCode": "JE",
    "branchCode": "ES2",
    "SWIFT Code": "PEITJES2",
    "Bank Name": "MORNINGSTAR WEALTH INTERNATIONAL LIMITED",
    "Address": "FLOOR 3, SALISBURY HOUSE, 1-9 UNION STREET",
    "City": "ST. HELIER",
    "Branch": "",
    "Postcode": "JE2 3RF",
    "Country": "Jersey",
    "Connection": "Active"
  },
  {
    "bankCode": "RFLC",
    "countryCode": "JE",
    "branchCode": "ESX",
    "SWIFT Code": "RFLCJESX",
    "Bank Name": "NEDBANK PRIVATE WEALTH LTD",
    "Address": "31 THE ESPLANADE",
    "City": "ST. HELIER",
    "Branch": "",
    "Postcode": "JE1 1FB",
    "Country": "Jersey",
    "Connection": "Active"
  },
  {
    "bankCode": "BEDL",
    "countryCode": "JE",
    "branchCode": "ESH",
    "SWIFT Code": "BEDLJESH",
    "Bank Name": "OCORIAN LIMITED",
    "Address": "26 NEW STREET",
    "City": "ST. HELIER",
    "Branch": "",
    "Postcode": "JE4 8PP",
    "Country": "Jersey",
    "Connection": "Active"
  },
  {
    "bankCode": "PERL",
    "countryCode": "JE",
    "branchCode": "ESH",
    "SWIFT Code": "PERLJESH",
    "Bank Name": "PERSHING (CHANNEL ISLANDS) LIMITED",
    "Address": "5 ST ANDREWS PLACE, CHARING CROSS",
    "City": "ST. HELIER",
    "Branch": "",
    "Postcode": "JE4 9RB",
    "Country": "Jersey",
    "Connection": "Active"
  },
  {
    "bankCode": "PEFO",
    "countryCode": "JE",
    "branchCode": "ESH",
    "SWIFT Code": "PEFOJESH",
    "Bank Name": "PETROFAC LIMITED",
    "Address": "26 NEW STREET",
    "City": "ST. HELIER",
    "Branch": "",
    "Postcode": "JE2 3RA",
    "Country": "Jersey",
    "Connection": "Active"
  },
  {
    "bankCode": "PLSN",
    "countryCode": "JE",
    "branchCode": "EJ2",
    "SWIFT Code": "PLSNJEJ2",
    "Bank Name": "PLATFORM SECURITIES INTERNATIONAL LIMITED",
    "Address": "FLOOR 1, THE VIEW, HARBOUR REACH, LA RUE DE CARTERET",
    "City": "ST. HELIER",
    "Branch": "",
    "Postcode": "JE2 4HR",
    "Country": "Jersey",
    "Connection": "Active"
  },
  {
    "bankCode": "PXIS",
    "countryCode": "JE",
    "branchCode": "ESH",
    "SWIFT Code": "PXISJESH",
    "Bank Name": "PRAXISIFM TRUST LIMITED",
    "Address": "CHARTER PLACE, 23-27 SEATON PLACE",
    "City": "ST. HELIER",
    "Branch": "",
    "Postcode": "JE1 1JY",
    "Country": "Jersey",
    "Connection": "Active"
  },
  {
    "bankCode": "RBOS",
    "countryCode": "JE",
    "branchCode": "ESX",
    "SWIFT Code": "RBOSJESX",
    "Bank Name": "RBS INTERNATIONAL (JERSEY)",
    "Address": "ROYAL BANK HOUSE, 71 BATH STREET",
    "City": "ST. HELIER",
    "Branch": "",
    "Postcode": "JE4 8PJ",
    "Country": "Jersey",
    "Connection": "Active"
  },
  {
    "bankCode": "RBOS",
    "countryCode": "JE",
    "branchCode": "ESJ",
    "SWIFT Code": "RBOSJESJ",
    "Bank Name": "RBSI TRADING AS COUTTS CROWN DEPENDENCIES (JERSEY)",
    "Address": "ROYAL BANK HOUSE, 71 BATH STREET",
    "City": "ST. HELIER",
    "Branch": "",
    "Postcode": "JE4 8PJ",
    "Country": "Jersey",
    "Connection": "Active"
  },
  {
    "bankCode": "RBOS",
    "countryCode": "JE",
    "branchCode": "ESH",
    "SWIFT Code": "RBOSJESH",
    "Bank Name": "RBSI TRADING AS NATWEST INTERNATIONAL (JERSEY)",
    "Address": "16 LIBRARY PLACE",
    "City": "ST. HELIER",
    "Branch": "",
    "Postcode": "JE4 8NH",
    "Country": "Jersey",
    "Connection": "Active"
  },
  {
    "bankCode": "ROYC",
    "countryCode": "JE",
    "branchCode": "ESH",
    "SWIFT Code": "ROYCJESH",
    "Bank Name": "ROYAL BANK OF CANADA (CHANNEL ISLANDS) LIMITED",
    "Address": "GASPE HOUSE, 66-72 ESPLANADE",
    "City": "ST. HELIER",
    "Branch": "",
    "Postcode": "JE2 3QT",
    "Country": "Jersey",
    "Connection": "Active"
  },
  {
    "bankCode": "SLTG",
    "countryCode": "JE",
    "branchCode": "ESH",
    "SWIFT Code": "SLTGJESH",
    "Bank Name": "SALTGATE LIMITED",
    "Address": "27 ESPLANADE",
    "City": "ST. HELIER",
    "Branch": "",
    "Postcode": "JE1 1SG",
    "Country": "Jersey",
    "Connection": "Active"
  },
  {
    "bankCode": "ANIL",
    "countryCode": "JE",
    "branchCode": "ESH",
    "SWIFT Code": "ANILJESH",
    "Bank Name": "SANTANDER FINANCIAL SERVICES PLC",
    "Address": "SANTANDER WORK CAFE, 13 - 15 CHARING CROSS",
    "City": "ST. HELIER",
    "Branch": "",
    "Postcode": "JE2 3RP",
    "Country": "Jersey",
    "Connection": "Active"
  },
  {
    "bankCode": "ANIL",
    "countryCode": "JE",
    "branchCode": "TSY",
    "SWIFT Code": "ANILJESHTSY",
    "Bank Name": "SANTANDER FINANCIAL SERVICES PLC",
    "Address": "",
    "City": "ST. HELIER",
    "Branch": "TREASURY OPERATIONS",
    "Postcode": "",
    "Country": "Jersey",
    "Connection": "Active"
  },
  {
    "bankCode": "HAMB",
    "countryCode": "JE",
    "branchCode": "ESX",
    "SWIFT Code": "HAMBJESX",
    "Bank Name": "SG KLEINWORT HAMBROS BANK LIMITED - JERSEY BRANCH",
    "Address": "18 ESPLANADE",
    "City": "ST. HELIER",
    "Branch": "",
    "Postcode": "JE4 8PR",
    "Country": "Jersey",
    "Connection": "Active"
  },
  {
    "bankCode": "HAMB",
    "countryCode": "JE",
    "branchCode": "OPS",
    "SWIFT Code": "HAMBJESXOPS",
    "Bank Name": "SG KLEINWORT HAMBROS BANK LIMITED - JERSEY BRANCH",
    "Address": "18 ESPLANADE",
    "City": "ST. HELIER",
    "Branch": "GBP NATWEST",
    "Postcode": "JE4 8PR",
    "Country": "Jersey",
    "Connection": "Active"
  },
  {
    "bankCode": "SBIC",
    "countryCode": "JE",
    "branchCode": "ESH",
    "SWIFT Code": "SBICJESH",
    "Bank Name": "STANDARD BANK JERSEY LTD.",
    "Address": "STANDARD BANK HOUSE, 47-49 LA MOTTE STREET",
    "City": "ST. HELIER",
    "Branch": "",
    "Postcode": "JE4 8XR",
    "Country": "Jersey",
    "Connection": "Active"
  },
  {
    "bankCode": "SCBL",
    "countryCode": "JE",
    "branchCode": "ESH",
    "SWIFT Code": "SCBLJESH",
    "Bank Name": "STANDARD CHARTERED BANK, JERSEY BRANCH",
    "Address": "15 CASTLE STREET",
    "City": "ST. HELIER",
    "Branch": "",
    "Postcode": "JE4 8PT",
    "Country": "Jersey",
    "Connection": "Active"
  },
  {
    "bankCode": "SDTS",
    "countryCode": "JE",
    "branchCode": "ESH",
    "SWIFT Code": "SDTSJESH",
    "Bank Name": "STONEHAGE FLEMING DEALING AND TREASURY SERVICES (JERSEY) LTD",
    "Address": "THE FORUM, 2 GRENVILLE STREET",
    "City": "ST. HELIER",
    "Branch": "",
    "Postcode": "JE1 4HH",
    "Country": "Jersey",
    "Connection": "Active"
  },
  {
    "bankCode": "SFSH",
    "countryCode": "JE",
    "branchCode": "ESH",
    "SWIFT Code": "SFSHJESH",
    "Bank Name": "STONEHAGE FLEMING TRUST HOLDINGS (JERSEY) LIMITED",
    "Address": "NO 2 THE FORUM GRENVILLE STREET",
    "City": "ST. HELIER",
    "Branch": "",
    "Postcode": "JE1 4HH",
    "Country": "Jersey",
    "Connection": "Active"
  },
  {
    "bankCode": "TCMJ",
    "countryCode": "JE",
    "branchCode": "ES2",
    "SWIFT Code": "TCMJJES2",
    "Bank Name": "TAULA CAPITAL MANAGEMENT (JERSEY) LIMITED",
    "Address": "47 ESPLANADE",
    "City": "ST. HELIER",
    "Branch": "",
    "Postcode": "JE1 0BD",
    "Country": "Jersey",
    "Connection": "Active"
  },
  {
    "bankCode": "UBSW",
    "countryCode": "JE",
    "branchCode": "ESH",
    "SWIFT Code": "UBSWJESH",
    "Bank Name": "UBS AG JERSEY BRANCH",
    "Address": "IFC JERSEY, 1",
    "City": "ST. HELIER",
    "Branch": "JERSEY BRANCH",
    "Postcode": "JE2 3BX",
    "Country": "Jersey",
    "Connection": "Active"
  },
  {
    "bankCode": "UBPG",
    "countryCode": "JE",
    "branchCode": "ESX",
    "SWIFT Code": "UBPGJESX",
    "Bank Name": "UNION BANCAIRE PRIVEE, UBP SA",
    "Address": "FLOOR 5, 40 ESPLANADE",
    "City": "ST. HELIER",
    "Branch": "",
    "Postcode": "JE4 5UH",
    "Country": "Jersey",
    "Connection": "Active"
  },
  {
    "bankCode": "VIST",
    "countryCode": "JE",
    "branchCode": "ESH",
    "SWIFT Code": "VISTJESH",
    "Bank Name": "VISTRA (JERSEY) LIMITED",
    "Address": "FLOOR 4, 22-24 ST PAUL'S GATE, NEW STREET",
    "City": "ST. HELIER",
    "Branch": "",
    "Postcode": "JE1 4TR",
    "Country": "Jersey",
    "Connection": "Active"
  }
]
module.exports = jersey
