const jordan = [
  {
    "bankCode": "ALEY",
    "countryCode": "JO",
    "branchCode": "OAM",
    "SWIFT Code": "ALEYJOAM",
    "Bank Name": "AL ALAMI EXCHANGE COMPANY",
    "Address": "HADDAD BUILDING, GARDENS STREET 51",
    "City": "AMMAN",
    "Branch": "",
    "Postcode": "11192",
    "Country": "Jordan",
    "Connection": "Active"
  },
  {
    "bankCode": "RJHI",
    "countryCode": "JO",
    "branchCode": "OAM",
    "SWIFT Code": "RJHIJOAM",
    "Bank Name": "AL RAJHI BANK , JORDAN BRANCH",
    "Address": "ABDUL HAMEED SHARAF STREET 67, SHMEISSANI",
    "City": "AMMAN",
    "Branch": "",
    "Postcode": "11193",
    "Country": "Jordan",
    "Connection": "Active"
  },
  {
    "bankCode": "ALEL",
    "countryCode": "JO",
    "branchCode": "OAM",
    "SWIFT Code": "ALELJOAM",
    "Bank Name": "ALAWNEH EXCHANGE L.L.C",
    "Address": "ABDULHAMID SHOMAN STR 15",
    "City": "AMMAN",
    "Branch": "",
    "Postcode": "11194",
    "Country": "Jordan",
    "Connection": "Active"
  },
  {
    "bankCode": "ARAB",
    "countryCode": "JO",
    "branchCode": "119",
    "SWIFT Code": "ARABJOAX119",
    "Bank Name": "ARAB BANK PLC",
    "Address": "CAIRO ST",
    "City": "AMMAN",
    "Branch": "ABDALI BRANCH",
    "Postcode": "11118",
    "Country": "Jordan",
    "Connection": "Active"
  },
  {
    "bankCode": "ARAB",
    "countryCode": "JO",
    "branchCode": "133",
    "SWIFT Code": "ARABJOAX133",
    "Bank Name": "ARAB BANK PLC",
    "Address": "CAIRO",
    "City": "AMMAN",
    "Branch": "ABDOUN BRANCH",
    "Postcode": "11118",
    "Country": "Jordan",
    "Connection": "Active"
  },
  {
    "bankCode": "ARAB",
    "countryCode": "JO",
    "branchCode": "131",
    "SWIFT Code": "ARABJOAX131",
    "Bank Name": "ARAB BANK PLC",
    "Address": "AL-HIZAM AL-DAERI ST",
    "City": "AMMAN",
    "Branch": "ABU ALANDA",
    "Postcode": "11118",
    "Country": "Jordan",
    "Connection": "Active"
  },
  {
    "bankCode": "ARAB",
    "countryCode": "JO",
    "branchCode": "126",
    "SWIFT Code": "ARABJOAX126",
    "Bank Name": "ARAB BANK PLC",
    "Address": "THE UNIVERSITY OF JORDAN STREET",
    "City": "AMMAN",
    "Branch": "AL-JUBEIHA BRANCH",
    "Postcode": "19328",
    "Country": "Jordan",
    "Connection": "Active"
  },
  {
    "bankCode": "ARAB",
    "countryCode": "JO",
    "branchCode": "501",
    "SWIFT Code": "ARABJOAX501",
    "Bank Name": "ARAB BANK PLC",
    "Address": "AIRPORT",
    "City": "AMMAN",
    "Branch": "CENTRAL OPERATIONS UNIT-TRADE FINANCE SERVICES",
    "Postcode": "11104",
    "Country": "Jordan",
    "Connection": "Active"
  },
  {
    "bankCode": "ARAB",
    "countryCode": "JO",
    "branchCode": "CUT",
    "SWIFT Code": "ARABJOAXCUT",
    "Bank Name": "ARAB BANK PLC",
    "Address": "SAKER BEN ZEID STREET, SHMEISANI",
    "City": "AMMAN",
    "Branch": "CENTRALIZED INWARD TRANSFERS DEPT.",
    "Postcode": "11195",
    "Country": "Jordan",
    "Connection": "Active"
  },
  {
    "bankCode": "ARAB",
    "countryCode": "JO",
    "branchCode": "TRF",
    "SWIFT Code": "ARABJOAXTRF",
    "Bank Name": "ARAB BANK PLC",
    "Address": "QURAISH STREET",
    "City": "AMMAN",
    "Branch": "CENTRALIZED OUTWARD TRANSFERS DEPT.",
    "Postcode": "11118",
    "Country": "Jordan",
    "Connection": "Active"
  },
  {
    "bankCode": "ARAB",
    "countryCode": "JO",
    "branchCode": "SLR",
    "SWIFT Code": "ARABJOAXSLR",
    "Bank Name": "ARAB BANK PLC",
    "Address": "AIRPORT",
    "City": "AMMAN",
    "Branch": "CENTRALIZED SALARIES UNIT",
    "Postcode": "11104",
    "Country": "Jordan",
    "Connection": "Active"
  },
  {
    "bankCode": "ARAB",
    "countryCode": "JO",
    "branchCode": "DLR",
    "SWIFT Code": "ARABJOAXDLR",
    "Bank Name": "ARAB BANK PLC",
    "Address": "SHAKER BEN ZAID, SHMEISANI",
    "City": "AMMAN",
    "Branch": "DEALING ROOM",
    "Postcode": "11195",
    "Country": "Jordan",
    "Connection": "Active"
  },
  {
    "bankCode": "ARAB",
    "countryCode": "JO",
    "branchCode": "134",
    "SWIFT Code": "ARABJOAX134",
    "Bank Name": "ARAB BANK PLC",
    "Address": "ZAHRAN",
    "City": "AMMAN",
    "Branch": "FIFTH CIRCLE BRANCH",
    "Postcode": "11821",
    "Country": "Jordan",
    "Connection": "Active"
  },
  {
    "bankCode": "ARAB",
    "countryCode": "JO",
    "branchCode": "128",
    "SWIFT Code": "ARABJOAX128",
    "Bank Name": "ARAB BANK PLC",
    "Address": "WASFI AL TAL STREET",
    "City": "AMMAN",
    "Branch": "GARDENS BRANCH",
    "Postcode": "11180",
    "Country": "Jordan",
    "Connection": "Active"
  },
  {
    "bankCode": "ARAB",
    "countryCode": "JO",
    "branchCode": "SEC",
    "SWIFT Code": "ARABJOAXSEC",
    "Bank Name": "ARAB BANK PLC",
    "Address": "SHAKER BEN ZEID STREET, SCHMEISANI",
    "City": "AMMAN",
    "Branch": "GENERAL SECRETARIAT DEPARTMENT",
    "Postcode": "11195",
    "Country": "Jordan",
    "Connection": "Active"
  },
  {
    "bankCode": "ARAB",
    "countryCode": "JO",
    "branchCode": "OAX",
    "SWIFT Code": "ARABJOAX",
    "Bank Name": "ARAB BANK PLC",
    "Address": "SHAKER BEN ZEID STREET, SHMEISANI",
    "City": "AMMAN",
    "Branch": "HEAD OFFICE",
    "Postcode": "11195",
    "Country": "Jordan",
    "Connection": "Active"
  },
  {
    "bankCode": "ARAB",
    "countryCode": "JO",
    "branchCode": "INT",
    "SWIFT Code": "ARABJOAXINT",
    "Bank Name": "ARAB BANK PLC",
    "Address": "SHAKER BEN ZEID STREET, SCHMEISANI",
    "City": "AMMAN",
    "Branch": "INTERNATIONAL BANKING DIVISION",
    "Postcode": "11195",
    "Country": "Jordan",
    "Connection": "Active"
  },
  {
    "bankCode": "ARAB",
    "countryCode": "JO",
    "branchCode": "115",
    "SWIFT Code": "ARABJOAX115",
    "Bank Name": "ARAB BANK PLC",
    "Address": "QES BEN SA'EDAH ST",
    "City": "AMMAN",
    "Branch": "JABAL AMMAN BRANCH",
    "Postcode": "",
    "Country": "Jordan",
    "Connection": "Active"
  },
  {
    "bankCode": "ARAB",
    "countryCode": "JO",
    "branchCode": "116",
    "SWIFT Code": "ARABJOAX116",
    "Bank Name": "ARAB BANK PLC",
    "Address": "KHALED BEN ALWALEED STREET",
    "City": "AMMAN",
    "Branch": "JABAL HUSSEIN BRANCH",
    "Postcode": "11192",
    "Country": "Jordan",
    "Connection": "Active"
  },
  {
    "bankCode": "ARAB",
    "countryCode": "JO",
    "branchCode": "113",
    "SWIFT Code": "ARABJOAX113",
    "Bank Name": "ARAB BANK PLC",
    "Address": "ALBOUNEIH ST",
    "City": "AMMAN",
    "Branch": "JABAL LUWEIBDEH BRANCH",
    "Postcode": "11814",
    "Country": "Jordan",
    "Connection": "Active"
  },
  {
    "bankCode": "ARAB",
    "countryCode": "JO",
    "branchCode": "100",
    "SWIFT Code": "ARABJOAX100",
    "Bank Name": "ARAB BANK PLC",
    "Address": "SHAKER BEN ZAID STREET, SHMEISANI",
    "City": "AMMAN",
    "Branch": "JORDAN BRANCHES CENTRE",
    "Postcode": "11195",
    "Country": "Jordan",
    "Connection": "Active"
  },
  {
    "bankCode": "ARAB",
    "countryCode": "JO",
    "branchCode": "111",
    "SWIFT Code": "ARABJOAX111",
    "Bank Name": "ARAB BANK PLC",
    "Address": "KING FAISAL STREET",
    "City": "AMMAN",
    "Branch": "KING FAISAL STREET",
    "Postcode": "11185",
    "Country": "Jordan",
    "Connection": "Active"
  },
  {
    "bankCode": "ARAB",
    "countryCode": "JO",
    "branchCode": "112",
    "SWIFT Code": "ARABJOAX112",
    "Bank Name": "ARAB BANK PLC",
    "Address": "KING ABUDULLAH I ST",
    "City": "AMMAN",
    "Branch": "MAHATIA STREET BRANCH",
    "Postcode": "11821",
    "Country": "Jordan",
    "Connection": "Active"
  },
  {
    "bankCode": "ARAB",
    "countryCode": "JO",
    "branchCode": "117",
    "SWIFT Code": "ARABJOAX117",
    "Bank Name": "ARAB BANK PLC",
    "Address": "KING ABDULLAH ST",
    "City": "AMMAN",
    "Branch": "MARQA BRANCH",
    "Postcode": "11821",
    "Country": "Jordan",
    "Connection": "Active"
  },
  {
    "bankCode": "ARAB",
    "countryCode": "JO",
    "branchCode": "139",
    "SWIFT Code": "ARABJOAX139",
    "Bank Name": "ARAB BANK PLC",
    "Address": "MECCA",
    "City": "AMMAN",
    "Branch": "MECCA STREET BRANCH",
    "Postcode": "11192",
    "Country": "Jordan",
    "Connection": "Active"
  },
  {
    "bankCode": "ARAB",
    "countryCode": "JO",
    "branchCode": "OPS",
    "SWIFT Code": "ARABJOAXOPS",
    "Bank Name": "ARAB BANK PLC",
    "Address": "SHAKER BIN ZEID",
    "City": "AMMAN",
    "Branch": "OPERATIONS DIVISION",
    "Postcode": "11195",
    "Country": "Jordan",
    "Connection": "Active"
  },
  {
    "bankCode": "ARAB",
    "countryCode": "JO",
    "branchCode": "PBD",
    "SWIFT Code": "ARABJOAXPBD",
    "Bank Name": "ARAB BANK PLC",
    "Address": "SHAKER BEN ZEID",
    "City": "AMMAN",
    "Branch": "PRIVATE BANKING DEPARTMENT 6",
    "Postcode": "11195",
    "Country": "Jordan",
    "Connection": "Active"
  },
  {
    "bankCode": "ARAB",
    "countryCode": "JO",
    "branchCode": "108",
    "SWIFT Code": "ARABJOAX108",
    "Bank Name": "ARAB BANK PLC",
    "Address": "QURAISH STREET, SAQF AL SAIL",
    "City": "AMMAN",
    "Branch": "QURAYSH STREET BRANCH",
    "Postcode": "11118",
    "Country": "Jordan",
    "Connection": "Active"
  },
  {
    "bankCode": "ARAB",
    "countryCode": "JO",
    "branchCode": "138",
    "SWIFT Code": "ARABJOAX138",
    "Bank Name": "ARAB BANK PLC",
    "Address": "SIQILLIYAH",
    "City": "AMMAN",
    "Branch": "RABIA BRANCH",
    "Postcode": "11118",
    "Country": "Jordan",
    "Connection": "Active"
  },
  {
    "bankCode": "ARAB",
    "countryCode": "JO",
    "branchCode": "118",
    "SWIFT Code": "ARABJOAX118",
    "Bank Name": "ARAB BANK PLC",
    "Address": "SHAKER BEN ZEID STREET, SHMEISANI",
    "City": "AMMAN",
    "Branch": "SHMEISANI BRANCH",
    "Postcode": "11195",
    "Country": "Jordan",
    "Connection": "Active"
  },
  {
    "bankCode": "ARAB",
    "countryCode": "JO",
    "branchCode": "130",
    "SWIFT Code": "ARABJOAX130",
    "Bank Name": "ARAB BANK PLC",
    "Address": "NASSOUH TAHIR ST",
    "City": "AMMAN",
    "Branch": "SUWAIFEYYA BRANCH",
    "Postcode": "11947",
    "Country": "Jordan",
    "Connection": "Active"
  },
  {
    "bankCode": "ARAB",
    "countryCode": "JO",
    "branchCode": "110",
    "SWIFT Code": "ARABJOAX110",
    "Bank Name": "ARAB BANK PLC",
    "Address": "PRINCESS RAYA BINT HUSSEIN ST",
    "City": "AMMAN",
    "Branch": "SUWEILEH BRANCH",
    "Postcode": "11821",
    "Country": "Jordan",
    "Connection": "Active"
  },
  {
    "bankCode": "ARAB",
    "countryCode": "JO",
    "branchCode": "TKD",
    "SWIFT Code": "ARABJOAXTKD",
    "Bank Name": "ARAB BANK PLC",
    "Address": "AIRPORT",
    "City": "AMMAN",
    "Branch": "TEST KEY DEPARTMENT",
    "Postcode": "11104",
    "Country": "Jordan",
    "Connection": "Active"
  },
  {
    "bankCode": "ARAB",
    "countryCode": "JO",
    "branchCode": "125",
    "SWIFT Code": "ARABJOAX125",
    "Bank Name": "ARAB BANK PLC",
    "Address": "QUEEN RANIA ST",
    "City": "AMMAN",
    "Branch": "UNIVERSITY STREET",
    "Postcode": "11196",
    "Country": "Jordan",
    "Connection": "Active"
  },
  {
    "bankCode": "ARAB",
    "countryCode": "JO",
    "branchCode": "162",
    "SWIFT Code": "ARABJOAX162",
    "Bank Name": "ARAB BANK PLC",
    "Address": "HOSNI SOBR",
    "City": "AMMAN",
    "Branch": "WADI SEER BRANCH",
    "Postcode": "11814",
    "Country": "Jordan",
    "Connection": "Active"
  },
  {
    "bankCode": "ARAB",
    "countryCode": "JO",
    "branchCode": "114",
    "SWIFT Code": "ARABJOAX114",
    "Bank Name": "ARAB BANK PLC",
    "Address": "AL-MUTHANA BIN HARTHA ST",
    "City": "AMMAN",
    "Branch": "WAHDAT BRANCH",
    "Postcode": "11814",
    "Country": "Jordan",
    "Connection": "Active"
  },
  {
    "bankCode": "ARAB",
    "countryCode": "JO",
    "branchCode": "122",
    "SWIFT Code": "ARABJOAX122",
    "Bank Name": "ARAB BANK PLC",
    "Address": "ASSOUK ATTIJARI STREET",
    "City": "AQABA",
    "Branch": "AQABA BRANCH",
    "Postcode": "77110",
    "Country": "Jordan",
    "Connection": "Active"
  },
  {
    "bankCode": "ARAB",
    "countryCode": "JO",
    "branchCode": "120",
    "SWIFT Code": "ARABJOAX120",
    "Bank Name": "ARAB BANK PLC",
    "Address": "KING ABDUL SQUARE",
    "City": "IRBID",
    "Branch": "IRBID BRANCH",
    "Postcode": "",
    "Country": "Jordan",
    "Connection": "Active"
  },
  {
    "bankCode": "ARAB",
    "countryCode": "JO",
    "branchCode": "107",
    "SWIFT Code": "ARABJOAX107",
    "Bank Name": "ARAB BANK PLC",
    "Address": "KING ABUDULLAH ST",
    "City": "JERASH",
    "Branch": "JERASH BRANCH",
    "Postcode": "26110",
    "Country": "Jordan",
    "Connection": "Active"
  },
  {
    "bankCode": "ARAB",
    "countryCode": "JO",
    "branchCode": "102",
    "SWIFT Code": "ARABJOAX102",
    "Bank Name": "ARAB BANK PLC",
    "Address": "NUZHA ST",
    "City": "KARAK",
    "Branch": "KARAK BRANCH",
    "Postcode": "17110",
    "Country": "Jordan",
    "Connection": "Active"
  },
  {
    "bankCode": "ARAB",
    "countryCode": "JO",
    "branchCode": "104",
    "SWIFT Code": "ARABJOAX104",
    "Bank Name": "ARAB BANK PLC",
    "Address": "KING FAISAL I ST",
    "City": "MAFRAQ",
    "Branch": "MAFRAQ BRANCH",
    "Postcode": "25110",
    "Country": "Jordan",
    "Connection": "Active"
  },
  {
    "bankCode": "ARAB",
    "countryCode": "JO",
    "branchCode": "105",
    "SWIFT Code": "ARABJOAX105",
    "Bank Name": "ARAB BANK PLC",
    "Address": "KING HUSSAIN ST",
    "City": "RUSSEIFA",
    "Branch": "RUSSEIFA BRANCH",
    "Postcode": "13710",
    "Country": "Jordan",
    "Connection": "Active"
  },
  {
    "bankCode": "ARAB",
    "countryCode": "JO",
    "branchCode": "161",
    "SWIFT Code": "ARABJOAX161",
    "Bank Name": "ARAB BANK PLC",
    "Address": "STREET NO 1",
    "City": "SAHAB",
    "Branch": "SAHAB INDUSTRIAL CITY",
    "Postcode": "",
    "Country": "Jordan",
    "Connection": "Active"
  },
  {
    "bankCode": "ARAB",
    "countryCode": "JO",
    "branchCode": "121",
    "SWIFT Code": "ARABJOAX121",
    "Bank Name": "ARAB BANK PLC",
    "Address": "KING HUSSEIN STREET",
    "City": "ZARQA",
    "Branch": "ZERQA BRANCH",
    "Postcode": "13136",
    "Country": "Jordan",
    "Connection": "Active"
  },
  {
    "bankCode": "ABCJ",
    "countryCode": "JO",
    "branchCode": "OAM",
    "SWIFT Code": "ABCJJOAM",
    "Bank Name": "ARAB BANKING CORPORATION (JORDAN)",
    "Address": "QUEEN NOUR STREET",
    "City": "AMMAN",
    "Branch": "",
    "Postcode": "11190",
    "Country": "Jordan",
    "Connection": "Active"
  },
  {
    "bankCode": "AJIB",
    "countryCode": "JO",
    "branchCode": "OAX",
    "SWIFT Code": "AJIBJOAX",
    "Bank Name": "ARAB JORDAN INVESTMENT BANK",
    "Address": "ARAB JORDAN INVESTMENT BANK TOWER, ZAHRAN STREET 200",
    "City": "AMMAN",
    "Branch": "",
    "Postcode": "11121",
    "Country": "Jordan",
    "Connection": "Active"
  },
  {
    "bankCode": "AJIB",
    "countryCode": "JO",
    "branchCode": "600",
    "SWIFT Code": "AJIBJOAX600",
    "Bank Name": "ARAB JORDAN INVESTMENT BANK",
    "Address": "",
    "City": "AMMAN",
    "Branch": "",
    "Postcode": "11118",
    "Country": "Jordan",
    "Connection": "Active"
  },
  {
    "bankCode": "UBSI",
    "countryCode": "JO",
    "branchCode": "OAX",
    "SWIFT Code": "UBSIJOAX",
    "Bank Name": "BANK ALETIHAD",
    "Address": "CHAMBER OF COMMERCE BUILDING, PRINCE SHAKER BEN ZEID STREET, SHEMISANI",
    "City": "AMMAN",
    "Branch": "",
    "Postcode": "11180",
    "Country": "Jordan",
    "Connection": "Active"
  },
  {
    "bankCode": "BJOR",
    "countryCode": "JO",
    "branchCode": "OAX",
    "SWIFT Code": "BJORJOAX",
    "Bank Name": "BANK OF JORDAN PLC",
    "Address": "SHMEISANI ABDEL HAMID SHARAF STREET",
    "City": "AMMAN",
    "Branch": "",
    "Postcode": "11118",
    "Country": "Jordan",
    "Connection": "Active"
  },
  {
    "bankCode": "BJOR",
    "countryCode": "JO",
    "branchCode": "BHM",
    "SWIFT Code": "BJORJOAXBHM",
    "Bank Name": "BANK OF JORDAN PLC",
    "Address": "SHMEISANI ABDEL HAMID SHARAF STREET",
    "City": "AMMAN",
    "Branch": "",
    "Postcode": "11118",
    "Country": "Jordan",
    "Connection": "Active"
  },
  {
    "bankCode": "BJOR",
    "countryCode": "JO",
    "branchCode": "CNC",
    "SWIFT Code": "BJORJOAXCNC",
    "Bank Name": "BANK OF JORDAN PLC",
    "Address": "",
    "City": "AMMAN",
    "Branch": "",
    "Postcode": "11118",
    "Country": "Jordan",
    "Connection": "Active"
  },
  {
    "bankCode": "BLOM",
    "countryCode": "JO",
    "branchCode": "OAM",
    "SWIFT Code": "BLOMJOAM",
    "Bank Name": "BLOM BANK S.A.L.",
    "Address": "BLOM BANK BUILDING, SHAREEF ABDULHAMID SHARAF STREET 18, SHMEYSSANI",
    "City": "AMMAN",
    "Branch": "",
    "Postcode": "11193",
    "Country": "Jordan",
    "Connection": "Active"
  },
  {
    "bankCode": "CAAB",
    "countryCode": "JO",
    "branchCode": "OAM",
    "SWIFT Code": "CAABJOAM",
    "Bank Name": "CAIRO AMMAN BANK",
    "Address": "CAIRO AMMAN BANK BUILDING, WADI SAQRA STREET",
    "City": "AMMAN",
    "Branch": "",
    "Postcode": "11195",
    "Country": "Jordan",
    "Connection": "Active"
  },
  {
    "bankCode": "EFBK",
    "countryCode": "JO",
    "branchCode": "OAM",
    "SWIFT Code": "EFBKJOAM",
    "Bank Name": "CAPITAL BANK OF JORDAN",
    "Address": "BUILDING 26, AL ABDALI - SULAIMAN ALNABULSI ST, SHMEISANI",
    "City": "AMMAN",
    "Branch": "",
    "Postcode": "11194",
    "Country": "Jordan",
    "Connection": "Active"
  },
  {
    "bankCode": "CBJO",
    "countryCode": "JO",
    "branchCode": "OA2",
    "SWIFT Code": "CBJOJOA2",
    "Bank Name": "CENTRAL BANK OF JORDAN",
    "Address": "KING HUSSEIN STREET",
    "City": "AMMAN",
    "Branch": "",
    "Postcode": "11118",
    "Country": "Jordan",
    "Connection": "Active"
  },
  {
    "bankCode": "CBJO",
    "countryCode": "JO",
    "branchCode": "OA3",
    "SWIFT Code": "CBJOJOA3",
    "Bank Name": "CENTRAL BANK OF JORDAN",
    "Address": "KING HUSSEIN STREET",
    "City": "AMMAN",
    "Branch": "",
    "Postcode": "11118",
    "Country": "Jordan",
    "Connection": "Active"
  },
  {
    "bankCode": "CBJO",
    "countryCode": "JO",
    "branchCode": "OAX",
    "SWIFT Code": "CBJOJOAX",
    "Bank Name": "CENTRAL BANK OF JORDAN",
    "Address": "CENTRAL BANK OF JORDAN BUILDING, KING HUSSEIN STREET",
    "City": "AMMAN",
    "Branch": "",
    "Postcode": "11118",
    "Country": "Jordan",
    "Connection": "Active"
  },
  {
    "bankCode": "CBJO",
    "countryCode": "JO",
    "branchCode": "02A",
    "SWIFT Code": "CBJOJOAX02A",
    "Bank Name": "CENTRAL BANK OF JORDAN",
    "Address": "",
    "City": "AQABA",
    "Branch": "AQABA BRANCH",
    "Postcode": "77110",
    "Country": "Jordan",
    "Connection": "Active"
  },
  {
    "bankCode": "CBJO",
    "countryCode": "JO",
    "branchCode": "021",
    "SWIFT Code": "CBJOJOAX021",
    "Bank Name": "CENTRAL BANK OF JORDAN",
    "Address": "",
    "City": "IRBID",
    "Branch": "IRBID BRANCH",
    "Postcode": "21110",
    "Country": "Jordan",
    "Connection": "Active"
  },
  {
    "bankCode": "CITI",
    "countryCode": "JO",
    "branchCode": "OAX",
    "SWIFT Code": "CITIJOAX",
    "Bank Name": "CITIBANK N.A.",
    "Address": "",
    "City": "AMMAN",
    "Branch": "",
    "Postcode": "11118",
    "Country": "Jordan",
    "Connection": "Active"
  },
  {
    "bankCode": "ARLB",
    "countryCode": "JO",
    "branchCode": "OAM",
    "SWIFT Code": "ARLBJOAM",
    "Bank Name": "EGYPTIAN ARAB LAND BANK",
    "Address": "QUEEN NOOR STREET 100",
    "City": "AMMAN",
    "Branch": "",
    "Postcode": "11118",
    "Country": "Jordan",
    "Connection": "Active"
  },
  {
    "bankCode": "HBHO",
    "countryCode": "JO",
    "branchCode": "OAX",
    "SWIFT Code": "HBHOJOAX",
    "Bank Name": "HOUSING BANK FOR TRADE AND FINANCE, THE",
    "Address": "AL-SHUMAYSANI-PRINCE SHAKER BIN, ZAID STREET",
    "City": "AMMAN",
    "Branch": "",
    "Postcode": "11118",
    "Country": "Jordan",
    "Connection": "Active"
  },
  {
    "bankCode": "JIFB",
    "countryCode": "JO",
    "branchCode": "OAM",
    "SWIFT Code": "JIFBJOAM",
    "Bank Name": "INVESTBANK",
    "Address": "ABDUL HAMID SHARAF STREET 43, SHMEISANI",
    "City": "AMMAN",
    "Branch": "",
    "Postcode": "11195",
    "Country": "Jordan",
    "Connection": "Active"
  },
  {
    "bankCode": "IIBA",
    "countryCode": "JO",
    "branchCode": "OAM",
    "SWIFT Code": "IIBAJOAM",
    "Bank Name": "ISLAMIC INTERNATIONAL ARAB BANK",
    "Address": "WASFI AL TAL STREET, TLA AL-ALI",
    "City": "AMMAN",
    "Branch": "",
    "Postcode": "11110",
    "Country": "Jordan",
    "Connection": "Active"
  },
  {
    "bankCode": "IIBA",
    "countryCode": "JO",
    "branchCode": "JBC",
    "SWIFT Code": "IIBAJOAMJBC",
    "Bank Name": "ISLAMIC INTERNATIONAL ARAB BANK",
    "Address": "WASFI AL TAJ STREET, ILA' AL-ALI",
    "City": "AMMAN",
    "Branch": "CENTRAL OPERATIONS DEPARTMENT/ BACK OFFICE",
    "Postcode": "11953",
    "Country": "Jordan",
    "Connection": "Active"
  },
  {
    "bankCode": "IIBA",
    "countryCode": "JO",
    "branchCode": "100",
    "SWIFT Code": "IIBAJOAM100",
    "Bank Name": "ISLAMIC INTERNATIONAL ARAB BANK",
    "Address": "WASFI AL TAL STREET, TLA' AL-ALI",
    "City": "AMMAN",
    "Branch": "CENTRAL OPERATIONS DEPARTMENT/ LCS",
    "Postcode": "11953",
    "Country": "Jordan",
    "Connection": "Active"
  },
  {
    "bankCode": "IIBA",
    "countryCode": "JO",
    "branchCode": "300",
    "SWIFT Code": "IIBAJOAM300",
    "Bank Name": "ISLAMIC INTERNATIONAL ARAB BANK",
    "Address": "YARMOUK STREET, WAHDAT",
    "City": "AMMAN",
    "Branch": "CENTRAL OPERATIONS DEPARTMENT/ LGS AND BCS",
    "Postcode": "11152",
    "Country": "Jordan",
    "Connection": "Active"
  },
  {
    "bankCode": "IIBA",
    "countryCode": "JO",
    "branchCode": "200",
    "SWIFT Code": "IIBAJOAM200",
    "Bank Name": "ISLAMIC INTERNATIONAL ARAB BANK",
    "Address": "WASFI AL TAL",
    "City": "AMMAN",
    "Branch": "CENTRAL OPERATIONS DEPARTMENT/ TRANSFERS",
    "Postcode": "11180",
    "Country": "Jordan",
    "Connection": "Active"
  },
  {
    "bankCode": "JONB",
    "countryCode": "JO",
    "branchCode": "OAX",
    "SWIFT Code": "JONBJOAX",
    "Bank Name": "JORDAN AHLI BANK PLC",
    "Address": "SHMEISANI QUEEN NOOR STREET",
    "City": "AMMAN",
    "Branch": "JORDAN BRANCHES MANAGEMENT",
    "Postcode": "11182",
    "Country": "Jordan",
    "Connection": "Active"
  },
  {
    "bankCode": "JGBA",
    "countryCode": "JO",
    "branchCode": "OAM",
    "SWIFT Code": "JGBAJOAM",
    "Bank Name": "JORDAN COMMERCIAL BANK",
    "Address": "ABDULLAH II BIN AL-HUSSEIN STREET,, AIRPORT ROAD, 8TH CIRCLE",
    "City": "AMMAN",
    "Branch": "",
    "Postcode": "11191",
    "Country": "Jordan",
    "Connection": "Active"
  },
  {
    "bankCode": "JIBA",
    "countryCode": "JO",
    "branchCode": "OAM",
    "SWIFT Code": "JIBAJOAM",
    "Bank Name": "JORDAN ISLAMIC BANK",
    "Address": "AL THAQAFA STREET 3, SHMEISANI AREA",
    "City": "AMMAN",
    "Branch": "",
    "Postcode": "11194",
    "Country": "Jordan",
    "Connection": "Active"
  },
  {
    "bankCode": "JIBA",
    "countryCode": "JO",
    "branchCode": "111",
    "SWIFT Code": "JIBAJOAM111",
    "Bank Name": "JORDAN ISLAMIC BANK",
    "Address": "KHALID BIN-AL WALID STREET",
    "City": "AMMAN",
    "Branch": "AL-HUSSEIN BRANCH",
    "Postcode": "11110",
    "Country": "Jordan",
    "Connection": "Active"
  },
  {
    "bankCode": "JIBA",
    "countryCode": "JO",
    "branchCode": "113",
    "SWIFT Code": "JIBAJOAM113",
    "Bank Name": "JORDAN ISLAMIC BANK",
    "Address": "AL-YARMOUK STREET",
    "City": "AMMAN",
    "Branch": "AL-YARMOUK STREET BRANCH",
    "Postcode": "11162",
    "Country": "Jordan",
    "Connection": "Active"
  },
  {
    "bankCode": "JIBA",
    "countryCode": "JO",
    "branchCode": "110",
    "SWIFT Code": "JIBAJOAM110",
    "Bank Name": "JORDAN ISLAMIC BANK",
    "Address": "KING FAISAL STREET",
    "City": "AMMAN",
    "Branch": "AMMAN BRANCH",
    "Postcode": "11110",
    "Country": "Jordan",
    "Connection": "Active"
  },
  {
    "bankCode": "JIBA",
    "countryCode": "JO",
    "branchCode": "115",
    "SWIFT Code": "JIBAJOAM115",
    "Bank Name": "JORDAN ISLAMIC BANK",
    "Address": "11TH AUGUST STR, SHMEISANI",
    "City": "AMMAN",
    "Branch": "H.O.",
    "Postcode": "11190",
    "Country": "Jordan",
    "Connection": "Active"
  },
  {
    "bankCode": "JIBA",
    "countryCode": "JO",
    "branchCode": "112",
    "SWIFT Code": "JIBAJOAM112",
    "Bank Name": "JORDAN ISLAMIC BANK",
    "Address": "SAQF EL-SAIL STREET",
    "City": "AMMAN",
    "Branch": "SAQF EL-SAIL BRANCH",
    "Postcode": "11118",
    "Country": "Jordan",
    "Connection": "Active"
  },
  {
    "bankCode": "JIBA",
    "countryCode": "JO",
    "branchCode": "114",
    "SWIFT Code": "JIBAJOAM114",
    "Bank Name": "JORDAN ISLAMIC BANK",
    "Address": "WASFI AL-TEL STREET",
    "City": "AMMAN",
    "Branch": "WASFI-AL-TEL STREET BRANCH",
    "Postcode": "11196",
    "Country": "Jordan",
    "Connection": "Active"
  },
  {
    "bankCode": "JKBA",
    "countryCode": "JO",
    "branchCode": "OAM",
    "SWIFT Code": "JKBAJOAM",
    "Bank Name": "JORDAN KUWAIT BANK",
    "Address": "UMMAYA BIN ABED SHAMS ST 62",
    "City": "AMMAN",
    "Branch": "",
    "Postcode": "11191",
    "Country": "Jordan",
    "Connection": "Active"
  },
  {
    "bankCode": "MAKS",
    "countryCode": "JO",
    "branchCode": "OAX",
    "SWIFT Code": "MAKSJOAX",
    "Bank Name": "KAMAL EXCHANGE CO L.L.C",
    "Address": "KAMAL COMPLEX, AL-SHAREEF NASER BIN JAMEEL ST",
    "City": "AMMAN",
    "Branch": "",
    "Postcode": "11190",
    "Country": "Jordan",
    "Connection": "Active"
  },
  {
    "bankCode": "MUEO",
    "countryCode": "JO",
    "branchCode": "OAM",
    "SWIFT Code": "MUEOJOAM",
    "Bank Name": "MUSHARBASH EXCHANGE L.L.C",
    "Address": "WASFI AL-TAL STREET 133, FLOOR 1",
    "City": "AMMAN",
    "Branch": "",
    "Postcode": "11821",
    "Country": "Jordan",
    "Connection": "Active"
  },
  {
    "bankCode": "RAFB",
    "countryCode": "JO",
    "branchCode": "OAM",
    "SWIFT Code": "RAFBJOAM",
    "Bank Name": "RAFIDAIN BANK",
    "Address": "BUILDING NO. 16 MAHMOUD AL MUHIRAT, ALI NASOUH AL-TAHER STREET SWEIFIEH",
    "City": "AMMAN",
    "Branch": "",
    "Postcode": "11118",
    "Country": "Jordan",
    "Connection": "Active"
  },
  {
    "bankCode": "JDIB",
    "countryCode": "JO",
    "branchCode": "OAM",
    "SWIFT Code": "JDIBJOAM",
    "Bank Name": "SAFWA ISLAMIC BANK",
    "Address": "SULAIMAN AL NABULSI STREET, ABDALI",
    "City": "AMMAN",
    "Branch": "",
    "Postcode": "11118",
    "Country": "Jordan",
    "Connection": "Active"
  },
  {
    "bankCode": "SEDC",
    "countryCode": "JO",
    "branchCode": "OAX",
    "SWIFT Code": "SEDCJOAX",
    "Bank Name": "SECURITIES DEPOSITORY CENTER",
    "Address": "AL-MANSOUR BIN ABI AMER STREET 11",
    "City": "AMMAN",
    "Branch": "",
    "Postcode": "11121",
    "Country": "Jordan",
    "Connection": "Active"
  },
  {
    "bankCode": "SCBL",
    "countryCode": "JO",
    "branchCode": "OAX",
    "SWIFT Code": "SCBLJOAX",
    "Bank Name": "STANDARD CHARTERED BANK",
    "Address": "BUILDING NO.2, AL-THAQAFA STREET, SHMEISSANI",
    "City": "AMMAN",
    "Branch": "",
    "Postcode": "11190",
    "Country": "Jordan",
    "Connection": "Active"
  }
]
module.exports = jordan
