const kazakhstan = [
  {
    "countryCode": "HLAL",
    "bankCode": "KZ",
    "branchCode": "ZKZ",
    "SWIFT Code": "HLALKZKZ",
    "Bank Name": "AL HILAL ISLAMIC BANK JSC",
    "Address": "AL FARABI AVENUE, 77/7 FLOOR 14, OFFICE 13A, BUSINESS CENTER ESENTAI TOWER",
    "City": "ALMATY",
    "Branch": "",
    "Postcode": "050040",
    "Country": "Kazakhstan",
    "Connection": "Active"
  },
  {
    "countryCode": "ASIY",
    "bankCode": "KZ",
    "branchCode": "Z22",
    "SWIFT Code": "ASIYKZ22",
    "Bank Name": "AL SAQR ISLAMIC BANK LTD. PRIVATE COMPANY",
    "Address": "MANGILIK YEL AVENUE, 55/20, BLOCK C4.1",
    "City": "NUR-SULTAN",
    "Branch": "",
    "Postcode": "010000",
    "Country": "Kazakhstan",
    "Connection": "Active"
  },
  {
    "countryCode": "AILS",
    "bankCode": "KZ",
    "branchCode": "Z2K",
    "SWIFT Code": "AILSKZ2K",
    "Bank Name": "ALIF ISLAMIC BANK LTD.",
    "Address": "AL-FARABI AVENUE, 77/1, OFFICE 56",
    "City": "ALMATY",
    "Branch": "",
    "Postcode": "050060",
    "Country": "Kazakhstan",
    "Connection": "Active"
  },
  {
    "countryCode": "ASIH",
    "bankCode": "KZ",
    "branchCode": "Z22",
    "SWIFT Code": "ASIHKZ22",
    "Bank Name": "ASTANA INTERNATIONAL EXCHANGE LIMITED",
    "Address": "MANGILIK EL AVENUE, , 55, BUILDING 15",
    "City": "NUR-SULTAN",
    "Branch": "",
    "Postcode": "010000",
    "Country": "Kazakhstan",
    "Connection": "Active"
  },
  {
    "countryCode": "ASIH",
    "bankCode": "KZ",
    "branchCode": "REG",
    "SWIFT Code": "ASIHKZ22REG",
    "Bank Name": "ASTANA INTERNATIONAL EXCHANGE LIMITED",
    "Address": "MANGILIK EL AVENUE, , 55, BUILDING 15",
    "City": "NUR-SULTAN",
    "Branch": "AIX REGISTRAR LTD.",
    "Postcode": "010000",
    "Country": "Kazakhstan",
    "Connection": "Active"
  },
  {
    "countryCode": "ASIH",
    "bankCode": "KZ",
    "branchCode": "CSD",
    "SWIFT Code": "ASIHKZ22CSD",
    "Bank Name": "ASTANA INTERNATIONAL EXCHANGE LIMITED",
    "Address": "MANGILIK EL AVENUE, , 55, BUILDING 15",
    "City": "NUR-SULTAN",
    "Branch": "CENTRAL SECURITIES DEPOSITORY",
    "Postcode": "010000",
    "Country": "Kazakhstan",
    "Connection": "Active"
  },
  {
    "countryCode": "KSNV",
    "bankCode": "KZ",
    "branchCode": "ZKA",
    "SWIFT Code": "KSNVKZKA",
    "Bank Name": "BANK FREEDOM FINANCE KAZAKHSTAN JSC",
    "Address": "KUNAEV STREET , 10",
    "City": "NUR-SULTAN",
    "Branch": "",
    "Postcode": "010000",
    "Country": "Kazakhstan",
    "Connection": "Active"
  },
  {
    "countryCode": "BKCH",
    "bankCode": "KZ",
    "branchCode": "ZKA",
    "SWIFT Code": "BKCHKZKA",
    "Bank Name": "BANK OF CHINA KAZAKHSTAN",
    "Address": "MCR ZHETYSU 2, 71 B, AUEZOV DISTRICT",
    "City": "ALMATY",
    "Branch": "",
    "Postcode": "030000",
    "Country": "Kazakhstan",
    "Connection": "Active"
  },
  {
    "countryCode": "KINC",
    "bankCode": "KZ",
    "branchCode": "ZKA",
    "SWIFT Code": "KINCKZKA",
    "Bank Name": "BANK RBK",
    "Address": "ADI SHARIPOVA , 84",
    "City": "ALMATY",
    "Branch": "",
    "Postcode": "050012",
    "Country": "Kazakhstan",
    "Connection": "Active"
  },
  {
    "countryCode": "BRKE",
    "bankCode": "KZ",
    "branchCode": "ZKA",
    "SWIFT Code": "BRKEKZKA",
    "Bank Name": "BEREKE BANK JOINT STOCK COMPANY",
    "Address": "AV. AL-FARABI, 13/1",
    "City": "ALMATY",
    "Branch": "",
    "Postcode": "050059",
    "Country": "Kazakhstan",
    "Connection": "Active"
  },
  {
    "countryCode": "BRLP",
    "bankCode": "KZ",
    "branchCode": "Z22",
    "SWIFT Code": "BRLPKZ22",
    "Bank Name": "BRILLINK BANK CORPORATION LIMITED",
    "Address": "MANGILIK EL, RCA 0201800073913428, 55/20 OFFICE 251/252, BLOCK C4.1",
    "City": "NUR-SULTAN",
    "Branch": "",
    "Postcode": "010017",
    "Country": "Kazakhstan",
    "Connection": "Active"
  },
  {
    "countryCode": "CEDU",
    "bankCode": "KZ",
    "branchCode": "ZKA",
    "SWIFT Code": "CEDUKZKA",
    "Bank Name": "CENTRAL SECURITIES DEPOSITORY, JSC",
    "Address": "MICRODISTRICT SAMAL, 1 28",
    "City": "ALMATY",
    "Branch": "",
    "Postcode": "050051",
    "Country": "Kazakhstan",
    "Connection": "Active"
  },
  {
    "countryCode": "PCBC",
    "bankCode": "KZ",
    "branchCode": "Z2A",
    "SWIFT Code": "PCBCKZ2A",
    "Bank Name": "CHINA CONSTRUCTION BANK CORPORATION ASTANA BRANCH",
    "Address": "DOSTYK STREET , 16, FLOOR 26, TALAN TOWERS, ESIL DISTRICT",
    "City": "NUR-SULTAN",
    "Branch": "",
    "Postcode": "010000",
    "Country": "Kazakhstan",
    "Connection": "Active"
  },
  {
    "countryCode": "CITI",
    "bankCode": "KZ",
    "branchCode": "ZKA",
    "SWIFT Code": "CITIKZKA",
    "Bank Name": "CJSC CITIBANK KAZAKHSTAN",
    "Address": "ZENKOV ST, 26/41",
    "City": "ALMATY",
    "Branch": "",
    "Postcode": "050000",
    "Country": "Kazakhstan",
    "Connection": "Active"
  },
  {
    "countryCode": "CLPY",
    "bankCode": "KZ",
    "branchCode": "Z2A",
    "SWIFT Code": "CLPYKZ2A",
    "Bank Name": "COLLECT AND PAY LTD.",
    "Address": "MANGILIK EL AVENUE, 55/20, FLOOR 3, BLOCK C 4.1, AIFC PROPERTY",
    "City": "ASTANA",
    "Branch": "",
    "Postcode": "010000",
    "Country": "Kazakhstan",
    "Connection": "Active"
  },
  {
    "countryCode": "DVKA",
    "bankCode": "KZ",
    "branchCode": "ZKA",
    "SWIFT Code": "DVKAKZKA",
    "Bank Name": "DEVELOPMENT BANK OF KAZAKHSTAN JSC",
    "Address": "MANGILIK YEL , 55A, 15",
    "City": "NUR-SULTAN",
    "Branch": "",
    "Postcode": "010000",
    "Country": "Kazakhstan",
    "Connection": "Active"
  },
  {
    "countryCode": "EURI",
    "bankCode": "KZ",
    "branchCode": "ZKA",
    "SWIFT Code": "EURIKZKA",
    "Bank Name": "EURASIAN BANK",
    "Address": "KUNAYEV STR., 56",
    "City": "ALMATY",
    "Branch": "",
    "Postcode": "050002",
    "Country": "Kazakhstan",
    "Connection": "Active"
  },
  {
    "countryCode": "EABR",
    "bankCode": "KZ",
    "branchCode": "ZKA",
    "SWIFT Code": "EABRKZKA",
    "Bank Name": "EURASIAN DEVELOPMENT BANK",
    "Address": "DOSTYK AVE. , 220",
    "City": "ALMATY",
    "Branch": "",
    "Postcode": "050051",
    "Country": "Kazakhstan",
    "Connection": "Active"
  },
  {
    "countryCode": "EABR",
    "bankCode": "KZ",
    "branchCode": "ACF",
    "SWIFT Code": "EABRKZKAACF",
    "Bank Name": "EURASIAN DEVELOPMENT BANK",
    "Address": "DOSTYK STR, 220",
    "City": "ALMATY",
    "Branch": "EURASIAN FUND FOR STABILIZATION AND DEVELOPMENT",
    "Postcode": "050051",
    "Country": "Kazakhstan",
    "Connection": "Active"
  },
  {
    "countryCode": "TSES",
    "bankCode": "KZ",
    "branchCode": "ZKA",
    "SWIFT Code": "TSESKZKA",
    "Bank Name": "FIRST HEARTLAND JUSAN BANK JOINT-STOCK COMPANY",
    "Address": "SYGANAK STREET , 24",
    "City": "NUR-SULTAN",
    "Branch": "",
    "Postcode": "020000",
    "Country": "Kazakhstan",
    "Connection": "Active"
  },
  {
    "countryCode": "IRTY",
    "bankCode": "KZ",
    "branchCode": "001",
    "SWIFT Code": "IRTYKZKA001",
    "Bank Name": "FORTEBANK JSC",
    "Address": "DOSTYK , 8/1",
    "City": "ALMATY",
    "Branch": "",
    "Postcode": "010017",
    "Country": "Kazakhstan",
    "Connection": "Active"
  },
  {
    "countryCode": "IRTY",
    "bankCode": "KZ",
    "branchCode": "ZKA",
    "SWIFT Code": "IRTYKZKA",
    "Bank Name": "FORTEBANK JSC",
    "Address": "DOSTYK , 8/1",
    "City": "NUR-SULTAN",
    "Branch": "",
    "Postcode": "010017",
    "Country": "Kazakhstan",
    "Connection": "Active"
  },
  {
    "countryCode": "HSBK",
    "bankCode": "KZ",
    "branchCode": "ZKX",
    "SWIFT Code": "HSBKKZKX",
    "Bank Name": "HALYK BANK OF KAZAKHSTAN",
    "Address": "ABAY AVE , 109 V",
    "City": "ALMATY",
    "Branch": "",
    "Postcode": "050000",
    "Country": "Kazakhstan",
    "Connection": "Active"
  },
  {
    "countryCode": "HSBK",
    "bankCode": "KZ",
    "branchCode": "TSY",
    "SWIFT Code": "HSBKKZKXTSY",
    "Bank Name": "HALYK BANK OF KAZAKHSTAN",
    "Address": "ROZYBAKIEV STREET , 97",
    "City": "ALMATY",
    "Branch": "TREASURY DEPARTMENT",
    "Postcode": "480046",
    "Country": "Kazakhstan",
    "Connection": "Active"
  },
  {
    "countryCode": "ICBK",
    "bankCode": "KZ",
    "branchCode": "ZKX",
    "SWIFT Code": "ICBKKZKX",
    "Bank Name": "INDUSTRIAL AND COMMERCIAL BANK OF CHINA",
    "Address": "ABAY STR, TURGUT OZAL INT, 150/230, 846 BUILDING, 7 BLOCK",
    "City": "ALMATY",
    "Branch": "",
    "Postcode": "050046",
    "Country": "Kazakhstan",
    "Connection": "Active"
  },
  {
    "countryCode": "ICBK",
    "bankCode": "KZ",
    "branchCode": "CLR",
    "SWIFT Code": "ICBKKZKXCLR",
    "Bank Name": "INDUSTRIAL AND COMMERCIAL BANK OF CHINA",
    "Address": "ABAY, 150, FLOOR 1, GAUHARTAS",
    "City": "ALMATY",
    "Branch": "ICBC ALMATY (RMB CLEARING)",
    "Postcode": "050000",
    "Country": "Kazakhstan",
    "Connection": "Active"
  },
  {
    "countryCode": "ZAJS",
    "bankCode": "KZ",
    "branchCode": "Z22",
    "SWIFT Code": "ZAJSKZ22",
    "Bank Name": "ISLAMIC BANK 'ZAMAN-BANK' JSC",
    "Address": "MASHUR ZHUSIP STR , 111A",
    "City": "EKIBASTUZ",
    "Branch": "",
    "Postcode": "141206",
    "Country": "Kazakhstan",
    "Connection": "Active"
  },
  {
    "countryCode": "HCSK",
    "bankCode": "KZ",
    "branchCode": "ZKA",
    "SWIFT Code": "HCSKKZKA",
    "Bank Name": "JOINT STOCK COMPANY 'OTBASY BANK' HOUSE CONSTRUCTION SAVINGS BANK",
    "Address": "ABYLAI KHAN AVENUE , 91",
    "City": "ALMATY",
    "Branch": "",
    "Postcode": "050000",
    "Country": "Kazakhstan",
    "Connection": "Active"
  },
  {
    "countryCode": "ATYN",
    "bankCode": "KZ",
    "branchCode": "ZKA",
    "SWIFT Code": "ATYNKZKA",
    "Bank Name": "JSC 'ALTYN BANK' (SB OF CHINA CITIC BANK CORPORATION)",
    "Address": "ABAY AVENUE , 109B",
    "City": "ALMATY",
    "Branch": "",
    "Postcode": "050000",
    "Country": "Kazakhstan",
    "Connection": "Active"
  },
  {
    "countryCode": "KCJB",
    "bankCode": "KZ",
    "branchCode": "ZKX",
    "SWIFT Code": "KCJBKZKX",
    "Bank Name": "JSC 'BANK CENTERCREDIT'",
    "Address": "AL FARABI AVE. , 38",
    "City": "ALMATY",
    "Branch": "",
    "Postcode": "050059",
    "Country": "Kazakhstan",
    "Connection": "Active"
  },
  {
    "countryCode": "INLM",
    "bankCode": "KZ",
    "branchCode": "ZKA",
    "SWIFT Code": "INLMKZKA",
    "Bank Name": "JSC HOME CREDIT BANK",
    "Address": "NURSULTAN NAZARBAYEV AVENUE , 248",
    "City": "ALMATY",
    "Branch": "",
    "Postcode": "050059",
    "Country": "Kazakhstan",
    "Connection": "Active"
  },
  {
    "countryCode": "CASP",
    "bankCode": "KZ",
    "branchCode": "ZKA",
    "SWIFT Code": "CASPKZKA",
    "Bank Name": "KASPI BANK JSC",
    "Address": "NAURYZBAI BATYR STREET , 154A",
    "City": "ALMATY",
    "Branch": "",
    "Postcode": "050013",
    "Country": "Kazakhstan",
    "Connection": "Active"
  },
  {
    "countryCode": "KICE",
    "bankCode": "KZ",
    "branchCode": "ZKX",
    "SWIFT Code": "KICEKZKX",
    "Bank Name": "KAZAKHSTAN STOCK EXCHANGE",
    "Address": "BAIZAKOV STR, 280 FLOOR 8, ALMATY, TOWERS, NORTHERN TOWER",
    "City": "ALMATY",
    "Branch": "",
    "Postcode": "050040",
    "Country": "Kazakhstan",
    "Connection": "Active"
  },
  {
    "countryCode": "KZIB",
    "bankCode": "KZ",
    "branchCode": "ZKA",
    "SWIFT Code": "KZIBKZKA",
    "Bank Name": "KAZAKHSTAN-ZIRAAT INTERNATIONAL BANK",
    "Address": "KLOCHKOV STREET , 132",
    "City": "ALMATY",
    "Branch": "",
    "Postcode": "480057",
    "Country": "Kazakhstan",
    "Connection": "Active"
  },
  {
    "countryCode": "KJSC",
    "bankCode": "KZ",
    "branchCode": "Z22",
    "SWIFT Code": "KJSCKZ22",
    "Bank Name": "KAZPOST JOINT STOCK COMPANY",
    "Address": "BEIBITSHILIK ST., 37",
    "City": "NUR-SULTAN",
    "Branch": "",
    "Postcode": "010000",
    "Country": "Kazakhstan",
    "Connection": "Active"
  },
  {
    "countryCode": "IRTE",
    "bankCode": "KZ",
    "branchCode": "ZK2",
    "SWIFT Code": "IRTEKZK2",
    "Bank Name": "LIMITED LIABILITY PARTNERSHIP 'IRBIS TECH'",
    "Address": "ZHAROKOVA STREET, 217, BOSTANDYK DISTRICT",
    "City": "ALMATY",
    "Branch": "",
    "Postcode": "050057",
    "Country": "Kazakhstan",
    "Connection": "Active"
  },
  {
    "countryCode": "NBRK",
    "bankCode": "KZ",
    "branchCode": "ZKX",
    "SWIFT Code": "NBRKKZKX",
    "Bank Name": "NATIONAL BANK OF KAZAKHSTAN",
    "Address": "DISTRICT KOKTEM , 3 21",
    "City": "ALMATY",
    "Branch": "",
    "Postcode": "480070",
    "Country": "Kazakhstan",
    "Connection": "Active"
  },
  {
    "countryCode": "NURS",
    "bankCode": "KZ",
    "branchCode": "ZKX",
    "SWIFT Code": "NURSKZKX",
    "Bank Name": "NURBANK JOINT STOCK COMPANY",
    "Address": "ABAY AVENU , 10V",
    "City": "ALMATY",
    "Branch": "",
    "Postcode": "050010",
    "Country": "Kazakhstan",
    "Connection": "Active"
  },
  {
    "countryCode": "SENI",
    "bankCode": "KZ",
    "branchCode": "ZKA",
    "SWIFT Code": "SENIKZKA",
    "Bank Name": "QAZAQ BANKI JOINT STOCK COMPANY",
    "Address": "FURMANOV , 279",
    "City": "ALMATY",
    "Branch": "",
    "Postcode": "050059",
    "Country": "Kazakhstan",
    "Connection": "Active"
  },
  {
    "countryCode": "SHBK",
    "bankCode": "KZ",
    "branchCode": "ZKA",
    "SWIFT Code": "SHBKKZKA",
    "Bank Name": "SHINHAN BANK KAZAKHSTAN JSC",
    "Address": "DOSTYK AVE. , 38, MEDEU DISTRICT",
    "City": "ALMATY",
    "Branch": "",
    "Postcode": "050010",
    "Country": "Kazakhstan",
    "Connection": "Active"
  },
  {
    "countryCode": "VTBA",
    "bankCode": "KZ",
    "branchCode": "ZKZ",
    "SWIFT Code": "VTBAKZKZ",
    "Bank Name": "VTB BANK (KAZAKHSTAN)",
    "Address": "TEMIRYAZEVA ST. , 26/29",
    "City": "ALMATY",
    "Branch": "",
    "Postcode": "050040",
    "Country": "Kazakhstan",
    "Connection": "Active"
  }
]
module.exports = kazakhstan
