const kenya = [
  {
    "bankCode": "BARC",
    "countryCode": "KE",
    "branchCode": "ELD",
    "SWIFT Code": "BARCKENXELD",
    "Bank Name": "ABSA BANK KENYA PLC",
    "Address": "",
    "City": "ELDORET",
    "Branch": "ELDORET BRANCH",
    "Postcode": "30100",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "BARC",
    "countryCode": "KE",
    "branchCode": "MDR",
    "SWIFT Code": "BARCKENXMDR",
    "Bank Name": "ABSA BANK KENYA PLC",
    "Address": "",
    "City": "MOMBASA",
    "Branch": "DIGO ROAD MOMBASA",
    "Postcode": "80100",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "BARC",
    "countryCode": "KE",
    "branchCode": "MNR",
    "SWIFT Code": "BARCKENXMNR",
    "Bank Name": "ABSA BANK KENYA PLC",
    "Address": "NKRUMAH ROAD",
    "City": "MOMBASA",
    "Branch": "NKRUMAH ROAD BRANCH",
    "Postcode": "80100",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "BARC",
    "countryCode": "KE",
    "branchCode": "ENX",
    "SWIFT Code": "BARCKENX",
    "Bank Name": "ABSA BANK KENYA PLC",
    "Address": "THE WEST END BUILDING, WAIYAKI WAY",
    "City": "NAIROBI",
    "Branch": "",
    "Postcode": "00100",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "BARC",
    "countryCode": "KE",
    "branchCode": "OCB",
    "SWIFT Code": "BARCKENXOCB",
    "Bank Name": "ABSA BANK KENYA PLC",
    "Address": "",
    "City": "NAIROBI",
    "Branch": "BACK OFFICE PROCESSING CENTRE, BANK HOUSE",
    "Postcode": "00100",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "BARC",
    "countryCode": "KE",
    "branchCode": "NCC",
    "SWIFT Code": "BARCKENXNCC",
    "Bank Name": "ABSA BANK KENYA PLC",
    "Address": "",
    "City": "NAIROBI",
    "Branch": "CARD CENTRE NAIROBI",
    "Postcode": "00100",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "BARC",
    "countryCode": "KE",
    "branchCode": "CBO",
    "SWIFT Code": "BARCKENXCBO",
    "Bank Name": "ABSA BANK KENYA PLC",
    "Address": "THE WEST END BUILDING, WAIYAKI WAY",
    "City": "NAIROBI",
    "Branch": "CUSTODY BUSINESS OPERATIONS",
    "Postcode": "00100",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "BARC",
    "countryCode": "KE",
    "branchCode": "DLR",
    "SWIFT Code": "BARCKENXDLR",
    "Bank Name": "ABSA BANK KENYA PLC",
    "Address": "BARCLAYS PLAZA BUILDING, FLOOR 5, LOITA STREET",
    "City": "NAIROBI",
    "Branch": "DEALERS DEPARTMENT H/O",
    "Postcode": "00100",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "BARC",
    "countryCode": "KE",
    "branchCode": "NDC",
    "SWIFT Code": "BARCKENXNDC",
    "Bank Name": "ABSA BANK KENYA PLC",
    "Address": "MOMBASA ROAD",
    "City": "NAIROBI",
    "Branch": "NAIROBI DISTRIBUTION CENTRE",
    "Postcode": "00100",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "BARC",
    "countryCode": "KE",
    "branchCode": "PIS",
    "SWIFT Code": "BARCKENXPIS",
    "Bank Name": "ABSA BANK KENYA PLC",
    "Address": "",
    "City": "NAIROBI",
    "Branch": "PAYMENTS AND INTERNATIONAL SERVICES",
    "Postcode": "00100",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "BARC",
    "countryCode": "KE",
    "branchCode": "NPB",
    "SWIFT Code": "BARCKENXNPB",
    "Bank Name": "ABSA BANK KENYA PLC",
    "Address": "",
    "City": "NAIROBI",
    "Branch": "PLAZA BUSINESS CENTRE",
    "Postcode": "00100",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "BARC",
    "countryCode": "KE",
    "branchCode": "TPC",
    "SWIFT Code": "BARCKENXTPC",
    "Bank Name": "ABSA BANK KENYA PLC",
    "Address": "STANDARD BUILDING, KENYATTA AVENUE",
    "City": "NAIROBI",
    "Branch": "TRADE PROCESSING CENTRE",
    "Postcode": "00200",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "BARC",
    "countryCode": "KE",
    "branchCode": "VPC",
    "SWIFT Code": "BARCKENXVPC",
    "Bank Name": "ABSA BANK KENYA PLC",
    "Address": "AVON CENTER, ENTREPRISE ROAD",
    "City": "NAIROBI",
    "Branch": "VOUCHER PROCESSING CENTRE",
    "Postcode": "00200",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "ABNG",
    "countryCode": "KE",
    "branchCode": "ENA",
    "SWIFT Code": "ABNGKENA",
    "Bank Name": "ACCESS BANK (KENYA) PLC",
    "Address": "TRANSNATIONAL PLAZA, FLOOR 2, CITY HALL WAY",
    "City": "NAIROBI",
    "Branch": "",
    "Postcode": "00100",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "ABCL",
    "countryCode": "KE",
    "branchCode": "ENA",
    "SWIFT Code": "ABCLKENA",
    "Bank Name": "AFRICAN BANKING CORPORATION LTD",
    "Address": "ABC BANK HOUSE, WOODVALE GROVE, WESTLANDS",
    "City": "NAIROBI",
    "Branch": "",
    "Postcode": "00800",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "AFRI",
    "countryCode": "KE",
    "branchCode": "002",
    "SWIFT Code": "AFRIKENX002",
    "Bank Name": "BANK OF AFRICA KENYA LTD",
    "Address": "",
    "City": "MOMBASA",
    "Branch": "MOMBASA BRANCH",
    "Postcode": "80100",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "AFRI",
    "countryCode": "KE",
    "branchCode": "ENX",
    "SWIFT Code": "AFRIKENX",
    "Bank Name": "BANK OF AFRICA KENYA LTD",
    "Address": "REINSURANCE PLAZA, TAIFA ROAD",
    "City": "NAIROBI",
    "Branch": "",
    "Postcode": "00400",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "BARB",
    "countryCode": "KE",
    "branchCode": "ELD",
    "SWIFT Code": "BARBKENAELD",
    "Bank Name": "BANK OF BARODA (KENYA) LTD",
    "Address": "CHAROTAR PATEL, PLAZA MOI STREET",
    "City": "ELDORET",
    "Branch": "ELDORET BRANCH",
    "Postcode": "30100",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "BARB",
    "countryCode": "KE",
    "branchCode": "KAK",
    "SWIFT Code": "BARBKENAKAK",
    "Bank Name": "BANK OF BARODA (KENYA) LTD",
    "Address": "KENYATTA AVENUE",
    "City": "KAKAMEGA",
    "Branch": "KAKAMEGA BRANCH",
    "Postcode": "50100",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "BARB",
    "countryCode": "KE",
    "branchCode": "KIS",
    "SWIFT Code": "BARBKENAKIS",
    "Bank Name": "BANK OF BARODA (KENYA) LTD",
    "Address": "CENTRAL SQUARE",
    "City": "KISUMU",
    "Branch": "KISUMU BRANCH",
    "Postcode": "40100",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "BARB",
    "countryCode": "KE",
    "branchCode": "MER",
    "SWIFT Code": "BARBKENAMER",
    "Bank Name": "BANK OF BARODA (KENYA) LTD",
    "Address": "ROCK BUILDING, B11/72 JURI NCHEKE STREET",
    "City": "MERU",
    "Branch": "MERU BRANCH",
    "Postcode": "60200",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "BARB",
    "countryCode": "KE",
    "branchCode": "MOM",
    "SWIFT Code": "BARBKENAMOM",
    "Bank Name": "BANK OF BARODA (KENYA) LTD",
    "Address": "DIGO ROAD",
    "City": "MOMBASA",
    "Branch": "DIGO ROAD, MOMBASA",
    "Postcode": "80100",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "BARB",
    "countryCode": "KE",
    "branchCode": "MRN",
    "SWIFT Code": "BARBKENAMRN",
    "Bank Name": "BANK OF BARODA (KENYA) LTD",
    "Address": "AIRTEL BLDG, SOMAK HOUSE, FLOOR GF, MOMBASA ROAD",
    "City": "MOMBASA",
    "Branch": "MOMBASA ROAD BRANCH",
    "Postcode": "00500",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "BARB",
    "countryCode": "KE",
    "branchCode": "NYA",
    "SWIFT Code": "BARBKENANYA",
    "Bank Name": "BANK OF BARODA (KENYA) LTD",
    "Address": "TEXAS TOWERS, FLOOR GF, NYALI ROAD, NAYALI MO",
    "City": "MOMBASA",
    "Branch": "NYALI BRANCH, MOMBASA, KENYA",
    "Postcode": "80106",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "BARB",
    "countryCode": "KE",
    "branchCode": "ENA",
    "SWIFT Code": "BARBKENA",
    "Bank Name": "BANK OF BARODA (KENYA) LTD",
    "Address": "BARODA HOUSE, 29 KOINANGE STREET",
    "City": "NAIROBI",
    "Branch": "",
    "Postcode": "00100",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "BARB",
    "countryCode": "KE",
    "branchCode": "DIA",
    "SWIFT Code": "BARBKENADIA",
    "Bank Name": "BANK OF BARODA (KENYA) LTD",
    "Address": "HIGHRIDGE SHOPPING CENTRE, MASARI ROAD, PARKLANDS, WESTLANDS",
    "City": "NAIROBI",
    "Branch": "DIAMOND PLAZA",
    "Postcode": "00300",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "BARB",
    "countryCode": "KE",
    "branchCode": "IND",
    "SWIFT Code": "BARBKENAIND",
    "Bank Name": "BANK OF BARODA (KENYA) LTD",
    "Address": "ENTERPRISE ROAD, INDUSTRIAL AREA",
    "City": "NAIROBI",
    "Branch": "INDUSTRIAL AREA BR.",
    "Postcode": "00100",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "BARB",
    "countryCode": "KE",
    "branchCode": "NMO",
    "SWIFT Code": "BARBKENANMO",
    "Bank Name": "BANK OF BARODA (KENYA) LTD",
    "Address": "29 KOINANGE STREET",
    "City": "NAIROBI",
    "Branch": "NAIROBI MAIN",
    "Postcode": "00100",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "BARB",
    "countryCode": "KE",
    "branchCode": "SAR",
    "SWIFT Code": "BARBKENASAR",
    "Bank Name": "BANK OF BARODA (KENYA) LTD",
    "Address": "SARIT CENTRE, FLOOR LG, WESTLANDS",
    "City": "NAIROBI",
    "Branch": "SARIT CENTRE",
    "Postcode": "00606",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "BARB",
    "countryCode": "KE",
    "branchCode": "NAK",
    "SWIFT Code": "BARBKENANAK",
    "Bank Name": "BANK OF BARODA (KENYA) LTD",
    "Address": "VICKERS HOUSE, KENYATTA AVENUE",
    "City": "NAKURU",
    "Branch": "NAKURU BRANCH",
    "Postcode": "20100",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "BARB",
    "countryCode": "KE",
    "branchCode": "THI",
    "SWIFT Code": "BARBKENATHI",
    "Bank Name": "BANK OF BARODA (KENYA) LTD",
    "Address": "THIKA BRANCH KENYA HIGHWAY",
    "City": "THIKA",
    "Branch": "THIKA BRANCH",
    "Postcode": "00100",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "BKID",
    "countryCode": "KE",
    "branchCode": "ELD",
    "SWIFT Code": "BKIDKENAELD",
    "Bank Name": "BANK OF INDIA",
    "Address": "",
    "City": "ELDORET",
    "Branch": "ELDORET",
    "Postcode": "30100",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "BKID",
    "countryCode": "KE",
    "branchCode": "MSA",
    "SWIFT Code": "BKIDKENAMSA",
    "Bank Name": "BANK OF INDIA",
    "Address": "BANK OF INDIA BUILDING, NKRUMAH ROAD",
    "City": "MOMBASA",
    "Branch": "MOMBASA BR",
    "Postcode": "90684",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "BKID",
    "countryCode": "KE",
    "branchCode": "ENA",
    "SWIFT Code": "BKIDKENA",
    "Bank Name": "BANK OF INDIA",
    "Address": "KENYATTA AVENUE",
    "City": "NAIROBI",
    "Branch": "",
    "Postcode": "00100",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "BKID",
    "countryCode": "KE",
    "branchCode": "IAB",
    "SWIFT Code": "BKIDKENAIAB",
    "Bank Name": "BANK OF INDIA",
    "Address": "IDEAL CORNER, LUSAKA ROAD",
    "City": "NAIROBI",
    "Branch": "INDUSTRIAL AREA BR",
    "Postcode": "00500",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "BKID",
    "countryCode": "KE",
    "branchCode": "WST",
    "SWIFT Code": "BKIDKENAWST",
    "Bank Name": "BANK OF INDIA",
    "Address": "PROGRESSIVE PARK TOWERS, NAKUMATT UKAY",
    "City": "NAIROBI",
    "Branch": "WESTLANDS BR",
    "Postcode": "00800",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "CRMF",
    "countryCode": "KE",
    "branchCode": "ENA",
    "SWIFT Code": "CRMFKENA",
    "Bank Name": "CARITAS MICROFINANCE BANK LIMITED",
    "Address": "CARDINAL MAURICE OTUNGA PLAZA, KAUNDA STREET",
    "City": "NAIROBI",
    "Branch": "",
    "Postcode": "00100",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "CBKE",
    "countryCode": "KE",
    "branchCode": "ENX",
    "SWIFT Code": "CBKEKENX",
    "Bank Name": "CENTRAL BANK OF KENYA",
    "Address": "HAILE SELASSIE AVENUE",
    "City": "NAIROBI",
    "Branch": "",
    "Postcode": "00200",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "CBKE",
    "countryCode": "KE",
    "branchCode": "ENB",
    "SWIFT Code": "CBKEKENB",
    "Bank Name": "CENTRAL BANK OF KENYA",
    "Address": "BANKI KUU, HAILE SELASSIE AVENUE",
    "City": "NAIROBI",
    "Branch": "",
    "Postcode": "00200",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "CBKE",
    "countryCode": "KE",
    "branchCode": "BKG",
    "SWIFT Code": "CBKEKENXBKG",
    "Bank Name": "CENTRAL BANK OF KENYA",
    "Address": "HAILE SELASSIE AVENUE",
    "City": "NAIROBI",
    "Branch": "BANKING DIVISION",
    "Postcode": "00200",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "CBKE",
    "countryCode": "KE",
    "branchCode": "CNY",
    "SWIFT Code": "CBKEKENXCNY",
    "Bank Name": "CENTRAL BANK OF KENYA",
    "Address": "HAILE SELASSIE AVENUE",
    "City": "NAIROBI",
    "Branch": "CURRENCY DIVISION",
    "Postcode": "00200",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "CBKE",
    "countryCode": "KE",
    "branchCode": "NDO",
    "SWIFT Code": "CBKEKENXNDO",
    "Bank Name": "CENTRAL BANK OF KENYA",
    "Address": "HAILE SELASSIE AVENUE",
    "City": "NAIROBI",
    "Branch": "NATIONAL DEBT DIVISION",
    "Postcode": "00200",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "CDSN",
    "countryCode": "KE",
    "branchCode": "ENA",
    "SWIFT Code": "CDSNKENA",
    "Bank Name": "CENTRAL DEPOSITORY AND SETTLEMENT CORPORATION",
    "Address": "NATION CENTRE , 10TH, KIMATHI, KIMATHI",
    "City": "NAIROBI",
    "Branch": "",
    "Postcode": "00100",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "CHFI",
    "countryCode": "KE",
    "branchCode": "ENX",
    "SWIFT Code": "CHFIKENX",
    "Bank Name": "CHOICE MICROFINANCE BANK LIMITED",
    "Address": "FLOOR 1, SIRON PLACE",
    "City": "NAIROBI",
    "Branch": "",
    "Postcode": "00100",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "CITI",
    "countryCode": "KE",
    "branchCode": "ENA",
    "SWIFT Code": "CITIKENA",
    "Bank Name": "CITIBANK N.A. NAIROBI",
    "Address": "CITIBANK HOUSE, UPPERHILL ROAD",
    "City": "NAIROBI",
    "Branch": "",
    "Postcode": "00100",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "CITI",
    "countryCode": "KE",
    "branchCode": "TRD",
    "SWIFT Code": "CITIKENATRD",
    "Bank Name": "CITIBANK N.A. NAIROBI",
    "Address": "",
    "City": "NAIROBI",
    "Branch": "TRADE SERVICES DEPARTMENT",
    "Postcode": "00100",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "MYBK",
    "countryCode": "KE",
    "branchCode": "ENA",
    "SWIFT Code": "MYBKKENA",
    "Bank Name": "COMMERCIAL INTERNATIONAL BANK (CIB) KENYA LIMITED",
    "Address": "KAM HOUSE, FLOOR MEZZ, 2051 MWANZI ROAD, WESTLANDS",
    "City": "NAIROBI",
    "Branch": "",
    "Postcode": "00600",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "CONK",
    "countryCode": "KE",
    "branchCode": "ENA",
    "SWIFT Code": "CONKKENA",
    "Bank Name": "CONSOLIDATED BANK OF KENYA LTD",
    "Address": "CONSOLIDATED BANK HOUSE, KOINANGE STREET",
    "City": "NAIROBI",
    "Branch": "",
    "Postcode": "00200",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "CRBT",
    "countryCode": "KE",
    "branchCode": "ENA",
    "SWIFT Code": "CRBTKENA",
    "Bank Name": "CREDIT BANK PLC",
    "Address": "MERCANTILE HOUSE, KOINANGE STREET, CITY SQUARE",
    "City": "NAIROBI",
    "Branch": "",
    "Postcode": "00200",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "DEVK",
    "countryCode": "KE",
    "branchCode": "ENA",
    "SWIFT Code": "DEVKKENA",
    "Bank Name": "DEVELOPMENT BANK OF KENYA LIMITED",
    "Address": "FINANCE HOUSE, LOITA STREET",
    "City": "NAIROBI",
    "Branch": "",
    "Postcode": "00100",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "DTKE",
    "countryCode": "KE",
    "branchCode": "ENA",
    "SWIFT Code": "DTKEKENA",
    "Bank Name": "DIAMOND TRUST BANK KENYA LIMITED",
    "Address": "NATION CENTRE, FLOOR 8, KIMATHI STREET",
    "City": "NAIROBI",
    "Branch": "HEAD OFFICE",
    "Postcode": "00200",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "DUIB",
    "countryCode": "KE",
    "branchCode": "ENA",
    "SWIFT Code": "DUIBKENA",
    "Bank Name": "DIB BANK KENYA LTD",
    "Address": "SANDVIEW, FLOOR 2, 04 BUNYALA/LOWER HILL JUNCTION, UPPER HILL",
    "City": "NAIROBI",
    "Branch": "",
    "Postcode": "00200",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "ESAT",
    "countryCode": "KE",
    "branchCode": "ENA",
    "SWIFT Code": "ESATKENA",
    "Bank Name": "EASTERN AND SOUTHERN AFRICAN TRADE AND DEVELOPMENTBANK",
    "Address": "LENANA PLACE, FLOOR 1, 197 LENANA ROAD",
    "City": "NAIROBI",
    "Branch": "",
    "Postcode": "00100",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "ECOC",
    "countryCode": "KE",
    "branchCode": "ENA",
    "SWIFT Code": "ECOCKENA",
    "Bank Name": "ECOBANK KENYA LTD",
    "Address": "FEDHA TOWERS, FLOOR 5, MUINDI MBINGU STREET",
    "City": "NAIROBI",
    "Branch": "",
    "Postcode": "00100",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "EQBL",
    "countryCode": "KE",
    "branchCode": "ENA",
    "SWIFT Code": "EQBLKENA",
    "Bank Name": "EQUITY BANK (KENYA) LIMITED",
    "Address": "EQUITY CENTRE, FLOOR 9, HOSPITAL ROAD",
    "City": "NAIROBI",
    "Branch": "",
    "Postcode": "00200",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "FABL",
    "countryCode": "KE",
    "branchCode": "ENA",
    "SWIFT Code": "FABLKENA",
    "Bank Name": "FAMILY BANK LIMITED",
    "Address": "FOURWAY TOWERS, MUINDI MBINGU STREET",
    "City": "NAIROBI",
    "Branch": "",
    "Postcode": "00200",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "FAUM",
    "countryCode": "KE",
    "branchCode": "ENA",
    "SWIFT Code": "FAUMKENA",
    "Bank Name": "FAULU MICROFINANCE BANK LIMITED",
    "Address": "FLOOR GF, NGONG LANE, OFF NGONG ROAD",
    "City": "NAIROBI",
    "Branch": "FAULU HEAD OFFICE",
    "Postcode": "00200",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "GTBI",
    "countryCode": "KE",
    "branchCode": "ENA",
    "SWIFT Code": "GTBIKENA",
    "Bank Name": "GUARANTY TRUST BANK (KENYA) LTD",
    "Address": "SKY PARK PLAZA, WOODVALE CLOSE, WESTLANDS",
    "City": "NAIROBI",
    "Branch": "",
    "Postcode": "00200",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "GUAR",
    "countryCode": "KE",
    "branchCode": "ENA",
    "SWIFT Code": "GUARKENA",
    "Bank Name": "GUARDIAN BANK LIMITED",
    "Address": "GUARDIAN CENTRE, BIASHARA STREET",
    "City": "NAIROBI",
    "Branch": "",
    "Postcode": "67437",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "GAFR",
    "countryCode": "KE",
    "branchCode": "ENA",
    "SWIFT Code": "GAFRKENA",
    "Bank Name": "GULF AFRICAN BANK LTD",
    "Address": "GEMINIA INSURANCE PLAZA, KILIMANJARO AVENUE, UPPER HILL",
    "City": "NAIROBI",
    "Branch": "",
    "Postcode": "00100",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "HBZU",
    "countryCode": "KE",
    "branchCode": "ENA",
    "SWIFT Code": "HBZUKENA",
    "Bank Name": "HABIB BANK AG ZURICH",
    "Address": "HABIB HOUSE, KOINANGE STREET",
    "City": "NAIROBI",
    "Branch": "",
    "Postcode": "00100",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "HFCO",
    "countryCode": "KE",
    "branchCode": "ENA",
    "SWIFT Code": "HFCOKENA",
    "Bank Name": "HFC LIMITED",
    "Address": "REHANI HOUSE, 06 KOINANGE STREET",
    "City": "NAIROBI",
    "Branch": "",
    "Postcode": "00100",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "IMBL",
    "countryCode": "KE",
    "branchCode": "ENA",
    "SWIFT Code": "IMBLKENA",
    "Bank Name": "I AND M BANK LTD",
    "Address": "I AND M BANK HOUSE, 2ND NGONG AVENUE",
    "City": "NAIROBI",
    "Branch": "",
    "Postcode": "00100",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "IMBL",
    "countryCode": "KE",
    "branchCode": "FTR",
    "SWIFT Code": "IMBLKENAFTR",
    "Bank Name": "I AND M BANK LTD",
    "Address": "I AND M TOWERS, KENYATTA AVENUE",
    "City": "NAIROBI",
    "Branch": "FUNDS TRANSFER DEPARTMENT",
    "Postcode": "00100",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "IMBL",
    "countryCode": "KE",
    "branchCode": "STL",
    "SWIFT Code": "IMBLKENASTL",
    "Bank Name": "I AND M BANK LTD",
    "Address": "I AND M BANK HOUSE, 2ND NGONG ROAD",
    "City": "NAIROBI",
    "Branch": "SETTLEMENT DEPARTMENT",
    "Postcode": "00100",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "IMBL",
    "countryCode": "KE",
    "branchCode": "TRD",
    "SWIFT Code": "IMBLKENATRD",
    "Bank Name": "I AND M BANK LTD",
    "Address": "JETHALAL TOWERS, BIASHARA STREET",
    "City": "NAIROBI",
    "Branch": "TRADE FINANCE DEPARTMENT",
    "Postcode": "00100",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "KCBL",
    "countryCode": "KE",
    "branchCode": "080",
    "SWIFT Code": "KCBLKENX080",
    "Bank Name": "KCB BANK KENYA LIMITED",
    "Address": "",
    "City": "MOMBASA",
    "Branch": "TREASURY SQUARE",
    "Postcode": "80100",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "KCBL",
    "countryCode": "KE",
    "branchCode": "TFS",
    "SWIFT Code": "KCBLKENXTFS",
    "Bank Name": "KCB BANK KENYA LIMITED",
    "Address": "KENCOM HOUSE, MOI AVENUE",
    "City": "NAIROBI",
    "Branch": "",
    "Postcode": "00100",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "KCBL",
    "countryCode": "KE",
    "branchCode": "CUS",
    "SWIFT Code": "KCBLKENXCUS",
    "Bank Name": "KCB BANK KENYA LIMITED",
    "Address": "PIEDMONT PLAZA, NGONG ROAD",
    "City": "NAIROBI",
    "Branch": "",
    "Postcode": "00100",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "KCBL",
    "countryCode": "KE",
    "branchCode": "DMM",
    "SWIFT Code": "KCBLKENXDMM",
    "Bank Name": "KCB BANK KENYA LIMITED",
    "Address": "",
    "City": "NAIROBI",
    "Branch": "DOMESTIC MONEY MARKET UNIT",
    "Postcode": "00100",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "KCBL",
    "countryCode": "KE",
    "branchCode": "012",
    "SWIFT Code": "KCBLKENX012",
    "Bank Name": "KCB BANK KENYA LIMITED",
    "Address": "",
    "City": "NAIROBI",
    "Branch": "GIGIRI-UNEP BRANCH",
    "Postcode": "00100",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "KCBL",
    "countryCode": "KE",
    "branchCode": "ENX",
    "SWIFT Code": "KCBLKENX",
    "Bank Name": "KCB BANK KENYA LIMITED",
    "Address": "KENCOM HOUSE, FLOOR 7, MOI AVENUE",
    "City": "NAIROBI",
    "Branch": "HEAD OFFICE",
    "Postcode": "00100",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "KCBL",
    "countryCode": "KE",
    "branchCode": "002",
    "SWIFT Code": "KCBLKENX002",
    "Bank Name": "KCB BANK KENYA LIMITED",
    "Address": "",
    "City": "NAIROBI",
    "Branch": "INDUSTRIAL AREA",
    "Postcode": "00100",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "KCBL",
    "countryCode": "KE",
    "branchCode": "005",
    "SWIFT Code": "KCBLKENX005",
    "Bank Name": "KCB BANK KENYA LIMITED",
    "Address": "",
    "City": "NAIROBI",
    "Branch": "KIPANDE HOUSE",
    "Postcode": "00100",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "KCBL",
    "countryCode": "KE",
    "branchCode": "077",
    "SWIFT Code": "KCBLKENX077",
    "Bank Name": "KCB BANK KENYA LIMITED",
    "Address": "",
    "City": "NAIROBI",
    "Branch": "KISUMU MAIN",
    "Postcode": "00100",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "KCBL",
    "countryCode": "KE",
    "branchCode": "017",
    "SWIFT Code": "KCBLKENX017",
    "Bank Name": "KCB BANK KENYA LIMITED",
    "Address": "MOI AVENUE",
    "City": "NAIROBI",
    "Branch": "MOI AVENUE",
    "Postcode": "00100",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "KCBL",
    "countryCode": "KE",
    "branchCode": "TMK",
    "SWIFT Code": "KCBLKENXTMK",
    "Bank Name": "KCB BANK KENYA LIMITED",
    "Address": "",
    "City": "NAIROBI",
    "Branch": "TREASURY",
    "Postcode": "00100",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "KWMI",
    "countryCode": "KE",
    "branchCode": "ENX",
    "SWIFT Code": "KWMIKENX",
    "Bank Name": "KENYA WOMEN MICROFINANCE BANK",
    "Address": "AKIRA HOUSE, FLOOR 1, 4179 KIAMBERE ROAD, UPPER HILL",
    "City": "NAIROBI",
    "Branch": "",
    "Postcode": "00506",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "CIFI",
    "countryCode": "KE",
    "branchCode": "ENA",
    "SWIFT Code": "CIFIKENA",
    "Bank Name": "KINGDOM BANK LTD",
    "Address": "KINGDOM BANK TOWERS, ARWINGS KHODHEK ROAD, KILIMANI",
    "City": "NAIROBI",
    "Branch": "",
    "Postcode": "00400",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "MORB",
    "countryCode": "KE",
    "branchCode": "ENA",
    "SWIFT Code": "MORBKENA",
    "Bank Name": "M-ORIENTAL BANK LTD",
    "Address": "FINANCE HOUSE, KOINANGE STREET",
    "City": "NAIROBI",
    "Branch": "",
    "Postcode": "00100",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "MIEK",
    "countryCode": "KE",
    "branchCode": "ENA",
    "SWIFT Code": "MIEKKENA",
    "Bank Name": "MIDDLE EAST BANK KENYA LTD",
    "Address": "MEBANK TOWER, MILIMANI ROAD",
    "City": "NAIROBI",
    "Branch": "",
    "Postcode": "00100",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "MMTS",
    "countryCode": "KE",
    "branchCode": "ENA",
    "SWIFT Code": "MMTSKENA",
    "Bank Name": "MOBEX MONEY TRANSFER SERVICES LIMITED",
    "Address": "PARK PLACE, 2 PARK PLACE",
    "City": "NAIROBI",
    "Branch": "",
    "Postcode": "",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "NBKE",
    "countryCode": "KE",
    "branchCode": "ENX",
    "SWIFT Code": "NBKEKENX",
    "Bank Name": "NATIONAL BANK OF KENYA LTD.",
    "Address": "NATIONAL BANK BUILDING, FLOOR 2ND, HARAMBEE AVENUE",
    "City": "NAIROBI",
    "Branch": "",
    "Postcode": "00200",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "NBKE",
    "countryCode": "KE",
    "branchCode": "302",
    "SWIFT Code": "NBKEKENX302",
    "Bank Name": "NATIONAL BANK OF KENYA LTD.",
    "Address": "",
    "City": "NAIROBI",
    "Branch": "AWENDO BRANCH",
    "Postcode": "00100",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "NBKE",
    "countryCode": "KE",
    "branchCode": "957",
    "SWIFT Code": "NBKEKENX957",
    "Bank Name": "NATIONAL BANK OF KENYA LTD.",
    "Address": "",
    "City": "NAIROBI",
    "Branch": "BUNGOMA BRANCH",
    "Postcode": "00100",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "NBKE",
    "countryCode": "KE",
    "branchCode": "828",
    "SWIFT Code": "NBKEKENX828",
    "Bank Name": "NATIONAL BANK OF KENYA LTD.",
    "Address": "",
    "City": "NAIROBI",
    "Branch": "BUSIA BRANCH",
    "Postcode": "00100",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "NBKE",
    "countryCode": "KE",
    "branchCode": "310",
    "SWIFT Code": "NBKEKENX310",
    "Bank Name": "NATIONAL BANK OF KENYA LTD.",
    "Address": "",
    "City": "NAIROBI",
    "Branch": "CORPORATE DIVISION",
    "Postcode": "00100",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "NBKE",
    "countryCode": "KE",
    "branchCode": "789",
    "SWIFT Code": "NBKEKENX789",
    "Bank Name": "NATIONAL BANK OF KENYA LTD.",
    "Address": "",
    "City": "NAIROBI",
    "Branch": "ELDORET BRANCH",
    "Postcode": "00100",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "NBKE",
    "countryCode": "KE",
    "branchCode": "711",
    "SWIFT Code": "NBKEKENX711",
    "Bank Name": "NATIONAL BANK OF KENYA LTD.",
    "Address": "",
    "City": "NAIROBI",
    "Branch": "HARAMBEE AVENUE BRANCH",
    "Postcode": "00100",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "NBKE",
    "countryCode": "KE",
    "branchCode": "808",
    "SWIFT Code": "NBKEKENX808",
    "Bank Name": "NATIONAL BANK OF KENYA LTD.",
    "Address": "",
    "City": "NAIROBI",
    "Branch": "HILL PLAZA BRANCH",
    "Postcode": "00200",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "NBKE",
    "countryCode": "KE",
    "branchCode": "329",
    "SWIFT Code": "NBKEKENX329",
    "Bank Name": "NATIONAL BANK OF KENYA LTD.",
    "Address": "",
    "City": "NAIROBI",
    "Branch": "HOSPITAL BRANCH",
    "Postcode": "00100",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "NBKE",
    "countryCode": "KE",
    "branchCode": "965",
    "SWIFT Code": "NBKEKENX965",
    "Bank Name": "NATIONAL BANK OF KENYA LTD.",
    "Address": "",
    "City": "NAIROBI",
    "Branch": "KAPSABET BRANCH",
    "Postcode": "00100",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "NBKE",
    "countryCode": "KE",
    "branchCode": "841",
    "SWIFT Code": "NBKEKENX841",
    "Bank Name": "NATIONAL BANK OF KENYA LTD.",
    "Address": "",
    "City": "NAIROBI",
    "Branch": "KARATINA BRANCH",
    "Postcode": "00100",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "NBKE",
    "countryCode": "KE",
    "branchCode": "725",
    "SWIFT Code": "NBKEKENX725",
    "Bank Name": "NATIONAL BANK OF KENYA LTD.",
    "Address": "",
    "City": "NAIROBI",
    "Branch": "KENYATTA AVENUE BRANCH",
    "Postcode": "00100",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "NBKE",
    "countryCode": "KE",
    "branchCode": "815",
    "SWIFT Code": "NBKEKENX815",
    "Bank Name": "NATIONAL BANK OF KENYA LTD.",
    "Address": "",
    "City": "NAIROBI",
    "Branch": "KISII BRANCH",
    "Postcode": "00100",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "NBKE",
    "countryCode": "KE",
    "branchCode": "761",
    "SWIFT Code": "NBKEKENX761",
    "Bank Name": "NATIONAL BANK OF KENYA LTD.",
    "Address": "",
    "City": "NAIROBI",
    "Branch": "KISUMU BRANCH",
    "Postcode": "00200",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "NBKE",
    "countryCode": "KE",
    "branchCode": "884",
    "SWIFT Code": "NBKEKENX884",
    "Bank Name": "NATIONAL BANK OF KENYA LTD.",
    "Address": "",
    "City": "NAIROBI",
    "Branch": "KITALE BRANCH",
    "Postcode": "00100",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "NBKE",
    "countryCode": "KE",
    "branchCode": "930",
    "SWIFT Code": "NBKEKENX930",
    "Bank Name": "NATIONAL BANK OF KENYA LTD.",
    "Address": "",
    "City": "NAIROBI",
    "Branch": "KITUI BRANCH",
    "Postcode": "00100",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "NBKE",
    "countryCode": "KE",
    "branchCode": "922",
    "SWIFT Code": "NBKEKENX922",
    "Bank Name": "NATIONAL BANK OF KENYA LTD.",
    "Address": "",
    "City": "NAIROBI",
    "Branch": "LIMURU BRANCH",
    "Postcode": "00100",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "NBKE",
    "countryCode": "KE",
    "branchCode": "833",
    "SWIFT Code": "NBKEKENX833",
    "Bank Name": "NATIONAL BANK OF KENYA LTD.",
    "Address": "",
    "City": "NAIROBI",
    "Branch": "MERU BRANCH",
    "Postcode": "00100",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "NBKE",
    "countryCode": "KE",
    "branchCode": "743",
    "SWIFT Code": "NBKEKENX743",
    "Bank Name": "NATIONAL BANK OF KENYA LTD.",
    "Address": "",
    "City": "NAIROBI",
    "Branch": "MOI AVENUE BRANCH",
    "Postcode": "00100",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "NBKE",
    "countryCode": "KE",
    "branchCode": "949",
    "SWIFT Code": "NBKEKENX949",
    "Bank Name": "NATIONAL BANK OF KENYA LTD.",
    "Address": "",
    "City": "NAIROBI",
    "Branch": "MOLO BRANCH",
    "Postcode": "00100",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "NBKE",
    "countryCode": "KE",
    "branchCode": "973",
    "SWIFT Code": "NBKEKENX973",
    "Bank Name": "NATIONAL BANK OF KENYA LTD.",
    "Address": "",
    "City": "NAIROBI",
    "Branch": "MOMBASA MOI BRANCH",
    "Postcode": "00100",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "NBKE",
    "countryCode": "KE",
    "branchCode": "739",
    "SWIFT Code": "NBKEKENX739",
    "Bank Name": "NATIONAL BANK OF KENYA LTD.",
    "Address": "",
    "City": "NAIROBI",
    "Branch": "MOMBASA NKURUMAH BRANCH",
    "Postcode": "00100",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "NBKE",
    "countryCode": "KE",
    "branchCode": "757",
    "SWIFT Code": "NBKEKENX757",
    "Bank Name": "NATIONAL BANK OF KENYA LTD.",
    "Address": "",
    "City": "NAIROBI",
    "Branch": "NAKURU BRANCH",
    "Postcode": "00100",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "NBKE",
    "countryCode": "KE",
    "branchCode": "868",
    "SWIFT Code": "NBKEKENX868",
    "Bank Name": "NATIONAL BANK OF KENYA LTD.",
    "Address": "",
    "City": "NAIROBI",
    "Branch": "NAROK BRANCH",
    "Postcode": "00100",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "NBKE",
    "countryCode": "KE",
    "branchCode": "876",
    "SWIFT Code": "NBKEKENX876",
    "Bank Name": "NATIONAL BANK OF KENYA LTD.",
    "Address": "",
    "City": "NAIROBI",
    "Branch": "NYERI BRANCH",
    "Postcode": "00100",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "NBKE",
    "countryCode": "KE",
    "branchCode": "337",
    "SWIFT Code": "NBKEKENX337",
    "Bank Name": "NATIONAL BANK OF KENYA LTD.",
    "Address": "",
    "City": "RUIRU",
    "Branch": "RUIRU BRANCH",
    "Postcode": "00232",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "CBAF",
    "countryCode": "KE",
    "branchCode": "ENX",
    "SWIFT Code": "CBAFKENX",
    "Bank Name": "NCBA BANK KENYA PLC",
    "Address": "NCBA CENTRE, MARA AND RAGATI ROAD, UPPER HILL",
    "City": "NAIROBI",
    "Branch": "",
    "Postcode": "00100",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "PAUT",
    "countryCode": "KE",
    "branchCode": "ENA",
    "SWIFT Code": "PAUTKENA",
    "Bank Name": "PARAMOUNT BANK LIMITED",
    "Address": "SOUND PLAZA, FLOOR 4, WOODVALE GROOVE",
    "City": "NAIROBI",
    "Branch": "",
    "Postcode": "00800",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "IFCB",
    "countryCode": "KE",
    "branchCode": "ENA",
    "SWIFT Code": "IFCBKENA",
    "Bank Name": "PREMIER BANK KENYA LIMITED",
    "Address": "FCB MIHRAB, MEZZANINE 1, LENANA ROAD/RING ROAD KILIMANI",
    "City": "NAIROBI",
    "Branch": "",
    "Postcode": "00100",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "PRIE",
    "countryCode": "KE",
    "branchCode": "ENX",
    "SWIFT Code": "PRIEKENX",
    "Bank Name": "PRIME BANK LTD.",
    "Address": "KENINDIA HOUSE, LOITA STREET",
    "City": "NAIROBI",
    "Branch": "",
    "Postcode": "00100",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "RMFB",
    "countryCode": "KE",
    "branchCode": "ENA",
    "SWIFT Code": "RMFBKENA",
    "Bank Name": "RAFIKI MICROFINANCE BANK",
    "Address": "254 BIASHARA STREET",
    "City": "NAIROBI",
    "Branch": "",
    "Postcode": "00254",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "SLMI",
    "countryCode": "KE",
    "branchCode": "ENA",
    "SWIFT Code": "SLMIKENA",
    "Bank Name": "SALAAM MICROFINANCE BANK LIMITED",
    "Address": "PARK PLAZA, MOKTAR DADDAH STREET",
    "City": "NAIROBI",
    "Branch": "",
    "Postcode": "00100",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "SBMK",
    "countryCode": "KE",
    "branchCode": "ENA",
    "SWIFT Code": "SBMKKENA",
    "Bank Name": "SBM BANK (KENYA) LIMITED",
    "Address": "RIVERSIDE MEWS, RIVERSIDE DRIVE",
    "City": "NAIROBI",
    "Branch": "",
    "Postcode": "00623",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "SIDN",
    "countryCode": "KE",
    "branchCode": "ENA",
    "SWIFT Code": "SIDNKENA",
    "Bank Name": "SIDIAN BANK LIMITED",
    "Address": "K-REP CENTER, 25363 WOOD AVENUE",
    "City": "NAIROBI",
    "Branch": "",
    "Postcode": "00603",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "SBIC",
    "countryCode": "KE",
    "branchCode": "ENX",
    "SWIFT Code": "SBICKENX",
    "Bank Name": "STANBIC BANK KENYA LIMITED",
    "Address": "STANBIC CENTRE, CHIROMO ROAD, WESTLANDS",
    "City": "NAIROBI",
    "Branch": "",
    "Postcode": "00200",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "SCBL",
    "countryCode": "KE",
    "branchCode": "ENX",
    "SWIFT Code": "SCBLKENX",
    "Bank Name": "STANDARD CHARTERED BANK KENYA LIMITED",
    "Address": "48 WESTLANDS ROAD, CHIROMO",
    "City": "NAIROBI",
    "Branch": "",
    "Postcode": "00100",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "SCBL",
    "countryCode": "KE",
    "branchCode": "SSU",
    "SWIFT Code": "SCBLKENXSSU",
    "Bank Name": "STANDARD CHARTERED BANK KENYA LIMITED",
    "Address": "48 WESTLANDS ROAD, CHIROMO",
    "City": "NAIROBI",
    "Branch": "SECURITIES SERVICES UNIT",
    "Postcode": "00100",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "SCBL",
    "countryCode": "KE",
    "branchCode": "TRD",
    "SWIFT Code": "SCBLKENXTRD",
    "Bank Name": "STANDARD CHARTERED BANK KENYA LIMITED",
    "Address": "48 WESTLANDS ROAD, CHIROMO",
    "City": "NAIROBI",
    "Branch": "TRADE",
    "Postcode": "00100",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "KCOO",
    "countryCode": "KE",
    "branchCode": "ENA",
    "SWIFT Code": "KCOOKENA",
    "Bank Name": "THE CO-OPERATIVE BANK OF KENYA LTD",
    "Address": "CO-OPERATIVE HOUSE, HAILE SELASSIE AVENUE",
    "City": "NAIROBI",
    "Branch": "",
    "Postcode": "00200",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "SLTE",
    "countryCode": "KE",
    "branchCode": "ENA",
    "SWIFT Code": "SLTEKENA",
    "Bank Name": "THE COMPANY FOR HABITAT AND HOUSING IN AFRICA (SHELTER - AFRIQUE)",
    "Address": "SHELTER AFRIQUE CENTRE, LONGONOT ROAD",
    "City": "NAIROBI",
    "Branch": "",
    "Postcode": "00100",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "KE",
    "branchCode": "ENA",
    "SWIFT Code": "UNAFKENA",
    "Bank Name": "UBA KENYA BANK LIMITED",
    "Address": "APPOLLO PLAZA, VALE CLOSE, WESTLANDS",
    "City": "NAIROBI",
    "Branch": "",
    "Postcode": "00100",
    "Country": "Kenya",
    "Connection": "Active"
  },
  {
    "bankCode": "VICM",
    "countryCode": "KE",
    "branchCode": "ENA",
    "SWIFT Code": "VICMKENA",
    "Bank Name": "VICTORIA COMMERCIAL BANK PLC",
    "Address": "VICTORIA TOWERS, KILIMANJARO AVENUE, UPPER HILL",
    "City": "NAIROBI",
    "Branch": "",
    "Postcode": "00100",
    "Country": "Kenya",
    "Connection": "Active"
  }
]
module.exports = kenya
