const kosovo = [
  {
    "bankCode": "CDIS",
    "countryCode": "XK",
    "branchCode": "KPR",
    "SWIFT Code": "CDISXKPR",
    "Bank Name": "BANKA CREDINS KOSOVE SH.A.",
    "Address": "RR. UCK 240",
    "City": "PRISTINA",
    "Branch": "",
    "Postcode": "10000",
    "Country": "Kosovo",
    "Connection": "Active"
  },
  {
    "bankCode": "EKOM",
    "countryCode": "XK",
    "branchCode": "KPR",
    "SWIFT Code": "EKOMXKPR",
    "Bank Name": "BANKA EKONOMIKE SH.A",
    "Address": "SHESHI NENE TEREZE P.N, SWISS DIAMOND BUILDING",
    "City": "PRISTINA",
    "Branch": "",
    "Postcode": "10000",
    "Country": "Kosovo",
    "Connection": "Active"
  },
  {
    "bankCode": "NCBA",
    "countryCode": "XK",
    "branchCode": "KPR",
    "SWIFT Code": "NCBAXKPR",
    "Bank Name": "BANKA KOMBETARE TREGTARE KOSOVE",
    "Address": "UKSHIN HOTI 29",
    "City": "PRISTINA",
    "Branch": "",
    "Postcode": "10000",
    "Country": "Kosovo",
    "Connection": "Active"
  },
  {
    "bankCode": "BPBX",
    "countryCode": "XK",
    "branchCode": "KPR",
    "SWIFT Code": "BPBXXKPR",
    "Bank Name": "BANKA PER BIZNES SH.A.",
    "Address": "UKSHIN HOTI 128",
    "City": "PRISTINA",
    "Branch": "",
    "Postcode": "10000",
    "Country": "Kosovo",
    "Connection": "Active"
  },
  {
    "bankCode": "CBRK",
    "countryCode": "XK",
    "branchCode": "KPR",
    "SWIFT Code": "CBRKXKPR",
    "Bank Name": "CENTRAL BANK OF THE REPUBLIC OF KOSOVO",
    "Address": "GARIBALDI STREET 33",
    "City": "PRISTINA",
    "Branch": "",
    "Postcode": "10000",
    "Country": "Kosovo",
    "Connection": "Active"
  },
  {
    "bankCode": "NLPR",
    "countryCode": "XK",
    "branchCode": "KPR",
    "SWIFT Code": "NLPRXKPR",
    "Bank Name": "NLB BANKA SH.A.",
    "Address": "UKSHIN HOTI 124",
    "City": "PRISTINA",
    "Branch": "",
    "Postcode": "10000",
    "Country": "Kosovo",
    "Connection": "Active"
  },
  {
    "bankCode": "PAYK",
    "countryCode": "XK",
    "branchCode": "KP2",
    "SWIFT Code": "PAYKXKP2",
    "Bank Name": "PAYSERA KOSOVO",
    "Address": "HAJDAR DUSHI HYRJA 2",
    "City": "PRISTINA",
    "Branch": "",
    "Postcode": "10000",
    "Country": "Kosovo",
    "Connection": "Active"
  },
  {
    "bankCode": "PHHA",
    "countryCode": "XK",
    "branchCode": "KPR",
    "SWIFT Code": "PHHAXKPR",
    "Bank Name": "PRIBANK SH.A.",
    "Address": "KALABRI RR. SICILIA NR.2, BLLOKU A1, LAM: A1/2, KOMPLEKSI LUBJANA",
    "City": "PRISTINA",
    "Branch": "",
    "Postcode": "10000",
    "Country": "Kosovo",
    "Connection": "Active"
  },
  {
    "bankCode": "PHHA",
    "countryCode": "XK",
    "branchCode": "015",
    "SWIFT Code": "PHHAXKPR015",
    "Bank Name": "PRIBANK SH.A.",
    "Address": "KALABRI RR. SICILIA NR.2, BLLOKU A1, LAM: A1/2, KOMPLEKSI LUBJANA",
    "City": "PRISTINA",
    "Branch": "DEGA FUSHE KOSOVE- AAB",
    "Postcode": "10000",
    "Country": "Kosovo",
    "Connection": "Active"
  },
  {
    "bankCode": "MBKO",
    "countryCode": "XK",
    "branchCode": "KPR",
    "SWIFT Code": "MBKOXKPR",
    "Bank Name": "PROCREDIT BANK SH.A KOSOVO",
    "Address": "XHORXH BUSH 26",
    "City": "PRISTINA",
    "Branch": "",
    "Postcode": "10000",
    "Country": "Kosovo",
    "Connection": "Active"
  },
  {
    "bankCode": "RBKO",
    "countryCode": "XK",
    "branchCode": "KPR",
    "SWIFT Code": "RBKOXKPR",
    "Bank Name": "RAIFFEISEN BANK KOSOVO J.S.C. SH.A",
    "Address": "RRUGA ROBERT DOLL 99",
    "City": "PRISTINA",
    "Branch": "",
    "Postcode": "10000",
    "Country": "Kosovo",
    "Connection": "Active"
  },
  {
    "bankCode": "TEBK",
    "countryCode": "XK",
    "branchCode": "030",
    "SWIFT Code": "TEBKXKPR030",
    "Bank Name": "TEB SHA",
    "Address": "",
    "City": "KLINA",
    "Branch": "KLINA",
    "Postcode": "32000",
    "Country": "Kosovo",
    "Connection": "Active"
  },
  {
    "bankCode": "TEBK",
    "countryCode": "XK",
    "branchCode": "KPR",
    "SWIFT Code": "TEBKXKPR",
    "Bank Name": "TEB SHA",
    "Address": "MAGJISTRALIA PRISHTINA-FERIZAJ 7KM, PREOC GRACANICE",
    "City": "PRISTINA",
    "Branch": "",
    "Postcode": "10500",
    "Country": "Kosovo",
    "Connection": "Active"
  },
  {
    "bankCode": "TEBK",
    "countryCode": "XK",
    "branchCode": "020",
    "SWIFT Code": "TEBKXKPR020",
    "Bank Name": "TEB SHA",
    "Address": "NO.34, SHOPPING CENTRE NAPREDAKU",
    "City": "PRISTINA",
    "Branch": "DARDANIA",
    "Postcode": "10000",
    "Country": "Kosovo",
    "Connection": "Active"
  },
  {
    "bankCode": "TEBK",
    "countryCode": "XK",
    "branchCode": "024",
    "SWIFT Code": "TEBKXKPR024",
    "Bank Name": "TEB SHA",
    "Address": "RR.SKENDERBEU,PA NUMER",
    "City": "PRISTINA",
    "Branch": "DRENAS",
    "Postcode": "13000",
    "Country": "Kosovo",
    "Connection": "Active"
  },
  {
    "bankCode": "TEBK",
    "countryCode": "XK",
    "branchCode": "013",
    "SWIFT Code": "TEBKXKPR013",
    "Bank Name": "TEB SHA",
    "Address": "REXHEP BISLIMI N.N",
    "City": "PRISTINA",
    "Branch": "FERIZAJ",
    "Postcode": "70000",
    "Country": "Kosovo",
    "Connection": "Active"
  },
  {
    "bankCode": "TEBK",
    "countryCode": "XK",
    "branchCode": "014",
    "SWIFT Code": "TEBKXKPR014",
    "Bank Name": "TEB SHA",
    "Address": "NENA TEREZA NO. 113/1, FUSHE KOSOVA",
    "City": "PRISTINA",
    "Branch": "FUSHE KOSOVA",
    "Postcode": "12000",
    "Country": "Kosovo",
    "Connection": "Active"
  },
  {
    "bankCode": "TEBK",
    "countryCode": "XK",
    "branchCode": "018",
    "SWIFT Code": "TEBKXKPR018",
    "Bank Name": "TEB SHA",
    "Address": "ISMAJL QEMAJLI NO.22, GJAKOVE",
    "City": "PRISTINA",
    "Branch": "GJAKOVA",
    "Postcode": "50000",
    "Country": "Kosovo",
    "Connection": "Active"
  },
  {
    "bankCode": "TEBK",
    "countryCode": "XK",
    "branchCode": "017",
    "SWIFT Code": "TEBKXKPR017",
    "Bank Name": "TEB SHA",
    "Address": "MULLA IDRIZI N.N, GJILAN",
    "City": "PRISTINA",
    "Branch": "GJILAN",
    "Postcode": "60000",
    "Country": "Kosovo",
    "Connection": "Active"
  },
  {
    "bankCode": "TEBK",
    "countryCode": "XK",
    "branchCode": "029",
    "SWIFT Code": "TEBKXKPR029",
    "Bank Name": "TEB SHA",
    "Address": "",
    "City": "PRISTINA",
    "Branch": "HANI ELEZIT",
    "Postcode": "10000",
    "Country": "Kosovo",
    "Connection": "Active"
  },
  {
    "bankCode": "TEBK",
    "countryCode": "XK",
    "branchCode": "026",
    "SWIFT Code": "TEBKXKPR026",
    "Bank Name": "TEB SHA",
    "Address": "RR.QERAMIDNICA,PA NUMER",
    "City": "PRISTINA",
    "Branch": "LYPJAN",
    "Postcode": "14000",
    "Country": "Kosovo",
    "Connection": "Active"
  },
  {
    "bankCode": "TEBK",
    "countryCode": "XK",
    "branchCode": "011",
    "SWIFT Code": "TEBKXKPR011",
    "Bank Name": "TEB SHA",
    "Address": "AGIM RAMADANI",
    "City": "PRISTINA",
    "Branch": "MAIN",
    "Postcode": "10000",
    "Country": "Kosovo",
    "Connection": "Active"
  },
  {
    "bankCode": "TEBK",
    "countryCode": "XK",
    "branchCode": "023",
    "SWIFT Code": "TEBKXKPR023",
    "Bank Name": "TEB SHA",
    "Address": "RR. RILINDJA KOMBETARE,PA NUMER",
    "City": "PRISTINA",
    "Branch": "MALISHEVA",
    "Postcode": "24000",
    "Country": "Kosovo",
    "Connection": "Active"
  },
  {
    "bankCode": "TEBK",
    "countryCode": "XK",
    "branchCode": "027",
    "SWIFT Code": "TEBKXKPR027",
    "Bank Name": "TEB SHA",
    "Address": "RR. MBRETERESHA TEUTE NR.10",
    "City": "PRISTINA",
    "Branch": "MITROVICA",
    "Postcode": "40000",
    "Country": "Kosovo",
    "Connection": "Active"
  },
  {
    "bankCode": "TEBK",
    "countryCode": "XK",
    "branchCode": "015",
    "SWIFT Code": "TEBKXKPR015",
    "Bank Name": "TEB SHA",
    "Address": "MBRETERESHA TEUTA N.N",
    "City": "PRISTINA",
    "Branch": "PEJA",
    "Postcode": "30000",
    "Country": "Kosovo",
    "Connection": "Active"
  },
  {
    "bankCode": "TEBK",
    "countryCode": "XK",
    "branchCode": "031",
    "SWIFT Code": "TEBKXKPR031",
    "Bank Name": "TEB SHA",
    "Address": "",
    "City": "PRISTINA",
    "Branch": "PEJA CITY OFFICE",
    "Postcode": "10000",
    "Country": "Kosovo",
    "Connection": "Active"
  },
  {
    "bankCode": "TEBK",
    "countryCode": "XK",
    "branchCode": "034",
    "SWIFT Code": "TEBKXKPR034",
    "Bank Name": "TEB SHA",
    "Address": "",
    "City": "PRISTINA",
    "Branch": "PRISTINA QENDRA",
    "Postcode": "10000",
    "Country": "Kosovo",
    "Connection": "Active"
  },
  {
    "bankCode": "TEBK",
    "countryCode": "XK",
    "branchCode": "028",
    "SWIFT Code": "TEBKXKPR028",
    "Bank Name": "TEB SHA",
    "Address": "",
    "City": "PRISTINA",
    "Branch": "PRIZREN MAIN",
    "Postcode": "10000",
    "Country": "Kosovo",
    "Connection": "Active"
  },
  {
    "bankCode": "TEBK",
    "countryCode": "XK",
    "branchCode": "033",
    "SWIFT Code": "TEBKXKPR033",
    "Bank Name": "TEB SHA",
    "Address": "",
    "City": "PRISTINA",
    "Branch": "QAFA CITY OFFICE",
    "Postcode": "10000",
    "Country": "Kosovo",
    "Connection": "Active"
  },
  {
    "bankCode": "TEBK",
    "countryCode": "XK",
    "branchCode": "019",
    "SWIFT Code": "TEBKXKPR019",
    "Bank Name": "TEB SHA",
    "Address": "RAHOVEC VILLAGE, GJAKOVE",
    "City": "PRISTINA",
    "Branch": "RAHOVEC",
    "Postcode": "21080",
    "Country": "Kosovo",
    "Connection": "Active"
  },
  {
    "bankCode": "TEBK",
    "countryCode": "XK",
    "branchCode": "012",
    "SWIFT Code": "TEBKXKPR012",
    "Bank Name": "TEB SHA",
    "Address": "RRASAT E KOSHARES",
    "City": "PRISTINA",
    "Branch": "SHADERVAN",
    "Postcode": "20000",
    "Country": "Kosovo",
    "Connection": "Active"
  },
  {
    "bankCode": "TEBK",
    "countryCode": "XK",
    "branchCode": "022",
    "SWIFT Code": "TEBKXKPR022",
    "Bank Name": "TEB SHA",
    "Address": "SHESHI ADEM JASHARI",
    "City": "PRISTINA",
    "Branch": "SKENDERAJ",
    "Postcode": "41000",
    "Country": "Kosovo",
    "Connection": "Active"
  },
  {
    "bankCode": "TEBK",
    "countryCode": "XK",
    "branchCode": "025",
    "SWIFT Code": "TEBKXKPR025",
    "Bank Name": "TEB SHA",
    "Address": "RR.BRIGADA, PA NUMER 123",
    "City": "PRISTINA",
    "Branch": "THERANDA",
    "Postcode": "23000",
    "Country": "Kosovo",
    "Connection": "Active"
  },
  {
    "bankCode": "TEBK",
    "countryCode": "XK",
    "branchCode": "021",
    "SWIFT Code": "TEBKXKPR021",
    "Bank Name": "TEB SHA",
    "Address": "BULEVARDI I DESHMOREVE PN",
    "City": "PRISTINA",
    "Branch": "ULPIANA",
    "Postcode": "10000",
    "Country": "Kosovo",
    "Connection": "Active"
  },
  {
    "bankCode": "TEBK",
    "countryCode": "XK",
    "branchCode": "016",
    "SWIFT Code": "TEBKXKPR016",
    "Bank Name": "TEB SHA",
    "Address": "DESHMORET E KOMBIT NO.23, VUSHTRRI",
    "City": "PRISTINA",
    "Branch": "VUSHTRRI",
    "Postcode": "42000",
    "Country": "Kosovo",
    "Connection": "Active"
  },
  {
    "bankCode": "TCZB",
    "countryCode": "XK",
    "branchCode": "KPR",
    "SWIFT Code": "TCZBXKPR",
    "Bank Name": "TURKIYE CUMHURIYETI ZIRAAT BANKASI",
    "Address": "UKSHIN HOTI 13, FLOOR 1",
    "City": "PRISTINA",
    "Branch": "",
    "Postcode": "10000",
    "Country": "Kosovo",
    "Connection": "Active"
  },
  {
    "bankCode": "ISBK",
    "countryCode": "XK",
    "branchCode": "KPR",
    "SWIFT Code": "ISBKXKPR",
    "Bank Name": "TURKIYE IS BANKASI A.S. ALL KOSOVO BRANCHES",
    "Address": "STR. UKSHIN HOTI 100",
    "City": "PRISTINA",
    "Branch": "",
    "Postcode": "10000",
    "Country": "Kosovo",
    "Connection": "Active"
  }
]
module.exports = kosovo
