const kuwait = [
  {
    "bankCode": "APWA",
    "countryCode": "KW",
    "branchCode": "WKW",
    "SWIFT Code": "APWAKWKW",
    "Bank Name": "AGILITY PUBLIC WAREHOUSING COMPANY K.S.C.P",
    "Address": "AL SULAIBIYA STREET, 2, SULAIBIYA, INDUSTRIAL AREA 2",
    "City": "KUWAIT",
    "Branch": "AGILITY GROUP HEADQUARTERS",
    "Postcode": "13115",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "BKME",
    "countryCode": "KW",
    "branchCode": "WKW",
    "SWIFT Code": "BKMEKWKW",
    "Bank Name": "AHLI UNITED BANK K.S.C.P.",
    "Address": "MUBARAK AL KABEER ST, JOINT BANKING COMPLEX EAST TOWER, SAFAT",
    "City": "KUWAIT",
    "Branch": "",
    "Postcode": "12168",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "ABKK",
    "countryCode": "KW",
    "branchCode": "WKW",
    "SWIFT Code": "ABKKKWKW",
    "Bank Name": "AL AHLI BANK OF KUWAIT K.S.C.P",
    "Address": "AHMED AL JABER STREET, SAFAT SQUARE",
    "City": "KUWAIT",
    "Branch": "",
    "Postcode": "13014",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "ABKK",
    "countryCode": "KW",
    "branchCode": "ACI",
    "SWIFT Code": "ABKKKWKWACI",
    "Bank Name": "AL AHLI BANK OF KUWAIT K.S.C.P",
    "Address": "AHMED AL JABER STREET, SAFAT SQUARE",
    "City": "KUWAIT",
    "Branch": "",
    "Postcode": "13014",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "MGHM",
    "countryCode": "KW",
    "branchCode": "WKW",
    "SWIFT Code": "MGHMKWKW",
    "Bank Name": "AL MULLA GROUP HOLDING CO. KSCC",
    "Address": "BUILDING A, FREE TRADE ZONE",
    "City": "SHUWAIKH",
    "Branch": "",
    "Postcode": "50000",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "AMIE",
    "countryCode": "KW",
    "branchCode": "WKW",
    "SWIFT Code": "AMIEKWKW",
    "Bank Name": "AL MULLA INTERNATIONAL EXCHANGE CO",
    "Address": "AHMED AL SALEH AND SONS COMPLEX, FLOOR 1-2-3, BLOCK 10 QIBLA",
    "City": "KUWAIT",
    "Branch": "",
    "Postcode": "13002",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "AMIE",
    "countryCode": "KW",
    "branchCode": "1ME",
    "SWIFT Code": "AMIEKWKW1ME",
    "Bank Name": "AL MULLA INTERNATIONAL EXCHANGE CO",
    "Address": "ABDULAZIZ HAMAD AL SAQER STREET, MEC OMN AHMED AL SALEH AND SONS, COM, FLOOR 1",
    "City": "KUWAIT",
    "Branch": "ALMULLA2",
    "Postcode": "55000",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "AMIE",
    "countryCode": "KW",
    "branchCode": "2ME",
    "SWIFT Code": "AMIEKWKW2ME",
    "Bank Name": "AL MULLA INTERNATIONAL EXCHANGE CO",
    "Address": "ABDULAZIZ HAMAD AL SAQER STREET, MEC OMN AHMED AL SALEH AND SONS COM",
    "City": "KUWAIT",
    "Branch": "ALMULLA3",
    "Postcode": "55000",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "AAAC",
    "countryCode": "KW",
    "branchCode": "WKW",
    "SWIFT Code": "AAACKWKW",
    "Bank Name": "AL MUZAINI EXCHANGE CO. KSCC",
    "Address": "SAUD BIN ABDULAZIZ ST, BUILDING 9, BLOCK 4",
    "City": "KUWAIT",
    "Branch": "",
    "Postcode": "13022",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "NIEN",
    "countryCode": "KW",
    "branchCode": "WKW",
    "SWIFT Code": "NIENKWKW",
    "Bank Name": "AL NADA INTERNATIONAL EXCHANGE COMPANY WLL",
    "Address": "HAWALLY, SALEM AL-MUBARAK, PLOT, 018801 BLOCK 9, FLOOR 00, SHOP 19",
    "City": "SALMIYA",
    "Branch": "",
    "Postcode": "13085",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "RJHI",
    "countryCode": "KW",
    "branchCode": "WKW",
    "SWIFT Code": "RJHIKWKW",
    "Bank Name": "AL RAJHI BANK, KUWAIT",
    "Address": "ARABIAN GULF STREET, AHMAD TOWER, FLOOR 9, SHARQ",
    "City": "KUWAIT",
    "Branch": "",
    "Postcode": "13060",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "AFBO",
    "countryCode": "KW",
    "branchCode": "WK2",
    "SWIFT Code": "AFBOKWK2",
    "Bank Name": "AL-WASEET FINANCIAL BUSINESS CO. (K.S.C)CLOSED",
    "Address": "AL MUTANABI ST, AL KHALEEJIA COMPLEX, FLOOR 8",
    "City": "KUWAIT",
    "Branch": "",
    "Postcode": "26822",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "AXCW",
    "countryCode": "KW",
    "branchCode": "WKW",
    "SWIFT Code": "AXCWKWKW",
    "Bank Name": "AMAN EXCHANGE CO. WLL",
    "Address": "STREET, 58,28",
    "City": "KUWAIT",
    "Branch": "",
    "Postcode": "13137",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "KFDC",
    "countryCode": "KW",
    "branchCode": "WKW",
    "SWIFT Code": "KFDCKWKW",
    "Bank Name": "AMERICANA KUWAIT COMPANY FOR RESTAURANTS WLL",
    "Address": "SHEIKHA NOURIYEH SAB, ABU FATIRA WEST, 12 PLOT 1-137 AL MUBARAK BUILDING",
    "City": "KUWAIT",
    "Branch": "",
    "Postcode": "13051",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "AFED",
    "countryCode": "KW",
    "branchCode": "WKW",
    "SWIFT Code": "AFEDKWKW",
    "Bank Name": "ARAB FUND FOR ECONOMIC AND SOCIAL DEVELOPMENT",
    "Address": "AIRPORT ROAD, 21923, ARAB HEADQUARTER ORG. BUILDING, SAFAT, SHUWAIKH",
    "City": "KUWAIT",
    "Branch": "",
    "Postcode": "13080",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "AFGP",
    "countryCode": "KW",
    "branchCode": "WKW",
    "SWIFT Code": "AFGPKWKW",
    "Bank Name": "ARZAN FINANCIAL GROUP FOR FINANCING AND INVESTMENTS K.P.S.C",
    "Address": "AHMAD AL JABER, 450, ARZAN TOWER ALL",
    "City": "KUWAIT",
    "Branch": "",
    "Postcode": "13125",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "BECX",
    "countryCode": "KW",
    "branchCode": "WKW",
    "SWIFT Code": "BECXKWKW",
    "Bank Name": "BAHRAIN EXCHANGE COMPANY WLL",
    "Address": "ABDUL AZIZ HAMAD AL SAQER STREET, AL-HAJERY BUILDING NO 1, MURGAB",
    "City": "KUWAIT",
    "Branch": "",
    "Postcode": "29149",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "BMUS",
    "countryCode": "KW",
    "branchCode": "WKW",
    "SWIFT Code": "BMUSKWKW",
    "Bank Name": "BANKMUSCAT",
    "Address": "AL SHUHADAA STREET, AL SAFAT COMMERCIAL CENTRE",
    "City": "KUWAIT",
    "Branch": "",
    "Postcode": "15259",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "BBKU",
    "countryCode": "KW",
    "branchCode": "WKW",
    "SWIFT Code": "BBKUKWKW",
    "Bank Name": "BBK",
    "Address": "AHMED AL JABER STREET, SAFAT",
    "City": "KUWAIT",
    "Branch": "",
    "Postcode": "13104",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "BNPA",
    "countryCode": "KW",
    "branchCode": "WKW",
    "SWIFT Code": "BNPAKWKW",
    "Bank Name": "BNP PARIBAS KUWAIT",
    "Address": "AHMAD AL JABER STREET, 80, DAR AL AWADHI TOWER, SHARQ",
    "City": "KUWAIT",
    "Branch": "",
    "Postcode": "15310",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "BBYN",
    "countryCode": "KW",
    "branchCode": "WKW",
    "SWIFT Code": "BBYNKWKW",
    "Bank Name": "BOUBYAN BANK (K.S.C)",
    "Address": "ABDULLAH SALEM STREET, QIBLA",
    "City": "KUWAIT",
    "Branch": "",
    "Postcode": "13116",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "BRGN",
    "countryCode": "KW",
    "branchCode": "WKW",
    "SWIFT Code": "BRGNKWKW",
    "Bank Name": "BURGAN BANK K.P.S.C",
    "Address": "ABDULLA AL AHMAD STREET, BURGAN TOWER, SHARQ",
    "City": "KUWAIT",
    "Branch": "",
    "Postcode": "12170",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "CBKU",
    "countryCode": "KW",
    "branchCode": "WKW",
    "SWIFT Code": "CBKUKWKW",
    "Bank Name": "CENTRAL BANK OF KUWAIT",
    "Address": "ABDULLAH AL-AHMAD STREET, SAFAT, SHARQ",
    "City": "KUWAIT",
    "Branch": "",
    "Postcode": "13006",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "CBKU",
    "countryCode": "KW",
    "branchCode": "BOD",
    "SWIFT Code": "CBKUKWKWBOD",
    "Bank Name": "CENTRAL BANK OF KUWAIT",
    "Address": "",
    "City": "KUWAIT",
    "Branch": "BANKING OPERATIONS DEPARTMENT - KWD ONLY",
    "Postcode": "",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "CITI",
    "countryCode": "KW",
    "branchCode": "WKW",
    "SWIFT Code": "CITIKWKW",
    "Bank Name": "CITIBANK N.A.",
    "Address": "ARABIAN GULF ROAD AHMED TOWER, BLDG. NO 1, BLOCK 3, PLOT 1 SHARQ AREA",
    "City": "KUWAIT",
    "Branch": "",
    "Postcode": "13121",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "COMB",
    "countryCode": "KW",
    "branchCode": "A14",
    "SWIFT Code": "COMBKWKWA14",
    "Bank Name": "COMMERCIAL BANK OF KUWAIT KPSC",
    "Address": "",
    "City": "AHMADI",
    "Branch": "EA. AHMADI BRANCH",
    "Postcode": "",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "COMB",
    "countryCode": "KW",
    "branchCode": "A19",
    "SWIFT Code": "COMBKWKWA19",
    "Bank Name": "COMMERCIAL BANK OF KUWAIT KPSC",
    "Address": "",
    "City": "ARDHIYA",
    "Branch": "ARDHIYA BRANCH",
    "Postcode": "",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "COMB",
    "countryCode": "KW",
    "branchCode": "A66",
    "SWIFT Code": "COMBKWKWA66",
    "Bank Name": "COMMERCIAL BANK OF KUWAIT KPSC",
    "Address": "",
    "City": "FAHAHEEL",
    "Branch": "",
    "Postcode": "",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "COMB",
    "countryCode": "KW",
    "branchCode": "A11",
    "SWIFT Code": "COMBKWKWA11",
    "Bank Name": "COMMERCIAL BANK OF KUWAIT KPSC",
    "Address": "",
    "City": "FAHAHEEL",
    "Branch": "AJIAL COMPLEX BRANCH",
    "Postcode": "",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "COMB",
    "countryCode": "KW",
    "branchCode": "A06",
    "SWIFT Code": "COMBKWKWA06",
    "Bank Name": "COMMERCIAL BANK OF KUWAIT KPSC",
    "Address": "",
    "City": "FAHAHEEL",
    "Branch": "FAHAHEEL BRANCH",
    "Postcode": "",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "COMB",
    "countryCode": "KW",
    "branchCode": "A04",
    "SWIFT Code": "COMBKWKWA04",
    "Bank Name": "COMMERCIAL BANK OF KUWAIT KPSC",
    "Address": "",
    "City": "FARWANIA",
    "Branch": "AIRPORT BRANCH",
    "Postcode": "",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "COMB",
    "countryCode": "KW",
    "branchCode": "A27",
    "SWIFT Code": "COMBKWKWA27",
    "Bank Name": "COMMERCIAL BANK OF KUWAIT KPSC",
    "Address": "",
    "City": "FARWANIA",
    "Branch": "FARWANIA COOP. BRANCH",
    "Postcode": "",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "COMB",
    "countryCode": "KW",
    "branchCode": "A34",
    "SWIFT Code": "COMBKWKWA34",
    "Bank Name": "COMMERCIAL BANK OF KUWAIT KPSC",
    "Address": "",
    "City": "FARWANIA",
    "Branch": "SIXTH RING ROAD BRANCH",
    "Postcode": "",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "COMB",
    "countryCode": "KW",
    "branchCode": "A2O",
    "SWIFT Code": "COMBKWKWA2O",
    "Bank Name": "COMMERCIAL BANK OF KUWAIT KPSC",
    "Address": "",
    "City": "HAWALLI",
    "Branch": "BEIRUT STREET BRANCH",
    "Postcode": "",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "COMB",
    "countryCode": "KW",
    "branchCode": "A16",
    "SWIFT Code": "COMBKWKWA16",
    "Bank Name": "COMMERCIAL BANK OF KUWAIT KPSC",
    "Address": "",
    "City": "HAWALLI",
    "Branch": "HAWALLI BRANCH",
    "Postcode": "",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "COMB",
    "countryCode": "KW",
    "branchCode": "A35",
    "SWIFT Code": "COMBKWKWA35",
    "Bank Name": "COMMERCIAL BANK OF KUWAIT KPSC",
    "Address": "",
    "City": "JABRIYA",
    "Branch": "JABRIYA BRANCH",
    "Postcode": "",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "COMB",
    "countryCode": "KW",
    "branchCode": "A07",
    "SWIFT Code": "COMBKWKWA07",
    "Bank Name": "COMMERCIAL BANK OF KUWAIT KPSC",
    "Address": "",
    "City": "JAHRA",
    "Branch": "JAHRA BRANCH",
    "Postcode": "",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "COMB",
    "countryCode": "KW",
    "branchCode": "A08",
    "SWIFT Code": "COMBKWKWA08",
    "Bank Name": "COMMERCIAL BANK OF KUWAIT KPSC",
    "Address": "",
    "City": "KHAITAN",
    "Branch": "KHAITAN BRANCH",
    "Postcode": "",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "COMB",
    "countryCode": "KW",
    "branchCode": "A15",
    "SWIFT Code": "COMBKWKWA15",
    "Bank Name": "COMMERCIAL BANK OF KUWAIT KPSC",
    "Address": "",
    "City": "KHALDIYA",
    "Branch": "KHALDIYA BRANCH",
    "Postcode": "",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "COMB",
    "countryCode": "KW",
    "branchCode": "WKW",
    "SWIFT Code": "COMBKWKW",
    "Bank Name": "COMMERCIAL BANK OF KUWAIT KPSC",
    "Address": "MUBARAK AL KABIR STREET",
    "City": "KUWAIT",
    "Branch": "",
    "Postcode": "13029",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "COMB",
    "countryCode": "KW",
    "branchCode": "A05",
    "SWIFT Code": "COMBKWKWA05",
    "Bank Name": "COMMERCIAL BANK OF KUWAIT KPSC",
    "Address": "SAFAT",
    "City": "KUWAIT",
    "Branch": "ABD. MUBARAK BRANCH",
    "Postcode": "",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "COMB",
    "countryCode": "KW",
    "branchCode": "A02",
    "SWIFT Code": "COMBKWKWA02",
    "Bank Name": "COMMERCIAL BANK OF KUWAIT KPSC",
    "Address": "",
    "City": "KUWAIT",
    "Branch": "ABDULLAH AL-SALEM STREET BRANCH",
    "Postcode": "",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "COMB",
    "countryCode": "KW",
    "branchCode": "A36",
    "SWIFT Code": "COMBKWKWA36",
    "Bank Name": "COMMERCIAL BANK OF KUWAIT KPSC",
    "Address": "MUBARAK AL-KABIR STREET, SAFAT",
    "City": "KUWAIT",
    "Branch": "AL ANDALUS BRANCH",
    "Postcode": "13029",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "COMB",
    "countryCode": "KW",
    "branchCode": "A25",
    "SWIFT Code": "COMBKWKWA25",
    "Bank Name": "COMMERCIAL BANK OF KUWAIT KPSC",
    "Address": "MUBARAK AL-KABIR STREET, SAFAT",
    "City": "KUWAIT",
    "Branch": "AL MUHALAB CENTER BRANCH",
    "Postcode": "13029",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "COMB",
    "countryCode": "KW",
    "branchCode": "A56",
    "SWIFT Code": "COMBKWKWA56",
    "Bank Name": "COMMERCIAL BANK OF KUWAIT KPSC",
    "Address": "",
    "City": "KUWAIT",
    "Branch": "AL NAEEM",
    "Postcode": "",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "COMB",
    "countryCode": "KW",
    "branchCode": "A60",
    "SWIFT Code": "COMBKWKWA60",
    "Bank Name": "COMMERCIAL BANK OF KUWAIT KPSC",
    "Address": "",
    "City": "KUWAIT",
    "Branch": "AL SOUR STREET BRANCH",
    "Postcode": "",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "COMB",
    "countryCode": "KW",
    "branchCode": "A58",
    "SWIFT Code": "COMBKWKWA58",
    "Bank Name": "COMMERCIAL BANK OF KUWAIT KPSC",
    "Address": "AL-DHOW, BEHBEHANI ROUNDABOUT, SAFAT",
    "City": "KUWAIT",
    "Branch": "AL-DHOW",
    "Postcode": "13029",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "COMB",
    "countryCode": "KW",
    "branchCode": "A57",
    "SWIFT Code": "COMBKWKWA57",
    "Bank Name": "COMMERCIAL BANK OF KUWAIT KPSC",
    "Address": "AL-RABIA, SAFAT",
    "City": "KUWAIT",
    "Branch": "AL-RABIA BRANCH",
    "Postcode": "13029",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "COMB",
    "countryCode": "KW",
    "branchCode": "A45",
    "SWIFT Code": "COMBKWKWA45",
    "Bank Name": "COMMERCIAL BANK OF KUWAIT KPSC",
    "Address": "AL-RAI",
    "City": "KUWAIT",
    "Branch": "AL-RAI",
    "Postcode": "13029",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "COMB",
    "countryCode": "KW",
    "branchCode": "A32",
    "SWIFT Code": "COMBKWKWA32",
    "Bank Name": "COMMERCIAL BANK OF KUWAIT KPSC",
    "Address": "MUBARAK AL-KABIR STREET, SAFAT",
    "City": "KUWAIT",
    "Branch": "AL-YARMOUK BRANCH",
    "Postcode": "13029",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "COMB",
    "countryCode": "KW",
    "branchCode": "A20",
    "SWIFT Code": "COMBKWKWA20",
    "Bank Name": "COMMERCIAL BANK OF KUWAIT KPSC",
    "Address": "MUBARAK AL-KABIR STREET, SAFAT",
    "City": "KUWAIT",
    "Branch": "BEIRUT ST. BRANCH",
    "Postcode": "13029",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "COMB",
    "countryCode": "KW",
    "branchCode": "A52",
    "SWIFT Code": "COMBKWKWA52",
    "Bank Name": "COMMERCIAL BANK OF KUWAIT KPSC",
    "Address": "MUBARAK AL-KABIR STREET, SAFAT",
    "City": "KUWAIT",
    "Branch": "BNEID AL GAR BRANCH",
    "Postcode": "13029",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "COMB",
    "countryCode": "KW",
    "branchCode": "COM",
    "SWIFT Code": "COMBKWKWCOM",
    "Bank Name": "COMMERCIAL BANK OF KUWAIT KPSC",
    "Address": "",
    "City": "KUWAIT",
    "Branch": "COMMERCIAL SERVICES DEPARTMENT",
    "Postcode": "",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "COMB",
    "countryCode": "KW",
    "branchCode": "SEC",
    "SWIFT Code": "COMBKWKWSEC",
    "Bank Name": "COMMERCIAL BANK OF KUWAIT KPSC",
    "Address": "",
    "City": "KUWAIT",
    "Branch": "CUSTODY DEPARTMENT",
    "Postcode": "",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "COMB",
    "countryCode": "KW",
    "branchCode": "A62",
    "SWIFT Code": "COMBKWKWA62",
    "Bank Name": "COMMERCIAL BANK OF KUWAIT KPSC",
    "Address": "",
    "City": "KUWAIT",
    "Branch": "DASMA",
    "Postcode": "",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "COMB",
    "countryCode": "KW",
    "branchCode": "A41",
    "SWIFT Code": "COMBKWKWA41",
    "Bank Name": "COMMERCIAL BANK OF KUWAIT KPSC",
    "Address": "",
    "City": "KUWAIT",
    "Branch": "DHAHER BRANCH",
    "Postcode": "",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "COMB",
    "countryCode": "KW",
    "branchCode": "A09",
    "SWIFT Code": "COMBKWKWA09",
    "Bank Name": "COMMERCIAL BANK OF KUWAIT KPSC",
    "Address": "FAHD AL SALEM ST, AL NASSER TOWER",
    "City": "KUWAIT",
    "Branch": "FAHD AL SALEM BR.",
    "Postcode": "13122",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "COMB",
    "countryCode": "KW",
    "branchCode": "FXS",
    "SWIFT Code": "COMBKWKWFXS",
    "Bank Name": "COMMERCIAL BANK OF KUWAIT KPSC",
    "Address": "",
    "City": "KUWAIT",
    "Branch": "FOREIGN EXCHANGE DEPARTMENT",
    "Postcode": "",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "COMB",
    "countryCode": "KW",
    "branchCode": "A38",
    "SWIFT Code": "COMBKWKWA38",
    "Bank Name": "COMMERCIAL BANK OF KUWAIT KPSC",
    "Address": "",
    "City": "KUWAIT",
    "Branch": "FREE TRADE ZONE BRANCH",
    "Postcode": "",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "COMB",
    "countryCode": "KW",
    "branchCode": "GTT",
    "SWIFT Code": "COMBKWKWGTT",
    "Bank Name": "COMMERCIAL BANK OF KUWAIT KPSC",
    "Address": "",
    "City": "KUWAIT",
    "Branch": "GUARANTEES DEPARTMENT",
    "Postcode": "",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "COMB",
    "countryCode": "KW",
    "branchCode": "A64",
    "SWIFT Code": "COMBKWKWA64",
    "Bank Name": "COMMERCIAL BANK OF KUWAIT KPSC",
    "Address": "",
    "City": "KUWAIT",
    "Branch": "HADIYA",
    "Postcode": "",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "COMB",
    "countryCode": "KW",
    "branchCode": "A01",
    "SWIFT Code": "COMBKWKWA01",
    "Bank Name": "COMMERCIAL BANK OF KUWAIT KPSC",
    "Address": "SAFAT",
    "City": "KUWAIT",
    "Branch": "HEAD OFFICE BRANCH",
    "Postcode": "",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "COMB",
    "countryCode": "KW",
    "branchCode": "INT",
    "SWIFT Code": "COMBKWKWINT",
    "Bank Name": "COMMERCIAL BANK OF KUWAIT KPSC",
    "Address": "",
    "City": "KUWAIT",
    "Branch": "INTERNATIONAL DIVISION",
    "Postcode": "",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "COMB",
    "countryCode": "KW",
    "branchCode": "A63",
    "SWIFT Code": "COMBKWKWA63",
    "Bank Name": "COMMERCIAL BANK OF KUWAIT KPSC",
    "Address": "",
    "City": "KUWAIT",
    "Branch": "JELEEB SHOYOKH",
    "Postcode": "",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "COMB",
    "countryCode": "KW",
    "branchCode": "A43",
    "SWIFT Code": "COMBKWKWA43",
    "Bank Name": "COMMERCIAL BANK OF KUWAIT KPSC",
    "Address": "ABO HALIFA",
    "City": "KUWAIT",
    "Branch": "KUWAIT MAGIC",
    "Postcode": "13029",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "COMB",
    "countryCode": "KW",
    "branchCode": "LCS",
    "SWIFT Code": "COMBKWKWLCS",
    "Bank Name": "COMMERCIAL BANK OF KUWAIT KPSC",
    "Address": "",
    "City": "KUWAIT",
    "Branch": "LETTERS OF CREDIT DEPARTMENT",
    "Postcode": "",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "COMB",
    "countryCode": "KW",
    "branchCode": "A44",
    "SWIFT Code": "COMBKWKWA44",
    "Bank Name": "COMMERCIAL BANK OF KUWAIT KPSC",
    "Address": "MANSOURIYA",
    "City": "KUWAIT",
    "Branch": "MANSOURIYA",
    "Postcode": "13029",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "COMB",
    "countryCode": "KW",
    "branchCode": "A31",
    "SWIFT Code": "COMBKWKWA31",
    "Bank Name": "COMMERCIAL BANK OF KUWAIT KPSC",
    "Address": "MINISTRIES COMPLEX",
    "City": "KUWAIT",
    "Branch": "MINISTRIES COMPLEX BRANCH",
    "Postcode": "",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "COMB",
    "countryCode": "KW",
    "branchCode": "B00",
    "SWIFT Code": "COMBKWKWB00",
    "Bank Name": "COMMERCIAL BANK OF KUWAIT KPSC",
    "Address": "SAFAT",
    "City": "KUWAIT",
    "Branch": "NEW HEAD OFFICE BRANCH",
    "Postcode": "",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "COMB",
    "countryCode": "KW",
    "branchCode": "A47",
    "SWIFT Code": "COMBKWKWA47",
    "Bank Name": "COMMERCIAL BANK OF KUWAIT KPSC",
    "Address": "",
    "City": "KUWAIT",
    "Branch": "PHONE BANKING SERVICES",
    "Postcode": "",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "COMB",
    "countryCode": "KW",
    "branchCode": "A40",
    "SWIFT Code": "COMBKWKWA40",
    "Bank Name": "COMMERCIAL BANK OF KUWAIT KPSC",
    "Address": "",
    "City": "KUWAIT",
    "Branch": "PRIVATE BANKING UNIT",
    "Postcode": "",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "COMB",
    "countryCode": "KW",
    "branchCode": "SWI",
    "SWIFT Code": "COMBKWKWSWI",
    "Bank Name": "COMMERCIAL BANK OF KUWAIT KPSC",
    "Address": "",
    "City": "KUWAIT",
    "Branch": "S.W.I.F.T. SUPPORT DEPARTMENT",
    "Postcode": "",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "COMB",
    "countryCode": "KW",
    "branchCode": "A54",
    "SWIFT Code": "COMBKWKWA54",
    "Bank Name": "COMMERCIAL BANK OF KUWAIT KPSC",
    "Address": "",
    "City": "KUWAIT",
    "Branch": "SABAH AL SALEM",
    "Postcode": "",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "COMB",
    "countryCode": "KW",
    "branchCode": "A30",
    "SWIFT Code": "COMBKWKWA30",
    "Bank Name": "COMMERCIAL BANK OF KUWAIT KPSC",
    "Address": "SAFAT",
    "City": "KUWAIT",
    "Branch": "SALHIYA BRANCH",
    "Postcode": "",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "COMB",
    "countryCode": "KW",
    "branchCode": "A51",
    "SWIFT Code": "COMBKWKWA51",
    "Bank Name": "COMMERCIAL BANK OF KUWAIT KPSC",
    "Address": "MUBARAK AL-KABIR STREET, SAFAT",
    "City": "KUWAIT",
    "Branch": "SALWA BRANCH",
    "Postcode": "13029",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "COMB",
    "countryCode": "KW",
    "branchCode": "A55",
    "SWIFT Code": "COMBKWKWA55",
    "Bank Name": "COMMERCIAL BANK OF KUWAIT KPSC",
    "Address": "",
    "City": "KUWAIT",
    "Branch": "SOUTH SURRA",
    "Postcode": "",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "COMB",
    "countryCode": "KW",
    "branchCode": "TLX",
    "SWIFT Code": "COMBKWKWTLX",
    "Bank Name": "COMMERCIAL BANK OF KUWAIT KPSC",
    "Address": "",
    "City": "KUWAIT",
    "Branch": "TELEX DEPARTMENT",
    "Postcode": "",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "COMB",
    "countryCode": "KW",
    "branchCode": "A53",
    "SWIFT Code": "COMBKWKWA53",
    "Bank Name": "COMMERCIAL BANK OF KUWAIT KPSC",
    "Address": "",
    "City": "KUWAIT",
    "Branch": "TRADERS MALL",
    "Postcode": "",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "COMB",
    "countryCode": "KW",
    "branchCode": "A42",
    "SWIFT Code": "COMBKWKWA42",
    "Bank Name": "COMMERCIAL BANK OF KUWAIT KPSC",
    "Address": "",
    "City": "KUWAIT",
    "Branch": "UM AL HAIMAN BRANCH",
    "Postcode": "",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "COMB",
    "countryCode": "KW",
    "branchCode": "A65",
    "SWIFT Code": "COMBKWKWA65",
    "Bank Name": "COMMERCIAL BANK OF KUWAIT KPSC",
    "Address": "",
    "City": "MESSILAH",
    "Branch": "",
    "Postcode": "",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "COMB",
    "countryCode": "KW",
    "branchCode": "A24",
    "SWIFT Code": "COMBKWKWA24",
    "Bank Name": "COMMERCIAL BANK OF KUWAIT KPSC",
    "Address": "",
    "City": "MESSILAH",
    "Branch": "MESSILAH BRANCH",
    "Postcode": "",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "COMB",
    "countryCode": "KW",
    "branchCode": "A17",
    "SWIFT Code": "COMBKWKWA17",
    "Bank Name": "COMMERCIAL BANK OF KUWAIT KPSC",
    "Address": "",
    "City": "MINA ABDULLA",
    "Branch": "MINA ABDULLA BRANCH",
    "Postcode": "",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "COMB",
    "countryCode": "KW",
    "branchCode": "A10",
    "SWIFT Code": "COMBKWKWA10",
    "Bank Name": "COMMERCIAL BANK OF KUWAIT KPSC",
    "Address": "",
    "City": "OMARIA",
    "Branch": "OMARIYA BRANCH",
    "Postcode": "",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "COMB",
    "countryCode": "KW",
    "branchCode": "A67",
    "SWIFT Code": "COMBKWKWA67",
    "Bank Name": "COMMERCIAL BANK OF KUWAIT KPSC",
    "Address": "",
    "City": "REGAEE",
    "Branch": "",
    "Postcode": "",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "COMB",
    "countryCode": "KW",
    "branchCode": "A18",
    "SWIFT Code": "COMBKWKWA18",
    "Bank Name": "COMMERCIAL BANK OF KUWAIT KPSC",
    "Address": "",
    "City": "RUMAITHIYA",
    "Branch": "RUMAITHIYA BRANCH",
    "Postcode": "",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "COMB",
    "countryCode": "KW",
    "branchCode": "A12",
    "SWIFT Code": "COMBKWKWA12",
    "Bank Name": "COMMERCIAL BANK OF KUWAIT KPSC",
    "Address": "",
    "City": "SABAHIYA",
    "Branch": "SABAHIYA BRANCH",
    "Postcode": "",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "COMB",
    "countryCode": "KW",
    "branchCode": "A33",
    "SWIFT Code": "COMBKWKWA33",
    "Bank Name": "COMMERCIAL BANK OF KUWAIT KPSC",
    "Address": "",
    "City": "SALMIYA",
    "Branch": "RAS SALMIYA BRANCH",
    "Postcode": "",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "COMB",
    "countryCode": "KW",
    "branchCode": "A23",
    "SWIFT Code": "COMBKWKWA23",
    "Bank Name": "COMMERCIAL BANK OF KUWAIT KPSC",
    "Address": "",
    "City": "SALMIYA",
    "Branch": "SALMIYA BRANCH",
    "Postcode": "",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "COMB",
    "countryCode": "KW",
    "branchCode": "A48",
    "SWIFT Code": "COMBKWKWA48",
    "Bank Name": "COMMERCIAL BANK OF KUWAIT KPSC",
    "Address": "",
    "City": "SALMIYA",
    "Branch": "SOUK AL SALMIYA BRANCH",
    "Postcode": "",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "COMB",
    "countryCode": "KW",
    "branchCode": "A26",
    "SWIFT Code": "COMBKWKWA26",
    "Bank Name": "COMMERCIAL BANK OF KUWAIT KPSC",
    "Address": "SHARQ",
    "City": "SHARQ",
    "Branch": "AHMAD AL JABER STREET",
    "Postcode": "",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "COMB",
    "countryCode": "KW",
    "branchCode": "A39",
    "SWIFT Code": "COMBKWKWA39",
    "Bank Name": "COMMERCIAL BANK OF KUWAIT KPSC",
    "Address": "SHARQ",
    "City": "SHARQ",
    "Branch": "SOUK SHARQ BRANCH",
    "Postcode": "",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "COMB",
    "countryCode": "KW",
    "branchCode": "A21",
    "SWIFT Code": "COMBKWKWA21",
    "Bank Name": "COMMERCIAL BANK OF KUWAIT KPSC",
    "Address": "",
    "City": "SHUWAIKH",
    "Branch": "SHUWAIKH BRANCH",
    "Postcode": "",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "COMB",
    "countryCode": "KW",
    "branchCode": "A28",
    "SWIFT Code": "COMBKWKWA28",
    "Bank Name": "COMMERCIAL BANK OF KUWAIT KPSC",
    "Address": "",
    "City": "SHUWAIKH",
    "Branch": "VEGETABLE MARKET BRANCH",
    "Postcode": "",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "COMB",
    "countryCode": "KW",
    "branchCode": "A13",
    "SWIFT Code": "COMBKWKWA13",
    "Bank Name": "COMMERCIAL BANK OF KUWAIT KPSC",
    "Address": "",
    "City": "SULAIBIKHAT",
    "Branch": "SULAIBIKHAT BRANCH",
    "Postcode": "",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "COMB",
    "countryCode": "KW",
    "branchCode": "A46",
    "SWIFT Code": "COMBKWKWA46",
    "Bank Name": "COMMERCIAL BANK OF KUWAIT KPSC",
    "Address": "",
    "City": "WEST MISHRIF",
    "Branch": "WEST MISHRIF BRANCH",
    "Postcode": "",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "DOHB",
    "countryCode": "KW",
    "branchCode": "WKW",
    "SWIFT Code": "DOHBKWKW",
    "Bank Name": "DOHA BANK",
    "Address": "ABRAJ AL WATIYA COMPOUND, AL KUBLA AREA",
    "City": "KUWAIT",
    "Branch": "",
    "Postcode": "",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "EQPC",
    "countryCode": "KW",
    "branchCode": "WKW",
    "SWIFT Code": "EQPCKWKW",
    "Bank Name": "EQUATE PETROCHEMICAL COMPANY KSCC",
    "Address": "EQUATE HQ, BUILDING 900011, BLOCK, 12",
    "City": "AL AHMADI",
    "Branch": "",
    "Postcode": "61001",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "NBAD",
    "countryCode": "KW",
    "branchCode": "WKW",
    "SWIFT Code": "NBADKWKW",
    "Bank Name": "FIRST ABU DHABI BANK (FORMERLY NATIONAL BANK OF ABU DHABI)",
    "Address": "AHMED AL JABER STREET, AL BAHAR TOWER, SAFAT, SHARQ",
    "City": "KUWAIT",
    "Branch": "",
    "Postcode": "13027",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "GULB",
    "countryCode": "KW",
    "branchCode": "WKW",
    "SWIFT Code": "GULBKWKW",
    "Bank Name": "GULF BANK, K.S.C.P.",
    "Address": "MUBARAK AL-KABIR STREET",
    "City": "KUWAIT",
    "Branch": "",
    "Postcode": "13032",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "GULB",
    "countryCode": "KW",
    "branchCode": "TFS",
    "SWIFT Code": "GULBKWKWTFS",
    "Bank Name": "GULF BANK, K.S.C.P.",
    "Address": "MUBARAK AL KABEER STREET, 21, FLOOR B2",
    "City": "KUWAIT",
    "Branch": "HEAD OFFICE",
    "Postcode": "13032",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "GULB",
    "countryCode": "KW",
    "branchCode": "TRO",
    "SWIFT Code": "GULBKWKWTRO",
    "Bank Name": "GULF BANK, K.S.C.P.",
    "Address": "",
    "City": "KUWAIT",
    "Branch": "TREASURY OPERATIONS",
    "Postcode": "",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "GULB",
    "countryCode": "KW",
    "branchCode": "VOS",
    "SWIFT Code": "GULBKWKWVOS",
    "Bank Name": "GULF BANK, K.S.C.P.",
    "Address": "",
    "City": "KUWAIT",
    "Branch": "VOSTRO/KD DEPARTMENT",
    "Postcode": "",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "GCHS",
    "countryCode": "KW",
    "branchCode": "WKW",
    "SWIFT Code": "GCHSKWKW",
    "Bank Name": "GULF CRYO HOLDING CO. KSCC",
    "Address": "MINA ABDULLAH STREET, BLOCK 4",
    "City": "KUWAIT",
    "Branch": "",
    "Postcode": "",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "GCCO",
    "countryCode": "KW",
    "branchCode": "WKW",
    "SWIFT Code": "GCCOKWKW",
    "Bank Name": "GULF CUSTODY COMPANY",
    "Address": "MUBARAK AL KABEER STREET, ZIAD AL KAZEMI BUILDING, FLOOR 5-6",
    "City": "KUWAIT",
    "Branch": "",
    "Postcode": "13072",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "GCOR",
    "countryCode": "KW",
    "branchCode": "WKW",
    "SWIFT Code": "GCORKWKW",
    "Bank Name": "GULF INVESTMENT CORPORATION",
    "Address": "JABER AL-MUBARAK STREET, SHARQ",
    "City": "KUWAIT",
    "Branch": "",
    "Postcode": "13035",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "HBME",
    "countryCode": "KW",
    "branchCode": "WKW",
    "SWIFT Code": "HBMEKWKW",
    "Bank Name": "HSBC BANK MIDDLE EAST LIMITED",
    "Address": "AL-HAMRA TOWER, FLOOR 37, ABDULAZIZ AL SAGER STREET, SHARQ AREA",
    "City": "KUWAIT",
    "Branch": "",
    "Postcode": "13017",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "ICBK",
    "countryCode": "KW",
    "branchCode": "WKW",
    "SWIFT Code": "ICBKKWKW",
    "Bank Name": "ICBC KUWAIT BRANCH",
    "Address": "AL-SOOR ST, AL-TIJARIA, FLOOR 7, BLOCK 3",
    "City": "KUWAIT",
    "Branch": "",
    "Postcode": "13059",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "IPGH",
    "countryCode": "KW",
    "branchCode": "WKW",
    "SWIFT Code": "IPGHKWKW",
    "Bank Name": "INDEPENDENT PETROLEUM GROUP",
    "Address": "STREET, 7, BUILDING 18, FLOOR 1-5",
    "City": "JABRIYA",
    "Branch": "",
    "Postcode": "24027",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "IBKU",
    "countryCode": "KW",
    "branchCode": "WKW",
    "SWIFT Code": "IBKUKWKW",
    "Bank Name": "INDUSTRIAL BANK OF KUWAIT K.S.C., THE",
    "Address": "DARWAZAT AL-ABDUL RAZZAK, JOINT BANKING CENTRE, FLOOR GF",
    "City": "KUWAIT",
    "Branch": "",
    "Postcode": "13032",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "TIDC",
    "countryCode": "KW",
    "branchCode": "WKW",
    "SWIFT Code": "TIDCKWKW",
    "Bank Name": "INVESTMENT DAR COMPANY K.S.C.C, THE",
    "Address": "AL SHUHADA STREET, KRE TOWER, FLOOR 6",
    "City": "KUWAIT",
    "Branch": "",
    "Postcode": "13060",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "KMCO",
    "countryCode": "KW",
    "branchCode": "WKW",
    "SWIFT Code": "KMCOKWKW",
    "Bank Name": "KAMCO INVESTMENT COMPANY K.S.C. (PUBLIC)",
    "Address": "KHALID BIN WALEED STREET, AL-SHAHEED TOWER, SAFAT, SHARQ",
    "City": "KUWAIT",
    "Branch": "",
    "Postcode": "13149",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "KNPC",
    "countryCode": "KW",
    "branchCode": "WKW",
    "SWIFT Code": "KNPCKWKW",
    "Bank Name": "KNPC",
    "Address": "HAMAD AL ZUWAYER, BLOCK 12",
    "City": "AL AHMADI",
    "Branch": "",
    "Postcode": "60000",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "KACC",
    "countryCode": "KW",
    "branchCode": "WKW",
    "SWIFT Code": "KACCKWKW",
    "Bank Name": "KUWAIT AIRWAYS CORPORATION",
    "Address": "KWI AIRPORT, SAFAT",
    "City": "KUWAIT",
    "Branch": "KUWAIT AIRWAYS HEAD OFFICE",
    "Postcode": "13004",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "KAFO",
    "countryCode": "KW",
    "branchCode": "WKW",
    "SWIFT Code": "KAFOKWKW",
    "Bank Name": "KUWAIT AVIATION FUELLING COMPANY, K.S.C",
    "Address": "KUWAIT INTERNATIONAL AIRPORT, HEAD QUARTER BUILDING, FLOOR 1, SAFAT",
    "City": "KUWAIT",
    "Branch": "",
    "Postcode": "13017",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "KCCK",
    "countryCode": "KW",
    "branchCode": "WKW",
    "SWIFT Code": "KCCKKWKW",
    "Bank Name": "KUWAIT CLEARING COMPANY SAK",
    "Address": "AHMED ALJABER STREET, MUBARAK, ALKABEER STREET BOURSA KUWAIT,, FLOOR 6 SHARQ",
    "City": "KUWAIT",
    "Branch": "",
    "Postcode": "13081",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "KFHO",
    "countryCode": "KW",
    "branchCode": "WKW",
    "SWIFT Code": "KFHOKWKW",
    "Bank Name": "KUWAIT FINANCE HOUSE K.S.C.P.",
    "Address": "ABDULLA AL MUBARAK STREET, KUWAIT FINANCE HOUSE, FLOOR 1",
    "City": "KUWAIT",
    "Branch": "",
    "Postcode": "13110",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "KFCE",
    "countryCode": "KW",
    "branchCode": "WKW",
    "SWIFT Code": "KFCEKWKW",
    "Bank Name": "KUWAIT FINANCIAL CENTRE K.P.S.C.",
    "Address": "AHMAD AL-JABER S, UNIVERSAL TOWER, FLOOR 3, BLOCK 1, AL-SHARQ",
    "City": "KUWAIT",
    "Branch": "",
    "Postcode": "13095",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "KFPE",
    "countryCode": "KW",
    "branchCode": "WKW",
    "SWIFT Code": "KFPEKWKW",
    "Bank Name": "KUWAIT FOREIGN PETROLEUM EXPLORATION COMPANY KSCC",
    "Address": "ADMINISTRATIVE SHUWAIKH, 102, NO.9, SAFAT AREA 4",
    "City": "SHUWAIKH",
    "Branch": "",
    "Postcode": "13053",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "KFAE",
    "countryCode": "KW",
    "branchCode": "WKW",
    "SWIFT Code": "KFAEKWKW",
    "Bank Name": "KUWAIT FUND FOR ARAB ECONOMIC DEVELOPMENT",
    "Address": "MUBARAK AL-KABEER STREET, KFAED BUILDING",
    "City": "KUWAIT",
    "Branch": "",
    "Postcode": "13030",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "KGOC",
    "countryCode": "KW",
    "branchCode": "WKW",
    "SWIFT Code": "KGOCKWKW",
    "Bank Name": "KUWAIT GULF OIL CO. K.S.C",
    "Address": "BLOCK 1, FLOOR GF",
    "City": "AL AHMADI",
    "Branch": "KGOC HO",
    "Postcode": "61010",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "KIPM",
    "countryCode": "KW",
    "branchCode": "WKW",
    "SWIFT Code": "KIPMKWKW",
    "Bank Name": "KUWAIT INTEGRATED PETROLEUM INDUSTRIES CO. K.S.C.C.C.C.",
    "Address": "PETROLEUM CORPORATION, FLOOR 2, BLOCK 1",
    "City": "SHUWAIKH",
    "Branch": "",
    "Postcode": "13039",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "KWIB",
    "countryCode": "KW",
    "branchCode": "WKW",
    "SWIFT Code": "KWIBKWKW",
    "Bank Name": "KUWAIT INTERNATIONAL BANK",
    "Address": "AL MUBARKIA AHMAD AL-JABBER, STREET, AL ABD GATE WEST TOWER",
    "City": "KUWAIT",
    "Branch": "",
    "Postcode": "13089",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "KIAK",
    "countryCode": "KW",
    "branchCode": "WKW",
    "SWIFT Code": "KIAKKWKW",
    "Bank Name": "KUWAIT INVESTMENT AUTHORITY",
    "Address": "STREET, 201, BLOCK 1, SAFAT, SHARQ",
    "City": "KUWAIT",
    "Branch": "",
    "Postcode": "13001",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "KIAK",
    "countryCode": "KW",
    "branchCode": "WKB",
    "SWIFT Code": "KIAKKWKB",
    "Bank Name": "KUWAIT INVESTMENT AUTHORITY",
    "Address": "STREET, 201, BLOCK 1, SAFAT, SHARQ",
    "City": "KUWAIT",
    "Branch": "",
    "Postcode": "13001",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "KICO",
    "countryCode": "KW",
    "branchCode": "WKW",
    "SWIFT Code": "KICOKWKW",
    "Bank Name": "KUWAIT INVESTMENT COMPANY (S.A.K.)",
    "Address": "MUBARAK AL KABIR STREET, SOUK AL MANAKH BLDG, FLOOR 5",
    "City": "KUWAIT",
    "Branch": "",
    "Postcode": "13011",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "KUOC",
    "countryCode": "KW",
    "branchCode": "WKW",
    "SWIFT Code": "KUOCKWKW",
    "Bank Name": "KUWAIT OIL COMPANY K.S.C.",
    "Address": "MID AVENUE STREET",
    "City": "AL AHMADI",
    "Branch": "MAIN OFFICE",
    "Postcode": "61008",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "KOTA",
    "countryCode": "KW",
    "branchCode": "WKW",
    "SWIFT Code": "KOTAKWKW",
    "Bank Name": "KUWAIT OIL TANKER CO. S.A.K.",
    "Address": "JAMAL ABDULNASSER STREET, KUWAIT OIL TANKER COMPANY BUILDING",
    "City": "KUWAIT",
    "Branch": "",
    "Postcode": "13001",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "KPCO",
    "countryCode": "KW",
    "branchCode": "WKW",
    "SWIFT Code": "KPCOKWKW",
    "Bank Name": "KUWAIT PETROLEUM CORPORATION",
    "Address": "GULF ROAD, OIL SECTOR BUILDING, SHUWAIKH AREA",
    "City": "KUWAIT",
    "Branch": "",
    "Postcode": "13126",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "KTCK",
    "countryCode": "KW",
    "branchCode": "WKW",
    "SWIFT Code": "KTCKKWKW",
    "Bank Name": "KUWAIT TELECOMMUNICATION COMPANY (K.S.C.)",
    "Address": "AL-KHANSA STREET, OLMPIA MALL, FLOOR 5-20",
    "City": "SALMIYA",
    "Branch": "",
    "Postcode": "22002",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "MSHQ",
    "countryCode": "KW",
    "branchCode": "WKW",
    "SWIFT Code": "MSHQKWKW",
    "Bank Name": "MASHREQBANK PSC.",
    "Address": "GULF ROAD AHMAD TOWER BUILDING 1, FLOOR 5, BLOCK 3 DASMAN, SHARQ",
    "City": "KUWAIT",
    "Branch": "",
    "Postcode": "15455",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "MEFB",
    "countryCode": "KW",
    "branchCode": "WK2",
    "SWIFT Code": "MEFBKWK2",
    "Bank Name": "MIDDLE EAST FINANCIAL BROKERAGE CO.",
    "Address": "MUBARAK ALKABEER ST BOURSA KUWAIT, FLOOR 2, OFFICE 117-121-112",
    "City": "KUWAIT",
    "Branch": "",
    "Postcode": "15461",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "MNAN",
    "countryCode": "KW",
    "branchCode": "WKW",
    "SWIFT Code": "MNANKWKW",
    "Bank Name": "MOHAMMED NASER AL SAYER AND SONS EST. CO",
    "Address": "FREE ZONE NASER MOHAMMED ALSAYER, BUILDING, FLOOR 1",
    "City": "KUWAIT",
    "Branch": "",
    "Postcode": "13005",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "NBOK",
    "countryCode": "KW",
    "branchCode": "WKW",
    "SWIFT Code": "NBOKKWKW",
    "Bank Name": "NATIONAL BANK OF KUWAIT S.A.K.P.",
    "Address": "ALSHUHADA STREET, SAFAT, SHARQ DISTRICT",
    "City": "KUWAIT",
    "Branch": "NBK HEADQUARTERS",
    "Postcode": "13001",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "NICK",
    "countryCode": "KW",
    "branchCode": "WKW",
    "SWIFT Code": "NICKKWKW",
    "Bank Name": "NATIONAL INVESTMENTS COMPANY K.S.C. (CLOSED)",
    "Address": "AL-MUTHANNABI STREET, AL KHALEEJIA BUILDING, SAFAT, SHARQ",
    "City": "KUWAIT",
    "Branch": "",
    "Postcode": "13117",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "NFIC",
    "countryCode": "KW",
    "branchCode": "WKW",
    "SWIFT Code": "NFICKWKW",
    "Bank Name": "NOOR FINANCIAL INVESTMENT COMPANY",
    "Address": "INTERSECTION OF AL JAHRA STREET, AND AIRPORT ROAD NOOR BUILDING",
    "City": "SHUWAIKH",
    "Branch": "",
    "Postcode": "13034",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "OMAN",
    "countryCode": "KW",
    "branchCode": "WKW",
    "SWIFT Code": "OMANKWKW",
    "Bank Name": "OMAN EXCHANGE CO. WLL",
    "Address": "SHOUDHA STREET, MARWAB",
    "City": "KUWAIT",
    "Branch": "",
    "Postcode": "13121",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "PIPC",
    "countryCode": "KW",
    "branchCode": "WKW",
    "SWIFT Code": "PIPCKWKW",
    "Bank Name": "PETROCHEMICAL INDUSTRIES COMPANY K.S.C.",
    "Address": "NEAR AHMADI COURT, P.I.C. BUILDING, NO. 19, FLOOR 1",
    "City": "SABAHIYA",
    "Branch": "",
    "Postcode": "53700",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "PISU",
    "countryCode": "KW",
    "branchCode": "WKW",
    "SWIFT Code": "PISUKWKW",
    "Bank Name": "PUBLIC INSTITUTION FOR SOCIAL SECURITY,THE",
    "Address": "AL SHOUHADA STREET OPPOSITE TO, CINEMA AL HAMRA AL TAMINAT BUILDING",
    "City": "KUWAIT",
    "Branch": "",
    "Postcode": "13104",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "QNBA",
    "countryCode": "KW",
    "branchCode": "WKW",
    "SWIFT Code": "QNBAKWKW",
    "Bank Name": "QATAR NATIONAL BANK",
    "Address": "AHMED AL-JABER, AL-ARABIA TOWER",
    "City": "KUWAIT",
    "Branch": "",
    "Postcode": "13119",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "WRBA",
    "countryCode": "KW",
    "branchCode": "WKW",
    "SWIFT Code": "WRBAKWKW",
    "Bank Name": "WARBA BANK",
    "Address": "OMAR BEN AL KHATTAB STREET, ARRAYA TOWER, FLOOR 01-13, BLOCK 7, SHARQ",
    "City": "KUWAIT",
    "Branch": "",
    "Postcode": "13013",
    "Country": "Kuwait",
    "Connection": "Active"
  },
  {
    "bankCode": "ALGW",
    "countryCode": "KW",
    "branchCode": "WKW",
    "SWIFT Code": "ALGWKWKW",
    "Bank Name": "YUSUF AHMED ALGHANIM AND SONS WLL",
    "Address": "SHUHADA STREET, 14A, AL HAMRA BUSINESS TOWER, FLOOR 72, SHARQ",
    "City": "KUWAIT",
    "Branch": "",
    "Postcode": "13500",
    "Country": "Kuwait",
    "Connection": "Active"
  }
]
module.exports = kuwait
