const kyrgyzstan = [
  {
    "countryCode": "AJRA",
    "bankCode": "KG",
    "branchCode": "G22",
    "SWIFT Code": "AJRAKG22",
    "Bank Name": "AMANBANK (JOINT-STOCK RUSSIAN-KYRGYZ AMANBANK)",
    "Address": "249, UL. TYNYSTANOVA",
    "City": "BISHKEK",
    "Branch": "",
    "Postcode": "720040",
    "Country": "Kyrgyzstan",
    "Connection": "Active"
  },
  {
    "countryCode": "BBTP",
    "bankCode": "KG",
    "branchCode": "G22",
    "SWIFT Code": "BBTPKG22",
    "Bank Name": "BAI-TUSHUM BANK OJSC",
    "Address": "76 , UMETALIEV",
    "City": "BISHKEK",
    "Branch": "",
    "Postcode": "720001",
    "Country": "Kyrgyzstan",
    "Connection": "Active"
  },
  {
    "countryCode": "BAKA",
    "bankCode": "KG",
    "branchCode": "G22",
    "SWIFT Code": "BAKAKG22",
    "Bank Name": "BAKAI BANK OJSC",
    "Address": "118 , MOSKOVSKAYA STREET",
    "City": "BISHKEK",
    "Branch": "",
    "Postcode": "720017",
    "Country": "Kyrgyzstan",
    "Connection": "Active"
  },
  {
    "countryCode": "ASCJ",
    "bankCode": "KG",
    "branchCode": "G22",
    "SWIFT Code": "ASCJKG22",
    "Bank Name": "BANK OF ASIA CJSC",
    "Address": "303 , MIRA AVE",
    "City": "BISHKEK",
    "Branch": "",
    "Postcode": "720016",
    "Country": "Kyrgyzstan",
    "Connection": "Active"
  },
  {
    "countryCode": "ECBI",
    "bankCode": "KG",
    "branchCode": "G22",
    "SWIFT Code": "ECBIKG22",
    "Bank Name": "CJSC ECOISLAMICBANK",
    "Address": "17, PEREULOK GEOLOGICHESKY",
    "City": "BISHKEK",
    "Branch": "",
    "Postcode": "720005",
    "Country": "Kyrgyzstan",
    "Connection": "Active"
  },
  {
    "countryCode": "FBAN",
    "bankCode": "KG",
    "branchCode": "G22",
    "SWIFT Code": "FBANKG22",
    "Bank Name": "CJSC FINCA BANK",
    "Address": "93/2, SHOPOKOV STREET , FLOOR 3",
    "City": "BISHKEK",
    "Branch": "",
    "Postcode": "720021",
    "Country": "Kyrgyzstan",
    "Connection": "Active"
  },
  {
    "countryCode": "DEMI",
    "bankCode": "KG",
    "branchCode": "G22",
    "SWIFT Code": "DEMIKG22",
    "Bank Name": "DEMIR KYRGYZ INTERNATIONAL BANK",
    "Address": "245 , CHUI AVENUE",
    "City": "BISHKEK",
    "Branch": "",
    "Postcode": "720040",
    "Country": "Kyrgyzstan",
    "Connection": "Active"
  },
  {
    "countryCode": "DOSS",
    "bankCode": "KG",
    "branchCode": "G22",
    "SWIFT Code": "DOSSKG22",
    "Bank Name": "DOS-CREDOBANK OJSC",
    "Address": "92 , CHUI AVENUE, FLOOR 6",
    "City": "BISHKEK",
    "Branch": "",
    "Postcode": "720000",
    "Country": "Kyrgyzstan",
    "Connection": "Active"
  },
  {
    "countryCode": "KYRG",
    "bankCode": "KG",
    "branchCode": "G22",
    "SWIFT Code": "KYRGKG22",
    "Bank Name": "EURASIAN SAVINGS BANK, OJSC",
    "Address": "40/1 , IBRAIMOVA STREET",
    "City": "BISHKEK",
    "Branch": "",
    "Postcode": "720021",
    "Country": "Kyrgyzstan",
    "Connection": "Active"
  },
  {
    "countryCode": "FIKB",
    "bankCode": "KG",
    "branchCode": "G22",
    "SWIFT Code": "FIKBKG22",
    "Bank Name": "FINANCECREDITBANK KAB",
    "Address": "105 , ABDRAKHMANOVA",
    "City": "BISHKEK",
    "Branch": "",
    "Postcode": "720021",
    "Country": "Kyrgyzstan",
    "Connection": "Active"
  },
  {
    "countryCode": "JSCE",
    "bankCode": "KG",
    "branchCode": "G22",
    "SWIFT Code": "JSCEKG22",
    "Bank Name": "JOINT STOCK COMPANY 'EURASIAN CURRENCY AND STOCK EXCHANGE INVESTMENT EXCHANGE 'UNION''",
    "Address": "109/1 , TURUSBEKOVA, 514",
    "City": "BISHKEK",
    "Branch": "",
    "Postcode": "720010",
    "Country": "Kyrgyzstan",
    "Connection": "Active"
  },
  {
    "countryCode": "KOMP",
    "bankCode": "KG",
    "branchCode": "G22",
    "SWIFT Code": "KOMPKG22",
    "Bank Name": "KOMPANION BANK CLOSED JOINT-STOCK COMPANY",
    "Address": "62 , SHOTA RUSTAVELI",
    "City": "BISHKEK",
    "Branch": "",
    "Postcode": "720044",
    "Country": "Kyrgyzstan",
    "Connection": "Active"
  },
  {
    "countryCode": "KSBC",
    "bankCode": "KG",
    "branchCode": "G22",
    "SWIFT Code": "KSBCKG22",
    "Bank Name": "KSB COMMERCIAL BANK CLOSED JOINT-STOCK COMPANY",
    "Address": "68 , BAYTIK BAATYR STREET",
    "City": "BISHKEK",
    "Branch": "",
    "Postcode": "720005",
    "Country": "Kyrgyzstan",
    "Connection": "Active"
  },
  {
    "countryCode": "KICB",
    "bankCode": "KG",
    "branchCode": "G22",
    "SWIFT Code": "KICBKG22",
    "Bank Name": "KYRGYZ INVESTMENT AND CREDIT BANK",
    "Address": "21 , ERKINDIK BLVD",
    "City": "BISHKEK",
    "Branch": "",
    "Postcode": "720040",
    "Country": "Kyrgyzstan",
    "Connection": "Active"
  },
  {
    "countryCode": "NBPA",
    "bankCode": "KG",
    "branchCode": "G22",
    "SWIFT Code": "NBPAKG22",
    "Bank Name": "NATIONAL BANK OF PAKISTAN BISHKEK BRANCH",
    "Address": "NBP BUILDING, 84, MOSKOWSKAYA STREET",
    "City": "BISHKEK",
    "Branch": "",
    "Postcode": "720021",
    "Country": "Kyrgyzstan",
    "Connection": "Active"
  },
  {
    "countryCode": "NBKI",
    "bankCode": "KG",
    "branchCode": "G22",
    "SWIFT Code": "NBKIKG22",
    "Bank Name": "NATIONAL BANK OF THE KYRGYZ REPUBLIC",
    "Address": "168 , CHUY AVENUE",
    "City": "BISHKEK",
    "Branch": "",
    "Postcode": "720001",
    "Country": "Kyrgyzstan",
    "Connection": "Active"
  },
  {
    "countryCode": "AIYL",
    "bankCode": "KG",
    "branchCode": "G22",
    "SWIFT Code": "AIYLKG22",
    "Bank Name": "OJSC AIYL BANK",
    "Address": "14 , LOGVINENKO STREET",
    "City": "BISHKEK",
    "Branch": "",
    "Postcode": "720040",
    "Country": "Kyrgyzstan",
    "Connection": "Active"
  },
  {
    "countryCode": "KYRS",
    "bankCode": "KG",
    "branchCode": "G22",
    "SWIFT Code": "KYRSKG22",
    "Bank Name": "OJSC COMMERCIAL BANK KYRGYZSTAN",
    "Address": "54 , TOGOLOK MOLDO STREET",
    "City": "BISHKEK",
    "Branch": "",
    "Postcode": "720001",
    "Country": "Kyrgyzstan",
    "Connection": "Active"
  },
  {
    "countryCode": "MAKA",
    "bankCode": "KG",
    "branchCode": "G22",
    "SWIFT Code": "MAKAKG22",
    "Bank Name": "OJSC HALYK BANK KYRGYZSTAN",
    "Address": "390 , FRUNZE STREET",
    "City": "BISHKEK",
    "Branch": "",
    "Postcode": "720033",
    "Country": "Kyrgyzstan",
    "Connection": "Active"
  },
  {
    "countryCode": "KAKY",
    "bankCode": "KG",
    "branchCode": "G22",
    "SWIFT Code": "KAKYKG22",
    "Bank Name": "OJSC KYRGYZKOMMERTSBANK",
    "Address": "101-101A, SHOPOKOV",
    "City": "BISHKEK",
    "Branch": "",
    "Postcode": "720021",
    "Country": "Kyrgyzstan",
    "Connection": "Active"
  },
  {
    "countryCode": "SESV",
    "bankCode": "KG",
    "branchCode": "G22",
    "SWIFT Code": "SESVKG22",
    "Bank Name": "OJSC RSK BANK",
    "Address": "80/1 , MOSKOVSKAYA STREET",
    "City": "BISHKEK",
    "Branch": "",
    "Postcode": "720021",
    "Country": "Kyrgyzstan",
    "Connection": "Active"
  },
  {
    "countryCode": "RINB",
    "bankCode": "KG",
    "branchCode": "G22",
    "SWIFT Code": "RINBKG22",
    "Bank Name": "OPEN JOINT STOCK COMPANY KEREMET BANK",
    "Address": "40/4 , TOGOLOK-MOLDO",
    "City": "BISHKEK",
    "Branch": "",
    "Postcode": "720001",
    "Country": "Kyrgyzstan",
    "Connection": "Active"
  },
  {
    "countryCode": "ENEJ",
    "bankCode": "KG",
    "branchCode": "G22",
    "SWIFT Code": "ENEJKG22",
    "Bank Name": "OPTIMA BANK OJSC",
    "Address": "493 , JIBEK-JOLU STREET",
    "City": "BISHKEK",
    "Branch": "",
    "Postcode": "720070",
    "Country": "Kyrgyzstan",
    "Connection": "Active"
  },
  {
    "countryCode": "AKIL",
    "bankCode": "KG",
    "branchCode": "G22",
    "SWIFT Code": "AKILKG22",
    "Bank Name": "THE OPEN JOINT-STOCK COMPANY CAPITAL BANK",
    "Address": "161, MOSKOVSKAYA STR",
    "City": "BISHKEK",
    "Branch": "",
    "Postcode": "720010",
    "Country": "Kyrgyzstan",
    "Connection": "Active"
  },
  {
    "countryCode": "TOLU",
    "bankCode": "KG",
    "branchCode": "G22",
    "SWIFT Code": "TOLUKG22",
    "Bank Name": "TOLUBAY BANK - CLOSED JOINT STOCK COMPANY",
    "Address": "105 , UMETALIEV STR",
    "City": "BISHKEK",
    "Branch": "",
    "Postcode": "720010",
    "Country": "Kyrgyzstan",
    "Connection": "Active"
  }
]
module.exports = kyrgyzstan
