const laos = [
  {
    "bankCode": "ACLB",
    "countryCode": "LA",
    "branchCode": "ALA",
    "SWIFT Code": "ACLBLALA",
    "Bank Name": "ACLEDA BANK (LAO) LTD",
    "Address": "UNIT 20 398, CNR OF DONGPALANE AND, DONGPAINA PHONESAVANH NEUA VILLAGE, SISATTANAK",
    "City": "VIENTIANE",
    "Branch": "",
    "Postcode": "01000",
    "Country": "Laos",
    "Connection": "Active"
  },
  {
    "bankCode": "AGPB",
    "countryCode": "LA",
    "branchCode": "ALA",
    "SWIFT Code": "AGPBLALA",
    "Bank Name": "AGRICULTURAL PROMOTION BANK CO.,LTD",
    "Address": "KAISONPHOMVIHAN ROAD, PHAKHAO VILLAGE, XAYTHANY DISTRICT",
    "City": "VIENTIANE",
    "Branch": "",
    "Postcode": "01000",
    "Country": "Laos",
    "Connection": "Active"
  },
  {
    "bankCode": "ANZB",
    "countryCode": "LA",
    "branchCode": "ALA",
    "SWIFT Code": "ANZBLALA",
    "Bank Name": "AUSTRALIA AND NEW ZEALAND BANKING GROUP LIMITED, LAO BRANCH",
    "Address": "ANZ BANK (LAO) LIMITED BUILDING, 33 , LANEXANG AVENUE",
    "City": "VIENTIANE",
    "Branch": "",
    "Postcode": "01000",
    "Country": "Laos",
    "Connection": "Active"
  },
  {
    "bankCode": "BKKB",
    "countryCode": "LA",
    "branchCode": "ALA",
    "SWIFT Code": "BKKBLALA",
    "Bank Name": "BANGKOK BANK PUBLIC CO. LTD, VIENTIANE BRANCH",
    "Address": "UNIT 12, SAMSENTHAI RD, XIENG NGUEN VILLAGE, CHANTHABOULY DISTRICT",
    "City": "VIENTIANE",
    "Branch": "",
    "Postcode": "01000",
    "Country": "Laos",
    "Connection": "Active"
  },
  {
    "bankCode": "AYUD",
    "countryCode": "LA",
    "branchCode": "ALA",
    "SWIFT Code": "AYUDLALA",
    "Bank Name": "BANK OF AYUDHYA PCL VIENTIANE BRANCH",
    "Address": "084/1-2 , LANE XANG AVENUE",
    "City": "VIENTIANE",
    "Branch": "",
    "Postcode": "01000",
    "Country": "Laos",
    "Connection": "Active"
  },
  {
    "bankCode": "BKCH",
    "countryCode": "LA",
    "branchCode": "ALA",
    "SWIFT Code": "BKCHLALA",
    "Bank Name": "BANK OF CHINA (HONG KONG) LIMITED VIENTIANE BRANCH",
    "Address": "VIENTIANE CENTRE BUILDING, KHOUVIENG ROAD, NONGCHAN VILLAGE",
    "City": "VIENTIANE",
    "Branch": "",
    "Postcode": "01000",
    "Country": "Laos",
    "Connection": "Active"
  },
  {
    "bankCode": "LPDR",
    "countryCode": "LA",
    "branchCode": "ALA",
    "SWIFT Code": "LPDRLALA",
    "Bank Name": "BANK OF THE LAO P.D.R.",
    "Address": "YONNET ROAD",
    "City": "VIENTIANE",
    "Branch": "",
    "Postcode": "01000",
    "Country": "Laos",
    "Connection": "Active"
  },
  {
    "bankCode": "BFLL",
    "countryCode": "LA",
    "branchCode": "ALA",
    "SWIFT Code": "BFLLLALA",
    "Bank Name": "BANQUE FRANCO-LAO LTD",
    "Address": "11 , AVENUE LANE XANG",
    "City": "VIENTIANE",
    "Branch": "",
    "Postcode": "01000",
    "Country": "Laos",
    "Connection": "Active"
  },
  {
    "bankCode": "COEB",
    "countryCode": "LA",
    "branchCode": "SVN",
    "SWIFT Code": "COEBLALASVN",
    "Bank Name": "BANQUE POUR LE COMMERCE EXTERIEUR LAO PUBLIC",
    "Address": "LATSAVONGSEAK STREET, SOUNANTHA, KHANTHABOULY DISTRICT",
    "City": "KAYSONE PHOMVIHANE",
    "Branch": "SAVANNAKHET BRANCH",
    "Postcode": "00856",
    "Country": "Laos",
    "Connection": "Active"
  },
  {
    "bankCode": "COEB",
    "countryCode": "LA",
    "branchCode": "LNT",
    "SWIFT Code": "COEBLALALNT",
    "Bank Name": "BANQUE POUR LE COMMERCE EXTERIEUR LAO PUBLIC",
    "Address": "LUANGNAMTHA STREET, OUDOMSI VILLAGE, NAMTHA DISTRICT",
    "City": "LUANG NAMTHA",
    "Branch": "LUANGNAMTHA BRANCH",
    "Postcode": "03000",
    "Country": "Laos",
    "Connection": "Active"
  },
  {
    "bankCode": "COEB",
    "countryCode": "LA",
    "branchCode": "LBP",
    "SWIFT Code": "COEBLALALBP",
    "Bank Name": "BANQUE POUR LE COMMERCE EXTERIEUR LAO PUBLIC",
    "Address": "109/3 , PARASAMANH STREET, VIENGXAY VILLAGE",
    "City": "LUANG PHABANG",
    "Branch": "LUANGPRABANG BRANCH",
    "Postcode": "06000",
    "Country": "Laos",
    "Connection": "Active"
  },
  {
    "bankCode": "COEB",
    "countryCode": "LA",
    "branchCode": "ODX",
    "SWIFT Code": "COEBLALAODX",
    "Bank Name": "BANQUE POUR LE COMMERCE EXTERIEUR LAO PUBLIC",
    "Address": "13 , NEUA STREET, PASACK VILLAGE, XAY DISTRICT",
    "City": "OUDOMXAI",
    "Branch": "OUDOMXAY BRANCH",
    "Postcode": "13000",
    "Country": "Laos",
    "Connection": "Active"
  },
  {
    "bankCode": "COEB",
    "countryCode": "LA",
    "branchCode": "CPS",
    "SWIFT Code": "COEBLALACPS",
    "Bank Name": "BANQUE POUR LE COMMERCE EXTERIEUR LAO PUBLIC",
    "Address": "11, WATLUANG VILLAGE",
    "City": "PAKSE",
    "Branch": "CHAMPASACK BRANCH",
    "Postcode": "16000",
    "Country": "Laos",
    "Connection": "Active"
  },
  {
    "bankCode": "COEB",
    "countryCode": "LA",
    "branchCode": "KMN",
    "SWIFT Code": "COEBLALAKMN",
    "Bank Name": "BANQUE POUR LE COMMERCE EXTERIEUR LAO PUBLIC",
    "Address": "CHOMEUGEUN VILLAGE",
    "City": "THAKHEK",
    "Branch": "KHAMMOUANE BRANCH",
    "Postcode": "12000",
    "Country": "Laos",
    "Connection": "Active"
  },
  {
    "bankCode": "COEB",
    "countryCode": "LA",
    "branchCode": "ALA",
    "SWIFT Code": "COEBLALA",
    "Bank Name": "BANQUE POUR LE COMMERCE EXTERIEUR LAO PUBLIC",
    "Address": "1 , PANGKHAM STREET",
    "City": "VIENTIANE",
    "Branch": "",
    "Postcode": "01000",
    "Country": "Laos",
    "Connection": "Active"
  },
  {
    "bankCode": "LICB",
    "countryCode": "LA",
    "branchCode": "ALA",
    "SWIFT Code": "LICBLALA",
    "Bank Name": "BIC BANK LAO CO.,LTD",
    "Address": "127/07 , HATSADY ROAD, HATSADY TAI VILLAGE",
    "City": "VIENTIANE",
    "Branch": "",
    "Postcode": "01000",
    "Country": "Laos",
    "Connection": "Active"
  },
  {
    "bankCode": "CADI",
    "countryCode": "LA",
    "branchCode": "ALA",
    "SWIFT Code": "CADILALA",
    "Bank Name": "CANADIA BANK LAO CO LTD.",
    "Address": "UNIT 7, PANGKHAM ROAD",
    "City": "VIENTIANE",
    "Branch": "",
    "Postcode": "01000",
    "Country": "Laos",
    "Connection": "Active"
  },
  {
    "bankCode": "FCBK",
    "countryCode": "LA",
    "branchCode": "ALA",
    "SWIFT Code": "FCBKLALA",
    "Bank Name": "FIRST COMMERCIAL BANK LTD, VIENTIANE BRANCH",
    "Address": "23 , SINGHA ROAD",
    "City": "VIENTIANE",
    "Branch": "",
    "Postcode": "01000",
    "Country": "Laos",
    "Connection": "Active"
  },
  {
    "bankCode": "IDCB",
    "countryCode": "LA",
    "branchCode": "ALA",
    "SWIFT Code": "IDCBLALA",
    "Bank Name": "INDOCHINA BANK LTD",
    "Address": "CAPITAL TOWER, 116 23 , SINGHA ROAD",
    "City": "VIENTIANE",
    "Branch": "",
    "Postcode": "01000",
    "Country": "Laos",
    "Connection": "Active"
  },
  {
    "bankCode": "ICBK",
    "countryCode": "LA",
    "branchCode": "ALA",
    "SWIFT Code": "ICBKLALA",
    "Bank Name": "INDUSTRIAL AND COMMERCIAL BANK OF CHINA LIMITED VIENTIANE BRANCH",
    "Address": "UNIT12, 358 , ASEAN ROAD, SIBOUNHEUANG VILLAG, CHANTHABOULY",
    "City": "VIENTIANE",
    "Branch": "",
    "Postcode": "01000",
    "Country": "Laos",
    "Connection": "Active"
  },
  {
    "bankCode": "ICBK",
    "countryCode": "LA",
    "branchCode": "CLR",
    "SWIFT Code": "ICBKLALACLR",
    "Bank Name": "INDUSTRIAL AND COMMERCIAL BANK OF CHINA LIMITED VIENTIANE BRANCH",
    "Address": "UNIT12, 358, ASEAN ROAD, SIBOUNHEUANG VILLAG, CHANTHABOULY DISTRICT",
    "City": "VIENTIANE",
    "Branch": "LAOS RMB CLEARING BANK",
    "Postcode": "",
    "Country": "Laos",
    "Connection": "Active"
  },
  {
    "bankCode": "JDBK",
    "countryCode": "LA",
    "branchCode": "ALA",
    "SWIFT Code": "JDBKLALA",
    "Bank Name": "JOINT DEVELOPMENT BANK",
    "Address": "82 , LANEXANG AVE",
    "City": "VIENTIANE",
    "Branch": "",
    "Postcode": "01000",
    "Country": "Laos",
    "Connection": "Active"
  },
  {
    "bankCode": "KASI",
    "countryCode": "LA",
    "branchCode": "ALA",
    "SWIFT Code": "KASILALA",
    "Bank Name": "KASIKORNTHAI BANK SOLE LIMITED",
    "Address": "12 , LANE XANG AVENUE, XIENGGNEUN VILL, CHANTHABOURY DISTRICT",
    "City": "VIENTIANE",
    "Branch": "",
    "Postcode": "01000",
    "Country": "Laos",
    "Connection": "Active"
  },
  {
    "bankCode": "LCNB",
    "countryCode": "LA",
    "branchCode": "ALA",
    "SWIFT Code": "LCNBLALA",
    "Bank Name": "LAO CHINA BANK CO., LTD.",
    "Address": "UNIT 02, KAYSONE PHOMVIHAN AVENUE, PHONEXAY VILLAGE, XAYSETTHA",
    "City": "VIENTIANE",
    "Branch": "",
    "Postcode": "01000",
    "Country": "Laos",
    "Connection": "Active"
  },
  {
    "bankCode": "LCBV",
    "countryCode": "LA",
    "branchCode": "ALA",
    "SWIFT Code": "LCBVLALA",
    "Bank Name": "LAO CONSTRUCTION BANK",
    "Address": "UNIT 10, COSCO ROAD, PHONSINUAN VILLAGE, SISATTANAK",
    "City": "VIENTIANE",
    "Branch": "",
    "Postcode": "01000",
    "Country": "Laos",
    "Connection": "Active"
  },
  {
    "bankCode": "LDBB",
    "countryCode": "LA",
    "branchCode": "ALA",
    "SWIFT Code": "LDBBLALA",
    "Bank Name": "LAO DEVELOPMENT BANK CO.,LTD",
    "Address": "013 , SOUPHANOUVONG ROAD, SIHOM VILLAGE",
    "City": "VIENTIANE",
    "Branch": "",
    "Postcode": "01000",
    "Country": "Laos",
    "Connection": "Active"
  },
  {
    "bankCode": "LAOV",
    "countryCode": "LA",
    "branchCode": "CPS",
    "SWIFT Code": "LAOVLALACPS",
    "Bank Name": "LAO-VIET BANK CO,LTD",
    "Address": "ROAD 13, BAN THALUANG, PARSE TOWN",
    "City": "PAKSE",
    "Branch": "CHAMPASAK BRANCH",
    "Postcode": "16000",
    "Country": "Laos",
    "Connection": "Active"
  },
  {
    "bankCode": "LAOV",
    "countryCode": "LA",
    "branchCode": "ALA",
    "SWIFT Code": "LAOVLALA",
    "Bank Name": "LAO-VIET BANK CO,LTD",
    "Address": "44 , LANEXANG AVENUE",
    "City": "VIENTIANE",
    "Branch": "",
    "Postcode": "01000",
    "Country": "Laos",
    "Connection": "Active"
  },
  {
    "bankCode": "MJBL",
    "countryCode": "LA",
    "branchCode": "ALA",
    "SWIFT Code": "MJBLLALA",
    "Bank Name": "MARUHAN JAPAN BANK LAO CO., LTD",
    "Address": "FLOOR 14, 23 , SINGHA ROAD, BAN PHONXAY",
    "City": "VIENTIANE",
    "Branch": "",
    "Postcode": "01000",
    "Country": "Laos",
    "Connection": "Active"
  },
  {
    "bankCode": "MBBE",
    "countryCode": "LA",
    "branchCode": "ALA",
    "SWIFT Code": "MBBELALA",
    "Bank Name": "MAYBANK LAO",
    "Address": "MAYBANK LAO BUILDING, 43-45-47 , LANE XANG AVENUE, HATSADY VILLAGE, CHANTHABOULY DISTRICT",
    "City": "VIENTIANE",
    "Branch": "",
    "Postcode": "01000",
    "Country": "Laos",
    "Connection": "Active"
  },
  {
    "bankCode": "PSVB",
    "countryCode": "LA",
    "branchCode": "ALA",
    "SWIFT Code": "PSVBLALA",
    "Bank Name": "PHONGSAVANH BANK LTD",
    "Address": "H O BUILDING, UNIT 01, KHAISONE PHOMVIHAN ROAD, BAN PHAKHAO, SAYTHANY DISTRICT",
    "City": "VIENTIANE",
    "Branch": "",
    "Postcode": "01000",
    "Country": "Laos",
    "Connection": "Active"
  },
  {
    "bankCode": "PBBE",
    "countryCode": "LA",
    "branchCode": "ALA",
    "SWIFT Code": "PBBELALA",
    "Bank Name": "PUBLIC BANK, VIENTIANE BRANCH, LAO P.D.R.",
    "Address": "100/1-4 , KHUNBULOM ROAD",
    "City": "VIENTIANE",
    "Branch": "",
    "Postcode": "01000",
    "Country": "Laos",
    "Connection": "Active"
  },
  {
    "bankCode": "RHBB",
    "countryCode": "LA",
    "branchCode": "ALA",
    "SWIFT Code": "RHBBLALA",
    "Bank Name": "RHB BANK LAO SOLE CO.,LTD",
    "Address": "01/008 , KAYSONE PHOMVIHANE",
    "City": "VIENTIANE",
    "Branch": "",
    "Postcode": "00856",
    "Country": "Laos",
    "Connection": "Active"
  },
  {
    "bankCode": "SICO",
    "countryCode": "LA",
    "branchCode": "ALA",
    "SWIFT Code": "SICOLALA",
    "Bank Name": "SIAM COMMERCIAL BANK PCL., THE",
    "Address": "117 , LANXANG-SAMSENTHAI RD, BAN SISAKET M, CHANTHA",
    "City": "VIENTIANE",
    "Branch": "",
    "Postcode": "01000",
    "Country": "Laos",
    "Connection": "Active"
  },
  {
    "bankCode": "STBD",
    "countryCode": "LA",
    "branchCode": "ALA",
    "SWIFT Code": "STBDLALA",
    "Bank Name": "ST BANK LTD",
    "Address": "SOUPHANOUVONG AVENUE, MUENGVATHA",
    "City": "VIENTIANE",
    "Branch": "",
    "Postcode": "01000",
    "Country": "Laos",
    "Connection": "Active"
  },
  {
    "bankCode": "TACB",
    "countryCode": "LA",
    "branchCode": "ALT",
    "SWIFT Code": "TACBLALT",
    "Bank Name": "TAIWAN COOPERATIVE BANK CO., LTD VIENTIANE CAPITAL BRANCH",
    "Address": "064 / 1, DONGPAYNA ROAD, SAPHANTHONG NEUA, SISATTANAK DIS",
    "City": "VIENTIANE",
    "Branch": "",
    "Postcode": "01000",
    "Country": "Laos",
    "Connection": "Active"
  },
  {
    "bankCode": "BFTV",
    "countryCode": "LA",
    "branchCode": "ALL",
    "SWIFT Code": "BFTVLALL",
    "Bank Name": "VCB LAOS",
    "Address": "UNIT 12, LANEXANG AVENUE, HATSADY",
    "City": "VIENTIANE",
    "Branch": "",
    "Postcode": "01000",
    "Country": "Laos",
    "Connection": "Active"
  },
  {
    "bankCode": "ICBV",
    "countryCode": "LA",
    "branchCode": "ALA",
    "SWIFT Code": "ICBVLALA",
    "Bank Name": "VIETINBANK LAO LIMITED",
    "Address": "268 , LANXANG AVENUE, HATSADY WARD, CHANTHABOULY DISTRICT",
    "City": "VIENTIANE",
    "Branch": "",
    "Postcode": "01000",
    "Country": "Laos",
    "Connection": "Active"
  }
]
module.exports = laos
