const latvia = [
  {
    "bankCode": "AIZK",
    "countryCode": "LV",
    "branchCode": "V22",
    "SWIFT Code": "AIZKLV22",
    "Bank Name": "ABLV BANK, AS IN LIQUIDATION",
    "Address": "MIHAILA TALA STREET 1",
    "City": "RIGA",
    "Branch": "",
    "Postcode": "LV-1045",
    "Country": "Latvia",
    "Connection": "Active"
  },
  {
    "bankCode": "AIZK",
    "countryCode": "LV",
    "branchCode": "CLN",
    "SWIFT Code": "AIZKLV22CLN",
    "Bank Name": "ABLV BANK, AS IN LIQUIDATION",
    "Address": "ELIZABETES STREET 23",
    "City": "RIGA",
    "Branch": "CLIENT SEGREGATED FUNDS",
    "Postcode": "LV-1010",
    "Country": "Latvia",
    "Connection": "Active"
  },
  {
    "bankCode": "IDXO",
    "countryCode": "LV",
    "branchCode": "V22",
    "SWIFT Code": "IDXOLV22",
    "Bank Name": "AS IDX1R",
    "Address": "ELIZABETES STREET 13-1A",
    "City": "RIGA",
    "Branch": "",
    "Postcode": "LV-1010",
    "Country": "Latvia",
    "Connection": "Active"
  },
  {
    "bankCode": "MULT",
    "countryCode": "LV",
    "branchCode": "V2X",
    "SWIFT Code": "MULTLV2X",
    "Bank Name": "AS INDUSTRA BANK",
    "Address": "MUITAS IELA 1",
    "City": "RIGA",
    "Branch": "",
    "Postcode": "LV-1010",
    "Country": "Latvia",
    "Connection": "Active"
  },
  {
    "bankCode": "LAPB",
    "countryCode": "LV",
    "branchCode": "V2X",
    "SWIFT Code": "LAPBLV2X",
    "Bank Name": "AS LPB BANK",
    "Address": "BRIVIBAS IELA 54",
    "City": "RIGA",
    "Branch": "",
    "Postcode": "LV-1011",
    "Country": "Latvia",
    "Connection": "Active"
  },
  {
    "bankCode": "LAPB",
    "countryCode": "LV",
    "branchCode": "TIP",
    "SWIFT Code": "LAPBLV2XTIP",
    "Bank Name": "AS LPB BANK",
    "Address": "BRIVIBAS IELA 54",
    "City": "RIGA",
    "Branch": "",
    "Postcode": "LV-1011",
    "Country": "Latvia",
    "Connection": "Active"
  },
  {
    "bankCode": "LACB",
    "countryCode": "LV",
    "branchCode": "EKS",
    "SWIFT Code": "LACBLV2XEKS",
    "Bank Name": "BANK OF LATVIA",
    "Address": "K. VALDEMARA STREET 2A",
    "City": "RIGA",
    "Branch": "",
    "Postcode": "LV-1050",
    "Country": "Latvia",
    "Connection": "Active"
  },
  {
    "bankCode": "LACB",
    "countryCode": "LV",
    "branchCode": "V2X",
    "SWIFT Code": "LACBLV2X",
    "Bank Name": "BANK OF LATVIA",
    "Address": "K. VALDEMARA STREET 2A",
    "City": "RIGA",
    "Branch": "",
    "Postcode": "LV-1050",
    "Country": "Latvia",
    "Connection": "Active"
  },
  {
    "bankCode": "LACB",
    "countryCode": "LV",
    "branchCode": "CCB",
    "SWIFT Code": "LACBLV2XCCB",
    "Bank Name": "BANK OF LATVIA",
    "Address": "K. VALDEMARA STREET 2A",
    "City": "RIGA",
    "Branch": "CCBM OPERATIONS",
    "Postcode": "LV-1050",
    "Country": "Latvia",
    "Connection": "Active"
  },
  {
    "bankCode": "LACB",
    "countryCode": "LV",
    "branchCode": "ZMS",
    "SWIFT Code": "LACBLV2XZMS",
    "Bank Name": "BANK OF LATVIA",
    "Address": "K. VALDEMARA STREET 2A",
    "City": "RIGA",
    "Branch": "INSTANT PAYMENTS",
    "Postcode": "LV-1050",
    "Country": "Latvia",
    "Connection": "Active"
  },
  {
    "bankCode": "LACB",
    "countryCode": "LV",
    "branchCode": "AMS",
    "SWIFT Code": "LACBLV2XAMS",
    "Bank Name": "BANK OF LATVIA",
    "Address": "K. VALDEMARA STREET 2A",
    "City": "RIGA",
    "Branch": "INSTANT PAYMENTS",
    "Postcode": "LV-1050",
    "Country": "Latvia",
    "Connection": "Active"
  },
  {
    "bankCode": "CBBR",
    "countryCode": "LV",
    "branchCode": "V22",
    "SWIFT Code": "CBBRLV22",
    "Bank Name": "BLUOR BANK AS",
    "Address": "SMILSU IELA 6",
    "City": "RIGA",
    "Branch": "",
    "Postcode": "LV-1050",
    "Country": "Latvia",
    "Connection": "Active"
  },
  {
    "bankCode": "CBBR",
    "countryCode": "LV",
    "branchCode": "OVE",
    "SWIFT Code": "CBBRLV22OVE",
    "Bank Name": "BLUOR BANK AS",
    "Address": "SMILSU IELA 6",
    "City": "RIGA",
    "Branch": "TGT ACC OVE",
    "Postcode": "LV-1050",
    "Country": "Latvia",
    "Connection": "Active"
  },
  {
    "bankCode": "CBBR",
    "countryCode": "LV",
    "branchCode": "TIP",
    "SWIFT Code": "CBBRLV22TIP",
    "Bank Name": "BLUOR BANK AS",
    "Address": "SMILSU IELA 6",
    "City": "RIGA",
    "Branch": "TIPS ACC",
    "Postcode": "LV-1050",
    "Country": "Latvia",
    "Connection": "Active"
  },
  {
    "bankCode": "JOPS",
    "countryCode": "LV",
    "branchCode": "V22",
    "SWIFT Code": "JOPSLV22",
    "Bank Name": "JOOL PAY SIA",
    "Address": "LIELIRBES 27",
    "City": "RIGA",
    "Branch": "",
    "Postcode": "LV-1046",
    "Country": "Latvia",
    "Connection": "Active"
  },
  {
    "bankCode": "PARX",
    "countryCode": "LV",
    "branchCode": "V22",
    "SWIFT Code": "PARXLV22",
    "Bank Name": "JSC CITADELE BANKA",
    "Address": "REPUBLIKAS LAUKUMS 2A",
    "City": "RIGA",
    "Branch": "",
    "Postcode": "LV-1010",
    "Country": "Latvia",
    "Connection": "Active"
  },
  {
    "bankCode": "PARX",
    "countryCode": "LV",
    "branchCode": "TIP",
    "SWIFT Code": "PARXLV22TIP",
    "Bank Name": "JSC CITADELE BANKA",
    "Address": "REPUBLIKAS LAUKUMS 2A",
    "City": "RIGA",
    "Branch": "TIPS ACC",
    "Postcode": "LV-1010",
    "Country": "Latvia",
    "Connection": "Active"
  },
  {
    "bankCode": "KKSL",
    "countryCode": "LV",
    "branchCode": "V22",
    "SWIFT Code": "KKSLLV22",
    "Bank Name": "KOOPERATIVA KRAJAIZDEVU SABIEDRIBA ALFABETA",
    "Address": "AUSEKLA STREET 3-60",
    "City": "RIGA",
    "Branch": "",
    "Postcode": "LV-1050",
    "Country": "Latvia",
    "Connection": "Active"
  },
  {
    "bankCode": "RIKO",
    "countryCode": "LV",
    "branchCode": "V2X",
    "SWIFT Code": "RIKOLV2X",
    "Bank Name": "LUMINOR BANK AS LATVIAN BRANCH",
    "Address": "SKANSTES STREET 12",
    "City": "RIGA",
    "Branch": "",
    "Postcode": "LV-1013",
    "Country": "Latvia",
    "Connection": "Active"
  },
  {
    "bankCode": "RIKO",
    "countryCode": "LV",
    "branchCode": "IPA",
    "SWIFT Code": "RIKOLV2XIPA",
    "Bank Name": "LUMINOR BANK AS LATVIAN BRANCH",
    "Address": "SKANSTES STREET 12",
    "City": "RIGA",
    "Branch": "",
    "Postcode": "LV-1013",
    "Country": "Latvia",
    "Connection": "Active"
  },
  {
    "bankCode": "MIMK",
    "countryCode": "LV",
    "branchCode": "V22",
    "SWIFT Code": "MIMKLV22",
    "Bank Name": "MINTOS MARKETPLACE AS",
    "Address": "FLOOR 6TH, SKANSTES CITY, SKANSTES STREET 50",
    "City": "RIGA",
    "Branch": "",
    "Postcode": "LV-1013",
    "Country": "Latvia",
    "Connection": "Active"
  },
  {
    "bankCode": "LCDE",
    "countryCode": "LV",
    "branchCode": "CLT",
    "SWIFT Code": "LCDELV22CLT",
    "Bank Name": "NASDAQ CSD SE",
    "Address": "VALNU STREET 1",
    "City": "RIGA",
    "Branch": "",
    "Postcode": "LV-1050",
    "Country": "Latvia",
    "Connection": "Active"
  },
  {
    "bankCode": "LCDE",
    "countryCode": "LV",
    "branchCode": "CEE",
    "SWIFT Code": "LCDELV22CEE",
    "Bank Name": "NASDAQ CSD SE",
    "Address": "VALNU STREET 1",
    "City": "RIGA",
    "Branch": "",
    "Postcode": "LV-1050",
    "Country": "Latvia",
    "Connection": "Active"
  },
  {
    "bankCode": "LCDE",
    "countryCode": "LV",
    "branchCode": "V22",
    "SWIFT Code": "LCDELV22",
    "Bank Name": "NASDAQ CSD SE",
    "Address": "VALNU STREET 1",
    "City": "RIGA",
    "Branch": "",
    "Postcode": "LV-1050",
    "Country": "Latvia",
    "Connection": "Active"
  },
  {
    "bankCode": "LCDE",
    "countryCode": "LV",
    "branchCode": "EEX",
    "SWIFT Code": "LCDELV22EEX",
    "Bank Name": "NASDAQ CSD SE",
    "Address": "VALNU STREET 1",
    "City": "RIGA",
    "Branch": "ESTONIAN EXCHANGE",
    "Postcode": "LV-1050",
    "Country": "Latvia",
    "Connection": "Active"
  },
  {
    "bankCode": "LCDE",
    "countryCode": "LV",
    "branchCode": "LVX",
    "SWIFT Code": "LCDELV22LVX",
    "Bank Name": "NASDAQ CSD SE",
    "Address": "VALNU STREET 1",
    "City": "RIGA",
    "Branch": "LATVIAN EXCHANGE",
    "Postcode": "LV-1050",
    "Country": "Latvia",
    "Connection": "Active"
  },
  {
    "bankCode": "LCDE",
    "countryCode": "LV",
    "branchCode": "LTX",
    "SWIFT Code": "LCDELV22LTX",
    "Bank Name": "NASDAQ CSD SE",
    "Address": "VALNU STREET 1",
    "City": "RIGA",
    "Branch": "LITHUANIAN EXCHANGE",
    "Postcode": "LV-1050",
    "Country": "Latvia",
    "Connection": "Active"
  },
  {
    "bankCode": "LCDE",
    "countryCode": "LV",
    "branchCode": "CLM",
    "SWIFT Code": "LCDELV22CLM",
    "Bank Name": "NASDAQ CSD SE",
    "Address": "VALNU STREET 1",
    "City": "RIGA",
    "Branch": "USED IN LATVIAN CENTRAL BANK",
    "Postcode": "LV-1050",
    "Country": "Latvia",
    "Connection": "Active"
  },
  {
    "bankCode": "OKOY",
    "countryCode": "LV",
    "branchCode": "V2X",
    "SWIFT Code": "OKOYLV2X",
    "Bank Name": "OP CORPORATE BANK PLC LATVIA BRANCH",
    "Address": "MUITAS IELA 1",
    "City": "RIGA",
    "Branch": "",
    "Postcode": "LV-1010",
    "Country": "Latvia",
    "Connection": "Active"
  },
  {
    "bankCode": "RIBR",
    "countryCode": "LV",
    "branchCode": "TIP",
    "SWIFT Code": "RIBRLV22TIP",
    "Bank Name": "REGIONALA INVESTICIJU BANKA",
    "Address": "J. ALUNANA 2",
    "City": "RIGA",
    "Branch": "",
    "Postcode": "LV-1010",
    "Country": "Latvia",
    "Connection": "Active"
  },
  {
    "bankCode": "RIBR",
    "countryCode": "LV",
    "branchCode": "V22",
    "SWIFT Code": "RIBRLV22",
    "Bank Name": "REGIONALA INVESTICIJU BANKA",
    "Address": "J. ALUNANA 2",
    "City": "RIGA",
    "Branch": "",
    "Postcode": "LV-1010",
    "Country": "Latvia",
    "Connection": "Active"
  },
  {
    "bankCode": "RTMB",
    "countryCode": "LV",
    "branchCode": "V2X",
    "SWIFT Code": "RTMBLV2X",
    "Bank Name": "RIETUMU BANKA",
    "Address": "VESETAS STREET 7",
    "City": "RIGA",
    "Branch": "",
    "Postcode": "LV-1013",
    "Country": "Latvia",
    "Connection": "Active"
  },
  {
    "bankCode": "UNLA",
    "countryCode": "LV",
    "branchCode": "TPS",
    "SWIFT Code": "UNLALV2XTPS",
    "Bank Name": "SEB BANKA",
    "Address": "SEB FINANCE CENTER, MEISTARU 1, VALDLAUCI, KEKAVAS PAG",
    "City": "RIGA",
    "Branch": "",
    "Postcode": "LV-1076",
    "Country": "Latvia",
    "Connection": "Active"
  },
  {
    "bankCode": "UNLA",
    "countryCode": "LV",
    "branchCode": "V2X",
    "SWIFT Code": "UNLALV2X",
    "Bank Name": "SEB BANKA",
    "Address": "SEB FINANCE CENTER, MEISTARU 1, VALDLAUCI, KEKAVAS PAG",
    "City": "RIGA",
    "Branch": "",
    "Postcode": "LV-1076",
    "Country": "Latvia",
    "Connection": "Active"
  },
  {
    "bankCode": "SIAX",
    "countryCode": "LV",
    "branchCode": "V22",
    "SWIFT Code": "SIAXLV22",
    "Bank Name": "SIA 'XPATE'",
    "Address": "DZIRNAVU 42",
    "City": "RIGA",
    "Branch": "",
    "Postcode": "LV-1010",
    "Country": "Latvia",
    "Connection": "Active"
  },
  {
    "bankCode": "TPRO",
    "countryCode": "LV",
    "branchCode": "V22",
    "SWIFT Code": "TPROLV22",
    "Bank Name": "SIA TRANSACT PRO",
    "Address": "KR. VALDEMARA 62",
    "City": "RIGA",
    "Branch": "",
    "Postcode": "LV-1013",
    "Country": "Latvia",
    "Connection": "Active"
  },
  {
    "bankCode": "LLBB",
    "countryCode": "LV",
    "branchCode": "222",
    "SWIFT Code": "LLBBLV2X222",
    "Bank Name": "SIGNET BANK AS",
    "Address": "ANTONIJAS 3",
    "City": "RIGA",
    "Branch": "",
    "Postcode": "LV-1010",
    "Country": "Latvia",
    "Connection": "Active"
  },
  {
    "bankCode": "LLBB",
    "countryCode": "LV",
    "branchCode": "V2X",
    "SWIFT Code": "LLBBLV2X",
    "Bank Name": "SIGNET BANK AS",
    "Address": "ANTONIJAS 3",
    "City": "RIGA",
    "Branch": "",
    "Postcode": "LV-1010",
    "Country": "Latvia",
    "Connection": "Active"
  },
  {
    "bankCode": "LLBB",
    "countryCode": "LV",
    "branchCode": "111",
    "SWIFT Code": "LLBBLV2X111",
    "Bank Name": "SIGNET BANK AS",
    "Address": "ANTONIJAS 3",
    "City": "RIGA",
    "Branch": "CUSTOMERS ACCOUNTS",
    "Postcode": "LV-1010",
    "Country": "Latvia",
    "Connection": "Active"
  },
  {
    "bankCode": "HABA",
    "countryCode": "LV",
    "branchCode": "TIP",
    "SWIFT Code": "HABALV22TIP",
    "Bank Name": "SWEDBANK AS",
    "Address": "BALASTA DAMBIS 1A",
    "City": "RIGA",
    "Branch": "",
    "Postcode": "LV-1048",
    "Country": "Latvia",
    "Connection": "Active"
  },
  {
    "bankCode": "HABA",
    "countryCode": "LV",
    "branchCode": "V22",
    "SWIFT Code": "HABALV22",
    "Bank Name": "SWEDBANK AS",
    "Address": "BALASTA DAMBIS 1A",
    "City": "RIGA",
    "Branch": "",
    "Postcode": "LV-1048",
    "Country": "Latvia",
    "Connection": "Active"
  },
  {
    "bankCode": "LAVF",
    "countryCode": "LV",
    "branchCode": "V22",
    "SWIFT Code": "LAVFLV22",
    "Bank Name": "TF BANK AB LATVIJAS FILIALE",
    "Address": "DELU IELA 4",
    "City": "RIGA",
    "Branch": "",
    "Postcode": "LV-1004",
    "Country": "Latvia",
    "Connection": "Active"
  },
  {
    "bankCode": "TREL",
    "countryCode": "LV",
    "branchCode": "ZIB",
    "SWIFT Code": "TRELLV22ZIB",
    "Bank Name": "TREASURY OF THE REPUBLIC OF LATVIA, THE",
    "Address": "SMILSU STREET 1",
    "City": "RIGA",
    "Branch": "",
    "Postcode": "LV-1919",
    "Country": "Latvia",
    "Connection": "Active"
  },
  {
    "bankCode": "TREL",
    "countryCode": "LV",
    "branchCode": "V22",
    "SWIFT Code": "TRELLV22",
    "Bank Name": "TREASURY OF THE REPUBLIC OF LATVIA, THE",
    "Address": "SMILSU STREET 1",
    "City": "RIGA",
    "Branch": "",
    "Postcode": "LV-1919",
    "Country": "Latvia",
    "Connection": "Active"
  },
  {
    "bankCode": "PANX",
    "countryCode": "LV",
    "branchCode": "V22",
    "SWIFT Code": "PANXLV22",
    "Bank Name": "UNIFIEDPOST PAYMENTS SA FILIALE LATVIJA",
    "Address": "DELU IELA 4",
    "City": "RIGA",
    "Branch": "",
    "Postcode": "LV-1004",
    "Country": "Latvia",
    "Connection": "Active"
  }
]
module.exports = latvia
