const lebanon = [
  {
    "countryCode": "CITI",
    "bankCode": "LB",
    "branchCode": "BBE",
    "SWIFT Code": "CITILBBE",
    "Bank Name": "CITIBANK NA-BEIRUT BRANCH",
    "Address": "BLOCK A, FLOOR 3, PARK AVENUE, BERYTUS PARKS",
    "City": "BEIRUT",
    "Branch": "",
    "Postcode": "2011 6201",
    "Country": "Lebanon",
    "Connection": "Active"
  },
  {
    "countryCode": "CLIB",
    "bankCode": "LB",
    "branchCode": "BBX",
    "SWIFT Code": "CLIBLBBX",
    "Bank Name": "CREDIT LIBANAIS S.A.L.",
    "Address": "CREDIT LIBANAIS TOWER, CORNICHE EL NAHR, ADLIEH, ASHRAFIEH",
    "City": "BEIRUT",
    "Branch": "",
    "Postcode": "",
    "Country": "Lebanon",
    "Connection": "Active"
  },
  {
    "countryCode": "CLIB",
    "bankCode": "LB",
    "branchCode": "DLP",
    "SWIFT Code": "CLIBLBBXDLP",
    "Bank Name": "CREDIT LIBANAIS S.A.L.",
    "Address": "CREDIT LIBANAIS TOWER, CORNICHE EL NAHR, ADLIEH, ASHRAFIEH",
    "City": "BEIRUT",
    "Branch": "DOMESTIC LEBANESE PAYMENTS",
    "Postcode": "",
    "Country": "Lebanon",
    "Connection": "Active"
  },
  {
    "countryCode": "CBCB",
    "bankCode": "LB",
    "branchCode": "BBE",
    "SWIFT Code": "CBCBLBBE",
    "Bank Name": "CREDITBANK SAL",
    "Address": "BECHIR GEMAYEL AVENUE, ACHRAFIEH",
    "City": "BEIRUT",
    "Branch": "",
    "Postcode": "",
    "Country": "Lebanon",
    "Connection": "Active"
  },
  {
    "countryCode": "CCSC",
    "bankCode": "LB",
    "branchCode": "BBE",
    "SWIFT Code": "CCSCLBBE",
    "Bank Name": "CSCBANK SAL",
    "Address": "150 COMMODORE STREET, HAMRA",
    "City": "BEIRUT",
    "Branch": "",
    "Postcode": "1103 2120",
    "Country": "Lebanon",
    "Connection": "Active"
  },
  {
    "countryCode": "ELBK",
    "bankCode": "LB",
    "branchCode": "BBX",
    "SWIFT Code": "ELBKLBBX",
    "Bank Name": "EMIRATES LEBANON BANK SAL",
    "Address": "BOURJ EL GHAZAL, AV FOUAD CHEHAB",
    "City": "BEIRUT",
    "Branch": "",
    "Postcode": "",
    "Country": "Lebanon",
    "Connection": "Active"
  },
  {
    "countryCode": "FBLE",
    "bankCode": "LB",
    "branchCode": "BBX",
    "SWIFT Code": "FBLELBBX",
    "Bank Name": "FEDERAL BANK OF LEBANON S A L",
    "Address": "VARTANIAN CENTER, 4 DORA HIGHWAY",
    "City": "BEIRUT",
    "Branch": "",
    "Postcode": "",
    "Country": "Lebanon",
    "Connection": "Active"
  },
  {
    "countryCode": "FBLE",
    "bankCode": "LB",
    "branchCode": "DLP",
    "SWIFT Code": "FBLELBBXDLP",
    "Bank Name": "FEDERAL BANK OF LEBANON S A L",
    "Address": "VARTANIAN CENTER, 4 DORA HIGHWAY",
    "City": "BEIRUT",
    "Branch": "DOMESTIC LOCAL PAYMENTS",
    "Postcode": "110-2209",
    "Country": "Lebanon",
    "Connection": "Active"
  },
  {
    "countryCode": "BKAW",
    "bankCode": "LB",
    "branchCode": "BBE",
    "SWIFT Code": "BKAWLBBE",
    "Bank Name": "FENICIA BANK S.A.L.",
    "Address": "FENECIA BANK BUILDING, FOCH STREET",
    "City": "BEIRUT",
    "Branch": "",
    "Postcode": "1103 2110",
    "Country": "Lebanon",
    "Connection": "Active"
  },
  {
    "countryCode": "FIDR",
    "bankCode": "LB",
    "branchCode": "BBX",
    "SWIFT Code": "FIDRLBBX",
    "Bank Name": "FIDUS SAL GROUPE SOCIETE GENERALE DE BANQUE AU LIBAN",
    "Address": "SEHNAOUI BUILDING, FLOOR 2, RIAD EL SOLH STREET",
    "City": "BEIRUT",
    "Branch": "",
    "Postcode": "",
    "Country": "Lebanon",
    "Connection": "Active"
  },
  {
    "countryCode": "FBLB",
    "bankCode": "LB",
    "branchCode": "BBX",
    "SWIFT Code": "FBLBLBBX",
    "Bank Name": "FINANCE BANK",
    "Address": "ABDEL AZIZ STREET, HAMRA",
    "City": "BEIRUT",
    "Branch": "",
    "Postcode": "",
    "Country": "Lebanon",
    "Connection": "Active"
  },
  {
    "countryCode": "FINK",
    "bankCode": "LB",
    "branchCode": "BBE",
    "SWIFT Code": "FINKLBBE",
    "Bank Name": "FIRST NATIONAL BANK S.A.L.",
    "Address": "FNB BUILDING, ALLENBY STREET",
    "City": "BEIRUT",
    "Branch": "",
    "Postcode": "",
    "Country": "Lebanon",
    "Connection": "Active"
  },
  {
    "countryCode": "FINK",
    "bankCode": "LB",
    "branchCode": "DLP",
    "SWIFT Code": "FINKLBBEDLP",
    "Bank Name": "FIRST NATIONAL BANK S.A.L.",
    "Address": "FNB BUILDING, ALLENBY STREET",
    "City": "BEIRUT",
    "Branch": "DOMESTIC LEBANESE PAYMENT",
    "Postcode": "110-435",
    "Country": "Lebanon",
    "Connection": "Active"
  },
  {
    "countryCode": "FRAI",
    "bankCode": "LB",
    "branchCode": "BBE",
    "SWIFT Code": "FRAILBBE",
    "Bank Name": "FRANSA INVEST BANK",
    "Address": "FRANSABANK CENTER, HAMRA STREET",
    "City": "BEIRUT",
    "Branch": "",
    "Postcode": "1107 2803",
    "Country": "Lebanon",
    "Connection": "Active"
  },
  {
    "countryCode": "FSAB",
    "bankCode": "LB",
    "branchCode": "BBX",
    "SWIFT Code": "FSABLBBX",
    "Bank Name": "FRANSABANK SAL",
    "Address": "FRANSABANK CENTER, HAMRA STREET",
    "City": "BEIRUT",
    "Branch": "",
    "Postcode": "",
    "Country": "Lebanon",
    "Connection": "Active"
  },
  {
    "countryCode": "HABB",
    "bankCode": "LB",
    "branchCode": "BBE",
    "SWIFT Code": "HABBLBBE",
    "Bank Name": "HABIB BANK LIMITED",
    "Address": "FLEIFEL BUILDING, MUSEUM HIGHWAY, BARBIR",
    "City": "BEIRUT",
    "Branch": "",
    "Postcode": "",
    "Country": "Lebanon",
    "Connection": "Active"
  },
  {
    "countryCode": "INLE",
    "bankCode": "LB",
    "branchCode": "BBE",
    "SWIFT Code": "INLELBBE",
    "Bank Name": "IBL BANK S.A.L.(FORMERLY INTERCONTINENTAL BANK OF LEBANON S.A.L.)",
    "Address": "CHARLES MALEK AVENUE",
    "City": "BEIRUT",
    "Branch": "",
    "Postcode": "",
    "Country": "Lebanon",
    "Connection": "Active"
  },
  {
    "countryCode": "IBLV",
    "bankCode": "LB",
    "branchCode": "BBE",
    "SWIFT Code": "IBLVLBBE",
    "Bank Name": "IBL INVESTMENT BANK SAL",
    "Address": "AL MADINA TOWER, FLOOR 1, RACHID KARAME, VERDUN",
    "City": "BEIRUT",
    "Branch": "",
    "Postcode": "",
    "Country": "Lebanon",
    "Connection": "Active"
  },
  {
    "countryCode": "IBTF",
    "bankCode": "LB",
    "branchCode": "BBE",
    "SWIFT Code": "IBTFLBBE",
    "Bank Name": "INVEST BANK (P.S.C.)",
    "Address": "INVEST BANK BUILDING, FLOOR GF-1, AIN AL-MRAYSE",
    "City": "BEIRUT",
    "Branch": "",
    "Postcode": "",
    "Country": "Lebanon",
    "Connection": "Active"
  },
  {},
  {
    "countryCode": "FFAI",
    "bankCode": "LB",
    "branchCode": "BBE",
    "SWIFT Code": "FFAILBBE",
    "Bank Name": "INVESTMENT AND CAPITAL BANK (I AND C) S.A.L",
    "Address": "128 FOCH STREET, ONE I AND C GATE, MARFAA, BEIRUT CENTRAL DISTRICT",
    "City": "BEIRUT",
    "Branch": "",
    "Postcode": "",
    "Country": "Lebanon",
    "Connection": "Active"
  },
  {
    "countryCode": "LIBB",
    "bankCode": "LB",
    "branchCode": "BBE",
    "SWIFT Code": "LIBBLBBE",
    "Bank Name": "LEBANESE ISLAMIC BANK S.A.L.",
    "Address": "LIBERTY TOWER BLDG, FLOOR 9, ROMA",
    "City": "BEIRUT",
    "Branch": "",
    "Postcode": "",
    "Country": "Lebanon",
    "Connection": "Active"
  },
  {
    "countryCode": "LIBB",
    "bankCode": "LB",
    "branchCode": "DLP",
    "SWIFT Code": "LIBBLBBEDLP",
    "Bank Name": "LEBANESE ISLAMIC BANK S.A.L.",
    "Address": "KANAFANI BLDG, FLOOR 1ST",
    "City": "BEIRUT",
    "Branch": "DOMESTIC LEBANESE PAYMENTS",
    "Postcode": "",
    "Country": "Lebanon",
    "Connection": "Active"
  },
  {
    "countryCode": "LEBS",
    "bankCode": "LB",
    "branchCode": "BBX",
    "SWIFT Code": "LEBSLBBX",
    "Bank Name": "LEBANESE SWISS BANK SAL",
    "Address": "CENTER CEBACO, DORA-TRIPOLI ROAD",
    "City": "BEIRUT",
    "Branch": "",
    "Postcode": "",
    "Country": "Lebanon",
    "Connection": "Active"
  },
  {
    "countryCode": "LGBA",
    "bankCode": "LB",
    "branchCode": "BBE",
    "SWIFT Code": "LGBALBBE",
    "Bank Name": "LGB BANK SAL",
    "Address": "ALLENBY STREET, RIAD EL SOLH, BEIRUT CENTRAL DSTR",
    "City": "BEIRUT",
    "Branch": "",
    "Postcode": "",
    "Country": "Lebanon",
    "Connection": "Active"
  },
  {
    "countryCode": "LIBK",
    "bankCode": "LB",
    "branchCode": "BBE",
    "SWIFT Code": "LIBKLBBE",
    "Bank Name": "LIBANK S.A.L. (LEVANT INVESTMENT BANK)",
    "Address": "SOFIL CENTER, FLOOR 4, 13 CHARLES MALEK AVENUE",
    "City": "BEIRUT",
    "Branch": "",
    "Postcode": "",
    "Country": "Lebanon",
    "Connection": "Active"
  },
  {
    "countryCode": "LIBK",
    "bankCode": "LB",
    "branchCode": "DLP",
    "SWIFT Code": "LIBKLBBEDLP",
    "Bank Name": "LIBANK S.A.L. (LEVANT INVESTMENT BANK)",
    "Address": "SOFIL CENTER, FLOOR 4, 13 CHARLES MALEK AVENUE",
    "City": "BEIRUT",
    "Branch": "DOMESTIC LEBANESE PAYMENTS",
    "Postcode": "",
    "Country": "Lebanon",
    "Connection": "Active"
  },
  {
    "countryCode": "LUCI",
    "bankCode": "LB",
    "branchCode": "BBX",
    "SWIFT Code": "LUCILBBX",
    "Bank Name": "LUCID INVESTMENT BANK S.A.L.",
    "Address": "109 ALLENBY",
    "City": "BEIRUT",
    "Branch": "",
    "Postcode": "",
    "Country": "Lebanon",
    "Connection": "Active"
  },
  {
    "countryCode": "MEAB",
    "bankCode": "LB",
    "branchCode": "BBE",
    "SWIFT Code": "MEABLBBE",
    "Bank Name": "MEAB BANK S.A.L.",
    "Address": "HEJEIJ BUILDING, ADNAN EL HAKIM STREET",
    "City": "BEIRUT",
    "Branch": "",
    "Postcode": "",
    "Country": "Lebanon",
    "Connection": "Active"
  },
  {
    "countryCode": "MECA",
    "bankCode": "LB",
    "branchCode": "BBE",
    "SWIFT Code": "MECALBBE",
    "Bank Name": "MECATTAF S.A.L",
    "Address": "MECATTAF BLDG, PRESIDENT AMINE GEMAYEL",
    "City": "EL METN",
    "Branch": "",
    "Postcode": "",
    "Country": "Lebanon",
    "Connection": "Active"
  },
  {
    "countryCode": "MIBL",
    "bankCode": "LB",
    "branchCode": "BBX",
    "SWIFT Code": "MIBLLBBX",
    "Bank Name": "MEDINVESTMENT BANK SAL",
    "Address": "MEDITERRANEE GROUP BUILDING, 482 CLEMENCEAU STREET, KANTARI",
    "City": "BEIRUT",
    "Branch": "",
    "Postcode": "2022 9302",
    "Country": "Lebanon",
    "Connection": "Active"
  },
  {
    "countryCode": "MIDR",
    "bankCode": "LB",
    "branchCode": "ASA",
    "SWIFT Code": "MIDRLBBEASA",
    "Bank Name": "MIDCLEAR S.A.L.",
    "Address": "",
    "City": "BEIRUT",
    "Branch": "",
    "Postcode": "",
    "Country": "Lebanon",
    "Connection": "Active"
  },
  {
    "countryCode": "MIDR",
    "bankCode": "LB",
    "branchCode": "BBE",
    "SWIFT Code": "MIDRLBBE",
    "Bank Name": "MIDCLEAR S.A.L.",
    "Address": "ARESCO CENTER, FLOOR 15, JUSTINIEN STREET, SANAYEH",
    "City": "BEIRUT",
    "Branch": "",
    "Postcode": "",
    "Country": "Lebanon",
    "Connection": "Active"
  },
  {
    "countryCode": "MEAL",
    "bankCode": "LB",
    "branchCode": "BBE",
    "SWIFT Code": "MEALLBBE",
    "Bank Name": "MIDDLE EAST AIRLINES-AIRLIBAN",
    "Address": "123 AIRPORT ROAD",
    "City": "BEIRUT",
    "Branch": "",
    "Postcode": "11206",
    "Country": "Lebanon",
    "Connection": "Active"
  },
  {
    "countryCode": "MINF",
    "bankCode": "LB",
    "branchCode": "BBE",
    "SWIFT Code": "MINFLBBE",
    "Bank Name": "MINISTRY OF FINANCE",
    "Address": "RIAD EL-SOLH SQUARE, DOWN TOWN BEIRUT",
    "City": "BEIRUT",
    "Branch": "",
    "Postcode": "",
    "Country": "Lebanon",
    "Connection": "Active"
  },
  {
    "countryCode": "NBOK",
    "bankCode": "LB",
    "branchCode": "BBE",
    "SWIFT Code": "NBOKLBBE",
    "Bank Name": "NATIONAL BANK OF KUWAIT (LEBANON) SAL",
    "Address": "B.A.C. BUILDING, JUSTINIEN STREET, SANAYEH",
    "City": "BEIRUT",
    "Branch": "",
    "Postcode": "",
    "Country": "Lebanon",
    "Connection": "Active"
  },
  {
    "countryCode": "NACB",
    "bankCode": "LB",
    "branchCode": "BBE",
    "SWIFT Code": "NACBLBBE",
    "Bank Name": "NORTH AFRICA COMMERCIAL BANK S.A.L.",
    "Address": "BEIRUT GARDEN BLOCK C, MARTYRS' SQUARE DOWN TOWN, DOWN TOWN",
    "City": "BEIRUT",
    "Branch": "",
    "Postcode": "",
    "Country": "Lebanon",
    "Connection": "Active"
  },
  {
    "countryCode": "OPTI",
    "bankCode": "LB",
    "branchCode": "DLP",
    "SWIFT Code": "OPTILBBEDLP",
    "Bank Name": "OPTIMUM INVEST SAL",
    "Address": "SOFIL CENTER BLOC C, FLOOR 4, CHARLES MALEK AVENUE, ACHRAFIEH",
    "City": "BEIRUT",
    "Branch": "",
    "Postcode": "",
    "Country": "Lebanon",
    "Connection": "Active"
  },
  {
    "countryCode": "OPTI",
    "bankCode": "LB",
    "branchCode": "BBE",
    "SWIFT Code": "OPTILBBE",
    "Bank Name": "OPTIMUM INVEST SAL",
    "Address": "SOFIL CENTER, BLOC C, FLOOR 4, CHARLES MALEK AVENUE, ACHRAFIEH",
    "City": "BEIRUT",
    "Branch": "",
    "Postcode": "",
    "Country": "Lebanon",
    "Connection": "Active"
  },
  {
    "countryCode": "QNBA",
    "bankCode": "LB",
    "branchCode": "BBE",
    "SWIFT Code": "QNBALBBE",
    "Bank Name": "QATAR NATIONAL BANK",
    "Address": "CAPITAL PLAZA BUILDING, AHMAD SHAWKI STREET, MINA EL HOSN",
    "City": "BEIRUT",
    "Branch": "",
    "Postcode": "",
    "Country": "Lebanon",
    "Connection": "Active"
  },
  {
    "countryCode": "QNBA",
    "bankCode": "LB",
    "branchCode": "DLP",
    "SWIFT Code": "QNBALBBEDLP",
    "Bank Name": "QATAR NATIONAL BANK",
    "Address": "CAPITAL PLAZA BUILDING, AHMAD SHAWKI STREET, MINA EL HOSN",
    "City": "BEIRUT",
    "Branch": "DOMESTIC LEBANESE PAYMENTS",
    "Postcode": "2028 1212",
    "Country": "Lebanon",
    "Connection": "Active"
  },
  {
    "countryCode": "RAFB",
    "bankCode": "LB",
    "branchCode": "BBE",
    "SWIFT Code": "RAFBLBBE",
    "Bank Name": "RAFIDAIN BANK",
    "Address": "FLOOR 1, MAKDESSI STREET, HAMRA",
    "City": "BEIRUT",
    "Branch": "",
    "Postcode": "",
    "Country": "Lebanon",
    "Connection": "Active"
  },
  {
    "countryCode": "BTLV",
    "bankCode": "LB",
    "branchCode": "BBE",
    "SWIFT Code": "BTLVLBBE",
    "Bank Name": "SARADAR BANK S.A.L.",
    "Address": "SARADAR BUILDING, CHARLES MALEK AVENUE",
    "City": "ACHRAFIEH",
    "Branch": "",
    "Postcode": "",
    "Country": "Lebanon",
    "Connection": "Active"
  },
  {
    "countryCode": "SLBL",
    "bankCode": "LB",
    "branchCode": "BBX",
    "SWIFT Code": "SLBLLBBX",
    "Bank Name": "SAUDI LEBANESE BANK SAL.",
    "Address": "BASHIR AL KASAR STREET, VERDUN",
    "City": "BEIRUT",
    "Branch": "HEAD OFFICE",
    "Postcode": "",
    "Country": "Lebanon",
    "Connection": "Active"
  },
  {
    "countryCode": "SGLI",
    "bankCode": "LB",
    "branchCode": "BBX",
    "SWIFT Code": "SGLILBBX",
    "Bank Name": "SOCIETE GENERALE DE BANQUE AU LIBAN S.A.L.",
    "Address": "SEHNAOUI BUILDING, SIN ELFIL ROND POINT, SALOUMEH",
    "City": "BEIRUT",
    "Branch": "",
    "Postcode": "",
    "Country": "Lebanon",
    "Connection": "Active"
  },
  {
    "countryCode": "SYLC",
    "bankCode": "LB",
    "branchCode": "BBE",
    "SWIFT Code": "SYLCLBBE",
    "Bank Name": "SYRIAN LEBANESE COMMERCIAL BANK SAL.",
    "Address": "AL HAMRA BUILDING, AL HAMRA STREET",
    "City": "BEIRUT",
    "Branch": "",
    "Postcode": "",
    "Country": "Lebanon",
    "Connection": "Active"
  },
  {
    "countryCode": "ALCV",
    "bankCode": "LB",
    "branchCode": "BBE",
    "SWIFT Code": "ALCVLBBE",
    "Bank Name": "AL BARAKA BANK S.A.L.",
    "Address": "BAC CENTER, FLOOR 12 JUSTINIAN, STREET, NEAR CHAMBER OF COMMERCE, AND INDUSTRY",
    "City": "BEIRUT",
    "Branch": "",
    "Postcode": "",
    "Country": "Lebanon",
    "Connection": "Active"
  },
  {
    "countryCode": "ALCV",
    "bankCode": "LB",
    "branchCode": "DLP",
    "SWIFT Code": "ALCVLBBEDLP",
    "Bank Name": "AL BARAKA BANK S.A.L.",
    "Address": "BAC CENTER, FLOOR 12 JUSTINIAN, STREET, NEAR CHAMBER OF COMMERCE, AND INDUSTRY",
    "City": "BEIRUT",
    "Branch": "DOMESTICS LEBANESE PAYMENTS",
    "Postcode": "113-5683",
    "Country": "Lebanon",
    "Connection": "Active"
  },
  {
    "countryCode": "MABA",
    "bankCode": "LB",
    "branchCode": "BBE",
    "SWIFT Code": "MABALBBE",
    "Bank Name": "AM BANK S.A.L.",
    "Address": "YARED BUILDING, FLOOR 3, ABDUL AZIZ STREET",
    "City": "BEIRUT",
    "Branch": "",
    "Postcode": "",
    "Country": "Lebanon",
    "Connection": "Active"
  },
  {
    "countryCode": "MABA",
    "bankCode": "LB",
    "branchCode": "DLP",
    "SWIFT Code": "MABALBBEDLP",
    "Bank Name": "AM BANK S.A.L.",
    "Address": "YARED BUILDING, FLOOR 3, ABDUL AZIZ STREET",
    "City": "BEIRUT",
    "Branch": "DOMESTIC LEBANESE PAYMENTS",
    "Postcode": "1136260",
    "Country": "Lebanon",
    "Connection": "Active"
  },
  {
    "countryCode": "ARAI",
    "bankCode": "LB",
    "branchCode": "BBE",
    "SWIFT Code": "ARAILBBE",
    "Bank Name": "ARAB AFRICAN INTERNATIONAL BANK",
    "Address": "ARAB AFRICAN INTL BANK BUILDING, RIAD EL SOLH STREET",
    "City": "BEIRUT",
    "Branch": "",
    "Postcode": "",
    "Country": "Lebanon",
    "Connection": "Active"
  },
  {
    "countryCode": "ARAI",
    "bankCode": "LB",
    "branchCode": "DLP",
    "SWIFT Code": "ARAILBBEDLP",
    "Bank Name": "ARAB AFRICAN INTERNATIONAL BANK",
    "Address": "ARAB AFRICAN INTL BANK BUILDING, RIAD EL SOLH STREET",
    "City": "BEIRUT",
    "Branch": "DEPARTMENT",
    "Postcode": "11-6066",
    "Country": "Lebanon",
    "Connection": "Active"
  },
  {
    "countryCode": "ARBV",
    "bankCode": "LB",
    "branchCode": "BBE",
    "SWIFT Code": "ARBVLBBE",
    "Bank Name": "ARAB BANK (SWITZERLAND) LEBANON SAL",
    "Address": "BLOCK 25, FLOOR 4, ALLENBY STREET, BEIRUT SOUKS",
    "City": "BEIRUT",
    "Branch": "",
    "Postcode": "1107 2230",
    "Country": "Lebanon",
    "Connection": "Active"
  },
  {
    "countryCode": "ARAB",
    "bankCode": "LB",
    "branchCode": "0B9",
    "SWIFT Code": "ARABLBBX0B9",
    "Bank Name": "ARAB BANK PLC",
    "Address": "RIAD EL SOLH - BANKS STREET",
    "City": "BEIRUT",
    "Branch": "HAZMIEH",
    "Postcode": "",
    "Country": "Lebanon",
    "Connection": "Active"
  },
  {
    "countryCode": "ARAB",
    "bankCode": "LB",
    "branchCode": "BBX",
    "SWIFT Code": "ARABLBBX",
    "Bank Name": "ARAB BANK PLC",
    "Address": "RIAD EL SOLH - BANKS STREET",
    "City": "BEIRUT",
    "Branch": "LEBANON BRANCHES CENTRE",
    "Postcode": "",
    "Country": "Lebanon",
    "Connection": "Active"
  },
  {
    "countryCode": "ARAB",
    "bankCode": "LB",
    "branchCode": "TBO",
    "SWIFT Code": "ARABLBBXTBO",
    "Bank Name": "ARAB BANK PLC",
    "Address": "11-1015 RIAD EL SOLH - BANKS STREET",
    "City": "BEIRUT",
    "Branch": "TREASURY BACKOFFICE",
    "Postcode": "1107 2070",
    "Country": "Lebanon",
    "Connection": "Active"
  },
  {
    "countryCode": "ARAB",
    "bankCode": "LB",
    "branchCode": "0B7",
    "SWIFT Code": "ARABLBBX0B7",
    "Bank Name": "ARAB BANK PLC",
    "Address": "SHIYAH HIGHWAY",
    "City": "SHYAH",
    "Branch": "SHYAH BRANCH",
    "Postcode": "",
    "Country": "Lebanon",
    "Connection": "Active"
  },
  {
    "countryCode": "ARAB",
    "bankCode": "LB",
    "branchCode": "0B8",
    "SWIFT Code": "ARABLBBX0B8",
    "Bank Name": "ARAB BANK PLC",
    "Address": "SIN EL FIL HIGHWAY",
    "City": "SIN EL-FIL",
    "Branch": "SIN EL-FIL BRANCH",
    "Postcode": "",
    "Country": "Lebanon",
    "Connection": "Active"
  },
  {
    "countryCode": "AFCO",
    "bankCode": "LB",
    "branchCode": "BBE",
    "SWIFT Code": "AFCOLBBE",
    "Bank Name": "ARAB FINANCE CORPORATION SAL",
    "Address": "NEW STARCO BLDG., STARCO CENTER, FLOOR 4 RIZKALLAH STREET, MINA EL HOSN",
    "City": "BEIRUT",
    "Branch": "",
    "Postcode": "",
    "Country": "Lebanon",
    "Connection": "Active"
  },
  {
    "countryCode": "AFHO",
    "bankCode": "LB",
    "branchCode": "BBE",
    "SWIFT Code": "AFHOLBBE",
    "Bank Name": "ARAB FINANCE HOUSE SAL (ISLAMIC BANK)",
    "Address": "AFH TOWER, CORNICHE EL MAZRAA, SAEB SALAM AVE",
    "City": "BEIRUT",
    "Branch": "",
    "Postcode": "11273",
    "Country": "Lebanon",
    "Connection": "Active"
  },
  {
    "countryCode": "AEEB",
    "bankCode": "LB",
    "branchCode": "BBE",
    "SWIFT Code": "AEEBLBBE",
    "Bank Name": "AREEBA",
    "Address": "M1 BUILDING, FLOOR 7, OMAR DAOUK",
    "City": "BEIRUT",
    "Branch": "",
    "Postcode": "",
    "Country": "Lebanon",
    "Connection": "Active"
  },
  {
    "countryCode": "LICO",
    "bankCode": "LB",
    "branchCode": "BBX",
    "SWIFT Code": "LICOLBBX",
    "Bank Name": "B.L.C. BANK S.A.L.",
    "Address": "ADLIEH SQUARE",
    "City": "BEIRUT",
    "Branch": "",
    "Postcode": "",
    "Country": "Lebanon",
    "Connection": "Active"
  },
  {
    "countryCode": "AUDB",
    "bankCode": "LB",
    "branchCode": "BBX",
    "SWIFT Code": "AUDBLBBX",
    "Bank Name": "BANK AUDI S.A.L.",
    "Address": "AUDI PLAZA, OMAR DAOUK STREET, BAB IDRISS",
    "City": "BEIRUT",
    "Branch": "",
    "Postcode": "2021 8102",
    "Country": "Lebanon",
    "Connection": "Active"
  },
  {
    "countryCode": "BABI",
    "bankCode": "LB",
    "branchCode": "BBE",
    "SWIFT Code": "BABILBBE",
    "Bank Name": "BANK OF BAGHDAD",
    "Address": "TOWERS BUILDING, FLOOR 1, MINET EL HOSN",
    "City": "BEIRUT",
    "Branch": "",
    "Postcode": "",
    "Country": "Lebanon",
    "Connection": "Active"
  },
  {
    "countryCode": "BOBP",
    "bankCode": "LB",
    "branchCode": "BBE",
    "SWIFT Code": "BOBPLBBE",
    "Bank Name": "BANK OF BEIRUT INVEST S.A.L",
    "Address": "BANK OF BEIRUT BLDG, RIYAD EL SOLH STREET",
    "City": "BEIRUT",
    "Branch": "",
    "Postcode": "",
    "Country": "Lebanon",
    "Connection": "Active"
  },
  {
    "countryCode": "BABE",
    "bankCode": "LB",
    "branchCode": "BBE",
    "SWIFT Code": "BABELBBE",
    "Bank Name": "BANK OF BEIRUT S.A.L.",
    "Address": "FOCH STREET, BEIRUT CENTRAL DISTRICT",
    "City": "BEIRUT",
    "Branch": "",
    "Postcode": "",
    "Country": "Lebanon",
    "Connection": "Active"
  },
  {
    "countryCode": "BABE",
    "bankCode": "LB",
    "branchCode": "DLP",
    "SWIFT Code": "BABELBBEDLP",
    "Bank Name": "BANK OF BEIRUT S.A.L.",
    "Address": "FOCH STREET, BEIRUT CENTRAL DISTRICT",
    "City": "BEIRUT",
    "Branch": "",
    "Postcode": "",
    "Country": "Lebanon",
    "Connection": "Active"
  },
  {
    "countryCode": "MEDL",
    "bankCode": "LB",
    "branchCode": "BBX",
    "SWIFT Code": "MEDLLBBX",
    "Bank Name": "BANKMED,SAL",
    "Address": "GROUP MEDITERRANEE BUILDING, 2022 CLEMENCEAU STREET, KANTARI",
    "City": "BEIRUT",
    "Branch": "",
    "Postcode": "",
    "Country": "Lebanon",
    "Connection": "Active"
  },
  {
    "countryCode": "EUMO",
    "bankCode": "LB",
    "branchCode": "BBE",
    "SWIFT Code": "EUMOLBBE",
    "Bank Name": "BANQUE BEMO SAL",
    "Address": "BEMO BLDG. ASHRAF, ELIAS SARKIS AVE",
    "City": "BEIRUT",
    "Branch": "",
    "Postcode": "",
    "Country": "Lebanon",
    "Connection": "Active"
  },
  {
    "countryCode": "BCNB",
    "bankCode": "LB",
    "branchCode": "BBE",
    "SWIFT Code": "BCNBLBBE",
    "Bank Name": "BANQUE DE CREDIT NATIONAL S.A.L.",
    "Address": "MEDGULF BUILDING, FLOOR 1, PATRIARCHE HOYAYEK STREET, BEIRUT CENTRAL DISTRICT",
    "City": "BEIRUT",
    "Branch": "",
    "Postcode": "",
    "Country": "Lebanon",
    "Connection": "Active"
  },
  {
    "countryCode": "BCNB",
    "bankCode": "LB",
    "branchCode": "DLP",
    "SWIFT Code": "BCNBLBBEDLP",
    "Bank Name": "BANQUE DE CREDIT NATIONAL S.A.L.",
    "Address": "MEDGULF BUILDING, FLOOR 1, PATRIARCHE HOYAYEK STREET, BEIRUT CENTRAL DISTRICT",
    "City": "BEIRUT",
    "Branch": "FRESH ACCOUNT",
    "Postcode": "110-204",
    "Country": "Lebanon",
    "Connection": "Active"
  },
  {
    "countryCode": "LHBA",
    "bankCode": "LB",
    "branchCode": "BBX",
    "SWIFT Code": "LHBALBBX",
    "Bank Name": "BANQUE DE L'HABITAT S.A.L.",
    "Address": "CITY DORA II, FLOOR 6-7-8, DORA MAIN ROAD",
    "City": "BEIRUT",
    "Branch": "",
    "Postcode": "",
    "Country": "Lebanon",
    "Connection": "Active"
  },
  {
    "countryCode": "LHBA",
    "bankCode": "LB",
    "branchCode": "DLP",
    "SWIFT Code": "LHBALBBXDLP",
    "Bank Name": "BANQUE DE L'HABITAT S.A.L.",
    "Address": "CITY DORA II, FLOOR 6-7-8, DORA MAIN ROAD",
    "City": "BEIRUT",
    "Branch": "FRESH",
    "Postcode": "",
    "Country": "Lebanon",
    "Connection": "Active"
  },
  {
    "countryCode": "BDLC",
    "bankCode": "LB",
    "branchCode": "BBG",
    "SWIFT Code": "BDLCLBBG",
    "Bank Name": "BANQUE DU LIBAN",
    "Address": "MASRAF LUBNAN STREET",
    "City": "BEIRUT",
    "Branch": "",
    "Postcode": "",
    "Country": "Lebanon",
    "Connection": "Active"
  },
  {
    "countryCode": "BDLC",
    "bankCode": "LB",
    "branchCode": "BBF",
    "SWIFT Code": "BDLCLBBF",
    "Bank Name": "BANQUE DU LIBAN",
    "Address": "MASRAF LUBNAN STREET",
    "City": "BEIRUT",
    "Branch": "",
    "Postcode": "",
    "Country": "Lebanon",
    "Connection": "Active"
  },
  {
    "countryCode": "BDLC",
    "bankCode": "LB",
    "branchCode": "BBA",
    "SWIFT Code": "BDLCLBBA",
    "Bank Name": "BANQUE DU LIBAN",
    "Address": "MASRAF LUBNAN STREET",
    "City": "BEIRUT",
    "Branch": "",
    "Postcode": "",
    "Country": "Lebanon",
    "Connection": "Active"
  },
  {
    "countryCode": "BDLC",
    "bankCode": "LB",
    "branchCode": "BBX",
    "SWIFT Code": "BDLCLBBX",
    "Bank Name": "BANQUE DU LIBAN",
    "Address": "MASRAF LUBNAN STREET",
    "City": "BEIRUT",
    "Branch": "",
    "Postcode": "",
    "Country": "Lebanon",
    "Connection": "Active"
  },
  {
    "countryCode": "BDLC",
    "bankCode": "LB",
    "branchCode": "TIA",
    "SWIFT Code": "BDLCLBBXTIA",
    "Bank Name": "BANQUE DU LIBAN",
    "Address": "RUE BANQUE DU LIBAN HAMRA",
    "City": "BEIRUT",
    "Branch": "",
    "Postcode": "",
    "Country": "Lebanon",
    "Connection": "Active"
  },
  {
    "countryCode": "BDLC",
    "bankCode": "LB",
    "branchCode": "ASA",
    "SWIFT Code": "BDLCLBBXASA",
    "Bank Name": "BANQUE DU LIBAN",
    "Address": "RUE BANQUE DU LIBAN HAMRA",
    "City": "BEIRUT",
    "Branch": "",
    "Postcode": "",
    "Country": "Lebanon",
    "Connection": "Active"
  },
  {
    "countryCode": "BDLC",
    "bankCode": "LB",
    "branchCode": "BBC",
    "SWIFT Code": "BDLCLBBC",
    "Bank Name": "BANQUE DU LIBAN",
    "Address": "MASRAF LUBNAN STREET",
    "City": "BEIRUT",
    "Branch": "",
    "Postcode": "",
    "Country": "Lebanon",
    "Connection": "Active"
  },
  {
    "countryCode": "BDLC",
    "bankCode": "LB",
    "branchCode": "ACD",
    "SWIFT Code": "BDLCLBBXACD",
    "Bank Name": "BANQUE DU LIBAN",
    "Address": "RUE BANQUE DU LIBAN HAMRA",
    "City": "BEIRUT",
    "Branch": "ACCOUNTING DEPARTMENT",
    "Postcode": "",
    "Country": "Lebanon",
    "Connection": "Active"
  },
  {
    "countryCode": "BDLC",
    "bankCode": "LB",
    "branchCode": "COD",
    "SWIFT Code": "BDLCLBBXCOD",
    "Bank Name": "BANQUE DU LIBAN",
    "Address": "RUE BANQUE DU LIBAN HAMRA",
    "City": "BEIRUT",
    "Branch": "CURRENT OPERATIONS DEPARTMENT",
    "Postcode": "",
    "Country": "Lebanon",
    "Connection": "Active"
  },
  {
    "countryCode": "BDLC",
    "bankCode": "LB",
    "branchCode": "FOD",
    "SWIFT Code": "BDLCLBBXFOD",
    "Bank Name": "BANQUE DU LIBAN",
    "Address": "RUE BANQUE DU LIBAN HAMRA",
    "City": "BEIRUT",
    "Branch": "FINANCIAL OPERATIONS DEPARTMENT",
    "Postcode": "",
    "Country": "Lebanon",
    "Connection": "Active"
  },
  {
    "countryCode": "BDLC",
    "bankCode": "LB",
    "branchCode": "FXD",
    "SWIFT Code": "BDLCLBBXFXD",
    "Bank Name": "BANQUE DU LIBAN",
    "Address": "RUE BANQUE DU LIBAN HAMRA",
    "City": "BEIRUT",
    "Branch": "FOREIGN EXCHANGE DEPARTMENT",
    "Postcode": "",
    "Country": "Lebanon",
    "Connection": "Active"
  },
  {
    "countryCode": "BDLC",
    "bankCode": "LB",
    "branchCode": "MOF",
    "SWIFT Code": "BDLCLBBXMOF",
    "Bank Name": "BANQUE DU LIBAN",
    "Address": "",
    "City": "BEIRUT",
    "Branch": "MINISTRY OF FINANCE - TREASURY AND PUBLIC DEBT DIRECTORATE",
    "Postcode": "",
    "Country": "Lebanon",
    "Connection": "Active"
  },
  {
    "countryCode": "BLFS",
    "bankCode": "LB",
    "branchCode": "BBX",
    "SWIFT Code": "BLFSLBBX",
    "Bank Name": "BANQUE LIBANO FRANCAISE",
    "Address": "LIBERTY TOWER PLAZA BUILDING, ROME STREET, HAMRA",
    "City": "BEIRUT",
    "Branch": "",
    "Postcode": "",
    "Country": "Lebanon",
    "Connection": "Active"
  },
  {
    "countryCode": "BMIS",
    "bankCode": "LB",
    "branchCode": "BBE",
    "SWIFT Code": "BMISLBBE",
    "Bank Name": "BANQUE MISR LIBAN S.A.L.",
    "Address": "RIAD ELSOLH STREET",
    "City": "BEIRUT",
    "Branch": "",
    "Postcode": "",
    "Country": "Lebanon",
    "Connection": "Active"
  },
  {
    "countryCode": "BBAC",
    "bankCode": "LB",
    "branchCode": "BBX",
    "SWIFT Code": "BBACLBBX",
    "Bank Name": "BBAC SAL",
    "Address": "250 CLEMENCEAU STREET",
    "City": "BEIRUT",
    "Branch": "",
    "Postcode": "",
    "Country": "Lebanon",
    "Connection": "Active"
  },
  {
    "countryCode": "BLOM",
    "bankCode": "LB",
    "branchCode": "BBX",
    "SWIFT Code": "BLOMLBBX",
    "Bank Name": "BLOM BANK S.A.L.",
    "Address": "BLOM BUILDING, RASHID KARAMEH STREET",
    "City": "BEIRUT",
    "Branch": "",
    "Postcode": "1107 2807",
    "Country": "Lebanon",
    "Connection": "Active"
  },
  {
    "countryCode": "BDBL",
    "bankCode": "LB",
    "branchCode": "BBE",
    "SWIFT Code": "BDBLLBBE",
    "Bank Name": "BLOM DEVELOPMENT BANK S.A.L.",
    "Address": "BLOM BANK BUILDING, CORNICHE EL MAZRAA, BLVD SAEB SALAM",
    "City": "BEIRUT",
    "Branch": "",
    "Postcode": "",
    "Country": "Lebanon",
    "Connection": "Active"
  },
  {
    "countryCode": "BLIN",
    "bankCode": "LB",
    "branchCode": "BBE",
    "SWIFT Code": "BLINLBBE",
    "Bank Name": "BLOMINVEST BANK S.A.L.",
    "Address": "BLOM BLDG, RASHID KARAMEH ST",
    "City": "BEIRUT",
    "Branch": "",
    "Postcode": "1107 2807",
    "Country": "Lebanon",
    "Connection": "Active"
  },
  {
    "countryCode": "SONB",
    "bankCode": "LB",
    "branchCode": "BBE",
    "SWIFT Code": "SONBLBBE",
    "Bank Name": "BSL BANK S.A.L.",
    "Address": "SNBSL BUILDING, RIAD SOLH STREET",
    "City": "BEIRUT",
    "Branch": "",
    "Postcode": "11957",
    "Country": "Lebanon",
    "Connection": "Active"
  },
  {
    "countryCode": "BYBA",
    "bankCode": "LB",
    "branchCode": "BBX",
    "SWIFT Code": "BYBALBBX",
    "Bank Name": "BYBLOS BANK S.A.L.",
    "Address": "BYBLOS TOWER, ELIAS SARKIS AVE",
    "City": "BEIRUT",
    "Branch": "",
    "Postcode": "",
    "Country": "Lebanon",
    "Connection": "Active"
  },
  {
    "countryCode": "BYBI",
    "bankCode": "LB",
    "branchCode": "BBX",
    "SWIFT Code": "BYBILBBX",
    "Bank Name": "BYBLOS INVEST BANK S.A.L.",
    "Address": "BYBLOS TOWER, PRESIDENT ELIAS SARKIS AVENUE",
    "City": "BEIRUT",
    "Branch": "",
    "Postcode": "1107 2811",
    "Country": "Lebanon",
    "Connection": "Active"
  },
  {
    "countryCode": "CEDX",
    "bankCode": "LB",
    "branchCode": "BBE",
    "SWIFT Code": "CEDXLBBE",
    "Bank Name": "CEDRUS BANK S.A.L.",
    "Address": "DORA HIGHWAY",
    "City": "BEIRUT",
    "Branch": "",
    "Postcode": "",
    "Country": "Lebanon",
    "Connection": "Active"
  },
  {
    "countryCode": "CIBX",
    "bankCode": "LB",
    "branchCode": "BBE",
    "SWIFT Code": "CIBXLBBE",
    "Bank Name": "CEDRUS INVEST BANK S.A.L",
    "Address": "CEDRUS BANK BUILDING, FLOOR 6, DORA HIGHWAY",
    "City": "BEIRUT",
    "Branch": "",
    "Postcode": "",
    "Country": "Lebanon",
    "Connection": "Active"
  }
]
module.exports = lebanon
