const liberia = [
  {
    "bankCode": "ACLI",
    "countryCode": "LR",
    "branchCode": "RLM",
    "SWIFT Code": "ACLILRLM",
    "Bank Name": "ACCESSBANK LIBERIA LIMITED",
    "Address": "20TH STREET, TUBMAN BOULEVARD, SINKOR",
    "City": "MONROVIA",
    "Branch": "",
    "Postcode": "1000",
    "Country": "Liberia",
    "Connection": "Active"
  },
  {},
  {
    "bankCode": "CBLR",
    "countryCode": "LR",
    "branchCode": "RLA",
    "SWIFT Code": "CBLRLRLA",
    "Bank Name": "CENTRAL BANK OF LIBERIA",
    "Address": "CENTRAL BANK OF LIBERIA BUILDING, WARREN AND CAREY STREETS",
    "City": "MONROVIA",
    "Branch": "",
    "Postcode": "1000",
    "Country": "Liberia",
    "Connection": "Active"
  },
  {
    "bankCode": "CBLR",
    "countryCode": "LR",
    "branchCode": "RLM",
    "SWIFT Code": "CBLRLRLM",
    "Bank Name": "CENTRAL BANK OF LIBERIA",
    "Address": "ASHMUN AND LYNCH STREETS",
    "City": "MONROVIA",
    "Branch": "",
    "Postcode": "1000",
    "Country": "Liberia",
    "Connection": "Active"
  },
  {
    "bankCode": "ECOC",
    "countryCode": "LR",
    "branchCode": "RLM",
    "SWIFT Code": "ECOCLRLM",
    "Bank Name": "ECOBANK LIBERIA LIMITED",
    "Address": "CHURCH OFFICE BUILDING, ASHMUN / RANDALL STREETS",
    "City": "MONROVIA",
    "Branch": "",
    "Postcode": "4825",
    "Country": "Liberia",
    "Connection": "Active"
  },
  {
    "bankCode": "PHBX",
    "countryCode": "LR",
    "branchCode": "RLM",
    "SWIFT Code": "PHBXLRLM",
    "Bank Name": "GLOBAL BANK LIBERIA LIMITED (MEMBER BANKPHB GROUP)",
    "Address": "6TH STREET SINKOR",
    "City": "MONROVIA",
    "Branch": "",
    "Postcode": "1442",
    "Country": "Liberia",
    "Connection": "Active"
  },
  {
    "bankCode": "GTBI",
    "countryCode": "LR",
    "branchCode": "RLM",
    "SWIFT Code": "GTBILRLM",
    "Bank Name": "GUARANTY TRUST BANK (LIBERIA) LIMITED",
    "Address": "13TH STREET, SINKOR, TUBMAN BOULEVARD",
    "City": "MONROVIA",
    "Branch": "",
    "Postcode": "",
    "Country": "Liberia",
    "Connection": "Active"
  },
  {
    "bankCode": "IBLR",
    "countryCode": "LR",
    "branchCode": "RLM",
    "SWIFT Code": "IBLRLRLM",
    "Bank Name": "INTERNATIONAL BANK (LIBERIA) LIMITED",
    "Address": "KING BUILDING, BROAD STREET",
    "City": "MONROVIA",
    "Branch": "",
    "Postcode": "1935",
    "Country": "Liberia",
    "Connection": "Active"
  },
  {
    "bankCode": "LBDE",
    "countryCode": "LR",
    "branchCode": "RLM",
    "SWIFT Code": "LBDELRLM",
    "Bank Name": "LIBERIAN BANK FOR DEVELOPMENT AND INVESTMENT",
    "Address": "9TH STREET, SINKOR",
    "City": "MONROVIA",
    "Branch": "",
    "Postcode": "1000",
    "Country": "Liberia",
    "Connection": "Active"
  },
  {
    "bankCode": "GNER",
    "countryCode": "LR",
    "branchCode": "RLM",
    "SWIFT Code": "GNERLRLM",
    "Bank Name": "SAPELLE INTERNATIONAL BANK LIBERIA LIMITED (SIBLL)",
    "Address": "LUKE BUILDING, BROAD STREET",
    "City": "MONROVIA",
    "Branch": "",
    "Postcode": "1935",
    "Country": "Liberia",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "LR",
    "branchCode": "RLM",
    "SWIFT Code": "UNAFLRLM",
    "Bank Name": "UNITED BANK FOR AFRICA (LIBERIA) LIMITED",
    "Address": "BROAD AND NELSON STREET",
    "City": "MONROVIA",
    "Branch": "",
    "Postcode": "4523",
    "Country": "Liberia",
    "Connection": "Active"
  }
]
module.exports = liberia
