const liechtenstein = [
  {
    "countryCode": "AMNS",
    "bankCode": "LI",
    "branchCode": "I22",
    "SWIFT Code": "AMNSLI22",
    "Bank Name": "AMNIS EUROPE AG",
    "Address": "GEWERBEWEG 15",
    "City": "VADUZ",
    "Branch": "",
    "Postcode": "9490",
    "Country": "Liechtenstein",
    "Connection": "Active"
  },
  {
    "countryCode": "BFRI",
    "bankCode": "LI",
    "branchCode": "I22",
    "SWIFT Code": "BFRILI22",
    "Bank Name": "BANK FRICK AND CO AKTIENGESELLSCHAFT",
    "Address": "LANDSTRASSE 14",
    "City": "BALZERS",
    "Branch": "",
    "Postcode": "9496",
    "Country": "Liechtenstein",
    "Connection": "Active"
  },
  {
    "countryCode": "SFBA",
    "bankCode": "LI",
    "branchCode": "I22",
    "SWIFT Code": "SFBALI22",
    "Bank Name": "BANQUE HAVILLAND (LIECHTENSTEIN) AG",
    "Address": "AUSTRASSE 61",
    "City": "VADUZ",
    "Branch": "",
    "Postcode": "9490",
    "Country": "Liechtenstein",
    "Connection": "Active"
  },
  {
    "countryCode": "HYIB",
    "bankCode": "LI",
    "branchCode": "I22",
    "SWIFT Code": "HYIBLI22",
    "Bank Name": "BENDURA BANK AG",
    "Address": "SCHAANER STRASSE 27",
    "City": "GAMPRIN-BENDERN",
    "Branch": "",
    "Postcode": "9487",
    "Country": "Liechtenstein",
    "Connection": "Active"
  },
  {
    "countryCode": "EFGB",
    "bankCode": "LI",
    "branchCode": "I22",
    "SWIFT Code": "EFGBLI22",
    "Bank Name": "EFG BANK VON ERNST AG",
    "Address": "EGERTASTRASSE 10",
    "City": "VADUZ",
    "Branch": "",
    "Postcode": "9490",
    "Country": "Liechtenstein",
    "Connection": "Active"
  },
  {
    "countryCode": "FDSF",
    "bankCode": "LI",
    "branchCode": "ASM",
    "SWIFT Code": "FDSFLI22ASM",
    "Bank Name": "FDS FINANCIAL DATA SERVICES AG",
    "Address": "WUHRSTRASSE 6",
    "City": "VADUZ",
    "Branch": "",
    "Postcode": "9490",
    "Country": "Liechtenstein",
    "Connection": "Active"
  },
  {
    "countryCode": "FDSF",
    "bankCode": "LI",
    "branchCode": "I22",
    "SWIFT Code": "FDSFLI22",
    "Bank Name": "FDS FINANCIAL DATA SERVICES AG",
    "Address": "WUHRSTRASSE 6",
    "City": "VADUZ",
    "Branch": "",
    "Postcode": "9490",
    "Country": "Liechtenstein",
    "Connection": "Active"
  },
  {
    "countryCode": "FDSF",
    "bankCode": "LI",
    "branchCode": "LV1",
    "SWIFT Code": "FDSFLI22LV1",
    "Bank Name": "FDS FINANCIAL DATA SERVICES AG",
    "Address": "WUHRSTRASSE 6",
    "City": "VADUZ",
    "Branch": "LV1871",
    "Postcode": "9490",
    "Country": "Liechtenstein",
    "Connection": "Active"
  },
  {
    "countryCode": "HILT",
    "bankCode": "LI",
    "branchCode": "I22",
    "SWIFT Code": "HILTLI22",
    "Bank Name": "HILTI CORPORATION",
    "Address": "FELDKIRCHERSTRASSE 100",
    "City": "SCHAAN",
    "Branch": "",
    "Postcode": "9494",
    "Country": "Liechtenstein",
    "Connection": "Active"
  },
  {
    "countryCode": "SERB",
    "bankCode": "LI",
    "branchCode": "I22",
    "SWIFT Code": "SERBLI22",
    "Bank Name": "KAISER PARTNER PRIVATBANK AG",
    "Address": "HERRENGASSE 23",
    "City": "VADUZ",
    "Branch": "",
    "Postcode": "9490",
    "Country": "Liechtenstein",
    "Connection": "Active"
  },
  {
    "countryCode": "BLFL",
    "bankCode": "LI",
    "branchCode": "I2X",
    "SWIFT Code": "BLFLLI2X",
    "Bank Name": "LGT BANK AG",
    "Address": "HERRENGASSE 12",
    "City": "VADUZ",
    "Branch": "",
    "Postcode": "9490",
    "Country": "Liechtenstein",
    "Connection": "Active"
  },
  {
    "countryCode": "BLFL",
    "bankCode": "LI",
    "branchCode": "AGX",
    "SWIFT Code": "BLFLLI2XAGX",
    "Bank Name": "LGT BANK AG",
    "Address": "HERRENGASSE 12",
    "City": "VADUZ",
    "Branch": "AGX FUNDS",
    "Postcode": "9490",
    "Country": "Liechtenstein",
    "Connection": "Active"
  },
  {
    "countryCode": "BLFL",
    "bankCode": "LI",
    "branchCode": "224",
    "SWIFT Code": "BLFLLI2X224",
    "Bank Name": "LGT BANK AG",
    "Address": "HERRENGASSE 12",
    "City": "VADUZ",
    "Branch": "CONV SHAREKLASSE GBP",
    "Postcode": "9490",
    "Country": "Liechtenstein",
    "Connection": "Active"
  },
  {
    "countryCode": "BLFL",
    "bankCode": "LI",
    "branchCode": "225",
    "SWIFT Code": "BLFLLI2X225",
    "Bank Name": "LGT BANK AG",
    "Address": "HERRENGASSE 12",
    "City": "VADUZ",
    "Branch": "EQ NAM SHAREKLASSE EUR",
    "Postcode": "9490",
    "Country": "Liechtenstein",
    "Connection": "Active"
  },
  {
    "countryCode": "BLFL",
    "bankCode": "LI",
    "branchCode": "EXC",
    "SWIFT Code": "BLFLLI2XEXC",
    "Bank Name": "LGT BANK AG",
    "Address": "HERRENGASSE 12",
    "City": "VADUZ",
    "Branch": "EX CUSTODY",
    "Postcode": "9490",
    "Country": "Liechtenstein",
    "Connection": "Active"
  },
  {
    "countryCode": "BLFL",
    "bankCode": "LI",
    "branchCode": "275",
    "SWIFT Code": "BLFLLI2X275",
    "Bank Name": "LGT BANK AG",
    "Address": "HERRENGASSE 12",
    "City": "VADUZ",
    "Branch": "LGT SELECT CONVERTIBLE CHF C",
    "Postcode": "9490",
    "Country": "Liechtenstein",
    "Connection": "Active"
  },
  {
    "countryCode": "BLFL",
    "bankCode": "LI",
    "branchCode": "276",
    "SWIFT Code": "BLFLLI2X276",
    "Bank Name": "LGT BANK AG",
    "Address": "HERRENGASSE 12",
    "City": "VADUZ",
    "Branch": "LGT SELECT CONVERTIBLE CHF I1",
    "Postcode": "9490",
    "Country": "Liechtenstein",
    "Connection": "Active"
  },
  {},
  {
    "countryCode": "BLFL",
    "bankCode": "LI",
    "branchCode": "281",
    "SWIFT Code": "BLFLLI2X281",
    "Bank Name": "LGT BANK AG",
    "Address": "HERRENGASSE 12",
    "City": "VADUZ",
    "Branch": "LGT SELECT CONVERTIBLE EUR I1",
    "Postcode": "9490",
    "Country": "Liechtenstein",
    "Connection": "Active"
  },
  {
    "countryCode": "BLFL",
    "bankCode": "LI",
    "branchCode": "283",
    "SWIFT Code": "BLFLLI2X283",
    "Bank Name": "LGT BANK AG",
    "Address": "HERRENGASSE 12",
    "City": "VADUZ",
    "Branch": "LGT SELECT CONVERTIBLE GBP C",
    "Postcode": "9490",
    "Country": "Liechtenstein",
    "Connection": "Active"
  },
  {
    "countryCode": "BLFL",
    "bankCode": "LI",
    "branchCode": "314",
    "SWIFT Code": "BLFLLI2X314",
    "Bank Name": "LGT BANK AG",
    "Address": "HERRENGASSE 12",
    "City": "VADUZ",
    "Branch": "LGT SELECT CONVERTIBLE GBP I1",
    "Postcode": "9490",
    "Country": "Liechtenstein",
    "Connection": "Active"
  },
  {
    "countryCode": "BLFL",
    "bankCode": "LI",
    "branchCode": "315",
    "SWIFT Code": "BLFLLI2X315",
    "Bank Name": "LGT BANK AG",
    "Address": "HERRENGASSE 12",
    "City": "VADUZ",
    "Branch": "LGT SELECT EQUITY JAPAN USD C",
    "Postcode": "9490",
    "Country": "Liechtenstein",
    "Connection": "Active"
  },
  {
    "countryCode": "BLFL",
    "bankCode": "LI",
    "branchCode": "252",
    "SWIFT Code": "BLFLLI2X252",
    "Bank Name": "LGT BANK AG",
    "Address": "HERRENGASSE 12",
    "City": "VADUZ",
    "Branch": "LGT SLC EQ JP USD B",
    "Postcode": "9490",
    "Country": "Liechtenstein",
    "Connection": "Active"
  },
  {
    "countryCode": "BLFL",
    "bankCode": "LI",
    "branchCode": "253",
    "SWIFT Code": "BLFLLI2X253",
    "Bank Name": "LGT BANK AG",
    "Address": "HERRENGASSE 12",
    "City": "VADUZ",
    "Branch": "LGT SLC EQ JP USD I1",
    "Postcode": "9490",
    "Country": "Liechtenstein",
    "Connection": "Active"
  },
  {
    "countryCode": "BLFL",
    "bankCode": "LI",
    "branchCode": "496",
    "SWIFT Code": "BLFLLI2X496",
    "Bank Name": "LGT BANK AG",
    "Address": "HERRENGASSE 12",
    "City": "VADUZ",
    "Branch": "M-M CONV. SHAREKLASSE CHF",
    "Postcode": "9490",
    "Country": "Liechtenstein",
    "Connection": "Active"
  },
  {
    "countryCode": "BLFL",
    "bankCode": "LI",
    "branchCode": "495",
    "SWIFT Code": "BLFLLI2X495",
    "Bank Name": "LGT BANK AG",
    "Address": "HERRENGASSE 12",
    "City": "VADUZ",
    "Branch": "M-M CONV. SHAREKLASSE EUR",
    "Postcode": "9490",
    "Country": "Liechtenstein",
    "Connection": "Active"
  },
  {
    "countryCode": "LILA",
    "bankCode": "LI",
    "branchCode": "I2X",
    "SWIFT Code": "LILALI2X",
    "Bank Name": "LIECHTENSTEINISCHE LANDESBANK AKTIENGESELLSCHAFT",
    "Address": "STAEDTLE 44",
    "City": "VADUZ",
    "Branch": "",
    "Postcode": "9490",
    "Country": "Liechtenstein",
    "Connection": "Active"
  },
  {
    "countryCode": "NBAN",
    "bankCode": "LI",
    "branchCode": "I22",
    "SWIFT Code": "NBANLI22",
    "Bank Name": "NEUE BANK AG",
    "Address": "MARKTGASS 20",
    "City": "VADUZ",
    "Branch": "",
    "Postcode": "9490",
    "Country": "Liechtenstein",
    "Connection": "Active"
  },
  {
    "countryCode": "OICE",
    "bankCode": "LI",
    "branchCode": "I22",
    "SWIFT Code": "OICELI22",
    "Bank Name": "OLAYAN INVESTMENTS COMPANY ESTABLISHMENT",
    "Address": "HERRENGASSE 2",
    "City": "VADUZ",
    "Branch": "",
    "Postcode": "9490",
    "Country": "Liechtenstein",
    "Connection": "Active"
  },
  {
    "countryCode": "VOAG",
    "bankCode": "LI",
    "branchCode": "I22",
    "SWIFT Code": "VOAGLI22",
    "Bank Name": "SIGMA BANK AG",
    "Address": "FELDKIRCHER STRASSE 2",
    "City": "SCHAAN",
    "Branch": "VOLKSBANK AG",
    "Postcode": "9494",
    "Country": "Liechtenstein",
    "Connection": "Active"
  },
  {
    "countryCode": "BALP",
    "bankCode": "LI",
    "branchCode": "I22",
    "SWIFT Code": "BALPLI22",
    "Bank Name": "SORA BANK AG",
    "Address": "AUSTRASSE 59",
    "City": "VADUZ",
    "Branch": "",
    "Postcode": "9490",
    "Country": "Liechtenstein",
    "Connection": "Active"
  },
  {
    "countryCode": "SWLC",
    "bankCode": "LI",
    "branchCode": "I22",
    "SWIFT Code": "SWLCLI22",
    "Bank Name": "SWISS LIFE (LIECHTENSTEIN) AG",
    "Address": "INDUSTRIESTRASSE 56",
    "City": "RUGGELL",
    "Branch": "",
    "Postcode": "9491",
    "Country": "Liechtenstein",
    "Connection": "Active"
  },
  {
    "countryCode": "TANT",
    "bankCode": "LI",
    "branchCode": "I22",
    "SWIFT Code": "TANTLI22",
    "Bank Name": "TANTUM AG",
    "Address": "LANDSTRASSE 114",
    "City": "TRIESEN",
    "Branch": "",
    "Postcode": "9495",
    "Country": "Liechtenstein",
    "Connection": "Active"
  },
  {
    "countryCode": "VPBV",
    "bankCode": "LI",
    "branchCode": "I2X",
    "SWIFT Code": "VPBVLI2X",
    "Bank Name": "VP BANK AG",
    "Address": "AEULESTR 6",
    "City": "VADUZ",
    "Branch": "",
    "Postcode": "9490",
    "Country": "Liechtenstein",
    "Connection": "Active"
  },
  {
    "countryCode": "VPBV",
    "bankCode": "LI",
    "branchCode": "LIC",
    "SWIFT Code": "VPBVLI2XLIC",
    "Bank Name": "VP BANK AG",
    "Address": "AEULESTRASSE 6",
    "City": "VADUZ",
    "Branch": "BUSINESS UNIT LIECHTENSTEIN",
    "Postcode": "9490",
    "Country": "Liechtenstein",
    "Connection": "Active"
  }
]
module.exports = liechtenstein
