const lithuania = [
  {
    "countryCode": "UNEC",
    "bankCode": "LT",
    "branchCode": "T2V",
    "SWIFT Code": "UNECLT2V",
    "Bank Name": "NEOCARD UAB",
    "Address": "TOPOLIU ST 24A-2, NEMEZIS",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "13262",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "NIKU",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "NIKULT22",
    "Bank Name": "NIKULIPE",
    "Address": "KONSTITUCIJOS AV",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "09020",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "NODT",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "NODTLT22",
    "Bank Name": "NORDSTREET",
    "Address": "NAUGARDUKO STREET 19, BUILDING, OFFICE",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "03226",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "OKEO",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "OKEOLT22",
    "Bank Name": "OKEO PAYMENTS UAB",
    "Address": "GEDIMINO PR. 20",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "01013",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "OKOY",
    "bankCode": "LT",
    "branchCode": "T2X",
    "SWIFT Code": "OKOYLT2X",
    "Bank Name": "OP CORPORATE BANK PLC LITHUANIA BRANCH",
    "Address": "KONSTITUCIJOS PR. 29, FLOOR 4",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "08105",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "OPTU",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "OPTULT22",
    "Bank Name": "OPAL TRANSFER EU, UAB",
    "Address": "KONSTITUCIJOS PR. 21A",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "08130",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "OWEA",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "OWEALT22",
    "Bank Name": "ORION WEALTH, UAB",
    "Address": "A. TUMENO 4",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "01109",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "HAWK",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "HAWKLT22",
    "Bank Name": "PAYHAWK FINANCIAL SERVICES UAB",
    "Address": "LVOVO G. 25",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "LT-09320",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {},
  {},
  {
    "countryCode": "PMNT",
    "bankCode": "LT",
    "branchCode": "T2V",
    "SWIFT Code": "PMNTLT2V",
    "Bank Name": "PAYMONT, UAB",
    "Address": "GYNEJU G. 14-65",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "01109",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "PYYR",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "PYYRLT22",
    "Bank Name": "PAYRAY",
    "Address": "LVOVO 25, BURES 3, FLOOR 11",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "09320",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "EVIU",
    "bankCode": "LT",
    "branchCode": "T2V",
    "SWIFT Code": "EVIULT2V",
    "Bank Name": "PAYSERA LT UAB",
    "Address": "PILAITES PR. 16",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "04352",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "EVIU",
    "bankCode": "LT",
    "branchCode": "001",
    "SWIFT Code": "EVIULT2V001",
    "Bank Name": "PAYSERA LT UAB",
    "Address": "PILAITES PR. 16",
    "City": "VILNIUS",
    "Branch": "LBTIPS",
    "Postcode": "04352",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "PAUB",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "PAUBLT22",
    "Bank Name": "PAYSOLUT, UAB",
    "Address": "GYNEJU G. 4-333",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "01013",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "GLUA",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "GLUALT22",
    "Bank Name": "PAYSWIX, UAB",
    "Address": "RACIU 1",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "03001",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "PRFT",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "PRFTLT22",
    "Bank Name": "PROFITUS",
    "Address": "VASARIO 16-OSIOS G. 2",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "01106",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "REOL",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "REOLLT22",
    "Bank Name": "REGO.LT",
    "Address": "SAVANORIU PR. 1, HELIO CITY",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "03116",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "RVUA",
    "bankCode": "LT",
    "branchCode": "T2V",
    "SWIFT Code": "RVUALT2V",
    "Bank Name": "REVOLUT BANK UAB",
    "Address": "KONSTITUCIJOS AVE 21B",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "08104",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "RVUA",
    "bankCode": "LT",
    "branchCode": "TPS",
    "SWIFT Code": "RVUALT2VTPS",
    "Bank Name": "REVOLUT BANK UAB",
    "Address": "KONSTITUCIJOS AVE 21B",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "08104",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "REVO",
    "bankCode": "LT",
    "branchCode": "T23",
    "SWIFT Code": "REVOLT23",
    "Bank Name": "REVOLUT HOLDINGS EUROPE UAB",
    "Address": "KONSTITUCIJOS AVE. 21B, QUADRUM, FLOOR 4",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "08130",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "REVB",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "REVBLT22",
    "Bank Name": "REVOLUT SECURITIES UAB",
    "Address": "KONSTITUCIJOS PR. 21B",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "08130",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "RILA",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "RILALT22",
    "Bank Name": "RIA LITHUANIA UAB",
    "Address": "UPES G. 23",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "08128",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {},
  {
    "countryCode": "SESF",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "SESFLT22",
    "Bank Name": "SEVEN SEAS FINANCE",
    "Address": "LAISVES AVE. 60",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "05120",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "CBSB",
    "bankCode": "LT",
    "branchCode": "T26",
    "SWIFT Code": "CBSBLT26",
    "Bank Name": "SIAULIU BANKAS AB",
    "Address": "TILZES STREET 149",
    "City": "SIAULIAI",
    "Branch": "",
    "Postcode": "76348",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "CBSB",
    "bankCode": "LT",
    "branchCode": "DCA",
    "SWIFT Code": "CBSBLT26DCA",
    "Bank Name": "SIAULIU BANKAS AB",
    "Address": "TILZES STREET 149",
    "City": "SIAULIAI",
    "Branch": "REACHABLE TIPS DCA",
    "Postcode": "76348",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "SUPU",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "SUPULT22",
    "Bank Name": "SUMUP EU PAYMENTS, UAB",
    "Address": "UPES GATVE 23",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "09020",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "HABA",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "HABALT22",
    "Bank Name": "SWEDBANK AB",
    "Address": "KONSTITUCIJOS 20A",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "03502",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "HABA",
    "bankCode": "LT",
    "branchCode": "TIP",
    "SWIFT Code": "HABALT22TIP",
    "Bank Name": "SWEDBANK AB",
    "Address": "KONSTITUCIJOS 20A",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "03502",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "SWLU",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "SWLULT22",
    "Bank Name": "SWEDBANK LIZINGAS, UAB",
    "Address": "KONSTITUCIJOS PR. 20A",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "09321",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "TEUA",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "TEUALT22",
    "Bank Name": "TESLAPAY UAB",
    "Address": "DARIAUS IR GIRENO G. 42A, WINGS BUSINESS CENTER, FLOOR 5",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "02189",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "TRFB",
    "bankCode": "LT",
    "branchCode": "T2V",
    "SWIFT Code": "TRFBLT2V",
    "Bank Name": "TRUSTCOM FINANCIAL UAB",
    "Address": "PAMENKALNIO GATVE 36-2A",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "01114",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "EXUA",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "EXUALT22",
    "Bank Name": "TT EXPRESS UAB",
    "Address": "OZESKIENES G 15",
    "City": "KAUNAS",
    "Branch": "",
    "Postcode": "44254",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "UFPO",
    "bankCode": "LT",
    "branchCode": "T23",
    "SWIFT Code": "UFPOLT23",
    "Bank Name": "UAB 'FINANSINES PASLAUGOS' CONTIS",
    "Address": "MENULIO STR 11-101",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "LT-04326",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "UAFM",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "UAFMLT22",
    "Bank Name": "UAB 'FINOMARK'",
    "Address": "ULONU 5",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "08240",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "FNRK",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "FNRKLT22",
    "Bank Name": "UAB 'FINORA KREDITAS'",
    "Address": "ZALGIRIO 88",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "09303",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "IBNN",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "IBNNLT22",
    "Bank Name": "UAB 'IBAN ONLINE'",
    "Address": "DIDZIOJI G 18",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "01128",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "UIPU",
    "bankCode": "LT",
    "branchCode": "T2V",
    "SWIFT Code": "UIPULT2V",
    "Bank Name": "UAB 'INTERNATIONAL PAYMENT UNION'",
    "Address": "BARBOROS RADVILAITES STRT. 1",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "01124",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "NSPT",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "NSPTLT22",
    "Bank Name": "UAB 'NEOSPORTAS'",
    "Address": "ARCHITEKTU 56-101",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "04111",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "UAPU",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "UAPULT22",
    "Bank Name": "UAB 'PAYTEND EUROPE'",
    "Address": "PAMENKALNIO STR 25-1",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "01113",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "PAYH",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "PAYHLT22",
    "Bank Name": "UAB 'PAYWHO'",
    "Address": "A. GOSTAUTO G 8-108, FLOOR 1",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "01108",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "UASV",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "UASVLT22",
    "Bank Name": "UAB 'SANDO INVESTMENT'",
    "Address": "EISISKIU SODU 5-OJI STR",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "02194",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "UAAF",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "UAAFLT22",
    "Bank Name": "UAB ALTERNATYVUS FINANSAVIMAS",
    "Address": "SALTONISKIU 12-2",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "08105",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "UABK",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "UABKLT22",
    "Bank Name": "UAB BALTIJOS KONCERNAS",
    "Address": "MINDAUGO 4-1",
    "City": "MAZEIKIAI",
    "Branch": "",
    "Postcode": "89215",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "UABE",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "UABELT22",
    "Bank Name": "UAB BEBAWA",
    "Address": "MESINIU STR 5",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "01135",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "UABI",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "UABILT22",
    "Bank Name": "UAB BEST FINANCE",
    "Address": "DYSNOS 2",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "01135",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "UABL",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "UABLLT22",
    "Bank Name": "UAB BLENDER LITHUANIA F1",
    "Address": "J.BASANAVICIAUS 26, B NORDIC 26, FLOOR 4",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "03224",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "UABL",
    "bankCode": "LT",
    "branchCode": "T23",
    "SWIFT Code": "UABLLT23",
    "Bank Name": "UAB BLENDER LITHUANIA F2",
    "Address": "JONO BASANAVICIAUS 26, FLOOR 4",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "LT-03224",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {},
  {
    "countryCode": "UBBF",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "UBBFLT22",
    "Bank Name": "UAB BOURGEOIS BOHEME FINTECH",
    "Address": "JONO BASANAVICIAUS G, B NORDIC 26, FLOOR 5",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "03224",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "UACA",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "UACALT22",
    "Bank Name": "UAB CRAFTSOFT",
    "Address": "V. NAGEVICIAUS GATVE 3",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "08009",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "UACD",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "UACDLT22",
    "Bank Name": "UAB CREDIT DAY",
    "Address": "KESTUTIS STREET 370",
    "City": "KAUNAS",
    "Branch": "",
    "Postcode": "46352",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "UACW",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "UACWLT22",
    "Bank Name": "UAB CROWDPEAR",
    "Address": "KAREIVIU ST 11B, KAREIVIUS, FLOOR 2",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "09109",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "CUEU",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "CUEULT22",
    "Bank Name": "UAB CURVE EUROPE",
    "Address": "JOGAILOS G. 9",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "01116",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "UDBS",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "UDBSLT22",
    "Bank Name": "UAB DERISK BUSINESS SOLUTIONS",
    "Address": "KALVARIJU G. 137E",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "08221",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "UDVP",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "UDVPLT22",
    "Bank Name": "UAB DIGITAL VIRGO PAYMENT",
    "Address": "VYTENIO 4",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "03113",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "UDRU",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "UDRULT22",
    "Bank Name": "UAB DRUSVALAS",
    "Address": "NAUGARDUKO STR. 19",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "03226",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "UAEV",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "UAEVLT22",
    "Bank Name": "UAB EDS INVEST 4",
    "Address": "ANTANO TUMENO 4",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "01109",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "UAEN",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "UAENLT22",
    "Bank Name": "UAB EDS INVEST 5",
    "Address": "ANTANO TUMENO 4",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "01109",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "UFBV",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "UFBVLT22",
    "Bank Name": "UAB FINANSU BITE VERSLUI",
    "Address": "SV. IGNOTO ST. 5",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "15026",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "UAFB",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "UAFBLT22",
    "Bank Name": "UAB FINBRO",
    "Address": "JURGIO BALRUSAICIO STR. 9",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "06145",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "UFOS",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "UFOSLT22",
    "Bank Name": "UAB FMI ORION SECURITIES",
    "Address": "A. TUMENO 4, VILNIAUS VARTAI, FLOOR 7",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "01013",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "UAHK",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "UAHKLT22",
    "Bank Name": "UAB HIPOTEKINIAI KREDITAI",
    "Address": "V. PUTVINSKIO G. 62, FLOOR 1",
    "City": "KAUNAS",
    "Branch": "",
    "Postcode": "44243",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "UAAA",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "UAAALT22",
    "Bank Name": "UAB HOKODO",
    "Address": "GYNEJU ST. 4",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "01109",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "UAIR",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "UAIRLT22",
    "Bank Name": "UAB INRENTO",
    "Address": "RAMYBES G. 4-70",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "02103",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "UAKP",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "UAKPLT22",
    "Bank Name": "UAB KREDITO PARTNERIS",
    "Address": "NAGEVICIAUS",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "08009",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "UAKR",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "UAKRLT22",
    "Bank Name": "UAB KREDUS",
    "Address": "SAVANORIU PR. 11A-22",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "03001",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "UALT",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "UALTLT22",
    "Bank Name": "UAB LOCK TRUST",
    "Address": "J. BASANAVICIAUS STR. 26",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "03224",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "MDBA",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "MDBALT22",
    "Bank Name": "UAB MEDICINOS BANKAS",
    "Address": "PAMENKALNIO 40",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "01114",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "MDBA",
    "bankCode": "LT",
    "branchCode": "DCA",
    "SWIFT Code": "MDBALT22DCA",
    "Bank Name": "UAB MEDICINOS BANKAS",
    "Address": "PAMENKALNIO 40",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "01114",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "UAMT",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "UAMTLT22",
    "Bank Name": "UAB MONSOON CAPITAL",
    "Address": "A.TUMENO 4",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "01109",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "UANI",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "UANILT22",
    "Bank Name": "UAB NANDI FINANCE",
    "Address": "ANTANO TUMENO G. 4, FLOOR 7",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "01109",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "UANO",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "UANOLT22",
    "Bank Name": "UAB NOVAPAY",
    "Address": "LVOVO G 105A",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "08104",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "UAAY",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "UAAYLT22",
    "Bank Name": "UAB NS PAY",
    "Address": "A. DOMASEVICIAUS G. 9",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "LT-01400",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "USPE",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "USPELT22",
    "Bank Name": "UAB NUVEI",
    "Address": "LVIVO STR 37, L37 OFFICE BUILDING, FLOOR 8",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "09306",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "USPE",
    "bankCode": "LT",
    "branchCode": "T2V",
    "SWIFT Code": "USPELT2V",
    "Bank Name": "UAB NUVEI",
    "Address": "LVIVO STR 37, L37 OFFICE BUILDING, FLOOR 8",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "09306",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "UAOS",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "UAOSLT22",
    "Bank Name": "UAB OPAY SOLUTIONS",
    "Address": "M. K. PACO ST 4",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "10309",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "UAPA",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "UAPALT22",
    "Bank Name": "UAB PAYRNET",
    "Address": "VILNIUS GIRULIU, FLOOR G20",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "01013",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "UAPS",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "UAPSLT22",
    "Bank Name": "UAB PERLOSA",
    "Address": "JOGAILOS STR 4",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "01116",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "UAPE",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "UAPELT22",
    "Bank Name": "UAB PERVESK",
    "Address": "GEDIMINO AV. 5, FLOOR 3",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "LT-01103",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "UAPP",
    "bankCode": "LT",
    "branchCode": "T2V",
    "SWIFT Code": "UAPPLT2V",
    "Bank Name": "UAB PHOENIX PAYMENTS",
    "Address": "SVITRIGAILOS STR 11M",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "03228",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "UPFI",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "UPFILT22",
    "Bank Name": "UAB PRIMERO FINANCE",
    "Address": "LAISVES PR 10A, FLOOR 2",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "04125",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "UAEL",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "UAELLT22",
    "Bank Name": "UAB SEILI",
    "Address": "PAIKISKIU STREET 16",
    "City": "MARIJAMPOLE",
    "Branch": "",
    "Postcode": "68001",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "UASI",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "UASILT22",
    "Bank Name": "UAB SILVERGATE LT",
    "Address": "J BASANAVICIAUS G 15",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "03108",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "USDF",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "USDFLT22",
    "Bank Name": "UAB SME BANK",
    "Address": "ANTANO TUMENO G. 4-15, FLOOR 18",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "01109",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "UASA",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "UASALT22",
    "Bank Name": "UAB SME LEASING",
    "Address": "ANTANO TUMENO",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "01135",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "UASD",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "UASDLT22",
    "Bank Name": "UAB SPEEDYTELLER",
    "Address": "MESINU G. 5",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "01013",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "USTI",
    "bankCode": "LT",
    "branchCode": "T2V",
    "SWIFT Code": "USTILT2V",
    "Bank Name": "UAB STANHOPE FINANCIAL",
    "Address": "UPES G. 23",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "08128",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "UATU",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "UATULT22",
    "Bank Name": "UAB TRAVEL UNION",
    "Address": "VERKIU STR 31B-2",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "09108",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "UVIP",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "UVIPLT22",
    "Bank Name": "UAB VIESUJU INVESTICIJU PLETROS AGENTURA",
    "Address": "LUKISKIU 2",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "01013",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "UAWA",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "UAWALT22",
    "Bank Name": "UAB WALLETTO",
    "Address": "ZALGIRIO STR 92-805",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "09303",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "UGAF",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "UGAFLT22",
    "Bank Name": "UAB ZEMES UKIO PASKOLU GARANTIJU FONDAS",
    "Address": "BLINDZIU 17",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "08111",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "BZEN",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "BZENLT22",
    "Bank Name": "UAB ZEN.COM",
    "Address": "MESINIU 5",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "01133",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "UAZI",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "UAZILT22",
    "Bank Name": "UAB ZUPER LITHUANIA",
    "Address": "VILNIAUS G. 28, FLOOR 1",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "01402",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "PANX",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "PANXLT22",
    "Bank Name": "UNIFIEDPOST PAYMENTS FILIALAS",
    "Address": "UZUBALIU K, AVIZIENIU SEN",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "14180",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "UABN",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "UABNLT22",
    "Bank Name": "UZDAROJI AKCINE BENDROVE- INVESTICIJU IR VERSLO GARANTIJOS",
    "Address": "KONSTITUCIJOS PROSPEKTAS 7, FLOOR 16",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "09020",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "VIVG",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "VIVGLT22",
    "Bank Name": "VALSTYBES INVESTICIJU VALDYMO AGENT",
    "Address": "JOGAILOS",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "01116",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "VEPA",
    "bankCode": "LT",
    "branchCode": "T2X",
    "SWIFT Code": "VEPALT2X",
    "Bank Name": "VERIFIED PAYMENTS JSC",
    "Address": "T. KOSCIUSKOS ST. 24",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "01100",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "VFUA",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "VFUALT22",
    "Bank Name": "VFS LT, UAB",
    "Address": "MINSKO PL 9",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "02121",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "VIPU",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "VIPULT22",
    "Bank Name": "VIA PAYMENTS UAB",
    "Address": "KONSTITUCIJOS PR. 7",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "09308",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "VTEK",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "VTEKLT22",
    "Bank Name": "VYRIAUSIOJI TARNYBINES ETIKOS KOMIS",
    "Address": "VILNIAUS 27",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "01402",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "WTCA",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "WTCALT22",
    "Bank Name": "W1TTY CAPITAL UAB",
    "Address": "JOGAILOS G. 9",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "01116",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "WFGU",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "WFGULT22",
    "Bank Name": "WEGENERAL FINANCIAL GROUP UAB",
    "Address": "GEDIMINO AVE. 44A-101",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "01013",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "WIUA",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "WIUALT22",
    "Bank Name": "WITTIX UAB",
    "Address": "LVOVO 25 VERSLO BURES BUSINESS, CENTRE, FLOOR 6",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "09320",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "WIGU",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "WIGULT22",
    "Bank Name": "WITTY GLOBAL UAB",
    "Address": "DIDZIOJI G. 303, 304, 305",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "01128",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "XPUB",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "XPUBLT22",
    "Bank Name": "XPATE UAB",
    "Address": "SVITRIGAILOS G. 11A",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "03111",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "PAUA",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "PAUALT22",
    "Bank Name": "AB 'PAYSTRAX'",
    "Address": "VILNIAUS 31",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "01402",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "FJOR",
    "bankCode": "LT",
    "branchCode": "T23",
    "SWIFT Code": "FJORLT23",
    "Bank Name": "AB FJORD BANK",
    "Address": "RINKTINES G. 5",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "KUSR",
    "bankCode": "LT",
    "branchCode": "T24",
    "SWIFT Code": "KUSRLT24",
    "Bank Name": "AB MANO BANKAS",
    "Address": "S. MONIUSKOS 27",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "08115",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "KUSR",
    "bankCode": "LT",
    "branchCode": "TIP",
    "SWIFT Code": "KUSRLT24TIP",
    "Bank Name": "AB MANO BANKAS",
    "Address": "S. MONIUSKOS 27",
    "City": "VILNIUS",
    "Branch": "BIC FOR TIPS",
    "Postcode": "LT-08115",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "CBVI",
    "bankCode": "LT",
    "branchCode": "T2X",
    "SWIFT Code": "CBVILT2X",
    "Bank Name": "AB SEB BANKAS",
    "Address": "KONSTITUCIJOS AVE. 24",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "08105",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "CBVI",
    "bankCode": "LT",
    "branchCode": "TPS",
    "SWIFT Code": "CBVILT2XTPS",
    "Bank Name": "AB SEB BANKAS",
    "Address": "KONSTITUCIJOS AVE. 24",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "08105",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "AMPU",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "AMPULT22",
    "Bank Name": "AMBR PAYMENTS UAB",
    "Address": "KAUNO G. KAUNO G. 16-305",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "LT-03212",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "ARUA",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "ARUALT22",
    "Bank Name": "ARCAPAY UAB",
    "Address": "KONSTITUCIJOS PR. 21B",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "08130",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "INDU",
    "bankCode": "LT",
    "branchCode": "T2X",
    "SWIFT Code": "INDULT2X",
    "Bank Name": "AS CITADELE BANKA LIETUVOS FILIALAS",
    "Address": "UPES STR 21-1",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "08128",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "IBFL",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "IBFLLT22",
    "Bank Name": "AS INBANK FILIALAS",
    "Address": "KAREIVIU 11B, BUSINESS OFFICE, FLOOR 11",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "09109",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "AWXL",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "AWXLLT22",
    "Bank Name": "AWX LITHUANIA UAB",
    "Address": "KONSTITUCIJOS PR 21B",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "08130",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "BNUA",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "BNUALT22",
    "Bank Name": "BANXS UAB",
    "Address": "LVOVO STR 105A",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "08104",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "BEMU",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "BEMULT22",
    "Bank Name": "BEM EUROPE UAB",
    "Address": "MESINIU G. 5",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "01133",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "CBNU",
    "bankCode": "LT",
    "branchCode": "T2V",
    "SWIFT Code": "CBNULT2V",
    "Bank Name": "CBI MONEY UAB",
    "Address": "SENASIS UKMERGES KL.4",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "14302",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "CLUA",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "CLUALT22",
    "Bank Name": "CLEARSHIFT UAB",
    "Address": "UPES STR. 23",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "08128",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "CRUB",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "CRUBLT22",
    "Bank Name": "CRIUS LT, UAB",
    "Address": "UPES G. 23",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "08128",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "DMVO",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "DMVOLT22",
    "Bank Name": "DEMIVOLT",
    "Address": "JOGAILOS ST. 4",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "01116",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "DIUA",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "DIUALT22",
    "Bank Name": "DIPOCKET, UAB",
    "Address": "LVIVO 25-104, GREEN HALL 2, FLOOR 5",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "09320",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "EPSU",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "EPSULT22",
    "Bank Name": "EARTHPORT PAYMENT SERVICES UAB",
    "Address": "LVOVO STR. 25-104",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "09320",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "EDIN",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "EDINLT22",
    "Bank Name": "EDS INVEST 2",
    "Address": "A. TUMENO STR. 4",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "01135",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "EDIV",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "EDIVLT22",
    "Bank Name": "EDS INVEST 3",
    "Address": "A. TUMENO STR. 4",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "01135",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "EPUA",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "EPUALT22",
    "Bank Name": "EPAYBLOCK UAB",
    "Address": "UPES GATVE 23",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "09020",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "ESUA",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "ESUALT22",
    "Bank Name": "ESTO UAB",
    "Address": "VERKIU ST. 31B-2",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "09001",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "EUEB",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "EUEBLT22",
    "Bank Name": "EUROPEAN MERCHANT BANK UAB",
    "Address": "GEDIMINO PR. 35",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "01109",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "BAXX",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "BAXXLT22",
    "Bank Name": "FINCI, UAB",
    "Address": "MENULIO G. 11-101",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "04326",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "FIUB",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "FIUBLT22",
    "Bank Name": "FINHERO, UAB",
    "Address": "K. DONELAICIO G. 60",
    "City": "KAUNAS",
    "Branch": "",
    "Postcode": "44248",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "FLUA",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "FLUALT22",
    "Bank Name": "FLORIOFINANCE UAB",
    "Address": "KONSTITUCIJOS AVE. 21B",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "08130",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "FUNA",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "FUNALT22",
    "Bank Name": "FUNDVEST UAB",
    "Address": "KONSTITUCIJOS PR 7",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "09307",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "GUPU",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "GUPULT22",
    "Bank Name": "GURU PAY UAB",
    "Address": "JONO BASANAVICIAUS STR 24",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "03224",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "IBIU",
    "bankCode": "LT",
    "branchCode": "T2X",
    "SWIFT Code": "IBIULT2X",
    "Bank Name": "IBS LITHUANIA",
    "Address": "L. STUOKOS-GUCEVICIAUS 7",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "01122",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "MAKR",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "MAKRLT22",
    "Bank Name": "INHOUSE LOAN",
    "Address": "OZO G. 12A, TECHNOPOLIS, FLOOR 7A",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "08200",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "KUFU",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "KUFULT22",
    "Bank Name": "KUAN FINANCIAL, UAB",
    "Address": "GEDIMINO PR. 44A, GEDIMINO LIVESQUARE",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "01400",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "LIAB",
    "bankCode": "LT",
    "branchCode": "PAY",
    "SWIFT Code": "LIABLT2XPAY",
    "Bank Name": "LIETUVOS BANKAS (BANK OF LITHUANIA)",
    "Address": "GEDIMINO 6",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "01103",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "LIAB",
    "bankCode": "LT",
    "branchCode": "T2X",
    "SWIFT Code": "LIABLT2X",
    "Bank Name": "LIETUVOS BANKAS (BANK OF LITHUANIA)",
    "Address": "GEDIMINO 6",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "01103",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "LIAB",
    "bankCode": "LT",
    "branchCode": "ECM",
    "SWIFT Code": "LIABLT2XECM",
    "Bank Name": "LIETUVOS BANKAS (BANK OF LITHUANIA)",
    "Address": "GEDIMINO 6",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "01103",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "LIAB",
    "bankCode": "LT",
    "branchCode": "DCA",
    "SWIFT Code": "LIABLT2XDCA",
    "Bank Name": "LIETUVOS BANKAS (BANK OF LITHUANIA)",
    "Address": "GEDIMINO 6",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "01103",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "LIAB",
    "bankCode": "LT",
    "branchCode": "MMS",
    "SWIFT Code": "LIABLT2XMMS",
    "Bank Name": "LIETUVOS BANKAS (BANK OF LITHUANIA)",
    "Address": "",
    "City": "VILNIUS",
    "Branch": "BANKING SERVICE",
    "Postcode": "",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "LIAB",
    "bankCode": "LT",
    "branchCode": "SNO",
    "SWIFT Code": "LIABLT2XSNO",
    "Bank Name": "LIETUVOS BANKAS (BANK OF LITHUANIA)",
    "Address": "",
    "City": "VILNIUS",
    "Branch": "INFORMATION SERVICE",
    "Postcode": "",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "LIAB",
    "bankCode": "LT",
    "branchCode": "MSD",
    "SWIFT Code": "LIABLT2XMSD",
    "Bank Name": "LIETUVOS BANKAS (BANK OF LITHUANIA)",
    "Address": "ZIRMUNU G. 151",
    "City": "VILNIUS",
    "Branch": "PAYMENT SYSTEMS DEPARTMENT",
    "Postcode": "09128",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "LIAB",
    "bankCode": "LT",
    "branchCode": "CON",
    "SWIFT Code": "LIABLT2XCON",
    "Bank Name": "LIETUVOS BANKAS (BANK OF LITHUANIA)",
    "Address": "",
    "City": "VILNIUS",
    "Branch": "TARGET2 CONTINGENCY",
    "Postcode": "",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "LCKU",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "LCKULT22",
    "Bank Name": "LITHUANIAN CENTRAL CREDIT UNION",
    "Address": "SAVANORIAI AVENUE 363B-201",
    "City": "KAUNAS",
    "Branch": "",
    "Postcode": "51480",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "WBNK",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "WBNKLT22",
    "Bank Name": "LTL KREDITO UNIJA",
    "Address": "SPORTO G. 18",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "09238",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "AGBL",
    "bankCode": "LT",
    "branchCode": "T2X",
    "SWIFT Code": "AGBLLT2X",
    "Bank Name": "LUMINOR BANK AS LITHUANIAN BRANCH",
    "Address": "KONSTITUCIJOS AVE. 21",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "03601",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "AGBL",
    "bankCode": "LT",
    "branchCode": "TGT",
    "SWIFT Code": "AGBLLT2XTGT",
    "Bank Name": "LUMINOR BANK AS LITHUANIAN BRANCH",
    "Address": "KONSTITUCIJOS AVE. 21A",
    "City": "VILNIUS",
    "Branch": "FOR MINIMUM RESERVES AT CENTRAL BANK",
    "Postcode": "03601",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "LIPY",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "LIPYLT22",
    "Bank Name": "LUX INTERNATIONAL PAYMENT SYSTEM UAB",
    "Address": "JOGAILOS 4",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "01116",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "MAAB",
    "bankCode": "LT",
    "branchCode": "T2V",
    "SWIFT Code": "MAABLT2V",
    "Bank Name": "MAJESTIC FINANCIAL UAB",
    "Address": "MESINIU G. 5",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "01133",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "MFRL",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "MFRLLT22",
    "Bank Name": "MINISTRY OF FINANCE OF THE REPUBLIC OF LITHUANIA",
    "Address": "LUKISKIU STR 2",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "01512",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "CSDL",
    "bankCode": "LT",
    "branchCode": "T22",
    "SWIFT Code": "CSDLLT22",
    "Bank Name": "NASDAQ CSD SE LITHUANIAN BRANCH",
    "Address": "KONSITUCIJOS AVENUE 29",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "08105",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "CSDL",
    "bankCode": "LT",
    "branchCode": "577",
    "SWIFT Code": "CSDLLT22577",
    "Bank Name": "NASDAQ CSD SE LITHUANIAN BRANCH",
    "Address": "",
    "City": "VILNIUS",
    "Branch": "",
    "Postcode": "",
    "Country": "Lithuania",
    "Connection": "Active"
  },
  {
    "countryCode": "CSDL",
    "bankCode": "LT",
    "branchCode": "RTG",
    "SWIFT Code": "CSDLLT22RTG",
    "Bank Name": "NASDAQ CSD SE LITHUANIAN BRANCH",
    "Address": "",
    "City": "VILNIUS",
    "Branch": "PM",
    "Postcode": "",
    "Country": "Lithuania",
    "Connection": "Active"
  }
]
module.exports = lithuania
