const macao = [
  {
    "countryCode": "ABOC",
    "bankCode": "MO",
    "branchCode": "OMM",
    "SWIFT Code": "ABOCMOMM",
    "Bank Name": "AGRICULTURAL BANK OF CHINA LIMITED MACAO BRANCH",
    "Address": "AVENIDA DOUTOR MARIO SOARES 300-322",
    "City": "MACAU",
    "Branch": "",
    "Postcode": "999078",
    "Country": "Macao",
    "Connection": "Active"
  },
  {
    "countryCode": "CIGG",
    "bankCode": "MO",
    "branchCode": "OMM",
    "SWIFT Code": "CIGGMOMM",
    "Bank Name": "ANT BANK (MACAO) LIMITED",
    "Address": "FINANCE AND IT CENTRE OF MACAU,, FLOOR 22",
    "City": "MACAU",
    "Branch": "",
    "Postcode": "999078",
    "Country": "Macao",
    "Connection": "Active"
  },
  {
    "countryCode": "MFAM",
    "bankCode": "MO",
    "branchCode": "OMS",
    "SWIFT Code": "MFAMMOMS",
    "Bank Name": "AUTORIDADE MONETARIA DE MACAU",
    "Address": "CALCADA DO GAIO 24-26",
    "City": "MACAU",
    "Branch": "",
    "Postcode": "",
    "Country": "Macao",
    "Connection": "Active"
  },
  {
    "countryCode": "MFAM",
    "bankCode": "MO",
    "branchCode": "OMU",
    "SWIFT Code": "MFAMMOMU",
    "Bank Name": "AUTORIDADE MONETARIA DE MACAU",
    "Address": "CALCADA DO GAIO, 24-26",
    "City": "MACAU",
    "Branch": "",
    "Postcode": "",
    "Country": "Macao",
    "Connection": "Active"
  },
  {
    "countryCode": "MFAM",
    "bankCode": "MO",
    "branchCode": "OMX",
    "SWIFT Code": "MFAMMOMX",
    "Bank Name": "AUTORIDADE MONETARIA DE MACAU",
    "Address": "CALCADA DO GAIO 24-26",
    "City": "MACAU",
    "Branch": "",
    "Postcode": "999078",
    "Country": "Macao",
    "Connection": "Active"
  },
  {
    "countryCode": "CMAC",
    "bankCode": "MO",
    "branchCode": "OMX",
    "SWIFT Code": "CMACMOMX",
    "Bank Name": "BANCO COMERCIAL DE MACAU, S.A.",
    "Address": "AVENIDA DA PRAIA GRANDE 572",
    "City": "MACAU",
    "Branch": "",
    "Postcode": "999078",
    "Country": "Macao",
    "Connection": "Active"
  },
  {
    "countryCode": "BCOM",
    "bankCode": "MO",
    "branchCode": "OMX",
    "SWIFT Code": "BCOMMOMX",
    "Bank Name": "BANCO COMERCIAL PORTUGUES",
    "Address": "AV COMERCIAL DE MACAU Q 5- LT A, FIT CENTER, FLOOR 19 G-I",
    "City": "MACAU",
    "Branch": "",
    "Postcode": "999078",
    "Country": "Macao",
    "Connection": "Active"
  },
  {
    "countryCode": "DABG",
    "bankCode": "MO",
    "branchCode": "OMX",
    "SWIFT Code": "DABGMOMX",
    "Bank Name": "BANCO DELTA ASIA S.A.",
    "Address": "LARGO DE ST.AGOSTINHO",
    "City": "MACAU",
    "Branch": "",
    "Postcode": "999078",
    "Country": "Macao",
    "Connection": "Active"
  },
  {},
  {
    "countryCode": "BESC",
    "bankCode": "MO",
    "branchCode": "OMX",
    "SWIFT Code": "BESCMOMX",
    "Bank Name": "BANCO WELL LINK, S.A.",
    "Address": "AVENIDA DOUTOR MARIO SOARES 320, FINANCE AND IT CENTER OF MACAO",
    "City": "MACAU",
    "Branch": "",
    "Postcode": "999078",
    "Country": "Macao",
    "Connection": "Active"
  },
  {
    "countryCode": "BKCH",
    "bankCode": "MO",
    "branchCode": "OMA",
    "SWIFT Code": "BKCHMOMA",
    "Bank Name": "BANK OF CHINA (MACAU) LIMITED",
    "Address": "AVENIDA DR. MARIO SOARES 323, EDIFICIO DO BANCO DA CHINA",
    "City": "MACAU",
    "Branch": "",
    "Postcode": "999078",
    "Country": "Macao",
    "Connection": "Active"
  },
  {
    "countryCode": "BKCH",
    "bankCode": "MO",
    "branchCode": "OMX",
    "SWIFT Code": "BKCHMOMX",
    "Bank Name": "BANK OF CHINA, MACAU BRANCH",
    "Address": "AVENIDA DOUTOR MARIO SOARES, BANK OF CHINA BUILDING",
    "City": "MACAU",
    "Branch": "",
    "Postcode": "999078",
    "Country": "Macao",
    "Connection": "Active"
  },
  {
    "countryCode": "BKCH",
    "bankCode": "MO",
    "branchCode": "CLR",
    "SWIFT Code": "BKCHMOMXCLR",
    "Bank Name": "BANK OF CHINA, MACAU BRANCH",
    "Address": "AVENIDA DOUTOR MARIO SOARES, BANK OF CHINA BUILDING",
    "City": "MACAU",
    "Branch": "BANK OF CHINA LIMITED MACAU BRANCH(MO HKD CLEARING CENTRE",
    "Postcode": "999078",
    "Country": "Macao",
    "Connection": "Active"
  },
  {
    "countryCode": "BKCH",
    "bankCode": "MO",
    "branchCode": "CUS",
    "SWIFT Code": "BKCHMOMXCUS",
    "Bank Name": "BANK OF CHINA, MACAU BRANCH",
    "Address": "AVENIDA DOUTOR MARIO SOARES, BANK OF CHINA BUILDING",
    "City": "MACAU",
    "Branch": "CUSTODY-MACAU",
    "Postcode": "999078",
    "Country": "Macao",
    "Connection": "Active"
  },
  {
    "countryCode": "BKCH",
    "bankCode": "MO",
    "branchCode": "868",
    "SWIFT Code": "BKCHMOMX868",
    "Bank Name": "BANK OF CHINA, MACAU BRANCH",
    "Address": "",
    "City": "MACAU",
    "Branch": "RENMINBI CLEARING CENTRE",
    "Postcode": "999078",
    "Country": "Macao",
    "Connection": "Active"
  },
  {
    "countryCode": "COMM",
    "bankCode": "MO",
    "branchCode": "OMX",
    "SWIFT Code": "COMMMOMX",
    "Bank Name": "BANK OF COMMUNICATIONS CO.,LTD. MACAU BRANCH",
    "Address": "AVENIDA COMERCIAL DE MACAU 251A, AIA TOWER, FLOOR 9, ROOM 1603-1608",
    "City": "MACAU",
    "Branch": "",
    "Postcode": "999078",
    "Country": "Macao",
    "Connection": "Active"
  },
  {
    "countryCode": "SINO",
    "bankCode": "MO",
    "branchCode": "OMX",
    "SWIFT Code": "SINOMOMX",
    "Bank Name": "BANK SINOPAC (FORMERLY INT'L BANK OF TAIPEI)",
    "Address": "AVENIDA DOUTOR MARIO SOARES, FINANCE AND IT CENTER OF MACAO,, FLOOR 9",
    "City": "MACAU",
    "Branch": "",
    "Postcode": "999078",
    "Country": "Macao",
    "Connection": "Active"
  },
  {
    "countryCode": "CIEP",
    "bankCode": "MO",
    "branchCode": "OMX",
    "SWIFT Code": "CIEPMOMX",
    "Bank Name": "CAIXA ECONOMICA POSTAL",
    "Address": "RUA DA SE S/N",
    "City": "MACAU",
    "Branch": "",
    "Postcode": "999078",
    "Country": "Macao",
    "Connection": "Active"
  },
  {
    "countryCode": "KWHK",
    "bankCode": "MO",
    "branchCode": "OMX",
    "SWIFT Code": "KWHKMOMX",
    "Bank Name": "CHINA CITIC BANK INTERNATIONAL LIMITED MACAU BRANCH",
    "Address": "AVENIDA DOUTOR MARIO SOARES, 300-322 FINANCE AND IT CENTER OF, MACAU, FLOOR 22, UNIT B",
    "City": "MACAU",
    "Branch": "",
    "Postcode": "999078",
    "Country": "Macao",
    "Connection": "Active"
  },
  {
    "countryCode": "CCBQ",
    "bankCode": "MO",
    "branchCode": "OMX",
    "SWIFT Code": "CCBQMOMX",
    "Bank Name": "CHINA CONSTRUCTION BANK CORPORATION MACAU BRANCH",
    "Address": "AVENIDA DE ALMEIDA RIBEIRO 61, CIRCLE SQUARE, FLOOR 5",
    "City": "MACAU",
    "Branch": "",
    "Postcode": "999078",
    "Country": "Macao",
    "Connection": "Active"
  },
  {
    "countryCode": "CCBQ",
    "bankCode": "MO",
    "branchCode": "RTL",
    "SWIFT Code": "CCBQMOMXRTL",
    "Bank Name": "CHINA CONSTRUCTION BANK CORPORATION MACAU BRANCH",
    "Address": "",
    "City": "MACAU",
    "Branch": "RETAIL AND COMMERCIAL",
    "Postcode": "999078",
    "Country": "Macao",
    "Connection": "Active"
  },
  {
    "countryCode": "EVER",
    "bankCode": "MO",
    "branchCode": "OMX",
    "SWIFT Code": "EVERMOMX",
    "Bank Name": "CHINA EVERBRIGHT BANK COMPANY LIMITED MACAO BRANCH",
    "Address": "AVENIDA DOUTOR MARIO SOARES 320, FINANCE AND IT CENTRE OF MACAO,, FLOOR 23",
    "City": "MACAU",
    "Branch": "",
    "Postcode": "999078",
    "Country": "Macao",
    "Connection": "Active"
  },
  {
    "countryCode": "GDBK",
    "bankCode": "MO",
    "branchCode": "OMX",
    "SWIFT Code": "GDBKMOMX",
    "Bank Name": "CHINA GUANGFA BANK CO., LTD MACAU BRANCH",
    "Address": "AVENIDA DA PRAIA GRANDE 269",
    "City": "MACAU",
    "Branch": "",
    "Postcode": "999078",
    "Country": "Macao",
    "Connection": "Active"
  },
  {
    "countryCode": "LCHB",
    "bankCode": "MO",
    "branchCode": "OMX",
    "SWIFT Code": "LCHBMOMX",
    "Bank Name": "CHONG HING BANK LIMITED MACAU BRANCH",
    "Address": "AVENIDA DA PRAIA GRANDE 693, TAI WAH SHOP A",
    "City": "MACAU",
    "Branch": "",
    "Postcode": "999078",
    "Country": "Macao",
    "Connection": "Active"
  },
  {
    "countryCode": "CITI",
    "bankCode": "MO",
    "branchCode": "OMX",
    "SWIFT Code": "CITIMOMX",
    "Bank Name": "CITIBANK NA, MACAU",
    "Address": "AVENIDA DO INFANTE D. HENRIQ 43-53A, MACAU SQUARE, UNIT A, FLOOR 15",
    "City": "MACAU",
    "Branch": "",
    "Postcode": "999078",
    "Country": "Macao",
    "Connection": "Active"
  },
  {
    "countryCode": "WUBA",
    "bankCode": "MO",
    "branchCode": "OMX",
    "SWIFT Code": "WUBAMOMX",
    "Bank Name": "CMB WING LUNG BANK LIMITED MACAU BRANCH",
    "Address": "AVENIDA COMERCIAL DE MACAU FINANCE, AND IT CENTER OF MACAU, R/C-A",
    "City": "MACAU",
    "Branch": "",
    "Postcode": "999078",
    "Country": "Macao",
    "Connection": "Active"
  },
  {
    "countryCode": "DBSS",
    "bankCode": "MO",
    "branchCode": "OMX",
    "SWIFT Code": "DBSSMOMX",
    "Bank Name": "DBS BANK (HONG KONG) LIMITED, MACAU BRANCH",
    "Address": "DA RUA DE SANTA CLARA 5 A 7E, EDIF. RIBEIRO, LOJA C E D",
    "City": "MACAU",
    "Branch": "",
    "Postcode": "999078",
    "Country": "Macao",
    "Connection": "Active"
  },
  {
    "countryCode": "FCBK",
    "bankCode": "MO",
    "branchCode": "OMX",
    "SWIFT Code": "FCBKMOMX",
    "Bank Name": "FIRST COMMERCIAL BANK, MACAU BRANCH",
    "Address": "AVENIDA COMERCIAL DE MACAU FINANCE, AND IT CENTRE OF MACAU, FLOOR 16",
    "City": "MACAU",
    "Branch": "",
    "Postcode": "999078",
    "Country": "Macao",
    "Connection": "Active"
  },
  {
    "countryCode": "HMBA",
    "bankCode": "MO",
    "branchCode": "OMM",
    "SWIFT Code": "HMBAMOMM",
    "Bank Name": "HAITONG BANK, MACAU BRANCH",
    "Address": "AVENIDA DOUTOR MARIO SOARES, 300-322 FINANCE AND IT CENTRE OF, MACAU, FLOOR 20, UNIT - F",
    "City": "MACAU",
    "Branch": "",
    "Postcode": "999078",
    "Country": "Macao",
    "Connection": "Active"
  },
  {
    "countryCode": "HASE",
    "bankCode": "MO",
    "branchCode": "OMX",
    "SWIFT Code": "HASEMOMX",
    "Bank Name": "HANG SENG BANK LIMITED,MACAU BRANCH",
    "Address": "CIRCLE SQUARE, UNIT A-F FLOOR 3, 61 AV.DE ALMEIDA RIBEIRO",
    "City": "MACAU",
    "Branch": "",
    "Postcode": "999078",
    "Country": "Macao",
    "Connection": "Active"
  },
  {
    "countryCode": "HNBK",
    "bankCode": "MO",
    "branchCode": "OMX",
    "SWIFT Code": "HNBKMOMX",
    "Bank Name": "HUA NAN COMMERCIAL BANK,LTD. MACAU BRANCH",
    "Address": "AVENIDA DOUTOR MARIO SOARES, FINANCE AND IT CENTRE, FLOOR 17,, UNIT B-C",
    "City": "MACAU",
    "Branch": "",
    "Postcode": "999078",
    "Country": "Macao",
    "Connection": "Active"
  },
  {
    "countryCode": "ICBK",
    "bankCode": "MO",
    "branchCode": "OMX",
    "SWIFT Code": "ICBKMOMX",
    "Bank Name": "INDUSTRIAL AND COMMERCIAL BANK OF CHINA (MACAU) LIMITED",
    "Address": "AVENIDA DA AMIZADE 555, MACAU LANDMARK, FLOOR 18",
    "City": "MACAU",
    "Branch": "",
    "Postcode": "999078",
    "Country": "Macao",
    "Connection": "Active"
  },
  {
    "countryCode": "ICBK",
    "bankCode": "MO",
    "branchCode": "OMM",
    "SWIFT Code": "ICBKMOMM",
    "Bank Name": "INDUSTRIAL AND COMMERCIAL BANK OF CHINA, MACAU BRANCH",
    "Address": "AVENIDA DA AMIZADA 555, ICBC TOWER",
    "City": "MACAU",
    "Branch": "",
    "Postcode": "",
    "Country": "Macao",
    "Connection": "Active"
  },
  {
    "countryCode": "LUSO",
    "bankCode": "MO",
    "branchCode": "OMX",
    "SWIFT Code": "LUSOMOMX",
    "Bank Name": "LUSO INTERNATIONAL BANKING LTD.",
    "Address": "AVENIDA DR. MARIO SOARES 47",
    "City": "MACAU",
    "Branch": "",
    "Postcode": "999078",
    "Country": "Macao",
    "Connection": "Active"
  },
  {
    "countryCode": "MCES",
    "bankCode": "MO",
    "branchCode": "OMM",
    "SWIFT Code": "MCESMOMM",
    "Bank Name": "MACAO CENTRAL SECURITIES DEPOSITORY AND CLEARING LIMITED",
    "Address": "AVENIDA DA PRAIA GRANDE 429 CENTRO, COMERCIAL DA PRAIA GRANDE, FLOOR 4",
    "City": "MACAU",
    "Branch": "",
    "Postcode": "999078",
    "Country": "Macao",
    "Connection": "Active"
  },
  {
    "countryCode": "MCDE",
    "bankCode": "MO",
    "branchCode": "OMM",
    "SWIFT Code": "MCDEMOMM",
    "Bank Name": "MACAO DEVELOPMENT BANK LIMITED",
    "Address": "ALAMEDA DR. CARLOS D'ASSUMPCAO 22, FLOOR GF",
    "City": "MACAU",
    "Branch": "",
    "Postcode": "999078",
    "Country": "Macao",
    "Connection": "Active"
  },
  {
    "countryCode": "WIHB",
    "bankCode": "MO",
    "branchCode": "OMX",
    "SWIFT Code": "WIHBMOMX",
    "Bank Name": "OCBC BANK (MACAU) LIMITED",
    "Address": "AVENIDA DE ALMEIDA RIBEIRO 241",
    "City": "MACAU",
    "Branch": "",
    "Postcode": "999078",
    "Country": "Macao",
    "Connection": "Active"
  },
  {
    "countryCode": "SCBL",
    "bankCode": "MO",
    "branchCode": "OMX",
    "SWIFT Code": "SCBLMOMX",
    "Bank Name": "STANDARD CHARTERED BANK",
    "Address": "AVENIDA DE AMIZADE Z.A.P.E OFFICE, TOWER, MACAU LANDMARK, FLOOR 8,, ROOM 807",
    "City": "MACAU",
    "Branch": "",
    "Postcode": "999078",
    "Country": "Macao",
    "Connection": "Active"
  },
  {
    "countryCode": "TFBL",
    "bankCode": "MO",
    "branchCode": "OMX",
    "SWIFT Code": "TFBLMOMX",
    "Bank Name": "TAI FUNG BANK LIMITED",
    "Address": "ALAMEDA DR CARLOS D'ASSUMPCAO 418, TAI FUNG BANK BUILDING",
    "City": "MACAU",
    "Branch": "",
    "Postcode": "999078",
    "Country": "Macao",
    "Connection": "Active"
  },
  {
    "countryCode": "BEAS",
    "bankCode": "MO",
    "branchCode": "OMX",
    "SWIFT Code": "BEASMOMX",
    "Bank Name": "THE BANK OF EAST ASIA,LIMITED MACAU BRANCH",
    "Address": "ALAMEDA DR.CARLOS D'ASSUMPCAO, RES-DO-CHAO AP-AW 322 FU TAT FA, YUEN",
    "City": "MACAU",
    "Branch": "",
    "Postcode": "999078",
    "Country": "Macao",
    "Connection": "Active"
  },
  {
    "countryCode": "HSBC",
    "bankCode": "MO",
    "branchCode": "AAM",
    "SWIFT Code": "HSBCMOMXAAM",
    "Bank Name": "THE HONGKONG AND SHANGHAI BANKING CORPORATION LIMITED",
    "Address": "",
    "City": "MACAU",
    "Branch": "",
    "Postcode": "999078",
    "Country": "Macao",
    "Connection": "Active"
  },
  {
    "countryCode": "HSBC",
    "bankCode": "MO",
    "branchCode": "OMX",
    "SWIFT Code": "HSBCMOMX",
    "Bank Name": "THE HONGKONG AND SHANGHAI BANKING CORPORATION LIMITED",
    "Address": "613 - 639 AVENIDA DA PRAIA GRANDE",
    "City": "MACAU",
    "Branch": "",
    "Postcode": "999078",
    "Country": "Macao",
    "Connection": "Active"
  },
  {
    "countryCode": "MCHN",
    "bankCode": "MO",
    "branchCode": "OMX",
    "SWIFT Code": "MCHNMOMX",
    "Bank Name": "THE MACAU CHINESE BANK LIMITED",
    "Address": "AVENIDA DA PRAIA GRANDE 101, THE MACAU CHINESE BANK BUILDING",
    "City": "MACAU",
    "Branch": "",
    "Postcode": "999078",
    "Country": "Macao",
    "Connection": "Active"
  }
]
module.exports = macao
