const madagascar = [
  {
    "bankCode": "ABMG",
    "countryCode": "MG",
    "branchCode": "GMG",
    "SWIFT Code": "ABMGMGMG",
    "Bank Name": "ACCESBANQUE MADAGASCAR",
    "Address": "VILLA BIR HACKEIM, IBG 21 , TER ANTSAHAVOLA",
    "City": "ANTANANARIVO",
    "Branch": "",
    "Postcode": "101",
    "Country": "Madagascar",
    "Connection": "Active"
  },
  {
    "bankCode": "AFGM",
    "countryCode": "MG",
    "branchCode": "GMG",
    "SWIFT Code": "AFGMMGMG",
    "Bank Name": "AFG BANK MADAGASCAR",
    "Address": "IMMEUBLE LES JARDINS D'IVANDRY",
    "City": "",
    "Branch": "",
    "Postcode": "",
    "Country": "Madagascar",
    "Connection": "Active"
  },
  {
    "bankCode": "AFRI",
    "countryCode": "MG",
    "branchCode": "GMG",
    "SWIFT Code": "AFRIMGMG",
    "Bank Name": "BANK OF AFRICA MADAGASCAR",
    "Address": "2 , PLACE DE L'INDEPENDANCE",
    "City": "ANTANANARIVO",
    "Branch": "",
    "Postcode": "101",
    "Country": "Madagascar",
    "Connection": "Active"
  },
  {
    "bankCode": "REPU",
    "countryCode": "MG",
    "branchCode": "GMG",
    "SWIFT Code": "REPUMGMG",
    "Bank Name": "BANQUE CENTRALE DE MADAGASCAR",
    "Address": "RUE REVOLUTION SOCIALISTE MALGACHE",
    "City": "ANTANANARIVO",
    "Branch": "",
    "Postcode": "101",
    "Country": "Madagascar",
    "Connection": "Active"
  },
  {
    "bankCode": "REPU",
    "countryCode": "MG",
    "branchCode": "RTG",
    "SWIFT Code": "REPUMGMGRTG",
    "Bank Name": "BANQUE CENTRALE DE MADAGASCAR",
    "Address": "RUE REVOLUTION SOCIALISTE",
    "City": "ANTANANARIVO",
    "Branch": "RTGS BACKUP LINE",
    "Postcode": "101",
    "Country": "Madagascar",
    "Connection": "Active"
  },
  {
    "bankCode": "BMOI",
    "countryCode": "MG",
    "branchCode": "GMG",
    "SWIFT Code": "BMOIMGMG",
    "Bank Name": "BANQUE MALGACHE DE L'OCEAN INDIEN",
    "Address": "PLACE DE L'INDEPENDANCE",
    "City": "ANTANANARIVO",
    "Branch": "",
    "Postcode": "101",
    "Country": "Madagascar",
    "Connection": "Active"
  },
  {
    "bankCode": "BSBM",
    "countryCode": "MG",
    "branchCode": "GMG",
    "SWIFT Code": "BSBMMGMG",
    "Bank Name": "BANQUE SBM MADAGASCAR",
    "Address": "1 , RUE ANDIANARY RATIANARIVO, ANTZAHAVOLA",
    "City": "ANTANANARIVO",
    "Branch": "",
    "Postcode": "101",
    "Country": "Madagascar",
    "Connection": "Active"
  },
  {
    "bankCode": "BMAD",
    "countryCode": "MG",
    "branchCode": "GMG",
    "SWIFT Code": "BMADMGMG",
    "Bank Name": "BAOBAB BANQUE MADAGASCAR SA",
    "Address": "ARIANE BUILDING 5A, FLOOR 1, 5A, AREA GALAXY",
    "City": "ANTANANARIVO",
    "Branch": "",
    "Postcode": "101",
    "Country": "Madagascar",
    "Connection": "Active"
  },
  {
    "bankCode": "BFAV",
    "countryCode": "MG",
    "branchCode": "GMG",
    "SWIFT Code": "BFAVMGMG",
    "Bank Name": "BFV-SOCIETE GENERALE",
    "Address": "25 , LALANA RAZAFIMAHANDRY",
    "City": "ANTANANARIVO",
    "Branch": "",
    "Postcode": "101",
    "Country": "Madagascar",
    "Connection": "Active"
  },
  {
    "bankCode": "BGFI",
    "countryCode": "MG",
    "branchCode": "GMG",
    "SWIFT Code": "BGFIMGMG",
    "Bank Name": "BGFIBANK MADAGASCAR",
    "Address": "EXPLORER BUSINESS PARK, 101 , ANTANANARIVO RENIVOHITRA, ANKORONDRANO",
    "City": "ANTANANARIVO",
    "Branch": "",
    "Postcode": "101",
    "Country": "Madagascar",
    "Connection": "Active"
  },
  {
    "bankCode": "BAIM",
    "countryCode": "MG",
    "branchCode": "GMG",
    "SWIFT Code": "BAIMMGMG",
    "Bank Name": "BM MADAGASCAR S.A",
    "Address": "AVENUE INDEPENDENCE",
    "City": "ANTANANARIVO",
    "Branch": "",
    "Postcode": "101",
    "Country": "Madagascar",
    "Connection": "Active"
  },
  {
    "bankCode": "CLMD",
    "countryCode": "MG",
    "branchCode": "GMG",
    "SWIFT Code": "CLMDMGMG",
    "Bank Name": "BNI MADAGASCAR",
    "Address": "74 , RUE DU 26 JUIN 1960",
    "City": "ANTANANARIVO",
    "Branch": "",
    "Postcode": "101",
    "Country": "Madagascar",
    "Connection": "Active"
  },
  {
    "bankCode": "MCBL",
    "countryCode": "MG",
    "branchCode": "GMG",
    "SWIFT Code": "MCBLMGMG",
    "Bank Name": "THE MAURITIUS COMMERCIAL BANK (MADAGASCAR) SA",
    "Address": "77 A , RUE SOLOMBAVAMBAHOAKA, FRANTSAY, ANTSAHAVOLA",
    "City": "ANTANANARIVO",
    "Branch": "",
    "Postcode": "101",
    "Country": "Madagascar",
    "Connection": "Active"
  }
]
module.exports = madagascar
