const malaysia = [
  {
    "countryCode": "PTRO",
    "bankCode": "MY",
    "branchCode": "FSD",
    "SWIFT Code": "PTROMYKLFSD",
    "Bank Name": "PETROLIAM NASIONAL BERHAD",
    "Address": "FLOOR 57, PETRONAS TWIN TOWERS,, TOWER 1",
    "City": "KUALA LUMPUR",
    "Branch": "KLCC",
    "Postcode": "50088",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "AINE",
    "bankCode": "MY",
    "branchCode": "Y22",
    "SWIFT Code": "AINEMY22",
    "Bank Name": "PG ASIA INVESTMENT BANK LTD",
    "Address": "FLOOR 5, MAIN OFFICE TOWER, 5 E-2, FINANCIAL PARK COMPLEX",
    "City": "LABUAN",
    "Branch": "",
    "Postcode": "87000",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "PHCH",
    "bankCode": "MY",
    "branchCode": "Y22",
    "SWIFT Code": "PHCHMY22",
    "Bank Name": "PHILLIP CAPITAL SDN BHD",
    "Address": "FLOOR 18, BLOCK B 2, NO 12 , MEGAN, AVENUE, JALAN YAP KWAN SENG",
    "City": "KUALA LUMPUR",
    "Branch": "",
    "Postcode": "50450",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "PBLL",
    "bankCode": "MY",
    "branchCode": "YKA",
    "SWIFT Code": "PBLLMYKA",
    "Bank Name": "PUBLIC BANK (L) LTD",
    "Address": "FLOOR 8, MAIN OFFICE TOWER, FINANCIAL PARK, JLN MERDEKA",
    "City": "LABUAN",
    "Branch": "",
    "Postcode": "87000",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "PBBE",
    "bankCode": "MY",
    "branchCode": "YKL",
    "SWIFT Code": "PBBEMYKL",
    "Bank Name": "PUBLIC BANK BERHAD",
    "Address": "MENARA PUBLIC BANK, 146, JALAN AMPANG",
    "City": "KUALA LUMPUR",
    "Branch": "",
    "Postcode": "50450",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "PUIB",
    "bankCode": "MY",
    "branchCode": "YKL",
    "SWIFT Code": "PUIBMYKL",
    "Bank Name": "PUBLIC ISLAMIC BANK BERHAD",
    "Address": "146, JALAN AMPANG",
    "City": "KUALA LUMPUR",
    "Branch": "",
    "Postcode": "50450",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "RHBT",
    "bankCode": "MY",
    "branchCode": "YKL",
    "SWIFT Code": "RHBTMYKL",
    "Bank Name": "RHB ASSET MANAGEMENT SDN BHD",
    "Address": "FLOOR 8, TOWER 2 AND 3, RHB CENTRE, JALAN TUN RAZAK",
    "City": "KUALA LUMPUR",
    "Branch": "",
    "Postcode": "50400",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "RHBB",
    "bankCode": "MY",
    "branchCode": "YKA",
    "SWIFT Code": "RHBBMYKA",
    "Bank Name": "RHB BANK (L) LTD",
    "Address": "FLOOR 15B, MAIN OFFICE TOWER, FINANCIAL PARK, JALAN MERDEKA",
    "City": "LABUAN",
    "Branch": "",
    "Postcode": "87000",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "RHBB",
    "bankCode": "MY",
    "branchCode": "YKL",
    "SWIFT Code": "RHBBMYKL",
    "Bank Name": "RHB BANK BERHAD",
    "Address": "426, JALAN TUN RAZAK",
    "City": "KUALA LUMPUR",
    "Branch": "",
    "Postcode": "50400",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "OSKI",
    "bankCode": "MY",
    "branchCode": "YKL",
    "SWIFT Code": "OSKIMYKL",
    "Bank Name": "RHB INVESTMENT BANK BERHAD",
    "Address": "FLOOR 10, TOWER ONE, RHB CENTRE, JALAN TUN RAZAK",
    "City": "KUALA LUMPUR",
    "Branch": "",
    "Postcode": "50400",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "RHBA",
    "bankCode": "MY",
    "branchCode": "YKL",
    "SWIFT Code": "RHBAMYKL",
    "Bank Name": "RHB ISLAMIC BANK BERHAD",
    "Address": "FLOOR 10, RHB CENTRE, TOWER ONE, 426, JALAN TUN RAZAK",
    "City": "KUALA LUMPUR",
    "Branch": "",
    "Postcode": "50400",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "SCCH",
    "bankCode": "MY",
    "branchCode": "YKL",
    "SWIFT Code": "SCCHMYKL",
    "Bank Name": "SEA CAPITAL SERVICES BERHAD",
    "Address": "FLOOR 25, MENARA SOUTHPOINT, LINGKARAN SYED PUTRA, MID VALLEY CITY",
    "City": "KUALA LUMPUR",
    "Branch": "",
    "Postcode": "59200",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "SIMV",
    "bankCode": "MY",
    "branchCode": "Y2L",
    "SWIFT Code": "SIMVMY2L",
    "Bank Name": "SINGPOLI INVESTMENT BANK LIMITED",
    "Address": "FLOOR 11(A), UNIT B6, BLOCK 4 MAIN, OFFICE TOWER JALAN MERDEKA, FINANCIAL PARK",
    "City": "LABUAN",
    "Branch": "",
    "Postcode": "87000",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "SCBL",
    "bankCode": "MY",
    "branchCode": "YKX",
    "SWIFT Code": "SCBLMYKX",
    "Bank Name": "STANDARD CHARTERED BANK MALAYSIA BERHAD",
    "Address": "FLOOR 26, EQUATORIAL PLAZA, JALAN SULTAN ISMAIL",
    "City": "KUALA LUMPUR",
    "Branch": "ALL OFFICES IN MALAYSIA",
    "Postcode": "50250",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {},
  {
    "countryCode": "SCBL",
    "bankCode": "MY",
    "branchCode": "LAB",
    "SWIFT Code": "SCBLMYKXLAB",
    "Bank Name": "STANDARD CHARTERED BANK MALAYSIA BERHAD",
    "Address": "FLOOR 10, MAIN OFFICE TOWERS, JALAN MERDEKA, FINANCIAL PARK",
    "City": "LABUAN",
    "Branch": "LABUAN OFFSHORE BANKING UNIT ONLY",
    "Postcode": "87000",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "SCSR",
    "bankCode": "MY",
    "branchCode": "YKK",
    "SWIFT Code": "SCSRMYKK",
    "Bank Name": "STANDARD CHARTERED SAADIQ BERHAD",
    "Address": "FLOOR 26, EQUATORIAL PLAZA, JALAN SULTAN ISMAIL",
    "City": "KUALA LUMPUR",
    "Branch": "",
    "Postcode": "50250",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "SMBC",
    "bankCode": "MY",
    "branchCode": "YKA",
    "SWIFT Code": "SMBCMYKA",
    "Bank Name": "SUMITOMO MITSUI BANKING CORPORATION",
    "Address": "FLOOR 12 (B AND C), MAIN OFFICE, TOWER FINANCIAL PARK LABUAN, JLN, MERDEKA",
    "City": "LABUAN",
    "Branch": "",
    "Postcode": "87000",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "SMBC",
    "bankCode": "MY",
    "branchCode": "YKL",
    "SWIFT Code": "SMBCMYKL",
    "Bank Name": "SUMITOMO MITSUI BANKING CORPORATION MALAYSIA BERHAD",
    "Address": "FLOOR 22, SUITE 22-03, INTEGRA, TOWER, THE INTERMARK 348, JALAN TUN, RAZAK",
    "City": "KUALA LUMPUR",
    "Branch": "",
    "Postcode": "50400",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "SMBC",
    "bankCode": "MY",
    "branchCode": "Y22",
    "SWIFT Code": "SMBCMY22",
    "Bank Name": "SUMITOMO MITSUI BANKING CORPORATION MALAYSIA BERHAD",
    "Address": "FLOOR 21, INTEGRA TOWER, THE INTERMARK 348, JALAN TUN RAZAK",
    "City": "KUALA LUMPUR",
    "Branch": "",
    "Postcode": "50400",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {},
  {
    "countryCode": "TSIB",
    "bankCode": "MY",
    "branchCode": "Y22",
    "SWIFT Code": "TSIBMY22",
    "Bank Name": "TAISHIN INTERNATIONAL BANK CO.,LTD.LABUAN BRANCH",
    "Address": "FLOOR 9, MAIN OFFICE TOWER, FINANCIAL PARK, JLN MERDEKA",
    "City": "LABUAN",
    "Branch": "",
    "Postcode": "87000",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "NOSC",
    "bankCode": "MY",
    "branchCode": "YKL",
    "SWIFT Code": "NOSCMYKL",
    "Bank Name": "THE BANK OF NOVA SCOTIA BERHAD",
    "Address": "FLOOR 10, MENARA HAP SENG 2, 1, JALAN P RAMLEE",
    "City": "KUALA LUMPUR",
    "Branch": "",
    "Postcode": "50250",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "HSBC",
    "bankCode": "MY",
    "branchCode": "YKA",
    "SWIFT Code": "HSBCMYKA",
    "Bank Name": "THE HONGKONG AND SHANGHAI BANKING CORPORATION LIMITED",
    "Address": "MAIN OFFICE TOWER, B1 FLOOR 11, FINANCIAL PARK LABUAN, JLN MERDEKA",
    "City": "LABUAN",
    "Branch": "",
    "Postcode": "87000",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "TMCB",
    "bankCode": "MY",
    "branchCode": "YKL",
    "SWIFT Code": "TMCBMYKL",
    "Bank Name": "TMC SERVICES SDN. BHD.",
    "Address": "FLOOR 2, 62-68 , JALAN SULTAN AZLAN SHAH",
    "City": "KUALA LUMPUR",
    "Branch": "",
    "Postcode": "51200",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "TRTD",
    "bankCode": "MY",
    "branchCode": "Y22",
    "SWIFT Code": "TRTDMY22",
    "Bank Name": "TML REMITTANCE CENTER SDN. BHD.",
    "Address": "TAMAN MEGAH, 14-16, 3, JALAN MEGAH",
    "City": "BATU PAHAT",
    "Branch": "",
    "Postcode": "83000",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "TRLO",
    "bankCode": "MY",
    "branchCode": "YKL",
    "SWIFT Code": "TRLOMYKL",
    "Bank Name": "TRANGLO SDN BHD",
    "Address": "FLOOR 10, UNIT 10-1, TOWER 9, 8, 5, JALAN KERINCHI, AVENUE, BANGSAR SOUTH",
    "City": "KUALA LUMPUR",
    "Branch": "",
    "Postcode": "59200",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "TROH",
    "bankCode": "MY",
    "branchCode": "Y22",
    "SWIFT Code": "TROHMY22",
    "Bank Name": "TROPICANA CORPORATION BERHAD",
    "Address": "FLOOR 11, TROPICANA CITY OFFICE, TOWER 3, SS20/27, JALAN",
    "City": "PETALING JAYA",
    "Branch": "",
    "Postcode": "47400",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "UBBI",
    "bankCode": "MY",
    "branchCode": "Y22",
    "SWIFT Code": "UBBIMY22",
    "Bank Name": "UBB INVESTMENT BANK LIMITED",
    "Address": "FLOOR 10, MAIN OFFICE TWR, FIN, PARK COMPLEX JALAN MERDEKA",
    "City": "LABUAN",
    "Branch": "",
    "Postcode": "87000",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "UOVB",
    "bankCode": "MY",
    "branchCode": "YKL",
    "SWIFT Code": "UOVBMYKL",
    "Bank Name": "UNITED OVERSEAS BANK (MALAYSIA) BERHAD",
    "Address": "FLOOR 11, MENARA UOB, JALAN RAJA LAUT",
    "City": "KUALA LUMPUR",
    "Branch": "",
    "Postcode": "50350",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "UOVB",
    "bankCode": "MY",
    "branchCode": "CND",
    "SWIFT Code": "UOVBMYKLCND",
    "Bank Name": "UNITED OVERSEAS BANK (MALAYSIA) BERHAD",
    "Address": "FLOOR 9, CKB BUILDING, JALAN RAJA LAUT",
    "City": "KUALA LUMPUR",
    "Branch": "CUSTODIAN AND NOMINEES DEPARTMENT",
    "Postcode": "50350",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "UOVB",
    "bankCode": "MY",
    "branchCode": "CMS",
    "SWIFT Code": "UOVBMYKLCMS",
    "Bank Name": "UNITED OVERSEAS BANK (MALAYSIA) BERHAD",
    "Address": "FLOOR 11, MENARA UOB, JALAN RAJA LAUT",
    "City": "KUALA LUMPUR",
    "Branch": "TRANSACTION BANKING",
    "Postcode": "50350",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "UOVB",
    "bankCode": "MY",
    "branchCode": "Y2L",
    "SWIFT Code": "UOVBMY2L",
    "Bank Name": "UNITED OVERSEAS BANK LIMITED LABUAN BRANCH",
    "Address": "FLOOR 6A, MAIN OFFICE TOWER, FINANCIAL PARK LABUAN, JLN MERDEKA",
    "City": "LABUAN",
    "Branch": "",
    "Postcode": "87000",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "VAMS",
    "bankCode": "MY",
    "branchCode": "YK2",
    "SWIFT Code": "VAMSMYK2",
    "Bank Name": "VCAP ASSET MANAGERS SDN BHD",
    "Address": "BLOCK B, FLOOR 8, 12, JALAN GELENGGANG, BUKIT DAMANSARA",
    "City": "KUALA LUMPUR",
    "Branch": "",
    "Postcode": "50490",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "WAAF",
    "bankCode": "MY",
    "branchCode": "Y2L",
    "SWIFT Code": "WAAFMY2L",
    "Bank Name": "WAAFI BANK LTD.",
    "Address": "FLOOR 15, MAIN OFFICE TOWER, A1 , LABUAN,JALAN MERDEKA, FINANCIAL PARK",
    "City": "LABUAN",
    "Branch": "",
    "Postcode": "87000",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "WSMH",
    "bankCode": "MY",
    "branchCode": "YKL",
    "SWIFT Code": "WSMHMYKL",
    "Bank Name": "WILHELMSEN SHIP MANAGEMENT SDN BHD",
    "Address": "FLOOR 19, KUALA LUMP SENTRAL, 1, JALAN RAKYAT",
    "City": "KUALA LUMPUR",
    "Branch": "",
    "Postcode": "50470",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "YIHB",
    "bankCode": "MY",
    "branchCode": "YKL",
    "SWIFT Code": "YIHBMYKL",
    "Bank Name": "YINSON HOLDINGS BERHAD",
    "Address": "FLOOR 16, MENARA SOUTH POINT, MEDAN SYED PUTRA SELATAN, MID VALLEY CITY",
    "City": "KUALA LUMPUR",
    "Branch": "",
    "Postcode": "59200",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "MBBE",
    "bankCode": "MY",
    "branchCode": "JOB",
    "SWIFT Code": "MBBEMYKLJOB",
    "Bank Name": "MALAYAN BANKING BERHAD (MAYBANK)",
    "Address": "",
    "City": "JOHOR BAHRU",
    "Branch": "",
    "Postcode": "80000",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "MBBE",
    "bankCode": "MY",
    "branchCode": "PKG",
    "SWIFT Code": "MBBEMYKLPKG",
    "Bank Name": "MALAYAN BANKING BERHAD (MAYBANK)",
    "Address": "PORT KLANG",
    "City": "KLANG",
    "Branch": "",
    "Postcode": "42000",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "MBBE",
    "bankCode": "MY",
    "branchCode": "KIN",
    "SWIFT Code": "MBBEMYKLKIN",
    "Bank Name": "MALAYAN BANKING BERHAD (MAYBANK)",
    "Address": "",
    "City": "KOTA KINABALU",
    "Branch": "",
    "Postcode": "88000",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "MBBE",
    "bankCode": "MY",
    "branchCode": "YKL",
    "SWIFT Code": "MBBEMYKL",
    "Bank Name": "MALAYAN BANKING BERHAD (MAYBANK)",
    "Address": "FLOOR 8, MENARA MAYBANK, 100, JALAN TUN PERAK",
    "City": "KUALA LUMPUR",
    "Branch": "",
    "Postcode": "50050",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "MBBE",
    "bankCode": "MY",
    "branchCode": "BAN",
    "SWIFT Code": "MBBEMYKLBAN",
    "Bank Name": "MALAYAN BANKING BERHAD (MAYBANK)",
    "Address": "BANGSAR BARU",
    "City": "KUALA LUMPUR",
    "Branch": "BANGSAR BARU BRANCH",
    "Postcode": "58000",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "MBBE",
    "bankCode": "MY",
    "branchCode": "BBG",
    "SWIFT Code": "MBBEMYKLBBG",
    "Bank Name": "MALAYAN BANKING BERHAD (MAYBANK)",
    "Address": "BUKIT BINTANG",
    "City": "KUALA LUMPUR",
    "Branch": "BUKIT BINTANG BRANCH",
    "Postcode": "50250",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "MBBE",
    "bankCode": "MY",
    "branchCode": "WEB",
    "SWIFT Code": "MBBEMYKLWEB",
    "Bank Name": "MALAYAN BANKING BERHAD (MAYBANK)",
    "Address": "FLOOR 23, MENARA MAYBANK, 100, JALAN TUN PERAK",
    "City": "KUALA LUMPUR",
    "Branch": "CASH MANAGEMENT DEPARTMENT",
    "Postcode": "50050",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "MBBE",
    "bankCode": "MY",
    "branchCode": "CSD",
    "SWIFT Code": "MBBEMYKLCSD",
    "Bank Name": "MALAYAN BANKING BERHAD (MAYBANK)",
    "Address": "FLOOR 8, MENARA MAYBANK, 100, JALAN TUN PERAK",
    "City": "KUALA LUMPUR",
    "Branch": "CUSTODIAN SERVICES DEPARTMENT",
    "Postcode": "50050",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "MBBE",
    "bankCode": "MY",
    "branchCode": "KEP",
    "SWIFT Code": "MBBEMYKLKEP",
    "Bank Name": "MALAYAN BANKING BERHAD (MAYBANK)",
    "Address": "KEPONG",
    "City": "KUALA LUMPUR",
    "Branch": "KEPONG BRANCH",
    "Postcode": "52100",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "MBBE",
    "bankCode": "MY",
    "branchCode": "PWM",
    "SWIFT Code": "MBBEMYKLPWM",
    "Bank Name": "MALAYAN BANKING BERHAD (MAYBANK)",
    "Address": "PRIVATE WEALTH MY FLOOR 27, MENARA MAYBANK 100, JALAN TUN PERAK",
    "City": "KUALA LUMPUR",
    "Branch": "PRIVATE WEALTH MALAYSIA",
    "Postcode": "50050",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "MBBE",
    "bankCode": "MY",
    "branchCode": "PUD",
    "SWIFT Code": "MBBEMYKLPUD",
    "Bank Name": "MALAYAN BANKING BERHAD (MAYBANK)",
    "Address": "PUDU",
    "City": "KUALA LUMPUR",
    "Branch": "PUDU BRANCH",
    "Postcode": "55100",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "MBBE",
    "bankCode": "MY",
    "branchCode": "SUB",
    "SWIFT Code": "MBBEMYKLSUB",
    "Bank Name": "MALAYAN BANKING BERHAD (MAYBANK)",
    "Address": "",
    "City": "KUALA LUMPUR",
    "Branch": "SUBANG AIRPORT",
    "Postcode": "50000",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "MBBE",
    "bankCode": "MY",
    "branchCode": "KLC",
    "SWIFT Code": "MBBEMYKLKLC",
    "Bank Name": "MALAYAN BANKING BERHAD (MAYBANK)",
    "Address": "",
    "City": "KUALA LUMPUR",
    "Branch": "TRADE FINANCE CENTER",
    "Postcode": "50000",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "MBBE",
    "bankCode": "MY",
    "branchCode": "WSD",
    "SWIFT Code": "MBBEMYKLWSD",
    "Bank Name": "MALAYAN BANKING BERHAD (MAYBANK)",
    "Address": "WISMA SIME DARBY",
    "City": "KUALA LUMPUR",
    "Branch": "WISMA SIME DARBY BRANCH",
    "Postcode": "50350",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "MBBE",
    "bankCode": "MY",
    "branchCode": "MAL",
    "SWIFT Code": "MBBEMYKLMAL",
    "Bank Name": "MALAYAN BANKING BERHAD (MAYBANK)",
    "Address": "",
    "City": "MELAKA",
    "Branch": "",
    "Postcode": "75000",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "MBBE",
    "bankCode": "MY",
    "branchCode": "PSG",
    "SWIFT Code": "MBBEMYKLPSG",
    "Bank Name": "MALAYAN BANKING BERHAD (MAYBANK)",
    "Address": "",
    "City": "PASIR GUDANG",
    "Branch": "",
    "Postcode": "81700",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "MBBE",
    "bankCode": "MY",
    "branchCode": "PJY",
    "SWIFT Code": "MBBEMYKLPJY",
    "Bank Name": "MALAYAN BANKING BERHAD (MAYBANK)",
    "Address": "",
    "City": "PETALING JAYA",
    "Branch": "",
    "Postcode": "46000",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "MBBE",
    "bankCode": "MY",
    "branchCode": "PJC",
    "SWIFT Code": "MBBEMYKLPJC",
    "Bank Name": "MALAYAN BANKING BERHAD (MAYBANK)",
    "Address": "",
    "City": "PETALING JAYA",
    "Branch": "TRADE FINANCE CENTER",
    "Postcode": "46000",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "MBBE",
    "bankCode": "MY",
    "branchCode": "YSL",
    "SWIFT Code": "MBBEMYKLYSL",
    "Bank Name": "MALAYAN BANKING BERHAD (MAYBANK)",
    "Address": "YONG SHOOK LIN",
    "City": "PETALING JAYA",
    "Branch": "YONG SHOOK LIN BRANCH",
    "Postcode": "46200",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "MBBE",
    "bankCode": "MY",
    "branchCode": "SBN",
    "SWIFT Code": "MBBEMYKLSBN",
    "Bank Name": "MALAYAN BANKING BERHAD (MAYBANK)",
    "Address": "",
    "City": "SEREMBAN",
    "Branch": "",
    "Postcode": "70000",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "MBBE",
    "bankCode": "MY",
    "branchCode": "SHA",
    "SWIFT Code": "MBBEMYKLSHA",
    "Bank Name": "MALAYAN BANKING BERHAD (MAYBANK)",
    "Address": "",
    "City": "SHAH ALAM",
    "Branch": "",
    "Postcode": "40000",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "MBBE",
    "bankCode": "MY",
    "branchCode": "SAC",
    "SWIFT Code": "MBBEMYKLSAC",
    "Bank Name": "MALAYAN BANKING BERHAD (MAYBANK)",
    "Address": "",
    "City": "SHAH ALAM",
    "Branch": "TRADE FINANCE CENTER",
    "Postcode": "40000",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "MAYH",
    "bankCode": "MY",
    "branchCode": "Y2S",
    "SWIFT Code": "MAYHMY2S",
    "Bank Name": "MALAYSIA AIRLINES BERHAD 1116944-X",
    "Address": "CITTA MALL",
    "City": "PETALING JAYA",
    "Branch": "",
    "Postcode": "47301",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "MBBE",
    "bankCode": "MY",
    "branchCode": "YKA",
    "SWIFT Code": "MBBEMYKA",
    "Bank Name": "MAYBANK INTERNATIONAL (L) LTD.",
    "Address": "MAIN OFFICE TOWER, FINANCIAL PARK LABUAN, JLN MERDEKA",
    "City": "LABUAN",
    "Branch": "",
    "Postcode": "87000",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "MBBE",
    "bankCode": "MY",
    "branchCode": "Y2L",
    "SWIFT Code": "MBBEMY2L",
    "Bank Name": "MAYBANK INTERNATIONAL LABUAN BRANCH",
    "Address": "FLOOR 16 B, FINANCIAL PARK, JALAN MERDEKA",
    "City": "LABUAN",
    "Branch": "",
    "Postcode": "87000",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "MBEA",
    "bankCode": "MY",
    "branchCode": "YKL",
    "SWIFT Code": "MBEAMYKL",
    "Bank Name": "MAYBANK INVESTMENT BANK BERHAD",
    "Address": "TINGKAT 33, MENARA MAYBANK, 100, JALAN TUN PERAK",
    "City": "KUALA LUMPUR",
    "Branch": "",
    "Postcode": "50050",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "MBIS",
    "bankCode": "MY",
    "branchCode": "YKL",
    "SWIFT Code": "MBISMYKL",
    "Bank Name": "MAYBANK ISLAMIC BERHAD",
    "Address": "FLOOR 10, DATARAN MAYBANK, 1, JALAN MAAROF",
    "City": "KUALA LUMPUR",
    "Branch": "",
    "Postcode": "59000",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "AFBQ",
    "bankCode": "MY",
    "branchCode": "YKL",
    "SWIFT Code": "AFBQMYKL",
    "Bank Name": "MBSB BANK BERHAD",
    "Address": "FLOOR 2, KENANGA INTERNATIONAL, PODIUM BLOC JALAN SULTAN ISMAIL",
    "City": "KUALA LUMPUR",
    "Branch": "",
    "Postcode": "50250",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "ICBC",
    "bankCode": "MY",
    "branchCode": "Y2L",
    "SWIFT Code": "ICBCMY2L",
    "Bank Name": "MEGA INTERNATIONAL COMMERCIAL BANK CO., LTD. LABUAN BRANCH",
    "Address": "FLOOR 7 E2, FINANCIAL PARK COMPLEX, JLN MERDEKA",
    "City": "LABUAN",
    "Branch": "",
    "Postcode": "87000",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "DABE",
    "bankCode": "MY",
    "branchCode": "YKL",
    "SWIFT Code": "DABEMYKL",
    "Bank Name": "MERCEDES-BENZ MALAYSIA SDN. BHD.",
    "Address": "16A,1/13, JALAN BK, TAMAN PERINDUSTRIAN BANDAR KINRARA",
    "City": "PUCHONG",
    "Branch": "",
    "Postcode": "59800",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "MBSM",
    "bankCode": "MY",
    "branchCode": "YKL",
    "SWIFT Code": "MBSMMYKL",
    "Bank Name": "MERCEDES-BENZ SERVICES MALAYSIA SDN. BHD.",
    "Address": "WISMA MERCEDES-BENZ 16A, 1/13, JLN BK, TAMAN PERINDUSTRIAN KINRARA",
    "City": "PUCHONG",
    "Branch": "",
    "Postcode": "47180",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "MEIB",
    "bankCode": "MY",
    "branchCode": "YKA",
    "SWIFT Code": "MEIBMYKA",
    "Bank Name": "MIDDLE EAST INVESTMENT BANK LTD",
    "Address": "FLOOR 7, UNIT 7(B1) , MAIN OFFICE, TOWER FINANCIAL PARK LABUAN, JLN, MERDEKA",
    "City": "LABUAN",
    "Branch": "",
    "Postcode": "87000",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "MHCB",
    "bankCode": "MY",
    "branchCode": "YKA",
    "SWIFT Code": "MHCBMYKA",
    "Bank Name": "MIZUHO BANK (MALAYSIA) BERHAD",
    "Address": "FLOOR 27, MENARA MAXIS",
    "City": "KUALA LUMPUR",
    "Branch": "",
    "Postcode": "50088",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "MHCB",
    "bankCode": "MY",
    "branchCode": "YK2",
    "SWIFT Code": "MHCBMYK2",
    "Bank Name": "MIZUHO BANK (MALAYSIA) BERHAD",
    "Address": "FLOOR 27, KUALA LUMPUR CITY CENTRE, MENARA MAXIS",
    "City": "KUALA LUMPUR",
    "Branch": "",
    "Postcode": "50088",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "MHCB",
    "bankCode": "MY",
    "branchCode": "Y2L",
    "SWIFT Code": "MHCBMY2L",
    "Bank Name": "MIZUHO BANK, LTD., LABUAN BRANCH",
    "Address": "JALAN MERDEKA",
    "City": "LABUAN",
    "Branch": "",
    "Postcode": "87000",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "MBSD",
    "bankCode": "MY",
    "branchCode": "YKM",
    "SWIFT Code": "MBSDMYKM",
    "Bank Name": "MOBILITYONE SDN. BHD.",
    "Address": "UNIT 6-2A-2, WISMA LMS, NO 6, JALAN ABDUL RAHMAN IDRIS, KAMPUNG BARU",
    "City": "KUALA LUMPUR",
    "Branch": "",
    "Postcode": "50300",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "MOFD",
    "bankCode": "MY",
    "branchCode": "Y2L",
    "SWIFT Code": "MOFDMY2L",
    "Bank Name": "MONFI DIGITAL BANK LTD.",
    "Address": "UNIT 12E(2), MAIN OFFICE TOWER, FINANCIAL PARK COMPLEX",
    "City": "LABUAN",
    "Branch": "",
    "Postcode": "87000",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "BOTK",
    "bankCode": "MY",
    "branchCode": "YKX",
    "SWIFT Code": "BOTKMYKX",
    "Bank Name": "MUFG BANK (MALAYSIA) BERHAD",
    "Address": "FLOOR 9, MENARA IMC, 8, JALAN SULTAN ISMAIL",
    "City": "KUALA LUMPUR",
    "Branch": "",
    "Postcode": "50250",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "BOTK",
    "bankCode": "MY",
    "branchCode": "YKA",
    "SWIFT Code": "BOTKMYKA",
    "Bank Name": "MUFG BANK, LTD., LABUAN BRANCH",
    "Address": "FINANCIAL PARK, JALAN MERDEKA",
    "City": "LABUAN",
    "Branch": "LABUAN BRANCH",
    "Postcode": "87000",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "NOCM",
    "bankCode": "MY",
    "branchCode": "YKL",
    "SWIFT Code": "NOCMMYKL",
    "Bank Name": "NOMURA ASSET MANAGEMENT MALAYSIA SDN BHD",
    "Address": "FLOOR 16, SUITE 16.2, MENARA IMC, 8, JALAN SULTAN ISMAIL",
    "City": "KUALA LUMPUR",
    "Branch": "",
    "Postcode": "50250",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "OABB",
    "bankCode": "MY",
    "branchCode": "YKL",
    "SWIFT Code": "OABBMYKL",
    "Bank Name": "OCBC AL-AMIN BANK BERHAD",
    "Address": "FLOOR 25, WISMA LEE RUBBER, JALAN MELAKA",
    "City": "KUALA LUMPUR",
    "Branch": "",
    "Postcode": "50100",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "OCBC",
    "bankCode": "MY",
    "branchCode": "YKL",
    "SWIFT Code": "OCBCMYKL",
    "Bank Name": "OCBC BANK (MALAYSIA) BERHAD",
    "Address": "FLOOR 11, MENARA OCBC, 18, JALAN TUN PERAK",
    "City": "KUALA LUMPUR",
    "Branch": "",
    "Postcode": "50500",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "OCBC",
    "bankCode": "MY",
    "branchCode": "YKA",
    "SWIFT Code": "OCBCMYKA",
    "Bank Name": "OVERSEA-CHINESE BANKING CORPORATION LIMITED, LABUAN BRANCH",
    "Address": "FLOOR 8C, MAIN OFFICE TOWER, FINANCIAL PARK, JALAN MERDEKA",
    "City": "LABUAN",
    "Branch": "",
    "Postcode": "87000",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "PCTR",
    "bankCode": "MY",
    "branchCode": "YK2",
    "SWIFT Code": "PCTRMYK2",
    "Bank Name": "PACIFIC TRUSTEES BERHAD",
    "Address": "FLOOR 11, UNIT A-11-8, MEGAN, AVENUE 1 189, JALAN TUN RAZAK",
    "City": "KUALA LUMPUR",
    "Branch": "",
    "Postcode": "57000",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "PHCI",
    "bankCode": "MY",
    "branchCode": "Y2L",
    "SWIFT Code": "PHCIMY2L",
    "Bank Name": "PERFECT HEXAGON COMMODITY AND INVESTMENT BANK LIMITED",
    "Address": "FLOOR 8, UNIT 8B(3), FINANCIAL, PARK COMPLEX MAIN TWR JALAN MERDEKA",
    "City": "LABUAN",
    "Branch": "",
    "Postcode": "87000",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "PERM",
    "bankCode": "MY",
    "branchCode": "YKB",
    "SWIFT Code": "PERMMYKB",
    "Bank Name": "PERMODALAN NASIONAL BERHAD",
    "Address": "FLOOR 4, PNB TOWER, 201-A, JALAN TUN RAZAK",
    "City": "KUALA LUMPUR",
    "Branch": "",
    "Postcode": "50400",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "PERM",
    "bankCode": "MY",
    "branchCode": "YKP",
    "SWIFT Code": "PERMMYKP",
    "Bank Name": "PERMODALAN NASIONAL BERHAD",
    "Address": "FLOOR 32, MENARA PNB, 201-A , JALAN TUN RAZAK",
    "City": "KUALA LUMPUR",
    "Branch": "",
    "Postcode": "50400",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "PERM",
    "bankCode": "MY",
    "branchCode": "YKK",
    "SWIFT Code": "PERMMYKK",
    "Bank Name": "PERMODALAN NASIONAL BERHAD",
    "Address": "FLOOR 4, PNB TOWER, 201-A, JALAN TUN RAZAK",
    "City": "KUALA LUMPUR",
    "Branch": "",
    "Postcode": "50400",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "PERM",
    "bankCode": "MY",
    "branchCode": "YKG",
    "SWIFT Code": "PERMMYKG",
    "Bank Name": "PERMODALAN NASIONAL BERHAD",
    "Address": "32 FLOOR 4, PNB TOWER, 201-A, JALAN TUN RAZAK",
    "City": "KUALA LUMPUR",
    "Branch": "",
    "Postcode": "50400",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "PTRO",
    "bankCode": "MY",
    "branchCode": "YKL",
    "SWIFT Code": "PTROMYKL",
    "Bank Name": "PETROLIAM NASIONAL BERHAD",
    "Address": "FLOOR 56, PETRONAS TWIN TOWER,, TOWER 1",
    "City": "KUALA LUMPUR",
    "Branch": "",
    "Postcode": "50088",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "CITI",
    "bankCode": "MY",
    "branchCode": "PEN",
    "SWIFT Code": "CITIMYKLPEN",
    "Bank Name": "CITIBANK BERHAD",
    "Address": "MENARA NORTHAM, 42, JALAN SULTAN AHMAD SHAH",
    "City": "GEORGE TOWN",
    "Branch": "PENANG BRANCH",
    "Postcode": "10050",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "CITI",
    "bankCode": "MY",
    "branchCode": "JOD",
    "SWIFT Code": "CITIMYKLJOD",
    "Bank Name": "CITIBANK BERHAD",
    "Address": "BANGUNAN CITY PLAZA, 21, JALAN TEBRAU",
    "City": "JOHOR BAHRU",
    "Branch": "JOHOR BAHRU BRANCH",
    "Postcode": "80300",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "CITI",
    "bankCode": "MY",
    "branchCode": "YKL",
    "SWIFT Code": "CITIMYKL",
    "Bank Name": "CITIBANK BERHAD",
    "Address": "FLOOR 45, MENARA CITIBANK, 165, JALAN AMPANG",
    "City": "KUALA LUMPUR",
    "Branch": "JALAN AMPANG",
    "Postcode": "50450",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "CITI",
    "bankCode": "MY",
    "branchCode": "LAB",
    "SWIFT Code": "CITIMYKLLAB",
    "Bank Name": "CITIBANK BERHAD",
    "Address": "",
    "City": "KUALA LUMPUR",
    "Branch": "LAB",
    "Postcode": "50000",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "CRES",
    "bankCode": "MY",
    "branchCode": "YKL",
    "SWIFT Code": "CRESMYKL",
    "Bank Name": "CREDIT SUISSE SECURITIES (MALAYSIA) SDN. BHD.",
    "Address": "SUITE 7.6, MENARA IMC, 8, JALAN SULTAN ISMAIL",
    "City": "KUALA LUMPUR",
    "Branch": "",
    "Postcode": "50250",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "DBSS",
    "bankCode": "MY",
    "branchCode": "Y2A",
    "SWIFT Code": "DBSSMY2A",
    "Bank Name": "DBS BANK LTD, LABUAN BRANCH",
    "Address": "FLOOR 10A, MAIN OFFICE TOWER, FINANCIAL PARK LABUAN, JLN MERDEKA",
    "City": "LABUAN",
    "Branch": "",
    "Postcode": "87000",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "DEUT",
    "bankCode": "MY",
    "branchCode": "GMO",
    "SWIFT Code": "DEUTMYKLGMO",
    "Bank Name": "DEUTSCHE BANK (MALAYSIA) BERHAD",
    "Address": "",
    "City": "KUALA LUMPUR",
    "Branch": "",
    "Postcode": "50000",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "DEUT",
    "bankCode": "MY",
    "branchCode": "IBW",
    "SWIFT Code": "DEUTMYKLIBW",
    "Bank Name": "DEUTSCHE BANK (MALAYSIA) BERHAD",
    "Address": "",
    "City": "KUALA LUMPUR",
    "Branch": "",
    "Postcode": "50000",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "DEUT",
    "bankCode": "MY",
    "branchCode": "YKL",
    "SWIFT Code": "DEUTMYKL",
    "Bank Name": "DEUTSCHE BANK (MALAYSIA) BERHAD",
    "Address": "FLOOR 18-20, MENARA IMC, 8, JALAN SULTAN ISMAIL",
    "City": "KUALA LUMPUR",
    "Branch": "",
    "Postcode": "50250",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "DEUT",
    "bankCode": "MY",
    "branchCode": "DFS",
    "SWIFT Code": "DEUTMYKLDFS",
    "Bank Name": "DEUTSCHE BANK (MALAYSIA) BERHAD",
    "Address": "FLOOR 18-20, MENARA IMC, 8, JALAN SULTAN ISMAIL",
    "City": "KUALA LUMPUR",
    "Branch": "",
    "Postcode": "50250",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "DEUT",
    "bankCode": "MY",
    "branchCode": "ISB",
    "SWIFT Code": "DEUTMYKLISB",
    "Bank Name": "DEUTSCHE BANK (MALAYSIA) BERHAD",
    "Address": "",
    "City": "KUALA LUMPUR",
    "Branch": "INTERNATIONAL ISLAMIC BANKING, MALAYSIA BRANCH",
    "Postcode": "50000",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "DEUT",
    "bankCode": "MY",
    "branchCode": "BLB",
    "SWIFT Code": "DEUTMYKLBLB",
    "Bank Name": "DEUTSCHE BANK (MALAYSIA) BERHAD",
    "Address": "",
    "City": "LABUAN",
    "Branch": "LABUAN BRANCH",
    "Postcode": "87000",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "EUIE",
    "bankCode": "MY",
    "branchCode": "Y22",
    "SWIFT Code": "EUIEMY22",
    "Bank Name": "EUROPE-ASIA INVESTMENT BANK LIMITED",
    "Address": "FLOOR 8, STRATA OFFICE, 1, JALAN BANGSAR, MENARA",
    "City": "KUALA LUMPUR",
    "Branch": "",
    "Postcode": "59200",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "EXMB",
    "bankCode": "MY",
    "branchCode": "YKL",
    "SWIFT Code": "EXMBMYKL",
    "Bank Name": "EXPORT-IMPORT BANK OF MALAYSIA BERHAD",
    "Address": "FLOOR 8, EXIM BANK, JALAN SULTAN ISMAIL",
    "City": "KUALA LUMPUR",
    "Branch": "",
    "Postcode": "50250",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "FGVC",
    "bankCode": "MY",
    "branchCode": "YKL",
    "SWIFT Code": "FGVCMYKL",
    "Bank Name": "FGV CAPITAL SDN. BHD.",
    "Address": "EAST FLOOR 20, WISMA FGV, JALAN RAJA LAUT",
    "City": "KUALA LUMPUR",
    "Branch": "",
    "Postcode": "50350",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "FGVH",
    "bankCode": "MY",
    "branchCode": "YKL",
    "SWIFT Code": "FGVHMYKL",
    "Bank Name": "FGV HOLDINGS BERHAD",
    "Address": "LEVEL 20 EAST, WISMA FGV, JALAN RAJA LAUT",
    "City": "KUALA LUMPUR",
    "Branch": "",
    "Postcode": "50350",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "FABE",
    "bankCode": "MY",
    "branchCode": "Y22",
    "SWIFT Code": "FABEMY22",
    "Bank Name": "FIDELITY ASIA BANK LTD",
    "Address": "FLOOR 5-E-1, MAIN OFFICE TOWER, FINANCIAL PARK, JLN MERDEKA SABAH",
    "City": "LABUAN",
    "Branch": "",
    "Postcode": "87000",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "FNTH",
    "bankCode": "MY",
    "branchCode": "Y2L",
    "SWIFT Code": "FNTHMY2L",
    "Bank Name": "FINTECH BANK LTD.",
    "Address": "FLOOR 4, FINANC PRK CPLEX MAIN, OFFICE TOWER JALAN MERDEKA",
    "City": "LABUAN",
    "Branch": "",
    "Postcode": "87000",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "NBAD",
    "bankCode": "MY",
    "branchCode": "YKL",
    "SWIFT Code": "NBADMYKL",
    "Bank Name": "FIRST ABU DHABI BANK PJSC ( FORMERLY NATIONAL BANK OF ABU DHABI)",
    "Address": "FLOOR 26, TIARA LABUAN, JALAN TANJUNG BATU",
    "City": "LABUAN",
    "Branch": "",
    "Postcode": "87000",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "NBAD",
    "bankCode": "MY",
    "branchCode": "LAU",
    "SWIFT Code": "NBADMYKLLAU",
    "Bank Name": "FIRST ABU DHABI BANK PJSC ( FORMERLY NATIONAL BANK OF ABU DHABI)",
    "Address": "FLOOR 3, UNIT (I) , MAIN OFFICE, TOWER FINANCIAL PARK LABUAN, JLN, MERDEKA",
    "City": "LABUAN",
    "Branch": "",
    "Postcode": "87000",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "GATI",
    "bankCode": "MY",
    "branchCode": "Y22",
    "SWIFT Code": "GATIMY22",
    "Bank Name": "GAT INVESTMENT BANK LIMITED",
    "Address": "FLOOR 14, OFFICE 1423, 14(C),, FINANCIAL PARK LABUAN COMPLEX JALAN, MEDERKA",
    "City": "LABUAN",
    "Branch": "",
    "Postcode": "87000",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "GTIV",
    "bankCode": "MY",
    "branchCode": "Y2L",
    "SWIFT Code": "GTIVMY2L",
    "Bank Name": "GOLDEN TOUCH INVESTMENT BANK LIMITED",
    "Address": "LOT 7616, KENSINGTON GARDENS, U1317, JALAN JUMIDAR BUYONG",
    "City": "LABUAN",
    "Branch": "",
    "Postcode": "87000",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "GXSP",
    "bankCode": "MY",
    "branchCode": "YKL",
    "SWIFT Code": "GXSPMYKL",
    "Bank Name": "GX BANK BERHAD",
    "Address": "KL ECO CITY, 1,3, MENARA, JALAN BANGSAR",
    "City": "KUALA LUMPUR",
    "Branch": "",
    "Postcode": "59200",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "HLBB",
    "bankCode": "MY",
    "branchCode": "YKL",
    "SWIFT Code": "HLBBMYKL",
    "Bank Name": "HONG LEONG BANK BERHAD",
    "Address": "FLOOR 3, WISMA HONG LEONG, 18 , JALAN PERAK",
    "City": "KUALA LUMPUR",
    "Branch": "",
    "Postcode": "50450",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "HLBL",
    "bankCode": "MY",
    "branchCode": "Y22",
    "SWIFT Code": "HLBLMY22",
    "Bank Name": "HONG LEONG BANK BERHAD, LABUAN INTERNATIONAL BRANCH",
    "Address": "JALAN MERDEKA",
    "City": "LABUAN",
    "Branch": "",
    "Postcode": "87000",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "HLIV",
    "bankCode": "MY",
    "branchCode": "YKL",
    "SWIFT Code": "HLIVMYKL",
    "Bank Name": "HONG LEONG INVESTMENT BANK BERHAD",
    "Address": "FLOOR 10, WISMA HONG LEONG, 18 , JALAN PERAK",
    "City": "KUALA LUMPUR",
    "Branch": "",
    "Postcode": "50450",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "HLIB",
    "bankCode": "MY",
    "branchCode": "YKL",
    "SWIFT Code": "HLIBMYKL",
    "Bank Name": "HONG LEONG ISLAMIC BANK BERHAD",
    "Address": "FLOOR 23, MENARA HONG LEONG, NO. 6, JALAN DAMANLELA, BUKIT DAMANS",
    "City": "KUALA LUMPUR",
    "Branch": "",
    "Postcode": "50490",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "HSTM",
    "bankCode": "MY",
    "branchCode": "YKL",
    "SWIFT Code": "HSTMMYKL",
    "Bank Name": "HSBC (MALAYSIA) TRUSTEE BERHAD",
    "Address": "HSBC SOUTH TOWER, FLOOR 13, 2 LEBOH AMPANG",
    "City": "KUALA LUMPUR",
    "Branch": "",
    "Postcode": "50100",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "HSTM",
    "bankCode": "MY",
    "branchCode": "GWS",
    "SWIFT Code": "HSTMMYKLGWS",
    "Bank Name": "HSBC (MALAYSIA) TRUSTEE BERHAD",
    "Address": "WISMA MARAN, FLOOR 6, 28 MEDAN PASAR",
    "City": "KUALA LUMPUR",
    "Branch": "GLOBAL WEALTH SOLUTIONS",
    "Postcode": "50050",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "HMAB",
    "bankCode": "MY",
    "branchCode": "YKL",
    "SWIFT Code": "HMABMYKL",
    "Bank Name": "HSBC AMANAH MALAYSIA BERHAD",
    "Address": "BANGUNAN HSBC, 2 LEBOH AMPANG",
    "City": "KUALA LUMPUR",
    "Branch": "",
    "Postcode": "50100",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "HBMB",
    "bankCode": "MY",
    "branchCode": "YKL",
    "SWIFT Code": "HBMBMYKL",
    "Bank Name": "HSBC BANK MALAYSIA BERHAD",
    "Address": "FLOOR 21, MENARA IQ, TUN RAZAK, EXCHANGE LINGKARAN TRX",
    "City": "KUALA LUMPUR",
    "Branch": "",
    "Postcode": "55188",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "IMSH",
    "bankCode": "MY",
    "branchCode": "YK2",
    "SWIFT Code": "IMSHMYK2",
    "Bank Name": "I-VCAP MANAGEMENT SDN BHD",
    "Address": "BLOCK B, FLOOR 8, 12, JALAN GELENGGANG, BUKIT DAMANSARA",
    "City": "KUALA LUMPUR",
    "Branch": "",
    "Postcode": "50490",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "IBHI",
    "bankCode": "MY",
    "branchCode": "Y2L",
    "SWIFT Code": "IBHIMY2L",
    "Bank Name": "IBH INVESTMENT BANK LIMITED",
    "Address": "LEVEL 6F (2), MAIN OFFICE TOWER, FINANCIAL PARK COMPLEX, JLN MERDEKA",
    "City": "LABUAN",
    "Branch": "",
    "Postcode": "87000",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "IIMB",
    "bankCode": "MY",
    "branchCode": "YKL",
    "SWIFT Code": "IIMBMYKL",
    "Bank Name": "INDIA INTERNATIONAL BANK (MALAYSIA) BERHAD",
    "Address": "FLOOR 0,MEZANINE, BGN YEE SENG, 15, JALAN RAJA CHULAN",
    "City": "KUALA LUMPUR",
    "Branch": "",
    "Postcode": "50200",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "ICBK",
    "bankCode": "MY",
    "branchCode": "YKL",
    "SWIFT Code": "ICBKMYKL",
    "Bank Name": "INDUSTRIAL AND COMMERCIAL BANK OF CHINA (MALAYSIA) BERHAD.",
    "Address": "FLOOR 10, MENARA MAXIS",
    "City": "KUALA LUMPUR",
    "Branch": "",
    "Postcode": "50088",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "ICBK",
    "bankCode": "MY",
    "branchCode": "LAB",
    "SWIFT Code": "ICBKMYKLLAB",
    "Bank Name": "INDUSTRIAL AND COMMERCIAL BANK OF CHINA (MALAYSIA) BERHAD.",
    "Address": "",
    "City": "LABUAN",
    "Branch": "LABUAN BRANCH",
    "Postcode": "87000",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "CHAS",
    "bankCode": "MY",
    "branchCode": "YKX",
    "SWIFT Code": "CHASMYKX",
    "Bank Name": "J.P.MORGAN CHASE BANK BERHAD",
    "Address": "FLOOR 18, THE INTERMARK, NTEGRA, TOWER 348, JALAN TUN RAZAK",
    "City": "KUALA LUMPUR",
    "Branch": "",
    "Postcode": "50400",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "CHAS",
    "bankCode": "MY",
    "branchCode": "SEC",
    "SWIFT Code": "CHASMYKXSEC",
    "Bank Name": "J.P.MORGAN CHASE BANK BERHAD",
    "Address": "",
    "City": "KUALA LUMPUR",
    "Branch": "JPMORGAN SECURITIES - MALAYSIA",
    "Postcode": "50000",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "CHAS",
    "bankCode": "MY",
    "branchCode": "Y2A",
    "SWIFT Code": "CHASMY2A",
    "Bank Name": "JPMORGAN CHASE BANK, N.A., LABUAN BRANCH",
    "Address": "FLOOR 5, MAIN OFFICE TOWER, FINANCIAL PARK, JLN MERDEKA",
    "City": "LABUAN",
    "Branch": "",
    "Postcode": "87000",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "KAFB",
    "bankCode": "MY",
    "branchCode": "YKL",
    "SWIFT Code": "KAFBMYKL",
    "Bank Name": "KAF INVESTMENT BANK BERHAD",
    "Address": "FLOOR 14, CHULAN TOWER, 3, JALAN CONLAY",
    "City": "KUALA LUMPUR",
    "Branch": "",
    "Postcode": "50450",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "KAFB",
    "bankCode": "MY",
    "branchCode": "YK2",
    "SWIFT Code": "KAFBMYK2",
    "Bank Name": "KAF INVESTMENT BANK BERHAD",
    "Address": "FLOOR 14, CHULAN TOWER, 14, JALAN CONLAY",
    "City": "KUALA LUMPUR",
    "Branch": "",
    "Postcode": "50450",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "ECML",
    "bankCode": "MY",
    "branchCode": "YKL",
    "SWIFT Code": "ECMLMYKL",
    "Bank Name": "KENANGA INVESTMENT BANK BERHAD",
    "Address": "FLOOR 17, KENANGA TOWER, 237, JALAN TUN RAZAK",
    "City": "KUALA LUMPUR",
    "Branch": "",
    "Postcode": "50400",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "KHAZ",
    "bankCode": "MY",
    "branchCode": "YKL",
    "SWIFT Code": "KHAZMYKL",
    "Bank Name": "KHAZANAH NASIONAL BERHAD",
    "Address": "FLOOR 22, MERCU UEM, 5, JALAN STESEN SENTRAL",
    "City": "KUALA LUMPUR",
    "Branch": "",
    "Postcode": "50470",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "KLKB",
    "bankCode": "MY",
    "branchCode": "Y2I",
    "SWIFT Code": "KLKBMY2I",
    "Bank Name": "KUALA LUMPUR KEPONG BERHAD",
    "Address": "WISMA TAIKO, 1, JALAN S.P.SEENIVASAGAM",
    "City": "IPOH",
    "Branch": "",
    "Postcode": "30000",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "KFHO",
    "bankCode": "MY",
    "branchCode": "YKL",
    "SWIFT Code": "KFHOMYKL",
    "Bank Name": "KUWAIT FINANCE HOUSE (MALAYSIA) BERHAD",
    "Address": "FLOOR 26, MENARA PRESTIGE, 1, JALAN PINANG",
    "City": "KUALA LUMPUR",
    "Branch": "",
    "Postcode": "50450",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "LBGR",
    "bankCode": "MY",
    "branchCode": "Y22",
    "SWIFT Code": "LBGRMY22",
    "Bank Name": "LBS",
    "Address": "FLOOR 1-4, PLAZA SERI SETIA, 1, SS9/2, JALAN",
    "City": "PETALING JAYA",
    "Branch": "",
    "Postcode": "47300",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "MBBE",
    "bankCode": "MY",
    "branchCode": "PEN",
    "SWIFT Code": "MBBEMYKLPEN",
    "Bank Name": "MALAYAN BANKING BERHAD (MAYBANK)",
    "Address": "",
    "City": "",
    "Branch": "",
    "Postcode": "",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "MBBE",
    "bankCode": "MY",
    "branchCode": "PGC",
    "SWIFT Code": "MBBEMYKLPGC",
    "Bank Name": "MALAYAN BANKING BERHAD (MAYBANK)",
    "Address": "",
    "City": "",
    "Branch": "TRADE FINANCE CENTER",
    "Postcode": "",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "MBBE",
    "bankCode": "MY",
    "branchCode": "BWC",
    "SWIFT Code": "MBBEMYKLBWC",
    "Bank Name": "MALAYAN BANKING BERHAD (MAYBANK)",
    "Address": "",
    "City": "BUTTERWORTH",
    "Branch": "TRADE FINANCE CENTER",
    "Postcode": "12000",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "MBBE",
    "bankCode": "MY",
    "branchCode": "IPH",
    "SWIFT Code": "MBBEMYKLIPH",
    "Bank Name": "MALAYAN BANKING BERHAD (MAYBANK)",
    "Address": "",
    "City": "IPOH",
    "Branch": "",
    "Postcode": "30000",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "ACDB",
    "bankCode": "MY",
    "branchCode": "YK2",
    "SWIFT Code": "ACDBMYK2",
    "Bank Name": "ACS DIGITAL BERHAD",
    "Address": "FLOOR 18, UOA CORPORATE TOWER, 8, JALAN KERINCHI",
    "City": "KUALA LUMPUR",
    "Branch": "",
    "Postcode": "59200",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "PHBM",
    "bankCode": "MY",
    "branchCode": "YKL",
    "SWIFT Code": "PHBMMYKL",
    "Bank Name": "AFFIN BANK BERHAD",
    "Address": "FLOOR 19, MENARA AFFIN, LINGKARAN TRX, TUN RAZAK EXCHANGE",
    "City": "KUALA LUMPUR",
    "Branch": "",
    "Postcode": "55188",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "HDSB",
    "bankCode": "MY",
    "branchCode": "Y2P",
    "SWIFT Code": "HDSBMY2P",
    "Bank Name": "AFFIN HWANG INVESTMENT BANK BERHAD",
    "Address": "FLOOR 27, MENARA BOUSTEAD, 69, JALAN RAJA CHULAN",
    "City": "KUALA LUMPUR",
    "Branch": "",
    "Postcode": "50200",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "AIBB",
    "bankCode": "MY",
    "branchCode": "YKL",
    "SWIFT Code": "AIBBMYKL",
    "Bank Name": "AFFIN ISLAMIC BANK BERHAD",
    "Address": "FLOOR 19, MENARA AFFIN, LINGKARAN TRX, TUN RAZAK EXCHANGE",
    "City": "KUALA LUMPUR",
    "Branch": "",
    "Postcode": "55188",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "HIMR",
    "bankCode": "MY",
    "branchCode": "YKL",
    "SWIFT Code": "HIMRMYKL",
    "Bank Name": "AHAM ASSET MANAGEMENT BERHAD",
    "Address": "FLOOR GF, MENARA BOUSTEAD, 69, JALAN RAJA CHULAN",
    "City": "KUALA LUMPUR",
    "Branch": "",
    "Postcode": "50200",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "AIAC",
    "bankCode": "MY",
    "branchCode": "YKL",
    "SWIFT Code": "AIACMYKL",
    "Bank Name": "AIA BHD.",
    "Address": "FLOOR 29, MENARA AIA, 99, JALAN AMPANG",
    "City": "KUALA LUMPUR",
    "Branch": "",
    "Postcode": "50450",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "AIBM",
    "bankCode": "MY",
    "branchCode": "YKL",
    "SWIFT Code": "AIBMMYKL",
    "Bank Name": "AIBL",
    "Address": "FLOOR 15, B02-B, ACE TOWER, ECO, CITY 3, MENARA , JALAN BANGSAR KL",
    "City": "KUALA LUMPUR",
    "Branch": "",
    "Postcode": "59200",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "RJHI",
    "bankCode": "MY",
    "branchCode": "YKL",
    "SWIFT Code": "RJHIMYKL",
    "Bank Name": "AL RAJHI BANKING AND INVESTMENT CORPORATION (MALAYSIA) BHD",
    "Address": "FLOOR GROUND, WISMA GOLDEN EAGLE REALTY 142-B, J JALAN AMPANG, EAST BLOCK",
    "City": "KUALA LUMPUR",
    "Branch": "",
    "Postcode": "50450",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "MFBB",
    "bankCode": "MY",
    "branchCode": "YKL",
    "SWIFT Code": "MFBBMYKL",
    "Bank Name": "ALLIANCE BANK MALAYSIA BERHAD",
    "Address": "MENARA MULTI-PURPOSE, CAPITAL SQ, 8, JALAN MUNSHI ABDULLAH",
    "City": "KUALA LUMPUR",
    "Branch": "",
    "Postcode": "50100",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "ALSR",
    "bankCode": "MY",
    "branchCode": "YKL",
    "SWIFT Code": "ALSRMYKL",
    "Bank Name": "ALLIANCE ISLAMIC BANK BERHAD",
    "Address": "FLOOR 22, MENARA MULTI-PURPOSE, CAPITAL SQ 8, JALAN MUNSHI ABDULLAH",
    "City": "KUALA LUMPUR",
    "Branch": "",
    "Postcode": "50100",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "AMTB",
    "bankCode": "MY",
    "branchCode": "YKL",
    "SWIFT Code": "AMTBMYKL",
    "Bank Name": "AMANAHRAYA TRUSTEES BERHAD",
    "Address": "FLOOR 14, WISMA AMANAHRAYA, 2, JALAN AMPANG",
    "City": "KUALA LUMPUR",
    "Branch": "",
    "Postcode": "50508",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "ARBK",
    "bankCode": "MY",
    "branchCode": "YKL",
    "SWIFT Code": "ARBKMYKL",
    "Bank Name": "AMBANK (M) BERHAD",
    "Address": "FLOOR 23, BANGUNAN AMBANK GROUP, 55, JALAN RAJA CHULAN",
    "City": "KUALA LUMPUR",
    "Branch": "",
    "Postcode": "50200",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "ARBK",
    "bankCode": "MY",
    "branchCode": "LAB",
    "SWIFT Code": "ARBKMYKLLAB",
    "Bank Name": "AMBANK (M) BERHAD",
    "Address": "",
    "City": "LABUAN",
    "Branch": "LABUAN OFFSHORE BRANCH (LICENSED LABUAN BANK NO.080097D)",
    "Postcode": "87000",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "AISL",
    "bankCode": "MY",
    "branchCode": "YKL",
    "SWIFT Code": "AISLMYKL",
    "Bank Name": "AMBANK ISLAMIC BERHAD",
    "Address": "FLOOR 45, MENARA AMBANK, JALAN YAP KWAN SENG",
    "City": "KUALA LUMPUR",
    "Branch": "",
    "Postcode": "50450",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "AMMB",
    "bankCode": "MY",
    "branchCode": "YKL",
    "SWIFT Code": "AMMBMYKL",
    "Bank Name": "AMINVESTMENT BANK BERHAD (FORMERLY KNOWN AS AMMERCHANT BANK BERHAD)",
    "Address": "FLOOR 22, BANGUNAN AMBANK GROUP, 55, JALAN RAJA CHULAN",
    "City": "KUALA LUMPUR",
    "Branch": "",
    "Postcode": "50200",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "ADLN",
    "bankCode": "MY",
    "branchCode": "Y2L",
    "SWIFT Code": "ADLNMY2L",
    "Bank Name": "ASIA DIGITAL BANK LTD. (LABUAN INVESTMENT BANK)",
    "Address": "UNIT OFFICE 3D, MAIN OFFICE TOWER, FINANCIAL PARK JALAN MERDEKA",
    "City": "LABUAN",
    "Branch": "",
    "Postcode": "87000",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "ASNC",
    "bankCode": "MY",
    "branchCode": "Y2L",
    "SWIFT Code": "ASNCMY2L",
    "Bank Name": "ASIA INVESTMENT BANKING CORPORATION",
    "Address": "UNIT 5(C), MAIN OFFICE TOWER, FINANCIAL PARK COMPLEX, JLN MERDEKA",
    "City": "LABUAN",
    "Branch": "",
    "Postcode": "87000",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "ASPM",
    "bankCode": "MY",
    "branchCode": "YKL",
    "SWIFT Code": "ASPMMYKL",
    "Bank Name": "ASIA PACIFIC INVESTMENT BANK LTD",
    "Address": "FLOOR 7, SUITE 07-01, MENARA KECK SENG 203, JALAN BUKIT BINTANG",
    "City": "KUALA LUMPUR",
    "Branch": "",
    "Postcode": "55100",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "AXGB",
    "bankCode": "MY",
    "branchCode": "YKK",
    "SWIFT Code": "AXGBMYKK",
    "Bank Name": "AXIATA GROUP BERHAD",
    "Address": "9, 5, JALAN STESEN SENTRAL",
    "City": "KUALA LUMPUR",
    "Branch": "",
    "Postcode": "50470",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "BKKB",
    "bankCode": "MY",
    "branchCode": "YKL",
    "SWIFT Code": "BKKBMYKL",
    "Bank Name": "BANGKOK BANK BERHAD",
    "Address": "MENARA BANGKOK BANK, 105 , JALAN AMPANG",
    "City": "KUALA LUMPUR",
    "Branch": "",
    "Postcode": "50450",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "BAHL",
    "bankCode": "MY",
    "branchCode": "Y2A",
    "SWIFT Code": "BAHLMY2A",
    "Bank Name": "BANK AL HABIB LIMITED",
    "Address": "FLOOR 11B, MAIN OFFICE TOWER, LABUAN COMPLEX, JLN MERDEKA",
    "City": "LABUAN",
    "Branch": "",
    "Postcode": "87000",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "BIMB",
    "bankCode": "MY",
    "branchCode": "YKL",
    "SWIFT Code": "BIMBMYKL",
    "Bank Name": "BANK ISLAM MALAYSIA BERHAD",
    "Address": "MENARA BANK ISLAM, JALAN PERAK",
    "City": "KUALA LUMPUR",
    "Branch": "",
    "Postcode": "50450",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "BKRM",
    "bankCode": "MY",
    "branchCode": "YKL",
    "SWIFT Code": "BKRMMYKL",
    "Bank Name": "BANK KERJASAMA RAKYAT MALAYSIA BERHAD (BANK RAKYAT)",
    "Address": "FLOOR 1, BANGUNAN BANK RAKYAT, PTPK, 11024, JALAN TANGSI",
    "City": "KUALA LUMPUR",
    "Branch": "",
    "Postcode": "50732",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "BMMB",
    "bankCode": "MY",
    "branchCode": "YKL",
    "SWIFT Code": "BMMBMYKL",
    "Bank Name": "BANK MUAMALAT MALAYSIA BERHAD (6175-W)",
    "Address": "FLOOR 25, MENARA BUMIPUTRA, JALAN MELAKA",
    "City": "KUALA LUMPUR",
    "Branch": "",
    "Postcode": "50100",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "BMMB",
    "bankCode": "MY",
    "branchCode": "TFD",
    "SWIFT Code": "BMMBMYKLTFD",
    "Bank Name": "BANK MUAMALAT MALAYSIA BERHAD (6175-W)",
    "Address": "FLOOR 12, MENARA BUMIPUTRA, JALAN MELAKA",
    "City": "KUALA LUMPUR",
    "Branch": "TRADE FINANCE",
    "Postcode": "50100",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "BNMA",
    "bankCode": "MY",
    "branchCode": "YK3",
    "SWIFT Code": "BNMAMYK3",
    "Bank Name": "BANK NEGARA MALAYSIA",
    "Address": "JALAN DATO ONN",
    "City": "KUALA LUMPUR",
    "Branch": "",
    "Postcode": "50480",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "BNMA",
    "bankCode": "MY",
    "branchCode": "Y2K",
    "SWIFT Code": "BNMAMY2K",
    "Bank Name": "BANK NEGARA MALAYSIA",
    "Address": "BUKIT KEWANGAN, 1, JALAN DATO ONN",
    "City": "KUALA LUMPUR",
    "Branch": "",
    "Postcode": "50480",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "BNMA",
    "bankCode": "MY",
    "branchCode": "YKL",
    "SWIFT Code": "BNMAMYKL",
    "Bank Name": "BANK NEGARA MALAYSIA",
    "Address": "BANK NEGARA MALAYSIA BUILDING, JALAN DATO' ONN",
    "City": "KUALA LUMPUR",
    "Branch": "HEAD OFFICE",
    "Postcode": "50480",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "BOFA",
    "bankCode": "MY",
    "branchCode": "GRC",
    "SWIFT Code": "BOFAMY2XGRC",
    "Bank Name": "BANK OF AMERICA, MALAYSIA BERHAD",
    "Address": "",
    "City": "KUALA LUMPUR",
    "Branch": "",
    "Postcode": "50000",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "BOFA",
    "bankCode": "MY",
    "branchCode": "Y2X",
    "SWIFT Code": "BOFAMY2X",
    "Bank Name": "BANK OF AMERICA, MALAYSIA BERHAD",
    "Address": "WISMA GOLDHILL, 67, JALAN RAJA CHULAN",
    "City": "KUALA LUMPUR",
    "Branch": "",
    "Postcode": "50200",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "BOFA",
    "bankCode": "MY",
    "branchCode": "LMY",
    "SWIFT Code": "BOFAMY2XLMY",
    "Bank Name": "BANK OF AMERICA, MALAYSIA BERHAD",
    "Address": "",
    "City": "KUALA LUMPUR",
    "Branch": "",
    "Postcode": "50000",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "BOFA",
    "bankCode": "MY",
    "branchCode": "LBN",
    "SWIFT Code": "BOFAMY2XLBN",
    "Bank Name": "BANK OF AMERICA, MALAYSIA BERHAD",
    "Address": "FLOOR 10, MAIN OFFICE TOWER, FINANCIAL PARK COMPLEX",
    "City": "LABUAN",
    "Branch": "",
    "Postcode": "87000",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "BKCH",
    "bankCode": "MY",
    "branchCode": "YKL",
    "SWIFT Code": "BKCHMYKL",
    "Bank Name": "BANK OF CHINA (MALAYSIA) BERHAD",
    "Address": "MEZZANINE, FLOOR 0, PLAZA OSK, 25, JALAN AMPANG",
    "City": "KUALA LUMPUR",
    "Branch": "",
    "Postcode": "50450",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "BKCH",
    "bankCode": "MY",
    "branchCode": "CLR",
    "SWIFT Code": "BKCHMYKLCLR",
    "Bank Name": "BANK OF CHINA (MALAYSIA) BERHAD",
    "Address": "MEZZANINE, FLOOR 4TH, PLAZA OSK, 25, JALAN AMPANG",
    "City": "KUALA LUMPUR",
    "Branch": "BANK OF CHINA MALAYSIA RMB CLEARING CENTER",
    "Postcode": "50450",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "AGOB",
    "bankCode": "MY",
    "branchCode": "YKL",
    "SWIFT Code": "AGOBMYKL",
    "Bank Name": "BANK PERTANIAN MALAYSIA BERHAD-AGROBANK",
    "Address": "MENARA AGROBANK, 1, LEBOH PASAR BESAR",
    "City": "KUALA LUMPUR",
    "Branch": "",
    "Postcode": "50726",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "BNPA",
    "bankCode": "MY",
    "branchCode": "YKA",
    "SWIFT Code": "BNPAMYKA",
    "Bank Name": "BNP PARIBAS",
    "Address": "FLOOR 90, FINANCIAL PARK, JALAN MERDEKA",
    "City": "LABUAN",
    "Branch": "",
    "Postcode": "87000",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "BNPA",
    "bankCode": "MY",
    "branchCode": "YKL",
    "SWIFT Code": "BNPAMYKL",
    "Bank Name": "BNP PARIBAS MALAYSIA BERHAD",
    "Address": "FLOOR 48A, THE INTERMARK, VISTA, TOWER 182, JALAN TUN RAZAK",
    "City": "KUALA LUMPUR",
    "Branch": "",
    "Postcode": "50400",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "BNPA",
    "bankCode": "MY",
    "branchCode": "SPI",
    "SWIFT Code": "BNPAMYKLSPI",
    "Bank Name": "BNP PARIBAS MALAYSIA BERHAD",
    "Address": "FLOOR 48A, THE INTERMARK, VISTA, TOWER JALAN TUN RAZAK",
    "City": "KUALA LUMPUR",
    "Branch": "BNPPM ISLAMIC BANKING WINDOW",
    "Postcode": "50400",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "BOBE",
    "bankCode": "MY",
    "branchCode": "YK2",
    "SWIFT Code": "BOBEMYK2",
    "Bank Name": "BOOST BANK BERHAD",
    "Address": "FLOOR 26, AXIATA TOWER, 9 5, JALAN STESEN SENTRAL",
    "City": "KUALA LUMPUR",
    "Branch": "",
    "Postcode": "50470",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "CAGA",
    "bankCode": "MY",
    "branchCode": "YKL",
    "SWIFT Code": "CAGAMYKL",
    "Bank Name": "CAGAMAS BERHAD",
    "Address": "FLOOR 19, TOWER 3 , LINGKARAN SYED, PUTRA,MENARA MAYBANK THE GARDENS, NORTH, MID VALLEY CITY",
    "City": "KUALA LUMPUR",
    "Branch": "",
    "Postcode": "50050",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "PCBC",
    "bankCode": "MY",
    "branchCode": "YKL",
    "SWIFT Code": "PCBCMYKL",
    "Bank Name": "CHINA CONSTRUCTION BANK (MALAYSIA) BERHAD",
    "Address": "WISMA SELANGOR DREDGING, 142A, JALAN AMPANG",
    "City": "KUALA LUMPUR",
    "Branch": "",
    "Postcode": "50450",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "PCBC",
    "bankCode": "MY",
    "branchCode": "Y22",
    "SWIFT Code": "PCBCMY22",
    "Bank Name": "CHINA CONSTRUCTION BANK CORPORATION LABUAN BRANCH",
    "Address": "MAIN OFFICE FLOOR 13, FINANCIAL, PARK COMPLEX LABUAN JALAN MERDEKA",
    "City": "LABUAN",
    "Branch": "",
    "Postcode": "87000",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "RINT",
    "bankCode": "MY",
    "branchCode": "Y22",
    "SWIFT Code": "RINTMY22",
    "Bank Name": "CIB",
    "Address": "LOT 7616, KENSINGTON GARDENS, NO. U1317, JALAN JUMIDAR BUYONG",
    "City": "LABUAN",
    "Branch": "",
    "Postcode": "87000",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "CIBB",
    "bankCode": "MY",
    "branchCode": "YKA",
    "SWIFT Code": "CIBBMYKA",
    "Bank Name": "CIMB BANK (L) LIMITED",
    "Address": "FINANCIAL PARK, JALAN MERDEKA",
    "City": "LABUAN",
    "Branch": "",
    "Postcode": "87000",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "CIBB",
    "bankCode": "MY",
    "branchCode": "YKL",
    "SWIFT Code": "CIBBMYKL",
    "Bank Name": "CIMB BANK BERHAD",
    "Address": "FLOOR 13, MENARA CIMB, KL SENTRAL, 2, JALAN STESEN SENTRAL",
    "City": "KUALA LUMPUR",
    "Branch": "",
    "Postcode": "50470",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "CIBB",
    "bankCode": "MY",
    "branchCode": "SBL",
    "SWIFT Code": "CIBBMYKLSBL",
    "Bank Name": "CIMB BANK BERHAD",
    "Address": "",
    "City": "KUALA LUMPUR",
    "Branch": "SECURITIES BORROWING AND LENDING",
    "Postcode": "50000",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "CIBB",
    "bankCode": "MY",
    "branchCode": "Y2L",
    "SWIFT Code": "CIBBMY2L",
    "Bank Name": "CIMB BANK BERHAD, LABUAN OFFSHORE BRANCH",
    "Address": "FLOOR 14 A, MAIN OFFICE TOWER, FINANCIAL PARK LABUAN, JLN MERDEKA",
    "City": "LABUAN",
    "Branch": "",
    "Postcode": "87000",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "COIM",
    "bankCode": "MY",
    "branchCode": "YKL",
    "SWIFT Code": "COIMMYKL",
    "Bank Name": "CIMB INVESTMENT BANK BERHAD",
    "Address": "FLOOR 17, MENARA CIMB, JALAN STESEN SENTRAL 2, KL SENTRAL",
    "City": "KUALA LUMPUR",
    "Branch": "",
    "Postcode": "50470",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "CTBB",
    "bankCode": "MY",
    "branchCode": "YKL",
    "SWIFT Code": "CTBBMYKL",
    "Bank Name": "CIMB ISLAMIC BANK BERHAD",
    "Address": "FLOOR 17, MENARA CIMB, JALAN STESEN SENTRAL 2, KL SENTRAL",
    "City": "KUALA LUMPUR",
    "Branch": "",
    "Postcode": "50470",
    "Country": "Malaysia",
    "Connection": "Active"
  },
  {
    "countryCode": "CANH",
    "bankCode": "MY",
    "branchCode": "YKL",
    "SWIFT Code": "CANHMYKL",
    "Bank Name": "CIMB-PRINCIPAL ASSET MANAGEMENT BERHAD",
    "Address": "FLOOR 5, BANGUNAN CIMB, JALAN SEMANTAN",
    "City": "KUALA LUMPUR",
    "Branch": "",
    "Postcode": "50490",
    "Country": "Malaysia",
    "Connection": "Active"
  }
]
module.exports = malaysia
