const malawi = [
  {
    "countryCode": "CDHI",
    "bankCode": "MW",
    "branchCode": "WMW",
    "SWIFT Code": "CDHIMWMW",
    "Bank Name": "CDH INVESTMENT BANK (CDHIB)",
    "Address": "CDH HOUSE, 5 INDEPENDENCE DRIVE",
    "City": "BLANTYRE",
    "Branch": "",
    "Postcode": "",
    "Country": "Malawi",
    "Connection": "Active"
  },
  {
    "countryCode": "MBBC",
    "bankCode": "MW",
    "branchCode": "WMW",
    "SWIFT Code": "MBBCMWMW",
    "Bank Name": "CENTENARY BANK LIMITED",
    "Address": "EKISTICS HOUSE",
    "City": "LILONGWE",
    "Branch": "",
    "Postcode": "",
    "Country": "Malawi",
    "Connection": "Active"
  },
  {},
  {
    "countryCode": "FDHF",
    "bankCode": "MW",
    "branchCode": "WMW",
    "SWIFT Code": "FDHFMWMW",
    "Bank Name": "FDH BANK PLC",
    "Address": "UMOYO HOUSE, 8 VICTORIA AVENUE NORTH",
    "City": "BLANTYRE",
    "Branch": "",
    "Postcode": "",
    "Country": "Malawi",
    "Connection": "Active"
  },
  {
    "countryCode": "FRCG",
    "bankCode": "MW",
    "branchCode": "WMW",
    "SWIFT Code": "FRCGMWMW",
    "Bank Name": "FIRST CAPITAL BANK PLC., MALAWI",
    "Address": "FLOOR 1, LIVINGSTONE TOWERS, GLYN JONES ROAD",
    "City": "BLANTYRE",
    "Branch": "",
    "Postcode": "",
    "Country": "Malawi",
    "Connection": "Active"
  },
  {
    "countryCode": "FDHD",
    "bankCode": "MW",
    "branchCode": "WMW",
    "SWIFT Code": "FDHDMWMW",
    "Bank Name": "FIRST DISCOUNT HOUSE LIMITED",
    "Address": "8 VICTORIA AVENUE",
    "City": "BLANTYRE",
    "Branch": "",
    "Postcode": "",
    "Country": "Malawi",
    "Connection": "Active"
  },
  {
    "countryCode": "NFBM",
    "bankCode": "MW",
    "branchCode": "WMW",
    "SWIFT Code": "NFBMMWMW",
    "Bank Name": "MYBUCKS BANKING CORPORATION LIMITED",
    "Address": "EKISTICS HSE, CON DR CITY CTR",
    "City": "LILONGWE",
    "Branch": "",
    "Postcode": "",
    "Country": "Malawi",
    "Connection": "Active"
  },
  {
    "countryCode": "NBMA",
    "bankCode": "MW",
    "branchCode": "WMW",
    "SWIFT Code": "NBMAMWMW",
    "Bank Name": "NATIONAL BANK OF MALAWI",
    "Address": "NBM TOWERS, 7 HENDERSON STREET",
    "City": "BLANTYRE",
    "Branch": "",
    "Postcode": "",
    "Country": "Malawi",
    "Connection": "Active"
  },
  {
    "countryCode": "NBMA",
    "bankCode": "MW",
    "branchCode": "044",
    "SWIFT Code": "NBMAMWMW044",
    "Bank Name": "NATIONAL BANK OF MALAWI",
    "Address": "",
    "City": "BLANTYRE",
    "Branch": "FINANCIAL MANAGEMENT SERVICES",
    "Postcode": "",
    "Country": "Malawi",
    "Connection": "Active"
  },
  {
    "countryCode": "NBMA",
    "bankCode": "MW",
    "branchCode": "001",
    "SWIFT Code": "NBMAMWMW001",
    "Bank Name": "NATIONAL BANK OF MALAWI",
    "Address": "HENDERSON STREET",
    "City": "BLANTYRE",
    "Branch": "HENDERSON STREET BRANCH",
    "Postcode": "",
    "Country": "Malawi",
    "Connection": "Active"
  },
  {
    "countryCode": "NBMA",
    "bankCode": "MW",
    "branchCode": "002",
    "SWIFT Code": "NBMAMWMW002",
    "Bank Name": "NATIONAL BANK OF MALAWI",
    "Address": "VICTORIA AVENUE",
    "City": "BLANTYRE",
    "Branch": "VICTORIA AVENUE BRANCH",
    "Postcode": "",
    "Country": "Malawi",
    "Connection": "Active"
  },
  {
    "countryCode": "NBMA",
    "bankCode": "MW",
    "branchCode": "045",
    "SWIFT Code": "NBMAMWMW045",
    "Bank Name": "NATIONAL BANK OF MALAWI",
    "Address": "NBM TOWERS, 7 HENDERSON STREET",
    "City": "BLANTYRE",
    "Branch": "WORLDLINK",
    "Postcode": "",
    "Country": "Malawi",
    "Connection": "Active"
  },
  {
    "countryCode": "NBMA",
    "bankCode": "MW",
    "branchCode": "003",
    "SWIFT Code": "NBMAMWMW003",
    "Bank Name": "NATIONAL BANK OF MALAWI",
    "Address": "",
    "City": "CHICHIRI",
    "Branch": "CHICHIRI BRANCH",
    "Postcode": "312225",
    "Country": "Malawi",
    "Connection": "Active"
  },
  {
    "countryCode": "NBMA",
    "bankCode": "MW",
    "branchCode": "007",
    "SWIFT Code": "NBMAMWMW007",
    "Bank Name": "NATIONAL BANK OF MALAWI",
    "Address": "",
    "City": "LILONGWE",
    "Branch": "CAPITAL CITY BRANCH",
    "Postcode": "",
    "Country": "Malawi",
    "Connection": "Active"
  },
  {
    "countryCode": "NBMA",
    "bankCode": "MW",
    "branchCode": "008",
    "SWIFT Code": "NBMAMWMW008",
    "Bank Name": "NATIONAL BANK OF MALAWI",
    "Address": "",
    "City": "LILONGWE",
    "Branch": "LILONGWE BRANCH",
    "Postcode": "",
    "Country": "Malawi",
    "Connection": "Active"
  },
  {
    "countryCode": "NBMA",
    "bankCode": "MW",
    "branchCode": "005",
    "SWIFT Code": "NBMAMWMW005",
    "Bank Name": "NATIONAL BANK OF MALAWI",
    "Address": "CHURCHILL ROAD",
    "City": "LIMBE",
    "Branch": "CHURCHILL ROAD BRANCH",
    "Postcode": "312229",
    "Country": "Malawi",
    "Connection": "Active"
  },
  {
    "countryCode": "NBMA",
    "bankCode": "MW",
    "branchCode": "004",
    "SWIFT Code": "NBMAMWMW004",
    "Bank Name": "NATIONAL BANK OF MALAWI",
    "Address": "CUSTOMS ROAD",
    "City": "LIMBE",
    "Branch": "CUSTOMS ROAD BRANCH",
    "Postcode": "312229",
    "Country": "Malawi",
    "Connection": "Active"
  },
  {
    "countryCode": "NBST",
    "bankCode": "MW",
    "branchCode": "WMW",
    "SWIFT Code": "NBSTMWMW",
    "Bank Name": "NBS BANK PLC",
    "Address": "FLOOR 1, NBS HOUSE JOHNSTONE ROAD, AND CNR CHIPEMBERE HIGHWAY",
    "City": "BLANTYRE",
    "Branch": "",
    "Postcode": "",
    "Country": "Malawi",
    "Connection": "Active"
  },
  {
    "countryCode": "RBMA",
    "bankCode": "MW",
    "branchCode": "MRA",
    "SWIFT Code": "RBMAMWMWMRA",
    "Bank Name": "RESERVE BANK OF MALAWI",
    "Address": "",
    "City": "BLANTYRE",
    "Branch": "",
    "Postcode": "",
    "Country": "Malawi",
    "Connection": "Active"
  },
  {
    "countryCode": "RBMA",
    "bankCode": "MW",
    "branchCode": "WMR",
    "SWIFT Code": "RBMAMWMR",
    "Bank Name": "RESERVE BANK OF MALAWI",
    "Address": "1 CONVENTION DRIVE",
    "City": "LILONGWE",
    "Branch": "",
    "Postcode": "",
    "Country": "Malawi",
    "Connection": "Active"
  },
  {
    "countryCode": "RBMA",
    "bankCode": "MW",
    "branchCode": "MOF",
    "SWIFT Code": "RBMAMWMWMOF",
    "Bank Name": "RESERVE BANK OF MALAWI",
    "Address": "",
    "City": "LILONGWE",
    "Branch": "",
    "Postcode": "",
    "Country": "Malawi",
    "Connection": "Active"
  },
  {
    "countryCode": "RBMA",
    "bankCode": "MW",
    "branchCode": "WMW",
    "SWIFT Code": "RBMAMWMW",
    "Bank Name": "RESERVE BANK OF MALAWI",
    "Address": "CONVENTION DRIVE",
    "City": "LILONGWE",
    "Branch": "",
    "Postcode": "",
    "Country": "Malawi",
    "Connection": "Active"
  },
  {
    "countryCode": "RBMA",
    "bankCode": "MW",
    "branchCode": "ADV",
    "SWIFT Code": "RBMAMWMWADV",
    "Bank Name": "RESERVE BANK OF MALAWI",
    "Address": "CONVENTION DRIVE",
    "City": "LILONGWE",
    "Branch": "MALAWI GOVERNMENT ADVANCES PAYMENTS",
    "Postcode": "",
    "Country": "Malawi",
    "Connection": "Active"
  },
  {
    "countryCode": "RBMA",
    "bankCode": "MW",
    "branchCode": "COM",
    "SWIFT Code": "RBMAMWMWCOM",
    "Bank Name": "RESERVE BANK OF MALAWI",
    "Address": "CONVENTION DRIVE",
    "City": "LILONGWE",
    "Branch": "MALAWI GOVERNMENT COMPENSATION AND LOSSES PAYMENTS",
    "Postcode": "",
    "Country": "Malawi",
    "Connection": "Active"
  },
  {},
  {
    "countryCode": "RBMA",
    "bankCode": "MW",
    "branchCode": "DVT",
    "SWIFT Code": "RBMAMWMWDVT",
    "Bank Name": "RESERVE BANK OF MALAWI",
    "Address": "CONVENTION DRIVE",
    "City": "LILONGWE",
    "Branch": "MALAWI GOVERNMENT DEVELOPMENT PAYMENTS",
    "Postcode": "",
    "Country": "Malawi",
    "Connection": "Active"
  },
  {
    "countryCode": "RBMA",
    "bankCode": "MW",
    "branchCode": "DEV",
    "SWIFT Code": "RBMAMWMWDEV",
    "Bank Name": "RESERVE BANK OF MALAWI",
    "Address": "CONVENTION DRIVE",
    "City": "LILONGWE",
    "Branch": "MALAWI GOVERNMENT DEVELOPMENT PAYMENTS",
    "Postcode": "",
    "Country": "Malawi",
    "Connection": "Active"
  },
  {
    "countryCode": "RBMA",
    "bankCode": "MW",
    "branchCode": "MIS",
    "SWIFT Code": "RBMAMWMWMIS",
    "Bank Name": "RESERVE BANK OF MALAWI",
    "Address": "CONVENTION DRIVE",
    "City": "LILONGWE",
    "Branch": "MALAWI GOVERNMENT MISCELLEANEOUS, COMPENSATIONS AND OTHER PAYMENTS",
    "Postcode": "",
    "Country": "Malawi",
    "Connection": "Active"
  },
  {
    "countryCode": "RBMA",
    "bankCode": "MW",
    "branchCode": "ORT",
    "SWIFT Code": "RBMAMWMWORT",
    "Bank Name": "RESERVE BANK OF MALAWI",
    "Address": "CONVENTION DRIVE",
    "City": "LILONGWE",
    "Branch": "MALAWI GOVERNMENT ORT PAYMENTS",
    "Postcode": "",
    "Country": "Malawi",
    "Connection": "Active"
  },
  {
    "countryCode": "RBMA",
    "bankCode": "MW",
    "branchCode": "PEN",
    "SWIFT Code": "RBMAMWMWPEN",
    "Bank Name": "RESERVE BANK OF MALAWI",
    "Address": "CONVENTION DRIVE",
    "City": "LILONGWE",
    "Branch": "MALAWI GOVERNMENT PENSION PAYMENTS",
    "Postcode": "",
    "Country": "Malawi",
    "Connection": "Active"
  },
  {
    "countryCode": "RBMA",
    "bankCode": "MW",
    "branchCode": "SAL",
    "SWIFT Code": "RBMAMWMWSAL",
    "Bank Name": "RESERVE BANK OF MALAWI",
    "Address": "CONVENTION DRIVE",
    "City": "LILONGWE",
    "Branch": "MALAWI GOVERNMENT SALARIES PAYMENTS",
    "Postcode": "",
    "Country": "Malawi",
    "Connection": "Active"
  },
  {
    "countryCode": "SBIC",
    "bankCode": "MW",
    "branchCode": "WMX",
    "SWIFT Code": "SBICMWMX",
    "Bank Name": "STANDARD BANK PLC",
    "Address": "STANDARD BANK CENTRE, AFRICA UNITY AVENUE",
    "City": "LILONGWE",
    "Branch": "",
    "Postcode": "",
    "Country": "Malawi",
    "Connection": "Active"
  }
]
module.exports = malawi
