const maldives = [
  {
    "countryCode": "BCEY",
    "bankCode": "MV",
    "branchCode": "VMV",
    "SWIFT Code": "BCEYMVMV",
    "Bank Name": "BANK OF CEYLON",
    "Address": "AAGE, 12 BODUTHAKURUFAANU MAGU, HENVEIRU",
    "City": "MALE",
    "Branch": "",
    "Postcode": "20094",
    "Country": "Maldives",
    "Connection": "Active"
  },
  {
    "countryCode": "MALB",
    "bankCode": "MV",
    "branchCode": "VMV",
    "SWIFT Code": "MALBMVMV",
    "Bank Name": "BANK OF MALDIVES PLC.",
    "Address": "BML BUILDING, 11 BODUTHAKURUFAANU MAGU",
    "City": "MALE",
    "Branch": "",
    "Postcode": "20094",
    "Country": "Maldives",
    "Connection": "Active"
  },
  {
    "countryCode": "CBMV",
    "bankCode": "MV",
    "branchCode": "VMV",
    "SWIFT Code": "CBMVMVMV",
    "Bank Name": "COMMERCIAL BANK OF MALDIVES PRIVATE LIMITED",
    "Address": "H. GADHAMOO, 2 BODUTHAKURUFAANU MAGU",
    "City": "MALE",
    "Branch": "",
    "Postcode": "20003",
    "Country": "Maldives",
    "Connection": "Active"
  },
  {
    "countryCode": "HABB",
    "bankCode": "MV",
    "branchCode": "VMV",
    "SWIFT Code": "HABBMVMV",
    "Bank Name": "HABIB BANK LIMITED",
    "Address": "H THUNIYA BUILDING, FLOOR 1, 1-6 BODUTHAKURUFAANU MAGU",
    "City": "MALE",
    "Branch": "",
    "Postcode": "20003",
    "Country": "Maldives",
    "Connection": "Active"
  },
  {
    "countryCode": "HSBC",
    "bankCode": "MV",
    "branchCode": "VMV",
    "SWIFT Code": "HSBCMVMV",
    "Bank Name": "HONGKONG AND SHANGHAI BANKING CORPORATION LIMITED, THE",
    "Address": "H.ZONEYRIA BUILDING, FLOOR 9, BODUTHAKURUFAANU MAGU",
    "City": "MALE",
    "Branch": "",
    "Postcode": "20057",
    "Country": "Maldives",
    "Connection": "Active"
  },
  {},
  {
    "countryCode": "MMAU",
    "bankCode": "MV",
    "branchCode": "VMV",
    "SWIFT Code": "MMAUMVMV",
    "Bank Name": "MALDIVES MONETARY AUTHORITY",
    "Address": "MALDIVES MONETARY AUTHORITY, BODUTHAKURUFAANU MAGU",
    "City": "MALE",
    "Branch": "",
    "Postcode": "20182",
    "Country": "Maldives",
    "Connection": "Active"
  },
  {
    "countryCode": "SBIN",
    "bankCode": "MV",
    "branchCode": "VMV",
    "SWIFT Code": "SBINMVMV",
    "Bank Name": "STATE BANK OF INDIA",
    "Address": "H. SUNLEET, BODUTHAKURUFAANU MAGU",
    "City": "MALE",
    "Branch": "",
    "Postcode": "20003",
    "Country": "Maldives",
    "Connection": "Active"
  },
  {
    "countryCode": "MCBL",
    "bankCode": "MV",
    "branchCode": "VMV",
    "SWIFT Code": "MCBLMVMV",
    "Bank Name": "THE MAURITIUS COMMERCIAL BANK LIMITED",
    "Address": "H. SIFA BUILDING, FLOOR GF, BODUTHAKURUFAANU MAGU",
    "City": "MALE",
    "Branch": "",
    "Postcode": "20003",
    "Country": "Maldives",
    "Connection": "Active"
  }
]
module.exports = maldives
