const mali = [
  {
    "countryCode": "AFRI",
    "bankCode": "ML",
    "branchCode": "LBA",
    "SWIFT Code": "AFRIMLBA",
    "Bank Name": "BANK OF AFRICA - MALI",
    "Address": "AVENUE DE LA MARNE 418",
    "City": "BAMAKO",
    "Branch": "",
    "Postcode": "",
    "Country": "Mali",
    "Connection": "Active"
  },
  {
    "countryCode": "AFRI",
    "bankCode": "ML",
    "branchCode": "022",
    "SWIFT Code": "AFRIMLBA022",
    "Bank Name": "BANK OF AFRICA - MALI",
    "Address": "AVENUE DE LA MARNE 418",
    "City": "BAMAKO",
    "Branch": "",
    "Postcode": "",
    "Country": "Mali",
    "Connection": "Active"
  },
  {
    "countryCode": "BCAO",
    "bankCode": "ML",
    "branchCode": "MOP",
    "SWIFT Code": "BCAOMLBAMOP",
    "Bank Name": "BANQUE (MALI) CENTRALE DES ETATS DE L'AFRIQUE ET DE L'OUEST",
    "Address": "",
    "City": "MOPTI",
    "Branch": "MOPTI BRANCH",
    "Postcode": "",
    "Country": "Mali",
    "Connection": "Active"
  },
  {
    "countryCode": "ATML",
    "bankCode": "ML",
    "branchCode": "LBA",
    "SWIFT Code": "ATMLMLBA",
    "Bank Name": "BANQUE ATLANTIQUE MALI",
    "Address": "IMMEUBLE BALDE, AVENUE CHEICK ZAHED, ROUTE LAFIABOUGOU",
    "City": "BAMAKO",
    "Branch": "",
    "Postcode": "",
    "Country": "Mali",
    "Connection": "Active"
  },
  {
    "countryCode": "BCAO",
    "bankCode": "ML",
    "branchCode": "LBA",
    "SWIFT Code": "BCAOMLBA",
    "Bank Name": "BANQUE CENTRALE DES ETATS DE L'AFRIQUE DE L'OUEST",
    "Address": "AVENUE MOUSSA TRAVELE 94",
    "City": "BAMAKO",
    "Branch": "",
    "Postcode": "",
    "Country": "Mali",
    "Connection": "Active"
  },
  {
    "countryCode": "BCAO",
    "bankCode": "ML",
    "branchCode": "SIK",
    "SWIFT Code": "BCAOMLBASIK",
    "Bank Name": "BANQUE CENTRALE DES ETATS DE L'AFRIQUE DE L'OUEST",
    "Address": "",
    "City": "SIKASSO",
    "Branch": "SIKASSO BRANCH",
    "Postcode": "",
    "Country": "Mali",
    "Connection": "Active"
  },
  {
    "countryCode": "ALIM",
    "bankCode": "ML",
    "branchCode": "LBA",
    "SWIFT Code": "ALIMMLBA",
    "Bank Name": "BANQUE COMMERCIALE DU SAHEL SA",
    "Address": "RUE BOZOLA 127",
    "City": "BAMAKO",
    "Branch": "",
    "Postcode": "",
    "Country": "Mali",
    "Connection": "Active"
  },
  {
    "countryCode": "BDMA",
    "bankCode": "ML",
    "branchCode": "LBA",
    "SWIFT Code": "BDMAMLBA",
    "Bank Name": "BANQUE DE DEVELOPPEMENT DU MALI - S.A.",
    "Address": "SIEGE CENTRAL, AVENUE MODIBA KEITA PORTE 525",
    "City": "BAMAKO",
    "Branch": "",
    "Postcode": "",
    "Country": "Mali",
    "Connection": "Active"
  },
  {
    "countryCode": "BIPM",
    "bankCode": "ML",
    "branchCode": "LBA",
    "SWIFT Code": "BIPMMLBA",
    "Bank Name": "BANQUE INTERNATIONALE POUR LE MALI SA.",
    "Address": "BOULEVARD DE L'INDEPENDENCE, BOLIBANA",
    "City": "BAMAKO",
    "Branch": "",
    "Postcode": "",
    "Country": "Mali",
    "Connection": "Active"
  },
  {
    "countryCode": "BMSM",
    "bankCode": "ML",
    "branchCode": "LBA",
    "SWIFT Code": "BMSMMLBA",
    "Bank Name": "BANQUE MALIENNE DE SOLIDARITE",
    "Address": "L'IMMEUBLE BMS- SA HAMDALLAYE, AVENUE DE L'UNION AFRICAINE",
    "City": "BAMAKO",
    "Branch": "",
    "Postcode": "2000",
    "Country": "Mali",
    "Connection": "Active"
  },
  {
    "countryCode": "BNAD",
    "bankCode": "ML",
    "branchCode": "LBA",
    "SWIFT Code": "BNADMLBA",
    "Bank Name": "BANQUE NATIONALE DE DEVELOPPEMENT AGRICOLE (BNDA)",
    "Address": "IMMEUBLE CAA, QUARTIER DU FLEURE",
    "City": "BAMAKO",
    "Branch": "",
    "Postcode": "",
    "Country": "Mali",
    "Connection": "Active"
  },
  {
    "countryCode": "BSAH",
    "bankCode": "ML",
    "branchCode": "LBA",
    "SWIFT Code": "BSAHMLBA",
    "Bank Name": "BANQUE SAHELO-SAHARIENNE POUR L'INVESTISSEMENT ET LE COMMERCE (MALI) S.A.",
    "Address": "QUARTIER DU FLEUVE",
    "City": "BAMAKO",
    "Branch": "",
    "Postcode": "",
    "Country": "Mali",
    "Connection": "Active"
  },
  {
    "countryCode": "COLI",
    "bankCode": "ML",
    "branchCode": "LBA",
    "SWIFT Code": "COLIMLBA",
    "Bank Name": "BCI-MALI",
    "Address": "IMMEUBLE BALDE, AVENUE CHEICK ZAYED, HAMDALLAYE",
    "City": "BAMAKO",
    "Branch": "",
    "Postcode": "4373",
    "Country": "Mali",
    "Connection": "Active"
  },
  {
    "countryCode": "BICI",
    "bankCode": "ML",
    "branchCode": "LBA",
    "SWIFT Code": "BICIMLBA",
    "Bank Name": "BICIM",
    "Address": "ABDELAZIZ BOUTEFLIKA",
    "City": "BAMAKO",
    "Branch": "",
    "Postcode": "",
    "Country": "Mali",
    "Connection": "Active"
  },
  {
    "countryCode": "CORI",
    "bankCode": "ML",
    "branchCode": "LBA",
    "SWIFT Code": "CORIMLBA",
    "Bank Name": "CORIS BANK INTERNATIONAL",
    "Address": "BOULEVARD DU 22 OCTOBRE 22",
    "City": "BAMAKO",
    "Branch": "",
    "Postcode": "",
    "Country": "Mali",
    "Connection": "Active"
  },
  {},
  {
    "countryCode": "ORBK",
    "bankCode": "ML",
    "branchCode": "LBA",
    "SWIFT Code": "ORBKMLBA",
    "Bank Name": "ORABANK MALI",
    "Address": "AV. DU MALI, HAMDALLAYE ACI 2000",
    "City": "BAMAKO",
    "Branch": "",
    "Postcode": "",
    "Country": "Mali",
    "Connection": "Active"
  },
  {
    "countryCode": "UNAF",
    "bankCode": "ML",
    "branchCode": "LBA",
    "SWIFT Code": "UNAFMLBA",
    "Bank Name": "UNITED BANK FOR AFRICA MALI SA",
    "Address": "AVENUE DE LA PAIX 360, HAMDALLAYE ACI 2000",
    "City": "BAMAKO",
    "Branch": "",
    "Postcode": "",
    "Country": "Mali",
    "Connection": "Active"
  }
]
module.exports = mali
