const malta = [
  {
    "countryCode": "FEMA",
    "bankCode": "MT",
    "branchCode": "DCA",
    "SWIFT Code": "FEMAMTMADCA",
    "Bank Name": "MULTITUDE BANK P.L.C.",
    "Address": "FLOOR 9, ST BUSINESS CENTRE, 120 THE STRAND",
    "City": "GZIRA",
    "Branch": "TIPS ROUTING FOR SEPA GATEWAY",
    "Postcode": "GZR 1027",
    "Country": "Malta",
    "Connection": "Active"
  },
  {
    "countryCode": "NEXD",
    "bankCode": "MT",
    "branchCode": "TM2",
    "SWIFT Code": "NEXDMTM2",
    "Bank Name": "NEXTMARKETS TRADING LTD",
    "Address": "FLOOR 19, PORTOMASO BUSINESS TOWER",
    "City": "ST. JULIAN'S",
    "Branch": "",
    "Postcode": "STJ 4011",
    "Country": "Malta",
    "Connection": "Active"
  },
  {
    "countryCode": "VOCB",
    "bankCode": "MT",
    "branchCode": "TMT",
    "SWIFT Code": "VOCBMTMT",
    "Bank Name": "NOVUM BANK LTD",
    "Address": "FLOOR 2, THE EMPORIUM, C DE BROCKTORFF STREET",
    "City": "MSIDA",
    "Branch": "",
    "Postcode": "MSD 1421",
    "Country": "Malta",
    "Connection": "Active"
  },
  {
    "countryCode": "CFTE",
    "bankCode": "MT",
    "branchCode": "TM3",
    "SWIFT Code": "CFTEMTM3",
    "Bank Name": "OPENPAYD FINANCIAL SERVICES MALTA LTD",
    "Address": "FLOOR 3, 137 SPINOLA ROAD",
    "City": "ST. JULIAN'S",
    "Branch": "",
    "Postcode": "STJ 3140",
    "Country": "Malta",
    "Connection": "Active"
  },
  {
    "countryCode": "PAPY",
    "bankCode": "MT",
    "branchCode": "TMT",
    "SWIFT Code": "PAPYMTMT",
    "Bank Name": "PAPAYA LTD",
    "Address": "31 SLIEMA ROAD",
    "City": "GZIRA",
    "Branch": "",
    "Postcode": "GZR 1637",
    "Country": "Malta",
    "Connection": "Active"
  },
  {},
  {
    "countryCode": "REVC",
    "bankCode": "MT",
    "branchCode": "TM2",
    "SWIFT Code": "REVCMTM2",
    "Bank Name": "REPLICA SICAV PLC",
    "Address": "FLOOR 1, CENTRAL NORTH BUSINESS, CENTRE SQAQ IL-FAWWARA",
    "City": "SLIEMA",
    "Branch": "",
    "Postcode": "SLM 1670",
    "Country": "Malta",
    "Connection": "Active"
  },
  {
    "countryCode": "RMMN",
    "bankCode": "MT",
    "branchCode": "TM2",
    "SWIFT Code": "RMMNMTM2",
    "Bank Name": "RMB MANAGEMENT LIMITED",
    "Address": "113B PAOLA ROAD",
    "City": "TARXIEN",
    "Branch": "",
    "Postcode": "TXN 1807",
    "Country": "Malta",
    "Connection": "Active"
  },
  {
    "countryCode": "SBMT",
    "bankCode": "MT",
    "branchCode": "TMT",
    "SWIFT Code": "SBMTMTMT",
    "Bank Name": "SPARKASSE BANK MALTA PLC",
    "Address": "TOWNSQUARE, 101 TRIQ IX XATT TA QUI SI SANA",
    "City": "SLIEMA",
    "Branch": "",
    "Postcode": "SLM 3112",
    "Country": "Malta",
    "Connection": "Active"
  },
  {
    "countryCode": "TIMV",
    "bankCode": "MT",
    "branchCode": "TM2",
    "SWIFT Code": "TIMVMTM2",
    "Bank Name": "TIMBERLAND INVEST LIMITED",
    "Address": "ARAGON HOUSE BUSINESS CENTRE, DRAGONARA ROAD",
    "City": "ST. JULIAN'S",
    "Branch": "",
    "Postcode": "STJ 3140",
    "Country": "Malta",
    "Connection": "Active"
  },
  {
    "countryCode": "TPML",
    "bankCode": "MT",
    "branchCode": "TMT",
    "SWIFT Code": "TPMLMTMT",
    "Bank Name": "TRANSACT PAYMENTS MALTA LTD",
    "Address": "FLOOR 1, SOHO STRAND FAWWARA, BUILDING TRIQ I-IMSIDA",
    "City": "GZIRA",
    "Branch": "",
    "Postcode": "GZR 1401",
    "Country": "Malta",
    "Connection": "Active"
  },
  {},
  {
    "countryCode": "TRPE",
    "bankCode": "MT",
    "branchCode": "TMT",
    "SWIFT Code": "TRPEMTMT",
    "Bank Name": "TRUEVO PAYMENTS LTD",
    "Address": "FLOOR 3, THE WATERCOURSE",
    "City": "BIRKIRKARA",
    "Branch": "",
    "Postcode": "CBD 2010",
    "Country": "Malta",
    "Connection": "Active"
  },
  {
    "countryCode": "TRUM",
    "bankCode": "MT",
    "branchCode": "TM2",
    "SWIFT Code": "TRUMMTM2",
    "Bank Name": "TRUMIA LIMITED",
    "Address": "FLOOR 3, QUAD CENTRAL Q3, TRIQ L-ESPLORATURI, ZONE 1, CENTRAL BUSINESS DISTRICT",
    "City": "BIRKIRKARA",
    "Branch": "",
    "Postcode": "CBD 1040",
    "Country": "Malta",
    "Connection": "Active"
  },
  {},
  {
    "countryCode": "VPAY",
    "bankCode": "MT",
    "branchCode": "TM2",
    "SWIFT Code": "VPAYMTM2",
    "Bank Name": "VIVA PAYMENT SERVICES SINGLE MEMBER S.A. MALTA BRANCH",
    "Address": "FLOOR 5, OHEA BUILDINGS, 6 SIR WILLIAM REID STREET",
    "City": "GZIRA",
    "Branch": "",
    "Postcode": "GZR 1362",
    "Country": "Malta",
    "Connection": "Active"
  },
  {
    "countryCode": "COPX",
    "bankCode": "MT",
    "branchCode": "TMT",
    "SWIFT Code": "COPXMTMT",
    "Bank Name": "W AND J COPPINI AND CO",
    "Address": "144 TOWER ROAD",
    "City": "SLIEMA",
    "Branch": "",
    "Postcode": "SLM 1604",
    "Country": "Malta",
    "Connection": "Active"
  },
  {
    "countryCode": "WCOR",
    "bankCode": "MT",
    "branchCode": "TMQ",
    "SWIFT Code": "WCORMTMQ",
    "Bank Name": "WEBCOR INVESTMENTS LTD",
    "Address": "FJVA BUSINESS CENTRE, B2 INDUSTRY STREET, ZONE 5, CENTRAL BUSINESS DISTRICT",
    "City": "QORMI",
    "Branch": "",
    "Postcode": "CBD 5030",
    "Country": "Malta",
    "Connection": "Active"
  },
  {
    "countryCode": "ITHO",
    "bankCode": "MT",
    "branchCode": "TM2",
    "SWIFT Code": "ITHOMTM2",
    "Bank Name": "A2A INTERNATIONAL HOLDINGS LIMITED",
    "Address": "VILLA MALITAH, MEDITERRANEAN STREET",
    "City": "ST. JULIAN'S",
    "Branch": "",
    "Postcode": "STJ 3155",
    "Country": "Malta",
    "Connection": "Active"
  },
  {
    "countryCode": "AKBK",
    "bankCode": "MT",
    "branchCode": "TMT",
    "SWIFT Code": "AKBKMTMT",
    "Bank Name": "AKBANK T.A.S. (MALTA BRANCH)",
    "Address": "FLOOR 6, PORTOMASO BUSINESS TOWER, 01 PORTOMASO PTM",
    "City": "ST. JULIAN'S",
    "Branch": "",
    "Postcode": "STJ 4011",
    "Country": "Malta",
    "Connection": "Active"
  },
  {
    "countryCode": "APAH",
    "bankCode": "MT",
    "branchCode": "TMT",
    "SWIFT Code": "APAHMTMT",
    "Bank Name": "ALPHA FX EUROPE LIMITED",
    "Address": "171 OLD BAKERY STREET",
    "City": "VALLETTA",
    "Branch": "",
    "Postcode": "VLT 1455",
    "Country": "Malta",
    "Connection": "Active"
  },
  {
    "countryCode": "APAH",
    "bankCode": "MT",
    "branchCode": "TMV",
    "SWIFT Code": "APAHMTMV",
    "Bank Name": "ALPHA FX EUROPE LIMITED",
    "Address": "171 OLD BAKERY STREET",
    "City": "VALLETTA",
    "Branch": "",
    "Postcode": "VLT 1455",
    "Country": "Malta",
    "Connection": "Active"
  },
  {
    "countryCode": "ANFV",
    "bankCode": "MT",
    "branchCode": "TMM",
    "SWIFT Code": "ANFVMTMM",
    "Bank Name": "ANDARIA FINANCIAL SERVICES LIMITED",
    "Address": "FLOOR 2, MELITA COURT GIUSEPPE CALI STREET, C/W TRIQ ABATE RIGORD",
    "City": "TA'XBIEX",
    "Branch": "",
    "Postcode": "XBX 1420",
    "Country": "Malta",
    "Connection": "Active"
  },
  {
    "countryCode": "APSB",
    "bankCode": "MT",
    "branchCode": "TMT",
    "SWIFT Code": "APSBMTMT",
    "Bank Name": "APS BANK PLC.",
    "Address": "APS CENTRE, TOWER STREET",
    "City": "BIRKIRKARA",
    "Branch": "",
    "Postcode": "BKR 4012",
    "Country": "Malta",
    "Connection": "Active"
  },
  {
    "countryCode": "BLLG",
    "bankCode": "MT",
    "branchCode": "TMB",
    "SWIFT Code": "BLLGMTMB",
    "Bank Name": "BALLINGER EU LIMITED",
    "Address": "FLOOR 2, TRIDENT PARK, NOTABILE, GARDENS 7 MDINA ROAD ZONE 2 CENTRAL, BUSINESS DISTRICT",
    "City": "BIRKIRKARA",
    "Branch": "",
    "Postcode": "CBD 2010",
    "Country": "Malta",
    "Connection": "Active"
  },
  {
    "countryCode": "BLLG",
    "bankCode": "MT",
    "branchCode": "TMT",
    "SWIFT Code": "BLLGMTMT",
    "Bank Name": "BALLINGER MARKETS LTD.",
    "Address": "FLOOR 2, TRIDENT PARK NOTABILE G, 7 MDINA ROAD, ZONE 2",
    "City": "BIRKIRKARA",
    "Branch": "",
    "Postcode": "CBD 2010",
    "Country": "Malta",
    "Connection": "Active"
  },
  {
    "countryCode": "VALL",
    "bankCode": "MT",
    "branchCode": "TMT",
    "SWIFT Code": "VALLMTMT",
    "Bank Name": "BANK OF VALLETTA P.L.C.",
    "Address": "BOV CENTRE, TRIQ IL-KANUN, ZONE 4, CENTRAL BUSINESS DISTRICT",
    "City": "SANTA VENERA",
    "Branch": "",
    "Postcode": "CBD 4060",
    "Country": "Malta",
    "Connection": "Active"
  },
  {
    "countryCode": "BNIF",
    "bankCode": "MT",
    "branchCode": "TMT",
    "SWIFT Code": "BNIFMTMT",
    "Bank Name": "BNF BANK PLC (FORMERLY BANIF BANK MALTA)",
    "Address": "FLOOR 2, 203 RUE D'ARGENS",
    "City": "GZIRA",
    "Branch": "",
    "Postcode": "GZR 1368",
    "Country": "Malta",
    "Connection": "Active"
  },
  {
    "countryCode": "MALT",
    "bankCode": "MT",
    "branchCode": "TMT",
    "SWIFT Code": "MALTMTMT",
    "Bank Name": "CENTRAL BANK OF MALTA",
    "Address": "CASTILLE PLACE",
    "City": "VALLETTA",
    "Branch": "",
    "Postcode": "VLT 1063",
    "Country": "Malta",
    "Connection": "Active"
  },
  {
    "countryCode": "MALT",
    "bankCode": "MT",
    "branchCode": "ECM",
    "SWIFT Code": "MALTMTMTECM",
    "Bank Name": "CENTRAL BANK OF MALTA",
    "Address": "CASTILLE PLACE",
    "City": "VALLETTA",
    "Branch": "",
    "Postcode": "",
    "Country": "Malta",
    "Connection": "Active"
  },
  {
    "countryCode": "MALT",
    "bankCode": "MT",
    "branchCode": "GCP",
    "SWIFT Code": "MALTMTMTGCP",
    "Bank Name": "CENTRAL BANK OF MALTA",
    "Address": "",
    "City": "VALLETTA",
    "Branch": "EUREX BRANCH ACCOUNT",
    "Postcode": "",
    "Country": "Malta",
    "Connection": "Active"
  },
  {
    "countryCode": "CITC",
    "bankCode": "MT",
    "branchCode": "TMT",
    "SWIFT Code": "CITCMTMT",
    "Bank Name": "CITCO CUSTODY LIMITED",
    "Address": "LEVEL 2 WEST, MERCURY TOWER, ELIA ZAMMIT STREET",
    "City": "ST. JULIAN'S",
    "Branch": "",
    "Postcode": "STJ 3155",
    "Country": "Malta",
    "Connection": "Active"
  },
  {
    "countryCode": "TGBP",
    "bankCode": "MT",
    "branchCode": "TMT",
    "SWIFT Code": "TGBPMTMT",
    "Bank Name": "CONVERA MALTA FINANCIAL LIMITED",
    "Address": "FLOOR 5, W BUSINESS CENTRE, 1 TRIQ DUN KARM",
    "City": "BIRKIRKARA",
    "Branch": "",
    "Postcode": "BKR 9033",
    "Country": "Malta",
    "Connection": "Active"
  },
  {
    "countryCode": "FBHL",
    "bankCode": "MT",
    "branchCode": "TMT",
    "SWIFT Code": "FBHLMTMT",
    "Bank Name": "CREDIT EUROPE BANK N.V. MALTA BRANCH",
    "Address": "143/2 TOWER ROAD",
    "City": "SLIEMA",
    "Branch": "",
    "Postcode": "SLM 1604",
    "Country": "Malta",
    "Connection": "Active"
  },
  {
    "countryCode": "CRXB",
    "bankCode": "MT",
    "branchCode": "TMT",
    "SWIFT Code": "CRXBMTMT",
    "Bank Name": "CREDORAX BANK LIMITED",
    "Address": "PALAZZO HOMEDES, 80 STRAIT STREET",
    "City": "VALLETTA",
    "Branch": "",
    "Postcode": "VLT 1436",
    "Country": "Malta",
    "Connection": "Active"
  },
  {
    "countryCode": "DIEU",
    "bankCode": "MT",
    "branchCode": "TMT",
    "SWIFT Code": "DIEUMTMT",
    "Bank Name": "DERIV INVESTMENTS (EUROPE) LIMITED",
    "Address": "FLOOR 3, W BUSINESS CENTRE, TRIQ DUN KARM",
    "City": "BIRKIRKARA",
    "Branch": "",
    "Postcode": "BKR 9033",
    "Country": "Malta",
    "Connection": "Active"
  },
  {
    "countryCode": "ECMB",
    "bankCode": "MT",
    "branchCode": "TMT",
    "SWIFT Code": "ECMBMTMT",
    "Bank Name": "ECCM BANK PLC",
    "Address": "THE ADELAIDE, 230-231 TOWER ROAD",
    "City": "SLIEMA",
    "Branch": "",
    "Postcode": "SLM 1601",
    "Country": "Malta",
    "Connection": "Active"
  },
  {
    "countryCode": "EMOE",
    "bankCode": "MT",
    "branchCode": "TM2",
    "SWIFT Code": "EMOEMTM2",
    "Bank Name": "EMONEY PLC",
    "Address": "TRIQ IX XATT TA' XBIEX",
    "City": "MSIDA",
    "Branch": "",
    "Postcode": "MSD 1516",
    "Country": "Malta",
    "Connection": "Active"
  },
  {
    "countryCode": "EMON",
    "bankCode": "MT",
    "branchCode": "TM2",
    "SWIFT Code": "EMONMTM2",
    "Bank Name": "EMONEY PLC",
    "Address": "TRIQ IX XATT TA' XBIEX",
    "City": "MSIDA",
    "Branch": "",
    "Postcode": "MSD 1516",
    "Country": "Malta",
    "Connection": "Active"
  },
  {
    "countryCode": "EMSY",
    "bankCode": "MT",
    "branchCode": "TMT",
    "SWIFT Code": "EMSYMTMT",
    "Bank Name": "EMP SYSTEMS LIMITED",
    "Address": "PARTHENON BUILDING",
    "City": "SLIEMA",
    "Branch": "",
    "Postcode": "SLM 3141",
    "Country": "Malta",
    "Connection": "Active"
  },
  {
    "countryCode": "EDMB",
    "bankCode": "MT",
    "branchCode": "TM2",
    "SWIFT Code": "EDMBMTM2",
    "Bank Name": "EUROPEAN DEPOSITARY BANK SA MALTA BRANCH",
    "Address": "FLOOR 1A, CENTRAL NORTH BUSINESS, CENTRE SQAQ IL-FAWWARA",
    "City": "SLIEMA",
    "Branch": "",
    "Postcode": "SLM 1670",
    "Country": "Malta",
    "Connection": "Active"
  },
  {
    "countryCode": "EVNE",
    "bankCode": "MT",
    "branchCode": "TM2",
    "SWIFT Code": "EVNEMTM2",
    "Bank Name": "EVEREST NETWORK LTD.",
    "Address": "OFFICE 1/1165 , FLOOR G, QUANTUM, HOUSE 75 ABATE RIGORD STREET",
    "City": "TA'XBIEX",
    "Branch": "",
    "Postcode": "XBX 1120",
    "Country": "Malta",
    "Connection": "Active"
  },
  {
    "countryCode": "FCMF",
    "bankCode": "MT",
    "branchCode": "TMT",
    "SWIFT Code": "FCMFMTMT",
    "Bank Name": "FCM BANK LIMITED",
    "Address": "SUITE 3, TOWER BUSINESS CENTRE, TOWER STREET",
    "City": "SWATAR",
    "Branch": "",
    "Postcode": "BKR 4013",
    "Country": "Malta",
    "Connection": "Active"
  },
  {
    "countryCode": "FIMB",
    "bankCode": "MT",
    "branchCode": "TM3",
    "SWIFT Code": "FIMBMTM3",
    "Bank Name": "FIMBANK PLC",
    "Address": "MERCURY TOWER, ELIA ZAMMIT STREET",
    "City": "ST. JULIAN'S",
    "Branch": "",
    "Postcode": "STJ 3153",
    "Country": "Malta",
    "Connection": "Active"
  },
  {
    "countryCode": "PYMX",
    "bankCode": "MT",
    "branchCode": "TMT",
    "SWIFT Code": "PYMXMTMT",
    "Bank Name": "FINANCE INCORPORATED LIMITED",
    "Address": "FLOOR 2, CAPITAL BUSINESS CENTRE,, BLOCK A TRIQ TAZ- ZWEJT",
    "City": "SAN GWANN",
    "Branch": "",
    "Postcode": "SGN 3000",
    "Country": "Malta",
    "Connection": "Active"
  },
  {
    "countryCode": "PYMX",
    "bankCode": "MT",
    "branchCode": "TMA",
    "SWIFT Code": "PYMXMTMA",
    "Bank Name": "FINANCE INCORPORATED LIMITED",
    "Address": "THE PENTHOUSE, TAZ-ZWEJT STREET",
    "City": "SAN GWANN",
    "Branch": "",
    "Postcode": "SGN 3000",
    "Country": "Malta",
    "Connection": "Active"
  },
  {
    "countryCode": "PYMX",
    "bankCode": "MT",
    "branchCode": "MAL",
    "SWIFT Code": "PYMXMTMTMAL",
    "Bank Name": "FINANCE INCORPORATED LIMITED",
    "Address": "BLOCK A, FLOOR 2, CAPITAL BUSINESS, CENTRE TRIQ TAZ- ZWEJT",
    "City": "SAN GWANN",
    "Branch": "",
    "Postcode": "SGN 3000",
    "Country": "Malta",
    "Connection": "Active"
  },
  {
    "countryCode": "FIND",
    "bankCode": "MT",
    "branchCode": "TMT",
    "SWIFT Code": "FINDMTMT",
    "Bank Name": "FINDUCTIVE LTD.",
    "Address": "FLOOR 2, CENTRIS BUSINESS GATEWAY, II 46 TRIQ IS-SALIB TAL-IMRIEHEL, CENTRAL BUSINESS DISTRICT",
    "City": "BIRKIRKARA",
    "Branch": "",
    "Postcode": "CBD 3020",
    "Country": "Malta",
    "Connection": "Active"
  },
  {
    "countryCode": "TGBA",
    "bankCode": "MT",
    "branchCode": "TMT",
    "SWIFT Code": "TGBAMTMT",
    "Bank Name": "GARANTI BANK, MALTA BRANCH",
    "Address": "STRAND TOWERS, 36 THE STRAND",
    "City": "SLIEMA",
    "Branch": "",
    "Postcode": "SLM 1022",
    "Country": "Malta",
    "Connection": "Active"
  },
  {
    "countryCode": "GSES",
    "bankCode": "MT",
    "branchCode": "TMT",
    "SWIFT Code": "GSESMTMT",
    "Bank Name": "GLOBAL SHARES EXECUTION SERVICES LIMITED",
    "Address": "171 OLD BAKERY STREET",
    "City": "VALLETTA",
    "Branch": "",
    "Postcode": "VLT 1455",
    "Country": "Malta",
    "Connection": "Active"
  },
  {
    "countryCode": "MMEB",
    "bankCode": "MT",
    "branchCode": "TMT",
    "SWIFT Code": "MMEBMTMT",
    "Bank Name": "HSBC BANK MALTA P.L.C.",
    "Address": "116 ARCHBISHOP STREET",
    "City": "VALLETTA",
    "Branch": "",
    "Postcode": "VLT 1444",
    "Country": "Malta",
    "Connection": "Active"
  },
  {
    "countryCode": "IIGB",
    "bankCode": "MT",
    "branchCode": "TMT",
    "SWIFT Code": "IIGBMTMT",
    "Bank Name": "IIG BANK (MALTA) LTD",
    "Address": "PORTOMASO BUSINESS TOWER, PORTOMASO",
    "City": "ST. JULIAN'S",
    "Branch": "",
    "Postcode": "STJ 4011",
    "Country": "Malta",
    "Connection": "Active"
  },
  {
    "countryCode": "ICDR",
    "bankCode": "MT",
    "branchCode": "TMT",
    "SWIFT Code": "ICDRMTMT",
    "Bank Name": "INSIGNIA CARDS LIMITED",
    "Address": "FLOOR 4, PALAZZO SPINOLA, 46 ST. CHRISTOPHER STREET",
    "City": "VALLETTA",
    "Branch": "",
    "Postcode": "VLT 1464",
    "Country": "Malta",
    "Connection": "Active"
  },
  {
    "countryCode": "IZOL",
    "bankCode": "MT",
    "branchCode": "TMT",
    "SWIFT Code": "IZOLMTMT",
    "Bank Name": "IZOLA BANK PLC",
    "Address": "53-58 EAST STREET",
    "City": "VALLETTA",
    "Branch": "",
    "Postcode": "VLT 1251",
    "Country": "Malta",
    "Connection": "Active"
  },
  {
    "countryCode": "KGIT",
    "bankCode": "MT",
    "branchCode": "TMT",
    "SWIFT Code": "KGITMTMT",
    "Bank Name": "KAIZEN GAMING INTERNATIONAL LIMITED",
    "Address": "FLAT B8, THE ATRIUM, WEST STREET",
    "City": "MSIDA",
    "Branch": "",
    "Postcode": "MSD 1731",
    "Country": "Malta",
    "Connection": "Active"
  },
  {
    "countryCode": "AGRK",
    "bankCode": "MT",
    "branchCode": "TMT",
    "SWIFT Code": "AGRKMTMT",
    "Bank Name": "LIDION BANK PLC",
    "Address": "FLOOR 1, MALTA INTERNATIONAL, AIRPORT",
    "City": "LUQA",
    "Branch": "",
    "Postcode": "LQA 4000",
    "Country": "Malta",
    "Connection": "Active"
  },
  {
    "countryCode": "LBMA",
    "bankCode": "MT",
    "branchCode": "TMT",
    "SWIFT Code": "LBMAMTMT",
    "Bank Name": "LOMBARD BANK MALTA PLC",
    "Address": "LOMBARD HOUSE, 67 REPUBLIC STREET",
    "City": "VALLETTA",
    "Branch": "",
    "Postcode": "VLT 1117",
    "Country": "Malta",
    "Connection": "Active"
  },
  {
    "countryCode": "XMAL",
    "bankCode": "MT",
    "branchCode": "TMT",
    "SWIFT Code": "XMALMTMT",
    "Bank Name": "MALTA STOCK EXCHANGE",
    "Address": "GARRISON CHAPEL, CASTILE PLACE",
    "City": "VALLETTA",
    "Branch": "",
    "Postcode": "VLT 1063",
    "Country": "Malta",
    "Connection": "Active"
  },
  {
    "countryCode": "MBWM",
    "bankCode": "MT",
    "branchCode": "TMT",
    "SWIFT Code": "MBWMMTMT",
    "Bank Name": "MEDIRECT BANK (MALTA) PLC",
    "Address": "FLOOR 1, THE CENTRE, TIGNE POINT",
    "City": "SLIEMA",
    "Branch": "",
    "Postcode": "TPO 0001",
    "Country": "Malta",
    "Connection": "Active"
  },
  {
    "countryCode": "MBWM",
    "bankCode": "MT",
    "branchCode": "010",
    "SWIFT Code": "MBWMMTMT010",
    "Bank Name": "MEDIRECT BANK (MALTA) PLC",
    "Address": "FLOOR 1, THE CENTRE, TIGNE POINT",
    "City": "SLIEMA",
    "Branch": "MEDIRECT MT TGT 2",
    "Postcode": "TPO 0001",
    "Country": "Malta",
    "Connection": "Active"
  },
  {
    "countryCode": "MFCB",
    "bankCode": "MT",
    "branchCode": "TMS",
    "SWIFT Code": "MFCBMTMS",
    "Bank Name": "MERKANTI BANK LIMITED",
    "Address": "ARAGON HOUSE BUSINESS CENTRE, DRAGONARA ROAD",
    "City": "ST. JULIAN'S",
    "Branch": "",
    "Postcode": "STJ 3203",
    "Country": "Malta",
    "Connection": "Active"
  },
  {
    "countryCode": "MFMA",
    "bankCode": "MT",
    "branchCode": "TM2",
    "SWIFT Code": "MFMAMTM2",
    "Bank Name": "MIFINITY MALTA LIMITED",
    "Address": "FLOOR 3, TOWER BUSINESS CENTRE, TOWER STREET",
    "City": "BIRKIRKARA",
    "Branch": "",
    "Postcode": "BKR 4013",
    "Country": "Malta",
    "Connection": "Active"
  },
  {
    "countryCode": "CCUH",
    "bankCode": "MT",
    "branchCode": "TMT",
    "SWIFT Code": "CCUHMTMT",
    "Bank Name": "MONEYBASE",
    "Address": "FLOOR GF, EWROPA BUSINESS CENTRE, TRIQ DUN KARM",
    "City": "BIRKIRKARA",
    "Branch": "",
    "Postcode": "BKR 9034",
    "Country": "Malta",
    "Connection": "Active"
  },
  {
    "countryCode": "CCUH",
    "bankCode": "MT",
    "branchCode": "MBB",
    "SWIFT Code": "CCUHMTMTMBB",
    "Bank Name": "MONEYBASE",
    "Address": "FLOOR GF, EWROPA BUSINESS CENTRE, TRIQ DUN KARM",
    "City": "BIRKIRKARA",
    "Branch": "",
    "Postcode": "BKR 9034",
    "Country": "Malta",
    "Connection": "Active"
  },
  {
    "countryCode": "MTCC",
    "bankCode": "MT",
    "branchCode": "TMT",
    "SWIFT Code": "MTCCMTMT",
    "Bank Name": "MTACC LIMITED",
    "Address": "ST JULIANS BUSINESS CENTRE, 2 ELIA ZAMMIT STREET",
    "City": "ST. JULIAN'S",
    "Branch": "",
    "Postcode": "STJ 3155",
    "Country": "Malta",
    "Connection": "Active"
  },
  {
    "countryCode": "MTCC",
    "bankCode": "MT",
    "branchCode": "STJ",
    "SWIFT Code": "MTCCMTMTSTJ",
    "Bank Name": "MTACC LIMITED",
    "Address": "ST JULIANS BUSINESS CENTRE, 2 ELIA ZAMMIT STREET",
    "City": "ST. JULIAN'S",
    "Branch": "",
    "Postcode": "STJ 3153",
    "Country": "Malta",
    "Connection": "Active"
  },
  {
    "countryCode": "FEMA",
    "bankCode": "MT",
    "branchCode": "TMA",
    "SWIFT Code": "FEMAMTMA",
    "Bank Name": "MULTITUDE BANK P.L.C.",
    "Address": "FLOOR 9, ST BUSINESS CENTRE, 120 THE STRAND",
    "City": "GZIRA",
    "Branch": "",
    "Postcode": "GZR 1027",
    "Country": "Malta",
    "Connection": "Active"
  },
  {
    "countryCode": "FEMA",
    "bankCode": "MT",
    "branchCode": "TMT",
    "SWIFT Code": "FEMAMTMT",
    "Bank Name": "MULTITUDE BANK P.L.C.",
    "Address": "FLOOR 9, ST BUSINESS CENTRE, 120 THE STRAND",
    "City": "GZIRA",
    "Branch": "",
    "Postcode": "GZR 1027",
    "Country": "Malta",
    "Connection": "Active"
  }
]
module.exports = malta
