const mauritius = [
  {
    "countryCode": "ABCK",
    "bankCode": "MU",
    "branchCode": "UMU",
    "SWIFT Code": "ABCKMUMU",
    "Bank Name": "ABC BANKING CORPORATION LTD",
    "Address": "FLOOR 2, ABC CENTRE, 1 , MILITARY ROAD",
    "City": "PORT LOUIS",
    "Branch": "",
    "Postcode": "11601",
    "Country": "Mauritius",
    "Connection": "Active"
  },
  {
    "countryCode": "BARC",
    "bankCode": "MU",
    "branchCode": "CSU",
    "SWIFT Code": "BARCMUMUCSU",
    "Bank Name": "ABSA BANK (MAURITIUS) LIMITED",
    "Address": "ABSA HOUSE, 68 , WALL STREET",
    "City": "EBENE",
    "Branch": "CUSTODY SERVICES",
    "Postcode": "72201",
    "Country": "Mauritius",
    "Connection": "Active"
  },
  {
    "countryCode": "BARC",
    "bankCode": "MU",
    "branchCode": "MAF",
    "SWIFT Code": "BARCMUMUMAF",
    "Bank Name": "ABSA BANK (MAURITIUS) LIMITED",
    "Address": "",
    "City": "PORT LOUIS",
    "Branch": "M.A.F.E.X BRANCH",
    "Postcode": "",
    "Country": "Mauritius",
    "Connection": "Active"
  },
  {
    "countryCode": "BARC",
    "bankCode": "MU",
    "branchCode": "OBU",
    "SWIFT Code": "BARCMUMUOBU",
    "Bank Name": "ABSA BANK (MAURITIUS) LIMITED",
    "Address": "FLOOR 5, MOORGATE HOUSE, SIR WILLIAM NEWTON STREET",
    "City": "PORT LOUIS",
    "Branch": "MAURITIUS OFFSHORE BANKING UNIT",
    "Postcode": "11328",
    "Country": "Mauritius",
    "Connection": "Active"
  },
  {
    "countryCode": "BARC",
    "bankCode": "MU",
    "branchCode": "UMU",
    "SWIFT Code": "BARCMUMU",
    "Bank Name": "ABSA BANK (MAURITIUS) LIMITED",
    "Address": "ABSA HOUSE, 68 , WALL STREET, EBENE CYBERCITY",
    "City": "Quatre Bornes",
    "Branch": "",
    "Postcode": "72201",
    "Country": "Mauritius",
    "Connection": "Active"
  },
  {
    "countryCode": "AFBL",
    "bankCode": "MU",
    "branchCode": "UMU",
    "SWIFT Code": "AFBLMUMU",
    "Bank Name": "AFRASIA BANK LIMITED",
    "Address": "BOWEN SQUARE, 10 , DR FERRIERE STREET",
    "City": "PORT LOUIS",
    "Branch": "",
    "Postcode": "11328",
    "Country": "Mauritius",
    "Connection": "Active"
  },
  {
    "countryCode": "AFBL",
    "bankCode": "MU",
    "branchCode": "101",
    "SWIFT Code": "AFBLMUMU101",
    "Bank Name": "AFRASIA BANK LIMITED",
    "Address": "EBENE CYBERCITY",
    "City": "Quatre Bornes",
    "Branch": "EBENE BRANCH",
    "Postcode": "",
    "Country": "Mauritius",
    "Connection": "Active"
  },
  {
    "countryCode": "BARB",
    "bankCode": "MU",
    "branchCode": "UMU",
    "SWIFT Code": "BARBMUMU",
    "Bank Name": "BANK OF BARODA",
    "Address": "SIR WILLIAM NEWTON STREET",
    "City": "PORT LOUIS",
    "Branch": "",
    "Postcode": "11328",
    "Country": "Mauritius",
    "Connection": "Active"
  },
  {
    "countryCode": "BARB",
    "bankCode": "MU",
    "branchCode": "OBU",
    "SWIFT Code": "BARBMUMUOBU",
    "Bank Name": "BANK OF BARODA",
    "Address": "FLOOR 4, BANK OF BARODA BUILDING, SIR WILLIAM NEWTON STREET",
    "City": "PORT LOUIS",
    "Branch": "OFFSHORE BANKING UNIT",
    "Postcode": "11328",
    "Country": "Mauritius",
    "Connection": "Active"
  },
  {
    "countryCode": "BKCH",
    "bankCode": "MU",
    "branchCode": "UMU",
    "SWIFT Code": "BKCHMUMU",
    "Bank Name": "BANK OF CHINA (MAURITIUS) LIMITED",
    "Address": "FLOOR 4, DIAS PIER, LE CAUDAN WATERFRONT",
    "City": "PORT LOUIS",
    "Branch": "",
    "Postcode": "11307",
    "Country": "Mauritius",
    "Connection": "Active"
  },
  {
    "countryCode": "COCU",
    "bankCode": "MU",
    "branchCode": "UMU",
    "SWIFT Code": "COCUMUMU",
    "Bank Name": "BANK OF MAURITIUS",
    "Address": "1 , SIR WILLIAM NEWTON STREET",
    "City": "PORT LOUIS",
    "Branch": "",
    "Postcode": "11328",
    "Country": "Mauritius",
    "Connection": "Active"
  },
  {
    "countryCode": "BOMM",
    "bankCode": "MU",
    "branchCode": "UPL",
    "SWIFT Code": "BOMMMUPL",
    "Bank Name": "BANK OF MAURITIUS",
    "Address": "SIR WILLIAM NEWTON STREET",
    "City": "PORT LOUIS",
    "Branch": "",
    "Postcode": "11328",
    "Country": "Mauritius",
    "Connection": "Active"
  },
  {
    "countryCode": "BKON",
    "bankCode": "MU",
    "branchCode": "UMU",
    "SWIFT Code": "BKONMUMU",
    "Bank Name": "BANK ONE LTD",
    "Address": "16 , SIR WILLIAM NEWTON STREET",
    "City": "PORT LOUIS",
    "Branch": "",
    "Postcode": "11328",
    "Country": "Mauritius",
    "Connection": "Active"
  },
  {
    "countryCode": "BPLL",
    "bankCode": "MU",
    "branchCode": "UMU",
    "SWIFT Code": "BPLLMUMU",
    "Bank Name": "BANQUE PATRONUS LIMITEE",
    "Address": "SHENAZ TOWER, 30, LOUIS PASTEUR STREET",
    "City": "PORT LOUIS",
    "Branch": "",
    "Postcode": "11602",
    "Country": "Mauritius",
    "Connection": "Active"
  },
  {
    "countryCode": "BAIM",
    "bankCode": "MU",
    "branchCode": "UMU",
    "SWIFT Code": "BAIMMUMU",
    "Bank Name": "BCP BANK (MAURITIUS) LTD (FORMERLY BANQUE DES MASCAREIGNES LTEE)",
    "Address": "FLOOR 9, MAEVA TOWER, CORNER SILICON AVE BANK STREET, EBENE CYBERCITY",
    "City": "Quatre Bornes",
    "Branch": "",
    "Postcode": "72201",
    "Country": "Mauritius",
    "Connection": "Active"
  },
  {
    "countryCode": "CIMU",
    "bankCode": "MU",
    "branchCode": "UMU",
    "SWIFT Code": "CIMUMUMU",
    "Bank Name": "CHOICE INTERNATIONAL (MAURITIUS) LTD",
    "Address": "FLOOR 2, SCB TOWER, BANK STREET",
    "City": "EBENE",
    "Branch": "",
    "Postcode": "72201",
    "Country": "Mauritius",
    "Connection": "Active"
  },
  {
    "countryCode": "DEUT",
    "bankCode": "MU",
    "branchCode": "UML",
    "SWIFT Code": "DEUTMUML",
    "Bank Name": "DEUTSCHE SECURITIES MAURITIUS LTD",
    "Address": "FLOOR 4, BARKLY WHARF EAST, LE CAUDAN WATERFRONT",
    "City": "PORT LOUIS",
    "Branch": "",
    "Postcode": "11307",
    "Country": "Mauritius",
    "Connection": "Active"
  },
  {
    "countryCode": "DEIM",
    "bankCode": "MU",
    "branchCode": "UMU",
    "SWIFT Code": "DEIMMUMU",
    "Bank Name": "DUNEARN INVESTMENTS (MAURITIUS) PTE LTD",
    "Address": "33 , EDITH CAVELL STREET",
    "City": "PORT LOUIS",
    "Branch": "C/O INT'L MANAGEMENT MAURITIUS LTD",
    "Postcode": "11324",
    "Country": "Mauritius",
    "Connection": "Active"
  },
  {
    "countryCode": "HABB",
    "bankCode": "MU",
    "branchCode": "UMU",
    "SWIFT Code": "HABBMUMU",
    "Bank Name": "HABIB BANK LTD MAURITIUS",
    "Address": "SIR WILLIAM NEWTON STREET",
    "City": "PORT LOUIS",
    "Branch": "",
    "Postcode": "11328",
    "Country": "Mauritius",
    "Connection": "Active"
  },
  {
    "countryCode": "HSBC",
    "bankCode": "MU",
    "branchCode": "UMU",
    "SWIFT Code": "HSBCMUMU",
    "Bank Name": "HONGKONG AND SHANGHAI BANKING CORPORATION LTD., THE",
    "Address": "18 HSBC CENTRE, CYBER CITY",
    "City": "Quatre Bornes",
    "Branch": "",
    "Postcode": "72201",
    "Country": "Mauritius",
    "Connection": "Active"
  },
  {
    "countryCode": "HSBC",
    "bankCode": "MU",
    "branchCode": "OBU",
    "SWIFT Code": "HSBCMUMUOBU",
    "Bank Name": "HONGKONG AND SHANGHAI BANKING CORPORATION LTD., THE",
    "Address": "HSBC CENTRE, FLOOR 6, 18 CYBERCITY",
    "City": "Quatre Bornes",
    "Branch": "HBMU BRANCH",
    "Postcode": "72201",
    "Country": "Mauritius",
    "Connection": "Active"
  },
  {
    "countryCode": "IHSA",
    "bankCode": "MU",
    "branchCode": "UMU",
    "SWIFT Code": "IHSAMUMU",
    "Bank Name": "IHS MAURITIUS CAMEROON",
    "Address": "FLOOR 1, FELIX HOUSE, 24 , DR. JOSEPH RIVIERE STREET",
    "City": "PORT LOUIS",
    "Branch": "",
    "Postcode": "",
    "Country": "Mauritius",
    "Connection": "Active"
  },
  {
    "countryCode": "IVES",
    "bankCode": "MU",
    "branchCode": "UMU",
    "SWIFT Code": "IVESMUMU",
    "Bank Name": "INVESTEC BANK (MAURITIUS) LIMITED",
    "Address": "FLOOR 0, OFFICE 2, THE STRAND, LE CAUDAN WATERFRONT",
    "City": "PORT LOUIS",
    "Branch": "",
    "Postcode": "11307",
    "Country": "Mauritius",
    "Connection": "Active"
  },
  {
    "countryCode": "KASV",
    "bankCode": "MU",
    "branchCode": "UMU",
    "SWIFT Code": "KASVMUMU",
    "Bank Name": "KASADA SERVICES LIMITED",
    "Address": "SANNE HOUSE, TWENTYEIGHT, BANK STREET, EBENE CYBERCITY",
    "City": "Quatre Bornes",
    "Branch": "",
    "Postcode": "72201",
    "Country": "Mauritius",
    "Connection": "Active"
  },
  {
    "countryCode": "MPCB",
    "bankCode": "MU",
    "branchCode": "UMU",
    "SWIFT Code": "MPCBMUMU",
    "Bank Name": "MAUBANK LTD",
    "Address": "25 , BANK STREET, EBENE CYBERCITY",
    "City": "Quatre Bornes",
    "Branch": "",
    "Postcode": "72201",
    "Country": "Mauritius",
    "Connection": "Active"
  },
  {
    "countryCode": "OMMC",
    "bankCode": "MU",
    "branchCode": "UMM",
    "SWIFT Code": "OMMCMUMM",
    "Bank Name": "OMNICANE MANAGEMENT AND CONSULTANCY LIMITED",
    "Address": "OMNICANE HOUSE, MON TRESOR BUSINESS, NEW AIRPORT ACCESS ROAD",
    "City": "PLAINE MAGNIEN",
    "Branch": "",
    "Postcode": "51521",
    "Country": "Mauritius",
    "Connection": "Active"
  },
  {
    "countryCode": "PLLP",
    "bankCode": "MU",
    "branchCode": "UMU",
    "SWIFT Code": "PLLPMUMU",
    "Bank Name": "PROVIDENCE LIFE LIMITED, PCC",
    "Address": "FLOOR 3, NEXTERACOM TOWERS. TOWER 1, EBENE CYBERCITY",
    "City": "Quatre Bornes",
    "Branch": "",
    "Postcode": "00000",
    "Country": "Mauritius",
    "Connection": "Active"
  },
  {
    "countryCode": "QCFN",
    "bankCode": "MU",
    "branchCode": "UMU",
    "SWIFT Code": "QCFNMUMU",
    "Bank Name": "QC FINANCE",
    "Address": "FLOOR 7, 51, RUE DU SAVOIR",
    "City": "EBENE",
    "Branch": "",
    "Postcode": "72201",
    "Country": "Mauritius",
    "Connection": "Active"
  },
  {
    "countryCode": "FIRN",
    "bankCode": "MU",
    "branchCode": "UMU",
    "SWIFT Code": "FIRNMUMU",
    "Bank Name": "RMB INTERNATIONAL (MAURITIUS) LTD",
    "Address": "FLOOR 3, PERRIERI OFFICE SUITES,, LA CROISETTE C2-302",
    "City": "GRAND-BAIE",
    "Branch": "",
    "Postcode": "30517",
    "Country": "Mauritius",
    "Connection": "Active"
  },
  {
    "countryCode": "INIL",
    "bankCode": "MU",
    "branchCode": "101",
    "SWIFT Code": "INILMUMU101",
    "Bank Name": "SBI (MAURITIUS) LTD",
    "Address": "34 , SIR WILLIAM NEWTON STREET",
    "City": "PORT LOUIS",
    "Branch": "WILLIAM NEWTON STREET",
    "Postcode": "11328",
    "Country": "Mauritius",
    "Connection": "Active"
  },
  {
    "countryCode": "INIL",
    "bankCode": "MU",
    "branchCode": "UMU",
    "SWIFT Code": "INILMUMU",
    "Bank Name": "SBI (MAURITIUS) LTD",
    "Address": "FLOOR 7, SBI TOWER MINDSPACE, 45, EBENE CYBERCITY",
    "City": "Quatre Bornes",
    "Branch": "",
    "Postcode": "72201",
    "Country": "Mauritius",
    "Connection": "Active"
  },
  {
    "countryCode": "STCB",
    "bankCode": "MU",
    "branchCode": "UMU",
    "SWIFT Code": "STCBMUMU",
    "Bank Name": "SBM BANK(MAURITIUS)LTD",
    "Address": "STATE BANK TOWER, 1 , QUEEN ELIZABETH II AVENUE",
    "City": "PORT LOUIS",
    "Branch": "",
    "Postcode": "11307",
    "Country": "Mauritius",
    "Connection": "Active"
  },
  {
    "countryCode": "STCB",
    "bankCode": "MU",
    "branchCode": "575",
    "SWIFT Code": "STCBMUMU575",
    "Bank Name": "SBM BANK(MAURITIUS)LTD",
    "Address": "STATE BANK TOWER, 1 , QUEEN ELIZABETH II AVENUE",
    "City": "PORT LOUIS",
    "Branch": "CUSTODY",
    "Postcode": "11307",
    "Country": "Mauritius",
    "Connection": "Active"
  },
  {
    "countryCode": "BTBL",
    "bankCode": "MU",
    "branchCode": "UMU",
    "SWIFT Code": "BTBLMUMU",
    "Bank Name": "SILVER BANK LIMITED",
    "Address": "NEXTERACOM, 13, 1, EBENE CYBERCITY",
    "City": "Quatre Bornes",
    "Branch": "",
    "Postcode": "00230",
    "Country": "Mauritius",
    "Connection": "Active"
  },
  {
    "countryCode": "SKCB",
    "bankCode": "MU",
    "branchCode": "UMU",
    "SWIFT Code": "SKCBMUMU",
    "Bank Name": "SKI CARBON BLACK (MAURITIUS) LIMITED",
    "Address": "SANNE HOUSE, 28, BANK STREET, EBENE CYBERCITY",
    "City": "Quatre Bornes",
    "Branch": "",
    "Postcode": "72201",
    "Country": "Mauritius",
    "Connection": "Active"
  },
  {
    "countryCode": "SBIC",
    "bankCode": "MU",
    "branchCode": "UMU",
    "SWIFT Code": "SBICMUMU",
    "Bank Name": "STANDARD BANK (MAURITIUS) LIMITED",
    "Address": "FLOOR 9, TOWER A, 1, EBENE CYBERCITY",
    "City": "Quatre Bornes",
    "Branch": "",
    "Postcode": "72201",
    "Country": "Mauritius",
    "Connection": "Active"
  },
  {
    "countryCode": "SCBL",
    "bankCode": "MU",
    "branchCode": "ZOP",
    "SWIFT Code": "SCBLMUMUZOP",
    "Bank Name": "STANDARD CHARTERED BANK (MAURITIUS) LTD",
    "Address": "",
    "City": "PORT LOUIS",
    "Branch": "FM ASSET SERVICING",
    "Postcode": "",
    "Country": "Mauritius",
    "Connection": "Active"
  },
  {
    "countryCode": "SCBL",
    "bankCode": "MU",
    "branchCode": "UMU",
    "SWIFT Code": "SCBLMUMU",
    "Bank Name": "STANDARD CHARTERED BANK (MAURITIUS) LTD",
    "Address": "FLOOR 6, 19 , BANK STREET, EBENE CYBERCITY",
    "City": "Quatre Bornes",
    "Branch": "",
    "Postcode": "72201",
    "Country": "Mauritius",
    "Connection": "Active"
  },
  {
    "countryCode": "SCBL",
    "bankCode": "MU",
    "branchCode": "SSU",
    "SWIFT Code": "SCBLMUMUSSU",
    "Bank Name": "STANDARD CHARTERED BANK (MAURITIUS) LTD",
    "Address": "FLOOR 6, 19 , BANK STREET, EBENE CYBERCITY",
    "City": "Quatre Bornes",
    "Branch": "SECURITIES SERVICES UNIT",
    "Postcode": "72201",
    "Country": "Mauritius",
    "Connection": "Active"
  },
  {
    "countryCode": "TPSV",
    "bankCode": "MU",
    "branchCode": "UMU",
    "SWIFT Code": "TPSVMUMU",
    "Bank Name": "TERRA PAYMENT SERVICES (MAURITIUS)",
    "Address": "APEX HOUSE, 28, BANK STREET",
    "City": "EBENE",
    "Branch": "",
    "Postcode": "72201",
    "Country": "Mauritius",
    "Connection": "Active"
  },
  {
    "countryCode": "MCBL",
    "bankCode": "MU",
    "branchCode": "UMU",
    "SWIFT Code": "MCBLMUMU",
    "Bank Name": "THE MAURITIUS COMMERCIAL BANK LIMITED",
    "Address": "9-15 , SIR WILLIAM NEWTON STREET",
    "City": "PORT LOUIS",
    "Branch": "",
    "Postcode": "11328",
    "Country": "Mauritius",
    "Connection": "Active"
  },
  {
    "countryCode": "VFIM",
    "bankCode": "MU",
    "branchCode": "UMU",
    "SWIFT Code": "VFIMMUMU",
    "Bank Name": "VALOR FINANCIAL MAURITIUS LTD",
    "Address": "MOKA",
    "City": "PORT LOUIS",
    "Branch": "",
    "Postcode": "",
    "Country": "Mauritius",
    "Connection": "Active"
  },
  {
    "countryCode": "WPBL",
    "bankCode": "MU",
    "branchCode": "UMU",
    "SWIFT Code": "WPBLMUMU",
    "Bank Name": "WARWYCK PRIVATE BANK LTD",
    "Address": "WARWYCK HOUSE, NALLETAMBY RD",
    "City": "VACOAS-PHOENIX",
    "Branch": "",
    "Postcode": "73538",
    "Country": "Mauritius",
    "Connection": "Active"
  }
]
module.exports = mauritius
