const mauritania = [
  {
    "countryCode": "AUBM",
    "bankCode": "MR",
    "branchCode": "RMR",
    "SWIFT Code": "AUBMMRMR",
    "Bank Name": "ALGERIAN UNION BANK-SA (AUB-SA)",
    "Address": "LOT NR 80, TAGVRAGH ZEINA, NOUAKCHOTT",
    "City": "NOUAKCHOTT",
    "Branch": "",
    "Postcode": "",
    "Country": "Mauritania",
    "Connection": "Active"
  },
  {
    "countryCode": "BCMA",
    "bankCode": "MR",
    "branchCode": "RMR",
    "SWIFT Code": "BCMAMRMR",
    "Bank Name": "ATTIJARI BANK MAURITANIE",
    "Address": "91-92 , MAMADOU KONATE",
    "City": "NOUAKCHOTT",
    "Branch": "",
    "Postcode": "5219",
    "Country": "Mauritania",
    "Connection": "Active"
  },
  {
    "countryCode": "BMSH",
    "bankCode": "MR",
    "branchCode": "RMR",
    "SWIFT Code": "BMSHMRMR",
    "Bank Name": "BANQUE AL MUAMELAT AS SAHIHA",
    "Address": "IMMEUBLE AL KAYMA, FLOOR 4, 10 , MAMADOU KONATE",
    "City": "NOUAKCHOTT",
    "Branch": "",
    "Postcode": "5243",
    "Country": "Mauritania",
    "Connection": "Active"
  },
  {
    "countryCode": "BAAW",
    "bankCode": "MR",
    "branchCode": "RMR",
    "SWIFT Code": "BAAWMRMR",
    "Bank Name": "BANQUE AL WAVA MAURITANIENNE ISLAMIQUE (BAMIS)",
    "Address": "AVENUE DU ROI FAYCAL",
    "City": "NOUAKCHOTT",
    "Branch": "",
    "Postcode": "",
    "Country": "Mauritania",
    "Connection": "Active"
  },
  {
    "countryCode": "BCEM",
    "bankCode": "MR",
    "branchCode": "RMR",
    "SWIFT Code": "BCEMMRMR",
    "Bank Name": "BANQUE CENTRALE DE MAURITANIE",
    "Address": "BCM BUILDING, AVENUE DE L'INDEPENDANCE",
    "City": "NOUAKCHOTT",
    "Branch": "",
    "Postcode": "",
    "Country": "Mauritania",
    "Connection": "Active"
  },
  {
    "countryCode": "FIAQ",
    "bankCode": "MR",
    "branchCode": "RMR",
    "SWIFT Code": "FIAQMRMR",
    "Bank Name": "BANQUE DES FINANCEMENTS ISLAMIQUES",
    "Address": "N 31, ANGLE AVENUE BOUDDAH OULD BOUSSEIRY, AVENUE ROI FAYCAL ILOT T",
    "City": "NOUAKCHOTT",
    "Branch": "",
    "Postcode": "6082",
    "Country": "Mauritania",
    "Connection": "Active"
  },
  {
    "countryCode": "AMDH",
    "bankCode": "MR",
    "branchCode": "RMR",
    "SWIFT Code": "AMDHMRMR",
    "Bank Name": "BANQUE EL AMANA (BEA)",
    "Address": "BANQUE EL AMANA BUILDING AVENUE, ALI IBN ABI TALEB, AVENUE OUMAR IBN, EL KHATTAB",
    "City": "NOUAKCHOTT",
    "Branch": "",
    "Postcode": "5559",
    "Country": "Mauritania",
    "Connection": "Active"
  },
  {
    "countryCode": "BIMM",
    "bankCode": "MR",
    "branchCode": "RMR",
    "SWIFT Code": "BIMMMRMR",
    "Bank Name": "BANQUE ISLAMIQUE DE MAURITANIE",
    "Address": "402 , AVENUE DU ROI FAYCAL, KSAR",
    "City": "NOUAKCHOTT",
    "Branch": "",
    "Postcode": "",
    "Country": "Mauritania",
    "Connection": "Active"
  },
  {
    "countryCode": "BQMI",
    "bankCode": "MR",
    "branchCode": "RMR",
    "SWIFT Code": "BQMIMRMR",
    "Bank Name": "BANQUE MAURITANIENNE DE L'INVESTISSEMENT",
    "Address": "20, SOCOGIM TVZ ZR",
    "City": "NOUAKCHOTT",
    "Branch": "",
    "Postcode": "",
    "Country": "Mauritania",
    "Connection": "Active"
  },
  {
    "countryCode": "MBIC",
    "bankCode": "MR",
    "branchCode": "0MN",
    "SWIFT Code": "MBICMRMR0MN",
    "Bank Name": "BANQUE MAURITANIENNE POUR LE COMMERCE INTERNATIONAL",
    "Address": "",
    "City": "NOUADHIBOU",
    "Branch": "",
    "Postcode": "",
    "Country": "Mauritania",
    "Connection": "Active"
  },
  {},
  {
    "countryCode": "BQNM",
    "bankCode": "MR",
    "branchCode": "RMR",
    "SWIFT Code": "BQNMMRMR",
    "Bank Name": "BANQUE NATIONALE DE MAURITANIE",
    "Address": "AVENUE GAMAL ABD EL NASSER",
    "City": "NOUAKCHOTT",
    "Branch": "",
    "Postcode": "2391",
    "Country": "Mauritania",
    "Connection": "Active"
  },
  {
    "countryCode": "BPMA",
    "bankCode": "MR",
    "branchCode": "RMR",
    "SWIFT Code": "BPMAMRMR",
    "Bank Name": "BANQUE POPULAIRE DE MAURITANIE",
    "Address": "100 , AVENUE EL HAJ OUMAR TALL, SOCOGIM TEVRAGH ZEINA",
    "City": "CITY OF MAKATI",
    "Branch": "",
    "Postcode": "3842",
    "Country": "Mauritania",
    "Connection": "Active"
  },
  {
    "countryCode": "COLI",
    "bankCode": "MR",
    "branchCode": "RMR",
    "SWIFT Code": "COLIMRMR",
    "Bank Name": "BANQUE POUR LE COMMERCE ET L'INDUSTRIE",
    "Address": "AVENUE NASSER",
    "City": "NOUAKCHOTT",
    "Branch": "",
    "Postcode": "5050",
    "Country": "Mauritania",
    "Connection": "Active"
  },
  {
    "countryCode": "CZRZ",
    "bankCode": "MR",
    "branchCode": "RMR",
    "SWIFT Code": "CZRZMRMR",
    "Bank Name": "CHINGUITTY BANK",
    "Address": "AVENUE GAMAL ABD EL NASSER",
    "City": "NOUAKCHOTT",
    "Branch": "",
    "Postcode": "",
    "Country": "Mauritania",
    "Connection": "Active"
  },
  {
    "countryCode": "GBMC",
    "bankCode": "MR",
    "branchCode": "NDB",
    "SWIFT Code": "GBMCMRMRNDB",
    "Bank Name": "GENERALE DE BANQUE DE MAURITANIE POUR L'INVESTISSEMENT ET LE COMMERCE",
    "Address": "BOULEVARD MEDIAN",
    "City": "NOUADHIBOU",
    "Branch": "",
    "Postcode": "",
    "Country": "Mauritania",
    "Connection": "Active"
  },
  {
    "countryCode": "GBMC",
    "bankCode": "MR",
    "branchCode": "RMR",
    "SWIFT Code": "GBMCMRMR",
    "Bank Name": "GENERALE DE BANQUE DE MAURITANIE POUR L'INVESTISSEMENT ET LE COMMERCE",
    "Address": "AVENUE DE L'INDEPENDANCE",
    "City": "NOUAKCHOTT",
    "Branch": "",
    "Postcode": "",
    "Country": "Mauritania",
    "Connection": "Active"
  },
  {
    "countryCode": "IBMR",
    "bankCode": "MR",
    "branchCode": "RMR",
    "SWIFT Code": "IBMRMRMR",
    "Bank Name": "INTERNATIONAL BANK OF MAURITANIA",
    "Address": "14, ZRB TZ, ILOT V",
    "City": "NOUAKCHOTT",
    "Branch": "",
    "Postcode": "",
    "Country": "Mauritania",
    "Connection": "Active"
  },
  {
    "countryCode": "NBMR",
    "bankCode": "MR",
    "branchCode": "RMR",
    "SWIFT Code": "NBMRMRMR",
    "Bank Name": "NOUVELLE BANQUE DE MAURITANIE",
    "Address": "585, ZRA",
    "City": "NOUAKCHOTT",
    "Branch": "",
    "Postcode": "1272",
    "Country": "Mauritania",
    "Connection": "Active"
  },
  {
    "countryCode": "ORBK",
    "bankCode": "MR",
    "branchCode": "RMR",
    "SWIFT Code": "ORBKMRMR",
    "Bank Name": "ORABANK MAURITANIE",
    "Address": "42-060 4, AV GENERAL CHARLES DE GAULLE, 20 RUE TEVRAGH ZEINA",
    "City": "NOUAKCHOTT",
    "Branch": "",
    "Postcode": "",
    "Country": "Mauritania",
    "Connection": "Active"
  },
  {
    "countryCode": "QNBA",
    "bankCode": "MR",
    "branchCode": "RMU",
    "SWIFT Code": "QNBAMRMU",
    "Bank Name": "QATAR NATIONAL BANK (QNB)",
    "Address": "AL KHAIMA BUILDING, U10 , MAMADOU KONATE STREET",
    "City": "NOUAKCHOTT",
    "Branch": "",
    "Postcode": "",
    "Country": "Mauritania",
    "Connection": "Active"
  },
  {
    "countryCode": "BIIM",
    "bankCode": "MR",
    "branchCode": "RMR",
    "SWIFT Code": "BIIMMRMR",
    "Bank Name": "SOCIETE GENERALE MAURITANIE",
    "Address": "N 652, AVENUE EL HADJ OUMAR TALL, ILOT A",
    "City": "NOUAKCHOTT",
    "Branch": "",
    "Postcode": "",
    "Country": "Mauritania",
    "Connection": "Active"
  }
]
module.exports = mauritania
