const moldova = [
  {
    "countryCode": "CMTB",
    "bankCode": "MD",
    "branchCode": "D2X",
    "SWIFT Code": "CMTBMD2X",
    "Bank Name": "BANCA COMERCIALA 'COMERTBANK' S.A.",
    "Address": "INDEPENDENTEI 1/1",
    "City": "CHISINAU",
    "Branch": "",
    "Postcode": "MD-2043",
    "Country": "Moldova",
    "Connection": "Active"
  },
  {
    "countryCode": "EXMM",
    "bankCode": "MD",
    "branchCode": "D22",
    "SWIFT Code": "EXMMMD22",
    "Bank Name": "BANCA COMERCIALA EXIMBANK S.A.",
    "Address": "BD. STEFAN CEL MARE 171/1",
    "City": "CHISINAU",
    "Branch": "",
    "Postcode": "MD-2004",
    "Country": "Moldova",
    "Connection": "Active"
  },
  {
    "countryCode": "FTMD",
    "bankCode": "MD",
    "branchCode": "D2X",
    "SWIFT Code": "FTMDMD2X",
    "Bank Name": "BANCA DE FINANTE SI COMERT S.A. (FINCOMBANK S.A.)",
    "Address": "PUSKIN STREET 26",
    "City": "CHISINAU",
    "Branch": "",
    "Postcode": "MD-2012",
    "Country": "Moldova",
    "Connection": "Active"
  },
  {
    "countryCode": "ENEG",
    "bankCode": "MD",
    "branchCode": "D22",
    "SWIFT Code": "ENEGMD22",
    "Bank Name": "BC ENERGBANK S.A.",
    "Address": "TIGHINA STREET 23/3",
    "City": "CHISINAU",
    "Branch": "",
    "Postcode": "MD-2001",
    "Country": "Moldova",
    "Connection": "Active"
  },
  {
    "countryCode": "ECBM",
    "bankCode": "MD",
    "branchCode": "D2X",
    "SWIFT Code": "ECBMMD2X",
    "Bank Name": "BC EUROCREDITBANK S.A.",
    "Address": "ISMAIL STREET 33",
    "City": "CHISINAU",
    "Branch": "",
    "Postcode": "MD-2001",
    "Country": "Moldova",
    "Connection": "Active"
  },
  {
    "countryCode": "AGRN",
    "bankCode": "MD",
    "branchCode": "D2X",
    "SWIFT Code": "AGRNMD2X",
    "Bank Name": "BC MOLDOVA - AGROINDBANK S.A.",
    "Address": "CONSTANTIN TANASE 9/1",
    "City": "CHISINAU",
    "Branch": "",
    "Postcode": "MD-2005",
    "Country": "Moldova",
    "Connection": "Active"
  },
  {
    "countryCode": "PRCB",
    "bankCode": "MD",
    "branchCode": "D22",
    "SWIFT Code": "PRCBMD22",
    "Bank Name": "BC PROCREDIT BANK S.A.",
    "Address": "STEFAN CEL MARE SI SFINT AVE 65",
    "City": "CHISINAU",
    "Branch": "",
    "Postcode": "MD-2012",
    "Country": "Moldova",
    "Connection": "Active"
  },
  {
    "countryCode": "VICB",
    "bankCode": "MD",
    "branchCode": "D2X",
    "SWIFT Code": "VICBMD2X",
    "Bank Name": "JOINT-STOCK COMMERCIAL VICTORIABANK",
    "Address": "31 AUGUST 1989 141",
    "City": "CHISINAU",
    "Branch": "",
    "Postcode": "MD-2004",
    "Country": "Moldova",
    "Connection": "Active"
  },
  {
    "countryCode": "MOLD",
    "bankCode": "MD",
    "branchCode": "D2X",
    "SWIFT Code": "MOLDMD2X",
    "Bank Name": "MOLDINDCONBANK",
    "Address": "ARMENEASCA 38",
    "City": "CHISINAU",
    "Branch": "",
    "Postcode": "MD-2012",
    "Country": "Moldova",
    "Connection": "Active"
  },
  {
    "countryCode": "NBMD",
    "bankCode": "MD",
    "branchCode": "D2X",
    "SWIFT Code": "NBMDMD2X",
    "Bank Name": "NATIONAL BANK OF MOLDOVA",
    "Address": "GRIGORE VIERU AVENUE 1",
    "City": "CHISINAU",
    "Branch": "HEAD OFFICE",
    "Postcode": "MD-2005",
    "Country": "Moldova",
    "Connection": "Active"
  },
  {
    "countryCode": "MOBB",
    "bankCode": "MD",
    "branchCode": "D22",
    "SWIFT Code": "MOBBMD22",
    "Bank Name": "OTP BANK S.A.",
    "Address": "BLVD. STEFAN CEL MARE SI SFANT 81A",
    "City": "CHISINAU",
    "Branch": "",
    "Postcode": "MD-2012",
    "Country": "Moldova",
    "Connection": "Active"
  },
  {
    "countryCode": "RNCB",
    "bankCode": "MD",
    "branchCode": "D2X",
    "SWIFT Code": "RNCBMD2X",
    "Bank Name": "ROMANIAN COMMERCIAL BANK CHISINAU S.A.",
    "Address": "PUSKIN STREET 60/2",
    "City": "CHISINAU",
    "Branch": "",
    "Postcode": "MD-2005",
    "Country": "Moldova",
    "Connection": "Active"
  }
]
module.exports = moldova
