const monaco = [
  {
    "bankCode": "BACA",
    "countryCode": "MC",
    "branchCode": "CMC",
    "SWIFT Code": "BACAMCMC",
    "Bank Name": "ANDBANC MONACO SAM",
    "Address": "1 AVENUE DES CITRONNIERS",
    "City": "MONACO",
    "Branch": "",
    "Postcode": "98000",
    "Country": "Monaco",
    "Connection": "Active"
  },
  {
    "bankCode": "BAER",
    "countryCode": "MC",
    "branchCode": "CMC",
    "SWIFT Code": "BAERMCMC",
    "Bank Name": "BANK JULIUS BAER (MONACO) S.A.M.",
    "Address": "12 BOULEVARD DES MOULINS",
    "City": "MONACO",
    "Branch": "",
    "Postcode": "98000",
    "Country": "Monaco",
    "Connection": "Active"
  },
  {
    "bankCode": "PICT",
    "countryCode": "MC",
    "branchCode": "CMC",
    "SWIFT Code": "PICTMCMC",
    "Bank Name": "BANK PICTET AND CIE (EUROPE) AG, SUCCURSALE DE MONACO",
    "Address": "VILLA MIRAFLORES, 2 AVENUE SAINT-MICHEL",
    "City": "MONACO",
    "Branch": "",
    "Postcode": "98000",
    "Country": "Monaco",
    "Connection": "Active"
  },
  {
    "bankCode": "PICT",
    "countryCode": "MC",
    "branchCode": "COR",
    "SWIFT Code": "PICTMCMCCOR",
    "Bank Name": "BANK PICTET AND CIE (EUROPE) AG, SUCCURSALE DE MONACO",
    "Address": "VILLA MIRAFLORES, 2 AVENUE SAINT-MICHEL",
    "City": "MONACO",
    "Branch": "CORPORATE ACTION",
    "Postcode": "98000",
    "Country": "Monaco",
    "Connection": "Active"
  },
  {
    "bankCode": "HAVL",
    "countryCode": "MC",
    "branchCode": "BDF",
    "SWIFT Code": "HAVLMCMXBDF",
    "Bank Name": "BANQUE HAVILLAND (MONACO) S.A.M.",
    "Address": "",
    "City": "MONACO",
    "Branch": "",
    "Postcode": "98000",
    "Country": "Monaco",
    "Connection": "Active"
  },
  {
    "bankCode": "HAVL",
    "countryCode": "MC",
    "branchCode": "CMX",
    "SWIFT Code": "HAVLMCMX",
    "Bank Name": "BANQUE HAVILLAND (MONACO) S.A.M.",
    "Address": "3-7 BOULEVARD DES MOULINS",
    "City": "MONACO",
    "Branch": "",
    "Postcode": "98000",
    "Country": "Monaco",
    "Connection": "Active"
  },
  {
    "bankCode": "BJSB",
    "countryCode": "MC",
    "branchCode": "CMX",
    "SWIFT Code": "BJSBMCMX",
    "Bank Name": "BANQUE J. SAFRA SARASIN (MONACO) SA",
    "Address": "LE BELLE EPOQUE, 15BIS/17 AVENUE D'OSTENDE",
    "City": "MONACO",
    "Branch": "",
    "Postcode": "98000",
    "Country": "Monaco",
    "Connection": "Active"
  },
  {
    "bankCode": "BJSB",
    "countryCode": "MC",
    "branchCode": "LCO",
    "SWIFT Code": "BJSBMCMXLCO",
    "Bank Name": "BANQUE J. SAFRA SARASIN (MONACO) SA",
    "Address": "",
    "City": "MONACO",
    "Branch": "ONLY BANQUE DE FRANCE",
    "Postcode": "98000",
    "Country": "Monaco",
    "Connection": "Active"
  },
  {
    "bankCode": "KBLX",
    "countryCode": "MC",
    "branchCode": "CMC",
    "SWIFT Code": "KBLXMCMC",
    "Bank Name": "BANQUE RICHELIEU MONACO",
    "Address": "BRETAGNE, 8 AVENUE DE GRANDE BRETAGNE",
    "City": "MONACO",
    "Branch": "",
    "Postcode": "98005",
    "Country": "Monaco",
    "Connection": "Active"
  },
  {
    "bankCode": "BARC",
    "countryCode": "MC",
    "branchCode": "CMX",
    "SWIFT Code": "BARCMCMX",
    "Bank Name": "BARCLAYS BANK PLC MONACO",
    "Address": "31 AVENUE DE LA COSTA",
    "City": "MONACO",
    "Branch": "",
    "Postcode": "98000",
    "Country": "Monaco",
    "Connection": "Active"
  },
  {
    "bankCode": "BEHM",
    "countryCode": "MC",
    "branchCode": "CMC",
    "SWIFT Code": "BEHMMCMC",
    "Bank Name": "BESINS HEALTHCARE MONACO SAM",
    "Address": "LOT 777 , FLOOR RDC, LES TERRASSES, DU PORT 2 AVENUE DES LIGURES",
    "City": "MONACO",
    "Branch": "",
    "Postcode": "98000",
    "Country": "Monaco",
    "Connection": "Active"
  },
  {
    "bankCode": "BPPB",
    "countryCode": "MC",
    "branchCode": "CMC",
    "SWIFT Code": "BPPBMCMC",
    "Bank Name": "BNP PARIBAS WEALTH MANAGEMENT MONACO",
    "Address": "15-17 AVENUE D'OSTENDE",
    "City": "MONACO",
    "Branch": "",
    "Postcode": "98000",
    "Country": "Monaco",
    "Connection": "Active"
  },
  {
    "bankCode": "CFMO",
    "countryCode": "MC",
    "branchCode": "CMX",
    "SWIFT Code": "CFMOMCMX",
    "Bank Name": "CFM INDOSUEZ WEALTH",
    "Address": "11 BOULEVARD ALBERT IER",
    "City": "MONACO",
    "Branch": "",
    "Postcode": "98012",
    "Country": "Monaco",
    "Connection": "Active"
  },
  {
    "bankCode": "AZFM",
    "countryCode": "MC",
    "branchCode": "CMC",
    "SWIFT Code": "AZFMMCMC",
    "Bank Name": "CGM-AZIMUT MONACO",
    "Address": "ESCALIER DES FLEURS, 8 BOULEVARD DES MOULINS",
    "City": "MONACO",
    "Branch": "",
    "Postcode": "98000",
    "Country": "Monaco",
    "Connection": "Active"
  },
  {
    "bankCode": "CMBM",
    "countryCode": "MC",
    "branchCode": "CMX",
    "SWIFT Code": "CMBMMCMX",
    "Bank Name": "CMB MONACO",
    "Address": "23 AVENUE DE LA COSTA",
    "City": "MONACO",
    "Branch": "",
    "Postcode": "98003",
    "Country": "Monaco",
    "Connection": "Active"
  },
  {
    "bankCode": "DIET",
    "countryCode": "MC",
    "branchCode": "CMC",
    "SWIFT Code": "DIETMCMC",
    "Bank Name": "DIETSMANN MONTE CARLO SAM",
    "Address": "GILDO PASTOR CENTER, 7, 9 RUE DU GABIAN",
    "City": "MONACO",
    "Branch": "",
    "Postcode": "98000",
    "Country": "Monaco",
    "Connection": "Active"
  },
  {
    "bankCode": "DOAV",
    "countryCode": "MC",
    "branchCode": "CMC",
    "SWIFT Code": "DOAVMCMC",
    "Bank Name": "DOXA ADVISORS S.A.M.",
    "Address": "LES CARAVELLES",
    "City": "MONACO",
    "Branch": "",
    "Postcode": "98000",
    "Country": "Monaco",
    "Connection": "Active"
  },
  {
    "bankCode": "BERL",
    "countryCode": "MC",
    "branchCode": "BDF",
    "SWIFT Code": "BERLMCMCBDF",
    "Bank Name": "EDMOND DE ROTHSCHILD-MONACO",
    "Address": "",
    "City": "MONACO",
    "Branch": "",
    "Postcode": "98000",
    "Country": "Monaco",
    "Connection": "Active"
  },
  {
    "bankCode": "BERL",
    "countryCode": "MC",
    "branchCode": "CMC",
    "SWIFT Code": "BERLMCMC",
    "Bank Name": "EDMOND DE ROTHSCHILD-MONACO",
    "Address": "LES TERRASSES, CARLO, 2 AVENUE DE MONTE",
    "City": "MONACO",
    "Branch": "",
    "Postcode": "98000",
    "Country": "Monaco",
    "Connection": "Active"
  },
  {
    "bankCode": "EFGB",
    "countryCode": "MC",
    "branchCode": "CMC",
    "SWIFT Code": "EFGBMCMC",
    "Bank Name": "EFG BANK (MONACO)",
    "Address": "VILLA DES AIGLES, 15 AVENUE D'OSTENDE",
    "City": "MONACO",
    "Branch": "",
    "Postcode": "98000",
    "Country": "Monaco",
    "Connection": "Active"
  },
  {
    "bankCode": "PMMC",
    "countryCode": "MC",
    "branchCode": "CMC",
    "SWIFT Code": "PMMCMCMC",
    "Bank Name": "PACIFIC MANAGEMENT SAM",
    "Address": "7 RUE DU GABIAN",
    "City": "MONACO",
    "Branch": "",
    "Postcode": "98000",
    "Country": "Monaco",
    "Connection": "Active"
  },
  {
    "bankCode": "RTLD",
    "countryCode": "MC",
    "branchCode": "CMC",
    "SWIFT Code": "RTLDMCMC",
    "Bank Name": "ROTHELAND S.A.M.",
    "Address": "4-6 RUELLE SAINTE DEVOTE",
    "City": "MONACO",
    "Branch": "",
    "Postcode": "98000",
    "Country": "Monaco",
    "Connection": "Active"
  },
  {
    "bankCode": "SBMM",
    "countryCode": "MC",
    "branchCode": "CMC",
    "SWIFT Code": "SBMMMCMC",
    "Bank Name": "SOCIETE ANONYME DES BAINS DE MER ET DU CERCLE DES ETRANGERS A MONACO",
    "Address": "PLACE DU CASINO",
    "City": "MONACO",
    "Branch": "",
    "Postcode": "98000",
    "Country": "Monaco",
    "Connection": "Active"
  },
  {
    "bankCode": "SDBM",
    "countryCode": "MC",
    "branchCode": "CM2",
    "SWIFT Code": "SDBMMCM2",
    "Bank Name": "SOCIETE GENERALE (FORMERLY SOCIETE DE BANQUE MONACO)",
    "Address": "LE PARK PALACE, 27 AVENUE DE LA COSTA",
    "City": "MONACO",
    "Branch": "",
    "Postcode": "98000",
    "Country": "Monaco",
    "Connection": "Active"
  },
  {
    "bankCode": "SDBM",
    "countryCode": "MC",
    "branchCode": "TPS",
    "SWIFT Code": "SDBMMCM2TPS",
    "Bank Name": "SOCIETE GENERALE (FORMERLY SOCIETE DE BANQUE MONACO)",
    "Address": "LE PARK PALACE, 27 AVENUE DE LA COSTA",
    "City": "MONACO",
    "Branch": "TIPS INSTANT PAYMENT",
    "Postcode": "98000",
    "Country": "Monaco",
    "Connection": "Active"
  },
  {
    "bankCode": "SGBT",
    "countryCode": "MC",
    "branchCode": "CMC",
    "SWIFT Code": "SGBTMCMC",
    "Bank Name": "SOCIETE GENERALE PRIVATE BANKING (MONACO)",
    "Address": "IMMEUBLE LE REGINA, 13-15 BOULEVARD DES MOULINS",
    "City": "MONACO",
    "Branch": "",
    "Postcode": "98000",
    "Country": "Monaco",
    "Connection": "Active"
  },
  {
    "bankCode": "UBSW",
    "countryCode": "MC",
    "branchCode": "CMX",
    "SWIFT Code": "UBSWMCMX",
    "Bank Name": "UBS (MONACO) S.A.",
    "Address": "BRETAGNE, 2 AVENUE DE GRANDE",
    "City": "MONACO",
    "Branch": "",
    "Postcode": "98007",
    "Country": "Monaco",
    "Connection": "Active"
  },
  {
    "bankCode": "UBPG",
    "countryCode": "MC",
    "branchCode": "CMX",
    "SWIFT Code": "UBPGMCMX",
    "Bank Name": "UNION BANCAIRE PRIVEE, UBP SA",
    "Address": "LA BELLE EPOQUE, 17 AVENUE D'OSTENDE",
    "City": "MONACO",
    "Branch": "",
    "Postcode": "98000",
    "Country": "Monaco",
    "Connection": "Active"
  },
  {},
  {
    "bankCode": "VENU",
    "countryCode": "MC",
    "branchCode": "CMC",
    "SWIFT Code": "VENUMCMC",
    "Bank Name": "VENUS MANAGEMENT COMPANY S.A.M.",
    "Address": "VILLA BIJOU, 19 AVENUE DE LA COSTA",
    "City": "MONACO",
    "Branch": "",
    "Postcode": "98000",
    "Country": "Monaco",
    "Connection": "Active"
  }
]
module.exports = monaco
