const mongolia = [
  {
    "bankCode": "ARGB",
    "countryCode": "MN",
    "branchCode": "NUB",
    "SWIFT Code": "ARGBMNUB",
    "Bank Name": "ARIG BANK OF MONGOLIA (ARIG BANK LLC)",
    "Address": "ARIG BANK BUILDING, CHINGIS AVENUE, KHAN-UUL DISTRICT",
    "City": "ULAANBAATAR",
    "Branch": "",
    "Postcode": "17061",
    "Country": "Mongolia",
    "Connection": "Active"
  },
  {
    "bankCode": "BOMU",
    "countryCode": "MN",
    "branchCode": "NUB",
    "SWIFT Code": "BOMUMNUB",
    "Bank Name": "BANK OF MONGOLIA, THE",
    "Address": "THE CENTRAL BANK, BAGA TOIRUU 3",
    "City": "ULAANBAATAR",
    "Branch": "",
    "Postcode": "15160",
    "Country": "Mongolia",
    "Connection": "Active"
  },
  {
    "bankCode": "BOGD",
    "countryCode": "MN",
    "branchCode": "NUB",
    "SWIFT Code": "BOGDMNUB",
    "Bank Name": "BOGD BANK",
    "Address": "BODI TOWER 2, JIGJIDJAV STR 3",
    "City": "ULAANBAATAR",
    "Branch": "",
    "Postcode": "15160",
    "Country": "Mongolia",
    "Connection": "Active"
  },
  {
    "bankCode": "CBMN",
    "countryCode": "MN",
    "branchCode": "NUB",
    "SWIFT Code": "CBMNMNUB",
    "Bank Name": "CAPITAL BANK OF MONGOLIA",
    "Address": "SAMBUU STREET 48",
    "City": "ULAANBAATAR",
    "Branch": "",
    "Postcode": "15141",
    "Country": "Mongolia",
    "Connection": "Active"
  },
  {
    "bankCode": "CPIT",
    "countryCode": "MN",
    "branchCode": "NUB",
    "SWIFT Code": "CPITMNUB",
    "Bank Name": "CAPITRON BANK",
    "Address": "USNY GUDAMJ-4 2-R, KHOROO",
    "City": "ULAANBAATAR",
    "Branch": "",
    "Postcode": "14253",
    "Country": "Mongolia",
    "Connection": "Active"
  },
  {
    "bankCode": "CHKH",
    "countryCode": "MN",
    "branchCode": "NUB",
    "SWIFT Code": "CHKHMNUB",
    "Bank Name": "CHINGGIS KHAAN BANK",
    "Address": "NEW CENTURY PLAZA, CHINGGIS AVEN 15, SUKHBAATAR DISTRICT",
    "City": "ULAANBAATAR",
    "Branch": "",
    "Postcode": "14251",
    "Country": "Mongolia",
    "Connection": "Active"
  },
  {
    "bankCode": "DBOM",
    "countryCode": "MN",
    "branchCode": "NUB",
    "SWIFT Code": "DBOMMNUB",
    "Bank Name": "DEVELOPMENT BANK OF MONGOLIA",
    "Address": "FLOOR 11,12, PEACE AVENUE 19, SUKHBAATAR DISTR",
    "City": "ULAANBAATAR",
    "Branch": "",
    "Postcode": "15160",
    "Country": "Mongolia",
    "Connection": "Active"
  },
  {
    "bankCode": "GLMT",
    "countryCode": "MN",
    "branchCode": "NUB",
    "SWIFT Code": "GLMTMNUB",
    "Bank Name": "GOLOMT BANK OF MONGOLIA",
    "Address": "D.SUKHBAATARS SQUARE 5",
    "City": "ULAANBAATAR",
    "Branch": "",
    "Postcode": "15160",
    "Country": "Mongolia",
    "Connection": "Active"
  },
  {
    "bankCode": "GLMT",
    "countryCode": "MN",
    "branchCode": "CUS",
    "SWIFT Code": "GLMTMNUBCUS",
    "Bank Name": "GOLOMT BANK OF MONGOLIA",
    "Address": "D.SUKHBAATAR SQUARE 5",
    "City": "ULAANBAATAR",
    "Branch": "HEAD OFFICE",
    "Postcode": "15160",
    "Country": "Mongolia",
    "Connection": "Active"
  },
  {
    "bankCode": "AGMO",
    "countryCode": "MN",
    "branchCode": "CUS",
    "SWIFT Code": "AGMOMNUBCUS",
    "Bank Name": "KHAN BANK JSC",
    "Address": "KHAN BANK TOWER, STADIUM ORGIL 1, CHINGGIS AVENUE 6",
    "City": "ULAANBAATAR",
    "Branch": "",
    "Postcode": "17010",
    "Country": "Mongolia",
    "Connection": "Active"
  },
  {
    "bankCode": "AGMO",
    "countryCode": "MN",
    "branchCode": "NUB",
    "SWIFT Code": "AGMOMNUB",
    "Bank Name": "KHAN BANK JSC",
    "Address": "KHAN BANK TOWER, STADIUM ORGIL 1, CHINGGIS AVENUE 6",
    "City": "ULAANBAATAR",
    "Branch": "",
    "Postcode": "17010",
    "Country": "Mongolia",
    "Connection": "Active"
  },
  {
    "bankCode": "MBKN",
    "countryCode": "MN",
    "branchCode": "NUB",
    "SWIFT Code": "MBKNMNUB",
    "Bank Name": "M BANK JSC",
    "Address": "FLOOR 15, CENTRAL TOWER, SUKHBAATAR SQUARE 2, 8TH KHOROO, SUKHBAATAR DISTRICT",
    "City": "ULAANBAATAR",
    "Branch": "",
    "Postcode": "14200",
    "Country": "Mongolia",
    "Connection": "Active"
  },
  {
    "bankCode": "MNJS",
    "countryCode": "MN",
    "branchCode": "NU2",
    "SWIFT Code": "MNJSMNU2",
    "Bank Name": "MONGOL POST JSC",
    "Address": "ENKHTAIVAN STREET",
    "City": "ULAANBAATAR",
    "Branch": "",
    "Postcode": "00976",
    "Country": "Mongolia",
    "Connection": "Active"
  },
  {
    "bankCode": "NAIM",
    "countryCode": "MN",
    "branchCode": "NUB",
    "SWIFT Code": "NAIMMNUB",
    "Bank Name": "NATIONAL INVESTMENT BANK OF MONGOLIA",
    "Address": "BLDG 1, USNII STREET 1, KHOROO 3",
    "City": "ULAANBAATAR",
    "Branch": "",
    "Postcode": "14252",
    "Country": "Mongolia",
    "Connection": "Active"
  },
  {
    "bankCode": "FSNL",
    "countryCode": "MN",
    "branchCode": "NU2",
    "SWIFT Code": "FSNLMNU2",
    "Bank Name": "SENDMN NBFI",
    "Address": "FLOOR 1, 3 KHOROO, 5TH KHOROOLOL, 5TH KHOROOLOL 2A, 3 KHOROO",
    "City": "ULAANBAATAR",
    "Branch": "",
    "Postcode": "14251",
    "Country": "Mongolia",
    "Connection": "Active"
  },
  {
    "bankCode": "STBM",
    "countryCode": "MN",
    "branchCode": "NUB",
    "SWIFT Code": "STBMMNUB",
    "Bank Name": "STATE BANK",
    "Address": "STATE BANK BUILDING, BAGA TOIRUU 7/1, CHINGELTEI DISTRICT, 1ST KHOROO",
    "City": "ULAANBAATAR",
    "Branch": "",
    "Postcode": "14201",
    "Country": "Mongolia",
    "Connection": "Active"
  },
  {
    "bankCode": "TDBM",
    "countryCode": "MN",
    "branchCode": "NUB",
    "SWIFT Code": "TDBMMNUB",
    "Bank Name": "TRADE AND DEVELOPMENT BANK JSC",
    "Address": "TDBM BUILDING, PEACE AVENUE 19, SBD DIST, 1-KHOROO",
    "City": "ULAANBAATAR",
    "Branch": "",
    "Postcode": "14210",
    "Country": "Mongolia",
    "Connection": "Active"
  },
  {
    "bankCode": "TBOM",
    "countryCode": "MN",
    "branchCode": "NUB",
    "SWIFT Code": "TBOMMNUB",
    "Bank Name": "TRANSBANK",
    "Address": "FLOOR 15, SHANGRI-LA OFFICE, OLYMPIC STREET 19A, SUKHBAATAR DISTRICT 1",
    "City": "ULAANBAATAR",
    "Branch": "",
    "Postcode": "14241",
    "Country": "Mongolia",
    "Connection": "Active"
  },
  {
    "bankCode": "CAXB",
    "countryCode": "MN",
    "branchCode": "NUB",
    "SWIFT Code": "CAXBMNUB",
    "Bank Name": "XACBANK",
    "Address": "XAC BANK BUILDING, PRIME MINISTER AMAR'S STREET, SUHBAATAR DISTRICT",
    "City": "ULAANBAATAR",
    "Branch": "",
    "Postcode": "14200",
    "Country": "Mongolia",
    "Connection": "Active"
  }
]
module.exports = mongolia
