const montenegro = [
  {
    "countryCode": "HAAB",
    "bankCode": "ME",
    "branchCode": "EPG",
    "SWIFT Code": "HAABMEPG",
    "Bank Name": "ADDIKO BANK A.D. PODGORICA",
    "Address": "BULEVAR DZORDZA VASINGTONA 98",
    "City": "PODGORICA",
    "Branch": "",
    "Postcode": "81000",
    "Country": "Montenegro",
    "Connection": "Active"
  },
  {
    "countryCode": "AZMN",
    "bankCode": "ME",
    "branchCode": "EPG",
    "SWIFT Code": "AZMNMEPG",
    "Bank Name": "ADRIATIC BANK AD PODGORICA",
    "Address": "DZORDZA VASINGTONA 8, 98, THE CAPITAL PLAZA",
    "City": "PODGORICA",
    "Branch": "",
    "Postcode": "81000",
    "Country": "Montenegro",
    "Connection": "Active"
  },
  {
    "countryCode": "CBCG",
    "bankCode": "ME",
    "branchCode": "EPG",
    "SWIFT Code": "CBCGMEPG",
    "Bank Name": "CENTRALNA BANKA CRNE GORE (CENTRAL BANK OF MONTENEGRO)",
    "Address": "BLVD SVETOG PETRA CETINJSKOG 6",
    "City": "PODGORICA",
    "Branch": "",
    "Postcode": "81000",
    "Country": "Montenegro",
    "Connection": "Active"
  },
  {
    "countryCode": "CKBC",
    "bankCode": "ME",
    "branchCode": "EPG",
    "SWIFT Code": "CKBCMEPG",
    "Bank Name": "CRNOGORSKA KOMERCIJALNA BANKA AD PODGORICA",
    "Address": "MARKSA I ENGELSA BB",
    "City": "PODGORICA",
    "Branch": "",
    "Postcode": "81000",
    "Country": "Montenegro",
    "Connection": "Active"
  },
  {
    "countryCode": "OPPO",
    "bankCode": "ME",
    "branchCode": "EPG",
    "SWIFT Code": "OPPOMEPG",
    "Bank Name": "ERSTE BANK AD PODGORICA",
    "Address": "ARSENIJA BOLJEVICA 2A",
    "City": "PODGORICA",
    "Branch": "",
    "Postcode": "81000",
    "Country": "Montenegro",
    "Connection": "Active"
  },
  {
    "countryCode": "HBBA",
    "bankCode": "ME",
    "branchCode": "EPG",
    "SWIFT Code": "HBBAMEPG",
    "Bank Name": "HIPOTEKARNA BANKA AD",
    "Address": "JOSIPA BROZA TITA 67, ROKSPED",
    "City": "PODGORICA",
    "Branch": "",
    "Postcode": "81000",
    "Country": "Montenegro",
    "Connection": "Active"
  },
  {
    "countryCode": "LOVB",
    "bankCode": "ME",
    "branchCode": "EPG",
    "SWIFT Code": "LOVBMEPG",
    "Bank Name": "LOVCEN BANKA AD",
    "Address": "BULEVAR DZORDZA VASINGTONA 56",
    "City": "PODGORICA",
    "Branch": "",
    "Postcode": "81000",
    "Country": "Montenegro",
    "Connection": "Active"
  },
  {
    "countryCode": "MNBA",
    "bankCode": "ME",
    "branchCode": "EPG",
    "SWIFT Code": "MNBAMEPG",
    "Bank Name": "NLB BANKA AD PODGORICA",
    "Address": "BUL. STANKA DRAGOJEVICA 43",
    "City": "PODGORICA",
    "Branch": "",
    "Postcode": "81000",
    "Country": "Montenegro",
    "Connection": "Active"
  },
  {
    "countryCode": "PRVA",
    "bankCode": "ME",
    "branchCode": "EPG",
    "SWIFT Code": "PRVAMEPG",
    "Bank Name": "PRVA BANKA CRNE GORE AD",
    "Address": "CETINJSKI PUT BB",
    "City": "PODGORICA",
    "Branch": "",
    "Postcode": "81000",
    "Country": "Montenegro",
    "Connection": "Active"
  },
  {
    "countryCode": "UNCB",
    "bankCode": "ME",
    "branchCode": "EPG",
    "SWIFT Code": "UNCBMEPG",
    "Bank Name": "UNIVERSAL CAPITAL BANK",
    "Address": "STANKA DRAGOJEVICA BB",
    "City": "PODGORICA",
    "Branch": "",
    "Postcode": "81000",
    "Country": "Montenegro",
    "Connection": "Active"
  },
  {
    "countryCode": "ZBCG",
    "bankCode": "ME",
    "branchCode": "EPG",
    "SWIFT Code": "ZBCGMEPG",
    "Bank Name": "ZAPAD BANKA AD PODGORICA",
    "Address": "MOSKOVSKA 42, VEKTRA",
    "City": "PODGORICA",
    "Branch": "",
    "Postcode": "81000",
    "Country": "Montenegro",
    "Connection": "Active"
  },
  {
    "countryCode": "TCZB",
    "bankCode": "ME",
    "branchCode": "EPG",
    "SWIFT Code": "TCZBMEPG",
    "Bank Name": "ZIRAAT BANK MONTENEGRO",
    "Address": "ULICA SLOBODE 17, FLOOR 2",
    "City": "PODGORICA",
    "Branch": "",
    "Postcode": "81000",
    "Country": "Montenegro",
    "Connection": "Active"
  }
]
module.exports = montenegro
