const morocco = [
  {
    "countryCode": "ABBM",
    "bankCode": "MA",
    "branchCode": "AMC",
    "SWIFT Code": "ABBMMAMC",
    "Bank Name": "AL BARID BANK",
    "Address": "ANGLE BOULEVARD GHANDI ET, BOULEVARD ROUDANI",
    "City": "CASABLANCA",
    "Branch": "",
    "Postcode": "20100",
    "Country": "Morocco",
    "Connection": "Active"
  },
  {
    "countryCode": "ARAB",
    "bankCode": "MA",
    "branchCode": "250",
    "SWIFT Code": "ARABMAMC250",
    "Bank Name": "ARAB BANK PLC",
    "Address": "GUELIZ, PLACE DE LA LIBERTE, MOULAY EL HASSAN BLD",
    "City": "MARRAKESH",
    "Branch": "MARRAKECH BRANCH",
    "Postcode": "40000",
    "Country": "Morocco",
    "Connection": "Active"
  },
  {
    "countryCode": "ARAB",
    "bankCode": "MA",
    "branchCode": "260",
    "SWIFT Code": "ARABMAMC260",
    "Bank Name": "ARAB BANK PLC.",
    "Address": "",
    "City": "AGADIR",
    "Branch": "",
    "Postcode": "80000",
    "Country": "Morocco",
    "Connection": "Active"
  },
  {
    "countryCode": "ARAB",
    "bankCode": "MA",
    "branchCode": "AMC",
    "SWIFT Code": "ARABMAMC",
    "Bank Name": "ARAB BANK PLC.",
    "Address": "174 BOULEVARD MOHAMMED V",
    "City": "CASABLANCA",
    "Branch": "",
    "Postcode": "20000",
    "Country": "Morocco",
    "Connection": "Active"
  },
  {
    "countryCode": "ARAB",
    "bankCode": "MA",
    "branchCode": "210",
    "SWIFT Code": "ARABMAMC210",
    "Bank Name": "ARAB BANK PLC.",
    "Address": "",
    "City": "CASABLANCA",
    "Branch": "MAIN BRANCH",
    "Postcode": "",
    "Country": "Morocco",
    "Connection": "Active"
  },
  {
    "countryCode": "ARAB",
    "bankCode": "MA",
    "branchCode": "240",
    "SWIFT Code": "ARABMAMC240",
    "Bank Name": "ARAB BANK PLC.",
    "Address": "57 BOULEVARD MOHAMMED SLAOVI",
    "City": "FES",
    "Branch": "",
    "Postcode": "30000",
    "Country": "Morocco",
    "Connection": "Active"
  },
  {
    "countryCode": "ARAB",
    "bankCode": "MA",
    "branchCode": "220",
    "SWIFT Code": "ARABMAMC220",
    "Bank Name": "ARAB BANK PLC.",
    "Address": "2 AVENUE ALLAL BEN ABDELLAH",
    "City": "RABAT",
    "Branch": "",
    "Postcode": "20000",
    "Country": "Morocco",
    "Connection": "Active"
  },
  {
    "countryCode": "ARAB",
    "bankCode": "MA",
    "branchCode": "221",
    "SWIFT Code": "ARABMAMC221",
    "Bank Name": "ARAB BANK PLC.",
    "Address": "",
    "City": "RABAT",
    "Branch": "AGDAL BRANCH",
    "Postcode": "",
    "Country": "Morocco",
    "Connection": "Active"
  },
  {
    "countryCode": "ARAB",
    "bankCode": "MA",
    "branchCode": "230",
    "SWIFT Code": "ARABMAMC230",
    "Bank Name": "ARAB BANK PLC.",
    "Address": "43 BOULEVARD MOHAMMED V",
    "City": "TANGER",
    "Branch": "",
    "Postcode": "10000",
    "Country": "Morocco",
    "Connection": "Active"
  },
  {
    "countryCode": "AIBS",
    "bankCode": "MA",
    "branchCode": "AMT",
    "SWIFT Code": "AIBSMAMT",
    "Bank Name": "ATTIJARI INTERNATIONAL BANK S.A. - BANQUE OFF SHORE",
    "Address": "58 BOULEVARD PASTEUR",
    "City": "TANGER",
    "Branch": "",
    "Postcode": "90000",
    "Country": "Morocco",
    "Connection": "Active"
  },
  {
    "countryCode": "BCMA",
    "bankCode": "MA",
    "branchCode": "AMC",
    "SWIFT Code": "BCMAMAMC",
    "Bank Name": "ATTIJARIWAFA BANK (FORMERLY BANQUE COMMERCIALE DU MAROC)",
    "Address": "2 BOULEVARD MOULAY YOUSSEF",
    "City": "CASABLANCA",
    "Branch": "",
    "Postcode": "20000",
    "Country": "Morocco",
    "Connection": "Active"
  },
  {
    "countryCode": "BCMA",
    "bankCode": "MA",
    "branchCode": "ATI",
    "SWIFT Code": "BCMAMAMCATI",
    "Bank Name": "ATTIJARIWAFA BANK (FORMERLY BANQUE COMMERCIALE DU MAROC)",
    "Address": "",
    "City": "CASABLANCA",
    "Branch": "ATTIJARI INTERMEDIATION",
    "Postcode": "",
    "Country": "Morocco",
    "Connection": "Active"
  },
  {
    "countryCode": "BCMA",
    "bankCode": "MA",
    "branchCode": "BAS",
    "SWIFT Code": "BCMAMAMCBAS",
    "Bank Name": "ATTIJARIWAFA BANK (FORMERLY BANQUE COMMERCIALE DU MAROC)",
    "Address": "19 BOULEVARD ABDELMOUMEN",
    "City": "CASABLANCA",
    "Branch": "BCMAMAMCBAS",
    "Postcode": "20100",
    "Country": "Morocco",
    "Connection": "Active"
  },
  {
    "countryCode": "BCMA",
    "bankCode": "MA",
    "branchCode": "DEV",
    "SWIFT Code": "BCMAMAMCDEV",
    "Bank Name": "ATTIJARIWAFA BANK (FORMERLY BANQUE COMMERCIALE DU MAROC)",
    "Address": "",
    "City": "CASABLANCA",
    "Branch": "BRANCH CTN DEVISE",
    "Postcode": "",
    "Country": "Morocco",
    "Connection": "Active"
  },
  {
    "countryCode": "BSAB",
    "bankCode": "MA",
    "branchCode": "AMC",
    "SWIFT Code": "BSABMAMC",
    "Bank Name": "BANCO DE SABADELL, S.A.",
    "Address": "FLOOR 12, TOUR OUEST, ANGLE BDS ZERKTOUNI AL MASSIRA",
    "City": "CASABLANCA",
    "Branch": "",
    "Postcode": "20100",
    "Country": "Morocco",
    "Connection": "Active"
  },
  {
    "countryCode": "BKAM",
    "bankCode": "MA",
    "branchCode": "AMR",
    "SWIFT Code": "BKAMMAMR",
    "Bank Name": "BANK AL-MAGHRIB",
    "Address": "277 AVENUE MOHAMMED V",
    "City": "RABAT",
    "Branch": "",
    "Postcode": "11100",
    "Country": "Morocco",
    "Connection": "Active"
  },
  {
    "countryCode": "ASSF",
    "bankCode": "MA",
    "branchCode": "AMC",
    "SWIFT Code": "ASSFMAMC",
    "Bank Name": "BANK ASSAFA",
    "Address": "19 BOULEVARD ABDELMOUMEN",
    "City": "CASABLANCA",
    "Branch": "",
    "Postcode": "20000",
    "Country": "Morocco",
    "Connection": "Active"
  },
  {
    "countryCode": "BMCE",
    "bankCode": "MA",
    "branchCode": "BTI",
    "SWIFT Code": "BMCEMAMCBTI",
    "Bank Name": "BANK OF AFRICA",
    "Address": "140 AVENUE HASSAN II",
    "City": "CASABLANCA",
    "Branch": "",
    "Postcode": "20000",
    "Country": "Morocco",
    "Connection": "Active"
  },
  {
    "countryCode": "BMCE",
    "bankCode": "MA",
    "branchCode": "AMC",
    "SWIFT Code": "BMCEMAMC",
    "Bank Name": "BANK OF AFRICA",
    "Address": "140 AVENUE HASSAN II",
    "City": "CASABLANCA",
    "Branch": "",
    "Postcode": "20000",
    "Country": "Morocco",
    "Connection": "Active"
  },
  {
    "countryCode": "BMCE",
    "bankCode": "MA",
    "branchCode": "COR",
    "SWIFT Code": "BMCEMAMCCOR",
    "Bank Name": "BANK OF AFRICA",
    "Address": "140 AVENUE HASSAN II",
    "City": "CASABLANCA",
    "Branch": "AGENCE CORPORATE",
    "Postcode": "20000",
    "Country": "Morocco",
    "Connection": "Active"
  },
  {
    "countryCode": "BMCE",
    "bankCode": "MA",
    "branchCode": "BCB",
    "SWIFT Code": "BMCEMAMCBCB",
    "Bank Name": "BANK OF AFRICA",
    "Address": "140 AVENUE HASSAN II",
    "City": "CASABLANCA",
    "Branch": "BMCE CAPITAL",
    "Postcode": "20000",
    "Country": "Morocco",
    "Connection": "Active"
  },
  {
    "countryCode": "BMCE",
    "bankCode": "MA",
    "branchCode": "MRE",
    "SWIFT Code": "BMCEMAMCMRE",
    "Bank Name": "BANK OF AFRICA",
    "Address": "140 AVENUE HASSAN II",
    "City": "CASABLANCA",
    "Branch": "COMPTE SPECIAL MRE",
    "Postcode": "20250",
    "Country": "Morocco",
    "Connection": "Active"
  },
  {},
  {
    "countryCode": "BMCE",
    "bankCode": "MA",
    "branchCode": "TCM",
    "SWIFT Code": "BMCEMAMCTCM",
    "Bank Name": "BANK OF AFRICA",
    "Address": "ZONE FRANCE DE TANGER",
    "City": "TANGER",
    "Branch": "OFFSHORE BRANCH TRADING ROOM, TANGIER",
    "Postcode": "90024",
    "Country": "Morocco",
    "Connection": "Active"
  },
  {
    "countryCode": "BMCE",
    "bankCode": "MA",
    "branchCode": "TZF",
    "SWIFT Code": "BMCEMAMCTZF",
    "Bank Name": "BANK OF AFRICA",
    "Address": "ZONE FRANCE PORT DE TANGER",
    "City": "TANGER",
    "Branch": "OFFSHORE BRANCH, TANGIER",
    "Postcode": "90024",
    "Country": "Morocco",
    "Connection": "Active"
  },
  {
    "countryCode": "BCPO",
    "bankCode": "MA",
    "branchCode": "AMC",
    "SWIFT Code": "BCPOMAMC",
    "Bank Name": "BANQUE CENTRALE POPULAIRE",
    "Address": "101 BOULEVARD ZERKTOUNI",
    "City": "CASABLANCA",
    "Branch": "",
    "Postcode": "10622",
    "Country": "Morocco",
    "Connection": "Active"
  },
  {
    "countryCode": "BCPO",
    "bankCode": "MA",
    "branchCode": "BKO",
    "SWIFT Code": "BCPOMAMCBKO",
    "Bank Name": "BANQUE CENTRALE POPULAIRE",
    "Address": "",
    "City": "CASABLANCA",
    "Branch": "DEPT. BACK OFFICE",
    "Postcode": "",
    "Country": "Morocco",
    "Connection": "Active"
  },
  {
    "countryCode": "BCPO",
    "bankCode": "MA",
    "branchCode": "MON",
    "SWIFT Code": "BCPOMAMCMON",
    "Bank Name": "BANQUE CENTRALE POPULAIRE",
    "Address": "",
    "City": "CASABLANCA",
    "Branch": "DEPT. MONETIQUES",
    "Postcode": "",
    "Country": "Morocco",
    "Connection": "Active"
  },
  {
    "countryCode": "BCPO",
    "bankCode": "MA",
    "branchCode": "REC",
    "SWIFT Code": "BCPOMAMCREC",
    "Bank Name": "BANQUE CENTRALE POPULAIRE",
    "Address": "",
    "City": "CASABLANCA",
    "Branch": "DEPT. RECONCILIATION",
    "Postcode": "",
    "Country": "Morocco",
    "Connection": "Active"
  },
  {
    "countryCode": "BCPO",
    "bankCode": "MA",
    "branchCode": "DOC",
    "SWIFT Code": "BCPOMAMCDOC",
    "Bank Name": "BANQUE CENTRALE POPULAIRE",
    "Address": "",
    "City": "CASABLANCA",
    "Branch": "SCE. DOCUMENTAIRE",
    "Postcode": "",
    "Country": "Morocco",
    "Connection": "Active"
  },
  {
    "countryCode": "BCPO",
    "bankCode": "MA",
    "branchCode": "FIN",
    "SWIFT Code": "BCPOMAMCFIN",
    "Bank Name": "BANQUE CENTRALE POPULAIRE",
    "Address": "",
    "City": "CASABLANCA",
    "Branch": "SCE. FINANCIER",
    "Postcode": "",
    "Country": "Morocco",
    "Connection": "Active"
  },
  {
    "countryCode": "BCPO",
    "bankCode": "MA",
    "branchCode": "MRE",
    "SWIFT Code": "BCPOMAMCMRE",
    "Bank Name": "BANQUE CENTRALE POPULAIRE",
    "Address": "",
    "City": "CASABLANCA",
    "Branch": "TRANFERTS DES MAROCAINS RESIDANTS A L'ETRANGER",
    "Postcode": "",
    "Country": "Morocco",
    "Connection": "Active"
  },
  {
    "countryCode": "BCPO",
    "bankCode": "MA",
    "branchCode": "YSR",
    "SWIFT Code": "BCPOMAMCYSR",
    "Bank Name": "BANQUE CENTRALE POPULAIRE",
    "Address": "MADO, 162 ANGLE RUE MOLIERE ET BOULEVARD",
    "City": "CASABLANCA",
    "Branch": "YSR",
    "Postcode": "20050",
    "Country": "Morocco",
    "Connection": "Active"
  },
  {
    "countryCode": "BCPO",
    "bankCode": "MA",
    "branchCode": "CIB",
    "SWIFT Code": "BCPOMAMCCIB",
    "Bank Name": "BANQUE CENTRALE POPULAIRE",
    "Address": "ZONE FRANCHE D EXPORTATION",
    "City": "TANGER",
    "Branch": "OFFSHORE BRANCH, TANGIER",
    "Postcode": "90100",
    "Country": "Morocco",
    "Connection": "Active"
  },
  {
    "countryCode": "BMCI",
    "bankCode": "MA",
    "branchCode": "AMC",
    "SWIFT Code": "BMCIMAMC",
    "Bank Name": "BANQUE MAROCAINE POUR LE COMMERCE ET L'INDUSTRIE",
    "Address": "26 PLACE MOHAMMED V",
    "City": "CASABLANCA",
    "Branch": "",
    "Postcode": "21000",
    "Country": "Morocco",
    "Connection": "Active"
  },
  {
    "countryCode": "BMCI",
    "bankCode": "MA",
    "branchCode": "NFP",
    "SWIFT Code": "BMCIMAMCNFP",
    "Bank Name": "BANQUE MAROCAINE POUR LE COMMERCE ET L'INDUSTRIE",
    "Address": "26 PLACE DES NATIONS UNIES",
    "City": "CASABLANCA",
    "Branch": "BMCI FINANCE PARTICIPATIVE",
    "Postcode": "20000",
    "Country": "Morocco",
    "Connection": "Active"
  },
  {
    "countryCode": "BMCI",
    "bankCode": "MA",
    "branchCode": "TOF",
    "SWIFT Code": "BMCIMAMCTOF",
    "Bank Name": "BANQUE MAROCAINE POUR LE COMMERCE ET L'INDUSTRIE",
    "Address": "ANGLE BOULEVARD YOUSSEF BEN, TACHFINE ET RUE MADRID",
    "City": "TANGER",
    "Branch": "OFFSHORE BRANCH",
    "Postcode": "90000",
    "Country": "Morocco",
    "Connection": "Active"
  },
  {
    "countryCode": "BCPO",
    "bankCode": "MA",
    "branchCode": "CES",
    "SWIFT Code": "BCPOMAMCCES",
    "Bank Name": "BANQUE POPULAIRE AGADIR",
    "Address": "BOULEVARD HASSAN II",
    "City": "AGADIR",
    "Branch": "",
    "Postcode": "80000",
    "Country": "Morocco",
    "Connection": "Active"
  },
  {
    "countryCode": "BCPO",
    "bankCode": "MA",
    "branchCode": "ALH",
    "SWIFT Code": "BCPOMAMCALH",
    "Bank Name": "BANQUE POPULAIRE AL HOCEIMA",
    "Address": "88-90 BOULEVARD MOHAMED V",
    "City": "AL HOCEIMA",
    "Branch": "",
    "Postcode": "32000",
    "Country": "Morocco",
    "Connection": "Active"
  },
  {
    "countryCode": "BCPO",
    "bankCode": "MA",
    "branchCode": "BNM",
    "SWIFT Code": "BCPOMAMCBNM",
    "Bank Name": "BANQUE POPULAIRE BENI MELLAL",
    "Address": "287 BOULEVARD MOHAMED V",
    "City": "BENI MELLAL",
    "Branch": "",
    "Postcode": "23000",
    "Country": "Morocco",
    "Connection": "Active"
  },
  {
    "countryCode": "BCPO",
    "bankCode": "MA",
    "branchCode": "BRK",
    "SWIFT Code": "BCPOMAMCBRK",
    "Bank Name": "BANQUE POPULAIRE BERKANE",
    "Address": "7 BOULEVARD IDRISS 1ER",
    "City": "BERKANE",
    "Branch": "",
    "Postcode": "25004",
    "Country": "Morocco",
    "Connection": "Active"
  },
  {
    "countryCode": "BCPO",
    "bankCode": "MA",
    "branchCode": "CAS",
    "SWIFT Code": "BCPOMAMCCAS",
    "Bank Name": "BANQUE POPULAIRE CASA-ANFA",
    "Address": "",
    "City": "CASABLANCA",
    "Branch": "",
    "Postcode": "",
    "Country": "Morocco",
    "Connection": "Active"
  },
  {
    "countryCode": "BCPO",
    "bankCode": "MA",
    "branchCode": "ELJ",
    "SWIFT Code": "BCPOMAMCELJ",
    "Bank Name": "BANQUE POPULAIRE EL JADIDA",
    "Address": "22-23 BIS BOULEVARD ENNAKHIL",
    "City": "EL JADIDA",
    "Branch": "",
    "Postcode": "24000",
    "Country": "Morocco",
    "Connection": "Active"
  },
  {
    "countryCode": "BCPO",
    "bankCode": "MA",
    "branchCode": "FES",
    "SWIFT Code": "BCPOMAMCFES",
    "Bank Name": "BANQUE POPULAIRE FES",
    "Address": "ANGLE RUE LOUDIYI A BENCH",
    "City": "FES",
    "Branch": "",
    "Postcode": "30000",
    "Country": "Morocco",
    "Connection": "Active"
  },
  {
    "countryCode": "BCPO",
    "bankCode": "MA",
    "branchCode": "GHA",
    "SWIFT Code": "BCPOMAMCGHA",
    "Bank Name": "BANQUE POPULAIRE GHARB",
    "Address": "53 AVENUE AL ISTIQLAL",
    "City": "KENITRA",
    "Branch": "",
    "Postcode": "14000",
    "Country": "Morocco",
    "Connection": "Active"
  },
  {
    "countryCode": "BCPO",
    "bankCode": "MA",
    "branchCode": "LAY",
    "SWIFT Code": "BCPOMAMCLAY",
    "Bank Name": "BANQUE POPULAIRE LAAYOUNE",
    "Address": "9 BOULEVARD MOHAMED V",
    "City": "LAAYOUNE",
    "Branch": "",
    "Postcode": "70000",
    "Country": "Morocco",
    "Connection": "Active"
  },
  {
    "countryCode": "BCPO",
    "bankCode": "MA",
    "branchCode": "MKH",
    "SWIFT Code": "BCPOMAMCMKH",
    "Bank Name": "BANQUE POPULAIRE MARRAKECH",
    "Address": "AVENUE A KHETTABI",
    "City": "MARRAKESH",
    "Branch": "",
    "Postcode": "44000",
    "Country": "Morocco",
    "Connection": "Active"
  },
  {
    "countryCode": "BCPO",
    "bankCode": "MA",
    "branchCode": "MEK",
    "SWIFT Code": "BCPOMAMCMEK",
    "Bank Name": "BANQUE POPULAIRE MEKNES",
    "Address": "4 RUE ALEXANDRIE",
    "City": "MEKNES",
    "Branch": "",
    "Postcode": "50000",
    "Country": "Morocco",
    "Connection": "Active"
  },
  {
    "countryCode": "BCPO",
    "bankCode": "MA",
    "branchCode": "NAD",
    "SWIFT Code": "BCPOMAMCNAD",
    "Bank Name": "BANQUE POPULAIRE NADOR",
    "Address": "113 BOULEVARD AL MASSIRA",
    "City": "NADOR",
    "Branch": "",
    "Postcode": "26003",
    "Country": "Morocco",
    "Connection": "Active"
  },
  {
    "countryCode": "BCPO",
    "bankCode": "MA",
    "branchCode": "OUJ",
    "SWIFT Code": "BCPOMAMCOUJ",
    "Bank Name": "BANQUE POPULAIRE OUJDA",
    "Address": "BOULEVARD IDRISS AL AKBAR",
    "City": "OUJDA",
    "Branch": "",
    "Postcode": "60000",
    "Country": "Morocco",
    "Connection": "Active"
  },
  {
    "countryCode": "BCPO",
    "bankCode": "MA",
    "branchCode": "RAB",
    "SWIFT Code": "BCPOMAMCRAB",
    "Bank Name": "BANQUE POPULAIRE RABAT",
    "Address": "3 AVENUE TRABLESS",
    "City": "RABAT",
    "Branch": "",
    "Postcode": "10000",
    "Country": "Morocco",
    "Connection": "Active"
  },
  {
    "countryCode": "BCPO",
    "bankCode": "MA",
    "branchCode": "SAF",
    "SWIFT Code": "BCPOMAMCSAF",
    "Bank Name": "BANQUE POPULAIRE SAFI",
    "Address": "PLACE MOHAMED V",
    "City": "SAFI",
    "Branch": "",
    "Postcode": "46000",
    "Country": "Morocco",
    "Connection": "Active"
  },
  {
    "countryCode": "BCPO",
    "bankCode": "MA",
    "branchCode": "TAT",
    "SWIFT Code": "BCPOMAMCTAT",
    "Bank Name": "BANQUE POPULAIRE TANGER",
    "Address": "73 BOULEVARD MOHAMED V",
    "City": "TANGER",
    "Branch": "",
    "Postcode": "90000",
    "Country": "Morocco",
    "Connection": "Active"
  },
  {
    "countryCode": "MEDC",
    "bankCode": "MA",
    "branchCode": "AMC",
    "SWIFT Code": "MEDCMAMC",
    "Bank Name": "BCP SECURITIES SERVICES",
    "Address": "27 BOULEVARD MOULAY YOUSSEF",
    "City": "CASABLANCA",
    "Branch": "",
    "Postcode": "20060",
    "Country": "Morocco",
    "Connection": "Active"
  },
  {
    "countryCode": "CADG",
    "bankCode": "MA",
    "branchCode": "AMR",
    "SWIFT Code": "CADGMAMR",
    "Bank Name": "CAISSE DE DEPOT ET DE GESTION",
    "Address": "PLACE MY EL HASSAN",
    "City": "RABAT",
    "Branch": "",
    "Postcode": "10050",
    "Country": "Morocco",
    "Connection": "Active"
  },
  {
    "countryCode": "CAIX",
    "bankCode": "MA",
    "branchCode": "AMC",
    "SWIFT Code": "CAIXMAMC",
    "Bank Name": "CAIXABANK, S.A. SUCCURSALE AU MAROC",
    "Address": "179 BOULEVARD D'ANFA",
    "City": "CASABLANCA",
    "Branch": "",
    "Postcode": "20100",
    "Country": "Morocco",
    "Connection": "Active"
  },
  {
    "countryCode": "RDGC",
    "bankCode": "MA",
    "branchCode": "AMR",
    "SWIFT Code": "RDGCMAMR",
    "Bank Name": "CDG CAPITAL",
    "Address": "MAMOUNIA, PLACE MY EL HASSAN",
    "City": "RABAT",
    "Branch": "",
    "Postcode": "10050",
    "Country": "Morocco",
    "Connection": "Active"
  },
  {
    "countryCode": "CAFG",
    "bankCode": "MA",
    "branchCode": "AMC",
    "SWIFT Code": "CAFGMAMC",
    "Bank Name": "CFG BANK",
    "Address": "5 RUE IBNOU TOUFAIL PALMIER",
    "City": "CASABLANCA",
    "Branch": "",
    "Postcode": "20100",
    "Country": "Morocco",
    "Connection": "Active"
  },
  {
    "countryCode": "CAFG",
    "bankCode": "MA",
    "branchCode": "CFM",
    "SWIFT Code": "CAFGMAMCCFM",
    "Bank Name": "CFG BANK",
    "Address": "5 RUE IBNOU TOUFAIL PALMIER",
    "City": "CASABLANCA",
    "Branch": "CFG MARCHE",
    "Postcode": "20100",
    "Country": "Morocco",
    "Connection": "Active"
  },
  {
    "countryCode": "CITI",
    "bankCode": "MA",
    "branchCode": "AMC",
    "SWIFT Code": "CITIMAMC",
    "Bank Name": "CITIBANK MAGHREB",
    "Address": "IMMEUBLE 1, ZENITH MILLENIUM, SIDI MAAROUF",
    "City": "CASABLANCA",
    "Branch": "",
    "Postcode": "20190",
    "Country": "Morocco",
    "Connection": "Active"
  },
  {
    "countryCode": "CITI",
    "bankCode": "MA",
    "branchCode": "TRD",
    "SWIFT Code": "CITIMAMCTRD",
    "Bank Name": "CITIBANK MAGHREB",
    "Address": "52 AVENUE HASSAN II",
    "City": "CASABLANCA",
    "Branch": "TRADE SERVICES DEPARTMENT",
    "Postcode": "20250",
    "Country": "Morocco",
    "Connection": "Active"
  },
  {
    "countryCode": "RAMS",
    "bankCode": "MA",
    "branchCode": "AMC",
    "SWIFT Code": "RAMSMAMC",
    "Bank Name": "COMPAGNIE NATIONALE ROYAL AIR MAROC",
    "Address": "AEROPORT CASA, BD ABDELLAH BENCHRIF, ANFA",
    "City": "CASABLANCA",
    "Branch": "",
    "Postcode": "20000",
    "Country": "Morocco",
    "Connection": "Active"
  },
  {
    "countryCode": "CNCA",
    "bankCode": "MA",
    "branchCode": "AMR",
    "SWIFT Code": "CNCAMAMR",
    "Bank Name": "CREDIT AGRICOLE DU MAROC",
    "Address": "49 PLACE DES ALAOUITES BP",
    "City": "RABAT",
    "Branch": "",
    "Postcode": "10000",
    "Country": "Morocco",
    "Connection": "Active"
  },
  {
    "countryCode": "CNCA",
    "bankCode": "MA",
    "branchCode": "AAB",
    "SWIFT Code": "CNCAMAMRAAB",
    "Bank Name": "CREDIT AGRICOLE DU MAROC",
    "Address": "ANGLE AVENUE D'ALGER, RUE D'ORAN",
    "City": "RABAT",
    "Branch": "AL AKHDAR BRANCH",
    "Postcode": "10020",
    "Country": "Morocco",
    "Connection": "Active"
  },
  {
    "countryCode": "CDMA",
    "bankCode": "MA",
    "branchCode": "706",
    "SWIFT Code": "CDMAMAMC706",
    "Bank Name": "CREDIT DU MAROC",
    "Address": "IMMEUBLE MARHABA ANGLE AV 29, FEVRIER ET BD MOHAMED CHEIKH SAADI, QUARTIER TALBORJT",
    "City": "AGADIR",
    "Branch": "TRADE CENTER TALBORJT",
    "Postcode": "80030",
    "Country": "Morocco",
    "Connection": "Active"
  },
  {
    "countryCode": "CDMA",
    "bankCode": "MA",
    "branchCode": "702",
    "SWIFT Code": "CDMAMAMC702",
    "Bank Name": "CREDIT DU MAROC",
    "Address": "TRADE CENTER NOUVEL HORIZON, 146 BD EMILE ZOLA ET RUE RETHEL",
    "City": "CASABLANCA",
    "Branch": "",
    "Postcode": "20310",
    "Country": "Morocco",
    "Connection": "Active"
  },
  {
    "countryCode": "CDMA",
    "bankCode": "MA",
    "branchCode": "701",
    "SWIFT Code": "CDMAMAMC701",
    "Bank Name": "CREDIT DU MAROC",
    "Address": "TRADE CENTER ESSALAM, 262 BD YACOUB AL MANSOUR",
    "City": "CASABLANCA",
    "Branch": "",
    "Postcode": "20250",
    "Country": "Morocco",
    "Connection": "Active"
  },
  {
    "countryCode": "CDMA",
    "bankCode": "MA",
    "branchCode": "PAR",
    "SWIFT Code": "CDMAMAMCPAR",
    "Bank Name": "CREDIT DU MAROC",
    "Address": "48-58 BOULEVARD MOHAMMED V",
    "City": "CASABLANCA",
    "Branch": "ACTIVITES ET OPERATIONS PARTICIPATIVES",
    "Postcode": "20250",
    "Country": "Morocco",
    "Connection": "Active"
  },
  {
    "countryCode": "CDMA",
    "bankCode": "MA",
    "branchCode": "AMC",
    "SWIFT Code": "CDMAMAMC",
    "Bank Name": "CREDIT DU MAROC",
    "Address": "48-58 BOULEVARD MOHAMMED V",
    "City": "CASABLANCA",
    "Branch": "ALL MOROCCO BRANCHES",
    "Postcode": "20250",
    "Country": "Morocco",
    "Connection": "Active"
  },
  {
    "countryCode": "CDMA",
    "bankCode": "MA",
    "branchCode": "COS",
    "SWIFT Code": "CDMAMAMCCOS",
    "Bank Name": "CREDIT DU MAROC",
    "Address": "48-58 BOULEVARD MOHAMMED V",
    "City": "CASABLANCA",
    "Branch": "OFFSHORE SERVICES",
    "Postcode": "20250",
    "Country": "Morocco",
    "Connection": "Active"
  },
  {
    "countryCode": "CDMA",
    "bankCode": "MA",
    "branchCode": "703",
    "SWIFT Code": "CDMAMAMC703",
    "Bank Name": "CREDIT DU MAROC",
    "Address": "TRADE CENTER CENTRE-VILLE, 48-58 BD. MOHAMMED V",
    "City": "CASABLANCA",
    "Branch": "TRADE CENTER CENTRE-VILLE",
    "Postcode": "20250",
    "Country": "Morocco",
    "Connection": "Active"
  },
  {
    "countryCode": "CDMA",
    "bankCode": "MA",
    "branchCode": "700",
    "SWIFT Code": "CDMAMAMC700",
    "Bank Name": "CREDIT DU MAROC",
    "Address": "TRADE CENTER EXPANSION, 7 300 ROUTE DE RABAT",
    "City": "CASABLANCA",
    "Branch": "TRADE CENTER EXPANSION",
    "Postcode": "20250",
    "Country": "Morocco",
    "Connection": "Active"
  },
  {
    "countryCode": "CDMA",
    "bankCode": "MA",
    "branchCode": "707",
    "SWIFT Code": "CDMAMAMC707",
    "Bank Name": "CREDIT DU MAROC",
    "Address": "RESIDENCE TARIK, AVENUE DU ROI HOUSSEIN DE JORDANIE",
    "City": "FES",
    "Branch": "TRADE CENTER QUARAOUYINE",
    "Postcode": "30000",
    "Country": "Morocco",
    "Connection": "Active"
  },
  {
    "countryCode": "CDMA",
    "bankCode": "MA",
    "branchCode": "704",
    "SWIFT Code": "CDMAMAMC704",
    "Bank Name": "CREDIT DU MAROC",
    "Address": "176 BD ABDELKRIM EL KHATABI",
    "City": "MARRAKESH",
    "Branch": "TRADE CENTER MENARA",
    "Postcode": "40000",
    "Country": "Morocco",
    "Connection": "Active"
  },
  {
    "countryCode": "CDMA",
    "bankCode": "MA",
    "branchCode": "708",
    "SWIFT Code": "CDMAMAMC708",
    "Bank Name": "CREDIT DU MAROC",
    "Address": "2 BD. ALLAL EL FASSI, DHAR EL M'HALLA",
    "City": "OUJDA",
    "Branch": "TRADE CENTER AL MOUSTAGBAL",
    "Postcode": "60010",
    "Country": "Morocco",
    "Connection": "Active"
  },
  {
    "countryCode": "CDMA",
    "bankCode": "MA",
    "branchCode": "709",
    "SWIFT Code": "CDMAMAMC709",
    "Bank Name": "CREDIT DU MAROC",
    "Address": "21 RUE ALLAL BEN ABDELLAH",
    "City": "RABAT",
    "Branch": "TRADE CENTER CHELLAH",
    "Postcode": "10000",
    "Country": "Morocco",
    "Connection": "Active"
  },
  {
    "countryCode": "CDMA",
    "bankCode": "MA",
    "branchCode": "705",
    "SWIFT Code": "CDMAMAMC705",
    "Bank Name": "CREDIT DU MAROC",
    "Address": "26 LOTISSEMENT HAJ TATARI, QUARTIER SOURIYINE",
    "City": "TANGER",
    "Branch": "TRADE CENTER BOUGHAZ",
    "Postcode": "12000",
    "Country": "Morocco",
    "Connection": "Active"
  },
  {
    "countryCode": "CIHM",
    "bankCode": "MA",
    "branchCode": "AMC",
    "SWIFT Code": "CIHMMAMC",
    "Bank Name": "CREDIT IMMOBILIER ET HOTELIER",
    "Address": "187 AVENUE HASSAN II",
    "City": "CASABLANCA",
    "Branch": "",
    "Postcode": "20000",
    "Country": "Morocco",
    "Connection": "Active"
  },
  {
    "countryCode": "CIHM",
    "bankCode": "MA",
    "branchCode": "DEP",
    "SWIFT Code": "CIHMMAMCDEP",
    "Bank Name": "CREDIT IMMOBILIER ET HOTELIER",
    "Address": "",
    "City": "CASABLANCA",
    "Branch": "DEPARTEMENT ETRANGER",
    "Postcode": "",
    "Country": "Morocco",
    "Connection": "Active"
  },
  {
    "countryCode": "CIHM",
    "bankCode": "MA",
    "branchCode": "SDM",
    "SWIFT Code": "CIHMMAMCSDM",
    "Bank Name": "CREDIT IMMOBILIER ET HOTELIER",
    "Address": "",
    "City": "CASABLANCA",
    "Branch": "SALLE DES MARCHES",
    "Postcode": "",
    "Country": "Morocco",
    "Connection": "Active"
  },
  {
    "countryCode": "CIHM",
    "bankCode": "MA",
    "branchCode": "UBP",
    "SWIFT Code": "CIHMMAMCUBP",
    "Bank Name": "CREDIT IMMOBILIER ET HOTELIER",
    "Address": "187 AVENUE HASSAN II",
    "City": "CASABLANCA",
    "Branch": "UMNIA BANK",
    "Postcode": "20019",
    "Country": "Morocco",
    "Connection": "Active"
  },
  {
    "countryCode": "GOCP",
    "bankCode": "MA",
    "branchCode": "AMC",
    "SWIFT Code": "GOCPMAMC",
    "Bank Name": "GROUPE OCP",
    "Address": "4-2 RUE ABTAL, HAY ERRAHA",
    "City": "CASABLANCA",
    "Branch": "",
    "Postcode": "20200",
    "Country": "Morocco",
    "Connection": "Active"
  },
  {
    "countryCode": "OFCH",
    "bankCode": "MA",
    "branchCode": "AMR",
    "SWIFT Code": "OFCHMAMR",
    "Bank Name": "OFFICE DES CHANGES",
    "Address": "31 AVENUE PATRICE LUMUMBA",
    "City": "RABAT",
    "Branch": "",
    "Postcode": "10000",
    "Country": "Morocco",
    "Connection": "Active"
  },
  {
    "countryCode": "SGMB",
    "bankCode": "MA",
    "branchCode": "PA1",
    "SWIFT Code": "SGMBMAMCPA1",
    "Bank Name": "SOCIETE GENERALE MAROCAINE DE BANQUES",
    "Address": "55 BOULEVARD ABDELMOUMEN",
    "City": "CASABLANCA",
    "Branch": "",
    "Postcode": "21100",
    "Country": "Morocco",
    "Connection": "Active"
  },
  {
    "countryCode": "SGMB",
    "bankCode": "MA",
    "branchCode": "AMC",
    "SWIFT Code": "SGMBMAMC",
    "Bank Name": "SOCIETE GENERALE MAROCAINE DE BANQUES",
    "Address": "55 BOULEVARD ABDELMOUMEN",
    "City": "CASABLANCA",
    "Branch": "",
    "Postcode": "21100",
    "Country": "Morocco",
    "Connection": "Active"
  },
  {
    "countryCode": "SGMB",
    "bankCode": "MA",
    "branchCode": "CMI",
    "SWIFT Code": "SGMBMAMCCMI",
    "Bank Name": "SOCIETE GENERALE MAROCAINE DE BANQUES",
    "Address": "",
    "City": "CASABLANCA",
    "Branch": "CASH MANAGEMENT INTERNATIONAL",
    "Postcode": "",
    "Country": "Morocco",
    "Connection": "Active"
  },
  {
    "countryCode": "SGMB",
    "bankCode": "MA",
    "branchCode": "FCM",
    "SWIFT Code": "SGMBMAMCFCM",
    "Bank Name": "SOCIETE GENERALE MAROCAINE DE BANQUES",
    "Address": "55 BOULEVARD ABDELMOUMEN",
    "City": "CASABLANCA",
    "Branch": "FLUX CASH MANAGEMENT",
    "Postcode": "21100",
    "Country": "Morocco",
    "Connection": "Active"
  },
  {
    "countryCode": "SGMB",
    "bankCode": "MA",
    "branchCode": "SFS",
    "SWIFT Code": "SGMBMAMCSFS",
    "Bank Name": "SOCIETE GENERALE MAROCAINE DE BANQUES",
    "Address": "55 BOULEVARD ABDELMOUMEN",
    "City": "CASABLANCA",
    "Branch": "SECURITIES AND FUNDS SERVICES",
    "Postcode": "21100",
    "Country": "Morocco",
    "Connection": "Active"
  },
  {
    "countryCode": "SGMB",
    "bankCode": "MA",
    "branchCode": "TIT",
    "SWIFT Code": "SGMBMAMCTIT",
    "Bank Name": "SOCIETE GENERALE MAROCAINE DE BANQUES",
    "Address": "55 BOULEVARD ABDELMOUMEN",
    "City": "CASABLANCA",
    "Branch": "SECURITIES SERVICES DEPARTMENT",
    "Postcode": "21100",
    "Country": "Morocco",
    "Connection": "Active"
  },
  {
    "countryCode": "SGTG",
    "bankCode": "MA",
    "branchCode": "AMC",
    "SWIFT Code": "SGTGMAMC",
    "Bank Name": "SOCIETE GENERALE OFFSHORE",
    "Address": "ROUTE DE RABAT, ZONE FRANCHE D'EXPORTATION",
    "City": "TANGER",
    "Branch": "",
    "Postcode": "90100",
    "Country": "Morocco",
    "Connection": "Active"
  },
  {
    "countryCode": "UMNI",
    "bankCode": "MA",
    "branchCode": "AMM",
    "SWIFT Code": "UMNIMAMM",
    "Bank Name": "UMNIA BANK",
    "Address": "397 ROUTE AL JAMIAA EX ROUTE EL, JADIDA",
    "City": "CASABLANCA",
    "Branch": "",
    "Postcode": "20410",
    "Country": "Morocco",
    "Connection": "Active"
  },
  {
    "countryCode": "UMAB",
    "bankCode": "MA",
    "branchCode": "AMC",
    "SWIFT Code": "UMABMAMC",
    "Bank Name": "UNION MAROCAINE DE BANQUES",
    "Address": "36 RUE TAHAR SEBTI",
    "City": "CASABLANCA",
    "Branch": "",
    "Postcode": "20000",
    "Country": "Morocco",
    "Connection": "Active"
  },
  {
    "countryCode": "WACO",
    "bankCode": "MA",
    "branchCode": "AMM",
    "SWIFT Code": "WACOMAMM",
    "Bank Name": "WANA CORPORATE",
    "Address": "2 LOTISSEMENT LA COLINE, SIDI MAAROUF",
    "City": "CASABLANCA",
    "Branch": "",
    "Postcode": "",
    "Country": "Morocco",
    "Connection": "Active"
  }
]
module.exports = morocco
