const mozambique = [
  {
    "bankCode": "ABMZ",
    "countryCode": "MZ",
    "branchCode": "ZMA",
    "SWIFT Code": "ABMZMZMA",
    "Bank Name": "ABSA BANK MOCAMBIQUE,SA",
    "Address": "AVENIDA 25 DE SETEMBRO 1184",
    "City": "MAPUTO",
    "Branch": "",
    "Postcode": "1184",
    "Country": "Mozambique",
    "Connection": "Active"
  },
  {
    "bankCode": "ABNG",
    "countryCode": "MZ",
    "branchCode": "ZMA",
    "SWIFT Code": "ABNGMZMA",
    "Bank Name": "ACCESS BANK MOZAMBIQUE, SA",
    "Address": "BUSINESS TOWELL, RUA DOS DESPORTISTAS 480, FLOOR 18",
    "City": "MAPUTO",
    "Branch": "",
    "Postcode": "1012",
    "Country": "Mozambique",
    "Connection": "Active"
  },
  {
    "bankCode": "BDIG",
    "countryCode": "MZ",
    "branchCode": "ZMA",
    "SWIFT Code": "BDIGMZMA",
    "Bank Name": "BANCO BIG MOCAMBIQUE, S.A.",
    "Address": "RUA DOS DESPORTISTAS 733, JAT 6 - 3",
    "City": "MAPUTO",
    "Branch": "",
    "Postcode": "1106",
    "Country": "Mozambique",
    "Connection": "Active"
  },
  {
    "bankCode": "BMOC",
    "countryCode": "MZ",
    "branchCode": "ZMP",
    "SWIFT Code": "BMOCMZMP",
    "Bank Name": "BANCO DE MOCAMBIQUE",
    "Address": "AVENUE 25 DE SETEMBRO 1695",
    "City": "MAPUTO",
    "Branch": "",
    "Postcode": "",
    "Country": "Mozambique",
    "Connection": "Active"
  },
  {
    "bankCode": "BMOC",
    "countryCode": "MZ",
    "branchCode": "ZMA",
    "SWIFT Code": "BMOCMZMA",
    "Bank Name": "BANCO DE MOCAMBIQUE",
    "Address": "AVENUE 25 DE SETEMBRO 1695",
    "City": "MAPUTO",
    "Branch": "",
    "Postcode": "1695",
    "Country": "Mozambique",
    "Connection": "Active"
  },
  {
    "bankCode": "BIMO",
    "countryCode": "MZ",
    "branchCode": "ZMX",
    "SWIFT Code": "BIMOMZMX",
    "Bank Name": "BANCO INTERNACIONAL DE MOCAMBIQUE, S.A",
    "Address": "AVENIDA 25 DE SETEMBRO 1800",
    "City": "MAPUTO",
    "Branch": "",
    "Postcode": "1800",
    "Country": "Mozambique",
    "Connection": "Active"
  },
  {
    "bankCode": "BIMO",
    "countryCode": "MZ",
    "branchCode": "FIN",
    "SWIFT Code": "BIMOMZMXFIN",
    "Bank Name": "BANCO INTERNACIONAL DE MOCAMBIQUE, S.A",
    "Address": "RUA DOS DESPORTISTAS 873-879/12",
    "City": "MAPUTO",
    "Branch": "DIRECCAO FINANCEIRA",
    "Postcode": "1100",
    "Country": "Mozambique",
    "Connection": "Active"
  },
  {
    "bankCode": "BIMO",
    "countryCode": "MZ",
    "branchCode": "INT",
    "SWIFT Code": "BIMOMZMXINT",
    "Bank Name": "BANCO INTERNACIONAL DE MOCAMBIQUE, S.A",
    "Address": "RUA DOS DESPORTISTAS 873-879/11",
    "City": "MAPUTO",
    "Branch": "DIRECCAO INTERNACIONAL",
    "Postcode": "1100",
    "Country": "Mozambique",
    "Connection": "Active"
  },
  {
    "bankCode": "MAIS",
    "countryCode": "MZ",
    "branchCode": "ZMA",
    "SWIFT Code": "MAISMZMA",
    "Bank Name": "BANCO MAIS, SA",
    "Address": "AV. JULIUS NYERERE 2385",
    "City": "MAPUTO",
    "Branch": "",
    "Postcode": "2268",
    "Country": "Mozambique",
    "Connection": "Active"
  },
  {
    "bankCode": "BNIM",
    "countryCode": "MZ",
    "branchCode": "ZMP",
    "SWIFT Code": "BNIMMZMP",
    "Bank Name": "BANCO NACIONAL DE INVESTIMENTO, SA",
    "Address": "BLOCO A2, AV. JULIUS NYERERE 3504",
    "City": "MAPUTO",
    "Branch": "",
    "Postcode": "4668",
    "Country": "Mozambique",
    "Connection": "Active"
  },
  {
    "bankCode": "SOGE",
    "countryCode": "MZ",
    "branchCode": "ZMA",
    "SWIFT Code": "SOGEMZMA",
    "Bank Name": "BANCO SOCIETE GENERALE (MOCAMBIQUE) S.A.",
    "Address": "AV. JULIUS NYERERE N140",
    "City": "MAPUTO",
    "Branch": "",
    "Postcode": "3412",
    "Country": "Mozambique",
    "Connection": "Active"
  },
  {
    "bankCode": "CGDI",
    "countryCode": "MZ",
    "branchCode": "ZMA",
    "SWIFT Code": "CGDIMZMA",
    "Bank Name": "BCI",
    "Address": "AVENIDA 25 DE SETEMBRO 4",
    "City": "MAPUTO",
    "Branch": "",
    "Postcode": "4745",
    "Country": "Mozambique",
    "Connection": "Active"
  },
  {
    "bankCode": "ECOC",
    "countryCode": "MZ",
    "branchCode": "ZMP",
    "SWIFT Code": "ECOCMZMP",
    "Bank Name": "ECOBANK MOCAMBIQUE, S.A.",
    "Address": "VLADIMIR LENINE 210",
    "City": "MAPUTO",
    "Branch": "",
    "Postcode": "1106",
    "Country": "Mozambique",
    "Connection": "Active"
  },
  {
    "bankCode": "FRCG",
    "countryCode": "MZ",
    "branchCode": "ZMA",
    "SWIFT Code": "FRCGMZMA",
    "Bank Name": "FIRST CAPITAL BANK SA",
    "Address": "EDIF. MARYAH AV 25 SETEMBRO ATERRO, MAXAQUENE, 7 ANDAR",
    "City": "MAPUTO",
    "Branch": "",
    "Postcode": "1695",
    "Country": "Mozambique",
    "Connection": "Active"
  },
  {
    "bankCode": "FIRN",
    "countryCode": "MZ",
    "branchCode": "ZMX",
    "SWIFT Code": "FIRNMZMX",
    "Bank Name": "FNB MOZAMBIQUE,SA",
    "Address": "JAT, FRONT OF FACIM, AVENUE 25 DE SEPTEMBRE 420, FLOOR 1",
    "City": "MAPUTO",
    "Branch": "",
    "Postcode": "1695",
    "Country": "Mozambique",
    "Connection": "Active"
  },
  {
    "bankCode": "MOZA",
    "countryCode": "MZ",
    "branchCode": "ZMA",
    "SWIFT Code": "MOZAMZMA",
    "Bank Name": "MOZA BANCO SA",
    "Address": "AV. KWAME NKRUMAH 97",
    "City": "MAPUTO",
    "Branch": "",
    "Postcode": "1012",
    "Country": "Mozambique",
    "Connection": "Active"
  },
  {
    "bankCode": "UNIC",
    "countryCode": "MZ",
    "branchCode": "ZMX",
    "SWIFT Code": "UNICMZMX",
    "Bank Name": "NEDBANK MOCAMBIQUE, S.A.",
    "Address": "AVENUE JULIUS NYERERE 590",
    "City": "MAPUTO",
    "Branch": "",
    "Postcode": "3412",
    "Country": "Mozambique",
    "Connection": "Active"
  },
  {
    "bankCode": "SBIC",
    "countryCode": "MZ",
    "branchCode": "ZMX",
    "SWIFT Code": "SBICMZMX",
    "Bank Name": "STANDARD BANK SA",
    "Address": "PRACA 25 DE JUNHO 1",
    "City": "MAPUTO",
    "Branch": "",
    "Postcode": "1119",
    "Country": "Mozambique",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "MZ",
    "branchCode": "ZMA",
    "SWIFT Code": "UNAFMZMA",
    "Bank Name": "UBA MOCAMBIQUE,SA",
    "Address": "PRACA 16 DE JUNHO, FLOOR 2",
    "City": "MAPUTO",
    "Branch": "",
    "Postcode": "1100",
    "Country": "Mozambique",
    "Connection": "Active"
  }
]
module.exports = mozambique
