const nepal = [
  {
    "bankCode": "ADBL",
    "countryCode": "NP",
    "branchCode": "PKA",
    "SWIFT Code": "ADBLNPKA",
    "Bank Name": "AGRICULTURAL DEVELOPMENT BANK LTD",
    "Address": "RAMSHAHPATH",
    "City": "KATHMANDU",
    "Branch": "",
    "Postcode": "44600",
    "Country": "Nepal",
    "Connection": "Active"
  },
  {
    "bankCode": "CTZN",
    "countryCode": "NP",
    "branchCode": "PKA",
    "SWIFT Code": "CTZNNPKA",
    "Bank Name": "CITIZENS BANK INTERNATIONAL LIMITED",
    "Address": "NARAYANHITI PATH",
    "City": "KATHMANDU",
    "Branch": "",
    "Postcode": "44600",
    "Country": "Nepal",
    "Connection": "Active"
  },
  {
    "bankCode": "EVBL",
    "countryCode": "NP",
    "branchCode": "PKA",
    "SWIFT Code": "EVBLNPKA",
    "Bank Name": "EVEREST BANK LTD.",
    "Address": "EBL HOUSE, LAZIMPAT",
    "City": "KATHMANDU",
    "Branch": "",
    "Postcode": "13384",
    "Country": "Nepal",
    "Connection": "Active"
  },
  {
    "bankCode": "GLBB",
    "countryCode": "NP",
    "branchCode": "PKA",
    "SWIFT Code": "GLBBNPKA",
    "Bank Name": "GLOBAL IME BANK LIMITED",
    "Address": "KAMALADI 28",
    "City": "KATHMANDU",
    "Branch": "",
    "Postcode": "44600",
    "Country": "Nepal",
    "Connection": "Active"
  },
  {
    "bankCode": "HIMA",
    "countryCode": "NP",
    "branchCode": "PKA",
    "SWIFT Code": "HIMANPKA",
    "Bank Name": "HIMALAYAN BANK LTD.",
    "Address": "KARMACHARI SANCHAYA KOSH BUILDING, TRADEVI MARG THAMEL",
    "City": "KATHMANDU",
    "Branch": "",
    "Postcode": "44600",
    "Country": "Nepal",
    "Connection": "Active"
  },
  {
    "bankCode": "KMBL",
    "countryCode": "NP",
    "branchCode": "PKA",
    "SWIFT Code": "KMBLNPKA",
    "Bank Name": "KUMARI BANK LTD",
    "Address": "TANGAL 2",
    "City": "KATHMANDU",
    "Branch": "",
    "Postcode": "21128",
    "Country": "Nepal",
    "Connection": "Active"
  },
  {
    "bankCode": "LXBL",
    "countryCode": "NP",
    "branchCode": "PKA",
    "SWIFT Code": "LXBLNPKA",
    "Bank Name": "LAXMI SUNRISE BANK LIMITED",
    "Address": "",
    "City": "KATHMANDU",
    "Branch": "",
    "Postcode": "44600",
    "Country": "Nepal",
    "Connection": "Active"
  },
  {
    "bankCode": "MBLN",
    "countryCode": "NP",
    "branchCode": "PKA",
    "SWIFT Code": "MBLNNPKA",
    "Bank Name": "MACHHAPUCHCHHRE BANK LIMITED",
    "Address": "MBL TOWER, LAZIMPAT",
    "City": "KATHMANDU",
    "Branch": "",
    "Postcode": "44600",
    "Country": "Nepal",
    "Connection": "Active"
  },
  {
    "bankCode": "NARB",
    "countryCode": "NP",
    "branchCode": "PKA",
    "SWIFT Code": "NARBNPKA",
    "Bank Name": "NABIL BANK LIMITED",
    "Address": "NABIL CENTER, BEENA MARGA, TEENDHARA, DURBARMARGH",
    "City": "KATHMANDU",
    "Branch": "",
    "Postcode": "44600",
    "Country": "Nepal",
    "Connection": "Active"
  },
  {
    "bankCode": "NEBL",
    "countryCode": "NP",
    "branchCode": "PKA",
    "SWIFT Code": "NEBLNPKA",
    "Bank Name": "NEPAL BANK LIMITED",
    "Address": "NEPAL BANK LIMITED BUILDING, NEW ROAD, DHARMA PATH",
    "City": "KATHMANDU",
    "Branch": "",
    "Postcode": "44600",
    "Country": "Nepal",
    "Connection": "Active"
  },
  {
    "bankCode": "NINF",
    "countryCode": "NP",
    "branchCode": "PKA",
    "SWIFT Code": "NINFNPKA",
    "Bank Name": "NEPAL INFRASTRUCTURE BANK LTD",
    "Address": "BANESHWOR 10",
    "City": "KATHMANDU",
    "Branch": "",
    "Postcode": "44600",
    "Country": "Nepal",
    "Connection": "Active"
  },
  {
    "bankCode": "NIBL",
    "countryCode": "NP",
    "branchCode": "PKT",
    "SWIFT Code": "NIBLNPKT",
    "Bank Name": "NEPAL INVESTMENT MEGA BANK LTD.",
    "Address": "DURBAR MARG 3412",
    "City": "KATHMANDU",
    "Branch": "",
    "Postcode": "44600",
    "Country": "Nepal",
    "Connection": "Active"
  },
  {
    "bankCode": "NRBL",
    "countryCode": "NP",
    "branchCode": "PKA",
    "SWIFT Code": "NRBLNPKA",
    "Bank Name": "NEPAL RASTRA BANK",
    "Address": "KATHMANDU BANKING OFFICE, THAPATHALI",
    "City": "KATHMANDU",
    "Branch": "",
    "Postcode": "44600",
    "Country": "Nepal",
    "Connection": "Active"
  },
  {
    "bankCode": "NRBL",
    "countryCode": "NP",
    "branchCode": "FED",
    "SWIFT Code": "NRBLNPKAFED",
    "Bank Name": "NEPAL RASTRA BANK",
    "Address": "BALUWATAR MARG, LALITNIWAS",
    "City": "KATHMANDU",
    "Branch": "FOREIGN EXCHANGE DEPARTMENT",
    "Postcode": "44600",
    "Country": "Nepal",
    "Connection": "Active"
  },
  {
    "bankCode": "NSBI",
    "countryCode": "NP",
    "branchCode": "PKA",
    "SWIFT Code": "NSBINPKA",
    "Bank Name": "NEPAL SBI BANK LTD",
    "Address": "KESHARMAHAL, LAINCHAOUR",
    "City": "KATHMANDU",
    "Branch": "",
    "Postcode": "44600",
    "Country": "Nepal",
    "Connection": "Active"
  },
  {
    "bankCode": "NSBI",
    "countryCode": "NP",
    "branchCode": "001",
    "SWIFT Code": "NSBINPKA001",
    "Bank Name": "NEPAL SBI BANK LTD",
    "Address": "KESHARMAHAL",
    "City": "KATHMANDU",
    "Branch": "BIRGUNJ BRANCH",
    "Postcode": "44600",
    "Country": "Nepal",
    "Connection": "Active"
  },
  {
    "bankCode": "NICE",
    "countryCode": "NP",
    "branchCode": "PKA",
    "SWIFT Code": "NICENPKA",
    "Bank Name": "NIC ASIA BANK LIMITED",
    "Address": "TRADE TOWER, THAPATHALI",
    "City": "KATHMANDU",
    "Branch": "",
    "Postcode": "44600",
    "Country": "Nepal",
    "Connection": "Active"
  },
  {
    "bankCode": "NMBB",
    "countryCode": "NP",
    "branchCode": "PKA",
    "SWIFT Code": "NMBBNPKA",
    "Bank Name": "NMB BANK LTD",
    "Address": "NMB BHAWAN, BABARMAHAL",
    "City": "KATHMANDU",
    "Branch": "",
    "Postcode": "11543",
    "Country": "Nepal",
    "Connection": "Active"
  },
  {
    "bankCode": "PRVU",
    "countryCode": "NP",
    "branchCode": "PKA",
    "SWIFT Code": "PRVUNPKA",
    "Bank Name": "PRABHU BANK LTD",
    "Address": "",
    "City": "KATHMANDU",
    "Branch": "",
    "Postcode": "44600",
    "Country": "Nepal",
    "Connection": "Active"
  },
  {
    "bankCode": "PCBL",
    "countryCode": "NP",
    "branchCode": "PKA",
    "SWIFT Code": "PCBLNPKA",
    "Bank Name": "PRIME COMMERCIAL BANK LTD",
    "Address": "KAMALPOKHARI",
    "City": "KATHMANDU",
    "Branch": "",
    "Postcode": "44600",
    "Country": "Nepal",
    "Connection": "Active"
  },
  {
    "bankCode": "RBBA",
    "countryCode": "NP",
    "branchCode": "PKA",
    "SWIFT Code": "RBBANPKA",
    "Bank Name": "RASTRIYA BANIJYA BANK LTD.",
    "Address": "R.B. BANK BUILDING, SINGHA DURBAR PLAZA 111",
    "City": "KATHMANDU",
    "Branch": "",
    "Postcode": "44600",
    "Country": "Nepal",
    "Connection": "Active"
  },
  {
    "bankCode": "SNMA",
    "countryCode": "NP",
    "branchCode": "PKA",
    "SWIFT Code": "SNMANPKA",
    "Bank Name": "SANIMA BANK LIMITED",
    "Address": "ALAKAPURI, NARAYAN CHAUR, NAXAL",
    "City": "KATHMANDU",
    "Branch": "",
    "Postcode": "44600",
    "Country": "Nepal",
    "Connection": "Active"
  },
  {
    "bankCode": "SIDD",
    "countryCode": "NP",
    "branchCode": "PKA",
    "SWIFT Code": "SIDDNPKA",
    "Bank Name": "SIDDHARTHA BANK LIMITED",
    "Address": "TEEN DHARA ROAD, KAMALADI 130/23",
    "City": "KATHMANDU",
    "Branch": "",
    "Postcode": "44600",
    "Country": "Nepal",
    "Connection": "Active"
  },
  {
    "bankCode": "SCBL",
    "countryCode": "NP",
    "branchCode": "PKA",
    "SWIFT Code": "SCBLNPKA",
    "Bank Name": "STANDARD CHARTERED BANK NEPAL LIMITED",
    "Address": "MADAN BHANDARI MARG, 34 WARD",
    "City": "KATHMANDU",
    "Branch": "",
    "Postcode": "44600",
    "Country": "Nepal",
    "Connection": "Active"
  }
]
module.exports = nepal
