const newZealand = [
  {
    "bankCode": "ACCN",
    "countryCode": "NZ",
    "branchCode": "Z2B",
    "SWIFT Code": "ACCNNZ2B",
    "Bank Name": "ACCIDENT COMPENSATION CORPORATION",
    "Address": "FLOOR 7, JUSTICE CENTER, 19 AITKEN STREET, THORNDON",
    "City": "WELLINGTON",
    "Branch": "",
    "Postcode": "6011",
    "Country": "New Zealand",
    "Connection": "Active"
  },
  {
    "bankCode": "ANZB",
    "countryCode": "NZ",
    "branchCode": "102",
    "SWIFT Code": "ANZBNZ22102",
    "Bank Name": "ANZ BANK NEW ZEALAND LIMITED",
    "Address": "CORNER QUEEN AND VICTORIA STREETS",
    "City": "AUCKLAND",
    "Branch": "AUCKLAND CENTRAL",
    "Postcode": "",
    "Country": "New Zealand",
    "Connection": "Active"
  },
  {
    "bankCode": "ANZB",
    "countryCode": "NZ",
    "branchCode": "797",
    "SWIFT Code": "ANZBNZ22797",
    "Bank Name": "ANZ BANK NEW ZEALAND LIMITED",
    "Address": "CORNER COLOMBO AND HEREFORD STREETS",
    "City": "CHRISTCHURCH",
    "Branch": "",
    "Postcode": "",
    "Country": "New Zealand",
    "Connection": "Active"
  },
  {
    "bankCode": "ANZB",
    "countryCode": "NZ",
    "branchCode": "Z22",
    "SWIFT Code": "ANZBNZ22",
    "Bank Name": "ANZ BANK NEW ZEALAND LIMITED",
    "Address": "FLOOR 10, 170-186 FEATHERSTONE STREET",
    "City": "WELLINGTON",
    "Branch": "",
    "Postcode": "6011",
    "Country": "New Zealand",
    "Connection": "Active"
  },
  {
    "bankCode": "ANZB",
    "countryCode": "NZ",
    "branchCode": "058",
    "SWIFT Code": "ANZBNZ22058",
    "Bank Name": "ANZ BANK NEW ZEALAND LIMITED",
    "Address": "215-229 LAMBTON QUAY",
    "City": "WELLINGTON",
    "Branch": "",
    "Postcode": "6000",
    "Country": "New Zealand",
    "Connection": "Active"
  },
  {
    "bankCode": "MMCC",
    "countryCode": "NZ",
    "branchCode": "Z23",
    "SWIFT Code": "MMCCNZ23",
    "Bank Name": "APEX INVESTMENT ADMINISTRATION (NZ)",
    "Address": "FLOOR 25, QUEEN'S RISE, 125 QUEEN STREET",
    "City": "AUCKLAND",
    "Branch": "",
    "Postcode": "1010",
    "Country": "New Zealand",
    "Connection": "Active"
  },
  {
    "bankCode": "ASBB",
    "countryCode": "NZ",
    "branchCode": "Z2A",
    "SWIFT Code": "ASBBNZ2A",
    "Bank Name": "ASB BANK LIMITED",
    "Address": "ASB NORTH WHARF, 12 JELLICOE STREET",
    "City": "AUCKLAND",
    "Branch": "",
    "Postcode": "1010",
    "Country": "New Zealand",
    "Connection": "Active"
  },
  {
    "bankCode": "ASBB",
    "countryCode": "NZ",
    "branchCode": "CLS",
    "SWIFT Code": "ASBBNZ2ACLS",
    "Bank Name": "ASB BANK LIMITED",
    "Address": "",
    "City": "AUCKLAND",
    "Branch": "CLS PAYMENTS ONLY",
    "Postcode": "",
    "Country": "New Zealand",
    "Connection": "Active"
  },
  {
    "bankCode": "ASBB",
    "countryCode": "NZ",
    "branchCode": "FXD",
    "SWIFT Code": "ASBBNZ2AFXD",
    "Bank Name": "ASB BANK LIMITED",
    "Address": "",
    "City": "AUCKLAND",
    "Branch": "FOREIGN EXCHANGE",
    "Postcode": "",
    "Country": "New Zealand",
    "Connection": "Active"
  },
  {
    "bankCode": "ASBB",
    "countryCode": "NZ",
    "branchCode": "ITS",
    "SWIFT Code": "ASBBNZ2AITS",
    "Bank Name": "ASB BANK LIMITED",
    "Address": "ASB NORTH WHARF, 12 JELLICOE STREET",
    "City": "AUCKLAND",
    "Branch": "INTERNATIONAL TRADE SERVICES",
    "Postcode": "1010",
    "Country": "New Zealand",
    "Connection": "Active"
  },
  {
    "bankCode": "ASBB",
    "countryCode": "NZ",
    "branchCode": "MMD",
    "SWIFT Code": "ASBBNZ2AMMD",
    "Bank Name": "ASB BANK LIMITED",
    "Address": "",
    "City": "AUCKLAND",
    "Branch": "MONEY MARKET",
    "Postcode": "",
    "Country": "New Zealand",
    "Connection": "Active"
  },
  {
    "bankCode": "ASBB",
    "countryCode": "NZ",
    "branchCode": "SEC",
    "SWIFT Code": "ASBBNZ2ASEC",
    "Bank Name": "ASB BANK LIMITED",
    "Address": "",
    "City": "AUCKLAND",
    "Branch": "SECURITIES",
    "Postcode": "",
    "Country": "New Zealand",
    "Connection": "Active"
  },
  {
    "bankCode": "BARB",
    "countryCode": "NZ",
    "branchCode": "Z2A",
    "SWIFT Code": "BARBNZ2A",
    "Bank Name": "BANK OF BARODA (NEW ZELAND) LTD",
    "Address": "114 DOMINION ROAD",
    "City": "AUCKLAND",
    "Branch": "",
    "Postcode": "1446",
    "Country": "New Zealand",
    "Connection": "Active"
  },
  {
    "bankCode": "BKCH",
    "countryCode": "NZ",
    "branchCode": "Z22",
    "SWIFT Code": "BKCHNZ22",
    "Bank Name": "BANK OF CHINA (NEW ZEALAND) LIMITED",
    "Address": "FLOOR 17, 205 QUEEN STREET",
    "City": "AUCKLAND",
    "Branch": "",
    "Postcode": "1010",
    "Country": "New Zealand",
    "Connection": "Active"
  },
  {
    "bankCode": "BKCH",
    "countryCode": "NZ",
    "branchCode": "Z2A",
    "SWIFT Code": "BKCHNZ2A",
    "Bank Name": "BANK OF CHINA LIMITED, AUCKLAND BRANCH",
    "Address": "FLOOR 17, TOWER 1, 205 QUEEN STREET",
    "City": "AUCKLAND",
    "Branch": "",
    "Postcode": "1010",
    "Country": "New Zealand",
    "Connection": "Active"
  },
  {
    "bankCode": "BKID",
    "countryCode": "NZ",
    "branchCode": "Z2A",
    "SWIFT Code": "BKIDNZ2A",
    "Bank Name": "BANK OF INDIA (NEW ZEALAND) LIMITED",
    "Address": "10 MANUKAU ROAD, EPSOM",
    "City": "AUCKLAND",
    "Branch": "",
    "Postcode": "1023",
    "Country": "New Zealand",
    "Connection": "Active"
  },
  {
    "bankCode": "BKNZ",
    "countryCode": "NZ",
    "branchCode": "100",
    "SWIFT Code": "BKNZNZ22100",
    "Bank Name": "BANK OF NEW ZEALAND",
    "Address": "80 QUEEN STREET",
    "City": "AUCKLAND",
    "Branch": "AUCKLAND",
    "Postcode": "1010",
    "Country": "New Zealand",
    "Connection": "Active"
  },
  {
    "bankCode": "BKNZ",
    "countryCode": "NZ",
    "branchCode": "800",
    "SWIFT Code": "BKNZNZ22800",
    "Bank Name": "BANK OF NEW ZEALAND",
    "Address": "114 FITZGERALD AVENUE",
    "City": "CHRISTCHURCH",
    "Branch": "CHRISTCHURCH",
    "Postcode": "8011",
    "Country": "New Zealand",
    "Connection": "Active"
  },
  {
    "bankCode": "BKNZ",
    "countryCode": "NZ",
    "branchCode": "900",
    "SWIFT Code": "BKNZNZ22900",
    "Bank Name": "BANK OF NEW ZEALAND",
    "Address": "98 GEORGE STREET",
    "City": "DUNEDIN",
    "Branch": "DUNEDIN",
    "Postcode": "9016",
    "Country": "New Zealand",
    "Connection": "Active"
  },
  {
    "bankCode": "BKNZ",
    "countryCode": "NZ",
    "branchCode": "Z22",
    "SWIFT Code": "BKNZNZ22",
    "Bank Name": "BANK OF NEW ZEALAND",
    "Address": "FLOOR 2, SPARK CENTRAL, 42 WILLIS STREET",
    "City": "WELLINGTON",
    "Branch": "",
    "Postcode": "6011",
    "Country": "New Zealand",
    "Connection": "Active"
  },
  {
    "bankCode": "BKNZ",
    "countryCode": "NZ",
    "branchCode": "985",
    "SWIFT Code": "BKNZNZ22985",
    "Bank Name": "BANK OF NEW ZEALAND",
    "Address": "HARBOUR QUAYS, 60 WATERLOO QUAY, PIPITEA",
    "City": "WELLINGTON",
    "Branch": "HEAD OFFICE",
    "Postcode": "6011",
    "Country": "New Zealand",
    "Connection": "Active"
  },
  {
    "bankCode": "BKNZ",
    "countryCode": "NZ",
    "branchCode": "500",
    "SWIFT Code": "BKNZNZ22500",
    "Bank Name": "BANK OF NEW ZEALAND",
    "Address": "38 WILLIS STREET",
    "City": "WELLINGTON",
    "Branch": "WELLINGTON",
    "Postcode": "6011",
    "Country": "New Zealand",
    "Connection": "Active"
  },
  {
    "bankCode": "BTOP",
    "countryCode": "NZ",
    "branchCode": "Z2A",
    "SWIFT Code": "BTOPNZ2A",
    "Bank Name": "BANZPAY TECHNOLOGY OPERATIONS LIMITED",
    "Address": "FLOOR 3, COFFEY HOUSE, 25 TEED STREET, NEWMARKET",
    "City": "AUCKLAND",
    "Branch": "",
    "Postcode": "1023",
    "Country": "New Zealand",
    "Connection": "Active"
  },
  {
    "bankCode": "PCBC",
    "countryCode": "NZ",
    "branchCode": "Z22",
    "SWIFT Code": "PCBCNZ22",
    "Bank Name": "CHINA CONSTRUCTION BANK (NEW ZEALAND) LIMITED",
    "Address": "FLOOR 29, VERO CENTRE, 48 SHORTLAND STREET",
    "City": "AUCKLAND",
    "Branch": "",
    "Postcode": "1010",
    "Country": "New Zealand",
    "Connection": "Active"
  },
  {
    "bankCode": "PCBC",
    "countryCode": "NZ",
    "branchCode": "Z2A",
    "SWIFT Code": "PCBCNZ2A",
    "Bank Name": "CHINA CONSTRUCTION BANK CORPORATION NEW ZEALAND BRANCH",
    "Address": "FLOOR 29, VERO CENTRE, 48 SHORTLAND STREET",
    "City": "AUCKLAND",
    "Branch": "",
    "Postcode": "1010",
    "Country": "New Zealand",
    "Connection": "Active"
  },
  {
    "bankCode": "CITI",
    "countryCode": "NZ",
    "branchCode": "Z2X",
    "SWIFT Code": "CITINZ2X",
    "Bank Name": "CITIBANK NA NEW ZEALAND BRANCH",
    "Address": "CITIBANK CENTRE, 23 CUSTOMS STREET EAST",
    "City": "AUCKLAND",
    "Branch": "",
    "Postcode": "1010",
    "Country": "New Zealand",
    "Connection": "Active"
  },
  {
    "bankCode": "CITI",
    "countryCode": "NZ",
    "branchCode": "COP",
    "SWIFT Code": "CITINZ2XCOP",
    "Bank Name": "CITIBANK NA NEW ZEALAND BRANCH",
    "Address": "",
    "City": "AUCKLAND",
    "Branch": "CO-OP",
    "Postcode": "",
    "Country": "New Zealand",
    "Connection": "Active"
  },
  {
    "bankCode": "CPNR",
    "countryCode": "NZ",
    "branchCode": "Z22",
    "SWIFT Code": "CPNRNZ22",
    "Bank Name": "COMPUTERSHARE INVESTOR SERVICES LTD",
    "Address": "FLOOR 2, 159 HURSTMERE ROAD",
    "City": "AUCKLAND",
    "Branch": "",
    "Postcode": "0622",
    "Country": "New Zealand",
    "Connection": "Active"
  },
  {
    "bankCode": "CGIP",
    "countryCode": "NZ",
    "branchCode": "Z22",
    "SWIFT Code": "CGIPNZ22",
    "Bank Name": "CRAIGS INVESTMENT PARTNERS LTD",
    "Address": "158 CAMERON ROAD",
    "City": "TAURANGA",
    "Branch": "",
    "Postcode": "3110",
    "Country": "New Zealand",
    "Connection": "Active"
  },
  {
    "bankCode": "FPNZ",
    "countryCode": "NZ",
    "branchCode": "Z2A",
    "SWIFT Code": "FPNZNZ2A",
    "Bank Name": "FISHER AND PAYKEL APPLIANCES LIMITED",
    "Address": "78 SPRINGS ROAD",
    "City": "AUCKLAND",
    "Branch": "",
    "Postcode": "2013",
    "Country": "New Zealand",
    "Connection": "Active"
  },
  {
    "bankCode": "FRFM",
    "countryCode": "NZ",
    "branchCode": "Z2A",
    "SWIFT Code": "FRFMNZ2A",
    "Bank Name": "FISHER FUNDS MANAGEMENT LIMITED",
    "Address": "FLOOR 1, CROWN CENTRE, 67-73 HURSTMERE ROAD",
    "City": "AUCKLAND",
    "Branch": "",
    "Postcode": "0622",
    "Country": "New Zealand",
    "Connection": "Active"
  },
  {
    "bankCode": "FNZW",
    "countryCode": "NZ",
    "branchCode": "Z22",
    "SWIFT Code": "FNZWNZ22",
    "Bank Name": "FNZ CLEARING LIMITED",
    "Address": "FLOOR 3, FNZ HOUSE, 29A BRANDON STREET",
    "City": "WELLINGTON",
    "Branch": "",
    "Postcode": "6011",
    "Country": "New Zealand",
    "Connection": "Active"
  },
  {
    "bankCode": "FONT",
    "countryCode": "NZ",
    "branchCode": "Z2A",
    "SWIFT Code": "FONTNZ2A",
    "Bank Name": "FONTERRA CO-OPERATIVE GROUP LIMITED",
    "Address": "109 FANSHAWE STREET",
    "City": "AUCKLAND",
    "Branch": "",
    "Postcode": "1010",
    "Country": "New Zealand",
    "Connection": "Active"
  },
  {
    "bankCode": "FORB",
    "countryCode": "NZ",
    "branchCode": "Z23",
    "SWIFT Code": "FORBNZ23",
    "Bank Name": "FORSYTH BARR LIMITED",
    "Address": "FLOOR 10, FORSYTH BARR HOUSE, 35 THE OCTAGON",
    "City": "DUNEDIN",
    "Branch": "",
    "Postcode": "9016",
    "Country": "New Zealand",
    "Connection": "Active"
  },
  {
    "bankCode": "GNZS",
    "countryCode": "NZ",
    "branchCode": "Z2A",
    "SWIFT Code": "GNZSNZ2A",
    "Bank Name": "GUARDIANS OF NEW ZEALAND SUPERANNUATION",
    "Address": "FLOOR 12, ZURICH HOUSE, 21 QUEEN STREET",
    "City": "AUCKLAND",
    "Branch": "",
    "Postcode": "1143",
    "Country": "New Zealand",
    "Connection": "Active"
  },
  {
    "bankCode": "HAAM",
    "countryCode": "NZ",
    "branchCode": "Z2B",
    "SWIFT Code": "HAAMNZ2B",
    "Bank Name": "HARBOUR ASSET MANAGEMENT LIMITED",
    "Address": "FLOOR 16, ANZ CENTER, 171 FEATHERSTON STREET",
    "City": "WELLINGTON",
    "Branch": "",
    "Postcode": "6011",
    "Country": "New Zealand",
    "Connection": "Active"
  },
  {
    "bankCode": "HEAT",
    "countryCode": "NZ",
    "branchCode": "Z22",
    "SWIFT Code": "HEATNZ22",
    "Bank Name": "HEARTLAND BANK LIMITED",
    "Address": "FLOOR 3, HEARTLAND HOUSE, 35 TEED STREET, NEWMARKET",
    "City": "AUCKLAND",
    "Branch": "",
    "Postcode": "1023",
    "Country": "New Zealand",
    "Connection": "Active"
  },
  {
    "bankCode": "HIFX",
    "countryCode": "NZ",
    "branchCode": "Z2A",
    "SWIFT Code": "HIFXNZ2A",
    "Bank Name": "HIFX LTD",
    "Address": "FLOOR 4, NZ INVEST HOUSE, 32 MAHUHU CRESENT",
    "City": "AUCKLAND",
    "Branch": "",
    "Postcode": "1010",
    "Country": "New Zealand",
    "Connection": "Active"
  },
  {
    "bankCode": "HSBC",
    "countryCode": "NZ",
    "branchCode": "Z2A",
    "SWIFT Code": "HSBCNZ2A",
    "Bank Name": "HONGKONG AND SHANGHAI BANKING CORPORATION LIMITED, THE",
    "Address": "HSBC TOWER, FLOOR 21, 188 QUAY STREET",
    "City": "AUCKLAND",
    "Branch": "",
    "Postcode": "1010",
    "Country": "New Zealand",
    "Connection": "Active"
  },
  {
    "bankCode": "HSBC",
    "countryCode": "NZ",
    "branchCode": "CLS",
    "SWIFT Code": "HSBCNZ2ACLS",
    "Bank Name": "HONGKONG AND SHANGHAI BANKING CORPORATION LIMITED, THE",
    "Address": "HSBC HOUSE, FLOOR 9, ONE QUEEN STREET",
    "City": "AUCKLAND",
    "Branch": "(CONTINUOUS LINK SETTELMENT DEPARTMENT)",
    "Postcode": "1010",
    "Country": "New Zealand",
    "Connection": "Active"
  },
  {
    "bankCode": "HSBC",
    "countryCode": "NZ",
    "branchCode": "GPI",
    "SWIFT Code": "HSBCNZ2AGPI",
    "Bank Name": "HONGKONG AND SHANGHAI BANKING CORPORATION LIMITED, THE",
    "Address": "FLOOR 21, HSBC TOWER, 188 QUAY STREET",
    "City": "AUCKLAND",
    "Branch": "GLOBAL PAYMENT INVESTIGATION",
    "Postcode": "1010",
    "Country": "New Zealand",
    "Connection": "Active"
  },
  {
    "bankCode": "HSBC",
    "countryCode": "NZ",
    "branchCode": "CHC",
    "SWIFT Code": "HSBCNZ2ACHC",
    "Bank Name": "HONGKONG AND SHANGHAI BANKING CORPORATION LIMITED, THE",
    "Address": "HONGKONG BANK HOUSE, FLOOR 6, 141 CAMBRIDGE TERRACE",
    "City": "CHRISTCHURCH",
    "Branch": "(CHRISTCHURCH BRANCH)",
    "Postcode": "8140",
    "Country": "New Zealand",
    "Connection": "Active"
  },
  {
    "bankCode": "HSBC",
    "countryCode": "NZ",
    "branchCode": "WLT",
    "SWIFT Code": "HSBCNZ2AWLT",
    "Bank Name": "HONGKONG AND SHANGHAI BANKING CORPORATION LIMITED, THE",
    "Address": "",
    "City": "WELLINGTON",
    "Branch": "WELLINGTON BRANCH",
    "Postcode": "",
    "Country": "New Zealand",
    "Connection": "Active"
  },
  {
    "bankCode": "TECY",
    "countryCode": "NZ",
    "branchCode": "Z22",
    "SWIFT Code": "TECYNZ22",
    "Bank Name": "IE TECHNOLOGY LIMITED",
    "Address": "C4, 14 TRITON DRIVE, ROSEDALE",
    "City": "AUCKLAND",
    "Branch": "",
    "Postcode": "0632",
    "Country": "New Zealand",
    "Connection": "Active"
  },
  {
    "bankCode": "ICBK",
    "countryCode": "NZ",
    "branchCode": "Z2A",
    "SWIFT Code": "ICBKNZ2A",
    "Bank Name": "INDUSTRIAL AND COMMERCIAL BANK OF CHINA (NEW ZEALAND) LIMITED",
    "Address": "FLOOR 11, HSBC TOWER, 188 QUAY STREET",
    "City": "AUCKLAND",
    "Branch": "",
    "Postcode": "1010",
    "Country": "New Zealand",
    "Connection": "Active"
  },
  {
    "bankCode": "ICBK",
    "countryCode": "NZ",
    "branchCode": "Z22",
    "SWIFT Code": "ICBKNZ22",
    "Bank Name": "INDUSTRIAL AND COMMERCIAL BANK OF CHINA LIMITED",
    "Address": "FLOOR 11, 188 QUAY STREET",
    "City": "AUCKLAND",
    "Branch": "",
    "Postcode": "1010",
    "Country": "New Zealand",
    "Connection": "Active"
  },
  {
    "bankCode": "FCAS",
    "countryCode": "NZ",
    "branchCode": "Z22",
    "SWIFT Code": "FCASNZ22",
    "Bank Name": "JARDEN SECURITIES LIMITED",
    "Address": "FLOOR 39, ANZ CENTRE, 23-29 ALBERT STREET",
    "City": "AUCKLAND",
    "Branch": "",
    "Postcode": "1010",
    "Country": "New Zealand",
    "Connection": "Active"
  },
  {
    "bankCode": "CHAS",
    "countryCode": "NZ",
    "branchCode": "CCS",
    "SWIFT Code": "CHASNZ2ACCS",
    "Bank Name": "JPMORGAN CHASE BANK, N.A., NEW ZEALAND BRANCH",
    "Address": "",
    "City": "AUCKLAND",
    "Branch": "WSS LOCAL CUSTODIAN SERVICES",
    "Postcode": "",
    "Country": "New Zealand",
    "Connection": "Active"
  },
  {
    "bankCode": "CHAS",
    "countryCode": "NZ",
    "branchCode": "Z2A",
    "SWIFT Code": "CHASNZ2A",
    "Bank Name": "JPMORGAN CHASE BANK, N.A., NEW ZEALAND BRANCH",
    "Address": "FLOOR 13, ASB TOWER, 2 HUNTER STREET",
    "City": "WELLINGTON",
    "Branch": "",
    "Postcode": "6011",
    "Country": "New Zealand",
    "Connection": "Active"
  },
  {
    "bankCode": "CHAS",
    "countryCode": "NZ",
    "branchCode": "SHR",
    "SWIFT Code": "CHASNZ2ASHR",
    "Bank Name": "JPMORGAN CHASE BANK, N.A., NEW ZEALAND BRANCH",
    "Address": "FLOOR 13, ASB TOWER, 2 HUNTER STREET",
    "City": "WELLINGTON",
    "Branch": "DIRECT CUSTODY AND CLEARING NEW ZEALAND PHYSICAL PSET",
    "Postcode": "6011",
    "Country": "New Zealand",
    "Connection": "Active"
  },
  {
    "bankCode": "TSBA",
    "countryCode": "NZ",
    "branchCode": "Z22",
    "SWIFT Code": "TSBANZ22",
    "Bank Name": "TSB BANK LIMITED",
    "Address": "TSB CENTRE, 122 DEVON STREET EAST",
    "City": "NEW PLYMOUTH",
    "Branch": "",
    "Postcode": "4342",
    "Country": "New Zealand",
    "Connection": "Active"
  },
  {
    "bankCode": "WPAC",
    "countryCode": "NZ",
    "branchCode": "Z2W",
    "SWIFT Code": "WPACNZ2W",
    "Bank Name": "WESTPAC NEW ZEALAND LIMITED, A WHOLLY OWNED SUBSIDIARY OF WESTPAC BANKING CORPORATION",
    "Address": "FLOOR 3, WESTPAC ON TAKUTAI, 16 TAKUTAI SQUARE",
    "City": "AUCKLAND",
    "Branch": "FOR ALL NEW ZEALAND BRANCHES",
    "Postcode": "1010",
    "Country": "New Zealand",
    "Connection": "Active"
  },
  {
    "bankCode": "ZEGR",
    "countryCode": "NZ",
    "branchCode": "Z22",
    "SWIFT Code": "ZEGRNZ22",
    "Bank Name": "ZESPRI GROUP LIMITED",
    "Address": "400 MAUNGANUI ROAD",
    "City": "TAURANGA",
    "Branch": "",
    "Postcode": "3116",
    "Country": "New Zealand",
    "Connection": "Active"
  },
  {
    "bankCode": "CHAS",
    "countryCode": "NZ",
    "branchCode": "VLT",
    "SWIFT Code": "CHASNZ2AVLT",
    "Bank Name": "JPMORGAN CHASE BANK, N.A., NEW ZEALAND BRANCH",
    "Address": "FLOOR 13, ASB TOWER, 2 HUNTER STREET",
    "City": "WELLINGTON",
    "Branch": "DIRECT CUSTODY AND CLEARING NEW ZEALAND PHYSICAL VAULT",
    "Postcode": "6011",
    "Country": "New Zealand",
    "Connection": "Active"
  },
  {},
  {
    "bankCode": "NZRC",
    "countryCode": "NZ",
    "branchCode": "Z2W",
    "SWIFT Code": "NZRCNZ2W",
    "Bank Name": "KIWIRAIL HOLDINGS LIMITED",
    "Address": "FLOOR 4, WELLINGTON RAILWAY STATION, 1 BUNNY STREET",
    "City": "WELLINGTON",
    "Branch": "",
    "Postcode": "6011",
    "Country": "New Zealand",
    "Connection": "Active"
  },
  {
    "bankCode": "CZNB",
    "countryCode": "NZ",
    "branchCode": "Z2A",
    "SWIFT Code": "CZNBNZ2A",
    "Bank Name": "KOOKMIN BANK, AUCKLAND BRANCH",
    "Address": "FLOOR 16, LUMLEY CENTRE, 88 SHORTLAND STREET",
    "City": "AUCKLAND",
    "Branch": "",
    "Postcode": "1010",
    "Country": "New Zealand",
    "Connection": "Active"
  },
  {
    "bankCode": "LIMV",
    "countryCode": "NZ",
    "branchCode": "Z22",
    "SWIFT Code": "LIMVNZ22",
    "Bank Name": "LINK MARKET SERVICES LIMITED",
    "Address": "FLOOR 11, DELOITTE CENTRE, 80 QUEEN STREET",
    "City": "AUCKLAND",
    "Branch": "",
    "Postcode": "1010",
    "Country": "New Zealand",
    "Connection": "Active"
  },
  {},
  {
    "bankCode": "DCFS",
    "countryCode": "NZ",
    "branchCode": "Z2A",
    "SWIFT Code": "DCFSNZ2A",
    "Bank Name": "MERCEDES-BENZ FINANCIAL SERVICES NEW ZEALAND LTD.",
    "Address": "FLOOR 3, OFFICE TOWER, 277 BROADWAY, NEWMARKET",
    "City": "AUCKLAND",
    "Branch": "",
    "Postcode": "1023",
    "Country": "New Zealand",
    "Connection": "Active"
  },
  {
    "bankCode": "DABE",
    "countryCode": "NZ",
    "branchCode": "Z2A",
    "SWIFT Code": "DABENZ2A",
    "Bank Name": "MERCEDES-BENZ NEW ZEALAND LTD.",
    "Address": "FLOOR 3, OFFICE TOWER, 277 BROAWAY, NEWMARKET",
    "City": "AUCKLAND",
    "Branch": "",
    "Postcode": "1060",
    "Country": "New Zealand",
    "Connection": "Active"
  },
  {
    "bankCode": "MMIA",
    "countryCode": "NZ",
    "branchCode": "Z22",
    "SWIFT Code": "MMIANZ22",
    "Bank Name": "MIMAII NZ LIMITED",
    "Address": "51 JOSEPH BANKS DRIVE",
    "City": "WELLINGTON",
    "Branch": "",
    "Postcode": "5024",
    "Country": "New Zealand",
    "Connection": "Active"
  },
  {
    "bankCode": "BOTK",
    "countryCode": "NZ",
    "branchCode": "Z2A",
    "SWIFT Code": "BOTKNZ2A",
    "Bank Name": "MUFG BANK, LTD.",
    "Address": "FLOOR 19, 151 QUEEN STREET",
    "City": "AUCKLAND",
    "Branch": "",
    "Postcode": "1010",
    "Country": "New Zealand",
    "Connection": "Active"
  },
  {
    "bankCode": "NBSE",
    "countryCode": "NZ",
    "branchCode": "Z22",
    "SWIFT Code": "NBSENZ22",
    "Bank Name": "NELSON BUILDING SOCIETY",
    "Address": "111 TRAFALGAR STREET",
    "City": "NELSON",
    "Branch": "",
    "Postcode": "7010",
    "Country": "New Zealand",
    "Connection": "Active"
  },
  {
    "bankCode": "NZXC",
    "countryCode": "NZ",
    "branchCode": "Z2W",
    "SWIFT Code": "NZXCNZ2W",
    "Bank Name": "NEW ZEALAND EXCHANGE LIMITED",
    "Address": "NZX CENTRE, 11 CABLE STREET",
    "City": "WELLINGTON",
    "Branch": "",
    "Postcode": "6011",
    "Country": "New Zealand",
    "Connection": "Active"
  },
  {
    "bankCode": "NZLG",
    "countryCode": "NZ",
    "branchCode": "Z22",
    "SWIFT Code": "NZLGNZ22",
    "Bank Name": "NEW ZEALAND LOCAL GOVERNMENT FUNDING AGENCY LIMITED",
    "Address": "FLOOR 8, CITY CHAMBERS, 142 FEATHERSTON STREET",
    "City": "WELLINGTON",
    "Branch": "",
    "Postcode": "6011",
    "Country": "New Zealand",
    "Connection": "Active"
  },
  {
    "bankCode": "NZTR",
    "countryCode": "NZ",
    "branchCode": "Z2W",
    "SWIFT Code": "NZTRNZ2W",
    "Bank Name": "NEW ZEALAND TREASURY",
    "Address": "FLOOR 13, 1 THE TERRACE",
    "City": "WELLINGTON",
    "Branch": "",
    "Postcode": "6011",
    "Country": "New Zealand",
    "Connection": "Active"
  },
  {
    "bankCode": "NZTR",
    "countryCode": "NZ",
    "branchCode": "222",
    "SWIFT Code": "NZTRNZ2W222",
    "Bank Name": "NEW ZEALAND TREASURY",
    "Address": "FLOOR 13, 1 THE TERRACE",
    "City": "WELLINGTON",
    "Branch": "TRUST ACCOUNT",
    "Postcode": "6011",
    "Country": "New Zealand",
    "Connection": "Active"
  },
  {},
  {
    "bankCode": "PIFA",
    "countryCode": "NZ",
    "branchCode": "Z22",
    "SWIFT Code": "PIFANZ22",
    "Bank Name": "PIE FUNDS MANAGEMENT LIMITED",
    "Address": "FLOOR 1, 1 BYRON AVENUE",
    "City": "AUCKLAND",
    "Branch": "",
    "Postcode": "0620",
    "Country": "New Zealand",
    "Connection": "Active"
  },
  {
    "bankCode": "PUTS",
    "countryCode": "NZ",
    "branchCode": "Z22",
    "SWIFT Code": "PUTSNZ22",
    "Bank Name": "PUBLIC TRUST",
    "Address": "FLOOR 10, 34 SHORTLAND ST",
    "City": "AUCKLAND",
    "Branch": "",
    "Postcode": "1140",
    "Country": "New Zealand",
    "Connection": "Active"
  },
  {},
  {},
  {
    "bankCode": "RABO",
    "countryCode": "NZ",
    "branchCode": "Z2W",
    "SWIFT Code": "RABONZ2W",
    "Bank Name": "RABOBANK NEW ZEALAND BRANCH",
    "Address": "FLOOR 23, DIMENSION DATA HOUSE, 157 LAMBTON QUAY",
    "City": "WELLINGTON",
    "Branch": "",
    "Postcode": "6011",
    "Country": "New Zealand",
    "Connection": "Active"
  },
  {
    "bankCode": "RABO",
    "countryCode": "NZ",
    "branchCode": "Z22",
    "SWIFT Code": "RABONZ22",
    "Bank Name": "RABOBANK NEW ZEALAND LIMITED",
    "Address": "FLOOR 23, VODAFONE ON THE QUAY, 157 LAMBTON QUAY, HAMILTON CENTRAL",
    "City": "WELLINGTON",
    "Branch": "",
    "Postcode": "6011",
    "Country": "New Zealand",
    "Connection": "Active"
  },
  {
    "bankCode": "RBNZ",
    "countryCode": "NZ",
    "branchCode": "Z2S",
    "SWIFT Code": "RBNZNZ2S",
    "Bank Name": "RESERVE BANK OF NEW ZEALAND",
    "Address": "2 THE TERRACE",
    "City": "WELLINGTON",
    "Branch": "",
    "Postcode": "6011",
    "Country": "New Zealand",
    "Connection": "Active"
  },
  {
    "bankCode": "RBNZ",
    "countryCode": "NZ",
    "branchCode": "ACC",
    "SWIFT Code": "RBNZNZ2WACC",
    "Bank Name": "RESERVE BANK OF NEW ZEALAND",
    "Address": "THE TERRACE",
    "City": "WELLINGTON",
    "Branch": "",
    "Postcode": "6011",
    "Country": "New Zealand",
    "Connection": "Active"
  },
  {
    "bankCode": "RBNZ",
    "countryCode": "NZ",
    "branchCode": "CCY",
    "SWIFT Code": "RBNZNZ2WCCY",
    "Bank Name": "RESERVE BANK OF NEW ZEALAND",
    "Address": "THE TERRACE",
    "City": "WELLINGTON",
    "Branch": "",
    "Postcode": "6011",
    "Country": "New Zealand",
    "Connection": "Active"
  },
  {
    "bankCode": "RBNZ",
    "countryCode": "NZ",
    "branchCode": "Z2W",
    "SWIFT Code": "RBNZNZ2W",
    "Bank Name": "RESERVE BANK OF NEW ZEALAND",
    "Address": "2 THE TERRACE",
    "City": "WELLINGTON",
    "Branch": "",
    "Postcode": "6011",
    "Country": "New Zealand",
    "Connection": "Active"
  },
  {
    "bankCode": "RBNZ",
    "countryCode": "NZ",
    "branchCode": "ASA",
    "SWIFT Code": "RBNZNZ2SASA",
    "Bank Name": "RESERVE BANK OF NEW ZEALAND",
    "Address": "2 THE TERRACE",
    "City": "WELLINGTON",
    "Branch": "",
    "Postcode": "6011",
    "Country": "New Zealand",
    "Connection": "Active"
  },
  {},
  {
    "bankCode": "RBNZ",
    "countryCode": "NZ",
    "branchCode": "Z22",
    "SWIFT Code": "RBNZNZ22",
    "Bank Name": "RESERVE BANK OF NEW ZEALAND",
    "Address": "2 THE TERRACE",
    "City": "WELLINGTON",
    "Branch": "",
    "Postcode": "6011",
    "Country": "New Zealand",
    "Connection": "Active"
  },
  {
    "bankCode": "RBNZ",
    "countryCode": "NZ",
    "branchCode": "ASA",
    "SWIFT Code": "RBNZNZ2WASA",
    "Bank Name": "RESERVE BANK OF NEW ZEALAND",
    "Address": "2 THE TERRACE",
    "City": "WELLINGTON",
    "Branch": "",
    "Postcode": "6011",
    "Country": "New Zealand",
    "Connection": "Active"
  },
  {
    "bankCode": "RBNZ",
    "countryCode": "NZ",
    "branchCode": "Z2B",
    "SWIFT Code": "RBNZNZ2B",
    "Bank Name": "RESERVE BANK OF NEW ZEALAND",
    "Address": "2 THE TERRACE",
    "City": "WELLINGTON",
    "Branch": "",
    "Postcode": "",
    "Country": "New Zealand",
    "Connection": "Active"
  },
  {
    "bankCode": "RBNZ",
    "countryCode": "NZ",
    "branchCode": "HCK",
    "SWIFT Code": "RBNZNZ2SHCK",
    "Bank Name": "RESERVE BANK OF NEW ZEALAND",
    "Address": "2 THE TERRACE",
    "City": "WELLINGTON",
    "Branch": "",
    "Postcode": "",
    "Country": "New Zealand",
    "Connection": "Active"
  },
  {
    "bankCode": "ESAS",
    "countryCode": "NZ",
    "branchCode": "Z2A",
    "SWIFT Code": "ESASNZ2A",
    "Bank Name": "RESERVE BANK OF NEW ZEALAND",
    "Address": "FLOOR 6, 2 THE TERRACE",
    "City": "WELLINGTON",
    "Branch": "",
    "Postcode": "6011",
    "Country": "New Zealand",
    "Connection": "Active"
  },
  {
    "bankCode": "RBNZ",
    "countryCode": "NZ",
    "branchCode": "TSA",
    "SWIFT Code": "RBNZNZ2STSA",
    "Bank Name": "RESERVE BANK OF NEW ZEALAND",
    "Address": "2 THE TERRACE",
    "City": "WELLINGTON",
    "Branch": "EAST TEST BANK",
    "Postcode": "",
    "Country": "New Zealand",
    "Connection": "Active"
  },
  {
    "bankCode": "RBNZ",
    "countryCode": "NZ",
    "branchCode": "TSD",
    "SWIFT Code": "RBNZNZ2STSD",
    "Bank Name": "RESERVE BANK OF NEW ZEALAND",
    "Address": "2 THE TERRACE",
    "City": "WELLINGTON",
    "Branch": "PILOT BANK A",
    "Postcode": "",
    "Country": "New Zealand",
    "Connection": "Active"
  },
  {
    "bankCode": "RBNZ",
    "countryCode": "NZ",
    "branchCode": "TSE",
    "SWIFT Code": "RBNZNZ2STSE",
    "Bank Name": "RESERVE BANK OF NEW ZEALAND",
    "Address": "2 THE TERRACE",
    "City": "WELLINGTON",
    "Branch": "PILOT BANK B",
    "Postcode": "",
    "Country": "New Zealand",
    "Connection": "Active"
  },
  {
    "bankCode": "RBNZ",
    "countryCode": "NZ",
    "branchCode": "TSF",
    "SWIFT Code": "RBNZNZ2STSF",
    "Bank Name": "RESERVE BANK OF NEW ZEALAND",
    "Address": "2 THE TERRACE",
    "City": "WELLINGTON",
    "Branch": "PILOT BANK C",
    "Postcode": "",
    "Country": "New Zealand",
    "Connection": "Active"
  },
  {
    "bankCode": "RBNZ",
    "countryCode": "NZ",
    "branchCode": "TSG",
    "SWIFT Code": "RBNZNZ2STSG",
    "Bank Name": "RESERVE BANK OF NEW ZEALAND",
    "Address": "2 THE TERRACE",
    "City": "WELLINGTON",
    "Branch": "PILOT BANK D",
    "Postcode": "",
    "Country": "New Zealand",
    "Connection": "Active"
  },
  {
    "bankCode": "RBNZ",
    "countryCode": "NZ",
    "branchCode": "TSH",
    "SWIFT Code": "RBNZNZ2STSH",
    "Bank Name": "RESERVE BANK OF NEW ZEALAND",
    "Address": "2 THE TERRACE",
    "City": "WELLINGTON",
    "Branch": "PILOT BANK E",
    "Postcode": "",
    "Country": "New Zealand",
    "Connection": "Active"
  },
  {},
  {
    "bankCode": "RBNZ",
    "countryCode": "NZ",
    "branchCode": "TSJ",
    "SWIFT Code": "RBNZNZ2STSJ",
    "Bank Name": "RESERVE BANK OF NEW ZEALAND",
    "Address": "2 THE TERRACE",
    "City": "WELLINGTON",
    "Branch": "PILOT BANK G",
    "Postcode": "",
    "Country": "New Zealand",
    "Connection": "Active"
  },
  {
    "bankCode": "RBNZ",
    "countryCode": "NZ",
    "branchCode": "TSK",
    "SWIFT Code": "RBNZNZ2STSK",
    "Bank Name": "RESERVE BANK OF NEW ZEALAND",
    "Address": "2 THE TERRACE",
    "City": "WELLINGTON",
    "Branch": "PILOT BANK H",
    "Postcode": "",
    "Country": "New Zealand",
    "Connection": "Active"
  },
  {
    "bankCode": "RBNZ",
    "countryCode": "NZ",
    "branchCode": "REG",
    "SWIFT Code": "RBNZNZ2WREG",
    "Bank Name": "RESERVE BANK OF NEW ZEALAND",
    "Address": "2 THE TERRACE",
    "City": "WELLINGTON",
    "Branch": "REGISTRY DEPARTMENT",
    "Postcode": "6011",
    "Country": "New Zealand",
    "Connection": "Active"
  },
  {
    "bankCode": "RBNZ",
    "countryCode": "NZ",
    "branchCode": "TSC",
    "SWIFT Code": "RBNZNZ2STSC",
    "Bank Name": "RESERVE BANK OF NEW ZEALAND",
    "Address": "2 THE TERRACE",
    "City": "WELLINGTON",
    "Branch": "WEST TEST BANK",
    "Postcode": "",
    "Country": "New Zealand",
    "Connection": "Active"
  },
  {
    "bankCode": "RPNZ",
    "countryCode": "NZ",
    "branchCode": "Z22",
    "SWIFT Code": "RPNZNZ22",
    "Bank Name": "REVOLUT PAYMENTS NEW ZEALAND PTY LTD",
    "Address": "FLOOR 2, 318 LAMBTON QUAY",
    "City": "WELLINGTON",
    "Branch": "",
    "Postcode": "6011",
    "Country": "New Zealand",
    "Connection": "Active"
  },
  {
    "bankCode": "REVO",
    "countryCode": "NZ",
    "branchCode": "Z23",
    "SWIFT Code": "REVONZ23",
    "Bank Name": "REVOLUT PAYMENTS NEW ZEALAND PTY LTD",
    "Address": "FLOOR 2, 318 LAMBTON QUAY",
    "City": "WELLINGTON",
    "Branch": "",
    "Postcode": "6011",
    "Country": "New Zealand",
    "Connection": "Active"
  },
  {
    "bankCode": "SKTE",
    "countryCode": "NZ",
    "branchCode": "Z22",
    "SWIFT Code": "SKTENZ22",
    "Bank Name": "SKYLINE TECH LIMITED",
    "Address": "296 VICTORIA AVENUE, REMUERA",
    "City": "AUCKLAND",
    "Branch": "",
    "Postcode": "1050",
    "Country": "New Zealand",
    "Connection": "Active"
  },
  {
    "bankCode": "SBSY",
    "countryCode": "NZ",
    "branchCode": "Z22",
    "SWIFT Code": "SBSYNZ22",
    "Bank Name": "SOUTHLAND BUILDING SOCIETY",
    "Address": "51 DON STREET",
    "City": "INVERCARGILL",
    "Branch": "",
    "Postcode": "9810",
    "Country": "New Zealand",
    "Connection": "Active"
  },
  {
    "bankCode": "TMTC",
    "countryCode": "NZ",
    "branchCode": "Z2A",
    "SWIFT Code": "TMTCNZ2A",
    "Bank Name": "TRADE AND MERCHANT TRUST COMPANY LIMITED",
    "Address": "130 ST GEORGES BAY RD, PARNELL",
    "City": "AUCKLAND",
    "Branch": "",
    "Postcode": "1052",
    "Country": "New Zealand",
    "Connection": "Active"
  },
  {
    "bankCode": "TREX",
    "countryCode": "NZ",
    "branchCode": "Z22",
    "SWIFT Code": "TREXNZ22",
    "Bank Name": "TRUSTEES EXECUTORS LIMITED",
    "Address": "FLOOR 9, SPARK CENTRAL, 42-52 WILLIS STREET",
    "City": "WELLINGTON",
    "Branch": "",
    "Postcode": "6011",
    "Country": "New Zealand",
    "Connection": "Active"
  }
]
module.exports = newZealand
