const nicaragua = [
  {
    "countryCode": "ATTD",
    "bankCode": "NI",
    "branchCode": "IMA",
    "SWIFT Code": "ATTDNIMA",
    "Bank Name": "BANCO ATLANTIDA NICARAGUA, SOCIEDAD ANONIMA",
    "Address": "CC CAMINO DE ORIENTE MODULO S, KM, 6.5 CARRETERA MASAYA PARTE TRASERA, AREA CORPORATIVA EN EL",
    "City": "MANAGUA",
    "Branch": "",
    "Postcode": "14164",
    "Country": "Nicaragua",
    "Connection": "Active"
  },
  {
    "countryCode": "PRCB",
    "bankCode": "NI",
    "branchCode": "IMA",
    "SWIFT Code": "PRCBNIMA",
    "Bank Name": "BANCO AVANZ S.A.",
    "Address": "EDIFICIO AVANZ, AVENIDA JEAN PAUL GENIE",
    "City": "MANAGUA",
    "Branch": "",
    "Postcode": "14125",
    "Country": "Nicaragua",
    "Connection": "Active"
  },
  {
    "countryCode": "BCNI",
    "bankCode": "NI",
    "branchCode": "IMA",
    "SWIFT Code": "BCNINIMA",
    "Bank Name": "BANCO CENTRAL DE NICARAGUA",
    "Address": "PASO A DESNIVEL NEJAPA, 100 METROS AL ESTE, PISTA JUAN PABLO II",
    "City": "MANAGUA",
    "Branch": "",
    "Postcode": "14198",
    "Country": "Nicaragua",
    "Connection": "Active"
  },
  {
    "countryCode": "BAMC",
    "bankCode": "NI",
    "branchCode": "IMA",
    "SWIFT Code": "BAMCNIMA",
    "Bank Name": "BANCO DE AMERICA CENTRAL",
    "Address": "KM 4 1/2 CENTRO BAC CARRETERA A, MASAYA",
    "City": "MANAGUA",
    "Branch": "",
    "Postcode": "14125",
    "Country": "Nicaragua",
    "Connection": "Active"
  },
  {
    "countryCode": "BBDF",
    "bankCode": "NI",
    "branchCode": "IMA",
    "SWIFT Code": "BBDFNIMA",
    "Bank Name": "BANCO DE FINANZAS, S.A.(BDF)",
    "Address": "CENTRO CORPORATIVO BDF, FLOOR 4, DEL CLUB TERRAZA 440 METROS AL ESTE, PISTA JEAN PAUL GENIE",
    "City": "MANAGUA",
    "Branch": "",
    "Postcode": "14114",
    "Country": "Nicaragua",
    "Connection": "Active"
  },
  {
    "countryCode": "BFLP",
    "bankCode": "NI",
    "branchCode": "IM2",
    "SWIFT Code": "BFLPNIM2",
    "Bank Name": "BANCO DE FOMENTO A LA PRODUCCION",
    "Address": "ROTONDA METROCENTRO 600 MTS ESTE, AVENIDA JUAN PABLO II",
    "City": "MANAGUA",
    "Branch": "",
    "Postcode": "14012",
    "Country": "Nicaragua",
    "Connection": "Active"
  },
  {
    "countryCode": "BUNO",
    "bankCode": "NI",
    "branchCode": "IMA",
    "SWIFT Code": "BUNONIMA",
    "Bank Name": "BANCO FICOHSA NICARAGUA S.A.",
    "Address": "ROTONDA EL GUEGUENSE VRS. AL OESTE, 20",
    "City": "MANAGUA",
    "Branch": "",
    "Postcode": "14171",
    "Country": "Nicaragua",
    "Connection": "Active"
  },
  {
    "countryCode": "BCCE",
    "bankCode": "NI",
    "branchCode": "IMA",
    "SWIFT Code": "BCCENIMA",
    "Bank Name": "BANCO LAFISE BANCENTRO, S.A.",
    "Address": "CENTRO FINANCIERO LAFISE, KM 5.5 CARRETERA MASAYA",
    "City": "MANAGUA",
    "Branch": "",
    "Postcode": "14187",
    "Country": "Nicaragua",
    "Connection": "Active"
  },
  {
    "countryCode": "BAPR",
    "bankCode": "NI",
    "branchCode": "IMA",
    "SWIFT Code": "BAPRNIMA",
    "Bank Name": "BANPRO",
    "Address": "CUADRA AL ESTE 1, ROTONDA EL GUEGUENSE",
    "City": "MANAGUA",
    "Branch": "",
    "Postcode": "14145",
    "Country": "Nicaragua",
    "Connection": "Active"
  }
]
module.exports = nicaragua
