const nigeria = [
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "154",
    "SWIFT Code": "UNAFNGLA154",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "GRA LAYOUT DUTSIN-MA",
    "City": "KATSINA",
    "Branch": "DUTSINMA BRANCH",
    "Postcode": "800243",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "125",
    "SWIFT Code": "UNAFNGLA125",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "23 IBB WAY",
    "City": "KATSINA",
    "Branch": "KATSINA BRANCH",
    "Postcode": "920211",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "147",
    "SWIFT Code": "UNAFNGLA147",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "",
    "City": "KONTAGORA",
    "Branch": "KONTAGORA BRANCH",
    "Postcode": "920001",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "GLA",
    "SWIFT Code": "UNAFNGLA",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "57 MARINA, FLOOR 8, UBA HOUSE",
    "City": "LAGOS",
    "Branch": "",
    "Postcode": "100221",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "138",
    "SWIFT Code": "UNAFNGLA138",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "P/HARCOURT CRESCENT, AGBARA ESTATE",
    "City": "LAGOS",
    "Branch": "AGBARA ESTATE BRANCH",
    "Postcode": "500265",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "227",
    "SWIFT Code": "UNAFNGLA227",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "ALABA INTERNATIONAL MARKET",
    "City": "LAGOS",
    "Branch": "ALABA INTERNATIONAL MARKET",
    "Postcode": "100050",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "026",
    "SWIFT Code": "UNAFNGLA026",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "11/13 WAREHOUSE ROAD",
    "City": "LAGOS",
    "Branch": "APAPA WAREHOUSE BRANCH",
    "Postcode": "101001",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "004",
    "SWIFT Code": "UNAFNGLA004",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "9 WHARF ROAD",
    "City": "LAGOS",
    "Branch": "APAPA WHARF BRANCH",
    "Postcode": "104214",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "219",
    "SWIFT Code": "UNAFNGLA219",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "11/12 DAVIES STREET",
    "City": "LAGOS",
    "Branch": "BREADFRUIT BRANCH",
    "Postcode": "100213",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "228",
    "SWIFT Code": "UNAFNGLA228",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "57 MARINA, FLOOR 16, UBA HOUSE",
    "City": "LAGOS",
    "Branch": "E-BANKING SERVICE DEPT.",
    "Postcode": "100221",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "008",
    "SWIFT Code": "UNAFNGLA008",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "86 MURTALA MOHAMMED",
    "City": "LAGOS",
    "Branch": "EBUTE METTA BRANCH",
    "Postcode": "100272",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "012",
    "SWIFT Code": "UNAFNGLA012",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "AWOLOWO WAY, FALOMO SHOPPING CENTRE",
    "City": "LAGOS",
    "Branch": "FALOMO BRANCH",
    "Postcode": "100282",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "303",
    "SWIFT Code": "UNAFNGLA303",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "57 MARINA, FLOOR 16, UBA HOUSE",
    "City": "LAGOS",
    "Branch": "FINANCE OPERATIONS (FINOPS)",
    "Postcode": "100221",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "304",
    "SWIFT Code": "UNAFNGLA304",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "57 MARINA, FLOOR 8, UBA HOUSE",
    "City": "LAGOS",
    "Branch": "FOREIGN CURRENCT DOMICILIARY",
    "Postcode": "100221",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "306",
    "SWIFT Code": "UNAFNGLA306",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "57 MARINA, FLOOR 8, UBA HOUSE",
    "City": "LAGOS",
    "Branch": "FOREIGN TRADE",
    "Postcode": "100221",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "305",
    "SWIFT Code": "UNAFNGLA305",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "57 MARINA, FLOOR 8, UBA HOUSE",
    "City": "LAGOS",
    "Branch": "FOREIGN TREASURY OPERATIONS",
    "Postcode": "100221",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {},
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "011",
    "SWIFT Code": "UNAFNGLA011",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "10 ABEBE VILLAGE ROAD",
    "City": "LAGOS",
    "Branch": "IGANMU BRANCH",
    "Postcode": "101212",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "007",
    "SWIFT Code": "UNAFNGLA007",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "10 IJORA CAUSEWAY",
    "City": "LAGOS",
    "Branch": "IJORA BRANCH",
    "Postcode": "101253",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "005",
    "SWIFT Code": "UNAFNGLA005",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "OBA AKRAN AVENUE",
    "City": "LAGOS",
    "Branch": "IKEJA BRANCH",
    "Postcode": "100282",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "143",
    "SWIFT Code": "UNAFNGLA143",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "300 IKORODU ROAD, ANTHONY VILLAGE",
    "City": "LAGOS",
    "Branch": "IKORODU ROAD BRANCH",
    "Postcode": "104101",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "006",
    "SWIFT Code": "UNAFNGLA006",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "10 INDUSTRIAL ROAD, INDUSTRIAL ESTATE",
    "City": "LAGOS",
    "Branch": "ILUPEJU BRANCH",
    "Postcode": "101233",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {},
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "226",
    "SWIFT Code": "UNAFNGLA226",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "97/105 BROAD STREET, RAYMOND HOUSE",
    "City": "LAGOS",
    "Branch": "LAGOS CASH MANAGMENT CENTRE",
    "Postcode": "100221",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "002",
    "SWIFT Code": "UNAFNGLA002",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "97/105 BROAD STREET",
    "City": "LAGOS",
    "Branch": "LAGOS CENTRAL BRANCH",
    "Postcode": "102263",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "003",
    "SWIFT Code": "UNAFNGLA003",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "12/14 BROAD STREET",
    "City": "LAGOS",
    "Branch": "LAGOS EAST BRANCH",
    "Postcode": "102263",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "150",
    "SWIFT Code": "UNAFNGLA150",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "54 MARINA",
    "City": "LAGOS",
    "Branch": "MARINA WEST BRANCH",
    "Postcode": "100221",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "217",
    "SWIFT Code": "UNAFNGLA217",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "62/64 MURTALA MOHAMMED INT'L, AIRPORT RD",
    "City": "LAGOS",
    "Branch": "MM INT'L AIRPORT ROAD",
    "Postcode": "100271",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "130",
    "SWIFT Code": "UNAFNGLA130",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "ST GREGORY STREET, OBALENDE",
    "City": "LAGOS",
    "Branch": "OBALENDE BRANCH",
    "Postcode": "101232",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "221",
    "SWIFT Code": "UNAFNGLA221",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "34 ISSA WILLIAMS STREET",
    "City": "LAGOS",
    "Branch": "OKE ARIN BRANCH",
    "Postcode": "101227",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "016",
    "SWIFT Code": "UNAFNGLA016",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "16B OREGUN ROAD",
    "City": "LAGOS",
    "Branch": "OREGUN BRANCH",
    "Postcode": "100212",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "307",
    "SWIFT Code": "UNAFNGLA307",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "57 MARINA, FLOOR 9, UBA HOUSE",
    "City": "LAGOS",
    "Branch": "SALARY ADMINISTRATION DEPT.",
    "Postcode": "100221",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "205",
    "SWIFT Code": "UNAFNGLA205",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "68 WESTERN AVENUE",
    "City": "LAGOS",
    "Branch": "SURULERE BRANCH",
    "Postcode": "101283",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "014",
    "SWIFT Code": "UNAFNGLA014",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "17A TINUBU STREET",
    "City": "LAGOS",
    "Branch": "TINUBU BRANCH",
    "Postcode": "100244",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "302",
    "SWIFT Code": "UNAFNGLA302",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "57 MARINA, FLOOR 16, UBA HOUSE",
    "City": "LAGOS",
    "Branch": "TREASURY OPERATIONS",
    "Postcode": "100221",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "204",
    "SWIFT Code": "UNAFNGLA204",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "57 MARINA",
    "City": "LAGOS",
    "Branch": "UBA HOUSE BRANCH",
    "Postcode": "100221",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "181",
    "SWIFT Code": "UNAFNGLA181",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "97/105 BROAD STREET, FLOOR 2-3, RAYMOND HOUSE",
    "City": "LAGOS",
    "Branch": "UBA REGISTRARS",
    "Postcode": "101001",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "010",
    "SWIFT Code": "UNAFNGLA010",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "11 AKOKA STREET, YABA UNILAG CAMPUS",
    "City": "LAGOS",
    "Branch": "UNILAG BRANCH",
    "Postcode": "100213",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "127",
    "SWIFT Code": "UNAFNGLA127",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "WHARF ROAD",
    "City": "LOKOJA",
    "Branch": "LOKOJA BRANCH",
    "Postcode": "270001",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "179",
    "SWIFT Code": "UNAFNGLA179",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "BAGA ROAD",
    "City": "MAIDUGURI",
    "Branch": "BAGA ROAD BRANCH",
    "Postcode": "600235",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "067",
    "SWIFT Code": "UNAFNGLA067",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "2 SIR HASHIM ROAD",
    "City": "MAIDUGURI",
    "Branch": "MAIDUGURI MAIN BRANCH",
    "Postcode": "600231",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "031",
    "SWIFT Code": "UNAFNGLA031",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "28 OTURKPO ROAD",
    "City": "MAKURDI",
    "Branch": "MAKURDI BRANCH",
    "Postcode": "972001",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "099",
    "SWIFT Code": "UNAFNGLA099",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "",
    "City": "MINNA",
    "Branch": "MINNA BRANCH",
    "Postcode": "920001",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "159",
    "SWIFT Code": "UNAFNGLA159",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "56 AHMADU BELLO WAY",
    "City": "MUBI",
    "Branch": "MUBI BRANCH",
    "Postcode": "650272",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "050",
    "SWIFT Code": "UNAFNGLA050",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "CENTRAL PARADE ROAD",
    "City": "NEW BUSSA",
    "Branch": "NEW BUSSA BRANCH",
    "Postcode": "912105",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "113",
    "SWIFT Code": "UNAFNGLA113",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "24 AMECHI ROAD, OTOLO",
    "City": "NNEWI",
    "Branch": "NNEWI BRANCH",
    "Postcode": "435101",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "160",
    "SWIFT Code": "UNAFNGLA160",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "OKE-APAKEE ILORIN ROAD",
    "City": "OGBOMOSHO",
    "Branch": "OGBOMOSHO BRANCH",
    "Postcode": "240272",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "139",
    "SWIFT Code": "UNAFNGLA139",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "GERRGU CAMP, AJAOKUTA",
    "City": "OKENE",
    "Branch": "AJAOKUTA BRANCH",
    "Postcode": "263106",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "115",
    "SWIFT Code": "UNAFNGLA115",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "AGBODO OKE, YABA",
    "City": "ONDO",
    "Branch": "ONDO BRANCH",
    "Postcode": "351105",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "086",
    "SWIFT Code": "UNAFNGLA086",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "NEW MARKET ROAD",
    "City": "ONITSHA",
    "Branch": "ONITSHA BRANCH",
    "Postcode": "430262",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "022",
    "SWIFT Code": "UNAFNGLA022",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "",
    "City": "OSHOGBO",
    "Branch": "OSHOGBO BRANCH",
    "Postcode": "230212",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "039",
    "SWIFT Code": "UNAFNGLA039",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "IDIROKO ROAD, OJU ORE",
    "City": "OTA",
    "Branch": "OTTA BRANCH",
    "Postcode": "112233",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "087",
    "SWIFT Code": "UNAFNGLA087",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "34 DOUGLAS ROAD",
    "City": "OWERRI",
    "Branch": "OWERRI BRANCH",
    "Postcode": "460221",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "206",
    "SWIFT Code": "UNAFNGLA206",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "OGBOMOSHO ROAD, ODO-ARO QUARTERS",
    "City": "OYO",
    "Branch": "OYO BRANCH",
    "Postcode": "210232",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "220",
    "SWIFT Code": "UNAFNGLA220",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "FINIMA BONNY ISLAND",
    "City": "PORT HARCOURT",
    "Branch": "BONNY BRANCH",
    "Postcode": "500262",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "082",
    "SWIFT Code": "UNAFNGLA082",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "13 AGGREY ROAD",
    "City": "PORT HARCOURT",
    "Branch": "PH AGGREY RD. BRANCH",
    "Postcode": "500242",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "080",
    "SWIFT Code": "UNAFNGLA080",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "14A AZIKWE ROAD",
    "City": "PORT HARCOURT",
    "Branch": "PORT HARCOURT",
    "Postcode": "500242",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "083",
    "SWIFT Code": "UNAFNGLA083",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "TRANS AMADI IND. ESTATE",
    "City": "PORT HARCOURT",
    "Branch": "TRANS AMADI BRANCH",
    "Postcode": "500242",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "046",
    "SWIFT Code": "UNAFNGLA046",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "4 COURT ROAD",
    "City": "SAPELE",
    "Branch": "SAPELE BRANCH",
    "Postcode": "331211",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "118",
    "SWIFT Code": "UNAFNGLA118",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "YELWA ROAD",
    "City": "SHENDAM",
    "Branch": "SHENDAM",
    "Postcode": "942002",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "210",
    "SWIFT Code": "UNAFNGLA210",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "GUSAU",
    "City": "SOKOTO",
    "Branch": "GUSAU BRANCH",
    "Postcode": "860211",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "070",
    "SWIFT Code": "UNAFNGLA070",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "ALIYU JODI ROAD",
    "City": "SOKOTO",
    "Branch": "SOKOTO FODIO RD. BRANCH",
    "Postcode": "840231",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "025",
    "SWIFT Code": "UNAFNGLA025",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "KRB GUSAU ROAD",
    "City": "SOKOTO",
    "Branch": "SOKOTO KRB BRANCH",
    "Postcode": "840101",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "141",
    "SWIFT Code": "UNAFNGLA141",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "68 ABA ROAD, IKWUANO L.G.A",
    "City": "UMUAHIA",
    "Branch": "UMUAHIA BRANCH",
    "Postcode": "440221",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "024",
    "SWIFT Code": "UNAFNGLA024",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "7-13 AKWA ROAD, UYO L.G.A",
    "City": "UYO",
    "Branch": "UYO BRANCH",
    "Postcode": "520251",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "213",
    "SWIFT Code": "UNAFNGLA213",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "115A ADEOLA ODEKU",
    "City": "VICTORIA ISLAND",
    "Branch": "ADEOLA ODEKU BRANCH",
    "Postcode": "102314",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "193",
    "SWIFT Code": "UNAFNGLA193",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "22B IDOWU TAYLOR",
    "City": "VICTORIA ISLAND",
    "Branch": "IDOWU TAYLOR BRANCH",
    "Postcode": "101241",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "048",
    "SWIFT Code": "UNAFNGLA048",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "65 WARRI/SAPELE RD",
    "City": "WARRI",
    "Branch": "WARRI BRANCH",
    "Postcode": "332231",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "032",
    "SWIFT Code": "UNAFNGLA032",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "36 GALADIMA AMINU RD",
    "City": "YOLA",
    "Branch": "YOLA BRANCH",
    "Postcode": "640282",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "203",
    "SWIFT Code": "UNAFNGLA203",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "161/162 SOKOTO ROAD, OPP. ABU ZARIA",
    "City": "ZARIA",
    "Branch": "SAMARU BRANCH",
    "Postcode": "810221",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "065",
    "SWIFT Code": "UNAFNGLA065",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "KADUNA ROAD",
    "City": "ZARIA",
    "Branch": "ZARIA BRANCH",
    "Postcode": "800242",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "ICIT",
    "countryCode": "NG",
    "branchCode": "GLA",
    "SWIFT Code": "ICITNGLA",
    "Bank Name": "UNITY BANK PLC",
    "Address": "PLOT 42, UNITY BANK BUILDING",
    "City": "VICTORIA ISLAND",
    "Branch": "",
    "Postcode": "106104",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "VEGN",
    "countryCode": "NG",
    "branchCode": "GLA",
    "SWIFT Code": "VEGNNGLA",
    "Bank Name": "VENTURE GARDEN NIGERIA LIMITED",
    "Address": "42 LOCAL AIRPORT ROAD, VIBRANIUM VALLEY",
    "City": "LAGOS",
    "Branch": "",
    "Postcode": "100271",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "WEMA",
    "countryCode": "NG",
    "branchCode": "02K",
    "SWIFT Code": "WEMANGLA02K",
    "Bank Name": "WEMA BANK PLC",
    "Address": "",
    "City": "KANO",
    "Branch": "",
    "Postcode": "800001",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "WEMA",
    "countryCode": "NG",
    "branchCode": "GLA",
    "SWIFT Code": "WEMANGLA",
    "Bank Name": "WEMA BANK PLC",
    "Address": "54 MARINA, WEMA TOWERS",
    "City": "LAGOS",
    "Branch": "",
    "Postcode": "100221",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "WEMA",
    "countryCode": "NG",
    "branchCode": "02T",
    "SWIFT Code": "WEMANGLA02T",
    "Bank Name": "WEMA BANK PLC",
    "Address": "TINUBU",
    "City": "OSUN",
    "Branch": "",
    "Postcode": "232111",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "ZEIB",
    "countryCode": "NG",
    "branchCode": "013",
    "SWIFT Code": "ZEIBNGLA013",
    "Bank Name": "ZENITH BANK PLC",
    "Address": "",
    "City": "ABUJA",
    "Branch": "ABUJA BRANCH",
    "Postcode": "900001",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "ZEIB",
    "countryCode": "NG",
    "branchCode": "WEB",
    "SWIFT Code": "ZEIBNGLAWEB",
    "Bank Name": "ZENITH BANK PLC",
    "Address": "",
    "City": "LAGOS",
    "Branch": "ELECTRONIC TRANSACTIONS",
    "Postcode": "100001",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "ZEIB",
    "countryCode": "NG",
    "branchCode": "GLA",
    "SWIFT Code": "ZEIBNGLA",
    "Bank Name": "ZENITH BANK PLC",
    "Address": "87 AJOSE ADEOGUN STREET, ZENITH HEIGHTS",
    "City": "VICTORIA ISLAND",
    "Branch": "",
    "Postcode": "101241",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "ZEPC",
    "countryCode": "NG",
    "branchCode": "GLA",
    "SWIFT Code": "ZEPCNGLA",
    "Bank Name": "ZENITH PENSIONS CUSTODIAN LIMITED",
    "Address": "OZUMBA MBADIWE ROAD, FLOOR 4-5, CIVIC TOWERS",
    "City": "VICTORIA ISLAND",
    "Branch": "",
    "Postcode": "102113",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "SCBL",
    "countryCode": "NG",
    "branchCode": "STM",
    "SWIFT Code": "SCBLNGLASTM",
    "Bank Name": "STANDARD CHARTERED BANK NIGERIA LIMITED",
    "Address": "142 AHMADU BELLO WAY",
    "City": "VICTORIA ISLAND",
    "Branch": "STORM II",
    "Postcode": "101241",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "SCBL",
    "countryCode": "NG",
    "branchCode": "TSY",
    "SWIFT Code": "SCBLNGLATSY",
    "Bank Name": "STANDARD CHARTERED BANK NIGERIA LIMITED",
    "Address": "142 AHMADU BELLO WAY",
    "City": "VICTORIA ISLAND",
    "Branch": "TREASURY SERVICES",
    "Postcode": "101241",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "SCBL",
    "countryCode": "NG",
    "branchCode": "PYT",
    "SWIFT Code": "SCBLNGLAPYT",
    "Bank Name": "STANDARD CHARTERED BANK NIGERIA LIMITED",
    "Address": "105B AJOSE ADEOGUN STREET, UNITRUST HOUSE",
    "City": "VICTORIA ISLAND",
    "Branch": "UNITRUST, HEAD OFFICE BRANCH",
    "Postcode": "106104",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "NAME",
    "countryCode": "NG",
    "branchCode": "GLA",
    "SWIFT Code": "NAMENGLA",
    "Bank Name": "STERLING BANK PLC",
    "Address": "20 MARINA, STERLING TOWERS",
    "City": "LAGOS",
    "Branch": "",
    "Postcode": "101001",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "NAME",
    "countryCode": "NG",
    "branchCode": "SAF",
    "SWIFT Code": "NAMENGLASAF",
    "Bank Name": "STERLING BANK PLC",
    "Address": "20 MARINA, STERLING TOWERS",
    "City": "LAGOS",
    "Branch": "",
    "Postcode": "100221",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "SUTG",
    "countryCode": "NG",
    "branchCode": "GLA",
    "SWIFT Code": "SUTGNGLA",
    "Bank Name": "SUNTRUST BANK NIGERIA LIMITED",
    "Address": "1 OLADELE OLASHORE STREET, OFF SANUSI FAFUNWA",
    "City": "LAGOS",
    "Branch": "",
    "Postcode": "101241",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "TAJJ",
    "countryCode": "NG",
    "branchCode": "GLA",
    "SWIFT Code": "TAJJNGLA",
    "Bank Name": "TAJ BANK LIMITED",
    "Address": "76 AHMADU BELLO WAY, BENUE PLAZA",
    "City": "ABUJA",
    "Branch": "",
    "Postcode": "900211",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "TTRU",
    "countryCode": "NG",
    "branchCode": "GLA",
    "SWIFT Code": "TTRUNGLA",
    "Bank Name": "TITAN TRUST BANK LIMITED",
    "Address": "PLOT 1680 SANUSI FAFUNWA STREET",
    "City": "VICTORIA ISLAND",
    "Branch": "",
    "Postcode": "101241",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UBNI",
    "countryCode": "NG",
    "branchCode": "GLA",
    "SWIFT Code": "UBNINGLA",
    "Bank Name": "UNION BANK OF NIGERIA PLC",
    "Address": "36 MARINA, STALLION PLAZA",
    "City": "LAGOS",
    "Branch": "",
    "Postcode": "101001",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "088",
    "SWIFT Code": "UNAFNGLA088",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "IKOTEKPENE ROAD",
    "City": "ABA",
    "Branch": "ABA MAIN BRANCH",
    "Postcode": "450221",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "171",
    "SWIFT Code": "UNAFNGLA171",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "171/173 ABA/OWERRI RD",
    "City": "ABA",
    "Branch": "ABA/OWERRI RD. BRANCH",
    "Postcode": "440221",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "223",
    "SWIFT Code": "UNAFNGLA223",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "3A CEMENTARY ROAD, EZIUKWU MARKET",
    "City": "ABA",
    "Branch": "EZIUKWU BRANCH",
    "Postcode": "450211",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "055",
    "SWIFT Code": "UNAFNGLA055",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "48 TINUBU STREET, IBARA",
    "City": "ABEOKUTA",
    "Branch": "ABEOKUTA BRANCH",
    "Postcode": "110002",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "114",
    "SWIFT Code": "UNAFNGLA114",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "AREA 3, GARKI",
    "City": "ABUJA",
    "Branch": "ABUJA BRANCH",
    "Postcode": "900243",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "215",
    "SWIFT Code": "UNAFNGLA215",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "NICON NOGA HOTEL",
    "City": "ABUJA",
    "Branch": "NICON NOGA BRANCH",
    "Postcode": "900001",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "056",
    "SWIFT Code": "UNAFNGLA056",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "19A OBA ADESINA ROAD",
    "City": "AKURE",
    "Branch": "AKURE BRANCH",
    "Postcode": "340222",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "175",
    "SWIFT Code": "UNAFNGLA175",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "149A NNEBISI ROAD",
    "City": "ASABA",
    "Branch": "ASABA BRANCH",
    "Postcode": "320213",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "164",
    "SWIFT Code": "UNAFNGLA164",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "29 ENUGU-EAST ROAD",
    "City": "AWKA",
    "Branch": "AWKA BRANCH",
    "Postcode": "430231",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "030",
    "SWIFT Code": "UNAFNGLA030",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "BANK RD, COMM. AREA",
    "City": "BAUCHI",
    "Branch": "BAUCHI BRANCH",
    "Postcode": "740001",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "044",
    "SWIFT Code": "UNAFNGLA044",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "4 AKPAKPAVA ROAD",
    "City": "BENIN",
    "Branch": "BENIN BRANCH",
    "Postcode": "300002",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "117",
    "SWIFT Code": "UNAFNGLA117",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "156 USELU ROAD, UGBOWO",
    "City": "BENIN",
    "Branch": "UGBOWO BRANCH",
    "Postcode": "300212",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "094",
    "SWIFT Code": "UNAFNGLA094",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "CALABAR ROAD",
    "City": "CALABAR",
    "Branch": "CALABAR BRANCH",
    "Postcode": "551241",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "034",
    "SWIFT Code": "UNAFNGLA034",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "39 WARRI/SAPELE ROAD",
    "City": "EFFURUN",
    "Branch": "EFFURUN BRANCH",
    "Postcode": "332231",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "222",
    "SWIFT Code": "UNAFNGLA222",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "12 GRACE HILL ROAD",
    "City": "EKET",
    "Branch": "EKET BRANCH",
    "Postcode": "524101",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {},
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "084",
    "SWIFT Code": "UNAFNGLA084",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "STATION ROAD",
    "City": "ENUGU",
    "Branch": "ENUGU BRANCH",
    "Postcode": "400261",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "123",
    "SWIFT Code": "UNAFNGLA123",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "UNN, ENUGU CAMPUS",
    "City": "ENUGU",
    "Branch": "UNEC BRANCH",
    "Postcode": "400241",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "054",
    "SWIFT Code": "UNAFNGLA054",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "19 KATSINA ROAD",
    "City": "FUNTUA",
    "Branch": "FUNTUA BRANCH",
    "Postcode": "820252",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "152",
    "SWIFT Code": "UNAFNGLA152",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "8 BIU/SABON LINE RD",
    "City": "GOMBE",
    "Branch": "GOMBE BRANCH",
    "Postcode": "810106",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "126",
    "SWIFT Code": "UNAFNGLA126",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "JIGAWA-HADEJIA ROAD",
    "City": "HADEJIA",
    "Branch": "HADEJIA BRANCH",
    "Postcode": "731211",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "043",
    "SWIFT Code": "UNAFNGLA043",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "104 AMUNIGUN STREET",
    "City": "IBADAN",
    "Branch": "AMUNIGUN BRANCH",
    "Postcode": "200263",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "040",
    "SWIFT Code": "UNAFNGLA040",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "LEBANON STREET, DUGBE",
    "City": "IBADAN",
    "Branch": "IBADAN MAIN BRANCH",
    "Postcode": "200263",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "166",
    "SWIFT Code": "UNAFNGLA166",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "IWO ROAD",
    "City": "IBADAN",
    "Branch": "IWO ROAD BRANCH",
    "Postcode": "200223",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "042",
    "SWIFT Code": "UNAFNGLA042",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "IJEBU BYE PASS, OKE ADO",
    "City": "IBADAN",
    "Branch": "MOLETE BRANCH",
    "Postcode": "360101",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "112",
    "SWIFT Code": "UNAFNGLA112",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "89C IDIROKO STREET, AYEGBA OMA",
    "City": "IDAH",
    "Branch": "IDAH BRANCH",
    "Postcode": "270106",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "132",
    "SWIFT Code": "UNAFNGLA132",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "59 IBADAN ROAD",
    "City": "IJEBU ODE",
    "Branch": "IJEBU ODE BRANCH",
    "Postcode": "120213",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "218",
    "SWIFT Code": "UNAFNGLA218",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "CORPORATE H/O WAPCO, ALAUSA",
    "City": "IKEJA",
    "Branch": "ALAUSA BRANCH",
    "Postcode": "100212",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "023",
    "SWIFT Code": "UNAFNGLA023",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "18 AKIN ASABO STREET",
    "City": "IKOM",
    "Branch": "IKOM BRANCH",
    "Postcode": "551001",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "049",
    "SWIFT Code": "UNAFNGLA049",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "101 MURTALA MOHAMMED",
    "City": "ILORIN",
    "Branch": "ILORIN BRANCH",
    "Postcode": "240223",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "098",
    "SWIFT Code": "UNAFNGLA098",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "16/17 BANK ROAD",
    "City": "JOS",
    "Branch": "JOS BRANCH",
    "Postcode": "930262",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "062",
    "SWIFT Code": "UNAFNGLA062",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "HOSPITAL ROAD",
    "City": "KADUNA",
    "Branch": "KADUNA NORTH BRANCH",
    "Postcode": "810232",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "064",
    "SWIFT Code": "UNAFNGLA064",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "INDUSTRIAL ESTATE RD",
    "City": "KADUNA",
    "Branch": "KADUNA SOUTH BRANCH",
    "Postcode": "800242",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "153",
    "SWIFT Code": "UNAFNGLA153",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "POLYTECHNIC ROAD, TUDUN WADA",
    "City": "KADUNA",
    "Branch": "TUDUN WADA BRANCH",
    "Postcode": "800243",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "195",
    "SWIFT Code": "UNAFNGLA195",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "3 KAGORO ROAD",
    "City": "KAFANCHAN",
    "Branch": "KAFANCHAN BRANCH",
    "Postcode": "800272",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "224",
    "SWIFT Code": "UNAFNGLA224",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "31E ADO BAYERO ROAD",
    "City": "KANO",
    "Branch": "ADO BAYERO BRANCH",
    "Postcode": "700213",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "169",
    "SWIFT Code": "UNAFNGLA169",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "AMINU KANO INT'L AIRPORT",
    "City": "KANO",
    "Branch": "AMINU KANO INT'L AIRPORT",
    "Postcode": "700231",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "066",
    "SWIFT Code": "UNAFNGLA066",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "BAYERO UNIVERSITY",
    "City": "KANO",
    "Branch": "BAYERO UNIVERSITY BR.",
    "Postcode": "700006",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "060",
    "SWIFT Code": "UNAFNGLA060",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "4B BANK ROAD",
    "City": "KANO",
    "Branch": "KANO MAIN BRANCH",
    "Postcode": "700213",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "136",
    "SWIFT Code": "UNAFNGLA136",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "1 SHARADA, INDUSTRIAL ESTATE",
    "City": "KANO",
    "Branch": "KANO SHARADA BRANCH",
    "Postcode": "700234",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "NG",
    "branchCode": "137",
    "SWIFT Code": "UNAFNGLA137",
    "Bank Name": "UNITED BANK FOR AFRICA PLC",
    "Address": "38 MURTALA MOHAMMED",
    "City": "KANO",
    "Branch": "KANO WAJE BRANCH",
    "Postcode": "700213",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "IPSB",
    "countryCode": "NG",
    "branchCode": "GLA",
    "SWIFT Code": "IPSBNGLA",
    "Bank Name": "9 PAYMENT SERVICE BANK LIMITED",
    "Address": "16 ADEOLA ODEKU STREET",
    "City": "VICTORIA ISLAND",
    "Branch": "",
    "Postcode": "101241",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "ASNI",
    "countryCode": "NG",
    "branchCode": "GL2",
    "SWIFT Code": "ASNINGL2",
    "Bank Name": "ABSA SECURITIES NIGERIA LIMITED",
    "Address": "38A GLOVER ROAD, PROSPACE CENTRE, IKOYI",
    "City": "LAGOS",
    "Branch": "",
    "Postcode": "106104",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "ABNG",
    "countryCode": "NG",
    "branchCode": "GLA",
    "SWIFT Code": "ABNGNGLA",
    "Bank Name": "ACCESS BANK PLC",
    "Address": "PRINCE ALABA ONIRU STREET ONIRU, ESTATE",
    "City": "VICTORIA ISLAND",
    "Branch": "",
    "Postcode": "100212",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "AFFC",
    "countryCode": "NG",
    "branchCode": "GLA",
    "SWIFT Code": "AFFCNGLA",
    "Bank Name": "AFRICA FINANCE CORPORATION",
    "Address": "3A OSBORNE ROAD, IKOYI",
    "City": "LAGOS",
    "Branch": "",
    "Postcode": "101233",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "PASS",
    "countryCode": "NG",
    "branchCode": "GLA",
    "SWIFT Code": "PASSNGLA",
    "Bank Name": "AFRICAN EXPORT-IMPORT BANK",
    "Address": "2 GNASSINGBE EYADEMA STREET",
    "City": "ABUJA",
    "Branch": "",
    "Postcode": "900211",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "AMNG",
    "countryCode": "NG",
    "branchCode": "GLA",
    "SWIFT Code": "AMNGNGLA",
    "Bank Name": "ASSET MANAGEMENT CORPORATION OF NIGERIA",
    "Address": "1, PLOT 417 TIGRIS CRESCENT, OFF, AGUIYI IRONSI WAY AANI HOUSE, MAITAMA",
    "City": "ABUJA",
    "Branch": "",
    "Postcode": "23411",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "BOIY",
    "countryCode": "NG",
    "branchCode": "GLA",
    "SWIFT Code": "BOIYNGLA",
    "Bank Name": "BANK OF INDUSTRY FINANCIAL DEPARTMENT",
    "Address": "23 MARINA",
    "City": "LAGOS",
    "Branch": "",
    "Postcode": "100221",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "CBNI",
    "countryCode": "NG",
    "branchCode": "GLG",
    "SWIFT Code": "CBNINGLG",
    "Bank Name": "CENTRAL BANK OF NIGERIA",
    "Address": "PLOT 33 TAFAWA BALEWA WAY",
    "City": "ABUJA",
    "Branch": "",
    "Postcode": "900103",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "CBNI",
    "countryCode": "NG",
    "branchCode": "GLA",
    "SWIFT Code": "CBNINGLA",
    "Bank Name": "CENTRAL BANK OF NIGERIA",
    "Address": "PLOT 33 TAFAWA BALEWA WAY",
    "City": "LAGOS",
    "Branch": "",
    "Postcode": "100221",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "CBNI",
    "countryCode": "NG",
    "branchCode": "NGA",
    "SWIFT Code": "CBNINGLANGA",
    "Bank Name": "CENTRAL BANK OF NIGERIA",
    "Address": "PLOT 33 TAFAWA BALEWA WAY",
    "City": "LAGOS",
    "Branch": "CBN FIN INFORMATION SERVICE",
    "Postcode": "101282",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "CSCY",
    "countryCode": "NG",
    "branchCode": "GLA",
    "SWIFT Code": "CSCYNGLA",
    "Bank Name": "CENTRAL SECURITIES CLEARING SYSTEM PLC",
    "Address": "2/4 CUSTOMS STREET, MARINA, THE NIGERIAN STOCK EXCHANGE HOUSE",
    "City": "LAGOS",
    "Branch": "",
    "Postcode": "100216",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "CITI",
    "countryCode": "NG",
    "branchCode": "GLA",
    "SWIFT Code": "CITINGLA",
    "Bank Name": "CITIBANK NIGERIA LIMITED",
    "Address": "27 KOFO ABAYOMI STREET, CHARLES S SANKEY HOUSE",
    "City": "VICTORIA ISLAND",
    "Branch": "",
    "Postcode": "101241",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "CITI",
    "countryCode": "NG",
    "branchCode": "TRD",
    "SWIFT Code": "CITINGLATRD",
    "Bank Name": "CITIBANK NIGERIA LIMITED",
    "Address": "1 IDOWU TAYLOR STREET",
    "City": "VICTORIA ISLAND",
    "Branch": "TRADE SERVICES DEPARTMENT",
    "Postcode": "101241",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "CMBB",
    "countryCode": "NG",
    "branchCode": "GLA",
    "SWIFT Code": "CMBBNGLA",
    "Bank Name": "CORONATION MERCHANT BANK LIMITED",
    "Address": "10 AMODU OJIKUTU, CORONATION HOUSE",
    "City": "LAGOS",
    "Branch": "",
    "Postcode": "100248",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "ECOC",
    "countryCode": "NG",
    "branchCode": "GLA",
    "SWIFT Code": "ECOCNGLA",
    "Bank Name": "ECOBANK NIGERIA LIMITED",
    "Address": "21 AHMADU BELLO WAY",
    "City": "VICTORIA ISLAND",
    "Branch": "",
    "Postcode": "101241",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "KDHL",
    "countryCode": "NG",
    "branchCode": "GLA",
    "SWIFT Code": "KDHLNGLA",
    "Bank Name": "FBNQUEST MERCHANT BANK LIMITED",
    "Address": "10 KEFFI STREET, S.W. IKOYI",
    "City": "LAGOS",
    "Branch": "",
    "Postcode": "101232",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "FIDT",
    "countryCode": "NG",
    "branchCode": "GLA",
    "SWIFT Code": "FIDTNGLA",
    "Bank Name": "FIDELITY BANK PLC",
    "Address": "2 KOFO ABAYOMI STREET, FIDELITY PLACE",
    "City": "LAGOS",
    "Branch": "",
    "Postcode": "101241",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "FBNI",
    "countryCode": "NG",
    "branchCode": "GLA",
    "SWIFT Code": "FBNINGLA",
    "Bank Name": "FIRST BANK OF NIGERIA LTD",
    "Address": "35 MARINA, SAMUEL ASABIA HOUSE",
    "City": "LAGOS",
    "Branch": "",
    "Postcode": "100221",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "FBNI",
    "countryCode": "NG",
    "branchCode": "GCS",
    "SWIFT Code": "FBNINGLAGCS",
    "Bank Name": "FIRST BANK OF NIGERIA LTD",
    "Address": "",
    "City": "LAGOS",
    "Branch": "CUSTODIAN SERVICES",
    "Postcode": "100001",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "FCMB",
    "countryCode": "NG",
    "branchCode": "GLA",
    "SWIFT Code": "FCMBNGLA",
    "Bank Name": "FIRST CITY MONUMENT BANK LIMITED",
    "Address": "17A TINUBU STREET, PRIMROSE TOWER",
    "City": "LAGOS",
    "Branch": "",
    "Postcode": "100244",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "FCMB",
    "countryCode": "NG",
    "branchCode": "WEB",
    "SWIFT Code": "FCMBNGLAWEB",
    "Bank Name": "FIRST CITY MONUMENT BANK LIMITED",
    "Address": "",
    "City": "LAGOS",
    "Branch": "ELECTRONIC BANKING",
    "Postcode": "100001",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "FMDQ",
    "countryCode": "NG",
    "branchCode": "GLA",
    "SWIFT Code": "FMDQNGLA",
    "Bank Name": "FMDQ SECURITIES EXCHANGE LIMITED",
    "Address": "35 IDOWU TAYLOR STREET, EXCHANGE PLACE",
    "City": "VICTORIA ISLAND",
    "Branch": "",
    "Postcode": "101241",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "FSDH",
    "countryCode": "NG",
    "branchCode": "GLA",
    "SWIFT Code": "FSDHNGLA",
    "Bank Name": "FSDH MERCHANT BANK LTD",
    "Address": "1/5 ODUNLAMI STREET, FLOOR 5-8, UAC HOUSE",
    "City": "LAGOS",
    "Branch": "",
    "Postcode": "100221",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "GLOU",
    "countryCode": "NG",
    "branchCode": "GLA",
    "SWIFT Code": "GLOUNGLA",
    "Bank Name": "GLOBUS BANK LIMITED",
    "Address": "6 ADEYEMO ALAKIJA STREET",
    "City": "VICTORIA ISLAND",
    "Branch": "",
    "Postcode": "101241",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "GMBL",
    "countryCode": "NG",
    "branchCode": "GLA",
    "SWIFT Code": "GMBLNGLA",
    "Bank Name": "GREENWICH MERCHANT BANK LIMITED",
    "Address": "1698A OYIN JOLAYEMI, GREENWICH HOUSE",
    "City": "VICTORIA ISLAND",
    "Branch": "",
    "Postcode": "101241",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "GTBI",
    "countryCode": "NG",
    "branchCode": "IFP",
    "SWIFT Code": "GTBINGLAIFP",
    "Bank Name": "GUARANTY TRUST BANK PLC",
    "Address": "",
    "City": "LAGOS",
    "Branch": "INFO POOL",
    "Postcode": "100001",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "GTBI",
    "countryCode": "NG",
    "branchCode": "GLA",
    "SWIFT Code": "GTBINGLA",
    "Bank Name": "GUARANTY TRUST BANK PLC",
    "Address": "635 AKIN ADESOLA STREET",
    "City": "VICTORIA ISLAND",
    "Branch": "",
    "Postcode": "101241",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "HBCL",
    "countryCode": "NG",
    "branchCode": "GLA",
    "SWIFT Code": "HBCLNGLA",
    "Bank Name": "HERITAGE BANK PLC",
    "Address": "292B AJOSE ADEOGUN",
    "City": "LAGOS",
    "Branch": "",
    "Postcode": "106104",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "HPSB",
    "countryCode": "NG",
    "branchCode": "GLA",
    "SWIFT Code": "HPSBNGLA",
    "Bank Name": "HOPE PSBANK",
    "Address": "3 IDOWU TAYLOR",
    "City": "VICTORIA ISLAND",
    "Branch": "",
    "Postcode": "101241",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "INTW",
    "countryCode": "NG",
    "branchCode": "GL2",
    "SWIFT Code": "INTWNGL2",
    "Bank Name": "INTERSWITCH LIMITED",
    "Address": "1648C OKO AWO STREET",
    "City": "LAGOS",
    "Branch": "",
    "Postcode": "100001",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "JAIZ",
    "countryCode": "NG",
    "branchCode": "GLA",
    "SWIFT Code": "JAIZNGLA",
    "Bank Name": "JAIZ BANK PLC",
    "Address": "1073 J.S TARKA STREET, FLOOR 1, JAIZ BANK HOUSE AREA 3, GARKI",
    "City": "ABUJA",
    "Branch": "",
    "Postcode": "900001",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "PLNI",
    "countryCode": "NG",
    "branchCode": "GLA",
    "SWIFT Code": "PLNINGLA",
    "Bank Name": "KEYSTONE BANK LIMITED",
    "Address": "1 KEYSTONE BANK CRESCENT, KEYSTONE BANK BUILDING",
    "City": "LAGOS",
    "Branch": "",
    "Postcode": "100223",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "LOTU",
    "countryCode": "NG",
    "branchCode": "GLA",
    "SWIFT Code": "LOTUNGLA",
    "Bank Name": "LOTUS BANK LIMITED",
    "Address": "2 BOURDILLON ROAD, IKOYI",
    "City": "LAGOS",
    "Branch": "",
    "Postcode": "101233",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "MMPS",
    "countryCode": "NG",
    "branchCode": "GLA",
    "SWIFT Code": "MMPSNGLA",
    "Bank Name": "MONEYMASTER PAYMENT SERVICE BANK LIMITED",
    "Address": "50 ADEOLA ODEKU STREET",
    "City": "LAGOS",
    "Branch": "",
    "Postcode": "101241",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "NLNG",
    "countryCode": "NG",
    "branchCode": "GLP",
    "SWIFT Code": "NLNGNGLP",
    "Bank Name": "NIGERIA LNG LIMITED",
    "Address": "AMADI CREEK, OFF EASTERN BY-PASS, NLNG CORPORATE HEAD OFFICE, MAKATI",
    "City": "PORT HARCOURT",
    "Branch": "",
    "Postcode": "500241",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "NEXM",
    "countryCode": "NG",
    "branchCode": "GLA",
    "SWIFT Code": "NEXMNGLA",
    "Bank Name": "NIGERIAN EXPORT IMPORT BANK",
    "Address": "975, NEXIM HOUSE, CADASTRAL ZONE AO",
    "City": "ABUJA",
    "Branch": "",
    "Postcode": "900211",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "NNPC",
    "countryCode": "NG",
    "branchCode": "GLA",
    "SWIFT Code": "NNPCNGLA",
    "Bank Name": "NIGERIAN NATIONAL PETROLEUM COMPANY LIMITED",
    "Address": "HERBERT MACAULAY WAY, NNPC TOWERS, CENTRAL BUSINESS DISTRICT",
    "City": "ABUJA",
    "Branch": "",
    "Postcode": "",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "NVMB",
    "countryCode": "NG",
    "branchCode": "GLA",
    "SWIFT Code": "NVMBNGLA",
    "Bank Name": "NOVA MERCHANT BANK LIMITED",
    "Address": "23 KOFO ABOYOMI",
    "City": "VICTORIA ISLAND",
    "Branch": "",
    "Postcode": "103242",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "OPTS",
    "countryCode": "NG",
    "branchCode": "GLA",
    "SWIFT Code": "OPTSNGLA",
    "Bank Name": "OPTIMUS BANK LIMITED",
    "Address": "55 BISHOP OLUWOLE STREET, VICTORIA ISLAND",
    "City": "LAGOS",
    "Branch": "",
    "Postcode": "106104",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "PARA",
    "countryCode": "NG",
    "branchCode": "GLA",
    "SWIFT Code": "PARANGLA",
    "Bank Name": "PARALLEX BANK LIMITED",
    "Address": "PLOT 1261 ADEOLA HOPEWELL STREET",
    "City": "VICTORIA ISLAND",
    "Branch": "",
    "Postcode": "101241",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "PRDT",
    "countryCode": "NG",
    "branchCode": "GLA",
    "SWIFT Code": "PRDTNGLA",
    "Bank Name": "POLARIS BANK LIMITED",
    "Address": "3 AKIN ADESOLA",
    "City": "VICTORIA ISLAND",
    "Branch": "",
    "Postcode": "101241",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "PTRU",
    "countryCode": "NG",
    "branchCode": "GLA",
    "SWIFT Code": "PTRUNGLA",
    "Bank Name": "PREMIUM TRUST BANK LIMITED",
    "Address": "PLOT 1612 ADEOLA HOPEWELL",
    "City": "LAGOS",
    "Branch": "",
    "Postcode": "100001",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "UMPL",
    "countryCode": "NG",
    "branchCode": "GLA",
    "SWIFT Code": "UMPLNGLA",
    "Bank Name": "PROVIDUSBANK PLC",
    "Address": "54 ADETOKUNBO ADEMOLA STREET",
    "City": "LAGOS",
    "Branch": "",
    "Postcode": "101241",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "FIRN",
    "countryCode": "NG",
    "branchCode": "RMS",
    "SWIFT Code": "FIRNNGLARMS",
    "Bank Name": "RAND MERCHANT BANK NIGERIA LIMITED",
    "Address": "17A OZUMBA MBADIWE, FLOOR 2, WINGS TOWER",
    "City": "LAGOS",
    "Branch": "",
    "Postcode": "101241",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "FIRN",
    "countryCode": "NG",
    "branchCode": "GLA",
    "SWIFT Code": "FIRNNGLA",
    "Bank Name": "RAND MERCHANT BANK NIGERIA LIMITED",
    "Address": "17A OZUMBA MBADIWE STREET, FLOOR 3, WINGS TOWER",
    "City": "VICTORIA ISLAND",
    "Branch": "",
    "Postcode": "101241",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "SNIG",
    "countryCode": "NG",
    "branchCode": "GLA",
    "SWIFT Code": "SNIGNGLA",
    "Bank Name": "SIGNATURE BANK LIMITED",
    "Address": "31B, PLOT 1707 GANA STREET, CADASTRAL ZONE A05, MAITAMA",
    "City": "ABUJA",
    "Branch": "",
    "Postcode": "900001",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "SBIC",
    "countryCode": "NG",
    "branchCode": "GLX",
    "SWIFT Code": "SBICNGLX",
    "Bank Name": "STANBIC IBTC BANK PLC",
    "Address": "WALTER CARRINGTON CRESCENT, I.B.T.C. PLACE",
    "City": "VICTORIA ISLAND",
    "Branch": "HEAD OFFICE",
    "Postcode": "101241",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "STIK",
    "countryCode": "NG",
    "branchCode": "GL2",
    "SWIFT Code": "STIKNGL2",
    "Bank Name": "STANBIC IBTC STOCKBROKERS LIMITED",
    "Address": "NA WALTER CARRINGTON CRESCENT, FLOOR 2, STANBIC IBTC PLACE,, BUILDING A VICTORIA ISLAND",
    "City": "LAGOS",
    "Branch": "",
    "Postcode": "100001",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "SCBL",
    "countryCode": "NG",
    "branchCode": "GLA",
    "SWIFT Code": "SCBLNGLA",
    "Bank Name": "STANDARD CHARTERED BANK NIGERIA LIMITED",
    "Address": "142 AHMADU BELLO WAY",
    "City": "VICTORIA ISLAND",
    "Branch": "",
    "Postcode": "101241",
    "Country": "Nigeria",
    "Connection": "Active"
  },
  {
    "bankCode": "SCBL",
    "countryCode": "NG",
    "branchCode": "SSU",
    "SWIFT Code": "SCBLNGLASSU",
    "Bank Name": "STANDARD CHARTERED BANK NIGERIA LIMITED",
    "Address": "142 AHMADU BELLO WAY",
    "City": "VICTORIA ISLAND",
    "Branch": "SECURITIES SERVICES",
    "Postcode": "101241",
    "Country": "Nigeria",
    "Connection": "Active"
  }
]
module.exports = nigeria
