const niger = [
  {
    "bankCode": "AFRI",
    "countryCode": "NE",
    "branchCode": "ENI",
    "SWIFT Code": "AFRINENI",
    "Bank Name": "BANK OF AFRICA NIGER",
    "Address": "IMMEUBLE BOA, RUE DU GAWEYE",
    "City": "NIAMEY",
    "Branch": "",
    "Postcode": "8001",
    "Country": "Niger",
    "Connection": "Active"
  },
  {
    "bankCode": "BANE",
    "countryCode": "NE",
    "branchCode": "ENI",
    "SWIFT Code": "BANENENI",
    "Bank Name": "BANQUE AGRICOLE DU NIGER",
    "Address": "PLACE TOUMO, AVENUE DE L'OUA",
    "City": "NIAMEY",
    "Branch": "",
    "Postcode": "8001",
    "Country": "Niger",
    "Connection": "Active"
  },
  {
    "bankCode": "ATNE",
    "countryCode": "NE",
    "branchCode": "ENI",
    "SWIFT Code": "ATNENENI",
    "Bank Name": "BANQUE ATLANTIQUE NIGER",
    "Address": "IMMEUBLE ATLANTIQUE, ROND POINT DE LA LIBERTE",
    "City": "NIAMEY",
    "Branch": "",
    "Postcode": "8001",
    "Country": "Niger",
    "Connection": "Active"
  },
  {
    "bankCode": "BCAO",
    "countryCode": "NE",
    "branchCode": "MAR",
    "SWIFT Code": "BCAONENIMAR",
    "Bank Name": "BANQUE CENTRALE DES ETATS DE L'AFRIQUE DE L'OUEST",
    "Address": "",
    "City": "MARADI",
    "Branch": "MARADI BRANCH",
    "Postcode": "4000",
    "Country": "Niger",
    "Connection": "Active"
  },
  {
    "bankCode": "BCAO",
    "countryCode": "NE",
    "branchCode": "ENI",
    "SWIFT Code": "BCAONENI",
    "Bank Name": "BANQUE CENTRALE DES ETATS DE L'AFRIQUE DE L'OUEST",
    "Address": "RUE DE L'URANIUM",
    "City": "NIAMEY",
    "Branch": "",
    "Postcode": "8001",
    "Country": "Niger",
    "Connection": "Active"
  },
  {
    "bankCode": "BCAO",
    "countryCode": "NE",
    "branchCode": "ZIN",
    "SWIFT Code": "BCAONENIZIN",
    "Bank Name": "BANQUE CENTRALE DES ETATS DE L'AFRIQUE DE L'OUEST",
    "Address": "",
    "City": "ZINDER",
    "Branch": "ZINDER BRANCH",
    "Postcode": "7000",
    "Country": "Niger",
    "Connection": "Active"
  },
  {
    "bankCode": "BCDN",
    "countryCode": "NE",
    "branchCode": "ENI",
    "SWIFT Code": "BCDNNENI",
    "Bank Name": "BANQUE COMMERCIALE DU NIGER",
    "Address": "RUE DU COMBATTANT, MAOUREY",
    "City": "NIAMEY",
    "Branch": "",
    "Postcode": "11363",
    "Country": "Niger",
    "Connection": "Active"
  },
  {
    "bankCode": "BHDN",
    "countryCode": "NE",
    "branchCode": "ENI",
    "SWIFT Code": "BHDNNENI",
    "Bank Name": "BANQUE DE L'HABITAT DU NIGER - BHN",
    "Address": "IMMEUBLE BHN PLACE TOUMO, AVENUE DE L'OUA",
    "City": "NIAMEY",
    "Branch": "",
    "Postcode": "8001",
    "Country": "Niger",
    "Connection": "Active"
  },
  {
    "bankCode": "BIAN",
    "countryCode": "NE",
    "branchCode": "ENI",
    "SWIFT Code": "BIANNENI",
    "Bank Name": "BANQUE INTERNATIONALE POUR L'AFRIQUE AU NIGER",
    "Address": "AVENUE DE LA MAIRIE",
    "City": "NIAMEY",
    "Branch": "",
    "Postcode": "8001",
    "Country": "Niger",
    "Connection": "Active"
  },
  {
    "bankCode": "BICV",
    "countryCode": "NE",
    "branchCode": "ENI",
    "SWIFT Code": "BICVNENI",
    "Bank Name": "BANQUE ISLAMIQUE DU NIGER POUR LE COMMERCE ET L'INVESTISSEMENT",
    "Address": "IMMEUBLE EL-NASER",
    "City": "NIAMEY",
    "Branch": "",
    "Postcode": "8001",
    "Country": "Niger",
    "Connection": "Active"
  },
  {
    "bankCode": "BRMX",
    "countryCode": "NE",
    "branchCode": "ENI",
    "SWIFT Code": "BRMXNENI",
    "Bank Name": "BANQUE REGIONALE DE MARCHES",
    "Address": "QUARTIER NOUVEAU MARCHE, FLOOR 1, NM2 BOULEVARD DE LA LIBERTE",
    "City": "NIAMEY",
    "Branch": "",
    "Postcode": "8001",
    "Country": "Niger",
    "Connection": "Active"
  },
  {
    "bankCode": "BSAH",
    "countryCode": "NE",
    "branchCode": "ENI",
    "SWIFT Code": "BSAHNENI",
    "Bank Name": "BANQUE SAHELO-SAHARIENNE POUR L'INVESTISSEMENT ET LE COMMERCE (NIGER) S.A.",
    "Address": "193 RUE DE LA COPRO, MAOUREY",
    "City": "NIAMEY",
    "Branch": "",
    "Postcode": "8001",
    "Country": "Niger",
    "Connection": "Active"
  },
  {
    "bankCode": "CBAO",
    "countryCode": "NE",
    "branchCode": "ENI",
    "SWIFT Code": "CBAONENI",
    "Bank Name": "CBAO GROUPE ATTIJARIWAFA BANK",
    "Address": "LOT 573, PARCELLE NO7, QUARTIER TERMINUS RUE HENRICH LUBKE",
    "City": "NIAMEY",
    "Branch": "",
    "Postcode": "8001",
    "Country": "Niger",
    "Connection": "Active"
  },
  {
    "bankCode": "CORI",
    "countryCode": "NE",
    "branchCode": "ENI",
    "SWIFT Code": "CORINENI",
    "Bank Name": "CORIS BANK INTERNATIONAL SA-BRANCH OF NIGER",
    "Address": "NOUVEAU MARCHE, FLOOR 1, NM-2 BOULEVARD DE LA LIBERTE",
    "City": "NIAMEY",
    "Branch": "",
    "Postcode": "8001",
    "Country": "Niger",
    "Connection": "Active"
  },
  {
    "bankCode": "ECOC",
    "countryCode": "NE",
    "branchCode": "ENI",
    "SWIFT Code": "ECOCNENI",
    "Bank Name": "ECOBANK NIGER ECN",
    "Address": "BLD DE LA LIBERTE, ANGLE RUE DES BATISSEURS",
    "City": "NIAMEY",
    "Branch": "",
    "Postcode": "8001",
    "Country": "Niger",
    "Connection": "Active"
  },
  {
    "bankCode": "ORBK",
    "countryCode": "NE",
    "branchCode": "ENI",
    "SWIFT Code": "ORBKNENI",
    "Bank Name": "ORABANK NIGER",
    "Address": "IMMEUBLE BRS, AVENUE DE L'AMITIE",
    "City": "NIAMEY",
    "Branch": "",
    "Postcode": "8001",
    "Country": "Niger",
    "Connection": "Active"
  },
  {
    "bankCode": "SOCN",
    "countryCode": "NE",
    "branchCode": "ENI",
    "SWIFT Code": "SOCNNENI",
    "Bank Name": "SOCIETE NIGERIENNE DE BANQUE",
    "Address": "AVENUE DE LA MAIRIE",
    "City": "NIAMEY",
    "Branch": "",
    "Postcode": "8001",
    "Country": "Niger",
    "Connection": "Active"
  }
]
module.exports = niger
