const norway = [
  {
    "countryCode": "ADNA",
    "bankCode": "NO",
    "branchCode": "OKK",
    "SWIFT Code": "ADNANOKK",
    "Bank Name": "ADEVINTA ASA",
    "Address": "GRENSEN 5",
    "City": "OSLO",
    "Branch": "",
    "Postcode": "0159",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "KBNO",
    "bankCode": "NO",
    "branchCode": "O22",
    "SWIFT Code": "KBNONO22",
    "Bank Name": "BNBANK ASA",
    "Address": "KONGENS GATE 2",
    "City": "TRONDHEIM",
    "Branch": "",
    "Postcode": "7011",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "BNPA",
    "bankCode": "NO",
    "branchCode": "OKK",
    "SWIFT Code": "BNPANOKK",
    "Bank Name": "BNP PARIBAS S.A. NORWAY BRANCH",
    "Address": "STOPERIGATA 2",
    "City": "OSLO",
    "Branch": "",
    "Postcode": "0250",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "PRBO",
    "bankCode": "NO",
    "branchCode": "O22",
    "SWIFT Code": "PRBONO22",
    "Bank Name": "BOLIGBANKEN ASA",
    "Address": "STORGATA 14A",
    "City": "LILLESTROEM",
    "Branch": "",
    "Postcode": "2000",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "MNAS",
    "bankCode": "NO",
    "branchCode": "OB2",
    "SWIFT Code": "MNASNOB2",
    "Bank Name": "BRABANK ASA",
    "Address": "STARVHUSGATEN 4",
    "City": "BERGEN",
    "Branch": "",
    "Postcode": "5014",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "CEND",
    "bankCode": "NO",
    "branchCode": "O22",
    "SWIFT Code": "CENDNO22",
    "Bank Name": "CELSA NORDIC AS",
    "Address": "MO INDUSTRIPARK",
    "City": "MO I RANA",
    "Branch": "",
    "Postcode": "8601",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "CENV",
    "bankCode": "NO",
    "branchCode": "OKK",
    "SWIFT Code": "CENVNOKK",
    "Bank Name": "CENTEVO",
    "Address": "FLOOR 3, RADHUSGATA 4",
    "City": "OSLO",
    "Branch": "",
    "Postcode": "0151",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "CITI",
    "bankCode": "NO",
    "branchCode": "OKX",
    "SWIFT Code": "CITINOKX",
    "Bank Name": "CITIBANK EUROPE PLC NORWAY BRANCH",
    "Address": "BOLETTE BRYGGE 1",
    "City": "OSLO",
    "Branch": "",
    "Postcode": "0252",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "DABA",
    "bankCode": "NO",
    "branchCode": "KSU",
    "SWIFT Code": "DABANO22KSU",
    "Bank Name": "DANSKE BANK A/S",
    "Address": "KNUT SIEMS GATEN 3",
    "City": "KRISTIANSAND",
    "Branch": "KRISTIANSUND",
    "Postcode": "6501",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "DABA",
    "bankCode": "NO",
    "branchCode": "OSL",
    "SWIFT Code": "DABANO22OSL",
    "Bank Name": "DANSKE BANK A/S",
    "Address": "AKERSGATEN 28",
    "City": "OSLO",
    "Branch": "OSLO BRANCH",
    "Postcode": "0107",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "DABA",
    "bankCode": "NO",
    "branchCode": "SKE",
    "SWIFT Code": "DABANO22SKE",
    "Bank Name": "DANSKE BANK A/S",
    "Address": "KONGENS GATEN 9",
    "City": "SKIEN",
    "Branch": "SKIEN BRANCH",
    "Postcode": "3701",
    "Country": "Norway",
    "Connection": "Active"
  },
  {},
  {
    "countryCode": "DABA",
    "bankCode": "NO",
    "branchCode": "STE",
    "SWIFT Code": "DABANO22STE",
    "Bank Name": "DANSKE BANK A/S",
    "Address": "BOMVEIEN 3",
    "City": "STEINKJER",
    "Branch": "STEINKJER",
    "Postcode": "7701",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "DABA",
    "bankCode": "NO",
    "branchCode": "STJ",
    "SWIFT Code": "DABANO22STJ",
    "Bank Name": "DANSKE BANK A/S",
    "Address": "KJOEPMANNSGATEN",
    "City": "STJOERDAL",
    "Branch": "STJOERDAL BRANCH",
    "Postcode": "7501",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "DABA",
    "bankCode": "NO",
    "branchCode": "STO",
    "SWIFT Code": "DABANO22STO",
    "Bank Name": "DANSKE BANK A/S",
    "Address": "BORGGATA 5",
    "City": "STORD",
    "Branch": "STORD BRANCH",
    "Postcode": "5401",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "DABA",
    "bankCode": "NO",
    "branchCode": "TRM",
    "SWIFT Code": "DABANO22TRM",
    "Bank Name": "DANSKE BANK A/S",
    "Address": "STORGATAN 74",
    "City": "TROMSOE",
    "Branch": "TROMSOE BRANCH",
    "Postcode": "9260",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "DABA",
    "bankCode": "NO",
    "branchCode": "O22",
    "SWIFT Code": "DABANO22",
    "Bank Name": "DANSKE BANK A/S",
    "Address": "SONDREGT. 15",
    "City": "TRONDHEIM",
    "Branch": "",
    "Postcode": "7466",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "DABA",
    "bankCode": "NO",
    "branchCode": "CLS",
    "SWIFT Code": "DABANO22CLS",
    "Bank Name": "DANSKE BANK A/S",
    "Address": "VESTRE TOSTEN 77",
    "City": "TRONDHEIM",
    "Branch": "CLS SERVICES",
    "Postcode": "7003",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "DNAM",
    "bankCode": "NO",
    "branchCode": "OKK",
    "SWIFT Code": "DNAMNOKK",
    "Bank Name": "DNB ASSET MANAGEMENT AS",
    "Address": "GATE BYGG DRONNING EUFEMIAS 30,, M-12",
    "City": "OSLO",
    "Branch": "",
    "Postcode": "0191",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "DNBA",
    "bankCode": "NO",
    "branchCode": "OKK",
    "SWIFT Code": "DNBANOKK",
    "Bank Name": "DNB BANK ASA",
    "Address": "DRONNING EUFEMIAS GATE 30",
    "City": "OSLO",
    "Branch": "",
    "Postcode": "0091",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "SBAK",
    "bankCode": "NO",
    "branchCode": "OBB",
    "SWIFT Code": "SBAKNOBB",
    "Bank Name": "DNB BANK ASA",
    "Address": "DRONNING EUFEMIAS 30",
    "City": "OSLO",
    "Branch": "",
    "Postcode": "0191",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "DNBA",
    "bankCode": "NO",
    "branchCode": "OKC",
    "SWIFT Code": "DNBANOKC",
    "Bank Name": "DNB MARKETS CUSTODY, A BUSINESS UNIT OF DNB BANK   ASA, OSLO",
    "Address": "DRONNING EUFEMIAS GATE 30",
    "City": "OSLO",
    "Branch": "",
    "Postcode": "0191",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "DNBA",
    "bankCode": "NO",
    "branchCode": "CLS",
    "SWIFT Code": "DNBANOKXCLS",
    "Bank Name": "DNB MARKETS, A BUSINESS UNIT OF DNB BANK ASA, OSLO",
    "Address": "LARS HILLESGATE 30",
    "City": "BERGEN",
    "Branch": "CLS NOSTRO AGENT CONTROL BRANCH",
    "Postcode": "5020",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "DNBA",
    "bankCode": "NO",
    "branchCode": "OKX",
    "SWIFT Code": "DNBANOKX",
    "Bank Name": "DNB MARKETS, A BUSINESS UNIT OF DNB BANK ASA, OSLO",
    "Address": "DRONNING EUFEMIAS GATE 30",
    "City": "OSLO",
    "Branch": "",
    "Postcode": "0191",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "DNBA",
    "bankCode": "NO",
    "branchCode": "SEC",
    "SWIFT Code": "DNBANOKXSEC",
    "Bank Name": "DNB MARKETS, A BUSINESS UNIT OF DNB BANK ASA, OSLO",
    "Address": "DRONNING EUFEMIAS GATE 30",
    "City": "OSLO",
    "Branch": "",
    "Postcode": "0191",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "DNBA",
    "bankCode": "NO",
    "branchCode": "RPO",
    "SWIFT Code": "DNBANOKXRPO",
    "Bank Name": "DNB MARKETS, A BUSINESS UNIT OF DNB BANK ASA, OSLO",
    "Address": "DRONNING EUFEMIAS GATE 30",
    "City": "OSLO",
    "Branch": "",
    "Postcode": "0191",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "DNVG",
    "bankCode": "NO",
    "branchCode": "O22",
    "SWIFT Code": "DNVGNO22",
    "Bank Name": "DNV GROUP AS",
    "Address": "VERITASVEIEN 1",
    "City": "HOVIK",
    "Branch": "",
    "Postcode": "1363",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "BNPA",
    "bankCode": "NO",
    "branchCode": "OK2",
    "SWIFT Code": "BNPANOK2",
    "Bank Name": "EKSPRESS BANK",
    "Address": "ROSENKRANTZ' GATE 20",
    "City": "OSLO",
    "Branch": "",
    "Postcode": "0160",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "SASA",
    "bankCode": "NO",
    "branchCode": "O22",
    "SWIFT Code": "SASANO22",
    "Bank Name": "EQUINOR ASA",
    "Address": "FORUSBEEN 50",
    "City": "STAVANGER",
    "Branch": "",
    "Postcode": "4035",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "SASA",
    "bankCode": "NO",
    "branchCode": "MMP",
    "SWIFT Code": "SASANO22MMP",
    "Bank Name": "EQUINOR ASA",
    "Address": "FORUSBEEN 50",
    "City": "STAVANGER",
    "Branch": "",
    "Postcode": "4035",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "SASA",
    "bankCode": "NO",
    "branchCode": "TPD",
    "SWIFT Code": "SASANO22TPD",
    "Bank Name": "EQUINOR ASA",
    "Address": "FORUSBEEN 50",
    "City": "STAVANGER",
    "Branch": "",
    "Postcode": "4035",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "STKS",
    "bankCode": "NO",
    "branchCode": "O22",
    "SWIFT Code": "STKSNO22",
    "Bank Name": "EQUINOR ASSET MANAGEMENT AS",
    "Address": "FORUSBEEN 50",
    "City": "STAVANGER",
    "Branch": "",
    "Postcode": "4035",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "FOLT",
    "bankCode": "NO",
    "branchCode": "OKK",
    "SWIFT Code": "FOLTNOKK",
    "Bank Name": "FOLKETRYGDFONDET",
    "Address": "HAAKON VIIS GATE 2",
    "City": "OSLO",
    "Branch": "",
    "Postcode": "0123",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "FRSF",
    "bankCode": "NO",
    "branchCode": "OB2",
    "SWIFT Code": "FRSFNOB2",
    "Bank Name": "FRENDE SKADEFORSIKRING AS",
    "Address": "JONSVOLLSGATEN 2",
    "City": "BERGEN",
    "Branch": "",
    "Postcode": "5011",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "FRSF",
    "bankCode": "NO",
    "branchCode": "OB3",
    "SWIFT Code": "FRSFNOB3",
    "Bank Name": "FRENDE SKADEFORSIKRING AS",
    "Address": "JONSVOLLSGATEN 2",
    "City": "BERGEN",
    "Branch": "",
    "Postcode": "5011",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "HAND",
    "bankCode": "NO",
    "branchCode": "OKK",
    "SWIFT Code": "HANDNOKK",
    "Bank Name": "HANDELSBANKEN",
    "Address": "TJUVHOLMEN ALLE 11, VIKA",
    "City": "OSLO",
    "Branch": "",
    "Postcode": "0252",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "HAND",
    "bankCode": "NO",
    "branchCode": "CUS",
    "SWIFT Code": "HANDNOKKCUS",
    "Bank Name": "HANDELSBANKEN",
    "Address": "",
    "City": "OSLO",
    "Branch": "NORDIC CUSTODY SERVICES",
    "Postcode": "",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "INKT",
    "bankCode": "NO",
    "branchCode": "OK2",
    "SWIFT Code": "INKTNOK2",
    "Bank Name": "INDUSTRIFINANS KPITALFORVALTNING AS",
    "Address": "OSCARS GATE 30",
    "City": "OSLO",
    "Branch": "",
    "Postcode": "0352",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "ISAS",
    "bankCode": "NO",
    "branchCode": "OK2",
    "SWIFT Code": "ISASNOK2",
    "Bank Name": "INSTABANK ASA",
    "Address": "DRAMMENSVEIEN 175",
    "City": "OSLO",
    "Branch": "",
    "Postcode": "0277",
    "Country": "Norway",
    "Connection": "Active"
  },
  {},
  {
    "countryCode": "KOBA",
    "bankCode": "NO",
    "branchCode": "OKK",
    "SWIFT Code": "KOBANOKK",
    "Bank Name": "KOMMUNALBANKEN AS",
    "Address": "HAAKON VIIS GATE 5B",
    "City": "OSLO",
    "Branch": "",
    "Postcode": "0161",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "KBGG",
    "bankCode": "NO",
    "branchCode": "O2K",
    "SWIFT Code": "KBGGNO2K",
    "Bank Name": "KONGSBERG GRUPPEN ASA",
    "Address": "BUILDING 55, KIRKEGAARDSVEIEN 45",
    "City": "KONGSBERG",
    "Branch": "",
    "Postcode": "3616",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "LNLN",
    "bankCode": "NO",
    "branchCode": "D08",
    "SWIFT Code": "LNLNNOB2D08",
    "Bank Name": "LIVSFORSIKRINSSELSKAPET NORDEA LIV NORGE AS",
    "Address": "FOLKE BERNADOTTES VEI 38",
    "City": "BERGEN",
    "Branch": "",
    "Postcode": "5147",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "LNLN",
    "bankCode": "NO",
    "branchCode": "D15",
    "SWIFT Code": "LNLNNOB2D15",
    "Bank Name": "LIVSFORSIKRINSSELSKAPET NORDEA LIV NORGE AS",
    "Address": "FOLKE BERNADOTTES VEI 38",
    "City": "BERGEN",
    "Branch": "",
    "Postcode": "5147",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "LNLN",
    "bankCode": "NO",
    "branchCode": "D09",
    "SWIFT Code": "LNLNNOB2D09",
    "Bank Name": "LIVSFORSIKRINSSELSKAPET NORDEA LIV NORGE AS",
    "Address": "FOLKE BERNADOTTES VEI 38",
    "City": "BERGEN",
    "Branch": "",
    "Postcode": "5147",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "LNLN",
    "bankCode": "NO",
    "branchCode": "D10",
    "SWIFT Code": "LNLNNOB2D10",
    "Bank Name": "LIVSFORSIKRINSSELSKAPET NORDEA LIV NORGE AS",
    "Address": "FOLKE BERNADOTTES VEI 38",
    "City": "BERGEN",
    "Branch": "",
    "Postcode": "5147",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "LNLN",
    "bankCode": "NO",
    "branchCode": "D11",
    "SWIFT Code": "LNLNNOB2D11",
    "Bank Name": "LIVSFORSIKRINSSELSKAPET NORDEA LIV NORGE AS",
    "Address": "FOLKE BERNADOTTES VEI 38",
    "City": "BERGEN",
    "Branch": "",
    "Postcode": "5147",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "LNLN",
    "bankCode": "NO",
    "branchCode": "D14",
    "SWIFT Code": "LNLNNOB2D14",
    "Bank Name": "LIVSFORSIKRINSSELSKAPET NORDEA LIV NORGE AS",
    "Address": "FOLKE BERNADOTTES VEI 38",
    "City": "BERGEN",
    "Branch": "",
    "Postcode": "5147",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "LNLN",
    "bankCode": "NO",
    "branchCode": "D18",
    "SWIFT Code": "LNLNNOB2D18",
    "Bank Name": "LIVSFORSIKRINSSELSKAPET NORDEA LIV NORGE AS",
    "Address": "FOLKE BERNADOTTES VEI 38",
    "City": "BERGEN",
    "Branch": "",
    "Postcode": "5147",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "LNLN",
    "bankCode": "NO",
    "branchCode": "D12",
    "SWIFT Code": "LNLNNOB2D12",
    "Bank Name": "LIVSFORSIKRINSSELSKAPET NORDEA LIV NORGE AS",
    "Address": "FOLKE BERNADOTTES VEI 38",
    "City": "BERGEN",
    "Branch": "",
    "Postcode": "5147",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "SPRO",
    "bankCode": "NO",
    "branchCode": "HAU",
    "SWIFT Code": "SPRONO22HAU",
    "Bank Name": "SPAREBANK 1 SR-BANK ASA",
    "Address": "",
    "City": "HAUGESUND",
    "Branch": "",
    "Postcode": "",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "SPRO",
    "bankCode": "NO",
    "branchCode": "JPL",
    "SWIFT Code": "SPRONO22JPL",
    "Bank Name": "SPAREBANK 1 SR-BANK ASA",
    "Address": "",
    "City": "JOERPELAND",
    "Branch": "",
    "Postcode": "4100",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "SPRO",
    "bankCode": "NO",
    "branchCode": "KRS",
    "SWIFT Code": "SPRONO22KRS",
    "Bank Name": "SPAREBANK 1 SR-BANK ASA",
    "Address": "",
    "City": "KRISTIANSAND",
    "Branch": "",
    "Postcode": "",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "SPRO",
    "bankCode": "NO",
    "branchCode": "OLN",
    "SWIFT Code": "SPRONO22OLN",
    "Bank Name": "SPAREBANK 1 SR-BANK ASA",
    "Address": "",
    "City": "OELEN",
    "Branch": "",
    "Postcode": "5580",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "SPRO",
    "bankCode": "NO",
    "branchCode": "SDS",
    "SWIFT Code": "SPRONO22SDS",
    "Bank Name": "SPAREBANK 1 SR-BANK ASA",
    "Address": "",
    "City": "SANDNES",
    "Branch": "",
    "Postcode": "",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "SPRO",
    "bankCode": "NO",
    "branchCode": "SOL",
    "SWIFT Code": "SPRONO22SOL",
    "Bank Name": "SPAREBANK 1 SR-BANK ASA",
    "Address": "",
    "City": "SOLA",
    "Branch": "",
    "Postcode": "",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "SPRO",
    "bankCode": "NO",
    "branchCode": "O22",
    "SWIFT Code": "SPRONO22",
    "Bank Name": "SPAREBANK 1 SR-BANK ASA",
    "Address": "CHRISTEN TRANES GATE 35",
    "City": "STAVANGER",
    "Branch": "",
    "Postcode": "4007",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "SPAR",
    "bankCode": "NO",
    "branchCode": "O22",
    "SWIFT Code": "SPARNO22",
    "Bank Name": "SPAREBANKEN MOERE",
    "Address": "KEISER WILHELMSG 29/33",
    "City": "AALESUND",
    "Branch": "",
    "Postcode": "6003",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "SAOE",
    "bankCode": "NO",
    "branchCode": "O22",
    "SWIFT Code": "SAOENO22",
    "Bank Name": "SPAREBANKEN OEST",
    "Address": "BRAGERNES TORG 2",
    "City": "DRAMMEN",
    "Branch": "",
    "Postcode": "3017",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "SOFJ",
    "bankCode": "NO",
    "branchCode": "O22",
    "SWIFT Code": "SOFJNO22",
    "Bank Name": "SPAREBANKEN SOGN OG FJORDANE",
    "Address": "LANGEBRUVEIEN 12",
    "City": "FOERDE",
    "Branch": "",
    "Postcode": "6801",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "SPSO",
    "bankCode": "NO",
    "branchCode": "O22",
    "SWIFT Code": "SPSONO22",
    "Bank Name": "SPAREBANKEN SOR",
    "Address": "RADHUSGATEN 7-9",
    "City": "KRISTIANSAND",
    "Branch": "",
    "Postcode": "4611",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "SPAV",
    "bankCode": "NO",
    "branchCode": "OBB",
    "SWIFT Code": "SPAVNOBB",
    "Bank Name": "SPAREBANKEN VEST",
    "Address": "JONSVOLLSGATEN 2",
    "City": "BERGEN",
    "Branch": "",
    "Postcode": "5011",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "STRB",
    "bankCode": "NO",
    "branchCode": "O22",
    "SWIFT Code": "STRBNO22",
    "Bank Name": "STOREBRAND ASSET MANAGEMENT",
    "Address": "PROFESSOR KOHTS VEI 9",
    "City": "LYSAKER",
    "Branch": "",
    "Postcode": "1366",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "SKGN",
    "bankCode": "NO",
    "branchCode": "O22",
    "SWIFT Code": "SKGNNO22",
    "Bank Name": "STOREBRAND ASSET MANAGEMENT",
    "Address": "SKAGEN 3",
    "City": "STAVANGER",
    "Branch": "",
    "Postcode": "4006",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "STFB",
    "bankCode": "NO",
    "branchCode": "OKK",
    "SWIFT Code": "STFBNOKK",
    "Bank Name": "STOREBRAND BANK ASA",
    "Address": "PROFESSOR KOHTS VEI LYSAKER 9",
    "City": "OSLO",
    "Branch": "",
    "Postcode": "1327",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "FISA",
    "bankCode": "NO",
    "branchCode": "OKK",
    "SWIFT Code": "FISANOKK",
    "Bank Name": "SWEDBANK AB",
    "Address": "AKER BRYGGE, FJORDALLEEN 16",
    "City": "OSLO",
    "Branch": "",
    "Postcode": "0250",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "SWED",
    "bankCode": "NO",
    "branchCode": "OKK",
    "SWIFT Code": "SWEDNOKK",
    "Bank Name": "SWEDBANK NORGE",
    "Address": "RUSELOKKVEIEN 36",
    "City": "OSLO",
    "Branch": "",
    "Postcode": "0251",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "TEOR",
    "bankCode": "NO",
    "branchCode": "O22",
    "SWIFT Code": "TEORNO22",
    "Bank Name": "TELENOR ASA",
    "Address": "SNAROYVEIEN 30",
    "City": "FORNEBU",
    "Branch": "",
    "Postcode": "1331",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "TEOR",
    "bankCode": "NO",
    "branchCode": "O2F",
    "SWIFT Code": "TEORNO2F",
    "Bank Name": "TELENOR ASA",
    "Address": "SNAROYVEIEN 30",
    "City": "FORNEBU",
    "Branch": "",
    "Postcode": "1331",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "TFBA",
    "bankCode": "NO",
    "branchCode": "OB2",
    "SWIFT Code": "TFBANOB2",
    "Bank Name": "TF BANK AB",
    "Address": "MARKEVEIEN 1A",
    "City": "BERGEN",
    "Branch": "",
    "Postcode": "5012",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "NKAS",
    "bankCode": "NO",
    "branchCode": "OK2",
    "SWIFT Code": "NKASNOK2",
    "Bank Name": "VERDIPAPIRFONDET NORDEA FRN KREDITT",
    "Address": "ESSENDROPS GATE 7",
    "City": "OSLO",
    "Branch": "",
    "Postcode": "0368",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "VPSN",
    "bankCode": "NO",
    "branchCode": "OKK",
    "SWIFT Code": "VPSNNOKK",
    "Bank Name": "VERDIPAPIRSENTRALEN, VPS",
    "Address": "FRED. OLSENS GATE 1",
    "City": "OSLO",
    "Branch": "",
    "Postcode": "0152",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "VPSN",
    "bankCode": "NO",
    "branchCode": "REC",
    "SWIFT Code": "VPSNNOKKREC",
    "Bank Name": "VERDIPAPIRSENTRALEN, VPS",
    "Address": "FRED. OLSENS GATE 1",
    "City": "OSLO",
    "Branch": "",
    "Postcode": "0152",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "VPSN",
    "bankCode": "NO",
    "branchCode": "CCP",
    "SWIFT Code": "VPSNNOKKCCP",
    "Bank Name": "VERDIPAPIRSENTRALEN, VPS",
    "Address": "FRED. OLSENS GATE 1",
    "City": "OSLO",
    "Branch": "CCP SETTLEMENT",
    "Postcode": "0107",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "VPSN",
    "bankCode": "NO",
    "branchCode": "CLE",
    "SWIFT Code": "VPSNNOKKCLE",
    "Bank Name": "VERDIPAPIRSENTRALEN, VPS",
    "Address": "",
    "City": "OSLO",
    "Branch": "VPS CLEARING",
    "Postcode": "",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "VPSN",
    "bankCode": "NO",
    "branchCode": "CLR",
    "SWIFT Code": "VPSNNOKKCLR",
    "Bank Name": "VERDIPAPIRSENTRALEN, VPS",
    "Address": "",
    "City": "OSLO",
    "Branch": "VPS CLEARING",
    "Postcode": "",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "VPAY",
    "bankCode": "NO",
    "branchCode": "OK2",
    "SWIFT Code": "VPAYNOK2",
    "Bank Name": "VIVA PAYMENT SERVICES SINGLE MEMBER S.A. - NORWAY BRANCH",
    "Address": "RUSELOKKVEIEN 34",
    "City": "OSLO",
    "Branch": "",
    "Postcode": "0251",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "WAWI",
    "bankCode": "NO",
    "branchCode": "O22",
    "SWIFT Code": "WAWINO22",
    "Bank Name": "WALLENIUS WILHELMSEN ASA",
    "Address": "STRANDVEIEN 20",
    "City": "LYSAKER",
    "Branch": "",
    "Postcode": "1366",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "YARA",
    "bankCode": "NO",
    "branchCode": "OKK",
    "SWIFT Code": "YARANOKK",
    "Bank Name": "YARA INTERNATIONAL ASA",
    "Address": "DRAMMENSVEIEN 131",
    "City": "OSLO",
    "Branch": "",
    "Postcode": "0277",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "NEFN",
    "bankCode": "NO",
    "branchCode": "OKK",
    "SWIFT Code": "NEFNNOKK",
    "Bank Name": "NORDNET BANK NUF",
    "Address": "KARL JOHANS GATE 16C",
    "City": "OSLO",
    "Branch": "",
    "Postcode": "0154",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "NFFA",
    "bankCode": "NO",
    "branchCode": "O22",
    "SWIFT Code": "NFFANO22",
    "Bank Name": "NORDNORGE FINANS FORUM ASA",
    "Address": "HAANDVERKEREN 1",
    "City": "ROGNAN",
    "Branch": "",
    "Postcode": "8250",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "NBHK",
    "bankCode": "NO",
    "branchCode": "OKK",
    "SWIFT Code": "NBHKNOKK",
    "Bank Name": "NORGES BANK",
    "Address": "BANKPLASSEN 2, SENTRUM",
    "City": "OSLO",
    "Branch": "",
    "Postcode": "0107",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "NBHK",
    "bankCode": "NO",
    "branchCode": "OKA",
    "SWIFT Code": "NBHKNOKA",
    "Bank Name": "NORGES BANK",
    "Address": "BANKPLASSEN 2",
    "City": "OSLO",
    "Branch": "",
    "Postcode": "",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "NBHK",
    "bankCode": "NO",
    "branchCode": "BRA",
    "SWIFT Code": "NBHKNOKKBRA",
    "Bank Name": "NORGES BANK",
    "Address": "BANKPLASSEN 2",
    "City": "OSLO",
    "Branch": "BRA",
    "Postcode": "0107",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "NBHK",
    "bankCode": "NO",
    "branchCode": "SKK",
    "SWIFT Code": "NBHKNOKKSKK",
    "Bank Name": "NORGES BANK",
    "Address": "BANKPLASSEN 2",
    "City": "OSLO",
    "Branch": "CENTRAL GOVERNMENT'S CONSOLIDATED ACCOUNT SYSTEM",
    "Postcode": "0107",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "NBHK",
    "bankCode": "NO",
    "branchCode": "MOA",
    "SWIFT Code": "NBHKNOKKMOA",
    "Bank Name": "NORGES BANK",
    "Address": "BANKPLASSEN 2",
    "City": "OSLO",
    "Branch": "DEPARTMENT FOR MARKET OPERATIONS AND ANALYSIS",
    "Postcode": "0107",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "NBHK",
    "bankCode": "NO",
    "branchCode": "TVA",
    "SWIFT Code": "NBHKNOKKTVA",
    "Bank Name": "NORGES BANK",
    "Address": "BANKPLASSEN 2",
    "City": "OSLO",
    "Branch": "INTERIM TVANGSBALANSERING",
    "Postcode": "0107",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "NBHK",
    "bankCode": "NO",
    "branchCode": "ASA",
    "SWIFT Code": "NBHKNOKKASA",
    "Bank Name": "NORGES BANK",
    "Address": "BANKPLASSEN 2",
    "City": "OSLO",
    "Branch": "NORGES BANK AS AN AUTHORISED AGENT IN NBO",
    "Postcode": "0107",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "NBHK",
    "bankCode": "NO",
    "branchCode": "SIL",
    "SWIFT Code": "NBHKNOKKSIL",
    "Bank Name": "NORGES BANK",
    "Address": "BANKPLASSEN 2",
    "City": "OSLO",
    "Branch": "NORGES BANK AS EXTERNAL COLLATERAL AGENT (SIL)",
    "Postcode": "0107",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "NBHK",
    "bankCode": "NO",
    "branchCode": "KOL",
    "SWIFT Code": "NBHKNOKKKOL",
    "Bank Name": "NORGES BANK",
    "Address": "BANKPLASSEN 2",
    "City": "OSLO",
    "Branch": "NORGES BANK KOLLOR ASA",
    "Postcode": "0107",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "NBHK",
    "bankCode": "NO",
    "branchCode": "005",
    "SWIFT Code": "NBHKNOKK005",
    "Bank Name": "NORGES BANK",
    "Address": "BANKPLASSEN 2",
    "City": "OSLO",
    "Branch": "PARTICIPANT005",
    "Postcode": "0107",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "NBHK",
    "bankCode": "NO",
    "branchCode": "006",
    "SWIFT Code": "NBHKNOKK006",
    "Bank Name": "NORGES BANK",
    "Address": "BANKPLASSEN 2",
    "City": "OSLO",
    "Branch": "PARTICIPANT006",
    "Postcode": "0107",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "NBHK",
    "bankCode": "NO",
    "branchCode": "007",
    "SWIFT Code": "NBHKNOKK007",
    "Bank Name": "NORGES BANK",
    "Address": "BANKPLASSEN 2",
    "City": "OSLO",
    "Branch": "PARTICIPANT007",
    "Postcode": "0107",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "NBHK",
    "bankCode": "NO",
    "branchCode": "008",
    "SWIFT Code": "NBHKNOKK008",
    "Bank Name": "NORGES BANK",
    "Address": "BANKPLASSEN 2",
    "City": "OSLO",
    "Branch": "PARTICIPANT008",
    "Postcode": "0107",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "NBHK",
    "bankCode": "NO",
    "branchCode": "009",
    "SWIFT Code": "NBHKNOKK009",
    "Bank Name": "NORGES BANK",
    "Address": "BANKPLASSEN 2",
    "City": "OSLO",
    "Branch": "PARTICIPANT009",
    "Postcode": "0107",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "NBHK",
    "bankCode": "NO",
    "branchCode": "010",
    "SWIFT Code": "NBHKNOKK010",
    "Bank Name": "NORGES BANK",
    "Address": "BANKPLASSEN 2",
    "City": "OSLO",
    "Branch": "PARTICIPANT010",
    "Postcode": "0107",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "NBHK",
    "bankCode": "NO",
    "branchCode": "011",
    "SWIFT Code": "NBHKNOKK011",
    "Bank Name": "NORGES BANK",
    "Address": "BANKPLASSEN 2",
    "City": "OSLO",
    "Branch": "PARTICIPANT011",
    "Postcode": "0107",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "NBHK",
    "bankCode": "NO",
    "branchCode": "012",
    "SWIFT Code": "NBHKNOKK012",
    "Bank Name": "NORGES BANK",
    "Address": "BANKPLASSEN 2",
    "City": "OSLO",
    "Branch": "PARTICIPANT012",
    "Postcode": "0107",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "NBHK",
    "bankCode": "NO",
    "branchCode": "013",
    "SWIFT Code": "NBHKNOKK013",
    "Bank Name": "NORGES BANK",
    "Address": "BANKPLASSEN 2",
    "City": "OSLO",
    "Branch": "PARTICIPANT013",
    "Postcode": "0107",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "NBHK",
    "bankCode": "NO",
    "branchCode": "014",
    "SWIFT Code": "NBHKNOKK014",
    "Bank Name": "NORGES BANK",
    "Address": "BANKPLASSEN 2",
    "City": "OSLO",
    "Branch": "PARTICIPANT014",
    "Postcode": "0107",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "NBHK",
    "bankCode": "NO",
    "branchCode": "015",
    "SWIFT Code": "NBHKNOKK015",
    "Bank Name": "NORGES BANK",
    "Address": "BANKPLASSEN 2",
    "City": "OSLO",
    "Branch": "PARTICIPANT015",
    "Postcode": "0107",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "NBHK",
    "bankCode": "NO",
    "branchCode": "016",
    "SWIFT Code": "NBHKNOKK016",
    "Bank Name": "NORGES BANK",
    "Address": "BANKPLASSEN 2",
    "City": "OSLO",
    "Branch": "PARTICIPANT016",
    "Postcode": "0107",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "NBHK",
    "bankCode": "NO",
    "branchCode": "017",
    "SWIFT Code": "NBHKNOKK017",
    "Bank Name": "NORGES BANK",
    "Address": "BANKPLASSEN 2",
    "City": "OSLO",
    "Branch": "PARTICIPANT017",
    "Postcode": "0107",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "NBHK",
    "bankCode": "NO",
    "branchCode": "018",
    "SWIFT Code": "NBHKNOKK018",
    "Bank Name": "NORGES BANK",
    "Address": "BANKPLASSEN 2",
    "City": "OSLO",
    "Branch": "PARTICIPANT018",
    "Postcode": "0107",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "NBHK",
    "bankCode": "NO",
    "branchCode": "019",
    "SWIFT Code": "NBHKNOKK019",
    "Bank Name": "NORGES BANK",
    "Address": "BANKPLASSEN 2",
    "City": "OSLO",
    "Branch": "PARTICIPANT019",
    "Postcode": "0107",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "NBHK",
    "bankCode": "NO",
    "branchCode": "020",
    "SWIFT Code": "NBHKNOKK020",
    "Bank Name": "NORGES BANK",
    "Address": "BANKPLASSEN 2",
    "City": "OSLO",
    "Branch": "PARTICIPANT020",
    "Postcode": "0107",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "NBHK",
    "bankCode": "NO",
    "branchCode": "021",
    "SWIFT Code": "NBHKNOKK021",
    "Bank Name": "NORGES BANK",
    "Address": "BANKPLASSEN 2",
    "City": "OSLO",
    "Branch": "PARTICIPANT021",
    "Postcode": "0107",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "NBHK",
    "bankCode": "NO",
    "branchCode": "022",
    "SWIFT Code": "NBHKNOKK022",
    "Bank Name": "NORGES BANK",
    "Address": "BANKPLASSEN 2",
    "City": "OSLO",
    "Branch": "PARTICIPANT022",
    "Postcode": "0107",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "NBHK",
    "bankCode": "NO",
    "branchCode": "023",
    "SWIFT Code": "NBHKNOKK023",
    "Bank Name": "NORGES BANK",
    "Address": "BANKPLASSEN 2",
    "City": "OSLO",
    "Branch": "PARTICIPANT023",
    "Postcode": "0107",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "NBHK",
    "bankCode": "NO",
    "branchCode": "024",
    "SWIFT Code": "NBHKNOKK024",
    "Bank Name": "NORGES BANK",
    "Address": "BANKPLASSEN 2",
    "City": "OSLO",
    "Branch": "PARTICIPANT024",
    "Postcode": "0107",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "NBHK",
    "bankCode": "NO",
    "branchCode": "025",
    "SWIFT Code": "NBHKNOKK025",
    "Bank Name": "NORGES BANK",
    "Address": "BANKPLASSEN 2",
    "City": "OSLO",
    "Branch": "PARTICIPANT025",
    "Postcode": "0107",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "NBHK",
    "bankCode": "NO",
    "branchCode": "026",
    "SWIFT Code": "NBHKNOKK026",
    "Bank Name": "NORGES BANK",
    "Address": "BANKPLASSEN 2",
    "City": "OSLO",
    "Branch": "PARTICIPANT026",
    "Postcode": "0107",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "NBHK",
    "bankCode": "NO",
    "branchCode": "027",
    "SWIFT Code": "NBHKNOKK027",
    "Bank Name": "NORGES BANK",
    "Address": "BANKPLASSEN 2",
    "City": "OSLO",
    "Branch": "PARTICIPANT027",
    "Postcode": "0107",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "NBHK",
    "bankCode": "NO",
    "branchCode": "028",
    "SWIFT Code": "NBHKNOKK028",
    "Bank Name": "NORGES BANK",
    "Address": "BANKPLASSEN 2",
    "City": "OSLO",
    "Branch": "PARTICIPANT028",
    "Postcode": "0107",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "NBHK",
    "bankCode": "NO",
    "branchCode": "029",
    "SWIFT Code": "NBHKNOKK029",
    "Bank Name": "NORGES BANK",
    "Address": "BANKPLASSEN 2",
    "City": "OSLO",
    "Branch": "PARTICIPANT029",
    "Postcode": "0107",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "NBHK",
    "bankCode": "NO",
    "branchCode": "030",
    "SWIFT Code": "NBHKNOKK030",
    "Bank Name": "NORGES BANK",
    "Address": "BANKPLASSEN 2",
    "City": "OSLO",
    "Branch": "PARTICIPANT030",
    "Postcode": "0107",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "NBHK",
    "bankCode": "NO",
    "branchCode": "031",
    "SWIFT Code": "NBHKNOKK031",
    "Bank Name": "NORGES BANK",
    "Address": "BANKPLASSEN 2",
    "City": "OSLO",
    "Branch": "PARTICIPANT031",
    "Postcode": "0107",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "NBHK",
    "bankCode": "NO",
    "branchCode": "032",
    "SWIFT Code": "NBHKNOKK032",
    "Bank Name": "NORGES BANK",
    "Address": "BANKPLASSEN 2",
    "City": "OSLO",
    "Branch": "PARTICIPANT032",
    "Postcode": "0107",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "NBHK",
    "bankCode": "NO",
    "branchCode": "033",
    "SWIFT Code": "NBHKNOKK033",
    "Bank Name": "NORGES BANK",
    "Address": "BANKPLASSEN 2",
    "City": "OSLO",
    "Branch": "PARTICIPANT033",
    "Postcode": "0107",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "NBHK",
    "bankCode": "NO",
    "branchCode": "034",
    "SWIFT Code": "NBHKNOKK034",
    "Bank Name": "NORGES BANK",
    "Address": "BANKPLASSEN 2",
    "City": "OSLO",
    "Branch": "PARTICIPANT034",
    "Postcode": "0107",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "NBHK",
    "bankCode": "NO",
    "branchCode": "035",
    "SWIFT Code": "NBHKNOKK035",
    "Bank Name": "NORGES BANK",
    "Address": "BANKPLASSEN 2",
    "City": "OSLO",
    "Branch": "PARTICIPANT035",
    "Postcode": "0107",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "NBHK",
    "bankCode": "NO",
    "branchCode": "036",
    "SWIFT Code": "NBHKNOKK036",
    "Bank Name": "NORGES BANK",
    "Address": "BANKPLASSEN 2",
    "City": "OSLO",
    "Branch": "PARTICIPANT036",
    "Postcode": "0107",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "NBHK",
    "bankCode": "NO",
    "branchCode": "037",
    "SWIFT Code": "NBHKNOKK037",
    "Bank Name": "NORGES BANK",
    "Address": "BANKPLASSEN 2",
    "City": "OSLO",
    "Branch": "PARTICIPANT037",
    "Postcode": "0107",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "NBHK",
    "bankCode": "NO",
    "branchCode": "038",
    "SWIFT Code": "NBHKNOKK038",
    "Bank Name": "NORGES BANK",
    "Address": "BANKPLASSEN 2",
    "City": "OSLO",
    "Branch": "PARTICIPANT038",
    "Postcode": "0107",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "NBHK",
    "bankCode": "NO",
    "branchCode": "039",
    "SWIFT Code": "NBHKNOKK039",
    "Bank Name": "NORGES BANK",
    "Address": "BANKPLASSEN 2",
    "City": "OSLO",
    "Branch": "PARTICIPANT039",
    "Postcode": "0107",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "NBHK",
    "bankCode": "NO",
    "branchCode": "040",
    "SWIFT Code": "NBHKNOKK040",
    "Bank Name": "NORGES BANK",
    "Address": "BANKPLASSEN 2",
    "City": "OSLO",
    "Branch": "PARTICIPANT040",
    "Postcode": "0107",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "NBHK",
    "bankCode": "NO",
    "branchCode": "041",
    "SWIFT Code": "NBHKNOKK041",
    "Bank Name": "NORGES BANK",
    "Address": "BANKPLASSEN 2",
    "City": "OSLO",
    "Branch": "PARTICIPANT041",
    "Postcode": "0107",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "NBHK",
    "bankCode": "NO",
    "branchCode": "042",
    "SWIFT Code": "NBHKNOKK042",
    "Bank Name": "NORGES BANK",
    "Address": "BANKPLASSEN 2",
    "City": "OSLO",
    "Branch": "PARTICIPANT042",
    "Postcode": "0107",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "NBHK",
    "bankCode": "NO",
    "branchCode": "043",
    "SWIFT Code": "NBHKNOKK043",
    "Bank Name": "NORGES BANK",
    "Address": "BANKPLASSEN 2",
    "City": "OSLO",
    "Branch": "PARTICIPANT043",
    "Postcode": "0107",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "NBHK",
    "bankCode": "NO",
    "branchCode": "044",
    "SWIFT Code": "NBHKNOKK044",
    "Bank Name": "NORGES BANK",
    "Address": "BANKPLASSEN 2",
    "City": "OSLO",
    "Branch": "PARTICIPANT044",
    "Postcode": "0107",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "NBHK",
    "bankCode": "NO",
    "branchCode": "045",
    "SWIFT Code": "NBHKNOKK045",
    "Bank Name": "NORGES BANK",
    "Address": "BANKPLASSEN 2",
    "City": "OSLO",
    "Branch": "PARTICIPANT045",
    "Postcode": "0107",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "NBHK",
    "bankCode": "NO",
    "branchCode": "046",
    "SWIFT Code": "NBHKNOKK046",
    "Bank Name": "NORGES BANK",
    "Address": "BANKPLASSEN 2",
    "City": "OSLO",
    "Branch": "PARTICIPANT046",
    "Postcode": "0107",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "NBHK",
    "bankCode": "NO",
    "branchCode": "047",
    "SWIFT Code": "NBHKNOKK047",
    "Bank Name": "NORGES BANK",
    "Address": "BANKPLASSEN 2",
    "City": "OSLO",
    "Branch": "PARTICIPANT047",
    "Postcode": "0107",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "NBHK",
    "bankCode": "NO",
    "branchCode": "048",
    "SWIFT Code": "NBHKNOKK048",
    "Bank Name": "NORGES BANK",
    "Address": "BANKPLASSEN 2",
    "City": "OSLO",
    "Branch": "PARTICIPANT048",
    "Postcode": "0107",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "NBHK",
    "bankCode": "NO",
    "branchCode": "049",
    "SWIFT Code": "NBHKNOKK049",
    "Bank Name": "NORGES BANK",
    "Address": "BANKPLASSEN 2",
    "City": "OSLO",
    "Branch": "PARTICIPANT049",
    "Postcode": "0107",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "NBHK",
    "bankCode": "NO",
    "branchCode": "050",
    "SWIFT Code": "NBHKNOKK050",
    "Bank Name": "NORGES BANK",
    "Address": "BANKPLASSEN 2",
    "City": "OSLO",
    "Branch": "PARTICIPANT050",
    "Postcode": "0107",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "NBHK",
    "bankCode": "NO",
    "branchCode": "100",
    "SWIFT Code": "NBHKNOKK100",
    "Bank Name": "NORGES BANK",
    "Address": "BANKPLASSEN 2, SENTRUM",
    "City": "OSLO",
    "Branch": "PARTICIPANT100",
    "Postcode": "0107",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "NBHK",
    "bankCode": "NO",
    "branchCode": "101",
    "SWIFT Code": "NBHKNOKK101",
    "Bank Name": "NORGES BANK",
    "Address": "BANKPLASSEN 2, SENTRUM",
    "City": "OSLO",
    "Branch": "PARTICIPANT101",
    "Postcode": "0107",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "NBHK",
    "bankCode": "NO",
    "branchCode": "102",
    "SWIFT Code": "NBHKNOKK102",
    "Bank Name": "NORGES BANK",
    "Address": "BANKPLASSEN 2, SENTRUM",
    "City": "OSLO",
    "Branch": "PARTICIPANT102",
    "Postcode": "0107",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "NBHK",
    "bankCode": "NO",
    "branchCode": "103",
    "SWIFT Code": "NBHKNOKK103",
    "Bank Name": "NORGES BANK",
    "Address": "BANKPLASSEN 2, SENTRUM",
    "City": "OSLO",
    "Branch": "PARTICIPANT103",
    "Postcode": "0107",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "NBHK",
    "bankCode": "NO",
    "branchCode": "S01",
    "SWIFT Code": "NBHKNOKKS01",
    "Bank Name": "NORGES BANK",
    "Address": "BANKPLASSEN 21",
    "City": "OSLO",
    "Branch": "S-LAAN1",
    "Postcode": "0107",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "NBHK",
    "bankCode": "NO",
    "branchCode": "S02",
    "SWIFT Code": "NBHKNOKKS02",
    "Bank Name": "NORGES BANK",
    "Address": "BANKPLASSEN 2",
    "City": "OSLO",
    "Branch": "S-LAAN2",
    "Postcode": "0107",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "NBHK",
    "bankCode": "NO",
    "branchCode": "S03",
    "SWIFT Code": "NBHKNOKKS03",
    "Bank Name": "NORGES BANK",
    "Address": "BANKPLASSEN 2",
    "City": "OSLO",
    "Branch": "S-LAAN3",
    "Postcode": "0107",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "NBHK",
    "bankCode": "NO",
    "branchCode": "S04",
    "SWIFT Code": "NBHKNOKKS04",
    "Bank Name": "NORGES BANK",
    "Address": "BANKPLASSEN 2",
    "City": "OSLO",
    "Branch": "S-LAAN4",
    "Postcode": "0107",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "NBHK",
    "bankCode": "NO",
    "branchCode": "S05",
    "SWIFT Code": "NBHKNOKKS05",
    "Bank Name": "NORGES BANK",
    "Address": "BANKPLASSEN 2",
    "City": "OSLO",
    "Branch": "S-LAAN5",
    "Postcode": "0107",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "NBHK",
    "bankCode": "NO",
    "branchCode": "TIA",
    "SWIFT Code": "NBHKNOKKTIA",
    "Bank Name": "NORGES BANK",
    "Address": "BANKPLASSEN 2",
    "City": "OSLO",
    "Branch": "TECHNICAL INFRASTRUCTURE AGENT ROLE FOR NBO",
    "Postcode": "0107",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "NBHK",
    "bankCode": "NO",
    "branchCode": "TIK",
    "SWIFT Code": "NBHKNOKKTIK",
    "Bank Name": "NORGES BANK",
    "Address": "BANKPLASSEN 2",
    "City": "OSLO",
    "Branch": "TIA ROLE FOR KOLLOR NBO",
    "Postcode": "0107",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "NGIM",
    "bankCode": "NO",
    "branchCode": "OKK",
    "SWIFT Code": "NGIMNOKK",
    "Bank Name": "NORGES BANK (DIVISION NORGES BANK INVESTMENT MANAGEMENT)",
    "Address": "BANKPLASSEN 2",
    "City": "OSLO",
    "Branch": "",
    "Postcode": "0107",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "NBRE",
    "bankCode": "NO",
    "branchCode": "OKK",
    "SWIFT Code": "NBRENOKK",
    "Bank Name": "NORGES BANK -DIV. REAL ASSETS",
    "Address": "BANKPLASSEN 2",
    "City": "OSLO",
    "Branch": "",
    "Postcode": "0151",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "NHYD",
    "bankCode": "NO",
    "branchCode": "OKK",
    "SWIFT Code": "NHYDNOKK",
    "Bank Name": "NORSK HYDRO A.S.A., HYDRO FINANS",
    "Address": "DRAMMESVEIEN 264",
    "City": "OSLO",
    "Branch": "",
    "Postcode": "0283",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "NHYD",
    "bankCode": "NO",
    "branchCode": "HIF",
    "SWIFT Code": "NHYDNOKKHIF",
    "Bank Name": "NORSK HYDRO A.S.A., HYDRO FINANS",
    "Address": "DRAMMESVEIEN 264",
    "City": "OSLO",
    "Branch": "",
    "Postcode": "0283",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "NHYD",
    "bankCode": "NO",
    "branchCode": "HPJ",
    "SWIFT Code": "NHYDNOKKHPJ",
    "Bank Name": "NORSK HYDRO A.S.A., HYDRO FINANS",
    "Address": "DRAMMESVEIEN 264",
    "City": "OSLO",
    "Branch": "",
    "Postcode": "0283",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "ODFO",
    "bankCode": "NO",
    "branchCode": "OKK",
    "SWIFT Code": "ODFONOKK",
    "Bank Name": "ODIN FORVALTNING AS",
    "Address": "FJORDALLEEN 16",
    "City": "OSLO",
    "Branch": "",
    "Postcode": "0250",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "OPAS",
    "bankCode": "NO",
    "branchCode": "OK2",
    "SWIFT Code": "OPASNOK2",
    "Bank Name": "OPTIN BANK ASA",
    "Address": "MUNKEDAMSVEIEN 53B",
    "City": "OSLO",
    "Branch": "",
    "Postcode": "0250",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "SASK",
    "bankCode": "NO",
    "branchCode": "O22",
    "SWIFT Code": "SASKNO22",
    "Bank Name": "SANDNES SPAREBANK",
    "Address": "",
    "City": "SANDNES",
    "Branch": "",
    "Postcode": "4319",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "BSNO",
    "bankCode": "NO",
    "branchCode": "OKK",
    "SWIFT Code": "BSNONOKK",
    "Bank Name": "SANTANDER CONSUMER BANK AS",
    "Address": "STRANDVEIEN 18",
    "City": "LYSAKER",
    "Branch": "",
    "Postcode": "1366",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "SEGP",
    "bankCode": "NO",
    "branchCode": "OK2",
    "SWIFT Code": "SEGPNOK2",
    "Bank Name": "SETTLE GROUP AS",
    "Address": "TORDENSKIOLDS GATA 8-10",
    "City": "OSLO",
    "Branch": "",
    "Postcode": "0160",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "OSCL",
    "bankCode": "NO",
    "branchCode": "OKK",
    "SWIFT Code": "OSCLNOKK",
    "Bank Name": "SIX X-CLEAR AG NORWEGIAN BRANCH",
    "Address": "ROSENKRANTZ GATE 20",
    "City": "OSLO",
    "Branch": "",
    "Postcode": "0160",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "OSCL",
    "bankCode": "NO",
    "branchCode": "OKX",
    "SWIFT Code": "OSCLNOKX",
    "Bank Name": "SIX X-CLEAR AG NORWEGIAN BRANCH",
    "Address": "ROSENKRANTZ GATE 20",
    "City": "OSLO",
    "Branch": "",
    "Postcode": "0160",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "OSCL",
    "bankCode": "NO",
    "branchCode": "CLN",
    "SWIFT Code": "OSCLNOKXCLN",
    "Bank Name": "SIX X-CLEAR AG NORWEGIAN BRANCH",
    "Address": "TOLLBUGATA",
    "City": "OSLO",
    "Branch": "",
    "Postcode": "0152",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "OSCL",
    "bankCode": "NO",
    "branchCode": "CLR",
    "SWIFT Code": "OSCLNOKXCLR",
    "Bank Name": "SIX X-CLEAR AG NORWEGIAN BRANCH",
    "Address": "TOLLBUGATA",
    "City": "OSLO",
    "Branch": "",
    "Postcode": "0152",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "OSCL",
    "bankCode": "NO",
    "branchCode": "LAN",
    "SWIFT Code": "OSCLNOKKLAN",
    "Bank Name": "SIX X-CLEAR AG NORWEGIAN BRANCH",
    "Address": "TOLLBUGATA 2",
    "City": "OSLO",
    "Branch": "OSLO CLEARING",
    "Postcode": "0152",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "OSCL",
    "bankCode": "NO",
    "branchCode": "VPO",
    "SWIFT Code": "OSCLNOKKVPO",
    "Bank Name": "SIX X-CLEAR AG NORWEGIAN BRANCH",
    "Address": "TOLLBUGATA",
    "City": "OSLO",
    "Branch": "OSLO CLEARING",
    "Postcode": "0152",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "ESSE",
    "bankCode": "NO",
    "branchCode": "PRB",
    "SWIFT Code": "ESSENOKXPRB",
    "Bank Name": "SKANDINAVISKA ENSKILDA BANKEN",
    "Address": "FILIPSTAD BRYGGE 1, VIKA",
    "City": "OSLO",
    "Branch": "PROBROKER",
    "Postcode": "0252",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "ESSE",
    "bankCode": "NO",
    "branchCode": "CLS",
    "SWIFT Code": "ESSENOKXCLS",
    "Bank Name": "SKANDINAVISKA ENSKILDA BANKEN AB (PUBL) OSLOFILIALEN",
    "Address": "",
    "City": "OSLO",
    "Branch": "",
    "Postcode": "",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "ESSE",
    "bankCode": "NO",
    "branchCode": "OKX",
    "SWIFT Code": "ESSENOKX",
    "Bank Name": "SKANDINAVISKA ENSKILDA BANKEN AB (PUBL) OSLOFILIALEN",
    "Address": "FILIPSTAD BRYGGE 1, VIKA",
    "City": "OSLO",
    "Branch": "",
    "Postcode": "0252",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "ESSE",
    "bankCode": "NO",
    "branchCode": "CAL",
    "SWIFT Code": "ESSENOKXCAL",
    "Bank Name": "SKANDINAVISKA ENSKILDA BANKEN AB (PUBL) OSLOFILIALEN",
    "Address": "",
    "City": "OSLO",
    "Branch": "SEB OSLO CALYPSO BRANCH CODE",
    "Postcode": "",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "ENSK",
    "bankCode": "NO",
    "branchCode": "OKK",
    "SWIFT Code": "ENSKNOKK",
    "Bank Name": "SKANDINAVISKA ENSKILDA BANKEN AB (PUBL) OSLOFILIALEN (FORMERLY SEB ENSKILDA AS)",
    "Address": "FILIPSTAD BRYGGE 1, VIKA",
    "City": "OSLO",
    "Branch": "",
    "Postcode": "0075",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "ESSE",
    "bankCode": "NO",
    "branchCode": "O22",
    "SWIFT Code": "ESSENO22",
    "Bank Name": "SKANDINAVISKA ENSKILDA BANKEN AB (PUBL) OSLOFILIALEN (FORMERLY SEB PRIVATE BANKING)",
    "Address": "FILIPSTAD BRYGGE 1, VIKA",
    "City": "OSLO",
    "Branch": "",
    "Postcode": "0123",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "SNOW",
    "bankCode": "NO",
    "branchCode": "O22",
    "SWIFT Code": "SNOWNO22",
    "Bank Name": "SPAREBANK 1 NORD-NORGE",
    "Address": "STORGATEN 65",
    "City": "TROMSOE",
    "Branch": "",
    "Postcode": "9005",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "SHED",
    "bankCode": "NO",
    "branchCode": "O22",
    "SWIFT Code": "SHEDNO22",
    "Bank Name": "SPAREBANK 1 OSTLANDET (FORMERLY SPAREBANKEN HEDMARK)",
    "Address": "STRANDGATA 15",
    "City": "HAMAR",
    "Branch": "HEAD OFFICE",
    "Postcode": "2317",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "SHED",
    "bankCode": "NO",
    "branchCode": "KVR",
    "SWIFT Code": "SHEDNO22KVR",
    "Bank Name": "SPAREBANK 1 OSTLANDET (FORMERLY SPAREBANKEN HEDMARK)",
    "Address": "",
    "City": "KONGSVINGER",
    "Branch": "KONGSVINGER BRANCH",
    "Postcode": "2201",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "SPTR",
    "bankCode": "NO",
    "branchCode": "SB1",
    "SWIFT Code": "SPTRNO22SB1",
    "Bank Name": "SPAREBANK 1 SMN",
    "Address": "OLAV VS GT",
    "City": "OSLO",
    "Branch": "SPAREBANK 1 MARKETS",
    "Postcode": "0161",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "SPTR",
    "bankCode": "NO",
    "branchCode": "O22",
    "SWIFT Code": "SPTRNO22",
    "Bank Name": "SPAREBANK 1 SMN",
    "Address": "SONDRE GATE 4, SLUPPEN",
    "City": "TRONDHEIM",
    "Branch": "",
    "Postcode": "7467",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "SPRO",
    "bankCode": "NO",
    "branchCode": "AGD",
    "SWIFT Code": "SPRONO22AGD",
    "Bank Name": "SPAREBANK 1 SR-BANK ASA",
    "Address": "",
    "City": "AALGAARD",
    "Branch": "",
    "Postcode": "4330",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "SPRO",
    "bankCode": "NO",
    "branchCode": "BNE",
    "SWIFT Code": "SPRONO22BNE",
    "Bank Name": "SPAREBANK 1 SR-BANK ASA",
    "Address": "",
    "City": "BRYNE",
    "Branch": "",
    "Postcode": "4340",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "SPRO",
    "bankCode": "NO",
    "branchCode": "EGE",
    "SWIFT Code": "SPRONO22EGE",
    "Bank Name": "SPAREBANK 1 SR-BANK ASA",
    "Address": "",
    "City": "EGERSUND",
    "Branch": "",
    "Postcode": "4370",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "SPRO",
    "bankCode": "NO",
    "branchCode": "FLE",
    "SWIFT Code": "SPRONO22FLE",
    "Bank Name": "SPAREBANK 1 SR-BANK ASA",
    "Address": "",
    "City": "FLEKKEFJORD",
    "Branch": "",
    "Postcode": "",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "SPRO",
    "bankCode": "NO",
    "branchCode": "FOR",
    "SWIFT Code": "SPRONO22FOR",
    "Bank Name": "SPAREBANK 1 SR-BANK ASA",
    "Address": "",
    "City": "FORUS",
    "Branch": "",
    "Postcode": "4068",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "LNLN",
    "bankCode": "NO",
    "branchCode": "Z23",
    "SWIFT Code": "LNLNNOB2Z23",
    "Bank Name": "LIVSFORSIKRINSSELSKAPET NORDEA LIV NORGE AS",
    "Address": "FOLKE BERNADOTTES VEI 38",
    "City": "BERGEN",
    "Branch": "",
    "Postcode": "5147",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "LNLN",
    "bankCode": "NO",
    "branchCode": "Z22",
    "SWIFT Code": "LNLNNOB2Z22",
    "Bank Name": "LIVSFORSIKRINSSELSKAPET NORDEA LIV NORGE AS",
    "Address": "FOLKE BERNADOTTES VEI 38",
    "City": "BERGEN",
    "Branch": "",
    "Postcode": "5147",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "LNLN",
    "bankCode": "NO",
    "branchCode": "Z21",
    "SWIFT Code": "LNLNNOB2Z21",
    "Bank Name": "LIVSFORSIKRINSSELSKAPET NORDEA LIV NORGE AS",
    "Address": "FOLKE BERNADOTTES VEI 38",
    "City": "BERGEN",
    "Branch": "",
    "Postcode": "5147",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "LNLN",
    "bankCode": "NO",
    "branchCode": "Z20",
    "SWIFT Code": "LNLNNOB2Z20",
    "Bank Name": "LIVSFORSIKRINSSELSKAPET NORDEA LIV NORGE AS",
    "Address": "FOLKE BERNADOTTES VEI 38",
    "City": "BERGEN",
    "Branch": "",
    "Postcode": "5147",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "LNLN",
    "bankCode": "NO",
    "branchCode": "Z19",
    "SWIFT Code": "LNLNNOB2Z19",
    "Bank Name": "LIVSFORSIKRINSSELSKAPET NORDEA LIV NORGE AS",
    "Address": "FOLKE BERNADOTTES VEI 38",
    "City": "BERGEN",
    "Branch": "",
    "Postcode": "5147",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "LNLN",
    "bankCode": "NO",
    "branchCode": "OB2",
    "SWIFT Code": "LNLNNOB2",
    "Bank Name": "LIVSFORSIKRINSSELSKAPET NORDEA LIV NORGE AS",
    "Address": "FOLKE BERNADOTTES VEI 38",
    "City": "BERGEN",
    "Branch": "",
    "Postcode": "5147",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "LNLN",
    "bankCode": "NO",
    "branchCode": "D27",
    "SWIFT Code": "LNLNNOB2D27",
    "Bank Name": "LIVSFORSIKRINSSELSKAPET NORDEA LIV NORGE AS",
    "Address": "FOLKE BERNADOTTES VEI 38",
    "City": "BERGEN",
    "Branch": "",
    "Postcode": "5147",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "LNLN",
    "bankCode": "NO",
    "branchCode": "D26",
    "SWIFT Code": "LNLNNOB2D26",
    "Bank Name": "LIVSFORSIKRINSSELSKAPET NORDEA LIV NORGE AS",
    "Address": "FOLKE BERNADOTTES VEI 38",
    "City": "BERGEN",
    "Branch": "",
    "Postcode": "5147",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "LNLN",
    "bankCode": "NO",
    "branchCode": "D25",
    "SWIFT Code": "LNLNNOB2D25",
    "Bank Name": "LIVSFORSIKRINSSELSKAPET NORDEA LIV NORGE AS",
    "Address": "FOLKE BERNADOTTES VEI 38",
    "City": "BERGEN",
    "Branch": "",
    "Postcode": "5147",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "LNLN",
    "bankCode": "NO",
    "branchCode": "D24",
    "SWIFT Code": "LNLNNOB2D24",
    "Bank Name": "LIVSFORSIKRINSSELSKAPET NORDEA LIV NORGE AS",
    "Address": "FOLKE BERNADOTTES VEI 38",
    "City": "BERGEN",
    "Branch": "",
    "Postcode": "5147",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "LNLN",
    "bankCode": "NO",
    "branchCode": "D23",
    "SWIFT Code": "LNLNNOB2D23",
    "Bank Name": "LIVSFORSIKRINSSELSKAPET NORDEA LIV NORGE AS",
    "Address": "FOLKE BERNADOTTES VEI 38",
    "City": "BERGEN",
    "Branch": "",
    "Postcode": "5147",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "LNLN",
    "bankCode": "NO",
    "branchCode": "D22",
    "SWIFT Code": "LNLNNOB2D22",
    "Bank Name": "LIVSFORSIKRINSSELSKAPET NORDEA LIV NORGE AS",
    "Address": "FOLKE BERNADOTTES VEI 38",
    "City": "BERGEN",
    "Branch": "",
    "Postcode": "5147",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "LNLN",
    "bankCode": "NO",
    "branchCode": "D21",
    "SWIFT Code": "LNLNNOB2D21",
    "Bank Name": "LIVSFORSIKRINSSELSKAPET NORDEA LIV NORGE AS",
    "Address": "FOLKE BERNADOTTES VEI 38",
    "City": "BERGEN",
    "Branch": "",
    "Postcode": "5147",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "LNLN",
    "bankCode": "NO",
    "branchCode": "D20",
    "SWIFT Code": "LNLNNOB2D20",
    "Bank Name": "LIVSFORSIKRINSSELSKAPET NORDEA LIV NORGE AS",
    "Address": "FOLKE BERNADOTTES VEI 38",
    "City": "BERGEN",
    "Branch": "",
    "Postcode": "5147",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "LNLN",
    "bankCode": "NO",
    "branchCode": "D19",
    "SWIFT Code": "LNLNNOB2D19",
    "Bank Name": "LIVSFORSIKRINSSELSKAPET NORDEA LIV NORGE AS",
    "Address": "FOLKE BERNADOTTES VEI 38",
    "City": "BERGEN",
    "Branch": "",
    "Postcode": "5147",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "LNLN",
    "bankCode": "NO",
    "branchCode": "D18",
    "SWIFT Code": "LNLNNOB2D18",
    "Bank Name": "LIVSFORSIKRINSSELSKAPET NORDEA LIV NORGE AS",
    "Address": "FOLKE BERNADOTTES VEI 38",
    "City": "BERGEN",
    "Branch": "",
    "Postcode": "5147",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "LNLN",
    "bankCode": "NO",
    "branchCode": "D17",
    "SWIFT Code": "LNLNNOB2D17",
    "Bank Name": "LIVSFORSIKRINSSELSKAPET NORDEA LIV NORGE AS",
    "Address": "FOLKE BERNADOTTES VEI 38",
    "City": "BERGEN",
    "Branch": "",
    "Postcode": "5147",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "LNLN",
    "bankCode": "NO",
    "branchCode": "D16",
    "SWIFT Code": "LNLNNOB2D16",
    "Bank Name": "LIVSFORSIKRINSSELSKAPET NORDEA LIV NORGE AS",
    "Address": "FOLKE BERNADOTTES VEI 38",
    "City": "BERGEN",
    "Branch": "",
    "Postcode": "5147",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "LNLN",
    "bankCode": "NO",
    "branchCode": "D15",
    "SWIFT Code": "LNLNNOB2D15",
    "Bank Name": "LIVSFORSIKRINSSELSKAPET NORDEA LIV NORGE AS",
    "Address": "FOLKE BERNADOTTES VEI 38",
    "City": "BERGEN",
    "Branch": "",
    "Postcode": "5147",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "LNLN",
    "bankCode": "NO",
    "branchCode": "D14",
    "SWIFT Code": "LNLNNOB2D14",
    "Bank Name": "LIVSFORSIKRINSSELSKAPET NORDEA LIV NORGE AS",
    "Address": "FOLKE BERNADOTTES VEI 38",
    "City": "BERGEN",
    "Branch": "",
    "Postcode": "5147",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "LNLN",
    "bankCode": "NO",
    "branchCode": "D13",
    "SWIFT Code": "LNLNNOB2D13",
    "Bank Name": "LIVSFORSIKRINSSELSKAPET NORDEA LIV NORGE AS",
    "Address": "FOLKE BERNADOTTES VEI 38",
    "City": "BERGEN",
    "Branch": "",
    "Postcode": "5147",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "LNLN",
    "bankCode": "NO",
    "branchCode": "D12",
    "SWIFT Code": "LNLNNOB2D12",
    "Bank Name": "LIVSFORSIKRINSSELSKAPET NORDEA LIV NORGE AS",
    "Address": "FOLKE BERNADOTTES VEI 38",
    "City": "BERGEN",
    "Branch": "",
    "Postcode": "5147",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "LNLN",
    "bankCode": "NO",
    "branchCode": "D11",
    "SWIFT Code": "LNLNNOB2D11",
    "Bank Name": "LIVSFORSIKRINSSELSKAPET NORDEA LIV NORGE AS",
    "Address": "FOLKE BERNADOTTES VEI 38",
    "City": "BERGEN",
    "Branch": "",
    "Postcode": "5147",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "LNLN",
    "bankCode": "NO",
    "branchCode": "D10",
    "SWIFT Code": "LNLNNOB2D10",
    "Bank Name": "LIVSFORSIKRINSSELSKAPET NORDEA LIV NORGE AS",
    "Address": "FOLKE BERNADOTTES VEI 38",
    "City": "BERGEN",
    "Branch": "",
    "Postcode": "5147",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "LNLN",
    "bankCode": "NO",
    "branchCode": "D09",
    "SWIFT Code": "LNLNNOB2D09",
    "Bank Name": "LIVSFORSIKRINSSELSKAPET NORDEA LIV NORGE AS",
    "Address": "FOLKE BERNADOTTES VEI 38",
    "City": "BERGEN",
    "Branch": "",
    "Postcode": "5147",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "LNLN",
    "bankCode": "NO",
    "branchCode": "D08",
    "SWIFT Code": "LNLNNOB2D08",
    "Bank Name": "LIVSFORSIKRINSSELSKAPET NORDEA LIV NORGE AS",
    "Address": "FOLKE BERNADOTTES VEI 38",
    "City": "BERGEN",
    "Branch": "",
    "Postcode": "5147",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "LNLN",
    "bankCode": "NO",
    "branchCode": "D07",
    "SWIFT Code": "LNLNNOB2D07",
    "Bank Name": "LIVSFORSIKRINSSELSKAPET NORDEA LIV NORGE AS",
    "Address": "FOLKE BERNADOTTES VEI 38",
    "City": "BERGEN",
    "Branch": "",
    "Postcode": "5147",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "LNLN",
    "bankCode": "NO",
    "branchCode": "D06",
    "SWIFT Code": "LNLNNOB2D06",
    "Bank Name": "LIVSFORSIKRINSSELSKAPET NORDEA LIV NORGE AS",
    "Address": "FOLKE BERNADOTTES VEI 38",
    "City": "BERGEN",
    "Branch": "",
    "Postcode": "5147",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "LNLN",
    "bankCode": "NO",
    "branchCode": "D04",
    "SWIFT Code": "LNLNNOB2D04",
    "Bank Name": "LIVSFORSIKRINSSELSKAPET NORDEA LIV NORGE AS",
    "Address": "FOLKE BERNADOTTES VEI 38",
    "City": "BERGEN",
    "Branch": "",
    "Postcode": "5147",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "LNLN",
    "bankCode": "NO",
    "branchCode": "D03",
    "SWIFT Code": "LNLNNOB2D03",
    "Bank Name": "LIVSFORSIKRINSSELSKAPET NORDEA LIV NORGE AS",
    "Address": "FOLKE BERNADOTTES VEI 38",
    "City": "BERGEN",
    "Branch": "",
    "Postcode": "5147",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "LNLN",
    "bankCode": "NO",
    "branchCode": "D02",
    "SWIFT Code": "LNLNNOB2D02",
    "Bank Name": "LIVSFORSIKRINSSELSKAPET NORDEA LIV NORGE AS",
    "Address": "FOLKE BERNADOTTES VEI 38",
    "City": "BERGEN",
    "Branch": "",
    "Postcode": "5147",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "LNLN",
    "bankCode": "NO",
    "branchCode": "D01",
    "SWIFT Code": "LNLNNOB2D01",
    "Bank Name": "LIVSFORSIKRINSSELSKAPET NORDEA LIV NORGE AS",
    "Address": "FOLKE BERNADOTTES VEI 38",
    "City": "BERGEN",
    "Branch": "",
    "Postcode": "5147",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "LNLN",
    "bankCode": "NO",
    "branchCode": "014",
    "SWIFT Code": "LNLNNOB2014",
    "Bank Name": "LIVSFORSIKRINSSELSKAPET NORDEA LIV NORGE AS",
    "Address": "FOLKE BERNADOTTES VEI 38",
    "City": "BERGEN",
    "Branch": "",
    "Postcode": "5147",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "CPBI",
    "bankCode": "NO",
    "branchCode": "OKK",
    "SWIFT Code": "CPBINOKK",
    "Bank Name": "LOOMIS FX, GOLD AND SERVICES",
    "Address": "PERSVEIEN 26",
    "City": "OSLO",
    "Branch": "",
    "Postcode": "0581",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "BBSN",
    "bankCode": "NO",
    "branchCode": "OKK",
    "SWIFT Code": "BBSNNOKK",
    "Bank Name": "MASTERCARD PAYMENT SERVICES NORWAY AS",
    "Address": "HAARVARD MARTINSENS VEI 54",
    "City": "OSLO",
    "Branch": "",
    "Postcode": "0978",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "BBSN",
    "bankCode": "NO",
    "branchCode": "OKA",
    "SWIFT Code": "BBSNNOKA",
    "Bank Name": "MASTERCARD PAYMENT SERVICES NORWAY AS",
    "Address": "HAARVARD MARTINSENS VEI 54",
    "City": "OSLO",
    "Branch": "",
    "Postcode": "0978",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "NDEA",
    "bankCode": "NO",
    "branchCode": "NCL",
    "SWIFT Code": "NDEANOKKNCL",
    "Bank Name": "NORDEA BANK ABP, FILIAL I NORGE",
    "Address": "ESSENDROPS GATE 7",
    "City": "OSLO",
    "Branch": "",
    "Postcode": "0368",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "NDEA",
    "bankCode": "NO",
    "branchCode": "OKK",
    "SWIFT Code": "NDEANOKK",
    "Bank Name": "NORDEA BANK ABP, FILIAL I NORGE",
    "Address": "ESSENDROPSGATE 7, SENTRUM",
    "City": "OSLO",
    "Branch": "",
    "Postcode": "0368",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "NDEA",
    "bankCode": "NO",
    "branchCode": "VPU",
    "SWIFT Code": "NDEANOKKVPU",
    "Bank Name": "NORDEA BANK ABP, FILIAL I NORGE",
    "Address": "ESSENDROPS GT 7",
    "City": "OSLO",
    "Branch": "CUSTODY INTERNATIONAL",
    "Postcode": "0368",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "NDEA",
    "bankCode": "NO",
    "branchCode": "NKR",
    "SWIFT Code": "NDEANOKKNKR",
    "Bank Name": "NORDEA BANK ABP, FILIAL I NORGE",
    "Address": "ESSENDRUPS GATE 7",
    "City": "OSLO",
    "Branch": "REALKREDITAKTIESELSKAB",
    "Postcode": "0368",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "NDEA",
    "bankCode": "NO",
    "branchCode": "NEK",
    "SWIFT Code": "NDEANOKKNEK",
    "Bank Name": "NORDEA BANK ABP, FILIAL I NORGE",
    "Address": "ESSENDROPSGATE 7, SENTRUM",
    "City": "OSLO",
    "Branch": "THE NORDEA EIENDOMSKREDITT",
    "Postcode": "0368",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "NPAS",
    "bankCode": "NO",
    "branchCode": "OK2",
    "SWIFT Code": "NPASNOK2",
    "Bank Name": "NORDEA FUNDS, NORWEGIAN BRANCH",
    "Address": "ESSENDROPS GATE 7",
    "City": "OSLO",
    "Branch": "",
    "Postcode": "0368",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "NLSS",
    "bankCode": "NO",
    "branchCode": "OK2",
    "SWIFT Code": "NLSSNOK2",
    "Bank Name": "NORDEA FUNDS, NORWEGIAN BRANCH",
    "Address": "ESSENDROPS GATE 7",
    "City": "OSLO",
    "Branch": "",
    "Postcode": "0368",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "NLPA",
    "bankCode": "NO",
    "branchCode": "OK2",
    "SWIFT Code": "NLPANOK2",
    "Bank Name": "NORDEA FUNDS, NORWEGIAN BRANCH",
    "Address": "ESSENDROPS GATE 7",
    "City": "OSLO",
    "Branch": "",
    "Postcode": "0368",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "NLIA",
    "bankCode": "NO",
    "branchCode": "OK2",
    "SWIFT Code": "NLIANOK2",
    "Bank Name": "NORDEA FUNDS, NORWEGIAN BRANCH",
    "Address": "ESSENDROPS GATE 7",
    "City": "OSLO",
    "Branch": "",
    "Postcode": "0368",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "NLAS",
    "bankCode": "NO",
    "branchCode": "OK2",
    "SWIFT Code": "NLASNOK2",
    "Bank Name": "NORDEA FUNDS, NORWEGIAN BRANCH",
    "Address": "ESSENDROPS GATE 7",
    "City": "OSLO",
    "Branch": "",
    "Postcode": "0368",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "NLAE",
    "bankCode": "NO",
    "branchCode": "OK2",
    "SWIFT Code": "NLAENOK2",
    "Bank Name": "NORDEA FUNDS, NORWEGIAN BRANCH",
    "Address": "ESSENDROPS GATE 7",
    "City": "OSLO",
    "Branch": "",
    "Postcode": "0368",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "NOTS",
    "bankCode": "NO",
    "branchCode": "OK2",
    "SWIFT Code": "NOTSNOK2",
    "Bank Name": "NORDEA OBLIGASJON II - ASSET SIDE",
    "Address": "ESSENDROPS GATE 7",
    "City": "OSLO",
    "Branch": "",
    "Postcode": "0368",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "NBIE",
    "bankCode": "NO",
    "branchCode": "OK2",
    "SWIFT Code": "NBIENOK2",
    "Bank Name": "NORDEA OBLIGASJON III - ASSET SIDE",
    "Address": "ESSENDROPS GATE 7",
    "City": "OSLO",
    "Branch": "",
    "Postcode": "0368",
    "Country": "Norway",
    "Connection": "Active"
  },
  {
    "countryCode": "NRCA",
    "bankCode": "NO",
    "branchCode": "OK2",
    "SWIFT Code": "NRCANOK2",
    "Bank Name": "NORDIC CORPORATE BANK ASA",
    "Address": "INKOGNITO GATE 8",
    "City": "OSLO",
    "Branch": "",
    "Postcode": "0258",
    "Country": "Norway",
    "Connection": "Active"
  }
]
module.exports = norway
