const oman = [
  {
    "countryCode": "AUBO",
    "bankCode": "OM",
    "branchCode": "ALH",
    "SWIFT Code": "AUBOOMRUALH",
    "Bank Name": "AHLI BANK S.A.O.G",
    "Address": "AL WATAYA",
    "City": "MUSCAT",
    "Branch": "AHLI ISLAMIC",
    "Postcode": "114",
    "Country": "Oman",
    "Connection": "Active"
  },
  {
    "countryCode": "AUBO",
    "bankCode": "OM",
    "branchCode": "MRU",
    "SWIFT Code": "AUBOOMRU",
    "Bank Name": "AHLI BANK S.A.O.G",
    "Address": "116 MINA AL FAHAL",
    "City": "RUWI",
    "Branch": "",
    "Postcode": "126",
    "Country": "Oman",
    "Connection": "Active"
  },
  {
    "countryCode": "IZZB",
    "bankCode": "OM",
    "branchCode": "MRU",
    "SWIFT Code": "IZZBOMRU",
    "Bank Name": "ALIZZ ISLAMIC BANK",
    "Address": "FLOOR 9, GOLDEN TOWER, 903 ROAD 2732",
    "City": "MUSCAT",
    "Branch": "",
    "Postcode": "112",
    "Country": "Oman",
    "Connection": "Active"
  },
  {
    "countryCode": "BDOF",
    "bankCode": "OM",
    "branchCode": "MRU",
    "SWIFT Code": "BDOFOMRU",
    "Bank Name": "BANK DHOFAR (S.A.O.G.)",
    "Address": "CBD AREA",
    "City": "RUWI",
    "Branch": "",
    "Postcode": "112",
    "Country": "Oman",
    "Connection": "Active"
  },
  {
    "countryCode": "BDOF",
    "bankCode": "OM",
    "branchCode": "TFD",
    "SWIFT Code": "BDOFOMRUTFD",
    "Bank Name": "BANK DHOFAR (S.A.O.G.)",
    "Address": "",
    "City": "RUWI",
    "Branch": "",
    "Postcode": "112",
    "Country": "Oman",
    "Connection": "Active"
  },
  {
    "countryCode": "BDOF",
    "bankCode": "OM",
    "branchCode": "MIB",
    "SWIFT Code": "BDOFOMRUMIB",
    "Bank Name": "BANK DHOFAR (S.A.O.G.)",
    "Address": "",
    "City": "RUWI",
    "Branch": "MAISARAH ISLAMIC BANKING SERVICES",
    "Postcode": "112",
    "Country": "Oman",
    "Connection": "Active"
  },
  {
    "countryCode": "BMUS",
    "bankCode": "OM",
    "branchCode": "MRX",
    "SWIFT Code": "BMUSOMRX",
    "Bank Name": "BANK MUSCAT SAOG",
    "Address": "BUILDING NO. 120/4 BLOCK NO. 311, 62 AIRPORT HEIGHTS - SEEB",
    "City": "MUSCAT",
    "Branch": "",
    "Postcode": "112",
    "Country": "Oman",
    "Connection": "Active"
  },
  {
    "countryCode": "BMUS",
    "bankCode": "OM",
    "branchCode": "ISL",
    "SWIFT Code": "BMUSOMRXISL",
    "Bank Name": "BANK MUSCAT SAOG",
    "Address": "",
    "City": "MUSCAT",
    "Branch": "ISLAMIC BANKING",
    "Postcode": "112",
    "Country": "Oman",
    "Connection": "Active"
  },
  {
    "countryCode": "BMUS",
    "bankCode": "OM",
    "branchCode": "TBG",
    "SWIFT Code": "BMUSOMRXTBG",
    "Bank Name": "BANK MUSCAT SAOG",
    "Address": "BUILDING NO. 120/4 BLOCK NO. 311, 62 AIRPORT HEIGHTS - SEEB",
    "City": "MUSCAT",
    "Branch": "TRANSACTION BANKING GROUP",
    "Postcode": "112",
    "Country": "Oman",
    "Connection": "Active"
  },
  {
    "countryCode": "BNZW",
    "bankCode": "OM",
    "branchCode": "MRX",
    "SWIFT Code": "BNZWOMRX",
    "Bank Name": "BANK NIZWA",
    "Address": "BEACH ONE BUILDING, AL KHUWAIR, SHATTI A QURUM",
    "City": "MUSCAT",
    "Branch": "",
    "Postcode": "133",
    "Country": "Oman",
    "Connection": "Active"
  },
  {
    "countryCode": "BARB",
    "bankCode": "OM",
    "branchCode": "MUT",
    "SWIFT Code": "BARBOMMXMUT",
    "Bank Name": "BANK OF BARODA, GREATER MUTTRAH BRANCH",
    "Address": "CORNICHE MUTHAR",
    "City": "MUTTRAH",
    "Branch": "MUTRAH BRANCH",
    "Postcode": "114",
    "Country": "Oman",
    "Connection": "Active"
  },
  {
    "countryCode": "BARB",
    "bankCode": "OM",
    "branchCode": "SAL",
    "SWIFT Code": "BARBOMMXSAL",
    "Bank Name": "BANK OF BARODA, GREATER MUTTRAH BRANCH",
    "Address": "AL SALAM ROAD, SALALAH",
    "City": "MUTTRAH",
    "Branch": "SALALAH BRANCH",
    "Postcode": "211",
    "Country": "Oman",
    "Connection": "Active"
  },
  {
    "countryCode": "BARB",
    "bankCode": "OM",
    "branchCode": "MMX",
    "SWIFT Code": "BARBOMMX",
    "Bank Name": "BANK OF BARODA, GREATER MUTTRAH BRANCH",
    "Address": "BEHIND INDIAN EMBASSY, MBD AREA",
    "City": "RUWI",
    "Branch": "GREATER MUTTRRAH BRANCH",
    "Postcode": "112",
    "Country": "Oman",
    "Connection": "Active"
  },
  {
    "countryCode": "BARB",
    "bankCode": "OM",
    "branchCode": "SOH",
    "SWIFT Code": "BARBOMMXSOH",
    "Bank Name": "BANK OF BARODA, GREATER MUTTRAH BRANCH",
    "Address": "PLOT NO 596 BLOCK NO, 1 FALAJ ALQABAIL SOH",
    "City": "SOHAR",
    "Branch": "SOHAR BRANCH",
    "Postcode": "322",
    "Country": "Oman",
    "Connection": "Active"
  },
  {
    "countryCode": "BABE",
    "bankCode": "OM",
    "branchCode": "MRX",
    "SWIFT Code": "BABEOMRX",
    "Bank Name": "BANK OF BEIRUT S.A.L.- OMAN BRANCH",
    "Address": "AL-JAWHARA BUILDING, BLOC 3, 576 WAY NO 3009, SHATTI AL QURUM",
    "City": "MUSCAT",
    "Branch": "",
    "Postcode": "114",
    "Country": "Oman",
    "Connection": "Active"
  },
  {
    "countryCode": "CBOM",
    "bankCode": "OM",
    "branchCode": "MRU",
    "SWIFT Code": "CBOMOMRU",
    "Bank Name": "CENTRAL BANK OF OMAN",
    "Address": "MBD AREA, BAITAL FALAJ",
    "City": "MUTTRAH",
    "Branch": "",
    "Postcode": "118",
    "Country": "Oman",
    "Connection": "Active"
  },
  {
    "countryCode": "NBAD",
    "bankCode": "OM",
    "branchCode": "MRX",
    "SWIFT Code": "NBADOMRX",
    "Bank Name": "FIRST ABU DHABI BANK (FORMERLY NATIONAL BANK OF ABU DHABI) OMAN MAIN BR",
    "Address": "COMMERCIAL BUSINESS DISTRICT",
    "City": "MUTTRAH",
    "Branch": "",
    "Postcode": "100",
    "Country": "Oman",
    "Connection": "Active"
  },
  {
    "countryCode": "NBAD",
    "bankCode": "OM",
    "branchCode": "CMS",
    "SWIFT Code": "NBADOMRXCMS",
    "Bank Name": "FIRST ABU DHABI BANK (FORMERLY NATIONAL BANK OF ABU DHABI) OMAN MAIN BR",
    "Address": "",
    "City": "MUTTRAH",
    "Branch": "NATIONAL BANK OF ABU DHABI",
    "Postcode": "125",
    "Country": "Oman",
    "Connection": "Active"
  },
  {
    "countryCode": "NBAD",
    "bankCode": "OM",
    "branchCode": "TFO",
    "SWIFT Code": "NBADOMRXTFO",
    "Bank Name": "FIRST ABU DHABI BANK (FORMERLY NATIONAL BANK OF ABU DHABI) OMAN MAIN BR",
    "Address": "",
    "City": "MUTTRAH",
    "Branch": "TRADE FINANCE DEPARTMENT",
    "Postcode": "125",
    "Country": "Oman",
    "Connection": "Active"
  },
  {
    "countryCode": "GULF",
    "bankCode": "OM",
    "branchCode": "MRX",
    "SWIFT Code": "GULFOMRX",
    "Bank Name": "GULF INTERNATIONAL BANK (OMAN BRANCH)",
    "Address": "",
    "City": "",
    "Branch": "",
    "Postcode": "",
    "Country": "Oman",
    "Connection": "Active"
  },
  {
    "countryCode": "HABB",
    "bankCode": "OM",
    "branchCode": "MRX",
    "SWIFT Code": "HABBOMRX",
    "Bank Name": "HABIB BANK OMAN",
    "Address": "BUILDING NO 71, BLOCK NO.233, 281, AL KHUWAIR AREA",
    "City": "MUSCAT",
    "Branch": "",
    "Postcode": "112",
    "Country": "Oman",
    "Connection": "Active"
  },
  {
    "countryCode": "HBME",
    "bankCode": "OM",
    "branchCode": "MRX",
    "SWIFT Code": "HBMEOMRX",
    "Bank Name": "HSBC BANK MIDDLE EAST LIMITED(OMAN BRANCH)",
    "Address": "SALAM GALLERY, BOUSHER AREA, AL KHUWAIR",
    "City": "MUSCAT",
    "Branch": "",
    "Postcode": "",
    "Country": "Oman",
    "Connection": "Active"
  },
  {
    "countryCode": "MINI",
    "bankCode": "OM",
    "branchCode": "MRU",
    "SWIFT Code": "MINIOMRU",
    "Bank Name": "MINISTRY OF FINANCE",
    "Address": "AL-SAIDIA STREET",
    "City": "MUSCAT",
    "Branch": "",
    "Postcode": "113",
    "Country": "Oman",
    "Connection": "Active"
  },
  {
    "countryCode": "NBOM",
    "bankCode": "OM",
    "branchCode": "MRX",
    "SWIFT Code": "NBOMOMRX",
    "Bank Name": "NATIONAL BANK OF OMAN",
    "Address": "65 AL MARKAZI STREET, MUTTRAH BUSINESS DISTRICT AREA",
    "City": "MUSCAT",
    "Branch": "",
    "Postcode": "112",
    "Country": "Oman",
    "Connection": "Active"
  },
  {
    "countryCode": "NBOM",
    "bankCode": "OM",
    "branchCode": "IBS",
    "SWIFT Code": "NBOMOMRXIBS",
    "Bank Name": "NATIONAL BANK OF OMAN",
    "Address": "AZAIBA",
    "City": "MUSCAT",
    "Branch": "MUZN ISLAMIC BANKING",
    "Postcode": "130",
    "Country": "Oman",
    "Connection": "Active"
  },
  {
    "countryCode": "NBOM",
    "bankCode": "OM",
    "branchCode": "ITF",
    "SWIFT Code": "NBOMOMRXITF",
    "Bank Name": "NATIONAL BANK OF OMAN",
    "Address": "NBO HEAD OFFICE, AZAIBA",
    "City": "MUSCAT",
    "Branch": "MUZN ISLAMIC TRADE FINANCE",
    "Postcode": "112",
    "Country": "Oman",
    "Connection": "Active"
  },
  {
    "countryCode": "NBOM",
    "bankCode": "OM",
    "branchCode": "TSS",
    "SWIFT Code": "NBOMOMRXTSS",
    "Bank Name": "NATIONAL BANK OF OMAN",
    "Address": "NBO HEAD OFFICE, AZAIBA",
    "City": "MUSCAT",
    "Branch": "TRADE SERVICES",
    "Postcode": "112",
    "Country": "Oman",
    "Connection": "Active"
  },
  {
    "countryCode": "OPCF",
    "bankCode": "OM",
    "branchCode": "MRX",
    "SWIFT Code": "OPCFOMRX",
    "Bank Name": "OCTAL PETROCHEMICALS FZC",
    "Address": "FLOOR 4, AL RAWAQ BUILDING, 3786 AL QURUM",
    "City": "MUSCAT",
    "Branch": "",
    "Postcode": "112",
    "Country": "Oman",
    "Connection": "Active"
  },
  {
    "countryCode": "OMAB",
    "bankCode": "OM",
    "branchCode": "MRU",
    "SWIFT Code": "OMABOMRU",
    "Bank Name": "OMAN ARAB BANK SAOG",
    "Address": "OAB BUILDING, MUTTRAH BUSINESS DISTRICT",
    "City": "RUWI",
    "Branch": "",
    "Postcode": "112",
    "Country": "Oman",
    "Connection": "Active"
  },
  {
    "countryCode": "OMAB",
    "bankCode": "OM",
    "branchCode": "YSR",
    "SWIFT Code": "OMABOMRUYSR",
    "Bank Name": "OMAN ARAB BANK SAOG",
    "Address": "",
    "City": "RUWI",
    "Branch": "AL-YUSR ISLAMIC BANKING",
    "Postcode": "112",
    "Country": "Oman",
    "Connection": "Active"
  },
  {
    "countryCode": "SGRF",
    "bankCode": "OM",
    "branchCode": "MRA",
    "SWIFT Code": "SGRFOMRA",
    "Bank Name": "OMAN INVESTMENT AUTHORITY",
    "Address": "MINISTRY OF FINANCE BUILDING, WAY NO. 9105, WALJAT STREET",
    "City": "MUSCAT",
    "Branch": "",
    "Postcode": "113",
    "Country": "Oman",
    "Connection": "Active"
  },
  {
    "countryCode": "SGRF",
    "bankCode": "OM",
    "branchCode": "MRB",
    "SWIFT Code": "SGRFOMRB",
    "Bank Name": "OMAN INVESTMENT AUTHORITY",
    "Address": "FLOOR 5, BEACH ONE, 37 WAY 2601, SHATTI AL-QURM",
    "City": "MUSCAT",
    "Branch": "",
    "Postcode": "100",
    "Country": "Oman",
    "Connection": "Active"
  },
  {
    "countryCode": "SGRF",
    "bankCode": "OM",
    "branchCode": "BRA",
    "SWIFT Code": "SGRFOMRABRA",
    "Bank Name": "OMAN INVESTMENT AUTHORITY",
    "Address": "MINISTRY OF FINANCE BUILDING, WAY NO. 9105, WALJAT STREET",
    "City": "MUSCAT",
    "Branch": "",
    "Postcode": "113",
    "Country": "Oman",
    "Connection": "Active"
  },
  {
    "countryCode": "OIBB",
    "bankCode": "OM",
    "branchCode": "MRX",
    "SWIFT Code": "OIBBOMRX",
    "Bank Name": "OMAN INVESTMENT BANK SAOC",
    "Address": "SOUTH AL KHUWAIR AL KHUWAIR BOUSHER",
    "City": "MUSCAT",
    "Branch": "",
    "Postcode": "133",
    "Country": "Oman",
    "Connection": "Active"
  },
  {
    "countryCode": "QNBA",
    "bankCode": "OM",
    "branchCode": "MRX",
    "SWIFT Code": "QNBAOMRX",
    "Bank Name": "QATAR NATIONAL BANK",
    "Address": "QATAR NATIONAL BANK BUILDING, NEXT OF CENTRAL BANK OMAN, MBD AREA, NORTH",
    "City": "MUSCAT",
    "Branch": "",
    "Postcode": "112",
    "Country": "Oman",
    "Connection": "Active"
  },
  {
    "countryCode": "BBME",
    "bankCode": "OM",
    "branchCode": "MRX",
    "SWIFT Code": "BBMEOMRX",
    "Bank Name": "SOHAR INTERNATIONAL BANK S.A.O.G",
    "Address": "BUILDING NO.123, OFF SULTAN QABOOS ST, AL KHUWAIR",
    "City": "MUSCAT",
    "Branch": "",
    "Postcode": "111",
    "Country": "Oman",
    "Connection": "Active"
  },
  {
    "countryCode": "BSHR",
    "bankCode": "OM",
    "branchCode": "MRU",
    "SWIFT Code": "BSHROMRU",
    "Bank Name": "SOHAR INTERNATIONAL BANK S.A.O.G",
    "Address": "FLOOR 4, HAI AL MINA, 166 WATER FRONT, AL SHATTI BEACH",
    "City": "MUSCAT",
    "Branch": "",
    "Postcode": "114",
    "Country": "Oman",
    "Connection": "Active"
  },
  {
    "countryCode": "BSHR",
    "bankCode": "OM",
    "branchCode": "ISL",
    "SWIFT Code": "BSHROMRUISL",
    "Bank Name": "SOHAR INTERNATIONAL BANK S.A.O.G",
    "Address": "CBD AREA",
    "City": "RUWI",
    "Branch": "SOHAR ISLAMIC",
    "Postcode": "114",
    "Country": "Oman",
    "Connection": "Active"
  },
  {
    "countryCode": "SCBL",
    "bankCode": "OM",
    "branchCode": "MRX",
    "SWIFT Code": "SCBLOMRX",
    "Bank Name": "STANDARD CHARTERED BANK",
    "Address": "FLOOR 6, SUPER PLAZA, BUILDING 340, 4805 SULTAN QABOOS STREET, AL AZAIBA",
    "City": "MUSCAT",
    "Branch": "",
    "Postcode": "112",
    "Country": "Oman",
    "Connection": "Active"
  },
  {
    "countryCode": "SBIN",
    "bankCode": "OM",
    "branchCode": "MRX",
    "SWIFT Code": "SBINOMRX",
    "Bank Name": "STATE BANK OF INDIA, MUSCAT, OMAN",
    "Address": "SALAH HOUSE, 619/346 BAIT AL FALAJ WAY",
    "City": "MUSCAT",
    "Branch": "",
    "Postcode": "112",
    "Country": "Oman",
    "Connection": "Active"
  },
  {
    "countryCode": "OUAE",
    "bankCode": "OM",
    "branchCode": "MRU",
    "SWIFT Code": "OUAEOMRU",
    "Bank Name": "UNIMONI EXCHANGE LLC",
    "Address": "O C CENTRE, RUWI STREET",
    "City": "RUWI",
    "Branch": "",
    "Postcode": "131",
    "Country": "Oman",
    "Connection": "Active"
  }
]
module.exports = oman
