const palestine = [
  {
    "bankCode": "ALXC",
    "countryCode": "PS",
    "branchCode": "S2J",
    "SWIFT Code": "ALXCPS2J",
    "Bank Name": "ALKHALEJ EXCHANGE COMPANY",
    "Address": "ABU BAKER STREET, MUNICIPAL BUILDING, FLOOR 0",
    "City": "JENIN",
    "Branch": "",
    "Postcode": "",
    "Country": "Palestine",
    "Connection": "Active"
  },
  {
    "bankCode": "ARAB",
    "countryCode": "PS",
    "branchCode": "030",
    "SWIFT Code": "ARABPS22030",
    "Bank Name": "ARAB BANK PLC",
    "Address": "",
    "City": "AL-BIREH",
    "Branch": "AL-BIREH BRANCH",
    "Postcode": "",
    "Country": "Palestine",
    "Connection": "Active"
  },
  {
    "bankCode": "ARAB",
    "countryCode": "PS",
    "branchCode": "110",
    "SWIFT Code": "ARABPS22110",
    "Bank Name": "ARAB BANK PLC",
    "Address": "",
    "City": "AL-RAM",
    "Branch": "AL-RAM BRANCH",
    "Postcode": "",
    "Country": "Palestine",
    "Connection": "Active"
  },
  {
    "bankCode": "ARAB",
    "countryCode": "PS",
    "branchCode": "100",
    "SWIFT Code": "ARABPS22100",
    "Bank Name": "ARAB BANK PLC",
    "Address": "",
    "City": "BETHANY",
    "Branch": "BETHANY BRANCH",
    "Postcode": "",
    "Country": "Palestine",
    "Connection": "Active"
  },
  {
    "bankCode": "ARAB",
    "countryCode": "PS",
    "branchCode": "050",
    "SWIFT Code": "ARABPS22050",
    "Bank Name": "ARAB BANK PLC",
    "Address": "MANGER STREET",
    "City": "BETHLEHEM",
    "Branch": "BETHLEHEM BRANCH",
    "Postcode": "",
    "Country": "Palestine",
    "Connection": "Active"
  },
  {
    "bankCode": "ARAB",
    "countryCode": "PS",
    "branchCode": "500",
    "SWIFT Code": "ARABPS22500",
    "Bank Name": "ARAB BANK PLC",
    "Address": "OMAR AL-MUKHTAR STREET",
    "City": "GAZA",
    "Branch": "GAZA BRANCH",
    "Postcode": "",
    "Country": "Palestine",
    "Connection": "Active"
  },
  {
    "bankCode": "ARAB",
    "countryCode": "PS",
    "branchCode": "600",
    "SWIFT Code": "ARABPS22600",
    "Bank Name": "ARAB BANK PLC",
    "Address": "",
    "City": "GAZA",
    "Branch": "RIMAL BRANCH",
    "Postcode": "",
    "Country": "Palestine",
    "Connection": "Active"
  },
  {
    "bankCode": "ARAB",
    "countryCode": "PS",
    "branchCode": "040",
    "SWIFT Code": "ARABPS22040",
    "Bank Name": "ARAB BANK PLC",
    "Address": "",
    "City": "HEBRON",
    "Branch": "HEBRON BRANCH",
    "Postcode": "",
    "Country": "Palestine",
    "Connection": "Active"
  },
  {
    "bankCode": "ARAB",
    "countryCode": "PS",
    "branchCode": "060",
    "SWIFT Code": "ARABPS22060",
    "Bank Name": "ARAB BANK PLC",
    "Address": "",
    "City": "JENIN",
    "Branch": "JENIN BRANCH",
    "Postcode": "",
    "Country": "Palestine",
    "Connection": "Active"
  },
  {
    "bankCode": "ARAB",
    "countryCode": "PS",
    "branchCode": "550",
    "SWIFT Code": "ARABPS22550",
    "Bank Name": "ARAB BANK PLC",
    "Address": "",
    "City": "JERICHO",
    "Branch": "JERICH BRANCH",
    "Postcode": "",
    "Country": "Palestine",
    "Connection": "Active"
  },
  {
    "bankCode": "ARAB",
    "countryCode": "PS",
    "branchCode": "650",
    "SWIFT Code": "ARABPS22650",
    "Bank Name": "ARAB BANK PLC",
    "Address": "",
    "City": "KHAN YOUNIS",
    "Branch": "KHAN YOUNIS BRANCH",
    "Postcode": "",
    "Country": "Palestine",
    "Connection": "Active"
  },
  {
    "bankCode": "ARAB",
    "countryCode": "PS",
    "branchCode": "020",
    "SWIFT Code": "ARABPS22020",
    "Bank Name": "ARAB BANK PLC",
    "Address": "AL-HUSSEIN CIRCLE, A.B. BUILDING",
    "City": "NABLUS",
    "Branch": "NABLUS BRANCH",
    "Postcode": "",
    "Country": "Palestine",
    "Connection": "Active"
  },
  {
    "bankCode": "ARAB",
    "countryCode": "PS",
    "branchCode": "080",
    "SWIFT Code": "ARABPS22080",
    "Bank Name": "ARAB BANK PLC",
    "Address": "",
    "City": "QALQILYA",
    "Branch": "QALQILIAH BRANCH",
    "Postcode": "",
    "Country": "Palestine",
    "Connection": "Active"
  },
  {
    "bankCode": "ARAB",
    "countryCode": "PS",
    "branchCode": "S22",
    "SWIFT Code": "ARABPS22",
    "Bank Name": "ARAB BANK PLC",
    "Address": "AL MASYOON",
    "City": "RAMALLAH",
    "Branch": "REGIONAL MANAGEMENT",
    "Postcode": "",
    "Country": "Palestine",
    "Connection": "Active"
  },
  {
    "bankCode": "ARAB",
    "countryCode": "PS",
    "branchCode": "DLR",
    "SWIFT Code": "ARABPS22DLR",
    "Bank Name": "ARAB BANK PLC",
    "Address": "RAFAT STREET - RAMALLAH",
    "City": "RAMALLAH",
    "Branch": "REGIONAL MANAGEMENT",
    "Postcode": "",
    "Country": "Palestine",
    "Connection": "Active"
  },
  {
    "bankCode": "ARAB",
    "countryCode": "PS",
    "branchCode": "090",
    "SWIFT Code": "ARABPS22090",
    "Bank Name": "ARAB BANK PLC",
    "Address": "AL MASYOON",
    "City": "RAMALLAH",
    "Branch": "REGIONAL MANAGEMENT",
    "Postcode": "",
    "Country": "Palestine",
    "Connection": "Active"
  },
  {
    "bankCode": "ARAB",
    "countryCode": "PS",
    "branchCode": "COU",
    "SWIFT Code": "ARABPS22COU",
    "Bank Name": "ARAB BANK PLC",
    "Address": "AL MASYOON",
    "City": "RAMALLAH",
    "Branch": "REGIONAL MANAGEMENT",
    "Postcode": "",
    "Country": "Palestine",
    "Connection": "Active"
  },
  {
    "bankCode": "ARAB",
    "countryCode": "PS",
    "branchCode": "COT",
    "SWIFT Code": "ARABPS22COT",
    "Bank Name": "ARAB BANK PLC",
    "Address": "AL MASYOON",
    "City": "RAMALLAH",
    "Branch": "REGIONAL MANAGEMENT",
    "Postcode": "",
    "Country": "Palestine",
    "Connection": "Active"
  },
  {
    "bankCode": "ARAB",
    "countryCode": "PS",
    "branchCode": "070",
    "SWIFT Code": "ARABPS22070",
    "Bank Name": "ARAB BANK PLC",
    "Address": "",
    "City": "TULKARM",
    "Branch": "TULKARM BRANCH",
    "Postcode": "",
    "Country": "Palestine",
    "Connection": "Active"
  },
  {
    "bankCode": "AISB",
    "countryCode": "PS",
    "branchCode": "S22",
    "SWIFT Code": "AISBPS22",
    "Bank Name": "ARAB ISLAMIC BANK",
    "Address": "NABLUS STREET",
    "City": "RAMALLAH",
    "Branch": "",
    "Postcode": "",
    "Country": "Palestine",
    "Connection": "Active"
  },
  {
    "bankCode": "BJOR",
    "countryCode": "PS",
    "branchCode": "S22",
    "SWIFT Code": "BJORPS22",
    "Bank Name": "BANK OF JORDAN PLC",
    "Address": "AL MAAREF STREET, BAHHOUR BUILDING",
    "City": "RAMALLAH",
    "Branch": "REGIONAL OFFICE",
    "Postcode": "",
    "Country": "Palestine",
    "Connection": "Active"
  },
  {
    "bankCode": "PALS",
    "countryCode": "PS",
    "branchCode": "S22",
    "SWIFT Code": "PALSPS22",
    "Bank Name": "BANK OF PALESTINE PLC",
    "Address": "COURT STREET EIN MESBAH",
    "City": "RAMALLAH",
    "Branch": "",
    "Postcode": "",
    "Country": "Palestine",
    "Connection": "Active"
  },
  {
    "bankCode": "CAAB",
    "countryCode": "PS",
    "branchCode": "S22",
    "SWIFT Code": "CAABPS22",
    "Bank Name": "CAIRO AMMAN BANK",
    "Address": "KHALIL AL WAZEER STREET",
    "City": "RAMALLAH",
    "Branch": "",
    "Postcode": "",
    "Country": "Palestine",
    "Connection": "Active"
  },
  {
    "bankCode": "ARLB",
    "countryCode": "PS",
    "branchCode": "S22",
    "SWIFT Code": "ARLBPS22",
    "Bank Name": "EGYPTIAN ARAB LAND BANK",
    "Address": "RAMALLAH STREET, AL FUAD BUILDING, AL BIREH",
    "City": "RAMALLAH",
    "Branch": "",
    "Postcode": "",
    "Country": "Palestine",
    "Connection": "Active"
  },
  {
    "bankCode": "JONB",
    "countryCode": "PS",
    "branchCode": "S22",
    "SWIFT Code": "JONBPS22",
    "Bank Name": "JORDAN AHLI BANK-PLC FOREIGN PUBLIC COMPANY",
    "Address": "AL MASYOON NAJI AL ALI ST",
    "City": "RAMALLAH",
    "Branch": "",
    "Postcode": "",
    "Country": "Palestine",
    "Connection": "Active"
  },
  {
    "bankCode": "PINV",
    "countryCode": "PS",
    "branchCode": "S22",
    "SWIFT Code": "PINVPS22",
    "Bank Name": "PALESTINE INVESTMENT BANK",
    "Address": "AL BERIEH AL ERSAL ST",
    "City": "RAMALLAH",
    "Branch": "",
    "Postcode": "",
    "Country": "Palestine",
    "Connection": "Active"
  },
  {
    "bankCode": "PIBC",
    "countryCode": "PS",
    "branchCode": "S22",
    "SWIFT Code": "PIBCPS22",
    "Bank Name": "PALESTINE ISLAMIC BANK",
    "Address": "ALQUDS STREET, PALESTINE ISLAMIC BANK BUILDING",
    "City": "RAMALLAH",
    "Branch": "",
    "Postcode": "",
    "Country": "Palestine",
    "Connection": "Active"
  },
  {
    "bankCode": "PMAP",
    "countryCode": "PS",
    "branchCode": "S2P",
    "SWIFT Code": "PMAPPS2P",
    "Bank Name": "PALESTINE MONETARY AUTHORITY",
    "Address": "AL-IRSAL STREET, PMA BUILDING",
    "City": "AL-BIREH",
    "Branch": "",
    "Postcode": "",
    "Country": "Palestine",
    "Connection": "Active"
  },
  {
    "bankCode": "PMAP",
    "countryCode": "PS",
    "branchCode": "S22",
    "SWIFT Code": "PMAPPS22",
    "Bank Name": "PALESTINE MONETARY AUTHORITY",
    "Address": "AL-IRSAL STREET, PMA BUILDING",
    "City": "AL-BIREH",
    "Branch": "",
    "Postcode": "",
    "Country": "Palestine",
    "Connection": "Active"
  },
  {
    "bankCode": "PMAP",
    "countryCode": "PS",
    "branchCode": "PEX",
    "SWIFT Code": "PMAPPS22PEX",
    "Bank Name": "PALESTINE MONETARY AUTHORITY",
    "Address": "",
    "City": "AL-BIREH",
    "Branch": "CSD",
    "Postcode": "",
    "Country": "Palestine",
    "Connection": "Active"
  },
  {
    "bankCode": "PMAP",
    "countryCode": "PS",
    "branchCode": "ECC",
    "SWIFT Code": "PMAPPS22ECC",
    "Bank Name": "PALESTINE MONETARY AUTHORITY",
    "Address": "AL-IRSAL STREET, PMA BUILDING",
    "City": "AL-BIREH",
    "Branch": "ELECTRONIC CHEQUES CLEARING ECC",
    "Postcode": "",
    "Country": "Palestine",
    "Connection": "Active"
  },
  {
    "bankCode": "PMAP",
    "countryCode": "PS",
    "branchCode": "ACH",
    "SWIFT Code": "PMAPPS22ACH",
    "Bank Name": "PALESTINE MONETARY AUTHORITY",
    "Address": "",
    "City": "RAMALLAH",
    "Branch": "",
    "Postcode": "",
    "Country": "Palestine",
    "Connection": "Active"
  },
  {
    "bankCode": "PMAP",
    "countryCode": "PS",
    "branchCode": "ASA",
    "SWIFT Code": "PMAPPS22ASA",
    "Bank Name": "PALESTINE MONETARY AUTHORITY",
    "Address": "",
    "City": "RAMALLAH",
    "Branch": "AUTHORIZED SETTLEMENT AGENRT",
    "Postcode": "",
    "Country": "Palestine",
    "Connection": "Active"
  },
  {
    "bankCode": "PMAP",
    "countryCode": "PS",
    "branchCode": "TIA",
    "SWIFT Code": "PMAPPS22TIA",
    "Bank Name": "PALESTINE MONETARY AUTHORITY",
    "Address": "",
    "City": "RAMALLAH",
    "Branch": "TECHNICAL INFRATRUCTURE AGENT",
    "Postcode": "",
    "Country": "Palestine",
    "Connection": "Active"
  },
  {
    "bankCode": "ALDN",
    "countryCode": "PS",
    "branchCode": "S22",
    "SWIFT Code": "ALDNPS22",
    "Bank Name": "QUDS BANK",
    "Address": "AL-QUDS STREET, MASSYOUN, QUDS BANK BUILDING",
    "City": "RAMALLAH",
    "Branch": "",
    "Postcode": "",
    "Country": "Palestine",
    "Connection": "Active"
  },
  {
    "bankCode": "SAFK",
    "countryCode": "PS",
    "branchCode": "S22",
    "SWIFT Code": "SAFKPS22",
    "Bank Name": "SAFA BANK",
    "Address": "AL JIHAD (STRUGGLE) ST",
    "City": "RAMALLAH",
    "Branch": "",
    "Postcode": "",
    "Country": "Palestine",
    "Connection": "Active"
  },
  {
    "bankCode": "HBHO",
    "countryCode": "PS",
    "branchCode": "S22",
    "SWIFT Code": "HBHOPS22",
    "Bank Name": "THE HOUSING BANK FOR TRADE AND FINANCE/RAMALLAH",
    "Address": "AL-BAREED STREET, RUKAB BUILDING",
    "City": "RAMALLAH",
    "Branch": "",
    "Postcode": "",
    "Country": "Palestine",
    "Connection": "Active"
  },
  {
    "bankCode": "TNBC",
    "countryCode": "PS",
    "branchCode": "S22",
    "SWIFT Code": "TNBCPS22",
    "Bank Name": "THE NATIONAL BANK PLC (FORMERLY AL RAFAH MICROFINANCE BANK)",
    "Address": "MAHMOUD DARWEESH CIRCLE, THE NATIONAL BANK PLC BUILDING",
    "City": "RAMALLAH",
    "Branch": "",
    "Postcode": "",
    "Country": "Palestine",
    "Connection": "Active"
  }
]
module.exports = palestine
