const papuaNewGuinea = [
  {
    "bankCode": "ANZB",
    "countryCode": "PG",
    "branchCode": "GPX",
    "SWIFT Code": "ANZBPGPX",
    "Bank Name": "AUSTRALIA AND NEW ZEALAND BANKING GROUP (PNG) LTD.",
    "Address": "INVESMEN HAUS, DOUGLAS STREET",
    "City": "PORT MORESBY",
    "Branch": "",
    "Postcode": "121",
    "Country": "Papua New Guinea",
    "Connection": "Active"
  },
  {
    "bankCode": "BPNG",
    "countryCode": "PG",
    "branchCode": "GPM",
    "SWIFT Code": "BPNGPGPM",
    "Bank Name": "BANK OF PAPUA NEW GUINEA",
    "Address": "TOROBERT HAUS LOT 1 CORNER OF, DOUGLAS STREET SECTION 25",
    "City": "PORT MORESBY",
    "Branch": "",
    "Postcode": "121",
    "Country": "Papua New Guinea",
    "Connection": "Active"
  },
  {
    "bankCode": "BOSP",
    "countryCode": "PG",
    "branchCode": "GPM",
    "SWIFT Code": "BOSPPGPM",
    "Bank Name": "BSP FINANCIAL GROUP LIMITED",
    "Address": "ALLOTMENTS 6 - 7 KLINKI STREET,, WAIGANI DRIVE SECTION 34",
    "City": "PORT MORESBY",
    "Branch": "",
    "Postcode": "121",
    "Country": "Papua New Guinea",
    "Connection": "Active"
  },
  {
    "bankCode": "CPFN",
    "countryCode": "PG",
    "branchCode": "GPM",
    "SWIFT Code": "CPFNPGPM",
    "Bank Name": "CREDIT CORPORATION FINANCE LIMITED",
    "Address": "CREDIT HOUSE GRANVILLE, FLOOR 1 2,, 3 AND 8 CUTHBERTSON STREET SECTION, 45 ALLOTMENT",
    "City": "PORT MORESBY",
    "Branch": "",
    "Postcode": "121",
    "Country": "Papua New Guinea",
    "Connection": "Active"
  },
  {
    "bankCode": "FIVF",
    "countryCode": "PG",
    "branchCode": "GPM",
    "SWIFT Code": "FIVFPGPM",
    "Bank Name": "FIRST INVESTMENT FINANCE LIMITED",
    "Address": "ELA BEACH TOWER, FLOOR TOP, 26 SECTION 6 ALLOTMENT GRANVILLE",
    "City": "PORT MORESBY",
    "Branch": "",
    "Postcode": "121",
    "Country": "Papua New Guinea",
    "Connection": "Active"
  },
  {
    "bankCode": "KINI",
    "countryCode": "PG",
    "branchCode": "GPG",
    "SWIFT Code": "KINIPGPG",
    "Bank Name": "KINA SECURITIES LIMITED",
    "Address": "KINA BANK HAUS, 9 DOUGLAS STREET",
    "City": "PORT MORESBY",
    "Branch": "",
    "Postcode": "121",
    "Country": "Papua New Guinea",
    "Connection": "Active"
  },
  {
    "bankCode": "TSLS",
    "countryCode": "PG",
    "branchCode": "GPP",
    "SWIFT Code": "TSLSPGPP",
    "Bank Name": "TEACHERS SAVINGS AND LOAN SOCIETY LIMITED",
    "Address": "2 TISA HOUSE, FLOOR 1, SIR JOHN GUISE DRIVE, WAIGANI",
    "City": "PORT MORESBY",
    "Branch": "",
    "Postcode": "121",
    "Country": "Papua New Guinea",
    "Connection": "Active"
  },
  {
    "bankCode": "WPAC",
    "countryCode": "PG",
    "branchCode": "GPM",
    "SWIFT Code": "WPACPGPM",
    "Bank Name": "WESTPAC BANK - PNG - LIMITED",
    "Address": "FLOOR 1 BURNS PHILP HAUS, CORNER, OF CHAMPION PARADE AND MUSGRAVE, STREET",
    "City": "PORT MORESBY",
    "Branch": "",
    "Postcode": "121",
    "Country": "Papua New Guinea",
    "Connection": "Active"
  }
]
module.exports = papuaNewGuinea
