const paraguay = [
  {
    "countryCode": "BNIT",
    "bankCode": "PY",
    "branchCode": "YPA",
    "SWIFT Code": "BNITPYPA",
    "Bank Name": "BANCO ATLAS S.A.",
    "Address": "QUESADA , ESQUINA TTE. ZOTTI 4926, ATLAS CENTER",
    "City": "ASUNCION",
    "Branch": "",
    "Postcode": "1113",
    "Country": "Paraguay",
    "Connection": "Active"
  },
  {
    "countryCode": "AMAM",
    "bankCode": "PY",
    "branchCode": "YPA",
    "SWIFT Code": "AMAMPYPA",
    "Bank Name": "BANCO BASA S.A.",
    "Address": "AVIADORES DEL CHACO, Y PABLO, ALBORNO",
    "City": "ASUNCION",
    "Branch": "",
    "Postcode": "3309",
    "Country": "Paraguay",
    "Connection": "Active"
  },
  {
    "countryCode": "BCPA",
    "bankCode": "PY",
    "branchCode": "YPB",
    "SWIFT Code": "BCPAPYPB",
    "Bank Name": "BANCO CENTRAL DEL PARAGUAY",
    "Address": "AVENIDA PABLO VI Y SARGENTO MARECOS",
    "City": "ASUNCION",
    "Branch": "",
    "Postcode": "1767",
    "Country": "Paraguay",
    "Connection": "Active"
  },
  {
    "countryCode": "BCPA",
    "bankCode": "PY",
    "branchCode": "YPD",
    "SWIFT Code": "BCPAPYPD",
    "Bank Name": "BANCO CENTRAL DEL PARAGUAY",
    "Address": "FEDERACION RUSA, Y CABO MARECOS 861",
    "City": "ASUNCION",
    "Branch": "",
    "Postcode": "1767",
    "Country": "Paraguay",
    "Connection": "Active"
  },
  {
    "countryCode": "BCPA",
    "bankCode": "PY",
    "branchCode": "YPR",
    "SWIFT Code": "BCPAPYPR",
    "Bank Name": "BANCO CENTRAL DEL PARAGUAY",
    "Address": "FEDERACION RUSA, Y CABO MARECOS 861",
    "City": "ASUNCION",
    "Branch": "",
    "Postcode": "1767",
    "Country": "Paraguay",
    "Connection": "Active"
  },
  {
    "countryCode": "BCPA",
    "bankCode": "PY",
    "branchCode": "YPX",
    "SWIFT Code": "BCPAPYPX",
    "Bank Name": "BANCO CENTRAL DEL PARAGUAY",
    "Address": "FEDERACION RUSA, Y A. R. BASTOS 861",
    "City": "ASUNCION",
    "Branch": "",
    "Postcode": "1767",
    "Country": "Paraguay",
    "Connection": "Active"
  },
  {
    "countryCode": "BCPA",
    "bankCode": "PY",
    "branchCode": "GON",
    "SWIFT Code": "BCPAPYPXGON",
    "Bank Name": "BANCO CENTRAL DEL PARAGUAY",
    "Address": "",
    "City": "ASUNCION",
    "Branch": "OPERACIONES NACIONALES - DPTO. DE CREDITO Y CTAS. CTES.",
    "Postcode": "",
    "Country": "Paraguay",
    "Connection": "Active"
  },
  {
    "countryCode": "BCNA",
    "bankCode": "PY",
    "branchCode": "YPA",
    "SWIFT Code": "BCNAPYPA",
    "Bank Name": "BANCO CONTINENTAL SAECA",
    "Address": "LA PARAGUAYA, ESTRELLA 621",
    "City": "ASUNCION",
    "Branch": "",
    "Postcode": "",
    "Country": "Paraguay",
    "Connection": "Active"
  },
  {
    "countryCode": "NACN",
    "bankCode": "PY",
    "branchCode": "YPA",
    "SWIFT Code": "NACNPYPA",
    "Bank Name": "BANCO DE LA NACION ARGENTINA",
    "Address": "PALMA Y CHILE",
    "City": "ASUNCION",
    "Branch": "SUCURSAL ASUNCION",
    "Postcode": "1221",
    "Country": "Paraguay",
    "Connection": "Active"
  },
  {
    "countryCode": "NACN",
    "bankCode": "PY",
    "branchCode": "0PC",
    "SWIFT Code": "NACNPYPA0PC",
    "Bank Name": "BANCO DE LA NACION ARGENTINA",
    "Address": "",
    "City": "CONCEPCION",
    "Branch": "",
    "Postcode": "",
    "Country": "Paraguay",
    "Connection": "Active"
  },
  {
    "countryCode": "NACN",
    "bankCode": "PY",
    "branchCode": "0PE",
    "SWIFT Code": "NACNPYPA0PE",
    "Bank Name": "BANCO DE LA NACION ARGENTINA",
    "Address": "",
    "City": "ENCARNACION",
    "Branch": "",
    "Postcode": "",
    "Country": "Paraguay",
    "Connection": "Active"
  },
  {
    "countryCode": "NACN",
    "bankCode": "PY",
    "branchCode": "0P3",
    "SWIFT Code": "NACNPYPA0P3",
    "Bank Name": "BANCO DE LA NACION ARGENTINA",
    "Address": "",
    "City": "VILLARRICA",
    "Branch": "",
    "Postcode": "",
    "Country": "Paraguay",
    "Connection": "Active"
  },
  {
    "countryCode": "BRAS",
    "bankCode": "PY",
    "branchCode": "YPX",
    "SWIFT Code": "BRASPYPX",
    "Bank Name": "BANCO DO BRASIL S.A.",
    "Address": "CHACO Y HERMINIO MALDONADO, AVDA., SANTA TERESA E/AVIADORES 2106, COMPLEJO BLUE TOWER, TORRE 1, FLOOR, 19",
    "City": "ASUNCION",
    "Branch": "",
    "Postcode": "1827",
    "Country": "Paraguay",
    "Connection": "Active"
  },
  {
    "countryCode": "FAMI",
    "bankCode": "PY",
    "branchCode": "YPA",
    "SWIFT Code": "FAMIPYPA",
    "Bank Name": "BANCO FAMILIAR S.A.E.C.A.",
    "Address": "ED. GRUPO GENERAL, CHILE, C/ JEJUI, 1080",
    "City": "ASUNCION",
    "Branch": "",
    "Postcode": "",
    "Country": "Paraguay",
    "Connection": "Active"
  },
  {
    "countryCode": "BGNB",
    "bankCode": "PY",
    "branchCode": "YPX",
    "SWIFT Code": "BGNBPYPX",
    "Bank Name": "BANCO GNB PARAGUAY S.A.",
    "Address": "AVENIDA AVIADORES DEL CHACO, ESQUINA HERIB CAMPOS CERVERA 2351",
    "City": "ASUNCION",
    "Branch": "",
    "Postcode": "1749",
    "Country": "Paraguay",
    "Connection": "Active"
  },
  {
    "countryCode": "UBBR",
    "bankCode": "PY",
    "branchCode": "TSS",
    "SWIFT Code": "UBBRPYPXTSS",
    "Bank Name": "BANCO ITAU PARAGUAY S.A.",
    "Address": "CALLE OLIVA CON CALLE CHILE 349, STRASSEN",
    "City": "ASUNCION",
    "Branch": "",
    "Postcode": "1101",
    "Country": "Paraguay",
    "Connection": "Active"
  },
  {
    "countryCode": "UBBR",
    "bankCode": "PY",
    "branchCode": "YPX",
    "SWIFT Code": "UBBRPYPX",
    "Bank Name": "BANCO ITAU PARAGUAY S.A.",
    "Address": "CALLE OLIVA, CON CALLE CHILE 349",
    "City": "ASUNCION",
    "Branch": "",
    "Postcode": "1221",
    "Country": "Paraguay",
    "Connection": "Active"
  },
  {
    "countryCode": "BNFA",
    "bankCode": "PY",
    "branchCode": "YPA",
    "SWIFT Code": "BNFAPYPA",
    "Bank Name": "BANCO NACIONAL DE FOMENTO",
    "Address": "INDEPENDENCIA NACIONAL, Y DE MAYO, 25",
    "City": "ASUNCION",
    "Branch": "",
    "Postcode": "1810",
    "Country": "Paraguay",
    "Connection": "Active"
  },
  {
    "countryCode": "BCOP",
    "bankCode": "PY",
    "branchCode": "YPA",
    "SWIFT Code": "BCOPPYPA",
    "Bank Name": "BANCO PARA LA COMERCIALIZACION Y LA PRODUCCION SOCIEDAD ANONIMA (BANCOP S.A.)",
    "Address": "AVDA. MCAL. LOPEZ, C/ DR. MORRA, 3811 EDIF. MARISCAL CENTER, FLOOR 0",
    "City": "ASUNCION",
    "Branch": "",
    "Postcode": "1808",
    "Country": "Paraguay",
    "Connection": "Active"
  },
  {
    "countryCode": "BISA",
    "bankCode": "PY",
    "branchCode": "YPE",
    "SWIFT Code": "BISAPYPE",
    "Bank Name": "BANCO RIO SAECA",
    "Address": "AV. MCAL LOPEZ E/AV. RCA. ARGENTINA",
    "City": "ASUNCION",
    "Branch": "",
    "Postcode": "1411",
    "Country": "Paraguay",
    "Connection": "Active"
  },
  {
    "countryCode": "FIPJ",
    "bankCode": "PY",
    "branchCode": "YPA",
    "SWIFT Code": "FIPJPYPA",
    "Bank Name": "FINANCIERA PARAGUAYO JAPONESA SAECA",
    "Address": "EDUARDO VICTOR HAEDO 179",
    "City": "ASUNCION",
    "Branch": "",
    "Postcode": "1245",
    "Country": "Paraguay",
    "Connection": "Active"
  },
  {
    "countryCode": "COMA",
    "bankCode": "PY",
    "branchCode": "YPA",
    "SWIFT Code": "COMAPYPA",
    "Bank Name": "FINANCIERA UENO S.A.E.C.A.",
    "Address": "AVDA SANTA TERESA E/ AVDA AVIA 1827",
    "City": "ASUNCION",
    "Branch": "",
    "Postcode": "1410",
    "Country": "Paraguay",
    "Connection": "Active"
  },
  {
    "countryCode": "FOPL",
    "bankCode": "PY",
    "branchCode": "YPA",
    "SWIFT Code": "FOPLPYPA",
    "Bank Name": "FONPLATA - FONDO FINANCIERO PARA EL DESAROLLO DE LA CUENCA DEL PLATA",
    "Address": "INDEPENDENCIA NACIONAL ESQ, FULGENCI P-15 ED. EL PRODUCTOR",
    "City": "ASUNCION",
    "Branch": "",
    "Postcode": "3300",
    "Country": "Paraguay",
    "Connection": "Active"
  },
  {
    "countryCode": "IIFA",
    "bankCode": "PY",
    "branchCode": "YPA",
    "SWIFT Code": "IIFAPYPA",
    "Bank Name": "GRUPO INTERNACIONAL DE FINANZAS S.A.E.C.A. (INTERFISA BANCO)",
    "Address": "DE MAYO ESQUINA PARAGUARI 25, 417",
    "City": "ASUNCION",
    "Branch": "",
    "Postcode": "9999",
    "Country": "Paraguay",
    "Connection": "Active"
  },
  {
    "countryCode": "SLRA",
    "bankCode": "PY",
    "branchCode": "YPA",
    "SWIFT Code": "SLRAPYPA",
    "Bank Name": "SOLAR BANCO S.A.E.",
    "Address": "AVDA. PERU CASI JUAN DE SALAZAR 592",
    "City": "ASUNCION",
    "Branch": "",
    "Postcode": "1409",
    "Country": "Paraguay",
    "Connection": "Active"
  },
  {
    "countryCode": "BSUD",
    "bankCode": "PY",
    "branchCode": "YPX",
    "SWIFT Code": "BSUDPYPX",
    "Bank Name": "SUDAMERIS BANK S.A.E.C.A.",
    "Address": "EDIFICIO SUDAMERIS, INDEPENDENCIA, NACIONAL 513 513",
    "City": "ASUNCION",
    "Branch": "",
    "Postcode": "1301",
    "Country": "Paraguay",
    "Connection": "Active"
  },
  {
    "countryCode": "VISC",
    "bankCode": "PY",
    "branchCode": "YPA",
    "SWIFT Code": "VISCPYPA",
    "Bank Name": "VISION BANCO S.A.E.C.A.",
    "Address": "AVDA. SANTA TERESA 3088",
    "City": "ASUNCION",
    "Branch": "",
    "Postcode": "1824",
    "Country": "Paraguay",
    "Connection": "Active"
  }
]
module.exports = paraguay
