const philippines = [
  {
    "countryCode": "WERA",
    "bankCode": "PH",
    "branchCode": "HM2",
    "SWIFT Code": "WERAPHM2",
    "Bank Name": "WELCOME BANK, RURAL BANK INC.",
    "Address": "FLOOR GO2, I SQUARE BUILDING, 15 MERALCO AVENUE, ORTIGAS CENTER",
    "City": "CITY OF PASIG",
    "Branch": "",
    "Postcode": "1605",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "TYBK",
    "bankCode": "PH",
    "branchCode": "HMM",
    "SWIFT Code": "TYBKPHMM",
    "Bank Name": "YUANTA SAVINGS BANK (FORMERLY TONGYANG SAVINGS BANK)",
    "Address": "FLOOR GF, CHATHAM BUILDING, 116 VALERE CORNER V.A. RUFINO STREE, SALCEDO VILLAGE",
    "City": "CITY OF MANILA",
    "Branch": "",
    "Postcode": "1227",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "ZBTE",
    "bankCode": "PH",
    "branchCode": "HM2",
    "SWIFT Code": "ZBTEPHM2",
    "Bank Name": "ZYBI TECH INC.",
    "Address": "FLOOR 8, BPO TOWER, METROPOLITAN PARK, ROXAS BLVD, BAY AREA",
    "City": "CITY OF PASAY",
    "Branch": "",
    "Postcode": "1302",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "GLTE",
    "bankCode": "PH",
    "branchCode": "HMT",
    "SWIFT Code": "GLTEPHMT",
    "Bank Name": "GLOBE TELECOM, INC.",
    "Address": "THE GLOBE TOWER, 32 STREET CORNER 7TH AVENUE, BONIFACIO GLOBAL CITY",
    "City": "CITY OF TAGUIG",
    "Branch": "",
    "Postcode": "1634",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "LURR",
    "bankCode": "PH",
    "branchCode": "HM2",
    "SWIFT Code": "LURRPHM2",
    "Bank Name": "GM BANK OF LUZON, INC. (A RURAL BANK)",
    "Address": "MAHARLIKA HIGHWAY, BRGY GENERAL",
    "City": "CITY OF CABANATUAN",
    "Branch": "",
    "Postcode": "3100",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "GOTY",
    "bankCode": "PH",
    "branchCode": "HM2",
    "SWIFT Code": "GOTYPHM2",
    "Bank Name": "GOTYME BANK CORPORATION",
    "Address": "FLOOR 30, ROBINSONS CYBERSCAPE, GAMMA TOPAZ AND RUBY ROADS SAN, ANTONIO ORTIGAS CENTER",
    "City": "CITY OF PASIG",
    "Branch": "",
    "Postcode": "1605",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "GPNE",
    "bankCode": "PH",
    "branchCode": "HM2",
    "SWIFT Code": "GPNEPHM2",
    "Bank Name": "GPAY NETWORK PH, INC.",
    "Address": "LOT 1A, FLOOR 27 AND 28, LOT 1A EXCHANGE ROAD CORNER JADE ST",
    "City": "CITY OF PASIG",
    "Branch": "",
    "Postcode": "1600",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "HBPH",
    "bankCode": "PH",
    "branchCode": "HMM",
    "SWIFT Code": "HBPHPHMM",
    "Bank Name": "HSBC SAVINGS BANK (PHILIPINES) INC.",
    "Address": "UNIT 1, THE COMMERCIAL COMPLEX, FLOOR GF, MADRIGA AVE, AYALA ALABANG VILLAGE",
    "City": "CITY OF MUNTINLUPA",
    "Branch": "",
    "Postcode": "1770",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "HNBK",
    "bankCode": "PH",
    "branchCode": "HMM",
    "SWIFT Code": "HNBKPHMM",
    "Bank Name": "HUA NAN COMMERCIAL BANK, LTD. MANILA BRANCH",
    "Address": "FLOOR 26, ALPHALAND AYALA TOWER, 6789 AYALA AVENUE",
    "City": "CITY OF MAKATI",
    "Branch": "",
    "Postcode": "1226",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "IREM",
    "bankCode": "PH",
    "branchCode": "HM2",
    "SWIFT Code": "IREMPHM2",
    "Bank Name": "I-REMIT, INC.",
    "Address": "FLOOR 26, DISCOVERY CENTER, 25 ADB AVENUE, ORTIGAS CENTER",
    "City": "CITY OF PASIG",
    "Branch": "",
    "Postcode": "1605",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "ICBK",
    "bankCode": "PH",
    "branchCode": "HMM",
    "SWIFT Code": "ICBKPHMM",
    "Bank Name": "INDUSTRIAL AND COMMERCIAL BANK OF CHINA LIMITED, MANILA BRANCH",
    "Address": "FLOOR 24, THE CURVE TOWER, 32ND STREET CORNER THIRD AVENUE",
    "City": "CITY OF TAGUIG",
    "Branch": "",
    "Postcode": "1637",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "IBKO",
    "bankCode": "PH",
    "branchCode": "HMM",
    "SWIFT Code": "IBKOPHMM",
    "Bank Name": "INDUSTRIAL BANK OF KOREA, MANILA BRANCH",
    "Address": "ONE WORLD PLACE, 8 32ND BONIFACIO GLOBAL CITY",
    "City": "CITY OF TAGUIG",
    "Branch": "",
    "Postcode": "1630",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "IFIP",
    "bankCode": "PH",
    "branchCode": "HM2",
    "SWIFT Code": "IFIPPHM2",
    "Bank Name": "INFOSERVE INCORPORATED",
    "Address": "CONDOMINIUM FLOOR UGF, VERNIDA 1, 120 AMORSOLO ST, LEGASPI VILLAGE, BGY. SAN LORENZO",
    "City": "CITY OF MAKATI",
    "Branch": "",
    "Postcode": "1229",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "INGB",
    "bankCode": "PH",
    "branchCode": "HMM",
    "SWIFT Code": "INGBPHMM",
    "Bank Name": "ING BANK N.V.",
    "Address": "FLOOR 22, ARTHALAND CENTURY, PACIFIC TOWER 5TH AVENUE CORNER, 30TH STREET BONIFACIO GLOBAL CITY",
    "City": "CITY OF TAGUIG",
    "Branch": "",
    "Postcode": "1634",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "ITDE",
    "bankCode": "PH",
    "branchCode": "HM2",
    "SWIFT Code": "ITDEPHM2",
    "Bank Name": "INTER-ASIA DEVELOPMENT BANK",
    "Address": "J. P. RIZAL",
    "City": "CITY OF TAGAYTAY",
    "Branch": "",
    "Postcode": "4120",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "CHAS",
    "bankCode": "PH",
    "branchCode": "OBU",
    "SWIFT Code": "CHASPHMMOBU",
    "Bank Name": "JPMORGAN CHASE BANK, N.A., MANILA BRANCH",
    "Address": "FLOOR 4, CORINTHIAN PLAZA BLDG, 121 PASEO DE ROAXAS",
    "City": "CITY OF MAKATI",
    "Branch": "OFFHORE BANKING UNIT",
    "Postcode": "1229",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "CHAS",
    "bankCode": "PH",
    "branchCode": "ENQ",
    "SWIFT Code": "CHASPHMMENQ",
    "Bank Name": "JPMORGAN CHASE BANK, N.A., MANILA BRANCH",
    "Address": "",
    "City": "CITY OF MANILA",
    "Branch": "TELEX AND S.W.I.F.T. MESSAGE ENQUIRIES",
    "Postcode": "1000",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "CHAS",
    "bankCode": "PH",
    "branchCode": "HMM",
    "SWIFT Code": "CHASPHMM",
    "Bank Name": "JPMORGAN CHASE BANK, N.A., MANILA BRANCH",
    "Address": "FLOOR 25, JPMORGAN CHASE AND CO, TOWER 9TH AVENUE CORNER 38TH STREET, BONIFACIO GLOBAL CITY",
    "City": "CITY OF TAGUIG",
    "Branch": "",
    "Postcode": "1635",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "KACU",
    "bankCode": "PH",
    "branchCode": "HM2",
    "SWIFT Code": "KACUPHM2",
    "Bank Name": "KATIPUNAN BANKING CORPORATION 'A RURAL BANK'",
    "Address": "FLOOR 3, KB BUILDING, QUEZON AVENUE CORNER AGUILAR STREET, MIPUTAK",
    "City": "CITY OF DIPOLOG",
    "Branch": "",
    "Postcode": "7100",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "KOEX",
    "bankCode": "PH",
    "branchCode": "HMM",
    "SWIFT Code": "KOEXPHMM",
    "Bank Name": "KEB HANA BANK",
    "Address": "FLOOR 21, ZUELLIG BUILDING, AKATI AVN CRN PASEO ROXAS STRT",
    "City": "CITY OF MAKATI",
    "Branch": "",
    "Postcode": "1225",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "LPCR",
    "bankCode": "PH",
    "branchCode": "HM2",
    "SWIFT Code": "LPCRPHM2",
    "Bank Name": "LAGUNA PRESTIGE BANKING CORPORATION A RURAL BANK",
    "Address": "JP RIZAL COR. F LIMCAOCO ST, POBLACION 1",
    "City": "CITY OF CABUYAO",
    "Branch": "",
    "Postcode": "4025",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "TLBP",
    "bankCode": "PH",
    "branchCode": "HMM",
    "SWIFT Code": "TLBPPHMM",
    "Bank Name": "LAND BANK OF THE PHILIPPINES",
    "Address": "LANDBANK PLAZA 1598 M.H.DEL PILAR, COR DR MALATE QUINTOS STREETS",
    "City": "CITY OF MANILA",
    "Branch": "",
    "Postcode": "1004",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "LIRA",
    "bankCode": "PH",
    "branchCode": "HM2",
    "SWIFT Code": "LIRAPHM2",
    "Bank Name": "LIFEBANK-A RURAL BANK",
    "Address": "BYPASS ROAD, BRGY. DUYANDUYAN, SANTA BARBARA",
    "City": "CITY OF ILOILO",
    "Branch": "",
    "Postcode": "5000",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "LOLP",
    "bankCode": "PH",
    "branchCode": "HM2",
    "SWIFT Code": "LOLPPHM2",
    "Bank Name": "LOLC BANK PHILIPPINES INC",
    "Address": "BRAVO BUSINESS CENTER, L 17 B 4 JP LAUREL HIGHWAY",
    "City": "CITY OF TANAUAN",
    "Branch": "",
    "Postcode": "4232",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "LFSH",
    "bankCode": "PH",
    "branchCode": "HM2",
    "SWIFT Code": "LFSHPHM2",
    "Bank Name": "LULU FINANCIAL SERVICES (PHILS) INC",
    "Address": "UNIT 1006, FLOOR 10, ONE WORLD PLACE 32ND ST., CORNER 9TH AVE",
    "City": "CITY OF TAGUIG",
    "Branch": "",
    "Postcode": "1634",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "MRLC",
    "bankCode": "PH",
    "branchCode": "HM2",
    "SWIFT Code": "MRLCPHM2",
    "Bank Name": "MACTAN RURAL BANK (LAPU-LAPU CITY) INC",
    "Address": "MYFC BUILDING, MAXIMO PATALINGHUG AVENUE",
    "City": "CITY OF LAPU-LAPU",
    "Branch": "",
    "Postcode": "6015",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "MKDC",
    "bankCode": "PH",
    "branchCode": "HM2",
    "SWIFT Code": "MKDCPHM2",
    "Bank Name": "MAKILING DEVELOPMENT BANK CORPORATION",
    "Address": "YTMI REALTY SEZ MAKILING",
    "City": "CITY OF CALAMBA",
    "Branch": "",
    "Postcode": "4027",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "MLRU",
    "bankCode": "PH",
    "branchCode": "HM2",
    "SWIFT Code": "MLRUPHM2",
    "Bank Name": "MALARAYAT RURAL BANK, INC.",
    "Address": "G.A. SOLIS ST",
    "City": "CITY OF LIPA",
    "Branch": "",
    "Postcode": "4217",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "MRAL",
    "bankCode": "PH",
    "branchCode": "HMM",
    "SWIFT Code": "MRALPHMM",
    "Bank Name": "MANILA ELECTRIC COMPANY",
    "Address": "FLOOR 5, LOPEZ BUILDING, ORTIGAS AVENUE",
    "City": "CITY OF PASIG",
    "Branch": "",
    "Postcode": "0300",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "MAYC",
    "bankCode": "PH",
    "branchCode": "HM2",
    "SWIFT Code": "MAYCPHM2",
    "Bank Name": "MARCOPAY INC.",
    "Address": "FLOOR 8, THREE/NEO BUILDING, COR. 30TH 3RD AVENUE COR. 30TH STRE, CRESCENT PARK WEST",
    "City": "CITY OF TAGUIG",
    "Branch": "",
    "Postcode": "1640",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "MYYA",
    "bankCode": "PH",
    "branchCode": "HM2",
    "SWIFT Code": "MYYAPHM2",
    "Bank Name": "MAYA BANK, INC.",
    "Address": "FLOOR 6, LAUNCHPAD, SHERIDAN CORNER RELIANCE STREETS",
    "City": "CITY OF MANDALUYONG",
    "Branch": "",
    "Postcode": "1552",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "MBBE",
    "bankCode": "PH",
    "branchCode": "HMM",
    "SWIFT Code": "MBBEPHMM",
    "Bank Name": "MAYBANK PHILIPPINES, INC",
    "Address": "LEGASPI TOWER 300 ROXAS BLVD COR., P. OCAMPO SR. ST",
    "City": "CITY OF MANILA",
    "Branch": "",
    "Postcode": "1229",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "ICBC",
    "bankCode": "PH",
    "branchCode": "HMM",
    "SWIFT Code": "ICBCPHMM",
    "Bank Name": "MEGA INTERNATIONAL COMMERCIAL BANK CO., LTD., MANILA BRANCH",
    "Address": "PACIFIC STAR BUILDING MAKATI, AVENUE CNR SEN. GIL. PUYA T AVENUE",
    "City": "CITY OF MAKATI",
    "Branch": "",
    "Postcode": "1225",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "MCCT",
    "bankCode": "PH",
    "branchCode": "HMM",
    "SWIFT Code": "MCCTPHMM",
    "Bank Name": "MEGAWIDE CONSTRUCTION CORPORATION",
    "Address": "20 N. DOMINGO STREET, BARANGAY VALENCIA",
    "City": "CITY OF QUEZON",
    "Branch": "",
    "Postcode": "1112",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "MEOP",
    "bankCode": "PH",
    "branchCode": "HM2",
    "SWIFT Code": "MEOPPHM2",
    "Bank Name": "METRO SOUTH COOPERATIVE BANK",
    "Address": "FLOOR 3, IDC CENTRE BUILDING, KALAYAAN AVENUE CORNER ZAPOTE ST",
    "City": "CITY OF MAKATI",
    "Branch": "",
    "Postcode": "1205",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "MBTC",
    "bankCode": "PH",
    "branchCode": "HMM",
    "SWIFT Code": "MBTCPHMM",
    "Bank Name": "METROPOLITAN BANK AND TRUST CO.",
    "Address": "METROBANK PLAZA BUILDING, SEN. GIL J. PUYAT AVENUE",
    "City": "CITY OF MAKATI",
    "Branch": "",
    "Postcode": "1200",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "MHCB",
    "bankCode": "PH",
    "branchCode": "HMM",
    "SWIFT Code": "MHCBPHMM",
    "Bank Name": "MIZUHO BANK, LTD., MANILA BRANCH",
    "Address": "FLOOR 25, THE ZUELLIG BUILDING, MAKATI AVENUE CORNER PASEO DE ROXAS",
    "City": "CITY OF MAKATI",
    "Branch": "",
    "Postcode": "1225",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "MOML",
    "bankCode": "PH",
    "branchCode": "HM2",
    "SWIFT Code": "MOMLPHM2",
    "Bank Name": "MONEY MALL RURAL BANK, INC.",
    "Address": "NATIONAL HIGHWAY, POBLACION",
    "City": "CITY OF DAVAO",
    "Branch": "",
    "Postcode": "8807",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "BOTK",
    "bankCode": "PH",
    "branchCode": "HMM",
    "SWIFT Code": "BOTKPHMM",
    "Bank Name": "MUFG BANK, LTD., MANILA BRANCH",
    "Address": "FLOOR 15, 6788 AYALA AVENUE",
    "City": "CITY OF MAKATI",
    "Branch": "MANILA BRANCH",
    "Postcode": "1226",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "MVRS",
    "bankCode": "PH",
    "branchCode": "HM2",
    "SWIFT Code": "MVRSPHM2",
    "Bank Name": "MVSM BANK (A RURAL BANK SINCE 1953)",
    "Address": "FLOOR 1, MVSM BANK BLDG, 389 J. P. RIZAL ST, STO. NINO",
    "City": "CITY OF MARIKINA",
    "Branch": "",
    "Postcode": "1800",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "NESN",
    "bankCode": "PH",
    "branchCode": "HMN",
    "SWIFT Code": "NESNPHMN",
    "Bank Name": "NESTLE BUSINESS SERVICES AOA INC",
    "Address": "LUCKY TEXT COMPOUND, SUPIMA E-CIRCLE MALHACAN ROAD",
    "City": "CITY OF MEYCAUAYAN",
    "Branch": "",
    "Postcode": "3020",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "OMNP",
    "bankCode": "PH",
    "branchCode": "HM2",
    "SWIFT Code": "OMNPPHM2",
    "Bank Name": "OMNIPAY, INC.",
    "Address": "FLOOR 27, CHATHAM HOUSE, 116 VALERO STREET",
    "City": "CITY OF MAKATI",
    "Branch": "",
    "Postcode": "1227",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "OWNO",
    "bankCode": "PH",
    "branchCode": "HM2",
    "SWIFT Code": "OWNOPHM2",
    "Bank Name": "OWN BANK THE RURAL BANK OF CAVITE CITY INC.",
    "Address": "505 P. BURGOS AVE, CARIDAD",
    "City": "CITY OF CAVITE",
    "Branch": "",
    "Postcode": "4100",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "PAEY",
    "bankCode": "PH",
    "branchCode": "HM2",
    "SWIFT Code": "PAEYPHM2",
    "Bank Name": "PAYMONGO PAYMENTS, INC.",
    "Address": "FLOOR 3308, HIGH STREET SOUTH CORP, PLAZA TWR 2 26TH STREET AND 11TH, AVENUE",
    "City": "CITY OF TAGUIG",
    "Branch": "",
    "Postcode": "1634",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "PAHC",
    "bankCode": "PH",
    "branchCode": "HM2",
    "SWIFT Code": "PAHCPHM2",
    "Bank Name": "PAYNAMICS TECHNOLOGIES INC",
    "Address": "FLOOR 2F, PACIFIC STAR BUILDING, MAKATI AVE SEN. GIL J. PUYAT AVE",
    "City": "MAKATI CITY",
    "Branch": "",
    "Postcode": "1226",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "CPHI",
    "bankCode": "PH",
    "branchCode": "HMM",
    "SWIFT Code": "CPHIPHMM",
    "Bank Name": "PHILIPPINE BANK OF COMMUNICATIONS",
    "Address": "PBCOM TOWER, 6795 AYALA AVENUE CORNER V. A. RUFI",
    "City": "CITY OF MAKATI",
    "Branch": "",
    "Postcode": "1226",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "PPBU",
    "bankCode": "PH",
    "branchCode": "HMM",
    "SWIFT Code": "PPBUPHMM",
    "Bank Name": "PHILIPPINE BUSINESS BANK",
    "Address": "350 RIZAL AVEMUE EXTENSION, GRACE PARK",
    "City": "CITY OF CALOOCAN",
    "Branch": "",
    "Postcode": "1400",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "PDAX",
    "bankCode": "PH",
    "branchCode": "HM2",
    "SWIFT Code": "PDAXPHM2",
    "Bank Name": "PHILIPPINE DIGITAL ASSET EXCHANGE, INC. (PDAX)",
    "Address": "FLOOR 12, 27 STREET CORNER 4TH AVENUE, FORT BONIFACIO",
    "City": "CITY OF TAGUIG",
    "Branch": "",
    "Postcode": "1634",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "PNBM",
    "bankCode": "PH",
    "branchCode": "HMM",
    "SWIFT Code": "PNBMPHMM",
    "Bank Name": "PHILIPPINE NATIONAL BANK",
    "Address": "FLOOR 2, PNB FINANCIAL CENTER, PRES. D. MACAPAGAL BLVD",
    "City": "CITY OF MANILA",
    "Branch": "",
    "Postcode": "1109",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "PNBM",
    "bankCode": "PH",
    "branchCode": "TOD",
    "SWIFT Code": "PNBMPHMMTOD",
    "Bank Name": "PHILIPPINE NATIONAL BANK",
    "Address": "PNB FINANCIAL CENTER, PRES. D. MACAPAGAL BLVD",
    "City": "CITY OF PASIG",
    "Branch": "TREASURY OPERATIONS DIVISION",
    "Postcode": "1300",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "PHSB",
    "bankCode": "PH",
    "branchCode": "HMM",
    "SWIFT Code": "PHSBPHMM",
    "Bank Name": "PHILIPPINE SAVINGS BANK",
    "Address": "PSBANK BUILDING, 777 PASEO DE ROXAS COR SEDENO ST",
    "City": "CITY OF MAKATI",
    "Branch": "",
    "Postcode": "1226",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "PHVB",
    "bankCode": "PH",
    "branchCode": "HMM",
    "SWIFT Code": "PHVBPHMM",
    "Bank Name": "PHILIPPINE VETERANS BANK",
    "Address": "PVB HEAD OFFICE BLDG, 101 V. A. RUFINO COR. DELA ROSA STS, LEGASPI VILLAGE",
    "City": "CITY OF MAKATI",
    "Branch": "",
    "Postcode": "1229",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "PHTB",
    "bankCode": "PH",
    "branchCode": "HMM",
    "SWIFT Code": "PHTBPHMM",
    "Bank Name": "PHILTRUST BANK (PHILIPPINE TRUST COMPANY)",
    "Address": "PHILTRUST BANK BUILDING, UNITED NATIONS AVE",
    "City": "CITY OF MANILA",
    "Branch": "",
    "Postcode": "1007",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "AIAC",
    "bankCode": "PH",
    "branchCode": "HMM",
    "SWIFT Code": "AIACPHMM",
    "Bank Name": "AIA PHILIPPINES",
    "Address": "FLOOR 23F, AIA TOWER, BONIFACIO GLOBAL CITY",
    "City": "CITY OF MAKATI",
    "Branch": "",
    "Postcode": "1634",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "AIIP",
    "bankCode": "PH",
    "branchCode": "HMM",
    "SWIFT Code": "AIIPPHMM",
    "Bank Name": "AL-AMANAH ISLAMIC INVESTMENT BANK OF THE PHILIPPINES",
    "Address": "MA-104B, GREENHILLS MCKINLEY ARCADE, ORTIGAS AVENUE",
    "City": "CITY OF MAKATI",
    "Branch": "",
    "Postcode": "1504",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "APHI",
    "bankCode": "PH",
    "branchCode": "HM3",
    "SWIFT Code": "APHIPHM3",
    "Bank Name": "ALIPAY PHILIPPINES INC.",
    "Address": "NET LIMA, 5TH AVE. COR. 26TH",
    "City": "CITY OF TAGUIG",
    "Branch": "",
    "Postcode": "1634",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "APHI",
    "bankCode": "PH",
    "branchCode": "HM2",
    "SWIFT Code": "APHIPHM2",
    "Bank Name": "ALIPAY PHILIPPINES INC.",
    "Address": "FLOOR 25, NET LIMA, 5TH AVE. COR. 26TH E-SQUARE, CRESCENT PARK WEST",
    "City": "CITY OF TAGUIG",
    "Branch": "",
    "Postcode": "1634",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "ALKB",
    "bankCode": "PH",
    "branchCode": "HM2",
    "SWIFT Code": "ALKBPHM2",
    "Bank Name": "ALLBANK (A THRIFT BANK) INC",
    "Address": "EDSA COR. CORNELL STREET",
    "City": "CITY OF MANDALUYONG",
    "Branch": "",
    "Postcode": "1554",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "AUBK",
    "bankCode": "PH",
    "branchCode": "HMM",
    "SWIFT Code": "AUBKPHMM",
    "Bank Name": "ASIA UNITED BANK CORPORATION",
    "Address": "JOY NOSTALG CENTER, 17 ADB AVENUE, ORTIGAS CENTER",
    "City": "CITY OF PASIG",
    "Branch": "",
    "Postcode": "1605",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "ASDB",
    "bankCode": "PH",
    "branchCode": "HMM",
    "SWIFT Code": "ASDBPHMM",
    "Bank Name": "ASIAN DEVELOPMENT BANK",
    "Address": "6 ADB AVENUE",
    "City": "CITY OF MANDALUYONG",
    "Branch": "",
    "Postcode": "1550",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "ANZB",
    "bankCode": "PH",
    "branchCode": "HMX",
    "SWIFT Code": "ANZBPHMX",
    "Bank Name": "AUSTRALIA AND NEW ZEALAND BANKING GROUP LIMITED",
    "Address": "FLOOR 9, MCC CENTRE, 6767 AYALA AVENUE",
    "City": "CITY OF MAKATI",
    "Branch": "",
    "Postcode": "1226",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "AYCO",
    "bankCode": "PH",
    "branchCode": "HMM",
    "SWIFT Code": "AYCOPHMM",
    "Bank Name": "AYALA CORPORATION",
    "Address": "FLOOR 33, TOWER ONE, TOWER ONE AYALA TRIANGLE",
    "City": "CITY OF MAKATI",
    "Branch": "",
    "Postcode": "1226",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "BFSR",
    "bankCode": "PH",
    "branchCode": "HM2",
    "SWIFT Code": "BFSRPHM2",
    "Bank Name": "BANANA FINTECH SERVICES CORPORATION",
    "Address": "FLOOR 6, EAST OFFICES BUILDING, 114 AGUIRRE ST, LEGASPI VILLAGE",
    "City": "CITY OF MAKATI",
    "Branch": "",
    "Postcode": "1229",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "BNNN",
    "bankCode": "PH",
    "branchCode": "HM2",
    "SWIFT Code": "BNNNPHM2",
    "Bank Name": "BANCNET, INC.",
    "Address": "FLOOR 19, BDO EQUITABLE TOWER, 8751 PASEO DE ROXAS",
    "City": "CITY OF MAKATI",
    "Branch": "",
    "Postcode": "1226",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "BNNN",
    "bankCode": "PH",
    "branchCode": "H22",
    "SWIFT Code": "BNNNPH22",
    "Bank Name": "BANCNET, INC.",
    "Address": "FLOOR 19, BDO EQUITABLE TOWER, 8751 PASEO DE ROXAS",
    "City": "CITY OF MAKATI",
    "Branch": "",
    "Postcode": "1226",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "MOUA",
    "bankCode": "PH",
    "branchCode": "HM2",
    "SWIFT Code": "MOUAPHM2",
    "Bank Name": "BANGKO MONTANOSA, INC. A RURAL BANK",
    "Address": "PROVINCIAL ROAD",
    "City": "CITY OF TABUK",
    "Branch": "",
    "Postcode": "3800",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "PHCB",
    "bankCode": "PH",
    "branchCode": "HMB",
    "SWIFT Code": "PHCBPHMB",
    "Bank Name": "BANGKO SENTRAL NG PILIPINAS",
    "Address": "",
    "City": "CITY OF MANILA",
    "Branch": "",
    "Postcode": "",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "PHCB",
    "bankCode": "PH",
    "branchCode": "HMA",
    "SWIFT Code": "PHCBPHMA",
    "Bank Name": "BANGKO SENTRAL NG PILIPINAS",
    "Address": "",
    "City": "CITY OF MANILA",
    "Branch": "",
    "Postcode": "",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "PHCB",
    "bankCode": "PH",
    "branchCode": "HMD",
    "SWIFT Code": "PHCBPHMD",
    "Bank Name": "BANGKO SENTRAL NG PILIPINAS",
    "Address": "ROOM 301, CORNER PABLO CAMPO STREET, MABINI",
    "City": "CITY OF MANILA",
    "Branch": "",
    "Postcode": "1004",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "PHCB",
    "bankCode": "PH",
    "branchCode": "HMM",
    "SWIFT Code": "PHCBPHMM",
    "Bank Name": "BANGKO SENTRAL NG PILIPINAS",
    "Address": "ROOM 308, FLOOR 3, CBP 5 STOREY, BUILDING A. MABINI CORNER VITO CRUZ, STREETS",
    "City": "CITY OF MANILA",
    "Branch": "",
    "Postcode": "1004",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "PHCB",
    "bankCode": "PH",
    "branchCode": "HMC",
    "SWIFT Code": "PHCBPHMC",
    "Bank Name": "BANGKO SENTRAL NG PILIPINAS",
    "Address": "RM. 301, EDPC BUILDING, A. MABINI COR. P. OCAMPO, MALATE",
    "City": "CITY OF MANILA",
    "Branch": "",
    "Postcode": "1004",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "BKKB",
    "bankCode": "PH",
    "branchCode": "HMM",
    "SWIFT Code": "BKKBPHMM",
    "Bank Name": "BANGKOK BANK PUBLIC COMPANY LIMITED, MANILA BRANCH",
    "Address": "FLOOR 10, THE ENTERPRISE CENTER, TOWER 2 6766 AYALA AVENUE CORNER, PASEO DE R",
    "City": "CITY OF MAKATI",
    "Branch": "",
    "Postcode": "1200",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "BOFA",
    "bankCode": "PH",
    "branchCode": "H2X",
    "SWIFT Code": "BOFAPH2X",
    "Bank Name": "BANK OF AMERICA, N.A. MANILA",
    "Address": "UNIT 1001, FLOOR 10, ECOPRIME TOWER, 32 STREET CORNER 9TH AVENUE",
    "City": "CITY OF MAKATI",
    "Branch": "",
    "Postcode": "1226",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "BKCH",
    "bankCode": "PH",
    "branchCode": "HMM",
    "SWIFT Code": "BKCHPHMM",
    "Bank Name": "BANK OF CHINA (HONG KONG) LIMITED - MANILA BRANCH",
    "Address": "FLOOR 28, THE FINANCE CENTRE, 26 STREET CORNER 9TH AVENUE, BONIFACIO CITY",
    "City": "CITY OF TAGUIG",
    "Branch": "",
    "Postcode": "1200",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "BKCH",
    "bankCode": "PH",
    "branchCode": "RTS",
    "SWIFT Code": "BKCHPHMMRTS",
    "Bank Name": "BANK OF CHINA (HONG KONG) LIMITED - MANILA BRANCH",
    "Address": "FLOOR 28, THE FINANCE CENTRE, 26 STREET CORNER 9TH AVENUE",
    "City": "TAGUIG CITY",
    "Branch": "BANK OF CHINA LIMITED MANILA BRANCH RMB CLEARING CENTER",
    "Postcode": "",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "PABI",
    "bankCode": "PH",
    "branchCode": "HMM",
    "SWIFT Code": "PABIPHMM",
    "Bank Name": "BANK OF COMMERCE",
    "Address": "SAN MIGUEL PROPERTIES CENTRE (SMPC), 7 ST. FRANCIS STREET",
    "City": "CITY OF MANDALUYONG",
    "Branch": "",
    "Postcode": "1550",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "BOPI",
    "bankCode": "PH",
    "branchCode": "HMM",
    "SWIFT Code": "BOPIPHMM",
    "Bank Name": "BANK OF THE PHILIPPINE ISLANDS",
    "Address": "AYALA AVENUE CORNER PASEO DE ROXAS",
    "City": "CITY OF MAKATI",
    "Branch": "",
    "Postcode": "1226",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "BOPI",
    "bankCode": "PH",
    "branchCode": "TRY",
    "SWIFT Code": "BOPIPHMMTRY",
    "Bank Name": "BANK OF THE PHILIPPINE ISLANDS",
    "Address": "AYALA AVENUE COR PASEO DE ROXAS",
    "City": "CITY OF MAKATI",
    "Branch": "TREASURY GROUP",
    "Postcode": "1226",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "RURL",
    "bankCode": "PH",
    "branchCode": "HM2",
    "SWIFT Code": "RURLPHM2",
    "Bank Name": "BANKWAYS, INC. (A RURAL BANK)",
    "Address": "BANKWAYS BLDG, GOV. M. CUENCO AVENUE, SITIO BACA",
    "City": "CITY OF CEBU",
    "Branch": "",
    "Postcode": "6000",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "BOPB",
    "bankCode": "PH",
    "branchCode": "HMM",
    "SWIFT Code": "BOPBPHMM",
    "Bank Name": "BDO PRIVATE BANK INC.",
    "Address": "FLOOR M/2F, BDO EQUITABLE TOWER, 8751 AYALA AVENUE",
    "City": "CITY OF MAKATI",
    "Branch": "",
    "Postcode": "1226",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "BNOR",
    "bankCode": "PH",
    "branchCode": "HMM",
    "SWIFT Code": "BNORPHMM",
    "Bank Name": "BDO UNIBANK, INC.",
    "Address": "BDO CORPORATE CENTER, 7899 MAKATI AVENUE",
    "City": "CITY OF MAKATI",
    "Branch": "",
    "Postcode": "0726",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "BIUR",
    "bankCode": "PH",
    "branchCode": "HM2",
    "SWIFT Code": "BIURPHM2",
    "Bank Name": "BINAN RURAL BANK, INC.",
    "Address": "RC VICTORIA, M. MANABAT ST, BGY. SAN ANTONIO",
    "City": "CITY OF BINAN",
    "Branch": "",
    "Postcode": "4024",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "BNPA",
    "bankCode": "PH",
    "branchCode": "HMM",
    "SWIFT Code": "BNPAPHMM",
    "Bank Name": "BNP PARIBAS, MANILA OFFSHORE BRANCH",
    "Address": "FLOOR 30, PHILAMLIFE TOWER, 8767 PASEO DE ROXAS",
    "City": "CITY OF MAKATI",
    "Branch": "",
    "Postcode": "1262",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "CAMZ",
    "bankCode": "PH",
    "branchCode": "HM2",
    "SWIFT Code": "CAMZPHM2",
    "Bank Name": "CARD MRI RIZAL BANK, INC.",
    "Address": "CARD MRI BLDG, P. GUEVARRA ST. COR AGUIRRE ST",
    "City": "SANTA CRUZ",
    "Branch": "",
    "Postcode": "4009",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "UWCB",
    "bankCode": "PH",
    "branchCode": "HMM",
    "SWIFT Code": "UWCBPHMM",
    "Bank Name": "CATHAY UNITED BANK CO., LTD. MANILA BRANCH",
    "Address": "UNIT 1, FLOOR 15, TOWER 6789, 6789 AYALA AVENUE",
    "City": "CITY OF MAKATI",
    "Branch": "",
    "Postcode": "1206",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "CCBC",
    "bankCode": "PH",
    "branchCode": "HMM",
    "SWIFT Code": "CCBCPHMM",
    "Bank Name": "CHANG HWA COMMERCIAL BANK,LTD. MANILA BRANCH",
    "Address": "FLOOR 43, PHILAMLIFE TOWER, 8767 PASEO DE ROXAS",
    "City": "CITY OF MAKATI",
    "Branch": "",
    "Postcode": "1226",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "CHBK",
    "bankCode": "PH",
    "branchCode": "HMM",
    "SWIFT Code": "CHBKPHMM",
    "Bank Name": "CHINA BANKING CORPORATION",
    "Address": "CHINA BANKING CORPORATION BLDG, 8745 PASEO DE ROXAS CORNER VILLAR, STREET",
    "City": "CITY OF MAKATI",
    "Branch": "",
    "Postcode": "1226",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "CIPH",
    "bankCode": "PH",
    "branchCode": "HMM",
    "SWIFT Code": "CIPHPHMM",
    "Bank Name": "CIMB BANK PHILIPPINES INC.",
    "Address": "FLOOR 28, ORE CENTRAL TOWER, 31 9TH AVENUE CORNER, BONIFACIO GLOBAL CITY",
    "City": "CITY OF TAGUIG",
    "Branch": "",
    "Postcode": "1634",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "CIYC",
    "bankCode": "PH",
    "branchCode": "HM2",
    "SWIFT Code": "CIYCPHM2",
    "Bank Name": "CIS BAYAD CENTER, INC.",
    "Address": "BUSINESS SOLUTIONS CENTER, ORTIGAS AVE",
    "City": "CITY OF PASIG",
    "Branch": "",
    "Postcode": "1605",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "CITI",
    "bankCode": "PH",
    "branchCode": "CBU",
    "SWIFT Code": "CITIPHMXCBU",
    "Bank Name": "CITIBANK,N.A., MANILA BRANCH",
    "Address": "",
    "City": "CITY OF CEBU",
    "Branch": "",
    "Postcode": "6000",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "CITI",
    "bankCode": "PH",
    "branchCode": "TSU",
    "SWIFT Code": "CITIPHMXTSU",
    "Bank Name": "CITIBANK,N.A., MANILA BRANCH",
    "Address": "",
    "City": "CITY OF MANILA",
    "Branch": "IBG-TREASURY SERVICES UNIT",
    "Postcode": "1000",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "CITI",
    "bankCode": "PH",
    "branchCode": "HMX",
    "SWIFT Code": "CITIPHMX",
    "Bank Name": "CITIBANK,N.A., MANILA BRANCH",
    "Address": "CITI PLAZA, 34TH FORT BONIFACIO STREET",
    "City": "CITY OF TAGUIG",
    "Branch": "HEAD OFFICE",
    "Postcode": "1226",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "CUOB",
    "bankCode": "PH",
    "branchCode": "HM2",
    "SWIFT Code": "CUOBPHM2",
    "Bank Name": "COMMUNITY RURAL BANK OF ROMBLON (ROMBLON), INC",
    "Address": "BAGONG LIPUNAN STREET COR GOV PEREZ",
    "City": "CITY OF ROMBLON",
    "Branch": "",
    "Postcode": "5500",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "COYA",
    "bankCode": "PH",
    "branchCode": "HM2",
    "SWIFT Code": "COYAPHM2",
    "Bank Name": "COOPERATIVE BANK OF CAGAYAN",
    "Address": "COOPBANK BUILDING, DIVERSION ROAD",
    "City": "CITY OF TUGUEGARAO",
    "Branch": "",
    "Postcode": "3500",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "CTCB",
    "bankCode": "PH",
    "branchCode": "HMM",
    "SWIFT Code": "CTCBPHMM",
    "Bank Name": "CTBC BANK (PHILIPPINES) CORP.",
    "Address": "FLOOR 16-18, FORT LEGEND TOWERS, 31ST STREET CORNER 3RD AVENUE",
    "City": "CITY OF TAGUIG",
    "Branch": "",
    "Postcode": "1634",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "DEUT",
    "bankCode": "PH",
    "branchCode": "HMM",
    "SWIFT Code": "DEUTPHMM",
    "Bank Name": "DEUTSCHE BANK AG",
    "Address": "FLOOR 19, NET QUAD CENTER, 31ST STREET CORNER 4TH AVENUE, CRESCENT PARK WEST",
    "City": "CITY OF MANILA",
    "Branch": "",
    "Postcode": "1634",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "DBPH",
    "bankCode": "PH",
    "branchCode": "HMM",
    "SWIFT Code": "DBPHPHMM",
    "Bank Name": "DEVELOPMENT BANK OF THE PHILIPPINES",
    "Address": "CORNER GIL PUYAT AND MAKATI AVENUES",
    "City": "CITY OF MAKATI",
    "Branch": "",
    "Postcode": "1200",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "EWBC",
    "bankCode": "PH",
    "branchCode": "HMM",
    "SWIFT Code": "EWBCPHMM",
    "Bank Name": "EAST WEST BANKING CORPORATION",
    "Address": "6795 AYALA AVENUE COR, V.A. RUFINO, ST SALCEDO VILL",
    "City": "CITY OF MAKATI",
    "Branch": "",
    "Postcode": "1226",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "EAWR",
    "bankCode": "PH",
    "branchCode": "HM2",
    "SWIFT Code": "EAWRPHM2",
    "Bank Name": "EAST WEST RURAL BANK, INC.",
    "Address": "EAST WEST BANK BUILDING, 3-4 JP LAUREL AVE. COR. INIGO ST",
    "City": "CITY OF DAVAO",
    "Branch": "",
    "Postcode": "8000",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "EAGM",
    "bankCode": "PH",
    "branchCode": "HM2",
    "SWIFT Code": "EAGMPHM2",
    "Bank Name": "EASYPAY GLOBAL EMI CORP.",
    "Address": "ECO TOWER BLDG, COR 9TH AVE 32ND ST",
    "City": "CITY OF TAGUIG",
    "Branch": "",
    "Postcode": "1630",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "ECAS",
    "bankCode": "PH",
    "branchCode": "HM2",
    "SWIFT Code": "ECASPHM2",
    "Bank Name": "ECASHPAY ASIA INC",
    "Address": "UNIT 202, PACIFIC CENTURY TOWER, QUEZON AVENUE",
    "City": "CITY OF QUEZON",
    "Branch": "",
    "Postcode": "1103",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "FCBK",
    "bankCode": "PH",
    "branchCode": "HMM",
    "SWIFT Code": "FCBKPHMM",
    "Bank Name": "FIRST COMMERCIAL BANK, LTD., MANILA BRANCH",
    "Address": "FLOOR 20, TOWER 6789, 6789 AYALA AVENUE",
    "City": "CITY OF MAKATI",
    "Branch": "",
    "Postcode": "1206",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "GXCH",
    "bankCode": "PH",
    "branchCode": "HM2",
    "SWIFT Code": "GXCHPHM2",
    "Bank Name": "G-XCHANGE, INC.",
    "Address": "FLOOR 8, W GLOBAL CENTER, 30 STREET CORNER 9TH AVENUE",
    "City": "CITY OF TAGUIG",
    "Branch": "",
    "Postcode": "1637",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "PPSF",
    "bankCode": "PH",
    "branchCode": "HM2",
    "SWIFT Code": "PPSFPHM2",
    "Bank Name": "PPS-PEPP FINANCIAL SERVICES CORPORATION",
    "Address": "170 RIZAL AVENUE, MASIKAP",
    "City": "CITY OF PUERTO PRINCESA",
    "Branch": "",
    "Postcode": "5300",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "POUA",
    "bankCode": "PH",
    "branchCode": "HM2",
    "SWIFT Code": "POUAPHM2",
    "Bank Name": "PROVIDENCE RURAL BANK INC.",
    "Address": "NATIONAL HIGHWAY CORNER AGLIPAY ST",
    "City": "CITY OF TUGUEGARAO",
    "Branch": "",
    "Postcode": "3510",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "QWBS",
    "bankCode": "PH",
    "branchCode": "HM2",
    "SWIFT Code": "QWBSPHM2",
    "Bank Name": "QWIKWIRE BILLING SYSTEMS INC",
    "Address": "FLOOR 5TH, GREENBELT MANSION, 106 PEREA",
    "City": "CITY OF MAKATI",
    "Branch": "",
    "Postcode": "1229",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "RBRU",
    "bankCode": "PH",
    "branchCode": "HM2",
    "SWIFT Code": "RBRUPHM2",
    "Bank Name": "RBT BANK, INC., A RURAL BANK",
    "Address": "RIZAL STREET",
    "City": "CITY OF CAGAYAN DE ORO",
    "Branch": "",
    "Postcode": "9012",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "RCBC",
    "bankCode": "PH",
    "branchCode": "HMM",
    "SWIFT Code": "RCBCPHMM",
    "Bank Name": "RIZAL COMMERCIAL BANKING CORPORATION",
    "Address": "6819 AYALA AVE. COR SENATOR GIL, PUYAT AYALA AVENUE",
    "City": "CITY OF MANILA",
    "Branch": "",
    "Postcode": "0727",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "ROBP",
    "bankCode": "PH",
    "branchCode": "HMQ",
    "SWIFT Code": "ROBPPHMQ",
    "Bank Name": "ROBINSONS BANK CORPORATION",
    "Address": "129 EDSA CORNER ORTIGAS",
    "City": "CITY OF QUEZON",
    "Branch": "",
    "Postcode": "1600",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "RUBC",
    "bankCode": "PH",
    "branchCode": "HM2",
    "SWIFT Code": "RUBCPHM2",
    "Bank Name": "RURAL BANK OF BACOLOD CITY, INC.",
    "Address": "RBBC BUILDING, 74 76 NARRA AVE CSC",
    "City": "CITY OF BACOLO",
    "Branch": "",
    "Postcode": "6100",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "RUBU",
    "bankCode": "PH",
    "branchCode": "HM2",
    "SWIFT Code": "RUBUPHM2",
    "Bank Name": "RURAL BANK OF BAUANG INC",
    "Address": "COR FLORENDO ST CENTRAL EAST",
    "City": "CITY OF SAN FERNANDO",
    "Branch": "",
    "Postcode": "2501",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "RUBY",
    "bankCode": "PH",
    "branchCode": "HM2",
    "SWIFT Code": "RUBYPHM2",
    "Bank Name": "RURAL BANK OF BAY, INC.",
    "Address": "BAY, RIZAL AVENUE CORNER A. BONIFACIO ST, SAN NICOLAS",
    "City": "CITY OF SAN PABLO",
    "Branch": "",
    "Postcode": "4033",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "RUHL",
    "bankCode": "PH",
    "branchCode": "HM2",
    "SWIFT Code": "RUHLPHM2",
    "Bank Name": "RURAL BANK OF HILONGOS (LEYTE), INC",
    "Address": "R.V. VILLAFLORES STREET, BARANGAY CENTRAL",
    "City": "CITY OF TACLOBAN",
    "Branch": "",
    "Postcode": "6524",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "RUIE",
    "bankCode": "PH",
    "branchCode": "HM2",
    "SWIFT Code": "RUIEPHM2",
    "Bank Name": "RURAL BANK OF ITOGON (BENGUET), INC",
    "Address": "KM 5 PICO LA TRINIDAD",
    "City": "CITY OF BAGUIO",
    "Branch": "",
    "Postcode": "2601",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "RUPZ",
    "bankCode": "PH",
    "branchCode": "HM2",
    "SWIFT Code": "RUPZPHM2",
    "Bank Name": "RURAL BANK OF LA PAZ, INC.",
    "Address": "CORNER J. CATALAN AND BURGOS STS, SAN ISIDRO, LA PAZ",
    "City": "CITY OF TARLAC",
    "Branch": "",
    "Postcode": "2314",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "RLSU",
    "bankCode": "PH",
    "branchCode": "HM2",
    "SWIFT Code": "RLSUPHM2",
    "Bank Name": "RURAL BANK OF LANUZA (SURIGAO DEL SUR), INC.",
    "Address": "URBIZTONDO COR. ARREZA ST, MAGOSILOM",
    "City": "CITY OF BISLIG",
    "Branch": "",
    "Postcode": "8317",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "RUMT",
    "bankCode": "PH",
    "branchCode": "HM2",
    "SWIFT Code": "RUMTPHM2",
    "Bank Name": "RURAL BANK OF MONTALBAN, INC.",
    "Address": "261 J.P. RIZAL AVENUE",
    "City": "CITY OF ANTIPOLO",
    "Branch": "",
    "Postcode": "1860",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "RUPP",
    "bankCode": "PH",
    "branchCode": "HM2",
    "SWIFT Code": "RUPPPHM2",
    "Bank Name": "RURAL BANK OF PORAC (PAMP), INC.",
    "Address": "PRISER BUILDING, COR FLORA AVE. SANTO ROSARIO ST",
    "City": "CITY OF ANGELES",
    "Branch": "",
    "Postcode": "2009",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "RURU",
    "bankCode": "PH",
    "branchCode": "HM2",
    "SWIFT Code": "RURUPHM2",
    "Bank Name": "RURAL BANK OF ROSARIO (LA UNION)INC",
    "Address": "POBLACION EAST",
    "City": "CITY OF SAN FERNANDO",
    "Branch": "",
    "Postcode": "2506",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "RUSY",
    "bankCode": "PH",
    "branchCode": "HM2",
    "SWIFT Code": "RUSYPHM2",
    "Bank Name": "RURAL BANK OF SAGAY, INC.",
    "Address": "NATIONAL HIGHWAY, POBLACION II",
    "City": "CITY OF SAGAY",
    "Branch": "",
    "Postcode": "6122",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "RSMS",
    "bankCode": "PH",
    "branchCode": "HM2",
    "SWIFT Code": "RSMSPHM2",
    "Bank Name": "RURAL BANK OF SAN MATEO (ISABELA) INC",
    "Address": "3 NATIONAL HIGHWAY, BARANGAY,SAN MATEO, ISABELA",
    "City": "CITY OF TUGUEGARAO",
    "Branch": "",
    "Postcode": "3318",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "RSNA",
    "bankCode": "PH",
    "branchCode": "HM2",
    "SWIFT Code": "RSNAPHM2",
    "Bank Name": "RURAL BANK OF SAN NARCISO, INC.",
    "Address": "BARANGAY LIBERTAD, FONTIMAYOR STREET, SAN NARCISO",
    "City": "ZAMBALES",
    "Branch": "",
    "Postcode": "2205",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "RSMC",
    "bankCode": "PH",
    "branchCode": "HM2",
    "SWIFT Code": "RSMCPHM2",
    "Bank Name": "RURAL BANK OF SANCHEZ MIRA CAGAYAN INC.",
    "Address": "LAGASCA ST. COR. MARZAN ST",
    "City": "CITY OF TUGUEGARAO",
    "Branch": "",
    "Postcode": "3500",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "RUST",
    "bankCode": "PH",
    "branchCode": "HM2",
    "SWIFT Code": "RUSTPHM2",
    "Bank Name": "RURAL BANK OF SILAY CITY, INC.",
    "Address": "CORNER EUSEBIO AND G. GAMBOA STREET",
    "City": "SILAY CITY",
    "Branch": "",
    "Postcode": "6116",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "RUSN",
    "bankCode": "PH",
    "branchCode": "HM2",
    "SWIFT Code": "RUSNPHM2",
    "Bank Name": "RURAL BANK OF SOLANO (N.V.),INC.",
    "Address": "MAHARLIKA HIGHWAY, POBLACION SOUTH",
    "City": "CITY OF SOLANO",
    "Branch": "",
    "Postcode": "3709",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "LAUI",
    "bankCode": "PH",
    "branchCode": "HM2",
    "SWIFT Code": "LAUIPHM2",
    "Bank Name": "SEABANK PHILIPPINES",
    "Address": "32 RIZAL STREET",
    "City": "SANTA CRUZ",
    "Branch": "",
    "Postcode": "4023",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "SETC",
    "bankCode": "PH",
    "branchCode": "HMM",
    "SWIFT Code": "SETCPHMM",
    "Bank Name": "SECURITY BANK CORPORATION",
    "Address": "SECURITY BANK CENTRE, 6776 AYALA AVENUE",
    "City": "CITY OF MAKATI",
    "Branch": "",
    "Postcode": "0719",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "SHBK",
    "bankCode": "PH",
    "branchCode": "HMM",
    "SWIFT Code": "SHBKPHMM",
    "Bank Name": "SHINHAN BANK MANILA BRANCH",
    "Address": "21, 25-26 BONIFACIO GLOBAL, BONIFACIO SOUTH",
    "City": "CITY OF TAGUIG",
    "Branch": "",
    "Postcode": "1637",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "SHPH",
    "bankCode": "PH",
    "branchCode": "HM2",
    "SWIFT Code": "SHPHPHM2",
    "Bank Name": "SHOPEEPAY PHILIPPINES, INC.",
    "Address": "FLOOR 37, NET PARK BUILDING, 5TH AVENUE, BONIFACIO GLOBAL CITY",
    "City": "CITY OF TAGUIG",
    "Branch": "",
    "Postcode": "1635",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "SPEY",
    "bankCode": "PH",
    "branchCode": "HM2",
    "SWIFT Code": "SPEYPHM2",
    "Bank Name": "SPEEDYPAY INC.",
    "Address": "UNIT 2002-2003, FLOOR 20, ANTEL, GLOBAL CORPORATE CENTER 3 JULIA, VARGAS AVENUE ORTIGAS BUSINESS, DISTRICT",
    "City": "CITY OF PASIG",
    "Branch": "",
    "Postcode": "1605",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "SCBL",
    "bankCode": "PH",
    "branchCode": "HMM",
    "SWIFT Code": "SCBLPHMM",
    "Bank Name": "STANDARD CHARTERED BANK",
    "Address": "THE SKY PLAZA BUILDING, 6788 AYALA AVENUE",
    "City": "CITY OF MAKATI",
    "Branch": "",
    "Postcode": "1226",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "SCBL",
    "bankCode": "PH",
    "branchCode": "EQI",
    "SWIFT Code": "SCBLPHMMEQI",
    "Bank Name": "STANDARD CHARTERED BANK",
    "Address": "THE SKY PLAZA BUILDING, 6788 AYALA AVENUE",
    "City": "CITY OF MAKATI",
    "Branch": "CUSTODIAL DEPARTMENT",
    "Postcode": "1226",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "SRCP",
    "bankCode": "PH",
    "branchCode": "HM2",
    "SWIFT Code": "SRCPPHM2",
    "Bank Name": "STARPAY CORPORATION",
    "Address": "FLOOR 402, TCI TOWER 61 WEST, CAPITOL DRIVE COR STELLA MARIS",
    "City": "CITY OF PASIG",
    "Branch": "",
    "Postcode": "1603",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "STLA",
    "bankCode": "PH",
    "branchCode": "H22",
    "SWIFT Code": "STLAPH22",
    "Bank Name": "STERLING BANK OF ASIA INC.(A SAVINGS BANK)",
    "Address": "FLOOR 1ST, STERLING BANK CORPORATE, CENTER 8004 ORTIGAS AVENUE, GREENHILLS",
    "City": "CITY OF SAN JUAN",
    "Branch": "",
    "Postcode": "1500",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "SMBC",
    "bankCode": "PH",
    "branchCode": "HMM",
    "SWIFT Code": "SMBCPHMM",
    "Bank Name": "SUMITOMO MITSUI BANKING CORPORATION MANILA BRANCH",
    "Address": "TOWER ONE AND EXCHANGE PLAZA, AYALA AVENUE, AYALA TRIANGLE",
    "City": "CITY OF MAKATI",
    "Branch": "",
    "Postcode": "1226",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "TAGC",
    "bankCode": "PH",
    "branchCode": "HM2",
    "SWIFT Code": "TAGCPHM2",
    "Bank Name": "TAGCASH LTD. INC.",
    "Address": "FLOOR 2108, 88 CORPORATE CENTER, 141 VALERO ST, SALCEDO VILLAGE",
    "City": "CITY OF MAKATI",
    "Branch": "",
    "Postcode": "1200",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "TACB",
    "bankCode": "PH",
    "branchCode": "HMM",
    "SWIFT Code": "TACBPHMM",
    "Bank Name": "TAIWAN COOPERATIVE BANK MANILA OFFSHORE BANKING BRANCH",
    "Address": "FLOOR 26/F, BDO TOWERS VALERO, 8741 PASEO DE ROXAS",
    "City": "CITY OF MANILA",
    "Branch": "",
    "Postcode": "1226",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "TAYO",
    "bankCode": "PH",
    "branchCode": "HM2",
    "SWIFT Code": "TAYOPHM2",
    "Bank Name": "TAYOCASH INC.",
    "Address": "2603, FLOOR 26, ANTEL GLOBAL, CORPORATE CENTER DONA JULIA VARGAS, AVENUE",
    "City": "CITY OF PASIG",
    "Branch": "",
    "Postcode": "1605",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "HSBC",
    "bankCode": "PH",
    "branchCode": "CEB",
    "SWIFT Code": "HSBCPHMMCEB",
    "Bank Name": "THE HONGKONG AND SHANGHAI BANKING CORPORATION LTD - PHILIPPINE BRANCH",
    "Address": "14 JUANA OSMENA STREET",
    "City": "CITY OF CEBU",
    "Branch": "CEBU BRANCH",
    "Postcode": "6000",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "HSBC",
    "bankCode": "PH",
    "branchCode": "TRY",
    "SWIFT Code": "HSBCPHMMTRY",
    "Bank Name": "THE HONGKONG AND SHANGHAI BANKING CORPORATION LTD - PHILIPPINE BRANCH",
    "Address": "",
    "City": "CITY OF MANILA",
    "Branch": "MNL TREASURY DEPARTMENT",
    "Postcode": "1000",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "HSBC",
    "bankCode": "PH",
    "branchCode": "SEC",
    "SWIFT Code": "HSBCPHMMSEC",
    "Bank Name": "THE HONGKONG AND SHANGHAI BANKING CORPORATION LTD - PHILIPPINE BRANCH",
    "Address": "PHILIPPINE STOCK EXCHANGE CENTRE, WEST TOWER FLOOR 33, EXCHANGE ROAD ORTIGAS CENTRE, PASIG CITY",
    "City": "CITY OF PASIG",
    "Branch": "CUSTODY AND CLEARING",
    "Postcode": "1600",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "HSBC",
    "bankCode": "PH",
    "branchCode": "HMM",
    "SWIFT Code": "HSBCPHMM",
    "Bank Name": "THE HONGKONG AND SHANGHAI BANKING CORPORATION LTD - PHILIPPINE BRANCH",
    "Address": "HSBC CENTRE, 3058 FIFTH AVENUE WEST, BONIFACIO GLOBAL CITY",
    "City": "CITY OF TAGUIG",
    "Branch": "",
    "Postcode": "1634",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "MFCT",
    "bankCode": "PH",
    "branchCode": "HMM",
    "SWIFT Code": "MFCTPHMM",
    "Bank Name": "THE MANUFACTURERS LIFE INSURANCE CO. (PHILS.), INC.",
    "Address": "6801 AYALA AVENUE",
    "City": "CITY OF MAKATI",
    "Branch": "",
    "Postcode": "1226",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "TOKT",
    "bankCode": "PH",
    "branchCode": "HM2",
    "SWIFT Code": "TOKTPHM2",
    "Bank Name": "TOKTOKWALLET INC.",
    "Address": "2021 EDISON STREET",
    "City": "CITY OF MAKATI",
    "Branch": "",
    "Postcode": "1234",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "TODG",
    "bankCode": "PH",
    "branchCode": "HM2",
    "SWIFT Code": "TODGPHM2",
    "Bank Name": "TONIK DIGITAL BANK, INC.",
    "Address": "605 B, FLOOR 6, ESTANCIA OFFICES, MERALCO AVENUE, ORANBO",
    "City": "CITY OF PASIG",
    "Branch": "",
    "Postcode": "1605",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "TOPJ",
    "bankCode": "PH",
    "branchCode": "HM2",
    "SWIFT Code": "TOPJPHM2",
    "Bank Name": "TOPJUAN TECH CORPORATION",
    "Address": "UNIT 411 , FLOOR 4, FIRST, INTRAMUROS BF CONDOMINIUM ADUANA ST",
    "City": "CITY OF MANILA",
    "Branch": "",
    "Postcode": "1002",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "TRXP",
    "bankCode": "PH",
    "branchCode": "HM2",
    "SWIFT Code": "TRXPPHM2",
    "Bank Name": "TRAXION PAY INC",
    "Address": "FLOOR 10, TAIPAN PLACE, EMERALD AVE",
    "City": "CITY OF PASIG",
    "Branch": "",
    "Postcode": "1605",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "UBPH",
    "bankCode": "PH",
    "branchCode": "HMM",
    "SWIFT Code": "UBPHPHMM",
    "Bank Name": "UNION BANK OF THE PHILIPPINES",
    "Address": "UNIONBANK PLAZA MERALCO AVE. COR., ONYX AND SAPPHIRE STS ORTIGAS, CENTRE",
    "City": "CITY OF PASIG",
    "Branch": "",
    "Postcode": "1605",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "UNOD",
    "bankCode": "PH",
    "branchCode": "HM2",
    "SWIFT Code": "UNODPHM2",
    "Bank Name": "UNIONDIGITAL BANK INC.",
    "Address": "UNIONBANK PLAZA, 41 MERALCO COR ONYX AND SAPPHIRE RO",
    "City": "CITY OF PASIG",
    "Branch": "",
    "Postcode": "",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "UOVB",
    "bankCode": "PH",
    "branchCode": "HMM",
    "SWIFT Code": "UOVBPHMM",
    "Bank Name": "UNITED OVERSEAS BANK LIMITED - MANILA BRANCH",
    "Address": "FLOOR 17, PACIFIC STAR BLDG, SEN. GIL PUYAT AVE",
    "City": "CITY OF MAKATI",
    "Branch": "",
    "Postcode": "1225",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "UNRP",
    "bankCode": "PH",
    "branchCode": "HMM",
    "SWIFT Code": "UNRPPHMM",
    "Bank Name": "UNIVERSAL ROBINA CORPORATION",
    "Address": "FLOOR 8, TERA TOWER, E. RODRIGUEZ JR. AVE. (C5 ROAD, BRIDGETOWN",
    "City": "CITY OF QUEZON",
    "Branch": "",
    "Postcode": "1110",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "UNOB",
    "bankCode": "PH",
    "branchCode": "HM2",
    "SWIFT Code": "UNOBPHM2",
    "Bank Name": "UNOBANK INC.",
    "Address": "FLOOR 20, THE FINANCE CENTER, 26TH ST CORNER 9TH AVE, BONIFACIO GLOBAL CITY",
    "City": "CITY OF TAGUIG",
    "Branch": "",
    "Postcode": "1630",
    "Country": "Philippines",
    "Connection": "Active"
  },
  {
    "countryCode": "USME",
    "bankCode": "PH",
    "branchCode": "HM2",
    "SWIFT Code": "USMEPHM2",
    "Bank Name": "USSC MONEY SERVICES INC",
    "Address": "USSC BUILDING, 711 EDSA, CUBAO",
    "City": "CITY OF QUEZON",
    "Branch": "",
    "Postcode": "1109",
    "Country": "Philippines",
    "Connection": "Active"
  }
]
module.exports = philippines
