const poland = [
  {
    "bankCode": "EBOS",
    "countryCode": "PL",
    "branchCode": "ZAA",
    "SWIFT Code": "EBOSPLPWZAA",
    "Bank Name": "BANK OCHRONY SRODOWISKA S.A.",
    "Address": "",
    "City": "ZAMOSC",
    "Branch": "",
    "Postcode": "",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "BKCH",
    "countryCode": "PL",
    "branchCode": "LPX",
    "SWIFT Code": "BKCHPLPX",
    "Bank Name": "BANK OF CHINA (EUROPE) S.A. POLAND BRANCH",
    "Address": "UL.ZIELNA 41/43",
    "City": "WARSZAWA",
    "Branch": "",
    "Postcode": "00-108",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "PKOP",
    "countryCode": "PL",
    "branchCode": "KRA",
    "SWIFT Code": "PKOPPLPWKRA",
    "Bank Name": "BANK POLSKA KASA OPIEKI SA - BANK PEKAO SA",
    "Address": "JOSEPHA CONRADA STR 37",
    "City": "KRAKOW",
    "Branch": "KRAKOW REGIONAL OFFICE",
    "Postcode": "31-357",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "PKOP",
    "countryCode": "PL",
    "branchCode": "SMK",
    "SWIFT Code": "PKOPPLPWSMK",
    "Bank Name": "BANK POLSKA KASA OPIEKI SA - BANK PEKAO SA",
    "Address": "WOLOSKA 18, FLOOR V",
    "City": "WARSZAWA",
    "Branch": "BIURO MAKLERSKIE PEKAO",
    "Postcode": "02-675",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "PKOP",
    "countryCode": "PL",
    "branchCode": "CUS",
    "SWIFT Code": "PKOPPLPWCUS",
    "Bank Name": "BANK POLSKA KASA OPIEKI SA - BANK PEKAO SA",
    "Address": "ZUBRA 1, FLOOR 9",
    "City": "WARSZAWA",
    "Branch": "CUSTODY",
    "Postcode": "01-066",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "PKOP",
    "countryCode": "PL",
    "branchCode": "LPW",
    "SWIFT Code": "PKOPPLPW",
    "Bank Name": "BANK POLSKA KASA OPIEKI SA - BANK PEKAO SA",
    "Address": "ZUBRA 1",
    "City": "WARSZAWA",
    "Branch": "HEAD OFFICE",
    "Postcode": "01-066",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "POLU",
    "countryCode": "PL",
    "branchCode": "LPR",
    "SWIFT Code": "POLUPLPR",
    "Bank Name": "BANK POLSKIEJ SPOLDZIELCZOSCI SPOLKA AKCYJNA",
    "Address": "UL. GRZYBOWSKA 81",
    "City": "WARSZAWA",
    "Branch": "",
    "Postcode": "00-844",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "SRZK",
    "countryCode": "PL",
    "branchCode": "LPK",
    "SWIFT Code": "SRZKPLPK",
    "Bank Name": "BANK SPOLDZIELCZY RZEMIOSLA W KRAKOWIE",
    "Address": "DUNAJEWSKIEGO 7",
    "City": "KRAKOW",
    "Branch": "",
    "Postcode": "31-133",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "SPBO",
    "countryCode": "PL",
    "branchCode": "LPW",
    "SWIFT Code": "SPBOPLPW",
    "Bank Name": "BANK SPOLDZIELCZY W BRODNICY",
    "Address": "KAMIONKA 27",
    "City": "BRODNICA",
    "Branch": "",
    "Postcode": "87-300",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "SPBC",
    "countryCode": "PL",
    "branchCode": "LPP",
    "SWIFT Code": "SPBCPLPP",
    "Bank Name": "BANK SPOLDZIELCZY W BYDGOSZCZY",
    "Address": "KOLLATAJA 8",
    "City": "BYDGOSZCZ",
    "Branch": "",
    "Postcode": "85-080",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "PPAB",
    "countryCode": "PL",
    "branchCode": "LPK",
    "SWIFT Code": "PPABPLPK",
    "Bank Name": "BNP PARIBAS BANK POLSKA S.A.",
    "Address": "KASPRZAKA STREET 2",
    "City": "WARSZAWA",
    "Branch": "",
    "Postcode": "01-211",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "BNPA",
    "countryCode": "PL",
    "branchCode": "LPX",
    "SWIFT Code": "BNPAPLPX",
    "Bank Name": "BNP PARIBAS S.A. BRANCH IN POLAND",
    "Address": "UL. WRONIA 31",
    "City": "WARSZAWA",
    "Branch": "",
    "Postcode": "00-846",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "PARB",
    "countryCode": "PL",
    "branchCode": "LPX",
    "SWIFT Code": "PARBPLPX",
    "Bank Name": "BNP PARIBAS SECURITIES POLAND",
    "Address": "UL. WRONIA 31",
    "City": "WARSZAWA",
    "Branch": "",
    "Postcode": "00-846",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "BONP",
    "countryCode": "PL",
    "branchCode": "LP9",
    "SWIFT Code": "BONPPLP9",
    "Bank Name": "BONDSPOT S.A.",
    "Address": "KSIAZECA 4",
    "City": "WARSZAWA",
    "Branch": "",
    "Postcode": "00-498",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "FBPL",
    "countryCode": "PL",
    "branchCode": "LPW",
    "SWIFT Code": "FBPLPLPW",
    "Bank Name": "CA AUTO BANK SPA SPOLKA AKCYJNA ODDZIAL W POLSCE",
    "Address": "AL. WYSCIGOWA 6",
    "City": "WARSZAWA",
    "Branch": "",
    "Postcode": "02-681",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "CAIX",
    "countryCode": "PL",
    "branchCode": "LPW",
    "SWIFT Code": "CAIXPLPW",
    "Bank Name": "CAIXABANK, S.A. (SPOLKA AKCYJNA) ODDZIAL W POLSCE",
    "Address": "UL. PROSTA 51",
    "City": "WARSZAWA",
    "Branch": "",
    "Postcode": "00-838",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "PCBC",
    "countryCode": "PL",
    "branchCode": "LPW",
    "SWIFT Code": "PCBCPLPW",
    "Bank Name": "CHINA CONSTRUCTION BANK(EUROPE)WARSAW BRANCH",
    "Address": "WARSAW FINANCIAL CENTER, UL.EMILII PLATER 53, FLOOR 11",
    "City": "WARSZAWA",
    "Branch": "",
    "Postcode": "00-113",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "CINK",
    "countryCode": "PL",
    "branchCode": "LPZ",
    "SWIFT Code": "CINKPLPZ",
    "Bank Name": "CINKCIARZ.PL SP. Z O.O.",
    "Address": "WROCLAWSKA 17B",
    "City": "ZIELONA GORA",
    "Branch": "",
    "Postcode": "65-427",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "CONP",
    "countryCode": "PL",
    "branchCode": "LPW",
    "SWIFT Code": "CONPPLPW",
    "Bank Name": "CONOTOXIA SP. Z O.O.",
    "Address": "WROCLAWSKA 17B",
    "City": "ZIELONA GORA",
    "Branch": "",
    "Postcode": "65-427",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "AGRI",
    "countryCode": "PL",
    "branchCode": "LPR",
    "SWIFT Code": "AGRIPLPR",
    "Bank Name": "CREDIT AGRICOLE BANK POLSKA S.A.",
    "Address": "UL. LEGNICKA 48 C-D",
    "City": "WROCLAW",
    "Branch": "",
    "Postcode": "54-202",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "DABA",
    "countryCode": "PL",
    "branchCode": "LPW",
    "SWIFT Code": "DABAPLPW",
    "Bank Name": "DANSKE BANK A/S S.A. ODZIAL W POLSCE",
    "Address": "WSPOLNA 70",
    "City": "WARSZAWA",
    "Branch": "",
    "Postcode": "00-687",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "DEUT",
    "countryCode": "PL",
    "branchCode": "LPX",
    "SWIFT Code": "DEUTPLPX",
    "Bank Name": "DEUTSCHE BANK POLSKA S.A.",
    "Address": "FOCUS BUILDING, AL. ARMII LUDOWEJ 26",
    "City": "WARSZAWA",
    "Branch": "",
    "Postcode": "00-609",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "MHBF",
    "countryCode": "PL",
    "branchCode": "LPW",
    "SWIFT Code": "MHBFPLPW",
    "Bank Name": "DNB BANK POLSKA S.A.",
    "Address": "CROWN SQUARE, PRZYOKOPOWA 31, FLOOR 9",
    "City": "WARSZAWA",
    "Branch": "",
    "Postcode": "01-208",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "FESK",
    "countryCode": "PL",
    "branchCode": "LP2",
    "SWIFT Code": "FESKPLP2",
    "Bank Name": "FENIGE SPOLKA AKCYJNA",
    "Address": "PROMIENNA 38/1",
    "City": "WARSZAWA",
    "Branch": "",
    "Postcode": "03-672",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "FNTM",
    "countryCode": "PL",
    "branchCode": "LP2",
    "SWIFT Code": "FNTMPLP2",
    "Bank Name": "FINTECOM SP. Z O.O.",
    "Address": "MARSZALKA JOZEFA PILSUDSKIEGO 45",
    "City": "KOSZALIN",
    "Branch": "",
    "Postcode": "75-502",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "GUAV",
    "countryCode": "PL",
    "branchCode": "LPP",
    "SWIFT Code": "GUAVPLPP",
    "Bank Name": "GUAVAPAY POLAND SPOLKA Z OGRANICZONA ODPOWIEDZIALNOSCIA",
    "Address": "SW. MIKOLAJA 8/11",
    "City": "WROCLAW",
    "Branch": "",
    "Postcode": "50-125",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "ESSI",
    "countryCode": "PL",
    "branchCode": "LPX",
    "SWIFT Code": "ESSIPLPX",
    "Bank Name": "HAITONG BANK S.A., SPOLKA AKCYJNA ODDZIAL W POLSCE",
    "Address": "WEST LUMEN BULDING, ZLOTA STREET 59, FLOOR V",
    "City": "WARSZAWA",
    "Branch": "",
    "Postcode": "00-120",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "HSBC",
    "countryCode": "PL",
    "branchCode": "LPS",
    "SWIFT Code": "HSBCPLPS",
    "Bank Name": "HSBC CONTINENTAL EUROPE (SA) ODDZIAL W POLSCE",
    "Address": "RONDO ONZ 1",
    "City": "WARSZAWA",
    "Branch": "",
    "Postcode": "00-124",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "HSBC",
    "countryCode": "PL",
    "branchCode": "LPW",
    "SWIFT Code": "HSBCPLPW",
    "Bank Name": "HSBC CONTINENTAL EUROPE (SA) ODDZIAL W POLSCE",
    "Address": "RONDO ONZ 1",
    "City": "WARSZAWA",
    "Branch": "",
    "Postcode": "00-124",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "ICBK",
    "countryCode": "PL",
    "branchCode": "LPW",
    "SWIFT Code": "ICBKPLPW",
    "Bank Name": "ICBC POLAND BRANCH",
    "Address": "PLAC TRZECH KRZYZY 18",
    "City": "WARSZAWA",
    "Branch": "",
    "Postcode": "00-499",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "IGTR",
    "countryCode": "PL",
    "branchCode": "LPW",
    "SWIFT Code": "IGTRPLPW",
    "Bank Name": "IGORIA TRADE S.A.",
    "Address": "UL. PULAWSKA 111A, FLOOR 5",
    "City": "WARSZAWA",
    "Branch": "",
    "Postcode": "02-707",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "INGB",
    "countryCode": "PL",
    "branchCode": "LPH",
    "SWIFT Code": "INGBPLPH",
    "Bank Name": "ING BANK HIPOTECZNY S.A.",
    "Address": "CHORZOWSKA 50",
    "City": "KATOWICE",
    "Branch": "",
    "Postcode": "40-101",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "INGB",
    "countryCode": "PL",
    "branchCode": "LPW",
    "SWIFT Code": "INGBPLPW",
    "Bank Name": "ING BANK SLASKI SA",
    "Address": "UL. SOKOLSKA 34",
    "City": "KATOWICE",
    "Branch": "",
    "Postcode": "40-086",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "BCIT",
    "countryCode": "PL",
    "branchCode": "LPW",
    "SWIFT Code": "BCITPLPW",
    "Bank Name": "INTESA SANPAOLO SPA",
    "Address": "CENTRUM GIELDOWE, TOWER C, UL. KSIAZECA 4, FLOOR 5",
    "City": "WARSZAWA",
    "Branch": "",
    "Postcode": "00-498",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "IPAG",
    "countryCode": "PL",
    "branchCode": "LPL",
    "SWIFT Code": "IPAGPLPL",
    "Bank Name": "IPAGOO LLP, SPOLKA PARTNERSKA ODDZIAL",
    "Address": "HENRYKA SIENKIEWICZA 82/84, FLOOR 3",
    "City": "LODZ",
    "Branch": "",
    "Postcode": "90-318",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "KCCP",
    "countryCode": "PL",
    "branchCode": "ASI",
    "SWIFT Code": "KCCPPLPWASI",
    "Bank Name": "KDPW CCP",
    "Address": "",
    "City": "WARSZAWA",
    "Branch": "",
    "Postcode": "",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "KCCP",
    "countryCode": "PL",
    "branchCode": "OTC",
    "SWIFT Code": "KCCPPLPWOTC",
    "Bank Name": "KDPW CCP",
    "Address": "",
    "City": "WARSZAWA",
    "Branch": "",
    "Postcode": "",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "KCCP",
    "countryCode": "PL",
    "branchCode": "LPW",
    "SWIFT Code": "KCCPPLPW",
    "Bank Name": "KDPW CCP",
    "Address": "KSIAZECA 4",
    "City": "WARSZAWA",
    "Branch": "",
    "Postcode": "00-498",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "KDPW",
    "countryCode": "PL",
    "branchCode": "LPW",
    "SWIFT Code": "KDPWPLPW",
    "Bank Name": "KDPW S.A.",
    "Address": "UL. KSIAZECA 4",
    "City": "WARSZAWA",
    "Branch": "",
    "Postcode": "00-498",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "EKIR",
    "countryCode": "PL",
    "branchCode": "LPD",
    "SWIFT Code": "EKIRPLPD",
    "Bank Name": "KRAJOWA IZBA ROZLICZENIOWA S.A. (KIR S.A.)",
    "Address": "RTM. W. PILECKIEGO 65",
    "City": "WARSZAWA",
    "Branch": "",
    "Postcode": "02-781",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "EKIR",
    "countryCode": "PL",
    "branchCode": "LPW",
    "SWIFT Code": "EKIRPLPW",
    "Bank Name": "KRAJOWA IZBA ROZLICZENIOWA S.A. (KIR S.A.)",
    "Address": "PILECKIEGO ST",
    "City": "WARSZAWA",
    "Branch": "",
    "Postcode": "02-781",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "SKOK",
    "countryCode": "PL",
    "branchCode": "LPW",
    "SWIFT Code": "SKOKPLPW",
    "Bank Name": "KRAJOWA SPOLDZIELCZA KASA OSZCZEDNOSCIOWO-KREDYTOWA",
    "Address": "WLADYSLAWA IV 22",
    "City": "SOPOT",
    "Branch": "",
    "Postcode": "81-743",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "KRSP",
    "countryCode": "PL",
    "branchCode": "LPK",
    "SWIFT Code": "KRSPPLPK",
    "Bank Name": "KRAKOWSKI BANK SPOLDZIELCZY",
    "Address": "RYNEK KLEPARSKI 8",
    "City": "KRAKOW",
    "Branch": "",
    "Postcode": "31-150",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "KRSP",
    "countryCode": "PL",
    "branchCode": "LP2",
    "SWIFT Code": "KRSPPLP2",
    "Bank Name": "KRAKOWSKI BANK SPOLDZIELCZY",
    "Address": "RYNEK KLEPARSKI 8",
    "City": "KRAKOW",
    "Branch": "",
    "Postcode": "31-150",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "RHBH",
    "countryCode": "PL",
    "branchCode": "LPW",
    "SWIFT Code": "RHBHPLPW",
    "Bank Name": "MBANK HIPOTECZNY SA",
    "Address": "PROSTA 18",
    "City": "WARSZAWA",
    "Branch": "",
    "Postcode": "00-850",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "BREX",
    "countryCode": "PL",
    "branchCode": "BIA",
    "SWIFT Code": "BREXPLPWBIA",
    "Bank Name": "MBANK S.A. (FORMERLY BRE BANK S.A.)",
    "Address": "UL. SWIETOJANSKA 15",
    "City": "BIALYSTOK",
    "Branch": "BIALYSTOK BRANCH",
    "Postcode": "15-277",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "BREX",
    "countryCode": "PL",
    "branchCode": "BIB",
    "SWIFT Code": "BREXPLPWBIB",
    "Bank Name": "MBANK S.A. (FORMERLY BRE BANK S.A.)",
    "Address": "PLAC WOLNOSCI 7",
    "City": "BIELSKO BIALA",
    "Branch": "BIELSKO BIALA BRANCH",
    "Postcode": "43-300",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "BREX",
    "countryCode": "PL",
    "branchCode": "BYD",
    "SWIFT Code": "BREXPLPWBYD",
    "Bank Name": "MBANK S.A. (FORMERLY BRE BANK S.A.)",
    "Address": "GRODZKA 19-21",
    "City": "BYDGOSZCZ",
    "Branch": "BYDGOSZCZ BRANCH",
    "Postcode": "85-109",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "BREX",
    "countryCode": "PL",
    "branchCode": "CZE",
    "SWIFT Code": "BREXPLPWCZE",
    "Bank Name": "MBANK S.A. (FORMERLY BRE BANK S.A.)",
    "Address": "JASNOGORSKA 79",
    "City": "CZESTOCHOWA",
    "Branch": "CZESTOCHOWA BRANCH",
    "Postcode": "42-217",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "BREX",
    "countryCode": "PL",
    "branchCode": "GDA",
    "SWIFT Code": "BREXPLPWGDA",
    "Bank Name": "MBANK S.A. (FORMERLY BRE BANK S.A.)",
    "Address": "JANA Z KOLNA 11",
    "City": "GDANSK",
    "Branch": "",
    "Postcode": "80-864",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "BREX",
    "countryCode": "PL",
    "branchCode": "GDY",
    "SWIFT Code": "BREXPLPWGDY",
    "Bank Name": "MBANK S.A. (FORMERLY BRE BANK S.A.)",
    "Address": "SLASKA 47",
    "City": "GDYNIA",
    "Branch": "GDYNIA BRANCH",
    "Postcode": "81-310",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "BREX",
    "countryCode": "PL",
    "branchCode": "GOR",
    "SWIFT Code": "BREXPLPWGOR",
    "Bank Name": "MBANK S.A. (FORMERLY BRE BANK S.A.)",
    "Address": "PRZEMYSLOWA 2",
    "City": "GORZOW WIELKOPOLSKI",
    "Branch": "GORZOW WIELKOPOLSKI BRANCH",
    "Postcode": "66-400",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "BREX",
    "countryCode": "PL",
    "branchCode": "KAL",
    "SWIFT Code": "BREXPLPWKAL",
    "Bank Name": "MBANK S.A. (FORMERLY BRE BANK S.A.)",
    "Address": "FRYDERYKA CHOPINA 26/28",
    "City": "KALISZ",
    "Branch": "KALISZ BRANCH",
    "Postcode": "62-800",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "BREX",
    "countryCode": "PL",
    "branchCode": "KAT",
    "SWIFT Code": "BREXPLPWKAT",
    "Bank Name": "MBANK S.A. (FORMERLY BRE BANK S.A.)",
    "Address": "POWSTANCOW 43",
    "City": "KATOWICE",
    "Branch": "KATOWICE BRANCH",
    "Postcode": "40-024",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "BREX",
    "countryCode": "PL",
    "branchCode": "RCO",
    "SWIFT Code": "BREXPLPWRCO",
    "Bank Name": "MBANK S.A. (FORMERLY BRE BANK S.A.)",
    "Address": "POWSTANCOW 43",
    "City": "KATOWICE",
    "Branch": "REGIONAL OPERATION CENTER",
    "Postcode": "40-024",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "BREX",
    "countryCode": "PL",
    "branchCode": "KIE",
    "SWIFT Code": "BREXPLPWKIE",
    "Bank Name": "MBANK S.A. (FORMERLY BRE BANK S.A.)",
    "Address": "IX WIEKOW KIELC 4",
    "City": "KIELCE",
    "Branch": "KIELCE BRANCH",
    "Postcode": "25-516",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "BREX",
    "countryCode": "PL",
    "branchCode": "KOS",
    "SWIFT Code": "BREXPLPWKOS",
    "Bank Name": "MBANK S.A. (FORMERLY BRE BANK S.A.)",
    "Address": "OKRZEI 3",
    "City": "KOSZALIN",
    "Branch": "CORPORATE BRANCH",
    "Postcode": "75-203",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "BREX",
    "countryCode": "PL",
    "branchCode": "KRA",
    "SWIFT Code": "BREXPLPWKRA",
    "Bank Name": "MBANK S.A. (FORMERLY BRE BANK S.A.)",
    "Address": "AUGUSTIANSKA 15",
    "City": "KRAKOW",
    "Branch": "KRAKOW BRANCH",
    "Postcode": "31-064",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "BREX",
    "countryCode": "PL",
    "branchCode": "LOD",
    "SWIFT Code": "BREXPLPWLOD",
    "Bank Name": "MBANK S.A. (FORMERLY BRE BANK S.A.)",
    "Address": "JANA KILINSKIEGO 74",
    "City": "LODZ",
    "Branch": "LODZ BRANCH",
    "Postcode": "90-119",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "BREX",
    "countryCode": "PL",
    "branchCode": "OMB",
    "SWIFT Code": "BREXPLPWOMB",
    "Bank Name": "MBANK S.A. (FORMERLY BRE BANK S.A.)",
    "Address": "PILSUDSKIEGO STR 3",
    "City": "LODZ",
    "Branch": "MOBILE BANKING",
    "Postcode": "90-368",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "BREX",
    "countryCode": "PL",
    "branchCode": "MBK",
    "SWIFT Code": "BREXPLPWMBK",
    "Bank Name": "MBANK S.A. (FORMERLY BRE BANK S.A.)",
    "Address": "SKRYTKA POCZTOWA 2108",
    "City": "LODZ",
    "Branch": "RETAIL BANKING",
    "Postcode": "90-959",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "BREX",
    "countryCode": "PL",
    "branchCode": "MUL",
    "SWIFT Code": "BREXPLPWMUL",
    "Bank Name": "MBANK S.A. (FORMERLY BRE BANK S.A.)",
    "Address": "SKRYTKA POCZTOWA 2108",
    "City": "LODZ",
    "Branch": "RETAIL BANKING",
    "Postcode": "90-959",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "BREX",
    "countryCode": "PL",
    "branchCode": "LUB",
    "SWIFT Code": "BREXPLPWLUB",
    "Bank Name": "MBANK S.A. (FORMERLY BRE BANK S.A.)",
    "Address": "SPOKOJNA 2",
    "City": "LUBLIN",
    "Branch": "LUBLIN BRANCH",
    "Postcode": "20-074",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "BREX",
    "countryCode": "PL",
    "branchCode": "NWS",
    "SWIFT Code": "BREXPLPWNWS",
    "Bank Name": "MBANK S.A. (FORMERLY BRE BANK S.A.)",
    "Address": "PRAZMOWSKIEGO 11",
    "City": "NOWY SACZ",
    "Branch": "CORPORATE BRANCH",
    "Postcode": "33-300",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "BREX",
    "countryCode": "PL",
    "branchCode": "OLS",
    "SWIFT Code": "BREXPLPWOLS",
    "Bank Name": "MBANK S.A. (FORMERLY BRE BANK S.A.)",
    "Address": "PILSUDSKIEGO 44A",
    "City": "OLSZTYN",
    "Branch": "OLSZTYN BRANCH",
    "Postcode": "10-450",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "BREX",
    "countryCode": "PL",
    "branchCode": "OPO",
    "SWIFT Code": "BREXPLPWOPO",
    "Bank Name": "MBANK S.A. (FORMERLY BRE BANK S.A.)",
    "Address": "KSIAZAT OPOLSKICH 29",
    "City": "OPOLE",
    "Branch": "OPOLE BRANCH",
    "Postcode": "45-005",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "BREX",
    "countryCode": "PL",
    "branchCode": "POZ",
    "SWIFT Code": "BREXPLPWPOZ",
    "Bank Name": "MBANK S.A. (FORMERLY BRE BANK S.A.)",
    "Address": "ROOSEVELTA 22",
    "City": "POZNAN",
    "Branch": "POZNAN BRANCH",
    "Postcode": "60-829",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "BREX",
    "countryCode": "PL",
    "branchCode": "RYB",
    "SWIFT Code": "BREXPLPWRYB",
    "Bank Name": "MBANK S.A. (FORMERLY BRE BANK S.A.)",
    "Address": "RUDZKA 3",
    "City": "RYBNIK",
    "Branch": "RYBNIK BRANCH",
    "Postcode": "44-200",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "BREX",
    "countryCode": "PL",
    "branchCode": "RZE",
    "SWIFT Code": "BREXPLPWRZE",
    "Bank Name": "MBANK S.A. (FORMERLY BRE BANK S.A.)",
    "Address": "SOKOLA 6",
    "City": "RZESZOW",
    "Branch": "RZESZOW BRANCH",
    "Postcode": "35-010",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "BREX",
    "countryCode": "PL",
    "branchCode": "SZC",
    "SWIFT Code": "BREXPLPWSZC",
    "Bank Name": "MBANK S.A. (FORMERLY BRE BANK S.A.)",
    "Address": "ZBOZOWA 4",
    "City": "SZCZECIN",
    "Branch": "SZCZECIN BRANCH",
    "Postcode": "70-653",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "BREX",
    "countryCode": "PL",
    "branchCode": "TOR",
    "SWIFT Code": "BREXPLPWTOR",
    "Bank Name": "MBANK S.A. (FORMERLY BRE BANK S.A.)",
    "Address": "BYDGOSKA 1",
    "City": "TORUN",
    "Branch": "CORPORATE BRANCH",
    "Postcode": "87-100",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "BREX",
    "countryCode": "PL",
    "branchCode": "WAL",
    "SWIFT Code": "BREXPLPWWAL",
    "Bank Name": "MBANK S.A. (FORMERLY BRE BANK S.A.)",
    "Address": "SIENKIEWICZA 2",
    "City": "WALBRZYCH",
    "Branch": "CORPORATE BRANCH",
    "Postcode": "58-300",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "BREX",
    "countryCode": "PL",
    "branchCode": "WA1",
    "SWIFT Code": "BREXPLPWWA1",
    "Bank Name": "MBANK S.A. (FORMERLY BRE BANK S.A.)",
    "Address": "UL. SENATORSKA 18",
    "City": "WARSZAWA",
    "Branch": "BRANCH",
    "Postcode": "00-950",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "BREX",
    "countryCode": "PL",
    "branchCode": "WA4",
    "SWIFT Code": "BREXPLPWWA4",
    "Bank Name": "MBANK S.A. (FORMERLY BRE BANK S.A.)",
    "Address": "AL.JEROZOLIMSKIE 174",
    "City": "WARSZAWA",
    "Branch": "CORPORATE BRANCH",
    "Postcode": "02-486",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "BREX",
    "countryCode": "PL",
    "branchCode": "WA5",
    "SWIFT Code": "BREXPLPWWA5",
    "Bank Name": "MBANK S.A. (FORMERLY BRE BANK S.A.)",
    "Address": "PROSTA 68",
    "City": "WARSZAWA",
    "Branch": "CORPORATE BRANCH",
    "Postcode": "00-838",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "BREX",
    "countryCode": "PL",
    "branchCode": "CUS",
    "SWIFT Code": "BREXPLPWCUS",
    "Bank Name": "MBANK S.A. (FORMERLY BRE BANK S.A.)",
    "Address": "CYBERNETYKI 7A",
    "City": "WARSZAWA",
    "Branch": "CUSTODY DEPARTMENT",
    "Postcode": "02-677",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "BREX",
    "countryCode": "PL",
    "branchCode": "MDM",
    "SWIFT Code": "BREXPLPWMDM",
    "Bank Name": "MBANK S.A. (FORMERLY BRE BANK S.A.)",
    "Address": "WSPOLNA 47/49",
    "City": "WARSZAWA",
    "Branch": "DOM MAKLERSKI MBANKU S.A.",
    "Postcode": "00-684",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "BREX",
    "countryCode": "PL",
    "branchCode": "LPW",
    "SWIFT Code": "BREXPLPW",
    "Bank Name": "MBANK S.A. (FORMERLY BRE BANK S.A.)",
    "Address": "UL. PROSTA 18",
    "City": "WARSZAWA",
    "Branch": "HEAD OFFICE",
    "Postcode": "00-850",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "BREX",
    "countryCode": "PL",
    "branchCode": "DKS",
    "SWIFT Code": "BREXPLPWDKS",
    "Bank Name": "MBANK S.A. (FORMERLY BRE BANK S.A.)",
    "Address": "SENATORSKA 18",
    "City": "WARSZAWA",
    "Branch": "STRATEGIC CLIENTS DEPARTMENT",
    "Postcode": "00-950",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "BREX",
    "countryCode": "PL",
    "branchCode": "WA2",
    "SWIFT Code": "BREXPLPWWA2",
    "Bank Name": "MBANK S.A. (FORMERLY BRE BANK S.A.)",
    "Address": "",
    "City": "WARSZAWA",
    "Branch": "WARSZAWA II BRANCH",
    "Postcode": "",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "BREX",
    "countryCode": "PL",
    "branchCode": "WA3",
    "SWIFT Code": "BREXPLPWWA3",
    "Bank Name": "MBANK S.A. (FORMERLY BRE BANK S.A.)",
    "Address": "OSTROBRAMSKA 207",
    "City": "WARSZAWA",
    "Branch": "WARSZAWA III BRANCH",
    "Postcode": "04-077",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "BREX",
    "countryCode": "PL",
    "branchCode": "WRO",
    "SWIFT Code": "BREXPLPWWRO",
    "Bank Name": "MBANK S.A. (FORMERLY BRE BANK S.A.)",
    "Address": "PL. JANA PAWLA II 9",
    "City": "WROCLAW",
    "Branch": "",
    "Postcode": "50-136",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "BREX",
    "countryCode": "PL",
    "branchCode": "ZIE",
    "SWIFT Code": "BREXPLPWZIE",
    "Bank Name": "MBANK S.A. (FORMERLY BRE BANK S.A.)",
    "Address": "PLAC JANA MATEJKI 19",
    "City": "ZIELONA GORA",
    "Branch": "ZIELONA GORA BRANCH",
    "Postcode": "65-056",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "MBBP",
    "countryCode": "PL",
    "branchCode": "LPW",
    "SWIFT Code": "MBBPPLPW",
    "Bank Name": "MERCEDES-BENZ BANK POLSKA S.A.",
    "Address": "GOTTLIEBA DAIMLERA 1",
    "City": "WARSZAWA",
    "Branch": "",
    "Postcode": "02-460",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "MSDM",
    "countryCode": "PL",
    "branchCode": "LP2",
    "SWIFT Code": "MSDMPLP2",
    "Bank Name": "MICHAEL STROM DOM MAKLERSKI S.A.",
    "Address": "ALEJE JEROZOLIMSKIE 100, FLOOR 6",
    "City": "WARSZAWA",
    "Branch": "",
    "Postcode": "00-807",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "MOPZ",
    "countryCode": "PL",
    "branchCode": "LP2",
    "SWIFT Code": "MOPZPLP2",
    "Bank Name": "MONEZIUM SP.Z.O.O",
    "Address": "GRZYBOWSKA 80/82, LOK. 700",
    "City": "WARSZAWA",
    "Branch": "",
    "Postcode": "00-844",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "MNAA",
    "countryCode": "PL",
    "branchCode": "LP2",
    "SWIFT Code": "MNAAPLP2",
    "Bank Name": "MONSAS SP. Z O.O.",
    "Address": "UL. MONIUSZKI 1A",
    "City": "WARSZAWA",
    "Branch": "",
    "Postcode": "05-800",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "NBPL",
    "countryCode": "PL",
    "branchCode": "BAN",
    "SWIFT Code": "NBPLPLPWBAN",
    "Bank Name": "NARODOWY BANK POLSKI",
    "Address": "",
    "City": "WARSZAWA",
    "Branch": "",
    "Postcode": "",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "NBPL",
    "countryCode": "PL",
    "branchCode": "LPA",
    "SWIFT Code": "NBPLPLPA",
    "Bank Name": "NARODOWY BANK POLSKI",
    "Address": "UL. SWIETOKRZYSKA 11/21",
    "City": "WARSZAWA",
    "Branch": "",
    "Postcode": "00-919",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "NBPL",
    "countryCode": "PL",
    "branchCode": "LPD",
    "SWIFT Code": "NBPLPLPD",
    "Bank Name": "NARODOWY BANK POLSKI",
    "Address": "UL. SWIETOKRZYSKA 11/21",
    "City": "WARSZAWA",
    "Branch": "",
    "Postcode": "00-919",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "NBPL",
    "countryCode": "PL",
    "branchCode": "LPW",
    "SWIFT Code": "NBPLPLPW",
    "Bank Name": "NARODOWY BANK POLSKI",
    "Address": "SWIETOKRZYSKA 11-21",
    "City": "WARSZAWA",
    "Branch": "HEAD OFFICE",
    "Postcode": "00-919",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "NBPL",
    "countryCode": "PL",
    "branchCode": "KIR",
    "SWIFT Code": "NBPLPLPWKIR",
    "Bank Name": "NARODOWY BANK POLSKI",
    "Address": "",
    "City": "WARSZAWA",
    "Branch": "INTERNAL ROUTING",
    "Postcode": "",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "NBPL",
    "countryCode": "PL",
    "branchCode": "DSP",
    "SWIFT Code": "NBPLPLPDDSP",
    "Bank Name": "NARODOWY BANK POLSKI",
    "Address": "",
    "City": "WARSZAWA",
    "Branch": "PLN - RTGS ONLY",
    "Postcode": "",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "NBPL",
    "countryCode": "PL",
    "branchCode": "SEA",
    "SWIFT Code": "NBPLPLPWSEA",
    "Bank Name": "NARODOWY BANK POLSKI",
    "Address": "SWIETOKRZYSKA 11-21",
    "City": "WARSZAWA",
    "Branch": "T2S AUTO-COLLAT.",
    "Postcode": "00-919",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "NBPL",
    "countryCode": "PL",
    "branchCode": "SEB",
    "SWIFT Code": "NBPLPLPWSEB",
    "Bank Name": "NARODOWY BANK POLSKI",
    "Address": "SWIETOKRZYSKA 11-21",
    "City": "WARSZAWA",
    "Branch": "T2S AUTO-COLLAT.",
    "Postcode": "00-919",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "NBPL",
    "countryCode": "PL",
    "branchCode": "CRD",
    "SWIFT Code": "NBPLPLPWCRD",
    "Bank Name": "NARODOWY BANK POLSKI",
    "Address": "SWIETOKRZYSKA 11-21",
    "City": "WARSZAWA",
    "Branch": "T2S OPERATIONS",
    "Postcode": "00-919",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "KDPW",
    "countryCode": "PL",
    "branchCode": "LPA",
    "SWIFT Code": "KDPWPLPA",
    "Bank Name": "NATIONAL DEPOSITORY FOR SECURITIES (KDPW SA)",
    "Address": "CENTRUM GIELDOWE, KSIAZECA 4",
    "City": "WARSZAWA",
    "Branch": "",
    "Postcode": "00-498",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "NESB",
    "countryCode": "PL",
    "branchCode": "LPW",
    "SWIFT Code": "NESBPLPW",
    "Bank Name": "NEST BANK S.A.",
    "Address": "UL. WOLOSKA 24",
    "City": "WARSZAWA",
    "Branch": "",
    "Postcode": "02-675",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "NESB",
    "countryCode": "PL",
    "branchCode": "FMB",
    "SWIFT Code": "NESBPLPWFMB",
    "Bank Name": "NEST BANK S.A.",
    "Address": "SOLEC 38",
    "City": "WARSZAWA",
    "Branch": "",
    "Postcode": "00-394",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "NWDM",
    "countryCode": "PL",
    "branchCode": "LP2",
    "SWIFT Code": "NWDMPLP2",
    "Bank Name": "NWAI DOM MAKLERSKI S.A.",
    "Address": "NOWY SWIAT 64",
    "City": "WARSZAWA",
    "Branch": "",
    "Postcode": "00-357",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "HYVE",
    "countryCode": "PL",
    "branchCode": "LP2",
    "SWIFT Code": "HYVEPLP2",
    "Bank Name": "PEKAO BANK HIPOTECZNY SA",
    "Address": "RENAISSANCE TOWER, UL. SKIERNIEWICKA 10A",
    "City": "WARSZAWA",
    "Branch": "",
    "Postcode": "01-230",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "TPEO",
    "countryCode": "PL",
    "branchCode": "LPW",
    "SWIFT Code": "TPEOPLPW",
    "Bank Name": "PEKAO TFI S.A.",
    "Address": "NEW CITY, MARYNARSKA 15, FLOOR 4",
    "City": "WARSZAWA",
    "Branch": "",
    "Postcode": "02-674",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "BPKH",
    "countryCode": "PL",
    "branchCode": "LPG",
    "SWIFT Code": "BPKHPLPG",
    "Bank Name": "PKO BANK HIPOTECZNY SA",
    "Address": "PULAWSKA 15",
    "City": "WARSZAWA",
    "Branch": "",
    "Postcode": "02-515",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "BPKO",
    "countryCode": "PL",
    "branchCode": "BIA",
    "SWIFT Code": "BPKOPLPWBIA",
    "Bank Name": "PKO BANK POLSKI S.A.",
    "Address": "TYSIACLECIA PANSTWA POLSKIEGO 6",
    "City": "BIALYSTOK",
    "Branch": "PKO O.REGIONALNY W BIALYMSTOKU",
    "Postcode": "15-111",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "BPKO",
    "countryCode": "PL",
    "branchCode": "TOB",
    "SWIFT Code": "BPKOPLPWTOB",
    "Bank Name": "PKO BANK POLSKI S.A.",
    "Address": "PLAC TEATRALNY 4",
    "City": "BYDGOSZCZ",
    "Branch": "ODDZIAL BYDGOSZCZ",
    "Postcode": "85-950",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "BPKO",
    "countryCode": "PL",
    "branchCode": "GDG",
    "SWIFT Code": "BPKOPLPWGDG",
    "Bank Name": "PKO BANK POLSKI S.A.",
    "Address": "SWIETOJANSKA 17",
    "City": "GDYNIA",
    "Branch": "I/O GDYNIA",
    "Postcode": "71-368",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "BPKO",
    "countryCode": "PL",
    "branchCode": "GOA",
    "SWIFT Code": "BPKOPLPWGOA",
    "Bank Name": "PKO BANK POLSKI S.A.",
    "Address": "KOSYNIEROW GDYNSKICH 79",
    "City": "GORZOW WIELKOPOLSKI",
    "Branch": "I/O GORZOW WIELKOPOLSKI",
    "Postcode": "66-400",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "BPKO",
    "countryCode": "PL",
    "branchCode": "KAB",
    "SWIFT Code": "BPKOPLPWKAB",
    "Bank Name": "PKO BANK POLSKI S.A.",
    "Address": "DAMROTA 23",
    "City": "KATOWICE",
    "Branch": "ODDZIAL KATOWICE",
    "Postcode": "40-022",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "BPKO",
    "countryCode": "PL",
    "branchCode": "KRD",
    "SWIFT Code": "BPKOPLPWKRD",
    "Bank Name": "PKO BANK POLSKI S.A.",
    "Address": "OSIEDLE KOSCIUSZKOWSKIE 1",
    "City": "KRAKOW",
    "Branch": "ODDZIAL KRAKOW",
    "Postcode": "31-858",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "BPKO",
    "countryCode": "PL",
    "branchCode": "LDA",
    "SWIFT Code": "BPKOPLPWLDA",
    "Bank Name": "PKO BANK POLSKI S.A.",
    "Address": "PIOTRKOWSKA STREET 173",
    "City": "LODZ",
    "Branch": "ODDZIAL LODZ",
    "Postcode": "90-959",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "BPKO",
    "countryCode": "PL",
    "branchCode": "LUA",
    "SWIFT Code": "BPKOPLPWLUA",
    "Bank Name": "PKO BANK POLSKI S.A.",
    "Address": "WATYKANSKA 7",
    "City": "LUBLIN",
    "Branch": "ODDZIAL LUBLIN",
    "Postcode": "20-538",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "BPKO",
    "countryCode": "PL",
    "branchCode": "OLS",
    "SWIFT Code": "BPKOPLPWOLS",
    "Bank Name": "PKO BANK POLSKI S.A.",
    "Address": "KOSCIUSZKI STREET 89/91",
    "City": "OLSZTYN",
    "Branch": "ODDZIAL OLSZTYN",
    "Postcode": "10-584",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "BPKO",
    "countryCode": "PL",
    "branchCode": "POA",
    "SWIFT Code": "BPKOPLPWPOA",
    "Bank Name": "PKO BANK POLSKI S.A.",
    "Address": "GORDA WILDA 109",
    "City": "POZNAN",
    "Branch": "ODDZIAL POZNAN",
    "Postcode": "60-959",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "BPKO",
    "countryCode": "PL",
    "branchCode": "LPW",
    "SWIFT Code": "BPKOPLPW",
    "Bank Name": "PKO BANK POLSKI S.A.",
    "Address": "UL. PULAWSKA 15",
    "City": "WARSZAWA",
    "Branch": "",
    "Postcode": "02-515",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "BPKO",
    "countryCode": "PL",
    "branchCode": "CSD",
    "SWIFT Code": "BPKOPLPWCSD",
    "Bank Name": "PKO BANK POLSKI S.A.",
    "Address": "",
    "City": "WARSZAWA",
    "Branch": "CUSTODY SERVICES DIVISION",
    "Postcode": "",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "BPKO",
    "countryCode": "PL",
    "branchCode": "TDH",
    "SWIFT Code": "BPKOPLPWTDH",
    "Bank Name": "PKO BANK POLSKI S.A.",
    "Address": "PULAWSKA STREET 16",
    "City": "WARSZAWA",
    "Branch": "HEAD OFFICE - TREASURY DEPARTMENT",
    "Postcode": "02-515",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "BPKO",
    "countryCode": "PL",
    "branchCode": "WAA",
    "SWIFT Code": "BPKOPLPWWAA",
    "Bank Name": "PKO BANK POLSKI S.A.",
    "Address": "SIENKIEWICZA 12/14",
    "City": "WARSZAWA",
    "Branch": "ODDZIAL WARSZAWA",
    "Postcode": "00-944",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "BPKO",
    "countryCode": "PL",
    "branchCode": "SEC",
    "SWIFT Code": "BPKOPLPWSEC",
    "Bank Name": "PKO BANK POLSKI S.A.",
    "Address": "",
    "City": "WARSZAWA",
    "Branch": "PKO BP SECURITIES",
    "Postcode": "",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "BPKO",
    "countryCode": "PL",
    "branchCode": "WRD",
    "SWIFT Code": "BPKOPLPWWRD",
    "Bank Name": "PKO BANK POLSKI S.A.",
    "Address": "WITA STWOSZA 12",
    "City": "WROCLAW",
    "Branch": "ODDZIAL WROCLAW",
    "Postcode": "50-950",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "PTFI",
    "countryCode": "PL",
    "branchCode": "LPW",
    "SWIFT Code": "PTFIPLPW",
    "Bank Name": "PKO TOWARZYSTWO FUNDUSZY INWESTYCYJNYCH SA",
    "Address": "UL CHLODNA 52",
    "City": "WARSZAWA",
    "Branch": "",
    "Postcode": "00-872",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "PTFI",
    "countryCode": "PL",
    "branchCode": "AKG",
    "SWIFT Code": "PTFIPLPWAKG",
    "Bank Name": "PKO TOWARZYSTWO FUNDUSZY INWESTYCYJNYCH SA",
    "Address": "UL CHLODNA 52",
    "City": "WARSZAWA",
    "Branch": "",
    "Postcode": "00-872",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "PTFI",
    "countryCode": "PL",
    "branchCode": "AKT",
    "SWIFT Code": "PTFIPLPWAKT",
    "Bank Name": "PKO TOWARZYSTWO FUNDUSZY INWESTYCYJNYCH SA",
    "Address": "UL CHLODNA 52",
    "City": "WARSZAWA",
    "Branch": "",
    "Postcode": "00-872",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "PTFI",
    "countryCode": "PL",
    "branchCode": "ALF",
    "SWIFT Code": "PTFIPLPWALF",
    "Bank Name": "PKO TOWARZYSTWO FUNDUSZY INWESTYCYJNYCH SA",
    "Address": "UL CHLODNA 52",
    "City": "WARSZAWA",
    "Branch": "",
    "Postcode": "00-872",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "PTFI",
    "countryCode": "PL",
    "branchCode": "ALS",
    "SWIFT Code": "PTFIPLPWALS",
    "Bank Name": "PKO TOWARZYSTWO FUNDUSZY INWESTYCYJNYCH SA",
    "Address": "UL CHLODNA 52",
    "City": "WARSZAWA",
    "Branch": "",
    "Postcode": "00-872",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "PTFI",
    "countryCode": "PL",
    "branchCode": "DEL",
    "SWIFT Code": "PTFIPLPWDEL",
    "Bank Name": "PKO TOWARZYSTWO FUNDUSZY INWESTYCYJNYCH SA",
    "Address": "UL CHLODNA 52",
    "City": "WARSZAWA",
    "Branch": "",
    "Postcode": "00-872",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "PTFI",
    "countryCode": "PL",
    "branchCode": "GAM",
    "SWIFT Code": "PTFIPLPWGAM",
    "Bank Name": "PKO TOWARZYSTWO FUNDUSZY INWESTYCYJNYCH SA",
    "Address": "UL CHLODNA 52",
    "City": "WARSZAWA",
    "Branch": "",
    "Postcode": "00-872",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "PTFI",
    "countryCode": "PL",
    "branchCode": "NED",
    "SWIFT Code": "PTFIPLPWNED",
    "Bank Name": "PKO TOWARZYSTWO FUNDUSZY INWESTYCYJNYCH SA",
    "Address": "UL CHLODNA 52",
    "City": "WARSZAWA",
    "Branch": "",
    "Postcode": "00-872",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "PTFI",
    "countryCode": "PL",
    "branchCode": "OGL",
    "SWIFT Code": "PTFIPLPWOGL",
    "Bank Name": "PKO TOWARZYSTWO FUNDUSZY INWESTYCYJNYCH SA",
    "Address": "UL CHLODNA 52",
    "City": "WARSZAWA",
    "Branch": "",
    "Postcode": "00-872",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "PTFI",
    "countryCode": "PL",
    "branchCode": "OKP",
    "SWIFT Code": "PTFIPLPWOKP",
    "Bank Name": "PKO TOWARZYSTWO FUNDUSZY INWESTYCYJNYCH SA",
    "Address": "UL CHLODNA 52",
    "City": "WARSZAWA",
    "Branch": "",
    "Postcode": "00-872",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "PTFI",
    "countryCode": "PL",
    "branchCode": "PAK",
    "SWIFT Code": "PTFIPLPWPAK",
    "Bank Name": "PKO TOWARZYSTWO FUNDUSZY INWESTYCYJNYCH SA",
    "Address": "UL CHLODNA 52",
    "City": "WARSZAWA",
    "Branch": "",
    "Postcode": "00-872",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "PTFI",
    "countryCode": "PL",
    "branchCode": "PAS",
    "SWIFT Code": "PTFIPLPWPAS",
    "Bank Name": "PKO TOWARZYSTWO FUNDUSZY INWESTYCYJNYCH SA",
    "Address": "UL CHLODNA 52",
    "City": "WARSZAWA",
    "Branch": "",
    "Postcode": "00-872",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "PTFI",
    "countryCode": "PL",
    "branchCode": "POB",
    "SWIFT Code": "PTFIPLPWPOB",
    "Bank Name": "PKO TOWARZYSTWO FUNDUSZY INWESTYCYJNYCH SA",
    "Address": "UL CHLODNA 52",
    "City": "WARSZAWA",
    "Branch": "",
    "Postcode": "00-872",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "PTFI",
    "countryCode": "PL",
    "branchCode": "PPI",
    "SWIFT Code": "PTFIPLPWPPI",
    "Bank Name": "PKO TOWARZYSTWO FUNDUSZY INWESTYCYJNYCH SA",
    "Address": "UL CHLODNA 52",
    "City": "WARSZAWA",
    "Branch": "",
    "Postcode": "00-872",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "PTFI",
    "countryCode": "PL",
    "branchCode": "AMM",
    "SWIFT Code": "PTFIPLPWAMM",
    "Bank Name": "PKO TOWARZYSTWO FUNDUSZY INWESTYCYJNYCH SA",
    "Address": "UL CHLODNA 52",
    "City": "WARSZAWA",
    "Branch": "GAMMA PARASOL BIZNES - SFIO SUBFUNDUSZ GAMMA",
    "Postcode": "00-872",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "PTFI",
    "countryCode": "PL",
    "branchCode": "SGM",
    "SWIFT Code": "PTFIPLPWSGM",
    "Bank Name": "PKO TOWARZYSTWO FUNDUSZY INWESTYCYJNYCH SA",
    "Address": "UL CHLODNA 52",
    "City": "WARSZAWA",
    "Branch": "GAMMA PARASOL BIZNES - SFIO SUBFUNDUSZ SIGMA OBLIGACJI PLUS",
    "Postcode": "00-872",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "PTFI",
    "countryCode": "PL",
    "branchCode": "MER",
    "SWIFT Code": "PTFIPLPWMER",
    "Bank Name": "PKO TOWARZYSTWO FUNDUSZY INWESTYCYJNYCH SA",
    "Address": "UL CHLODNA 52",
    "City": "WARSZAWA",
    "Branch": "MERKURY FIZAN",
    "Postcode": "00-872",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "PTFI",
    "countryCode": "PL",
    "branchCode": "ASZ",
    "SWIFT Code": "PTFIPLPWASZ",
    "Bank Name": "PKO TOWARZYSTWO FUNDUSZY INWESTYCYJNYCH SA",
    "Address": "UL CHLODNA 52",
    "City": "WARSZAWA",
    "Branch": "PKO ABSOLUTNEJ STOPY ZWROTU EUROPA WSCHOD-ZACHOD FIZ",
    "Postcode": "00-872",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "PTFI",
    "countryCode": "PL",
    "branchCode": "FBL",
    "SWIFT Code": "PTFIPLPWFBL",
    "Bank Name": "PKO TOWARZYSTWO FUNDUSZY INWESTYCYJNYCH SA",
    "Address": "UL CHLODNA 52",
    "City": "WARSZAWA",
    "Branch": "PKO BEZPIECZNA LOKATA I FIZ",
    "Postcode": "00-872",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "PTFI",
    "countryCode": "PL",
    "branchCode": "P25",
    "SWIFT Code": "PTFIPLPWP25",
    "Bank Name": "PKO TOWARZYSTWO FUNDUSZY INWESTYCYJNYCH SA",
    "Address": "UL CHLODNA 52",
    "City": "WARSZAWA",
    "Branch": "PKO EMERYTURA SFIO SUBFUNDUSZ PKO EMERYTURA 2025",
    "Postcode": "00-872",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "PTFI",
    "countryCode": "PL",
    "branchCode": "P30",
    "SWIFT Code": "PTFIPLPWP30",
    "Bank Name": "PKO TOWARZYSTWO FUNDUSZY INWESTYCYJNYCH SA",
    "Address": "UL CHLODNA 52",
    "City": "WARSZAWA",
    "Branch": "PKO EMERYTURA SFIO SUBFUNDUSZ PKO EMERYTURA 2030",
    "Postcode": "00-872",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "PTFI",
    "countryCode": "PL",
    "branchCode": "P35",
    "SWIFT Code": "PTFIPLPWP35",
    "Bank Name": "PKO TOWARZYSTWO FUNDUSZY INWESTYCYJNYCH SA",
    "Address": "UL CHLODNA 52",
    "City": "WARSZAWA",
    "Branch": "PKO EMERYTURA SFIO SUBFUNDUSZ PKO EMERYTURA 2035",
    "Postcode": "00-872",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "PTFI",
    "countryCode": "PL",
    "branchCode": "P40",
    "SWIFT Code": "PTFIPLPWP40",
    "Bank Name": "PKO TOWARZYSTWO FUNDUSZY INWESTYCYJNYCH SA",
    "Address": "UL CHLODNA 52",
    "City": "WARSZAWA",
    "Branch": "PKO EMERYTURA SFIO SUBFUNDUSZ PKO EMERYTURA 2040",
    "Postcode": "00-872",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "PTFI",
    "countryCode": "PL",
    "branchCode": "P45",
    "SWIFT Code": "PTFIPLPWP45",
    "Bank Name": "PKO TOWARZYSTWO FUNDUSZY INWESTYCYJNYCH SA",
    "Address": "UL CHLODNA 52",
    "City": "WARSZAWA",
    "Branch": "PKO EMERYTURA SFIO SUBFUNDUSZ PKO EMERYTURA 2045",
    "Postcode": "00-872",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "PTFI",
    "countryCode": "PL",
    "branchCode": "P50",
    "SWIFT Code": "PTFIPLPWP50",
    "Bank Name": "PKO TOWARZYSTWO FUNDUSZY INWESTYCYJNYCH SA",
    "Address": "UL CHLODNA 52",
    "City": "WARSZAWA",
    "Branch": "PKO EMERYTURA SFIO SUBFUNDUSZ PKO EMERYTURA 2050",
    "Postcode": "00-872",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "PTFI",
    "countryCode": "PL",
    "branchCode": "P55",
    "SWIFT Code": "PTFIPLPWP55",
    "Bank Name": "PKO TOWARZYSTWO FUNDUSZY INWESTYCYJNYCH SA",
    "Address": "UL CHLODNA 52",
    "City": "WARSZAWA",
    "Branch": "PKO EMERYTURA SFIO SUBFUNDUSZ PKO EMERYTURA 2055",
    "Postcode": "00-872",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "PTFI",
    "countryCode": "PL",
    "branchCode": "P60",
    "SWIFT Code": "PTFIPLPWP60",
    "Bank Name": "PKO TOWARZYSTWO FUNDUSZY INWESTYCYJNYCH SA",
    "Address": "UL CHLODNA 52",
    "City": "WARSZAWA",
    "Branch": "PKO EMERYTURA SFIO SUBFUNDUSZ PKO EMERYTURA 2060",
    "Postcode": "00-872",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "PTFI",
    "countryCode": "PL",
    "branchCode": "P65",
    "SWIFT Code": "PTFIPLPWP65",
    "Bank Name": "PKO TOWARZYSTWO FUNDUSZY INWESTYCYJNYCH SA",
    "Address": "UL CHLODNA 52",
    "City": "WARSZAWA",
    "Branch": "PKO EMERYTURA SFIO SUBFUNDUSZ PKO EMERYTURA 2065",
    "Postcode": "00-872",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "PTFI",
    "countryCode": "PL",
    "branchCode": "FEO",
    "SWIFT Code": "PTFIPLPWFEO",
    "Bank Name": "PKO TOWARZYSTWO FUNDUSZY INWESTYCYJNYCH SA",
    "Address": "UL CHLODNA 52",
    "City": "WARSZAWA",
    "Branch": "PKO ENERGII ODNAWIALNEJ FIZAN",
    "Postcode": "00-872",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "PTFI",
    "countryCode": "PL",
    "branchCode": "EWZ",
    "SWIFT Code": "PTFIPLPWEWZ",
    "Bank Name": "PKO TOWARZYSTWO FUNDUSZY INWESTYCYJNYCH SA",
    "Address": "UL CHLODNA 52",
    "City": "WARSZAWA",
    "Branch": "PKO EUROPA WSCHOD-ZACHOD FIZ",
    "Postcode": "00-872",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "PTFI",
    "countryCode": "PL",
    "branchCode": "FGD",
    "SWIFT Code": "PTFIPLPWFGD",
    "Bank Name": "PKO TOWARZYSTWO FUNDUSZY INWESTYCYJNYCH SA",
    "Address": "UL CHLODNA 52",
    "City": "WARSZAWA",
    "Branch": "PKO GLOBALNEGO DOCHODU FIZ",
    "Postcode": "00-872",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "BMPB",
    "countryCode": "PL",
    "branchCode": "LPP",
    "SWIFT Code": "BMPBPLPP",
    "Bank Name": "AION S.A. SPOLKA AKCYJNA ODDZIAL W POLSCE",
    "Address": "DOBRA 40",
    "City": "WARSZAWA",
    "Branch": "",
    "Postcode": "00-344",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "ALBP",
    "countryCode": "PL",
    "branchCode": "CUS",
    "SWIFT Code": "ALBPPLPWCUS",
    "Bank Name": "ALIOR BANK SPOLKA AKCYJNA",
    "Address": "LOPUSZANSKA BUSINESS PARK, LOPUSZANSKA 38 D",
    "City": "WARSZAWA",
    "Branch": "",
    "Postcode": "02-232",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "ALBP",
    "countryCode": "PL",
    "branchCode": "LPW",
    "SWIFT Code": "ALBPPLPW",
    "Bank Name": "ALIOR BANK SPOLKA AKCYJNA",
    "Address": "LOPUSZANSKA BUSINESS PARK, LOPUSZANSKA 38 D",
    "City": "WARSZAWA",
    "Branch": "",
    "Postcode": "02-232",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "ASFH",
    "countryCode": "PL",
    "branchCode": "LPK",
    "SWIFT Code": "ASFHPLPK",
    "Bank Name": "AMER SPORTS FINANCIAL SHARED SERVICE SP.",
    "Address": "AL. POKOJU 5",
    "City": "KRAKOW",
    "Branch": "",
    "Postcode": "31-548",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "ISAO",
    "countryCode": "PL",
    "branchCode": "LPP",
    "SWIFT Code": "ISAOPLPP",
    "Bank Name": "AS INBANK SPOLKA AKCYJNA ODDZIAL W POLSCE",
    "Address": "RIVERSIDE PARK, FABRYCZNA 5A",
    "City": "WARSZAWA",
    "Branch": "",
    "Postcode": "00-446",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "BPHK",
    "countryCode": "PL",
    "branchCode": "LPK",
    "SWIFT Code": "BPHKPLPK",
    "Bank Name": "BANK BPH SA",
    "Address": "UL. CYPRIANA KAMILA NORWIDA 1",
    "City": "GDANSK",
    "Branch": "",
    "Postcode": "80-280",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "BPHK",
    "countryCode": "PL",
    "branchCode": "CUS",
    "SWIFT Code": "BPHKPLPKCUS",
    "Bank Name": "BANK BPH SA",
    "Address": "UL. CYPRIANA KAMILA NORWIDA 1",
    "City": "GDANSK",
    "Branch": "CUSTODY DEPARTMENT",
    "Postcode": "80-280",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "GOSK",
    "countryCode": "PL",
    "branchCode": "LPW",
    "SWIFT Code": "GOSKPLPW",
    "Bank Name": "BANK GOSPODARSTWA KRAJOWEGO",
    "Address": "AL. JEROZOLIMSKIE 7",
    "City": "WARSZAWA",
    "Branch": "",
    "Postcode": "00-496",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "CITI",
    "countryCode": "PL",
    "branchCode": "LPX",
    "SWIFT Code": "CITIPLPX",
    "Bank Name": "BANK HANDLOWY W WARSZAWIE SA",
    "Address": "SENATORSKA 16",
    "City": "WARSZAWA",
    "Branch": "",
    "Postcode": "00-923",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "CITI",
    "countryCode": "PL",
    "branchCode": "BRO",
    "SWIFT Code": "CITIPLPXBRO",
    "Bank Name": "BANK HANDLOWY W WARSZAWIE SA",
    "Address": "SENATORSKA 16",
    "City": "WARSZAWA",
    "Branch": "BANK HANDLOWY W WARSZAWIE SA BROKERAGE ACTIVITY",
    "Postcode": "00-923",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "CITI",
    "countryCode": "PL",
    "branchCode": "CCH",
    "SWIFT Code": "CITIPLPXCCH",
    "Bank Name": "BANK HANDLOWY W WARSZAWIE SA",
    "Address": "",
    "City": "WARSZAWA",
    "Branch": "WARSAW COMMODITY CLEARING HOUSE MESSAGES EXCHANGE ONLY",
    "Postcode": "",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "BIGB",
    "countryCode": "PL",
    "branchCode": "LPW",
    "SWIFT Code": "BIGBPLPW",
    "Bank Name": "BANK MILLENNIUM S.A.",
    "Address": "HARMONY CENTER, UL. STANISLAWA ZARYNA 2A",
    "City": "WARSZAWA",
    "Branch": "",
    "Postcode": "02-593",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "BIGB",
    "countryCode": "PL",
    "branchCode": "CUS",
    "SWIFT Code": "BIGBPLPWCUS",
    "Bank Name": "BANK MILLENNIUM S.A.",
    "Address": "HARMONY CENTER, UL. STANISLAWA ZARYNA 2A",
    "City": "WARSZAWA",
    "Branch": "CUSTODY DEPARTMENT",
    "Postcode": "02-593",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "NOSJ",
    "countryCode": "PL",
    "branchCode": "LPP",
    "SWIFT Code": "NOSJPLPP",
    "Bank Name": "BANK NOWY SPOLKA AKCYJNA",
    "Address": "UL. MALE GARBARY 8",
    "City": "POZNAN",
    "Branch": "",
    "Postcode": "61-756",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "EBOS",
    "countryCode": "PL",
    "branchCode": "216",
    "SWIFT Code": "EBOSPLPW216",
    "Bank Name": "BANK OCHRONY SRODOWISKA S.A.",
    "Address": "",
    "City": "BIALYSTOK",
    "Branch": "",
    "Postcode": "",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "EBOS",
    "countryCode": "PL",
    "branchCode": "261",
    "SWIFT Code": "EBOSPLPW261",
    "Bank Name": "BANK OCHRONY SRODOWISKA S.A.",
    "Address": "",
    "City": "BIELSKO BIALA",
    "Branch": "",
    "Postcode": "",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "EBOS",
    "countryCode": "PL",
    "branchCode": "018",
    "SWIFT Code": "EBOSPLPW018",
    "Bank Name": "BANK OCHRONY SRODOWISKA S.A.",
    "Address": "",
    "City": "BYDGOSZCZ",
    "Branch": "",
    "Postcode": "",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "EBOS",
    "countryCode": "PL",
    "branchCode": "CHA",
    "SWIFT Code": "EBOSPLPWCHA",
    "Bank Name": "BANK OCHRONY SRODOWISKA S.A.",
    "Address": "",
    "City": "CHELM",
    "Branch": "",
    "Postcode": "",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "EBOS",
    "countryCode": "PL",
    "branchCode": "005",
    "SWIFT Code": "EBOSPLPW005",
    "Bank Name": "BANK OCHRONY SRODOWISKA S.A.",
    "Address": "",
    "City": "CZESTOCHOWA",
    "Branch": "",
    "Postcode": "",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "EBOS",
    "countryCode": "PL",
    "branchCode": "274",
    "SWIFT Code": "EBOSPLPW274",
    "Bank Name": "BANK OCHRONY SRODOWISKA S.A.",
    "Address": "",
    "City": "ELBLAG",
    "Branch": "",
    "Postcode": "",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "EBOS",
    "countryCode": "PL",
    "branchCode": "089",
    "SWIFT Code": "EBOSPLPW089",
    "Bank Name": "BANK OCHRONY SRODOWISKA S.A.",
    "Address": "",
    "City": "GDANSK",
    "Branch": "",
    "Postcode": "",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "EBOS",
    "countryCode": "PL",
    "branchCode": "199",
    "SWIFT Code": "EBOSPLPW199",
    "Bank Name": "BANK OCHRONY SRODOWISKA S.A.",
    "Address": "",
    "City": "JELENIA GORA",
    "Branch": "JELENIA GORA",
    "Postcode": "",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "EBOS",
    "countryCode": "PL",
    "branchCode": "119",
    "SWIFT Code": "EBOSPLPW119",
    "Bank Name": "BANK OCHRONY SRODOWISKA S.A.",
    "Address": "",
    "City": "KATOWICE",
    "Branch": "",
    "Postcode": "",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "EBOS",
    "countryCode": "PL",
    "branchCode": "KIA",
    "SWIFT Code": "EBOSPLPWKIA",
    "Bank Name": "BANK OCHRONY SRODOWISKA S.A.",
    "Address": "",
    "City": "KIELCE",
    "Branch": "",
    "Postcode": "",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "EBOS",
    "countryCode": "PL",
    "branchCode": "232",
    "SWIFT Code": "EBOSPLPW232",
    "Bank Name": "BANK OCHRONY SRODOWISKA S.A.",
    "Address": "",
    "City": "KONIN",
    "Branch": "",
    "Postcode": "",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "EBOS",
    "countryCode": "PL",
    "branchCode": "034",
    "SWIFT Code": "EBOSPLPW034",
    "Bank Name": "BANK OCHRONY SRODOWISKA S.A.",
    "Address": "",
    "City": "KOSZALIN",
    "Branch": "",
    "Postcode": "",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "EBOS",
    "countryCode": "PL",
    "branchCode": "106",
    "SWIFT Code": "EBOSPLPW106",
    "Bank Name": "BANK OCHRONY SRODOWISKA S.A.",
    "Address": "",
    "City": "KRAKOW",
    "Branch": "",
    "Postcode": "",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "EBOS",
    "countryCode": "PL",
    "branchCode": "258",
    "SWIFT Code": "EBOSPLPW258",
    "Bank Name": "BANK OCHRONY SRODOWISKA S.A.",
    "Address": "",
    "City": "LEGNICA",
    "Branch": "",
    "Postcode": "",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "EBOS",
    "countryCode": "PL",
    "branchCode": "245",
    "SWIFT Code": "EBOSPLPW245",
    "Bank Name": "BANK OCHRONY SRODOWISKA S.A.",
    "Address": "",
    "City": "LODZ",
    "Branch": "",
    "Postcode": "",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "EBOS",
    "countryCode": "PL",
    "branchCode": "LOA",
    "SWIFT Code": "EBOSPLPWLOA",
    "Bank Name": "BANK OCHRONY SRODOWISKA S.A.",
    "Address": "",
    "City": "LOMZA",
    "Branch": "",
    "Postcode": "18-400",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "EBOS",
    "countryCode": "PL",
    "branchCode": "135",
    "SWIFT Code": "EBOSPLPW135",
    "Bank Name": "BANK OCHRONY SRODOWISKA S.A.",
    "Address": "",
    "City": "LUBLIN",
    "Branch": "",
    "Postcode": "",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "EBOS",
    "countryCode": "PL",
    "branchCode": "210",
    "SWIFT Code": "EBOSPLPW210",
    "Bank Name": "BANK OCHRONY SRODOWISKA S.A.",
    "Address": "",
    "City": "OBORNIKI",
    "Branch": "",
    "Postcode": "64-600",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "EBOS",
    "countryCode": "PL",
    "branchCode": "063",
    "SWIFT Code": "EBOSPLPW063",
    "Bank Name": "BANK OCHRONY SRODOWISKA S.A.",
    "Address": "",
    "City": "OLSZTYN",
    "Branch": "",
    "Postcode": "",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "EBOS",
    "countryCode": "PL",
    "branchCode": "229",
    "SWIFT Code": "EBOSPLPW229",
    "Bank Name": "BANK OCHRONY SRODOWISKA S.A.",
    "Address": "",
    "City": "OPOLE",
    "Branch": "",
    "Postcode": "",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "EBOS",
    "countryCode": "PL",
    "branchCode": "223",
    "SWIFT Code": "EBOSPLPW223",
    "Bank Name": "BANK OCHRONY SRODOWISKA S.A.",
    "Address": "",
    "City": "OSTROW WIELKOPOLSKI",
    "Branch": "",
    "Postcode": "",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "EBOS",
    "countryCode": "PL",
    "branchCode": "PIA",
    "SWIFT Code": "EBOSPLPWPIA",
    "Bank Name": "BANK OCHRONY SRODOWISKA S.A.",
    "Address": "",
    "City": "PILA",
    "Branch": "",
    "Postcode": "64-920",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "EBOS",
    "countryCode": "PL",
    "branchCode": "290",
    "SWIFT Code": "EBOSPLPW290",
    "Bank Name": "BANK OCHRONY SRODOWISKA S.A.",
    "Address": "",
    "City": "PLOCK",
    "Branch": "",
    "Postcode": "",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "EBOS",
    "countryCode": "PL",
    "branchCode": "047",
    "SWIFT Code": "EBOSPLPW047",
    "Bank Name": "BANK OCHRONY SRODOWISKA S.A.",
    "Address": "",
    "City": "POZNAN",
    "Branch": "",
    "Postcode": "",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "EBOS",
    "countryCode": "PL",
    "branchCode": "122",
    "SWIFT Code": "EBOSPLPW122",
    "Bank Name": "BANK OCHRONY SRODOWISKA S.A.",
    "Address": "",
    "City": "RZESZOW",
    "Branch": "",
    "Postcode": "",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "EBOS",
    "countryCode": "PL",
    "branchCode": "SUA",
    "SWIFT Code": "EBOSPLPWSUA",
    "Bank Name": "BANK OCHRONY SRODOWISKA S.A.",
    "Address": "",
    "City": "SUWALKI",
    "Branch": "",
    "Postcode": "",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "EBOS",
    "countryCode": "PL",
    "branchCode": "076",
    "SWIFT Code": "EBOSPLPW076",
    "Bank Name": "BANK OCHRONY SRODOWISKA S.A.",
    "Address": "",
    "City": "SZCZECIN",
    "Branch": "",
    "Postcode": "",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "EBOS",
    "countryCode": "PL",
    "branchCode": "252",
    "SWIFT Code": "EBOSPLPW252",
    "Bank Name": "BANK OCHRONY SRODOWISKA S.A.",
    "Address": "",
    "City": "TARNOW",
    "Branch": "",
    "Postcode": "",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "EBOS",
    "countryCode": "PL",
    "branchCode": "304",
    "SWIFT Code": "EBOSPLPW304",
    "Bank Name": "BANK OCHRONY SRODOWISKA S.A.",
    "Address": "",
    "City": "TORUN",
    "Branch": "",
    "Postcode": "",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "EBOS",
    "countryCode": "PL",
    "branchCode": "LPW",
    "SWIFT Code": "EBOSPLPW",
    "Bank Name": "BANK OCHRONY SRODOWISKA S.A.",
    "Address": "UL. ZELAZNA 32",
    "City": "WARSZAWA",
    "Branch": "",
    "Postcode": "00-832",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "EBOS",
    "countryCode": "PL",
    "branchCode": "017",
    "SWIFT Code": "EBOSPLPW017",
    "Bank Name": "BANK OCHRONY SRODOWISKA S.A.",
    "Address": "",
    "City": "WARSZAWA",
    "Branch": "CORPORATE CLIENTS UNIT",
    "Postcode": "",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "EBOS",
    "countryCode": "PL",
    "branchCode": "102",
    "SWIFT Code": "EBOSPLPW102",
    "Bank Name": "BANK OCHRONY SRODOWISKA S.A.",
    "Address": "",
    "City": "WARSZAWA",
    "Branch": "I/O WARSZAWA",
    "Postcode": "",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "EBOS",
    "countryCode": "PL",
    "branchCode": "157",
    "SWIFT Code": "EBOSPLPW157",
    "Bank Name": "BANK OCHRONY SRODOWISKA S.A.",
    "Address": "",
    "City": "WARSZAWA",
    "Branch": "II/O WARSZAWA",
    "Postcode": "",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "EBOS",
    "countryCode": "PL",
    "branchCode": "287",
    "SWIFT Code": "EBOSPLPW287",
    "Bank Name": "BANK OCHRONY SRODOWISKA S.A.",
    "Address": "",
    "City": "WARSZAWA",
    "Branch": "III/O WARSZAWA",
    "Postcode": "",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "EBOS",
    "countryCode": "PL",
    "branchCode": "050",
    "SWIFT Code": "EBOSPLPW050",
    "Bank Name": "BANK OCHRONY SRODOWISKA S.A.",
    "Address": "",
    "City": "WLOCLAWEK",
    "Branch": "",
    "Postcode": "",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "EBOS",
    "countryCode": "PL",
    "branchCode": "021",
    "SWIFT Code": "EBOSPLPW021",
    "Bank Name": "BANK OCHRONY SRODOWISKA S.A.",
    "Address": "",
    "City": "WROCLAW",
    "Branch": "",
    "Postcode": "",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "WBKP",
    "countryCode": "PL",
    "branchCode": "CBM",
    "SWIFT Code": "WBKPPLPPCBM",
    "Bank Name": "SANTANDER BANK POLSKA S.A. (FORMERLY BANK ZACHODNI WBK S.A.)",
    "Address": "PLAC WOLNOSCI 15",
    "City": "POZNAN",
    "Branch": "BZWBK BROKERAGE HOUSE",
    "Postcode": "60-967",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "WBKP",
    "countryCode": "PL",
    "branchCode": "LPP",
    "SWIFT Code": "WBKPPLPP",
    "Bank Name": "SANTANDER BANK POLSKA S.A. (FORMERLY BANK ZACHODNI WBK S.A.)",
    "Address": "AL. JANA PAWLA II 17",
    "City": "WARSZAWA",
    "Branch": "HEAD OFFICE",
    "Postcode": "00-854",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "SCFB",
    "countryCode": "PL",
    "branchCode": "LPW",
    "SWIFT Code": "SCFBPLPW",
    "Bank Name": "SANTANDER CONSUMER BANK SA",
    "Address": "LEGNICKA 48 B",
    "City": "WROCLAW",
    "Branch": "",
    "Postcode": "54-202",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "GBWC",
    "countryCode": "PL",
    "branchCode": "LPP",
    "SWIFT Code": "GBWCPLPP",
    "Bank Name": "SGB-BANK S.A. (FORMERLY GOSPODARCZY BANK WIELKOPOLSKI S.A.)",
    "Address": "UL. SZARYCH SZEREGOW 23A",
    "City": "POZNAN",
    "Branch": "",
    "Postcode": "60-462",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "ESSE",
    "countryCode": "PL",
    "branchCode": "LPW",
    "SWIFT Code": "ESSEPLPW",
    "Bank Name": "SKANDINAVISKA ENSKILDA BANKEN AB, SPOLKA AKCYJNA, ODDZIAL W POLSCE",
    "Address": "UL. ZELAZNA 51/53",
    "City": "WARSZAWA",
    "Branch": "",
    "Postcode": "00-841",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "SOGE",
    "countryCode": "PL",
    "branchCode": "LPW",
    "SWIFT Code": "SOGEPLPW",
    "Bank Name": "SOCIETE GENERALE SPOLKA AKCYJNA ODDZIAL W POLSCE",
    "Address": "MARSZALKOWSKA STREET 111",
    "City": "WARSZAWA",
    "Branch": "",
    "Postcode": "00-102",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "HAND",
    "countryCode": "PL",
    "branchCode": "LPW",
    "SWIFT Code": "HANDPLPW",
    "Bank Name": "SVENSKA HANDELSBANKEN AB SPOLKA AKCYJNA ODDZIAL W POLSCE",
    "Address": "WOLOSKA 22",
    "City": "WARSZAWA",
    "Branch": "",
    "Postcode": "02-675",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "TOFN",
    "countryCode": "PL",
    "branchCode": "LPP",
    "SWIFT Code": "TOFNPLPP",
    "Bank Name": "TOWARZYSTWO FUNDUSZY INWESTYCYJNYCH PZU SA",
    "Address": "PZU PARK, RONDO IGNACEGO DASZYNSKIEGO 4",
    "City": "WARSZAWA",
    "Branch": "",
    "Postcode": "00-843",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "TOBA",
    "countryCode": "PL",
    "branchCode": "LPW",
    "SWIFT Code": "TOBAPLPW",
    "Bank Name": "TOYOTA BANK POLSKA S.A.",
    "Address": "ORION, POSTEPU 18B, FLOOR 3",
    "City": "WARSZAWA",
    "Branch": "",
    "Postcode": "02-676",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "WART",
    "countryCode": "PL",
    "branchCode": "LPW",
    "SWIFT Code": "WARTPLPW",
    "Bank Name": "TUIR WARTA S.A.",
    "Address": "RONDO I. DASZYNSKIEGO 1",
    "City": "WARSZAWA",
    "Branch": "",
    "Postcode": "00-843",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "PANX",
    "countryCode": "PL",
    "branchCode": "LP2",
    "SWIFT Code": "PANXPLP2",
    "Bank Name": "UNIFIEDPOST PAYMENTS JOINT STOCK COMPANY, BRANCH IN POLAND",
    "Address": "AL. ALEJE JEROZOLIMSKIE 123A",
    "City": "WARSZAWA",
    "Branch": "",
    "Postcode": "02-017",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "GBGC",
    "countryCode": "PL",
    "branchCode": "LPK",
    "SWIFT Code": "GBGCPLPK",
    "Bank Name": "VELOBANK S.A.",
    "Address": "THE WARSAW HUB, RONDO I. DASZYNSKIEGO 2C",
    "City": "WARSZAWA",
    "Branch": "",
    "Postcode": "00-843",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "VPAY",
    "countryCode": "PL",
    "branchCode": "LP2",
    "SWIFT Code": "VPAYPLP2",
    "Bank Name": "VIVA PAYMENT SERVICES SPOLKA AKCYJNA ODDZIAL W POLSCE",
    "Address": "VILLA METRO BUSINESS HOUSE, 145",
    "City": "WARSZAWA",
    "Branch": "",
    "Postcode": "02-715",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "VOWA",
    "countryCode": "PL",
    "branchCode": "LP9",
    "SWIFT Code": "VOWAPLP9",
    "Bank Name": "VOLKSWAGEN BANK GMBH SP.Z O.O. ODDZIAL W POLSCE",
    "Address": "RONDO ONZ 1",
    "City": "WARSZAWA",
    "Branch": "",
    "Postcode": "00-124",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "WSPD",
    "countryCode": "PL",
    "branchCode": "LPP",
    "SWIFT Code": "WSPDPLPP",
    "Bank Name": "WARMINSKO-MAZURSKI BANK SPOLDZIELCZY (WARMIA MASURIA COOPERATIVE BANK)",
    "Address": "UL. GIZEWIUSZA 2A",
    "City": "PISZ",
    "Branch": "",
    "Postcode": "12-200",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "PTFI",
    "countryCode": "PL",
    "branchCode": "FGM",
    "SWIFT Code": "PTFIPLPWFGM",
    "Bank Name": "PKO TOWARZYSTWO FUNDUSZY INWESTYCYJNYCH SA",
    "Address": "UL CHLODNA 52",
    "City": "WARSZAWA",
    "Branch": "PKO GLOBALNEJ MAKROEKONOMII FIZ",
    "Postcode": "00-872",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "PTFI",
    "countryCode": "PL",
    "branchCode": "FGS",
    "SWIFT Code": "PTFIPLPWFGS",
    "Bank Name": "PKO TOWARZYSTWO FUNDUSZY INWESTYCYJNYCH SA",
    "Address": "UL CHLODNA 52",
    "City": "WARSZAWA",
    "Branch": "PKO GLOBALNEJ STRATEGII FIZ",
    "Postcode": "00-872",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "PTFI",
    "countryCode": "PL",
    "branchCode": "FMS",
    "SWIFT Code": "PTFIPLPWFMS",
    "Bank Name": "PKO TOWARZYSTWO FUNDUSZY INWESTYCYJNYCH SA",
    "Address": "UL CHLODNA 52",
    "City": "WARSZAWA",
    "Branch": "PKO MULTI STRATEGIA FIZ",
    "Postcode": "00-872",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "PTFI",
    "countryCode": "PL",
    "branchCode": "FNK",
    "SWIFT Code": "PTFIPLPWFNK",
    "Bank Name": "PKO TOWARZYSTWO FUNDUSZY INWESTYCYJNYCH SA",
    "Address": "UL CHLODNA 52",
    "City": "WARSZAWA",
    "Branch": "PKO NIERUCHOMOSCI KOMERCYJNYCH FIZAN",
    "Postcode": "00-872",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "PTFI",
    "countryCode": "PL",
    "branchCode": "FOW",
    "SWIFT Code": "PTFIPLPWFOW",
    "Bank Name": "PKO TOWARZYSTWO FUNDUSZY INWESTYCYJNYCH SA",
    "Address": "UL CHLODNA 52",
    "City": "WARSZAWA",
    "Branch": "PKO OBLIGACJI WYSOKODOCHODOWYCH GLOBALNY",
    "Postcode": "00-872",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "PTFI",
    "countryCode": "PL",
    "branchCode": "ADG",
    "SWIFT Code": "PTFIPLPWADG",
    "Bank Name": "PKO TOWARZYSTWO FUNDUSZY INWESTYCYJNYCH SA",
    "Address": "UL CHLODNA 52",
    "City": "WARSZAWA",
    "Branch": "PKO PARASOLOWY FIO SUBFUNDUSZ PKO AKCJI DYWIDENDOWYCH GLOBALNY",
    "Postcode": "00-872",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "PTFI",
    "countryCode": "PL",
    "branchCode": "AMS",
    "SWIFT Code": "PTFIPLPWAMS",
    "Bank Name": "PKO TOWARZYSTWO FUNDUSZY INWESTYCYJNYCH SA",
    "Address": "UL CHLODNA 52",
    "City": "WARSZAWA",
    "Branch": "PKO PARASOLOWY FIO SUBFUNDUSZ PKO AKCJI MALYCH I SREDNICH SPOLEK",
    "Postcode": "00-872",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "PTFI",
    "countryCode": "PL",
    "branchCode": "FAP",
    "SWIFT Code": "PTFIPLPWFAP",
    "Bank Name": "PKO TOWARZYSTWO FUNDUSZY INWESTYCYJNYCH SA",
    "Address": "UL CHLODNA 52",
    "City": "WARSZAWA",
    "Branch": "PKO PARASOLOWY FIO SUBFUNDUSZ PKO AKCJI PLUS",
    "Postcode": "00-872",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "PTFI",
    "countryCode": "PL",
    "branchCode": "ARW",
    "SWIFT Code": "PTFIPLPWARW",
    "Bank Name": "PKO TOWARZYSTWO FUNDUSZY INWESTYCYJNYCH SA",
    "Address": "UL CHLODNA 52",
    "City": "WARSZAWA",
    "Branch": "PKO PARASOLOWY FIO SUBFUNDUSZ PKO AKCJI RYNKOW WSCHODZACYCH",
    "Postcode": "00-872",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "PTFI",
    "countryCode": "PL",
    "branchCode": "ARA",
    "SWIFT Code": "PTFIPLPWARA",
    "Bank Name": "PKO TOWARZYSTWO FUNDUSZY INWESTYCYJNYCH SA",
    "Address": "UL CHLODNA 52",
    "City": "WARSZAWA",
    "Branch": "PKO PARASOLOWY FIO SUBFUNDUSZ PKO AKCJI RYNKU AMERYKANSKIEGO",
    "Postcode": "00-872",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "PTFI",
    "countryCode": "PL",
    "branchCode": "AAP",
    "SWIFT Code": "PTFIPLPWAAP",
    "Bank Name": "PKO TOWARZYSTWO FUNDUSZY INWESTYCYJNYCH SA",
    "Address": "UL CHLODNA 52",
    "City": "WARSZAWA",
    "Branch": "PKO PARASOLOWY FIO SUBFUNDUSZ PKO AKCJI RYNKU AZJI I PACYFIKU",
    "Postcode": "00-872",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "PTFI",
    "countryCode": "PL",
    "branchCode": "ARE",
    "SWIFT Code": "PTFIPLPWARE",
    "Bank Name": "PKO TOWARZYSTWO FUNDUSZY INWESTYCYJNYCH SA",
    "Address": "UL CHLODNA 52",
    "City": "WARSZAWA",
    "Branch": "PKO PARASOLOWY FIO SUBFUNDUSZ PKO AKCJI RYNKU EUROPEJSKIEGO",
    "Postcode": "00-872",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "PTFI",
    "countryCode": "PL",
    "branchCode": "ARJ",
    "SWIFT Code": "PTFIPLPWARJ",
    "Bank Name": "PKO TOWARZYSTWO FUNDUSZY INWESTYCYJNYCH SA",
    "Address": "UL CHLODNA 52",
    "City": "WARSZAWA",
    "Branch": "PKO PARASOLOWY FIO SUBFUNDUSZ PKO AKCJI RYNKU JAPONSKIEGO",
    "Postcode": "00-872",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "PTFI",
    "countryCode": "PL",
    "branchCode": "ARZ",
    "SWIFT Code": "PTFIPLPWARZ",
    "Bank Name": "PKO TOWARZYSTWO FUNDUSZY INWESTYCYJNYCH SA",
    "Address": "UL CHLODNA 52",
    "City": "WARSZAWA",
    "Branch": "PKO PARASOLOWY FIO SUBFUNDUSZ PKO AKCJI RYNKU ZLOTA",
    "Postcode": "00-872",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "PTFI",
    "countryCode": "PL",
    "branchCode": "FDL",
    "SWIFT Code": "PTFIPLPWFDL",
    "Bank Name": "PKO TOWARZYSTWO FUNDUSZY INWESTYCYJNYCH SA",
    "Address": "UL CHLODNA 52",
    "City": "WARSZAWA",
    "Branch": "PKO PARASOLOWY FIO SUBFUNDUSZ PKO DOBR LUKSUSOWYCH GLOBALNY",
    "Postcode": "00-872",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "PTFI",
    "countryCode": "PL",
    "branchCode": "EOS",
    "SWIFT Code": "PTFIPLPWEOS",
    "Bank Name": "PKO TOWARZYSTWO FUNDUSZY INWESTYCYJNYCH SA",
    "Address": "UL CHLODNA 52",
    "City": "WARSZAWA",
    "Branch": "PKO PARASOLOWY FIO SUBFUNDUSZ PKO EKOLOGII I ODPOWIEDZIALNOSCI SPL",
    "Postcode": "00-872",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "PTFI",
    "countryCode": "PL",
    "branchCode": "GPL",
    "SWIFT Code": "PTFIPLPWGPL",
    "Bank Name": "PKO TOWARZYSTWO FUNDUSZY INWESTYCYJNYCH SA",
    "Address": "UL CHLODNA 52",
    "City": "WARSZAWA",
    "Branch": "PKO PARASOLOWY FIO SUBFUNDUSZ PKO GAMMA PLUS",
    "Postcode": "00-872",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "PTFI",
    "countryCode": "PL",
    "branchCode": "FIB",
    "SWIFT Code": "PTFIPLPWFIB",
    "Bank Name": "PKO TOWARZYSTWO FUNDUSZY INWESTYCYJNYCH SA",
    "Address": "UL CHLODNA 52",
    "City": "WARSZAWA",
    "Branch": "PKO PARASOLOWY FIO SUBFUNDUSZ PKO INFRASTRUKTURY BUDOWNICTWA GLOBAL",
    "Postcode": "00-872",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "PTFI",
    "countryCode": "PL",
    "branchCode": "MDG",
    "SWIFT Code": "PTFIPLPWMDG",
    "Bank Name": "PKO TOWARZYSTWO FUNDUSZY INWESTYCYJNYCH SA",
    "Address": "UL CHLODNA 52",
    "City": "WARSZAWA",
    "Branch": "PKO PARASOLOWY FIO SUBFUNDUSZ PKO MEDYCYNY I DEMOGRAFII GLOBALNY",
    "Postcode": "00-872",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "PTFI",
    "countryCode": "PL",
    "branchCode": "FOD",
    "SWIFT Code": "PTFIPLPWFOD",
    "Bank Name": "PKO TOWARZYSTWO FUNDUSZY INWESTYCYJNYCH SA",
    "Address": "UL CHLODNA 52",
    "City": "WARSZAWA",
    "Branch": "PKO PARASOLOWY FIO SUBFUNDUSZ PKO OBLIGACJI DLUGOTERMINOWYCH",
    "Postcode": "00-872",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "PTFI",
    "countryCode": "PL",
    "branchCode": "OBG",
    "SWIFT Code": "PTFIPLPWOBG",
    "Bank Name": "PKO TOWARZYSTWO FUNDUSZY INWESTYCYJNYCH SA",
    "Address": "UL CHLODNA 52",
    "City": "WARSZAWA",
    "Branch": "PKO PARASOLOWY FIO SUBFUNDUSZ PKO OBLIGACJI GLOBALNY",
    "Postcode": "00-872",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "PTFI",
    "countryCode": "PL",
    "branchCode": "ORP",
    "SWIFT Code": "PTFIPLPWORP",
    "Bank Name": "PKO TOWARZYSTWO FUNDUSZY INWESTYCYJNYCH SA",
    "Address": "UL CHLODNA 52",
    "City": "WARSZAWA",
    "Branch": "PKO PARASOLOWY FIO SUBFUNDUSZ PKO OBLIGACJI RYNKU POLSKIEGO",
    "Postcode": "00-872",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "PTFI",
    "countryCode": "PL",
    "branchCode": "FOS",
    "SWIFT Code": "PTFIPLPWFOS",
    "Bank Name": "PKO TOWARZYSTWO FUNDUSZY INWESTYCYJNYCH SA",
    "Address": "UL CHLODNA 52",
    "City": "WARSZAWA",
    "Branch": "PKO PARASOLOWY FIO SUBFUNDUSZ PKO OBLIGACJI SAMORZADOWYCH",
    "Postcode": "00-872",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "PTFI",
    "countryCode": "PL",
    "branchCode": "DUS",
    "SWIFT Code": "PTFIPLPWDUS",
    "Bank Name": "PKO TOWARZYSTWO FUNDUSZY INWESTYCYJNYCH SA",
    "Address": "UL CHLODNA 52",
    "City": "WARSZAWA",
    "Branch": "PKO PARASOLOWY FIO SUBFUNDUSZ PKO PAPIEROW DLUZNYCH USD",
    "Postcode": "00-872",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "PTFI",
    "countryCode": "PL",
    "branchCode": "FSK",
    "SWIFT Code": "PTFIPLPWFSK",
    "Bank Name": "PKO TOWARZYSTWO FUNDUSZY INWESTYCYJNYCH SA",
    "Address": "UL CHLODNA 52",
    "City": "WARSZAWA",
    "Branch": "PKO PARASOLOWY FIO SUBFUNDUSZ PKO SKARBOWY",
    "Postcode": "00-872",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "PTFI",
    "countryCode": "PL",
    "branchCode": "FSW",
    "SWIFT Code": "PTFIPLPWFSW",
    "Bank Name": "PKO TOWARZYSTWO FUNDUSZY INWESTYCYJNYCH SA",
    "Address": "UL CHLODNA 52",
    "City": "WARSZAWA",
    "Branch": "PKO PARASOLOWY FIO SUBFUNDUSZ PKO STABILNEGO WZROSTU",
    "Postcode": "00-872",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "PTFI",
    "countryCode": "PL",
    "branchCode": "SUR",
    "SWIFT Code": "PTFIPLPWSUR",
    "Bank Name": "PKO TOWARZYSTWO FUNDUSZY INWESTYCYJNYCH SA",
    "Address": "UL CHLODNA 52",
    "City": "WARSZAWA",
    "Branch": "PKO PARASOLOWY FIO SUBFUNDUSZ PKO SUROWCOW GLOBALNY",
    "Postcode": "00-872",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "PTFI",
    "countryCode": "PL",
    "branchCode": "ECH",
    "SWIFT Code": "PTFIPLPWECH",
    "Bank Name": "PKO TOWARZYSTWO FUNDUSZY INWESTYCYJNYCH SA",
    "Address": "UL CHLODNA 52",
    "City": "WARSZAWA",
    "Branch": "PKO PARASOLOWY FIO SUBFUNDUSZ PKO TECHNOLOGII I INNOWACJI GLOBALNY",
    "Postcode": "00-872",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "PTFI",
    "countryCode": "PL",
    "branchCode": "DIA",
    "SWIFT Code": "PTFIPLPWDIA",
    "Bank Name": "PKO TOWARZYSTWO FUNDUSZY INWESTYCYJNYCH SA",
    "Address": "UL CHLODNA 52",
    "City": "WARSZAWA",
    "Branch": "PKO PORTFELE INWESTYCYJNE - SFIO SUBFUNDUSZ PKO DIAMENTOWY",
    "Postcode": "00-872",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "PTFI",
    "countryCode": "PL",
    "branchCode": "RUB",
    "SWIFT Code": "PTFIPLPWRUB",
    "Bank Name": "PKO TOWARZYSTWO FUNDUSZY INWESTYCYJNYCH SA",
    "Address": "UL CHLODNA 52",
    "City": "WARSZAWA",
    "Branch": "PKO PORTFELE INWESTYCYJNE - SFIO SUBFUNDUSZ PKO RUBINOWY",
    "Postcode": "00-872",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "PTFI",
    "countryCode": "PL",
    "branchCode": "SZA",
    "SWIFT Code": "PTFIPLPWSZA",
    "Bank Name": "PKO TOWARZYSTWO FUNDUSZY INWESTYCYJNYCH SA",
    "Address": "UL CHLODNA 52",
    "City": "WARSZAWA",
    "Branch": "PKO PORTFELE INWESTYCYJNE - SFIO SUBFUNDUSZ PKO SZAFIROWY",
    "Postcode": "00-872",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "PTFI",
    "countryCode": "PL",
    "branchCode": "SZM",
    "SWIFT Code": "PTFIPLPWSZM",
    "Bank Name": "PKO TOWARZYSTWO FUNDUSZY INWESTYCYJNYCH SA",
    "Address": "UL CHLODNA 52",
    "City": "WARSZAWA",
    "Branch": "PKO PORTFELE INWESTYCYJNE - SFIO SUBFUNDUSZ PKO SZMARAGDOWY",
    "Postcode": "00-872",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "PTFI",
    "countryCode": "PL",
    "branchCode": "SIG",
    "SWIFT Code": "PTFIPLPWSIG",
    "Bank Name": "PKO TOWARZYSTWO FUNDUSZY INWESTYCYJNYCH SA",
    "Address": "UL CHLODNA 52",
    "City": "WARSZAWA",
    "Branch": "PKO SPOLEK INNOWACYJNYCH GLOBALNY FIZ",
    "Postcode": "00-872",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "PTFI",
    "countryCode": "PL",
    "branchCode": "FSD",
    "SWIFT Code": "PTFIPLPWFSD",
    "Bank Name": "PKO TOWARZYSTWO FUNDUSZY INWESTYCYJNYCH SA",
    "Address": "UL CHLODNA 52",
    "City": "WARSZAWA",
    "Branch": "PKO STRATEGII DLUZNYCH FIZ",
    "Postcode": "00-872",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "PTFI",
    "countryCode": "PL",
    "branchCode": "FSO",
    "SWIFT Code": "PTFIPLPWFSO",
    "Bank Name": "PKO TOWARZYSTWO FUNDUSZY INWESTYCYJNYCH SA",
    "Address": "UL CHLODNA 52",
    "City": "WARSZAWA",
    "Branch": "PKO STRATEGII OBLIGACYJNYCH FIZ",
    "Postcode": "00-872",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "PTFI",
    "countryCode": "PL",
    "branchCode": "FSF",
    "SWIFT Code": "PTFIPLPWFSF",
    "Bank Name": "PKO TOWARZYSTWO FUNDUSZY INWESTYCYJNYCH SA",
    "Address": "UL CHLODNA 52",
    "City": "WARSZAWA",
    "Branch": "PKO VC FIZAN  SUBFUNDUSZ FINANSOWY",
    "Postcode": "00-872",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "PTFI",
    "countryCode": "PL",
    "branchCode": "FSS",
    "SWIFT Code": "PTFIPLPWFSS",
    "Bank Name": "PKO TOWARZYSTWO FUNDUSZY INWESTYCYJNYCH SA",
    "Address": "UL CHLODNA 52",
    "City": "WARSZAWA",
    "Branch": "PKO VC FIZAN  SUBFUNDUSZ STRATEGICZNY",
    "Postcode": "00-872",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "PTFI",
    "countryCode": "PL",
    "branchCode": "BUR",
    "SWIFT Code": "PTFIPLPWBUR",
    "Bank Name": "PKO TOWARZYSTWO FUNDUSZY INWESTYCYJNYCH SA",
    "Address": "UL CHLODNA 52",
    "City": "WARSZAWA",
    "Branch": "PORTFELE INWESTYCYJNE - SFIO SUBFUNDUSZ PKO BURSZTYNOWY",
    "Postcode": "00-872",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "PTFI",
    "countryCode": "PL",
    "branchCode": "E70",
    "SWIFT Code": "PTFIPLPWE70",
    "Bank Name": "PKO TOWARZYSTWO FUNDUSZY INWESTYCYJNYCH SA",
    "Address": "UL CHLODNA 52",
    "City": "WARSZAWA",
    "Branch": "SUBFUNDUSZ PKO ZABEZPIECZENIA EMERYTALNEGO 2070",
    "Postcode": "00-872",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "PTFI",
    "countryCode": "PL",
    "branchCode": "E20",
    "SWIFT Code": "PTFIPLPWE20",
    "Bank Name": "PKO TOWARZYSTWO FUNDUSZY INWESTYCYJNYCH SA",
    "Address": "UL CHLODNA 52",
    "City": "WARSZAWA",
    "Branch": "ZEBEZPIECZENIA EMERYTALNEGO FIO SUBFUNDUSZ PKO ZABEZPIECZENIA EME",
    "Postcode": "00-872",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "PTFI",
    "countryCode": "PL",
    "branchCode": "E30",
    "SWIFT Code": "PTFIPLPWE30",
    "Bank Name": "PKO TOWARZYSTWO FUNDUSZY INWESTYCYJNYCH SA",
    "Address": "UL CHLODNA 52",
    "City": "WARSZAWA",
    "Branch": "ZEBEZPIECZENIA EMERYTALNEGO FIO SUBFUNDUSZ PKO ZABEZPIECZENIA EME",
    "Postcode": "00-872",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "PTFI",
    "countryCode": "PL",
    "branchCode": "E40",
    "SWIFT Code": "PTFIPLPWE40",
    "Bank Name": "PKO TOWARZYSTWO FUNDUSZY INWESTYCYJNYCH SA",
    "Address": "UL CHLODNA 52",
    "City": "WARSZAWA",
    "Branch": "ZEBEZPIECZENIA EMERYTALNEGO FIO SUBFUNDUSZ PKO ZABEZPIECZENIA EME",
    "Postcode": "00-872",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "PTFI",
    "countryCode": "PL",
    "branchCode": "E50",
    "SWIFT Code": "PTFIPLPWE50",
    "Bank Name": "PKO TOWARZYSTWO FUNDUSZY INWESTYCYJNYCH SA",
    "Address": "UL CHLODNA 52",
    "City": "WARSZAWA",
    "Branch": "ZEBEZPIECZENIA EMERYTALNEGO FIO SUBFUNDUSZ PKO ZABEZPIECZENIA EME",
    "Postcode": "00-872",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "PTFI",
    "countryCode": "PL",
    "branchCode": "E60",
    "SWIFT Code": "PTFIPLPWE60",
    "Bank Name": "PKO TOWARZYSTWO FUNDUSZY INWESTYCYJNYCH SA",
    "Address": "UL CHLODNA 52",
    "City": "WARSZAWA",
    "Branch": "ZEBEZPIECZENIA EMERYTALNEGO FIO SUBFUNDUSZ PKO ZABEZPIECZENIA EME",
    "Postcode": "00-872",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "IVSE",
    "countryCode": "PL",
    "branchCode": "LPP",
    "SWIFT Code": "IVSEPLPP",
    "Bank Name": "PLUS BANK S.A.",
    "Address": "AL. STANOW ZJEDNOCZONYCH 61A",
    "City": "WARSZAWA",
    "Branch": "HEAD OFFICE",
    "Postcode": "04-028",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "POCZ",
    "countryCode": "PL",
    "branchCode": "LP4",
    "SWIFT Code": "POCZPLP4",
    "Bank Name": "POCZTOWY BANK SA",
    "Address": "JAGIELLONSKA 17",
    "City": "BYDGOSZCZ",
    "Branch": "",
    "Postcode": "85-959",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "BLIK",
    "countryCode": "PL",
    "branchCode": "LPW",
    "SWIFT Code": "BLIKPLPW",
    "Bank Name": "POLSKI STANDARD PLATNOSCI SP. Z O.O.",
    "Address": "CZERNIAKOWSKA X20, 97A, FLOOR 2",
    "City": "WARSZAWA",
    "Branch": "",
    "Postcode": "00-718",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "PZUZ",
    "countryCode": "PL",
    "branchCode": "LPP",
    "SWIFT Code": "PZUZPLPP",
    "Bank Name": "POWSZECHNY ZAKLAD UBEZPIECZEN NA ZYCIE SPOLKA AKCYJNA",
    "Address": "PZU PARK, RONDO IGNACEGO DASZYNSKIEGO 4",
    "City": "WARSZAWA",
    "Branch": "",
    "Postcode": "00-843",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "PZUS",
    "countryCode": "PL",
    "branchCode": "LPP",
    "SWIFT Code": "PZUSPLPP",
    "Bank Name": "POWSZECHNY ZAKLAD UBEZPIECZEN SPOLKA AKCYJNA",
    "Address": "PZU PARK, RONDO IGNACEGO DASZYNSKIEGO 4",
    "City": "WARSZAWA",
    "Branch": "",
    "Postcode": "00-843",
    "Country": "Poland",
    "Connection": "Active"
  },
  {
    "bankCode": "PSAT",
    "countryCode": "PL",
    "branchCode": "LPW",
    "SWIFT Code": "PSATPLPW",
    "Bank Name": "PROSERVICE FINTECO SP Z O.O.",
    "Address": "KONSTRUKTORSKA 12A",
    "City": "WARSZAWA",
    "Branch": "",
    "Postcode": "02-673",
    "Country": "Poland",
    "Connection": "Active"
  }
]
module.exports = poland
