const portugal = [
  {
    "countryCode": "BESC",
    "bankCode": "PT",
    "branchCode": "OPR",
    "SWIFT Code": "BESCPTPLOPR",
    "Bank Name": "NOVO BANCO, SA",
    "Address": "RUA JOSE FALCAO 176",
    "City": "PORTO",
    "Branch": "",
    "Postcode": "4050-314",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "OGEU",
    "bankCode": "PT",
    "branchCode": "TPM",
    "SWIFT Code": "OGEUPTPM",
    "Bank Name": "OFERTA GENUINA, S.A.",
    "Address": "RUA DO OUTEIRO 589",
    "City": "MAIA",
    "Branch": "",
    "Postcode": "4475-150",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "OMIC",
    "bankCode": "PT",
    "branchCode": "TPL",
    "SWIFT Code": "OMICPTPL",
    "Bank Name": "OMICLEAR,C.C.,S.A.",
    "Address": "AVENIDA CASAL RIBEIRO 14 8",
    "City": "LISBON",
    "Branch": "",
    "Postcode": "1000-092",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "OMIC",
    "bankCode": "PT",
    "branchCode": "CLI",
    "SWIFT Code": "OMICPTPLCLI",
    "Bank Name": "OMICLEAR,C.C.,S.A.",
    "Address": "AV. CASAL RIBEIRO 8, FLOOR 14",
    "City": "LISBON",
    "Branch": "",
    "Postcode": "1000-092",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "OMIC",
    "bankCode": "PT",
    "branchCode": "ASA",
    "SWIFT Code": "OMICPTPLASA",
    "Bank Name": "OMICLEAR,C.C.,S.A.",
    "Address": "AV. CASAL RIBEIRO 14, FLOOR 8",
    "City": "LISBON",
    "Branch": "ANCILLARY SYSTEM ACCOUNT",
    "Postcode": "1000-092",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "PSTI",
    "bankCode": "PT",
    "branchCode": "TPM",
    "SWIFT Code": "PSTIPTPM",
    "Bank Name": "PAUL STRICKER, S.A.",
    "Address": "NUCLEO INDUSTRIAL 5",
    "City": "MURTEDE",
    "Branch": "",
    "Postcode": "3060-372",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "RENC",
    "bankCode": "PT",
    "branchCode": "TPL",
    "SWIFT Code": "RENCPTPL",
    "Bank Name": "REN - REN ELETRICA NACIONAL SA",
    "Address": "AV. ESTADOS UNIDOS DA AMERICA 55,, FLOOR 7",
    "City": "LISBON",
    "Branch": "",
    "Postcode": "1749-061",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "REVO",
    "bankCode": "PT",
    "branchCode": "TP2",
    "SWIFT Code": "REVOPTP2",
    "Bank Name": "REVOLUT BANK UAB - SUCURSAL EM PORTUGAL",
    "Address": "SITIO RUA DO CAMPO ALEGRE 774",
    "City": "PORTO",
    "Branch": "",
    "Postcode": "4150-171",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "ASAO",
    "bankCode": "PT",
    "branchCode": "TPP",
    "SWIFT Code": "ASAOPTPP",
    "Bank Name": "ROVENSA, S.A.",
    "Address": "EDIFICIO LUMNIA, RUA DA CEN N61, 5B",
    "City": "LISBON",
    "Branch": "",
    "Postcode": "1990-207",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "SISR",
    "bankCode": "PT",
    "branchCode": "TPL",
    "SWIFT Code": "SISRPTPL",
    "Bank Name": "SIBS FORWARD PAYMENT SOLUTIONS SA",
    "Address": "LOTE 1, RUA SOEIRO PEREIRA GOMES",
    "City": "LISBON",
    "Branch": "",
    "Postcode": "1600-024",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "SIEO",
    "bankCode": "PT",
    "branchCode": "TPP",
    "SWIFT Code": "SIEOPTPP",
    "Bank Name": "SIERRA PORTUGAL",
    "Address": "TORRE COLOMBO OCIDENTE, RUA GALILEU GALILEI 2, FLOOR 3",
    "City": "LISBON",
    "Branch": "",
    "Postcode": "1500-392",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "SGFP",
    "bankCode": "PT",
    "branchCode": "TPL",
    "SWIFT Code": "SGFPPTPL",
    "Bank Name": "SOCIEDADE GESTORA DOS FUNDOS DE PENSOES DO BANCO DE PORTUGAL S.A.",
    "Address": "AV DA REPUBLICA 57, FLOOR 7",
    "City": "LISBON",
    "Branch": "",
    "Postcode": "1050-189",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "SGFP",
    "bankCode": "PT",
    "branchCode": "PBD",
    "SWIFT Code": "SGFPPTPLPBD",
    "Bank Name": "SOCIEDADE GESTORA DOS FUNDOS DE PENSOES DO BANCO DE PORTUGAL S.A.",
    "Address": "AV DA REPUBLICA 57, FLOOR 7",
    "City": "LISBON",
    "Branch": "FUNDO DE PENSOES DO BANCO DE PORTUGAL - BENEFICIO DEFINIDO",
    "Postcode": "1050-189",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "SGFP",
    "bankCode": "PT",
    "branchCode": "PCD",
    "SWIFT Code": "SGFPPTPLPCD",
    "Bank Name": "SOCIEDADE GESTORA DOS FUNDOS DE PENSOES DO BANCO DE PORTUGAL S.A.",
    "Address": "AV DA REPUBLICA 57, FLOOR 7",
    "City": "LISBON",
    "Branch": "FUNDO DE PENSOES DO BANCO DE PORTUGAL - CONTRIBUICAO DEFINIDA",
    "Postcode": "1050-189",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "SORP",
    "bankCode": "PT",
    "branchCode": "TPL",
    "SWIFT Code": "SORPPTPL",
    "Bank Name": "SOVENA GROUP SGPS",
    "Address": "EDIFICIO ARQUIPARQUE 2 3, R. DR ANTONIO LOUREIRO BORGES 2, MIRAFLORES",
    "City": "ALGES",
    "Branch": "",
    "Postcode": "1495-131",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "POTC",
    "bankCode": "PT",
    "branchCode": "TPT",
    "SWIFT Code": "POTCPTPT",
    "Bank Name": "THE NAVIGATOR COMPANY SA",
    "Address": "APARTADO 55, MITRENA",
    "City": "SETUBAL",
    "Branch": "",
    "Postcode": "2901-861",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "UNNG",
    "bankCode": "PT",
    "branchCode": "TP2",
    "SWIFT Code": "UNNGPTP2",
    "Bank Name": "UNICAMBIO - INSTITUICAO DE PAGAMENTO, S.A.",
    "Address": "AEROPORTO DE LISBOA - EDIFICIO 124, RUA C, FLOOR 5",
    "City": "LISBON",
    "Branch": "",
    "Postcode": "1700-008",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "PANX",
    "bankCode": "PT",
    "branchCode": "TP2",
    "SWIFT Code": "PANXPTP2",
    "Bank Name": "UNIFIEDPOST PAYMENTS  BRANCH IN PORTUGAL",
    "Address": "AV. DA LIBERDADE 110",
    "City": "LISBON",
    "Branch": "",
    "Postcode": "1269-046",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "VPAY",
    "bankCode": "PT",
    "branchCode": "TP2",
    "SWIFT Code": "VPAYPTP2",
    "Bank Name": "VIVA PAYMENT SERVICES S.A. SUCURSAL EM PORTUGAL",
    "Address": "EDIFICIO FUNDACAO, RUA BARATA SALGUEIRO 2 ESQUERDO 30",
    "City": "LISBON",
    "Branch": "",
    "Postcode": "1250-044",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "WZNK",
    "bankCode": "PT",
    "branchCode": "TPL",
    "SWIFT Code": "WZNKPTPL",
    "Bank Name": "WIZINK BANK S.A.U. SUCURSAL EM PORTUGAL",
    "Address": "AV. COLEGIO MILITAR 37 F, FLOOR 6 D",
    "City": "LISBON",
    "Branch": "",
    "Postcode": "1500-180",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "WZNK",
    "bankCode": "PT",
    "branchCode": "SCO",
    "SWIFT Code": "WZNKPTPLSCO",
    "Bank Name": "WIZINK BANK S.A.U. SUCURSAL EM PORTUGAL",
    "Address": "AV. COLEGIO MILITAR 37F, FLOOR 6 D",
    "City": "LISBON",
    "Branch": "",
    "Postcode": "1500-180",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "ZURI",
    "bankCode": "PT",
    "branchCode": "TPL",
    "SWIFT Code": "ZURIPTPL",
    "Bank Name": "ZURICH-COMPANHIA DE SEGUROS S.A.",
    "Address": "EDIFICIO ZURICH, RUA BARATA SALGUEIRO 41",
    "City": "LISBON",
    "Branch": "",
    "Postcode": "1269-058",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "CDCT",
    "bankCode": "PT",
    "branchCode": "TP2",
    "SWIFT Code": "CDCTPTP2",
    "Bank Name": "CAIXA DE CREDITO DE LEIRIA",
    "Address": "LARGO CANDIDO DOS REIS 19 A 25",
    "City": "LEIRIA",
    "Branch": "",
    "Postcode": "2400-801",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "CDCT",
    "bankCode": "PT",
    "branchCode": "SIC",
    "SWIFT Code": "CDCTPTP2SIC",
    "Bank Name": "CAIXA DE CREDITO DE LEIRIA",
    "Address": "LARGO CANDIDO DOS REIS 19 A 25",
    "City": "LEIRIA",
    "Branch": "CCAML SICOI GUARANTEE MECHANISM",
    "Postcode": "2400-801",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "CEMA",
    "bankCode": "PT",
    "branchCode": "TP2",
    "SWIFT Code": "CEMAPTP2",
    "Bank Name": "CAIXA ECONOMICA DA MISERICORDIA DE ANGRA DO HEROISMO",
    "Address": "RUA DIREITA 118",
    "City": "ANGRA DO HEROISMO",
    "Branch": "",
    "Postcode": "9700-011",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "CEMA",
    "bankCode": "PT",
    "branchCode": "SIC",
    "SWIFT Code": "CEMAPTP2SIC",
    "Bank Name": "CAIXA ECONOMICA DA MISERICORDIA DE ANGRA DO HEROISMO",
    "Address": "RUA DIREITA 118",
    "City": "ANGRA DO HEROISMO",
    "Branch": "BIC ASSOCIADO SICOI",
    "Postcode": "9700-011",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "MPIO",
    "bankCode": "PT",
    "branchCode": "TIT",
    "SWIFT Code": "MPIOPTPLTIT",
    "Bank Name": "CAIXA ECONOMICA MONTEPIO GERAL, CAIXA ECONOMICA BANCARIA, SA",
    "Address": "RUA JOAO CHAGAS 53, FLOOR 0",
    "City": "ALGES",
    "Branch": "SERVICIO TITULOS",
    "Postcode": "1495-072",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "MPIO",
    "bankCode": "PT",
    "branchCode": "TPL",
    "SWIFT Code": "MPIOPTPL",
    "Bank Name": "CAIXA ECONOMICA MONTEPIO GERAL, CAIXA ECONOMICA BANCARIA, SA",
    "Address": "RUA CASTILHO 5, FLOOR 10",
    "City": "LISBON",
    "Branch": "",
    "Postcode": "1250-066",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "MPIO",
    "bankCode": "PT",
    "branchCode": "SIC",
    "SWIFT Code": "MPIOPTPLSIC",
    "Bank Name": "CAIXA ECONOMICA MONTEPIO GERAL, CAIXA ECONOMICA BANCARIA, SA",
    "Address": "RUA CASTILHO 5, FLOOR 10",
    "City": "LISBON",
    "Branch": "SICOI BRANCH FOR MPIOPTPL",
    "Postcode": "1250-066",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "CGDI",
    "bankCode": "PT",
    "branchCode": "OSF",
    "SWIFT Code": "CGDIPTPLOSF",
    "Bank Name": "CAIXA GERAL DE DEPOSITOS",
    "Address": "AVENIDA ARRIAGA 17, FLOOR 3",
    "City": "FUNCHAL",
    "Branch": "MADEIRA OFFSHORE BRANCH",
    "Postcode": "9000-059",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "CGDI",
    "bankCode": "PT",
    "branchCode": "TPL",
    "SWIFT Code": "CGDIPTPL",
    "Bank Name": "CAIXA GERAL DE DEPOSITOS",
    "Address": "AVENIDA JOAO XXI 63",
    "City": "LISBON",
    "Branch": "",
    "Postcode": "1000-300",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "CGDI",
    "bankCode": "PT",
    "branchCode": "MRS",
    "SWIFT Code": "CGDIPTPLMRS",
    "Bank Name": "CAIXA GERAL DE DEPOSITOS",
    "Address": "AVENIDA JOAO XXL 63",
    "City": "LISBON",
    "Branch": "CGD TARGET MECANISMO DE RISCO SICOI",
    "Postcode": "1000-300",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "CGDI",
    "bankCode": "PT",
    "branchCode": "OPR",
    "SWIFT Code": "CGDIPTPLOPR",
    "Bank Name": "CAIXA GERAL DE DEPOSITOS",
    "Address": "RUA CAMOES 139, FLOOR 6",
    "City": "PORTO",
    "Branch": "",
    "Postcode": "4000-265",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "BCOE",
    "bankCode": "PT",
    "branchCode": "TP2",
    "SWIFT Code": "BCOEPTP2",
    "Bank Name": "CAJA RURAL DEL SUR, SOCIEDAD COOPERATIVA DE CREDITO - SUCURSAL EM PORTUGAL",
    "Address": "RUA DR. CANDIDO GUERREIRO 55",
    "City": "FARO",
    "Branch": "",
    "Postcode": "8000-151",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "BCOE",
    "bankCode": "PT",
    "branchCode": "MGS",
    "SWIFT Code": "BCOEPTP2MGS",
    "Bank Name": "CAJA RURAL DEL SUR, SOCIEDAD COOPERATIVA DE CREDITO - SUCURSAL EM PORTUGAL",
    "Address": "RUA DR. CANDIDO GUERREIRO 55",
    "City": "FARO",
    "Branch": "",
    "Postcode": "8000-151",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "CGPS",
    "bankCode": "PT",
    "branchCode": "TPP",
    "SWIFT Code": "CGPSPTPP",
    "Bank Name": "CASAISINVEST SGPS S.A.",
    "Address": "R. DO ANJO 27",
    "City": "MIRE DE TIBAES",
    "Branch": "",
    "Postcode": "4700-565",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "CPHL",
    "bankCode": "PT",
    "branchCode": "TPL",
    "SWIFT Code": "CPHLPTPL",
    "Bank Name": "CIMPOR PORTUGAL HOLDINGS, SGPS, S.A.",
    "Address": "AVENIDA JOSE MALHOA 22",
    "City": "LISBON",
    "Branch": "",
    "Postcode": "1099-020",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "CITI",
    "bankCode": "PT",
    "branchCode": "SEC",
    "SWIFT Code": "CITIPTPXSEC",
    "Bank Name": "CITIBANK EUROPE PLC PORTUGAL BRANCH",
    "Address": "",
    "City": "LISBON",
    "Branch": "CITIBANK LISBON TARGET 2",
    "Postcode": "",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "CITI",
    "bankCode": "PT",
    "branchCode": "TPX",
    "SWIFT Code": "CITIPTPX",
    "Bank Name": "CITIBANK EUROPE PLC PORTUGAL BRANCH",
    "Address": "EDIFICIO FUNDACAO, RUA BARATA SALGUEIRO 30, FLOOR 5",
    "City": "LISBON",
    "Branch": "SUCURSAL EM PORTUGAL",
    "Postcode": "1269-056",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "LLIU",
    "bankCode": "PT",
    "branchCode": "TP2",
    "SWIFT Code": "LLIUPTP2",
    "Bank Name": "DE LAGE LANDEN INTERNATIONAL B.V. SUCURSAL EM PORTUGAL",
    "Address": "EDIFICIO QUINTA DA FONTE RUA DOS, MALHOES, D.MANUEL 1, FLOOR 1",
    "City": "PACO DE ARCOS",
    "Branch": "",
    "Postcode": "2770-071",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "DEUT",
    "bankCode": "PT",
    "branchCode": "FUN",
    "SWIFT Code": "DEUTPTPLFUN",
    "Bank Name": "DEUTSCHE BANK AG PORTUGAL BRANCH",
    "Address": "ED. MARINA CLUB, AV. ARRIAGA 73, FLOOR 2, SALA 209, ZONA FRANCA DA MADEIRA",
    "City": "FUNCHAL",
    "Branch": "SUCURSAL FINANCEIRA EXTERIOR - OFFSHORE",
    "Postcode": "9004-553",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "DEUT",
    "bankCode": "PT",
    "branchCode": "TPL",
    "SWIFT Code": "DEUTPTPL",
    "Bank Name": "DEUTSCHE BANK AG PORTUGAL BRANCH",
    "Address": "RUA CASTILHO 20",
    "City": "LISBON",
    "Branch": "",
    "Postcode": "1250-069",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "DEUT",
    "bankCode": "PT",
    "branchCode": "SIC",
    "SWIFT Code": "DEUTPTPLSIC",
    "Bank Name": "DEUTSCHE BANK AG PORTUGAL BRANCH",
    "Address": "",
    "City": "LISBON",
    "Branch": "SICOI",
    "Postcode": "",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "PRIB",
    "bankCode": "PT",
    "branchCode": "TPX",
    "SWIFT Code": "PRIBPTPX",
    "Bank Name": "EDMOND DE ROTHSCHILD EUROPE SUCURSAL PORTUGUESA",
    "Address": "RUA D. PEDRO V 130",
    "City": "LISBON",
    "Branch": "",
    "Postcode": "1250-095",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "EDEP",
    "bankCode": "PT",
    "branchCode": "TPP",
    "SWIFT Code": "EDEPPTPP",
    "Bank Name": "EDP - ENERGIAS DE PORTUGAL S.A.",
    "Address": "AV. 24 DE JULHO 12",
    "City": "LISBON",
    "Branch": "",
    "Postcode": "1249-300",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "EPOS",
    "bankCode": "PT",
    "branchCode": "TPP",
    "SWIFT Code": "EPOSPTPP",
    "Bank Name": "EFACEC POWER SOLUTIONS SGPS S.A.",
    "Address": "LUGAR DA ARROTEIA, LECA DO BALIO AND GUIFOES",
    "City": "MATOSINHOS",
    "Branch": "",
    "Postcode": "4465-587",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "FADI",
    "bankCode": "PT",
    "branchCode": "TPP",
    "SWIFT Code": "FADIPTPP",
    "Bank Name": "FASHION DIVISION S.A",
    "Address": "ESPIDO, VIA NORTE",
    "City": "MAIA",
    "Branch": "",
    "Postcode": "4470-177",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "FPEA",
    "bankCode": "PT",
    "branchCode": "TP2",
    "SWIFT Code": "FPEAPTP2",
    "Bank Name": "FINANCIERE DES PAIEMENTS ELECTRONIQUE SAS - SUCURSAL EM PORTUGAL",
    "Address": "TORRE OCIDENTE CENTRO COLOMBO, RUA GALILEU GALILEI 2, FLOOR 8",
    "City": "LISBON",
    "Branch": "",
    "Postcode": "1500-392",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "GAEG",
    "bankCode": "PT",
    "branchCode": "TPP",
    "SWIFT Code": "GAEGPTPP",
    "Bank Name": "GALP ENERGIA, SGPS S.A.",
    "Address": "TORRE C, RUA TOMAS DA FONSECA",
    "City": "LISBON",
    "Branch": "",
    "Postcode": "1600-209",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "GRPG",
    "bankCode": "PT",
    "branchCode": "TPP",
    "SWIFT Code": "GRPGPTPP",
    "Bank Name": "GRUPO PESTANA - S.G.P.S. S.A.",
    "Address": "LARGO ANTONIO NOBRE",
    "City": "FUNCHAL",
    "Branch": "",
    "Postcode": "9000-022",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "ESSI",
    "bankCode": "PT",
    "branchCode": "TPL",
    "SWIFT Code": "ESSIPTPL",
    "Bank Name": "HAITONG BANK, S.A.",
    "Address": "EDIFIZIO QUARTZO, RUA ALEXANDRE HERCULANO 38",
    "City": "LISBON",
    "Branch": "",
    "Postcode": "1050-040",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "ESSI",
    "bankCode": "PT",
    "branchCode": "SIC",
    "SWIFT Code": "ESSIPTPLSIC",
    "Bank Name": "HAITONG BANK, S.A.",
    "Address": "EDIFIZIO QUARTZO, RUA ALEXANDRE HERCULANO 38",
    "City": "LISBON",
    "Branch": "",
    "Postcode": "1269-161",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "HOVF",
    "bankCode": "PT",
    "branchCode": "TPT",
    "SWIFT Code": "HOVFPTPT",
    "Bank Name": "HOVIONE FARMACIENCIA SA",
    "Address": "SETE CASAS",
    "City": "LOURES",
    "Branch": "",
    "Postcode": "2674-506",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "IFLD",
    "bankCode": "PT",
    "branchCode": "TP2",
    "SWIFT Code": "IFLDPTP2",
    "Bank Name": "IFTHENPAY LDA",
    "Address": "RUA S. JOSE 771",
    "City": "SANTA MARIA DA FEIRA",
    "Branch": "",
    "Postcode": "4535-404",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "BBRU",
    "bankCode": "PT",
    "branchCode": "TPL",
    "SWIFT Code": "BBRUPTPL",
    "Bank Name": "ING BANK NV, SUCURSAL EM PORTUGAL",
    "Address": "AVENIDA DA LIBERDADE 200, FLOOR 6",
    "City": "LISBON",
    "Branch": "",
    "Postcode": "1250-147",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "BBRU",
    "bankCode": "PT",
    "branchCode": "MGS",
    "SWIFT Code": "BBRUPTPLMGS",
    "Bank Name": "ING BANK NV, SUCURSAL EM PORTUGAL",
    "Address": "AVENIDA DA LIBERDADE 200, FLOOR 6",
    "City": "LISBON",
    "Branch": "MECHANISM OF GUARANTEE SICOI",
    "Postcode": "1250-147",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "IBLS",
    "bankCode": "PT",
    "branchCode": "CUG",
    "SWIFT Code": "IBLSPTPPCUG",
    "Bank Name": "INTERBOLSA - S.G.S.L.S.C.V.M., S.A.",
    "Address": "AVENIDA DA BOAVISTA 3433",
    "City": "PORTO",
    "Branch": "",
    "Postcode": "4100-138",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "IBLS",
    "bankCode": "PT",
    "branchCode": "TPP",
    "SWIFT Code": "IBLSPTPP",
    "Bank Name": "INTERBOLSA - S.G.S.L.S.C.V.M., S.A.",
    "Address": "AVENIDA DA BOAVISTA 3433",
    "City": "PORTO",
    "Branch": "",
    "Postcode": "4100-138",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "IBLS",
    "bankCode": "PT",
    "branchCode": "998",
    "SWIFT Code": "IBLSPTPP998",
    "Bank Name": "INTERBOLSA - S.G.S.L.S.C.V.M., S.A.",
    "Address": "AVENIDA DA BOAVISTA 3433",
    "City": "PORTO",
    "Branch": "",
    "Postcode": "4100-138",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "IBLS",
    "bankCode": "PT",
    "branchCode": "101",
    "SWIFT Code": "IBLSPTPP101",
    "Bank Name": "INTERBOLSA - S.G.S.L.S.C.V.M., S.A.",
    "Address": "AVENIDA DA BOAVISTA 3433",
    "City": "PORTO",
    "Branch": "",
    "Postcode": "4100-138",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "IBLS",
    "bankCode": "PT",
    "branchCode": "999",
    "SWIFT Code": "IBLSPTPP999",
    "Bank Name": "INTERBOLSA - S.G.S.L.S.C.V.M., S.A.",
    "Address": "AVENIDA DA BOAVISTA 3433",
    "City": "PORTO",
    "Branch": "TECHNICAL ACCOUNT",
    "Postcode": "4100-138",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "IPAG",
    "bankCode": "PT",
    "branchCode": "TPL",
    "SWIFT Code": "IPAGPTPL",
    "Bank Name": "IPAGOO LLP PORTUGAL BRANCH",
    "Address": "AVENIDA DUQUE DE AVILA 1 DT 141",
    "City": "LISBON",
    "Branch": "",
    "Postcode": "1050-081",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "ITAU",
    "bankCode": "PT",
    "branchCode": "TPP",
    "SWIFT Code": "ITAUPTPP",
    "Bank Name": "ITAU BBA EUROPE",
    "Address": "TORRE 3, RUA TIERNO GALVAN, FLOOR 11",
    "City": "LISBON",
    "Branch": "",
    "Postcode": "1099-048",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "ITAU",
    "bankCode": "PT",
    "branchCode": "TPL",
    "SWIFT Code": "ITAUPTPL",
    "Bank Name": "ITAU BBA INTERNATIONAL LIMITED, SUCURSAL EM PORTUGAL",
    "Address": "TORRE 3, RUA TIERNO GALVAN, FLOOR 11",
    "City": "LISBON",
    "Branch": "",
    "Postcode": "1099-048",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "ISPR",
    "bankCode": "PT",
    "branchCode": "TPL",
    "SWIFT Code": "ISPRPTPL",
    "Bank Name": "IVN - SERVICOS PARTILHADOS, S.A.",
    "Address": "APARTADO 7079, AVENIDA DA INDUSTRIA 511",
    "City": "VILA NOVA DE FAMALICAO",
    "Branch": "",
    "Postcode": "4760-725",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "JERG",
    "bankCode": "PT",
    "branchCode": "TPL",
    "SWIFT Code": "JERGPTPL",
    "Bank Name": "JERONIMO MARTINS SGPS, S.A",
    "Address": "RUA ACTOR ANTONIO SILVA 7, FLOOR 14",
    "City": "LISBON",
    "Branch": "",
    "Postcode": "1649-033",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "NRRS",
    "bankCode": "PT",
    "branchCode": "TPP",
    "SWIFT Code": "NRRSPTPP",
    "Bank Name": "NORS, S.A.",
    "Address": "RUA MANUEL PINTO DE AZEVEDO 711/1",
    "City": "PORTO",
    "Branch": "",
    "Postcode": "4100-189",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "BESA",
    "bankCode": "PT",
    "branchCode": "TPA",
    "SWIFT Code": "BESAPTPA",
    "Bank Name": "NOVO BANCO DOS ACORES, SA",
    "Address": "RUA HINTZE RIBEIRO 2-8",
    "City": "PONTA DELGADA",
    "Branch": "",
    "Postcode": "9500-049",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "BESC",
    "bankCode": "PT",
    "branchCode": "OSF",
    "SWIFT Code": "BESCPTPLOSF",
    "Bank Name": "NOVO BANCO, SA",
    "Address": "RUA ANTONIO JOSE DE ALMEIDA 3-1",
    "City": "FUNCHAL",
    "Branch": "SUCURSAL FINANCEIRA EXTERIOR, MADEIRA BRANCH",
    "Postcode": "9000-062",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "BESC",
    "bankCode": "PT",
    "branchCode": "TPL",
    "SWIFT Code": "BESCPTPL",
    "Bank Name": "NOVO BANCO, SA",
    "Address": "AVENIDA DA LIBERDADE 195",
    "City": "LISBON",
    "Branch": "",
    "Postcode": "1250-142",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "BESC",
    "bankCode": "PT",
    "branchCode": "CLM",
    "SWIFT Code": "BESCPTPLCLM",
    "Bank Name": "NOVO BANCO, SA",
    "Address": "AVENIDA DA LIBERDADE 195",
    "City": "LISBON",
    "Branch": "2ND CLM - SICOI",
    "Postcode": "1250-142",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "BESC",
    "bankCode": "PT",
    "branchCode": "ISA",
    "SWIFT Code": "BESCPTPLISA",
    "Bank Name": "NOVO BANCO, SA",
    "Address": "AVENIDA DA LIBERDADE 195",
    "City": "LISBON",
    "Branch": "ISA CLEARING ACCOUNT",
    "Postcode": "1250-142",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "CAGL",
    "bankCode": "PT",
    "branchCode": "TPL",
    "SWIFT Code": "CAGLPTPL",
    "Bank Name": "ABANCA CORPORACION BANCARIA, SA, SUCURSAL EM PORTUGAL",
    "Address": "RUA CASTILHO 20, FLOOR 1, GRANDE LISBOA",
    "City": "LISBON",
    "Branch": "",
    "Postcode": "1250-069",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "IGCP",
    "bankCode": "PT",
    "branchCode": "CAB",
    "SWIFT Code": "IGCPPTPLCAB",
    "Bank Name": "AGENCIA GESTAO DA TESOURARIA E DIV. PUBLICA, IGCP EPE",
    "Address": "AV. DA REPUBLICA 57, FLOOR 6",
    "City": "LISBON",
    "Branch": "",
    "Postcode": "1050-189",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "IGCP",
    "bankCode": "PT",
    "branchCode": "TPL",
    "SWIFT Code": "IGCPPTPL",
    "Bank Name": "AGENCIA GESTAO DA TESOURARIA E DIV. PUBLICA, IGCP EPE",
    "Address": "AV. DA REPUBLICA 57, FLOOR 6",
    "City": "LISBON",
    "Branch": "",
    "Postcode": "1050-189",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "IGCP",
    "bankCode": "PT",
    "branchCode": "BRA",
    "SWIFT Code": "IGCPPTPLBRA",
    "Bank Name": "AGENCIA GESTAO DA TESOURARIA E DIV. PUBLICA, IGCP EPE",
    "Address": "AV. DA REPUBLICA 57, FLOOR 6",
    "City": "LISBON",
    "Branch": "",
    "Postcode": "1050-189",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "AGPP",
    "bankCode": "PT",
    "branchCode": "TPP",
    "SWIFT Code": "AGPPPTPP",
    "Bank Name": "ASCENDI, SGPS, S.A.",
    "Address": "EDIFICIO LITOGRAFIA LUSITANA, PRACA MOUZINHO DE ALBUQUERQUE 197",
    "City": "PORTO",
    "Branch": "",
    "Postcode": "4100-360",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "ACTV",
    "bankCode": "PT",
    "branchCode": "TPL",
    "SWIFT Code": "ACTVPTPL",
    "Bank Name": "BANCO ACTIVOBANK S.A.",
    "Address": "RUA AUGUSTA RC 84",
    "City": "LISBON",
    "Branch": "",
    "Postcode": "1100-053",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "BAPA",
    "bankCode": "PT",
    "branchCode": "TPL",
    "SWIFT Code": "BAPAPTPL",
    "Bank Name": "BANCO ATLANTICO EUROPA, SA",
    "Address": "AVENIDA DA LIBERDADE 259",
    "City": "LISBON",
    "Branch": "",
    "Postcode": "1250-143",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "BAPA",
    "bankCode": "PT",
    "branchCode": "SIC",
    "SWIFT Code": "BAPAPTPLSIC",
    "Bank Name": "BANCO ATLANTICO EUROPA, SA",
    "Address": "AVENIDA DA LIBERDADE 259",
    "City": "LISBON",
    "Branch": "SICOI",
    "Postcode": "1250-143",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "BAIP",
    "bankCode": "PT",
    "branchCode": "TPL",
    "SWIFT Code": "BAIPPTPL",
    "Bank Name": "BANCO BAI EUROPA, SA",
    "Address": "AVENIDA ANTONIO AUGUSTO AG 130-6",
    "City": "LISBON",
    "Branch": "",
    "Postcode": "1050-020",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "BAIP",
    "bankCode": "PT",
    "branchCode": "SIC",
    "SWIFT Code": "BAIPPTPLSIC",
    "Bank Name": "BANCO BAI EUROPA, SA",
    "Address": "AVENIDA ANTONIO AUGUSTO AG 130-6",
    "City": "LISBON",
    "Branch": "",
    "Postcode": "1050-020",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "BPNP",
    "bankCode": "PT",
    "branchCode": "TPL",
    "SWIFT Code": "BPNPPTPL",
    "Bank Name": "BANCO BIC PORTUGUES, S.A.",
    "Address": "AVENIDA ANTONIO AUGUSTO AGUIAR, 132, FLOOR 5",
    "City": "LISBON",
    "Branch": "",
    "Postcode": "1050-020",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "BPNP",
    "bankCode": "PT",
    "branchCode": "SIC",
    "SWIFT Code": "BPNPPTPLSIC",
    "Bank Name": "BANCO BIC PORTUGUES, S.A.",
    "Address": "AVENIDA ANTONIO AUGUSTO AGUIAR, 132, FLOOR 5",
    "City": "LISBON",
    "Branch": "GT SICOI",
    "Postcode": "1050-020",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "BPNP",
    "bankCode": "PT",
    "branchCode": "SFE",
    "SWIFT Code": "BPNPPTPLSFE",
    "Bank Name": "BANCO BIC PORTUGUES, S.A.",
    "Address": "",
    "City": "MADEIRA",
    "Branch": "SUCURSAL FINANCEIRA EXTERIOR",
    "Postcode": "",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "BBVA",
    "bankCode": "PT",
    "branchCode": "TG2",
    "SWIFT Code": "BBVAPTPLTG2",
    "Bank Name": "BANCO BILBAO VIZCAYA ARGENTARIA S.A., SUCURSAL EM PORTUGAL",
    "Address": "",
    "City": "LISBON",
    "Branch": "",
    "Postcode": "",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "BBVA",
    "bankCode": "PT",
    "branchCode": "TPL",
    "SWIFT Code": "BBVAPTPL",
    "Bank Name": "BANCO BILBAO VIZCAYA ARGENTARIA S.A., SUCURSAL EM PORTUGAL",
    "Address": "AVENIDA DA LIBERDADE 222",
    "City": "LISBON",
    "Branch": "",
    "Postcode": "1250-148",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "BBPI",
    "bankCode": "PT",
    "branchCode": "GLF",
    "SWIFT Code": "BBPIPTPLGLF",
    "Bank Name": "BANCO BPI SA",
    "Address": "AVENIDA DA BOAVISTA 1117",
    "City": "PORTO",
    "Branch": "",
    "Postcode": "4100-129",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "BBPI",
    "bankCode": "PT",
    "branchCode": "TPL",
    "SWIFT Code": "BBPIPTPL",
    "Bank Name": "BANCO BPI SA",
    "Address": "RUE TENENTE VALADIM 284",
    "City": "PORTO",
    "Branch": "ALL PT BRANCHES NOT LISTED",
    "Postcode": "4100-476",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "BCOM",
    "bankCode": "PT",
    "branchCode": "FUN",
    "SWIFT Code": "BCOMPTPLFUN",
    "Bank Name": "BANCO COMERCIAL PORTUGUES",
    "Address": "",
    "City": "FUNCHAL",
    "Branch": "",
    "Postcode": "",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "BCOM",
    "bankCode": "PT",
    "branchCode": "SFE",
    "SWIFT Code": "BCOMPTPLSFE",
    "Bank Name": "BANCO COMERCIAL PORTUGUES",
    "Address": "",
    "City": "FUNCHAL",
    "Branch": "OFFSHORE BRANCH",
    "Postcode": "",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "BCOM",
    "bankCode": "PT",
    "branchCode": "OFI",
    "SWIFT Code": "BCOMPTPLOFI",
    "Bank Name": "BANCO COMERCIAL PORTUGUES",
    "Address": "",
    "City": "FUNCHAL",
    "Branch": "OFFSHORE BRANCH - CORPORATE AREA",
    "Postcode": "",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "BCOM",
    "bankCode": "PT",
    "branchCode": "B07",
    "SWIFT Code": "BCOMPTPLB07",
    "Bank Name": "BANCO COMERCIAL PORTUGUES",
    "Address": "TAGUSPARK, AV DR. MARIO SOARES",
    "City": "LISBON",
    "Branch": "",
    "Postcode": "2744-005",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "BCOM",
    "bankCode": "PT",
    "branchCode": "LES",
    "SWIFT Code": "BCOMPTPLLES",
    "Bank Name": "BANCO COMERCIAL PORTUGUES",
    "Address": "",
    "City": "LISBON",
    "Branch": "",
    "Postcode": "",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "BCOM",
    "bankCode": "PT",
    "branchCode": "INT",
    "SWIFT Code": "BCOMPTPLINT",
    "Bank Name": "BANCO COMERCIAL PORTUGUES",
    "Address": "",
    "City": "LISBON",
    "Branch": "CORRESPONDENT BANKING DIVISION",
    "Postcode": "",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "BCOM",
    "bankCode": "PT",
    "branchCode": "DRI",
    "SWIFT Code": "BCOMPTPLDRI",
    "Bank Name": "BANCO COMERCIAL PORTUGUES",
    "Address": "",
    "City": "LISBON",
    "Branch": "INSTITUTIONAL CUSTODY",
    "Postcode": "",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "BCOM",
    "bankCode": "PT",
    "branchCode": "DIF",
    "SWIFT Code": "BCOMPTPLDIF",
    "Bank Name": "BANCO COMERCIAL PORTUGUES",
    "Address": "",
    "City": "LISBON",
    "Branch": "TREASURY DIVISION",
    "Postcode": "",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "BCOM",
    "bankCode": "PT",
    "branchCode": "TPL",
    "SWIFT Code": "BCOMPTPL",
    "Bank Name": "BANCO COMERCIAL PORTUGUES",
    "Address": "EDIFICIO 2 AV PROF DR CAVACO SILVA, 30, FLOOR 2-B",
    "City": "OEIRAS",
    "Branch": "ALL NON LISTED BRANCHES",
    "Postcode": "2740-256",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "BCOM",
    "bankCode": "PT",
    "branchCode": "B01",
    "SWIFT Code": "BCOMPTPLB01",
    "Bank Name": "BANCO COMERCIAL PORTUGUES",
    "Address": "EDIFICIO PERIFERICO, AV DR. MARIO SOARES 33-33A",
    "City": "OEIRAS",
    "Branch": "BOPB - LISBOA",
    "Postcode": "2740-119",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "BCOM",
    "bankCode": "PT",
    "branchCode": "LEU",
    "SWIFT Code": "BCOMPTPLLEU",
    "Bank Name": "BANCO COMERCIAL PORTUGUES",
    "Address": "EDIF PERIFERICO EDIFICIO 10, AV. DR. MARIO SOARES",
    "City": "OEIRAS",
    "Branch": "DOC CREDITS/COLLECTIONS",
    "Postcode": "2740-119",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "BCOM",
    "bankCode": "PT",
    "branchCode": "OTP",
    "SWIFT Code": "BCOMPTPLOTP",
    "Bank Name": "BANCO COMERCIAL PORTUGUES",
    "Address": "TAGUS PARK",
    "City": "OEIRAS",
    "Branch": "TAGUS PARK",
    "Postcode": "2740-122",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "BCOM",
    "bankCode": "PT",
    "branchCode": "PLC",
    "SWIFT Code": "BCOMPTPLPLC",
    "Bank Name": "BANCO COMERCIAL PORTUGUES",
    "Address": "PRACA DOM JOAO I 28",
    "City": "PORTO",
    "Branch": "BANKING GUARANTEES",
    "Postcode": "4000-380",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "CTTV",
    "bankCode": "PT",
    "branchCode": "TPL",
    "SWIFT Code": "CTTVPTPL",
    "Bank Name": "BANCO CTT, S.A.",
    "Address": "EDIFICIO ATRIUM SALDANHA, PRACA DUQUE DE SALDANHA 1, FLOOR 3",
    "City": "LISBON",
    "Branch": "",
    "Postcode": "1050-094",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "CTTV",
    "bankCode": "PT",
    "branchCode": "SIC",
    "SWIFT Code": "CTTVPTPLSIC",
    "Bank Name": "BANCO CTT, S.A.",
    "Address": "EDIFICIO ATRIUM SALDANHA, PRACA DUQUE DE SALDANHA 1, FLOOR 3",
    "City": "LISBON",
    "Branch": "",
    "Postcode": "1050-094",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "BDIG",
    "bankCode": "PT",
    "branchCode": "TPL",
    "SWIFT Code": "BDIGPTPL",
    "Bank Name": "BANCO DE INVESTIMENTO GLOBAL S.A.",
    "Address": "EDIFICIO BIG, AVENIDA 24 DE JULHO 74-76",
    "City": "LISBON",
    "Branch": "",
    "Postcode": "1200-869",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "BDIG",
    "bankCode": "PT",
    "branchCode": "CLM",
    "SWIFT Code": "BDIGPTPLCLM",
    "Bank Name": "BANCO DE INVESTIMENTO GLOBAL S.A.",
    "Address": "EDIFICIO BIG, AVENIDA DE JULHO 24",
    "City": "LISBON",
    "Branch": "MECANISMO GARANTIA SICOI",
    "Postcode": "1200-869",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "BGAL",
    "bankCode": "PT",
    "branchCode": "CON",
    "SWIFT Code": "BGALPTPLCON",
    "Bank Name": "BANCO DE PORTUGAL",
    "Address": "",
    "City": "LISBON",
    "Branch": "",
    "Postcode": "",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "BGAL",
    "bankCode": "PT",
    "branchCode": "TPL",
    "SWIFT Code": "BGALPTPL",
    "Bank Name": "BANCO DE PORTUGAL",
    "Address": "RUA FEBO MONIZ 2",
    "City": "LISBON",
    "Branch": "",
    "Postcode": "1150-020",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "BGAL",
    "bankCode": "PT",
    "branchCode": "CBC",
    "SWIFT Code": "BGALPTTGCBC",
    "Bank Name": "BANCO DE PORTUGAL",
    "Address": "EDIFICIO PORTUGAL, AV. ALMIRANTE REIS 71",
    "City": "LISBON",
    "Branch": "BDP CENTRAL BANK CUSTOMERS",
    "Postcode": "1150-012",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "BGAL",
    "bankCode": "PT",
    "branchCode": "SSB",
    "SWIFT Code": "BGALPTTGSSB",
    "Bank Name": "BANCO DE PORTUGAL",
    "Address": "EDIFICIO PORTUGAL, AV. ALMIRANTE REIS 71",
    "City": "LISBON",
    "Branch": "BDP SECURITIES AND SETTLEMENTS BRANCH",
    "Postcode": "1150-012",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "BGAL",
    "bankCode": "PT",
    "branchCode": "CCB",
    "SWIFT Code": "BGALPTTGCCB",
    "Bank Name": "BANCO DE PORTUGAL",
    "Address": "",
    "City": "LISBON",
    "Branch": "BP- CCBM",
    "Postcode": "",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "BGAL",
    "bankCode": "PT",
    "branchCode": "BAC",
    "SWIFT Code": "BGALPTTGBAC",
    "Bank Name": "BANCO DE PORTUGAL",
    "Address": "",
    "City": "LISBON",
    "Branch": "BP-BACK-OFFICE",
    "Postcode": "",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "BGAL",
    "bankCode": "PT",
    "branchCode": "MRR",
    "SWIFT Code": "BGALPTTGMRR",
    "Bank Name": "BANCO DE PORTUGAL",
    "Address": "",
    "City": "LISBON",
    "Branch": "BP-MINIMUM RESERVES",
    "Postcode": "",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "BGAL",
    "bankCode": "PT",
    "branchCode": "SIT",
    "SWIFT Code": "BGALPTTGSIT",
    "Bank Name": "BANCO DE PORTUGAL",
    "Address": "",
    "City": "LISBON",
    "Branch": "BP-MONETARY POLICY OPERATIONS",
    "Postcode": "",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "BGAL",
    "bankCode": "PT",
    "branchCode": "PTP",
    "SWIFT Code": "BGALPTTGPTP",
    "Bank Name": "BANCO DE PORTUGAL",
    "Address": "",
    "City": "LISBON",
    "Branch": "COLLATERAL MANAGEMENT PT PARTIES",
    "Postcode": "",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "BGAL",
    "bankCode": "PT",
    "branchCode": "PTP",
    "SWIFT Code": "BGALPTPLPTP",
    "Bank Name": "BANCO DE PORTUGAL",
    "Address": "",
    "City": "LISBON",
    "Branch": "COLLATERAL MANAGEMENT PT PARTIES",
    "Postcode": "",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "BGAL",
    "bankCode": "PT",
    "branchCode": "DCP",
    "SWIFT Code": "BGALPTPLDCP",
    "Bank Name": "BANCO DE PORTUGAL",
    "Address": "",
    "City": "LISBON",
    "Branch": "CONTABILIDADE E PAGAMENTOS",
    "Postcode": "",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "BGAL",
    "bankCode": "PT",
    "branchCode": "CCB",
    "SWIFT Code": "BGALPTPLCCB",
    "Bank Name": "BANCO DE PORTUGAL",
    "Address": "RUA FRANCISCO RIBEIRO 2-3",
    "City": "LISBON",
    "Branch": "CREDIT AND MARKETS DEPARTMENT",
    "Postcode": "1150-019",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "BGAL",
    "bankCode": "PT",
    "branchCode": "DET",
    "SWIFT Code": "BGALPTTGDET",
    "Bank Name": "BANCO DE PORTUGAL",
    "Address": "",
    "City": "LISBON",
    "Branch": "DET-EMISSAO E TESOURARIA",
    "Postcode": "",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "BGAL",
    "bankCode": "PT",
    "branchCode": "FGD",
    "SWIFT Code": "BGALPTPLFGD",
    "Bank Name": "BANCO DE PORTUGAL",
    "Address": "AVENIDA DA REPUBLICA 57, FLOOR 7",
    "City": "LISBON",
    "Branch": "FUNDO DE GARANTIA DE DEPOSITOS",
    "Postcode": "1050-189",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "BGAL",
    "bankCode": "PT",
    "branchCode": "FG1",
    "SWIFT Code": "BGALPTPLFG1",
    "Bank Name": "BANCO DE PORTUGAL",
    "Address": "AV. DA REPUBLICA 57, FLOOR 7",
    "City": "LISBON",
    "Branch": "FUNDO DE GARANTIA DE DEPOSITOS BDP01",
    "Postcode": "1050-189",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "BGAL",
    "bankCode": "PT",
    "branchCode": "FDR",
    "SWIFT Code": "BGALPTPLFDR",
    "Bank Name": "BANCO DE PORTUGAL",
    "Address": "AVENIDA DA REPUBLICA 57, FLOOR 7",
    "City": "LISBON",
    "Branch": "FUNDO DE RESOLUCAO",
    "Postcode": "1050-189",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "BGAL",
    "bankCode": "PT",
    "branchCode": "FR1",
    "SWIFT Code": "BGALPTPLFR1",
    "Bank Name": "BANCO DE PORTUGAL",
    "Address": "AV. DA REPUBLICA 57, FLOOR 7",
    "City": "LISBON",
    "Branch": "FUNDO DE RESOLUCAO BDP01",
    "Postcode": "1050-189",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "BGAL",
    "bankCode": "PT",
    "branchCode": "FR2",
    "SWIFT Code": "BGALPTPLFR2",
    "Bank Name": "BANCO DE PORTUGAL",
    "Address": "AV. DA REPUBLICA 57, FLOOR 57",
    "City": "LISBON",
    "Branch": "FUNDO DE RESOLUCAO BDP02",
    "Postcode": "1150-012",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "BGAL",
    "bankCode": "PT",
    "branchCode": "GPF",
    "SWIFT Code": "BGALPTPLGPF",
    "Bank Name": "BANCO DE PORTUGAL",
    "Address": "",
    "City": "LISBON",
    "Branch": "FUNDS",
    "Postcode": "",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "BGAL",
    "bankCode": "PT",
    "branchCode": "IBC",
    "SWIFT Code": "BGALPTTGIBC",
    "Bank Name": "BANCO DE PORTUGAL",
    "Address": "EDIFICIO PORTUGAL, AV. ALMIRANTE REIS 71",
    "City": "LISBON",
    "Branch": "INTERBOLSA CUST",
    "Postcode": "1150-012",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "BGAL",
    "bankCode": "PT",
    "branchCode": "MMI",
    "SWIFT Code": "BGALPTTGMMI",
    "Bank Name": "BANCO DE PORTUGAL",
    "Address": "",
    "City": "LISBON",
    "Branch": "MERCADO MONETARIO INTERBANCARIO",
    "Postcode": "",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "BGAL",
    "bankCode": "PT",
    "branchCode": "MGS",
    "SWIFT Code": "BGALPTTGMGS",
    "Bank Name": "BANCO DE PORTUGAL",
    "Address": "EDIFICIO PORTUGAL, AV. ALMIRANTE REIS 71",
    "City": "LISBON",
    "Branch": "SICOI GUARANTEE MECHANISM",
    "Postcode": "1150-012",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "BGAL",
    "bankCode": "PT",
    "branchCode": "IPS",
    "SWIFT Code": "BGALPTTGIPS",
    "Bank Name": "BANCO DE PORTUGAL",
    "Address": "EDIFICIO PORTUGAL, AV. ALMIRANTE REIS 71",
    "City": "LISBON",
    "Branch": "SICOI INSTANT PAYMENTS SOLUTION",
    "Postcode": "1150-012",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "BGAL",
    "bankCode": "PT",
    "branchCode": "TTG",
    "SWIFT Code": "BGALPTTG",
    "Bank Name": "BANCO DE PORTUGAL",
    "Address": "EDIFICIO PORTUGAL, AV. ALMIRANTE REIS 71",
    "City": "LISBON",
    "Branch": "SISTEMAS DE PAGAMENTOS",
    "Postcode": "1150-012",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "BGAL",
    "bankCode": "PT",
    "branchCode": "TIP",
    "SWIFT Code": "BGALPTTGTIP",
    "Bank Name": "BANCO DE PORTUGAL",
    "Address": "EDIFICIO PORTUGAL, AV. ALMIRANTE REIS 71",
    "City": "LISBON",
    "Branch": "TIPS BRANCH",
    "Postcode": "1150-012",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "BSAB",
    "bankCode": "PT",
    "branchCode": "TPL",
    "SWIFT Code": "BSABPTPL",
    "Bank Name": "BANCO DE SABADELL S.A., SUCURSAL EM PORTUGAL",
    "Address": "EDIFICIO LIBERDADE 225, AVDA. LIBERDADE 225,5",
    "City": "LISBON",
    "Branch": "",
    "Postcode": "1250-097",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "BSAB",
    "bankCode": "PT",
    "branchCode": "001",
    "SWIFT Code": "BSABPTPL001",
    "Bank Name": "BANCO DE SABADELL S.A., SUCURSAL EM PORTUGAL",
    "Address": "EDIFICIO LIBERDADE, AVDA. LIBERDADE 225, 5",
    "City": "LISBON",
    "Branch": "BANCO DE SABADELL, S.A. SUCURSAL EM PORTUGAL COMANAGEMENT",
    "Postcode": "1250-097",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "BRAS",
    "bankCode": "PT",
    "branchCode": "TPL",
    "SWIFT Code": "BRASPTPL",
    "Bank Name": "BANCO DO BRASIL AG-SUCURSAL EM PORTUGAL",
    "Address": "AVENIDA DA REPUBLICA 35, FLOOR 6",
    "City": "LISBON",
    "Branch": "",
    "Postcode": "1050-186",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "BRAS",
    "bankCode": "PT",
    "branchCode": "SIC",
    "SWIFT Code": "BRASPTPLSIC",
    "Bank Name": "BANCO DO BRASIL AG-SUCURSAL EM PORTUGAL",
    "Address": "AVENIDA DA REPUBLICA 35, FLOOR 6",
    "City": "LISBON",
    "Branch": "SICOI",
    "Postcode": "1050-186",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "BFIA",
    "bankCode": "PT",
    "branchCode": "TPL",
    "SWIFT Code": "BFIAPTPL",
    "Bank Name": "BANCO FINANTIA S.A.",
    "Address": "RUA GENERAL FIRMINO MIGUEL 5,, FLOOR 1",
    "City": "LISBON",
    "Branch": "",
    "Postcode": "1600-100",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "BFIA",
    "bankCode": "PT",
    "branchCode": "SEC",
    "SWIFT Code": "BFIAPTPLSEC",
    "Bank Name": "BANCO FINANTIA S.A.",
    "Address": "RUA GENERAL FIRMINO MIGUEL 5",
    "City": "LISBON",
    "Branch": "FINANTIA SECURITIES",
    "Postcode": "1600-100",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "BFIA",
    "bankCode": "PT",
    "branchCode": "MC2",
    "SWIFT Code": "BFIAPTPLMC2",
    "Bank Name": "BANCO FINANTIA S.A.",
    "Address": "RUA GENERAL FIRMINO MIGUEL 5,, FLOOR 1",
    "City": "LISBON",
    "Branch": "MCA SICCOI",
    "Postcode": "1600-100",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "IVVS",
    "bankCode": "PT",
    "branchCode": "TPL",
    "SWIFT Code": "IVVSPTPL",
    "Bank Name": "BANCO INVEST S.A.",
    "Address": "TORRE 1 AVENIDA ENGENHEIRO DUARTE, PACHECO, FLOOR 11",
    "City": "LISBON",
    "Branch": "",
    "Postcode": "1070-101",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "IVVS",
    "bankCode": "PT",
    "branchCode": "002",
    "SWIFT Code": "IVVSPTPL002",
    "Bank Name": "BANCO INVEST S.A.",
    "Address": "TORRE 1 AVENIDA ENGENHEIRO DUARTE, PACHECO, FLOOR 11",
    "City": "LISBON",
    "Branch": "MSC002",
    "Postcode": "1070-101",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "BLJC",
    "bankCode": "PT",
    "branchCode": "TPT",
    "SWIFT Code": "BLJCPTPT",
    "Bank Name": "BANCO L.J. CARREGOSA, S.A.",
    "Address": "AVENIDE DA BOAVISTA 1083",
    "City": "PORTO",
    "Branch": "",
    "Postcode": "4100-129",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "BLJC",
    "bankCode": "PT",
    "branchCode": "SIC",
    "SWIFT Code": "BLJCPTPTSIC",
    "Bank Name": "BANCO L.J. CARREGOSA, S.A.",
    "Address": "AVENIDE DA BOAVISTA 1083",
    "City": "PORTO",
    "Branch": "SICOI",
    "Postcode": "4100-129",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "BPGP",
    "bankCode": "PT",
    "branchCode": "TPL",
    "SWIFT Code": "BPGPPTPL",
    "Bank Name": "BANCO PORTUGUES DE GESTAO, S.A.",
    "Address": "RUA BARATA SALGUEIRO 37, FLOOR 4",
    "City": "LISBON",
    "Branch": "",
    "Postcode": "1250-042",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "BPGP",
    "bankCode": "PT",
    "branchCode": "001",
    "SWIFT Code": "BPGPPTPL001",
    "Bank Name": "BANCO PORTUGUES DE GESTAO, S.A.",
    "Address": "RUA BARATA SALGUEIRO 37, FLOOR 4",
    "City": "LISBON",
    "Branch": "",
    "Postcode": "1250-042",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "TOTA",
    "bankCode": "PT",
    "branchCode": "TPL",
    "SWIFT Code": "TOTAPTPL",
    "Bank Name": "BANCO SANTANDER TOTTA, SA",
    "Address": "CENTRO TOTTA TOWER B, RUA DA MESQUITA 6, FLOOR 1, DOOR A",
    "City": "LISBON",
    "Branch": "",
    "Postcode": "1070-238",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "TOTA",
    "bankCode": "PT",
    "branchCode": "SIC",
    "SWIFT Code": "TOTAPTPLSIC",
    "Bank Name": "BANCO SANTANDER TOTTA, SA",
    "Address": "CENTRO TOTTA TOWER B, RUA DA MESQUITA 6, FLOOR 1, DOOR A",
    "City": "LISBON",
    "Branch": "COMPENSACION SICOI",
    "Postcode": "1070-238",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "TOTA",
    "bankCode": "PT",
    "branchCode": "COV",
    "SWIFT Code": "TOTAPTPLCOV",
    "Bank Name": "BANCO SANTANDER TOTTA, SA",
    "Address": "CENTRO TOTTA TOWER B, RUA DA MESQUITA 6, FLOOR 1, DOOR A",
    "City": "LISBON",
    "Branch": "COVERED BONDS",
    "Postcode": "1070-238",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "TOTA",
    "bankCode": "PT",
    "branchCode": "EMI",
    "SWIFT Code": "TOTAPTPLEMI",
    "Bank Name": "BANCO SANTANDER TOTTA, SA",
    "Address": "CENTRO TOTTA, RUA DA MESQUITA 6, FLOOR 1",
    "City": "LISBON",
    "Branch": "EMIGRANTS REMITTANCES",
    "Postcode": "1070-238",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "TOTA",
    "bankCode": "PT",
    "branchCode": "MOB",
    "SWIFT Code": "TOTAPTPLMOB",
    "Bank Name": "BANCO SANTANDER TOTTA, SA",
    "Address": "",
    "City": "MADEIRA",
    "Branch": "MADEIRA OFFSHORE BRANCH",
    "Postcode": "",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "BKCH",
    "bankCode": "PT",
    "branchCode": "TPL",
    "SWIFT Code": "BKCHPTPL",
    "Bank Name": "BANK OF CHINA ( EUROPE) S.A. LISBON BRANCH - SUCURSAL EM PORTUGAL",
    "Address": "RUA DUQUE DE PALMELA 35-37",
    "City": "LISBON",
    "Branch": "",
    "Postcode": "1250-097",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "BKBK",
    "bankCode": "PT",
    "branchCode": "TPL",
    "SWIFT Code": "BKBKPTPL",
    "Bank Name": "BANKINTER SA-SUCURSAL EM PORTUGAL",
    "Address": "PRACA MARQUES DE POMBAL 13, FLOOR 2",
    "City": "LISBON",
    "Branch": "",
    "Postcode": "1250-162",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "BKBK",
    "bankCode": "PT",
    "branchCode": "MCA",
    "SWIFT Code": "BKBKPTPLMCA",
    "Bank Name": "BANKINTER SA-SUCURSAL EM PORTUGAL",
    "Address": "PRACA MARQUES DE POMBAL 13, FLOOR 2",
    "City": "LISBON",
    "Branch": "MCA/SICOI",
    "Postcode": "1250-162",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "BARC",
    "bankCode": "PT",
    "branchCode": "TPC",
    "SWIFT Code": "BARCPTPC",
    "Bank Name": "BARCLAYS BANK IRELAND PLC - SUCURSAL EM PORTUGAL",
    "Address": "RUA DUQUE DE PALMELA 37, FLOOR 5",
    "City": "LISBON",
    "Branch": "",
    "Postcode": "1050-040",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "BESZ",
    "bankCode": "PT",
    "branchCode": "TPL",
    "SWIFT Code": "BESZPTPL",
    "Bank Name": "BEST-BANCO ELECTRONICO DE SERVICO TOTAL S.A.",
    "Address": "PRACA MARQUES POMBAL",
    "City": "LISBON",
    "Branch": "",
    "Postcode": "1250-161",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "BHOD",
    "bankCode": "PT",
    "branchCode": "TPL",
    "SWIFT Code": "BHODPTPL",
    "Bank Name": "BIAL - HOLDING, S.A.",
    "Address": "AV. SIDERURGIA NACIONAL",
    "City": "CORONADO",
    "Branch": "",
    "Postcode": "4745-365",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "BNFI",
    "bankCode": "PT",
    "branchCode": "TPL",
    "SWIFT Code": "BNFIPTPL",
    "Bank Name": "BISON BANK, S.A.",
    "Address": "RUA BARATA SALGUEIRO 33",
    "City": "LISBON",
    "Branch": "",
    "Postcode": "1250-042",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "BNFI",
    "bankCode": "PT",
    "branchCode": "SIC",
    "SWIFT Code": "BNFIPTPLSIC",
    "Bank Name": "BISON BANK, S.A.",
    "Address": "RUA BARATA SALGUEIRO 33",
    "City": "LISBON",
    "Branch": "SICOI BRANCH",
    "Postcode": "1250-042",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "BNIC",
    "bankCode": "PT",
    "branchCode": "TPL",
    "SWIFT Code": "BNICPTPL",
    "Bank Name": "BNI - BANCO DE NEGOCIOS INTERNACIONAL (EUROPA), S.A.",
    "Address": "AMOREIRAS TORRE 1, AVENIDA ENG DUARTE PACHECO, FLOOR 7",
    "City": "LISBON",
    "Branch": "",
    "Postcode": "1070-101",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "BNIC",
    "bankCode": "PT",
    "branchCode": "001",
    "SWIFT Code": "BNICPTPL001",
    "Bank Name": "BNI - BANCO DE NEGOCIOS INTERNACIONAL (EUROPA), S.A.",
    "Address": "CC AMOREIRAS,TORRE 1, AVENIDA ENG DUARTE PACHECO, FLOOR 7",
    "City": "LISBON",
    "Branch": "",
    "Postcode": "1070-101",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "BNPA",
    "bankCode": "PT",
    "branchCode": "TPL",
    "SWIFT Code": "BNPAPTPL",
    "Bank Name": "BNP PARIBAS",
    "Address": "TORRE OCIDENTE, RUA GALILEU GALILEI 2, FLOOR 13",
    "City": "LISBON",
    "Branch": "",
    "Postcode": "1500-392",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "BNPA",
    "bankCode": "PT",
    "branchCode": "TPP",
    "SWIFT Code": "BNPAPTPP",
    "Bank Name": "BNP PARIBAS PERSONAL FINANCE, S.A. - SUCURSAL EM PORTUGAL",
    "Address": "CENTRO COL, GALILEU GALILEI 2, FLOOR 8",
    "City": "LISBON",
    "Branch": "",
    "Postcode": "1500-392",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "BNPA",
    "bankCode": "PT",
    "branchCode": "INS",
    "SWIFT Code": "BNPAPTPPINS",
    "Bank Name": "BNP PARIBAS PERSONAL FINANCE, S.A. - SUCURSAL EM PORTUGAL",
    "Address": "TORRE OCIDENTE GALILEU GALILEI, CENTRO COL 2, FLOOR 8",
    "City": "LISBON",
    "Branch": "SEPA INSTANT PAYMENTS",
    "Postcode": "1500-392",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "BNPA",
    "bankCode": "PT",
    "branchCode": "LIS",
    "SWIFT Code": "BNPAPTPLLIS",
    "Bank Name": "BNP PARIBAS PORTUGAL",
    "Address": "",
    "City": "LISBON",
    "Branch": "",
    "Postcode": "",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "CXBI",
    "bankCode": "PT",
    "branchCode": "TPL",
    "SWIFT Code": "CXBIPTPL",
    "Bank Name": "CAIXA BANCO DE INVESTIMENTO, S.A.",
    "Address": "AVENIDA JOAO XXI 63",
    "City": "LISBON",
    "Branch": "",
    "Postcode": "1000-300",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "CXBI",
    "bankCode": "PT",
    "branchCode": "MCA",
    "SWIFT Code": "CXBIPTPLMCA",
    "Bank Name": "CAIXA BANCO DE INVESTIMENTO, S.A.",
    "Address": "AVENIDA JOAO XXI 63",
    "City": "LISBON",
    "Branch": "SICOI",
    "Postcode": "1000-300",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "CXBI",
    "bankCode": "PT",
    "branchCode": "MOB",
    "SWIFT Code": "CXBIPTPLMOB",
    "Bank Name": "CAIXA BANCO DE INVESTIMENTO, S.A.",
    "Address": "",
    "City": "MADEIRA",
    "Branch": "MADEIRA OFFSHORE BRANCH",
    "Postcode": "",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "CCCM",
    "bankCode": "PT",
    "branchCode": "TPL",
    "SWIFT Code": "CCCMPTPL",
    "Bank Name": "CAIXA CENTRAL CREDITO AGRICOLA MUTUO",
    "Address": "RUA CASTILHO 233-233A",
    "City": "LISBON",
    "Branch": "",
    "Postcode": "1070-292",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "CCCM",
    "bankCode": "PT",
    "branchCode": "SCO",
    "SWIFT Code": "CCCMPTPLSCO",
    "Bank Name": "CAIXA CENTRAL CREDITO AGRICOLA MUTUO",
    "Address": "RUA CASTILHO 233-233A",
    "City": "LISBON",
    "Branch": "GARANTIA SICOI",
    "Postcode": "1070-292",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "CDOT",
    "bankCode": "PT",
    "branchCode": "TPP",
    "SWIFT Code": "CDOTPTPP",
    "Bank Name": "CAIXA DE CREDITO AGRICOLA MUTUO DE MAFRA CRL",
    "Address": "TERREIRO D.JOAO V",
    "City": "MAFRA",
    "Branch": "",
    "Postcode": "2640-492",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "CDOT",
    "bankCode": "PT",
    "branchCode": "CGS",
    "SWIFT Code": "CDOTPTPPCGS",
    "Bank Name": "CAIXA DE CREDITO AGRICOLA MUTUO DE MAFRA CRL",
    "Address": "TERREIRO D.JOAO V",
    "City": "MAFRA",
    "Branch": "CCAMM GARANT SICOI",
    "Postcode": "2640-492",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "CTIU",
    "bankCode": "PT",
    "branchCode": "TPP",
    "SWIFT Code": "CTIUPTPP",
    "Bank Name": "CAIXA DE CREDITO AGRICOLA MUTUO DE TORRES VEDRAS, C.R.L.",
    "Address": "RUA SANTOS BERNARDES 16A",
    "City": "TORRES VEDRAS",
    "Branch": "",
    "Postcode": "2560-231",
    "Country": "Portugal",
    "Connection": "Active"
  },
  {
    "countryCode": "CTIU",
    "bankCode": "PT",
    "branchCode": "CTV",
    "SWIFT Code": "CTIUPTPPCTV",
    "Bank Name": "CAIXA DE CREDITO AGRICOLA MUTUO DE TORRES VEDRAS, C.R.L.",
    "Address": "RUA SANTOS BERNARDES 16A",
    "City": "TORRES VEDRAS",
    "Branch": "",
    "Postcode": "2560-311",
    "Country": "Portugal",
    "Connection": "Active"
  }
]
module.exports = portugal
