const puertoRico = [
  {
    "bankCode": "ADGI",
    "countryCode": "PR",
    "branchCode": "RSJ",
    "SWIFT Code": "ADGIPRSJ",
    "Bank Name": "ADVANTAGE INTERNATIONAL BANK CORP.",
    "Address": "AMERICAN INTERNATIONAL PLAZA, 250 MUNOZ RIVERA AVENUE, SUITE 710",
    "City": "SAN JUAN",
    "Branch": "",
    "Postcode": "00918",
    "Country": "Puerto Rico",
    "Connection": "Active"
  },
  {
    "bankCode": "AICI",
    "countryCode": "PR",
    "branchCode": "R22",
    "SWIFT Code": "AICIPR22",
    "Bank Name": "ALLIANCE CAPITAL INTERNATIONAL BANK INC",
    "Address": "HATO REY CENTER, 268 AVENIDA PONCE DE LEON, FLOOR 4",
    "City": "HATO REY",
    "Branch": "",
    "Postcode": "00918",
    "Country": "Puerto Rico",
    "Connection": "Active"
  },
  {
    "bankCode": "AMTL",
    "countryCode": "PR",
    "branchCode": "RSJ",
    "SWIFT Code": "AMTLPRSJ",
    "Bank Name": "AMERICAN INTERNATIONAL BANK LLC",
    "Address": "VIG TOWER 1225 PONCE DE LEON AVE,, SUITE MZ-5 AND 6",
    "City": "SAN JUAN",
    "Branch": "",
    "Postcode": "00907",
    "Country": "Puerto Rico",
    "Connection": "Active"
  },
  {
    "bankCode": "ACBI",
    "countryCode": "PR",
    "branchCode": "R22",
    "SWIFT Code": "ACBIPR22",
    "Bank Name": "ANDCAPITAL BANK INTERNATIONAL CORP",
    "Address": "AMERICAN INTERNATIONAL PLAZA, 250 AVE. LUIS MUNOZ RIVERA",
    "City": "HATO REY",
    "Branch": "",
    "Postcode": "00918",
    "Country": "Puerto Rico",
    "Connection": "Active"
  },
  {
    "bankCode": "AFCP",
    "countryCode": "PR",
    "branchCode": "RS2",
    "SWIFT Code": "AFCPPRS2",
    "Bank Name": "APPLIED FINANCE CAPITAL MANAGEMENT LLC",
    "Address": "COND. ATLANTIS, 404 AVE. PONCE DE LEON, APT. 1804",
    "City": "SAN JUAN",
    "Branch": "",
    "Postcode": "00901",
    "Country": "Puerto Rico",
    "Connection": "Active"
  },
  {
    "bankCode": "MULN",
    "countryCode": "PR",
    "branchCode": "RSJ",
    "SWIFT Code": "MULNPRSJ",
    "Bank Name": "ARETIBANK INTERNATIONAL INC.",
    "Address": "THE HATO REY CENTER 268 AVENIDA, JUAN PONCE DE LEON, 1403",
    "City": "SAN JUAN",
    "Branch": "",
    "Postcode": "00918",
    "Country": "Puerto Rico",
    "Connection": "Active"
  },
  {
    "bankCode": "ARVB",
    "countryCode": "PR",
    "branchCode": "RS2",
    "SWIFT Code": "ARVBPRS2",
    "Bank Name": "ARIVAL BANK INTERNATIONAL CORP.",
    "Address": "1413 PONCE DE LEON AVE, FLOOR 4",
    "City": "SAN JUAN",
    "Branch": "",
    "Postcode": "00907",
    "Country": "Puerto Rico",
    "Connection": "Active"
  },
  {
    "bankCode": "ARNR",
    "countryCode": "PR",
    "branchCode": "RSJ",
    "SWIFT Code": "ARNRPRSJ",
    "Bank Name": "BANCARIBE INTERNATIONAL BANK, INC.",
    "Address": "33 CALLE BOLIVIA, FLOOR 8",
    "City": "SAN JUAN",
    "Branch": "",
    "Postcode": "00918",
    "Country": "Puerto Rico",
    "Connection": "Active"
  },
  {
    "bankCode": "BPPR",
    "countryCode": "PR",
    "branchCode": "RSB",
    "SWIFT Code": "BPPRPRSB",
    "Bank Name": "BANCO POPULAR DE PUERTO RICO",
    "Address": "STOP 22 BUILDING, 1500 PONCE DE LEON AVE",
    "City": "SAN JUAN",
    "Branch": "",
    "Postcode": "00926-2753",
    "Country": "Puerto Rico",
    "Connection": "Active"
  },
  {
    "bankCode": "BPPR",
    "countryCode": "PR",
    "branchCode": "RSX",
    "SWIFT Code": "BPPRPRSX",
    "Bank Name": "BANCO POPULAR DE PUERTO RICO",
    "Address": "POPULAR CENTER BUILDING, 209 MUNOZ RIVERA AVENUE, SUITE 913",
    "City": "SAN JUAN",
    "Branch": "",
    "Postcode": "00918",
    "Country": "Puerto Rico",
    "Connection": "Active"
  },
  {
    "bankCode": "CFSU",
    "countryCode": "PR",
    "branchCode": "RSJ",
    "SWIFT Code": "CFSUPRSJ",
    "Bank Name": "BANCOLOMBIA PUERTO RICO INTERNACIONAL INC.",
    "Address": "270 MUNOZ RIVERA AVENUE, SUITE 502",
    "City": "SAN JUAN",
    "Branch": "",
    "Postcode": "00918",
    "Country": "Puerto Rico",
    "Connection": "Active"
  },
  {
    "bankCode": "BIPN",
    "countryCode": "PR",
    "branchCode": "RSJ",
    "SWIFT Code": "BIPNPRSJ",
    "Bank Name": "BANPLUS INTERNATIONAL BANK, INC.",
    "Address": "221 PONCE DE LEON AVENUE, SUITE 804",
    "City": "SAN JUAN",
    "Branch": "",
    "Postcode": "00917",
    "Country": "Puerto Rico",
    "Connection": "Active"
  },
  {
    "bankCode": "CIBP",
    "countryCode": "PR",
    "branchCode": "RSJ",
    "SWIFT Code": "CIBPPRSJ",
    "Bank Name": "BNC INTERNATIONAL BANKING CORPORATION",
    "Address": "PLAZA, 221 AVE PONCE DE LEON, SUITE 701",
    "City": "SAN JUAN",
    "Branch": "",
    "Postcode": "00918",
    "Country": "Puerto Rico",
    "Connection": "Active"
  },
  {
    "bankCode": "CBNT",
    "countryCode": "PR",
    "branchCode": "RSJ",
    "SWIFT Code": "CBNTPRSJ",
    "Bank Name": "CARIBE INTERNATIONAL BANK, CORP.",
    "Address": "CITI TOWER BLDG, 252 PONCE DE LEON AVE, SUITE 501",
    "City": "SAN JUAN",
    "Branch": "",
    "Postcode": "00918",
    "Country": "Puerto Rico",
    "Connection": "Active"
  },
  {
    "bankCode": "CBLB",
    "countryCode": "PR",
    "branchCode": "RSJ",
    "SWIFT Code": "CBLBPRSJ",
    "Bank Name": "CB INTERNATIONAL BANK LLC",
    "Address": "PLAZA BUILDING 270 AVE. MUNOZ, RIVERA, FLOOR 3, STE 330",
    "City": "SAN JUAN",
    "Branch": "",
    "Postcode": "00918",
    "Country": "Puerto Rico",
    "Connection": "Active"
  },
  {
    "bankCode": "CITI",
    "countryCode": "PR",
    "branchCode": "RSJ",
    "SWIFT Code": "CITIPRSJ",
    "Bank Name": "CITIBANK, NA PUERTO RICO",
    "Address": "PARQUE LAS AMERICAS 1, 235 FEDERICO COSTA ST, FLOOR 4",
    "City": "SAN JUAN",
    "Branch": "",
    "Postcode": "00918",
    "Country": "Puerto Rico",
    "Connection": "Active"
  },
  {
    "bankCode": "DINT",
    "countryCode": "PR",
    "branchCode": "RSJ",
    "SWIFT Code": "DINTPRSJ",
    "Bank Name": "DIGITAL INTERNATIONAL BANK, INC.",
    "Address": "CITY TOWERS, 250 AVE PONCE DE LEON, FLOOR 5",
    "City": "SAN JUAN",
    "Branch": "",
    "Postcode": "00918",
    "Country": "Puerto Rico",
    "Connection": "Active"
  },
  {
    "bankCode": "ELIR",
    "countryCode": "PR",
    "branchCode": "RSJ",
    "SWIFT Code": "ELIRPRSJ",
    "Bank Name": "ELITE INTERNATIONAL BANK",
    "Address": "252, 906 AVENIDA PONCE DE LEON",
    "City": "SAN JUAN",
    "Branch": "",
    "Postcode": "00918",
    "Country": "Puerto Rico",
    "Connection": "Active"
  },
  {
    "bankCode": "ESYI",
    "countryCode": "PR",
    "branchCode": "909",
    "SWIFT Code": "ESYIPRSJ909",
    "Bank Name": "EPAY SYSTEMS INTERNATIONAL LIMITED LIABILITY COMPANY",
    "Address": "270 AVENIDA LUIS MUNOZ RIVERA",
    "City": "HATO REY",
    "Branch": "",
    "Postcode": "00918-1900",
    "Country": "Puerto Rico",
    "Connection": "Active"
  },
  {
    "bankCode": "ESYI",
    "countryCode": "PR",
    "branchCode": "RSJ",
    "SWIFT Code": "ESYIPRSJ",
    "Bank Name": "EPAY SYSTEMS INTERNATIONAL LIMITED LIABILITY COMPANY",
    "Address": "101 CALLE DEL RIO",
    "City": "SAN JUAN",
    "Branch": "",
    "Postcode": "00911",
    "Country": "Puerto Rico",
    "Connection": "Active"
  },
  {
    "bankCode": "EEIB",
    "countryCode": "PR",
    "branchCode": "RSJ",
    "SWIFT Code": "EEIBPRSJ",
    "Bank Name": "EURO EXCHANGE INTERNATIONAL BANK, INC.",
    "Address": "DISTRICT VIEW OFFICE CENTER 268, AVENIDA PONCE DE LEON, SUITE 916",
    "City": "SAN JUAN",
    "Branch": "",
    "Postcode": "00918",
    "Country": "Puerto Rico",
    "Connection": "Active"
  },
  {
    "bankCode": "EUPN",
    "countryCode": "PR",
    "branchCode": "RSJ",
    "SWIFT Code": "EUPNPRSJ",
    "Bank Name": "EURO PACIFIC INTL. BANK, INC.",
    "Address": "53 PALMERAS STREET, FLOOR 10",
    "City": "SAN JUAN",
    "Branch": "",
    "Postcode": "00901",
    "Country": "Puerto Rico",
    "Connection": "Active"
  },
  {
    "bankCode": "FILC",
    "countryCode": "PR",
    "branchCode": "R22",
    "SWIFT Code": "FILCPR22",
    "Bank Name": "FACEBANK INTERNATIONAL CORPORATION",
    "Address": "METRO OFFICE PARK VALENCIA BLDG 17, 2 CLL PARKSIDE, FLOOR 6, SUITE 600",
    "City": "GUAYNABO",
    "Branch": "",
    "Postcode": "00968",
    "Country": "Puerto Rico",
    "Connection": "Active"
  },
  {
    "bankCode": "FNTL",
    "countryCode": "PR",
    "branchCode": "RSJ",
    "SWIFT Code": "FNTLPRSJ",
    "Bank Name": "FAIRWINDS INTERNATIONAL BANK, LLC",
    "Address": "EDIFICIO RECINTO SUR, 259 CALLE RECINTO SUR",
    "City": "SAN JUAN",
    "Branch": "",
    "Postcode": "00901",
    "Country": "Puerto Rico",
    "Connection": "Active"
  },
  {
    "bankCode": "FBPR",
    "countryCode": "PR",
    "branchCode": "RSJ",
    "SWIFT Code": "FBPRPRSJ",
    "Bank Name": "FIRSTBANK PUERTO RICO",
    "Address": "PDA 23, 1519 PONCE DE LEON AVENUE, FLOOR 9",
    "City": "SAN JUAN",
    "Branch": "",
    "Postcode": "00908",
    "Country": "Puerto Rico",
    "Connection": "Active"
  },
  {
    "bankCode": "ITTL",
    "countryCode": "PR",
    "branchCode": "RS2",
    "SWIFT Code": "ITTLPRS2",
    "Bank Name": "FV BANK INTERNATIONAL INC",
    "Address": "270, 1120 AVENIDA MUNOZ RIVERA",
    "City": "SAN JUAN",
    "Branch": "",
    "Postcode": "00918",
    "Country": "Puerto Rico",
    "Connection": "Active"
  },
  {
    "bankCode": "GKBI",
    "countryCode": "PR",
    "branchCode": "RSJ",
    "SWIFT Code": "GKBIPRSJ",
    "Bank Name": "GKBANK",
    "Address": "CONDADO TOWER, 1473 WILSON AVE, FLOOR 1, SUITE 404",
    "City": "SAN JUAN",
    "Branch": "",
    "Postcode": "00907",
    "Country": "Puerto Rico",
    "Connection": "Active"
  },
  {
    "bankCode": "INTE",
    "countryCode": "PR",
    "branchCode": "R22",
    "SWIFT Code": "INTEPR22",
    "Bank Name": "INTERCAM BANCO INTERNACIONAL, INC.",
    "Address": "CITY VIEW PLAZA I, 48 ROAD 165, FLOOR 3, SUITE 319",
    "City": "GUAYNABO",
    "Branch": "",
    "Postcode": "00968-8031",
    "Country": "Puerto Rico",
    "Connection": "Active"
  },
  {
    "bankCode": "ITUL",
    "countryCode": "PR",
    "branchCode": "RSJ",
    "SWIFT Code": "ITULPRSJ",
    "Bank Name": "INTERNATIONAL UNION BANK LLC",
    "Address": "MCS PLAZA, 255 AV JUAN PONCE DE LEON, FLOOR 14",
    "City": "SAN JUAN",
    "Branch": "",
    "Postcode": "00917",
    "Country": "Puerto Rico",
    "Connection": "Active"
  },
  {
    "bankCode": "IBII",
    "countryCode": "PR",
    "branchCode": "RSJ",
    "SWIFT Code": "IBIIPRSJ",
    "Bank Name": "ITALBANK INTERNATIONAL, INC",
    "Address": "33 BOLIVIA STREET",
    "City": "SAN JUAN",
    "Branch": "",
    "Postcode": "00917-1923",
    "Country": "Puerto Rico",
    "Connection": "Active"
  },
  {
    "bankCode": "JICT",
    "countryCode": "PR",
    "branchCode": "RSJ",
    "SWIFT Code": "JICTPRSJ",
    "Bank Name": "JIC BANK",
    "Address": "HATO REY CENTER, 268 PONCE DE LEON AVE, SUITE 804",
    "City": "SAN JUAN",
    "Branch": "",
    "Postcode": "00918",
    "Country": "Puerto Rico",
    "Connection": "Active"
  },
  {
    "bankCode": "MDIC",
    "countryCode": "PR",
    "branchCode": "RS2",
    "SWIFT Code": "MDICPRS2",
    "Bank Name": "MEDICI BANK INTERNATIONAL LLC",
    "Address": "SAN JOSE BUILDING 1250 PONCE DE, LEON AVENUE, FLOOR 3, STE 301",
    "City": "SAN JUAN",
    "Branch": "",
    "Postcode": "00907",
    "Country": "Puerto Rico",
    "Connection": "Active"
  },
  {
    "bankCode": "MMGB",
    "countryCode": "PR",
    "branchCode": "RSJ",
    "SWIFT Code": "MMGBPRSJ",
    "Bank Name": "MMG BANK INTERNATIONAL, INC.",
    "Address": "250 MUNOZ RIVERA AVENUE, 315",
    "City": "SAN JUAN",
    "Branch": "",
    "Postcode": "00918",
    "Country": "Puerto Rico",
    "Connection": "Active"
  },
  {
    "bankCode": "NINT",
    "countryCode": "PR",
    "branchCode": "RSJ",
    "SWIFT Code": "NINTPRSJ",
    "Bank Name": "NEXT BANK INTERNATIONAL, INC.",
    "Address": "HATO REY CENTER 268 PONCE DE LEON, AVE, FLOOR 10, SUITE 1012",
    "City": "SAN JUAN",
    "Branch": "",
    "Postcode": "00918",
    "Country": "Puerto Rico",
    "Connection": "Active"
  },
  {
    "bankCode": "NDBK",
    "countryCode": "PR",
    "branchCode": "RSJ",
    "SWIFT Code": "NDBKPRSJ",
    "Bank Name": "NODUS INTERNATIONAL BANK, INC.",
    "Address": "CITI TOWERS BUILDING 252 PONCE DE, LEON AVENUE, SUITE 1501",
    "City": "SAN JUAN",
    "Branch": "",
    "Postcode": "00918",
    "Country": "Puerto Rico",
    "Connection": "Active"
  },
  {
    "bankCode": "OBPR",
    "countryCode": "PR",
    "branchCode": "RSJ",
    "SWIFT Code": "OBPRPRSJ",
    "Bank Name": "ORIENTAL BANK",
    "Address": "254 MUNOZ RIVERA",
    "City": "HATO REY",
    "Branch": "",
    "Postcode": "00918",
    "Country": "Puerto Rico",
    "Connection": "Active"
  },
  {
    "bankCode": "NOSC",
    "countryCode": "PR",
    "branchCode": "R22",
    "SWIFT Code": "NOSCPR22",
    "Bank Name": "ORIENTAL BANK (FORMERLY SCOTIABANK PUERTO RICO)",
    "Address": "254 MUNOZ RIVERA",
    "City": "HATO REY",
    "Branch": "",
    "Postcode": "00918-1900",
    "Country": "Puerto Rico",
    "Connection": "Active"
  },
  {
    "bankCode": "SGGI",
    "countryCode": "PR",
    "branchCode": "RSJ",
    "SWIFT Code": "SGGIPRSJ",
    "Bank Name": "SEGURA BANK INTERNATIONAL, CORP.",
    "Address": "270 AVE MUNOZ RIVERA, FLOOR 1130",
    "City": "SAN JUAN",
    "Branch": "",
    "Postcode": "00918",
    "Country": "Puerto Rico",
    "Connection": "Active"
  },
  {
    "bankCode": "STUL",
    "countryCode": "PR",
    "branchCode": "RSJ",
    "SWIFT Code": "STULPRSJ",
    "Bank Name": "STATETRUST INTERNATIONAL BANK AND TRUST, LLC",
    "Address": "CORPORATE OFFICE PARK ASSERTUS 107, KM2.2 ROAD 20 MARTINEZ NADAL AVE",
    "City": "SAN JUAN",
    "Branch": "",
    "Postcode": "00966",
    "Country": "Puerto Rico",
    "Connection": "Active"
  },
  {
    "bankCode": "STGN",
    "countryCode": "PR",
    "branchCode": "RSJ",
    "SWIFT Code": "STGNPRSJ",
    "Bank Name": "STRATEGIC BANK INTERNATIONAL CORP.",
    "Address": "VIG TOWER, 1225 PONCE DE LEON AVE, STE 705",
    "City": "SAN JUAN",
    "Branch": "",
    "Postcode": "00907",
    "Country": "Puerto Rico",
    "Connection": "Active"
  },
  {
    "bankCode": "ACTT",
    "countryCode": "PR",
    "branchCode": "RSJ",
    "SWIFT Code": "ACTTPRSJ",
    "Bank Name": "TBB INTERNATIONAL BANK CORP.",
    "Address": "PLAZA 221 AVE JUAN PONCE DE LEON,, FLOOR 11",
    "City": "SAN JUAN",
    "Branch": "",
    "Postcode": "00918",
    "Country": "Puerto Rico",
    "Connection": "Active"
  },
  {
    "bankCode": "LATA",
    "countryCode": "PR",
    "branchCode": "RSJ",
    "SWIFT Code": "LATAPRSJ",
    "Bank Name": "TC LATIN AMERICA PARTNERS LLC",
    "Address": "EL CARIBE OFFICE BLDG, 53 CALLE PALMERAS, FLOOR 601",
    "City": "SAN JUAN",
    "Branch": "",
    "Postcode": "00901",
    "Country": "Puerto Rico",
    "Connection": "Active"
  },
  {
    "bankCode": "TOLT",
    "countryCode": "PR",
    "branchCode": "RSJ",
    "SWIFT Code": "TOLTPRSJ",
    "Bank Name": "TOLOMEO BANK INTERNATIONAL, CORP.",
    "Address": "270 MUNOZ RIVERA AVENUE, FLOOR 504",
    "City": "SAN JUAN",
    "Branch": "",
    "Postcode": "00918",
    "Country": "Puerto Rico",
    "Connection": "Active"
  },
  {
    "bankCode": "WTCB",
    "countryCode": "PR",
    "branchCode": "RSJ",
    "SWIFT Code": "WTCBPRSJ",
    "Bank Name": "WTC INTERNATIONAL BANK CORPORATION",
    "Address": "PLAZA 270 AVENIDA LUIS MUNOZ, RIVERA, HATO REY OFFICE",
    "City": "SAN JUAN",
    "Branch": "",
    "Postcode": "00918",
    "Country": "Puerto Rico",
    "Connection": "Active"
  },
  {
    "bankCode": "ZEIT",
    "countryCode": "PR",
    "branchCode": "RSJ",
    "SWIFT Code": "ZEITPRSJ",
    "Bank Name": "ZENUS BANK INTERNATIONAL INC.",
    "Address": "CITI TOWER, 252 AVE PONCE DE LEON, FLOOR 19",
    "City": "SAN JUAN",
    "Branch": "",
    "Postcode": "00918",
    "Country": "Puerto Rico",
    "Connection": "Active"
  },
  {
    "bankCode": "ZEIT",
    "countryCode": "PR",
    "branchCode": "EUR",
    "SWIFT Code": "ZEITPRSJEUR",
    "Bank Name": "ZENUS BANK INTERNATIONAL INC.",
    "Address": "CITI TOWER, 252 AVE PONCE DE LEON, FLOOR 19",
    "City": "SAN JUAN",
    "Branch": "",
    "Postcode": "00918",
    "Country": "Puerto Rico",
    "Connection": "Active"
  },
  {
    "bankCode": "ZEIT",
    "countryCode": "PR",
    "branchCode": "GBP",
    "SWIFT Code": "ZEITPRSJGBP",
    "Bank Name": "ZENUS BANK INTERNATIONAL INC.",
    "Address": "CITI TOWER, 252 AVE PONCE DE LEON, FLOOR 19",
    "City": "SAN JUAN",
    "Branch": "",
    "Postcode": "00918",
    "Country": "Puerto Rico",
    "Connection": "Active"
  }
]
module.exports = puertoRico
