const romania = [
  {
    "countryCode": "TNIS",
    "bankCode": "RO",
    "branchCode": "OB2",
    "SWIFT Code": "TNISROB2",
    "Bank Name": "A1 TELECOM NETWORK ISP SRL",
    "Address": "ALBAC 11, FLOOR 2",
    "City": "BUCHAREST",
    "Branch": "",
    "Postcode": "011607",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "RZBL",
    "bankCode": "RO",
    "branchCode": "OBU",
    "SWIFT Code": "RZBLROBU",
    "Bank Name": "AEDIFICIUM BANCA PENTRU LOCUINTE S.A.",
    "Address": "FLOREASCA STR 246 D, DISTRICT 1",
    "City": "BUCHAREST",
    "Branch": "",
    "Postcode": "014146",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "ALBP",
    "bankCode": "RO",
    "branchCode": "OBU",
    "SWIFT Code": "ALBPROBU",
    "Bank Name": "ALIOR BANK SA WARSAW BUCHAREST BRANCH",
    "Address": "BUILDING D, MENUETULUI STREET 12, FLOOR 4, BUCHAREST BUSINESS PARK, SECTOR 1",
    "City": "BUCHAREST",
    "Branch": "",
    "Postcode": "013713",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BUCU",
    "bankCode": "RO",
    "branchCode": "OBU",
    "SWIFT Code": "BUCUROBU",
    "Bank Name": "ALPHA BANK ROMANIA SA",
    "Address": "PLATINUM BUSINESS CENTER SOSEAUA, BUCURESTI-PLOIESTI 172-176, FLOOR 4, SECTOR 1",
    "City": "BUCHAREST",
    "Branch": "",
    "Postcode": "013686",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "CRCO",
    "bankCode": "RO",
    "branchCode": "OBU",
    "SWIFT Code": "CRCOROBU",
    "Bank Name": "BANCA CENTRALA COOPERATISTA CREDITCOOP",
    "Address": "CREDITCOOP BUILDING, CALEA PLEVNEI 200",
    "City": "BUCHAREST",
    "Branch": "",
    "Postcode": "060015",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "RNCB",
    "bankCode": "RO",
    "branchCode": "AR0",
    "SWIFT Code": "RNCBROBUAR0",
    "Bank Name": "BANCA COMERCIALA ROMANA S.A",
    "Address": "",
    "City": "ARAD",
    "Branch": "ARAD BRANCH",
    "Postcode": "",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "RNCB",
    "bankCode": "RO",
    "branchCode": "OBU",
    "SWIFT Code": "RNCBROBU",
    "Bank Name": "BANCA COMERCIALA ROMANA S.A",
    "Address": "BUSINESS GARDEN BUCHAREST BLDG A, CALEA PLEVNEI 159, FLOOR 6, 6TH DISTRICT",
    "City": "BUCHAREST",
    "Branch": "",
    "Postcode": "060071",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "RNCB",
    "bankCode": "RO",
    "branchCode": "CS0",
    "SWIFT Code": "RNCBROBUCS0",
    "Bank Name": "BANCA COMERCIALA ROMANA S.A",
    "Address": "",
    "City": "RESITA",
    "Branch": "CARAS SEVERIN BRANCH",
    "Postcode": "",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "RNCB",
    "bankCode": "RO",
    "branchCode": "CV0",
    "SWIFT Code": "RNCBROBUCV0",
    "Bank Name": "BANCA COMERCIALA ROMANA S.A",
    "Address": "",
    "City": "SFANTU GHEORGHE",
    "Branch": "COVASNA BRANCH",
    "Postcode": "",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "RNCB",
    "bankCode": "RO",
    "branchCode": "IL0",
    "SWIFT Code": "RNCBROBUIL0",
    "Bank Name": "BANCA COMERCIALA ROMANA S.A",
    "Address": "",
    "City": "SLOBOZIA",
    "Branch": "IALOMITA BRANCH",
    "Postcode": "",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "MIND",
    "bankCode": "RO",
    "branchCode": "OBU",
    "SWIFT Code": "MINDROBU",
    "Bank Name": "BANCA ROMANA DE CREDITE SI INVESTITII S.A.",
    "Address": "STEFAN CEL MARE 3, FLOOR GF/1",
    "City": "BUCHAREST",
    "Branch": "",
    "Postcode": "011736",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BTRL",
    "bankCode": "RO",
    "branchCode": "ABI",
    "SWIFT Code": "BTRLRO22ABI",
    "Bank Name": "BANCA TRANSILVANIA S.A.",
    "Address": "STR. TRANSILVANIEI 5",
    "City": "AIUD",
    "Branch": "AIUD",
    "Postcode": "515200",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BTRL",
    "bankCode": "RO",
    "branchCode": "ABA",
    "SWIFT Code": "BTRLRO22ABA",
    "Bank Name": "BANCA TRANSILVANIA S.A.",
    "Address": "CALEA MOTILOV 4",
    "City": "ALBA IULIA",
    "Branch": "ALBA BRANCH",
    "Postcode": "510001",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BTRL",
    "bankCode": "RO",
    "branchCode": "BH4",
    "SWIFT Code": "BTRLRO22BH4",
    "Bank Name": "BANCA TRANSILVANIA S.A.",
    "Address": "P-TA UNIRII 6",
    "City": "ALESD",
    "Branch": "AG. ALESD",
    "Postcode": "415100",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BTRL",
    "bankCode": "RO",
    "branchCode": "TRA",
    "SWIFT Code": "BTRLRO22TRA",
    "Bank Name": "BANCA TRANSILVANIA S.A.",
    "Address": "",
    "City": "ALEXANDRIA",
    "Branch": "ALEXANDRIA",
    "Postcode": "",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BTRL",
    "bankCode": "RO",
    "branchCode": "AR1",
    "SWIFT Code": "BTRLRO22AR1",
    "Bank Name": "BANCA TRANSILVANIA S.A.",
    "Address": "BLVD. REVOLUTIEI 76",
    "City": "ARAD",
    "Branch": "AG. ARAD",
    "Postcode": "310130",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BTRL",
    "bankCode": "RO",
    "branchCode": "AR2",
    "SWIFT Code": "BTRLRO22AR2",
    "Bank Name": "BANCA TRANSILVANIA S.A.",
    "Address": "CALEA AUREL VLAICU 117-119",
    "City": "ARAD",
    "Branch": "AG. ARAD",
    "Postcode": "310381",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BTRL",
    "bankCode": "RO",
    "branchCode": "ARA",
    "SWIFT Code": "BTRLRO22ARA",
    "Bank Name": "BANCA TRANSILVANIA S.A.",
    "Address": "UNIRII STREET 5-7",
    "City": "ARAD",
    "Branch": "ARAD BRANCH",
    "Postcode": "310123",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BTRL",
    "bankCode": "RO",
    "branchCode": "BCA",
    "SWIFT Code": "BTRLRO22BCA",
    "Bank Name": "BANCA TRANSILVANIA S.A.",
    "Address": "MAI STREET 9, 33",
    "City": "BACAU",
    "Branch": "BACAU BRANCH",
    "Postcode": "600024",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BTRL",
    "bankCode": "RO",
    "branchCode": "MMA",
    "SWIFT Code": "BTRLRO22MMA",
    "Bank Name": "BANCA TRANSILVANIA S.A.",
    "Address": "UNIRII STREET 12-14",
    "City": "BAIA MARE",
    "Branch": "BAIA MARE BRANCH",
    "Postcode": "430271",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BTRL",
    "bankCode": "RO",
    "branchCode": "BHB",
    "SWIFT Code": "BTRLRO22BHB",
    "Bank Name": "BANCA TRANSILVANIA S.A.",
    "Address": "STR. HOREA 2",
    "City": "BEIUS",
    "Branch": "BEIUS",
    "Postcode": "415200",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BTRL",
    "bankCode": "RO",
    "branchCode": "BNA",
    "SWIFT Code": "BTRLRO22BNA",
    "Bank Name": "BANCA TRANSILVANIA S.A.",
    "Address": "PETRU RARES SQUARE 4",
    "City": "BISTRITA",
    "Branch": "BISTRITA BRANCH",
    "Postcode": "420036",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BTRL",
    "bankCode": "RO",
    "branchCode": "BTA",
    "SWIFT Code": "BTRLRO22BTA",
    "Bank Name": "BANCA TRANSILVANIA S.A.",
    "Address": "BL.G2, STR. MARCHIAN",
    "City": "BOTOSANI",
    "Branch": "BOTOSANI",
    "Postcode": "710210",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BTRL",
    "bankCode": "RO",
    "branchCode": "BRA",
    "SWIFT Code": "BTRLRO22BRA",
    "Bank Name": "BANCA TRANSILVANIA S.A.",
    "Address": "BL 10, CALEA CALARASILOR 54",
    "City": "BRAILA",
    "Branch": "BRAILA BRANCH",
    "Postcode": "810468",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BTRL",
    "bankCode": "RO",
    "branchCode": "BVA",
    "SWIFT Code": "BTRLRO22BVA",
    "Bank Name": "BANCA TRANSILVANIA S.A.",
    "Address": "M. KOGALNICEANU STREET 19",
    "City": "BRASOV",
    "Branch": "BRASOV BRANCH",
    "Postcode": "500090",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BTRL",
    "bankCode": "RO",
    "branchCode": "BB4",
    "SWIFT Code": "BTRLRO22BB4",
    "Bank Name": "BANCA TRANSILVANIA S.A.",
    "Address": "BL. 20, STR. AV. RADU BELLER 6",
    "City": "BUCHAREST",
    "Branch": "AG. DOROBANTI",
    "Postcode": "011703",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BTRL",
    "bankCode": "RO",
    "branchCode": "BB3",
    "SWIFT Code": "BTRLRO22BB3",
    "Bank Name": "BANCA TRANSILVANIA S.A.",
    "Address": "BLVD. NICOLAE BALCESCU 30",
    "City": "BUCHAREST",
    "Branch": "AG. MAGHERU",
    "Postcode": "010055",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BTRL",
    "bankCode": "RO",
    "branchCode": "BB2",
    "SWIFT Code": "BTRLRO22BB2",
    "Bank Name": "BANCA TRANSILVANIA S.A.",
    "Address": "CALEA 13 SEPT 118-120",
    "City": "BUCHAREST",
    "Branch": "AG. MARRIOTT",
    "Postcode": "061344",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BTRL",
    "bankCode": "RO",
    "branchCode": "BBC",
    "SWIFT Code": "BTRLRO22BBC",
    "Bank Name": "BANCA TRANSILVANIA S.A.",
    "Address": "CALEA GRIVITEI 395, SECTOR 1",
    "City": "BUCHAREST",
    "Branch": "BUCURESTI CHIBRIT",
    "Postcode": "012244",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BTRL",
    "bankCode": "RO",
    "branchCode": "BOT",
    "SWIFT Code": "BTRLRO22BOT",
    "Bank Name": "BANCA TRANSILVANIA S.A.",
    "Address": "CALEA BUCURESTI 78",
    "City": "BUCHAREST",
    "Branch": "BUCURESTI OTOPENI",
    "Postcode": "077180",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BTRL",
    "bankCode": "RO",
    "branchCode": "BVO",
    "SWIFT Code": "BTRLRO22BVO",
    "Bank Name": "BANCA TRANSILVANIA S.A.",
    "Address": "",
    "City": "BUCHAREST",
    "Branch": "BUCURESTI VOLUNTARI",
    "Postcode": "",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BTRL",
    "bankCode": "RO",
    "branchCode": "BBL",
    "SWIFT Code": "BTRLRO22BBL",
    "Bank Name": "BANCA TRANSILVANIA S.A.",
    "Address": "LIPSCANI STREET 102",
    "City": "BUCHAREST",
    "Branch": "CENTRE NOUVEAU BRANCH",
    "Postcode": "030167",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BTRL",
    "bankCode": "RO",
    "branchCode": "BB1",
    "SWIFT Code": "BTRLRO22BB1",
    "Bank Name": "BANCA TRANSILVANIA S.A.",
    "Address": "BLVD. IULIU MANIU 65",
    "City": "BUCHAREST",
    "Branch": "MILITARI BRANCH",
    "Postcode": "061085",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BTRL",
    "bankCode": "RO",
    "branchCode": "BBB",
    "SWIFT Code": "BTRLRO22BBB",
    "Bank Name": "BANCA TRANSILVANIA S.A.",
    "Address": "MIHAI BRAVU STREET 10",
    "City": "BUCHAREST",
    "Branch": "OBOR BRANCH",
    "Postcode": "030642",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BTRL",
    "bankCode": "RO",
    "branchCode": "BBP",
    "SWIFT Code": "BTRLRO22BBP",
    "Bank Name": "BANCA TRANSILVANIA S.A.",
    "Address": "BL.5, SOS. PANTELIMON 328",
    "City": "BUCHAREST",
    "Branch": "PANTELIMON BRANCH",
    "Postcode": "021657",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BTRL",
    "bankCode": "RO",
    "branchCode": "BBA",
    "SWIFT Code": "BTRLRO22BBA",
    "Bank Name": "BANCA TRANSILVANIA S.A.",
    "Address": "TRONSON I-II, ALBA-IULIA SQUARE 2",
    "City": "BUCHAREST",
    "Branch": "PIATA ALBA-IULIA BRANCH",
    "Postcode": "031108",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BTRL",
    "bankCode": "RO",
    "branchCode": "BBV",
    "SWIFT Code": "BTRLRO22BBV",
    "Bank Name": "BANCA TRANSILVANIA S.A.",
    "Address": "IANCU DE HUNEDOARA 6",
    "City": "BUCHAREST",
    "Branch": "VICTORIEI BRANCH",
    "Postcode": "011742",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BTRL",
    "bankCode": "RO",
    "branchCode": "BZA",
    "SWIFT Code": "BTRLRO22BZA",
    "Bank Name": "BANCA TRANSILVANIA S.A.",
    "Address": "UNIRII STREET 13 AB",
    "City": "BUZAU",
    "Branch": "BUZAU BRANCH",
    "Postcode": "120266",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BTRL",
    "bankCode": "RO",
    "branchCode": "SMC",
    "SWIFT Code": "BTRLRO22SMC",
    "Bank Name": "BANCA TRANSILVANIA S.A.",
    "Address": "BL. 35, STR. MIHAI VITEAZU",
    "City": "CAREI",
    "Branch": "AG. CAREI",
    "Postcode": "445100",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BTRL",
    "bankCode": "RO",
    "branchCode": "AR4",
    "SWIFT Code": "BTRLRO22AR4",
    "Bank Name": "BANCA TRANSILVANIA S.A.",
    "Address": "STR. INFRATIRII 89",
    "City": "CHISINAU CRIS",
    "Branch": "AG. CHISINAU CRIS",
    "Postcode": "315100",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BTRL",
    "bankCode": "RO",
    "branchCode": "O22",
    "SWIFT Code": "BTRLRO22",
    "Bank Name": "BANCA TRANSILVANIA S.A.",
    "Address": "CALEA DOROBANTILOR 30-36",
    "City": "CLUJ-NAPOCA",
    "Branch": "",
    "Postcode": "400117",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BTRL",
    "bankCode": "RO",
    "branchCode": "CJ8",
    "SWIFT Code": "BTRLRO22CJ8",
    "Bank Name": "BANCA TRANSILVANIA S.A.",
    "Address": "CALEA FLORESTI 75",
    "City": "CLUJ-NAPOCA",
    "Branch": "AG. BILLA",
    "Postcode": "400000",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BTRL",
    "bankCode": "RO",
    "branchCode": "BTS",
    "SWIFT Code": "BTRLRO22BTS",
    "Bank Name": "BANCA TRANSILVANIA S.A.",
    "Address": "MAESTRO BUSINESS CENTER, 21 DECEMBRIE 1989 104",
    "City": "CLUJ-NAPOCA",
    "Branch": "BT SECURITIES",
    "Postcode": "400124",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BTRL",
    "bankCode": "RO",
    "branchCode": "CJA",
    "SWIFT Code": "BTRLRO22CJA",
    "Bank Name": "BANCA TRANSILVANIA S.A.",
    "Address": "DOROBANTILOA 3",
    "City": "CLUJ-NAPOCA",
    "Branch": "CLUJ-NAPOCA BRANCH",
    "Postcode": "400000",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BTRL",
    "bankCode": "RO",
    "branchCode": "CJM",
    "SWIFT Code": "BTRLRO22CJM",
    "Bank Name": "BANCA TRANSILVANIA S.A.",
    "Address": "FABRICII 7",
    "City": "CLUJ-NAPOCA",
    "Branch": "MARASTI",
    "Postcode": "400000",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BTRL",
    "bankCode": "RO",
    "branchCode": "CJZ",
    "SWIFT Code": "BTRLRO22CJZ",
    "Bank Name": "BANCA TRANSILVANIA S.A.",
    "Address": "REPUBLICII 109",
    "City": "CLUJ-NAPOCA",
    "Branch": "ZORILOR",
    "Postcode": "400000",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BTRL",
    "bankCode": "RO",
    "branchCode": "CTA",
    "SWIFT Code": "BTRLRO22CTA",
    "Bank Name": "BANCA TRANSILVANIA S.A.",
    "Address": "FERDINAND AVENUE 53",
    "City": "CONSTANTA",
    "Branch": "CONSTANTA BRANCH",
    "Postcode": "900178",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BTRL",
    "bankCode": "RO",
    "branchCode": "DJA",
    "SWIFT Code": "BTRLRO22DJA",
    "Bank Name": "BANCA TRANSILVANIA S.A.",
    "Address": "JANCU JIANU STREET 16",
    "City": "CRAIOVA",
    "Branch": "CRAIOVA BRANCH",
    "Postcode": "200142",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BTRL",
    "bankCode": "RO",
    "branchCode": "CJD",
    "SWIFT Code": "BTRLRO22CJD",
    "Bank Name": "BANCA TRANSILVANIA S.A.",
    "Address": "1 MAI STREET 41",
    "City": "DEJ",
    "Branch": "DEJ BRANCH",
    "Postcode": "405200",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BTRL",
    "bankCode": "RO",
    "branchCode": "HDA",
    "SWIFT Code": "BTRLRO22HDA",
    "Bank Name": "BANCA TRANSILVANIA S.A.",
    "Address": "22 DECEMBER STREET 42",
    "City": "DEVA",
    "Branch": "DEVA BRANCH",
    "Postcode": "330162",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BRDE",
    "bankCode": "RO",
    "branchCode": "CAM",
    "SWIFT Code": "BRDEROBUCAM",
    "Bank Name": "BRD - GROUPE SOCIETE GENERALE SA",
    "Address": "UNION BUILDING, CAMPINEANU STREET 11",
    "City": "BUCHAREST",
    "Branch": "CAMPINEANU BRANCH",
    "Postcode": "030167",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BRDE",
    "bankCode": "RO",
    "branchCode": "TIT",
    "SWIFT Code": "BRDEROBUTIT",
    "Bank Name": "BRD - GROUPE SOCIETE GENERALE SA",
    "Address": "",
    "City": "BUCHAREST",
    "Branch": "SECURITIES DIVISION",
    "Postcode": "",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "CPFS",
    "bankCode": "RO",
    "branchCode": "OBU",
    "SWIFT Code": "CPFSROBU",
    "Bank Name": "CAPITAL FINANCIAL SERVICES SA",
    "Address": "CLADIREA CRYSTAL TOWER BD IANCU DE, HUNEDOARA NR. 48, FLOOR 11",
    "City": "BUCHAREST",
    "Branch": "",
    "Postcode": "011745",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "CBUH",
    "bankCode": "RO",
    "branchCode": "OBB",
    "SWIFT Code": "CBUHROBB",
    "Bank Name": "CCP.RO BUCHAREST S.A.",
    "Address": "CLADIREA IBC, BD. CAROL I 34-36, FLOOR 12, DISTRICT 2",
    "City": "BUCHAREST",
    "Branch": "",
    "Postcode": "020922",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "CECE",
    "bankCode": "RO",
    "branchCode": "OBU",
    "SWIFT Code": "CECEROBU",
    "Bank Name": "CEC BANK-S.A.",
    "Address": "CALEA VICTORIEI 13",
    "City": "BUCHAREST",
    "Branch": "",
    "Postcode": "030167",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "CEZO",
    "bankCode": "RO",
    "branchCode": "OBB",
    "SWIFT Code": "CEZOROBB",
    "Bank Name": "CEZ ROMANIA SA",
    "Address": "STR DARZU 1A, FLOOR 2",
    "City": "PITESTI",
    "Branch": "",
    "Postcode": "110268",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "CITI",
    "bankCode": "RO",
    "branchCode": "OBU",
    "SWIFT Code": "CITIROBU",
    "Bank Name": "CITIBANK EUROPE PLC, DUBLIN-SUCURSALA ROMANIA",
    "Address": "TIRIAC TOWER BUILDING, BUZESTI STREET 82-94, FLOOR 1, SECTOR 1, 1ST DISTRICT",
    "City": "BUCHAREST",
    "Branch": "",
    "Postcode": "011017",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "CITI",
    "bankCode": "RO",
    "branchCode": "TGT",
    "SWIFT Code": "CITIROBUTGT",
    "Bank Name": "CITIBANK EUROPE PLC, DUBLIN-SUCURSALA ROMANIA",
    "Address": "",
    "City": "BUCHAREST",
    "Branch": "TARGET 2",
    "Postcode": "",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "CITI",
    "bankCode": "RO",
    "branchCode": "TRD",
    "SWIFT Code": "CITIROBUTRD",
    "Bank Name": "CITIBANK EUROPE PLC, DUBLIN-SUCURSALA ROMANIA",
    "Address": "EXPOZITIEI BLVD 2, UNIT 2.05, SECTOR 1",
    "City": "BUCHAREST",
    "Branch": "TRADE SERVICES DEPT.",
    "Postcode": "012244",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "FNNB",
    "bankCode": "RO",
    "branchCode": "OBU",
    "SWIFT Code": "FNNBROBU",
    "Bank Name": "CREDIT EUROPE BANK (ROMANIA) S.A.",
    "Address": "BULEVARDUL TIMISOARA 26Z, SECTOR 6",
    "City": "BUCHAREST",
    "Branch": "",
    "Postcode": "061331",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "DECN",
    "bankCode": "RO",
    "branchCode": "OBU",
    "SWIFT Code": "DECNROBU",
    "Bank Name": "DEPOZITARUL CENTRAL S.A.",
    "Address": "CAROL I BOULEVARD 34 - 36, FLOOR 8, DISTRICT 2",
    "City": "BUCHAREST",
    "Branch": "",
    "Postcode": "020922",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BRMA",
    "bankCode": "RO",
    "branchCode": "OBU",
    "SWIFT Code": "BRMAROBU",
    "Bank Name": "EXIM BANCA ROMANEASCA S.A.",
    "Address": "BARBU DELAVRANCEA 6A, SECTOR 1",
    "City": "BUCHAREST",
    "Branch": "",
    "Postcode": "011355",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "FNOI",
    "bankCode": "RO",
    "branchCode": "OB2",
    "SWIFT Code": "FNOIROB2",
    "Bank Name": "FINANCE ONE IFN S.A.",
    "Address": "CASA PRESEI LIBERE, PIATA PRESEI LIBERE 1, FLOOR 6",
    "City": "BUCHAREST",
    "Branch": "",
    "Postcode": "013701",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "PIRB",
    "bankCode": "RO",
    "branchCode": "OBU",
    "SWIFT Code": "PIRBROBU",
    "Bank Name": "FIRST BANK",
    "Address": "NICOLAE TITULESCU 29-31",
    "City": "BUCHAREST",
    "Branch": "",
    "Postcode": "011132",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "UGBI",
    "bankCode": "RO",
    "branchCode": "OBU",
    "SWIFT Code": "UGBIROBU",
    "Bank Name": "GARANTI BANK S.A.",
    "Address": "F BUILDING, BUS. CTR. NOVO PARK 3, FABRICA DE GLUCOZA 5",
    "City": "BUCHAREST",
    "Branch": "",
    "Postcode": "020331",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "INGB",
    "bankCode": "RO",
    "branchCode": "OBU",
    "SWIFT Code": "INGBROBU",
    "Bank Name": "ING BANK N.V., BUCHAREST BRANCH",
    "Address": "EXPO BUSINESS PARK NO. 3, AVIATOR POPISTEANU STREET 54A",
    "City": "BUCHAREST",
    "Branch": "",
    "Postcode": "012095",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "WBAN",
    "bankCode": "RO",
    "branchCode": "O22",
    "SWIFT Code": "WBANRO22",
    "Bank Name": "INTESA SANPAOLO ROMANIA S.A.",
    "Address": "AMERICA HOUSE SOSEAUA NICOLAE, TITULESCU 4-8, FLOOR 6",
    "City": "BUCHAREST",
    "Branch": "",
    "Postcode": "011141",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "IVVI",
    "bankCode": "RO",
    "branchCode": "OB2",
    "SWIFT Code": "IVVIROB2",
    "Bank Name": "INVESTIMENTAL S.A.",
    "Address": "MUNTII TATRA 4-10",
    "City": "BUCHAREST",
    "Branch": "",
    "Postcode": "011022",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "KMGR",
    "bankCode": "RO",
    "branchCode": "OBU",
    "SWIFT Code": "KMGRROBU",
    "Bank Name": "KMG ROMPETROL SRL",
    "Address": "CITY GATE NORTH TOWER, PIATA PRESEI LIBERE 3-5, FLOOR 1-6",
    "City": "BUCHAREST",
    "Branch": "",
    "Postcode": "013702",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BREL",
    "bankCode": "RO",
    "branchCode": "CAM",
    "SWIFT Code": "BRELROBUCAM",
    "Bank Name": "LIBRA BANK S.A.",
    "Address": "CIMPINEANU STREET 11",
    "City": "BUCHAREST",
    "Branch": "",
    "Postcode": "030167",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BREL",
    "bankCode": "RO",
    "branchCode": "OBU",
    "SWIFT Code": "BRELROBU",
    "Bank Name": "LIBRA BANK S.A.",
    "Address": "CALEA VITAN 6-6A, SECTOR 3",
    "City": "BUCHAREST",
    "Branch": "",
    "Postcode": "031296",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "TREZ",
    "bankCode": "RO",
    "branchCode": "OBU",
    "SWIFT Code": "TREZROBU",
    "Bank Name": "MINISTRY OF FINANCE",
    "Address": "CNIF LIBERTATII BLV, POENARU, BORDEA 16, 3-5 SECTOR 5",
    "City": "BUCHAREST",
    "Branch": "",
    "Postcode": "050706",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "NBOR",
    "bankCode": "RO",
    "branchCode": "OBP",
    "SWIFT Code": "NBORROBP",
    "Bank Name": "NATIONAL BANK OF ROMANIA",
    "Address": "III, LIPSCANI 25",
    "City": "BUCHAREST",
    "Branch": "",
    "Postcode": "030031",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "NBOR",
    "bankCode": "RO",
    "branchCode": "OBU",
    "SWIFT Code": "NBORROBU",
    "Bank Name": "NATIONAL BANK OF ROMANIA",
    "Address": "III, LIPSCANI 25",
    "City": "BUCHAREST",
    "Branch": "",
    "Postcode": "030031",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "NBOR",
    "bankCode": "RO",
    "branchCode": "OBA",
    "SWIFT Code": "NBORROBA",
    "Bank Name": "NATIONAL BANK OF ROMANIA - REGIS",
    "Address": "LIPSCANI 25",
    "City": "BUCHAREST",
    "Branch": "",
    "Postcode": "030031",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "NBOR",
    "bankCode": "RO",
    "branchCode": "OBB",
    "SWIFT Code": "NBORROBB",
    "Bank Name": "NATIONAL BANK OF ROMANIA - SAFIR",
    "Address": "LIPSCANI 25",
    "City": "BUCHAREST",
    "Branch": "",
    "Postcode": "030031",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "OMVP",
    "bankCode": "RO",
    "branchCode": "OBB",
    "SWIFT Code": "OMVPROBB",
    "Bank Name": "OMV PETROM SA",
    "Address": "CORALILOR STREET 22",
    "City": "BUCHAREST",
    "Branch": "",
    "Postcode": "013329",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "OTPV",
    "bankCode": "RO",
    "branchCode": "OBU",
    "SWIFT Code": "OTPVROBU",
    "Bank Name": "OTP BANK ROMANIA S.A.",
    "Address": "STR. BUZESTI 66-68, SECTOR 1",
    "City": "BUCHAREST",
    "Branch": "",
    "Postcode": "011017",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "CARP",
    "bankCode": "RO",
    "branchCode": "O22",
    "SWIFT Code": "CARPRO22",
    "Bank Name": "PATRIA BANK S.A.",
    "Address": "GLOBALWORTH PLAZA, SOSEAUA PIPERA 42, FLOOR 10",
    "City": "BUCHAREST",
    "Branch": "",
    "Postcode": "020112",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BPKO",
    "bankCode": "RO",
    "branchCode": "OBU",
    "SWIFT Code": "BPKOROBU",
    "Bank Name": "PKO BANK POLSKI S.A. VARSOVIA, SUCURSALA BUCURESTI",
    "Address": "CRYSTAL TOWER B-DUL. IANCU DE, HUNEDOARA 48, FLOOR 10",
    "City": "BUCHAREST",
    "Branch": "",
    "Postcode": "011745",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "PORL",
    "bankCode": "RO",
    "branchCode": "OBU",
    "SWIFT Code": "PORLROBU",
    "Bank Name": "PORSCHE BANK ROMANIA SA",
    "Address": "PORSCHE BUILDING, BULEVARDUL PIPERA 2",
    "City": "VOLUNTARI",
    "Branch": "",
    "Postcode": "077190",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "MIRO",
    "bankCode": "RO",
    "branchCode": "OBU",
    "SWIFT Code": "MIROROBU",
    "Bank Name": "PROCREDIT BANK S.A.",
    "Address": "CASCADE CENTER, BUZESTI STREET 62-64, SECTOR 1",
    "City": "BUCHAREST",
    "Branch": "",
    "Postcode": "011017",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "RZBR",
    "bankCode": "RO",
    "branchCode": "OBU",
    "SWIFT Code": "RZBRROBU",
    "Bank Name": "RAIFFEISEN BANK S.A.",
    "Address": "SKY TOWER BUILDING CALEA FLOREASCA, 246C, FLOOR 2-7,10,15 1ST DISTRICT, 246C",
    "City": "BUCHAREST",
    "Branch": "",
    "Postcode": "014476",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "REVO",
    "bankCode": "RO",
    "branchCode": "OBB",
    "SWIFT Code": "REVOROBB",
    "Bank Name": "REVOLUT BANK UAB VILNIUS SUCURSALA BUCURESTI",
    "Address": "CLADIREA TOWERCENTER INTERNATIONAL, BULEVARDUL ION MIHALACHE MINDSPACE, VICTORIEI, BIROUL 15-17 111, FLOOR, 1",
    "City": "BUCHAREST",
    "Branch": "",
    "Postcode": "011745",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "ROIN",
    "bankCode": "RO",
    "branchCode": "OBU",
    "SWIFT Code": "ROINROBU",
    "Bank Name": "SALT BANK SA",
    "Address": "HERMES BUSINESS CAMPUS, BD DIMITRIE POMPEI 5-7, FLOOR 6",
    "City": "BUCHAREST",
    "Branch": "",
    "Postcode": "020335",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "SUBG",
    "bankCode": "RO",
    "branchCode": "OBB",
    "SWIFT Code": "SUBGROBB",
    "Bank Name": "SUPERBET",
    "Address": "BUZESTI 75-77, FLOOR 2, ROOM 5, SECTORUL 1",
    "City": "BUCHAREST",
    "Branch": "",
    "Postcode": "011013",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "TBIB",
    "bankCode": "RO",
    "branchCode": "OBU",
    "SWIFT Code": "TBIBROBU",
    "Bank Name": "TBI BANK EAD SOFIA BUCHAREST BRANCH",
    "Address": "PUTUL LUI ZAMFIR 8-12, FLOOR 4",
    "City": "BUCHAREST",
    "Branch": "",
    "Postcode": "011683",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BFER",
    "bankCode": "RO",
    "branchCode": "OBU",
    "SWIFT Code": "BFERROBU",
    "Bank Name": "TECHVENTURES BANK SA",
    "Address": "CFR PALACE, DINICU GOLESCU BLVD 38, 1-ST DISTRICT",
    "City": "BUCHAREST",
    "Branch": "",
    "Postcode": "010867",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "TRPC",
    "bankCode": "RO",
    "branchCode": "OB2",
    "SWIFT Code": "TRPCROB2",
    "Bank Name": "TRANSFER RAPID ELECTRONIC",
    "Address": "BULEVARDUL UNIRII 72, FLOOR 8",
    "City": "BUCHAREST",
    "Branch": "",
    "Postcode": "030836",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "TRPC",
    "bankCode": "RO",
    "branchCode": "TRE",
    "SWIFT Code": "TRPCROB2TRE",
    "Bank Name": "TRANSFER RAPID ELECTRONIC",
    "Address": "BULEVARDUL UNIRII 72, FLOOR 8",
    "City": "BUCHAREST",
    "Branch": "RO",
    "Postcode": "030836",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "TRFD",
    "bankCode": "RO",
    "branchCode": "OBS",
    "SWIFT Code": "TRFDROBS",
    "Bank Name": "TRANSFOND S.A.",
    "Address": "BD. FICUSULUI 1, SECTOR 1",
    "City": "BUCHAREST",
    "Branch": "",
    "Postcode": "013971",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "TRFD",
    "bankCode": "RO",
    "branchCode": "SNT",
    "SWIFT Code": "TRFDROBSSNT",
    "Bank Name": "TRANSFOND S.A.",
    "Address": "",
    "City": "BUCHAREST",
    "Branch": "BACK OFFICE APPLICATION",
    "Postcode": "",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BACX",
    "bankCode": "RO",
    "branchCode": "OBU",
    "SWIFT Code": "BACXROBU",
    "Bank Name": "UNICREDIT BANK SA",
    "Address": "EXPOZITIEI BLVD 1F, SECTOR 1",
    "City": "BUCHAREST",
    "Branch": "",
    "Postcode": "012101",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "PANX",
    "bankCode": "RO",
    "branchCode": "O22",
    "SWIFT Code": "PANXRO22",
    "Bank Name": "UNIFIEDPOST PAYMENTS LA HULPE SUCURSALA TIMISOARA",
    "Address": "STRADA CORIOLAN BREDICEANU 10",
    "City": "TIMISOARA",
    "Branch": "",
    "Postcode": "300011",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "EGNA",
    "bankCode": "RO",
    "branchCode": "OBX",
    "SWIFT Code": "EGNAROBX",
    "Bank Name": "VISTA BANK (ROMANIA) S.A.",
    "Address": "EMANOIL PORUMBARU STREET 90-92, SECTOR1",
    "City": "BUCHAREST",
    "Branch": "",
    "Postcode": "010775",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "VPAY",
    "bankCode": "RO",
    "branchCode": "OB2",
    "SWIFT Code": "VPAYROB2",
    "Bank Name": "VIVA PAYMENT SERVICES S.A SUCURSALA BUCURESTI",
    "Address": "EMANOIL PORUMBARU STREET 21, DISTRICT 1",
    "City": "BUCHAREST",
    "Branch": "",
    "Postcode": "011426",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BTRL",
    "bankCode": "RO",
    "branchCode": "VLD",
    "SWIFT Code": "BTRLRO22VLD",
    "Bank Name": "BANCA TRANSILVANIA S.A.",
    "Address": "BL.A1, STR. GIB MIHAESCU",
    "City": "DRAGASANI",
    "Branch": "DRAGASANI",
    "Postcode": "245700",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BTRL",
    "bankCode": "RO",
    "branchCode": "BVF",
    "SWIFT Code": "BTRLRO22BVF",
    "Bank Name": "BANCA TRANSILVANIA S.A.",
    "Address": "STR. N. BALCESCU 15",
    "City": "FAGARAS",
    "Branch": "FAGARAS",
    "Postcode": "505200",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BTRL",
    "bankCode": "RO",
    "branchCode": "SVF",
    "SWIFT Code": "BTRLRO22SVF",
    "Bank Name": "BANCA TRANSILVANIA S.A.",
    "Address": "BD REVOLUTIEI 27",
    "City": "FALTICENI",
    "Branch": "FALTICENI",
    "Postcode": "725200",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BTRL",
    "bankCode": "RO",
    "branchCode": "VRA",
    "SWIFT Code": "BTRLRO22VRA",
    "Bank Name": "BANCA TRANSILVANIA S.A.",
    "Address": "MIHAIL KOGALNICEANU STREET 1",
    "City": "FOCSANI",
    "Branch": "FOCSANI BRANCH",
    "Postcode": "620036",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BTRL",
    "bankCode": "RO",
    "branchCode": "GLA",
    "SWIFT Code": "BTRLRO22GLA",
    "Bank Name": "BANCA TRANSILVANIA S.A.",
    "Address": "MAIOV IANCU FOTEA STREET 3",
    "City": "GALATI",
    "Branch": "GALATI BRANCH",
    "Postcode": "800017",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BTRL",
    "bankCode": "RO",
    "branchCode": "CJG",
    "SWIFT Code": "BTRLRO22CJG",
    "Bank Name": "BANCA TRANSILVANIA S.A.",
    "Address": "STR. BOBALNA 15",
    "City": "GHERLA",
    "Branch": "GHERLA",
    "Postcode": "405300",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BTRL",
    "bankCode": "RO",
    "branchCode": "GRA",
    "SWIFT Code": "BTRLRO22GRA",
    "Bank Name": "BANCA TRANSILVANIA S.A.",
    "Address": "PORTULUI STREET 1",
    "City": "GIURGIU",
    "Branch": "ZONA LIBERTA GIURGIU BRANCH",
    "Postcode": "080011",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BTRL",
    "bankCode": "RO",
    "branchCode": "CJH",
    "SWIFT Code": "BTRLRO22CJH",
    "Bank Name": "BANCA TRANSILVANIA S.A.",
    "Address": "HOREA STREET 2",
    "City": "HUEDIN",
    "Branch": "HUEDIN",
    "Postcode": "405400",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BTRL",
    "bankCode": "RO",
    "branchCode": "ISA",
    "SWIFT Code": "BTRLRO22ISA",
    "Bank Name": "BANCA TRANSILVANIA S.A.",
    "Address": "GHICA VODA STREET 3 A",
    "City": "IASI",
    "Branch": "IASI BRANCH",
    "Postcode": "700496",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BTRL",
    "bankCode": "RO",
    "branchCode": "AR5",
    "SWIFT Code": "BTRLRO22AR5",
    "Bank Name": "BANCA TRANSILVANIA S.A.",
    "Address": "CALEA REPUBLICII 11",
    "City": "INEU",
    "Branch": "AG. INEU",
    "Postcode": "315300",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BTRL",
    "bankCode": "RO",
    "branchCode": "TML",
    "SWIFT Code": "BTRLRO22TML",
    "Bank Name": "BANCA TRANSILVANIA S.A.",
    "Address": "P-TA IOSIF C-TIN DRAGAN 10",
    "City": "LUGOJ",
    "Branch": "AG. LUGOJ",
    "Postcode": "305500",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BTRL",
    "bankCode": "RO",
    "branchCode": "CTM",
    "SWIFT Code": "BTRLRO22CTM",
    "Bank Name": "BANCA TRANSILVANIA S.A.",
    "Address": "STR. STEFAN CEL MARE 6",
    "City": "MANGALIA",
    "Branch": "AG. MANGALIA",
    "Postcode": "905500",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BTRL",
    "bankCode": "RO",
    "branchCode": "AR3",
    "SWIFT Code": "BTRLRO22AR3",
    "Bank Name": "BANCA TRANSILVANIA S.A.",
    "Address": "BL. A, P-TA UNIRII 8",
    "City": "NADLAC",
    "Branch": "AG. NADLAC",
    "Postcode": "315500",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BTRL",
    "bankCode": "RO",
    "branchCode": "HRO",
    "SWIFT Code": "BTRLRO22HRO",
    "Bank Name": "BANCA TRANSILVANIA S.A.",
    "Address": "STR. KOSSUTH LAJOS 1",
    "City": "ODORHEIU SECUIESC",
    "Branch": "ODORHEIU SECUIESC",
    "Postcode": "535600",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BTRL",
    "bankCode": "RO",
    "branchCode": "BCO",
    "SWIFT Code": "BTRLRO22BCO",
    "Bank Name": "BANCA TRANSILVANIA S.A.",
    "Address": "STR. OITUZ 23",
    "City": "ONESTI",
    "Branch": "ONESTI",
    "Postcode": "601032",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BTRL",
    "bankCode": "RO",
    "branchCode": "BHA",
    "SWIFT Code": "BTRLRO22BHA",
    "Bank Name": "BANCA TRANSILVANIA S.A.",
    "Address": "DACIA AVENUE 23",
    "City": "ORADEA",
    "Branch": "ORADEA BRANCH",
    "Postcode": "410457",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BTRL",
    "bankCode": "RO",
    "branchCode": "HDP",
    "SWIFT Code": "BTRLRO22HDP",
    "Bank Name": "BANCA TRANSILVANIA S.A.",
    "Address": "STR. N.BALCESCU 2",
    "City": "PETROSANI",
    "Branch": "PETROSANI",
    "Postcode": "332025",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BTRL",
    "bankCode": "RO",
    "branchCode": "NTA",
    "SWIFT Code": "BTRLRO22NTA",
    "Bank Name": "BANCA TRANSILVANIA S.A.",
    "Address": "STEFAN CEL MARE STREET 3",
    "City": "PIATRA NEAMT",
    "Branch": "NEAMT BRANCH",
    "Postcode": "610109",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BTRL",
    "bankCode": "RO",
    "branchCode": "AGA",
    "SWIFT Code": "BTRLRO22AGA",
    "Bank Name": "BANCA TRANSILVANIA S.A.",
    "Address": "I.C. BRATIANU 29",
    "City": "PITESTI",
    "Branch": "PITESTI BRANCH",
    "Postcode": "110005",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BTRL",
    "bankCode": "RO",
    "branchCode": "PHA",
    "SWIFT Code": "BTRLRO22PHA",
    "Bank Name": "BANCA TRANSILVANIA S.A.",
    "Address": "TARGOVISTEI STREET 6",
    "City": "PLOIESTI",
    "Branch": "PLOIESTI BRANCH",
    "Postcode": "100383",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BTRL",
    "bankCode": "RO",
    "branchCode": "SVR",
    "SWIFT Code": "BTRLRO22SVR",
    "Bank Name": "BANCA TRANSILVANIA S.A.",
    "Address": "P-TA UNIRII 33",
    "City": "RADAUTI",
    "Branch": "AG. RADAUTI",
    "Postcode": "725400",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BTRL",
    "bankCode": "RO",
    "branchCode": "BZR",
    "SWIFT Code": "BTRLRO22BZR",
    "Bank Name": "BANCA TRANSILVANIA S.A.",
    "Address": "BL.13 F, STR. VICTORIEI",
    "City": "RAMNICU SARAT",
    "Branch": "RAMNICU SARAT",
    "Postcode": "125300",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BTRL",
    "bankCode": "RO",
    "branchCode": "VLA",
    "SWIFT Code": "BTRLRO22VLA",
    "Bank Name": "BANCA TRANSILVANIA S.A.",
    "Address": "STIRBEI VODA STREET T 1",
    "City": "RAMNICU VALCEA",
    "Branch": "VALCEA BRANCH",
    "Postcode": "240184",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BTRL",
    "bankCode": "RO",
    "branchCode": "MSR",
    "SWIFT Code": "BTRLRO22MSR",
    "Bank Name": "BANCA TRANSILVANIA S.A.",
    "Address": "P-TA MIHAI VITEAZUL 2",
    "City": "REGHIN",
    "Branch": "AG. REGHIN",
    "Postcode": "545300",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BTRL",
    "bankCode": "RO",
    "branchCode": "CSA",
    "SWIFT Code": "BTRLRO22CSA",
    "Bank Name": "BANCA TRANSILVANIA S.A.",
    "Address": "I.L.CARAGIALE STREET",
    "City": "RESITA",
    "Branch": "RESITA",
    "Postcode": "320068",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BTRL",
    "bankCode": "RO",
    "branchCode": "NTR",
    "SWIFT Code": "BTRLRO22NTR",
    "Bank Name": "BANCA TRANSILVANIA S.A.",
    "Address": "BL. 16, STR. NICULAE TITULESCU",
    "City": "ROMAN",
    "Branch": "AG. ROMAN",
    "Postcode": "210247",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BTRL",
    "bankCode": "RO",
    "branchCode": "SMA",
    "SWIFT Code": "BTRLRO22SMA",
    "Bank Name": "BANCA TRANSILVANIA S.A.",
    "Address": "25 OCTOMBRIE SQUARE 12",
    "City": "SATU MARE",
    "Branch": "SATU MARE BRANCH",
    "Postcode": "440026",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BTRL",
    "bankCode": "RO",
    "branchCode": "CVA",
    "SWIFT Code": "BTRLRO22CVA",
    "Bank Name": "BANCA TRANSILVANIA S.A.",
    "Address": "KOSSUTH LAJOS STREET 10",
    "City": "SFANTU GHEORGHE",
    "Branch": "SFANTU GHEORGHE BRANCH",
    "Postcode": "520008",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BTRL",
    "bankCode": "RO",
    "branchCode": "SBA",
    "SWIFT Code": "BTRLRO22SBA",
    "Bank Name": "BANCA TRANSILVANIA S.A.",
    "Address": "SOMESULUI STREET 57",
    "City": "SIBIU",
    "Branch": "SIBIU BRANCH",
    "Postcode": "550003",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BTRL",
    "bankCode": "RO",
    "branchCode": "MMS",
    "SWIFT Code": "BTRLRO22MMS",
    "Bank Name": "BANCA TRANSILVANIA S.A.",
    "Address": "P-TA LIBERTATII 10",
    "City": "SIGHET",
    "Branch": "AG. SIGHET",
    "Postcode": "435500",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BTRL",
    "bankCode": "RO",
    "branchCode": "OTA",
    "SWIFT Code": "BTRLRO22OTA",
    "Bank Name": "BANCA TRANSILVANIA S.A.",
    "Address": "BD. A.I. CUZA BL. UNION",
    "City": "SLATINA",
    "Branch": "SLATINA",
    "Postcode": "230025",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BTRL",
    "bankCode": "RO",
    "branchCode": "ILA",
    "SWIFT Code": "BTRLRO22ILA",
    "Bank Name": "BANCA TRANSILVANIA S.A.",
    "Address": "BL.U40, UNIRII STREET",
    "City": "SLOBOZIA",
    "Branch": "SLOBOZIA",
    "Postcode": "920012",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BTRL",
    "bankCode": "RO",
    "branchCode": "SVA",
    "SWIFT Code": "BTRLRO22SVA",
    "Bank Name": "BANCA TRANSILVANIA S.A.",
    "Address": "NICOLAE BALCESCU STREET 6",
    "City": "SUCEAVA",
    "Branch": "SUCEAVA BRANCH",
    "Postcode": "725700",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BTRL",
    "bankCode": "RO",
    "branchCode": "DBA",
    "SWIFT Code": "BTRLRO22DBA",
    "Bank Name": "BANCA TRANSILVANIA S.A.",
    "Address": "LIBERTATI STREET 66",
    "City": "TARGOVISTE",
    "Branch": "DAMBOVITA BRANCH",
    "Postcode": "727610",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BTRL",
    "bankCode": "RO",
    "branchCode": "GJA",
    "SWIFT Code": "BTRLRO22GJA",
    "Bank Name": "BANCA TRANSILVANIA S.A.",
    "Address": "STR. TRAIAN 33",
    "City": "TARGU JIU",
    "Branch": "TG. JIU BRANCH",
    "Postcode": "210147",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BTRL",
    "bankCode": "RO",
    "branchCode": "MSA",
    "SWIFT Code": "BTRLRO22MSA",
    "Bank Name": "BANCA TRANSILVANIA S.A.",
    "Address": "1 DECEMBRE 1918 AVENUE 35",
    "City": "TARGU MURES",
    "Branch": "MURES BRANCH",
    "Postcode": "550200",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BTRL",
    "bankCode": "RO",
    "branchCode": "NTT",
    "SWIFT Code": "BTRLRO22NTT",
    "Bank Name": "BANCA TRANSILVANIA S.A.",
    "Address": "BL.M4, STR. STEFAN CEL MARE",
    "City": "TARGU NEAMT",
    "Branch": "TARGU NEAMT",
    "Postcode": "615200",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BTRL",
    "bankCode": "RO",
    "branchCode": "CVT",
    "SWIFT Code": "BTRLRO22CVT",
    "Bank Name": "BANCA TRANSILVANIA S.A.",
    "Address": "BL 2, STR.GHEORGHE DOJA 40",
    "City": "TARGU SECUIESC",
    "Branch": "AG. TG. SECUIESC",
    "Postcode": "525400",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BTRL",
    "bankCode": "RO",
    "branchCode": "GLT",
    "SWIFT Code": "BTRLRO22GLT",
    "Bank Name": "BANCA TRANSILVANIA S.A.",
    "Address": "STR. 1 DECEMBRIE 1918 46",
    "City": "TECUCI",
    "Branch": "TECUCI",
    "Postcode": "805300",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BTRL",
    "bankCode": "RO",
    "branchCode": "TMA",
    "SWIFT Code": "BTRLRO22TMA",
    "Bank Name": "BANCA TRANSILVANIA S.A.",
    "Address": "RODNEI STREET 1",
    "City": "TIMISOARA",
    "Branch": "TIMISOARA BRANCH",
    "Postcode": "307285",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BTRL",
    "bankCode": "RO",
    "branchCode": "CJT",
    "SWIFT Code": "BTRLRO22CJT",
    "Bank Name": "BANCA TRANSILVANIA S.A.",
    "Address": "ROMANA SQUARE 15",
    "City": "TURDA",
    "Branch": "TURDA BRANCH",
    "Postcode": "400000",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BTRL",
    "bankCode": "RO",
    "branchCode": "MHA",
    "SWIFT Code": "BTRLRO22MHA",
    "Bank Name": "BANCA TRANSILVANIA S.A.",
    "Address": "TRAIAN STREET 83",
    "City": "TURNU SEVERIN",
    "Branch": "MEHEDINTI BRANCH",
    "Postcode": "220134",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BTRL",
    "bankCode": "RO",
    "branchCode": "SVV",
    "SWIFT Code": "BTRLRO22SVV",
    "Bank Name": "BANCA TRANSILVANIA S.A.",
    "Address": "STR. MIHAI EMINESCU 29",
    "City": "VATRA DORNEI",
    "Branch": "VATRA DORNEI",
    "Postcode": "725700",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BTRL",
    "bankCode": "RO",
    "branchCode": "SJA",
    "SWIFT Code": "BTRLRO22SJA",
    "Bank Name": "BANCA TRANSILVANIA S.A.",
    "Address": "UNIRII SQUARE 1",
    "City": "ZALAU",
    "Branch": "ZALAU BRANCH",
    "Postcode": "300085",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BKCH",
    "bankCode": "RO",
    "branchCode": "OBU",
    "SWIFT Code": "BKCHROBU",
    "Bank Name": "BANK OF CHINA (CENTRAL AND EASTERN EUROPE) LIMITED BUCHAREST BRANCH",
    "Address": "SOUTH TOWER OF BUILLDING CITY GATE, PIATA PRESEI LIBERE 3-5, FLOOR 11, DISTRICT 1",
    "City": "BUCHAREST",
    "Branch": "",
    "Postcode": "013702",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BLOM",
    "bankCode": "RO",
    "branchCode": "OBU",
    "SWIFT Code": "BLOMROBU",
    "Bank Name": "BANQUE BANORIENT FRANCE",
    "Address": "BLOCK K3 UNIRII BOULEVARD 66,, FLOOR MEZZANINE",
    "City": "BUCHAREST",
    "Branch": "",
    "Postcode": "030835",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BCRL",
    "bankCode": "RO",
    "branchCode": "OBU",
    "SWIFT Code": "BCRLROBU",
    "Bank Name": "BCR BANCA PENTRU LOCUINTE S.A.",
    "Address": "BUSINESS GARDEN BUCHAREST BLDG A, CALEA PLEVNEI 159, FLOOR 4, ROOMS, E4-14 - E4-26",
    "City": "BUCHAREST",
    "Branch": "",
    "Postcode": "060013",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BNPA",
    "bankCode": "RO",
    "branchCode": "OBU",
    "SWIFT Code": "BNPAROBU",
    "Bank Name": "BNP PARIBAS PERSONAL FINANCE S.A. PARIS SUCURSALA BUCURESTI",
    "Address": "CLUCERULUI STREET 78-80, FLOOR 6, SECTOR 1",
    "City": "BUCHAREST",
    "Branch": "",
    "Postcode": "011368",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "FTSB",
    "bankCode": "RO",
    "branchCode": "OBU",
    "SWIFT Code": "FTSBROBU",
    "Bank Name": "BNP PARIBAS S.A. PARIS SUCURSALA BUCURESTI",
    "Address": "C BUILDING, SOSEAUA PIPERA 46D-46E-48, FLOOR 6, DISTRICT 6",
    "City": "BUCHAREST",
    "Branch": "",
    "Postcode": "020309",
    "Country": "Romania",
    "Connection": "Active"
  },
  {
    "countryCode": "BRDE",
    "bankCode": "RO",
    "branchCode": "OBU",
    "SWIFT Code": "BRDEROBU",
    "Bank Name": "BRD - GROUPE SOCIETE GENERALE SA",
    "Address": "ION MIHALACHE BOULEVARD 1-7, 1. DISTRICT",
    "City": "BUCHAREST",
    "Branch": "",
    "Postcode": "011171",
    "Country": "Romania",
    "Connection": "Active"
  }
]
module.exports = romania
