const saintKittsAndNevis = [
  {
    "bankCode": "BNEI",
    "countryCode": "KN",
    "branchCode": "NNE",
    "SWIFT Code": "BNEIKNNE",
    "Bank Name": "BANK OF NEVIS INTERNATIONAL LIMITED",
    "Address": "450 MAIN STREET",
    "City": "CHARLESTOWN",
    "Branch": "",
    "Postcode": "KN1201",
    "Country": "Saint Kitts and Nevis",
    "Connection": "Active"
  },
  {
    "bankCode": "BNEV",
    "countryCode": "KN",
    "branchCode": "NNE",
    "SWIFT Code": "BNEVKNNE",
    "Bank Name": "BANK OF NEVIS, THE",
    "Address": "MAIN STREET",
    "City": "CHARLESTOWN",
    "Branch": "",
    "Postcode": "KN0302",
    "Country": "Saint Kitts and Nevis",
    "Connection": "Active"
  },
  {
    "bankCode": "ECCB",
    "countryCode": "KN",
    "branchCode": "NSK",
    "SWIFT Code": "ECCBKNSK",
    "Bank Name": "EASTERN CARIBBEAN CENTRAL BANK",
    "Address": "BIRD ROCK ROAD",
    "City": "BASSETERRE",
    "Branch": "",
    "Postcode": "KN7000",
    "Country": "Saint Kitts and Nevis",
    "Connection": "Active"
  },
  {
    "bankCode": "ECSX",
    "countryCode": "KN",
    "branchCode": "NSK",
    "SWIFT Code": "ECSXKNSK",
    "Bank Name": "EASTERN CARIBBEAN SECURITIES EXCHANGE LTD",
    "Address": "ECCB CAMPUS,PHASE 2 BLDG, BIRD ROCK ROAD",
    "City": "BASSETERRE",
    "Branch": "",
    "Postcode": "KN7000",
    "Country": "Saint Kitts and Nevis",
    "Connection": "Active"
  },
  {
    "bankCode": "FCIB",
    "countryCode": "KN",
    "branchCode": "NSK",
    "SWIFT Code": "FCIBKNSK",
    "Bank Name": "FIRSTCARIBBEAN INTERNATIONAL BANK (BARBADOS) LIMITED",
    "Address": "THE CIRCUS",
    "City": "BASSETERRE",
    "Branch": "",
    "Postcode": "KN0104",
    "Country": "Saint Kitts and Nevis",
    "Connection": "Active"
  },
  {
    "bankCode": "GVKN",
    "countryCode": "KN",
    "branchCode": "NSK",
    "SWIFT Code": "GVKNKNSK",
    "Bank Name": "GOVERMENT OF ST. KITTS AND NEVIS",
    "Address": "MINISTRY OF FINANCE, CHURCH STREET",
    "City": "BASSETERRE",
    "Branch": "",
    "Postcode": "KN0104",
    "Country": "Saint Kitts and Nevis",
    "Connection": "Active"
  },
  {
    "bankCode": "NIBT",
    "countryCode": "KN",
    "branchCode": "NNE",
    "SWIFT Code": "NIBTKNNE",
    "Bank Name": "HAMILTON RESERVE BANK LTD.",
    "Address": "HAMILTON RESERVE BANK PLAZA, JESSUPS ESTATE",
    "City": "NEVIS",
    "Branch": "",
    "Postcode": "KN1202",
    "Country": "Saint Kitts and Nevis",
    "Connection": "Active"
  },
  {
    "bankCode": "RBNK",
    "countryCode": "KN",
    "branchCode": "NSK",
    "SWIFT Code": "RBNKKNSK",
    "Bank Name": "REPUBLIC BANK (EC) LIMITED",
    "Address": "FORT STREET",
    "City": "BASSETERRE",
    "Branch": "",
    "Postcode": "KN0104",
    "Country": "Saint Kitts and Nevis",
    "Connection": "Active"
  },
  {
    "bankCode": "RBNK",
    "countryCode": "KN",
    "branchCode": "KNA",
    "SWIFT Code": "RBNKKNSKKNA",
    "Bank Name": "REPUBLIC BANK (EC) LIMITED",
    "Address": "FORT STREET",
    "City": "BASSETERRE",
    "Branch": "SETTLEMENTS",
    "Postcode": "KN0104",
    "Country": "Saint Kitts and Nevis",
    "Connection": "Active"
  },
  {
    "bankCode": "KNAN",
    "countryCode": "KN",
    "branchCode": "NSK",
    "SWIFT Code": "KNANKNSK",
    "Bank Name": "ST. KITTS-NEVIS-ANGUILLA NATIONAL BANK",
    "Address": "CENTRAL STREET",
    "City": "BASSETERRE",
    "Branch": "",
    "Postcode": "KN0104",
    "Country": "Saint Kitts and Nevis",
    "Connection": "Active"
  },
  {}
]
module.exports = saintKittsAndNevis
