const saintLucia = [
  {
    "countryCode": "LUOB",
    "bankCode": "LC",
    "branchCode": "CLC",
    "SWIFT Code": "LUOBLCLC",
    "Bank Name": "1ST NATIONAL BANK ST.LUCIA LIMITED",
    "Address": "21 BRIDGE STREET",
    "City": "CASTRIES",
    "Branch": "",
    "Postcode": "LC04 101",
    "Country": "Saint Lucia",
    "Connection": "Active"
  },
  {
    "countryCode": "BOSL",
    "bankCode": "LC",
    "branchCode": "CLC",
    "SWIFT Code": "BOSLLCLC",
    "Bank Name": "BANK OF SAINT LUCIA LIMITED",
    "Address": "FLOOR 4, FINANCIAL CENTER, 1 BRIDGE STREET",
    "City": "CASTRIES",
    "Branch": "",
    "Postcode": "LC04 101",
    "Country": "Saint Lucia",
    "Connection": "Active"
  },
  {
    "countryCode": "HMBT",
    "bankCode": "LC",
    "branchCode": "CLC",
    "SWIFT Code": "HMBTLCLC",
    "Bank Name": "BERKELEY BANK AND TRUST LIMITED",
    "Address": "FLOOR 1, UNIT 104 , JOHNSONS CENTER, 2 BELLA ROSA ROAD",
    "City": "GROS-ISLET",
    "Branch": "",
    "Postcode": "LC01 601",
    "Country": "Saint Lucia",
    "Connection": "Active"
  },
  {
    "countryCode": "FCIB",
    "bankCode": "LC",
    "branchCode": "CLC",
    "SWIFT Code": "FCIBLCLC",
    "Bank Name": "FIRSTCARIBBEAN INTERNATIONAL BANK (BARBADOS) LIMITED",
    "Address": "BRIDGE STREET",
    "City": "CASTRIES",
    "Branch": "",
    "Postcode": "LC04 101",
    "Country": "Saint Lucia",
    "Connection": "Active"
  },
  {
    "countryCode": "GVLC",
    "bankCode": "LC",
    "branchCode": "CLC",
    "SWIFT Code": "GVLCLCLC",
    "Bank Name": "GOVERNMENT OF SAINT LUCIA",
    "Address": "POINTE SERAPHINE",
    "City": "CASTRIES",
    "Branch": "",
    "Postcode": "LC04 301",
    "Country": "Saint Lucia",
    "Connection": "Active"
  },
  {
    "countryCode": "HEMM",
    "bankCode": "LC",
    "branchCode": "CL2",
    "SWIFT Code": "HEMMLCL2",
    "Bank Name": "HERMES BANK LIMITED",
    "Address": "MERIDIAN PLACE, 1 CHOC ESTATE",
    "City": "CASTRIES",
    "Branch": "",
    "Postcode": "LC02 501",
    "Country": "Saint Lucia",
    "Connection": "Active"
  },
  {
    "countryCode": "PTRV",
    "bankCode": "LC",
    "branchCode": "CLC",
    "SWIFT Code": "PTRVLCLC",
    "Bank Name": "PETRUS PRIVATE BANK LIMITED",
    "Address": "5 MARINA VILLAGE, MARIGOT BAY",
    "City": "CASTRIES",
    "Branch": "",
    "Postcode": "LC07 301",
    "Country": "Saint Lucia",
    "Connection": "Active"
  },
  {
    "countryCode": "BSLU",
    "bankCode": "LC",
    "branchCode": "CLC",
    "SWIFT Code": "BSLULCLC",
    "Bank Name": "PROVEN BANK (SAINT LUCIA) LIMITED",
    "Address": "PROVEN HOUSE, GROS ISLET HIGHWAY, RODNEY BAY MARINA",
    "City": "GROS-ISLET",
    "Branch": "",
    "Postcode": "LC01 401",
    "Country": "Saint Lucia",
    "Connection": "Active"
  },
  {
    "countryCode": "RBNK",
    "bankCode": "LC",
    "branchCode": "CLC",
    "SWIFT Code": "RBNKLCLC",
    "Bank Name": "REPUBLIC BANK (EC) LIMITED",
    "Address": "6 WM PETER BOULEVARD",
    "City": "CASTRIES",
    "Branch": "",
    "Postcode": "LC04 101",
    "Country": "Saint Lucia",
    "Connection": "Active"
  },
  {
    "countryCode": "RBNK",
    "bankCode": "LC",
    "branchCode": "LCA",
    "SWIFT Code": "RBNKLCLCLCA",
    "Bank Name": "REPUBLIC BANK (EC) LIMITED",
    "Address": "6 WM PETER BOULEVARD",
    "City": "CASTRIES",
    "Branch": "SETTLEMENTS",
    "Postcode": "LC04 101",
    "Country": "Saint Lucia",
    "Connection": "Active"
  },
  {
    "countryCode": "STTT",
    "bankCode": "LC",
    "branchCode": "CLC",
    "SWIFT Code": "STTTLCLC",
    "Bank Name": "STATETRUST BANK AND TRUST LTD.",
    "Address": "MASSADE",
    "City": "GROS-ISLET",
    "Branch": "",
    "Postcode": "LC04 301",
    "Country": "Saint Lucia",
    "Connection": "Active"
  }
]
module.exports = saintLucia
