const sanMarino = [
  {
    "bankCode": "BASM",
    "countryCode": "SM",
    "branchCode": "MSM",
    "SWIFT Code": "BASMSMSM",
    "Bank Name": "BANCA AGRICOLA COMMERCIALE ISTITUTO BANCARIO SAMMARINESE S.P.A.",
    "Address": "PIAZZA MARINO TINI , 26",
    "City": "DOGANA",
    "Branch": "",
    "Postcode": "47891",
    "Country": "San Marino",
    "Connection": "Active"
  },
  {
    "bankCode": "ICSM",
    "countryCode": "SM",
    "branchCode": "MSM",
    "SWIFT Code": "ICSMSMSM",
    "Bank Name": "BANCA CENTRALE DELLA REPUBBLICA DI SAN MARINO",
    "Address": "VIA DEL VOLTONE , 120",
    "City": "SAN MARINO",
    "Branch": "",
    "Postcode": "47890",
    "Country": "San Marino",
    "Connection": "Active"
  },
  {
    "bankCode": "MAOI",
    "countryCode": "SM",
    "branchCode": "013",
    "SWIFT Code": "MAOISMSM013",
    "Bank Name": "BANCA DI SAN MARINO SPA",
    "Address": "VIA VITTORIO SCIALOJA , 4",
    "City": "CAILUNGO",
    "Branch": "SUCCURSALE CAILUNGO",
    "Postcode": "47893",
    "Country": "San Marino",
    "Connection": "Active"
  },
  {
    "bankCode": "MAOI",
    "countryCode": "SM",
    "branchCode": "010",
    "SWIFT Code": "MAOISMSM010",
    "Bank Name": "BANCA DI SAN MARINO SPA",
    "Address": "VIA CAMPOLUNGO , 59",
    "City": "DOGANA",
    "Branch": "CORPORATE",
    "Postcode": "47891",
    "Country": "San Marino",
    "Connection": "Active"
  },
  {
    "bankCode": "MAOI",
    "countryCode": "SM",
    "branchCode": "002",
    "SWIFT Code": "MAOISMSM002",
    "Bank Name": "BANCA DI SAN MARINO SPA",
    "Address": "VIA TRE SETTEMBRE , 252",
    "City": "DOGANA",
    "Branch": "SUCCURSALE DOGANA",
    "Postcode": "47891",
    "Country": "San Marino",
    "Connection": "Active"
  },
  {
    "bankCode": "MAOI",
    "countryCode": "SM",
    "branchCode": "003",
    "SWIFT Code": "MAOISMSM003",
    "Bank Name": "BANCA DI SAN MARINO SPA",
    "Address": "VIA 25 MARZO , 4",
    "City": "DOMAGNANO",
    "Branch": "SUCCURSALE DOMAGNANO",
    "Postcode": "47895",
    "Country": "San Marino",
    "Connection": "Active"
  },
  {
    "bankCode": "MAOI",
    "countryCode": "SM",
    "branchCode": "MSM",
    "SWIFT Code": "MAOISMSM",
    "Bank Name": "BANCA DI SAN MARINO SPA",
    "Address": "STRADA DELLA CROCE , 39",
    "City": "FAETANO",
    "Branch": "",
    "Postcode": "47896",
    "Country": "San Marino",
    "Connection": "Active"
  },
  {
    "bankCode": "MAOI",
    "countryCode": "SM",
    "branchCode": "006",
    "SWIFT Code": "MAOISMSM006",
    "Bank Name": "BANCA DI SAN MARINO SPA",
    "Address": "VIA STRADA DELLA CROCE , 39",
    "City": "FAETANO",
    "Branch": "SEDE FAETANO",
    "Postcode": "47896",
    "Country": "San Marino",
    "Connection": "Active"
  },
  {
    "bankCode": "MAOI",
    "countryCode": "SM",
    "branchCode": "009",
    "SWIFT Code": "MAOISMSM009",
    "Bank Name": "BANCA DI SAN MARINO SPA",
    "Address": "VIA F. DA MONTEBELLO , 22",
    "City": "GUALDICCIOLO",
    "Branch": "SUCCURSALE GUALDICCIOLO",
    "Postcode": "47892",
    "Country": "San Marino",
    "Connection": "Active"
  },
  {
    "bankCode": "MAOI",
    "countryCode": "SM",
    "branchCode": "011",
    "SWIFT Code": "MAOISMSM011",
    "Bank Name": "BANCA DI SAN MARINO SPA",
    "Address": "VIA DEL SERRONE , 67/B",
    "City": "MURATA",
    "Branch": "SUCCURSALE MURATA",
    "Postcode": "47890",
    "Country": "San Marino",
    "Connection": "Active"
  },
  {
    "bankCode": "MAOI",
    "countryCode": "SM",
    "branchCode": "001",
    "SWIFT Code": "MAOISMSM001",
    "Bank Name": "BANCA DI SAN MARINO SPA",
    "Address": "VIA GINO GIACOMINI , 128",
    "City": "SAN MARINO",
    "Branch": "SUCCURSALE CITTA'",
    "Postcode": "47890",
    "Country": "San Marino",
    "Connection": "Active"
  },
  {
    "bankCode": "MAOI",
    "countryCode": "SM",
    "branchCode": "005",
    "SWIFT Code": "MAOISMSM005",
    "Bank Name": "BANCA DI SAN MARINO SPA",
    "Address": "VIA O. SCARITO , 68",
    "City": "VALDRAGONE",
    "Branch": "SUCCURSALE BORGO MAGGIORE",
    "Postcode": "47893",
    "Country": "San Marino",
    "Connection": "Active"
  },
  {
    "bankCode": "BSDI",
    "countryCode": "SM",
    "branchCode": "MSD",
    "SWIFT Code": "BSDISMSD",
    "Bank Name": "BANCA SAMMARINESE DI INVESTIMENTO S.P.A.",
    "Address": "VIA MONALDO DA FALCIANO , 3",
    "City": "ROVERETA",
    "Branch": "",
    "Postcode": "47891",
    "Country": "San Marino",
    "Connection": "Active"
  },
  {
    "bankCode": "BKNN",
    "countryCode": "SM",
    "branchCode": "MSM",
    "SWIFT Code": "BKNNSMSM",
    "Bank Name": "BKN301 S.P.A.",
    "Address": "ADMIRAL, FLOOR 2, VIA TRE SETTEMBRE, 99",
    "City": "DOGANA",
    "Branch": "",
    "Postcode": "47891",
    "Country": "San Marino",
    "Connection": "Active"
  },
  {
    "bankCode": "CSSM",
    "countryCode": "SM",
    "branchCode": "MSM",
    "SWIFT Code": "CSSMSMSM",
    "Bank Name": "CASSA DI RISPARMIO DELLA REPUBLICA DI SAN MARINO",
    "Address": "PIAZZETTA DEL TITANO , 2",
    "City": "SAN MARINO",
    "Branch": "",
    "Postcode": "47890",
    "Country": "San Marino",
    "Connection": "Active"
  }
]
module.exports = sanMarino
