const serbia = [
  {
    "countryCode": "OPPB",
    "bankCode": "RS",
    "branchCode": "S22",
    "SWIFT Code": "OPPBRS22",
    "Bank Name": "3 BANKA A.D. NOVI SAD",
    "Address": "BULEVAR OSLOBODJENJA 2A",
    "City": "NOVI SAD",
    "Branch": "",
    "Postcode": "21000",
    "Country": "Serbia",
    "Connection": "Active"
  },
  {
    "countryCode": "HAAB",
    "bankCode": "RS",
    "branchCode": "SBG",
    "SWIFT Code": "HAABRSBG",
    "Bank Name": "ADDIKO BANK A.D. BEOGRAD",
    "Address": "MILUTINA MILANKOVICA 7V",
    "City": "NOVI BEOGRAD",
    "Branch": "",
    "Postcode": "11070",
    "Country": "Serbia",
    "Connection": "Active"
  },
  {
    "countryCode": "LIKI",
    "bankCode": "RS",
    "branchCode": "SBG",
    "SWIFT Code": "LIKIRSBG",
    "Bank Name": "ADRIATIC BANK AD BEOGRAD",
    "Address": "DALMATINSKA 22",
    "City": "BEOGRAD",
    "Branch": "",
    "Postcode": "11000",
    "Country": "Serbia",
    "Connection": "Active"
  },
  {
    "countryCode": "AIKB",
    "bankCode": "RS",
    "branchCode": "S22",
    "SWIFT Code": "AIKBRS22",
    "Bank Name": "AIK BANKA AD",
    "Address": "DJ BULEVAR MIHAILA PUPINA 115",
    "City": "BEOGRAD",
    "Branch": "",
    "Postcode": "11070",
    "Country": "Serbia",
    "Connection": "Active"
  },
  {
    "countryCode": "JMBN",
    "bankCode": "RS",
    "branchCode": "SBG",
    "SWIFT Code": "JMBNRSBG",
    "Bank Name": "ALTA BANKA A.D. BEOGRAD",
    "Address": "BULEVAR ZORANA DJINDJICA 121",
    "City": "BEOGRAD",
    "Branch": "",
    "Postcode": "11070",
    "Country": "Serbia",
    "Connection": "Active"
  },
  {
    "countryCode": "APIB",
    "bankCode": "RS",
    "branchCode": "SBG",
    "SWIFT Code": "APIBRSBG",
    "Bank Name": "API BANK AD BEOGRAD",
    "Address": "BALKANSKA 2",
    "City": "BEOGRAD",
    "Branch": "",
    "Postcode": "11000",
    "Country": "Serbia",
    "Connection": "Active"
  },
  {
    "countryCode": "DBDB",
    "bankCode": "RS",
    "branchCode": "SBG",
    "SWIFT Code": "DBDBRSBG",
    "Bank Name": "BANCA INTESA AD, BEOGRAD",
    "Address": "MILENTIJA POPOVICA 7B",
    "City": "BEOGRAD",
    "Branch": "",
    "Postcode": "11070",
    "Country": "Serbia",
    "Connection": "Active"
  },
  {
    "countryCode": "BKCH",
    "bankCode": "RS",
    "branchCode": "SBG",
    "SWIFT Code": "BKCHRSBG",
    "Bank Name": "BANK OF CHINA SRBIJA A.D. BEOGRAD",
    "Address": "ZORANA DINDICA BLVD 2A",
    "City": "BEOGRAD",
    "Branch": "",
    "Postcode": "11070",
    "Country": "Serbia",
    "Connection": "Active"
  },
  {
    "countryCode": "CRPK",
    "bankCode": "RS",
    "branchCode": "SBB",
    "SWIFT Code": "CRPKRSBB",
    "Bank Name": "CENTRALNI REGISTAR DEPO I KLIRING HARTIJA OD VREDNOSTI AKCIONARSKO DRUSTVO, BEOGRAD",
    "Address": "TRG REPUBLIKE 5",
    "City": "BEOGRAD",
    "Branch": "",
    "Postcode": "11000",
    "Country": "Serbia",
    "Connection": "Active"
  },
  {
    "countryCode": "GIBA",
    "bankCode": "RS",
    "branchCode": "S22",
    "SWIFT Code": "GIBARS22",
    "Bank Name": "ERSTE BANK A.D. NOVI SAD",
    "Address": "BULEVAR OSLOBODJENJA 5",
    "City": "NOVI SAD",
    "Branch": "",
    "Postcode": "21000",
    "Country": "Serbia",
    "Connection": "Active"
  },
  {
    "countryCode": "ERBK",
    "bankCode": "RS",
    "branchCode": "SBG",
    "SWIFT Code": "ERBKRSBG",
    "Bank Name": "EUROBANK DIREKTNA A.D.",
    "Address": "VUKA KARADZICA 10",
    "City": "BEOGRAD",
    "Branch": "",
    "Postcode": "11000",
    "Country": "Serbia",
    "Connection": "Active"
  },
  {
    "countryCode": "ERBK",
    "bankCode": "RS",
    "branchCode": "SEC",
    "SWIFT Code": "ERBKRSBGSEC",
    "Bank Name": "EUROBANK DIREKTNA A.D.",
    "Address": "VUKA KARADZICA 10",
    "City": "BEOGRAD",
    "Branch": "CUSTODY UNIT",
    "Postcode": "11000",
    "Country": "Serbia",
    "Connection": "Active"
  },
  {
    "countryCode": "CABA",
    "bankCode": "RS",
    "branchCode": "S22",
    "SWIFT Code": "CABARS22",
    "Bank Name": "HALKBANK A.D. BEOGRAD",
    "Address": "MILUTINA MILANKOVICA 9E",
    "City": "BEOGRAD",
    "Branch": "",
    "Postcode": "11000",
    "Country": "Serbia",
    "Connection": "Active"
  },
  {
    "countryCode": "MRBN",
    "bankCode": "RS",
    "branchCode": "SBG",
    "SWIFT Code": "MRBNRSBG",
    "Bank Name": "MIRABANK A.D. BEOGRAD NOVI BEOGRAD",
    "Address": "BLUE CENTER, SPANSKIH BORACA 3",
    "City": "NOVI BEOGRAD",
    "Branch": "",
    "Postcode": "11070",
    "Country": "Serbia",
    "Connection": "Active"
  },
  {
    "countryCode": "AAAA",
    "bankCode": "RS",
    "branchCode": "SBG",
    "SWIFT Code": "AAAARSBG",
    "Bank Name": "MOBI BANKA AD",
    "Address": "OMLADINSKIH BRIGADA 90V",
    "City": "BEOGRAD",
    "Branch": "",
    "Postcode": "11070",
    "Country": "Serbia",
    "Connection": "Active"
  },
  {
    "countryCode": "NBSR",
    "bankCode": "RS",
    "branchCode": "SBD",
    "SWIFT Code": "NBSRRSBD",
    "Bank Name": "NARODNA BANKA SRBIJE (NATIONAL BANK OF SERBIA - NBS)",
    "Address": "KRALJA PETRA 12",
    "City": "BEOGRAD",
    "Branch": "",
    "Postcode": "11000",
    "Country": "Serbia",
    "Connection": "Active"
  },
  {
    "countryCode": "NBSR",
    "bankCode": "RS",
    "branchCode": "SBG",
    "SWIFT Code": "NBSRRSBG",
    "Bank Name": "NARODNA BANKA SRBIJE (NATIONAL BANK OF SERBIA - NBS)",
    "Address": "KRALJA PETRA 12",
    "City": "BEOGRAD",
    "Branch": "",
    "Postcode": "11000",
    "Country": "Serbia",
    "Connection": "Active"
  },
  {
    "countryCode": "KOBB",
    "bankCode": "RS",
    "branchCode": "SBG",
    "SWIFT Code": "KOBBRSBG",
    "Bank Name": "NLB KOMERCIJALNA BANKA AD BEOGRAD",
    "Address": "SVETOG SAVE 14",
    "City": "BEOGRAD",
    "Branch": "",
    "Postcode": "11000",
    "Country": "Serbia",
    "Connection": "Active"
  },
  {
    "countryCode": "OTPV",
    "bankCode": "RS",
    "branchCode": "S22",
    "SWIFT Code": "OTPVRS22",
    "Bank Name": "OTP BANKA SRBIJA AKCIONARSKO DRUSTVO NOVI SAD",
    "Address": "BULEVAR OSLOBODJENJA 80",
    "City": "NOVI SAD",
    "Branch": "",
    "Postcode": "21000",
    "Country": "Serbia",
    "Connection": "Active"
  },
  {
    "countryCode": "PADO",
    "bankCode": "RS",
    "branchCode": "S22",
    "SWIFT Code": "PADORS22",
    "Bank Name": "PAYSPOT DOO",
    "Address": "BRANIMIRA COSICA 2/II/201B",
    "City": "NOVI SAD",
    "Branch": "",
    "Postcode": "21000",
    "Country": "Serbia",
    "Connection": "Active"
  },
  {
    "countryCode": "SBPO",
    "bankCode": "RS",
    "branchCode": "SBG",
    "SWIFT Code": "SBPORSBG",
    "Bank Name": "POSTAL SAVINGS BANK JSC",
    "Address": "KRALJICE MARIJE 3",
    "City": "BEOGRAD",
    "Branch": "",
    "Postcode": "11000",
    "Country": "Serbia",
    "Connection": "Active"
  },
  {
    "countryCode": "SBPO",
    "bankCode": "RS",
    "branchCode": "100",
    "SWIFT Code": "SBPORSBG100",
    "Bank Name": "POSTAL SAVINGS BANK JSC",
    "Address": "MARTA 71 27",
    "City": "BEOGRAD",
    "Branch": "CORPORATE CUSTOMERS",
    "Postcode": "11000",
    "Country": "Serbia",
    "Connection": "Active"
  },
  {
    "countryCode": "PRCB",
    "bankCode": "RS",
    "branchCode": "SBG",
    "SWIFT Code": "PRCBRSBG",
    "Bank Name": "PROCREDIT BANK A.D. BELGRADE",
    "Address": "BULEVAR DESPOTA STEFANA 68C",
    "City": "BEOGRAD",
    "Branch": "",
    "Postcode": "11000",
    "Country": "Serbia",
    "Connection": "Active"
  },
  {
    "countryCode": "RZBS",
    "bankCode": "RS",
    "branchCode": "SBG",
    "SWIFT Code": "RZBSRSBG",
    "Bank Name": "RAIFFEISEN BANKA A.D.",
    "Address": "DJORDJA STANOJEVICA 16",
    "City": "BEOGRAD",
    "Branch": "",
    "Postcode": "11070",
    "Country": "Serbia",
    "Connection": "Active"
  },
  {
    "countryCode": "SRBN",
    "bankCode": "RS",
    "branchCode": "SBG",
    "SWIFT Code": "SRBNRSBG",
    "Bank Name": "SRPSKA BANKA A.D.",
    "Address": "SAVSKA 25",
    "City": "BEOGRAD",
    "Branch": "",
    "Postcode": "11000",
    "Country": "Serbia",
    "Connection": "Active"
  },
  {
    "countryCode": "BDDT",
    "bankCode": "RS",
    "branchCode": "S22",
    "SWIFT Code": "BDDTRS22",
    "Bank Name": "TESLA CAPITAL A.D. BELGRADE",
    "Address": "BULEVAR ZORANA DINDICA 121",
    "City": "NOVI BEOGRAD",
    "Branch": "",
    "Postcode": "",
    "Country": "Serbia",
    "Connection": "Active"
  },
  {
    "countryCode": "BACX",
    "bankCode": "RS",
    "branchCode": "SBG",
    "SWIFT Code": "BACXRSBG",
    "Bank Name": "UNICREDIT BANK SRBIJA A.D.",
    "Address": "RAJICEVA 27-29",
    "City": "BEOGRAD",
    "Branch": "",
    "Postcode": "11000",
    "Country": "Serbia",
    "Connection": "Active"
  }
]
module.exports = serbia
