const seychelles = [
  {
    "bankCode": "BARC",
    "countryCode": "SC",
    "branchCode": "CSC",
    "SWIFT Code": "BARCSCSC",
    "Bank Name": "ABSA BANK (SEYCHELLES) LIMITED",
    "Address": "INDEPENDANCE AVENUE",
    "City": "VICTORIA",
    "Branch": "",
    "Postcode": "",
    "Country": "Seychelles",
    "Connection": "Active"
  },
  {
    "bankCode": "BMUS",
    "countryCode": "SC",
    "branchCode": "CSC",
    "SWIFT Code": "BMUSSCSC",
    "Bank Name": "AL SALAM BANK SEYCHELLES LIMITED",
    "Address": "MAISON ESPLANADE, FRANCIS RACHEL",
    "City": "VICTORIA",
    "Branch": "",
    "Postcode": "",
    "Country": "Seychelles",
    "Connection": "Active"
  },
  {
    "bankCode": "BARB",
    "countryCode": "SC",
    "branchCode": "CSC",
    "SWIFT Code": "BARBSCSC",
    "Bank Name": "BANK OF BARODA",
    "Address": "TRINITY HOUSE, ALBERT STREET",
    "City": "VICTORIA",
    "Branch": "",
    "Postcode": "",
    "Country": "Seychelles",
    "Connection": "Active"
  },
  {
    "bankCode": "BCEY",
    "countryCode": "SC",
    "branchCode": "CSC",
    "SWIFT Code": "BCEYSCSC",
    "Bank Name": "BANK OF CEYLON, SEYCHELLES BRANCH",
    "Address": "OLIAJI BUILDING, FRANCIS RACHEL STREET",
    "City": "VICTORIA",
    "Branch": "",
    "Postcode": "",
    "Country": "Seychelles",
    "Connection": "Active"
  },
  {
    "bankCode": "SSCB",
    "countryCode": "SC",
    "branchCode": "CSC",
    "SWIFT Code": "SSCBSCSC",
    "Bank Name": "CENTRAL BANK OF SEYCHELLES",
    "Address": "CENTRAL BANK BUILDING, INDEPENDENCE AVENUE",
    "City": "VICTORIA",
    "Branch": "",
    "Postcode": "",
    "Country": "Seychelles",
    "Connection": "Active"
  },
  {
    "bankCode": "DIGL",
    "countryCode": "SC",
    "branchCode": "CSC",
    "SWIFT Code": "DIGLSCSC",
    "Bank Name": "DIGITAL BANK LIMITED",
    "Address": "FLOOR 2, OCEANIC MOTORS BUILDING, PROVIDENCE MAHE",
    "City": "VICTORIA",
    "Branch": "",
    "Postcode": "",
    "Country": "Seychelles",
    "Connection": "Active"
  },
  {
    "bankCode": "MCBL",
    "countryCode": "SC",
    "branchCode": "CSC",
    "SWIFT Code": "MCBLSCSC",
    "Bank Name": "MCB SEYCHELLES",
    "Address": "CARAVELLE HOUSE, MANGLIER STREET",
    "City": "VICTORIA",
    "Branch": "",
    "Postcode": "",
    "Country": "Seychelles",
    "Connection": "Active"
  },
  {
    "bankCode": "NOVH",
    "countryCode": "SC",
    "branchCode": "CSC",
    "SWIFT Code": "NOVHSCSC",
    "Bank Name": "NOUVOBANQ",
    "Address": "NOUVOBANQ HOUSE, RUE DE LA POSSESSION",
    "City": "VICTORIA",
    "Branch": "",
    "Postcode": "",
    "Country": "Seychelles",
    "Connection": "Active"
  },
  {
    "bankCode": "SEYS",
    "countryCode": "SC",
    "branchCode": "CSC",
    "SWIFT Code": "SEYSSCSC",
    "Bank Name": "SEYCHELLES COMMERCIAL BANK",
    "Address": "ORION MALL",
    "City": "VICTORIA",
    "Branch": "",
    "Postcode": "",
    "Country": "Seychelles",
    "Connection": "Active"
  }
]
module.exports = seychelles
