const slovenia = [
  {
    "countryCode": "HAAB",
    "bankCode": "SI",
    "branchCode": "I22",
    "SWIFT Code": "HAABSI22",
    "Bank Name": "ADDIKO BANK D.D.",
    "Address": "STEKLENI DVOR, DUNAJSKA 117",
    "City": "LJUBLJANA",
    "Branch": "",
    "Postcode": "1000",
    "Country": "Slovenia",
    "Connection": "Active"
  },
  {
    "countryCode": "BSLJ",
    "bankCode": "SI",
    "branchCode": "IND",
    "SWIFT Code": "BSLJSI2XIND",
    "Bank Name": "BANK OF SLOVENIA",
    "Address": "SLOVENSKA 35",
    "City": "LJUBLJANA",
    "Branch": "",
    "Postcode": "1505",
    "Country": "Slovenia",
    "Connection": "Active"
  },
  {
    "countryCode": "BSLJ",
    "bankCode": "SI",
    "branchCode": "I2X",
    "SWIFT Code": "BSLJSI2X",
    "Bank Name": "BANK OF SLOVENIA",
    "Address": "SLOVENSKA 35",
    "City": "LJUBLJANA",
    "Branch": "",
    "Postcode": "1505",
    "Country": "Slovenia",
    "Connection": "Active"
  },
  {
    "countryCode": "BSLJ",
    "bankCode": "SI",
    "branchCode": "ATM",
    "SWIFT Code": "BSLJSI2XATM",
    "Bank Name": "BANK OF SLOVENIA",
    "Address": "SLOVENSKA 35",
    "City": "LJUBLJANA",
    "Branch": "(PORAVNAVA BANKOMATOV)",
    "Postcode": "1505",
    "Country": "Slovenia",
    "Connection": "Active"
  },
  {},
  {
    "countryCode": "BSLJ",
    "bankCode": "SI",
    "branchCode": "IDD",
    "SWIFT Code": "BSLJSI2XIDD",
    "Bank Name": "BANK OF SLOVENIA",
    "Address": "SLOVENSKA 35",
    "City": "LJUBLJANA",
    "Branch": "(SIMP-PS - STORITEV IDD-CORE)",
    "Postcode": "1505",
    "Country": "Slovenia",
    "Connection": "Active"
  },
  {
    "countryCode": "BSLJ",
    "bankCode": "SI",
    "branchCode": "CCB",
    "SWIFT Code": "BSLJSI2XCCB",
    "Bank Name": "BANK OF SLOVENIA",
    "Address": "SLOVENSKA 35",
    "City": "LJUBLJANA",
    "Branch": "CCBM",
    "Postcode": "1505",
    "Country": "Slovenia",
    "Connection": "Active"
  },
  {
    "countryCode": "BSLJ",
    "bankCode": "SI",
    "branchCode": "ECM",
    "SWIFT Code": "BSLJSI2XECM",
    "Bank Name": "BANK OF SLOVENIA",
    "Address": "SLOVENSKA 35",
    "City": "LJUBLJANA",
    "Branch": "COLLATERAL MANAGEMENT",
    "Postcode": "1505",
    "Country": "Slovenia",
    "Connection": "Active"
  },
  {
    "countryCode": "BSLJ",
    "bankCode": "SI",
    "branchCode": "FNB",
    "SWIFT Code": "BSLJSI2XFNB",
    "Bank Name": "BANK OF SLOVENIA",
    "Address": "SLOVENSKA 35",
    "City": "LJUBLJANA",
    "Branch": "MONEY MARKET AND FOREIGN EXCHANGE ONLY",
    "Postcode": "1505",
    "Country": "Slovenia",
    "Connection": "Active"
  },
  {
    "countryCode": "BSLJ",
    "bankCode": "SI",
    "branchCode": "PAR",
    "SWIFT Code": "BSLJSI2XPAR",
    "Bank Name": "BANK OF SLOVENIA",
    "Address": "SLOVENSKA 35",
    "City": "LJUBLJANA",
    "Branch": "PARTY ID BANKA SLOVENIJE",
    "Postcode": "1505",
    "Country": "Slovenia",
    "Connection": "Active"
  },
  {
    "countryCode": "BSLJ",
    "bankCode": "SI",
    "branchCode": "PBO",
    "SWIFT Code": "BSLJSI2XPBO",
    "Bank Name": "BANK OF SLOVENIA",
    "Address": "SLOVENSKA 35",
    "City": "LJUBLJANA",
    "Branch": "PLACILNA BANKA BANKE SLOVENIJE",
    "Postcode": "1505",
    "Country": "Slovenia",
    "Connection": "Active"
  },
  {
    "countryCode": "BSLJ",
    "bankCode": "SI",
    "branchCode": "SCT",
    "SWIFT Code": "BSLJSI2XSCT",
    "Bank Name": "BANK OF SLOVENIA",
    "Address": "SLOVENSKA 35",
    "City": "LJUBLJANA",
    "Branch": "PORAVNAVA SEPA CT",
    "Postcode": "1505",
    "Country": "Slovenia",
    "Connection": "Active"
  },
  {
    "countryCode": "BSLJ",
    "bankCode": "SI",
    "branchCode": "B2B",
    "SWIFT Code": "BSLJSI2XB2B",
    "Bank Name": "BANK OF SLOVENIA",
    "Address": "SLOVENSKA 35",
    "City": "LJUBLJANA",
    "Branch": "PORAVNAVA STEP2 MPEDD - STORITEV B2B",
    "Postcode": "1505",
    "Country": "Slovenia",
    "Connection": "Active"
  },
  {
    "countryCode": "BSLJ",
    "bankCode": "SI",
    "branchCode": "COR",
    "SWIFT Code": "BSLJSI2XCOR",
    "Bank Name": "BANK OF SLOVENIA",
    "Address": "SLOVENSKA 35",
    "City": "LJUBLJANA",
    "Branch": "PORAVNAVA STEP2 MPEDD - STORITEV CORE",
    "Postcode": "1505",
    "Country": "Slovenia",
    "Connection": "Active"
  },
  {
    "countryCode": "BSLJ",
    "bankCode": "SI",
    "branchCode": "EUX",
    "SWIFT Code": "BSLJSI2XEUX",
    "Bank Name": "BANK OF SLOVENIA",
    "Address": "SLOVENSKA 35",
    "City": "LJUBLJANA",
    "Branch": "TARGET",
    "Postcode": "1505",
    "Country": "Slovenia",
    "Connection": "Active"
  },
  {
    "countryCode": "BAKO",
    "bankCode": "SI",
    "branchCode": "I2X",
    "SWIFT Code": "BAKOSI2X",
    "Bank Name": "BANKA INTESA SANPAOLO D.D.",
    "Address": "PRISTANISKA ULICA 14",
    "City": "KOPER",
    "Branch": "",
    "Postcode": "6502",
    "Country": "Slovenia",
    "Connection": "Active"
  },
  {
    "countryCode": "BAKO",
    "bankCode": "SI",
    "branchCode": "IBO",
    "SWIFT Code": "BAKOSI2XIBO",
    "Bank Name": "BANKA INTESA SANPAOLO D.D.",
    "Address": "PRISTANISKA ULICA 14",
    "City": "KOPER",
    "Branch": "IBOS CODE",
    "Postcode": "6502",
    "Country": "Slovenia",
    "Connection": "Active"
  },
  {
    "countryCode": "KSPK",
    "bankCode": "SI",
    "branchCode": "I22",
    "SWIFT Code": "KSPKSI22",
    "Bank Name": "BANKA SPARKASSE D.D.",
    "Address": "CESTA V KLECE 15",
    "City": "LJUBLJANA",
    "Branch": "",
    "Postcode": "1000",
    "Country": "Slovenia",
    "Connection": "Active"
  },
  {
    "countryCode": "BKDO",
    "bankCode": "SI",
    "branchCode": "ATR",
    "SWIFT Code": "BKDOSI22ATR",
    "Bank Name": "BANKART D.O.O.",
    "Address": "CELOVSKA 150",
    "City": "LJUBLJANA",
    "Branch": "",
    "Postcode": "1000",
    "Country": "Slovenia",
    "Connection": "Active"
  },
  {
    "countryCode": "BKDO",
    "bankCode": "SI",
    "branchCode": "IDR",
    "SWIFT Code": "BKDOSI22IDR",
    "Bank Name": "BANKART D.O.O.",
    "Address": "CELOVSKA 150",
    "City": "LJUBLJANA",
    "Branch": "",
    "Postcode": "1000",
    "Country": "Slovenia",
    "Connection": "Active"
  },
  {
    "countryCode": "BKDO",
    "bankCode": "SI",
    "branchCode": "POS",
    "SWIFT Code": "BKDOSI22POS",
    "Bank Name": "BANKART D.O.O.",
    "Address": "CELOVSKA 150",
    "City": "LJUBLJANA",
    "Branch": "",
    "Postcode": "1000",
    "Country": "Slovenia",
    "Connection": "Active"
  },
  {
    "countryCode": "BKDO",
    "bankCode": "SI",
    "branchCode": "PGF",
    "SWIFT Code": "BKDOSI22PGF",
    "Bank Name": "BANKART D.O.O.",
    "Address": "CELOVSKA 150",
    "City": "LJUBLJANA",
    "Branch": "",
    "Postcode": "1000",
    "Country": "Slovenia",
    "Connection": "Active"
  },
  {
    "countryCode": "BKDO",
    "bankCode": "SI",
    "branchCode": "IGF",
    "SWIFT Code": "BKDOSI22IGF",
    "Bank Name": "BANKART D.O.O.",
    "Address": "CELOVSKA 150",
    "City": "LJUBLJANA",
    "Branch": "",
    "Postcode": "1000",
    "Country": "Slovenia",
    "Connection": "Active"
  },
  {
    "countryCode": "BKDO",
    "bankCode": "SI",
    "branchCode": "IDD",
    "SWIFT Code": "BKDOSI22IDD",
    "Bank Name": "BANKART D.O.O.",
    "Address": "CELOVSKA 150",
    "City": "LJUBLJANA",
    "Branch": "",
    "Postcode": "1000",
    "Country": "Slovenia",
    "Connection": "Active"
  },
  {
    "countryCode": "BKDO",
    "bankCode": "SI",
    "branchCode": "ATM",
    "SWIFT Code": "BKDOSI22ATM",
    "Bank Name": "BANKART D.O.O.",
    "Address": "CELOVSKA 150",
    "City": "LJUBLJANA",
    "Branch": "",
    "Postcode": "1000",
    "Country": "Slovenia",
    "Connection": "Active"
  },
  {
    "countryCode": "BKDO",
    "bankCode": "SI",
    "branchCode": "AGF",
    "SWIFT Code": "BKDOSI22AGF",
    "Bank Name": "BANKART D.O.O.",
    "Address": "CELOVSKA 150",
    "City": "LJUBLJANA",
    "Branch": "",
    "Postcode": "1000",
    "Country": "Slovenia",
    "Connection": "Active"
  },
  {
    "countryCode": "BKDO",
    "bankCode": "SI",
    "branchCode": "POR",
    "SWIFT Code": "BKDOSI22POR",
    "Bank Name": "BANKART D.O.O.",
    "Address": "CELOVSKA 150",
    "City": "LJUBLJANA",
    "Branch": "",
    "Postcode": "1000",
    "Country": "Slovenia",
    "Connection": "Active"
  },
  {
    "countryCode": "BKDO",
    "bankCode": "SI",
    "branchCode": "I22",
    "SWIFT Code": "BKDOSI22",
    "Bank Name": "BANKART D.O.O.",
    "Address": "CELOVSKA 150",
    "City": "LJUBLJANA",
    "Branch": "",
    "Postcode": "1000",
    "Country": "Slovenia",
    "Connection": "Active"
  },
  {
    "countryCode": "BFKK",
    "bankCode": "SI",
    "branchCode": "I22",
    "SWIFT Code": "BFKKSI22",
    "Bank Name": "BKS BANK AG, BANCNA PODRUZNICA",
    "Address": "VEROVSKOVA ULICA 55A",
    "City": "LJUBLJANA",
    "Branch": "",
    "Postcode": "1000",
    "Country": "Slovenia",
    "Connection": "Active"
  },
  {
    "countryCode": "KDDS",
    "bankCode": "SI",
    "branchCode": "I22",
    "SWIFT Code": "KDDSSI22",
    "Bank Name": "CENTRAL SECURITIES CLEARING CORPORATION - KDD",
    "Address": "TIVOLSKA CESTA 48",
    "City": "LJUBLJANA",
    "Branch": "",
    "Postcode": "1000",
    "Country": "Slovenia",
    "Connection": "Active"
  },
  {
    "countryCode": "KDDS",
    "bankCode": "SI",
    "branchCode": "PB3",
    "SWIFT Code": "KDDSSI22PB3",
    "Bank Name": "CENTRAL SECURITIES CLEARING CORPORATION - KDD",
    "Address": "TIVOLSKA CESTA 48",
    "City": "LJUBLJANA",
    "Branch": "",
    "Postcode": "1000",
    "Country": "Slovenia",
    "Connection": "Active"
  },
  {
    "countryCode": "KDDS",
    "bankCode": "SI",
    "branchCode": "T2P",
    "SWIFT Code": "KDDSSI22T2P",
    "Bank Name": "CENTRAL SECURITIES CLEARING CORPORATION - KDD",
    "Address": "TIVOLSKA CESTA 48",
    "City": "LJUBLJANA",
    "Branch": "",
    "Postcode": "1000",
    "Country": "Slovenia",
    "Connection": "Active"
  },
  {
    "countryCode": "HDEL",
    "bankCode": "SI",
    "branchCode": "I22",
    "SWIFT Code": "HDELSI22",
    "Bank Name": "DELAVSKA HRANILNICA D.D. LJUBLJANA",
    "Address": "MIKLOSICEVA 5",
    "City": "LJUBLJANA",
    "Branch": "",
    "Postcode": "1000",
    "Country": "Slovenia",
    "Connection": "Active"
  },
  {
    "countryCode": "SZKB",
    "bankCode": "SI",
    "branchCode": "I2X",
    "SWIFT Code": "SZKBSI2X",
    "Bank Name": "DEZELNA BANKA SLOVENIJE D.D.",
    "Address": "KOLODVORSKA 9",
    "City": "LJUBLJANA",
    "Branch": "",
    "Postcode": "1000",
    "Country": "Slovenia",
    "Connection": "Active"
  },
  {
    "countryCode": "GEOL",
    "bankCode": "SI",
    "branchCode": "I22",
    "SWIFT Code": "GEOLSI22",
    "Bank Name": "GEOPLIN D.O.O. LJUBLJANA",
    "Address": "GEOPLIN, FLOOR 1, CESTA LJUBLJANSKE BRIGADE 11 11",
    "City": "LJUBLJANA",
    "Branch": "",
    "Postcode": "1000",
    "Country": "Slovenia",
    "Connection": "Active"
  },
  {
    "countryCode": "GORE",
    "bankCode": "SI",
    "branchCode": "I2X",
    "SWIFT Code": "GORESI2X",
    "Bank Name": "GORENJSKA BANKA D.D., KRANJ",
    "Address": "BLEIWEISOVA CESTA 1",
    "City": "KRANJ",
    "Branch": "",
    "Postcode": "4000",
    "Country": "Slovenia",
    "Connection": "Active"
  },
  {
    "countryCode": "HLON",
    "bankCode": "SI",
    "branchCode": "I22",
    "SWIFT Code": "HLONSI22",
    "Bank Name": "HRANILNICA LON D.D.",
    "Address": "ZANOVA ULICA 3",
    "City": "KRANJ",
    "Branch": "",
    "Postcode": "4000",
    "Country": "Slovenia",
    "Connection": "Active"
  },
  {
    "countryCode": "KBMA",
    "bankCode": "SI",
    "branchCode": "I2X",
    "SWIFT Code": "KBMASI2X",
    "Bank Name": "NOVA KREDITNA BANKA MARIBOR D.D.",
    "Address": "VITA KRAIGHERJA 4",
    "City": "MARIBOR",
    "Branch": "",
    "Postcode": "2505",
    "Country": "Slovenia",
    "Connection": "Active"
  },
  {
    "countryCode": "LJBA",
    "bankCode": "SI",
    "branchCode": "I2X",
    "SWIFT Code": "LJBASI2X",
    "Bank Name": "NOVA LJUBLJANSKA BANKA D.D.",
    "Address": "TRG REPUBLIKE 2",
    "City": "LJUBLJANA",
    "Branch": "",
    "Postcode": "1520",
    "Country": "Slovenia",
    "Connection": "Active"
  },
  {
    "countryCode": "PWSR",
    "bankCode": "SI",
    "branchCode": "I22",
    "SWIFT Code": "PWSRSI22",
    "Bank Name": "PAYWISER D.O.O.",
    "Address": "MODRA HISA, FLOOR 1, BRAVNICARJAVA ULICA 13",
    "City": "LJUBLJANA",
    "Branch": "",
    "Postcode": "1000",
    "Country": "Slovenia",
    "Connection": "Active"
  },
  {
    "countryCode": "HKVI",
    "bankCode": "SI",
    "branchCode": "I22",
    "SWIFT Code": "HKVISI22",
    "Bank Name": "PRIMORSKA HRANILNICA VIPAVA D.D.",
    "Address": "GLAVNI TRG 15",
    "City": "VIPAVA",
    "Branch": "",
    "Postcode": "5271",
    "Country": "Slovenia",
    "Connection": "Active"
  },
  {
    "countryCode": "SIDR",
    "bankCode": "SI",
    "branchCode": "I22",
    "SWIFT Code": "SIDRSI22",
    "Bank Name": "SID-SLOVENSKA IZVOZNA IN RAZVOJNA BANKA, D.D., LJUBLJANA",
    "Address": "JOSIPINE TURNOGRAJSKE 6",
    "City": "LJUBLJANA",
    "Branch": "",
    "Postcode": "1000",
    "Country": "Slovenia",
    "Connection": "Active"
  },
  {
    "countryCode": "SKBA",
    "bankCode": "SI",
    "branchCode": "I2X",
    "SWIFT Code": "SKBASI2X",
    "Bank Name": "SKB D.D",
    "Address": "",
    "City": "LJUBLJANA",
    "Branch": "",
    "Postcode": "1513",
    "Country": "Slovenia",
    "Connection": "Active"
  },
  {
    "countryCode": "BACX",
    "bankCode": "SI",
    "branchCode": "I22",
    "SWIFT Code": "BACXSI22",
    "Bank Name": "UNICREDIT BANKA SLOVENIJA D.D.",
    "Address": "SMARTINSKA 140",
    "City": "LJUBLJANA",
    "Branch": "",
    "Postcode": "1000",
    "Country": "Slovenia",
    "Connection": "Active"
  }
]
module.exports = slovenia
