const slovakia = [
  {
    "bankCode": "KOMA",
    "countryCode": "SK",
    "branchCode": "NIT",
    "SWIFT Code": "KOMASK2XNIT",
    "Bank Name": "PRIMA BANKA SLOVENSKO, A.S.",
    "Address": "FARSKA 7",
    "City": "NITRA",
    "Branch": "NITRA BRANCH",
    "Postcode": "949 01",
    "Country": "Slovakia",
    "Connection": "Active"
  },
  {
    "bankCode": "KOMA",
    "countryCode": "SK",
    "branchCode": "PBY",
    "SWIFT Code": "KOMASK2XPBY",
    "Bank Name": "PRIMA BANKA SLOVENSKO, A.S.",
    "Address": "24, M.R. STEFANIKA 171",
    "City": "POVAZSKA BYSTRICA",
    "Branch": "POVAZSKA BYSTRICA BRANCH",
    "Postcode": "017 01",
    "Country": "Slovakia",
    "Connection": "Active"
  },
  {
    "bankCode": "KOMA",
    "countryCode": "SK",
    "branchCode": "SNV",
    "SWIFT Code": "KOMASK2XSNV",
    "Bank Name": "PRIMA BANKA SLOVENSKO, A.S.",
    "Address": "STEFANIKOVO NAM. 10",
    "City": "SPISSKA NOVA VES",
    "Branch": "SPISSKA NOVA VES BRANCH",
    "Postcode": "052 80",
    "Country": "Slovakia",
    "Connection": "Active"
  },
  {
    "bankCode": "KOMA",
    "countryCode": "SK",
    "branchCode": "TRE",
    "SWIFT Code": "KOMASK2XTRE",
    "Bank Name": "PRIMA BANKA SLOVENSKO, A.S.",
    "Address": "PALACKEHO 35",
    "City": "TRENCIN",
    "Branch": "TRENCIN BRANCH",
    "Postcode": "911 00",
    "Country": "Slovakia",
    "Connection": "Active"
  },
  {
    "bankCode": "KOMA",
    "countryCode": "SK",
    "branchCode": "TNA",
    "SWIFT Code": "KOMASK2XTNA",
    "Bank Name": "PRIMA BANKA SLOVENSKO, A.S.",
    "Address": "HLAVNA 7",
    "City": "TRNAVA",
    "Branch": "TRNAVA BRANCH",
    "Postcode": "917 01",
    "Country": "Slovakia",
    "Connection": "Active"
  },
  {
    "bankCode": "LUBA",
    "countryCode": "SK",
    "branchCode": "KBX",
    "SWIFT Code": "LUBASKBX",
    "Bank Name": "PRIMA BANKA SLOVENSKO, A.S.",
    "Address": "HODZOVA 11",
    "City": "ZILINA",
    "Branch": "",
    "Postcode": "010 11",
    "Country": "Slovakia",
    "Connection": "Active"
  },
  {
    "bankCode": "KOMA",
    "countryCode": "SK",
    "branchCode": "K2X",
    "SWIFT Code": "KOMASK2X",
    "Bank Name": "PRIMA BANKA SLOVENSKO, A.S.",
    "Address": "HODZOVA 11",
    "City": "ZILINA",
    "Branch": "HEAD OFFICE",
    "Postcode": "010 01",
    "Country": "Slovakia",
    "Connection": "Active"
  },
  {
    "bankCode": "KOMA",
    "countryCode": "SK",
    "branchCode": "ZIL",
    "SWIFT Code": "KOMASK2XZIL",
    "Bank Name": "PRIMA BANKA SLOVENSKO, A.S.",
    "Address": "HODZOVA 9",
    "City": "ZILINA",
    "Branch": "ZILINA BRANCH",
    "Postcode": "010 11",
    "Country": "Slovakia",
    "Connection": "Active"
  },
  {
    "bankCode": "BSLO",
    "countryCode": "SK",
    "branchCode": "K22",
    "SWIFT Code": "BSLOSK22",
    "Bank Name": "PRIVATBANKA, A.S.",
    "Address": "EINSTEINOVA 25",
    "City": "BRATISLAVA",
    "Branch": "",
    "Postcode": "851 01",
    "Country": "Slovakia",
    "Connection": "Active"
  },
  {
    "bankCode": "PRVA",
    "countryCode": "SK",
    "branchCode": "KBA",
    "SWIFT Code": "PRVASKBA",
    "Bank Name": "PRVA STAVEBNA SPORITELNA, A.S.",
    "Address": "BAJKALSKA 30",
    "City": "BRATISLAVA",
    "Branch": "",
    "Postcode": "829 48",
    "Country": "Slovakia",
    "Connection": "Active"
  },
  {
    "bankCode": "FDXX",
    "countryCode": "SK",
    "branchCode": "KBA",
    "SWIFT Code": "FDXXSKBA",
    "Bank Name": "SIA CENTRAL EUROPE, A.S.",
    "Address": "DIGITAL PARK II, EINSTEINOVA 25",
    "City": "BRATISLAVA",
    "Branch": "",
    "Postcode": "851 01",
    "Country": "Slovakia",
    "Connection": "Active"
  },
  {
    "bankCode": "GIBA",
    "countryCode": "SK",
    "branchCode": "KBX",
    "SWIFT Code": "GIBASKBX",
    "Bank Name": "SLOVENSKA SPORITELNA, A.S.",
    "Address": "TOMASIKOVA 48",
    "City": "BRATISLAVA",
    "Branch": "",
    "Postcode": "832 37",
    "Country": "Slovakia",
    "Connection": "Active"
  },
  {
    "bankCode": "SLZB",
    "countryCode": "SK",
    "branchCode": "KBA",
    "SWIFT Code": "SLZBSKBA",
    "Bank Name": "SLOVENSKA ZARUCNA A ROZVOJOVA BANKA, A.S.",
    "Address": "STEFANIKOVA 27",
    "City": "BRATISLAVA",
    "Branch": "",
    "Postcode": "811 05",
    "Country": "Slovakia",
    "Connection": "Active"
  },
  {
    "bankCode": "SPSR",
    "countryCode": "SK",
    "branchCode": "KBA",
    "SWIFT Code": "SPSRSKBA",
    "Bank Name": "STATNA POKLADNICA",
    "Address": "RADLINSKEHO 32",
    "City": "BRATISLAVA",
    "Branch": "",
    "Postcode": "811 07",
    "Country": "Slovakia",
    "Connection": "Active"
  },
  {
    "bankCode": "SPSR",
    "countryCode": "SK",
    "branchCode": "ARD",
    "SWIFT Code": "SPSRSKBAARD",
    "Bank Name": "STATNA POKLADNICA",
    "Address": "RADLINSKEHO 32",
    "City": "BRATISLAVA",
    "Branch": "",
    "Postcode": "811 07",
    "Country": "Slovakia",
    "Connection": "Active"
  },
  {
    "bankCode": "TATR",
    "countryCode": "SK",
    "branchCode": "KBX",
    "SWIFT Code": "TATRSKBX",
    "Bank Name": "TATRA BANKA A.S.",
    "Address": "HODZOVO NAMESTIE 3",
    "City": "BRATISLAVA",
    "Branch": "",
    "Postcode": "811 06",
    "Country": "Slovakia",
    "Connection": "Active"
  },
  {
    "bankCode": "TPAY",
    "countryCode": "SK",
    "branchCode": "KBX",
    "SWIFT Code": "TPAYSKBX",
    "Bank Name": "TRUST PAY, A.S.",
    "Address": "ZA KASARNOU",
    "City": "BRATISLAVA",
    "Branch": "",
    "Postcode": "831 03",
    "Country": "Slovakia",
    "Connection": "Active"
  },
  {
    "bankCode": "SKSO",
    "countryCode": "SK",
    "branchCode": "K2X",
    "SWIFT Code": "SKSOSK2X",
    "Bank Name": "U. S. STEEL KOSICE, S.R.O.",
    "Address": "VSTUPNY AREAL U. S. STEEL",
    "City": "KOSICE",
    "Branch": "",
    "Postcode": "044 54",
    "Country": "Slovakia",
    "Connection": "Active"
  },
  {
    "bankCode": "UNCR",
    "countryCode": "SK",
    "branchCode": "KBX",
    "SWIFT Code": "UNCRSKBX",
    "Bank Name": "UNICREDIT BANK CZ AND SK, SK BRANCH",
    "Address": "A, SANCOVA 1",
    "City": "BRATISLAVA",
    "Branch": "",
    "Postcode": "813 33",
    "Country": "Slovakia",
    "Connection": "Active"
  },
  {
    "bankCode": "UNCR",
    "countryCode": "SK",
    "branchCode": "FAR",
    "SWIFT Code": "UNCRSKBXFAR",
    "Bank Name": "UNICREDIT BANK CZ AND SK, SK BRANCH",
    "Address": "",
    "City": "BRATISLAVA",
    "Branch": "INTERNAL FILE ACT ROUTING",
    "Postcode": "",
    "Country": "Slovakia",
    "Connection": "Active"
  },
  {
    "bankCode": "UNCR",
    "countryCode": "SK",
    "branchCode": "OWN",
    "SWIFT Code": "UNCRSKBXOWN",
    "Bank Name": "UNICREDIT BANK CZ AND SK, SK BRANCH",
    "Address": "A, SANCOVA 1",
    "City": "BRATISLAVA",
    "Branch": "SECURITIES SETTLEMENT",
    "Postcode": "813 33",
    "Country": "Slovakia",
    "Connection": "Active"
  },
  {
    "bankCode": "PANX",
    "countryCode": "SK",
    "branchCode": "K22",
    "SWIFT Code": "PANXSK22",
    "Bank Name": "UNIFIEDPOST PAYMENTS, ORGANIZACNA ZLOZKA",
    "Address": "NADRAZNA 1958",
    "City": "IVANKA PRI DUNAJI",
    "Branch": "",
    "Postcode": "900 28",
    "Country": "Slovakia",
    "Connection": "Active"
  },
  {
    "bankCode": "SUBA",
    "countryCode": "SK",
    "branchCode": "KBX",
    "SWIFT Code": "SUBASKBX",
    "Bank Name": "VSEOBECNA UVEROVA BANKA A.S.",
    "Address": "MLYNSKE NIVY 1",
    "City": "BRATISLAVA",
    "Branch": "",
    "Postcode": "829 90",
    "Country": "Slovakia",
    "Connection": "Active"
  },
  {
    "bankCode": "WUST",
    "countryCode": "SK",
    "branchCode": "KBA",
    "SWIFT Code": "WUSTSKBA",
    "Bank Name": "WUSTENROT STAVEBNA SPORITELNA, A.S.",
    "Address": "EINSTEINOVA 21, DIGITAL PARK I",
    "City": "BRATISLAVA",
    "Branch": "",
    "Postcode": "851 01",
    "Country": "Slovakia",
    "Connection": "Active"
  },
  {
    "bankCode": "POBN",
    "countryCode": "SK",
    "branchCode": "KBA",
    "SWIFT Code": "POBNSKBA",
    "Bank Name": "365.BANK, A. S.",
    "Address": "DVORAKOVO NABREZIE 4",
    "City": "BRATISLAVA",
    "Branch": "",
    "Postcode": "811 02",
    "Country": "Slovakia",
    "Connection": "Active"
  },
  {
    "bankCode": "BFKK",
    "countryCode": "SK",
    "branchCode": "KBB",
    "SWIFT Code": "BFKKSKBB",
    "Bank Name": "BKS BANK AG, POBOCKA ZAHRANICNEJ BANKY V SR",
    "Address": "EUROVEA CENTRAL 1, PRIBINOVA 4",
    "City": "BRATISLAVA",
    "Branch": "",
    "Postcode": "811 09",
    "Country": "Slovakia",
    "Connection": "Active"
  },
  {
    "bankCode": "CSDS",
    "countryCode": "SK",
    "branchCode": "KBA",
    "SWIFT Code": "CSDSSKBA",
    "Bank Name": "CENTRALNY DEPOZITAR CENNYCH PAPIEROV SR, A.S.",
    "Address": "A, UL.29.AUGUSTA 1",
    "City": "BRATISLAVA",
    "Branch": "",
    "Postcode": "814 80",
    "Country": "Slovakia",
    "Connection": "Active"
  },
  {
    "bankCode": "CSDS",
    "countryCode": "SK",
    "branchCode": "SYS",
    "SWIFT Code": "CSDSSKBASYS",
    "Bank Name": "CENTRALNY DEPOZITAR CENNYCH PAPIEROV SR, A.S.",
    "Address": "",
    "City": "BRATISLAVA",
    "Branch": "DEPOSITORY INFORMATION SYSTEM",
    "Postcode": "",
    "Country": "Slovakia",
    "Connection": "Active"
  },
  {
    "bankCode": "CSDS",
    "countryCode": "SK",
    "branchCode": "DTA",
    "SWIFT Code": "CSDSSKBADTA",
    "Bank Name": "CENTRALNY DEPOZITAR CENNYCH PAPIEROV SR, A.S.",
    "Address": "",
    "City": "BRATISLAVA",
    "Branch": "DEPOSITORY TECHNICAL ACCOUNT",
    "Postcode": "",
    "Country": "Slovakia",
    "Connection": "Active"
  },
  {
    "bankCode": "CEKO",
    "countryCode": "SK",
    "branchCode": "KBX",
    "SWIFT Code": "CEKOSKBX",
    "Bank Name": "CESKOSLOVENSKA OBCHODNA BANKA, A.S.",
    "Address": "ZIZKOVA 11",
    "City": "BRATISLAVA",
    "Branch": "SLOVAK REPUBLIC DIVISION",
    "Postcode": "811 02",
    "Country": "Slovakia",
    "Connection": "Active"
  },
  {
    "bankCode": "KBSP",
    "countryCode": "SK",
    "branchCode": "KBX",
    "SWIFT Code": "KBSPSKBX",
    "Bank Name": "CESKOSLOVENSKA OBCHODNA BANKA, A.S. (FORMERLY CSOB STAVEBNA SPORITELNA, A.S.)",
    "Address": "ZIZKOVA 11",
    "City": "BRATISLAVA",
    "Branch": "",
    "Postcode": "811 12",
    "Country": "Slovakia",
    "Connection": "Active"
  },
  {
    "bankCode": "CITI",
    "countryCode": "SK",
    "branchCode": "KBA",
    "SWIFT Code": "CITISKBA",
    "Bank Name": "CITIBANK EUROPE PLC, POBOCKA ZAHRANICNEJ BANKY",
    "Address": "DVORAKOVO NABREZIE 8",
    "City": "BRATISLAVA",
    "Branch": "",
    "Postcode": "811 02",
    "Country": "Slovakia",
    "Connection": "Active"
  },
  {
    "bankCode": "CITI",
    "countryCode": "SK",
    "branchCode": "SEC",
    "SWIFT Code": "CITISKBASEC",
    "Bank Name": "CITIBANK EUROPE PLC, POBOCKA ZAHRANICNEJ BANKY",
    "Address": "",
    "City": "BRATISLAVA",
    "Branch": "RESTRICTED USE CITIBANK BRATISLAVA TARGET 2",
    "Postcode": "",
    "Country": "Slovakia",
    "Connection": "Active"
  },
  {
    "bankCode": "EXSK",
    "countryCode": "SK",
    "branchCode": "KBX",
    "SWIFT Code": "EXSKSKBX",
    "Bank Name": "EXPORT-IMPORT BANK OF SLOVAK REPUBLIC",
    "Address": "GROSSLINGOVA 1",
    "City": "BRATISLAVA",
    "Branch": "",
    "Postcode": "813 50",
    "Country": "Slovakia",
    "Connection": "Active"
  },
  {
    "bankCode": "FIOZ",
    "countryCode": "SK",
    "branchCode": "KBA",
    "SWIFT Code": "FIOZSKBA",
    "Bank Name": "FIO BANKA, A.S., POBOCKA ZAHRANICNEJ BANKY",
    "Address": "DUNAJSKA 1",
    "City": "BRATISLAVA",
    "Branch": "",
    "Postcode": "811 08",
    "Country": "Slovakia",
    "Connection": "Active"
  },
  {
    "bankCode": "INGB",
    "countryCode": "SK",
    "branchCode": "KBX",
    "SWIFT Code": "INGBSKBX",
    "Bank Name": "ING BANK N.V., POBOCKA ZAHR, BANKY",
    "Address": "7C, PLYNARENSKA 5944",
    "City": "BRATISLAVA",
    "Branch": "",
    "Postcode": "821 09",
    "Country": "Slovakia",
    "Connection": "Active"
  },
  {
    "bankCode": "JTBP",
    "countryCode": "SK",
    "branchCode": "KBA",
    "SWIFT Code": "JTBPSKBA",
    "Bank Name": "J AND T BANKA, A.S.,POBOCKA ZAHRANICNEJ BANKY",
    "Address": "DVORAKOVO NABREZIE 8",
    "City": "BRATISLAVA",
    "Branch": "",
    "Postcode": "811 02",
    "Country": "Slovakia",
    "Connection": "Active"
  },
  {
    "bankCode": "KPAY",
    "countryCode": "SK",
    "branchCode": "K22",
    "SWIFT Code": "KPAYSK22",
    "Bank Name": "K-PAY A.S.",
    "Address": "KASTIEL 5",
    "City": "BERNOLAKOVO",
    "Branch": "",
    "Postcode": "900 27",
    "Country": "Slovakia",
    "Connection": "Active"
  },
  {
    "bankCode": "KODB",
    "countryCode": "SK",
    "branchCode": "KBX",
    "SWIFT Code": "KODBSKBX",
    "Bank Name": "KDB BANK EUROPE LTD SLOVAKIAN BRANCH OFFICE",
    "Address": "OBCHODNA 2",
    "City": "BRATISLAVA",
    "Branch": "",
    "Postcode": "811 06",
    "Country": "Slovakia",
    "Connection": "Active"
  },
  {
    "bankCode": "KOMB",
    "countryCode": "SK",
    "branchCode": "KBA",
    "SWIFT Code": "KOMBSKBA",
    "Bank Name": "KOMERCNI BANKA , A.S., POBOCKA ZAHRANICNEJ BANKY",
    "Address": "HODZOVO NAM. 1A",
    "City": "BRATISLAVA",
    "Branch": "",
    "Postcode": "811 06",
    "Country": "Slovakia",
    "Connection": "Active"
  },
  {
    "bankCode": "KOMB",
    "countryCode": "SK",
    "branchCode": "TGT",
    "SWIFT Code": "KOMBSKBATGT",
    "Bank Name": "KOMERCNI BANKA , A.S., POBOCKA ZAHRANICNEJ BANKY",
    "Address": "",
    "City": "BRATISLAVA",
    "Branch": "RESTRICTED TARGET USE",
    "Postcode": "",
    "Country": "Slovakia",
    "Connection": "Active"
  },
  {
    "bankCode": "BREX",
    "countryCode": "SK",
    "branchCode": "KBX",
    "SWIFT Code": "BREXSKBX",
    "Bank Name": "MBANK S.A., POBOCKA ZAHRANICNEJ BANKY",
    "Address": "PRIBINOVA 10",
    "City": "BRATISLAVA",
    "Branch": "",
    "Postcode": "811 09",
    "Country": "Slovakia",
    "Connection": "Active"
  },
  {
    "bankCode": "KRAF",
    "countryCode": "SK",
    "branchCode": "KBA",
    "SWIFT Code": "KRAFSKBA",
    "Bank Name": "MONDELEZ EUROPEAN BUSINESS SERVICES CENTRE, S.R.O.",
    "Address": "RACIANSKA 44",
    "City": "BRATISLAVA",
    "Branch": "",
    "Postcode": "814 99",
    "Country": "Slovakia",
    "Connection": "Active"
  },
  {
    "bankCode": "KRAF",
    "countryCode": "SK",
    "branchCode": "PYL",
    "SWIFT Code": "KRAFSKBAPYL",
    "Bank Name": "MONDELEZ EUROPEAN BUSINESS SERVICES CENTRE, S.R.O.",
    "Address": "",
    "City": "BRATISLAVA",
    "Branch": "CUSTOMER NAMING CONVENTION",
    "Postcode": "",
    "Country": "Slovakia",
    "Connection": "Active"
  },
  {
    "bankCode": "KRAF",
    "countryCode": "SK",
    "branchCode": "SSC",
    "SWIFT Code": "KRAFSKBASSC",
    "Bank Name": "MONDELEZ EUROPEAN BUSINESS SERVICES CENTRE, S.R.O.",
    "Address": "",
    "City": "BRATISLAVA",
    "Branch": "SHARED SERVICE CENTRE",
    "Postcode": "",
    "Country": "Slovakia",
    "Connection": "Active"
  },
  {
    "bankCode": "KRAF",
    "countryCode": "SK",
    "branchCode": "TSY",
    "SWIFT Code": "KRAFSKBATSY",
    "Bank Name": "MONDELEZ EUROPEAN BUSINESS SERVICES CENTRE, S.R.O.",
    "Address": "",
    "City": "BRATISLAVA",
    "Branch": "TREASURY",
    "Postcode": "",
    "Country": "Slovakia",
    "Connection": "Active"
  },
  {
    "bankCode": "NBSB",
    "countryCode": "SK",
    "branchCode": "KBX",
    "SWIFT Code": "NBSBSKBX",
    "Bank Name": "NARODNA BANKA SLOVENSKA (NATIONAL BANK OF SLOVAKIA)",
    "Address": "IMRICHA KARVASA 1",
    "City": "BRATISLAVA",
    "Branch": "",
    "Postcode": "813 25",
    "Country": "Slovakia",
    "Connection": "Active"
  },
  {
    "bankCode": "NBSB",
    "countryCode": "SK",
    "branchCode": "EBA",
    "SWIFT Code": "NBSBSKBXEBA",
    "Bank Name": "NARODNA BANKA SLOVENSKA (NATIONAL BANK OF SLOVAKIA)",
    "Address": "IMRICHA KARVASA 1",
    "City": "BRATISLAVA",
    "Branch": "ACCOUNT FOR EBA CLEARING SETTLEMENT",
    "Postcode": "813 25",
    "Country": "Slovakia",
    "Connection": "Active"
  },
  {
    "bankCode": "NBSB",
    "countryCode": "SK",
    "branchCode": "FE1",
    "SWIFT Code": "NBSBSKBXFE1",
    "Bank Name": "NARODNA BANKA SLOVENSKA (NATIONAL BANK OF SLOVAKIA)",
    "Address": "IMRICHA KARVASA 1",
    "City": "BRATISLAVA",
    "Branch": "ACCOUNT FOR FEES",
    "Postcode": "813 25",
    "Country": "Slovakia",
    "Connection": "Active"
  },
  {
    "bankCode": "NBSB",
    "countryCode": "SK",
    "branchCode": "IN1",
    "SWIFT Code": "NBSBSKBXIN1",
    "Bank Name": "NARODNA BANKA SLOVENSKA (NATIONAL BANK OF SLOVAKIA)",
    "Address": "IMRICHA KARVASA 1",
    "City": "BRATISLAVA",
    "Branch": "ACCOUNT FOR INTERESTS",
    "Postcode": "813 25",
    "Country": "Slovakia",
    "Connection": "Active"
  },
  {
    "bankCode": "NBSB",
    "countryCode": "SK",
    "branchCode": "SIP",
    "SWIFT Code": "NBSBSKBXSIP",
    "Bank Name": "NARODNA BANKA SLOVENSKA (NATIONAL BANK OF SLOVAKIA)",
    "Address": "IMRICHA KARVASA 1",
    "City": "BRATISLAVA",
    "Branch": "AS",
    "Postcode": "813 25",
    "Country": "Slovakia",
    "Connection": "Active"
  },
  {
    "bankCode": "NBSB",
    "countryCode": "SK",
    "branchCode": "BIL",
    "SWIFT Code": "NBSBSKBXBIL",
    "Bank Name": "NARODNA BANKA SLOVENSKA (NATIONAL BANK OF SLOVAKIA)",
    "Address": "IMRICHA KARVASA 1",
    "City": "BRATISLAVA",
    "Branch": "AS - BILATERAL SETTLEMENT",
    "Postcode": "813 25",
    "Country": "Slovakia",
    "Connection": "Active"
  },
  {
    "bankCode": "NBSB",
    "countryCode": "SK",
    "branchCode": "CCB",
    "SWIFT Code": "NBSBSKBXCCB",
    "Bank Name": "NARODNA BANKA SLOVENSKA (NATIONAL BANK OF SLOVAKIA)",
    "Address": "IMRICHA KARVASA 1",
    "City": "BRATISLAVA",
    "Branch": "CCB ACCOUNT",
    "Postcode": "813 25",
    "Country": "Slovakia",
    "Connection": "Active"
  },
  {
    "bankCode": "NBSB",
    "countryCode": "SK",
    "branchCode": "EUX",
    "SWIFT Code": "NBSBSKBXEUX",
    "Bank Name": "NARODNA BANKA SLOVENSKA (NATIONAL BANK OF SLOVAKIA)",
    "Address": "IMRICHA KARVASA 1",
    "City": "BRATISLAVA",
    "Branch": "ECB ACCOUNT",
    "Postcode": "813 25",
    "Country": "Slovakia",
    "Connection": "Active"
  },
  {
    "bankCode": "NBSB",
    "countryCode": "SK",
    "branchCode": "TGT",
    "SWIFT Code": "NBSBSKBXTGT",
    "Bank Name": "NARODNA BANKA SLOVENSKA (NATIONAL BANK OF SLOVAKIA)",
    "Address": "IMRICHA KARVASA 1",
    "City": "BRATISLAVA",
    "Branch": "TARGET2 CUSTOMER PAYMENTS",
    "Postcode": "813 25",
    "Country": "Slovakia",
    "Connection": "Active"
  },
  {
    "bankCode": "NBSB",
    "countryCode": "SK",
    "branchCode": "ECM",
    "SWIFT Code": "NBSBSKBXECM",
    "Bank Name": "NARODNA BANKA SLOVENSKA (NATIONAL BANK OF SLOVAKIA)",
    "Address": "IMRICHA KARVASA 1",
    "City": "BRATISLAVA",
    "Branch": "TECHNICAL USER - ECMS",
    "Postcode": "813 25",
    "Country": "Slovakia",
    "Connection": "Active"
  },
  {
    "bankCode": "NBSB",
    "countryCode": "SK",
    "branchCode": "200",
    "SWIFT Code": "NBSBSKBX200",
    "Bank Name": "NARODNA BANKA SLOVENSKA (NATIONAL BANK OF SLOVAKIA)",
    "Address": "IMRICHA KARVASA 1",
    "City": "BRATISLAVA",
    "Branch": "TEST ACCOUNT",
    "Postcode": "813 25",
    "Country": "Slovakia",
    "Connection": "Active"
  },
  {
    "bankCode": "NBSB",
    "countryCode": "SK",
    "branchCode": "100",
    "SWIFT Code": "NBSBSKBX100",
    "Bank Name": "NARODNA BANKA SLOVENSKA (NATIONAL BANK OF SLOVAKIA)",
    "Address": "IMRICHA KARVASA 1",
    "City": "BRATISLAVA",
    "Branch": "TEST ACCOUNT",
    "Postcode": "813 25",
    "Country": "Slovakia",
    "Connection": "Active"
  },
  {
    "bankCode": "DSSO",
    "countryCode": "SK",
    "branchCode": "KBB",
    "SWIFT Code": "DSSOSKBB",
    "Bank Name": "NN DOCHODKOVA SPRAVCOVSKA SPOLOCNOST, A.S.",
    "Address": "C, JESENSKEHO 4",
    "City": "BRATISLAVA",
    "Branch": "",
    "Postcode": "811 02",
    "Country": "Slovakia",
    "Connection": "Active"
  },
  {
    "bankCode": "NNTS",
    "countryCode": "SK",
    "branchCode": "KB2",
    "SWIFT Code": "NNTSSKB2",
    "Bank Name": "NN TATRY - SYMPATIA, D.D.S., A.S.",
    "Address": "C, JESENSKEHO 4",
    "City": "BRATISLAVA",
    "Branch": "",
    "Postcode": "811 02",
    "Country": "Slovakia",
    "Connection": "Active"
  },
  {
    "bankCode": "OBKL",
    "countryCode": "SK",
    "branchCode": "KBA",
    "SWIFT Code": "OBKLSKBA",
    "Bank Name": "OBERBANK AG",
    "Address": "A, PRIEVOZSKA 4",
    "City": "BRATISLAVA",
    "Branch": "",
    "Postcode": "821 09",
    "Country": "Slovakia",
    "Connection": "Active"
  },
  {
    "bankCode": "PAMV",
    "countryCode": "SK",
    "branchCode": "KB2",
    "SWIFT Code": "PAMVSKB2",
    "Bank Name": "PARTNERS ASSET MANAGEMENT, SPRAV. SPOL., A.S.",
    "Address": "SLAVICIE UDOLIE 106",
    "City": "BRATISLAVA",
    "Branch": "",
    "Postcode": "811 02",
    "Country": "Slovakia",
    "Connection": "Active"
  },
  {
    "bankCode": "PAVO",
    "countryCode": "SK",
    "branchCode": "KB2",
    "SWIFT Code": "PAVOSKB2",
    "Bank Name": "PARTNERS INVESTMENTS, O.C.P, A.S.",
    "Address": "SLAVICIE UDOLIE 106",
    "City": "BRATISLAVA",
    "Branch": "",
    "Postcode": "811 02",
    "Country": "Slovakia",
    "Connection": "Active"
  },
  {
    "bankCode": "BPKO",
    "countryCode": "SK",
    "branchCode": "KBB",
    "SWIFT Code": "BPKOSKBB",
    "Bank Name": "PKO BP S.A., POBOCKA ZAHRANICNEJ BANKY",
    "Address": "PRIBINOVA 10",
    "City": "BRATISLAVA",
    "Branch": "",
    "Postcode": "811 09",
    "Country": "Slovakia",
    "Connection": "Active"
  },
  {
    "bankCode": "BPKO",
    "countryCode": "SK",
    "branchCode": "KB2",
    "SWIFT Code": "BPKOSKB2",
    "Bank Name": "PKO BP S.A., POBOCKA ZAHRANICNEJ BANKY",
    "Address": "PRIBINOVA 10",
    "City": "BRATISLAVA",
    "Branch": "",
    "Postcode": "811 09",
    "Country": "Slovakia",
    "Connection": "Active"
  },
  {
    "bankCode": "KOMA",
    "countryCode": "SK",
    "branchCode": "BBY",
    "SWIFT Code": "KOMASK2XBBY",
    "Bank Name": "PRIMA BANKA SLOVENSKO, A.S.",
    "Address": "BAKOSSOVA 6",
    "City": "BANSKA BYSTRICA",
    "Branch": "BANSKA BYSTRICA BRANCH",
    "Postcode": "974 00",
    "Country": "Slovakia",
    "Connection": "Active"
  },
  {
    "bankCode": "KOMA",
    "countryCode": "SK",
    "branchCode": "BST",
    "SWIFT Code": "KOMASK2XBST",
    "Bank Name": "PRIMA BANKA SLOVENSKO, A.S.",
    "Address": "KAMMERHOFSKA 8",
    "City": "BANSKA STIAVNICA",
    "Branch": "BANSKA STIAVNICA BRANCH",
    "Postcode": "969 00",
    "Country": "Slovakia",
    "Connection": "Active"
  },
  {
    "bankCode": "KOMA",
    "countryCode": "SK",
    "branchCode": "BRA",
    "SWIFT Code": "KOMASK2XBRA",
    "Bank Name": "PRIMA BANKA SLOVENSKO, A.S.",
    "Address": "SAFARIKOVO NAMESTIE 3",
    "City": "BRATISLAVA",
    "Branch": "BRATISLAVA BRANCH",
    "Postcode": "811 02",
    "Country": "Slovakia",
    "Connection": "Active"
  },
  {
    "bankCode": "KOMA",
    "countryCode": "SK",
    "branchCode": "BRE",
    "SWIFT Code": "KOMASK2XBRE",
    "Bank Name": "PRIMA BANKA SLOVENSKO, A.S.",
    "Address": "B. NEMCOVEJ 15",
    "City": "BREZNO",
    "Branch": "BREZNO BRANCH",
    "Postcode": "977 01",
    "Country": "Slovakia",
    "Connection": "Active"
  },
  {
    "bankCode": "KOMA",
    "countryCode": "SK",
    "branchCode": "KOS",
    "SWIFT Code": "KOMASK2XKOS",
    "Bank Name": "PRIMA BANKA SLOVENSKO, A.S.",
    "Address": "NERUDOVA 14",
    "City": "KOSICE",
    "Branch": "KOSICE BRANCH",
    "Postcode": "040 11",
    "Country": "Slovakia",
    "Connection": "Active"
  },
  {
    "bankCode": "KOMA",
    "countryCode": "SK",
    "branchCode": "LHR",
    "SWIFT Code": "KOMASK2XLHR",
    "Bank Name": "PRIMA BANKA SLOVENSKO, A.S.",
    "Address": "UL. SNP 137",
    "City": "LIPTOVSKY HRADOK",
    "Branch": "LIPTOVSKY HRADOK BRANCH",
    "Postcode": "033 01",
    "Country": "Slovakia",
    "Connection": "Active"
  },
  {
    "bankCode": "KOMA",
    "countryCode": "SK",
    "branchCode": "LCN",
    "SWIFT Code": "KOMASK2XLCN",
    "Bank Name": "PRIMA BANKA SLOVENSKO, A.S.",
    "Address": "MASARYKOVA 7",
    "City": "LUCENEC",
    "Branch": "LUCENEC BRANCH",
    "Postcode": "984 01",
    "Country": "Slovakia",
    "Connection": "Active"
  },
  {
    "bankCode": "KOMA",
    "countryCode": "SK",
    "branchCode": "MAL",
    "SWIFT Code": "KOMASK2XMAL",
    "Bank Name": "PRIMA BANKA SLOVENSKO, A.S.",
    "Address": "RADLINSKEHO 2751",
    "City": "MALACKY",
    "Branch": "MALACKY BRANCH",
    "Postcode": "901 01",
    "Country": "Slovakia",
    "Connection": "Active"
  },
  {
    "bankCode": "KOMA",
    "countryCode": "SK",
    "branchCode": "MCH",
    "SWIFT Code": "KOMASK2XMCH",
    "Bank Name": "PRIMA BANKA SLOVENSKO, A.S.",
    "Address": "62, NAM. OSLOBOD. 1031",
    "City": "MICHALOVCE",
    "Branch": "MICHALOVCE BRANCH",
    "Postcode": "871 01",
    "Country": "Slovakia",
    "Connection": "Active"
  }
]
module.exports = slovakia
