const sriLanka = [
  {
    "countryCode": "SBIN",
    "bankCode": "LK",
    "branchCode": "FCB",
    "SWIFT Code": "SBINLKLXFCB",
    "Bank Name": "STATE BANK OF INDIA",
    "Address": "16 SIR BARON JAYATILAKA MAWATHA",
    "City": "COLOMBO",
    "Branch": "FOREIGN CURRENCY BANKING UNIT",
    "Postcode": "01000",
    "Country": "Sri Lanka",
    "Connection": "Active"
  },
  {
    "countryCode": "SBIN",
    "bankCode": "LK",
    "branchCode": "KDY",
    "SWIFT Code": "SBINLKLXKDY",
    "Bank Name": "STATE BANK OF INDIA",
    "Address": "111 1/1 KOTUGODELLA VEEDIYA",
    "City": "KANDY",
    "Branch": "KANDY BRANCH",
    "Postcode": "20000",
    "Country": "Sri Lanka",
    "Connection": "Active"
  },
  {
    "countryCode": "SBIN",
    "bankCode": "LK",
    "branchCode": "TRI",
    "SWIFT Code": "SBINLKLXTRI",
    "Bank Name": "STATE BANK OF INDIA",
    "Address": "NO.178 MAIN STREET, TRINCOMALEE",
    "City": "TRINCOMALEE",
    "Branch": "TRINCOMALEE BRANCH",
    "Postcode": "",
    "Country": "Sri Lanka",
    "Connection": "Active"
  },
  {
    "countryCode": "UBCL",
    "bankCode": "LK",
    "branchCode": "KLC",
    "SWIFT Code": "UBCLLKLC",
    "Bank Name": "UNION BANK OF COLOMBO PLC",
    "Address": "64 GALLE ROAD, 03 COLOMBO",
    "City": "COLOMBO",
    "Branch": "",
    "Postcode": "01000",
    "Country": "Sri Lanka",
    "Connection": "Active"
  },
  {
    "countryCode": "WTEY",
    "bankCode": "LK",
    "branchCode": "KLX",
    "SWIFT Code": "WTEYLKLX",
    "Bank Name": "WEALTHTRUST SECURITIES LTD",
    "Address": "102/1 DR. N.M. PERERA MAWATHA",
    "City": "COLOMBO",
    "Branch": "",
    "Postcode": "01000",
    "Country": "Sri Lanka",
    "Connection": "Active"
  },
  {
    "countryCode": "HNBS",
    "bankCode": "LK",
    "branchCode": "KLX",
    "SWIFT Code": "HNBSLKLX",
    "Bank Name": "ACUITY SECURITIES LIMITED",
    "Address": "DHARMAPALA MAWATHA, COLOMBO 3",
    "City": "COLOMBO",
    "Branch": "",
    "Postcode": "01000",
    "Country": "Sri Lanka",
    "Connection": "Active"
  },
  {
    "countryCode": "AMNA",
    "bankCode": "LK",
    "branchCode": "KLX",
    "SWIFT Code": "AMNALKLX",
    "Bank Name": "AMANA BANK PLC",
    "Address": "486 GALLE ROAD, COLOMBO 3",
    "City": "COLOMBO",
    "Branch": "",
    "Postcode": "00100",
    "Country": "Sri Lanka",
    "Connection": "Active"
  },
  {
    "countryCode": "BCEY",
    "bankCode": "LK",
    "branchCode": "KLX",
    "SWIFT Code": "BCEYLKLX",
    "Bank Name": "BANK OF CEYLON",
    "Address": "FLOOR 8, HEAD OFFICE BUILDING, 1 BANK OF CEYLON MAWATHA, 1 COLOMBO",
    "City": "COLOMBO",
    "Branch": "",
    "Postcode": "01000",
    "Country": "Sri Lanka",
    "Connection": "Active"
  },
  {
    "countryCode": "BCEY",
    "bankCode": "LK",
    "branchCode": "004",
    "SWIFT Code": "BCEYLKLX004",
    "Bank Name": "BANK OF CEYLON",
    "Address": "212/63 GASWORK, PETTAH",
    "City": "COLOMBO",
    "Branch": "BANK OF CEYLON PETTAH BRANCH",
    "Postcode": "01100",
    "Country": "Sri Lanka",
    "Connection": "Active"
  },
  {
    "countryCode": "BCEY",
    "bankCode": "LK",
    "branchCode": "573",
    "SWIFT Code": "BCEYLKLX573",
    "Bank Name": "BANK OF CEYLON",
    "Address": "FLOOR 2, 16, 2/3 CENTRAL BUS STAND, PETTAH, 11 COLOMBO",
    "City": "COLOMBO",
    "Branch": "CENTRAL BUS STAND BRANCH",
    "Postcode": "01000",
    "Country": "Sri Lanka",
    "Connection": "Active"
  },
  {
    "countryCode": "BCEY",
    "bankCode": "LK",
    "branchCode": "131",
    "SWIFT Code": "BCEYLKLX131",
    "Bank Name": "BANK OF CEYLON",
    "Address": "FLOOR 7, N.H.O.B, 4 MAWATA",
    "City": "COLOMBO",
    "Branch": "FOREIGN CURRENCY BANKING UNIT",
    "Postcode": "01000",
    "Country": "Sri Lanka",
    "Connection": "Active"
  },
  {
    "countryCode": "BCEY",
    "bankCode": "LK",
    "branchCode": "618",
    "SWIFT Code": "BCEYLKLX618",
    "Bank Name": "BANK OF CEYLON",
    "Address": "61 HOSPITAL LANE, 1 COLOMBO",
    "City": "COLOMBO",
    "Branch": "METROPOLITAN BRANCH",
    "Postcode": "01000",
    "Country": "Sri Lanka",
    "Connection": "Active"
  },
  {
    "countryCode": "BCEY",
    "bankCode": "LK",
    "branchCode": "125",
    "SWIFT Code": "BCEYLKLX125",
    "Bank Name": "BANK OF CEYLON",
    "Address": "61 HOSPITAL LANE",
    "City": "COLOMBO",
    "Branch": "NON RESIDENT FOREIGN CURRENCY UNIT",
    "Postcode": "01000",
    "Country": "Sri Lanka",
    "Connection": "Active"
  },
  {
    "countryCode": "BCEY",
    "bankCode": "LK",
    "branchCode": "PRI",
    "SWIFT Code": "BCEYLKLXPRI",
    "Bank Name": "BANK OF CEYLON",
    "Address": "FLOOR 8, MAWATHA",
    "City": "COLOMBO",
    "Branch": "PRIMARY DEALER UNIT BACK OFFICE",
    "Postcode": "01000",
    "Country": "Sri Lanka",
    "Connection": "Active"
  },
  {
    "countryCode": "BCEY",
    "bankCode": "LK",
    "branchCode": "002",
    "SWIFT Code": "BCEYLKLX002",
    "Bank Name": "BANK OF CEYLON",
    "Address": "CEYBANK HOUSE, 88 DALADA VIDIYA",
    "City": "KANDY",
    "Branch": "SUPER GRADE BRANCH",
    "Postcode": "20000",
    "Country": "Sri Lanka",
    "Connection": "Active"
  },
  {
    "countryCode": "BKCH",
    "bankCode": "LK",
    "branchCode": "KLX",
    "SWIFT Code": "BKCHLKLX",
    "Bank Name": "BANK OF CHINA LIMITED COLOMBO BRANCH",
    "Address": "FLOOR 2, CARGILLS BUILDING, 40 YORK STREET, 01 COLOMBO",
    "City": "COLOMBO",
    "Branch": "",
    "Postcode": "01000",
    "Country": "Sri Lanka",
    "Connection": "Active"
  },
  {
    "countryCode": "CALD",
    "bankCode": "LK",
    "branchCode": "KLX",
    "SWIFT Code": "CALDLKLX",
    "Bank Name": "CAPITAL ALLIANCE PLC",
    "Address": "FLOOR 5, NORTH WING, 46/58 NAWAM MAWATHA, 2 COLOMBO",
    "City": "COLOMBO",
    "Branch": "",
    "Postcode": "01000",
    "Country": "Sri Lanka",
    "Connection": "Active"
  },
  {
    "countryCode": "CGRB",
    "bankCode": "LK",
    "branchCode": "KLX",
    "SWIFT Code": "CGRBLKLX",
    "Bank Name": "CARGILLS BANK LIMITED",
    "Address": "FLOOR 2, 696 GALLE ROAD",
    "City": "COLOMBO",
    "Branch": "",
    "Postcode": "00300",
    "Country": "Sri Lanka",
    "Connection": "Active"
  },
  {
    "countryCode": "CBCE",
    "bankCode": "LK",
    "branchCode": "KLX",
    "SWIFT Code": "CBCELKLX",
    "Bank Name": "CENTRAL BANK OF SRI LANKA",
    "Address": "30 JANADHIPATHI MAWATHA",
    "City": "COLOMBO",
    "Branch": "",
    "Postcode": "00100",
    "Country": "Sri Lanka",
    "Connection": "Active"
  },
  {
    "countryCode": "CBCE",
    "bankCode": "LK",
    "branchCode": "KLS",
    "SWIFT Code": "CBCELKLS",
    "Bank Name": "CENTRAL BANK OF SRI LANKA",
    "Address": "30 JANADHIPATHI MAWATHA",
    "City": "COLOMBO",
    "Branch": "",
    "Postcode": "00100",
    "Country": "Sri Lanka",
    "Connection": "Active"
  },
  {
    "countryCode": "CBCE",
    "bankCode": "LK",
    "branchCode": "EPF",
    "SWIFT Code": "CBCELKLXEPF",
    "Bank Name": "CENTRAL BANK OF SRI LANKA",
    "Address": "34-36 JANADHIPATHI MAWETHA, 01 COLOMBO",
    "City": "COLOMBO",
    "Branch": "EMPLOYEES' PROVIDENT FUND - CBSL",
    "Postcode": "01000",
    "Country": "Sri Lanka",
    "Connection": "Active"
  },
  {
    "countryCode": "CDSP",
    "bankCode": "LK",
    "branchCode": "KLC",
    "SWIFT Code": "CDSPLKLC",
    "Bank Name": "CENTRAL DEPOSITORY SYSTEMS (PVT) LTD",
    "Address": "WORLD TRADE CENTER, WEST BLOCK, 04-01 ECHELON SQUARE, 1 COLOMBO",
    "City": "COLOMBO",
    "Branch": "",
    "Postcode": "01000",
    "Country": "Sri Lanka",
    "Connection": "Active"
  },
  {
    "countryCode": "CITI",
    "bankCode": "LK",
    "branchCode": "KLX",
    "SWIFT Code": "CITILKLX",
    "Bank Name": "CITIBANK N.A. SRI LANKA",
    "Address": "67 DHARMAPALA MWATHA, 7 COLOMBO",
    "City": "COLOMBO",
    "Branch": "",
    "Postcode": "01000",
    "Country": "Sri Lanka",
    "Connection": "Active"
  },
  {
    "countryCode": "CCEY",
    "bankCode": "LK",
    "branchCode": "KLX",
    "SWIFT Code": "CCEYLKLX",
    "Bank Name": "COMMERCIAL BANK OF CEYLON PLC",
    "Address": "COMMERCIAL HOUSE, 21 SIR RAZIK FAREED MAWATHA, COLOMBO 1",
    "City": "COLOMBO",
    "Branch": "",
    "Postcode": "01000",
    "Country": "Sri Lanka",
    "Connection": "Active"
  },
  {
    "countryCode": "DEUT",
    "bankCode": "LK",
    "branchCode": "KLX",
    "SWIFT Code": "DEUTLKLX",
    "Bank Name": "DEUTSCHE BANK AG, COLOMBO BRANCH",
    "Address": "FLOOR 21, ONE GALLE FACE TOWER, 1A CENTRE ROAD, 3 COLOMBO",
    "City": "COLOMBO",
    "Branch": "",
    "Postcode": "01000",
    "Country": "Sri Lanka",
    "Connection": "Active"
  },
  {
    "countryCode": "DEUT",
    "bankCode": "LK",
    "branchCode": "GMO",
    "SWIFT Code": "DEUTLKLXGMO",
    "Bank Name": "DEUTSCHE BANK AG, COLOMBO BRANCH",
    "Address": "SIFANI BUILDING, 86 GALLE ROAD, 03 COLOMBO",
    "City": "COLOMBO",
    "Branch": "",
    "Postcode": "01000",
    "Country": "Sri Lanka",
    "Connection": "Active"
  },
  {
    "countryCode": "DEUT",
    "bankCode": "LK",
    "branchCode": "001",
    "SWIFT Code": "DEUTLKLX001",
    "Bank Name": "DEUTSCHE BANK AG, COLOMBO BRANCH",
    "Address": "86 GALLE ROAD",
    "City": "COLOMBO",
    "Branch": "COLOMBO BRANCH",
    "Postcode": "01000",
    "Country": "Sri Lanka",
    "Connection": "Active"
  },
  {
    "countryCode": "DFCC",
    "bankCode": "LK",
    "branchCode": "KLX",
    "SWIFT Code": "DFCCLKLX",
    "Bank Name": "DFCC BANK PLC",
    "Address": "73/5 GALLE ROAD, COLOMBO 3",
    "City": "COLOMBO",
    "Branch": "",
    "Postcode": "01000",
    "Country": "Sri Lanka",
    "Connection": "Active"
  },
  {
    "countryCode": "CSSL",
    "bankCode": "LK",
    "branchCode": "KLX",
    "SWIFT Code": "CSSLLKLX",
    "Bank Name": "ENTRUST SECURITIES PLC",
    "Address": "FLOOR 16, WORLD TRADE CENTER, WEST, BLOCK ECHELON SQUARE",
    "City": "COLOMBO",
    "Branch": "",
    "Postcode": "00300",
    "Country": "Sri Lanka",
    "Connection": "Active"
  },
  {
    "countryCode": "FCTL",
    "bankCode": "LK",
    "branchCode": "KLX",
    "SWIFT Code": "FCTLLKLX",
    "Bank Name": "FIRST CAPITAL TREASURIES PLC",
    "Address": "34 SIR MOHAMED MACAN MARKER MAWATHA",
    "City": "COLOMBO",
    "Branch": "",
    "Postcode": "00300",
    "Country": "Sri Lanka",
    "Connection": "Active"
  },
  {
    "countryCode": "HABB",
    "bankCode": "LK",
    "branchCode": "KLC",
    "SWIFT Code": "HABBLKLC",
    "Bank Name": "HABIB BANK LTD.",
    "Address": "140-142 2ND CROSS STREET, 11 COLOMBO",
    "City": "COLOMBO",
    "Branch": "",
    "Postcode": "01000",
    "Country": "Sri Lanka",
    "Connection": "Active"
  },
  {
    "countryCode": "HBLI",
    "bankCode": "LK",
    "branchCode": "KLX",
    "SWIFT Code": "HBLILKLX",
    "Bank Name": "HATTON NATIONAL BANK PLC",
    "Address": "FLOOR 11, HNB TOWERS, 479 T B JAYAH MAWATHA",
    "City": "COLOMBO",
    "Branch": "",
    "Postcode": "01000",
    "Country": "Sri Lanka",
    "Connection": "Active"
  },
  {
    "countryCode": "HBLI",
    "bankCode": "LK",
    "branchCode": "001",
    "SWIFT Code": "HBLILKLX001",
    "Bank Name": "HATTON NATIONAL BANK PLC",
    "Address": "16 JANADHIPATHI MAWATHA, 1 COLOMBO",
    "City": "COLOMBO",
    "Branch": "FOREIGN CURRENCY BANKING UNIT",
    "Postcode": "01000",
    "Country": "Sri Lanka",
    "Connection": "Active"
  },
  {
    "countryCode": "HSBC",
    "bankCode": "LK",
    "branchCode": "KLX",
    "SWIFT Code": "HSBCLKLX",
    "Bank Name": "HONGKONG AND SHANGHAI BANKING CORPORATION LIMITED, THE",
    "Address": "24 SIR BARON JAYATILAKA MAWATHA",
    "City": "COLOMBO",
    "Branch": "",
    "Postcode": "01000",
    "Country": "Sri Lanka",
    "Connection": "Active"
  },
  {
    "countryCode": "IDIB",
    "bankCode": "LK",
    "branchCode": "KLC",
    "SWIFT Code": "IDIBLKLC",
    "Bank Name": "INDIAN BANK",
    "Address": "356 GALLE ROAD, COLOMBO 3",
    "City": "COLOMBO",
    "Branch": "",
    "Postcode": "00300",
    "Country": "Sri Lanka",
    "Connection": "Active"
  },
  {
    "countryCode": "IOBA",
    "bankCode": "LK",
    "branchCode": "KLC",
    "SWIFT Code": "IOBALKLC",
    "Bank Name": "INDIAN OVERSEAS BANK",
    "Address": "IOB BUILDING, 139 MAIN STREET, 11 COLOMBO",
    "City": "COLOMBO",
    "Branch": "",
    "Postcode": "01000",
    "Country": "Sri Lanka",
    "Connection": "Active"
  },
  {
    "countryCode": "LOFC",
    "bankCode": "LK",
    "branchCode": "KLC",
    "SWIFT Code": "LOFCLKLC",
    "Bank Name": "LOLC FINANCE PLC",
    "Address": "100/1 SRI JAYAWARDANAPURA MAWATA, RAJAGIRIYA",
    "City": "COLOMBO",
    "Branch": "",
    "Postcode": "01000",
    "Country": "Sri Lanka",
    "Connection": "Active"
  },
  {
    "countryCode": "MUCB",
    "bankCode": "LK",
    "branchCode": "KLC",
    "SWIFT Code": "MUCBLKLC",
    "Bank Name": "MCB BANK LTD.",
    "Address": "8 LEYDEN BASTIAN ROAD",
    "City": "COLOMBO",
    "Branch": "",
    "Postcode": "01000",
    "Country": "Sri Lanka",
    "Connection": "Active"
  },
  {
    "countryCode": "NLEP",
    "bankCode": "LK",
    "branchCode": "KL2",
    "SWIFT Code": "NLEPLKL2",
    "Bank Name": "NATION LANKA EQUITIES (PVT) LTD.",
    "Address": "44 GUILDFORD CRESCENT, COLOMBO 7",
    "City": "COLOMBO",
    "Branch": "",
    "Postcode": "01000",
    "Country": "Sri Lanka",
    "Connection": "Active"
  },
  {
    "countryCode": "NDBS",
    "bankCode": "LK",
    "branchCode": "KLX",
    "SWIFT Code": "NDBSLKLX",
    "Bank Name": "NATIONAL DEVELOPMENT BANK PLC.",
    "Address": "40 NAWAM MAWATHA, 2 COLOMBO",
    "City": "COLOMBO",
    "Branch": "",
    "Postcode": "01000",
    "Country": "Sri Lanka",
    "Connection": "Active"
  },
  {
    "countryCode": "NSBA",
    "bankCode": "LK",
    "branchCode": "KLX",
    "SWIFT Code": "NSBALKLX",
    "Bank Name": "NATIONAL SAVINGS BANK",
    "Address": "SAVINGS HOUSE, 255 GALLE ROAD, 3 COLOMBO",
    "City": "COLOMBO",
    "Branch": "",
    "Postcode": "01000",
    "Country": "Sri Lanka",
    "Connection": "Active"
  },
  {
    "countryCode": "NTBC",
    "bankCode": "LK",
    "branchCode": "KLX",
    "SWIFT Code": "NTBCLKLX",
    "Bank Name": "NATIONS TRUST BANK PLC",
    "Address": "242 UNION PLACE",
    "City": "COLOMBO",
    "Branch": "",
    "Postcode": "00200",
    "Country": "Sri Lanka",
    "Connection": "Active"
  },
  {
    "countryCode": "NSBF",
    "bankCode": "LK",
    "branchCode": "KLX",
    "SWIFT Code": "NSBFLKLX",
    "Bank Name": "NSB FUND MANAGEMENT COMPANY LIMITED",
    "Address": "COLOMBO 03, 400 GALLE ROAD",
    "City": "COLOMBO",
    "Branch": "",
    "Postcode": "00300",
    "Country": "Sri Lanka",
    "Connection": "Active"
  },
  {
    "countryCode": "PABS",
    "bankCode": "LK",
    "branchCode": "KLX",
    "SWIFT Code": "PABSLKLX",
    "Bank Name": "PAN ASIA BANKING CORPORATION PLC",
    "Address": "PAN ASIA BANK BUILDING, 450 GALLE ROAD, 03 COLOMBO",
    "City": "COLOMBO",
    "Branch": "",
    "Postcode": "01000",
    "Country": "Sri Lanka",
    "Connection": "Active"
  },
  {
    "countryCode": "PSBK",
    "bankCode": "LK",
    "branchCode": "KLX",
    "SWIFT Code": "PSBKLKLX",
    "Bank Name": "PEOPLE'S BANK,HEAD OFFICE",
    "Address": "75 CHITTAMPALAM A GARDINER MW, 02 COLOMBO",
    "City": "COLOMBO",
    "Branch": "HEAD OFFICE",
    "Postcode": "01000",
    "Country": "Sri Lanka",
    "Connection": "Active"
  },
  {
    "countryCode": "PSBK",
    "bankCode": "LK",
    "branchCode": "022",
    "SWIFT Code": "PSBKLKLX022",
    "Bank Name": "PEOPLE'S BANK,HEAD OFFICE",
    "Address": "",
    "City": "COLOMBO",
    "Branch": "INTERNATIONAL DEPARTMENT",
    "Postcode": "",
    "Country": "Sri Lanka",
    "Connection": "Active"
  },
  {
    "countryCode": "PSBK",
    "bankCode": "LK",
    "branchCode": "023",
    "SWIFT Code": "PSBKLKLX023",
    "Bank Name": "PEOPLE'S BANK,HEAD OFFICE",
    "Address": "",
    "City": "COLOMBO",
    "Branch": "OVERSEAS DEPARTMENT",
    "Postcode": "",
    "Country": "Sri Lanka",
    "Connection": "Active"
  },
  {
    "countryCode": "PBBE",
    "bankCode": "LK",
    "branchCode": "KLX",
    "SWIFT Code": "PBBELKLX",
    "Bank Name": "PUBLIC BANK BERHAD",
    "Address": "340 R.A. DE MEL, MAWATHA",
    "City": "COLOMBO",
    "Branch": "",
    "Postcode": "00300",
    "Country": "Sri Lanka",
    "Connection": "Active"
  },
  {
    "countryCode": "BSAM",
    "bankCode": "LK",
    "branchCode": "KLX",
    "SWIFT Code": "BSAMLKLX",
    "Bank Name": "SAMPATH BANK PLC",
    "Address": "SAMPATH CENTRE, 110 SIR JAMES PEIRIS MAWATHA, 2 COLOMBO",
    "City": "COLOMBO",
    "Branch": "",
    "Postcode": "01000",
    "Country": "Sri Lanka",
    "Connection": "Active"
  },
  {
    "countryCode": "SENF",
    "bankCode": "LK",
    "branchCode": "KLX",
    "SWIFT Code": "SENFLKLX",
    "Bank Name": "SENKADAGALA FINANCE PLC",
    "Address": "267 GALLE ROAD",
    "City": "COLOMBO",
    "Branch": "",
    "Postcode": "00300",
    "Country": "Sri Lanka",
    "Connection": "Active"
  },
  {
    "countryCode": "SEYB",
    "bankCode": "LK",
    "branchCode": "KLX",
    "SWIFT Code": "SEYBLKLX",
    "Bank Name": "SEYLAN BANK PLC",
    "Address": "FLOOR 5, SEYLAN TOWERS, 90 GALLE ROAD, 03 COLOMBO",
    "City": "COLOMBO",
    "Branch": "",
    "Postcode": "01000",
    "Country": "Sri Lanka",
    "Connection": "Active"
  },
  {
    "countryCode": "SEYB",
    "bankCode": "LK",
    "branchCode": "TRY",
    "SWIFT Code": "SEYBLKLXTRY",
    "Bank Name": "SEYLAN BANK PLC",
    "Address": "",
    "City": "COLOMBO",
    "Branch": "TREASURY DIVISION",
    "Postcode": "",
    "Country": "Sri Lanka",
    "Connection": "Active"
  },
  {
    "countryCode": "SCBL",
    "bankCode": "LK",
    "branchCode": "KLX",
    "SWIFT Code": "SCBLLKLX",
    "Bank Name": "STANDARD CHARTERED BANK",
    "Address": "37 YORK STREET, 1 COLOMBO",
    "City": "COLOMBO",
    "Branch": "",
    "Postcode": "01000",
    "Country": "Sri Lanka",
    "Connection": "Active"
  },
  {
    "countryCode": "SCBL",
    "bankCode": "LK",
    "branchCode": "EQI",
    "SWIFT Code": "SCBLLKLXEQI",
    "Bank Name": "STANDARD CHARTERED BANK",
    "Address": "37 YORK STREET, 1 COLOMBO",
    "City": "COLOMBO",
    "Branch": "CUSTODY",
    "Postcode": "01000",
    "Country": "Sri Lanka",
    "Connection": "Active"
  },
  {
    "countryCode": "SBIN",
    "bankCode": "LK",
    "branchCode": "KLX",
    "SWIFT Code": "SBINLKLX",
    "Bank Name": "STATE BANK OF INDIA",
    "Address": "16 SIR BARON JAYATILAKA MAWATHA, 1 COLOMBO",
    "City": "COLOMBO",
    "Branch": "",
    "Postcode": "01000",
    "Country": "Sri Lanka",
    "Connection": "Active"
  }
]
module.exports = sriLanka
