const suriname = [
  {
    "countryCode": "CBVS",
    "bankCode": "SR",
    "branchCode": "RPA",
    "SWIFT Code": "CBVSSRPA",
    "Bank Name": "CENTRALE BANK VAN SURINAME",
    "Address": "WATERKANT 20",
    "City": "PARAMARIBO",
    "Branch": "",
    "Postcode": "",
    "Country": "Suriname",
    "Connection": "Active"
  },
  {
    "countryCode": "CBVS",
    "bankCode": "SR",
    "branchCode": "SUR",
    "SWIFT Code": "CBVSSRPASUR",
    "Bank Name": "CENTRALE BANK VAN SURINAME",
    "Address": "WATERKANT 20",
    "City": "PARAMARIBO",
    "Branch": "",
    "Postcode": "",
    "Country": "Suriname",
    "Connection": "Active"
  },
  {
    "countryCode": "GODO",
    "bankCode": "SR",
    "branchCode": "RPA",
    "SWIFT Code": "GODOSRPA",
    "Bank Name": "COOPERATIEVE SPAAR- EN KREDIETBANK GODO U.A.",
    "Address": "KEIZERSTRAAT 139 - 143",
    "City": "PARAMARIBO",
    "Branch": "",
    "Postcode": "",
    "Country": "Suriname",
    "Connection": "Active"
  },
  {
    "countryCode": "SURB",
    "bankCode": "SR",
    "branchCode": "RPA",
    "SWIFT Code": "SURBSRPA",
    "Bank Name": "DSB BANK ALSO KNOWN AS DE SURINAAMSCHE BANK N.V. PARAMARIBO SR",
    "Address": "HENCK ARRONSTRAAT 26-30",
    "City": "PARAMARIBO",
    "Branch": "",
    "Postcode": "",
    "Country": "Suriname",
    "Connection": "Active"
  },
  {
    "countryCode": "FBNA",
    "bankCode": "SR",
    "branchCode": "RPA",
    "SWIFT Code": "FBNASRPA",
    "Bank Name": "FINABANK N.V.",
    "Address": "DR. SOPHIE REDMONDSTRAAT 59-61",
    "City": "PARAMARIBO",
    "Branch": "",
    "Postcode": "",
    "Country": "Suriname",
    "Connection": "Active"
  },
  {
    "countryCode": "ICTB",
    "bankCode": "SR",
    "branchCode": "RPA",
    "SWIFT Code": "ICTBSRPA",
    "Bank Name": "FINATRUST, DE TRUSTBANK N.V.",
    "Address": "DR. SOPHIE REDMONDSTRAAT 93",
    "City": "PARAMARIBO",
    "Branch": "",
    "Postcode": "",
    "Country": "Suriname",
    "Connection": "Active"
  },
  {
    "countryCode": "HAKR",
    "bankCode": "SR",
    "branchCode": "RPA",
    "SWIFT Code": "HAKRSRPA",
    "Bank Name": "HAKRINBANK N.V.",
    "Address": "DR. SOPHIE REDMONDSTRAAT 11-13",
    "City": "PARAMARIBO",
    "Branch": "",
    "Postcode": "",
    "Country": "Suriname",
    "Connection": "Active"
  },
  {
    "countryCode": "RBNK",
    "bankCode": "SR",
    "branchCode": "RPA",
    "SWIFT Code": "RBNKSRPA",
    "Bank Name": "REPUBLIC BANK (SURINAME) N.V.",
    "Address": "KERKPLEIN 1",
    "City": "PARAMARIBO",
    "Branch": "",
    "Postcode": "",
    "Country": "Suriname",
    "Connection": "Active"
  },
  {
    "countryCode": "SOUO",
    "bankCode": "SR",
    "branchCode": "RPP",
    "SWIFT Code": "SOUOSRPP",
    "Bank Name": "SOUTHERN COMMERCIAL BANK NV",
    "Address": "TOURTONNELAAN 33",
    "City": "PARAMARIBO",
    "Branch": "",
    "Postcode": "",
    "Country": "Suriname",
    "Connection": "Active"
  },
  {
    "countryCode": "SURC",
    "bankCode": "SR",
    "branchCode": "RPA",
    "SWIFT Code": "SURCSRPA",
    "Bank Name": "SURICHANGE BANK N.V.",
    "Address": "DR. SOPHIE REDMONDSTRAAT 71",
    "City": "PARAMARIBO",
    "Branch": "",
    "Postcode": "",
    "Country": "Suriname",
    "Connection": "Active"
  },
  {
    "countryCode": "SDPO",
    "bankCode": "SR",
    "branchCode": "RPA",
    "SWIFT Code": "SDPOSRPA",
    "Bank Name": "SURINAAMSE POSTSPAARBANK",
    "Address": "KNUFFELSGRACHT 10-14",
    "City": "PARAMARIBO",
    "Branch": "",
    "Postcode": "",
    "Country": "Suriname",
    "Connection": "Active"
  },
  {
    "countryCode": "VCBS",
    "bankCode": "SR",
    "branchCode": "RPA",
    "SWIFT Code": "VCBSSRPA",
    "Bank Name": "SURINAAMSE VOLKSCREDIETBANK",
    "Address": "WATERKANT 104",
    "City": "PARAMARIBO",
    "Branch": "",
    "Postcode": "",
    "Country": "Suriname",
    "Connection": "Active"
  }
]
module.exports = suriname
