const sweden = [
  {
    "bankCode": "SWED",
    "countryCode": "SE",
    "branchCode": "ROB",
    "SWIFT Code": "SWEDSESSROB",
    "Bank Name": "SWEDBANK AB (PUBL)",
    "Address": "LANDSVAEGEN 40, SUNDBYBERG",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "172 63",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "SWED",
    "countryCode": "SE",
    "branchCode": "CUS",
    "SWIFT Code": "SWEDSESSCUS",
    "Bank Name": "SWEDBANK AB (PUBL)",
    "Address": "LANDSVAGEN 40, SUNDBYBERG",
    "City": "STOCKHOLM",
    "Branch": "SECURITIES SERVICES",
    "Postcode": "105 34",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "ROBR",
    "countryCode": "SE",
    "branchCode": "ESS",
    "SWIFT Code": "ROBRSESS",
    "Bank Name": "SWEDBANK ROBUR FONDER AB",
    "Address": "LANDSVAGEN",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "105 34",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "SEKX",
    "countryCode": "SE",
    "branchCode": "ESS",
    "SWIFT Code": "SEKXSESS",
    "Bank Name": "SWEDISH EXPORT CREDIT CORP.",
    "Address": "FLEMINGGATAN 20",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "101 23",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "SWIH",
    "countryCode": "SE",
    "branchCode": "EM2",
    "SWIFT Code": "SWIHSEM2",
    "Bank Name": "SWEDISH INTERNATIONAL HOLDING AB",
    "Address": "ST KNUTS VAG 19",
    "City": "MALMO",
    "Branch": "",
    "Postcode": "211 57",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "SNDO",
    "countryCode": "SE",
    "branchCode": "ESS",
    "SWIFT Code": "SNDOSESS",
    "Bank Name": "SWEDISH NATIONAL DEBT OFFICE",
    "Address": "OLOF PALMES GATA 17, FLOOR 4",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "103 74",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "TEER",
    "countryCode": "SE",
    "branchCode": "ESS",
    "SWIFT Code": "TEERSESS",
    "Bank Name": "TELEFONAKTIEBOLAGET LM ERICSSON",
    "Address": "TORSHAMNSGATAN 21",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "164 83",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "TEER",
    "countryCode": "SE",
    "branchCode": "ES3",
    "SWIFT Code": "TEERSES3",
    "Bank Name": "TELEFONAKTIEBOLAGET LM ERICSSON",
    "Address": "TORSHAMNSGATAN 23",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "164 83",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "TLSN",
    "countryCode": "SE",
    "branchCode": "ESS",
    "SWIFT Code": "TLSNSESS",
    "Bank Name": "TELIA COMPANY AB (PUBL)",
    "Address": "STJARNTORGET 1",
    "City": "SOLNA",
    "Branch": "",
    "Postcode": "169 94",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "TMHE",
    "countryCode": "SE",
    "branchCode": "E22",
    "SWIFT Code": "TMHESE22",
    "Bank Name": "TOYOTA MATERIAL HANDLING EUROPE AB",
    "Address": "SVARVARGATAN 8",
    "City": "MJOLBY",
    "Branch": "",
    "Postcode": "595 81",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "TEYD",
    "countryCode": "SE",
    "branchCode": "ES2",
    "SWIFT Code": "TEYDSES2",
    "Bank Name": "TREYD SERVICES AB",
    "Address": "REGERINGSGATAN 38, FLOOR 5",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "111 56",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "TRII",
    "countryCode": "SE",
    "branchCode": "ES2",
    "SWIFT Code": "TRIISES2",
    "Bank Name": "TRIOPTIMA AB",
    "Address": "FLEMINGGATAN 14",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "112 26",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "TRLY",
    "countryCode": "SE",
    "branchCode": "ESS",
    "SWIFT Code": "TRLYSESS",
    "Bank Name": "TRUSTLY GROUP AB",
    "Address": "RADMANSGATAN 40",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "113 57",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "PANX",
    "countryCode": "SE",
    "branchCode": "ES2",
    "SWIFT Code": "PANXSES2",
    "Bank Name": "UNIFIEDPOST PAYMENTS SWEDEN FILIAL",
    "Address": "",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "121 25",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "VASE",
    "countryCode": "SE",
    "branchCode": "ES2",
    "SWIFT Code": "VASESES2",
    "Bank Name": "VATOR SECURITIES AB",
    "Address": "KUNGSGATAN 34",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "111 35",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "VCTK",
    "countryCode": "SE",
    "branchCode": "ES2",
    "SWIFT Code": "VCTKSES2",
    "Bank Name": "VISTA CAPITAL TRUST KOMMANDITBOLAG",
    "Address": "",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "116 74",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "VPAY",
    "countryCode": "SE",
    "branchCode": "ES2",
    "SWIFT Code": "VPAYSES2",
    "Bank Name": "VIVA PAYMENT SERVICES S.A.- SWEDEN BRANCH FILIAL",
    "Address": "",
    "City": "STOCKHOLM",
    "Branch": "MAZARS SKATT KB",
    "Postcode": "111 83",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "VCAR",
    "countryCode": "SE",
    "branchCode": "EGG",
    "SWIFT Code": "VCARSEGG",
    "Bank Name": "VOLVO CAR CORPORATION",
    "Address": "AVD. HB3S 50090",
    "City": "GOTEBORG",
    "Branch": "",
    "Postcode": "405 31",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "VOTR",
    "countryCode": "SE",
    "branchCode": "EG2",
    "SWIFT Code": "VOTRSEG2",
    "Bank Name": "VOLVO TREASURY AB",
    "Address": "REGNBAGSGATAN 1, M2",
    "City": "GOTEBORG",
    "Branch": "",
    "Postcode": "405 08",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "VPCS",
    "countryCode": "SE",
    "branchCode": "EKA",
    "SWIFT Code": "VPCSSEKA",
    "Bank Name": "VPC AB",
    "Address": "",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "ZIMP",
    "countryCode": "SE",
    "branchCode": "ES2",
    "SWIFT Code": "ZIMPSES2",
    "Bank Name": "ZIMPLER AB",
    "Address": "DOBELSGATAN 12",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "113 58",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {},
  {
    "bankCode": "VPCS",
    "countryCode": "SE",
    "branchCode": "CLP",
    "SWIFT Code": "VPCSSESSCLP",
    "Bank Name": "EUROCLEAR SWEDEN AB",
    "Address": "",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "VPCS",
    "countryCode": "SE",
    "branchCode": "FND",
    "SWIFT Code": "VPCSSESSFND",
    "Bank Name": "EUROCLEAR SWEDEN AB",
    "Address": "KLARABERGSVIADUKTEN 63",
    "City": "STOCKHOLM",
    "Branch": "FUNDS",
    "Postcode": "101 23",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "VPCS",
    "countryCode": "SE",
    "branchCode": "VKI",
    "SWIFT Code": "VPCSSESSVKI",
    "Bank Name": "EUROCLEAR SWEDEN AB",
    "Address": "",
    "City": "STOCKHOLM",
    "Branch": "VPC AB'S ACCOUNT OPERATOR",
    "Postcode": "",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "EKTK",
    "countryCode": "SE",
    "branchCode": "ES2",
    "SWIFT Code": "EKTKSES2",
    "Bank Name": "EUROPEISK KOMMERSIELL TRUST KOMMANDITBOLAG",
    "Address": "ENGELBREKSGATAN 9-11",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "114 32",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "EWEL",
    "countryCode": "SE",
    "branchCode": "EGG",
    "SWIFT Code": "EWELSEGG",
    "Bank Name": "EWELLIX AB",
    "Address": "LILLA WATERLOOGATAN 8",
    "City": "GOTEBORG",
    "Branch": "",
    "Postcode": "415 02",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "BNPA",
    "countryCode": "SE",
    "branchCode": "ESS",
    "SWIFT Code": "BNPASESS",
    "Bank Name": "EXPRESS BANK SVERIGE FILIAL",
    "Address": "FAROGATAN 33, KISTA SCIENCE TOWER",
    "City": "KISTA",
    "Branch": "",
    "Postcode": "164 51",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "FRTD",
    "countryCode": "SE",
    "branchCode": "ES2",
    "SWIFT Code": "FRTDSES2",
    "Bank Name": "FREETRADE EUROPA AB",
    "Address": "KATARINAVAGEN 15, COVENDUM",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "116 45",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "GLSY",
    "countryCode": "SE",
    "branchCode": "ES2",
    "SWIFT Code": "GLSYSES2",
    "Bank Name": "GAMLA LIVFORSAKRINGSAKTIEBOLAGET SEB TRYGG LIV (PUBL)",
    "Address": "ARSENALSGATAN 2, FLOOR 5",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "111 47",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "GTRE",
    "countryCode": "SE",
    "branchCode": "EGG",
    "SWIFT Code": "GTRESEGG",
    "Bank Name": "GETINGE TREASURY AB",
    "Address": "LINDHOLMSPIREN 7",
    "City": "GOETEBORG",
    "Branch": "",
    "Postcode": "417 56",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "GITC",
    "countryCode": "SE",
    "branchCode": "ES2",
    "SWIFT Code": "GITCSES2",
    "Bank Name": "GIZA TRUST COMPANY KB",
    "Address": "STOCKHOLMS BREVBOXAR 447",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "116 74",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "GLCT",
    "countryCode": "SE",
    "branchCode": "ES2",
    "SWIFT Code": "GLCTSES2",
    "Bank Name": "GLENMUIR CAPITAL TRUST KB",
    "Address": "",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "116 74",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "GFTM",
    "countryCode": "SE",
    "branchCode": "ES2",
    "SWIFT Code": "GFTMSES2",
    "Bank Name": "GLOBAL FINANCIAL TRUST MANAGEMENT GROUP KB",
    "Address": "TEGELUDDSVAGEN 76, 2 TR",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "115 28",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "HMHM",
    "countryCode": "SE",
    "branchCode": "ESS",
    "SWIFT Code": "HMHMSESS",
    "Bank Name": "H AND M HENNES AND MAURITZ GBC AB",
    "Address": "MASTER SAMUELSGATAN 46A",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "106 38",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "HMHM",
    "countryCode": "SE",
    "branchCode": "GOE",
    "SWIFT Code": "HMHMSESSGOE",
    "Bank Name": "H AND M HENNES AND MAURITZ GBC AB",
    "Address": "MASTER SAMUELSGATAN 46A",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "106 38",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "HABM",
    "countryCode": "SE",
    "branchCode": "EMM",
    "SWIFT Code": "HABMSEMM",
    "Bank Name": "HEIMSTADEN AB",
    "Address": "OSTRA PROMENADEN 7A",
    "City": "MALMO",
    "Branch": "",
    "Postcode": "211 28",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "HSBO",
    "countryCode": "SE",
    "branchCode": "EMM",
    "SWIFT Code": "HSBOSEMM",
    "Bank Name": "HEIMSTADEN BOSTAD AB",
    "Address": "OSTRA PROMENADEN 7A",
    "City": "MALMO",
    "Branch": "",
    "Postcode": "211 28",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "ICHO",
    "countryCode": "SE",
    "branchCode": "ES2",
    "SWIFT Code": "ICHOSES2",
    "Bank Name": "ICM HOUSE KB",
    "Address": "",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "116 74",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "FTCS",
    "countryCode": "SE",
    "branchCode": "ES2",
    "SWIFT Code": "FTCSSES2",
    "Bank Name": "INTERGIRO INTL AB (PUBL)",
    "Address": "REGERINGSGATAN 59, FLOOR 9",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "111 56",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "FTCS",
    "countryCode": "SE",
    "branchCode": "ESS",
    "SWIFT Code": "FTCSSESS",
    "Bank Name": "INTERGIRO INTL AB (PUBL)",
    "Address": "REGERINGSGATAN 59, FLOOR 9",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "111 56",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "JAKM",
    "countryCode": "SE",
    "branchCode": "E22",
    "SWIFT Code": "JAKMSE22",
    "Bank Name": "JAK MEDLEMSBANK",
    "Address": "VASAGATAN 14",
    "City": "SKOVDE",
    "Branch": "",
    "Postcode": "541 25",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "KAMR",
    "countryCode": "SE",
    "branchCode": "ES2",
    "SWIFT Code": "KAMRSES2",
    "Bank Name": "KAMMARKOLLEGIET",
    "Address": "BIRGER JARLSGATAN 16",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "103 15",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "KLRN",
    "countryCode": "SE",
    "branchCode": "ESS",
    "SWIFT Code": "KLRNSESS",
    "Bank Name": "KLARNA BANK",
    "Address": "SVEAVAEGEN 46",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "111 34",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "KLRN",
    "countryCode": "SE",
    "branchCode": "TRE",
    "SWIFT Code": "KLRNSESSTRE",
    "Bank Name": "KLARNA BANK",
    "Address": "SVEAVAEGEN 46",
    "City": "STOCKHOLM",
    "Branch": "KLARNA TREASURY",
    "Postcode": "111 34",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "KLRN",
    "countryCode": "SE",
    "branchCode": "SWI",
    "SWIFT Code": "KLRNSESSSWI",
    "Bank Name": "KLARNA BANK",
    "Address": "",
    "City": "STOCKHOLM",
    "Branch": "SWISH",
    "Postcode": "",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "KLRN",
    "countryCode": "SE",
    "branchCode": "TIP",
    "SWIFT Code": "KLRNSESSTIP",
    "Bank Name": "KLARNA BANK",
    "Address": "SVEAVAEGEN 46",
    "City": "STOCKHOLM",
    "Branch": "TIPS PARTICIPANT",
    "Postcode": "111 34",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "KIAB",
    "countryCode": "SE",
    "branchCode": "E22",
    "SWIFT Code": "KIABSE22",
    "Bank Name": "KOMMUNINVEST I SVERIGE AB",
    "Address": "DROTTNINGGATAN 2, FENIX HOUSE",
    "City": "OREBRO",
    "Branch": "",
    "Postcode": "701 42",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "LAHY",
    "countryCode": "SE",
    "branchCode": "ESS",
    "SWIFT Code": "LAHYSESS",
    "Bank Name": "LANDSHYPOTEK BANK AB",
    "Address": "REGERINGSGATAN 48",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "104 41",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "LAFD",
    "countryCode": "SE",
    "branchCode": "ES2",
    "SWIFT Code": "LAFDSES2",
    "Bank Name": "LANNEBO FONDER AB",
    "Address": "KUNGSGATAN 5",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "103 99",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "ELLF",
    "countryCode": "SE",
    "branchCode": "ESS",
    "SWIFT Code": "ELLFSESS",
    "Bank Name": "LANSFORSAKRINGAR BANK AB",
    "Address": "TEGELUDDSVAEGEN 11-13",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "106 50",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "LAFK",
    "countryCode": "SE",
    "branchCode": "EST",
    "SWIFT Code": "LAFKSEST",
    "Bank Name": "LANSFORSAKRINGAR FONDFORVALTNING AKTIEBOLAG",
    "Address": "TEGELUDDSVAGEN 11-13",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "113 85",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "LLFP",
    "countryCode": "SE",
    "branchCode": "EST",
    "SWIFT Code": "LLFPSEST",
    "Bank Name": "LANSFORSAKRINGAR LIV FORSAKRINGSAKTIEBOLAG (PUBL)",
    "Address": "TEGELUDDSVAEGEN 11-13",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "106 50",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "LANT",
    "countryCode": "SE",
    "branchCode": "ESS",
    "SWIFT Code": "LANTSESS",
    "Bank Name": "LANTMANNEN EK",
    "Address": "ST GORANSGATAN 160A",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "104 25",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "LETE",
    "countryCode": "SE",
    "branchCode": "ES2",
    "SWIFT Code": "LETESES2",
    "Bank Name": "LESSLIE TECHNOLOGIES AB",
    "Address": "LOVSTIGEN 5, LIDINGO",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "181 32",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "LOWO",
    "countryCode": "SE",
    "branchCode": "ES2",
    "SWIFT Code": "LOWOSES2",
    "Bank Name": "LOTHAR WORLDWIDE",
    "Address": "FOLKUNGAGATAN 132C, STOCKHOLMS BREVBOXAR",
    "City": "STOCKHOLM",
    "Branch": "STOCKHOLMS BREVBOXAR",
    "Postcode": "116 30",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "MARG",
    "countryCode": "SE",
    "branchCode": "ESS",
    "SWIFT Code": "MARGSESS",
    "Bank Name": "MARGINALEN BANK BANKAKTIEBOLAG",
    "Address": "",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "100 41",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "MFEX",
    "countryCode": "SE",
    "branchCode": "ESS",
    "SWIFT Code": "MFEXSESS",
    "Bank Name": "MFEX MUTUAL FUNDS EXCHANGE AB",
    "Address": "GREV TUREGATAN 19",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "114 38",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "MFEX",
    "countryCode": "SE",
    "branchCode": "GFP",
    "SWIFT Code": "MFEXSESSGFP",
    "Bank Name": "MFEX MUTUAL FUNDS EXCHANGE AB",
    "Address": "GREV TUREGATAN 19",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "114 38",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "MOHE",
    "countryCode": "SE",
    "branchCode": "EGG",
    "SWIFT Code": "MOHESEGG",
    "Bank Name": "MOLNLYCKE HEALTH CARE AB",
    "Address": "GAMLESTADSVAGEN 3C, FLOOR 4",
    "City": "GOTEBORG",
    "Branch": "",
    "Postcode": "405 04",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "OMEC",
    "countryCode": "SE",
    "branchCode": "DKK",
    "SWIFT Code": "OMECSESSDKK",
    "Bank Name": "NASDAQ CLEARING AB",
    "Address": "TULLVAKTSVAGEN 15",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "105 78",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "OMEC",
    "countryCode": "SE",
    "branchCode": "TDK",
    "SWIFT Code": "OMECSESSTDK",
    "Bank Name": "NASDAQ CLEARING AB",
    "Address": "TULLVAKTSVAGEN 15",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "105 78",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "OMEC",
    "countryCode": "SE",
    "branchCode": "ESS",
    "SWIFT Code": "OMECSESS",
    "Bank Name": "NASDAQ CLEARING AB",
    "Address": "TULLVAKTSVAGEN 15",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "105 78",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "OMEC",
    "countryCode": "SE",
    "branchCode": "CCP",
    "SWIFT Code": "OMECSESSCCP",
    "Bank Name": "NASDAQ CLEARING AB",
    "Address": "TULLVAKTSVAGEN 15",
    "City": "STOCKHOLM",
    "Branch": "CENTRAL COUNTER PARTY",
    "Postcode": "105 78",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "OMEC",
    "countryCode": "SE",
    "branchCode": "NOC",
    "SWIFT Code": "OMECSESSNOC",
    "Bank Name": "NASDAQ CLEARING AB",
    "Address": "",
    "City": "STOCKHOLM",
    "Branch": "CLEARING",
    "Postcode": "",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "OMEC",
    "countryCode": "SE",
    "branchCode": "COL",
    "SWIFT Code": "OMECSESSCOL",
    "Bank Name": "NASDAQ CLEARING AB",
    "Address": "TULLVAKTSVAGEN 15",
    "City": "STOCKHOLM",
    "Branch": "COLLATERALS",
    "Postcode": "105 78",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "OMEC",
    "countryCode": "SE",
    "branchCode": "DVP",
    "SWIFT Code": "OMECSESSDVP",
    "Bank Name": "NASDAQ CLEARING AB",
    "Address": "",
    "City": "STOCKHOLM",
    "Branch": "DERIVATIVES",
    "Postcode": "",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "OMEC",
    "countryCode": "SE",
    "branchCode": "EXT",
    "SWIFT Code": "OMECSESSEXT",
    "Bank Name": "NASDAQ CLEARING AB",
    "Address": "",
    "City": "STOCKHOLM",
    "Branch": "EXTERNAL",
    "Postcode": "",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "OMEC",
    "countryCode": "SE",
    "branchCode": "TSU",
    "SWIFT Code": "OMECSESSTSU",
    "Bank Name": "NASDAQ CLEARING AB",
    "Address": "TULLVAKTSVAGEN 15",
    "City": "STOCKHOLM",
    "Branch": "TREASURY",
    "Postcode": "105 78",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "OMEC",
    "countryCode": "SE",
    "branchCode": "TRE",
    "SWIFT Code": "OMECSESSTRE",
    "Bank Name": "NASDAQ CLEARING AB",
    "Address": "",
    "City": "STOCKHOLM",
    "Branch": "TREASURY",
    "Postcode": "",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "NCTK",
    "countryCode": "SE",
    "branchCode": "ES2",
    "SWIFT Code": "NCTKSES2",
    "Bank Name": "NATIONAL CAPITAL TRUST KOMMANDITBOLAG",
    "Address": "VASAGATAN 28",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "111 20",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "NOFB",
    "countryCode": "SE",
    "branchCode": "ESS",
    "SWIFT Code": "NOFBSESS",
    "Bank Name": "NOBA BANK GROUP AB (PUBL)",
    "Address": "GAVLEGATAN 22",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "113 30",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "ESSE",
    "countryCode": "SE",
    "branchCode": "ENS",
    "SWIFT Code": "ESSESESSENS",
    "Bank Name": "SKANDINAVISKA ENSKILDA BANKEN AB",
    "Address": "",
    "City": "STOCKHOLM",
    "Branch": "ENSKILDA SECURITIES",
    "Postcode": "",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "ESSE",
    "countryCode": "SE",
    "branchCode": "EQU",
    "SWIFT Code": "ESSESESSEQU",
    "Bank Name": "SKANDINAVISKA ENSKILDA BANKEN AB",
    "Address": "STJARNTORGET 4",
    "City": "STOCKHOLM",
    "Branch": "EQUITIES",
    "Postcode": "106 40",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "ESSE",
    "countryCode": "SE",
    "branchCode": "IOS",
    "SWIFT Code": "ESSESESSIOS",
    "Bank Name": "SKANDINAVISKA ENSKILDA BANKEN AB",
    "Address": "RISSNELEDEN 110",
    "City": "STOCKHOLM",
    "Branch": "INVESTMENT OPERATIONS",
    "Postcode": "106 40",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "ESSE",
    "countryCode": "SE",
    "branchCode": "SLS",
    "SWIFT Code": "ESSESESSSLS",
    "Bank Name": "SKANDINAVISKA ENSKILDA BANKEN AB",
    "Address": "STJARNTORGET 4",
    "City": "STOCKHOLM",
    "Branch": "SECURITIES LENDING",
    "Postcode": "106 40",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "ESSE",
    "countryCode": "SE",
    "branchCode": "EGC",
    "SWIFT Code": "ESSESEGC",
    "Bank Name": "SKANDINAVISKA ENSKILDA BANKEN AB GLOBAL CUSTODY",
    "Address": "STJARNTORGET 4",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "106 40",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "SKFI",
    "countryCode": "SE",
    "branchCode": "EGA",
    "SWIFT Code": "SKFISEGA",
    "Bank Name": "SKF INTERNATIONAL AB",
    "Address": "HORNSGATAN 1",
    "City": "GOTEBORG",
    "Branch": "",
    "Postcode": "415 50",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "SKFI",
    "countryCode": "SE",
    "branchCode": "EGB",
    "SWIFT Code": "SKFISEGB",
    "Bank Name": "SKF INTERNATIONAL AB",
    "Address": "SVEN WINGQUIST GATA 2",
    "City": "GOTEBORG",
    "Branch": "",
    "Postcode": "415 50",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "SPSD",
    "countryCode": "SE",
    "branchCode": "E23",
    "SWIFT Code": "SPSDSE23",
    "Bank Name": "SPARBANKEN SYD",
    "Address": "HAMNGATAN 2",
    "City": "YSTAD",
    "Branch": "",
    "Postcode": "271 25",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "SPSD",
    "countryCode": "SE",
    "branchCode": "SWI",
    "SWIFT Code": "SPSDSE23SWI",
    "Bank Name": "SPARBANKEN SYD",
    "Address": "HAMNGATAN 2",
    "City": "YSTAD",
    "Branch": "",
    "Postcode": "271 25",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "SPOT",
    "countryCode": "SE",
    "branchCode": "ESS",
    "SWIFT Code": "SPOTSESS",
    "Bank Name": "SPOTIFY AB",
    "Address": "REGERINGSGATAN 19",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "111 53",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "ASAB",
    "countryCode": "SE",
    "branchCode": "ESS",
    "SWIFT Code": "ASABSESS",
    "Bank Name": "SSAB AB",
    "Address": "KLARABERGSVIADUKTEN 6, 70, WTC",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "101 21",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "SVVV",
    "countryCode": "SE",
    "branchCode": "ESS",
    "SWIFT Code": "SVVVSESS",
    "Bank Name": "STEVEN AB",
    "Address": "STUREGATAN 4 4, FLOOR 3",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "102 44",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "SVEA",
    "countryCode": "SE",
    "branchCode": "ESS",
    "SWIFT Code": "SVEASESS",
    "Bank Name": "SVEA BANK AB",
    "Address": "EVENEMANGSGATAN 31",
    "City": "SOLNA",
    "Branch": "",
    "Postcode": "169 03",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "SVEA",
    "countryCode": "SE",
    "branchCode": "IXX",
    "SWIFT Code": "SVEASESSIXX",
    "Bank Name": "SVEA BANK AB",
    "Address": "EVENEMANGSGATAN 31",
    "City": "SOLNA",
    "Branch": "",
    "Postcode": "169 03",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "HAND",
    "countryCode": "SE",
    "branchCode": "GBG",
    "SWIFT Code": "HANDSESSGBG",
    "Bank Name": "SVENSKA HANDELSBANKEN AB",
    "Address": "OSTRA HAMNGATAN 23",
    "City": "GOTEBORG",
    "Branch": "TRADE AND EXPORT FINANCE",
    "Postcode": "404 26",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "HAND",
    "countryCode": "SE",
    "branchCode": "MLM",
    "SWIFT Code": "HANDSESSMLM",
    "Bank Name": "SVENSKA HANDELSBANKEN AB",
    "Address": "SODERGATAN 12",
    "City": "MALMO",
    "Branch": "TRADE AND EXPORT FINANCE",
    "Postcode": "202 11",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "HAND",
    "countryCode": "SE",
    "branchCode": "CLS",
    "SWIFT Code": "HANDSESSCLS",
    "Bank Name": "SVENSKA HANDELSBANKEN AB",
    "Address": "BLASIEHOLMSTORG 11",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "106 70",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "HAND",
    "countryCode": "SE",
    "branchCode": "ESS",
    "SWIFT Code": "HANDSESS",
    "Bank Name": "SVENSKA HANDELSBANKEN AB",
    "Address": "KUNGSTRADGARDSGATAN 2",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "111 47",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "HAND",
    "countryCode": "SE",
    "branchCode": "SHP",
    "SWIFT Code": "HANDSESSSHP",
    "Bank Name": "SVENSKA HANDELSBANKEN AB",
    "Address": "BLASIEHOLMSTORG 11",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "106 70",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "HAND",
    "countryCode": "SE",
    "branchCode": "SH1",
    "SWIFT Code": "HANDSESSSH1",
    "Bank Name": "SVENSKA HANDELSBANKEN AB",
    "Address": "BLASIEHOLMSTORG 11",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "106 70",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "HAND",
    "countryCode": "SE",
    "branchCode": "FIC",
    "SWIFT Code": "HANDSESSFIC",
    "Bank Name": "SVENSKA HANDELSBANKEN AB",
    "Address": "BLASIEHOLMSTORG 11",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "106 70",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "HAND",
    "countryCode": "SE",
    "branchCode": "SHY",
    "SWIFT Code": "HANDSESSSHY",
    "Bank Name": "SVENSKA HANDELSBANKEN AB",
    "Address": "BLASIEHOLMSTORG 11",
    "City": "STOCKHOLM",
    "Branch": "AKTIESPAR",
    "Postcode": "106 70",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "HAND",
    "countryCode": "SE",
    "branchCode": "SHD",
    "SWIFT Code": "HANDSESSSHD",
    "Bank Name": "SVENSKA HANDELSBANKEN AB",
    "Address": "BLASIEHOLMSTORG 11",
    "City": "STOCKHOLM",
    "Branch": "DMA TRADING",
    "Postcode": "106 70",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "HAND",
    "countryCode": "SE",
    "branchCode": "CUS",
    "SWIFT Code": "HANDSESSCUS",
    "Bank Name": "SVENSKA HANDELSBANKEN AB",
    "Address": "BLASIEHOLMSTORG 11",
    "City": "STOCKHOLM",
    "Branch": "NORDIC CUSTODY SERVICES",
    "Postcode": "106 70",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "HAND",
    "countryCode": "SE",
    "branchCode": "I01",
    "SWIFT Code": "HANDSESSI01",
    "Bank Name": "SVENSKA HANDELSBANKEN AB",
    "Address": "KUNGSTRADGARDSGATAN 2",
    "City": "STOCKHOLM",
    "Branch": "RIX-INST",
    "Postcode": "106 70",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "HAND",
    "countryCode": "SE",
    "branchCode": "I02",
    "SWIFT Code": "HANDSESSI02",
    "Bank Name": "SVENSKA HANDELSBANKEN AB",
    "Address": "KUNGSTRADGARDSGATAN 2",
    "City": "STOCKHOLM",
    "Branch": "RIX-INST",
    "Postcode": "106 70",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "HAND",
    "countryCode": "SE",
    "branchCode": "ASM",
    "SWIFT Code": "HANDSESSASM",
    "Bank Name": "SVENSKA HANDELSBANKEN AB",
    "Address": "BLASIEHOLMSTORG 11",
    "City": "STOCKHOLM",
    "Branch": "STOCKHOLM",
    "Postcode": "106 70",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "RIKS",
    "countryCode": "SE",
    "branchCode": "ESS",
    "SWIFT Code": "RIKSSESS",
    "Bank Name": "SVERIGES RIKSBANK",
    "Address": "BRUNKEBERGSTORG 11",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "103 37",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "RIKS",
    "countryCode": "SE",
    "branchCode": "ES3",
    "SWIFT Code": "RIKSSES3",
    "Bank Name": "SVERIGES RIKSBANK",
    "Address": "BRUNKEBERGSTORG 11",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "103 37",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "RIKS",
    "countryCode": "SE",
    "branchCode": "KIR",
    "SWIFT Code": "RIKSSESSKIR",
    "Bank Name": "SVERIGES RIKSBANK",
    "Address": "BRUNKEBERGSTORG 11",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "103 37",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "RIKS",
    "countryCode": "SE",
    "branchCode": "CMS",
    "SWIFT Code": "RIKSSESSCMS",
    "Bank Name": "SVERIGES RIKSBANK",
    "Address": "BRUNKEBERGSTORG 11",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "103 37",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "RIKS",
    "countryCode": "SE",
    "branchCode": "DIM",
    "SWIFT Code": "RIKSSESSDIM",
    "Bank Name": "SVERIGES RIKSBANK",
    "Address": "BRUNKEBERGSTORG 11",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "103 37",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "RIKS",
    "countryCode": "SE",
    "branchCode": "LAG",
    "SWIFT Code": "RIKSSESSLAG",
    "Bank Name": "SVERIGES RIKSBANK",
    "Address": "BRUNKEBERGSTORG 11",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "103 37",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "RIKS",
    "countryCode": "SE",
    "branchCode": "SWA",
    "SWIFT Code": "RIKSSESSSWA",
    "Bank Name": "SVERIGES RIKSBANK",
    "Address": "BRUNKEBERGSTORG 11",
    "City": "STOCKHOLM",
    "Branch": "INTERNAL TECH",
    "Postcode": "103 37",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "RIKS",
    "countryCode": "SE",
    "branchCode": "SWP",
    "SWIFT Code": "RIKSSESSSWP",
    "Bank Name": "SVERIGES RIKSBANK",
    "Address": "BRUNKEBERGSTORG 11",
    "City": "STOCKHOLM",
    "Branch": "INTERNAL TECH",
    "Postcode": "103 37",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "RIKS",
    "countryCode": "SE",
    "branchCode": "SWT",
    "SWIFT Code": "RIKSSESSSWT",
    "Bank Name": "SVERIGES RIKSBANK",
    "Address": "BRUNKEBERGSTORG 11",
    "City": "STOCKHOLM",
    "Branch": "INTERNAL TECH",
    "Postcode": "103 37",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "RIKS",
    "countryCode": "SE",
    "branchCode": "TST",
    "SWIFT Code": "RIKSSESSTST",
    "Bank Name": "SVERIGES RIKSBANK",
    "Address": "BRUNKEBERGSTORG 11",
    "City": "STOCKHOLM",
    "Branch": "RIKSBANKENS TESTBANK 1",
    "Postcode": "103 37",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "RIKS",
    "countryCode": "SE",
    "branchCode": "RIK",
    "SWIFT Code": "RIKSSESSRIK",
    "Bank Name": "SVERIGES RIKSBANK",
    "Address": "BRUNKEBERGSTORG 11",
    "City": "STOCKHOLM",
    "Branch": "RIKSBANKENS TESTBANK 2",
    "Postcode": "103 37",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "RIKS",
    "countryCode": "SE",
    "branchCode": "RBT",
    "SWIFT Code": "RIKSSESSRBT",
    "Bank Name": "SVERIGES RIKSBANK",
    "Address": "BRUNKEBERGSTORG 11",
    "City": "STOCKHOLM",
    "Branch": "RIKSBANKENS TESTBANK 3",
    "Postcode": "103 37",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "RIKS",
    "countryCode": "SE",
    "branchCode": "PRX",
    "SWIFT Code": "RIKSSESSPRX",
    "Bank Name": "SVERIGES RIKSBANK",
    "Address": "BRUNKEBERGSTORG 11",
    "City": "STOCKHOLM",
    "Branch": "RIKSBANKENS TESTBANK 4",
    "Postcode": "103 37",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "RIKS",
    "countryCode": "SE",
    "branchCode": "TBA",
    "SWIFT Code": "RIKSSESSTBA",
    "Bank Name": "SVERIGES RIKSBANK",
    "Address": "BRUNKEBERGSTORG 11",
    "City": "STOCKHOLM",
    "Branch": "RIKSBANKENS TESTBANK A",
    "Postcode": "103 37",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "RIKS",
    "countryCode": "SE",
    "branchCode": "TBB",
    "SWIFT Code": "RIKSSESSTBB",
    "Bank Name": "SVERIGES RIKSBANK",
    "Address": "BRUNKEBERGSTORG 11",
    "City": "STOCKHOLM",
    "Branch": "RIKSBANKENS TESTBANK B",
    "Postcode": "103 37",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "RIKS",
    "countryCode": "SE",
    "branchCode": "TBC",
    "SWIFT Code": "RIKSSESSTBC",
    "Bank Name": "SVERIGES RIKSBANK",
    "Address": "BRUNKEBERGSTORG 11",
    "City": "STOCKHOLM",
    "Branch": "RIKSBANKENS TESTBANK C",
    "Postcode": "103 37",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "RIKS",
    "countryCode": "SE",
    "branchCode": "BER",
    "SWIFT Code": "RIKSSESSBER",
    "Bank Name": "SVERIGES RIKSBANK",
    "Address": "BRUNKEBERGSTORG 11",
    "City": "STOCKHOLM",
    "Branch": "UTBILDNINGSBANK BERLIN",
    "Postcode": "103 37",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "RIKS",
    "countryCode": "SE",
    "branchCode": "LON",
    "SWIFT Code": "RIKSSESSLON",
    "Bank Name": "SVERIGES RIKSBANK",
    "Address": "BRUNKEBERGSTORG 11",
    "City": "STOCKHOLM",
    "Branch": "UTBILDNINGSBANK LONDON",
    "Postcode": "103 37",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "RIKS",
    "countryCode": "SE",
    "branchCode": "PAR",
    "SWIFT Code": "RIKSSESSPAR",
    "Bank Name": "SVERIGES RIKSBANK",
    "Address": "BRUNKEBERGSTORG 11",
    "City": "STOCKHOLM",
    "Branch": "UTBILDNINGSBANK PARIS",
    "Postcode": "103 37",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "RIKS",
    "countryCode": "SE",
    "branchCode": "ESR",
    "SWIFT Code": "RIKSSESR",
    "Bank Name": "SVERIGES RIKSBANK - RGTS",
    "Address": "BRUNKEBERGSTORG 11",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "103 37",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "RIKS",
    "countryCode": "SE",
    "branchCode": "RIX",
    "SWIFT Code": "RIKSSESRRIX",
    "Bank Name": "SVERIGES RIKSBANK - RGTS",
    "Address": "BRUNKEBERGSTORG 11",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "103 37",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "SWED",
    "countryCode": "SE",
    "branchCode": "CLS",
    "SWIFT Code": "SWEDSESSCLS",
    "Bank Name": "SWEDBANK AB (PUBL)",
    "Address": "LANDSVAGEN 40, SUNDBYBERG",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "105 34",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "SWED",
    "countryCode": "SE",
    "branchCode": "ESS",
    "SWIFT Code": "SWEDSESS",
    "Bank Name": "SWEDBANK AB (PUBL)",
    "Address": "LANDSVAGEN 40, SUNDBYBERG",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "105 34",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "AAFC",
    "countryCode": "SE",
    "branchCode": "EMM",
    "SWIFT Code": "AAFCSEMM",
    "Bank Name": "AARHUSKARLSHAMN FINANCE AB",
    "Address": "SKRIVAREGATAN 9",
    "City": "MALMO",
    "Branch": "",
    "Postcode": "215 32",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "LNDX",
    "countryCode": "SE",
    "branchCode": "EGG",
    "SWIFT Code": "LNDXSEGG",
    "Bank Name": "AB LINDEX",
    "Address": "",
    "City": "GOETEBORG",
    "Branch": "",
    "Postcode": "401 23",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "ABVO",
    "countryCode": "SE",
    "branchCode": "EGG",
    "SWIFT Code": "ABVOSEGG",
    "Bank Name": "AB VOLVO",
    "Address": "AMAZONVAGEN 1",
    "City": "GOTEBORG",
    "Branch": "",
    "Postcode": "405 08",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "AFAI",
    "countryCode": "SE",
    "branchCode": "ESS",
    "SWIFT Code": "AFAISESS",
    "Bank Name": "AFA FORSAKRING TJANSTEPENSIONS AB",
    "Address": "KLARA SODRA KYRKOGATA 18",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "106 27",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "AGNT",
    "countryCode": "SE",
    "branchCode": "ES2",
    "SWIFT Code": "AGNTSES2",
    "Bank Name": "AGENTA INVESTMENT MANAGEMENT AB",
    "Address": "KUNGSGATAN 3",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "111 43",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "BMPB",
    "countryCode": "SE",
    "branchCode": "ESS",
    "SWIFT Code": "BMPBSESS",
    "Bank Name": "AION BANK SA SWEDISH BRANCH",
    "Address": "KUNGSGATAN 64",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "111 22",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "AABA",
    "countryCode": "SE",
    "branchCode": "ESS",
    "SWIFT Code": "AABASESS",
    "Bank Name": "ALANDSBANKEN ABP (FINLAND),SVENSK FILIAL",
    "Address": "STUREPLAN 19",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "107 81",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "AABA",
    "countryCode": "SE",
    "branchCode": "TMS",
    "SWIFT Code": "AABASESSTMS",
    "Bank Name": "ALANDSBANKEN ABP (FINLAND),SVENSK FILIAL",
    "Address": "STUREPLAN 19",
    "City": "STOCKHOLM",
    "Branch": "TREASURY DEPARTMENT",
    "Postcode": "107 81",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "ALTA",
    "countryCode": "SE",
    "branchCode": "ESS",
    "SWIFT Code": "ALTASESS",
    "Bank Name": "ALECTA PENSIONSFORSAKRING OMSESIDIGT",
    "Address": "REGERINGSGATAN 107",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "103 73",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "ALYN",
    "countryCode": "SE",
    "branchCode": "E22",
    "SWIFT Code": "ALYNSE22",
    "Bank Name": "ALFA LAVAL TREASURY INTERNATIONAL AB (PUBL)",
    "Address": "RUDEBOKSVAGEN 1",
    "City": "LUND",
    "Branch": "",
    "Postcode": "221 00",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "ALYN",
    "countryCode": "SE",
    "branchCode": "E2L",
    "SWIFT Code": "ALYNSE2L",
    "Bank Name": "ALFA LAVAL TREASURY INTERNATIONAL AB (PUBL)",
    "Address": "RUDEBOKSVAGEN 1",
    "City": "LUND",
    "Branch": "",
    "Postcode": "221 00",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "SMTA",
    "countryCode": "SE",
    "branchCode": "E22",
    "SWIFT Code": "SMTASE22",
    "Bank Name": "ALLEIMA TREASURY AB",
    "Address": "STORGATAN 2",
    "City": "SANDVIKEN",
    "Branch": "",
    "Postcode": "811 81",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "AEEF",
    "countryCode": "SE",
    "branchCode": "EG2",
    "SWIFT Code": "AEEFSEG2",
    "Bank Name": "AMAL EXPRESS EKONOMISK FORENING",
    "Address": "GENERALSGATAN 7, FLOOR 3",
    "City": "GOTEBORG",
    "Branch": "",
    "Postcode": "415 05",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "OUBI",
    "countryCode": "SE",
    "branchCode": "E22",
    "SWIFT Code": "OUBISE22",
    "Bank Name": "ARELION AB",
    "Address": "STJARNTORGET 1",
    "City": "SOLNA",
    "Branch": "",
    "Postcode": "169 94",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "AAFE",
    "countryCode": "SE",
    "branchCode": "ES2",
    "SWIFT Code": "AAFESES2",
    "Bank Name": "ASSA ABLOY FINANCIAL SERVICES AB",
    "Address": "KLARABERGSVIADUKTEN 90",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "107 23",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "ATLP",
    "countryCode": "SE",
    "branchCode": "ES2",
    "SWIFT Code": "ATLPSES2",
    "Bank Name": "ATLAS COPCO AB",
    "Address": "SICKLA INDUSTRIVAG 19",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "105 23",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "ATLP",
    "countryCode": "SE",
    "branchCode": "ESS",
    "SWIFT Code": "ATLPSESS",
    "Bank Name": "ATLAS COPCO AB",
    "Address": "SICKLA INDUSTRIVAG 19",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "105 23",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "AUTB",
    "countryCode": "SE",
    "branchCode": "ESS",
    "SWIFT Code": "AUTBSESS",
    "Bank Name": "AUTOLIV AKTIEBOLAG",
    "Address": "KLARABERGSVIADUKTEN 70, B7",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "111 64",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "AVAN",
    "countryCode": "SE",
    "branchCode": "ESX",
    "SWIFT Code": "AVANSESX",
    "Bank Name": "AVANZA BANK AB",
    "Address": "REGERINGGSGATAN 103",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "111 39",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "BFIU",
    "countryCode": "SE",
    "branchCode": "ES2",
    "SWIFT Code": "BFIUSES2",
    "Bank Name": "BAMBU FUND INTERNATIONAL TRUST KOMMANDITBOLAG",
    "Address": "DRONNINGENS GADE",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "BKCH",
    "countryCode": "SE",
    "branchCode": "ESS",
    "SWIFT Code": "BKCHSESS",
    "Bank Name": "BANK OF CHINA (EUROPE) S.A. STOCKHOLM BRANCH",
    "Address": "TEGELUDDSVAGEN 21",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "115 41",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "BGAB",
    "countryCode": "SE",
    "branchCode": "ESG",
    "SWIFT Code": "BGABSESG",
    "Bank Name": "BANKGIROCENTRALEN BGC AB",
    "Address": "MEJERIVAGEN 1",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "105 19",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "BGAB",
    "countryCode": "SE",
    "branchCode": "ESS",
    "SWIFT Code": "BGABSESS",
    "Bank Name": "BANKGIROCENTRALEN BGC AB",
    "Address": "MEJERIVAGEN 1",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "105 19",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "BGAB",
    "countryCode": "SE",
    "branchCode": "MUL",
    "SWIFT Code": "BGABSESSMUL",
    "Bank Name": "BANKGIROCENTRALEN BGC AB",
    "Address": "PALMFELTSVAGEN 5A",
    "City": "STOCKHOLM",
    "Branch": "MULTILATERAL SETTLEMENT",
    "Postcode": "105 19",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "BKAB",
    "countryCode": "SE",
    "branchCode": "E22",
    "SWIFT Code": "BKABSE22",
    "Bank Name": "BILLERUD AB",
    "Address": "EVENEMANGSGATAN 17, FLOOR 3",
    "City": "SOLNA",
    "Branch": "",
    "Postcode": "169 79",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "BSTP",
    "countryCode": "SE",
    "branchCode": "ESS",
    "SWIFT Code": "BSTPSESS",
    "Bank Name": "BLUESTEP BANK AB",
    "Address": "SVEAVAGEN 163",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "104 35",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "FTSB",
    "countryCode": "SE",
    "branchCode": "ESS",
    "SWIFT Code": "FTSBSESS",
    "Bank Name": "BNP PARIBAS S.A., BANKFILIAL SVERIGE",
    "Address": "HOVSLAGARGATAN 3",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "103 96",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "BRTE",
    "countryCode": "SE",
    "branchCode": "ESS",
    "SWIFT Code": "BRTESESS",
    "Bank Name": "BRITE AB",
    "Address": "LINNEGATAN 5",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "114 47",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "CCTK",
    "countryCode": "SE",
    "branchCode": "E22",
    "SWIFT Code": "CCTKSE22",
    "Bank Name": "CAB CAPITAL TRUST KOMMANDITBOLAG",
    "Address": "SVETSARVAEGEN 15, 2TR",
    "City": "SOLNA",
    "Branch": "",
    "Postcode": "171 41",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "CFNN",
    "countryCode": "SE",
    "branchCode": "ESS",
    "SWIFT Code": "CFNNSESS",
    "Bank Name": "CARNEGIE FONDER AB",
    "Address": "REGERINGSGATAN 56",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "103 97",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "CARN",
    "countryCode": "SE",
    "branchCode": "ES2",
    "SWIFT Code": "CARNSES2",
    "Bank Name": "CARNEGIE INVESTMENT BANK AB",
    "Address": "REGERINGSGATAN 56",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "103 38",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "CITI",
    "countryCode": "SE",
    "branchCode": "ESX",
    "SWIFT Code": "CITISESX",
    "Bank Name": "CITIBANK EUROPE PLC SWEDEN BRANCH",
    "Address": "",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "111 84",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "BSUI",
    "countryCode": "SE",
    "branchCode": "ESS",
    "SWIFT Code": "BSUISESS",
    "Bank Name": "CREDIT AGRICOLE CIB SWEDEN BRANCH",
    "Address": "REGERINGSGATAN 38",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "103 95",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "DABA",
    "countryCode": "SE",
    "branchCode": "GBG",
    "SWIFT Code": "DABASESXGBG",
    "Bank Name": "DANSKE BANK",
    "Address": "OESTRA HAMNGATAN 13",
    "City": "GOTEBORG",
    "Branch": "TRADE FINANCE, GOTHENBURG",
    "Postcode": "404 22",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "DABA",
    "countryCode": "SE",
    "branchCode": "ESX",
    "SWIFT Code": "DABASESX",
    "Bank Name": "DANSKE BANK",
    "Address": "NORRMALMSTORG 1",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "103 92",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "DABA",
    "countryCode": "SE",
    "branchCode": "CLS",
    "SWIFT Code": "DABASESXCLS",
    "Bank Name": "DANSKE BANK",
    "Address": "STUREPLAN 13",
    "City": "STOCKHOLM",
    "Branch": "CLS SERVICES",
    "Postcode": "111 45",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "DABA",
    "countryCode": "SE",
    "branchCode": "CON",
    "SWIFT Code": "DABASESXCON",
    "Bank Name": "DANSKE BANK",
    "Address": "NORRMALMSTORG 1",
    "City": "STOCKHOLM",
    "Branch": "DANSKE CONCENSUS",
    "Postcode": "103 92",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "DABA",
    "countryCode": "SE",
    "branchCode": "INS",
    "SWIFT Code": "DABASESXINS",
    "Bank Name": "DANSKE BANK",
    "Address": "NORRMALMSTORG 1",
    "City": "STOCKHOLM",
    "Branch": "TECHNICAL ADDRESS INSTANT",
    "Postcode": "103 92",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "DABA",
    "countryCode": "SE",
    "branchCode": "SWI",
    "SWIFT Code": "DABASESXSWI",
    "Bank Name": "DANSKE BANK",
    "Address": "NORRMALMSTORG 1",
    "City": "STOCKHOLM",
    "Branch": "TECHNICAL ADDRESS TIPS",
    "Postcode": "103 92",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "DABA",
    "countryCode": "SE",
    "branchCode": "TIP",
    "SWIFT Code": "DABASESXTIP",
    "Bank Name": "DANSKE BANK",
    "Address": "NORRMALMSTORG 1",
    "City": "STOCKHOLM",
    "Branch": "TECHNICAL ADDRESS TIPS",
    "Postcode": "103 92",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "DABA",
    "countryCode": "SE",
    "branchCode": "STO",
    "SWIFT Code": "DABASESXSTO",
    "Bank Name": "DANSKE BANK",
    "Address": "NORRMALMSTORG 1",
    "City": "STOCKHOLM",
    "Branch": "TRADE FINANCE, STOCKHOLM",
    "Postcode": "103 92",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "DNBA",
    "countryCode": "SE",
    "branchCode": "ESX",
    "SWIFT Code": "DNBASESX",
    "Bank Name": "DNB BANK ASA, FILIAL SVERIGE",
    "Address": "REGERINGSGATAN 59",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "105 88",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "DNBA",
    "countryCode": "SE",
    "branchCode": "CLS",
    "SWIFT Code": "DNBASESXCLS",
    "Bank Name": "DNB BANK ASA, FILIAL SVERIGE",
    "Address": "",
    "City": "STOCKHOLM",
    "Branch": "CLS NOSTRO AGENT CONTROL BRANCH",
    "Postcode": "",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "EKML",
    "countryCode": "SE",
    "branchCode": "E2S",
    "SWIFT Code": "EKMLSE2S",
    "Bank Name": "EKOBANKEN MEDLEMSBANK",
    "Address": "SKAVE MAGASIN 9, FLOOR 2, JARNA",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "153 31",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "ELKT",
    "countryCode": "SE",
    "branchCode": "ESS",
    "SWIFT Code": "ELKTSESS",
    "Bank Name": "ELEKTA AB",
    "Address": "KUNGSTENSGATAN 18",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "113 57",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "EPRC",
    "countryCode": "SE",
    "branchCode": "E22",
    "SWIFT Code": "EPRCSE22",
    "Bank Name": "EPIROC AB",
    "Address": "SICKLA INDUSTRIVAG 19",
    "City": "NACKA",
    "Branch": "",
    "Postcode": "131 54",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "EQTS",
    "countryCode": "SE",
    "branchCode": "ESS",
    "SWIFT Code": "EQTSSESS",
    "Bank Name": "EQT AB",
    "Address": "REGERINGSGATAN 25",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "111 53",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "ERPF",
    "countryCode": "SE",
    "branchCode": "ES2",
    "SWIFT Code": "ERPFSES2",
    "Bank Name": "ERIK PENSER BANK AB",
    "Address": "APELBERGSGATAN 27",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "103 91",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "ETRY",
    "countryCode": "SE",
    "branchCode": "ESS",
    "SWIFT Code": "ETRYSESS",
    "Bank Name": "ESSITY TREASURY AB",
    "Address": "KLARABERGSVIADUKTEN 63",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "111 64",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "VPCS",
    "countryCode": "SE",
    "branchCode": "CLP",
    "SWIFT Code": "VPCSSESSCLP",
    "Bank Name": "EUROCLEAR SWEDEN AB",
    "Address": "",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "NDEA",
    "countryCode": "SE",
    "branchCode": "EGG",
    "SWIFT Code": "NDEASEGG",
    "Bank Name": "NORDEA BANK ABP, FILIAL I SVERIGE",
    "Address": "OESTRA HAMNGATAN 16",
    "City": "GOTEBORG",
    "Branch": "",
    "Postcode": "405 09",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "NDEA",
    "countryCode": "SE",
    "branchCode": "NCL",
    "SWIFT Code": "NDEASESSNCL",
    "Bank Name": "NORDEA BANK ABP, FILIAL I SVERIGE",
    "Address": "",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "NDEA",
    "countryCode": "SE",
    "branchCode": "RCC",
    "SWIFT Code": "NDEASESSRCC",
    "Bank Name": "NORDEA BANK ABP, FILIAL I SVERIGE",
    "Address": "",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "NDEA",
    "countryCode": "SE",
    "branchCode": "ESS",
    "SWIFT Code": "NDEASESS",
    "Bank Name": "NORDEA BANK ABP, FILIAL I SVERIGE",
    "Address": "HAMNGATAN 10",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "105 71",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "NDEA",
    "countryCode": "SE",
    "branchCode": "FDS",
    "SWIFT Code": "NDEASESSFDS",
    "Bank Name": "NORDEA BANK ABP, FILIAL I SVERIGE",
    "Address": "",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "NDEA",
    "countryCode": "SE",
    "branchCode": "TRI",
    "SWIFT Code": "NDEASESSTRI",
    "Bank Name": "NORDEA BANK ABP, FILIAL I SVERIGE",
    "Address": "HAMNGATAN 10",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "105 71",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "NDEA",
    "countryCode": "SE",
    "branchCode": "INS",
    "SWIFT Code": "NDEASESSINS",
    "Bank Name": "NORDEA BANK ABP, FILIAL I SVERIGE",
    "Address": "HAMNGATAN 10",
    "City": "STOCKHOLM",
    "Branch": "INSTANT PAYMENTS",
    "Postcode": "105 71",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "NDEA",
    "countryCode": "SE",
    "branchCode": "NBM",
    "SWIFT Code": "NDEASESSNBM",
    "Bank Name": "NORDEA BANK ABP, FILIAL I SVERIGE",
    "Address": "",
    "City": "STOCKHOLM",
    "Branch": "NORDEA BANK MARKETS",
    "Postcode": "",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "NDEA",
    "countryCode": "SE",
    "branchCode": "PGI",
    "SWIFT Code": "NDEASESSPGI",
    "Bank Name": "NORDEA BANK ABP, FILIAL I SVERIGE",
    "Address": "HAMNGATAN 10",
    "City": "STOCKHOLM",
    "Branch": "PLUSGIROT",
    "Postcode": "105 71",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "NOLS",
    "countryCode": "SE",
    "branchCode": "910",
    "SWIFT Code": "NOLSSES2910",
    "Bank Name": "NORDEA LIVFORSAKRING SVERIGE AB",
    "Address": "M4460",
    "City": "STOCKHOLM",
    "Branch": "EKONOMIAVDELNINGEN",
    "Postcode": "",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "NOLS",
    "countryCode": "SE",
    "branchCode": "911",
    "SWIFT Code": "NOLSSES2911",
    "Bank Name": "NORDEA LIVFORSAKRING SVERIGE AB",
    "Address": "M4460",
    "City": "STOCKHOLM",
    "Branch": "EKONOMIAVDELNINGEN",
    "Postcode": "",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "NOLS",
    "countryCode": "SE",
    "branchCode": "913",
    "SWIFT Code": "NOLSSES2913",
    "Bank Name": "NORDEA LIVFORSAKRING SVERIGE AB",
    "Address": "M4460",
    "City": "STOCKHOLM",
    "Branch": "EKONOMIAVDELNINGEN",
    "Postcode": "",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "NOLS",
    "countryCode": "SE",
    "branchCode": "G10",
    "SWIFT Code": "NOLSSES2G10",
    "Bank Name": "NORDEA LIVFORSAKRING SVERIGE AB",
    "Address": "M4460",
    "City": "STOCKHOLM",
    "Branch": "EKONOMIAVDELNINGEN",
    "Postcode": "",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "NOLS",
    "countryCode": "SE",
    "branchCode": "G11",
    "SWIFT Code": "NOLSSES2G11",
    "Bank Name": "NORDEA LIVFORSAKRING SVERIGE AB",
    "Address": "M4460",
    "City": "STOCKHOLM",
    "Branch": "EKONOMIAVDELNINGEN",
    "Postcode": "",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "NOLS",
    "countryCode": "SE",
    "branchCode": "G12",
    "SWIFT Code": "NOLSSES2G12",
    "Bank Name": "NORDEA LIVFORSAKRING SVERIGE AB",
    "Address": "M4460",
    "City": "STOCKHOLM",
    "Branch": "EKONOMIAVDELNINGEN",
    "Postcode": "",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "NOLS",
    "countryCode": "SE",
    "branchCode": "G13",
    "SWIFT Code": "NOLSSES2G13",
    "Bank Name": "NORDEA LIVFORSAKRING SVERIGE AB",
    "Address": "M4460",
    "City": "STOCKHOLM",
    "Branch": "EKONOMIAVDELNINGEN",
    "Postcode": "",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "NOLS",
    "countryCode": "SE",
    "branchCode": "G14",
    "SWIFT Code": "NOLSSES2G14",
    "Bank Name": "NORDEA LIVFORSAKRING SVERIGE AB",
    "Address": "M4460",
    "City": "STOCKHOLM",
    "Branch": "EKONOMIAVDELNINGEN",
    "Postcode": "",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "NOLS",
    "countryCode": "SE",
    "branchCode": "W95",
    "SWIFT Code": "NOLSSES2W95",
    "Bank Name": "NORDEA LIVFORSAKRING SVERIGE AB",
    "Address": "M4460",
    "City": "STOCKHOLM",
    "Branch": "EKONOMIAVDELNINGEN",
    "Postcode": "",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "NOLS",
    "countryCode": "SE",
    "branchCode": "W96",
    "SWIFT Code": "NOLSSES2W96",
    "Bank Name": "NORDEA LIVFORSAKRING SVERIGE AB",
    "Address": "M4460",
    "City": "STOCKHOLM",
    "Branch": "EKONOMIAVDELNINGEN",
    "Postcode": "",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "NOLS",
    "countryCode": "SE",
    "branchCode": "ES2",
    "SWIFT Code": "NOLSSES2",
    "Bank Name": "NORDEA LIVFORSAKRING SVERIGE AB",
    "Address": "M4460",
    "City": "STOCKHOLM",
    "Branch": "EKONOMIAVDELNINGEN",
    "Postcode": "",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "NOLS",
    "countryCode": "SE",
    "branchCode": "491",
    "SWIFT Code": "NOLSSES2491",
    "Bank Name": "NORDEA LIVFORSAKRING SVERIGE AB",
    "Address": "M4460",
    "City": "STOCKHOLM",
    "Branch": "EKONOMIAVDELNINGEN",
    "Postcode": "",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "NOLS",
    "countryCode": "SE",
    "branchCode": "A96",
    "SWIFT Code": "NOLSSES2A96",
    "Bank Name": "NORDEA LIVFORSAKRING SVERIGE AB",
    "Address": "M4460",
    "City": "STOCKHOLM",
    "Branch": "EKONOMIAVDELNINGEN",
    "Postcode": "",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "NOLS",
    "countryCode": "SE",
    "branchCode": "E47",
    "SWIFT Code": "NOLSSES2E47",
    "Bank Name": "NORDEA LIVFORSAKRING SVERIGE AB",
    "Address": "M4460",
    "City": "STOCKHOLM",
    "Branch": "EKONOMIAVDELNINGEN",
    "Postcode": "",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "NOLS",
    "countryCode": "SE",
    "branchCode": "E48",
    "SWIFT Code": "NOLSSES2E48",
    "Bank Name": "NORDEA LIVFORSAKRING SVERIGE AB",
    "Address": "M4460",
    "City": "STOCKHOLM",
    "Branch": "EKONOMIAVDELNINGEN",
    "Postcode": "",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "NOLS",
    "countryCode": "SE",
    "branchCode": "E49",
    "SWIFT Code": "NOLSSES2E49",
    "Bank Name": "NORDEA LIVFORSAKRING SVERIGE AB",
    "Address": "M4460",
    "City": "STOCKHOLM",
    "Branch": "EKONOMIAVDELNINGEN",
    "Postcode": "",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "NPCO",
    "countryCode": "SE",
    "branchCode": "ES2",
    "SWIFT Code": "NPCOSES2",
    "Bank Name": "NORDIC PAYMENTS COUNCIL",
    "Address": "",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "103 94",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "NNSE",
    "countryCode": "SE",
    "branchCode": "E22",
    "SWIFT Code": "NNSESE22",
    "Bank Name": "NORDNET BANK AB",
    "Address": "",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "104 25",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "NOHL",
    "countryCode": "SE",
    "branchCode": "ESS",
    "SWIFT Code": "NOHLSESS",
    "Bank Name": "NORTHMILL BANK",
    "Address": "REGERINGSGATAN 20",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "111 53",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "NOHL",
    "countryCode": "SE",
    "branchCode": "IXX",
    "SWIFT Code": "NOHLSESSIXX",
    "Bank Name": "NORTHMILL BANK",
    "Address": "REGERINGSGATAN 20",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "111 53",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "OPST",
    "countryCode": "SE",
    "branchCode": "ES2",
    "SWIFT Code": "OPSTSES2",
    "Bank Name": "OPPENHEIM SAVINGS AND LOANS TRUST KB",
    "Address": "KARLAVAGEN 18",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "114 31",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "OHMJ",
    "countryCode": "SE",
    "branchCode": "ESS",
    "SWIFT Code": "OHMJSESS",
    "Bank Name": "PARETO SECURITIES AB",
    "Address": "BERZELI PARK 9",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "103 91",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "RESU",
    "countryCode": "SE",
    "branchCode": "E2H",
    "SWIFT Code": "RESUSE2H",
    "Bank Name": "RESURS BANK AB",
    "Address": "",
    "City": "HELSINGBORG",
    "Branch": "",
    "Postcode": "",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "RILU",
    "countryCode": "SE",
    "branchCode": "ES2",
    "SWIFT Code": "RILUSES2",
    "Bank Name": "RIGEL LUMINOUS KB",
    "Address": "STOCKHOLMS BREVBOXAR 337",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "116 74",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "AABB",
    "countryCode": "SE",
    "branchCode": "E22",
    "SWIFT Code": "AABBSE22",
    "Bank Name": "SAAB AB",
    "Address": "BRODERNA UGGLAS GATA H 209, 1, FLOOR 2",
    "City": "LINKOPING",
    "Branch": "",
    "Postcode": "582 54",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "SNDV",
    "countryCode": "SE",
    "branchCode": "E22",
    "SWIFT Code": "SNDVSE22",
    "Bank Name": "SANDVIK AB",
    "Address": "KUNGSBRON 1, ENTRANCE G , FLOOR 6",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "111 22",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "SVTR",
    "countryCode": "SE",
    "branchCode": "ESS",
    "SWIFT Code": "SVTRSESS",
    "Bank Name": "SANDVIK TREASURY AB",
    "Address": "KUNGSBRON 1, WORLD TRADE CENTER, FLOOR 6",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "101 30",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "BSNO",
    "countryCode": "SE",
    "branchCode": "ESS",
    "SWIFT Code": "BSNOSESS",
    "Bank Name": "SANTANDER CONSUMER BANK AS NORGE, SVERIGE FILIAL",
    "Address": "HEMVARNSGATAN 9",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "171 75",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "SBAV",
    "countryCode": "SE",
    "branchCode": "ESS",
    "SWIFT Code": "SBAVSESS",
    "Bank Name": "SBAB",
    "Address": "SVETSARVAEGEN 24",
    "City": "SOLNA",
    "Branch": "",
    "Postcode": "171 41",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "SSLT",
    "countryCode": "SE",
    "branchCode": "E22",
    "SWIFT Code": "SSLTSE22",
    "Bank Name": "SCANDINAVIAN SAVINGS AND LOANS TRUST KOMMANDITBOLAG",
    "Address": "STOCKHOLMS BREVBOXAR 1904",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "116 74",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "SCNN",
    "countryCode": "SE",
    "branchCode": "E23",
    "SWIFT Code": "SCNNSE23",
    "Bank Name": "SCANIA CV AB",
    "Address": "VAGNMAKARVAGEN 1, CK2-2, FLOOR 2",
    "City": "SODERTALJE",
    "Branch": "",
    "Postcode": "151 87",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "SCDR",
    "countryCode": "SE",
    "branchCode": "EMM",
    "SWIFT Code": "SCDRSEMM",
    "Bank Name": "SECURITAS DIRECT AB",
    "Address": "ANGBATSBRON 1",
    "City": "MALMO",
    "Branch": "",
    "Postcode": "211 20",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "SJAF",
    "countryCode": "SE",
    "branchCode": "EG2",
    "SWIFT Code": "SJAFSEG2",
    "Bank Name": "SJATTE AP-FONDEN",
    "Address": "KOPMANSGATAN 32",
    "City": "GOTHENBURG",
    "Branch": "",
    "Postcode": "411 06",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "SKIA",
    "countryCode": "SE",
    "branchCode": "ESS",
    "SWIFT Code": "SKIASESS",
    "Bank Name": "SKANDIABANKEN",
    "Address": "LINDHAGENSGATAN 86",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "106 55",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "ESSE",
    "countryCode": "SE",
    "branchCode": "ESG",
    "SWIFT Code": "ESSESESG",
    "Bank Name": "SKANDINAVISKA ENSKILDA BANKEN",
    "Address": "OESTRA HAMNGATAN 24",
    "City": "GOTEBORG",
    "Branch": "",
    "Postcode": "405 04",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "ESSE",
    "countryCode": "SE",
    "branchCode": "ESM",
    "SWIFT Code": "ESSESESM",
    "Bank Name": "SKANDINAVISKA ENSKILDA BANKEN",
    "Address": "OESTERGATAN 39",
    "City": "MALMO",
    "Branch": "",
    "Postcode": "205 20",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "ESSE",
    "countryCode": "SE",
    "branchCode": "ESS",
    "SWIFT Code": "ESSESESS",
    "Bank Name": "SKANDINAVISKA ENSKILDA BANKEN AB",
    "Address": "STJARNTORGET 4",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "106 40",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "ESSE",
    "countryCode": "SE",
    "branchCode": "CLS",
    "SWIFT Code": "ESSESESSCLS",
    "Bank Name": "SKANDINAVISKA ENSKILDA BANKEN AB",
    "Address": "",
    "City": "STOCKHOLM",
    "Branch": "",
    "Postcode": "106 40",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "ESSE",
    "countryCode": "SE",
    "branchCode": "CAL",
    "SWIFT Code": "ESSESESSCAL",
    "Bank Name": "SKANDINAVISKA ENSKILDA BANKEN AB",
    "Address": "",
    "City": "STOCKHOLM",
    "Branch": "CALYPSO BRANCH CODE",
    "Postcode": "",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "ESSE",
    "countryCode": "SE",
    "branchCode": "PCS",
    "SWIFT Code": "ESSESESSPCS",
    "Bank Name": "SKANDINAVISKA ENSKILDA BANKEN AB",
    "Address": "RISSNELEDEN 110",
    "City": "STOCKHOLM",
    "Branch": "COLLATERAL",
    "Postcode": "106 40",
    "Country": "Sweden",
    "Connection": "Active"
  },
  {
    "bankCode": "ESSE",
    "countryCode": "SE",
    "branchCode": "CCS",
    "SWIFT Code": "ESSESESSCCS",
    "Bank Name": "SKANDINAVISKA ENSKILDA BANKEN AB",
    "Address": "STJARNTORGET 4",
    "City": "STOCKHOLM",
    "Branch": "CUSTODY CORE SECURITIES",
    "Postcode": "106 40",
    "Country": "Sweden",
    "Connection": "Active"
  }
]
module.exports = sweden
