const tajikistan = [
  {
    "bankCode": "ACTJ",
    "countryCode": "TJ",
    "branchCode": "J22",
    "SWIFT Code": "ACTJTJ22",
    "Bank Name": "ACCESSBANK TAJIKISTAN",
    "Address": "FIRDAVSII 61/1",
    "City": "DUSHANBE",
    "Branch": "",
    "Postcode": "734061",
    "Country": "Tajikistan",
    "Connection": "Active"
  },
  {},
  {
    "bankCode": "ARUN",
    "countryCode": "TJ",
    "branchCode": "J22",
    "SWIFT Code": "ARUNTJ22",
    "Bank Name": "ARGUN",
    "Address": "FOTEH NIYOZI 32",
    "City": "DUSHANBE",
    "Branch": "",
    "Postcode": "734000",
    "Country": "Tajikistan",
    "Connection": "Active"
  },
  {
    "bankCode": "BRTA",
    "countryCode": "TJ",
    "branchCode": "J22",
    "SWIFT Code": "BRTATJ22",
    "Bank Name": "CJSC 'BONKI RUSHDI TOJIKISTON'",
    "Address": "PUSHKINA 20, BONKI RUSHDI TOJIKISTON",
    "City": "DUSHANBE",
    "Branch": "",
    "Postcode": "734025",
    "Country": "Tajikistan",
    "Connection": "Active"
  },
  {
    "bankCode": "KZKO",
    "countryCode": "TJ",
    "branchCode": "J22",
    "SWIFT Code": "KZKOTJ22",
    "Bank Name": "CJSC ACTIV BANK",
    "Address": "AYNI 42 A, 2",
    "City": "DUSHANBE",
    "Branch": "",
    "Postcode": "734012",
    "Country": "Tajikistan",
    "Connection": "Active"
  },
  {
    "bankCode": "ARVD",
    "countryCode": "TJ",
    "branchCode": "J22",
    "SWIFT Code": "ARVDTJ22",
    "Bank Name": "CJSC BANK ARVAND",
    "Address": "I. SOMONI AVENUE 1A",
    "City": "KHUJAND",
    "Branch": "",
    "Postcode": "735700",
    "Country": "Tajikistan",
    "Connection": "Active"
  },
  {
    "bankCode": "IBTK",
    "countryCode": "TJ",
    "branchCode": "J22",
    "SWIFT Code": "IBTKTJ22",
    "Bank Name": "CJSC INTERNATIONAL BANK OF TAJIKISTAN",
    "Address": "BUKHORO STREET 27, SHOHMANSUR DISTRICT",
    "City": "DUSHANBE",
    "Branch": "",
    "Postcode": "734000",
    "Country": "Tajikistan",
    "Connection": "Active"
  },
  {
    "bankCode": "NABW",
    "countryCode": "TJ",
    "branchCode": "J22",
    "SWIFT Code": "NABWTJ22",
    "Bank Name": "CJSC MDO 'IMON INTERNATIONAL'",
    "Address": "17, MICRODISTRICT 2",
    "City": "KHUJAND",
    "Branch": "",
    "Postcode": "735700",
    "Country": "Tajikistan",
    "Connection": "Active"
  },
  {
    "bankCode": "HUMO",
    "countryCode": "TJ",
    "branchCode": "J22",
    "SWIFT Code": "HUMOTJ22",
    "Bank Name": "CJSC MICROCREDIT DEPOSIT ORGANIZATION HUMO",
    "Address": "N. KARABOEV 148/1",
    "City": "DUSHANBE",
    "Branch": "",
    "Postcode": "734061",
    "Country": "Tajikistan",
    "Connection": "Active"
  },
  {
    "bankCode": "SPRB",
    "countryCode": "TJ",
    "branchCode": "J22",
    "SWIFT Code": "SPRBTJ22",
    "Bank Name": "CJSC SPITAMEN BANK",
    "Address": "SHAMSI STREET 4",
    "City": "DUSHANBE",
    "Branch": "",
    "Postcode": "734064",
    "Country": "Tajikistan",
    "Connection": "Active"
  },
  {
    "bankCode": "LCMD",
    "countryCode": "TJ",
    "branchCode": "J22",
    "SWIFT Code": "LCMDTJ22",
    "Bank Name": "CLOSED JOINT STOCK COMPANY DUSHANBE CITY BANK",
    "Address": "SOKHILI STR. 5",
    "City": "DUSHANBE",
    "Branch": "",
    "Postcode": "734001",
    "Country": "Tajikistan",
    "Connection": "Active"
  },
  {
    "bankCode": "EJSA",
    "countryCode": "TJ",
    "branchCode": "J22",
    "SWIFT Code": "EJSATJ22",
    "Bank Name": "ESKHATA BANK OPENED JOINT STOCK COMPANY",
    "Address": "GAGARIN 135",
    "City": "KHUJAND",
    "Branch": "",
    "Postcode": "735712",
    "Country": "Tajikistan",
    "Connection": "Active"
  },
  {
    "bankCode": "MDMA",
    "countryCode": "TJ",
    "branchCode": "J22",
    "SWIFT Code": "MDMATJ22",
    "Bank Name": "LIMITED LIABILITY COMPANY MICROCREDIT DEPOSIT ORGANIZATION 'MATIN' (LLC MDO MATIN)",
    "Address": "SHARQ 84, FLOOR 2",
    "City": "KHUJAND",
    "Branch": "",
    "Postcode": "735700",
    "Country": "Tajikistan",
    "Connection": "Active"
  },
  {
    "bankCode": "LCOC",
    "countryCode": "TJ",
    "branchCode": "J22",
    "SWIFT Code": "LCOCTJ22",
    "Bank Name": "LIMITED LIABILITY COMPANY NONBANKING CREDIT  ORGANIZATION 'VASL'",
    "Address": "MOYONSHO NAZARSHOEV STR. 80, FLOOR 1",
    "City": "DUSHANBE",
    "Branch": "",
    "Postcode": "734012",
    "Country": "Tajikistan",
    "Connection": "Active"
  },
  {},
  {
    "bankCode": "LMMS",
    "countryCode": "TJ",
    "branchCode": "J22",
    "SWIFT Code": "LMMSTJ22",
    "Bank Name": "LLC MDO EMIN SARMOYA",
    "Address": "GAFUROVA STREET 21, FLOOR 1",
    "City": "DUSHANBE",
    "Branch": "",
    "Postcode": "734064",
    "Country": "Tajikistan",
    "Connection": "Active"
  },
  {
    "bankCode": "SRVT",
    "countryCode": "TJ",
    "branchCode": "J22",
    "SWIFT Code": "SRVTTJ22",
    "Bank Name": "LLC MDO SARVAT",
    "Address": "SOVIETSKAYA STR 18",
    "City": "DUSHANBE",
    "Branch": "",
    "Postcode": "734001",
    "Country": "Tajikistan",
    "Connection": "Active"
  },
  {
    "bankCode": "BRKT",
    "countryCode": "TJ",
    "branchCode": "J22",
    "SWIFT Code": "BRKTTJ22",
    "Bank Name": "LLC MICROCREDIT DEPOSIT ORGANIZATIO N BARAKAT",
    "Address": "J. RASULOV STREET 9",
    "City": "DUSHANBE",
    "Branch": "",
    "Postcode": "734060",
    "Country": "Tajikistan",
    "Connection": "Active"
  },
  {
    "bankCode": "NATJ",
    "countryCode": "TJ",
    "branchCode": "FIN",
    "SWIFT Code": "NATJTJ22FIN",
    "Bank Name": "NATIONAL BANK OF TAJIKISTAN",
    "Address": "RUDAKI AVENUE 38/1",
    "City": "DUSHANBE",
    "Branch": "",
    "Postcode": "734025",
    "Country": "Tajikistan",
    "Connection": "Active"
  },
  {
    "bankCode": "NATJ",
    "countryCode": "TJ",
    "branchCode": "J22",
    "SWIFT Code": "NATJTJ22",
    "Bank Name": "NATIONAL BANK OF TAJIKISTAN",
    "Address": "RUDAKI AVENUE 38/1",
    "City": "DUSHANBE",
    "Branch": "",
    "Postcode": "734025",
    "Country": "Tajikistan",
    "Connection": "Active"
  },
  {
    "bankCode": "CBTF",
    "countryCode": "TJ",
    "branchCode": "J22",
    "SWIFT Code": "CBTFTJ22",
    "Bank Name": "OJSC COMMERCE BANK OF TAJIKISTAN",
    "Address": "J. RASULOF STREET 10, SINO DISTRICT",
    "City": "DUSHANBE",
    "Branch": "",
    "Postcode": "734000",
    "Country": "Tajikistan",
    "Connection": "Active"
  },
  {
    "bankCode": "SOHB",
    "countryCode": "TJ",
    "branchCode": "J22",
    "SWIFT Code": "SOHBTJ22",
    "Bank Name": "OPEN JOINT-STOCK COMPANY 'TAWHIDBANK'",
    "Address": "N. MUHAMMAD STR. 10/17",
    "City": "DUSHANBE",
    "Branch": "",
    "Postcode": "734012",
    "Country": "Tajikistan",
    "Connection": "Active"
  },
  {
    "bankCode": "OTJK",
    "countryCode": "TJ",
    "branchCode": "J22",
    "SWIFT Code": "OTJKTJ22",
    "Bank Name": "ORIENBANK, OPEN JOINT STOCK COMPANY",
    "Address": "RUDAKI AVENUE 95/1",
    "City": "DUSHANBE",
    "Branch": "",
    "Postcode": "734001",
    "Country": "Tajikistan",
    "Connection": "Active"
  },
  {
    "bankCode": "ASSE",
    "countryCode": "TJ",
    "branchCode": "J22",
    "SWIFT Code": "ASSETJ22",
    "Bank Name": "STATE UNITARY ENTERPRISE SAVINGS BANK OF THE REPUBLIC OF TAJIKISTAN 'AMONATBONK' (SUE SB RT 'AMONATBONK')",
    "Address": "RUDAKI AVENUE 105",
    "City": "DUSHANBE",
    "Branch": "",
    "Postcode": "734001",
    "Country": "Tajikistan",
    "Connection": "Active"
  },
  {
    "bankCode": "SUTL",
    "countryCode": "TJ",
    "branchCode": "J22",
    "SWIFT Code": "SUTLTJ22",
    "Bank Name": "STATE UNITARY ENTERPRISED INDUSTRIAL AND EXPORT BANK OF TAJIKISTAN 'SANOATSODIROTBONK'",
    "Address": "S.SHEROZI AVENUE 21",
    "City": "DUSHANBE",
    "Branch": "",
    "Postcode": "734018",
    "Country": "Tajikistan",
    "Connection": "Active"
  },
  {
    "bankCode": "FMBT",
    "countryCode": "TJ",
    "branchCode": "J22",
    "SWIFT Code": "FMBTTJ22",
    "Bank Name": "THE FIRST MICROFINANCEBANK",
    "Address": "PUSHKIN STR. 10",
    "City": "DUSHANBE",
    "Branch": "",
    "Postcode": "734003",
    "Country": "Tajikistan",
    "Connection": "Active"
  }
]
module.exports = tajikistan
