const tanzania = [
  {
    "bankCode": "NMIB",
    "countryCode": "TZ",
    "branchCode": "ZTZ",
    "SWIFT Code": "NMIBTZTZ",
    "Bank Name": "NMB BANK PLC",
    "Address": "OHIO STREET, ALI HASSAN MWINYI RD",
    "City": "DAR ES SALAAM",
    "Branch": "",
    "Postcode": "11101",
    "Country": "Tanzania",
    "Connection": "Active"
  },
  {
    "bankCode": "PBZA",
    "countryCode": "TZ",
    "branchCode": "ZTZ",
    "SWIFT Code": "PBZATZTZ",
    "Bank Name": "PEOPLE'S BANK OF ZANZIBAR, THE",
    "Address": "ZIC BUILDING, FLOOR 2, DR SALIMINI RD, MJINI MAGHARIBI-UNGUJA",
    "City": "ZANZIBAR",
    "Branch": "",
    "Postcode": "",
    "Country": "Tanzania",
    "Connection": "Active"
  },
  {
    "bankCode": "PBZA",
    "countryCode": "TZ",
    "branchCode": "CHK",
    "SWIFT Code": "PBZATZTZCHK",
    "Bank Name": "PEOPLE'S BANK OF ZANZIBAR, THE",
    "Address": "CHAKE CHAKE",
    "City": "ZANZIBAR",
    "Branch": "CHAKE CHAKE BRANCH",
    "Postcode": "74216",
    "Country": "Tanzania",
    "Connection": "Active"
  },
  {
    "bankCode": "PBZA",
    "countryCode": "TZ",
    "branchCode": "NWK",
    "SWIFT Code": "PBZATZTZNWK",
    "Bank Name": "PEOPLE'S BANK OF ZANZIBAR, THE",
    "Address": "MWANAKWEREKWE",
    "City": "ZANZIBAR",
    "Branch": "MWANAKWEREKWE BRANCH",
    "Postcode": "71201",
    "Country": "Tanzania",
    "Connection": "Active"
  },
  {
    "bankCode": "SBIC",
    "countryCode": "TZ",
    "branchCode": "ZTX",
    "SWIFT Code": "SBICTZTX",
    "Bank Name": "STANBIC BANK TANZANIA LIMITED",
    "Address": "STANBIC CENTER 99A ALI HASSAN, MWINYI/KINONDONI ROAD",
    "City": "DAR ES SALAAM",
    "Branch": "",
    "Postcode": "",
    "Country": "Tanzania",
    "Connection": "Active"
  },
  {
    "bankCode": "SCBL",
    "countryCode": "TZ",
    "branchCode": "ZTX",
    "SWIFT Code": "SCBLTZTX",
    "Bank Name": "STANDARD CHARTERED BANK TANZANIA LTD",
    "Address": "INTERNATIONAL HOUSE BUILDING, CORNER GARDEN AV / OHIO STREET",
    "City": "DAR ES SALAAM",
    "Branch": "",
    "Postcode": "",
    "Country": "Tanzania",
    "Connection": "Active"
  },
  {
    "bankCode": "SCBL",
    "countryCode": "TZ",
    "branchCode": "SSU",
    "SWIFT Code": "SCBLTZTXSSU",
    "Bank Name": "STANDARD CHARTERED BANK TANZANIA LTD",
    "Address": "INTERNATIONAL HOUSE BUILDING, CORNER GARDEN AV / OHIO STREET",
    "City": "DAR ES SALAAM",
    "Branch": "SECURITIES SERVICES UNIT",
    "Postcode": "",
    "Country": "Tanzania",
    "Connection": "Active"
  },
  {
    "bankCode": "TZAD",
    "countryCode": "TZ",
    "branchCode": "ZTZ",
    "SWIFT Code": "TZADTZTZ",
    "Bank Name": "TANZANIA AGRICULTURAL DEVELOPMENT BANK",
    "Address": "ACACIA ESTATES BUILDING, FLOOR 3, 84 KINONDONI ROAD",
    "City": "DAR ES SALAAM",
    "Branch": "",
    "Postcode": "14110",
    "Country": "Tanzania",
    "Connection": "Active"
  },
  {
    "bankCode": "TAPB",
    "countryCode": "TZ",
    "branchCode": "ZTZ",
    "SWIFT Code": "TAPBTZTZ",
    "Bank Name": "TANZANIA COMMMERCIAL BANK PLC",
    "Address": "LAPF TOWERS, FLOOR 10, BAGAMOYO ROAD",
    "City": "DAR ES SALAAM",
    "Branch": "",
    "Postcode": "22217",
    "Country": "Tanzania",
    "Connection": "Active"
  },
  {},
  {
    "bankCode": "UCCT",
    "countryCode": "TZ",
    "branchCode": "ZTZ",
    "SWIFT Code": "UCCTTZTZ",
    "Bank Name": "UCHUMI COMMERCIAL BANK LTD",
    "Address": "MOSHI LUTHERAN CHURCH BLDG, MARKET STREET",
    "City": "MOSHI",
    "Branch": "",
    "Postcode": "25101",
    "Country": "Tanzania",
    "Connection": "Active"
  },
  {
    "bankCode": "UNAF",
    "countryCode": "TZ",
    "branchCode": "ZTZ",
    "SWIFT Code": "UNAFTZTZ",
    "Bank Name": "UNITED BANK FOR AFRICA (TANZANIA) LIMITED",
    "Address": "30 C/30 D NYERERE ROAD",
    "City": "DAR ES SALAAM",
    "Branch": "",
    "Postcode": "15101",
    "Country": "Tanzania",
    "Connection": "Active"
  },
  {
    "bankCode": "YETM",
    "countryCode": "TZ",
    "branchCode": "ZTZ",
    "SWIFT Code": "YETMTZTZ",
    "Bank Name": "YETU MICROFINANCE BANK PLC",
    "Address": "MKUNAZINI BUILDING, FLOOR 2, KIUNGANI STREET",
    "City": "DAR ES SALAAM",
    "Branch": "",
    "Postcode": "75379",
    "Country": "Tanzania",
    "Connection": "Active"
  },
  {
    "bankCode": "BARC",
    "countryCode": "TZ",
    "branchCode": "ZTZ",
    "SWIFT Code": "BARCTZTZ",
    "Bank Name": "ABSA BANK TANZANIA LIMITED",
    "Address": "ABSA HOUSE, OHIO STREET",
    "City": "DAR ES SALAAM",
    "Branch": "",
    "Postcode": "72290",
    "Country": "Tanzania",
    "Connection": "Active"
  },
  {
    "bankCode": "ACTZ",
    "countryCode": "TZ",
    "branchCode": "ZTZ",
    "SWIFT Code": "ACTZTZTZ",
    "Bank Name": "ACCESS MICROFINANCE BANK TANZANIA LTD",
    "Address": "DERM HOUSE, BLOCK 45A, 16 NEW BAGAMOYO ROAD, KIJITONYAM",
    "City": "DAR ES SALAAM",
    "Branch": "",
    "Postcode": "95068",
    "Country": "Tanzania",
    "Connection": "Active"
  },
  {
    "bankCode": "FMBZ",
    "countryCode": "TZ",
    "branchCode": "ZTX",
    "SWIFT Code": "FMBZTZTX",
    "Bank Name": "AFRICAN BANKING CORPORATION TANZANIA LIMITED",
    "Address": "UHURU HEIGHTS, FLOOR 5-6, BIBI TITI MOHAMED ROAD",
    "City": "DAR ES SALAAM",
    "Branch": "",
    "Postcode": "70270",
    "Country": "Tanzania",
    "Connection": "Active"
  },
  {
    "bankCode": "AKCO",
    "countryCode": "TZ",
    "branchCode": "ZTZ",
    "SWIFT Code": "AKCOTZTZ",
    "Bank Name": "AKIBA COMMERCIAL BANK PLC",
    "Address": "AMANI PLACE BUILDING, FLOOR 3, OHIO STREET",
    "City": "DAR ES SALAAM",
    "Branch": "",
    "Postcode": "09574",
    "Country": "Tanzania",
    "Connection": "Active"
  },
  {
    "bankCode": "AMNN",
    "countryCode": "TZ",
    "branchCode": "ZTZ",
    "SWIFT Code": "AMNNTZTZ",
    "Bank Name": "AMANA BANK LIMITED",
    "Address": "GOLDEN JUBILEE TOWER, FLOOR 2, OHIO STREET",
    "City": "DAR ES SALAAM",
    "Branch": "",
    "Postcode": "11104",
    "Country": "Tanzania",
    "Connection": "Active"
  },
  {
    "bankCode": "AZAN",
    "countryCode": "TZ",
    "branchCode": "ZTZ",
    "SWIFT Code": "AZANTZTZ",
    "Bank Name": "AZANIA BANK LIMITED",
    "Address": "MAWASILIANO TOWER, FLOOR 3, 20 SAM NUJOMA ROAD, UBUNGO",
    "City": "DAR ES SALAAM",
    "Branch": "",
    "Postcode": "14414",
    "Country": "Tanzania",
    "Connection": "Active"
  },
  {
    "bankCode": "EUAF",
    "countryCode": "TZ",
    "branchCode": "ZTZ",
    "SWIFT Code": "EUAFTZTZ",
    "Bank Name": "BANK OF AFRICA TANZANIA LIMITED",
    "Address": "NDC DEVELOPMENT HOUSE, OHIO STREET, KIVUKONI",
    "City": "DAR ES SALAAM",
    "Branch": "",
    "Postcode": "00400",
    "Country": "Tanzania",
    "Connection": "Active"
  },
  {
    "bankCode": "BARB",
    "countryCode": "TZ",
    "branchCode": "ZTZ",
    "SWIFT Code": "BARBTZTZ",
    "Bank Name": "BANK OF BARODA (TANZANIA) LTD",
    "Address": "149/32 OHIO SOKOINE DRIVE",
    "City": "DAR ES SALAAM",
    "Branch": "",
    "Postcode": "12101",
    "Country": "Tanzania",
    "Connection": "Active"
  },
  {
    "bankCode": "BKID",
    "countryCode": "TZ",
    "branchCode": "ZTZ",
    "SWIFT Code": "BKIDTZTZ",
    "Bank Name": "BANK OF INDIA (TANZANIA) LIMITED",
    "Address": "MAKTABA STREET, MAKTABA BUSINESS PARK",
    "City": "DAR ES SALAAM",
    "Branch": "",
    "Postcode": "",
    "Country": "Tanzania",
    "Connection": "Active"
  },
  {
    "bankCode": "TANZ",
    "countryCode": "TZ",
    "branchCode": "ZTX",
    "SWIFT Code": "TANZTZTX",
    "Bank Name": "BANK OF TANZANIA",
    "Address": "2 MIRAMBO STREET",
    "City": "DAR ES SALAAM",
    "Branch": "",
    "Postcode": "11884",
    "Country": "Tanzania",
    "Connection": "Active"
  },
  {
    "bankCode": "BCTI",
    "countryCode": "TZ",
    "branchCode": "ZTT",
    "SWIFT Code": "BCTITZTT",
    "Bank Name": "BUSINESS CONNEXION (TANZANIA) LIMITED",
    "Address": "6 LUCY LAMECKY STREET, MWAI KIBAKI, ROAD",
    "City": "DAR ES SALAAM",
    "Branch": "",
    "Postcode": "14112",
    "Country": "Tanzania",
    "Connection": "Active"
  },
  {
    "bankCode": "CNRB",
    "countryCode": "TZ",
    "branchCode": "ZTZ",
    "SWIFT Code": "CNRBTZTZ",
    "Bank Name": "CANARA BANK  (TANZANIA) LTD",
    "Address": "ELIA COMPLEX, FLOOR GROUND, 16/1 BIBI TITI ROAD, ZANAKI",
    "City": "DAR ES SALAAM",
    "Branch": "",
    "Postcode": "71572",
    "Country": "Tanzania",
    "Connection": "Active"
  },
  {
    "bankCode": "CDSH",
    "countryCode": "TZ",
    "branchCode": "ZTZ",
    "SWIFT Code": "CDSHTZTZ",
    "Bank Name": "CHINA DASHENG BANK LIMITED",
    "Address": "FLOOR 1, 32 SAMORA AVENUE SAMORA/BRIDGE",
    "City": "DAR ES SALAAM",
    "Branch": "",
    "Postcode": "11950",
    "Country": "Tanzania",
    "Connection": "Active"
  },
  {
    "bankCode": "CITI",
    "countryCode": "TZ",
    "branchCode": "ZTZ",
    "SWIFT Code": "CITITZTZ",
    "Bank Name": "CITIBANK TANZANIA LTD",
    "Address": "1962 TOURE DRIVE, OYSTER BAY",
    "City": "DAR ES SALAAM",
    "Branch": "",
    "Postcode": "14111",
    "Country": "Tanzania",
    "Connection": "Active"
  },
  {
    "bankCode": "CORU",
    "countryCode": "TZ",
    "branchCode": "ZTZ",
    "SWIFT Code": "CORUTZTZ",
    "Bank Name": "CRDB BANK PLC",
    "Address": "PLOT NO. 25, 26 ALI HASSAN MWINYI, ROAD",
    "City": "DAR ES SALAAM",
    "Branch": "",
    "Postcode": "11101",
    "Country": "Tanzania",
    "Connection": "Active"
  },
  {
    "bankCode": "DSTX",
    "countryCode": "TZ",
    "branchCode": "ZTZ",
    "SWIFT Code": "DSTXTZTZ",
    "Bank Name": "DAR ES SALAAM STOCK EXCHANGE",
    "Address": "KAMBARAGE HOUSE NHC CORP OFFICE,, FLOOR 3 6 UFUKONI STREET",
    "City": "DAR ES SALAAM",
    "Branch": "",
    "Postcode": "",
    "Country": "Tanzania",
    "Connection": "Active"
  },
  {
    "bankCode": "DASU",
    "countryCode": "TZ",
    "branchCode": "ZTZ",
    "SWIFT Code": "DASUTZTZ",
    "Bank Name": "DCB COMMERCIAL BANK PLC",
    "Address": "DCB HOUSE, 183 MOROGORO R, MAGOMENI MWEMBECHAI",
    "City": "DAR ES SALAAM",
    "Branch": "",
    "Postcode": "14101",
    "Country": "Tanzania",
    "Connection": "Active"
  },
  {
    "bankCode": "DTKE",
    "countryCode": "TZ",
    "branchCode": "ZTZ",
    "SWIFT Code": "DTKETZTZ",
    "Bank Name": "DIAMOND TRUST BANK TANZANIA PUBLIC LIMITED COMPANY",
    "Address": "DTB CENTRE, FLOOR 5, 991 KAHAMA ROAD MASAKI",
    "City": "DAR ES SALAAM",
    "Branch": "",
    "Postcode": "35091",
    "Country": "Tanzania",
    "Connection": "Active"
  },
  {
    "bankCode": "ECOC",
    "countryCode": "TZ",
    "branchCode": "ZTZ",
    "SWIFT Code": "ECOCTZTZ",
    "Bank Name": "ECOBANK TANZANIA LIMITED",
    "Address": "ACACIA BUILDING, 84 KINONDONI ROAD HANANASIF, MNAZI MMOJA",
    "City": "DAR ES SALAAM",
    "Branch": "",
    "Postcode": "65468",
    "Country": "Tanzania",
    "Connection": "Active"
  },
  {
    "bankCode": "EQBL",
    "countryCode": "TZ",
    "branchCode": "ZTZ",
    "SWIFT Code": "EQBLTZTZ",
    "Bank Name": "EQUITY BANK TANZANIA LIMITED",
    "Address": "GOLDEN JUBILEE TOWER, FLOOR 3, OHIO STREET",
    "City": "DAR ES SALAAM",
    "Branch": "",
    "Postcode": "20660",
    "Country": "Tanzania",
    "Connection": "Active"
  },
  {
    "bankCode": "EXTN",
    "countryCode": "TZ",
    "branchCode": "ZTZ",
    "SWIFT Code": "EXTNTZTZ",
    "Bank Name": "EXIMBANK (TANZANIA) LTD",
    "Address": "9 SAMORA AVENUE",
    "City": "DAR ES SALAAM",
    "Branch": "",
    "Postcode": "",
    "Country": "Tanzania",
    "Connection": "Active"
  },
  {
    "bankCode": "EXTN",
    "countryCode": "TZ",
    "branchCode": "TFD",
    "SWIFT Code": "EXTNTZTZTFD",
    "Bank Name": "EXIMBANK (TANZANIA) LTD",
    "Address": "9 SAMORA AVENUE",
    "City": "DAR ES SALAAM",
    "Branch": "TRADE FINANCE DEPARTMENT",
    "Postcode": "SAMORA AVENUE",
    "Country": "Tanzania",
    "Connection": "Active"
  },
  {
    "bankCode": "FNMI",
    "countryCode": "TZ",
    "branchCode": "ZTZ",
    "SWIFT Code": "FNMITZTZ",
    "Bank Name": "FINCA MICROFINANCE BANK LIMITED",
    "Address": "TAN HOUSE, FLOOR 8, PLOT 34/1 BAGAMOYO ROAD, VICTORIA AREA",
    "City": "DAR ES SALAAM",
    "Branch": "",
    "Postcode": "78783",
    "Country": "Tanzania",
    "Connection": "Active"
  },
  {
    "bankCode": "GTBI",
    "countryCode": "TZ",
    "branchCode": "ZTZ",
    "SWIFT Code": "GTBITZTZ",
    "Bank Name": "GUARANTY TRUST BANK TANZANIA LTD",
    "Address": "4 REGENT ESTATE, BAGAMOYO RD, VICTORIA",
    "City": "DAR ES SALAAM",
    "Branch": "",
    "Postcode": "14112",
    "Country": "Tanzania",
    "Connection": "Active"
  },
  {
    "bankCode": "HABL",
    "countryCode": "TZ",
    "branchCode": "ZTZ",
    "SWIFT Code": "HABLTZTZ",
    "Bank Name": "HABIB AFRICAN BANK",
    "Address": "ZANAKI / INDIRA GANDHI STREET",
    "City": "DAR ES SALAAM",
    "Branch": "",
    "Postcode": "",
    "Country": "Tanzania",
    "Connection": "Active"
  },
  {
    "bankCode": "IMBL",
    "countryCode": "TZ",
    "branchCode": "ZTZ",
    "SWIFT Code": "IMBLTZTZ",
    "Bank Name": "I AND M BANK (T) LIMITED",
    "Address": "75/27 MAKTABA STREET",
    "City": "DAR ES SALAAM",
    "Branch": "",
    "Postcode": "77555",
    "Country": "Tanzania",
    "Connection": "Active"
  },
  {
    "bankCode": "BKMY",
    "countryCode": "TZ",
    "branchCode": "ZTZ",
    "SWIFT Code": "BKMYTZTZ",
    "Bank Name": "INTERNATIONAL COMMERCIAL BANK (TANZANIA) LIMITED",
    "Address": "FLOOR 1, JAMHURI STREET, MOROGORO ROAD",
    "City": "DAR ES SALAAM",
    "Branch": "",
    "Postcode": "80268",
    "Country": "Tanzania",
    "Connection": "Active"
  },
  {
    "bankCode": "KCBL",
    "countryCode": "TZ",
    "branchCode": "ZTZ",
    "SWIFT Code": "KCBLTZTZ",
    "Bank Name": "KCB BANK TANZANIA LIMITED",
    "Address": "HARAMBEE PLAZA ALI HASSAN MWINYI, ROAD, KAUNDA DRIVE",
    "City": "DAR ES SALAAM",
    "Branch": "",
    "Postcode": "11102",
    "Country": "Tanzania",
    "Connection": "Active"
  },
  {
    "bankCode": "KLMJ",
    "countryCode": "TZ",
    "branchCode": "ZTZ",
    "SWIFT Code": "KLMJTZTZ",
    "Bank Name": "KILIMANJARO CO-OPERATIVE BANK LTD",
    "Address": "KILIBANK BUILDING, NYRERE AVENUE",
    "City": "MOSHI",
    "Branch": "",
    "Postcode": "45113",
    "Country": "Tanzania",
    "Connection": "Active"
  },
  {
    "bankCode": "ADVB",
    "countryCode": "TZ",
    "branchCode": "ZTZ",
    "SWIFT Code": "ADVBTZTZ",
    "Bank Name": "LETSHEGO BANK (T) LIMITED",
    "Address": "395 MWAI KIBAKI ROAD, URSINO NORTH, URSINO NORTH",
    "City": "DAR ES SALAAM",
    "Branch": "",
    "Postcode": "34459",
    "Country": "Tanzania",
    "Connection": "Active"
  },
  {
    "bankCode": "MBTL",
    "countryCode": "TZ",
    "branchCode": "ZTZ",
    "SWIFT Code": "MBTLTZTZ",
    "Bank Name": "MAENDELEO BANK PLC",
    "Address": "LUTHER HOUSE, SOKOINE DRIVE",
    "City": "DAR ES SALAAM",
    "Branch": "",
    "Postcode": "31962",
    "Country": "Tanzania",
    "Connection": "Active"
  },
  {
    "bankCode": "MKCB",
    "countryCode": "TZ",
    "branchCode": "ZTZ",
    "SWIFT Code": "MKCBTZTZ",
    "Bank Name": "MKOMBOZI COMMERCIAL BANK LTD",
    "Address": "ST. JOSEPH'S CATHEDRAL, 40 MANSFILED",
    "City": "DAR ES SALAAM",
    "Branch": "",
    "Postcode": "38448",
    "Country": "Tanzania",
    "Connection": "Active"
  },
  {
    "bankCode": "MUOB",
    "countryCode": "TZ",
    "branchCode": "ZTZ",
    "SWIFT Code": "MUOBTZTZ",
    "Bank Name": "MUCOBA BANK PLC",
    "Address": "(3,4,5)B MARKET STREET, MAFINGA",
    "City": "IRINGA",
    "Branch": "",
    "Postcode": "",
    "Country": "Tanzania",
    "Connection": "Active"
  },
  {
    "bankCode": "MWCO",
    "countryCode": "TZ",
    "branchCode": "ZTZ",
    "SWIFT Code": "MWCOTZTZ",
    "Bank Name": "MWALIMU COMMERCIAL BANK PLC",
    "Address": "MILIMANI TOWERS, FLOOR 0, SAM NUJOMO ROAD",
    "City": "DAR ES SALAAM",
    "Branch": "",
    "Postcode": "14113",
    "Country": "Tanzania",
    "Connection": "Active"
  },
  {
    "bankCode": "MWCB",
    "countryCode": "TZ",
    "branchCode": "ZTZ",
    "SWIFT Code": "MWCBTZTZ",
    "Bank Name": "MWANGA HAKIKA BANK LIMITED",
    "Address": "SKY TOWER, FLOOR 16, 45 A NEW BAGAMOYO ROAD, KIJITONYAMA",
    "City": "DAR ES SALAAM",
    "Branch": "",
    "Postcode": "14113",
    "Country": "Tanzania",
    "Connection": "Active"
  },
  {
    "bankCode": "NLCB",
    "countryCode": "TZ",
    "branchCode": "0T4",
    "SWIFT Code": "NLCBTZTX0T4",
    "Bank Name": "NATIONAL BANK OF COMMERCE, THE",
    "Address": "",
    "City": "ARUSHA",
    "Branch": "ARUSHA BRANCH",
    "Postcode": "23100",
    "Country": "Tanzania",
    "Connection": "Active"
  },
  {
    "bankCode": "NLCB",
    "countryCode": "TZ",
    "branchCode": "0T3",
    "SWIFT Code": "NLCBTZTX0T3",
    "Bank Name": "NATIONAL BANK OF COMMERCE, THE",
    "Address": "",
    "City": "DAR ES SALAAM",
    "Branch": "CORPORATE BRANCH",
    "Postcode": "",
    "Country": "Tanzania",
    "Connection": "Active"
  },
  {
    "bankCode": "NLCB",
    "countryCode": "TZ",
    "branchCode": "FIN",
    "SWIFT Code": "NLCBTZTXFIN",
    "Bank Name": "NATIONAL BANK OF COMMERCE, THE",
    "Address": "",
    "City": "DAR ES SALAAM",
    "Branch": "FINANCIAL DEPARTMENT-NBC HOUSE",
    "Postcode": "",
    "Country": "Tanzania",
    "Connection": "Active"
  },
  {
    "bankCode": "NLCB",
    "countryCode": "TZ",
    "branchCode": "ZTX",
    "SWIFT Code": "NLCBTZTX",
    "Bank Name": "NATIONAL BANK OF COMMERCE, THE",
    "Address": "ILALA CBD, NBC HOUSE, SOKOINE DRIVE/AZIKIWE STREET",
    "City": "DAR ES SALAAM",
    "Branch": "HEADOFFICE",
    "Postcode": "11104",
    "Country": "Tanzania",
    "Connection": "Active"
  },
  {
    "bankCode": "NLCB",
    "countryCode": "TZ",
    "branchCode": "IND",
    "SWIFT Code": "NLCBTZTXIND",
    "Bank Name": "NATIONAL BANK OF COMMERCE, THE",
    "Address": "",
    "City": "DAR ES SALAAM",
    "Branch": "INDUSTRIAL BRANCH",
    "Postcode": "",
    "Country": "Tanzania",
    "Connection": "Active"
  },
  {
    "bankCode": "NLCB",
    "countryCode": "TZ",
    "branchCode": "KIC",
    "SWIFT Code": "NLCBTZTXKIC",
    "Bank Name": "NATIONAL BANK OF COMMERCE, THE",
    "Address": "",
    "City": "DAR ES SALAAM",
    "Branch": "KICHWELE BRANCH",
    "Postcode": "",
    "Country": "Tanzania",
    "Connection": "Active"
  },
  {
    "bankCode": "NLCB",
    "countryCode": "TZ",
    "branchCode": "MNA",
    "SWIFT Code": "NLCBTZTXMNA",
    "Bank Name": "NATIONAL BANK OF COMMERCE, THE",
    "Address": "",
    "City": "DAR ES SALAAM",
    "Branch": "MNAZI MMOJA BRANCH",
    "Postcode": "",
    "Country": "Tanzania",
    "Connection": "Active"
  },
  {
    "bankCode": "NLCB",
    "countryCode": "TZ",
    "branchCode": "0T8",
    "SWIFT Code": "NLCBTZTX0T8",
    "Bank Name": "NATIONAL BANK OF COMMERCE, THE",
    "Address": "SAMORA AVENUE",
    "City": "DAR ES SALAAM",
    "Branch": "SAMORA BRANCH",
    "Postcode": "00255",
    "Country": "Tanzania",
    "Connection": "Active"
  },
  {
    "bankCode": "NLCB",
    "countryCode": "TZ",
    "branchCode": "MBE",
    "SWIFT Code": "NLCBTZTXMBE",
    "Bank Name": "NATIONAL BANK OF COMMERCE, THE",
    "Address": "KARUME AVENUE",
    "City": "MBEYA",
    "Branch": "MBEYA BRANCH",
    "Postcode": "53107",
    "Country": "Tanzania",
    "Connection": "Active"
  },
  {
    "bankCode": "NLCB",
    "countryCode": "TZ",
    "branchCode": "MOR",
    "SWIFT Code": "NLCBTZTXMOR",
    "Bank Name": "NATIONAL BANK OF COMMERCE, THE",
    "Address": "",
    "City": "MOROGORO",
    "Branch": "MOROGORO BRANCH",
    "Postcode": "",
    "Country": "Tanzania",
    "Connection": "Active"
  },
  {
    "bankCode": "NLCB",
    "countryCode": "TZ",
    "branchCode": "0TM",
    "SWIFT Code": "NLCBTZTX0TM",
    "Bank Name": "NATIONAL BANK OF COMMERCE, THE",
    "Address": "",
    "City": "MOSHI",
    "Branch": "MOSHI BRANCH",
    "Postcode": "",
    "Country": "Tanzania",
    "Connection": "Active"
  },
  {
    "bankCode": "NLCB",
    "countryCode": "TZ",
    "branchCode": "0T5",
    "SWIFT Code": "NLCBTZTX0T5",
    "Bank Name": "NATIONAL BANK OF COMMERCE, THE",
    "Address": "NYERERE ROAD",
    "City": "MWANZA",
    "Branch": "MWANZA BRANCH",
    "Postcode": "33000",
    "Country": "Tanzania",
    "Connection": "Active"
  },
  {
    "bankCode": "NLCB",
    "countryCode": "TZ",
    "branchCode": "TAN",
    "SWIFT Code": "NLCBTZTXTAN",
    "Bank Name": "NATIONAL BANK OF COMMERCE, THE",
    "Address": "",
    "City": "TANGA",
    "Branch": "TANGA BRANCH",
    "Postcode": "",
    "Country": "Tanzania",
    "Connection": "Active"
  },
  {
    "bankCode": "NLCB",
    "countryCode": "TZ",
    "branchCode": "ZAN",
    "SWIFT Code": "NLCBTZTXZAN",
    "Bank Name": "NATIONAL BANK OF COMMERCE, THE",
    "Address": "",
    "City": "ZANZIBAR",
    "Branch": "ZANZIBAR BRANCH-UNGUJA",
    "Postcode": "",
    "Country": "Tanzania",
    "Connection": "Active"
  },
  {
    "bankCode": "CBAF",
    "countryCode": "TZ",
    "branchCode": "ZTZ",
    "SWIFT Code": "CBAFTZTZ",
    "Bank Name": "NCBA BANK TANZANIA LIMITED",
    "Address": "PPF HOUSE, MEZZANINE F FLOOR GF, SAMORA AVENUE, MOROGORO ROAD",
    "City": "DAR ES SALAAM",
    "Branch": "",
    "Postcode": "00255",
    "Country": "Tanzania",
    "Connection": "Active"
  }
]
module.exports = tanzania
