const thailand = [
  {
    "bankCode": "ICBC",
    "countryCode": "TH",
    "branchCode": "RYO",
    "SWIFT Code": "ICBCTHBKRYO",
    "Bank Name": "MEGA INTERNATIONAL COMMERCIAL BANK PUBLIC COMPANY LIMITED",
    "Address": "500/125, TAMBOL TASITH, MOO 3, AMPHUR PLUAK DANENG",
    "City": "RAYONG",
    "Branch": "RAYONG SUBBRANCH",
    "Postcode": "21140",
    "Country": "Thailand",
    "Connection": "Active"
  },
  {
    "bankCode": "DAIX",
    "countryCode": "TH",
    "branchCode": "HBK",
    "SWIFT Code": "DAIXTHBK",
    "Bank Name": "MERCEDES-BENZ (THAILAND) LIMITED",
    "Address": "FLOOR 20, 11/1, AIA SATHORN TOWER, SOUTH SATHORN RD, YANNAWA, SATHORN",
    "City": "BANGKOK",
    "Branch": "",
    "Postcode": "10120",
    "Country": "Thailand",
    "Connection": "Active"
  },
  {
    "bankCode": "MBMA",
    "countryCode": "TH",
    "branchCode": "HBK",
    "SWIFT Code": "MBMATHBK",
    "Bank Name": "MERCEDES-BENZ MANUFACTURING (THAILAND) LIMITED",
    "Address": "FLOOR 20, 11/1, 183, AIA SATHORN, TOWER SOUTH SATHORN ROAD YANNAWA,, SATHORN",
    "City": "BANGKOK",
    "Branch": "",
    "Postcode": "10120",
    "Country": "Thailand",
    "Connection": "Active"
  },
  {
    "bankCode": "MBLE",
    "countryCode": "TH",
    "branchCode": "HBK",
    "SWIFT Code": "MBLETHBK",
    "Bank Name": "MERCEDES-BENZ MOBILITY (THAILAND) CO. LTD.",
    "Address": "FLOOR 19, 11/1 , AIA SATHORN TOWER, SATHON TAI ROAD, YANNAWA, SATHORN",
    "City": "BANGKOK",
    "Branch": "",
    "Postcode": "10120",
    "Country": "Thailand",
    "Connection": "Active"
  },
  {
    "bankCode": "MHCB",
    "countryCode": "TH",
    "branchCode": "HB2",
    "SWIFT Code": "MHCBTHB2",
    "Bank Name": "MIZUHO BANK, LTD., BANGKOK BRANCH",
    "Address": "FLOOR 34, 98, SATHORN SQUARE, OFFICE TOWER NORTH SATHORN ROAD, SILOM, BANGRAK",
    "City": "BANGKOK",
    "Branch": "",
    "Postcode": "10500",
    "Country": "Thailand",
    "Connection": "Active"
  },
  {
    "bankCode": "MHCB",
    "countryCode": "TH",
    "branchCode": "HBK",
    "SWIFT Code": "MHCBTHBK",
    "Bank Name": "MIZUHO BANK, LTD., BANGKOK BRANCH",
    "Address": "FLOOR 34, 98, SATHORN SQUARE, OFFICE TOWER NORTH SATHORN ROAD, SILOM, BANG RAK",
    "City": "BANGKOK",
    "Branch": "",
    "Postcode": "10500",
    "Country": "Thailand",
    "Connection": "Active"
  },
  {
    "bankCode": "OCBC",
    "countryCode": "TH",
    "branchCode": "HBK",
    "SWIFT Code": "OCBCTHBK",
    "Bank Name": "OVERSEA-CHINESE BANKING CORPORATION LIMITED, BANGKOK BRANCH",
    "Address": "FLOOR 25, 1, QHOUSE LUMPINI UT, 2501 TUNGMAHAMEK SOUTH SATHORN ROAD, SATHORN",
    "City": "BANGKOK",
    "Branch": "",
    "Postcode": "10120",
    "Country": "Thailand",
    "Connection": "Active"
  },
  {
    "bankCode": "DCBB",
    "countryCode": "TH",
    "branchCode": "HBK",
    "SWIFT Code": "DCBBTHBK",
    "Bank Name": "RHB BANK BERHAD",
    "Address": "FLOOR GF/18, 87, M.THAI TOWER, ALL, SEASONS PLACE WIRELESS RD LUMPINI,, PATHUMWAN",
    "City": "BANGKOK",
    "Branch": "",
    "Postcode": "10330",
    "Country": "Thailand",
    "Connection": "Active"
  },
  {
    "bankCode": "RMGC",
    "countryCode": "TH",
    "branchCode": "HBK",
    "SWIFT Code": "RMGCTHBK",
    "Bank Name": "RMA GROUP COMPANY LIMITED",
    "Address": "FLOOR 15, 283/74, HOME PLACE, OFFICE BUILDING 55 SOI SUKHUMVIT, RD, THONGLOR 13",
    "City": "BANGKOK",
    "Branch": "",
    "Postcode": "10110",
    "Country": "Thailand",
    "Connection": "Active"
  },
  {
    "bankCode": "RMFR",
    "countryCode": "TH",
    "branchCode": "HB2",
    "SWIFT Code": "RMFRTHB2",
    "Bank Name": "ROBOWEALTH MUTUAL FUND BROKERAGE SECURITIES COMPANY LIMITED",
    "Address": "FLOOR 6, 1-7, ZUELLIG HOUSE, SILOM ROAD, SILOM, BANGRAK",
    "City": "BANGKOK",
    "Branch": "",
    "Postcode": "10500",
    "Country": "Thailand",
    "Connection": "Active"
  },
  {
    "bankCode": "SAWA",
    "countryCode": "TH",
    "branchCode": "HB2",
    "SWIFT Code": "SAWATHB2",
    "Bank Name": "SAWASDEESHOP CO., LTD.",
    "Address": "FLOOR 31, 75/78-79, OCEAN TOWER 2, SUKHUMVIT",
    "City": "BANGKOK",
    "Branch": "",
    "Postcode": "10110",
    "Country": "Thailand",
    "Connection": "Active"
  },
  {
    "bankCode": "SICO",
    "countryCode": "TH",
    "branchCode": "HBK",
    "SWIFT Code": "SICOTHBK",
    "Bank Name": "SIAM COMMERCIAL BANK PCL., THE",
    "Address": "BUILDING 2, RUTCHADAPISEK ROAD, CHATUCHAK",
    "City": "BANGKOK",
    "Branch": "",
    "Postcode": "10900",
    "Country": "Thailand",
    "Connection": "Active"
  },
  {
    "bankCode": "SICO",
    "countryCode": "TH",
    "branchCode": "TSD",
    "SWIFT Code": "SICOTHBKTSD",
    "Bank Name": "SIAM COMMERCIAL BANK PCL., THE",
    "Address": "RUTCHADAPISEK ROAD, CHATUCHAK",
    "City": "BANGKOK",
    "Branch": "TREASURY DEPARTMENT",
    "Postcode": "10900",
    "Country": "Thailand",
    "Connection": "Active"
  },
  {
    "bankCode": "SMEB",
    "countryCode": "TH",
    "branchCode": "HBK",
    "SWIFT Code": "SMEBTHBK",
    "Bank Name": "SMALL AND MEDIUM ENTERPRISE DEVELOPMENT BANK OF THAILAND",
    "Address": "310, SME BANK TOWER, PHAHOLYOTHIN RD, SAMSEN-NAI, PHAYATHAI",
    "City": "BANGKOK",
    "Branch": "",
    "Postcode": "10400",
    "Country": "Thailand",
    "Connection": "Active"
  },
  {
    "bankCode": "SGTE",
    "countryCode": "TH",
    "branchCode": "HB2",
    "SWIFT Code": "SGTETHB2",
    "Bank Name": "SONY GLOBAL TREASURY SERVICES (THAILAND) CO., LTD",
    "Address": "FLOOR 5, 2126, NEW PETCHBURI ROAD, BANGKAPI, HUAYKWANG",
    "City": "BANGKOK",
    "Branch": "",
    "Postcode": "10310",
    "Country": "Thailand",
    "Connection": "Active"
  },
  {
    "bankCode": "SGTE",
    "countryCode": "TH",
    "branchCode": "BKO",
    "SWIFT Code": "SGTETHB2BKO",
    "Bank Name": "SONY GLOBAL TREASURY SERVICES (THAILAND) CO., LTD",
    "Address": "FLOOR 5, 2126, NEW PETCHBURI ROAD, BANGKAPI, HUAYKWANG",
    "City": "BANGKOK",
    "Branch": "BACK OFFICE",
    "Postcode": "10310",
    "Country": "Thailand",
    "Connection": "Active"
  },
  {
    "bankCode": "SCBL",
    "countryCode": "TH",
    "branchCode": "HBX",
    "SWIFT Code": "SCBLTHBX",
    "Bank Name": "STANDARD CHARTERED BANK (THAI) PCL",
    "Address": "FLOOR 11-12-14, 140, WIRELESS ROAD, LUMPINI, PATUMWAN DISTRICT",
    "City": "BANGKOK",
    "Branch": "",
    "Postcode": "10330",
    "Country": "Thailand",
    "Connection": "Active"
  },
  {
    "bankCode": "SMBC",
    "countryCode": "TH",
    "branchCode": "HBK",
    "SWIFT Code": "SMBCTHBK",
    "Bank Name": "SUMITOMO MITSUI BANKING CORPORATION",
    "Address": "1, Q HOUSE LUMPINI BUILDING, SOUTH SATHORN ROAD",
    "City": "BANGKOK",
    "Branch": "",
    "Postcode": "10120",
    "Country": "Thailand",
    "Connection": "Active"
  },
  {
    "bankCode": "STBC",
    "countryCode": "TH",
    "branchCode": "HBK",
    "SWIFT Code": "STBCTHBK",
    "Bank Name": "SUMITOMO MITSUI TRUST BANK (THAI) PUBLIC COMPANY LIMITED",
    "Address": "FLOOR 32, 98, SATHORN SQUARE, OFFICE TOWER NORTH SATHORN ROAD, SILOM",
    "City": "BANGKOK",
    "Branch": "",
    "Postcode": "10500",
    "Country": "Thailand",
    "Connection": "Active"
  },
  {
    "bankCode": "THCE",
    "countryCode": "TH",
    "branchCode": "HB2",
    "SWIFT Code": "THCETHB2",
    "Bank Name": "THAI CREDIT BANK PUBLIC COMPANY LIMITED",
    "Address": "FLOOR 1, 123, THAI LIFE INSURANCE, BUILDING RATCHADAPHISEK RD DIN, DAENG SUB-DISTRICT",
    "City": "BANGKOK",
    "Branch": "",
    "Postcode": "10400",
    "Country": "Thailand",
    "Connection": "Active"
  },
  {
    "bankCode": "TSDC",
    "countryCode": "TH",
    "branchCode": "HBK",
    "SWIFT Code": "TSDCTHBK",
    "Bank Name": "THAILAND SECURITIES DEPOSITORY CO LTD",
    "Address": "FLOOR 14, 93, THE STOCK EXCHANGE, OF THAILAND RACHADAPISEK ROAD, DINDAENG",
    "City": "BANGKOK",
    "Branch": "",
    "Postcode": "10400",
    "Country": "Thailand",
    "Connection": "Active"
  },
  {
    "bankCode": "HSBC",
    "countryCode": "TH",
    "branchCode": "HBK",
    "SWIFT Code": "HSBCTHBK",
    "Bank Name": "THE HONGKONG AND SHANGHAI BANKING CORPORATION LIMITED",
    "Address": "HSBC BUILDING, 968 RAMA IV ROAD, SILOM, BANGRAK",
    "City": "BANGKOK",
    "Branch": "",
    "Postcode": "10500",
    "Country": "Thailand",
    "Connection": "Active"
  },
  {
    "bankCode": "TMBK",
    "countryCode": "TH",
    "branchCode": "HBK",
    "SWIFT Code": "TMBKTHBK",
    "Bank Name": "TMBTHANACHART BANK PUBLIC COMPANY LIMITED",
    "Address": "3000, PHAHOLYOTHIN ROAD, SAMSENNA, CHATUCHAK",
    "City": "BANGKOK",
    "Branch": "",
    "Postcode": "10900",
    "Country": "Thailand",
    "Connection": "Active"
  },
  {
    "bankCode": "UOVB",
    "countryCode": "TH",
    "branchCode": "HBK",
    "SWIFT Code": "UOVBTHBK",
    "Bank Name": "UNITED OVERSEAS BANK (THAI) PUBLIC COMPANY LIMITED",
    "Address": "690 , UOB PLAZA, SUKHUMVIT ROAD, KHLONG TAN",
    "City": "BANGKOK",
    "Branch": "",
    "Postcode": "10110",
    "Country": "Thailand",
    "Connection": "Active"
  },
  {
    "bankCode": "WMSC",
    "countryCode": "TH",
    "branchCode": "HB2",
    "SWIFT Code": "WMSCTHB2",
    "Bank Name": "WEALTH MAGIK SECURITIES COMPANY LIMITED",
    "Address": "FLOOR 5, NO. 383, CHIN PONG, LADYA ROAD, KHLONG SAN",
    "City": "BANGKOK",
    "Branch": "",
    "Postcode": "10600",
    "Country": "Thailand",
    "Connection": "Active"
  },
  {
    "bankCode": "AIAC",
    "countryCode": "TH",
    "branchCode": "HBK",
    "SWIFT Code": "AIACTHBK",
    "Bank Name": "AIA COMPANY LIMITED",
    "Address": "181, AIA TOWER, SURAWONGSE ROAD, SURIYAWONGSE",
    "City": "BANGKOK",
    "Branch": "",
    "Postcode": "10500",
    "Country": "Thailand",
    "Connection": "Active"
  },
  {
    "bankCode": "BKKB",
    "countryCode": "TH",
    "branchCode": "HBK",
    "SWIFT Code": "BKKBTHBK",
    "Bank Name": "BANGKOK BANK PUBLIC COMPANY LIMITED",
    "Address": "333, SILOM ROAD, BANGRUK",
    "City": "BANGKOK",
    "Branch": "",
    "Postcode": "10500",
    "Country": "Thailand",
    "Connection": "Active"
  },
  {
    "bankCode": "BKKB",
    "countryCode": "TH",
    "branchCode": "TRD",
    "SWIFT Code": "BKKBTHBKTRD",
    "Bank Name": "BANGKOK BANK PUBLIC COMPANY LIMITED",
    "Address": "333, BANGKOK BANK BUILDING, SILOM ROAD, BANGRUK",
    "City": "BANGKOK",
    "Branch": "BOND TRADING",
    "Postcode": "10500",
    "Country": "Thailand",
    "Connection": "Active"
  },
  {
    "bankCode": "BAAB",
    "countryCode": "TH",
    "branchCode": "HBK",
    "SWIFT Code": "BAABTHBK",
    "Bank Name": "BANK FOR AGRICULTURE AND AGRICULTURAL COOPERATIVES",
    "Address": "2346, PHAHOLYOTHIN ROAD, CHATUCHAK",
    "City": "BANGKOK",
    "Branch": "",
    "Postcode": "10900",
    "Country": "Thailand",
    "Connection": "Active"
  },
  {
    "bankCode": "BOFA",
    "countryCode": "TH",
    "branchCode": "H2X",
    "SWIFT Code": "BOFATH2X",
    "Bank Name": "BANK OF AMERICA, N.A. BANGKOK",
    "Address": "87/2, CRC TOWER, ALL SEASONS PLACE, WIRELESS ROAD, PATHUMWAN",
    "City": "BANGKOK",
    "Branch": "",
    "Postcode": "10330",
    "Country": "Thailand",
    "Connection": "Active"
  },
  {
    "bankCode": "BOFA",
    "countryCode": "TH",
    "branchCode": "THA",
    "SWIFT Code": "BOFATH2XTHA",
    "Bank Name": "BANK OF AMERICA, N.A. BANGKOK",
    "Address": "",
    "City": "BANGKOK",
    "Branch": "BANGKOK BRANCH",
    "Postcode": "",
    "Country": "Thailand",
    "Connection": "Active"
  },
  {
    "bankCode": "AYUD",
    "countryCode": "TH",
    "branchCode": "HBK",
    "SWIFT Code": "AYUDTHBK",
    "Bank Name": "BANK OF AYUDHYA PUBLIC COMPANY LIMITED",
    "Address": "1222, RAMA III ROAD, KHWENG BANGPONGPANG, KHET YANNAWA",
    "City": "BANGKOK",
    "Branch": "",
    "Postcode": "10120",
    "Country": "Thailand",
    "Connection": "Active"
  },
  {
    "bankCode": "BOTK",
    "countryCode": "TH",
    "branchCode": "HBX",
    "SWIFT Code": "BOTKTHBX",
    "Bank Name": "BANK OF AYUDHYA PUBLIC COMPANY LIMITED, BANGKOK OFFICE",
    "Address": "1222, RAMA III ROAD, KHWENG BANGPONGPANG, KHET YANNAWA",
    "City": "BANGKOK",
    "Branch": "",
    "Postcode": "10120",
    "Country": "Thailand",
    "Connection": "Active"
  },
  {
    "bankCode": "BKCH",
    "countryCode": "TH",
    "branchCode": "HBK",
    "SWIFT Code": "BKCHTHBK",
    "Bank Name": "BANK OF CHINA (THAI) PUBLIC COMPANY LIMITED",
    "Address": "179/4, BANGKOK CITY TOWER, SOUTH SATHORN ROAD, THUNGMAHAMEK, SATHORN",
    "City": "BANGKOK",
    "Branch": "",
    "Postcode": "10120",
    "Country": "Thailand",
    "Connection": "Active"
  },
  {
    "bankCode": "BOTH",
    "countryCode": "TH",
    "branchCode": "HBK",
    "SWIFT Code": "BOTHTHBK",
    "Bank Name": "BANK OF THAILAND",
    "Address": "273, SAMSEN ROAD, BANGKHUNPROM",
    "City": "BANGKOK",
    "Branch": "",
    "Postcode": "10200",
    "Country": "Thailand",
    "Connection": "Active"
  },
  {
    "bankCode": "BOTH",
    "countryCode": "TH",
    "branchCode": "HBP",
    "SWIFT Code": "BOTHTHBP",
    "Bank Name": "BANK OF THAILAND, BAHTNET PAYMENT SYSTEM",
    "Address": "FLOOR 3, 273, HEAD OFFICE BUILDING, SAMSEN ROAD, BANGKHUNPROM",
    "City": "BANGKOK",
    "Branch": "",
    "Postcode": "10200",
    "Country": "Thailand",
    "Connection": "Active"
  },
  {
    "bankCode": "BOTH",
    "countryCode": "TH",
    "branchCode": "TS1",
    "SWIFT Code": "BOTHTHBPTS1",
    "Bank Name": "BANK OF THAILAND, BAHTNET PAYMENT SYSTEM",
    "Address": "FLOOR 3, 273, HEAD OFFICE BUILDING, SAMSEN ROAD, BANGKHUNPROM",
    "City": "BANGKOK",
    "Branch": "BOT TESTING BIC 1",
    "Postcode": "10200",
    "Country": "Thailand",
    "Connection": "Active"
  },
  {
    "bankCode": "BOTH",
    "countryCode": "TH",
    "branchCode": "TS2",
    "SWIFT Code": "BOTHTHBPTS2",
    "Bank Name": "BANK OF THAILAND, BAHTNET PAYMENT SYSTEM",
    "Address": "FLOOR 3, 273, HEAD OFFICE BUILDING, SAMSEN ROAD, BANGKHUNPROM",
    "City": "BANGKOK",
    "Branch": "BOT TESTING BIC 2",
    "Postcode": "10200",
    "Country": "Thailand",
    "Connection": "Active"
  },
  {
    "bankCode": "BNPA",
    "countryCode": "TH",
    "branchCode": "HBK",
    "SWIFT Code": "BNPATHBK",
    "Bank Name": "BNP PARIBAS BANGKOK BRANCH",
    "Address": "FLOOR 41, 548, ONE CITY CENTRE, PHLOEN CHIT ROAD, PATHUM WAN",
    "City": "BANGKOK",
    "Branch": "",
    "Postcode": "10330",
    "Country": "Thailand",
    "Connection": "Active"
  },
  {
    "bankCode": "BOHH",
    "countryCode": "TH",
    "branchCode": "HBK",
    "SWIFT Code": "BOHHTHBK",
    "Bank Name": "BUSRAKHAM OIL (THAILAND) LTD.",
    "Address": "FLOOR 30-31, 1010, SHINAWATRA, TOWER 3 VIPHAVADI RANGSIT ROAD, CHATUCHAK SUB-DISTRICT",
    "City": "BANGKOK",
    "Branch": "",
    "Postcode": "10900",
    "Country": "Thailand",
    "Connection": "Active"
  },
  {
    "bankCode": "UBOB",
    "countryCode": "TH",
    "branchCode": "HBK",
    "SWIFT Code": "UBOBTHBK",
    "Bank Name": "CIMB THAI BANK PUBLIC COMPANY LIMITED (FORMERLY BANKTHAI PUBLIC COMPANY LIMITED)",
    "Address": "44, LANGSUAN ROAD BUILDING, LANGSUAN ROAD, LUMPINI SUBDISTR, PATHUMWAN DIST",
    "City": "BANGKOK",
    "Branch": "",
    "Postcode": "10330",
    "Country": "Thailand",
    "Connection": "Active"
  },
  {
    "bankCode": "CITI",
    "countryCode": "TH",
    "branchCode": "HBX",
    "SWIFT Code": "CITITHBX",
    "Bank Name": "CITIBANK N.A.",
    "Address": "399, INTERCHANGE 21 BUILDING, SUKHUMVIT ROAD, KLONGTOEY NUA, WATTANA",
    "City": "BANGKOK",
    "Branch": "",
    "Postcode": "10110",
    "Country": "Thailand",
    "Connection": "Active"
  },
  {
    "bankCode": "CITI",
    "countryCode": "TH",
    "branchCode": "IBF",
    "SWIFT Code": "CITITHBXIBF",
    "Bank Name": "CITIBANK N.A.",
    "Address": "82, NORTH SATHORN ROAD, SILOM, BANGRAK",
    "City": "BANGKOK",
    "Branch": "INTERNATIONAL BANKING FACILITY",
    "Postcode": "10500",
    "Country": "Thailand",
    "Connection": "Active"
  },
  {
    "bankCode": "CRES",
    "countryCode": "TH",
    "branchCode": "HBK",
    "SWIFT Code": "CRESTHBK",
    "Bank Name": "CREDIT SUISSE SECURITIES (THAILAND) LIMITED",
    "Address": "FLOOR 27, ABDULRAHIM PLACE, RAMA IV ROAD, KWANG SILOM",
    "City": "BANGKOK",
    "Branch": "",
    "Postcode": "10500",
    "Country": "Thailand",
    "Connection": "Active"
  },
  {
    "bankCode": "DEUT",
    "countryCode": "TH",
    "branchCode": "GMO",
    "SWIFT Code": "DEUTTHBKGMO",
    "Bank Name": "DEUTSCHE BANK AG, BANGKOK BRANCH",
    "Address": "63, ATHENEE TOWER, WIRELESS ROAD",
    "City": "BANGKOK",
    "Branch": "",
    "Postcode": "10330",
    "Country": "Thailand",
    "Connection": "Active"
  },
  {
    "bankCode": "DEUT",
    "countryCode": "TH",
    "branchCode": "HBK",
    "SWIFT Code": "DEUTTHBK",
    "Bank Name": "DEUTSCHE BANK AG, BANGKOK BRANCH",
    "Address": "63, ATHENEE TOWER, WIRELESS ROAD",
    "City": "BANGKOK",
    "Branch": "",
    "Postcode": "10330",
    "Country": "Thailand",
    "Connection": "Active"
  },
  {
    "bankCode": "EXTH",
    "countryCode": "TH",
    "branchCode": "HBK",
    "SWIFT Code": "EXTHTHBK",
    "Bank Name": "EXPORT-IMPORT BANK OF THAILAND",
    "Address": "FLOOR 17, 1193, EXIM BUILDING, PHAHOLYOTHIN ROAD, PHAYATHAI",
    "City": "BANGKOK",
    "Branch": "",
    "Postcode": "10400",
    "Country": "Thailand",
    "Connection": "Active"
  },
  {
    "bankCode": "GSBA",
    "countryCode": "TH",
    "branchCode": "HBK",
    "SWIFT Code": "GSBATHBK",
    "Bank Name": "GOVERNMENT SAVINGS BANK",
    "Address": "470, BUILDING 1, PHAHOLYOTHIN ROAD, SAMSEN NAI, PHAYATHAI",
    "City": "BANGKOK",
    "Branch": "",
    "Postcode": "10400",
    "Country": "Thailand",
    "Connection": "Active"
  },
  {
    "bankCode": "BHOB",
    "countryCode": "TH",
    "branchCode": "HBK",
    "SWIFT Code": "BHOBTHBK",
    "Bank Name": "INDIAN OVERSEAS BANK (FORMERLY BHARAT OVERSEAS BANK LTD.)",
    "Address": "221, RAJAWONGSE RD, SAMPHANTHAWONGSE",
    "City": "BANGKOK",
    "Branch": "",
    "Postcode": "10100",
    "Country": "Thailand",
    "Connection": "Active"
  },
  {
    "bankCode": "IVGS",
    "countryCode": "TH",
    "branchCode": "HBK",
    "SWIFT Code": "IVGSTHBK",
    "Bank Name": "INDORAMA VENTURES GLOBAL SERVICES LIMITED",
    "Address": "FLOOR 32, 75/80-81, OCEAN TOWER 2, ASOKE ROAD, SUKHUMVIT 19 ALLEY, VADHANA DISTRI",
    "City": "BANGKOK",
    "Branch": "",
    "Postcode": "10110",
    "Country": "Thailand",
    "Connection": "Active"
  },
  {
    "bankCode": "ICBK",
    "countryCode": "TH",
    "branchCode": "HBK",
    "SWIFT Code": "ICBKTHBK",
    "Bank Name": "INDUSTRIAL AND COMMERCIAL BANK OF CHINA (THAI) PUBLIC COMPANY LIMITED",
    "Address": "FLOOR 11-13, 622, EMPORIUM TOWER, SUKHUMVIT ROAD",
    "City": "BANGKOK",
    "Branch": "",
    "Postcode": "10110",
    "Country": "Thailand",
    "Connection": "Active"
  },
  {
    "bankCode": "ICBK",
    "countryCode": "TH",
    "branchCode": "CLR",
    "SWIFT Code": "ICBKTHBKCLR",
    "Bank Name": "INDUSTRIAL AND COMMERCIAL BANK OF CHINA (THAI) PUBLIC COMPANY LIMITED",
    "Address": "EMPORIUM TOWER",
    "City": "BANGKOK",
    "Branch": "RMB CLEARING BANK",
    "Postcode": "10110",
    "Country": "Thailand",
    "Connection": "Active"
  },
  {
    "bankCode": "TIBT",
    "countryCode": "TH",
    "branchCode": "HBK",
    "SWIFT Code": "TIBTTHBK",
    "Bank Name": "ISLAMIC BANK OF THAILAND",
    "Address": "FLOOR 28, 66, Q.HOUSE, 21 SUKHUMVIT ASOKE, NORTH KLONGTOEY, WATTANA",
    "City": "BANGKOK",
    "Branch": "",
    "Postcode": "10110",
    "Country": "Thailand",
    "Connection": "Active"
  },
  {
    "bankCode": "CHAS",
    "countryCode": "TH",
    "branchCode": "HBX",
    "SWIFT Code": "CHASTHBX",
    "Bank Name": "JPMORGAN CHASE BANK, N.A., BANGKOK BRANCH",
    "Address": "20, BUBHAJIT BUILDING, NORTH SATHORN ROAD, SILOM, BANG RAK",
    "City": "BANGKOK",
    "Branch": "",
    "Postcode": "10500",
    "Country": "Thailand",
    "Connection": "Active"
  },
  {
    "bankCode": "CHAS",
    "countryCode": "TH",
    "branchCode": "IBF",
    "SWIFT Code": "CHASTHBXIBF",
    "Bank Name": "JPMORGAN CHASE BANK, N.A., BANGKOK BRANCH",
    "Address": "",
    "City": "BANGKOK",
    "Branch": "INTERANATIONAL BANKING FACILITY",
    "Postcode": "",
    "Country": "Thailand",
    "Connection": "Active"
  },
  {
    "bankCode": "CHAS",
    "countryCode": "TH",
    "branchCode": "SEC",
    "SWIFT Code": "CHASTHBXSEC",
    "Bank Name": "JPMORGAN CHASE BANK, N.A., BANGKOK BRANCH",
    "Address": "",
    "City": "BANGKOK",
    "Branch": "JPMORGAN SECURITIES - THAILAND",
    "Postcode": "",
    "Country": "Thailand",
    "Connection": "Active"
  },
  {
    "bankCode": "CHAS",
    "countryCode": "TH",
    "branchCode": "LND",
    "SWIFT Code": "CHASTHBXLND",
    "Bank Name": "JPMORGAN CHASE BANK, N.A., BANGKOK BRANCH",
    "Address": "20, BUBHAJIT BUILDING, NORTH SATHORN ROAD, SILOM, BANG RAK",
    "City": "BANGKOK",
    "Branch": "LOANS AND DEPOSITIS SERVICES",
    "Postcode": "10500",
    "Country": "Thailand",
    "Connection": "Active"
  },
  {
    "bankCode": "CHAS",
    "countryCode": "TH",
    "branchCode": "MTS",
    "SWIFT Code": "CHASTHBXMTS",
    "Bank Name": "JPMORGAN CHASE BANK, N.A., BANGKOK BRANCH",
    "Address": "20, BUBHAJIT BUILDING, NORTH SATHORN ROAD, SILOM, BANG RAK",
    "City": "BANGKOK",
    "Branch": "MONEY TRANSFER SERVICES",
    "Postcode": "10500",
    "Country": "Thailand",
    "Connection": "Active"
  },
  {
    "bankCode": "CHAS",
    "countryCode": "TH",
    "branchCode": "TSD",
    "SWIFT Code": "CHASTHBXTSD",
    "Bank Name": "JPMORGAN CHASE BANK, N.A., BANGKOK BRANCH",
    "Address": "20, BUBHAJIT BUILDING, NORTH SATHORN ROAD, SILOM, BANG RAK",
    "City": "BANGKOK",
    "Branch": "TRADE SERVICES",
    "Postcode": "10500",
    "Country": "Thailand",
    "Connection": "Active"
  },
  {
    "bankCode": "CHAS",
    "countryCode": "TH",
    "branchCode": "TRO",
    "SWIFT Code": "CHASTHBXTRO",
    "Bank Name": "JPMORGAN CHASE BANK, N.A., BANGKOK BRANCH",
    "Address": "20, BUBHAJIT BUILDING, NORTH SATHORN ROAD, SILOM, BANG RAK",
    "City": "BANGKOK",
    "Branch": "TRADING/TREASURY OPERATIONS",
    "Postcode": "10500",
    "Country": "Thailand",
    "Connection": "Active"
  },
  {
    "bankCode": "KASI",
    "countryCode": "TH",
    "branchCode": "HBK",
    "SWIFT Code": "KASITHBK",
    "Bank Name": "KASIKORNBANK PUBLIC COMPANY LIMITED",
    "Address": "400/22, PHAHON YOTHIN BUILDING, PHAHON YOTHIN ROAD, SAM SEN NAI, PHAYA THAI",
    "City": "BANGKOK",
    "Branch": "",
    "Postcode": "10400",
    "Country": "Thailand",
    "Connection": "Active"
  },
  {
    "bankCode": "KASI",
    "countryCode": "TH",
    "branchCode": "CMD",
    "SWIFT Code": "KASITHBKCMD",
    "Bank Name": "KASIKORNBANK PUBLIC COMPANY LIMITED",
    "Address": "",
    "City": "BANGKOK",
    "Branch": "CASH MANAGEMENT DEPARTMENT",
    "Postcode": "",
    "Country": "Thailand",
    "Connection": "Active"
  },
  {
    "bankCode": "KASI",
    "countryCode": "TH",
    "branchCode": "CUS",
    "SWIFT Code": "KASITHBKCUS",
    "Bank Name": "KASIKORNBANK PUBLIC COMPANY LIMITED",
    "Address": "",
    "City": "BANGKOK",
    "Branch": "CUSTODIAN SERVICE DIVISION",
    "Postcode": "",
    "Country": "Thailand",
    "Connection": "Active"
  },
  {
    "bankCode": "KASI",
    "countryCode": "TH",
    "branchCode": "FMD",
    "SWIFT Code": "KASITHBKFMD",
    "Bank Name": "KASIKORNBANK PUBLIC COMPANY LIMITED",
    "Address": "",
    "City": "BANGKOK",
    "Branch": "FUND MANAGEMENT DEPT",
    "Postcode": "",
    "Country": "Thailand",
    "Connection": "Active"
  },
  {
    "bankCode": "KKPB",
    "countryCode": "TH",
    "branchCode": "HBK",
    "SWIFT Code": "KKPBTHBK",
    "Bank Name": "KIATNAKIN PHATRA BANK PUBLIC COMPANY LIMITED",
    "Address": "209, KKP TOWER, SUKHUMVIT 21 ASOKE, KHLONG TOEY NUA, WATTANA",
    "City": "BANGKOK",
    "Branch": "",
    "Postcode": "10110",
    "Country": "Thailand",
    "Connection": "Active"
  },
  {
    "bankCode": "KRTH",
    "countryCode": "TH",
    "branchCode": "HBK",
    "SWIFT Code": "KRTHTHBK",
    "Bank Name": "KRUNG THAI BANK PUBLIC COMPANY LIMITED",
    "Address": "FLOOR 6, 35, NANA NUA BUILDING, SUKHUMVIT ROAD",
    "City": "BANGKOK",
    "Branch": "",
    "Postcode": "10110",
    "Country": "Thailand",
    "Connection": "Active"
  },
  {
    "bankCode": "KRTH",
    "countryCode": "TH",
    "branchCode": "KNM",
    "SWIFT Code": "KRTHTHBKKNM",
    "Bank Name": "KRUNG THAI BANK PUBLIC COMPANY LIMITED",
    "Address": "",
    "City": "BANGKOK",
    "Branch": "KUNMING MESSAGING SUPPORT",
    "Postcode": "",
    "Country": "Thailand",
    "Connection": "Active"
  },
  {
    "bankCode": "KRTH",
    "countryCode": "TH",
    "branchCode": "PMP",
    "SWIFT Code": "KRTHTHBKPMP",
    "Bank Name": "KRUNG THAI BANK PUBLIC COMPANY LIMITED",
    "Address": "",
    "City": "BANGKOK",
    "Branch": "PHNOMPENH'S MESSAGING SUPPORT",
    "Postcode": "",
    "Country": "Thailand",
    "Connection": "Active"
  },
  {
    "bankCode": "KRTH",
    "countryCode": "TH",
    "branchCode": "SRP",
    "SWIFT Code": "KRTHTHBKSRP",
    "Bank Name": "KRUNG THAI BANK PUBLIC COMPANY LIMITED",
    "Address": "FLOOR 6, 35, NANA NUA BUILDING, SUKHUMVIT ROAD",
    "City": "BANGKOK",
    "Branch": "SIEMREAP MESSAGING SUPPORT",
    "Postcode": "10110",
    "Country": "Thailand",
    "Connection": "Active"
  },
  {
    "bankCode": "KRTH",
    "countryCode": "TH",
    "branchCode": "VTN",
    "SWIFT Code": "KRTHTHBKVTN",
    "Bank Name": "KRUNG THAI BANK PUBLIC COMPANY LIMITED",
    "Address": "FLOOR 6, 35, NANA NUA BUILDING, SUKHUMVIT ROAD",
    "City": "BANGKOK",
    "Branch": "VIENTIANE MESSAGING SUPPORT",
    "Postcode": "10110",
    "Country": "Thailand",
    "Connection": "Active"
  },
  {
    "bankCode": "LAHR",
    "countryCode": "TH",
    "branchCode": "HB2",
    "SWIFT Code": "LAHRTHB2",
    "Bank Name": "LAND AND HOUSES BANK PUBLIC COMPANY LIMITED",
    "Address": "G FLOOR 1,5,6,32, 1, Q HOUSE, LUMPINI SOUTH SATHORN THUNGMAHAMEK",
    "City": "BANGKOK",
    "Branch": "",
    "Postcode": "10120",
    "Country": "Thailand",
    "Connection": "Active"
  },
  {
    "bankCode": "ICBC",
    "countryCode": "TH",
    "branchCode": "BNA",
    "SWIFT Code": "ICBCTHBKBNA",
    "Bank Name": "MEGA INTERNATIONAL COMMERCIAL BANK PUBLIC COMPANY LIMITED",
    "Address": "FLOOR 2, 3, THOSAPOL LAND 3, UNIT B, BANGNA-TRAD RD, 947 MOO, BANGNA",
    "City": "BANGKOK",
    "Branch": "BANGNA BRANCH",
    "Postcode": "10260",
    "Country": "Thailand",
    "Connection": "Active"
  },
  {
    "bankCode": "ICBC",
    "countryCode": "TH",
    "branchCode": "HBK",
    "SWIFT Code": "ICBCTHBK",
    "Bank Name": "MEGA INTERNATIONAL COMMERCIAL BANK PUBLIC COMPANY LIMITED",
    "Address": "36/12, P.S. TOWER, 21 ASOKE SUKHUMVIT, WATTANA",
    "City": "BANGKOK",
    "Branch": "HEAD OFFICE, BANGKOK",
    "Postcode": "10110",
    "Country": "Thailand",
    "Connection": "Active"
  },
  {
    "bankCode": "ICBC",
    "countryCode": "TH",
    "branchCode": "CHB",
    "SWIFT Code": "ICBCTHBKCHB",
    "Bank Name": "MEGA INTERNATIONAL COMMERCIAL BANK PUBLIC COMPANY LIMITED",
    "Address": "39/4, SUKHUMVIT RD, MOO 3, HUAYKAPI MUANG",
    "City": "CHONBURI",
    "Branch": "CHONBURI BRANCH",
    "Postcode": "20130",
    "Country": "Thailand",
    "Connection": "Active"
  },
  {
    "bankCode": "ICBC",
    "countryCode": "TH",
    "branchCode": "BPO",
    "SWIFT Code": "ICBCTHBKBPO",
    "Bank Name": "MEGA INTERNATIONAL COMMERCIAL BANK PUBLIC COMPANY LIMITED",
    "Address": "SONGPOL RD, BANPONG",
    "City": "RATCHABURI",
    "Branch": "BANPONG BRANCH",
    "Postcode": "70110",
    "Country": "Thailand",
    "Connection": "Active"
  }
]
module.exports = thailand
