const togo = [
  {
    "bankCode": "ALTB",
    "countryCode": "TG",
    "branchCode": "GTG",
    "SWIFT Code": "ALTBTGTG",
    "Bank Name": "AFRICAN LEASE TOGO SA",
    "Address": "2 AVENUE SYLVANUS OLYMPIO, ALT , HOTEL PALM BEACH",
    "City": "LOME",
    "Branch": "",
    "Postcode": "3302",
    "Country": "Togo",
    "Connection": "Active"
  },
  {
    "bankCode": "AFRI",
    "countryCode": "TG",
    "branchCode": "GTG",
    "SWIFT Code": "AFRITGTG",
    "Bank Name": "BANK OF AFRICA TOGO",
    "Address": "AVENUE DE LA REPUBLIQUE",
    "City": "LOME",
    "Branch": "",
    "Postcode": "",
    "Country": "Togo",
    "Connection": "Active"
  },
  {
    "bankCode": "ATTG",
    "countryCode": "TG",
    "branchCode": "GTG",
    "SWIFT Code": "ATTGTGTG",
    "Bank Name": "BANQUE ATLANTIQUE TOGO",
    "Address": "RUE KOUMOUE, PLACE DU PETIT MARCHE, IMMEUBLE MISS TOGO",
    "City": "LOME",
    "Branch": "",
    "Postcode": "",
    "Country": "Togo",
    "Connection": "Active"
  },
  {
    "bankCode": "BCAO",
    "countryCode": "TG",
    "branchCode": "KAR",
    "SWIFT Code": "BCAOTGTGKAR",
    "Bank Name": "BANQUE CENTRALE DES ETATS DE L'AFRIQUE DE L'OUEST",
    "Address": "",
    "City": "KARA",
    "Branch": "KARA BRANCH",
    "Postcode": "",
    "Country": "Togo",
    "Connection": "Active"
  },
  {
    "bankCode": "BCAO",
    "countryCode": "TG",
    "branchCode": "GTG",
    "SWIFT Code": "BCAOTGTG",
    "Bank Name": "BANQUE CENTRALE DES ETATS DE L'AFRIQUE DE L'OUEST",
    "Address": "RUE ABDOULAYE FADIGA",
    "City": "LOME",
    "Branch": "",
    "Postcode": "3679",
    "Country": "Togo",
    "Connection": "Active"
  },
  {
    "bankCode": "BDMA",
    "countryCode": "TG",
    "branchCode": "GTG",
    "SWIFT Code": "BDMATGTG",
    "Bank Name": "BANQUE DE DEVELOPPEMENT DU MALI AU TOGO (BDM-TOGO)",
    "Address": "03 RUE KHRA PLACE ANANI SANTO",
    "City": "LOME",
    "Branch": "",
    "Postcode": "",
    "Country": "Togo",
    "Connection": "Active"
  },
  {
    "bankCode": "BILT",
    "countryCode": "TG",
    "branchCode": "GTG",
    "SWIFT Code": "BILTTGTG",
    "Bank Name": "BANQUE INTERNATIONALE POUR L'AFRIQUE AU TOGO",
    "Address": "13 AVENUE SYLVANUS OLYMPIO",
    "City": "LOME",
    "Branch": "",
    "Postcode": "3302",
    "Country": "Togo",
    "Connection": "Active"
  },
  {
    "bankCode": "BOAD",
    "countryCode": "TG",
    "branchCode": "GTG",
    "SWIFT Code": "BOADTGTG",
    "Bank Name": "BANQUE OUEST AFRICAINE DE DEVELOPPEMENT (BOAD)",
    "Address": "68 AVENUE DE LA LIBERATION, IMMEUBLE BOAD",
    "City": "LOME",
    "Branch": "",
    "Postcode": "2722",
    "Country": "Togo",
    "Connection": "Active"
  },
  {
    "bankCode": "BSAH",
    "countryCode": "TG",
    "branchCode": "GTG",
    "SWIFT Code": "BSAHTGTG",
    "Bank Name": "BSIC TOGO SA",
    "Address": "BOULEVARD DU 13 JANVIER, BSIC TOGO",
    "City": "LOME",
    "Branch": "",
    "Postcode": "2704",
    "Country": "Togo",
    "Connection": "Active"
  },
  {
    "bankCode": "CHRR",
    "countryCode": "TG",
    "branchCode": "GTG",
    "SWIFT Code": "CHRRTGTG",
    "Bank Name": "CAISSE REGIONALE DE REFINANCEMENT HYPOTHECAIRE DE L'UEMOA (CRRH- UEMOA)",
    "Address": "68 AVENUE DE LA LIBERATION, BOAD",
    "City": "LOME",
    "Branch": "",
    "Postcode": "5012",
    "Country": "Togo",
    "Connection": "Active"
  },
  {
    "bankCode": "CORI",
    "countryCode": "TG",
    "branchCode": "GTG",
    "SWIFT Code": "CORITGTG",
    "Bank Name": "CORIS BANK INTERNATIONAL TOGO",
    "Address": "BOULEVARD DU 13 JANVIER",
    "City": "LOME",
    "Branch": "",
    "Postcode": "4032",
    "Country": "Togo",
    "Connection": "Active"
  },
  {
    "bankCode": "ECOC",
    "countryCode": "TG",
    "branchCode": "GTU",
    "SWIFT Code": "ECOCTGTU",
    "Bank Name": "ECOBANK TOGO",
    "Address": "AVENUE SYLVANIUS OLYMPIO",
    "City": "LOME",
    "Branch": "",
    "Postcode": "3302",
    "Country": "Togo",
    "Connection": "Active"
  },
  {
    "bankCode": "ECOC",
    "countryCode": "TG",
    "branchCode": "GTX",
    "SWIFT Code": "ECOCTGTX",
    "Bank Name": "ECOBANK TOGO",
    "Address": "AVENUE SYLVANIUS OLYMPIO",
    "City": "LOME",
    "Branch": "",
    "Postcode": "3302",
    "Country": "Togo",
    "Connection": "Active"
  },
  {
    "bankCode": "ECOC",
    "countryCode": "TG",
    "branchCode": "GTG",
    "SWIFT Code": "ECOCTGTG",
    "Bank Name": "ECOBANK TOGO",
    "Address": "2 RUE DU COMMERCE",
    "City": "LOME",
    "Branch": "",
    "Postcode": "3261",
    "Country": "Togo",
    "Connection": "Active"
  },
  {
    "bankCode": "ECOC",
    "countryCode": "TG",
    "branchCode": "GTS",
    "SWIFT Code": "ECOCTGTS",
    "Bank Name": "ECOBANK TOGO",
    "Address": "AVENUE SYLVANIUS OLYMPIO",
    "City": "LOME",
    "Branch": "",
    "Postcode": "3302",
    "Country": "Togo",
    "Connection": "Active"
  },
  {
    "bankCode": "ECOC",
    "countryCode": "TG",
    "branchCode": "BID",
    "SWIFT Code": "ECOCTGTGBID",
    "Bank Name": "ECOBANK TOGO",
    "Address": "BLD CIRCULAIRE",
    "City": "LOME",
    "Branch": "",
    "Postcode": "2704",
    "Country": "Togo",
    "Connection": "Active"
  },
  {
    "bankCode": "ECOC",
    "countryCode": "TG",
    "branchCode": "GTA",
    "SWIFT Code": "ECOCTGTA",
    "Bank Name": "ECOBANK TOGO",
    "Address": "AVENUE SYLVANIUS OLYMPIO",
    "City": "LOME",
    "Branch": "",
    "Postcode": "3302",
    "Country": "Togo",
    "Connection": "Active"
  },
  {
    "bankCode": "ECOC",
    "countryCode": "TG",
    "branchCode": "EPI",
    "SWIFT Code": "ECOCTGTGEPI",
    "Bank Name": "ECOBANK TOGO",
    "Address": "2 RUE SYLVANUS OLYMPIO",
    "City": "LOME",
    "Branch": "EPROCESS INT.",
    "Postcode": "3261",
    "Country": "Togo",
    "Connection": "Active"
  },
  {
    "bankCode": "ECOC",
    "countryCode": "TG",
    "branchCode": "ETI",
    "SWIFT Code": "ECOCTGTGETI",
    "Bank Name": "ECOBANK TOGO",
    "Address": "20 RUE DU COMMERCE",
    "City": "LOME",
    "Branch": "ETI DEPARTMENT",
    "Postcode": "3302",
    "Country": "Togo",
    "Connection": "Active"
  },
  {
    "bankCode": "ECOC",
    "countryCode": "TG",
    "branchCode": "WPS",
    "SWIFT Code": "ECOCTGTGWPS",
    "Bank Name": "ECOBANK TOGO",
    "Address": "2 RUE DU COMMERCE",
    "City": "LOME",
    "Branch": "SOAPI/WAIPS",
    "Postcode": "3302",
    "Country": "Togo",
    "Connection": "Active"
  },
  {
    "bankCode": "EBID",
    "countryCode": "TG",
    "branchCode": "GTG",
    "SWIFT Code": "EBIDTGTG",
    "Bank Name": "ECOWAS BANK FOR INVESTMENT AND DEVELOPMENT",
    "Address": "128 BOULEVARD DU 13 JANVIER, EBID BUILDING",
    "City": "LOME",
    "Branch": "",
    "Postcode": "2704",
    "Country": "Togo",
    "Connection": "Active"
  },
  {
    "bankCode": "BTCI",
    "countryCode": "TG",
    "branchCode": "GTG",
    "SWIFT Code": "BTCITGTG",
    "Bank Name": "INTERNATIONAL BUSINESS BANK TOGO",
    "Address": "169 BOULEVARD 13 JANVIER",
    "City": "LOME",
    "Branch": "",
    "Postcode": "2932",
    "Country": "Togo",
    "Connection": "Active"
  },
  {
    "bankCode": "DBLN",
    "countryCode": "TG",
    "branchCode": "GTG",
    "SWIFT Code": "DBLNTGTG",
    "Bank Name": "NSIA BANQUE TOGO",
    "Address": "3519 BOULEVARD DU 13 JANVIER, QT DOULASSAME",
    "City": "LOME",
    "Branch": "",
    "Postcode": "3925",
    "Country": "Togo",
    "Connection": "Active"
  },
  {
    "bankCode": "ORBK",
    "countryCode": "TG",
    "branchCode": "GTG",
    "SWIFT Code": "ORBKTGTG",
    "Bank Name": "ORABANK TOGO",
    "Address": "11 AVENUE DU 24 JANVIER",
    "City": "LOME",
    "Branch": "",
    "Postcode": "3467",
    "Country": "Togo",
    "Connection": "Active"
  },
  {
    "bankCode": "ORBK",
    "countryCode": "TG",
    "branchCode": "BJ1",
    "SWIFT Code": "ORBKTGTGBJ1",
    "Bank Name": "ORABANK TOGO",
    "Address": "11 AVENUE DU 24 JANVIER",
    "City": "LOME",
    "Branch": "ORABANK BENIN",
    "Postcode": "3467",
    "Country": "Togo",
    "Connection": "Active"
  },
  {
    "bankCode": "ORBK",
    "countryCode": "TG",
    "branchCode": "OGP",
    "SWIFT Code": "ORBKTGTGOGP",
    "Bank Name": "ORABANK TOGO",
    "Address": "392 RUE DES PLANTAINS",
    "City": "LOME",
    "Branch": "ORAGROUP",
    "Postcode": "2810",
    "Country": "Togo",
    "Connection": "Active"
  },
  {
    "bankCode": "SOTO",
    "countryCode": "TG",
    "branchCode": "GTL",
    "SWIFT Code": "SOTOTGTL",
    "Bank Name": "SOCIETE DES POSTES DU TOGO",
    "Address": "23 AVENUE NICOLAS GRUNITZKY",
    "City": "LOME",
    "Branch": "",
    "Postcode": "2626",
    "Country": "Togo",
    "Connection": "Active"
  },
  {
    "bankCode": "SOGE",
    "countryCode": "TG",
    "branchCode": "GTG",
    "SWIFT Code": "SOGETGTG",
    "Bank Name": "SOCIETE GENERALE BENIN SUCCURSALE DU TOGO",
    "Address": "2983 AVENUE DE LA LIBERATION, TOKOIN-GBADAGO",
    "City": "LOME",
    "Branch": "",
    "Postcode": "5012",
    "Country": "Togo",
    "Connection": "Active"
  },
  {
    "bankCode": "SIAB",
    "countryCode": "TG",
    "branchCode": "GTG",
    "SWIFT Code": "SIABTGTG",
    "Bank Name": "SOCIETE INTER-AFRICAINE DE BANQUE",
    "Address": "14 AVENUE SYLVANUS OLYMPIO, ASSIGAME",
    "City": "LOME",
    "Branch": "",
    "Postcode": "4874",
    "Country": "Togo",
    "Connection": "Active"
  },
  {
    "bankCode": "SUNU",
    "countryCode": "TG",
    "branchCode": "GTG",
    "SWIFT Code": "SUNUTGTG",
    "Bank Name": "SUNU BANK TOGO",
    "Address": "23 AVENUE KLEBER DADJO",
    "City": "LOME",
    "Branch": "",
    "Postcode": "1115",
    "Country": "Togo",
    "Connection": "Active"
  },
  {
    "bankCode": "BPEC",
    "countryCode": "TG",
    "branchCode": "GTG",
    "SWIFT Code": "BPECTGTG",
    "Bank Name": "SUNU BANK TOGO",
    "Address": "23 AVENUE KLEBER DADJO",
    "City": "LOME",
    "Branch": "",
    "Postcode": "1115",
    "Country": "Togo",
    "Connection": "Active"
  },
  {
    "bankCode": "UNTB",
    "countryCode": "TG",
    "branchCode": "GTG",
    "SWIFT Code": "UNTBTGTG",
    "Bank Name": "UNION TOGOLAISE DE BANQUE",
    "Address": "BOULEVARD DU 13 JANVIER",
    "City": "LOME",
    "Branch": "",
    "Postcode": "2704",
    "Country": "Togo",
    "Connection": "Active"
  }
]
module.exports = togo
