const uzbekistan = [
  {
    "countryCode": "GJSO",
    "bankCode": "UZ",
    "branchCode": "Z22",
    "SWIFT Code": "GJSOUZ22",
    "Bank Name": "'BUSINESS DEVELOPMENT BANK' JSCB",
    "Address": "NAVOI STREET , 18A",
    "City": "TASHKENT",
    "Branch": "",
    "Postcode": "100011",
    "Country": "Uzbekistan",
    "Connection": "Active"
  },
  {
    "countryCode": "SNCU",
    "bankCode": "UZ",
    "branchCode": "Z22",
    "SWIFT Code": "SNCUUZ22",
    "Bank Name": "'CENTRAL SECURITIES DEPOSITORY' JOINT-STOCK COMPANY",
    "Address": "MUSTAKILLIK AVENUE, 107",
    "City": "TASHKENT",
    "Branch": "",
    "Postcode": "100170",
    "Country": "Uzbekistan",
    "Connection": "Active"
  },
  {
    "countryCode": "HPCJ",
    "bankCode": "UZ",
    "branchCode": "Z22",
    "SWIFT Code": "HPCJUZ22",
    "Bank Name": "'HI-TECH BANK' PRIVATE CLOSED JOINT STOCK COMMERCIAL BANK",
    "Address": "TARASA SHEVCHENKO STREET , 36A",
    "City": "TASHKENT",
    "Branch": "",
    "Postcode": "100060",
    "Country": "Uzbekistan",
    "Connection": "Active"
  },
  {
    "countryCode": "UJSI",
    "bankCode": "UZ",
    "branchCode": "Z22",
    "SWIFT Code": "UJSIUZ22",
    "Bank Name": "'UZBEK INDUSTRIAL AND CONSTRUCTION BANK' JOINT-STOCK COMMERCIAL BANK",
    "Address": "SHAKHRISABZ STR , 3",
    "City": "TASHKENT",
    "Branch": "",
    "Postcode": "100000",
    "Country": "Uzbekistan",
    "Connection": "Active"
  },
  {
    "countryCode": "ANOB",
    "bankCode": "UZ",
    "branchCode": "Z22",
    "SWIFT Code": "ANOBUZ22",
    "Bank Name": "ANOR BANK UZ",
    "Address": "SAYRAM STREET 5TH DRIVEWAY, NO.4",
    "City": "TASHKENT",
    "Branch": "",
    "Postcode": "100170",
    "Country": "Uzbekistan",
    "Connection": "Active"
  },
  {
    "countryCode": "ASAC",
    "bankCode": "UZ",
    "branchCode": "Z22",
    "SWIFT Code": "ASACUZ22",
    "Bank Name": "ASIA ALLIANCE BANK",
    "Address": "MAKHTUMQULI STR. , 2A",
    "City": "TASHKENT",
    "Branch": "",
    "Postcode": "100047",
    "Country": "Uzbekistan",
    "Connection": "Active"
  },
  {
    "countryCode": "CBUZ",
    "bankCode": "UZ",
    "branchCode": "Z22",
    "SWIFT Code": "CBUZUZ22",
    "Bank Name": "CENTRAL BANK OF THE REPUBLIC UZBEKISTAN",
    "Address": "ISLAM KARIMOV STREET , 6",
    "City": "TASHKENT",
    "Branch": "",
    "Postcode": "100001",
    "Country": "Uzbekistan",
    "Connection": "Active"
  },
  {
    "countryCode": "HJSC",
    "bankCode": "UZ",
    "branchCode": "Z22",
    "SWIFT Code": "HJSCUZ22",
    "Bank Name": "HAYOT BANK JSC",
    "Address": "OSYO, 40, FLOOR 4",
    "City": "TASHKENT",
    "Branch": "",
    "Postcode": "100000",
    "Country": "Uzbekistan",
    "Connection": "Active"
  },
  {
    "countryCode": "INFB",
    "bankCode": "UZ",
    "branchCode": "Z2X",
    "SWIFT Code": "INFBUZ2X",
    "Bank Name": "INVEST FINANCE BANK",
    "Address": "SHEVCHENKO STREET , 1",
    "City": "TASHKENT",
    "Branch": "",
    "Postcode": "100029",
    "Country": "Uzbekistan",
    "Connection": "Active"
  },
  {
    "countryCode": "UZHO",
    "bankCode": "UZ",
    "branchCode": "Z22",
    "SWIFT Code": "UZHOUZ22",
    "Bank Name": "IPOTEKA-BANK",
    "Address": "SHAKHRISABZ STREET , 30",
    "City": "TASHKENT",
    "Branch": "",
    "Postcode": "100000",
    "Country": "Uzbekistan",
    "Connection": "Active"
  },
  {
    "countryCode": "JSCL",
    "bankCode": "UZ",
    "branchCode": "Z22",
    "SWIFT Code": "JSCLUZ22",
    "Bank Name": "JOINT STOCK COMMERCIAL ALOQABANK",
    "Address": "AMIR TEMUR AVENUE , 4",
    "City": "TASHKENT",
    "Branch": "",
    "Postcode": "100047",
    "Country": "Uzbekistan",
    "Connection": "Active"
  },
  {
    "countryCode": "PAKH",
    "bankCode": "UZ",
    "branchCode": "Z22",
    "SWIFT Code": "PAKHUZ22",
    "Bank Name": "JOINT STOCK COMMERCIAL BANK 'AGROBANK'",
    "Address": "MUKIMI , 43",
    "City": "TASHKENT",
    "Branch": "",
    "Postcode": "100096",
    "Country": "Uzbekistan",
    "Connection": "Active"
  },
  {
    "countryCode": "JOCB",
    "bankCode": "UZ",
    "branchCode": "Z22",
    "SWIFT Code": "JOCBUZ22",
    "Bank Name": "JOINT STOCK COMMERCIAL BANK 'TBC BANK'",
    "Address": "AMIR TEMUR KING STREET , 118/A",
    "City": "TASHKENT",
    "Branch": "",
    "Postcode": "100000",
    "Country": "Uzbekistan",
    "Connection": "Active"
  },
  {
    "countryCode": "APXB",
    "bankCode": "UZ",
    "branchCode": "Z22",
    "SWIFT Code": "APXBUZ22",
    "Bank Name": "JOINT STOCK COMPANY 'APEX BANK'",
    "Address": "BUILDING 2, BRATISLAVA STREET",
    "City": "TASHKENT",
    "Branch": "",
    "Postcode": "100070",
    "Country": "Uzbekistan",
    "Connection": "Active"
  },
  {
    "countryCode": "UZGO",
    "bankCode": "UZ",
    "branchCode": "Z22",
    "SWIFT Code": "UZGOUZ22",
    "Bank Name": "JOINT STOCK COMPANY AVO BANK",
    "Address": "A.TEMUR STR , 79A",
    "City": "TASHKENT",
    "Branch": "",
    "Postcode": "100212",
    "Country": "Uzbekistan",
    "Connection": "Active"
  },
  {
    "countryCode": "HSBK",
    "bankCode": "UZ",
    "branchCode": "Z22",
    "SWIFT Code": "HSBKUZ22",
    "Bank Name": "JOINT-STOCK COMMERCIAL BANK 'TENGE BANK'",
    "Address": "BUSINESS CENTER, PARKENT STREET , 66, FLOOR 123",
    "City": "TASHKENT",
    "Branch": "",
    "Postcode": "100007",
    "Country": "Uzbekistan",
    "Connection": "Active"
  },
  {
    "countryCode": "TURO",
    "bankCode": "UZ",
    "branchCode": "Z22",
    "SWIFT Code": "TUROUZ22",
    "Bank Name": "JOINT-STOCK COMMERCIAL BANK TURONBANK",
    "Address": "ABAY STREET , 4A",
    "City": "TASHKENT",
    "Branch": "",
    "Postcode": "100011",
    "Country": "Uzbekistan",
    "Connection": "Active"
  },
  {
    "countryCode": "SCPE",
    "bankCode": "UZ",
    "branchCode": "Z22",
    "SWIFT Code": "SCPEUZ22",
    "Bank Name": "JOINT-STOCK COMMERCIAL XALQ BANK OF THE REPUBLIC OF UZBEKISTAN",
    "Address": "KATARTAL , 46",
    "City": "TASHKENT",
    "Branch": "",
    "Postcode": "100096",
    "Country": "Uzbekistan",
    "Connection": "Active"
  },
  {
    "countryCode": "ASBK",
    "bankCode": "UZ",
    "branchCode": "Z22",
    "SWIFT Code": "ASBKUZ22",
    "Bank Name": "JOINT-STOCK COMPANY 'ASAKABANK'",
    "Address": "NUKUS STREET , 67",
    "City": "TASHKENT",
    "Branch": "",
    "Postcode": "700015",
    "Country": "Uzbekistan",
    "Connection": "Active"
  },
  {
    "countryCode": "UZUM",
    "bankCode": "UZ",
    "branchCode": "Z22",
    "SWIFT Code": "UZUMUZ22",
    "Bank Name": "JOINT-STOCK COMPANY 'UZUM BANK'",
    "Address": "FIDOKOR STREET, 30, MIRABAD DISTRICT",
    "City": "TASHKENT",
    "Branch": "",
    "Postcode": "100015",
    "Country": "Uzbekistan",
    "Connection": "Active"
  },
  {
    "countryCode": "JSCS",
    "bankCode": "UZ",
    "branchCode": "Z22",
    "SWIFT Code": "JSCSUZ22",
    "Bank Name": "JOINT-STOCK COMPANY GARANT BANK",
    "Address": "SAID BARAKA",
    "City": "TASHKENT",
    "Branch": "",
    "Postcode": "700060",
    "Country": "Uzbekistan",
    "Connection": "Active"
  },
  {
    "countryCode": "JOCP",
    "bankCode": "UZ",
    "branchCode": "Z22",
    "SWIFT Code": "JOCPUZ22",
    "Bank Name": "JSC 'POYTAXT BANK'",
    "Address": "ISLOM KARIMOV , 55",
    "City": "TASHKENT",
    "Branch": "",
    "Postcode": "100063",
    "Country": "Uzbekistan",
    "Connection": "Active"
  },
  {
    "countryCode": "JSMI",
    "bankCode": "UZ",
    "branchCode": "Z22",
    "SWIFT Code": "JSMIUZ22",
    "Bank Name": "JSC MADAD INVEST BANK",
    "Address": "MUSTAQILLIK , 312",
    "City": "FERGHANA",
    "Branch": "",
    "Postcode": "150118",
    "Country": "Uzbekistan",
    "Connection": "Active"
  },
  {
    "countryCode": "TCZB",
    "bankCode": "UZ",
    "branchCode": "Z22",
    "SWIFT Code": "TCZBUZ22",
    "Bank Name": "JSC ZIRAAT BANK UZBEKISTAN",
    "Address": "BUNYODKOR AVE , 15/ABV",
    "City": "TASHKENT",
    "Branch": "",
    "Postcode": "100043",
    "Country": "Uzbekistan",
    "Connection": "Active"
  },
  {
    "countryCode": "KHKK",
    "bankCode": "UZ",
    "branchCode": "Z22",
    "SWIFT Code": "KHKKUZ22",
    "Bank Name": "JSCB HAMKORBANK",
    "Address": "BOBUR STREET, 85",
    "City": "ANDIJAN",
    "Branch": "",
    "Postcode": "170119",
    "Country": "Uzbekistan",
    "Connection": "Active"
  },
  {
    "countryCode": "INIP",
    "bankCode": "UZ",
    "branchCode": "Z22",
    "SWIFT Code": "INIPUZ22",
    "Bank Name": "JSIC BANK IPAK YULI",
    "Address": "A. QODIRIY STREET , 2",
    "City": "TASHKENT",
    "Branch": "",
    "Postcode": "100017",
    "Country": "Uzbekistan",
    "Connection": "Active"
  },
  {
    "countryCode": "KACH",
    "bankCode": "UZ",
    "branchCode": "Z22",
    "SWIFT Code": "KACHUZ22",
    "Bank Name": "KAPITALBANK, JSCB",
    "Address": "SAYILGOH STR , 7",
    "City": "TASHKENT",
    "Branch": "",
    "Postcode": "100047",
    "Country": "Uzbekistan",
    "Connection": "Active"
  },
  {
    "countryCode": "KODB",
    "bankCode": "UZ",
    "branchCode": "Z22",
    "SWIFT Code": "KODBUZ22",
    "Bank Name": "KDB BANK UZBEKISTAN JSC",
    "Address": "BUKHORO STREET , 3",
    "City": "TASHKENT",
    "Branch": "",
    "Postcode": "100047",
    "Country": "Uzbekistan",
    "Connection": "Active"
  },
  {
    "countryCode": "MICD",
    "bankCode": "UZ",
    "branchCode": "Z22",
    "SWIFT Code": "MICDUZ22",
    "Bank Name": "MICROCREDITBANK",
    "Address": "LUTFIY STREET , 14",
    "City": "TASHKENT",
    "Branch": "",
    "Postcode": "100096",
    "Country": "Uzbekistan",
    "Connection": "Active"
  },
  {
    "countryCode": "MFRU",
    "bankCode": "UZ",
    "branchCode": "Z22",
    "SWIFT Code": "MFRUUZ22",
    "Bank Name": "MINISTRY OF FINANCE THE REPUBLIC OF UZBEKISTAN",
    "Address": "ISTIKLOL STREET, HOUSE 29",
    "City": "TASHKENT",
    "Branch": "",
    "Postcode": "100017",
    "Country": "Uzbekistan",
    "Connection": "Active"
  },
  {
    "countryCode": "NBFA",
    "bankCode": "UZ",
    "branchCode": "Z2X",
    "SWIFT Code": "NBFAUZ2X",
    "Bank Name": "NATIONAL BANK FOR FOREIGN ECONOMIC ACTIVITY OF THE REPUBLIC OF UZBEKISTAN",
    "Address": "AMIR TEMUR AVE, 101, YUNUSABAD DIST",
    "City": "TASHKENT",
    "Branch": "",
    "Postcode": "100084",
    "Country": "Uzbekistan",
    "Connection": "Active"
  },
  {
    "countryCode": "RVBK",
    "bankCode": "UZ",
    "branchCode": "Z22",
    "SWIFT Code": "RVBKUZ22",
    "Bank Name": "OCTOBANK JSC",
    "Address": "FURKAT , 2",
    "City": "TASHKENT",
    "Branch": "",
    "Postcode": "100021",
    "Country": "Uzbekistan",
    "Connection": "Active"
  },
  {
    "countryCode": "ORFB",
    "bankCode": "UZ",
    "branchCode": "Z22",
    "SWIFT Code": "ORFBUZ22",
    "Bank Name": "PJSCB 'ORIENT FINANCE'",
    "Address": "YAKKACHINOR STR , 7A",
    "City": "TASHKENT",
    "Branch": "",
    "Postcode": "100029",
    "Country": "Uzbekistan",
    "Connection": "Active"
  },
  {
    "countryCode": "PJUN",
    "bankCode": "UZ",
    "branchCode": "Z22",
    "SWIFT Code": "PJUNUZ22",
    "Bank Name": "PJSCB UNIVERSAL BANK",
    "Address": "SHOHRUHOBOD NO",
    "City": "KOKAND",
    "Branch": "",
    "Postcode": "150700",
    "Country": "Uzbekistan",
    "Connection": "Active"
  },
  {
    "countryCode": "DVRB",
    "bankCode": "UZ",
    "branchCode": "Z22",
    "SWIFT Code": "DVRBUZ22",
    "Bank Name": "PRIVATE JOINT-STOCK COMMERCIAL BANK 'DAVR BANK'",
    "Address": "BLOCK A, NAVOI-ZARQAYNAR",
    "City": "TASHKENT",
    "Branch": "",
    "Postcode": "100021",
    "Country": "Uzbekistan",
    "Connection": "Active"
  },
  {
    "countryCode": "TRSA",
    "bankCode": "UZ",
    "branchCode": "Z22",
    "SWIFT Code": "TRSAUZ22",
    "Bank Name": "TRUSTBANK, PRIVATE JOINT-STOCK BANK",
    "Address": "NAVOI , 7",
    "City": "TASHKENT",
    "Branch": "",
    "Postcode": "100011",
    "Country": "Uzbekistan",
    "Connection": "Active"
  },
  {
    "countryCode": "ZRCE",
    "bankCode": "UZ",
    "branchCode": "Z22",
    "SWIFT Code": "ZRCEUZ22",
    "Bank Name": "UZBEK REPUBLICAN CURRENCY EXCHANGE JSC",
    "Address": "UZBEK REPUBLICAN CURRENCY EXCHANGE, SH. RASHIDOV AVE.,, 4",
    "City": "TASHKENT",
    "Branch": "",
    "Postcode": "100084",
    "Country": "Uzbekistan",
    "Connection": "Active"
  },
  {
    "countryCode": "JCYN",
    "bankCode": "UZ",
    "branchCode": "Z22",
    "SWIFT Code": "JCYNUZ22",
    "Bank Name": "YANGI BANK",
    "Address": "AMIR TEMUR STREET, 99, YUNUSABAD DISTRICT",
    "City": "TASHKENT",
    "Branch": "",
    "Postcode": "100084",
    "Country": "Uzbekistan",
    "Connection": "Active"
  }
]
module.exports = uzbekistan
