const vanuatu = [
  {
    "bankCode": "ALBU",
    "countryCode": "VU",
    "branchCode": "UVV",
    "SWIFT Code": "ALBUVUVV",
    "Bank Name": "ALPEN BARUCH BANK LIMITED",
    "Address": "OPPOSITE TANA CINE, LINI HIGHWAY, MELCOFEE AREA",
    "City": "PORT VILA",
    "Branch": "",
    "Postcode": "",
    "Country": "Vanuatu",
    "Connection": "Active"
  },
  {
    "bankCode": "ANZB",
    "countryCode": "VU",
    "branchCode": "UVX",
    "SWIFT Code": "ANZBVUVX",
    "Bank Name": "ANZ BANK (VANUATU) LTD",
    "Address": "ANZ HOUSE, KUMUL HIGHWAY",
    "City": "PORT VILA",
    "Branch": "",
    "Postcode": "",
    "Country": "Vanuatu",
    "Connection": "Active"
  },
  {
    "bankCode": "AMBV",
    "countryCode": "VU",
    "branchCode": "UVU",
    "SWIFT Code": "AMBVVUVU",
    "Bank Name": "ASIA MERCHANT BANK LIMITED",
    "Address": "FLOOR 1, HAWKES LAW HOUSE, RUE PASTEUR",
    "City": "PORT VILA",
    "Branch": "",
    "Postcode": "",
    "Country": "Vanuatu",
    "Connection": "Active"
  },
  {
    "bankCode": "BOSP",
    "countryCode": "VU",
    "branchCode": "UVX",
    "SWIFT Code": "BOSPVUVX",
    "Bank Name": "BANK SOUTH PACIFIC (VANUATU) LIMITED",
    "Address": "KUMUL HIGHWAY",
    "City": "PORT VILA",
    "Branch": "",
    "Postcode": "",
    "Country": "Vanuatu",
    "Connection": "Active"
  },
  {
    "bankCode": "BRED",
    "countryCode": "VU",
    "branchCode": "UVU",
    "SWIFT Code": "BREDVUVU",
    "Bank Name": "BRED (VANUATU) LTD",
    "Address": "LINI HIGHWAY",
    "City": "PORT VILA",
    "Branch": "",
    "Postcode": "",
    "Country": "Vanuatu",
    "Connection": "Active"
  },
  {
    "bankCode": "DIOC",
    "countryCode": "VU",
    "branchCode": "UVV",
    "SWIFT Code": "DIOCVUVV",
    "Bank Name": "DIGITAL OCEAN BANK LIMITED",
    "Address": "1F, ORCHID B 004, RUE PASTEUR",
    "City": "PORT VILA",
    "Branch": "",
    "Postcode": "",
    "Country": "Vanuatu",
    "Connection": "Active"
  },
  {
    "bankCode": "MGCB",
    "countryCode": "VU",
    "branchCode": "UVV",
    "SWIFT Code": "MGCBVUVV",
    "Bank Name": "MG COMMERCIAL BANK LIMITED",
    "Address": "FLOOR 1, THE VILA MALL",
    "City": "PORT VILA",
    "Branch": "",
    "Postcode": "",
    "Country": "Vanuatu",
    "Connection": "Active"
  },
  {
    "bankCode": "NBOV",
    "countryCode": "VU",
    "branchCode": "UVU",
    "SWIFT Code": "NBOVVUVU",
    "Bank Name": "NATIONAL BANK OF VANUATU LIMITED",
    "Address": "AIR VANUATU BLDG, RUE DE PARIS",
    "City": "PORT VILA",
    "Branch": "",
    "Postcode": "",
    "Country": "Vanuatu",
    "Connection": "Active"
  },
  {
    "bankCode": "PPBL",
    "countryCode": "VU",
    "branchCode": "UVU",
    "SWIFT Code": "PPBLVUVU",
    "Bank Name": "PACIFIC PRIVATE BANK LIMITED",
    "Address": "FLOOR 1, GOVANT BUILDING, 278 KUMUL HIGHWAY",
    "City": "PORT VILA",
    "Branch": "",
    "Postcode": "",
    "Country": "Vanuatu",
    "Connection": "Active"
  },
  {
    "bankCode": "RBVA",
    "countryCode": "VU",
    "branchCode": "UVU",
    "SWIFT Code": "RBVAVUVU",
    "Bank Name": "RESERVE BANK OF VANUATU",
    "Address": "EMMANUEL BRUNET STREET",
    "City": "PORT VILA",
    "Branch": "",
    "Postcode": "",
    "Country": "Vanuatu",
    "Connection": "Active"
  },
  {
    "bankCode": "WANF",
    "countryCode": "VU",
    "branchCode": "UVV",
    "SWIFT Code": "WANFVUVV",
    "Bank Name": "WANFUTENG BANK LIMITED",
    "Address": "CHURCHILL HOUSE, 65 KUMUL HIGHWAY",
    "City": "PORT VILA",
    "Branch": "",
    "Postcode": "",
    "Country": "Vanuatu",
    "Connection": "Active"
  },
  {
    "bankCode": "WEMT",
    "countryCode": "VU",
    "branchCode": "UVU",
    "SWIFT Code": "WEMTVUVU",
    "Bank Name": "WESTMINSTER BANK",
    "Address": "FLOOR 2, TANA RUSSET PLAZA, LINI HIGHWAY",
    "City": "PORT VILA",
    "Branch": "",
    "Postcode": "",
    "Country": "Vanuatu",
    "Connection": "Active"
  }
]
module.exports = vanuatu
