const zambia = [
  {
    "countryCode": "ABBA",
    "bankCode": "ZM",
    "branchCode": "MLU",
    "SWIFT Code": "ABBAZMLU",
    "Bank Name": "AB BANK ZAMBIA LTD.",
    "Address": "FLOOR 2, CHAINDA SQUARE, STAND 7393 CAIRO ROAD",
    "City": "LUSAKA",
    "Branch": "",
    "Postcode": "10101",
    "Country": "Zambia",
    "Connection": "Active"
  },
  {
    "countryCode": "BARC",
    "bankCode": "ZM",
    "branchCode": "KPC",
    "SWIFT Code": "BARCZMLXKPC",
    "Bank Name": "ABSA BANK ZAMBIA PLC",
    "Address": "BARCLAYS, OBOTE AVENUE",
    "City": "KITWE",
    "Branch": "KITWE PROCESSING CENTRE",
    "Postcode": "50100",
    "Country": "Zambia",
    "Connection": "Active"
  },
  {
    "countryCode": "BARC",
    "bankCode": "ZM",
    "branchCode": "MLX",
    "SWIFT Code": "BARCZMLX",
    "Bank Name": "ABSA BANK ZAMBIA PLC",
    "Address": "ABSA HOUSE STAND NO. 2374 KELVIN, SIWALE ROAD,SHOW GROUNDS",
    "City": "LUSAKA",
    "Branch": "HEAD OFFICE",
    "Postcode": "10101",
    "Country": "Zambia",
    "Connection": "Active"
  },
  {
    "countryCode": "AZAM",
    "bankCode": "ZM",
    "branchCode": "MLU",
    "SWIFT Code": "AZAMZMLU",
    "Bank Name": "ACCESS BANK ZAMBIA LIMITED",
    "Address": "PLOT 682, PLOT 682 CAIRO ROAD NORTH END",
    "City": "LUSAKA",
    "Branch": "",
    "Postcode": "",
    "Country": "Zambia",
    "Connection": "Active"
  },
  {
    "countryCode": "FMBZ",
    "bankCode": "ZM",
    "branchCode": "MLX",
    "SWIFT Code": "FMBZZMLX",
    "Bank Name": "AFRICAN BANKING CORPORATION ZAMBIA",
    "Address": "FLOOR GROUND, ATLAS MARA HOUSE, CORNER OF CHURCH/NASSER ROADS, RIDGEWAY",
    "City": "LUSAKA",
    "Branch": "",
    "Postcode": "10101",
    "Country": "Zambia",
    "Connection": "Active"
  },
  {
    "countryCode": "BKCH",
    "bankCode": "ZM",
    "branchCode": "MLU",
    "SWIFT Code": "BKCHZMLU",
    "Bank Name": "BANK OF CHINA (ZAMBIA) LTD",
    "Address": "PLOT NO.2339 KABELENGA ROAD",
    "City": "LUSAKA",
    "Branch": "",
    "Postcode": "10101",
    "Country": "Zambia",
    "Connection": "Active"
  },
  {
    "countryCode": "BAZA",
    "bankCode": "ZM",
    "branchCode": "MLA",
    "SWIFT Code": "BAZAZMLA",
    "Bank Name": "BANK OF ZAMBIA",
    "Address": "CAIRO ROAD BANK SQUARE",
    "City": "LUSAKA",
    "Branch": "",
    "Postcode": "10101",
    "Country": "Zambia",
    "Connection": "Active"
  },
  {
    "countryCode": "BAZA",
    "bankCode": "ZM",
    "branchCode": "MLU",
    "SWIFT Code": "BAZAZMLU",
    "Bank Name": "BANK OF ZAMBIA",
    "Address": "BANK SQUARE, CAIRO ROAD",
    "City": "LUSAKA",
    "Branch": "",
    "Postcode": "10101",
    "Country": "Zambia",
    "Connection": "Active"
  },
  {
    "countryCode": "BAZA",
    "bankCode": "ZM",
    "branchCode": "ASA",
    "SWIFT Code": "BAZAZMLUASA",
    "Bank Name": "BANK OF ZAMBIA",
    "Address": "",
    "City": "LUSAKA",
    "Branch": "AUTHORISED SETTLEMENT AGENT",
    "Postcode": "10101",
    "Country": "Zambia",
    "Connection": "Active"
  },
  {
    "countryCode": "CITI",
    "bankCode": "ZM",
    "branchCode": "MLU",
    "SWIFT Code": "CITIZMLU",
    "Bank Name": "CITIBANK ZAMBIA LTD",
    "Address": "CITIBANK HOUSE, STAND 4646 ADDIS ABABA ROUNDABOUT",
    "City": "LUSAKA",
    "Branch": "",
    "Postcode": "10101",
    "Country": "Zambia",
    "Connection": "Active"
  },
  {
    "countryCode": "ECOC",
    "bankCode": "ZM",
    "branchCode": "MLU",
    "SWIFT Code": "ECOCZMLU",
    "Bank Name": "ECOBANK ZAMBIA",
    "Address": "THABO MBEKI ROAD",
    "City": "LUSAKA",
    "Branch": "",
    "Postcode": "10101",
    "Country": "Zambia",
    "Connection": "Active"
  },
  {
    "countryCode": "FALL",
    "bankCode": "ZM",
    "branchCode": "MLU",
    "SWIFT Code": "FALLZMLU",
    "Bank Name": "FIRST ALLIANCE BANK",
    "Address": "ALLIANCE HOUSE, PLOT 627 CAIRO ROAD",
    "City": "LUSAKA",
    "Branch": "",
    "Postcode": "10101",
    "Country": "Zambia",
    "Connection": "Active"
  },
  {
    "countryCode": "FRCG",
    "bankCode": "ZM",
    "branchCode": "MLU",
    "SWIFT Code": "FRCGZMLU",
    "Bank Name": "FIRST CAPITAL BANK LIMITED",
    "Address": "FLOOR GF, KWACHA PENSION HOUSE, PLOT 4604 TITO ROAD",
    "City": "LUSAKA",
    "Branch": "",
    "Postcode": "",
    "Country": "Zambia",
    "Connection": "Active"
  },
  {
    "countryCode": "FIRN",
    "bankCode": "ZM",
    "branchCode": "MLX",
    "SWIFT Code": "FIRNZMLX",
    "Bank Name": "FIRST NATIONAL BANK ZAMBIA LIMITED",
    "Address": "STAND NO 22768 CNR GREAT EAST, ROAD, THABO MBEKI ROAD",
    "City": "LUSAKA",
    "Branch": "",
    "Postcode": "10101",
    "Country": "Zambia",
    "Connection": "Active"
  },
  {
    "countryCode": "INZA",
    "bankCode": "ZM",
    "branchCode": "MLX",
    "SWIFT Code": "INZAZMLX",
    "Bank Name": "INDO-ZAMBIA BANK",
    "Address": "PLOT NO. 6907 CAIRO ROAD",
    "City": "LUSAKA",
    "Branch": "",
    "Postcode": "10101",
    "Country": "Zambia",
    "Connection": "Active"
  },
  {
    "countryCode": "VSTR",
    "bankCode": "ZM",
    "branchCode": "MLU",
    "SWIFT Code": "VSTRZMLU",
    "Bank Name": "INVESTRUST BANK LTD",
    "Address": "INVESTRUST HOUSE, 28, PLOT 4227 FREEDOMWAY",
    "City": "LUSAKA",
    "Branch": "",
    "Postcode": "10101",
    "Country": "Zambia",
    "Connection": "Active"
  },
  {
    "countryCode": "RMIE",
    "bankCode": "ZM",
    "branchCode": "ML2",
    "SWIFT Code": "RMIEZML2",
    "Bank Name": "ROYAL MONZE INSTITUTE OF MEDICAL EVANGELISM LIMITED",
    "Address": "017 FAIRVIEW ROAD",
    "City": "MONZE",
    "Branch": "",
    "Postcode": "11800",
    "Country": "Zambia",
    "Connection": "Active"
  },
  {
    "countryCode": "SBIC",
    "bankCode": "ZM",
    "branchCode": "MLX",
    "SWIFT Code": "SBICZMLX",
    "Bank Name": "STANBIC BANK ZAMBIA LTD.",
    "Address": "STANBIC HOUSE, PLOT 2375 ADIDIS ABABA DRIVE, LONG ACRES",
    "City": "LUSAKA",
    "Branch": "LUSAKA BRANCH",
    "Postcode": "10101",
    "Country": "Zambia",
    "Connection": "Active"
  },
  {
    "countryCode": "SCBL",
    "bankCode": "ZM",
    "branchCode": "MLX",
    "SWIFT Code": "SCBLZMLX",
    "Bank Name": "STANDARD CHARTERED BANK ZAMBIA PLC",
    "Address": "STANDARD CHARTERED HOUSE, CAIRO ROAD",
    "City": "LUSAKA",
    "Branch": "",
    "Postcode": "10101",
    "Country": "Zambia",
    "Connection": "Active"
  },
  {
    "countryCode": "SCBL",
    "bankCode": "ZM",
    "branchCode": "SSU",
    "SWIFT Code": "SCBLZMLXSSU",
    "Bank Name": "STANDARD CHARTERED BANK ZAMBIA PLC",
    "Address": "STANDARD CHARTERED HOUSE, CAIRO ROAD",
    "City": "LUSAKA",
    "Branch": "SECURITIES SERVICES UNIT",
    "Postcode": "10101",
    "Country": "Zambia",
    "Connection": "Active"
  },
  {
    "countryCode": "UNAF",
    "bankCode": "ZM",
    "branchCode": "MLU",
    "SWIFT Code": "UNAFZMLU",
    "Bank Name": "UNITED BANK FOR AFRICA ZAMBIA LIMITED",
    "Address": "STAND 22768 THABO MBEKI ROAD",
    "City": "LUSAKA",
    "Branch": "",
    "Postcode": "10101",
    "Country": "Zambia",
    "Connection": "Active"
  },
  {
    "countryCode": "ZICB",
    "bankCode": "ZM",
    "branchCode": "MLU",
    "SWIFT Code": "ZICBZMLU",
    "Bank Name": "ZAMBIA INDUSTRIAL COMMERCIAL BANK LIMITED",
    "Address": "FLOOR 5, LONGACRES MALL OFFICE, BLOCK NO. 27395 STAND ALICK NKHATA, ROAD MASS MEDIA",
    "City": "LUSAKA",
    "Branch": "",
    "Postcode": "10101",
    "Country": "Zambia",
    "Connection": "Active"
  },
  {
    "countryCode": "ZNCO",
    "bankCode": "ZM",
    "branchCode": "MLU",
    "SWIFT Code": "ZNCOZMLU",
    "Bank Name": "ZAMBIA NATIONAL COMMERCIAL BANK PLC",
    "Address": "CAIRO ROAD",
    "City": "LUSAKA",
    "Branch": "",
    "Postcode": "10101",
    "Country": "Zambia",
    "Connection": "Active"
  }
]
module.exports = zambia
