const zimbabwe = [
  {
    "countryCode": "ABTI",
    "bankCode": "ZW",
    "branchCode": "WH2",
    "SWIFT Code": "ABTIZWH2",
    "Bank Name": "ABC STOCKBROKERS (PRIVATE) LIMITED",
    "Address": "FLOOR 1, HERITAGE HOUSE, 67 SAMORA MACHEL AVENUE",
    "City": "HARARE",
    "Branch": "",
    "Postcode": "",
    "Country": "Zimbabwe",
    "Connection": "Active"
  },
  {
    "countryCode": "AGRZ",
    "bankCode": "ZW",
    "branchCode": "WHA",
    "SWIFT Code": "AGRZZWHA",
    "Bank Name": "AFC COMMERCIAL BANK LIMITED",
    "Address": "HURUDZA HOUSE, 14-16 NELSON MANDELA AVENUE",
    "City": "HARARE",
    "Branch": "",
    "Postcode": "",
    "Country": "Zimbabwe",
    "Connection": "Active"
  },
  {
    "countryCode": "FMBZ",
    "bankCode": "ZW",
    "branchCode": "WHX",
    "SWIFT Code": "FMBZZWHX",
    "Bank Name": "AFRICAN BANKING CORP.OF ZIMBABWE LTD.",
    "Address": "MOUNT PLEASANT BUSINESS PARK, 1 ENDEAVOUR CRESCENT",
    "City": "HARARE",
    "Branch": "",
    "Postcode": "",
    "Country": "Zimbabwe",
    "Connection": "Active"
  },
  {
    "countryCode": "AFCN",
    "bankCode": "ZW",
    "branchCode": "WHA",
    "SWIFT Code": "AFCNZWHA",
    "Bank Name": "AFRICAN CENTURY LIMITED",
    "Address": "FLOOR 0, AFRICAN CENTURY GARDENS, 153 JOSIAH CHINAMANO",
    "City": "HARARE",
    "Branch": "",
    "Postcode": "",
    "Country": "Zimbabwe",
    "Connection": "Active"
  },
  {
    "countryCode": "COBZ",
    "bankCode": "ZW",
    "branchCode": "WHA",
    "SWIFT Code": "COBZZWHA",
    "Bank Name": "CBZ BANK LIMITED",
    "Address": "UNION HOUSE, 60 KWAME NKRUMAH AVENUE",
    "City": "HARARE",
    "Branch": "",
    "Postcode": "",
    "Country": "Zimbabwe",
    "Connection": "Active"
  },
  {
    "countryCode": "CABS",
    "bankCode": "ZW",
    "branchCode": "WHA",
    "SWIFT Code": "CABSZWHA",
    "Bank Name": "CENTRAL AFRICA BUILDING SOCIETY",
    "Address": "NORTHEND CLOSE, NORTHRIDGE PARK HIGHLANDS",
    "City": "HARARE",
    "Branch": "",
    "Postcode": "",
    "Country": "Zimbabwe",
    "Connection": "Active"
  },
  {
    "countryCode": "COCU",
    "bankCode": "ZW",
    "branchCode": "WHA",
    "SWIFT Code": "COCUZWHA",
    "Bank Name": "COMESA CLEARING HOUSE",
    "Address": "4 PURBECK CLOSE HIGHLANDS",
    "City": "HARARE",
    "Branch": "",
    "Postcode": "",
    "Country": "Zimbabwe",
    "Connection": "Active"
  },
  {
    "countryCode": "ECOC",
    "bankCode": "ZW",
    "branchCode": "WHX",
    "SWIFT Code": "ECOCZWHX",
    "Bank Name": "ECOBANK ZIMBABWE LIMITED",
    "Address": "SAM LEVY'S OFFICE PARK, BLOCK A, 2 PIERS ROAD, BORROWDALE",
    "City": "HARARE",
    "Branch": "",
    "Postcode": "",
    "Country": "Zimbabwe",
    "Connection": "Active"
  },
  {
    "countryCode": "EMPW",
    "bankCode": "ZW",
    "branchCode": "WHX",
    "SWIFT Code": "EMPWZWHX",
    "Bank Name": "EMPOWERBANK LIMITED",
    "Address": "FLOOR 1, BLOCK 4 TENDESEKA OFFICE, PARK 1 RENFREW ROAD, SAMORA MACHEL, AVENUE EASTLEA",
    "City": "HARARE",
    "Branch": "",
    "Postcode": "",
    "Country": "Zimbabwe",
    "Connection": "Active"
  },
  {
    "countryCode": "FBCP",
    "bankCode": "ZW",
    "branchCode": "WHA",
    "SWIFT Code": "FBCPZWHA",
    "Bank Name": "FBC BANK LTD",
    "Address": "FLOOR 6, FBC CENTRE, 45 NELSON MANDELA AVENUE",
    "City": "HARARE",
    "Branch": "",
    "Postcode": "",
    "Country": "Zimbabwe",
    "Connection": "Active"
  },
  {
    "countryCode": "FRCG",
    "bankCode": "ZW",
    "branchCode": "WHX",
    "SWIFT Code": "FRCGZWHX",
    "Bank Name": "FIRST CAPITAL BANK IN ASSOCIATION WITH BARCLAYS",
    "Address": "FLOOR 2, BARCLAYS HOUSE, 12 1ST ST FIRST STREET JASON MOYO A",
    "City": "HARARE",
    "Branch": "",
    "Postcode": "",
    "Country": "Zimbabwe",
    "Connection": "Active"
  },
  {
    "countryCode": "BARC",
    "bankCode": "ZW",
    "branchCode": "WHX",
    "SWIFT Code": "BARCZWHX",
    "Bank Name": "FIRST CAPITAL BANK LIMITED",
    "Address": "BARCLAYS HOUSE CORNER FIRST STREET, AND JASON MAYO AVENUE",
    "City": "HARARE",
    "Branch": "",
    "Postcode": "",
    "Country": "Zimbabwe",
    "Connection": "Active"
  },
  {
    "countryCode": "GBSP",
    "bankCode": "ZW",
    "branchCode": "WHA",
    "SWIFT Code": "GBSPZWHA",
    "Bank Name": "GETBUCKS MICROFINANCE BANK LIMITED",
    "Address": "1ST, MIPF BUILDING, 5 CENTRAL AVENUE",
    "City": "HARARE",
    "Branch": "",
    "Postcode": "",
    "Country": "Zimbabwe",
    "Connection": "Active"
  },
  {
    "countryCode": "IESP",
    "bankCode": "ZW",
    "branchCode": "WH2",
    "SWIFT Code": "IESPZWH2",
    "Bank Name": "IMARA EDWARDS SECURITIES (PRIVATE) LIMITED",
    "Address": "FLOOR 1, TENDESEKA OFFICE PARK, BLOCK 2 SAMORA MACHEL AVENUE EAST, EASTLEA",
    "City": "HARARE",
    "Branch": "",
    "Postcode": "",
    "Country": "Zimbabwe",
    "Connection": "Active"
  },
  {
    "countryCode": "ZDBL",
    "bankCode": "ZW",
    "branchCode": "WHA",
    "SWIFT Code": "ZDBLZWHA",
    "Bank Name": "INFRASTRUCTURE DEVELOPMENT BANK OF ZIMBABWE",
    "Address": "IDBZ HOUSE, 99 ROTTEN ROW",
    "City": "HARARE",
    "Branch": "",
    "Postcode": "",
    "Country": "Zimbabwe",
    "Connection": "Active"
  },
  {
    "countryCode": "NDOR",
    "bankCode": "ZW",
    "branchCode": "WHX",
    "SWIFT Code": "NDORZWHX",
    "Bank Name": "INNBUCKS MICROBANK LIMITED",
    "Address": "123 NELSON MANDELA AVENUE",
    "City": "HARARE",
    "Branch": "",
    "Postcode": "",
    "Country": "Zimbabwe",
    "Connection": "Active"
  },
  {
    "countryCode": "LMLD",
    "bankCode": "ZW",
    "branchCode": "WHA",
    "SWIFT Code": "LMLDZWHA",
    "Bank Name": "LION MICROFINANCE LIMITED",
    "Address": "FLOOR GF, CENTURY TOWERS, 45 SAMORA MACHEL AVENUE",
    "City": "HARARE",
    "Branch": "",
    "Postcode": "",
    "Country": "Zimbabwe",
    "Connection": "Active"
  },
  {
    "countryCode": "MBOZ",
    "bankCode": "ZW",
    "branchCode": "WHA",
    "SWIFT Code": "MBOZZWHA",
    "Bank Name": "METBANK LIMITED",
    "Address": "FLOOR 6, METROPOLITAN HOUSE, 3 CENTRAL AVENUE",
    "City": "HARARE",
    "Branch": "",
    "Postcode": "",
    "Country": "Zimbabwe",
    "Connection": "Active"
  },
  {
    "countryCode": "NABY",
    "bankCode": "ZW",
    "branchCode": "WHA",
    "SWIFT Code": "NABYZWHA",
    "Bank Name": "NATIONAL BUILDING SOCIETY",
    "Address": "SOCIAL SECURITY CENTRE, 14 SAM NUJOMA AND J NYERERE",
    "City": "HARARE",
    "Branch": "",
    "Postcode": "",
    "Country": "Zimbabwe",
    "Connection": "Active"
  },
  {
    "countryCode": "MBCA",
    "bankCode": "ZW",
    "branchCode": "WHX",
    "SWIFT Code": "MBCAZWHX",
    "Bank Name": "NEDBANK ZIMBABWE LIMITED",
    "Address": "FLOOR 14, OLD MUTUAL CENTRE, CNR 3RD STREET AND J. MOYO AVENUE",
    "City": "HARARE",
    "Branch": "",
    "Postcode": "",
    "Country": "Zimbabwe",
    "Connection": "Active"
  },
  {
    "countryCode": "NMBL",
    "bankCode": "ZW",
    "branchCode": "BYO",
    "SWIFT Code": "NMBLZWHXBYO",
    "Bank Name": "NMB BANK LIMITED",
    "Address": "",
    "City": "BULAWAYO",
    "Branch": "BULAWAYO BRANCH",
    "Postcode": "",
    "Country": "Zimbabwe",
    "Connection": "Active"
  },
  {
    "countryCode": "NMBL",
    "bankCode": "ZW",
    "branchCode": "WHX",
    "SWIFT Code": "NMBLZWHX",
    "Bank Name": "NMB BANK LIMITED",
    "Address": "FLOOR 1, UNITY COURT, CORNER UNION AVENUE/FIRST STREET",
    "City": "HARARE",
    "Branch": "",
    "Postcode": "",
    "Country": "Zimbabwe",
    "Connection": "Active"
  },
  {
    "countryCode": "PWSB",
    "bankCode": "ZW",
    "branchCode": "WHX",
    "SWIFT Code": "PWSBZWHX",
    "Bank Name": "PEOPLE'S OWN SAVINGS BANK",
    "Address": "FLOOR 6, CAUSEWAY BUILDING, CORNER THIRD STREET CENTRAL AVENUE",
    "City": "HARARE",
    "Branch": "",
    "Postcode": "",
    "Country": "Zimbabwe",
    "Connection": "Active"
  },
  {
    "countryCode": "REBZ",
    "bankCode": "ZW",
    "branchCode": "WHB",
    "SWIFT Code": "REBZZWHB",
    "Bank Name": "RESERVE BANK OF ZIMBABWE",
    "Address": "",
    "City": "HARARE",
    "Branch": "",
    "Postcode": "",
    "Country": "Zimbabwe",
    "Connection": "Active"
  },
  {
    "countryCode": "REBZ",
    "bankCode": "ZW",
    "branchCode": "WHA",
    "SWIFT Code": "REBZZWHA",
    "Bank Name": "RESERVE BANK OF ZIMBABWE",
    "Address": "",
    "City": "HARARE",
    "Branch": "",
    "Postcode": "",
    "Country": "Zimbabwe",
    "Connection": "Active"
  },
  {
    "countryCode": "REBZ",
    "bankCode": "ZW",
    "branchCode": "WHQ",
    "SWIFT Code": "REBZZWHQ",
    "Bank Name": "RESERVE BANK OF ZIMBABWE",
    "Address": "80 SAMORA MACHEL AVENUE",
    "City": "HARARE",
    "Branch": "",
    "Postcode": "",
    "Country": "Zimbabwe",
    "Connection": "Active"
  },
  {
    "countryCode": "REBZ",
    "bankCode": "ZW",
    "branchCode": "WHX",
    "SWIFT Code": "REBZZWHX",
    "Bank Name": "RESERVE BANK OF ZIMBABWE",
    "Address": "76 SAMORA MACHEL AVENUE",
    "City": "HARARE",
    "Branch": "",
    "Postcode": "",
    "Country": "Zimbabwe",
    "Connection": "Active"
  },
  {
    "countryCode": "REBZ",
    "bankCode": "ZW",
    "branchCode": "PCH",
    "SWIFT Code": "REBZZWHXPCH",
    "Bank Name": "RESERVE BANK OF ZIMBABWE",
    "Address": "80 SAMORA MACHEL AVENUE",
    "City": "HARARE",
    "Branch": "",
    "Postcode": "",
    "Country": "Zimbabwe",
    "Connection": "Active"
  },
  {
    "countryCode": "SBIC",
    "bankCode": "ZW",
    "branchCode": "WHX",
    "SWIFT Code": "SBICZWHX",
    "Bank Name": "STANBIC BANK ZIMBABWE LIMITED",
    "Address": "OTTOMAN HOUSE, 59 SAMORA MACHEL AVENUE",
    "City": "HARARE",
    "Branch": "",
    "Postcode": "",
    "Country": "Zimbabwe",
    "Connection": "Active"
  },
  {
    "countryCode": "SCBL",
    "bankCode": "ZW",
    "branchCode": "WHX",
    "SWIFT Code": "SCBLZWHX",
    "Bank Name": "STANDARD CHARTERED BANK ZIMBABWE LIMITED",
    "Address": "FLOOR 1, AFRICA UNITY SQUARE 68, NELSON MANDELA AVE / SAM NUJOMA ST",
    "City": "HARARE",
    "Branch": "",
    "Postcode": "",
    "Country": "Zimbabwe",
    "Connection": "Active"
  },
  {
    "countryCode": "SCBL",
    "bankCode": "ZW",
    "branchCode": "SSU",
    "SWIFT Code": "SCBLZWHXSSU",
    "Bank Name": "STANDARD CHARTERED BANK ZIMBABWE LIMITED",
    "Address": "FLOOR 1, AFRICA UNITY SQUARE 68, NELSON MANDELA AVE / SAM NUJOMA ST",
    "City": "HARARE",
    "Branch": "SECURITIES SERVICES UNIT",
    "Postcode": "",
    "Country": "Zimbabwe",
    "Connection": "Active"
  },
  {
    "countryCode": "STBL",
    "bankCode": "ZW",
    "branchCode": "WHX",
    "SWIFT Code": "STBLZWHX",
    "Bank Name": "STEWARD BANK LIMITED",
    "Address": "LIVINGSTONE HOUSE, 79 LIVINGSTONE AVENUE",
    "City": "HARARE",
    "Branch": "",
    "Postcode": "",
    "Country": "Zimbabwe",
    "Connection": "Active"
  },
  {
    "countryCode": "SMFB",
    "bankCode": "ZW",
    "branchCode": "WHA",
    "SWIFT Code": "SMFBZWHA",
    "Bank Name": "SUCCESS MICROFINANCE BANK LIMITED",
    "Address": "14 STEPPES ROAD",
    "City": "HARARE",
    "Branch": "",
    "Postcode": "",
    "Country": "Zimbabwe",
    "Connection": "Active"
  },
  {
    "countryCode": "ZBCO",
    "bankCode": "ZW",
    "branchCode": "BYO",
    "SWIFT Code": "ZBCOZWHXBYO",
    "Bank Name": "ZB BANK LTD",
    "Address": "",
    "City": "BULAWAYO",
    "Branch": "",
    "Postcode": "",
    "Country": "Zimbabwe",
    "Connection": "Active"
  },
  {
    "countryCode": "ZBCO",
    "bankCode": "ZW",
    "branchCode": "WHX",
    "SWIFT Code": "ZBCOZWHX",
    "Bank Name": "ZB BANK LTD",
    "Address": "ZIMBANK HOUSE, 46 SPEKE AVENUE",
    "City": "HARARE",
    "Branch": "",
    "Postcode": "",
    "Country": "Zimbabwe",
    "Connection": "Active"
  },
  {
    "countryCode": "ZWMF",
    "bankCode": "ZW",
    "branchCode": "WHA",
    "SWIFT Code": "ZWMFZWHA",
    "Bank Name": "ZIMBABWE WOMEN'S MICROFINANCE BANK LIMITED",
    "Address": "TRUST TOWERS, 56-60 SAMORA MACHEL AVENUE",
    "City": "HARARE",
    "Branch": "",
    "Postcode": "",
    "Country": "Zimbabwe",
    "Connection": "Active"
  }
]
module.exports = zimbabwe
